### ISSUE TITLE
Mix voice with background music while recording

### ISSUE THREAD

**Issue by bensan61** [AudioKit/AudioKit#1008]
I have some interesting background music files to modulate original human voice.
My questions is - 
Can we use AudioKit to mix the recorded human voice with background music?
So the voice will be modulated and mixed with the background music.
What I am saying is this app, "https://itunes.apple.com/app/apple-store/id1250518569?mt=8"
Any hint or help will be very greatly appreciated for me.

**Comment by aure** [comment]
This app is doable in AudioKit.

However, this is not an appropriate place to ask this question.  Issues are for bug tracking.  Please use the forum instead: https://groups.google.com/forum/#!forum/audiokit
