### ISSUE TITLE
AKSamplePlayer - Memory Leak when loading new sounds

### ISSUE THREAD

**Issue by nigamshah** [AudioKit/AudioKit#1020]
Hi everyone,

I am pretty sure I've found a major leak in AKSamplePlayer. When using `AKSamplePlayer.loadSound(file:)` it is correctly replacing the sound to be played, but the old sound data is never getting deallocated. My project is using lots of AKSamplePlayers and constantly loading new sounds based on the user's actions, so the memory climbs up rapidly.

I have a test project that demonstrates this.
https://www.dropbox.com/s/ahbx2qml0lfis3l/TestAudioKit-AKSamplePlayer-memory-leak.zip?dl=0

There is 1 button - every time you you tap, it loads a new sound into the AKSamplePlayer and plays it once. If you look at the memory footprint, it will keep climbing and climbing every time you tap the button.

I am also using AKAudioPlayer in my app, and it does not leak when loading new sounds. However, it is not responsive enough for this specific use case. AKSampler doesn't seem to have the leak, but I'm struggling with that, because all I have is individual m4a files coming from a server.

Please let me know if there is a manual way to free up the resources. AKSamplePlayer seems like it was designed for exactly what I want to do, but I can't have this large of a memory leak. Thanks in advance!

Nigam Shah

**Comment by aure** [comment]
Thanks for finding this, I think it should be fixable.

**Comment by aure** [comment]
I think its no longer leaking memory and I've tested your example.  One thing that I added was a maximumSamples: length so that the buffer has space for any potential sounds you might add.  It does require some knowledge of the sounds before hand, but its a necessary compromise.

**Comment by nigamshah** [comment]
Thanks Aurelius, sorry to post on a closed issue, but I have a simple question - will this work if I merge the changes into `master` (I won't push)?
I tried to compile `develop` and had some issues at runtime, but I can successfully compile and run `master`. I don't really have the time to dive into my issues with `develop`, so I'd like to stick with `master` for now.

**Comment by aure** [comment]
Yeah, you should just be able to apply the changes to the master branch.  mind you there were a few more improvements after the commit referenced above so you'll want the newest version of the Sample Player stuff, from the Swift level down, basically everything in the folder.
