### ISSUE TITLE
Prevent self-oscillation in Moog Ladder Filter playground

### ISSUE THREAD

**Issue by markuswustenberg** [AudioKit/AudioKit#1022]
Hi all,

I'm playing around with the (great!) AudioKit playgrounds, and everything was fine and good until I played with the parameters in the Filters > Moog Ladder filter playground. I turned up the resonance too quickly and got a really high-pitched and high-volume sound so I had to rip off my headphones (before realizing that the mute button would be a better choice, of course). I realize this is totally my own fault, but would it perhaps be a good idea to make the playground safe by default, to protect future ears and/or speakers? Maybe in the form of parameter restriction or a limiter. I'm guessing the filter was self-oscillating, but I don't know AudioKit well enough to know for sure.

Thanks for reading!

**Comment by aure** [comment]
Yeah, its pretty hard to give full range of value access and be sure nobody has found a set of parameters that makes things bad.  Be careful.  But, I can at least update the Moog Ladder one reducing the resonance which is what I've done.

**Comment by markuswustenberg** [comment]
Thanks for the quick turnaround! So adding a limiter of sorts to playgrounds in general is not a good idea?
