### ISSUE TITLE
AudioKit pauses background audio when started.

### ISSUE THREAD

**Issue by warpling** [AudioKit/AudioKit#1025]
Tested on `/develop` on 8/30/17.

To reproduce take any AudioKit example and run it while background audio is playing.

I've confirmed the session category is `.ambient` and the option `.mixWithOthers` is being used so something else must be afoot… suggestions welcome!

**Comment by EssamSoft** [comment]
seem here 👍

**Comment by aure** [comment]
I don't know if there's anything that can do be done with this issue.

**Comment by warpling** [comment]
It's possible to fix. Based on AudioKit's default category, mixing, and routing settings it appears it should not be mixing and not pausing music when started, but it is. I'd like to explore this more when I can because it probably will surface something else that is not as it appears configuration wise and because my users are mentioning it.

**Comment by aure** [comment]
You know where to find me.

**Comment by aure** [comment]
I think one of the things I'd like to verify with issues like this is whether or not AudioKit is the culprit, or just AVAudioEngine. Does this happen with a simple AVAudioEngine project with those session categories? If so, then its more of an Apple bug. We'd still want whatever work around that is found to be integrated into AK. Really I have no idea where to look and I hate having issues that I can't act on.

**Comment by dave234** [comment]
Do you have a control that you're using?  If another background app uses
mixwithothers, it works.

**Comment by warpling** [comment]
What do you mean by "a control"?
Which Audio Kit sample app are you testing with? I'll try to use the same.

**Comment by dave234** [comment]
By control I meant two apps where you can produce the desired result.  So
app a is in the background playing, then app b starts playback in the
foreground, result is - a keeps playing.  Then swap out app b for an
AudioKit app and test.

**Comment by warpling** [comment]
Ah right! I'll work on this. When I first tested it I used a few AK based apps on the store and an AK sample app. I know when I used to use TAAE it wasn't an issue so I assume it's not AV unless it's a recent bug but it seems unlikely.
