### ISSUE TITLE
AKAmplitudeTracker init

### ISSUE THREAD

**Issue by Adam259532** [AudioKit/AudioKit#1029]
So I see I can set the half frequency for low pass filter and amplification threshold in the amplitude tracker.
I write the below code to filter noise from human voice when record by microphone.

let mic = AKMicrophone()
var ampBooster: AKBooster!
tracker = AKAmplitudeTracker.init(mic, halfPowerPoint: 1310.0, threshold: 0.05, thresholdCallback: { (true) in
//what to write to filtered input here???
        })
 ampBooster = AKBooster(tracker, gain: 1)
 AudioKit.output = ampBooster

But now I hear only noise. Would you help me?

**Comment by aure** [comment]
There's not really enough information to go on, but this is not a forum for general discussion, but for problem/issue reports.  For general support please go to: https://groups.google.com/forum/#!forum/audiokit
