### ISSUE TITLE
Crash when disconnect bluetooth

### ISSUE THREAD

**Issue by EssamSoft** [AudioKit/AudioKit#1030]
Hi 

I'm try to make app recored while background audio playing such Soundcloud or Spotify 
when record and disconnect bluetooth the app get crashed 

![screen shot 2017-09-04 at 12 41 57 am](https://user-images.githubusercontent.com/4315102/30006804-f1db122e-9109-11e7-9252-d165ff06b3e4.png)

**Comment by aure** [comment]
This is not information for a Github issue, perhaps you want to start a discussion here: https://groups.google.com/forum/#!forum/audiokit
