### ISSUE TITLE
A bug in AKSequencer?

### ISSUE THREAD

**Issue by larryseyer** [AudioKit/AudioKit#1032]
Aure,

I may have found a bug in AKSequencer.

Here it is:

https://www.dropbox.com/s/fbg5zm5kisy4e2e/AKSequencerIssue.zip?dl=0

The example Xcode Project does only 2 things....

Starts and Stops the sequencer (works fine)

Swaps out MIDI files that the sequencer loads  (does NOT work... sequencer will not start playing again without quitting the program)

L

**Comment by aure** [comment]
Thanks for posting this.  I probably don't have time personally to look at it until next week, but maybe someone else will have a look and help out.

**Comment by larryseyer** [comment]
I've done more investigating... it appears that ANY time AKSequencer is called more than once, it will simply stop working.

Even if it points to a different variable, when it is called a 2nd time, it bombs out.

For instance, the following can be called:

sequenceStick = AKSequencer(filename: thisNewPath.stickPath, engine: AudioKit.engine)

And it will work fine.

But the following WILL NOT WORK - everything is muted:

   sequenceStick = AKSequencer(filename: thisNewPath.stickPath, engine: AudioKit.engine)
   sequenceSnare = AKSequencer(filename: thisNewPath.snarePath, engine: AudioKit.engine)

So it has something to do with calling AKSequencer a 2nd time.

L


L

**Comment by aure** [comment]
Hey, I see from your syntax that you're using the Sequencer from the master branch.  That sequencer is a major pain and we've deprecated it, or rather just renamed it to AKMIDIPlayer.  Its not suitable for anything but the simplest of MIDI usages.  The internals are not under our control as it is basically just AVAudioSequencer, so I can't really fix it, I don't think. You're welcome to try to fix it, but I think it will be futile.

**Comment by larryseyer** [comment]
Ok.  Understood.  

I'll try the one in the developer branch.   Hopefully that one will work. 

Thanks!

L
