### ISSUE TITLE
bash build_frameworks.sh fails with this

### ISSUE THREAD

**Issue by larryseyer** [AudioKit/AudioKit#1035]
Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **

I'm using Swift 4 Beta latest version trying to compile audiokit-develop

Seems like this should just work when downloading fresh copies of both the source and Xcode.

L

**Comment by aure** [comment]
Which version of AudioKit are your trying this with?  Works for me on develop, which is the only Swift 4 compatible version.

**Comment by larryseyer** [comment]
I'm using the latest developer branch from github.

**Comment by larryseyer** [comment]
Watch this.

https://youtu.be/OW7Wfa0qsqQ

L

**Comment by aure** [comment]
Great video!  I can't be sure, but I think you probably have downloaded Xcode-beta but you still have Xcode 8.3. From the looks of it on the video, you're still having Xcode8 do the building for you. Try doing this before running build_frameworks.sh:

sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer/

assuming that is where you have your beta Xcode installed.

**Comment by larryseyer** [comment]
Thank you.  

That makes perfect sense.  

I'll try it again using your suggestion. 

L

**Comment by aure** [comment]
Reopen if that doesn't solve it.
