### ISSUE TITLE
Sharp sign in file path crashes AKAudioFile init

### ISSUE THREAD

**Issue by alexvolchek** [AudioKit/AudioKit#1036]
AKAudioFile init `file = try AKAudioFile(forReading: fileURL)` crashes if file path contains sharp sign ('#'). Like this `"/var/mobile/Containers/Data/Application/0981133F-E902-4294-90ED-56028A6F4994/Library/Instruments/piano/A#0.wav"`, change `A#0` to `A0` and it works

**Comment by aure** [comment]
So, yeah, that's an issue because in URLs the pound sign is probably truncating the URL because it usually used for placeholders within an HTML file. I'm guessing you'll have to use a filename instead of a URL?

**Comment by aure** [comment]
I believe the solution is to encode the hash in the URL with %23 as per https://stackoverflow.com/questions/4960513/using-a-hash-within-a-url-path
