### ISSUE TITLE
Issue with exporting/extracting from AKAudioPlayer audioFile

### ISSUE THREAD

**Issue by Zei33** [AudioKit/AudioKit#1044]
I just solved a problem that's been doing my head in for the last 22 work hours so I'd like to make the solution known to others in the off chance that it saves somebody a whole lot of time debugging.

When using the following code and its exportAsynchronously sister

`player.audioFile.extractAsynchronously(fromSample: 0, toSample: Int64(44100*player.playhead), baseDir: .temp, name: UUID().uuidString, completionHandler: exportComplete)`

I kept on catching this error

`Error Domain=NSURLErrorDomain Code=-3000 "(null)"`

or the program would straight up crash during different approaches.

Eventually I tried the following code and similar variants

`AKAudioFile(readFileName: player.audioFile.fileName).extractAsynchronously(fromSample: 0, toSample: Int64(44100*player.playhead), baseDir: .temp, name: UUID().uuidString, completionHandler: exportComplete)`

Still failed.

Finally, however, I found a solution.

`AKAudioFile(forReading: player.audioFile.avAsset.url).extractAsynchronously(fromSample: 0, toSample: Int64(44100*player.playhead), baseDir: .temp, name: UUID().uuidString, completionHandler: exportComplete)`

I'm not entirely sure if this is intended behaviour. I don't entirely understand why this works when the other things I tried didn't. I'm just glad it works. Hopefully this might help somebody googling around.

**Comment by aure** [comment]
Thanks for posting this fix.  People do coming looking in the issues when they are having problems so its a great place to post it. Maybe we'll make the interface to this sort of thing better in the future as well.
