### ISSUE TITLE
Lots of rawwaves are missing

### ISSUE THREAD

**Issue by tengyifei** [AudioKit/AudioKit#1046]
E.g. when downloading AudioKit [from GitHub](https://github.com/AudioKit/AudioKit/releases/download/v3.7.1/AudioKit.framework.zip) or installing from CocoaPod, in the `macOS/AudioKit.framework/Resources` directory, there are only a couple of `mand*.raw` files, whereas there are much more in https://github.com/AudioKit/AudioKit/tree/master/AudioKit/Common/Internals/STK/rawwaves.

This has caused instruments such as Rhodes Piano to not work due to missing rawwave files.

This is apparently caused by [Xcode project files not including the entirety of rawwaves](https://github.com/AudioKit/AudioKit/blob/master/AudioKit/macOS/AudioKit%20For%20macOS.xcodeproj/project.pbxproj#L257). Could you confirm this?

**Comment by aure** [comment]
I think all the ones currently in use by AudioKit are there:  https://github.com/AudioKit/AudioKit/blob/master/AudioKit/macOS/AudioKit%20For%20macOS.xcodeproj/project.pbxproj#L2320

And in the finder...
![screen shot 2017-09-14 at 10 59 34 pm](https://user-images.githubusercontent.com/13122/30468485-74f24832-99a0-11e7-8fad-b80699685800.png)

Perhaps it was fixed more recently than your version?

**Comment by tengyifei** [comment]
Hmmm. But if you download AudioKit 3.7.1 from https://github.com/AudioKit/AudioKit/releases/download/v3.7.1/AudioKit-macOS-3.7.1.zip it's different. Specifically, it's missing the `sinewave.raw` file which the Rhodes instrument depends on.

Only the iOS release has `sinewave.raw`.

**Comment by aure** [comment]
That's true. Must have been fixed more recently.  We'll be making a new release sometime next week.
