### ISSUE TITLE
Problem with inputDevices

### ISSUE THREAD

**Issue by dorjeozer** [AudioKit/AudioKit#1047]
Hey,

I've been wondering why I lose the connection to my microphone once in a while, but now when I started digging deeper I found a weird piece of code that causing AudioKit to crash. Lines 62 and 150 (in develop branch lines 65 and 153) in AudioKit.swift are unwrapping an optional with force and when it's nil it doesn't do much good. These lines look like this:

`if device.dataSources!.isEmpty {`

Apple's Documentation about these dataSources ([AVAudioSessionDataSourceDescription]?) is following:

> You obtain data source descriptions from the shared AVAudioSession object or the AVAudioSessionPortDescription objects corresponding to its input and output ports. Only built-in microphone ports on certain devices support the location, orientation, and polar pattern properties; if a port does not support these features, the value of its dataSources property is nil.

So to prevent crashed I'd suggest these lines to be replaced with:

`if device.dataSources == nil || device.datasouces!.isEmpty {`

or alternatively do the conditional checking other way around starting with the case when the dataSources have data:

`if device.datasouces?.isEmpty == false {`

**Comment by aure** [comment]
Good ideas, would you like to make a pull request? If not I'll get to it shortly.

**Comment by dorjeozer** [comment]
I can do it, no problem.
