### ISSUE TITLE
No sound output

### ISSUE THREAD

**Issue by mani9876** [AudioKit/AudioKit#1049]
Hello!

I try to use AudioKit to ouput a pure sine wave. https://github.com/AudioKit/AudioKit I've tried to set up a new project like on there homepage, and also tried there "Hello World" Example, included in the AudioKit Download.

Both builds fine, and the Hello World example displays the generated sine wave, correctly on the screen, but there is no sound playing, I can't hear anything. I've set the volume to max and tried with other apps, if they were playing audio fine, and they do. Are there any suggestions?

I am using Xcode 8.3.3 and as device an iPad Mini 2 with iOS 10.3.1

Thank you

**Comment by aure** [comment]
Does it work on the simulator?  Can you try on a different device? If its displaying the waveform, things are being generated so I am not sure why it wouldn't make sound as well.

**Comment by mani9876** [comment]
Hello,

I only have the IPad mini as test device. I tried the simulator and you are right, in the simulator everything works fine.

I've never had any problems with my IPad and writing Apps for it. I've also checked with other apps, if they can play sound, and they can. Have you any suggestions, what there could be wrong? Or is it an IPad Mini 2 problem?

**Comment by aure** [comment]
It could be that AudioKit is obeying your mute switch while the other apps do not.

**Comment by markjeschke** [comment]
Good call, @aure! I was also thinking that it was the hardware's mute button. Add this to your code before `AudioKit.start`:

```
AKSettings.playbackWhileMuted = true
```

Please let us know if that works!

**Comment by cyberdude** [comment]
Same here. I've been trying to get a simple click track with the AKSynthKick or Snare and no audio is coming back.   I went ahead and build AudioKit tag 3.7.1 and ran the Sequencer demo and to my surprise the melody works but the Snare nor Drum Kick doesn't now.

I'm getting `2017-09-17 16:27:40.073541+0200 SequencerDemo[16093:179547] [i-aa] 957: AUParameterSet 2 (1/8): err -10867
`

Btw, I'm using. Xcode 9.0  My code was working before.

**Comment by mani9876** [comment]
Hello,

thank you very much. You were absolutely right, it was the mute button. As my mute button is defective, and I don't want to here that system sounds it was always muted, but normal Apps like Youtube etc. played sound just like normal. 
"AKSettings.playbackWhileMuted = true" did the trick, thank you very much!

I know it's a little bit off topic, but do you know why there is a little delay, when I change the oscillator frequency? I display the Oscillator Frequency in a label, and there are sometimes 2 - 3 seconds in beetween the display changes, and I can hear the frequency change.

**Comment by markjeschke** [comment]
@mani9876,

Without seeing your code, perhaps the delayed UILabel update is happening, because the request is not occurring on the main thread? Check out this example:

```
    func updateText(_ input: String) {
        DispatchQueue.main.async(execute: {
            self.outputTextView.text = "\(input)\n\(self.outputTextView.text!)"
        })
    }
```

Source used in context: 

https://github.com/AudioKit/AudioKit/blob/master/Examples/iOS/MidiMonitor/MidiMonitor/ViewController.swift#L62

If you need further support, I recommend that you join and post questions to the AudioKit Google group:

https://groups.google.com/forum/#!forum/audiokit

That way, the rest of the AudioKit community can benefit and learn from your solutions. :)

**Comment by mani9876** [comment]
Thank you, I am going to open a Thread there, and close this, as the mean issue was solved :)!
