### ISSUE TITLE
XCode 9 - AudioKit 4 - Objective C

### ISSUE THREAD

**Issue by jldunk** [AudioKit/AudioKit#1054]
If I am missing something, I apologize, but I am seeing no visible interface for what used to work in the previous version of AudioKit.

AKAudioPlayer *player = [[AKAudioPlayer alloc] initWithFile...

There is no initWithFile now for the AKAudioPlayer object when using Objective C.  I am actually getting this error with several objects like AKTimePitch, AKReverb, etc.

**Comment by megastep** [comment]
Mmh, I wouldn't be surprised if we're missing a few `@objc` qualifiers in the Swift code. I noticed that for some other classes I was using.

**Comment by jldunk** [comment]
any ideas how to work around or do I need to wait for an AudioKit new version?

**Comment by megastep** [comment]
We'll likely need to make a new build, I think there's too many of these oversights. Hunting them all down might take some time though.

**Comment by aure** [comment]
You could use the AudioKit develop branch and include the .xcodeproj in your project instead of the framework.  Then, you could find the offensive classes, add the @objc and make a pull request with the changes. That would be amazingly helpful and get you on the right track the fastest.  I can help you through screensharing if you need any help getting set up.

**Comment by jldunk** [comment]
I would be more than happy to help.  Is there any way for the time being to use the previous version I was using which was AudioKit 3.7.1 with XCode 9?  I seem to remember the issue with this was around Swift 4.

**Comment by aure** [comment]
Not as far as I know. iOS development is like this, constantly being shoved around by toolset, device, and operating system changes. I can only offer some commiseration!

**Comment by jldunk** [comment]
I will start tonight with the develop branch and then do the pull request with my findings.  Thanks again for your help.

**Comment by jldunk** [comment]
I am closing this issue as I was able to compile my app last night using the develop branch xcode project adding @objc where needed.  I'll do a pull request this morning, but basically found that several effects needed @objc added for the init so you could instantiate the object in obj-c.

**Comment by aure** [comment]
@jldunk Are you close to making a pull request? We've got a few other bugs I'd like to address with a 4.0.1 release

**Comment by jldunk** [comment]
Just uploaded changes. 


Jason
