### ISSUE TITLE
AK4 - Could not find an ftable match for callback

### ISSUE THREAD

**Issue by justbane** [AudioKit/AudioKit#1056]
OK so just update my previously working app to swift4 as well as a bunch of other pods... including Audiokit (previously 3.7.1 now 4.0)

None of my code has changed - the app will build (command b) - but when I run the app in simulator it crashed hard on this line.

`AudioKit.start()`

with this error preceding the crash:
```
Could not find an ftable match for callback.
f returned an error.
```

anyone have an idea?

**Comment by aure** [comment]
I'd need a little more context. Can you share your project publicly or privately? Or do a screenshare to show me what you use that's causing this?

**Comment by justbane** [comment]
@aure I can share the repo with you via bit bucket. What is your identity on bitbucket? Or maybe send me your email?

**Comment by aure** [comment]
I'm able to reproduce your problem on iOS (for some reason its not happening on macOS) independent of your project, and I am working on it now.

**Comment by justbane** [comment]
Agreed. I pulled the update and am no longer seeing the issue - Thanks, Aure!
