### ISSUE TITLE
Error: player started when engine not running

### ISSUE THREAD

**Issue by szczepanwaclaw** [AudioKit/AudioKit#1064]
Hello,
first of all - great work with AudioKit, amazing piece of software.
After upgrading to XCode 9 & AK 4, I have an issue I cannot resolve and would like for your help.

My code is simple, here is how I start the engine in view controller 

```
mixer = AKMixer()
        
AudioKit.output = mixer
AudioKit.start()
```

Than on button click (many buttons, many sounds) I connect player to mixer and play it

```
let file = try! AKAudioFile(readFileName: fileName, baseDir: .resources)
let plr = try! AKAudioPlayer(file: file!)

plr?.connect(to: mixer)
plr?.play()
```

Problem occurs after random couple of button clicks (might be 5, might be 10), doesn't have to be quick & chaotic, it can be one by one.
App crashes and says

> *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'player started when engine not running'

I am in a dead end and can't find a reason why, engine is running just before plr.play().
One thing I noticed is that crash takes a while. I hit the button app freeze & crash outputs with 2-3 sec delay.

Any help much appreciated, cheers.

Sz

**Comment by dave234** [comment]
This is the bug found by ryanfrancesconi.  If a mixer has 0 input connections when AudioKit is started, you can't make any subsequent connections while it's running.  A workaround is to stop AudioKit prior to making connections to "empty mixers", then restarting AudioKit after the connection has been made.

**Comment by szczepanwaclaw** [comment]
Thanks for such a quick response. I will test in a bit but already I can say I can connect players to my mixer, it fails after couple connections (and .play() causes crash not .connect(to:)), not immediately. Although I need to test your feedback first, cheers.

**Comment by szczepanwaclaw** [comment]
@dave234, a workaround you suggested works but AudioKit.stop() causes all active players stop and I want them to continue fluently, is there another trick I can use?
I also tried to look for ryanfrancesconi bug but cannot find it in the archive here or Google groups, if you could share link maybe it would limit size of this thread.

Once again thanks for help, cheers.

**Comment by dave234** [comment]
I've been meaning to address this issue, I speculate that it's an internal optimization of the mixer to just disable itself completely if there aren't any connections.  One way to get around this is to just connect a throwaway generator like AVAudioUnitSampler to the mixer before starting the engine.  I haven't tested this so if you do try it, let us know if it works.

**Comment by szczepanwaclaw** [comment]
@dave234 thank you very much for your help & time. I think I have solution to my problem.

Apparently there is a limit of items (at least AKAudioPlayer) added to the mixer and to clear the capacity I have to disconnect players once they're done. Every time I connect & play new player I set completionHandler and in it I disconnect from mixer.

It works but still rapid creation of new players kills the app I limited number of active players to 7.

Again thanks for help and maybe this will save someones time.

**Comment by dave234** [comment]
So this is a known issue/bug, there is a workaround.  The mixer will automatically make more inputs available when the setOutput(to: mixer) function is used rather than the connect(to: mixer) syntax.  You can solve this by creating a dummy node, set it's output to the mixer, then remove it.  Then there will be another input ready to be connected to.

if let mixer = node.inputNode as? AVAudioMixerNode {
    if mixer.nextAvailableInputBus >= mixer.numberOfInputs {
        let dummy = AVAudioMixerNode()
        dummy.setOutput(to: node)
        dummy.disconnectOutput()
    }
}

Then make your connection using the regular syntax.

**Comment by szczepanwaclaw** [comment]
Thank you! I will test and confirm, cheers.

**Comment by dave234** [comment]
Also, you could just use setOutput, but it will clear any other output connections from that node.

**Comment by szczepanwaclaw** [comment]
To be honest I can't make it work, here is code
```
let dummy = AKNode()
dummy.setOutput(to: mixer)
dummy.disconnectOutput()
```
mixer is AKMixer. This code throws error

> *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: node != nil'

BTW I have acceptable version now working, solution described in earlier post.

**Comment by dave234** [comment]
I think AKNode is supposed to be an abstract class.  Try using AVAudioMixerNode instead.

**Comment by dave234** [comment]
@szczepanwaclaw I've made a PR addressing this issue, let us know if it fixes it.  It uses the dummy node technique described above.  Let us know if it's still broken.

https://github.com/AudioKit/AudioKit/pull/1068

**Comment by aure** [comment]
Reopen if necessary.

**Comment by szczepanwaclaw** [comment]
@dave234 I will for sure but know I am offline for a while, cheers.
