### ISSUE TITLE
"Stack is empty" error for Metronome + others in playgrounds (AudioKit 4.0.1 + Xcode 9)

### ISSUE THREAD

**Issue by johnellmore** [AudioKit/AudioKit#1066]
Hey all,

When I use the _Basics > Metronome_ playground in the AudioKit playgrounds, I get a `Stack is empty.` error in the console.

Steps to reproduce (using Xcode 9):
1. Download the AudioKit 4.0.1 playgrounds file from the [releases page](https://github.com/AudioKit/AudioKit/releases).
2. Open the Playground in Xcode and build.
3. Open the Basics > Metronome playground tab.
4. The `Stack is empty.` message appears in the console.

The playground loads with the metronome started by default. However, if I stop and restart the metronome using the button in the playground view, it plays properly and doesn't display any errors.

This same error message is also popping up with in some other playgrounds intermittently, and with different symptoms. I've seen it happen on _Basics > Stereo Panner_, _Synthesis > Clarinet_, _Synthesis > Mandolin_, etc.

Normally, I'd think a playground issue is almost not worth reporting. But I'm having the same error in my iOS app and I'm trying to troubleshoot that too 😄 .

Thanks! AudioKit's fantastic, by the way!

**Comment by aure** [comment]
A playground error is always worth reporting!  I'll fix this up.

**Comment by aure** [comment]
This should be fixed in develop. Let me know if there are any other issues you find. Thanks!
