### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by npahucki** [audiokit/AudioKit#107]
There is nothing mentioned about this in the documents, but I get the following linker errors if I don't manually include 

    pod 'TPCircularBuffer'

in the pod file. Is this expected? I was just going to ignore it, but adding use_frameworks! to the Podfile has made the issue come back despite the inclusion of the TPCircularBuffer library. 

This is on iOS 8.x using AudioKit 2.0. 

Undefined symbols for architecture i386:
  "_TPCircularBufferCleanup", referenced from:
      +[EZAudio freeCircularBuffer:] in EZAudio.o
  "_TPCircularBufferClear", referenced from:
      +[EZAudio freeCircularBuffer:] in EZAudio.o
  "_TPCircularBufferInit", referenced from:
      +[EZAudio circularBuffer:withSize:] in EZAudio.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by megastep** [comment]
`TPCircularBuffer.c` is definitely included in the AudioKit repository. Maybe for some reason it is not getting compiled because it's a C file and not an Objective-C module?

**Comment by aure** [comment]
I only recently changed the podspec to include .c files as well.  Perhaps this will get fixed if I push up a new version for pods to point to?

**Comment by npahucki** [comment]
If I point the pod to the git repo at commit 7ea3f5b2863fd82219392f5dbf8eeb683ca0a622 which contains your recent changes, that seems to fix the problem, so I would think that pushing the new podspec should fix it the issue.

**Comment by aure** [comment]
I've pushed a 2.0.1 podspec, hopefully that fixing things.  Closing for now.
