### ISSUE TITLE
AKTable not working

### ISSUE THREAD

**Issue by highestage** [AudioKit/AudioKit#1070]
I am trying to build an iOS app and want to use a custom AKTable implementation (using a wav file). But audiokit is neither reading any audio file format (I even tried MP3), nor is it accessing AKTable. Please help.

**Comment by aure** [comment]
I just tested AKTable with a wav file and it works so unless you can provide more information, I can't really help you.

**Comment by highestage** [comment]
Is it possible that I can upload screenshots of the issue after some time?

**Comment by aure** [comment]
If you like, or share a project, that would be best.

**Comment by highestage** [comment]
I'll do that. But could you just show me how you use a .wav file to init aktable and where you are placing the audio file in the project explorer. Thanks

**Comment by aure** [comment]
I'm not going to create an example from scratch, but this is a playground for tables:
http://audiokit.io/playgrounds/Basics/Tables/

If you have a project to load I can check it out.

**Comment by highestage** [comment]
<img width="1400" alt="error_1" src="https://user-images.githubusercontent.com/8946051/31009670-f5ca5798-a525-11e7-8b46-c7409513250a.png">

As you can see, I am following exactly what happens in the playground you mentioned. But still it gives me the error that AKTable is accessing a nil value

**Comment by aure** [comment]
ITs also printing the error in the do try catch block that drumKit.wav isn't being found in the resources folder. This isn't AudioKit related, its including files in Xcode so that they can be found by the code.  Is drumKit.wav in your project?  Does it have the appropriate target membership?

**Comment by highestage** [comment]
Yes. But I wanted to ask if you are facing the same issue in your Xcode. Also I am using Xcode 9.0

**Comment by aure** [comment]
No I am not.

**Comment by highestage** [comment]
I found the solution. It’s bit of a workaround. You need Xcode 8 and 9 both. So, in order to import the file, I opened the project in Xcode 8, copies the files, and then reopened the entire project in Xcode 9. So I think I am good. Thanks for the help

**Comment by dave234** [comment]
This makes me think that Aure was right about checking target membership. Xcode 8 would make a File a target when importing while Xcode 9 does not.  When a file is selected, in the details pane (on the right) you need to make sure the target box is checked.
