### ISSUE TITLE
AKAudioFile throwing "pointer being freed was not allocated" error

### ISSUE THREAD

**Issue by zishanj** [AudioKit/AudioKit#1073]
I am trying to play remote audio file through `AKAudioFile` like this:

        let mixloop = try? AKAudioFile(forReading: URL(string: "http://anyurl.com/anyfile.mp3")!)
        guard mixloop != nil else {
            print("can't play file")
            return
        }
        let player = try? AKAudioPlayer(file: mixloop!) {
            print("completion callback has been triggered!")
        }
        AudioKit.output = player
        AudioKit.start()

But it throws this error on `AKAudioFile` init and never play the file:

    ERROR:    AVAudioFile.mm:32: AVAudioFileImpl: error 2003334207
    AKAudioPlayer(42498,0x67d61c0) malloc: *** error for object 0x7864b710: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug

Any workaround to this? I am using latest `AudioKit 4.0.1`.

**Comment by hhanesand** [comment]
I believe `mixloop` and `player` will go out of scope if they are not saved in instance variables.

this was in the issue template that you deleted https://vimeo.com/audiokit/connecting-nodes-part-2

**Comment by zishanj** [comment]
Thanks, that error has gone. But now I receive this error when I play any MP3 URL:

```
2017-10-12 08:50:41.931215+0500 AKAudioPlayer[15941:3859240] 231: EXCEPTION (2003334207): "open audio file"
2017-10-12 08:50:41.933073+0500 AKAudioPlayer[15941:3859240] [avae] AVAEInternal.h:77:_AVAE_CheckNoErr: [AVAudioFile.mm:133:AVAudioFileImpl: (ExtAudioFileOpenURL((CFURLRef)fileURL, &_extAudioFile)): error 2003334207
```

**Comment by hhanesand** [comment]
Are you saving `mixloop` in an instance variable? Either that, or there is some issue with your file.
Check https://stackoverflow.com/a/34563535/4080860 for suggestions. Make sure the initializer for `AKAudioFile` you are using ends up calling the same init function as described by the person in SO answer.
If that does not fix, I'm all out of ideas.

BTW, you can look up the error codes on https://www.osstatus.com (doesn't give you any more info than what you have here, but its a useful tool)

**Comment by zishanj** [comment]
Still no luck... I am in doubt that `AKAudioPlayer` does not support playing external file from URL. I have tried with native `AVFoundation` library and it playing well.

**Comment by aure** [comment]
Yeah, actually now that I look at this, external URLs are not allowed, going to close this.
