### ISSUE TITLE
Is it possible to capture system audio output?

### ISSUE THREAD

**Issue by laaksomavrick** [AudioKit/AudioKit#1078]
Hi, sorry if this is the wrong place to ask this.

I'm trying to make a music visualizer as a hobby project as a Mac OS app. I can't find any information online however about how to capture system audio output for doing FFT on. Does AudioKit have this functionality?

Thank you!

**Comment by aure** [comment]
We don't have that capability. Maybe you could use something like Rogue Amoeba's Loopback to get the system audio back into AudioKIt: https://rogueamoeba.com/loopback/
