### ISSUE TITLE
Possible crash because of this default initialization in `AKNodeOutputPlot`

### ISSUE THREAD

**Issue by andresinaka** [AudioKit/AudioKit#1079]
https://github.com/AudioKit/AudioKit/blob/b66633834c8b83206d5afe7801c611eac7c3c365/AudioKit/Common/User%20Interface/AKNodeOutputPlot.swift#L56

Hi guys, I've been using the library for a while, today I updated to the v4.0.1 and my app was crashing... started debugging and find out is because of this line. I added in my view controller the following in the viewDidLoad and everything started to work as expected:

```
if let output = AudioKit.output {
    output.avAudioNode.removeTap(onBus: 0)
}
```
I think is because AudioKit.output kept that tap installed and was never removed, after the view controller with the `AKNodeOutputPlot` was gone I was getting in my log tons of: "setupNode Unable to create strong reference to self". If I tried to push again a view using `AKNodeOutputPlot` the app just crashed... (maybe because it was trying to install again the tap in AudioKit.output?)

(BTW, I'm not a heavy user of the library so I'm not 100% sure of what I'm talking about but I noticed this and I think it's a bug. If you think I'm right let me know and I'll send a PR!)

**Comment by aure** [comment]
I think you should make a PR, seems like a good problem to fix.  Thanks in advance!
