### ISSUE TITLE
Duplicate tambourines

### ISSUE THREAD

**Issue by megastep** [audiokit/AudioKit#108]
I noticed that while trying to put together all of the AudioKit classes in a static library, but there is some apparent code duplication with AudioKitDemo which becomes a problem.

Specifically, the demo app has its own `Tambourine` instrument which differs slightly from the one in the AudioKit library itself. I think it would make sense to get rid of the definition inside of the demo and just reuse the one from the library, or alternatively rename this instrument to something that doesn't conflict if this is supposed to be a useful example. This way it will also solve the linking issues I'm having when we can't selectively select which of the files are included in the static library.

**Comment by aure** [comment]
I'll make the demo use the default tambourine.  Will commit in about 10 minutes.

**Comment by aure** [comment]
Removed the duplicate Tambourine.h/m

**Comment by megastep** [comment]
Not to nitpick here, but I see it's still in the Swift version. :smile: 

It's helping though, I'm greatly simplifying these demo projects with the static library and going through them one by one.

**Comment by aure** [comment]
I didn't rush to change the Swift since it's a Tambourine.swift file and couldn't be a conflict right?  I'll change it now just to not have them fall out of sync too much.

**Comment by megastep** [comment]
I haven't tried it because it's a pain to merge back the changes you make to the Xcode project in my branch later, but I'm pretty sure there can be linking clashes between Swift and Objective-C classes. But yeah better all of these demos to be consistent.

**Comment by aure** [comment]
I just committed them.  The only thing that is inconsistent with the AudioKitDemo projects are the use of plots.  Only the iOS is really using them correctly.

**Comment by megastep** [comment]
Yeah, we can tackle that later. Right now I'm just trying to get the static lib version to compile and run properly.
