### ISSUE TITLE
AK3DPanner broken in v4.0

### ISSUE THREAD

**Issue by pruthvikar** [AudioKit/AudioKit#1083]
This [commit](https://github.com/AudioKit/AudioKit/commit/b923a0dd5e44a879779adc246a4dcd91cd23bbad) seems to break the functionality of an AKAudioPlayer used with an AK3DPanner.

```
let player = try! AKAudioPlayer(file: audioFile, looping: true)
let panner = AK3DPanner(player)
AudioKit.output = panner
AudioKit.start()
player.play()
```

This causes a crash saying that player was started in a disconnected state. This code works in previous versions of AudioKit

**Comment by dave234** [comment]
Good catch.  Thanks for finding the commit, fixing now.
