### ISSUE TITLE
Synchronizing recording with playback

### ISSUE THREAD

**Issue by hhanesand** [AudioKit/AudioKit#1086]
I have an app in which users can layer tracks on top of each other. We play the already recorded layers through headphones while recording new layers, and we need to make sure that all of this happens in sync.
I've already made the needed tweaks to ensure that all playback starts at the same time, but I'm struggling to get the recording to sync up with the playback while using `AKNodeRecorder`.

A possible solution I could think of :
- Provide API in `AKNodeRecorder` similar to that in `AKAudioPlayer` that allows you to specify a start time in the form of an `AVAudioTime`. This would be specified on a call to `record`, as an optional argument.
- The tap block that writes to disk would then discard any incoming buffers that come before the specified `AVAudioTime`.
- By passing in the same start time as the players use, this would ensure that the recording is started more or less at the same time as playback.

I will happily take a stab at implementing this, but I wanted to get the go ahead from someone to see if this was the "right" way to accomplish this.

P. S. Could I use `AKClipRecorder` + `AKClipPlayer` to achieve this? I'm not at all familiar with their api or implementation. (there doesn't seem to be much documentation about this?)

**Comment by dave234** [comment]
AKClipRecorder and AKClipPlayer are great for what your doing.  AKClipRecorder writes to a temp directory, then calls back with the temp URL when complete (or stopped).  Timing is ample accurate.

http://audiokit.io/docs/Classes/AKClipPlayer.html#/s:8AudioKit12AKClipPlayerC8setClipsySayAA8FileClip_pG5clips_tKF

**Comment by hhanesand** [comment]
Doesn't that still leave the question of how to synchronize the start of playback with the start of recording?

**Comment by hhanesand** [comment]
Ah, I see. Thanks so much!
