### ISSUE TITLE
Error in file normalization?

### ISSUE THREAD

**Issue by fictorial** [AudioKit/AudioKit#1087]
https://github.com/AudioKit/AudioKit/blob/9ae8641551bc5f7b4c9b4c887aa327155fac83b5/AudioKit/Common/Internals/Audio%20File/AKAudioFile.swift#L294

**Comment by fictorial** [comment]
OK maybe that was too terse.  Aren't audio file samples root-power or field quantities since they are amplitudes?  If so, the conversions between decibels and gain would be: gain = 10^(dB/20) and db = 20 x log10(gain/ref).

I've only gotten into audio processing since a few months ago so if I'm missing something, forgive me (and tell me what I'm missing).  Thanks!

**Comment by aure** [comment]
I think you're right, can you make a pull request with the change?
