### ISSUE TITLE
Not sensitive enough on 6s

### ISSUE THREAD

**Issue by timroesner** [AudioKit/AudioKit#1092]
I have an issue where the microphone on my 6s will only give me an output if I am right in front of the microphone. I'd like to change the sensitivity so that it will read a frequency even from a couple of feet distance. 

This is how I initialize the AKMicrophone:

```swift
AKSettings.audioInputEnabled = true
        mic = AKMicrophone()
        tracker = AKFrequencyTracker.init(mic)
        silence = AKBooster(tracker, gain: 0)
```

I'm guessing it has something to do with the booster, but changing the gain value did not yield any result.

**Comment by aure** [comment]
This is not really an issue, we prefer support to go to StackOverflow.  If you post the question there, I have a response ready.  Thanks!

**Comment by timroesner** [comment]
https://stackoverflow.com/questions/46840362/audiokit-issue-mic-not-sensitive-enough
