### ISSUE TITLE
Using AKBandPassButterworthFilter in an Objective-C project

### ISSUE THREAD

**Issue by karapas** [AudioKit/AudioKit#1093]
Hi all,

I am trying to use AudioKit v4 in an Objective-C project. While things like AKOscillator and AKMixer work like a charm, I am not able to use AKBandPassButterworthFilter (or any other filter really) because none of their "init" methods are exposed to the Objective-C environment.

Is this intended, i.e., AKBandPassButterworthFilter cannot work with Objective-C, or is there a way that this can be corrected?

I am quite new to the whole iOS development business so I might be missing something obvious... Would greatly appreciate your help!

**Comment by megastep** [comment]
Looks like we're probably just missing some `@objc` specifiers in these classes. It seems these need to be put in explicitly with Swift 4 and we've been slowly but surely uncovering more classes where that's not the case...

**Comment by aure** [comment]
I believe this issue has been addressed by this commit https://github.com/AudioKit/AudioKit/commit/8aa4625b4dffdf755e8c223705666aad66a9372c

**Comment by karapas** [comment]
Great, thanks a lot!
