### ISSUE TITLE
No sound from Analog Synth X until Filter deactivated

### ISSUE THREAD

**Issue by eposien** [AudioKit/AudioKit#1094]
No sound at all from Analog Synth X (downloaded from app store), on ipad pro 12.9, 2017 (ios 11).

All my other synths works. Is this a known issue?

Best regards
Tomas

**Comment by aure** [comment]
Probably @swiftcodex and I need to make an iOS11 release of that synth. New synths are on their way too.

**Comment by swiftcodex** [comment]
We might as well look at it this weekend...

**Comment by aure** [comment]
Can you see if turning off the filter makes sound work?

**Comment by eposien** [comment]
Indeed. Turning of “Filter” does make the sound (and everything else as far as I can see) work ...!

**Comment by aure** [comment]
This is fixed in the latest version of AK, uploading a new Analog Synth X to the app store now.
