### ISSUE TITLE
Documentation implies I can change the playback position in AKAudioPlayer - but doesnt seem to..

### ISSUE THREAD

**Issue by roboldham** [AudioKit/AudioKit#1098]
Am just trying to find out how to instantly change the current playback position when using the AKAudioPlayer - my use case is simply playing a WAV and controlling its playback position using a UISlider

Changing player.startTime whilst the player is already playing seems to change the playback position in terms of the reported .playhead position (ie changes the UISlider position) but the actual audio being played does not change position - does not seem to scan to the updated sample position.

AKAudioPlayer documentation indicates that it should?: .startTime "sets the start time, If it is playing, player will restart playing from the start time each time end time is set" : [shown here](http://audiokit.io/docs/Classes/AKAudioPlayer.html#/c:@M@AudioKit@objc(cs)AKAudioPlayer(py)startTime)

Am I missing something or is this a bug?

**Comment by aure** [comment]
Thanks for pointing this out, I will look into it (sorry for the delay in responding).

**Comment by ryanfrancesconi** [comment]
Hi, there is now a new player that will replace AKAudioPlayer, please give it a try and send any feedback you might have. It will solve this issue. You can also see it in action in the AudioUnitManager macOS example. Thanks!

https://github.com/AudioKit/AudioKit/blob/develop/AudioKit/Common/Nodes/Playback/Player/AKPlayer.swift
