### ISSUE TITLE
how to process Variable bitrate music ?

### ISSUE THREAD

**Issue by CaichaoGitHub** [AudioKit/AudioKit#1106]
as i know ,the audio unit is not designed for VBR audio , so how to process VBR audio using AmazingAudio,should i use convert audio unit ? 

https://developer.apple.com/library/content/documentation/MusicAudio/Conceptual/AudioUnitProgrammingGuide/TheAudioUnit/TheAudioUnit.html

**Comment by aure** [comment]
Hi, this is more of a discussion than an issue just for AudioKit. Can you perhaps ask the question on StackOverflow? It will get a lot more attention there.
