### ISSUE TITLE
Xcode 9.1

### ISSUE THREAD

**Issue by StevenArmandLee** [AudioKit/AudioKit#1109]
"Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2"

I suspect that you are still using Xcode 9.0 to build the frameworks which causes this issue.

**Comment by megastep** [comment]
Nope, version 4.0.3 was built with Xcode 9.1. You probably have an old cached version of the framework somewhere being picked up.

**Comment by StevenArmandLee** [comment]
@megastep I've deleted my derive data and it's still the same. Have googled and it says 9.1 is version 4.0.2 for example from [https://github.com/realm/realm-cocoa/issues/5442](url) also has the same issue.

**Comment by megastep** [comment]
I compiled and uploaded the binaries myself so I think I know. ;) I am specifically talking about the latest AudioKit version 4.0.3, which was compiled in Xcode 9.1 hence with Swift 4.0.2. I can see how it can be confusing with these similar version numbers for different things though.

**Comment by StevenArmandLee** [comment]
I see, my apologise, I thought you were referring to swift version.

this case can be closed.
