### ISSUE TITLE
AVAudioUnitSampler (AKSampler) headphones route change problem

### ISSUE THREAD

**Issue by Zeken** [AudioKit/AudioKit#1110]
Hello,

I have isolated a problem by which AKSamplers (more general, AVAudioUnitSamplers) seem to, somehow, duplicate their audio output every time that the headphones are connected or disconnected, at least on iPhone.

The following class already reproduces the problem (here I use directly AVAudioUnitSampler, but AKSampler shows the same behaviour):

```
class MidiController: AKNode, AKMIDIListener {

    var midi = AKMIDI()
    var samplerUnit = AVAudioUnitSampler()

    override public init() {
        super.init()
        midi.openInput()
        midi.addListener(self)
        avAudioNode = samplerUnit
        AudioKit.output = self
        AudioKit.start()
    }
    func receivedMIDINoteOn(noteNumber: MIDINoteNumber, velocity: MIDIVelocity, channel: MIDIChannel) {
        if velocity > 0 {
            play(noteNumber: noteNumber, velocity: 127, channel: channel)
        } else {
            stop(noteNumber: noteNumber, channel: channel)
        }
    }
    func receivedMIDINoteOff(noteNumber: MIDINoteNumber, velocity: MIDIVelocity, channel: MIDIChannel) {
        stop(noteNumber: noteNumber, channel: channel)
    }
    func play(noteNumber: MIDINoteNumber, velocity: MIDIVelocity, channel: MIDIChannel) {
        samplerUnit.startNote(noteNumber, withVelocity: velocity, onChannel: channel)
    }

    func stop(noteNumber: MIDINoteNumber, channel: MIDIChannel) {
        samplerUnit.stopNote(noteNumber, onChannel: channel)
    }
}
```

Since the sampler is not initialised, it will generate a sinewave tone, but every time that the headphones are connected/disconnected the amplitude of the tone will be higher. If it were initialised with, let's say, a piano sound, the first time that headphones are connected or disconnected, piano+sine wave will be heard, after would be piano+sine*2, etc.

This problem might have something to do with 2) of #1099 , although the resulting sound posted there is quite strange by itself, and I thought it was going to be useful to have the minimal reproduction scenario for this isolated case anyway.

I also tried to manually handle the route changes and engine restart (instead of letting AudioKit do it) without success, but I don't have much experience with iOS audio development so I'm pretty much in the dark trying to debug this.

I have a forked [branch](https://github.com/Zeken/AudioKit/tree/bug-samplerHeadphones/Examples/iOS/HelloWorld) with a modified "HelloWorld" example that shows the problem.

Let me know if I can be of any further help!

**Comment by aure** [comment]
@Zeken Thanks for the in depth analysis and sample project. Aside from the AV sampler's built in handling of certain file types, i think we'd almost be better off with our own code than relying on Apple.

**Comment by aure** [comment]
@Zeken You might be well served to ask this question on StackOverflow as well since it is not necessarily an AudioKit-only problem.

**Comment by Zeken** [comment]
@aure Small update: I didn't observe the problem on iPad (both iOS v9.3 and v11.1), so it might be an iPhone-only problem (I tested shortly on iPhone under iOS 10, and I just got no sound output after headphones connect/disconnect)

**Comment by Zeken** [comment]
@aure Found a workaround! If the internal `AVAudioUnitSampler` gets re-initialised _a bit later_ than the route change (caused by connecting/disconnecting the headphones), everything works good:

```
class MidiController: NSObject, AKMIDIListener {

    var sampler = AKSampler()

    // ...

    override public init() {
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(handleRouteChange),
            name: .AVAudioSessionRouteChange,
            object: nil)

        initSampler()
        AudioKit.output = sampler
        // ...
    }
    func initSampler() {
        do {
            try sampler.loadWav("piano")
        } // ...
    }
    @objc func handleRouteChange(notification: NSNotification) {
        let deadlineTime = DispatchTime.now() + .milliseconds(100)
        DispatchQueue.main.asyncAfter(deadline: deadlineTime) {
            self.initSampler()
        }
    }
    // ....
}
```

So it looks indeed a problem related with the iOS audio engine rather than AudioKit. Still spooky, as I have no clue as to why do we need to re-initialise the samplers some time after the route change, and only in iPhone.... also, it doesn't solve the problem when someone (for some strange reason) would like to use the samplers uninitialised, but this workaround seem to work for the normal use-case of having a sampler loaded with some audio files.

I updated [my branch](https://github.com/Zeken/AudioKit/tree/bug-samplerHeadphones/Examples/iOS/HelloWorld) as a code reference.

Tested on iPhone, both iOS 10 and 11.

**Comment by aure** [comment]
That's some excellent sleuth work!

**Comment by trevor-sonic** [comment]
hi @Zeken thanks for the analyse I had the same issue, not resolved, at least i see better  why it was happening. I look for a solution, if a have time I'll dig in it

**Comment by mgill404** [comment]
This sounds related to the issue presented in this thread. The hardware speaker for some recent devices only support a sampling rate of 48 kHz. Unplugging the headphones on these devices will cause the operating sample rate to change.

https://forums.developer.apple.com/thread/22197
