### ISSUE TITLE
Plans on supporting linux

### ISSUE THREAD

**Issue by caiofbpa** [AudioKit/AudioKit#1112]
Are there any plans on supporting linux as a platform?

Although apple/swift-corelibs-foundation is still under development and a bit far from completion, it's being used by some Server Side Swift frameworks, so it's usable to some extent.

It would be really nice to be able to use AudioKit on the server to run DSP on Swift.

**Comment by aure** [comment]
There are no plans currently, but we'll watch as Swift on Linux evolves.

**Comment by guysoft** [comment]
Hey, it looks like there was quite a lot of progress. There is a docker container you can bring up and have a working environment (https://www.swift.org/install/linux/)

Is there some kind of example project to build? I can take a look if it works.
