### ISSUE TITLE
AKSamplePlayer only play few seconds

### ISSUE THREAD

**Issue by whisper-bye** [AudioKit/AudioKit#1113]
I have a wav file, duration 30s, but the AKSamplePlayer only play few seconds and then it loopback

this is my code

```swift
let audioFile = try AKAudioFile(forReading: musicURL)
let samplePlayer = AKSamplePlayer(file: audioFile)
samplePlayer.loopEnabled = true

AudioKit.output = samplePlayer
AudioKit.start()

samplePlayer.play()
```

**Comment by aure** [comment]
This hasn't been my experience. Unless you can provide more details like the operating system you're using, which version of AudioKit you're using, and hopefully even a sample project with the audio file in question, there's not a lot I can do to help you.  Feel free to reopen this issue with more information.

**Comment by whisper-bye** [comment]
AudioKit 4.0.3
iPhone 7, iOS 11

[gentle.wav.zip](https://github.com/AudioKit/AudioKit/files/1459890/gentle.wav.zip)

**Comment by aure** [comment]
That wav file is 8KHz. I resaved it as 44.1KHz and it plays appropriately.  I suppose there could be a problem with the way we convert wavs to the appropriate format.

**Comment by eljeff** [comment]
We fixed this in the develop branch - appreciate any feedback if it still gives you problems.
