### ISSUE TITLE
Save track using AKOfflineRenderNode with AKSequencers as an input instead of AKAudioPlayer

### ISSUE THREAD

**Issue by martinzp** [AudioKit/AudioKit#1115]
Hi, I have been trying to save a mix using AKOfflineRenderNode with AKSequencer instances, but the output is not as expected. I posted a question on StackOverflow (https://stackoverflow.com/questions/47076703/saved-file-using-audiokit-akofflinerendernode-not-right) and got a great reply from @aure offering to update the library for iOS 11+.

I wanted to know if that's possible. If there is something I can help with please let me know. I honestly don't know much about music processing and the internal code of the library, but I'm willing to get my hands dirty if there is any way I can help.

Thanks so much!

**Comment by aure** [comment]
@dave234 Recently added the more modern offline rendering. Are you on the develop branch?

**Comment by martinzp** [comment]
@aure I'm not, but I will try it out and post the result here. Thanks!

**Comment by martinzp** [comment]
Hi, I wanted to try this out but I am having trouble installing the library from the develop branch.

I am using CocoaPods and I'm using this in my Podfile:

pod 'AudioKit', :git => 'https://github.com/AudioKit/AudioKit.git', :branch => 'develop'

I am getting a this error: No such module 'AudioKit'

Any thoughts or tips? I'm using Xcode 9.1

Thanks

**Comment by megastep** [comment]
@martinzp You can't just switch the branch for the pod, unfortunately. The AK pod basically just downloads pre-compiled binaries we release, and we don't put those up for the develop branch. Instead you'd have to manually compile the library yourself from a checkout of the source code, using the provided `Frameworks/build_frameworks.sh` script.

**Comment by martinzp** [comment]
Thanks @megastep for your answer. After posting here I checkout out the develop branch and built the frameworks.

Doing that the project built successfully, but just after starting the app crashed with this error:

"dyld: Library not loaded: @rpath/AudioKit.framework/AudioKit
  Referenced from: /Users/martin/Library/Developer/CoreSimulator/Devices/70D4EF90-C3D5-41CB-ADED-609BB9C9A09F/data/Containers/Bundle/Application/3EDA9F3C-7138-43B0-8530-B3AB5CF2F870/memphis.app/memphis
  Reason: image not found"

Any thoughts on why this is happening? Am I doing something wrong?

**Comment by megastep** [comment]
Did you actually follow the instructions here? Sounds like the framework is not included correctly.

https://github.com/AudioKit/AudioKit/blob/master/Frameworks/README.md

**Comment by juangz** [comment]
Hello, I'm working with Martin and we couldn't make the new method to work properly.

We do get the exported file, but the result is not the expected one (the song has some weird speed effects, plus there are some noises on it). I'm attaching a test project in which we initialize a sequencer playing a midi + a WAV file, and the exported file (export.m4a). 

In the "save" method you'll find the following line: `self.sequencer!.setRate(60)`
If you don't set it, or you set it to a small int, the result it's not the same as if it were just playing the sequencer. Can you verify you get the same issue? 

Please, let us know if there's a way in which we can help you. 

Thanks

https://www.dropbox.com/s/rhgqgah46k4lh43/testRenderToFile.zip?dl=0

**Comment by aure** [comment]
Given that this issue is 4 months old and AudioKit has changed a lot since then, I would like to close it. If you would still like help, I'd suggest StackOverflow or maybe a fresh issue with updated specifics.
