### ISSUE TITLE
Using AudioKit node outputs in AudioKit operations

### ISSUE THREAD

**Issue by tengyifei** [AudioKit/AudioKit#1116]
Currently, there are lots of parallels between AudioKit nodes and individual operations. Operations come with the benefit of flexible connections, but still feel a bit isolated from the rest of AudioKit. Will it be possible to support external audio in the "operation world" e.g. taking the output from an `AKSampler`, and passing it through an operation-based lowpass filter whose cutoff frequency is driven by a sine wave generator?

**Comment by aure** [comment]
That's doable, just connecting up a operation based effect to a sampler. Not sure how this classifies as an issue though, so I'll close it.
