### ISSUE TITLE
AKSamplePlayer looping behaviour after update to 4.0.3

### ISSUE THREAD

**Issue by levitatingpineapple** [AudioKit/AudioKit#1121]
Hi Aurelius, I am experiencing change in how AKSamplePlayer handles looping after updating to xCode 9.1 and AudioKit 4.3.

1. AKSamplePlayer seems to "forget / reset" the loop start and end points after first loop. If I extract the issue to audioKit playgrounds:

```
import AudioKitPlaygrounds
import AudioKit

let file = try AKAudioFile(readFileName: "alphabet.mp3")
let samplePlayer = AKSamplePlayer(file: file)
AudioKit.output = samplePlayer
AudioKit.start()

samplePlayer.loopEnabled = true
samplePlayer.play(from: Sample(44100), length: Sample(44100))

import PlaygroundSupport
PlaygroundPage.current.needsIndefiniteExecution = true
```

Output of this is "b" on the first loop and whole alphabet on consecutive ones.

2. If loop end point is set on a separate line for the first loop it seems that the calculation is done twice. 

```
import AudioKitPlaygrounds
import AudioKit

let file = try AKAudioFile(readFileName: "alphabet.mp3")
let samplePlayer = AKSamplePlayer(file: file)
AudioKit.output = samplePlayer
AudioKit.start()

samplePlayer.loopEnabled = true
samplePlayer.loopEndPoint = Sample(Int(13 * 44100))
samplePlayer.play()

import PlaygroundSupport
PlaygroundPage.current.needsIndefiniteExecution = true
```
This playground plays first 6.5 letters on a first loop and first 13 letters on consecutive ones.

**Comment by aure** [comment]
Will hopefully have a chance to look at this on Wednesday.

**Comment by levitatingpineapple** [comment]
Thanks for all the efforts! The current workaround (kind of) that I am using is to initialise AKSamplePlayer with a "dummy sample" which is just 5 minutes of silence and then use the second approach. This makes the first loop really short and almost inaudible.

**Comment by eljeff** [comment]
In the develop branch, we changed the way AKSamplePlayer works, so this should be fixed now. Would appreciate any feedback.
Thanks
