### ISSUE TITLE
Xcode 9.1 Swift 4 Compatibility Issues

### ISSUE THREAD

**Issue by AppleEducate** [AudioKit/AudioKit#1123]
Xcode project will not compile in the latest version of Xcode.

**Comment by aure** [comment]
It verifiably compiles using Travis. What is your configuration that it is not compiling in? Too little information provided to call this an issue, maybe bring the question to STackOverflow.

**Comment by AppleEducate** [comment]
I am using the latest version of Xcode, and downloaded the project from Github. After importing the latest iOS AudioKit framework binary it displays the errors and keeps it from building.

**Comment by aure** [comment]
"the errors" are?

**Comment by AppleEducate** [comment]
Use of unresolved identifier:
'AKPropertySlider'

Rody Davis - Content Creator
Rodydavis.com - Rody.davis.jr@gmail.com

**Comment by megastep** [comment]
You need to import the AudioKitUI framework for this class.

**Comment by AppleEducate** [comment]
I was doing that too. Not sure why it’s not working. Ill try a few more things

Rody Davis - Content Creator
Rodydavis.com - Rody.davis.jr@gmail.com

**Comment by AppleEducate** [comment]
<img width="1059" alt="screen shot 2017-11-18 at 10 41 33 am" src="https://user-images.githubusercontent.com/31253215/32982112-2f6a2a84-cc4d-11e7-9b9e-3bef9c51bbcf.png">

Error Persists even while having both frameworks

**Comment by aure** [comment]
I wouldn't be surprised if this project builds if you ignore these errors in the editor. I think you need to reference the framework directory the same way that is done here by Eric:

https://stackoverflow.com/questions/47273149/referenced-audiokit-framework-is-not-recognized-by-xcode 

He composed this after we did a screenshare and he chronicled the solution brilliantly.
