### ISSUE TITLE
Callback instruments can't be renamed or assigned to proper MIDI client

### ISSUE THREAD

**Issue by teroparvinen** [AudioKit/AudioKit#1126]
There's a multitude of issues with the MIDI classes creating multiple instances of `MIDIClientRef`, not allowing initialisation without calling `enableMIDI` that accesses privately declared methods and so on, but I'll just pick one concrete example here.

If I want to create a callback instrument and assign it to a client reference I got through `AKMIDI().client`, a duplicate endpoint is created if I call `enableMIDI` on it. This is because `AKMIDIInstrument.enableMIDI` is called from `AKMIDIInstrument.init` and it contains a call to `MIDIDestinationCreateWithBlock` whereas there is no corresponding `MIDIEndpointDispose`.

I'm using an app called "MIDI Wrench" to check the fact that there are actually two virtual outputs reported to other apps. The code to duplicate this would be along the lines of:

```
let midiHandler = AKMIDI()
let callbackInstrument = AKCallbackInstrument()
callbackInstrument.enableMIDI(midiHandler.client, name: "Some other name")
```

Trying to work around this is especially painful because you have to override `enableMIDI` to stop the madness and replicating its functionality is redundant because `AKMIDIInstrument.enableMIDI` uses `handle` and `handleMIDI`, which are both private and can't be used from a derived class so all three have to be copied as is to the derived class.

**Comment by aure** [comment]
Thanks for the in-depth description of the issue. We'll definitely have a look, but also I want to encourage you to make pull requests with any changes you feel would help.

**Comment by teroparvinen** [comment]
I will see what I can do, but the problem is that to solve this, some overall changes to the MIDI classes would need to be done, and I'm not super confident in my CoreMIDI knowledge. For example, I think all references to `AKMIDI()` should be prohibited in all instrument classes (and probably other supporting classes like samplers etc., haven't dug that deep yet) because there should only ever be one instance of `MIDIClientRef` per app.

**Comment by aure** [comment]
AKMIDI is a singleton though, why is there more than on MIDIClientRef being instantiated?

**Comment by teroparvinen** [comment]
It's not a singleton though. Maybe if this was the idea, it all makes a bit more sense. Easy to test using:

```
print(AKMIDI().client)
print(AKMIDI().client)
```

From my initial look into this, maybe simply removing `enableMIDI` from all constructors (as probably was the intention) might remedy this, but would definitely not be directly downward compatible. My workaround looks like this currently:

```
class CallbackInstrument: AKCallbackInstrument {

	var sanitized = false
	
	init(handler: AKMIDI, name: String) {
		super.init()

		sanitized = true
		enableMIDI(handler.client, name: name)
	}
	
	override func enableMIDI(_ midiClient: MIDIClientRef, name: String) {
		if sanitized {
			super.enableMIDI(midiClient, name: name)
		}
	}

}
```

**Comment by aure** [comment]
Gotcha, well, I think think this could be resolved by making it a singleton perhaps.

**Comment by aure** [comment]
@teroparvinen I'm not sure if this circumvents the problem, but I've converted all occurrences of AKMIDI() on the develop branch to use an AudioKit.midi singleton. I'd be curious how that works for you.

**Comment by teroparvinen** [comment]
@aure I think the biggest concern was to override `enableMIDI` as I described above, because the stock version creates an end point with a default name and does not release it if called again with a custom name. Since you will need to do this, it typically takes care of the singleton issue at the same time (did for me at least). So the fix would obviously be to remove all `enableMIDI` calls from the default initializers and leave it to the user or to provide an `init` that takes the name as a parameter (what I did).

Also, if everything but virtual ports were private by default (as described in #1127), the singleton fix would most likely be enough for the typical user for now.

**Comment by aure** [comment]
@teroparvinen If you want to make a pull request, that would be great, but barring that would you be willing to do a screenshare with me while I make the changes?

**Comment by aure** [comment]
@teroparvinen Hi Tero, any progress towards a pull request on this or is it a dead issue?

**Comment by eljeff** [comment]
Again - these are great bugs you found. Fixing your other issue actually fixed most of these at the same time, so this should be good now.
