### ISSUE TITLE
Controlling a sampler with a sequencer requires MIDI that is exposed to other apps

### ISSUE THREAD

**Issue by teroparvinen** [AudioKit/AudioKit#1127]
All Audiokit MIDI endpoints expose the interfaces to outside apps. When connecting sequencers to samplers inside an application, this requires a MIDI endpoint, currently on the side of instruments and samplers. They are all visible in other apps' virtual MIDI lists, which is not very good, and can also in worst cases cause havoc with your app.

1) Instrument endpoints should probably be marked private by default, and this option should be available for other APIs as well. (https://developer.apple.com/documentation/coremidi/kmidipropertyprivate)

2) This property should probably be (optionally) respected by the virtual port lists Audiokit gives. There's apparently also a bug that should be considered (see https://developer.audiob.us/doc/_working-_with-_m_i_d_i.html: "Unfortunately there is currently a bug in iOS making these ports visible from time to time. To prevent your app's Core MIDI sources and destinations list from showing tons of Audiobus MIDI ports, please check if a port is private before displaying it to the user.")

3) Other properties could also be available for modification through the Audiokit APIs, listed here: https://developer.apple.com/documentation/coremidi/midi_services/global_constants

4) It's possible to do this control without MIDI. It seems like a pain, which is exactly the reason why Audiokit might look to help. Is there a reason why this is not supported? Does the dev team have opinions on how this should work? See more here: http://www.rockhoppertech.com/blog/multi-timbral-avaudiounitmidiinstrument/

**Comment by aure** [comment]
Thanks for the thoughtful and thorough issue post.  I can't look at this until later in the week due to holidays but hopefully someone else will.

**Comment by eljeff** [comment]
Awesome find. I've just submitted a pull-request that should fix this. Thank you!
