### ISSUE TITLE
Can't normalize audio file

### ISSUE THREAD

**Issue by rsimenok** [AudioKit/AudioKit#1130]
Hello i'm trying to normalize file after record. Using "Recorder" example, after record stopped and file exported I'm executing:
`let norm = try player.audioFile.normalized(newMaxLevel: -4.0);`

but getting `WARNING AKAudioFile: cannot normalize a silent file` and empty audio file.

I have checked just recordered `audioFile.maxLevel` and it was `1.17549e-38`, minimum float. Don't you know why? Record is loud enough. Thank you!

**Comment by aure** [comment]
Could I get an example project to look at?

**Comment by rsimenok** [comment]
[Example](https://drive.google.com/open?id=1YZ2KfL4uK9bCU1oeZrcYTFSipnoW3iHU)

- Run project.
- Press "Record", record some voice, then "Stop"
- See the logs

In code:
Look at lines 131-134

Thank you!

**Comment by rsimenok** [comment]
UPD: Guy from stackoverfrow answered to me right now:

> Rather than use the internal audio file of the player, make a new instance like so:
> ```
> if let file = try? AKAudioFile(forReading: url) {
>     if let normalizedFile = try? file.normalized(newMaxLevel: -4) {
>         Swift.print("Normalized file sucess: \(normalizedFile.maxLevel)")
>     }
> }
> ```
> I can add a normalize func to the AKAudioPlayer so that it's available for playback. Essentially, the player just uses the AKAudioFile for initialization, and all subsequent operations happen in a buffer.

as `url` I've used `self.player.audioFile.url`

It's working! But new file `maxLevel` not as I expect. For example if I execute `file.normalized()`, means set `maxLevel` to 0, i got this:

Example 1:
BEFORE: DB: -2.38453
AFTER: DB: -1.19227

Example 2:
BEFORE: DB: -1.30329
AFTER: DB: -0.651646

Is it ok? :)

**Comment by ryanfrancesconi** [comment]
No, it's not ok. We need to fix it!

**Comment by aure** [comment]
Can you share the code that prints out the "BEFORE DB:" and "AFTER DB:" output that you quote?

**Comment by ryanfrancesconi** [comment]
I think he's just printing maxLevel

**Comment by aure** [comment]
but maxlevel is not in dB so I am just a little suspicious.

**Comment by rsimenok** [comment]
@aure so you want to say that in `normalize` function i should set `newMaxLevel` in `db` but `maxLevel` is not in `db`?)

**Comment by ryanfrancesconi** [comment]
no, he's asking for your dB calculation i think from maxLevel

**Comment by ryanfrancesconi** [comment]
actually, is the AKAudioFile.maxLevel dB incorrect? Shouldn't it be: 

return 20 * log10(maxLev)

**Comment by aure** [comment]
This is the new preferred way to do normalization: https://github.com/AudioKit/AudioKit/pull/1306
