### ISSUE TITLE
No sound when AKCostelloReverb is bypassed

### ISSUE THREAD

**Issue by Selesao** [AudioKit/AudioKit#1132]
In code like this:
```
let mic = AKMicrophone()
let costelloReverb = AKCostelloReverb(mic)
AudioKit.output = costelloReverb
```
calling `costelloReverb.bypass()` causes all sound to stop instead of bypassing AKCostelloReverb node.

**Comment by ryanfrancesconi** [comment]
I checked the AudioUnit version of this and the bypass actually emits a weird tone like it is locked in a short loop.

**Comment by dave234** [comment]
Bypass isn't implemented in the AUAudioUnitOverrides.  I think we are supposed to memset the buffer to 0 if bypassed.  Otherwise, whatever was in the buffer before being bypassed might get processed every render, leading to the weird short loop tone.

**Comment by ryanfrancesconi** [comment]
bypass works in general, so the costello is an exception not the norm... would be good to fix it

**Comment by dave234** [comment]
Bypass works in general is a bit of an overstatement.  It just starts/stops the kernel.  If we were to really bypass, it should be done in the AUAudioUnitOverrides, bypassing the kernel.  It would also subsequently solve the problem.

**Comment by aure** [comment]
I am going to close this issue because its fixed, but we can continue the conversation here with Dave's insight that there might be a more general way to implement bypass.  This should be looked at once I implement @jandyman rearchitecting after the ramping works for me again.

**Comment by aure** [comment]
@Selesao Thanks very much for finding this btw, it was actually affecting two other effects.

**Comment by ryanfrancesconi** [comment]
oh ok. thanks @dave234 ! I meant it works as in ... I press bypass and the effect is bypassed. Generally. Glad to hear the underlying fix is happening.
