### ISSUE TITLE
Completionhandler executed immediately after play() in AKAudioPlayer

### ISSUE THREAD

**Issue by abw2912** [AudioKit/AudioKit#1134]
Problem while using audiokit ios.

Completionhandler immediately executed after play() called in AKAudioPlayer. Help me please ??

Using Xcode 9.2 beta and audiokit 4.0.4

Thanks,
Amit

**Comment by aure** [comment]
Hey Amit, I remember this being an issue on Apple's end a while ago but then they fixed it, so let me have another look and test it on a non beta Xcode. Is there a program or playground that demonstrates the problem?  That always speeds up addressing the issue.

**Comment by abw2912** [comment]
Hey !! Actually i am developing voice changer app with audiokit. Everything working normal pause(), play(),stop(). But when voice is playing then if i called stop and play then after play is called then suddenly it triggers completion handler.   Can you give me your email or mail me on abw2912@gmail.com. I will send you code if you wanna to take a look. Do you think it is happening because i am using xcode beta ??

**Comment by abw2912** [comment]
Hey @aure ..thanks for your help. I solved it with some minor changes in code. If we call stop() and play() instantly then we could have problem. But if we call play() after some it. It will automatically solves the issue. I'm not sure why it happened. But now my issue is solved. Thanks again :) :+1:

**Comment by aure** [comment]
Cool, there are some big changes ahead for audio playback so I am going to close this issue.
