### ISSUE TITLE
Can't restart AKAudioPlayer

### ISSUE THREAD

**Issue by meech-ward** [AudioKit/AudioKit#1139]
## Problem

I want to be able to have an `AKAudioPlayer` restart playing from the beginning while it's already playing. So the current playback would stop and it would start over from the beginning.

Ideally, I would love to be able to set the playhead of the player to any time that I want, while the player is playing. But for now, I just need to restart the file from the beginning.

## What I've Tried

According to the docs, I should be able to just reset the `startTime` or `endTime` of the player to restart the player, but this does not work:

```swift
/// sets the start time, If it is playing, player will
/// restart playing from the start time each time end time is set
@objc dynamic open var startTime: Double
```

I think that the following code should work, but it just stops the audio from playing:

```swift
player.stop()
player.start()
```

Also, just running `player.start()` while the player is playing causes the player to just stop.

## What Works

For some reason, telling the player to stop then start again after some time has passed is the only thing that has worked for me.

```swift
player.stop()
DispatchQueue.main.asyncAfter(deadline: .now() + 0.01, execute: {
  player.start()
});
```

I don't know why this works, and I'm afraid that it won't work in some situations; but for now, this is working the way I need it to.

**Comment by aure** [comment]
This is a nice writeup, we're currently rearchitecting the audio player so hopefully these kinds of issues will go away completely.

**Comment by aure** [comment]
I'm assigning @ryanfrancesconi on this issue just because he has written a new AudioKIt player, and I think he has / should have addressed this type of stuff already.

**Comment by ryanfrancesconi** [comment]
Yes this issue is now fixed in the upcoming AKPlayer. Stay tuned.

**Comment by ryanfrancesconi** [comment]
Hi, Was wondering if you'd like to give the new player a try. It's a little different in terms of setup but will be self-explanatory, it's in the development branch, or you can see here:

https://github.com/AudioKit/AudioKit/blob/develop/AudioKit/Common/Nodes/Playback/Player/AKPlayer.swift

**Comment by meech-ward** [comment]
It works as expected now, thanks.

```swift
player.stop()
player.play()
```

This stops the file and starts playing from the beginning.
