### ISSUE TITLE
Using AKMicrophoneTracker at the same time as a normal AudioKit chain doesn't work on physical iOS devices

### ISSUE THREAD

**Issue by johnellmore** [AudioKit/AudioKit#1142]
This is related to #1118, which is now locked to collaborators so I can't comment on it.

It appears that using `AKMicrophoneTracker` at the same time as the normal AudioKit signal flow causes the tracker to report both frequency and amplitude as `0`. The following code, adapted from [this answer on StackOverflow](https://stackoverflow.com/a/47585563/5651536), works in the iOS simulator (iPhone 7 Plus, iOS 11.1) but not on a physical device (iPhone 7 Plus, iOS 11.1).

```swift
import UIKit
import AudioKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

var window: UIWindow?
let tracker = AKMicrophoneTracker()
let dummyMixer = AKMixer() // NEW

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    // Override point for customization after application launch.

    // start the tracker and show frequency information
    tracker.start()
    Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true, block: { _ in
        print(self.tracker.frequency) // prints 0.0 on physical device
        print(self.tracker.amplitude) // prints 0.0 on physical device
    })
    AudioKit.output = dummyMixer // NEW
    AudioKit.start() // NEW

    return true
}
```

Removing the lines marked as `NEW` makes the frequency and amplitude print correctly. It appears that introducing a separate AudioKit signal path breaks `AKMicrophoneTracker`.

I'm using AudioKit 4.0.3, and I've got the appropriate entry in my `Info.plist` for requesting microphone permission.

Related StackOverflow threads that I've opened:
* [https://stackoverflow.com/questions/47300457/audiokit-can-i-disable-an-akmicrophone-without-calling-audiokit-stop](https://stackoverflow.com/questions/47300457/audiokit-can-i-disable-an-akmicrophone-without-calling-audiokit-stop)
* [https://stackoverflow.com/questions/47401897/why-doesnt-audiokits-akmicrophonetracker-work-on-a-physical-ios-device](https://stackoverflow.com/questions/47401897/why-doesnt-audiokits-akmicrophonetracker-work-on-a-physical-ios-device)

**Comment by aure** [comment]
I don't think I've ever got a better composed issue report. :)

**Comment by johnellmore** [comment]
Haha--it's in my best interest to be thorough! 😄

**Comment by warpling** [comment]
Hey @johnellmore, I run this sort of flow all the time. (I think my use was the impetus for the odd `AKMicrophoneTracker` too—thank you Aure 😇). I'm not sure if your code example is a smaller example you made or reflects fully what you were actually trying but did you try configuring `AKSettings` at all?
```
AKSettings.audioInputEnabled = true
```
Also fwiw I usually call `AKMicrophoneTracker.start()` before I call `AudioKit.start()` itself.

**Comment by aure** [comment]
I'm going to call this issue closed for now but if you need to reopen it or make a new issue or make a pull request, any correspondence with you is welcomed!
