### ISSUE TITLE
AKOscillator: No sound 

### ISSUE THREAD

**Issue by MrTristis** [AudioKit/AudioKit#1145]
Hi! 

So first off, big fan of AudioKit, however I have been banging my head against the wall trying to get it to work properly in a project. I can run the HelloWorld example just fine, however whenever I try to run Audiokit I get the following error: 

AKOscillator.swift:init(waveform:frequency:amplitude:detuningOffset:detuningMultiplier:):145:Parameter Tree Failed
AKOscillator.swift:init(waveform:frequency:amplitude:detuningOffset:detuningMultiplier:):145:Parameter Tree Failed
2017-12-06 04:23:50.239526-0500 BembeTEST[10576:254291] [avae] AVAEInternal.h:69:_AVAE_Check: required condition is false: [AVAudioEngine.mm:348:AttachNode: (node != nil)]
2017-12-06 04:23:50.247356-0500 BembeTEST[10576:254291] Failed to set (contentViewController) user defined inspected property on (NSWindow): required condition is false: node != nil

// end of error 

Literally just trying to run one oscillator, however despite my best edits the Parameter Tree Failed problem persists. 

Here is my sample code in question: 

import AudioKit

import Cocoa

class Conductor {
 let osc = AKOscillator()
    let osc2 = AKOscillator()
    
    init() {
        osc.frequency = 880.0
        osc.amplitude = 0.5
        osc.start()
        osc2.frequency = 440.0
        osc2.amplitude = 0.5
        osc2.start()
        let mixer = AKMixer(osc, osc2)
        AudioKit.output = mixer
        AudioKit.start()
    }
}

class ViewController: NSViewController {

   
   // var oscillator = AKOscillator()
 
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
      //  AudioEngine.init()
       
       Conductor.init()
    }

    override var representedObject: Any? {
        didSet {
        // Update the view, if already loaded.
        }
    }

}

Any help would be most appreciated, as I'm trying to utilize AudioKit in a final project.

**Comment by dave234** [comment]
I had this problem and it ruined an entire day.  The fix was to [delete derived data](https://stackoverflow.com/questions/38016143/how-to-delete-derived-data-in-xcode-8) and restart my Mac.  I wish I were joking about the restart.  I think there’s some cache that this ham fisted approach clears.

**Comment by aure** [comment]
@MrTristis Please reopen the issue with a comment if Dave's fix did not work for you.

**Comment by MrTristis** [comment]
Unfortunately Dave's fix did not do the trick, even after deleting the relevant folder for the project in the derived data folder and restarting my mac. Here's the error message 


AKOscillator.swift:init(waveform:frequency:amplitude:detuningOffset:detuningMultiplier:):145:Parameter Tree Failed
AKOscillator.swift:init(waveform:frequency:amplitude:detuningOffset:detuningMultiplier:):145:Parameter Tree Failed
2017-12-08 19:09:36.068283-0500 BembeTEST[818:18450] [avae] AVAEInternal.h:69:_AVAE_Check: required condition is false: [AVAudioEngine.mm:348:AttachNode: (node != nil)]
2017-12-08 19:09:36.118578-0500 BembeTEST[818:18450] Failed to set (contentViewController) user defined inspected property on (NSWindow): required condition is false: node != nil

**Comment by dave234** [comment]
Maybe move osc.start() down after AudioKit.Start()?

**Comment by SolidusMortis** [comment]
Hmm tried that dave234, but still getting the same error message. I'm going to repost my code and the subsequent error message, any ideas would be most appreciated as I'm getting a bit desperate:

//CODE: 

import AudioKit

import Cocoa

class Conductor {

  //  var mixer = AKMixer(osc, osc2)
    
    init() {
        
        let osc = AKOscillator()
        let osc2 =  AKOscillator()
        
        osc.frequency = 880.0
        osc.amplitude = 0.5
        
        osc2.frequency = 440.0
        osc2.amplitude = 0.5
        
        let mixer = AKMixer(osc, osc2)
        
        AudioKit.output = mixer
        AudioKit.start()
       
        
        osc2.play()
        sleep(2)
    
        }
    }


class ViewController: NSViewController {

   
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    
        // Do any additional setup after loading the view.

        var engine =  Conductor.init()
        
       // engine.osc2.play()
        
  //   var engine = Conductor.init()
     // engine.osc.play()
    //            osc2.play()
        
               // sleep(3)
        
    }

    override var representedObject: Any? {
        didSet {
        // Update the view, if already loaded.
        }
    }


}

// End of code

//ERROR OUTPUT: 
2017-12-09 21:28:28.144972-0500 BembeTEST[1073:75836] Month 13 is out of bounds
AKOscillator.swift:init(waveform:frequency:amplitude:detuningOffset:detuningMultiplier:):145:Parameter Tree Failed
AKOscillator.swift:init(waveform:frequency:amplitude:detuningOffset:detuningMultiplier:):145:Parameter Tree Failed
2017-12-09 21:28:36.157373-0500 BembeTEST[1073:75836] [avae] AVAEInternal.h:69:_AVAE_Check: required condition is false: [AVAudioEngine.mm:348:AttachNode: (node != nil)]
2017-12-09 21:28:36.359521-0500 BembeTEST[1073:75836] Failed to set (contentViewController) user defined inspected property on (NSWindow): required condition is false: node != nil

**Comment by omarperacha** [comment]
seems this hasn't actually been solved yet? I'm having the same issue, can confirm Dave's fix didn't solve it. I've had the problem on two separate machines, a laptop and a desktop. Not just with AKOscillator but a few other oscillator/generator objects too like AKWhiteNoise.
