### ISSUE TITLE
Swift 4 AND overriden "abs" functions

### ISSUE THREAD

**Issue by ingconti** [AudioKit/AudioKit#1152]
I have added AudioKit frameworks in a previously compiling code and added "import AudioKit".

now I got:
.... ViewController.swift:21:8: Binary operator '<' cannot be applied to operands of type 'AKOperation' and 'Double' 

So i replicated in brand-new iOS project:

if I write:

import UIKit
import AudioKit
func foo(){
	let a: Float = 10
	let b: Float = 20
	let c = abs(a+b)
	if c < 10.0{
	}
}
 I got the error. I noted that "abs" is colored as User-defined function.

to fix It I must use:

import UIKit
import AudioKit

func foo(){
	let a: Float = 10
	let b: Float = 20
	let c : **Float** = abs(a+b)
	if c < 10.0{
	}
}
 

so avoiding Swift inference will use native method "abs()", that is now colored as swift built-in type/functions/methods.

![screen shot 2017-12-09 at 7 00 35 pm](https://user-images.githubusercontent.com/4048423/33798129-aec2ff32-dd13-11e7-8dfc-8a6ac729579c.png)

**Comment by aure** [comment]
Clever work around!

**Comment by ingconti** [comment]
:)

I think other people will have it.

**Comment by aure** [comment]
I've made a documentation page for this sort of thing, hopefully it will grow over time and be more useful than having this stuff in the issues list, so I'll close this issue in favor:

https://github.com/AudioKit/AudioKit/blob/develop/Documentation/TipsAndTricks.md
