### ISSUE TITLE
Use one instance of AKSequencer to load MIDI-Files after another

### ISSUE THREAD

**Issue by mahal** [AudioKit/AudioKit#1155]
Steps to reproduce:
• Use one AKSequencer
• load a midi-file into the sequencer
• let it play
• load another midi-file into the sequencer
• let it play

Expected Result:
• Sequencer nicely layers each new midi-file on top of existing
• or stops first file and starts new file (as loadMIDIFile calls initTracks and clears existing)
• and some documentation in AKSequencer how it's supposed to be

Actual Result:
• AKSequencer logs deinit and sometimes then it crashes

Testcode (add another midi-file into the playground called "Octave.mid"):
```
//: ## Sequencer
//:
import AudioKitPlaygrounds
import AudioKit

//: Create some samplers, load different sounds, and connect it to a mixer and the output
var piano = AKMIDISampler()
try piano.loadWav("Samples/FM Piano")
var mixer = AKMixer(piano)
AudioKit.output = mixer

//: Create the sequencer after AudioKit's output has been set
//: Load in a midi file, and set the sequencer to the main audiokit engine
var sequencer = AKSequencer(filename: "4tracks")

//: Do some basic setup to make the sequence loop correctly
sequencer.setLength(AKDuration(beats: 4))
sequencer.enableLooping()
sequencer.setGlobalMIDIOutput(piano.midiIn)

AudioKit.start()
sequencer.play()

//: Set up a basic UI for setting outputs of tracks
import AudioKitUI

class LiveView: AKLiveViewController {

    override func viewDidLoad() {

        addTitle("Sequencer")

        let buttonNextMidi = AKButton(title:"new midifile") { _ in
            sequencer.stop()
            sequencer.loadMIDIFile("Octave")
            sequencer.setLength(AKDuration(beats: 4))
            sequencer.enableLooping()
            sequencer.play()

        }
        addView(buttonNextMidi)
        let buttonStop = AKButton(title:"stop") { _ in 
            sequencer.stop()
        }
        addView(buttonStop)
    }
}

import PlaygroundSupport
PlaygroundPage.current.needsIndefiniteExecution = true
PlaygroundPage.current.liveView = LiveView()

```

**Comment by aure** [comment]
We'll take a look at this this week, thanks for your patience.

**Comment by crashingbooth** [comment]
I've written some code that will add tracks from a new MIDI file onto the existing sequencer (i.e., Sequencer nicely layers each new midi-file on top of existing). It seems to work and seems like a useful thing to be able to do.
But I'm not at all sure that it is the expected default behaviour of loadMIDIFile.
On the other hand, maybe it is reasonable to expect that a client app should make a new AKSequencer if they want to use an entirely different MIDI file, since the two files might have different numbers of tracks etc.
