### ISSUE TITLE
Sysex > 256 bytes, unhandled exception

### ISSUE THREAD

**Issue by analoguwings** [AudioKit/AudioKit#1163]
Hi,

I am trying to build a (MacOS) app that sends patch and bank data to vintage synths via sysex. The banks are 4kb. 

I was getting a runtime error doing this with AKMIDI.sendEvent in my own app, so I tried the sysex send function in the MIDI Utility example, with the same result.

Through trial end error, it looks like the crash happens with > 256 bytes of sysex. From looking at the source, I get the feeling larger sysex commands are supposed to be broken up into MIDIPackets, though I'm uncertain how to do this.

I have two requests:

- Can MIDIEvent throw an exception when it has > 256 bytes of sysex?

- Can we get an example of how to send > 256 byte sysex, maybe in the MIDI Utility project?

Thanks!

**Comment by aure** [comment]
Sorry it has taken us a while to address this issue.  Hopefully this week.

**Comment by josevazquez** [comment]
I ran against this very same problem in my own app. I have a patch working under v4.0.4. I'll open a PR as soon as I can, but I am currently having trouble compiling against `develop` (see issue https://github.com/AudioKit/AudioKit/issues/1254)

**Comment by josevazquez** [comment]
I went ahead and opened the PR https://github.com/AudioKit/AudioKit/pull/1255 with the potential fix. I did not throw an exception when the data is too large (>65536 bytes) I just post an error to AKLog. I'm new to this project so I'm not sure how such situations should be handled.
