### ISSUE TITLE
Documentation regarding saving processed audio files

### ISSUE THREAD

**Issue by abw2912** [AudioKit/AudioKit#1164]
Stackoverflow has questions regarding saving processed audio file. But none of the answers is upto the mark.

How to save processed audio files using audiokit ?  After merging two audios how can i save them using audiokit ?

Is there any example project ??

Thanks in advance.

**Comment by EssamSoft** [comment]
https://github.com/AudioKit/AudioKit/blob/9ae8641551bc5f7b4c9b4c887aa327155fac83b5/Examples/iOS/SongProcessor/SongProcessor/SongExporter.swift
