### ISSUE TITLE
Document AU work

### ISSUE THREAD

**Issue by jandyman** [AudioKit/AudioKit#1167]
Create class diagrams and other documentation for work done on AU and DSP base classes

**Comment by aure** [comment]
Does your work on https://github.com/AudioKit/AudioKit/blob/develop/Documentation/AudioUnitCreation.md make this issue closed? If not, maybe it could be made more specific. I'm not sure its doing much good here as an issue, so I'll close it, but feel free to reopen it if it really was helpful to have it here.
