### ISSUE TITLE
File size of AudioKit binary

### ISSUE THREAD

**Issue by ruipaulo** [AudioKit/AudioKit#1173]
Hello AudioKit Team, 

first of all, let me thank you for the great software you have built! It is very useful for us!

We have a problem with the library and think that it might be also relevant to other users. We are using AudioKit "only" to capture the microphone input into a Stream. That works nicely. 

Unfortunately, it enlarges the file size of our app a lot (from 8Mb to ~80). We are currently thinking of migrating away from AudioKit because of this. I know that AudioKit is super powerful and therefore its large file size. So my question is, do you have any suggestions or ideas how to create a reduced size binary with only the functionality used?

I did not post this on StackOverflow because I think it would be a good "feature" for many users that want to use only a small portion of AudioKit.

**Comment by aure** [comment]
Yeah, you can somewhat easily extract the parts you don't need and rebuild AudioKit to your liking. I say somewhat because there's nothing difficult about it, but its not automated and you have to go systematically. If you'd like to do a screenshare, I could probably at least get you started.

**Comment by aure** [comment]
Closing until further information.
