### ISSUE TITLE
how is it possible to apply the AKAmplitudeTracker and AKFrequencyTracker for analyzing the audio stream

### ISSUE THREAD

**Issue by skylifewww** [AudioKit/AudioKit#1179]
I congratulate the AudioKit team on the upcoming holidays and wish you all the best! I am a musician (bass) and I am developing for IOS. Experimenting now with your product. There is a question: how is it possible to apply the AKAmplitudeTracker and AKFrequencyTracker for analyzing the audio stream from Apple Music. Thank you!

**Comment by aure** [comment]
No, this is not possible.  Apple protects their streams and we don't have access to them.

**Comment by skylifewww** [comment]
Greetings to you Aurelius! Thanks for the answer. I assumed that this would be so). And if intercept a signal coming from AVPlayer to the speaker of the device and send it to AKMicrophone? Make a "bridge" between them.



02 января 2018, 01:07:49, от Aurelius Prochazka <notifications@github.com>: 


No, this is not possible. Apple protects their streams and we don't have access to them.

**Comment by aure** [comment]
I suppose everything is possible somehow, but I certainly don't know how to do it.

**Comment by skylifewww** [comment]
I'll try, maybe it will)





02 января 2018, 21:56:29, от Aurelius Prochazka <notifications@github.com>: 


I suppose everything is possible somehow, but I certainly don't know how to do it.
