### ISSUE TITLE
Defined arguments for AKMusicTrack.clearRange() do not match with implementation

### ISSUE THREAD

**Issue by derekleerock** [AudioKit/AudioKit#1182]
First of all - thank you for AudioKit and all of the great work you've done with it! I previously implemented some low-level audio in Obj-C and it's been great to use AudioKit on new projects to simplify these complexities. 

I've been experimenting with AudioKit using the AKSequencer with the goal of being able to modify the length of a looping sequence (both adding to it and removing from it in real time). As a result, in trying to use the AKMusicTrack.clearRange() method to remove MIDI notes from a track I've noticed what I believe to be a discrepancy. I'd like to kindly ask for your confirmation and if this is the case I'd be happy to send a PR with an adjustment based on your feedback. 

The clearRange() method currently has the following definition:

    /// Clear some events from the track
    ///
    /// - Parameters:
    ///   - start:    Start of the range to clear, in beats
    ///   - duration: Duration of the range to clear, in beats
    ///
    open func clearRange(start: AKDuration, duration: AKDuration) {

This is directly calling "MusicTrackClear(track, start.beats, duration.beats)":

https://github.com/AudioKit/AudioKit/blob/f99e45103f42b02f995df7271264828d9d3e1dc1/AudioKit/Common/MIDI/Sequencer/AKMusicTrack.swift#L366

However, "MusicTrackClear" expects both a start time as a music time stamp as well as an end time as a music time stamp:

```
/*!
	@function	MusicTrackClear
	@abstract	Removes all events within the specified range
	@discussion	All time ranges are [starttime < endtime]
	@param		inTrack		the track
	@param		inStartTime	the start time for the range of events
	@param		inEndTime	the end time up to which will form the range of the events to clear
*/
@available(iOS 5.0, *)
public func MusicTrackClear(_ inTrack: MusicTrack, _ inStartTime: MusicTimeStamp, _ inEndTime: MusicTimeStamp) -> OSStatus
```

Therefore, with the current implementation, passing in a start AKDuration of, for example, 4 (for beat # 4), and a duration of 4 (to clear out one 4/4 measure of time), this actually passes in a start time and end time of 4 for both, effectively not clearing out any events (and also generating an "Invalid beat range or track is empty" error). 

It's my assumption that this is likely not the desired functionality, therefore I can see two approaches for improving this:
1. Keep the method declaration for clearRange() as it is indicating the start time and duration - but modify the clearRange() method implementation to calculate the end time to pass into the MusicTrackClear() method. 
1. Change the method declaration for clearRange() to instead take the start time and end time and keep the implementation the same, passing these values to the MusicTrackClear() method as it is currently. 

Thanks for your time and consideration! Best, Derek

**Comment by aure** [comment]
Great analysis Derek.  As it is currently broken, I'd love for you to make a PR with the solution you find most useful, and if the API has to change that is okay.

**Comment by derekleerock** [comment]
Thanks @aure! Happy New Year! =) 

I created PR #1185 today and included the details of the fix in there. Please take a look when you have a chance and let me know what you think. 👍
