### ISSUE TITLE
Playgrounds not working with Xcode 9.2

### ISSUE THREAD

**Issue by AnnCoa** [AudioKit/AudioKit#1191]
All of the playgrounds have errors and some do not work at all with Xcode 9.2.

**Comment by aure** [comment]
The playgrounds work, in general for me, so without further information from you I can't act on an issue this vague.  Please provide the errors at least.

**Comment by RickDT** [comment]
I had the same the same problem. Don't forget to hit Build. I still couldn't hear anything, even on the Hello World sample (errors logged, but no sound coming out). Xcode appeared to be stuck on "Running..." in the tasks list. Restarting my Mac worked! When in doubt, restart everything :)
