### ISSUE TITLE
Support Manually Built Framework in Podspec vs. Compiled Framework

### ISSUE THREAD

**Issue by b3ll** [AudioKit/AudioKit#1193]
Currently the podspec only really copies / links compiled frameworks. Are there any plans to have the ability to opt-in to have the frameworks compiled as part of Xcode's build phase? I know you can manually drag+drop the project, but having an opt-in option as part of the podspec or another dep name could be nice!

**Comment by aure** [comment]
Not really, we feel like if you want to take the easy road, use Cocoapods, if you want to take the nard, manually include the framework or even the project.  I'm not sure what audience would be served by this in-between solution. I'm willing to be convinced but it'll take more than "could be nice!" :)

**Comment by b3ll** [comment]
Fair enough. Personally I wanted to just point the podfile at my own fork as I make changes and such, and then eventually turn those into pull requests. I'll just use the manual Xcode project route for now. Thanks!

**Comment by aure** [comment]
For the AudioKit developer, I recommend developing your Xcode projects parallel to AudioKit in the file system, then you can point to one copy of AudioKit all the time and in any of your projects, should you find a bug you want to fix in AudioKit, you can do it right there and it will change your main AudioKit repo.
