### ISSUE TITLE
Fatal error: AudioKit: Could not start engine. Code=-10875  (iOS)

### ISSUE THREAD

**Issue by xJonas** [AudioKit/AudioKit#1194]
```
let SystemClass: System = System()
class System {
    public init() { }

    func playSound() {
        let sound = AKOscillator()
        AudioKit.output = sound
        AudioKit.start()
        sound.frequency = 500.0
        sound.amplitude = 0.5
        sound.start()
        DispatchQueue.main.asyncAfter(deadline: (DispatchTime.now() + 2.0)) {
            sound.stop()
        }
    }


    var tracker: AKFrequencyTracker!
    func receiveSound() {
        AudioKit.stop()
        AKSettings.audioInputEnabled = true
        let mic = AKMicrophone()
        tracker = AKFrequencyTracker(mic)
        let silence = AKBooster(tracker, gain: 0)
        AudioKit.output = silence
        AudioKit.start()
        Timer.scheduledTimer( timeInterval: 0.1, target: self, selector: #selector(SystemClass.outputFrequency), userInfo: nil, repeats: true)
    }

    @objc func outputFrequency() {
        print("Frequency: \(tracker.frequency)")
    }
}
```

I'm calling the small code from above with this lines..

```
SystemClass.playSound() //play sound
DispatchQueue.main.asyncAfter(deadline: (DispatchTime.now() + 3.0)) {
   SystemClass.receiveSound() //get microphone input 3 seconds later
}
```

... but I get big issues running the code on my iPhone device.

----

Issues:

`(1): AVAEInternal.h:103:_AVAE_CheckNoErr: [AVAudioEngineGraph.mm:1266:Initialize: (err = AUGraphParser::InitializeActiveNodesInOutputChain(ThisGraph, kOutputChainOptimizedTraversal, *GetOutputNode(), isOutputChainActive)): error -10875`

`(2): AVAudioEngine.mm:149:-[AVAudioEngine prepare]: Engine@0x1c401bff0: could not initialize, error = -10875`

`(3): [MediaRemote] [AVOutputContext] WARNING: AVF context unavailable for sharedSystemAudioContext`

`(4): [AVAudioEngineGraph.mm:1266:Initialize: (err = AUGraphParser::InitializeActiveNodesInOutputChain(ThisGraph, kOutputChainOptimizedTraversal, *GetOutputNode(), isOutputChainActive)): error -10875`

`(5): Fatal error: AudioKit: Could not start engine. error: Error`

`(6): Domain=com.apple.coreaudio.avfaudio Code=-10875 "(null)" UserInfo={failed call=err = AUGraphParser::InitializeActiveNodesInOutputChain(ThisGraph, kOutputChainOptimizedTraversal, *GetOutputNode(), isOutputChainActive)}.: file /Users/megastep/src/ak/AudioKit/AudioKit/Common/Internals/AudioKit.swift, line 243`

I got no idea how to solve the issues and would be super thankful for some useful tips.

Thanks in advance!

**Comment by aure** [comment]
This looks to be a bunch of errors due to local declaration of variables.  Don't do let mic or let silence inside of a function.  Instead, define them as instance variables.  Also, this is not an issue with AudioKit, its an implementation question, and should have been asked on StackOverflow.
