### ISSUE TITLE
AKFrequencyTrackerDSPKernel doing pointless extra work?

### ISSUE THREAD

**Issue by Meekohi** [AudioKit/AudioKit#1195]
https://github.com/AudioKit/AudioKit/blob/f99e45103f42b02f995df7271264828d9d3e1dc1/AudioKit/Common/Nodes/Analysis/Frequency%20Tracker/AKFrequencyTrackerDSPKernel.hpp#L65-L78

It seems to me like this loop goes through each channel, but just over-writes the results in `trackedFrequency` and `trackedAmplitude` each time, so is equivalent to just
`int channel = channels-1;` and doing it once.

Ideally we'd be averaging them together? For speed does it make more sense to just take the last channel?

**Comment by Meekohi** [comment]
Nevermind I get it now. This is feeding as many samples as it can to `sp_ptrack_compute` to try and fill up the `hopsize` buffer faster. `sp_ptrack_compute` only gets updated when the buffer fills up.

**Comment by Meekohi** [comment]
Hey reopening this -- upon further reflect this really doesn't make any sense, and is the reason in other places the frequency is mis-estimated by a factor of two and needs to be multipled by `channels`. For the `ptrack` algorithm it doesn't matter but you can imagine in the future this causing major issues (any algorithm that is intentionally biased toward certain frequencies). Fix is pretty simple I will probably make a PR after this deadline if nobody else has thoughts.

**Comment by aure** [comment]
A PR would be welcomed!

**Comment by Meekohi** [comment]
Closing this for now but expect a PR in the future when I get a little breathing room to work on it!
