### ISSUE TITLE
AudioKit  -  Listen for frequency change?

### ISSUE THREAD

**Issue by xJonas** [AudioKit/AudioKit#1196]
I'd like to track the frequency of the input microphone of my iOS device in real time.

Currently I'm using a timer calling the output-function thats prints `oscillator.frequency` every 0.1 seconds.

```
let timer = Timer.scheduledTimer( timeInterval: 0.1, target: self, selector: #selector(self.output), userInfo: nil, repeats: true)

func output() {
   print("Frequency: \(oscillator.frequency)")
}
```

---

But is there a way to just listen for the change of the `"oscillator.frequency"-struct`?

I need something like an event called every time if the "oscillator.frequency" changed.

Help would be very appreciated, thanks!

**Comment by aure** [comment]
This is not an issue with AudioKit, this a question about implementation and should be asked on StackOverflow.

**Comment by xJonas** [comment]
Your right aure it's really not an issue, however - Now I have asked the question on StackOverflow instead.
