### ISSUE TITLE
AudioKit AKSequencer does not loop

### ISSUE THREAD

**Issue by abinop** [AudioKit/AudioKit#1197]
The following code plays multiple audio files in a loop in iOS 11 but not in iOS 10. Seems like that AKSequencer cannot loop in iOS 10?

```
let mixer = AKMixer()
var sequencer: AKSequencer = AKSequencer()
sequencer.loadMIDIFile(fromUrl: URL(fileURLWithPath: midiFile))

for index in 0..<sequencer.tracks.count {
    let musicTrack: AKMusicTrack = sequencer.tracks[index]
    let sampler = AKMIDISampler()

    if index < samples.count {
        sampler.loadWavFromAbsolutePath(samples[index])
        sampler.enableMIDI(midi.client, name: "Sampler_\(index)")
        mixer.connect(input: sampler)
    }
    musicTrack.setMIDIOutput(sampler.midiIn)
}

AudioKit.output = mixer
AudioKit.start()
sequencer.enableLooping()
sequencer.play()
```

**Comment by aure** [comment]
That doesn't seem like a bug in AudioKit since we make no distinction between iOS10 and 11 in the source code for the sequencer. Probably a bug Apple fixed.  Not sure what we can really do about it.

**Comment by halldorel** [comment]
I'm seeing this behaviour on iOS 11, that is looping is not working. Plays once and then never again. 
As a workaround, I created a MIDI note 40 which plays when the loop should start again, and it calls `sequencer.rewind()`. Not sure if it's 100% accurate timing but is good enough for me at the moment.

```        let track = sequencer.newTrack()
        track!.setLength(AKDuration(beats: 5))
        
        track!.add(noteNumber: 36, velocity: 127, position: AKDuration(beats:0), duration: AKDuration(beats: 1))
        
        track!.add(noteNumber: 40, velocity: 1, position: AKDuration(beats:5), duration: AKDuration(beats: 1))
        
        sequencer.setTempo(86.0)
        sequencer.setLength(AKDuration(beats: 4))

        let callback = AKCallbackInstrument() { status, note, velocity in
            if status == .noteOn {
                if(note == 36) {
                    print("Callback triggered")
                    self.updatePlayStatusOnLoops()
                } else if (note == 40) {
                    sequencer.rewind()
                }
            }
        }

        sequencer.setGlobalMIDIOutput(callback.midiIn)
        
        mixer.start()
        
        sequencer.enableLooping()
        sequencer.play()```

**Comment by aure** [comment]
I think @crashingbooth has the solution. I'm not sure how I can force this to be the case, so I guess I'll just document it.

**Comment by crashingbooth** [comment]
I just posted this to the related SO question, where it's more likely to be seen.

**Comment by SebastianBoldt** [comment]
Is there any progress on this issue? 
I am experiencing the same faulty behaviour. 
The fix @crashingbooth suggested does not work for me.

**Comment by crashingbooth** [comment]
@SebastianBoldt, AKSequencer (and Apple's MusicSequence that it is based on) definitely loops, although admittedly it has a few quirks.  If you post your code to StackOverflow, or a link to your project, or (ideally) a link to a minimal project in which AKSequencer is not looping as expected, I'd be happy to take a look at it and see if I can help out.

**Comment by SebastianBoldt** [comment]
@crashingbooth Alright, i am not able to provide the whole project but i will try to create a project where things not working as expected. I will keep you updated.
