### ISSUE TITLE
AudioKit - "argument files (readFileName:) do not match any available overloads" Swift iOS

### ISSUE THREAD

**Issue by powsimian** [AudioKit/AudioKit#1200]
Hi Guys,

I hope the answer to this question is interesting for more than just myself. I had built my app to a further point, past this stage, but now I think the Update to 4.0.4 changed something.

I've modified the MicrophoneAnalysis example with the help of the AudioFileAnalysis playground file, and added into the code the AKAudioFile.

 `var input: AKAudioPlayer!` 
   `var song = try AKAudioFile!(readFileName: "TEST.mp3")  // ... the error is here` 

   ERROR:

> "(argument files (readFileName:) do not match any available overloads."

 ...and Ithe error here seems like it means "readFileName" is not the  right parameter name anymore. My other idea was that the file path isn't leading to TEST.mp3, but adding in " , baseDir: .resources" doesn't seem to change anything.

I read whilst searching for the answer to this new problem, that it's not a bug but rather a result of a modification in the API. That could be wrong. I'm sorry I don't know how to trouble shoot this myself but it seems to be

**Comment by aure** [comment]
I'm sorry it's taken so long to get back to you but this is just very strange because it does work for me. A ton of playgrounds use that exact same pattern.  Any further information?  Would you be willing to do a screenshare so I could see this happen in person (virtually)?

**Comment by powsimian** [comment]
Yes I'm willing to do a screen share. I hope the problem isn't just user-error. I don't know how you want to do this. Skype or Facetime?

**Comment by powsimian** [comment]
I just changed the code a TINY bit. The "try AKAudioFile!" is now "try! AKAudioFile"

BEFORE

```
var input: AKAudioPlayer!
var song = try AKAudioFile!(readFileName: "TEST.mp3") // ... the error is here
```


AFTER
```
var input: AKAudioPlayer!
var song = try! AKAudioFile(readFileName: "TEST.mp3") // ... the error is here
```

Sorry I struggled with it all last weekend but I think I figured it out after the week off.

**Comment by aure** [comment]
Strange that it didn't give you a better error message.  Wrap the try in a do catch block rather than try! if this is going to be production code.
