### ISSUE TITLE
Support for React Native & Apache Cordova? 

### ISSUE THREAD

**Issue by jamesharvey2** [AudioKit/AudioKit#1201]
Hello AudioKit team,

Thanks for creating this amazing audio framework for mobile devices.
However is it possible for you guys to create React Native version for android? 

React Native is a popular javascript based android framework from Facebook but it doesn't ship it any useful audio plugin...
https://facebook.github.io/react-native/

I would love to see React Native implementation of this library. 

Also, support for Apache Cordova would be great! 
cordova.apache.org

**Comment by jeden** [comment]
I'm new to this project, but I doubt that it will ever be ported to a cross-platform technology - if that is even possible, taking into account that you're mentioning javascript-based technology.

Btw I'd be happy to hear that I'm wrong... :)

**Comment by jamesharvey2** [comment]
It happened once before. This person converted EzAudio into NativeScript plugin... NativeScript is just like React Native. It builds android & iOS with javascript (www.nativescript.org)

https://github.com/NathanWalker/nativescript-ezaudio

and EzAudio is one of source libraries of AudioKit.

I hope someone can make this happen. I would love to use AudioKit on Android.... especially on React Native.

**Comment by jamesharvey2** [comment]
Even SDK version of AudioKit would solve the problems... then Java programmers can use AudioKit on android.

**Comment by dave234** [comment]
This is not going to happen with AudioKit, at it's core it is built on Apple technologies, so it would be an entire port.

**Comment by koraysels** [comment]
> This is not going to happen with AudioKit, at it's core it is built on Apple technologies, so it would be an entire port.

not really, we just need a plugin that can access the native methods of audiokit if the pltform is iOS. if it is android then another audio library can be used..

**Comment by trevor-sonic** [comment]
Android OS is just for web/data based apps. Mostly made for consuming data from the server and making  good looking web apps + photo sharing + some GPS stuffs that's it. Under the hood java is running to make the OS compatible with various devices. (like Adobe Flash player) What we had with windows os over the years now is happening on smart phone tech. with Android. Good in experimental  level.
