### ISSUE TITLE
xcodebuild build for Xcode 9.2 Failed ( Swift 4.0.3 and  iphonesimulator 11.2 )

### ISSUE THREAD

**Issue by lamgadekamal** [AudioKit/AudioKit#1203]
I am trying to run `$ xcodebuild -sdk iphonesimulator11.2` to build the `.app` file of the project of an iOS app project in Xcode to provide in Appium desired capabilities app path.
 Ref: (http://seleniumworks.blogspot.co.nz/2013/12/appium-native-ios-app-testing-webdriver.html) 
 
Build is failing with below error:
<img width="571" alt="screen shot 2018-01-16 at 10 44 36 pm" src="https://user-images.githubusercontent.com/34633303/34982540-8901ec30-fb0f-11e7-937b-2cd4a38d574e.png">

As per (https://github.com/AudioKit/AudioKit/issues/980) the binaries referenced in the pod were compiled with Xcode 8. So you can't use the pod version with Xcode 9, you'll have to build it from source, though that it is easy enough to do with the build_frameworks.sh script in Frameworks.

However, I am not clear how either one can be done.

**Comment by aure** [comment]
This does not make sense to me. The binaries were not made with Xcode 8 for some time, maybe you are using an old version. In any event, this is not an issue with AudioKit, but rather your implementation/installation quirks and shouldn't be raised on Github.
