### ISSUE TITLE
Example of using AudioKit to create an IAA or Audiobus host app

### ISSUE THREAD

**Issue by AnthonyMyatt** [AudioKit/AudioKit#1209]
Trying to replace the audio engine in my app with AudioKit, but I need some example code on how to implement an IAA / Audiobus host. The documentation hints at this example coming at some point, but has been like that for a long time. Is there any example code somewhere or plans to release some soon?

Thanks.

**Comment by aure** [comment]
Examples already exist: http://audiokit.io/audiobus/

**Comment by AnthonyMyatt** [comment]
Hi @aure,

Could you please provide more details. On that page I can only find examples for a generator (Sender Synth) and filter (Filter Effects App), not a host. I need my app to receive audio from IAA and Audiobus apps as the output node of a chain.

**Comment by aure** [comment]
We don't have an output node example, that is true, but is it much different than an effects node?

**Comment by AnthonyMyatt** [comment]
Normally in a host app, you would get a list of published AudioUnits and then connect one of the audio units as the input to the audio engine. I can use CoreAudio functions to get the list of AudioUnits as I have done before, I really just need to know how to set an AudioUnit as the AudioKit input. I assume I would need to create an AKNode subclass with a runtime settable AudioUnit and then I could just connect this AKNode as normal.

In regards to Audiobus, I need to call ABAudioReceiverPortReceive() to get the audio data from Audiobus and then pass the data to AudioKit. Again, I assume I would need to create an AKNode subclass with an AudioUnit subclass that calls ABAudioReceiverPortReceive() within its render function.

**Comment by aure** [comment]
I guess the issue here is that the effects example takes one stereo input from Audiobus and does processing on that whereas you want to get a multitude of inputs correct?

**Comment by AnthonyMyatt** [comment]
I only need a single input. The difference is that the effects example uses ABAudioFilterPort passing in the AudioKit input AudioUnit as the filter ports AudioUnit. ABAudioReceiverPort does not take an AudioUnit.

**Comment by aure** [comment]
Weird, yeah I guess I never considered this and it may require some code enhancements. You're the first to request this so if you end up finding a solution, it would be great to add it to our code base. I can invite you to our Slack group if you email me directly.

**Comment by AnthonyMyatt** [comment]
Thanks. Will see if I can work it out myself and contribute back to the project if I find a solution.

**Comment by aure** [comment]
Unless this issue see some action, I'm going to close it and instead refer to the fact that we need a host example in our projects: https://github.com/AudioKit/AudioKit/projects/2

**Comment by GeorgeL9** [comment]
Any updates to this? I am trying to build a host app as well.

**Comment by GeorgeL9** [comment]
I am interested in seeing how to do this as well.
