### ISSUE TITLE
update: Recognize metronome trigger using AKSamplerMetronome

### ISSUE THREAD

**Issue by Lennartbrugger** [AudioKit/AudioKit#1210]
🥇 Hey Aure,
this is an update to this [outdated question ](https://github.com/audiokit/AudioKit/issues/587) for the current version combined with using **AKSamplerMetronome**.

```
var metronome: AKSamplerMetronome

metronome = AKSamplerMetronome()
metronome.sound = Bundle.main.url(forResource: "my_soundA", withExtension: "wav")
        metronome.setBeatCount(4, at: now)
        metronome.setTempo(120, at: now)
        metronome.downBeatSound = Bundle.main.url(forResource: "my_soundB", withExtension: "wav")

let mixer = AKMixer()
metronome >>> mixer
AudioKit.output = mixer
AudioKit.start()
metronome.play()
```

Is there a way to detect the moment when the metronome triggers? - An event called every time if `metronome.sound` was played? So - **is there a way to count the amount of the already played sounds**?

EDIT: 
This is what I got so far, I'm using the `AKSamplerMetronome`-class to capture the `callback` I've found in your `AKMetronome.swift-file`. But tbh I can not really get it working so far!
 
```
open class AKSamplerMetronome2: AKSamplerMetronome {
    override init(sound soundURL: URL?, downBeatSound downBeatSoundURL: URL?) {
        self.callback = { print("test") }
        super.init(sound: soundURL, downBeatSound: downBeatSoundURL)
    }
    
    public var callback: AKCallback {
        didSet {
            callbackUgen.userData = callback
        }
    }
}
```

**Comment by dave234** [comment]
There's currently no callback built in to AKSamplerMetronome.

**Comment by aure** [comment]
So it seems the answer is no for now, but if you want to try to extend AK a pull request would be appreciated.
