### ISSUE TITLE
AKClarinet.stop() does not end note

### ISSUE THREAD

**Issue by crashingbooth** [AudioKit/AudioKit#1216]
AKClarinet's stop() method changes the isStopped value, but doesn't seem to do anything to the sound - there doesn't seem to be any obvious way to end a note.
By contrast, if, for example, you substitute an AKFlute into the AKClarinet's playground (or use AKFlute's nearly identical playground), the .stop() call clearly ends the note.  Presumably the method should work the same way for both classes.

**Comment by aure** [comment]
Yeah, these are identically implemented classes, I'll have to dig into STK to see what the issue is.

**Comment by aure** [comment]
For me stop works on neither of them.
