### ISSUE TITLE
Migration Guide for v4.1?

### ISSUE THREAD

**Issue by Meekohi** [AudioKit/AudioKit#1227]
Is there any migration guide or etc for upcoming changes? Wanted to try out the `develop` branch to see if any issues we're having have been resolved, but had to make some changes (handling new exceptions) and more importantly am stuck on an unexpected linker error (so I assume some functions have been removed or renamed?)

https://gist.github.com/Meekohi/626fb87c9a301a09c5bca4ab0f871a35

**Comment by aure** [comment]
There is a new Documentation folder in the develop branch where we can put such a guide, but for now I'd just like to suggest that you 

1. Delete the AudioKit-* directories inside of Frameworks that were generated by old versions
2. Clean the build folder cmd-opt-k I think
3. Make sure to see the new instructions on the Frameworks/README.md concerning no longer need to run "fix-frameworks.sh" as a build phase
4. Add the standard c++ library linker flags as described on the same Frameworks README.
5. Put AudioKit.start() inside a do try catch block
6. Migrate to AKPlayer if you were using AKAudioPlayer if possible (its still there, but good to move away from it)

There may be a few more changes I am forgetting, but this is a good start, see how you get on.

**Comment by Meekohi** [comment]
Thanks! Currently I'm building from source, so following this:

* Drag and drop the AudioKit For {platform}.xcodeproj file to your project in Xcode. The file is located within the AudioKit/{platform} subdirectory in the repository, where {platform} is one of iOS, macOS or tvOS.
* In the Build Phases tab, add AudioKit.framework in Target Dependencies for your target. Also add AudioKitUI.framework as needed.
* Make sure to add -lstdc++ to the Other Linker Flags setting in your target.

but am still getting the error above.

**Comment by aure** [comment]
Can you do a screenshare with me? There are a multitude of things that could be wrong.

**Comment by Meekohi** [comment]
Sure thing if you have time! I could do gchat:meekohi@gmail.com, or you can invite me to Slack if that's easier, or shoot me an e-mail if scheduling a time would be more convenient.

**Comment by polpiellaabadia** [comment]
I am having the same problem here, need some functionality from the new XCode beta (swift 4.1) and when importing the latest AudioKit, it gives me an error since it is built with swift 4.0.2. What should i do?

**Comment by Meekohi** [comment]
@polpiellaabadia Speculating, but I think in that case you may want to follow the 'build from source' instructions rather than try to use the Framework? I'm just using the normal stable XCode (which I think is still on Swift 3.2 by default?)

**Comment by polpiellaabadia** [comment]
alright i am going to try that, it is really vital because a quite big upgrade has been done to ARKit, so i would like to use the new version of Xcode. Will get back to you.

**Comment by polpiellaabadia** [comment]
Did not work... still having the same error.

**Comment by megastep** [comment]
If you used the script to compile, look at the value output by `xcode-select -print-path` - you need to switch the command-line tools to the beta Xcode first, else it will use the compiler from Xcode 9.2.

**Comment by polpiellaabadia** [comment]
I have actually switched the command-line tools to the beta Xcode and, when building, there are these errors and it fails to build. Any clue what to do now?
 <unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal 11 (use -v to see invocation)

**Comment by megastep** [comment]
Ugh... That actually does sound like crashes in the tools, it is an early beta still after all.

**Comment by polpa** [comment]
Yes it does seem like that, let's see when 9.3 actually comes out 👍

**Comment by Meekohi** [comment]
Hey everyone, the solution to my problem was to move AudioKit.framework from the "Embedded Binaries" section of project settings to the "Linked Frameworks and Libraries" section. See if that works for you!

https://www.dropbox.com/s/yy2l6eww4znmdn1/Screenshot%202018-02-01%2012.20.58.png?dl=0
