### ISSUE TITLE
Archive Fails with error

### ISSUE THREAD

**Issue by sinewavemultimedia** [AudioKit/AudioKit#1230]
I am getting the following error when I try to archive my app for the app store. I am 100% certain I am using a distribution profile.

iTunes Store Operation Failed
Invalid Signature. Code object is not signed at all. The file at path [MusiciansU.app/Frameworks/AudioKit.framework/fix-framework.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html

**Comment by sinewavemultimedia** [comment]
I got it working. I was not actually running that script first.

**Comment by ashusath** [comment]
@sinewavemultimedia Which script, i have installed it via cocoapod. its giving me same error while uploading to testflight

**Comment by pratik1311** [comment]
@ashusath Did you solve your issue ?
