### ISSUE TITLE
Delays when playing multiple AudioPlayer using AKMixer

### ISSUE THREAD

**Issue by TACGalang** [AudioKit/AudioKit#1238]
I've noticed some delays when playing multiple AKAudioPlayer using AKMixer.

self.playerList[0]?.play()
self.playerList[1]?.play()
self.playerList[2]?.play()
self.playerList[3]?.play()
self.playerList[4]?.play()
self.playerList[5]?.play()
self.playerList[6]?.play()
self.playerList[7]?.play()
self.playerList[8]?.play()
self.playerList[9]?.play()

**Comment by dave234** [comment]
This is more of a StackOverflow question.  Something like,  “How do I synchronize AKPlayers?”
