### ISSUE TITLE
Crash when plugging in/taking out headphones on iPhone6

### ISSUE THREAD

**Issue by Paulcoops** [AudioKit/AudioKit#1239]
Hello,

When I use AKChorus or AKFlanger in the chain and plug in/take out headphones on the iOS device, the app crashes.

<img width="501" alt="screen shot 2018-02-14 at 17 51 19" src="https://user-images.githubusercontent.com/6607599/36216831-2bd44d52-11b0-11e8-91d6-8504b461abfb.png">

Thank you!

**Comment by aure** [comment]
Thanks, I've alerted the author of these processors @getdunne

**Comment by getdunne** [comment]
I am unable to reproduce the problem, testing on an iPad Air 2. This code has recently been revamped quite extensively, including changes to the init() functions. Please test again with the latest AudioKit code (pull the Develop branch and be sure to re-compile the frameworks), and let us know if the problem persists.

**Comment by Paulcoops** [comment]
I've build the Develop branch framework and found out the problems persists and might be somewhere deeper. With AKChorus & AKFlanger the app crashes after the first time I plug-in/-out the headphone. And I get errors like:

```
Could not find function called '\321'.
\321 returned an error.
```

I discovered that without AKChorus & AKFlanger the app crashes after the second time I plug-in/-out the headphones. The first time I get a similar "Could not find function" message and the app continues. Second time: *boom.

```
Could not find function called '\243'.
\243 returned an error.
Plynx(37361,0x16f9c7000) malloc: *** error for object 0x103065820: pointer being freed was not allocated
```

I figured out that when I take out the AKOperationEffect, AKChorus & AKFlanger I can plug-in/-out my headphones all the time without any problems, just with a less desirable sound.

I can reproduce the problem with the Hello World example for iOS by adding an AKChorus:

```
20    var chorus = AKChorus()
21
22   required init?(coder aDecoder: NSCoder) {
23        super.init(coder: aDecoder)
24        mixer = AKMixer(oscillator1, oscillator2)
25        chorus = AKChorus(mixer)
26
27        // Cut the volume in half since we have two oscillators
28        mixer.volume = 0.5
29        AudioKit.output = chorus
```

I hope this helps to solve the issue.

Thank you!

**Comment by aure** [comment]
That's a problem with AKOperationEffect, no chorus or flanger, bu the HelloWorld crash is surprising since it does not have that.

**Comment by Paulcoops** [comment]
Okay, found out a bit more: Issue is with iPhone 6. Just tested it on an iPad Air 2 and it works all fine...

**Comment by aure** [comment]
Ok so this is because the iphone6 mucks with sample rate because some parts of it are 48 and others 44.

**Comment by Paulcoops** [comment]
Sorry, I wasn't aware this. Should I close this issue, or do you think there could be a solution?

**Comment by dave234** [comment]
6 still has a 44.1K sample rate, 6S has the 48K rate.

**Comment by aure** [comment]
Huh, then wtf

**Comment by mscheffel** [comment]
Same problem here. As soon as I connect the output to a node-output, I get 48kHz on iPhone 6s or higher. iPhone 6 and older are fine...
Even when I set the samplerate to 48kHz (or to the guiding samplerate of AVAudioSession.sharedInstance().sampleRate) I get the clicking noise, as it was the wrong samplerate...

**Comment by kunalzigma** [comment]
I also have the same issue with AKOperationEffect. I posted on stackoverflow - https://stackoverflow.com/questions/47965943/disconnecting-headphones-with-audiokit-running-gives-malloc-error-with-akoperati?noredirect=1#comment82902844_47965943  
some time back.
Any help would be appreciated. Thanks
