### ISSUE TITLE
What does fix-framework.sh do?

### ISSUE THREAD

**Issue by jnsu** [AudioKit/AudioKit#1243]
I installed v4.1 using cocoapods. It gives me the following compile error.

`/Users/jinsukim/Library/Developer/Xcode/DerivedData/Zone-gzyjrqeujuaitqdxshpdkrocrneq/Build/Intermediates.noindex/Zone.build/Debug-iphonesimulator/Zone.build/Script-744ED2A61EFBF6E200A0FE5B.sh: line 2: /Users/jinsukim/Library/Developer/Xcode/DerivedData/Zone-gzyjrqeujuaitqdxshpdkrocrneq/Build/Products/Debug-iphonesimulator/Zone.app/Frameworks/AudioKit.framework/fix-framework.sh: No such file or directory`

**Comment by megastep** [comment]
Version 4.1 is now a static framework, and there's no longer a need for running this script. It's probably a leftover from the previous version. Look at the run phases for the target in your project, and there's probably a script phase calling it. You can safely remove it.
