### ISSUE TITLE
Possible error in AKPlayer currentTime calculation?

### ISSUE THREAD

**Issue by ianclawsonhq** [AudioKit/AudioKit#1245]
Hey guys,

Excellent work on the entire library, it's a joy to work with.

I'm seeing what I believe to be unusual values print for AKPlayer's current time. If I run the following block of code:

```
player.startTime = 0
player.play()
printPlayerTimeDebugLog(withLabel: "mPlay")
```

where `player` is a successfully instantiated instance of AKPlayer with an mp3 or wav file, and `printPlayerTimeDebugLog(withLabel label: String)` is defined as 
```
func printPlayerTimeDebugLog(withLabel label: String) {
    print("\(label) playPos:\(player.currentTime), playStart:\(player.startTime), playEnd:\(player.endTime)")
}
```

then the following line will print:
```
mPlay playPos:-0.0464399092970522, playStart:0.0, playEnd:148.492403628118
```

I'm not sure how currentTime could be negative, so I believe it to be a bug in the calculation. I'm seeing the same value `-0.0464399092970522` print for the player's currentTime regardless of the loaded audio file's size or length.

If in that top line of code we set `player.startTime = 4`, for example, then the line prints as
```
mPlay playPos:3.95356009070295, playStart:4.0, playEnd:148.492403628118
```

So to us, it looks to be about that off each time.

Any idea what could be going on here? Is this expected behavior that I haven't learned yet?

Thanks!

**Comment by dave234** [comment]
This is an implementation artifact from the underlying AVAudioPlayerNode.  If play() is used (rather than play(at:)) the actual start time will be set to two render cycles in the future.  So with a default IOBufferDuration of 0.23, this seems about right.

**Comment by ianclawsonhq** [comment]
Thank you for the quick response! This is very helpful. From what you said, and after checking `AKSettings.ioBufferDuration` and including it * 2 for some calculations, this definitely seems to be the case. I will code accordingly. Thank you!

**Comment by dave234** [comment]
To be more specific, it’s actually two render cycles from the beginning of the last render cycle.  This can be obtained from AVAudioNode.lastRenderTime.

**Comment by ianclawsonhq** [comment]
I see, thank you! That would explain the very, very small difference in time that we're sometimes seeing, even after applying `AKSettings.ioBufferDuration * 2`.

If possible, I would like to get the lastRenderTime so we can get a more accurate calculation. But with AKPlayer, its underlying AVAudioPlayerNode is (understandably) private, so there's no way currently that I can see to get its lastRenderTime.

our current implementation is this:
```
func mPlayFrom(newPosition position: Double) {
    player.setPosition(position + (AKSettings.ioBufferDuration * 2 + 0.00001))
}
```

We allow the user to input a time down to the millisecond that the audio will jump to at a given other time in the audio playback. Once the given time is reached, the above function is called, passing in the user input time. We have `+ 0.00001` in there because, without it, the player will sometimes play just ever so slightly before the input time, which throws off some of our dependent logic.

Is there another way for us to get the players lastRenderTime?

**Comment by dave234** [comment]
You can get the lastRenderTime from any node, as long as there aren't any time/pitch effects in-line.  I usually get the output node.

```
if let lastRenderTime = AudioKit.engine.outputNode.lastRenderTime {
    // Code
}
```

**Comment by dave234** [comment]
If you are scheduling different segments of file(s) to play at precise times, you should try out AKClipPlayer.

**Comment by osheroff** [comment]
@dave234 came across this issue after an evening of pulling out hair trying to figure out why my code to sync two mixes (one of which is already playing) was off by just the littlest hair.  In my case 64 millseconds. 

> To be more specific, it’s actually two render cycles from the beginning of the last render cycle. This can be obtained from AVAudioNode.lastRenderTime.

Could you maybe show a bit of code for this?  I'm doing:

```
 let refThing = player.playerNode.lastRenderTime
 let syncTime = player.position(at: refThing) + (AKSettings.ioBufferDuration * 2)
 otherPlayer.play(from: syncTime, ...)
```

but it looks like my sync is still off by 21ms.  Should I just be multiplying ioBufferDuration by 3 here or is there something subtle I'm missing?
