### ISSUE TITLE
AKPitchShifter bug when connected to ADSR

### ISSUE THREAD

**Issue by alexbuga** [AudioKit/AudioKit#1246]
So I have an AKPlayer through this signal chain
        player >>> pitchShifter >>> lowPassFilter >>> highPassFilter >>> adsr
        output = adsr

If hit a note, I start the player and the adsr nodes. All good.
But If I hit a different note, which does the same thing, except it changes the pitch shift, the ADSR is ignored.

**Comment by aure** [comment]
I don't see anything obviously wrong from you description.  Perhaps you can share some code and/or a  project demonstrating the issue.  Also, until we can identify this as an issue with AudioKit and not your implementation, this is probably something better discussed on StackOverflow.
