### ISSUE TITLE
AKSamplerMetronome creates Pop when stopping engine

### ISSUE THREAD

**Issue by ryanfrancesconi** [AudioKit/AudioKit#1248]
Here's one for Dave,
I am getting a pop when stopping the Audio engine if I have an AKSamplerMetronome connected to my main mixer. I have only tried on macOS.

**Comment by dave234** [comment]
It always pops when stopping the engine?  Or is there a specific scenario where this happens.  In general, if audio is playing when the engine stops (without first fading valine to zero) you’re likely to hear a pop from any node.

**Comment by ryanfrancesconi** [comment]
As far as I can see it's clearly from the addition of the Metronome into my graph. It only happens after I added it. Now when I stop the engine I get a pop. This happens when there is no other audio playing or connected. 

If you're unable to reproduce easily I can try to make a test for you as it's in my large project right now.

**Comment by dave234** [comment]
A test project would be great!

**Comment by ryanfrancesconi** [comment]
[MetronomeTest.zip](https://github.com/AudioKit/AudioKit/files/1761354/MetronomeTest.zip)

**Comment by ryanfrancesconi** [comment]
i don't get the pop when just stopping the metronome, only when stopping the metronome and the engine. It doesn't seem quite expected to me the way I'm getting these sporadic pops after stop is called. Is that normal?

**Comment by ryanfrancesconi** [comment]
Note, the pop still occurs if the main output mixer volume is 0

**Comment by dave234** [comment]
I'm getting a " incompatible project version." message when trying to open that project.

**Comment by ryanfrancesconi** [comment]
I made with the latest xcode beta. Are you using an older version?

**Comment by dave234** [comment]
Yes, I'm on the 9.2 release.


On Tue, Feb 27, 2018 at 10:44 AM, Ryan Francesconi <notifications@github.com

**Comment by aure** [comment]
@dave234 and @ryanfrancesconi since Xcode 9.3 is out now, perhaps you both are on the same page with this project? And you're both on slack and no one else has chimed in, so I'm not sure this issue is doing much good here.

**Comment by ryanfrancesconi** [comment]
Oh yeah. We figured out that the bug is in the avsampleraudiounit. Sorry forgot about the issue.
