### ISSUE TITLE
Undefined symbols for architecture arm64 when update to  AudioKit v4.1

### ISSUE THREAD

**Issue by zbydonuts** [AudioKit/AudioKit#1250]
Thanks for providing such a grate library, It helps me a lot. 
I am trying to update the AudioKit from 4.0 to 4.1. I use the Carthage to  manage the libraries. But this time there is some error during my building phase. 

The warning message is "Carthage/Build/iOS/AudioKit.framework/AudioKit is not a dylib", and there a several error for "Undefined symbols for architecture arm64"
 "__T08AudioKitAAC19disconnectAllInputsyyFZ", referenced from:
 "__T08AudioKitAAC4stopyyKFZ", referenced from:
etc

I don't know what's wrong with it, can someone give me some suggestion?

**Comment by zbydonuts** [comment]
The AudioKit in AudioKit.framework is not executable,  However, the previous version has the executable AudioKit in the framework.

**Comment by megastep** [comment]
Starting in 4.1, we now ship AudioKit as a static framework (no longer dynamic). It would appear that this is not supported by Carthage. You could switch to CocoaPods or manually include the framework in your project.
