### ISSUE TITLE
Need to include comment about Dummy.swift in README

### ISSUE THREAD

**Issue by ideaMarcos** [AudioKit/AudioKit#1252]
I was trying to emulate HelloObjectiveC project but I would get a linker error regarding Metal Framework. Eventually I realized that Dummy.swift was needed in my Objective C project to trick Xcode into compiling (no bridge needed). Can you add some words to the README?

**Comment by aure** [comment]
Why don't you add this, it is open source after all!

**Comment by megastep** [comment]
Actually I found some compiler options that allows pure Objective-C projects to compile without that dummy file now. The options are set in the pod, and should be in the develop branch for the HelloObjectiveC project.

**Comment by megastep** [comment]
Basically you need to make sure your library search paths include this: `"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"`

**Comment by huangxinyu1213** [comment]
@megastep How to setting `"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"` in podspec?

**Comment by megastep** [comment]
The AudioKit podspec already includes that line so that Objective-C projects using the pod should already link properly out of the box.
