### ISSUE TITLE
Umbrella header missing 'AKExponentialParameterRamp.hpp' / Linker Error

### ISSUE THREAD

**Issue by josevazquez** [AudioKit/AudioKit#1254]
I have a simple macOS MIDI project which works fine when compiled against v4.0.4. When update AudioKit to more recent versions of the `develop` branch (484157dc007e3c5e4dc960dc63ef8f985acf7c41) the library still compiles fine, but my fails to link against it. First, I get the following warning:
```
<module-includes>:1:1: warning: umbrella header for module 'AudioKit' does not include header 'AKExponentialParameterRamp.hpp'
#import "Headers/AudioKit.h"
^
```
Followed by a series of undefined symbol errors during linking. (the full error message ca be seen [here](https://gist.github.com/josevazquez/8c664186cd920f8b319532a03f3f78ee).)

My app is a simple macOS app, straight from an Xcode template. I then dragged the AudioKit project and added the AudioKit framework to my project. Like I said it works fine when I take AudioKit back to v4.0.4.

**Comment by megastep** [comment]
You need to add `-lstdc++` to your linker flags. This is now a requirement with the static library shipping with version 4.1.

**Comment by josevazquez** [comment]
That worked, thank you.
