### ISSUE TITLE
Found an unexpected Mach-O header code when attempting to upload to the app store

### ISSUE THREAD

**Issue by derekleerock** [AudioKit/AudioKit#1257]
Hello Aure & AudioKit contributors - thanks again for providing this great framework for us to use!

I've been using AudioKit for a few months now and recently upgraded to 4.1. I'm using Carthage to pull AudioKit into my app and with 4.1 I had to make a few changes according to the [Frameworks Readme](https://github.com/audiokit/AudioKit/blob/master/Frameworks/README.md) that you kindly put together for us. 

I'm now getting a strange error when trying to upload an archived build to the App Store: "Found an unexpected Mach-O header code: 0x72613c21"

The logs indicate the following:

**IDEDistribution.critical.log** 
```
"2018-03-03 00:30:35 +0000  Failed to generate distribution items with error: Error Domain=DVTMachOErrorDomain Code=0 "Found an unexpected Mach-O header code: 0x72613c21" UserInfo={NSLocalizedDescription=Found an unexpected Mach-O header code: 0x72613c21, NSLocalizedRecoverySuggestion=}"
```

**IDEDistribution.standard.log**
```
"2018-03-03 00:30:35 +0000  [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fb0d0b829f0:'/Users/username/Library/Developer/Xcode/Archives/2018-03-03/AppName 3-3-18, 00.24.xcarchive/Products/Applications/AppName.app/Frameworks/AudioKit.framework'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/username/Library/Developer/Xcode/Archives/2018-03-03/AppName 3-3-18, 00.24.xcarchive/Products/Applications/AppName.app/Frameworks/AudioKit.framework" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/username/Library/Developer/Xcode/Archives/2018-03-03/AppName 3-3-18, 00.24.xcarchive/Products/Applications/AppName.app/Frameworks/AudioKit.framework" did not contain a "archived-expanded-entitlements.xcent" resource.}"
```

**IDEDistribution.verbose.log**
```
2018-03-03 00:30:35 +0000  [OPTIONAL] Can't have a profile, not a bundle at <DVTFilePath:0x7fb0cec7c4e0:'/Users/username/Library/Developer/Xcode/Archives/2018-03-03/AppName 3-3-18, 00.24.xcarchive/Products/Applications/AppName.app/Frameworks/libswiftCoreGraphics.dylib'>
2018-03-03 00:30:35 +0000  IDEDistributionItem init <DVTFilePath:0x7fb0d0b829f0:'/Users/username/Library/Developer/Xcode/Archives/2018-03-03/AppName 3-3-18, 00.24.xcarchive/Products/Applications/AppName.app/Frameworks/AudioKit.framework'>
```
Since I haven't changed my Carthage configuration and I'm able to build on both debug and release targets as well as run the application on my device, I don't think that there's an issue there. 

But just in case, I verified my Carthage configuration:

**Cartfile**
```
github "audiokit/AudioKit"
github "PureLayout/PureLayout"
```

**Cartfile.private**
```
github "Quick/Quick"
github "Quick/Nimble"
```

**Cartfile.resolved**
```
github "PureLayout/PureLayout" "v3.0.2"
github "Quick/Nimble" "v7.0.3"
github "Quick/Quick" "v1.2.0"
github "audiokit/AudioKit" "v4.1"
```

Then I deleted my entire Carthage directory and refreshed everything using:

`carthage update --platform iOS --no-use-binaries`

... and was surprised to see that AudioKit was not being built - but instead, a framework called DropDown was:

```
*** Fetching PureLayout
*** Fetching AudioKit
*** Fetching Nimble
*** Fetching Quick
*** Checking out AudioKit at "v4.1"
*** Checking out Nimble at "v7.0.3"
*** Checking out PureLayout at "v3.0.2"
*** Checking out Quick at "v1.2.0"
*** xcodebuild output can be found in /var/folders/qp/_gkfvwvn5wj71k95ljxzhbn80000gn/T/carthage-xcodebuild.SCSmnh.log
*** Building scheme "DropDown" in DropDown.xcodeproj
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "PureLayout_iOS" in PureLayout.xcodeproj
*** Building scheme "Quick-iOS" in Quick.xcworkspace
```

Checking the Carthage/Build folder there is a file named ".AudioKit.version" that I opened up to find the following:

```
{
  "commitish" : "v4.1",
  "iOS" : [
    {
      "name" : "DropDown",
      "hash" : "cb7e8ef90ee614c0dbb3839bf0132eaff8c490a0be3b553f85ed3e6c735c3ff6"
    }
  ]
}
```

And when comparing to other similar files, I would have expected the framework name to have matched like Nimble does:

```
{
  "commitish" : "v7.0.3",
  "iOS" : [
    {
      "name" : "Nimble",
      "hash" : "cea8db96b906c46f454ff0adffb2d10b3e24002f580c5c135fa60f054dff1f29"
    }
  ]
}
```

And naturally when trying to build my app, Xcode cannot find the AudioKit framework. So I tried to switch it over to DropDown just to see if that would work but naturally it cannot find the classes from AudioKit that I am using like AKSequencer, AKTrack, etc. 

Recalling that I recently added the `--no-use-binaries` to ensure that I was building everything from scratch, I decided to try to update without that:

`carthage bootstrap --platform iOS`

This downloaded the AudioKit binary and seemed to be working fine when running in the simulator and device, but it is generating the same "Found an unexpected Mach-O header code" error when trying to upload to the App Store after archiving. There are also warnings that are shown when trying to archive:

```
while processing /Users/username/path/AppName/Carthage/Build/iOS/AudioKit.framework/AudioKit(t.o):
warning: /var/folders/g3/3gw8_98n3d7_qkzthq9tx6t00000gn/C/org.llvm.clang.megastep/ModuleCache/37G0VU30FMI6Z/Darwin-MI6WZSG1PNOM.pcm: No such file or directory
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
```

Of course its entirely possible that I missed something when upgrading to 4.1 that needs to be done but I also wanted to share and see if this might be something within the Framework that is maybe configured differently in 4.1?

Xcode version is **9.2 (9C40b)**
Carthage version is **0.28.0**

Any help you can provide would be greatly appreciated. Thank you for your help and support!

Best,

Derek

**Comment by megastep** [comment]
Thanks for the detailed report, however the main issue here is that we switched from a dynamic framework to a static framework in AudioKit 4.1.

Unfortunately, this seems to mean that you cannot use Carthage with AudioKit because they only handle dynamic frameworks for now. This is the main reason why you get all of these issues.

I suggest you either switch to CocoaPods (at least just for AudioKit) or manually include the compiled framework in your project.

**Comment by derekleerock** [comment]
Thanks for the quick reply @megastep - I really appreciate it!

I just built the framework myself and included it in my app and as you mentioned this does solve the problem. 

However, I'm admittedly a bit disappointed that I spent a couple of hours trying to debug this. 😅

Would it be possible to update the documentation to make this a bit more clear? Maybe the best course of action is to remove Carthage from the list of available dependency managers in the main readme file? It might also help to include this in the release notes for 4.1 as well as the [Frameworks readme file](https://github.com/audiokit/AudioKit/blob/master/Frameworks/README.md).

**Comment by megastep** [comment]
Right, a couple of other people have also reported this and we just weren't aware of this limitation when we shipped 4.1. I suppose we'll clarify it in the next release. None of us really do use Carthage :)

**Comment by ppamorim** [comment]
Any update for the carthage fix?

**Comment by ppamorim** [comment]
Not working even if I build a universal frameworks, any idea how to solve this?

**Comment by megastep** [comment]
Apparently there is no way to solve this for Carthage, since they just don't support static frameworks.

**Comment by AviDutta** [comment]
https://github.com/Carthage/Carthage/releases/tag/0.28.0 of Carthage supports static binaries.

**Comment by megastep** [comment]
That's great news. We still ship the appropriate zip files with the releases which would work with Carthage. Have you tried it with AudioKit?
