### ISSUE TITLE
Volume boost file

### ISSUE THREAD

**Issue by Lennartbrugger** [AudioKit/AudioKit#1261]
I was wondering if there is a method to increase the volume of local stored AudioFiles above the default volume (1.0):

```
let metronome = AKSamplerMetronome()
let file = Bundle.main.url(forResource: "filename", withExtension: "wav")

metronome.sound = file
metronome.volume = 1.0 // How to volume boost on local file called "filename.wav"?
```

Any help would be very appreciated! Thanks in advance :)

**Comment by aure** [comment]
This would be a question for StackOverflow, not Github issues.  If you post there I'll make a quick reply.
