### ISSUE TITLE
Logo Desing Contribution

### ISSUE THREAD

**Issue by ihtiht** [AudioKit/AudioKit#1263]
Hi, I am happy to support open source projects. So I follow your AudioKit project closely. I wanted to make a small contribution to AudioKit.  I voluntarily designed a logo. I hope you will like it. If you like it, I will provide the necessary format files. Thank you !
![sunu1](https://user-images.githubusercontent.com/36369736/37299661-fa5024d8-2634-11e8-9383-b96f9f728f9c.jpg)
![sunu2](https://user-images.githubusercontent.com/36369736/37299672-ffb2c7be-2634-11e8-90d5-1827a268121d.jpg)
![icon](https://user-images.githubusercontent.com/36369736/37299682-09330074-2635-11e8-942a-5186703d02f8.png)
![webview2](https://user-images.githubusercontent.com/36369736/37299734-25c38574-2635-11e8-803a-0ec9aadb16de.jpg)

**Comment by aure** [comment]
Hi, thanks for your contribution.  It's not really an "issue" though so I will close it here and communicate with you via email. Thanks!
