### ISSUE TITLE
EZRecord / EZMicrophone crashes

### ISSUE THREAD

**Issue by leonardocustodio** [AudioKit/AudioKit#1264]
Same issue as here:
https://github.com/syedhali/EZAudio/issues/246

EZRecorder crashes when trying to update with different buffersize than 512 and 1024.

This issue was fixed in https://github.com/syedhali/EZAudio/pull/265/files

Is it possible to update the code in AudioKit?

Thanks,
Leonardo

**Comment by aure** [comment]
That pull has 587 changed files. I thought we got EZAudio more recently than when that pull request was made.  Why don't you make the changes in AudioKit and make a pull request? I'll happily accept it.

**Comment by leonardocustodio** [comment]
Ok, no problem. There you go: https://github.com/AudioKit/AudioKit/pull/1269
Thanks Aure
