### ISSUE TITLE
Plots don't get the node variable from the init call?

### ISSUE THREAD

**Issue by nCr78** [AudioKit/AudioKit#1266]
Hello! It seems this issue has been submitted before in a similar way and it might lead to some confusion. The AKNodeOutputPlot/AKOutputWaveformPlot and other plots don't seem to listen to .pause() or .resume() calls when you initialise them for example like:

`newPlot = AKNodeOutputPlot(someNode, frame: CGRect(...))`

Instead, you have to add that "someNode" after the initialisation, like this:

`newPlot = AKNodeOutputPlot(someNode, frame: CGRect(...))`
`newPlot.node = someNode`

Is this the intended behaviour? Shouldn't newPlot.node be initialised too from the init call?

**Comment by aure** [comment]
I think this has to do with view life cycle.  I haven't had luck with having the node in the init either.

**Comment by nCr78** [comment]
Well, adding it manually right after the init call seems to solve this. Calling newPlot.pause() only works if you had set the newPlot.node .

**Comment by aure** [comment]
You no longer have to set the node after the init.
