### ISSUE TITLE
Mandolin physical model is broken

### ISSUE THREAD

**Issue by ultimatedbz** [AudioKit/AudioKit#1270]
Initializing `let mandolin = AKMandolin()` produces an error. In the playground, the message `(3683,0x7fffb65e8340) malloc: *** error for object 0x1097f1300: pointer being freed was not allocated` is shown. When putting that line into an app, the stack trace shows
<img width="1796" alt="screen shot 2018-03-15 at 11 25 54 pm" src="https://user-images.githubusercontent.com/7156604/37506686-4419fc22-28a8-11e8-979e-4d248fa8d3d6.png">

Thanks!

**Comment by aure** [comment]
"Mandolin is broken" is a known issue in 4.1 as noted here https://github.com/AudioKit/AudioKit/releases/tag/v4.1 but we might as well have an open issue for this as well.

**Comment by megastep** [comment]
Do we have a test project exhibiting this problem?

**Comment by megastep** [comment]
Actually never mind, I think it should be fixed on develop right now.

**Comment by megastep** [comment]
Also, `_private` was never allocated as it should have been, causing nil pointer reference in the constructor. Should work now.
