### ISSUE TITLE
AKPlayer Pause / Resume Capability?

### ISSUE THREAD

**Issue by cojo** [AudioKit/AudioKit#1272]
Hi,

Just started using AudioKit and very excited about its potential.

I saw an indication in `AKAudioPlayer` that perhaps `AKPlayer` is the better / preferred way to play audio files going forward.  However, it currently does not appear to support pause / resume.  I was wondering if this is intentional / "will not implement" or if it's just pending future work as the class is still relatively new?

If it's not intentionally omitted, would you be open to a PR implementing that functionality?

Thanks!

**Comment by aure** [comment]
We're always interested in PRs!  I think a pause and resume file would be cool, but I'll also let @ryanfrancesconi chime in here.

**Comment by ryanfrancesconi** [comment]
I can add that for you.

**Comment by cojo** [comment]
Awesome, thanks!  Turns out I didn't have as much time available as I thought I did to try to add it myself.

**Comment by ryanfrancesconi** [comment]
Sorry, didn't notice this till today. Will just take a sec.

**Comment by ryanfrancesconi** [comment]
and thanks for pointing out the missing call. Wasn't something I need as my players are all driven by UI components.

**Comment by cojo** [comment]
No worries, 3 days is way faster than many projects I've worked with elsewhere!  Thanks for the quick follow-up and implementation - really appreciate the responsiveness and the effort on the project in general :+1:
