### ISSUE TITLE
[macOS] Best practices for switching Input and Output devices on the fly?

### ISSUE THREAD

**Issue by ericrieper** [AudioKit/AudioKit#1273]
Hi,

I'm wondering if there are best practices for how to switch the input of `AudioKit.setInputDevice(...)` and `mic.setDevice(...)`, as well as `AudioKit.setOutputDevice(...)` on the fly?

Working on an app that allows users to set their desired input and output devices, I usually receive numerous errors, usually resulting in no audio being functional after that point.

Setting the same custom input / output devices from startup works reliably.

Thanks!

**Comment by aure** [comment]
This is really something that should be posted to StackOverflow. We use issues for bug tracking and StackOverflow for answering questions.  StackOverflow is a large community, and questions don't get archived like issues do.  Thanks!
