### ISSUE TITLE
iOS 9 Error

### ISSUE THREAD

**Issue by GrantJEmerson** [AudioKit/AudioKit#1277]
I am getting the following error when downloading my Audio Kit application onto my iPad 2: AURemoteIO::IOThread (7): EXC_BAD_ACCESS (code=1, address=0x0). Do you have any idea as of what this might be related to?

**Comment by aure** [comment]
No I really don't.  You might have better luck asking this question on StackOverflow and if the solution is some work that needs to be done, come back here and reopen it as an issue. Thanks. I don't have an iPad2  to test but maybe does on SO.

**Comment by GrantJEmerson** [comment]
So, I looked into it some more and I found the root of the problem. 

First I create a variable to hold an AKOperationGenerator called synth. Then, inside of setUpAudioKit() I initialize a variable called voltageControlledAmplifer with AKBooster(synth, gain: 1). Right after this, I set AudioKit.output to voltageControlAmplifier. This results in the crash. However, if I set AudioKit.output directy to AKBooster(synth, gain: 1), no crash occurs. 

I tried looking into the code of AKBooster, but I couldn't find anything wrong. Do you have any further ideas of what this might be?

**Comment by aure** [comment]
It doesn't sound bad to me to have a booster in there, perhaps something is up with operation generators not being able to be the direct output of AudioKit. Hard to tell without the project in front of me.
