### ISSUE TITLE
Rendering sequencer with AudioKit plays extremely slow

### ISSUE THREAD

**Issue by robtize** [AudioKit/AudioKit#1278]
I'm porting my app's Audio Engine to AudioKit, however when I render a song using AudioKit's AKSequencer with AKSampler's and AudioKit.renderToFile, AKOfflineRenderNode, or even using the method found here https://github.com/VladimirKravchenko/AVAudioEngineOfflineRender (this still works for me on my previous audio engine), the output file plays at a very very slow rate. Exporting a song with just AudioPlayers works completely fine at the expected rate

**Comment by aure** [comment]
Could you share your code?  Not a lot I can debug without something like that.  Please reopen this issue or post to StackOverflow with the example project link.
