### ISSUE TITLE
AKPlayer doesn't seem to respect .play() calls in intermediate timestamps on iOS

### ISSUE THREAD

**Issue by adarhef** [AudioKit/AudioKit#1279]
Full disclosure: I'm attempting to emulate pause/resume capabilities that I've already seen were implemented recently. I was not able to embed the develop build of the framework in my project for testing however (even after reading the guidelines for doing so), so I've given up on it at this point because I don't want to embed the framework like this in production. 
Since pod updates are relatively few and far between, I would like to solve this issue directly with what's currently available, and so if this is isn't actually a bug then I'd love to know what I'm doing wrong.

With that said - no matter what play method I used and with what I called it to initiate playback from some intermediate point of the track's duration, it always plays from the beginning.

I have this class taken from the examples (give or take):

```
class AudioEngine {
    
    // Declare your nodes as instance variables
    var player: AKPlayer!
    var delay: AKDelay!
    var reverb: AKReverb!
    var file: AKAudioFile!
    
    func setup() {
        // Set up a player to the loop the file's playback
        player = AKPlayer(audioFile: file)
        player.isLooping = true
        player.prepare()
        
        // Next we'll connect the audio player to a delay effect
        delay = AKDelay(player)
        
        // Set the parameters of the delay here
        delay.time = 0.1 // seconds
        delay.feedback = 0.8 // Normalized Value 0 - 1
        delay.dryWetMix = 0.2 // Normalized Value 0 - 1
        
        // Continue adding more nodes as you wish, for example, reverb:
        reverb = AKReverb(delay)
        reverb.loadFactoryPreset(.cathedral)
        
        AudioKit.output = reverb
        do {
            try AudioKit.start()
        } catch {
            AKLog("AudioKit did not start!")
        }
    }
}
```

I then instantiate the audioEngine member of my view controller with a file:
```
audioEngine.file = try? AKAudioFile(forReading: inputVideoURL)
audioEngine.setup()
```

And then call `audioPlayer.play(from: 1)` (for example. I've tried plenty of different ways of doing this). I have not seen this use case anywhere in the repository or on StackOverflow so I have no actual reference unfortunately and so I'm suspecting this may be an actual issue on the framework's side.

Looking forward to your feedback.

**Comment by ryanfrancesconi** [comment]
I don't see an immediate problem with that code and i have verified here that play(from: 1) does play from 1. What it sounds like is that you aren't using the current development build. In the first AKPlayer it would play from loop.start if isLooping is enabled. This was fixed in the latest merge a few days ago. If you still have an issue and you are using the latest dev build, please post a complete project if you don't mind.

**Comment by ryanfrancesconi** [comment]
you can verify the problem i mention by setting isLooping = false. Also, you don't need to use player.prepare()

**Comment by ryanfrancesconi** [comment]
You can manage the loop on your end if you can't get the dev build to work - though I'd recommend just doing that. All you need to do is use the completionHandler then tell it to play again (for looping)

**Comment by adarhef** [comment]
Thanks for the tip Ryan. Unfortunately though the handler isn't called. I made sure isLooping is false and have no called .stop() on the player like the documentation instructed.

If you can't confirm this or shed light here I may have another go at embedding the framework instead.

**Comment by ryanfrancesconi** [comment]
please post a project that displays this. regardless, you'll need to learn how to use frameworks if there is any fix needed. I don't understand why you can't use the develop branch build?

**Comment by adarhef** [comment]
Every way of embedding the dev branch build (even including from source) was met with compilation issues I was not able to resolve, following the instructions in the repo.
I can’t afford to spend more time on this unfortunately. Hopefully when I get back to it I’ll have better luck. 
Thank you for your time so far.
