### ISSUE TITLE
AKMIDIEvent.swift force unwrap causing crash

### ISSUE THREAD

**Issue by robtize** [AudioKit/AudioKit#1282]
AKMIDIEvent.swift line 166

internalData = Array(internalData.prefix(Int(length!)))

when playing a lot of notes in a sequencer this force unrwap causes a crash sometimes

**Comment by aure** [comment]
This code is not in the most recent version of AudioKit.  I think Jeff fixed it on Feb 1st but didn't make the pull request until recently, so its on the develop branch:

https://github.com/AudioKit/AudioKit/commit/80a28e147d99490d7867e0cad178a81b2eb864d3#diff-f4024105244928ba6cd6889b7a204cd2
