### ISSUE TITLE
AKAppleSampler gets corrupted by an audio route change

### ISSUE THREAD

**Issue by teroparvinen** [AudioKit/AudioKit#1283]
When the audio session route changes (the iOS device is plugged into an external sound interface, headphones are connected, you start capturing a video on a mac using Quicktime...) `AKSampler`s start producing distorted audio.

This time I'm able to bring a solution to the table as well instead of just problems :) .

Registering for audio route changes is simple and doesn't require anything from the basic app flow like the delegate or view controllers. Just do:

    NotificationCenter.default.addObserver(self, selector: #selector(routeChanged), name: .AVAudioSessionRouteChange, object: AVAudioSession.sharedInstance())

Define the event handler:

	@objc func routeChanged(_ notification: Notification) {
		print("Audio route changed")
		
		AudioKit.stop() // Note 1

		do {
			try sampler.loadEXS24(yourSounds) // Note 2
		} catch  {
			print("could not load samples")
		}

		AudioKit.start()
	}

Note 1: Sometimes stopping and starting AudioKit is not necessary. I suspect that this has something to do with sampling rates and bit rates, but I didn't investigate further, because I needed to support the stricter case anyway

Note 2: Samplers need to reload. AudioKit could implement route tracking in the main singleton, register all samplers and do this automatically to work properly out of the box.

**Comment by aure** [comment]
I don't think that we can keep track of what the user needs to reload in Note 2. What we could do is run a callback that the user needs to define.  Something like 

```
routeChangedCallback: AKCallback = { 
	do {
		try sampler.loadEXS24(yourSounds) // Note 2
	} catch  {
		print("could not load samples")
	}
}
```
What do you think?
