### ISSUE TITLE
xCode can't import AudioKit module in Swift 4.1

### ISSUE THREAD

**Issue by yarivadam** [AudioKit/AudioKit#1287]
Hi,

I'm getting a compile error in XCode since the update to XCode 9.3(9E145): 
ViewController.swift:11:8: Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1: [my project]/Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/arm64.swiftmodule

I installed AudioKit using cocoa pods. pod update did not resolve this issue. my Podfile includes AudioKit using: 
pod 'AudioKit', '~> 4.1'

Any updates coming soon? anyone know how to resolve this?

Thanks!

**Comment by megastep** [comment]
We should have version 4.2 out in the coming days, that will include binaries that work with Xcode 9.3 and Swift 4.1.
