### ISSUE TITLE
 Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by Ged2323** [AudioKit/AudioKit#1288]
Hi,
I have updated to Xcode 9.3 and Swift 4.1 and using AudioKit 4.1.
Though I am getting this error when building.

![screen_shot_2018-04-02_at_8_25_49_am](https://user-images.githubusercontent.com/5620610/38178140-90d68698-364f-11e8-8226-e6fb41289ca1.png)
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1
How do you update the modules to Swift 4.1?

Thanks in advance for your help.

**Comment by megastep** [comment]
The frameworks need to be recompiled with the new Xcode. We actually have a new build coming out soon just for this (version 4.2), so just hold on a little bit longer...

**Comment by Ged2323** [comment]
Thank you for such a quick reply. You guys rock!!
