### ISSUE TITLE
Issue with Xcode 9.3 and following releases

### ISSUE THREAD

**Issue by bernikowich-cedoni** [AudioKit/AudioKit#1289]
Hello.
Looks like framework is broken on Swift 4.1 till release AudioKit 4.2. Can you please explain how can I use develop branch with Cocoapods for this period? This question will be actual each Swift release. Thanks in advance.

**Comment by aure** [comment]
This has been covered in StackOverflow.

**Comment by yarivadam** [comment]
I've tried to do the same using:
pod 'AudioKit', :git => 'https://github.com/audiokit/AudioKit.git', :branch => 'develop'
in my Podfile, but I get an empty directory under /Pods/AudioKit. It only contains the License and Readme files.

**Comment by megastep** [comment]
It's not that simple, the pod depends on built binaries we upload on GitHub. We don't have them up for the other branches.

**Comment by yarivadam** [comment]
Ok, got it. I'll eagerly wait for the release, since my code can't compile without it, so I'm stuck in the meantime.
I realize this isn't easy - I appreciate the hard work your putting into this library!

**Comment by bernikowich-cedoni** [comment]
@yarivadam you can build framework yourself from develop branch, but I prefer to use Xcode 9.2 for these few days.
