### ISSUE TITLE
AKRhodesPiano error (crush) on AudioKit v4.2

### ISSUE THREAD

**Issue by dodiku** [AudioKit/AudioKit#1290]
I'm using AudioKit version 4.2 and I receive this error after installing my app on my phone (iPhone X) - ![Screenshot of the error](https://i.stack.imgur.com/QiJ8b.jpg)

The error is thrown after the app is compiled and installed (after the app is being opened on the device).

This is the line that I'm using:

```swift
let pianoNote = AKRhodesPiano() // error
```

When I change this line to a different instrument, for example -

```swift
let pianoNote = AKPluckedString() // works good!
```

**Comment by megastep** [comment]
I bet this is related to changes to the STK code in 4.2 (it's probably failing to load wave files) - I may get around to fixing those later today for 4.2.1.

**Comment by dodiku** [comment]
Thanks!
Looking forward to it!

Is this going to be an official (production) release?

**Comment by megastep** [comment]
Yeah that would be a quick official release to address issues in 4.2.

**Comment by megastep** [comment]
This is actually my fault with incorrect use of `[NSData dataWithBytesNoCopy:]`. Easy to fix though.

**Comment by megastep** [comment]
I think it should be fixed in develop right now. Didn't crash in my test project.
