### ISSUE TITLE
Error installing version 4.2 using Cocoapods

### ISSUE THREAD

**Issue by yarivadam** [AudioKit/AudioKit#1292]
Hi,
I've tried to install the latest version by running 'pod update', and I get the following error:

[!] Error installing AudioKit
[!] /usr/bin/curl -f -L -o /var/folders/8k/9rrx9hzd1vn2frx0dzcny4ww0000gp/T/d20180403-23674-1xxak9n/file.zip http://github.com/audiokit/AudioKit/releases/download/v4.2/AudioKit.framework.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   612    0   612    0     0    384      0 --:--:--  0:00:01 --:--:--  2193
  1  135M    1 1393k    0     0   4332      0  9:07:09  0:05:29  9:01:40     0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

[!] 'AudioKit' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.

My Podfile includes:

pod 'AudioKit', '~> 4.1'

So first, as requested by Cocoapods, I'm notifying you of the non-encrypted protocol issue. And also, how do I install the latest version correctly?

Thanks!

**Comment by aure** [comment]
We had to switch to http instead of https because it was failing with https, we hypothesize because of a problem with github hosting connection to the Cocoapod central server.  @megastep and I worked on it for many hours. Hopefully it will be right for 4.2.1 which should be out shortly since it addresses a few other issues as well.  So, since we're on it I'll close the issue.

**Comment by yarivadam** [comment]
thanks for the quick response, and thanks for your hard work!
I was able to install by removing the pod and adding it back again - just FYI.
