### ISSUE TITLE
AudioKit library framework contains `_main` symbol

### ISSUE THREAD

**Issue by tengyifei** [AudioKit/AudioKit#1297]
It's declared in https://github.com/AudioKit/AudioKit/blob/cdb87c40d43171d988807614954a6bdf52bd2c3b/AudioKit/Core/Sporth/sporth.c#L32
I don't think it's relevant to the functioning of the library as a whole; nonetheless, it gets linked into the static framework.

As such, if the `-all_load` linker flag is used when building the application, this will result in a linker error since the sporth main function conflicts with the application's main. Using `-all_load` is sometimes necessary to work with specific C/C++ libraries (AudioKit's own documentation also suggests using it in one case). Perhaps we can remove the conflicting definition?

**Comment by megastep** [comment]
That's odd, I'm pretty sure I had explicitly unchecked that file from compilation in the framework. Actually at least on iOS it still is. Are you using another platform?

**Comment by tengyifei** [comment]
Ah gotcha. I'm using the macOS build. Maybe that's why :)

**Comment by megastep** [comment]
Actually you know what, I believe the real culprit is actually in `md5.c`. I think something got messed up when the code was reorganized to that Core directory.

**Comment by megastep** [comment]
But you're right for macOS the file was checked!

**Comment by tengyifei** [comment]
You're right there's also a main function in `md5.c`. Xcode was only able to report the first conflict though, which it did say `sporth.o`.

**Comment by megastep** [comment]
Fixed in the develop branch, will be in the next build. The mention in `md5.c` actually doesn't really get compiled unless the TEST macro is defined. So the code is there but not actually at fault.
