### ISSUE TITLE
Memory leak in AudioKit.AKMicrophoneTracker when calling from swift?

### ISSUE THREAD

**Issue by michellevey** [AudioKit/AudioKit#1298]
When I look at the memory graph of my project, I am leaking a bunch of malloc'ed blocks every time I create a AudioKit.AKMicrophoneTracker, AudioKit.AKMicrophoneTracker.__allocating_init() -> AudioKit.AKMicrophoneTracker. I can walk through my code and see the tracker get created and destroyed, so I know I'm not just leaking the whole tracker.

Has anyone else seen this? Any known solutions?

**Comment by aure** [comment]
How big is this memory leak?  I don't know if its a big deal because the microphone tracker is something that is usually used once and stays on during the lifetime of the app. You say you leak "a bunch" every time you create a tracker. Why are you creating more than one?

**Comment by michellevey** [comment]
I didn't write the code,  just in charge of tracking down leaks. Creating a singleton tracker would minimize the issue so I will look into it. 
I'm seeing about 20 or so blocks get leaked ranging from 147456 bytes - 80 bytes. 
The issue is also the noise in the memory tracking console. 
You might be able to recreate this issue by creating a basic app with two views/controllers and create a tracker on ViewDidAppear of one . Then just navigate back/forth and drop into "Debug Memory Graph" to see leaks.

**Comment by aure** [comment]
I'll need more information to act on this.  In general the microphone tracker is just a one time add on in a project.  I'd recommend using AKFrequencyTracker and AKAmplitudeTracker in the context of an audio graph for more complicated use cases.
