### ISSUE TITLE
iOS 9 Error AKBooster

### ISSUE THREAD

**Issue by GrantJEmerson** [AudioKit/AudioKit#1299]
I am getting the following error when downloading my Audio Kit application onto my iPad 2: AURemoteIO::IOThread (7): EXC_BAD_ACCESS (code=1, address=0x0). However, when I change the AudioKit.output to modulin, it works. This would lead to me to beleive that the problem lies in the AKBooster applied to the voltageControlledAmplifer. Is there any specific order of AudioKit configuration that I am not following?

`

    public var modulin: AKOperationGenerator!
    public var voltageControlledAmplifier: AKBooster!
    public var recordingNode: AKMixer!

    private var recorder: AKNodeRecorder!
    private var player: AKAudioPlayer?
    
    private let midi = AKMIDI()
    public var midiChannelIn: MIDIChannel = MIDIChannel(UserDefaults.midiChannel)
    private var currentlySelectedMidiNotes = Set<MIDINoteNumber>()
    
    // MARK: Init
    
    init() {
        setUpAudioKit()
        setUpMidi()
    }
    
    // MARK: Private Functions
    
    private func setUpAudioKit() {
        modulin = AKOperationGenerator.modulin()
        modulin.start()
        voltageControlledAmplifier = AKBooster(modulin, gain: 1)
        
        AKSettings.playbackWhileMuted = true
        AKSettings.defaultToSpeaker = true
        AKSettings.bufferLength = AKSettings.BufferLength(rawValue: UserDefaults.preferredBufferSize)!
        AKSettings.sampleRate = UserDefaults.preferredSampleRate
        
        do {
            try AKSettings.setSession(category: .playAndRecord, with: [.defaultToSpeaker, .allowBluetooth, .mixWithOthers])
            
            recordingNode = AKMixer(voltageControlledAmplifier)
            // Recording Node and AudioKit Output must be the same
            AudioKit.output = recordingNode
            recorder = try AKNodeRecorder(node: recordingNode)
            
            try AudioKit.start()
        } catch {
            print("AudioKit failed to set itself up.")
        }
 }`
Thanks for all your help.

**Comment by aure** [comment]
Until this is isolated as a fixable issue in AudioKit and not an implementation thing, I'm going to close this issue and let it play out on https://stackoverflow.com/questions/49680078/ios-9-error-akbooster

**Comment by GrantJEmerson** [comment]
Have you found anything else on this issue lately? It's still resulting in an error for me on the iOS 9.3 simulator in Xcode.
