### ISSUE TITLE
Installation without framework.bundle

### ISSUE THREAD

**Issue by nswoboda** [AudioKit/AudioKit#1302]
Thanks to the AudioKit Team! Audiokit's tools and implementation are flawless! 

All Installation documentation points to Folder-> Frameworks-> Framework.bundle 
For Versions 4+ there aren't any Framework.bundle file in any of the AudioKit folders ?
In the end I intend to manipulate a framework.sh file to allow for AudioKit with iOS 11 anyway, 
but any extra documentation would be extremely helpful for finding the .bundle file.

* Creating a framework from the .sh file seams easy enough but is the point to create your own 
.bundle from it or install with that .sh file?
* Starting from the AudioKit project file is not an option for me and neither are cocoappds or carthage.

**Comment by aure** [comment]
Can you ask your question on StackOverflow, because it doesn't seem to pinpoint an actionable issue.
