### ISSUE TITLE
AKSampler with sfz

### ISSUE THREAD

**Issue by jbmaxwell** [AudioKit/AudioKit#1307]
I noticed a few issues loading sfz files from "the wild", and made a few tweaks to get them loading: 

    open func loadUsingSfzFile(folderPath: String, sfzFileName: String) {
        let isRoland = true

        /* Common <group> opcodes (Not yet handled?) */
        var ampeg_attack: Float = 0.04
        var ampeg_release: Float = 0.5
        var amp_veltrack: Float = 75.0
        
        /* Common <region> opcodes */
        var lokey: Int32 = 0
        var hikey: Int32 = 127
        var pitch: Int32 = 60
        var lovel: Int32 = 0
        var hivel: Int32 = 127
        var sample: String = ""
        var loopmode: String = ""
        var loopstart: Float32 = 0
        var loopend: Float32 = 0

        let baseURL = URL(fileURLWithPath: folderPath)
        let sfzURL = baseURL.appendingPathComponent(sfzFileName)
        do {
            let data = try String(contentsOf: sfzURL, encoding: .ascii)
            let splitSet = Set("<")
            let lines = data.splitBefore(isSplit: splitSet.contains).map(String.init).map { $0.replacingOccurrences(of: "\\", with: "/") }
            
            for line in lines {
                let trimmed = String(line.trimmingCharacters(in: .whitespacesAndNewlines))
                if trimmed == "" || trimmed.hasPrefix("//") {
                    // ignore blank lines and comment lines
                    continue
                }
                if trimmed.hasPrefix("<group>") {
                    // parse a <group> line
                    lokey = 0
                    hikey = 127
                    pitch = 60
                    lovel = 0
                    hivel = 127
                    for part in trimmed.dropFirst(7).components(separatedBy: .whitespacesAndNewlines) {
                        if part.hasPrefix("key") {
                            let value = part.components(separatedBy: "=")[1]
                            let midiNote = noteStringToMIDINote(value, isRoland: isRoland)
                            pitch = Int32(midiNote)!
                            lokey = pitch
                            hikey = pitch
                        } else if part.hasPrefix("lokey") {
                            let value = part.components(separatedBy: "=")[1]
                            let midiNote = noteStringToMIDINote(value, isRoland: isRoland)
                            lokey = Int32(midiNote)!
                        } else if part.hasPrefix("hikey") {
                            let value = part.components(separatedBy: "=")[1]
                            let midiNote = noteStringToMIDINote(value, isRoland: isRoland)
                            hikey = Int32(midiNote)!
                        } else if part.hasPrefix("pitch_keycenter") {
                            let value = part.components(separatedBy: "=")[1]
                            let midiNote = noteStringToMIDINote(value, isRoland: isRoland)
                            pitch = Int32(midiNote)!
                        } else if part.hasPrefix("lovel") {
                            lovel = Int32(part.components(separatedBy: "=")[1])!
                        } else if part.hasPrefix("hivel") {
                            hivel = Int32(part.components(separatedBy: "=")[1])!
                        } else if part.hasPrefix("ampeg_attack") {
                            ampeg_attack = Float(part.components(separatedBy: "=")[1])!
                        } else if part.hasPrefix("ampeg_release") {
                            ampeg_release = Float(part.components(separatedBy: "=")[1])!
                        } else if part.hasPrefix("amp_veltrack") {
                            amp_veltrack = Float(part.components(separatedBy: "=")[1])!
                        } else if part.hasPrefix("loop_mode") {
                            loopmode = part.components(separatedBy: "=")[1]
                        }
                    }
                }
                if trimmed.hasPrefix("<region>") {
                    // parse a <region> line
                    lovel = 0
                    hivel = 127
                    sample = ""
                    loopmode = ""
                    loopstart = 0
                    loopend = 0
                    for part in trimmed.dropFirst(8).components(separatedBy: .whitespacesAndNewlines) {
                        print("part: \(part)")
                        if part.hasPrefix("key") {
                            let value = part.components(separatedBy: "=")[1]
                            let midiNote = noteStringToMIDINote(value, isRoland: isRoland)
                            pitch = Int32(midiNote)!
                            lokey = pitch
                            hikey = pitch
                        } else if part.hasPrefix("lokey") {
                            let value = part.components(separatedBy: "=")[1]
                            let midiNote = noteStringToMIDINote(value, isRoland: isRoland)
                            lokey = Int32(midiNote)!
                        } else if part.hasPrefix("hikey") {
                            let value = part.components(separatedBy: "=")[1]
                            let midiNote = noteStringToMIDINote(value, isRoland: isRoland)
                            hikey = Int32(midiNote)!
                        } else if part.hasPrefix("pitch_keycenter") {
                            let value = part.components(separatedBy: "=")[1]
                            let midiNote = noteStringToMIDINote(value, isRoland: isRoland)
                            pitch = Int32(midiNote)!
                        } else if part.hasPrefix("lovel") {
                            lovel = Int32(part.components(separatedBy: "=")[1])!
                        } else if part.hasPrefix("hivel") {
                            hivel = Int32(part.components(separatedBy: "=")[1])!
                        } else if part.hasPrefix("loop_mode") {
                            loopmode = part.components(separatedBy: "=")[1]
                        } else if part.hasPrefix("loop_start") {
                            loopstart = Float32(part.components(separatedBy: "=")[1])!
                        } else if part.hasPrefix("loop_end") {
                            loopend = Float32(part.components(separatedBy: "=")[1])!
                        } else if part.hasPrefix("sample") || sample.hasPrefix("sample") {
                            if !(part.contains(".") || sample.contains(".")) {
                                if sample.count == 0 {
                                    sample = part
                                } else {
                                    sample = "\(sample) \(part)"
                                }
                                continue
                            }
                            sample = "\(sample) \(part)"
                            sample = sample.components(separatedBy: "sample=")[1]
                        }
                    }

                    let noteFreq = Float(AKPolyphonicNode.tuningTable.frequency(forNoteNumber: MIDINoteNumber(pitch)))
                    print("load \(pitch) \(noteFreq) Hz range \(lokey)-\(hikey) vel \(lovel)-\(hivel) \(sample)")

                    let sd = AKSampleDescriptor(noteNumber: pitch,
                                                noteHz: noteFreq,
                                                min_note: lokey,
                                                max_note: hikey,
                                                min_vel: lovel,
                                                max_vel: hivel,
                                                bLoop: loopmode != "",
                                                fLoopStart: loopstart,
                                                fLoopEnd: loopend,
                                                fStart: 0.0,
                                                fEnd: 0.0)
                    let sampleFileURL = baseURL.appendingPathComponent(sample)
                    if sample.hasSuffix(".wv") {
                        loadCompressedSampleFile(sfd: AKSampleFileDescriptor(sd: sd, path: sampleFileURL.path))
                    } else {
                        if sample.hasSuffix(".aif") || sample.hasSuffix(".wav") {
                            let compressedFileURL = baseURL.appendingPathComponent(String(sample.dropLast(4) + ".wv"))
                            let fileMgr = FileManager.default
                            if fileMgr.fileExists(atPath: compressedFileURL.path) {
                                loadCompressedSampleFile(sfd: AKSampleFileDescriptor(sd: sd, path: compressedFileURL.path))
                            } else {
                                let sampleFile = try AKAudioFile(forReading: sampleFileURL)
                                loadAKAudioFile(sd: sd, file: sampleFile)
                            }
                        }
                    }
                }
            }
        } catch {
            print(error)
        }

        buildKeyMap()
    }

Some of the parameters in the "group" handler are not commonly used in groups, though it seems that the exs converter puts them there, so I left those and added the more common "group" ones from the spec. With the above changes I managed to get this sfz loading: [http://freepats.zenvoid.org/Piano/acoustic-grand-piano.html#KawaiUpright](url), but playback is choppy. It sounds like it's cutting off any sustaining notes as soon as a new note is articulated. (Just to note, it is polyphonic, so it's not some voice-stealing thing.)

**Comment by aure** [comment]
The new AKSampler is Shane's (@getdunne) baby, and I know he knows that sfz support is not complete, but perhaps he can look at this for you.  In the meantime, AKAppleSampler still exists if you want to continue to use that.

**Comment by getdunne** [comment]
Hi JB, thanks for the feedback and especially for improvements to SFZ interpretation. There's potentially a huge amount of work to do there, and any help would by hugely appreciated! I'll have a look at the SFZ file you linked to, and see if I can figure out what's going wrong. My first thought is that samples might not be looping correctly, or maybe not at all.

**Comment by jbmaxwell** [comment]
No problem, glad to help. I also wondered about the loops not playing, but longer notes do seem to speak reasonably well (i.e., they're not cut off). It really seems to be more related to the envelope somehow—it seems to me like new onsets re-articulate everything... As if, in a polyphonic context, there is only one series of envelopes (if that makes sense). But I think I'd have to test with various different types of musical material, to better understand the problem.

**Comment by getdunne** [comment]
JB can you please post the source for your String.splitBefore() function? I can't compile your code without it.

**Comment by jbmaxwell** [comment]
Sorry about that!

    extension Collection {

        func splitBefore(isSplit: (Iterator.Element) throws -> Bool) rethrows -> [SubSequence] {
            var p = self.startIndex
            var result:[SubSequence] = try self.indices.compactMap {
                i in
                guard try isSplit(self[i]) else {
                    return nil
                }
                defer {
                    p = self.index(i, offsetBy: 0)
                }
                return self[p..<i]
            }
            if p != self.endIndex {
                result.append(suffix(from: p))
            }
            return result
        }
    }

**Comment by jbmaxwell** [comment]
internal func noteStringToMIDINote(_ noteString: String, isRoland: Bool?) -> String {
        var midiNote = 60
        let chars = "-0123456789"
        let pitch = noteString.trimmingCharacters(in: CharacterSet(charactersIn: chars))
        let octave = Int(noteString.trimmingCharacters(in: CharacterSet(charactersIn: chars).inverted))
        var offset = 1
        if let cFlag = isRoland {
            if cFlag == false { offset = 2 }
        }
        if pitch == "" {
            return noteString
        }
        assert(octave != nil, "ERROR: noteString must contain a numeric element (e.g., octave number)")
        let names = ["c", "c#", "d", "d#", "e", "f", "f#", "g", "g#", "a", "a#", "b"]
        let pc = names.map { $0.localizedCaseInsensitiveContains(pitch) }.index(of: true)!
        midiNote = pc + ((octave! + offset) * 12)
        return "\(midiNote)"
    }

**Comment by jbmaxwell** [comment]
Yes, I totally understand about the depth of the sfz format—there's definitely a lot that would have to be done for full support.

**Comment by getdunne** [comment]
Thanks @jbmaxwell for sharing your extra code. My code above is now available as part of the AKSamplerDemo for macOS example in the Develop branch of AudioKit.

I'm going to close this GitHub issue, but as we've discussed this is an area for further work. We can use all the help we can get with understanding the SFZ format in terms of syntax/parsing and expectations/requirements for the sampler engine.

**Comment by jbmaxwell** [comment]
Just curious; are you experiencing the choppy playback, or does it sound correct? (I'm wondering if there's some more general problem with my project.)

**Comment by getdunne** [comment]
My playback is fine. Try the AKSamplerDemo example code and see if that works smoothly.

**Comment by jbmaxwell** [comment]
Ah, okay. Good to know. I've had nothing but trouble, so I'm really wondering if there's something wrong elsewhere in the project (AKAppleSampler only plays very quietly from the receiver, regardless of session settings, playback is choppy in AKSampler, etc.). I need to get to the bottom of this... Thanks!
