### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [AudioKit/AudioKit#1309]
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by aure** [comment]
This is not a proper forum for this kind of inquiry.

**Comment by redmusic27** [comment]
Why?

**Comment by aure** [comment]
Because this is not an issue, or problem with AudioKit.  Contact one of us by email, which is easy enough to discover.
