### ISSUE TITLE
AKFlanger/Chorus start() stop() methods do not work

### ISSUE THREAD

**Issue by temkich** [AudioKit/AudioKit#1315]
If I create for example Delay effect, then the start / stop methods work, but in some nodes, for example
AKPitchShifter or AKChowningReverb or AKAutoWah or AKFlanger etc.. it does not work.
How to disable these effects correctly? do you assign zero values?

**Comment by aure** [comment]
I believe this is fixed in develop.

**Comment by temkich** [comment]
Thanks a lot, it's cool, now the AKPitchShifter  stops when I want. And what about AKFlanger? It does not respond to the start/stop.

**Comment by getdunne** [comment]
Fixed in develop.
