### ISSUE TITLE
Crash when setting AudioKit output node on iPhone 5s

### ISSUE THREAD

**Issue by yarivadam** [AudioKit/AudioKit#1316]
Hi,

I get a consistent crash whenever I set AudioKit output to a mixer node. The crash happens on an iPhone 5s running iOS 10.3.3, but NOT on an iPhone 7 running iOS 11.3.

The code I'm running (setting up a recording view):

```
mic = AKMicrophone()
mic.stop()
fft = AKFFTTap.init(mic)
micMixer = AKMixer(mic)
micBooster = AKBooster(micMixer)
micBooster.gain = 0
do {
            recorder = try AKNodeRecorder(node: micMixer)
            
            if let file = recorder.audioFile {
                player = try AKAudioPlayer(file: file)
                player.looping = false
                player.completionHandler = playingEnded
            }
            mainMixer = AKMixer(player, micBooster)
            AudioKit.output = mainMixer //THIS IS WHERE IT CRASHES!
        }
        catch {
            //debug prints here don't get printed
            throw error
        }
```

The catch block is never called, an error is not thrown.

Crash details in logs:

ERROR:    [0x1b12c0b40] >avae> AVAudioIONodeImpl.mm:466: EnableBus_block_invoke: error -10849
*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10849'

Any help or information would be appreciated!

**Comment by aure** [comment]
This is not an actionable issue because it is device independent and doesn't come with a sample project. I think you might have better luck posting it to StackOverflow. I can only guess it has something to do with sample rate on the older phone's mic. Sorry man.

**Comment by yarivadam** [comment]
OK, Thanks. I'll try SO.
