### ISSUE TITLE
After building the frameworks for the different platforms, I was unable to import the libraries after dragging-and-dropping the frameworks into the Xcode MacOS project

### ISSUE THREAD

**Issue by shyamalschandra** [AudioKit/AudioKit#1317]
The Xcode project for MacOS AppKit says it cannot find the AudioKit and AudioKitUI frameworks even though they are in my Frameworks folder.  Do I have to go the carthage or cocoapod route?

**Comment by aure** [comment]
No, you're just doing something wrong.  Ask this question on StackOverflow please.
