### ISSUE TITLE
AKOscillator with zero amplitude produces a short high-pitched sound

### ISSUE THREAD

**Issue by simonpierreroy** [AudioKit/AudioKit#1321]
I was trying to produce a sine wave sound (AKOscillator) with a small amplitude (0.004) and I found that a short high-pitched sound was emitted during the first 0.5 seconds. The same sound  is emitted even if the amplitude is set to 0.

(AudioKit 4.2.2 and Xcode 9.3)

Here is a photo and a recording when the amplitude is set to 0.004 (code is below).

```
class ViewController: UIViewController {
    
    let oscillator = AKOscillator()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.oscillator.frequency = 500
        self.oscillator.amplitude = 0.004
        AudioKit.output = self.oscillator
        try! AudioKit.start()
        self.oscillator.start()
    }
}
```
![img_3515](https://user-images.githubusercontent.com/6798958/38572780-15c7fe0e-3cc2-11e8-856c-4b1c1015eb54.jpg)
[New Recording.m4a.zip](https://github.com/AudioKit/AudioKit/files/1895653/New.Recording.m4a.zip)

**Comment by aure** [comment]
How bizarre. I have some idea why this might be, but in the mean time, can you see if it happens if you don't do oscillator.start() immediately after AudioKit.start and instead wait for user interaction.

**Comment by simonpierreroy** [comment]
It works fine with the user interaction (when AudioKit it started before) only if I never change the AudioKit.output. Code below.

```
class ViewController: UIViewController {
    
    let oscillator = AKOscillator()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.oscillator.frequency = 500
        self.oscillator.amplitude = 0.004
        AudioKit.output = self.oscillator
        try! AudioKit.start()
    }
    
    @IBAction func stopStart() {
        if self.oscillator.isStarted {
            self.oscillator.stop()
        } else {
            self.oscillator.start()
        }
    }
}
```

I manage to reproduce the problem systematically, I suffice to change the AudioKit.output before starting the node. See the code below (do a start/stop/start). (In my real app I would like to switch the output between an AKPlayer and an AKOscillator upon user interaction.)

Is there something I can do the help fixing it?
 
```
 class ViewController: UIViewController {
    
    var currentOsc: AKOscillator? = nil
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        AudioKit.output = AKOscillator()
        try! AudioKit.start()
    }
    
    @IBAction func start() {
        let osc = AKOscillator()
        self.currentOsc = osc
        osc.amplitude = 0.004
        osc.frequency = 500
        AudioKit.output = osc
        osc.start()
    }
    
    @IBAction func stop() {
        self.currentOsc?.stop()
    }
} 
```

**Comment by aure** [comment]
It’s worth fixing but I don’t think it should hold you up.

**Comment by simonpierreroy** [comment]
Good, thank you :)

**Comment by aure** [comment]
For your app, you might want to instead mix the two outputs and just change the mix rather than changing the output.  It'll be smoother, less prone to issues, and neither thing is a cpu hog.

**Comment by aure** [comment]
It turns out this is not a bug at all.  What you're doing is instantiating the oscillator with default values, and then changing those values at time 0.  But, the ramp time for that change is still at the default of 0.02 seconds or so, so it takes some time to get to your new values.  Your options are to set the rampTime to 0 or set your initial values in the initializer.

**Comment by simonpierreroy** [comment]
Thank you so much!
