### ISSUE TITLE
After install of AudioKit 4.2.3 via Cocoapods: Receiving Dsymutil Warnings when build configuration is set to release. 

### ISSUE THREAD

**Issue by bmgire** [AudioKit/AudioKit#1325]
After installing AudioKit 4.2.3 via Cocoapods, everything worked fine excepted I receive several Dsymutil Warnings when my build configuration is set to Release but not when my build is set to Debug.

Some googling on the error message below suggests the static libraries need to be recompiled without Debug mode enabled for the distributed libraries to work correctly when Xcode projects are in release mode. I wanted to bring this to your attention. Note: I've removed my folder names from the paths in the warning messages. 

The warnings:

"while processing /.../Pods/AudioKit/iOS/AudioKit.framework/AudioKit(MIDIPacketList+SequenceType.o):
warning: /var/folders/g3/3gw8_98n3d7_qkzthq9tx6t00000gn/C/org.llvm.clang.megastep/ModuleCache/2FIVBIVNU84RC/CoreMIDI-2OV5TK5CIMZXQ.pcm: No such file or directory
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.

while processing /.../Pods/AudioKit/iOS/AudioKit.framework/AudioKit(AKTuningTable+Scala.o):
warning: /var/folders/g3/3gw8_98n3d7_qkzthq9tx6t00000gn/C/org.llvm.clang.megastep/ModuleCache/2FIVBIVNU84RC/ObjectiveC-1R06XOY9T4FIM.pcm: No such file or directory

while processing /.../Pods/AudioKit/iOS/AudioKit.framework/AudioKit(AKTuningTable+Scala.o):
warning: /var/folders/g3/3gw8_98n3d7_qkzthq9tx6t00000gn/C/org.llvm.clang.megastep/ModuleCache/2FIVBIVNU84RC/Foundation-3DFYNEBRQSXST.pcm: No such file or directory"

I hope this is the right place to be positing this issue. I absolutely love AudioKit!!!!!

**Comment by megastep** [comment]
Well it sucks that it still happening. I don't really want to disable debug symbols altogether as it would make debugging more difficult for our users. I had disabled the Clang setting producing this warning supposedly, so I'm not sure why this keeps happening.

**Comment by aure** [comment]
We've been getting these warnings even when we submit to cocoapods, I guess we just hoped it wouldn't rear its head for the user. 4.2.4 will probably drop soon and we'll have another opportunity to address this.

**Comment by ingconti** [comment]
similar for me. it works fine on dev device, but cannot submit to apple Store.

**Comment by megastep** [comment]
These are just warnings and should not prevent you from submitting to the App Store.

**Comment by aure** [comment]
Next release is out so please try 4.2.4. Closing the issue for now.  Reopen if needed.

**Comment by aure** [comment]
4.2.4 is having some issues with cocoapods, hopefully resolved soon.
