### ISSUE TITLE
CAF file size is too big 

### ISSUE THREAD

**Issue by ashusath** [AudioKit/AudioKit#1333]
I am using AudioKit's AKNodeRecorder for recording audio.

While recording audio it generates CAF file in a temp directory. if we save it with exportAsynchronously it creates a new file with m4a extension in document directory.

The CAF file generates in temp directory is too big in size.
1 sec of audio takes
1 sec = 360000 bytes = 0.36 MB
Disk space 

while after exporting m4a file takes 
1 sec = 32000 bytes = 0.032 MB
Disk space 

The m4a space is good for recording an audio. but the CAF file size is too big for long time recording.

I have to record 2.5 hrs of audio at one time, which will generate 3.6 GB of CAF file

Can we use less disk space while recording?

**Comment by aure** [comment]
This is not an issue with AudioKit, its an implementation challenge that you have.  You should be posting questions like this to StackOverflow so that many more programmers from various walks of life can help you address the problems.

**Comment by ashusath** [comment]
Thanks for the response. 
I thought this was the issue with AudioKit implementation because while recording with AVAudioRecorder it does not generate temporary CAF file.
It creates an m4a file which is compact in size anyways I will ask this question on StackOverflow.
