### ISSUE TITLE
AKNodeOutputPlot not working with AKMicrophone anymore (including example projects)

### ISSUE THREAD

**Issue by ryanthon** [AudioKit/AudioKit#1334]
Hi,

I recently tried updating AudioKit to v4.2, and have noticed that on any version since 4.1, I can no longer get AKNodeOuptutPlot to plot AKMicrophone input. I have tried building the frameworks myself, and running the "Recorder" example project, and saw that it doesn't work anymore either. I saw another issue on it marked as "Closed", but it doesn't seem to be fixed?

My usage of AKNodeOutputPlot is essentially the same as in the example project:

```
        let microphone = AKMicrophone()
        let micMixer = AKMixer(microphone)
        let micBooster = AKBooster(micMixer)

        ....

        AKAudioFile.cleanTempDirectory()
        AKSettings.bufferLength = .medium
        try? AKSettings.setSession(category: .playAndRecord, with: .defaultToSpeaker)
        
        AKSettings.defaultToSpeaker = true
        self.micBooster.gain = 0
        self.recorder = try? AKNodeRecorder(node: micMixer)
        
        guard let file = recorder?.audioFile, let player = try? AKAudioPlayer(file: file) else {
            initializationError()
            return
        }
        
        self.player = player
        
        let moogLadder = AKMoogLadder(player)
        moogLadder.cutoffFrequency = 1500
        output = AKMixer(moogLadder, micBooster)
        AudioKit.output = output
        AudioKit.start()

       .....

        self.audioFile = file
        
        do {
            try? recorder.record()
            outputPlot.node = microphone
        } catch {}
```

Sound definitely gets recorded to the output file, and I can play it back just fine, but setting the output plot node to the microphone has no effect, and doesn't plot the waveform.
The fix listed in #1042 did not help.

For now, I have still using a pre-4.1 version, which seems to work. However, this means that I can't update my project to Xcode 9.3 without using an AudioKit build that was built with that version. I tried building v4.0.4 with Xcode 9.3, which produced hundreds of errors.

Thanks

**Comment by aure** [comment]
The plots work on HelloWorld, so it has to do with the view life cycle.  But along the way I found some more bugs, so this should be taken care of shortly.

**Comment by aure** [comment]
Recorder example is now fixed.
