### ISSUE TITLE
Installing with CocoaPods gets this error: 'ModulatedDelay.hpp' file not found

### ISSUE THREAD

**Issue by mekeo** [AudioKit/AudioKit#1336]
Installing AudioKit from Cocoa Pods gets this issue:

#import "ModulatedDelay.hpp" ... ModulatedDelay.hpp' file not found

**Comment by aure** [comment]
I can't act on this much information.  Can you provide a project, and perhaps post this to StackOverflow until we are certain what the issue is.

**Comment by mekeo** [comment]
This is the project I'm trying to test: https://github.com/cemolcay/AUSequencer

Just to see an example of Ableton Link implementation from this post: https://audiokitpro.com/integrating-ableton-linkkit-with-audiokit-apps/

Tried several times and always getting this issue: ModulatedDelay.hpp' file not found

Also tried to install in my own project with Cocoa Pods with the same error.

**Comment by aure** [comment]
I think we'll go ahead and make this public and make a couple of other related changes, so I've reopened this issue.

**Comment by aure** [comment]
I thought about this and I'm not sure a change to AudioKit is necessary if you don't import AudioKit.h.

**Comment by ingconti** [comment]
a minor note. I built up form scratch frameworks. My project failed as I had an OLD setting:

"$BUILT_PRODUCTS_DIR/$FRAMEWORKS_FOLDER_PATH/AudioKit.framework/fix-framework.sh"

in runScript (maybe an old requirements?)

**Comment by megastep** [comment]
@ingconti Yes you can remove that script, it is no longer needed with the static frameworks.

**Comment by mekeo** [comment]
@cemolcay Aurelius gave this solution on stackoverflow, for your AUSequencer 
" So, actually I took a look at his example and he's doing an "import AudioKit/AudioKit.h" for no reason apparently, try commenting line 12 of AudioEngine.mm. "
