### ISSUE TITLE
Parameter tree failed

### ISSUE THREAD

**Issue by arduino-man** [AudioKit/AudioKit#1349]
I am having trouble following the simple example that you show on a video on the website:

I am putting this inside viewDidLoad() --

var oscillator = AKOscillator()
        oscillator.amplitude = 0.1
        do {
            try AudioKit.start()
        } catch {
            AKLog("AudioKit did not start!")
        }
        oscillator.start()

And getting the following error: 

AKOscillator.swift:init(waveform:frequency:amplitude:detuningOffset:detuningMultiplier:):175:Parameter Tree Failed
AudioKit.swift:start():229:No output node has been set yet, no processing will happen.
2018-04-29 19:16:44.083166-0600 voiceChanger[3819:79898] [avae] AVAEInternal.h:70:_AVAE_Check: required condition is false: [AVAudioEngineGraph.mm:1208:Initialize: (inputNode != nullptr || outputNode != nullptr)]
ViewController.swift:viewDidLoad():22:AudioKit did not start!

I haven't found anybody having the same error unfortunately.

**Comment by aure** [comment]
This should have been posted to StackOverflow, only use issues once you know for sure the problem is with AudioKit and not your own code.  You forgot to set AudioKit.output = oscillator.

**Comment by arduino-man** [comment]
My apologies

**Comment by aure** [comment]
No worries.
