### ISSUE TITLE
Audikit 4.2 not playing tone but 4.1 working fine.

### ISSUE THREAD

**Issue by Maulik699** [AudioKit/AudioKit#1355]
Hi,

I am using Audiokit in my project and recently i updated my xcode 9.3.
It says i need to update Audiokit as well. But when i updated i need to use try catch to start and stop audio kit. this is fine.

`do{
   try AudioKit.Start()
}catch{}`

But, It is not playing tone.

can you please tell me what is wrong with my code? because it's working in old version but not in latest version.

**Comment by aure** [comment]
Maybe the capital S in start?  In any event, this is very little code to go on, and it is a question for StackOverflow, not for AudioKit issues.

**Comment by Maulik699** [comment]
Not like that,
Let me put my code here

`oscillator = AKFMOscillator()
        oscillator!.amplitude = 0.0   // avoid clicks by ramping up from silence
        oscillator!.baseFrequency = Double(calibration.frequency)
        oscillator!.carrierMultiplier = 1.0
        oscillator!.modulatingMultiplier = HolmesMethod.warbleModulationFrequency / Double(calibration.frequency)
        oscillator!.modulationIndex = HolmesMethod.warbleModulationIndex
        oscillator!.rampTime = HolmesMethod.clickMillis / 1000.0
        
        
        AudioKit.output = panner
        do {
            try AudioKit.start()
        } catch  {
        }
        
        oscillator!.start()
        
        panner = AKPanner(oscillator, pan: calibration.channel == .Right ? 1.0 : -1.0)
        panner?.start()`
