### ISSUE TITLE
[Carthage] AKAppleSampler.loadMelodicSoundFont(): unrecognized selector sent to instance

### ISSUE THREAD

**Issue by DJBen** [AudioKit/AudioKit#1358]
When built with Carthage with only `github "audiokit/AudioKit"` in `Cartfile` and standard installation procedure, it seems the header and / or implementation of this method cannot be found.

**This works fine when built with Cocoapods**

I will attach a minimum demonstration example below shortly.

A minimum working example is here

https://github.com/DJBen/AudioKit-loadSF-demo

**Comment by aure** [comment]
AudioKit no longer supports Carthage.

**Comment by DJBen** [comment]
Good to know. Any reasons to keep the Carthage badges and Carthage installation guide in the README?
