### ISSUE TITLE
All Exceptions breakpoint

### ISSUE THREAD

**Issue by auguststurm** [AudioKit/AudioKit#1364]
If I have an All Exceptions breakpoint set, AudioKit has a strange exception on AKMixer() initialization. Plus, I can turn off the main breakpoint, and can turn on the two sub-breakpoints and AudioKit loads as expected.

Prior to AKMixer(), I am initializing AKMIDI(), and AKSequencer() without any exceptions thrown.

Not sure if this is really an issue, but it is quite strange. And, I really do like adding an All Exceptions in the Breakpoint navigator while developing in Xcode since it helps me locate the source of the problem in my code, versus the result of the problem of my code.

I did test with a fresh Xcode project w/o the all-exception breakpoint, and it loaded AudioKit without issue. Can someone test this out please?

Thank you!

**Comment by aure** [comment]
I think you'd have more luck posting this to StackOverflow.  It is something hard to address, a bit vague.  Can you provide a sample project as well?  I'm willing to do a screen share with you if you like.  I'm sure I'd learn a thing or two about breakpoints from you.
