### ISSUE TITLE
I also have the same problem, the xcode version is 9.0, the cocopods audiokit 4.2 version, and the Module compiled with Swift 4.1 cannot be imported in Swift 4.0: /Users/shaozhike/Desktop/SoundChange/Pods/AudioKit/iOS/AudioKit.framework/ Modules/AudioKit.swiftmodule/arm64.swiftmodule , I should upgrade xcode to 9.3? Originally low version of the audiokit can be used, I have to save the audio to the local when the iphone7s real machine will be a lot of noise, Don't know why, hope you can help me

### ISSUE THREAD

**Issue by jack-xiaobaicai** [AudioKit/AudioKit#1366]
If your issue is implementing AudioKit in your own code, post your problem to [StackOverflow](https://stackoverflow.com/search?q=AudioKit) with the #AudioKit hashtag.

GitHub Issues should only be used for confirmed problems with AudioKit and
well-defined feature requests.

Make sure you know about the common gotcha's outlined in this video:
https://vimeo.com/audiokit/connecting-nodes-part-2

Problems when submitting your app with the framework? First make sure to check your run phases are set up properly, as outlined in this doc:
https://github.com/AudioKit/AudioKit/blob/master/Frameworks/README.md

![2018-05-08 4 57 14](https://user-images.githubusercontent.com/22491353/39747912-3719ac26-52e1-11e8-8ea6-f21f1359d8dc.png)

**Comment by megastep** [comment]
Current versions of AudioKit typically target the current version of Swift in the current Xcode. Upgrade your Xcode if you want to use the compiled binaries for the latest version.
