### ISSUE TITLE
[iOS] [AudioKit.AudioKit startAndReturnError:]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by dddx80** [AudioKit/AudioKit#1368]
Hi,

First of all, thank you for your hard work keeping this great platform open to all and updated!

I've recently started getting the following error after compiling any code with AudioKit frameworks:

`+[AudioKit.AudioKit startAndReturnError:]: unrecognized selector sent to class 0x10051ab20
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[AudioKit.AudioKit startAndReturnError:]: unrecognized selector sent to class 0x10051ab20'`

This applies to even the HelloObjectiveC example included in the repository. I just pulled the latest updates and still getting this on all codes running the following line:

`[AudioKit startAndReturnError:nil];`

If I comment it out, the app doesn't crash but doesn't work as expected. I should mention that my app code has not changed nor have I made any changes to the HelloObjectiveC example codes. They used to work until I just recompiled the frameworks using `PLATFORMS="iOS" ./build_frameworks.sh` as I was getting "compiled with older version of Swift language (4.0) than previous files " error. I did not change anything in the source code before compiling.

Please let me know if you need further information.

Thanks

**Comment by aure** [comment]
Everything builds on my machine and on Travis, so I am thinking you are pointing to an old version of AUdioKit or something.  In any event, I don't think this is an issue with AudioKit and should probably be a question for StackOverflow.

**Comment by aure** [comment]
Right you are, I'll have to fix this.  At first I thought this was not our issue, but it certainly is.

**Comment by aure** [comment]
Add -all_load to the other linker flags in your build settings.  I just pushed this up to the Objective-C HelloWorld project on the develop branch.  Thanks!

**Comment by dddx80** [comment]
Worked! Thanks a lot!
