### ISSUE TITLE
It can't record when I write some codes in AppDelegate in the recorder demo

### ISSUE THREAD

**Issue by a1259667899** [AudioKit/AudioKit#1369]
` func applicationDidBecomeActive(_ application: UIApplication) {
            debugPrint("applicationDidBecomeActive")
            do{
                try AVAudioSession.sharedInstance().setActive(true)
                try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
            }catch{

            }
            UIApplication.shared.endReceivingRemoteControlEvents()//设置后台播放
        }`

**Comment by aure** [comment]
This is not an issue with AudioKit, but an implementation concern, please ask on StackOverflow and provide more information there.
