### ISSUE TITLE
How to combine parameters of both AKHighPassFilter and AKCompressor to AKAudioInput from microphone?

### ISSUE THREAD

**Issue by steve21124** [audiokit/AudioKit#137]

**Comment by aure** [comment]
Just chain these effects in the instrument, for instance:

AKHighPassFilter *hp = [[AKHighPassFilter alloc] initWithInput:mic cutoffFrequency:akp(2000)];
AKCombFilter *comb = [[AKCombFilter alloc] initWithInput:hp];
