### ISSUE TITLE
Objective-C project can't find AKSynthKick init can't be found.

### ISSUE THREAD

**Issue by librorum** [AudioKit/AudioKit#1373]
I'm using XCode 9.3.1

In AudioKit-Swift.h, I can't find AKSynthKick init method.  So I can't use that.

I looked at the source AKDrumSynths.swift, 

@objc  omitted in AKSynthKick class.

// Kick Drum Synthesizer Instrument
SWIFT_CLASS("_TtC8AudioKit11AKSynthKick")
@interface AKSynthKick : AKMIDIInstrument
/// Function to start, play, or activate the node, all do the same thing
- (void)playWithNoteNumber:(uint8_t)noteNumber velocity:(uint8_t)velocity;
/// Unneeded stop function since the sounds all decay quickly
- (void)stopWithNoteNumber:(uint8_t)noteNumber;
@end

/// Snare Drum Synthesizer Instrument
SWIFT_CLASS("_TtC8AudioKit12AKSynthSnare")
@interface AKSynthSnare : AKMIDIInstrument
/// Create the synth snare voice
- (nonnull instancetype)initWithDuration:(double)duration resonance:(double)resonance OBJC_DESIGNATED_INITIALIZER;
/// Function to start, play, or activate the node, all do the same thing
- (void)playWithNoteNumber:(uint8_t)noteNumber velocity:(uint8_t)velocity;
/// Unneeded stop function since the sounds all decay quickly
- (void)stopWithNoteNumber:(uint8_t)noteNumber;
@end

**Comment by aure** [comment]
Fixed on develop
