### ISSUE TITLE
AudioKit stop and start produces weird sounds

### ISSUE THREAD

**Issue by alimehdipk** [AudioKit/AudioKit#1375]
i have 2 issues regarding the weird sounds in audiokit. let me explain it to you.

my app has a framework that is using audio permissions. for playing and recording already.

i tried 3 things.
1st approach. i have added a new feature using the audio-kit. when i start the audio-kit for the first time its perfectly working. but when i go to other screen and give permission to other framework the other framework works fine but when i came back to audio-kit the volume is too low. it seems to be cut by 50% and i cannot boost it back to 100%.

to bypass this i thought i have to stop the audio-kit and start it again when i have to use it. but weird stuff happened.

2nd approach. if i stop the audio kit to before using other-framework and comeback to audio-kit and restart it again, it creates weird buzzing sounds on playing sound and on stopping sound.

3rd approach. i used a sample code from "MetronomeSamplerSync". i used a sample code for metronome app. and on play i start the audio-kit and on stop i stop the audio-kit. and if produces the same issue of weird sound.

**Comment by aure** [comment]
This is on StackOverflow, as it should be, thanks: https://stackoverflow.com/questions/50331467/audiokit-stop-and-start-produce-weird-sounds

**Comment by Maulik699** [comment]
@alimehdipk Did you found any solution for that weird sound? It happen to me as well. Here is my code.

@aure Can you please look into it?

`oscillator = AKFMOscillator()
        oscillator!.amplitude = 0.0  
        oscillator!.baseFrequency = Double(calibration.frequency)
        oscillator!.carrierMultiplier = 1.0
        oscillator!.modulatingMultiplier = HolmesMethod.warbleModulationFrequency / Double(calibration.frequency)
        oscillator!.modulationIndex = HolmesMethod.warbleModulationIndex
        oscillator!.rampDuration = HolmesMethod.clickMillis / 1000.0
        
        
        panner = AKPanner(oscillator, pan: calibration.channel == .Right ? 1.0 : -1.0)
        AudioKit.output = panner
        do {
            try AudioKit.start()
            } catch  {
        }
        
        oscillator!.start()
        panner?.start()`
