### ISSUE TITLE
Inter-App HostTransportState

### ISSUE THREAD

**Issue by mekeo** [AudioKit/AudioKit#1378]
I don't know if this problem is well exposed in this section ... anyway, I will post it. I think it's important to improve AudioKit

Audiobus.swift Class is oberving InterApp Audio Connections for property kAudioUnitProperty_IsInterAppConnected. I think we should add listeners to kAudioOutputUnitProperty_HostTransportState.

So, in this function : 

        private func startObservingInterAppAudioConnections() {
        audioUnitPropertyListener = AudioUnitPropertyListener { (_, _) in
            self.updateConnections()
        }

        try! audioUnit.add(listener: audioUnitPropertyListener, toProperty: kAudioUnitProperty_IsInterAppConnected)
    }

We could add...

        audioUnitPropertyListener = AudioUnitPropertyListener { (_, _) in
            self.updateTransport()
        }
        try! audioUnit.add(listener: audioUnitPropertyListener, toProperty: kAudioOutputUnitProperty_HostTransportState)

My problem here is Don't know how to retrieve data in swift from it: isPlaying, isRecording, currentBPM, currentBeat, to sync with AKSequencer.

This sample code from Apple shows how to retrieve (isPlaying or isRecording) in Objective C:
https://developer.apple.com/library/content/samplecode/InterAppAudioSuite/Listings/InterAppAudioSampler_InterAppAudioSampler_Sampler_mm.html

Current Beat and BPM like this in Objective C:

    Float64 isCurrentBeat; // = self.currentBeat;
    Float64 isCurrentBPM; // = self.currentBPM;
    HostCallback_GetBeatAndTempo beat = callBackInfo->beatAndTempoProc(hostUserData,
     &isCurrentBeat, &isCurrentBPM);

Any ideas getting it in swift ?

**Comment by aure** [comment]
I really think this is related to IAA that it should go into StackOverflow where it will get a lot more attention.
