### ISSUE TITLE
2.1 podspec

### ISSUE THREAD

**Issue by niklassaers** [audiokit/AudioKit#138]
Hi Aurelius,
has the updated podspec been sent to cocoapods yet? When I search I find version 2.0.1, but not 2.1.

So to test it out, I pointed my podfile directly:
     pod 'AudioKit', :git => 'https://github.com/AudioKit/AudioKit.git'

Having done this, I get "csound.h" not found on line 32 in CsoundObj.h

Any idea what this is about?

Cheers

    Nik

**Comment by megastep** [comment]
Since the library's structure has changed quite a bit since 2.0, especially when it comes to the static library and its assortment of dependencies, it's not a surprise that this would be currently broken. We were actually hoping that CocoaPods users might help us fix this. ;)

**Comment by megastep** [comment]
Actually I see quite a few references in the pod spec to some old files. Let me try to commit a fix for that and see if it helps...

**Comment by megastep** [comment]
Can you try the pod spec on the develop branch and see if it's any better?

**Comment by niklassaers** [comment]
Hi Peter, thanks for the quick reply. (sorry for my slow reply, I'll monitor the thread more closely now :-) )

The error is the same still.

I'm poking a bit at it and have a setup for it, so if you want to do some screen sharing or quick exchange of ideas, you can catch me on Skype as niklassaers

**Comment by niklassaers** [comment]
Hmm, perhaps I had something cached, because now it asks for CsoundObj.h instead. :-) (from AKManager.h)

**Comment by niklassaers** [comment]
Fixed that one, will send you a diff soon

**Comment by niklassaers** [comment]
Pull request sent :-)

**Comment by niklassaers** [comment]
PS, thank you soo much for your quick reply and update to the podspec :-) (and for all the good work you put into AudioKit)

**Comment by aure** [comment]
For me, Xcode can't find AKFoundation.h after I've pod init'ed and opened up the workspace.
