### ISSUE TITLE
player started but engine not running

### ISSUE THREAD

**Issue by jack-xiaobaicai** [AudioKit/AudioKit#1383]
![2018-05-28 8 24 17](https://user-images.githubusercontent.com/22491353/40614348-2967e5b4-62b5-11e8-92eb-65728928c172.png)
If your issue is implementing AudioKit in your own code, post your problem to [StackOverflow](https://stackoverflow.com/search?q=AudioKit) with the #AudioKit hashtag.

GitHub Issues should only be used for confirmed problems with AudioKit and
well-defined feature requests.

Make sure you know about the common gotcha's outlined in this video:
https://vimeo.com/audiokit/connecting-nodes-part-2

Problems when submitting your app with the framework? First make sure to check your run phases are set up properly, as outlined in this doc:
https://github.com/AudioKit/AudioKit/blob/master/Frameworks/README.md
God, hello, AKAudioPlayer to play after the recording is completed, there is no problem on the iPhone just after the recording is a bit stuck, but there is a crash above the ipad, very much hope to get your help

**Comment by aure** [comment]
Inappropriate issue.
