### ISSUE TITLE
AKAudioFile exportAsynchronously calls callback with error but continues and calls callback again

### ISSUE THREAD

**Issue by CrossProd** [AudioKit/AudioKit#1387]
See this line: https://github.com/AudioKit/AudioKit/blob/master/AudioKit/Common/Internals/Audio%20File/AKAudioFile%2BProcessingAsynchronously.swift#L402

It calls the completion handler with an error but continues and successfully exports the file and calls the completion handler again.

The method documentation states that the callback will be called when export is completed: 

"callback: AsyncProcessCallback function that will be triggered when export completed."

**Comment by CrossProd** [comment]
I don't mind making a pull request for this. Will do that today.

The underlying problem seems to be that the AKAudioFile reports a length & sampleCount of 0. Not sure how to fix that. I now changed my code to use recorder.audioFile instead for exporting.

**Comment by aure** [comment]
Yeah, I am no fan of AKAudioFile anymore, it is a target for refactoring, but of course, we will at least wait until WWDC to see what gifts / kicks in the nuts are in store first.

**Comment by CrossProd** [comment]
I'm trying to push some code to a branch but it appears I have no rights to do this. Error on my side or do I need to be given permissions?

**Comment by aure** [comment]
Reopen if the fix from the PR isn’t sufficient.  Thank you!
