### ISSUE TITLE
Example of using AudioKit to create an auv3 app on iOS

### ISSUE THREAD

**Issue by victorporof** [AudioKit/AudioKit#1389]
Is there some example code somewhere for how this library can be used for auv3 (not inter-app-audio) on iOS?

**Comment by aure** [comment]
It’s not a quite ready for prime tune so we haven’t highlighted it yet but check out progress in /AudioUnits

**Comment by aure** [comment]
Sort of.  A few people are working on it.  Do you want access to our Slack group?

**Comment by victorporof** [comment]
Sure thing! Happy to help however I can.
