### ISSUE TITLE
MIDI devices with duplicate names

### ISSUE THREAD

**Issue by Yilinm** [AudioKit/AudioKit#1390]
When having two midi instruments with same inputNames, is there any way to differentiate them when using 
`public func openInput(_ namedInput: String = "")`
Thanks!

**Comment by Yilinm** [comment]
Since `  internal var inputPorts: [String: MIDIPortRef] = [:]`  in AKMIDI.swift is internal, is very hard for users to find a work around without modifying the AudioKit itself. 
One possible way of resolving this issue is giving aliases to the duplicated midi devices, like what Ableton does: 
<img width="368" alt="screen shot 2018-05-31 at 1 08 25 pm" src="https://user-images.githubusercontent.com/26032964/40805858-7e3b93da-64d4-11e8-8612-71047e67c3f7.png">

**Comment by aure** [comment]
I'm consolidating the MIDI enhancement stuff here https://github.com/AudioKit/AudioKit/projects/3 because its probably not going to be addressed until AKMIDI gets a complete overhaul.

**Comment by aure** [comment]
We've recently switched to a UID based system on develop so this should be addressed.
