### ISSUE TITLE
Examples not working iOS 11.4, XCode 9.4

### ISSUE THREAD

**Issue by kowongh** [AudioKit/AudioKit#1391]
iOS 11.4, XCode 9.4

The SamplerDemo there is no sound. Try to press Play and it doesn't seem to trigger midi. No warnings. Tried on Device and Simulator.

AKSamplerDemo doesn't work.
The sfz files are missing.

> Time to load samples 0.00732829166554438 seconds
Error Domain=NSCocoaErrorDomain Code=260 "The file “TX Brass.sfz” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/14E36B87-1E77-4DAF-B8AC-647A938E1FA4/Documents/ROMPlayer Instruments/TX Brass.sfz, NSUnderlyingError=0x102ecab80 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by aure** [comment]
I’ll take a look but in general we don’t support beta software.  The sampler requires samples to downloaded, check the readme.

**Comment by megastep** [comment]
This is no longer beta though.

**Comment by aure** [comment]
iOS11.4 is out? I'm grabbing 9.4 now. I'm not ignoring this issue, I'll have a look.

**Comment by aure** [comment]
The README will help to fix this problem: https://github.com/AudioKit/AudioKit/tree/master/Examples/iOS/AKSamplerDemo
