### ISSUE TITLE
Feature Request: AKSequencer sequencingDidEnd

### ISSUE THREAD

**Issue by mahal** [AudioKit/AudioKit#1393]
As I'm migrating my app to Swift, I'm encountering following missing feature:

Using AKSequencer and enableLooping, with each loop the currentPosition goes further beyond length. With MusicPlayer I added a MusicSequenceSetUserCallback to the longest track and rewind / restart MusicPlayer on each callback and animate the playing position accordingly. 

Suggested solution for AKSequencer.swift:

```swift
    /// Add a block that is called when all tracks did end playing. 
    ///
    /// - Parameters:
    ///   - callback: Block to be executed at end of longest track
    ///
    /// Can be used when looping is not sufficient. With looping enabled
    /// currentPosition will go on and on and on beyond the length. 
    /// Setting a block will remove previously added blocks
    open func setDidEndSequencing(_ callback: () -> Swift.Void) {
       // enjoy adding pure old c MusicSequenceSetUserCallback and MusicTrackNewUserEvent 
       // typically add the callback to MusicPlayer in AKSequencer play() as the length can change when tracks are edited / added
    }

   ```

**Comment by crashingbooth** [comment]
I might be misunderstanding something, but are you sure that you can't use AKCallbackInstrument to do something like this?

**Comment by genedelisa** [comment]
What I do is add a "user event" to the MusicSequence and loop manually based on receiving that event simply because getting a "done" message was flaky at best.

**Comment by mahal** [comment]
"user event" is what I have now in my ObjC-Code. I'd like to migrate this to AudioKit. Would the user event be added with AKMusicTrack addController or AKMusicTrack addSysex? Or somewhere else?

When the AKCallbackInstrument is in the event flow: which AKMIDIStatus would I have to listen to the "user event"?

**Comment by eljeff** [comment]
I've done this with user events as well. I cannot remember if those are supported in AudioKit yet.

Because the callbackinstrument has been working very well for me. When you right the callback, you'll get a status, note, and velocity message. You can then choose what to do for each status / note / velocity combination as you want.

**Comment by genedelisa** [comment]
This is how I do it in regular Core MIDI

```
let sequencerCallback: MusicSequenceUserCallback = {
            (clientData: UnsafeMutableRawPointer?,
            sequence: MusicSequence,
            track: MusicTrack,
            eventTime: MusicTimeStamp,
            eventData: UnsafePointer<MusicEventUserData>,
            startSliceBeat: MusicTimeStamp,
            endSliceBeat: MusicTimeStamp)
            -> Void in
            
            let mySelf = Unmanaged<GridModel>.fromOpaque(UnsafeRawPointer(clientData)!).takeUnretainedValue()
            
            
            let d = eventData.pointee

            if d.data == 0xAA {
                //print("got the marker")
                DispatchQueue.main.async {
                    mySelf.hitEnd()
                }
            }
            
            if d.data == 0xBE {
                mySelf.gridDelegate?.beatReceived(eventTime)
            }
            
        }
        status = MusicSequenceSetUserCallback(musicSequence!, sequencerCallback, p)
```

and I add the markers like this

```
func addMarker(startBeat: MusicTimeStamp) {
        let endBeat = startBeat + MusicTimeStamp(numBeats)
        print("adding end of phrase marker at \(endBeat)")
        var event = MusicEventUserData(length: 1, data: (0xAA))
        let status = MusicTrackNewUserEvent(markerTrack!, endBeat, &event)
        if status != noErr {
            AudioUtils.checkError(status)
        }
}
```

**Comment by eljeff** [comment]
@genedelisa Thanks for that - I know when I was first doing the AKSequencer I wanted to use user events but got held up passing one of the data structures around. Now that I know a little bit more about this, I will probably attempt it again.
I smell a rewrite of AKSequencer coming on....

**Comment by mahal** [comment]
As this issue is too specific, I wanted to ask for a more general solution: Add user events to AudioKit-MIDI. See #1472

**Comment by govo** [comment]
> This is how I do it in regular Core MIDI
> 
> ```
> let sequencerCallback: MusicSequenceUserCallback = {
>             (clientData: UnsafeMutableRawPointer?,
>             sequence: MusicSequence,
>             track: MusicTrack,
>             eventTime: MusicTimeStamp,
>             eventData: UnsafePointer<MusicEventUserData>,
>             startSliceBeat: MusicTimeStamp,
>             endSliceBeat: MusicTimeStamp)
>             -> Void in
>             
>             let mySelf = Unmanaged<GridModel>.fromOpaque(UnsafeRawPointer(clientData)!).takeUnretainedValue()
>             
>             
>             let d = eventData.pointee
> 
>             if d.data == 0xAA {
>                 //print("got the marker")
>                 DispatchQueue.main.async {
>                     mySelf.hitEnd()
>                 }
>             }
>             
>             if d.data == 0xBE {
>                 mySelf.gridDelegate?.beatReceived(eventTime)
>             }
>             
>         }
>         status = MusicSequenceSetUserCallback(musicSequence!, sequencerCallback, p)
> ```
> 
> and I add the markers like this
> 
> ```
> func addMarker(startBeat: MusicTimeStamp) {
>         let endBeat = startBeat + MusicTimeStamp(numBeats)
>         print("adding end of phrase marker at \(endBeat)")
>         var event = MusicEventUserData(length: 1, data: (0xAA))
>         let status = MusicTrackNewUserEvent(markerTrack!, endBeat, &event)
>         if status != noErr {
>             AudioUtils.checkError(status)
>         }
> }
> ```

你好，已经可以让 MIDI 成功的运行并发出声音，但MusicSequenceSetUserCallback注册的方法总是无法触发，尝试过不同的MusicEventUserData数据，而且验证过MusicEventUserData已经在序列中，但MusicSequenceSetUserCallback就是无法触发
