### ISSUE TITLE
How to record OWN app audio output?

### ISSUE THREAD

**Issue by Vasili802** [AudioKit/AudioKit#1395]
I want to get my OWN app audio output (for example currently playing video in UIWebView) and save it to file. How create a Node for this purpose?

**Comment by aure** [comment]
As this on StackOverflow.

**Comment by Vasili802** [comment]
Please say if is it possible?

**Comment by Vasili802** [comment]
I created question on stackoverflow https://stackoverflow.com/questions/50746837/audiokit-how-to-record-own-app-audio-output-on-ios. Could you help me?
