### ISSUE TITLE
Trying to create a new AKMicrophone instances fails to compile on iPhone 8+.

### ISSUE THREAD

**Issue by dhillonwlknsn** [AudioKit/AudioKit#1397]
I am trying to create a new instance of `AKMicrophone` for using in my app but when I hit build, the build fails and tells me about all of these undefined symbols. I know it's not an issue with my project, because when I remove the `AudioKit.framework`, it works fine. (I am using AudioKit for iOS 4.2.2 and iOS 11.3.1 on an iPhone 8+).

Sample code (crashes when built):
```swift
import AudioKit
class TestVC: UIViewController {
    let mic = AKMicrophone()
    // rest of code below, but the app doesn't even build.
}
```

Error that I get (Apple Mach-O Linker (id) Error):
```
Undefined symbols for architecture arm64:
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(short)", referenced from:
      stk::FileRead::getWavInfo(char const*) in AudioKit(FileRead.o)
  "typeinfo for std::__1::basic_streambuf<char, std::__1::char_traits<char> >", referenced from:
      typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in AudioKit(Stk.o)
  "std::__1::basic_streambuf<char, std::__1::char_traits<char> >::imbue(std::__1::locale const&)", referenced from:
      vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in AudioKit(Stk.o)
```

**Comment by megastep** [comment]
You need to add `-lstdc++` to your linker flags.

**Comment by dhillonwlknsn** [comment]
Thanks it seems to work now, why did I need to add `-lstdc++` @megastep?

**Comment by megastep** [comment]
This became a requirement when we switched to a static framework (it used to be dynamic). Apparently it is not included automatically.

**Comment by dhillonwlknsn** [comment]
@megastep Ah okay, maybe you could add it automatically or put something in the README that tells people to add the flag?

**Comment by megastep** [comment]
It is already added automatically if you use CocoaPods, and the frameworks README already mention this (https://github.com/audiokit/AudioKit/blob/master/Frameworks/README.md) though it could be mentioned on the root README as well...
