### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by vensurfer61** [AudioKit/AudioKit#1402]
Greetings @Audiokit 

I'm a Graphic Designer and I've reached you believing that a logo proposal would be helpful to this project!
A good logo that transmit a message its helpful when it comes to publicity, making it appealing to the eye.
The logo will be made completely free for you, as a way to support open source software

If this is something of your interest, we can get started towards the logo-making process.

I'll be looking forward for your reply
Best Regards,
-Luis Baute

**Comment by Restructural** [comment]
I’d say the framework probably needs a full pattern library of sorts, for
various ui elements and ux processes. It might be going a bit far to roll
out a full on ‘systems design framework’, but I’m sure the community could
probably use a few preset interactions and displays etc, at least for
concepting or prototyping.

I’d be happy to help with this, if it’s something others are interested in.

Clifton Evans

**Comment by aure** [comment]
We keep some graphics in http://github.com/AudioKit/AudioKitGraphics/  but we also have a repo for our web page at http://github.com/AudioKit/audiokit.github.io/   We're a framework so we don't want the load the framework down with too many graphics, but you can contribute to these other repos.  In general this is not an "issue" with AudioKit , so I am going to close it.  You can reach out to us via email.
