### ISSUE TITLE
AKMicrophone restart

### ISSUE THREAD

**Issue by Ufosek** [AudioKit/AudioKit#1409]
Hello,

We are creating a Karaoke app in which user can select a song and sing with headphones. It's important that user can hear his voice mixed with song like in Garage Band.

Everything works great after first play but when user plug-out and plug-in mic - it doesn't start. We cannot hear our voices and we get 0 from AKFrequencyTracker. What's very interesting it works on iPhone 6s Plus - it doesn't on 6s or X.

This is how we use AudioKit:

1. We have static/singleton SongPlayer which has all AKNodes
2. We initialize some settings:
```
AKSettings.defaultToSpeaker = false
AKSettings.audioInputEnabled = true
AKSettings.bufferLength = .short
AKSettings.enableLogging = true
```
3. This is how we connect nodes and start playing:
```
if let file = try? AKAudioFile(forReading: url) {
    player = try AKAudioPlayer(file: file)
}
        
if AKSettings.headPhonesPlugged {
    mic = AKMicrophone()
    tracker = AKFrequencyTracker(mic)
    micBooster = AKBooster(tracker)
    mainMixer = AKMixer(player, micBooster)
    AudioKit.output = mainMixer
} else {
    AudioKit.output = player
}
do {
    try AudioKit.start()
} catch {
    print("Unexpected error: \(error).")
}

micBooster.gain = AKSettings.headPhonesPlugged ? Double(SongPlayer.MIC_VOLUME) : 0
mic.volume = AKSettings.headPhonesPlugged ? Double(SongPlayer.MIC_GAIN) : 0

tracker.start()

self.player.play()
```
4. We also listen for plug-in-out events:
```
switch audioRouteChangeReason {
    case AVAudioSessionRouteChangeReason.newDeviceAvailable.rawValue:
        SongPlayer.instance.stop()
        SongPlayer.instance.start()
    break
            
    case AVAudioSessionRouteChangeReason.oldDeviceUnavailable.rawValue:
        SongPlayer.instance.stop()
        SongPlayer.instance.start()
    break

    default:
    break
}
```

The only solution we found was to initialize AKMicrophone once in init. However then after plug-in-out we can hear crackling noises like here: https://github.com/AudioKit/AudioKit/issues/1213.
When we changed bufferLength to .long - crackling went off - however then delay of user's voice is too big - we need to have .short.

What may be the issues? Why mic doesn't work after second init? And why those crackling sounds appear?

**Comment by dave234** [comment]
@aure Changing bufferLength to .long shouldn't fix a sample rate mis-match.

**Comment by aure** [comment]
@dave234  Fair enough, any other ideas? You can remove yourself from the card, just thought it was something you may have touched on with your work.

**Comment by dave234** [comment]
I'm looking at it.

**Comment by dave234** [comment]
Nothing stands out.
@Ufosek Could you create a minimal test project with instructions to reproduce the issue?

**Comment by Ufosek** [comment]
@dave234 Of course: https://github.com/Ufosek/AudioKitProblemTest

In SongPlayer class there is a field INIT_MIC_ONCE - when it's set to true - mic is initialized only once and crackling sounds appear after few plug-in-out (mostly heard on iPhone X). When set to false - mic doesn't work after second plug-in-out.

**Comment by Ufosek** [comment]
@dave234 Hello, do you have any progress/workarounds for this?

**Comment by dave234** [comment]
I haven't yet, but still intend too.  I can reprioritize if it's holding you up.

**Comment by wangrenzhu** [comment]
I try this
  `    let input = AudioKit.engine.inputNode
        let bus = 0
        let inputFormat = input.outputFormat(forBus: bus)
        
        
        AKSettings.sampleRate = inputFormat.sampleRate
        AKSettings.channelCount = inputFormat.channelCount`
it's useful with commit
https://github.com/AudioKit/AudioKit/commit/a67674168adaf6e46da0ce6b0c07f4b41eefd999

**Comment by Ufosek** [comment]
@dave234 That would be great! Our whole project depends on AudioKit.

@wangrenzhu Could you tell me how to use it in my case and what do you mean "it's useful with the commit"? Or if you could make a pull request to my sample project that would be awesome.

**Comment by dave234** [comment]
@Ufosek I looked at the repo. It looks like you are making the node connections every time you [start](https://github.com/Ufosek/AudioKitProblemTest/blob/e9b705b520dd78d6b0579ea18c1abdcec10880f3/AudioKitProblemProj/SongPlayer.swift#L55).  It's best to make the connections just once and enable/disable as needed.

**Comment by Ufosek** [comment]
@dave234 It looks like it is working - I will test all scenarios and get back to this if something is wrong. My solution was inspired by [https://github.com/audiokit/AudioKit/issues/575](https://github.com/audiokit/AudioKit/issues/575), especially:

> In the reset function, what I did was completely reset AudioKit.output. I rebuilt all the instruments (not sure if this was necessary) and mixed all of them and set them as the output.
