### ISSUE TITLE
Need some help verifying Podspec set up for 2.1

### ISSUE THREAD

**Issue by aure** [audiokit/AudioKit#141]
Even though AudioKit is up to version 2.1 we have not updated CocoaPods to reflect this version because we have not verified that our podspec is sufficient to create a working project.

I've filed this issue so we have a discussion area, but the best write up of the details is up at http://audiokit.io/pod/

**Comment by jhersh** [comment]
>  As you can see, a big decision to be made is whether to use static libraries and be compatible with older versions of iOS, or use dynamic libraries and requiring iOS 8. For the cocoapod, do we make this decision for the user?

If I install AudioKit with CocoaPods then this decision is up to me; it depends whether I specify `use_frameworks!` in my `Podfile`. You can also certainly distribute AudioKit as a static library or dynamic framework in addition to CocoaPods.

> After copying the project file, there a couple of configuration steps. We've tried to add at least this line to the podspec:

>"xcconfig": {
>    "OTHER_LDFLAGS": "-ObjC"
>},
>but I'm guessing we also need something in the podspec that also does the "User Header Search Paths" correctly. And what about the other steps in the "Common Steps" section of the installation instructions?

CocoaPods automatically adds the `-ObjC` linker flag and updates header search paths for all included pods when you run `pod install`, so you shouldn't need to specify `OTHER_LDFLAGS` unless you need to pass any other custom flags. Is there a particular error you're seeing here?

**Comment by aure** [comment]
I can't import AKFoundation.h in my view controller using either of these.

#import "AKFoundation.h"
#import <AudioKit/AKFoundation.h>

So that would be the first problem...

**Comment by aure** [comment]
I still can't import AKFoundation when using the Podspec.  Maybe it is me?

**Comment by jhersh** [comment]
Make sure you do a `pod update AudioKit` to pull in the latest source, and make sure your podfile is pointing to the `develop` branch of this repo.

Here is [my sample project](https://github.com/jhersh/AudioKitTest) which has the line `#import <AKFoundation.h>` in its app delegate.

**Comment by aure** [comment]
Excellent.  It works now in a brand new project.  Closing the issue!  Thanks for your help!
