### ISSUE TITLE
Sysex received > 255 bytes, unhandled

### ISSUE THREAD

**Issue by viclabs** [AudioKit/AudioKit#1411]
I am trying to build a (MacOS) app that sends control data to an Eventide Eclipse via sysex. I am sending a request for screen dump which works fine but I only receive 255 bytes of the syses. The size should be 1152 bytes.  The last character should be 0xF7.

This issue was fixed for sending in March.  It looks like there has been some work towards this with the public var internalPackets: [[MIDIByte]]  definition in AKMIDIEvent.swift. 
"/// Internal MIDIByte-sized packets - in development / not used yet"
I would love it you guys could active this one. It looks ready as it iterates the packetList although it does not check the number of packets in the list like the send routine.  I am not sure about how to return a potentially big dynamic allocation for a big dump.  This is as big as I have used but bank dumps can go as big as 4k.  The screen dump for the Eventide H8000 is about that which I would like to support.  There would not be a need for 65536 bytes as with the sending buffer.

This all happens inside the MIDI Utility example for debug and testing purposes.
I have attached a screenshot of what happens when receiving MIDI sysex > 255 bytes.

Great work with Audiokit

Thanks!

![screen shot 2018-06-20 at 10 42 56 pm](https://user-images.githubusercontent.com/2097114/41659350-63b6085c-74dc-11e8-8ecb-46507b5429a1.png)

**Comment by aure** [comment]
Yeah, this is a known sysex bug. I've assigned myself and other midi knowledgable folks on the team.

**Comment by aure** [comment]
This should be fixed as soon as this pr is accepted https://github.com/AudioKit/AudioKit/pull/1444  Thanks @eljeff !

**Comment by viclabs** [comment]
Thanks @eljeff  and @aure 
Looks like I am shifting to the develop branch (y)

**Comment by eljeff** [comment]
Welcome to life on the edge!
Happy to have gotten this fixed - thanks for reminding us.
