### ISSUE TITLE
Sandboxed App for macOS crashing

### ISSUE THREAD

**Issue by serg-vinnie** [AudioKit/AudioKit#1415]
Code:

```
    let leftChannel   = AKOscillator()          // log error
    let rightChannel  = AKOscillator()          // log error
    left = AKPanner(leftChannel, pan: -1)       // log error
    right = AKPanner(rightChannel, pan: 1)     // log error
    mixer = AKMixer(left,right)                          // crash
```

Output:
```
AKOscillator.swift:init(waveform:frequency:amplitude:detuningOffset:detuningMultiplier:):175:Parameter Tree Failed
AKOscillator.swift:init(waveform:frequency:amplitude:detuningOffset:detuningMultiplier:):175:Parameter Tree Failed
AKPanner.swift:init(_:pan:):79:Parameter Tree Failed
AKPanner.swift:init(_:pan:):79:Parameter Tree Failed
2018-06-23 18:50:14.108436+0300 CoherentMac[67507:2019853] [avae] AVAEInternal.h:70:_AVAE_Check: required condition is false: [AVAudioEngine.mm:393:AttachNode: (node != nil)]
2018-06-23 18:50:14.108892+0300 CoherentMac[67507:2019853] required condition is false: node != nil
```

**Comment by aure** [comment]
I don't know what to do about this. Maybe AudioKit apps can't be sandboxed?  I need more information to go on.

**Comment by serg-vinnie** [comment]
@aure 
Sandboxing is mandatory if you need to submit app to the app store.  It limiting access to filesystem, networking, camera, microphone, etc. For example if you caching some files in app's folder it is ok, but if you access file system out of app's folder you need to specify exactly what you need:
![Uploading Screen Shot 2018-06-28 at 11.45.09 AM.png…]()

If you need any assistance I will be glad to help you.

**Comment by aure** [comment]
Can you try checking the microphone?  Even if you're not using it?

**Comment by serg-vinnie** [comment]
enabling of microphone in App Sandbox didn't help.

**Comment by serg-vinnie** [comment]
@aure, @megastep  I did try to debug Sandboxed Hello Word sample from AudioKit.
And have figured out source of problem: AVAudioUnit.instantiate returns nil.
It turns out that sandboxing of audio unit more complicated than turning some checkbox "on".
https://developer.apple.com/library/archive/technotes/tn2312/_index.html

Currently i'm trying to investigate the problem, but i'm not sure if have enough competence in CoreAudio to resolve this issue quick enough. So your help will be highly appreciated.

**Comment by serg-vinnie** [comment]
This entitlements file did work for me, but it doesn't cover all possible cases

![screen shot 2018-07-13 at 5 19 56 pm](https://user-images.githubusercontent.com/24904140/42696520-05d36314-86c1-11e8-9a3b-38fdac030afa.png)

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.device.audio-input</key>
	<true/>
	<key>com.apple.security.device.audio-video-bridging</key>
	<true/>
	<key>com.apple.security.files.bookmarks.document-scope</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
	<key>com.apple.security.temporary-exception.audio-unit-host</key>
	<true/>
	<key>com.apple.security.temporary-exception.mach-lookup.global-name</key>
	<array>
		<string>com.apple.midiserver</string>
		<string>com.apple.midiserver.io</string>
	</array>
</dict>
</plist>

**Comment by serg-vinnie** [comment]
I'm closing the issue. Please add sandboxing info to your documentation and please check documentation about kAudioComponentFlag_SandboxSafe for  AudioComponentFindNext(_,_).
I'm sure it will be helpful for someone else.
