### ISSUE TITLE
The iOS app doesn’t propperly support the 10,5” iPad Pro resolution

### ISSUE THREAD

**Issue by cor** [AudioKit/AudioKit#1417]
Everything looks blurry because of this

**Comment by aure** [comment]
This is the repo for AudioKit, the framework, not for any of the apps built with AudioKit. If you're addressing a problem with Synth One, I've forwarded this to the proper channels.  Thanks for the feedback, despite this being the wrong place to do it.

**Comment by aure** [comment]
BTW, the majority of graphics on Synth One are dynamically generated, they are not scaled, so I am not sure why things would be blurry.  Could you provide a screen shot?
