### ISSUE TITLE
Why is the output multiplied with 0.05 here?

### ISSUE THREAD

**Issue by ddoe777** [AudioKit/AudioKit#1418]
https://github.com/AudioKit/AudioKit/blob/79cebe3ff8acc64e743b9e9536693c193e478eb4/AudioKit/Common/Nodes/Effects/Reverb/Convolution/AKConvolutionDSPKernel.hpp#L87

After the convolution is computed, is it necessary to multiple the output value by 0.05? It says //hack in there.

**Comment by aure** [comment]
Just to get the volume down to a reasonable level.  It does say hack after all.
