### ISSUE TITLE
Fatal error when running Microtonality playground

### ISSUE THREAD

**Issue by sinewave440hz** [AudioKit/AudioKit#1419]
First of, let me thank you all for an amazing project. I hope I can contribute somehow in the future... Anyway, I just cloned the Audiokit repo and ran the playgrounds. I got an error in the Microtonality playground: 

`Fatal error: Only BidirectionalCollections can be advanced by a negative amount`

at `let tuningTable = AKPolyphonicNode.tuningTable` (that's line 47 in the playground)

As a starting point, I did find this which may provide a way to solve it (ie. using very latest swift build)... https://bugs.swift.org/browse/SR-7529

I'm on High Sierra, using Xcode 9.4.1.

Happy to provide any other info if necessary. Thanks.

**Comment by aure** [comment]
This is fixed on the develop branch, and will be official with AudioKit 4.4.1
