### ISSUE TITLE
How to change the frequency when playing a audio ?

### ISSUE THREAD

**Issue by shuijinliuxi** [audiokit/AudioKit#142]
I want to synthesize a SineWave with the the different frequency and time, how do I get it?

**Comment by shuijinliuxi** [comment]
I try the follow way:
//*******************
instrument.play()
self.oscillator.frequency = 100.ak;
********************//
But it's failed to set the frequency after instrument.play().

**Comment by aure** [comment]
There is not enough information on this to debug.  The instrument is play but self contains the oscillator?  Makes no sense.
