### ISSUE TITLE
AKPlayer for Objective C support

### ISSUE THREAD

**Issue by temkich** [AudioKit/AudioKit#1421]
Can I use AKPlayer in Objective C ?
How to load file for play?

**Comment by temkich** [comment]
I have a similar problem with https://github.com/AudioKit/AudioKit/issues/1139 but in Objective C, and i so I wanted to use AKPlayer.

**Comment by ryanfrancesconi** [comment]
I'll take a look this week.

**Comment by aure** [comment]
There are a few functions that couldn't be ported to objective-c due to incompatible arguments, but all the others, including loading a file should be fine.
