### ISSUE TITLE
AKPeakingParametricEqualizerFilter does not work in Objective C

### ISSUE THREAD

**Issue by temkich** [AudioKit/AudioKit#1426]
I tried to use a `AKPeakingParametricEqualizerFilter` in the Objective C, But if I start it, then there is silence. No effects at any frequency settings or gain or q. 
Same thing with the effects `AKHighShelfParametricEqualizerFilter `and `AKLowShelfParametricEqualizerFilter`.  In Swift project, everything works fine. 
Any help with this?

**Comment by aure** [comment]
That is strange.  Usually the problem with Objective-C is just when a class is not accessible from it, but here you're able to access them but then they don't work. Definitely an interesting mystery, we'll have a look.

**Comment by aure** [comment]
Do you think you could throw together a quick demo project in Objective-C showing these issues?

**Comment by aure** [comment]
Can you reopen this issue with an example project?
