### ISSUE TITLE
AKBooster

### ISSUE THREAD

**Issue by themichael123** [AudioKit/AudioKit#1427]
I am unable to change the gain on an AKBooster

Currently, I have several AKBooster's which I then combine in an AKMixer. 

Users are able to change their value with a slider. 

This used to work previously (I have not updated AudioKit since November).

**Comment by aure** [comment]
Weird. AKBooster is not only tested, but also implemented in just about every AudioKit app in existence. So, I'd love to see your implementation to see what is different.

**Comment by themichael123** [comment]
Ok, can I somehow use AudioKit 4.0.2 in the most recent Xcode ?

**Comment by themichael123** [comment]
Ok, version 4.0.4 is the last version in which it is working. Afterwards the audio quality dramatically changes.

**Comment by aure** [comment]
Can you provide me some of your code for AKBooster that doesn't allow you to change its value?

**Comment by aure** [comment]
Which low pass filter are you referring to?  AKLowPassFilter hasn't changed for a while.  Perhaps the butterworth version?  I really need more information.

**Comment by themichael123** [comment]
Yes, the part in question is really simple. This is the logic: 

Audio input -> AKLowPassButterworthFilter or AKHighPassButterworthFilter -> AKBooster -> Mixer -> Output. 

Is this enough? if not, I will prepare a sample project and send it to you.

**Comment by aure** [comment]
A sample project is necessary for me to debug, yes.

**Comment by themichael123** [comment]
Here is the sample: [High Pass Butterworth Filter.xcplaygroundpage.zip](https://github.com/AudioKit/AudioKit/files/2179643/High.Pass.Butterworth.Filter.xcplaygroundpage.zip)

**Comment by themichael123** [comment]
Thank you for the help Aure.

**Comment by themichael123** [comment]
I have created a new Booster via an extension. Thus, if you believe the clamp is necessary for most AK users, that is fine.

**Comment by ryanfrancesconi** [comment]
It’s good to put a reasonable upper limit. Aure, we had decided “2” before. The main thing is that the parameter ramper isn’t going to like a zero value.

Let’s try 4? or what is the upper range needed?

**Comment by ryanfrancesconi** [comment]
What is this about the audio quality changing?

**Comment by ryanfrancesconi** [comment]
I've been wondering something similar actually.

**Comment by dave234** [comment]
In my opinion it should be 0->~.  I created my own booster a few weeks ago that went to +24db.  The clamp is application logic and should not be in the library.

**Comment by ryanfrancesconi** [comment]
that makes sense

**Comment by aure** [comment]
Lets close this booster issue for now, if you want to open a new one with some evidence on the filter issues thats fine.
