### ISSUE TITLE
Question about some effects on Objective C

### ISSUE THREAD

**Issue by temkich** [AudioKit/AudioKit#1429]
A strange problem with some effects is observed in Objective C. If the `effect.isStarted = NO`, then changing its any parameters should not change the sound?

`AKReverb.isStarted = NO`, but if change `dryWetMix`, sound changed.
`AKReverb2.isStarted = NO`, but if change `dryWetMix`, sound changed.
`AKDelay.isStarted = NO`, but if change `dryWetMix`, sound changed.
`AKDecimator.isStarted = NO`, but if change `mix`, sound changed.
`AKDistortion.isStarted = NO`, but if change `finalMix`, sound changed.

So it should be?

p.s. And there is a question, or is it better to create a new issue? In `AKOfflineRenderNode` missing methods for renderer in Objective C:
`renderToURL`
`renderToBuffer`

**Comment by aure** [comment]
Always best to separate issues so that they can get crossed off independently.

**Comment by aure** [comment]
I addressed your PS with the latest commit.  The underlying dsp for the nodes that you notice this issue for all closed-source Apple nodes, so I don't think I can control how they work, but I guess they are assuming that if you are changing the drywetmix parameter, you want the node to be running.
