### ISSUE TITLE
AKSamplePlayer (Re)Load Length Issue

### ISSUE THREAD

**Issue by romancfischer** [AudioKit/AudioKit#1432]
thanks for the awesome library!
when I load a sample into memory with AKSamplePlayer, press on play, load another file and press on play again, then the length ( size ) seems to be restricted to the length / size of the former sample:

```
let file = try! AKAudioFile(forReading: Bundle.main.url(forResource: self.filename1, withExtension: "wav", subdirectory: "Samples")!  )
self.sample = AKSamplePlayer(file: file)
self.sample!.play()

// .. some time later:

self.sample!.stop()
let file = try! AKAudioFile(forReading: Bundle.main.url(forResource: self.filename2, withExtension: "wav", subdirectory: "Samples")!  )
self.sample!.load(file:file)
self.sample!.play()
```

Is this just me or is this a bug? Might there be a short workaround?

Edit:
The size is actually updated, but I can still only hear it play for as long as the old sample did, even though it's longer then the old one.

**Comment by eljeff** [comment]
That is working as intended. You have to allocate the maximumSamples available for the sampler on init. There is a parameter 'maximumSamples' - set that as big as you'd like on init, and then you can load in samples up to that length.

Also - AKSAmplePlayer has been deprecated in favor of AKWaveTable - so go ahead and switch to that.

Thanks
