### ISSUE TITLE
Node Removal Malloc/Object Leaks

### ISSUE THREAD

**Issue by JamesOrdner** [AudioKit/AudioKit#1433]
Hey all! I'm building a project that dynamically connects and disconnects nodes at runtime. Functionally everything works wonderfully, but I'm noticing some leaks as nodes are disconnected and garbage collected in swift. Each time a node is removed, I rebuild the entire audio graph. `detach()` is called on all existing nodes, as well as `AudioKit.disconnectAllInputs()`. Then new AKNodes are created and the entire audio graph rebuilt from scratch. From a user perspective everything works as it should, but I'm noticing a lot of leaked DSP objects. Here for example is after one complete rebuild of the graph. You can see the old DSP objects are still sticking around despite having no references:

<img width="962" alt="object leak" src="https://user-images.githubusercontent.com/5782729/42570904-b1f94936-8515-11e8-9c0e-a1ec744b8120.png">

I dug around in the source code and found that DSP objects are never actually freed. See the following code from `AKAudioUnitBase.mm`, for example:

```objective-c
- (instancetype)initWithComponentDescription:(AudioComponentDescription)componentDescription
                                     options:(AudioComponentInstantiationOptions)options
                                       error:(NSError **)outError {

    // Omitted for readability

    _kernel = (AKDSPBase*)[self initDSPWithSampleRate:defaultFormat.sampleRate
                                         channelCount:defaultFormat.channelCount];

    // Omitted for readability
}

- (BOOL)allocateRenderResourcesAndReturnError:(NSError **)outError {

    // Omitted for readability

    _inputBus.allocateRenderResources(self.maximumFramesToRender);
    _kernel->init(self.outputBus.format.channelCount, self.outputBus.format.sampleRate);
    _kernel->reset();
    return YES;
}

- (void)deallocateRenderResources {
    _inputBus.deallocateRenderResources();
    _kernel->deinit();
    [super deallocateRenderResources];
}
```

The `AKDSPBase` object is created in `initWithComponentDescription` and initialzed in `allocateRenderResourcesAndReturnError`, but it is never deallocated. `_kernel->deinit();` doesn't actually do anything -- it is an unimplemented virtual function of `AKDSPBase`. `AKSoundpipeDSPBase` and any DSP classes that subclass it do provide a `destroy()` function to deallocate memory created during `init()`, but this function is never called by any part of AudioKit and is not available for `AKAudioUnitBase.mm` to call directly because it is not declared in the top `AKDSPBase` class.

One potential solution to this would be to rename all `destroy()` functions in subclasses of `AKDSPBase` to overridden `deinit()` functions. Because `destroy()` is never called it would not break any part of the code, and `deinit()` is a virtual function available in `AKDSPBase` that could be called in `deallocateRenderResources` as it is now. Another possibility would be to include a virtual destructor in `AKDSPBase`, which would allow `delete _kernel` to be called in `deallocateRenderResources`. Child classes could call their `destroy()` functions from a virtual destructor.

I tried a combination of the above in a few audio units that I am working with: I changed `destroy()` to `deinit()` in `AKPanner`, `AKKorgLowpassFilter` and `AKWhiteNoise`, which I call from `deallocateRenderResources`. Additionally, I added an empty virtual destructor to `AKDSPBase` so that I could follow the `deinit()` call in `deallocateRenderResources` with a `delete _kernel` call. The good news is that objects are no longer leaked upon rebuilding the audio graph, but I'm not sure if this is really the proper fix for this, and doing a complete fix in this way would require modifying every DSP class that has a `destroy()` function. I just started using AudioKit and am not very familiar with the source as a whole, I'm sure y'all will know the best way to go about this!

**Comment by aure** [comment]
This is a lot of write up, we're working on making dynamically creating, connecting, and disconnecting nodes easier.  Perhaps @dave234 has something to say about this?

**Comment by aure** [comment]
So, looking at your write up again, I would say it would be great if you could make a pull request with your fix for at least one of the nodes. I can make the update to all the rest.

**Comment by JamesOrdner** [comment]
I'm happy to :) Though I'd like to discuss the best course of action before creating a pull request, as these are somewhat high level changes that may require changes in all child classes.

There's two parts to this leak. The first is that `delete` is never called on the  `AKDSPBase* _kernel` object in the AKAudioUnitBase and AKGeneratorAudioUnitBase classes. This _must_ happen, otherwise the DSP objects are leaked (as they are created with a `new` call). The second part is that, currently, all Soundpipe DSP classes do their memory cleanup in a function called `destroy` which is never called.

The solution to the first is to add a virtual destructor to AKDSPBase by adding `virtual ~AKDSPBase() {}` to the header. This is a one line fix for subclasses that define their own destructor (automatic override), or subclasses that declare no destructor. However, for some reason there are many DSP subclasses that declare a destructor in the header, but never actually define the destructor. This will cause linking errors with a virtual destructor in AKDSPBase unless the destructor declarations are removed in any subclasses without a corresponding definition (we could also just define an empty destructor in these classes, but if it's currently undefined what's the point of having a destructor at all?).

For the Soundpipe cleanup problem, there are two solutions that I can think of and I don't know which you'd prefer to do. The first would be to rename _all_ `destroy` functions in soundpipe DSP classes to `deinit` (including the one in AKSoundpipeDSPBase), thus overriding the virtual and currently empty `deinit` function in AKDSPBase. `deinit` is already being called in AKAudioUnitBase despite being an empty function, so it seems like `destroy` was intended to be `deinit` in the first place? The second option would be to make `destroy` a private function and call it from the destructor (which will actually be called now that we are calling `delete`). We would need to make it private to ensure that someone couldn't unknowingly call it manually and then delete the object, thus calling it twice. The first seems to be the cleanest method but I wanted to ask as this will require changing pretty much all of the soundpipe classes.

**Comment by aure** [comment]
The cleanest method is what I want.  I don't mind doing the busywork for the rest.

**Comment by aure** [comment]
This should be addressed by the recent PR and follow up commits. Any other helpful changes would be most welcomed. Thanks!
