### ISSUE TITLE
AKSamplePlayer Fade In / Fade Out / Crossfade between End- and Startposition

### ISSUE THREAD

**Issue by romancfischer** [AudioKit/AudioKit#1435]
The AKSamplePlayer is blazingly fast. I miss these two or three features though:
Setting fade In and fade Out, preferably on the fly like this:

sample?.play(fadeIn:0.2)
sample2.stop(fadeOut:0.2)

My ultimate request would be this one though: let's say you stop the sample before it has finished yet, reset to / replay it from the desired start position but with a cross fade inbetween! If you guys could manage to implement these features, you'd have won my heart forever.

**Comment by eljeff** [comment]
Thanks for the request I've actually done the fade in/out already somewhere else but it hasn't made it into ak yet.
A couple questions:
1) are you aware that AKSamplePlayer is being deprecated to be replaced with AKWavetable? Use that from now on
2) Can you clarify the last request, if the sample is stopped, what do you want to crossfade between? An example would really help - either an audio example or a very clear description.
Thanks

**Comment by romancfischer** [comment]
Hi Eljeff,
Thanks for your quick reply.
1. No, I actually didn't know that. Thanks for letting me know, I will switch to AKWavetable then.
2. I actually made a drawing, see below. 
![fade-a-b](https://user-images.githubusercontent.com/5124220/42678474-41cec990-867f-11e8-81bf-c48bb687cf1f.png)

I basically want to be able to loop the sample on the fly with a crossfade inbetween.
Background: I have a step sequencer where samples are dynamically triggered. I don't use your internal sequencer feature though - but my own.

Let's say you have a sample ( Start to End ) and you define the startposition as A. Sometimes I need to reset the playposition to A before the defined end has been reached. In this case this would be B then. The position should immediately jump to point A ( with a 2ms fadeIn ) then and at the same time continue playing from position B for 2ms with a fadeOut. So you would have a crossfade.

If this is something you don't really see fitting in to your library then I might have considering changing to AKTable and try creating something like that on my own, even though that will be challenging for me ;)

One more question: Does the internal looper of AKWavetable fade inbetween the end and the startposition? Can it be activated on the fly or is it necessary to define the .loopEnabled = true before play() was applied?

Please let me know if this was clear enough.

**Comment by wangrenzhu** [comment]
Make AKPlayer fadeOut public like this
 @objc public func fadeOut()

**Comment by eljeff** [comment]
@romancfischer I am very familiar with the concept of crossfade looping if that's what you are talking about - I think I'm getting lost though in your description.

When I think crossfade looping, there is a preset start and end time, and with no crossfade, the sample justs immediately from B to A. With say 100 samples of crossfade looping, point A would start to fade in, and the end would fade out 100 samples before point B.

I think you are also suggesting making this dynamic, basically a fade-seek anytime you want?

**Comment by romancfischer** [comment]
@eljeff sorry if it's confusing. yes, I guess that's what I am asking for.

**Comment by RockerHX** [comment]
@romancfischer A simple wath that you can use a AKNodeRecorder record player, and fadeIn & fadeOut like this:
```Swift4
    static func fadeIn(with player: AKPlayer?) {
        guard let node = player else { return }
        let helper = PlayerHelper.shared
        helper.timer = Repeater.every(.milliseconds(helper.durationInterval)) { [weak helper] timer in
            guard let this = helper else { return }
            if node.gain <= this.maxGrain {
                node.gain += this.rampInterval
            } else {
                timer.pause()
            }
        }
    }

    static func fadeOut(with player: AKPlayer?) {
        guard let node = player else { return }
        let helper = PlayerHelper.shared
        helper.timer = Repeater.every(.milliseconds(helper.durationInterval)) { [weak helper] timer in
            guard let this = helper else { return }
            if node.gain >= this.minGrain {
                node.gain -= this.rampInterval
            } else {
                timer.pause()
            }
        }
    }
```

**Comment by romancfischer** [comment]
I just managed to play around with the framework extension for the first time.
Here is a temporary solution for the fade-in and fade-out feature:

In AKWaveTableDSPKernel.hpp void process:
```
// insert in line 197:
float fadeVol = 1;
if (position >= startPointToUse && position <= startPointToUse + fadeLength){
     fadeVol = 1 - (position - (startPointToUse - fadeLength)) / fadeLength;
}else if(position >= endPointToUse - fadeLength && position <= endPointToUse){
     fadeVol = 1 - (position - (endPointToUse - fadeLength)) / fadeLength;
}

// replace line 209 with
*out *= volume;

```
It works with different start and end-points and a mutated rate but unfortunately it doesn't work in reversed mode. I guess I'll have to dig deeper and implement the sp_tabread_compute function into the class and modify that one. Especially for the seek-fade feature, since buffer from the end-point has to be copied and mixed together with buffer from the start-point under different output-levels in order to achieve a fast transition.

**Comment by aure** [comment]
There doesn't seem to be much actionable to do here, so I'm going to close this as an issue, but I'm sure @eljeff is aware of the idea.  You can still post here and if something can be done, @eljeff  or I will open it again.
