### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by themichael123** [AudioKit/AudioKit#1437]
Hi! Is there some documentation around how the filters etc. work i.e. how the code behind the HPBWF works?https://github.com/AudioKit/AudioKit/tree/master/AudioKit/Common/Nodes/Effects/Filters/High%20Pass%20Butterworth%20Filter

Thank you.

**Comment by aure** [comment]
Not much.  The algorithm is based of Csound's Butterworth filters: 
http://www.csounds.com/manual/html/butterhp.html

And here's a good write up of that:
https://en.wikipedia.org/wiki/Butterworth_filter
