### ISSUE TITLE
Crash when the app running

### ISSUE THREAD

**Issue by shuijinliuxi** [audiokit/AudioKit#144]
I drap the AudioKit folder to my project then run and build.
It crash when the app start.
The error is follow:
dyld: Library not loaded: @rpath/CsoundLib.framework/CsoundLib
  Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/51776503-6943-4AC0-903F-FE08A6AFB058/data/Containers/Bundle/Application/FBB6B689-8CE9-406D-B768-DEC2FD580054/audioSame.app/audioSame
  Reason: image not found

**Comment by narner** [comment]
Did you follow all of the steps in the 'Installation Screencasts and Walkthroughs' section on the website? http://audiokit.io/tutorials/

**Comment by aure** [comment]
This issue needs more information since we can't act on it.  Feel free to reopen it with more details.

**Comment by megastep** [comment]
I would guess that you probably forgot to include the CsoundLib.framework in your app, since it seems like it can't be loaded. You also need to include the run script build phase as explained in the instructions (check out `INSTALL-OSX.md`).

**Comment by turtec** [comment]
Maybe you should take a look on this

http://stackoverflow.com/questions/24993752/os-x-framework-library-not-loaded-image-not-found
