### ISSUE TITLE
AKPeriodicFunction set frequency

### ISSUE THREAD

**Issue by romancfischer** [AudioKit/AudioKit#1441]
I've been testing different techniques in order to find a reliable clock. In my scenario I frequently trigger up to 12 different WAV files with AKWavetable. I need the feature it offers ( startpoint, endpoint, etc..).

I tried to trigger the AKWavetable(s) via AKCallbackInstrument using AKSequencer, but at some points it creates a lot of glitches.

I tried the CADisplayLink approach, which surprisingly isn't that reliable either. The best and most satisfying result I had so far ( and by far ) was using AKPeriodicFunction. I don't know if it is considered a reliable clock for such usecases though - and unfortunately, I can't change the frequency on the fly. Is there maybe a way to set this parameter while the loop is running?

**Comment by aure** [comment]
Hi, this is isn't an issue, but a question, can you ask on StackOveflow please?
