### ISSUE TITLE
Add many sound effects to a dry audio at different time, and I can revoke someone effect.

### ISSUE THREAD

**Issue by RockerHX** [AudioKit/AudioKit#1448]
@aure 
I have a functional requirement, add many sound effects to a dry audio at different time. effects like door sound, footstep and so on. and I can cancel someone sound effect, like revoke function.

I don't know how chose class for complete this requirement that make code concise. 

I think a way use multistage track, eg:
1. I use a main track play dry audio.
2. Other track play sound effects on sometime.
3. All recorders mixer.
4. All track be recorded by AKNodeRecorder.

but this way take revoke function code too complicated.

I wish you can help me. thank you.

**Comment by aure** [comment]
This is not an issue, but more of a general support request.  YOu can either try to post the question to StackOverflow, or perhaps reach out by email if you want someone on the core team to help you with your app as a contractor.
