### ISSUE TITLE
Cannot Import <AudioKit/AudioKit-Swift.h> to Obj-C File

### ISSUE THREAD

**Issue by JamesOrdner** [AudioKit/AudioKit#1453]
I'm writing a custom Audio Unit with multiple inputs, closely following the setup of AKBalancer. However, when I import `<AudioKit/AudioKit-Swift.h>` in my audio unit .mm file, I get the error `'ModulatedDelay.hpp' file not found`. I'm using AudioKit via Cocoapods, so it's lacking the source code and ModulatedDelay.hpp (included by AKModulatedDelayDSP.hpp) is not included in the framework headers. I need to import AudioKit-Swift.h to get access to AKSettings for the sample rate and channel format. Should ModulatedDelay.hpp be added to the framework headers so that AudioKit-Swift.h can be imported in framework projects, or is there a different way to access AKSettings in Obj-C code via the framework? Either way, from my understanding it should be possible to include AudioKit-Swift.h without errors.

**Comment by aure** [comment]
I think the last cocoapods still had this as private but newest develop and staging branches don't so you could set up your cocoapods like I describe here: 

https://stackoverflow.com/questions/51488835/trying-to-upload-audiokit-framework-into-github/51490479#51490479

can you try this and reopen this issue if necessary?

**Comment by JamesOrdner** [comment]
I've modified the podfile accordingly, so that it looks like this:

```
source 'https://github.com/AudioKit/Specs.git'
  
target 'audiokitDaw' do
  use_frameworks!
  pod 'AudioKit', '~> 4.3'
end
```

I then did pod deintegrate and pod install. It is still failing to build with the same error.

**Comment by aure** [comment]
Hmm, that looks right, so maybe cocoapods is putting the header files in a weird place?  I'm not sure. Can you get by without using Cocoapods?
