### ISSUE TITLE
Swift 4.2 support

### ISSUE THREAD

**Issue by colinhumber** [AudioKit/AudioKit#1455]
In order to support using AudioKit in Xcode 10 in a project that uses Swift 4.2, the framework needs to be built with Swift 4.2. Are there plans to implement this before Xcode 10 is publicly released?

**Comment by aure** [comment]
A prebuilt framework will only be available when Xcode is out of beta, but you can use Xcode 10 to make your own built framework as described in the Frameworks README file.

**Comment by aure** [comment]
Yes, absolutely we will be up to date with Xcode within 24 hours of its release.
