### ISSUE TITLE
AKMIDISampler list of sound files added to it.

### ISSUE THREAD

**Issue by JuanPabloBoero** [AudioKit/AudioKit#1458]
Improve AKMIDISampler, we need a way to list the audio files added to the node, so we can filter/clear/remove/list/modify all the sound files added to it.

https://stackoverflow.com/questions/51530906/how-to-clear-remove-list-the-akmidisampler-sound-files-added-to-it/51531142#51531142

**Comment by aure** [comment]
Hi Juan, I looked into this and I don't see any way of doing it for this sampler.  It is based on Apple's AVAudioUnitSampler which can only, to the best of my knowledge, load audio files into a new instrument, so there's ability filter, clear, or modify the files. I have at least added the ability to get the audioFiles loaded into a sampler for future reference. I hope that helps.

**Comment by JuanPabloBoero** [comment]
@aure Thanks! that will help indeed, i was using a workaround that is having a dict to keep track of the files added.
