### ISSUE TITLE
AKPlayer. currentTime issue

### ISSUE THREAD

**Issue by trlniagto** [AudioKit/AudioKit#1466]
Hi everyone. I have an issue with AkPlayer's currentTime. If I try connect AKVariSpeed to AKPlayer and then use AKVariSpeed like output:

let speed = AKVariSpeed()
AudioKit.output = speed

then during playback I see that AKPlayer's currentTime changes quicker than usually (in 2 times faster). Although I change a rate of AKVariSpeed only between 0.997-1.01

**Comment by aure** [comment]
Usually multiples of 2 means something to do with stereo not being handled properly.

**Comment by aure** [comment]
Can you share a project demonstrating this?

**Comment by trlniagto** [comment]
Seems like I found a problem of such behaviour. It is on my side. Thanks
