### ISSUE TITLE
Impossible to create a Rolling Node + Trying to change theme without success

### ISSUE THREAD

**Issue by timdefo** [AudioKit/AudioKit#1470]
Quite New to Xcode and AudioKit, 

So for my App,

I have tried many times to changes the "theme" of Slider Colours.

I change it in the "Common" files, in the "AKView" file, but nothing happens in my project... 

What should I do ? 

Also, is there a working example of a rolling output node out there ? I'm having a lot of difficulties implementing it...

Thanks  ! :)

**Comment by aure** [comment]
I use the rolling plot daily on an app I am developing, so I know it works.  I am able to change its color no problem.  Could you share a project with me so I can follow up appropriately?  There's not enough information for me to keep this open as an issue, and it probably should have been posted to StackOverflow instead.  Anyway, let me know what I can do to help - a shared project would be best.
