### ISSUE TITLE
Enhancement: MIDI User Event

### ISSUE THREAD

**Issue by mahal** [AudioKit/AudioKit#1472]
As AudioKit is the most powerful and most easy to use CoreMIDI-Wrapper available, I'd love to see it even more versatile. Followup of #1393 

Now: AKMIDIStatus-Messages can be added dynamically to a AKMusicTrack

New: AKMIDIStatus-Message can contain user event as in CoreMIDI::MusicEventUserData and AKMIDIListener has a Default implementation with AKLog

**Comment by aure** [comment]
Thanks for the kind words. We'd really like to make a second pass at doing MIDI right in a very modern Swifty way.

**Comment by aure** [comment]
This is not really very actionable, and I'm trying to pare down the issues, so instead I've added it to our projects: https://github.com/AudioKit/AudioKit/projects/3 and when we do a bit of MIDI overhaul (coming soon) we'll be referring to that.
