### ISSUE TITLE
Crash / Failure When Handling MediaServicesReset on iOS

### ISSUE THREAD

**Issue by cojo** [AudioKit/AudioKit#1474]
Hi,

I apologize in advance if it ends up that StackOverflow is the appropriate place to post this - however I have searched the codebase to the best of my ability and I cannot find a reference to the iOS MediaService notifications / events and given that by "default" usage of AudioKit I experience a crash, I felt it appropriate to post an issue to GitHub.  Happy to change if needed, just let me know.

So, the issue I am seeing is that when I trigger a `Reset Media Services` from the `Settings -> Developer` menu on an iOS device, the next subsequent `AKPlayer.play()` call will fail with an assertion exception that looks something like:
`... required condition is false: _engine->IsRunning() Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: _engine->IsRunning()'`

I poked around a bit in `AudioKit+StartStop.swift` and it seems that there is some code to handle other similar events (route / configuration changes); fair enough, maybe I just need to do something similar in my own `AVAudioSessionMediaServicesWereReset` notification observer.

However, I can't seem to come up with a combination of calls that will properly reset the AudioKit engine without that "restart" failing separately (or crashing, depending on how I call things) with the following logs:
```
2018-08-21 16:15:12.634808-0700 Drivetime[7967:2553564] [aurioc] 921: failed: -50 (enable 2, outf< 2 ch,  44100 Hz, Float32, non-inter> inf< 2 ch,      0 Hz, Float32, non-inter>)
2018-08-21 16:15:12.672142-0700 Drivetime[7967:2553564] [avae] AVAEInternal.h:103:_AVAE_CheckNoErr: [AVAudioEngineGraph.mm:1227:Initialize: (err = PerformCommand(*outputNode, kAUInitialize, NULL, 0)): error -50
2018-08-21 16:15:12.672700-0700 Drivetime[7967:2553564] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -50'
```

Based on my (limited) understanding of AVAudioEngine et al., it seems like the internal engine initialization on my "second start" / "restart" is considered to be passing bad parameters of some sort to the system.

One operating theory I have is that perhaps the existence of the `finalMixer` internally from the previous engine is breaking things when calling start a second time (I've seen multiple suggestions / references elsewhere that in the event of a media services reset all nodes etc. should be completely dropped and re-created).

However, this appears to be set to `internal` so I can't test out resetting the `finalMixer` myself without building the library from code / scratch (not ideal for me but I can if necessary).

Anyways, to make a long story short - I feel like I'm missing something obvious here and I was hoping maybe you could help me understand why a media services reset doesn't appear to be handled like route / configuration changes already are, if these crashes / issues are expected as a result of a media services reset in the current codebase, and what I should do to handle them properly myself while using AudioKit.

Finally, for context, here are the two most relevant examples of what I've tried doing to handle this so far (without success) - keep in mind I am dispatching the call to this function to the main queue from the MediaServicesReset observer based on the example I saw in AudioKit+StartStop.swift:
```
func resetAudioKit() {
    do {
      // I've tried just calling start directly (and also calling engine.start() directly) as that's more or less how I see it handled in AudioKit+StartStop.swift
      mixer = AKMixer()
      AudioKit.output = mixer
      try AudioKit.start()  // I have also tried calling AudioKit.engine.start() directly as well.
    } catch {
      print("AudioKit Reset ERROR!")
    }
  }
```
```
func resetAudioKit() {
    do {
      // If we've already setup before, I have also tried stopping AudioKit first before starting it.
      if mixer != nil {
        try AudioKit.stop()  // I have also tried calling try AudioKit.engine.stop() directly as well.
      }
      mixer = AKMixer()
      AudioKit.output = mixer
      try AudioKit.start()  // I have also tried calling AudioKit.engine.start() directly as well.
    } catch {
      print("AudioKit Reset ERROR!")
    }
  }
```

**Comment by aure** [comment]
Definitely seems like it could get more attention in StackOverflow, but would need a tl;dr too. :). Basically it would be great if all our issues were actionable and I'm not really sure what to do here. Could this be broken up into smaller issues?

**Comment by cojo** [comment]
@aure thanks for the quick response!

I guess one first step / TL;DR version of this might be - as far as I can tell in my local testing, if I create an `AKMixer` as `AudioKit.output` and then connect `AKPlayer` nodes to them over time, `AudioKit` will not handle a `MediaServicesReset` gracefully and the app using it will crash on the next `AKPlayer.play()`.

Separate from all the other details / questions above, is that a concise enough version for the team to verify / reproduce and go from there?

**Comment by aure** [comment]
Verification and reproduction is made easier if you could supply a sample project. A lot of times we'll be given what people feel is the relevant code, but then to start, setup, and prove a project is time consuming.  Could you share a simple project that reproduces the problem?

**Comment by cojo** [comment]
Hi @aure,
I'll try to put together my own example project I can send that is super clean for this specific case, but in the meantime, if it's of any value, it appears some of the existing examples in the AudioKit repository that include interactivity ("play this sound now") etc. will break as-is if you hit the `Reset Media Services` button from the Developer menu on a physical device.  I'll see if I can find a specific good existing example with a write up of steps to send you to make it super easy.

In the meantime, I went ahead and integrated the source code version of AudioKit to play around a bit more and also did some more research.

Based on Apple's audio presentation at WWDC: http://devstreaming.apple.com/videos/wwdc/2016/507n0zrhzxdzmg20zcl/507/507_delivering_an_exceptional_audio_experience.pdf?dl=1 (slide 58), I do think that there is some additional plumbing needed to handle this event cleanly.  They specifically mention:
```
Need to destroy and recreate objects
• AVAudioEngine, queues, remote I/Os, players, etc
```
And I believe it is the lack of this which is causing a crash when this event occurs.
I implemented a basic test function in `AudioKit+StartStop` to test this:
```
    @objc open static func reset() throws {
        if engine.isRunning {
            try AKTry {
                engine.stop()
            }
        }
        
        let temp = output
        engine.reset()
        engine = AVAudioEngine()
        finalMixer = AKMixer()
        output = temp
        
        try AKTry {
            try start()
        }
    }
```

And it does indeed prevent the crash in question, but because I am not sure how to clean up all the other nodes (for example previous AKPlayer's and all of their sub-nodes), subsequent crashes still occur (e.g. the `dealloc` of the old `AVAudioEngine` ends up triggering `AKPlayer`'s completion callback, which in turn then goes and looks for the `currentFrame` and causes a crash because the old `AVAudioEngine` is now `nil` and triggers an assert...

Anyhow - I'll see if I can find a very specific example / set of steps I can send to allow a quick repro on your side.  Just thought I'd share my ongoing findings in the meantime as well.

**Comment by extnous** [comment]
Hi, did you solve the problem? 
Similar crash sometimes occurs when you try play() for AKPlayer (Fatal Exception: com.apple.coreaudio.avfaudio player started when engine not running)

**Comment by cojo** [comment]
Hi @extnous and @aure 

Sorry for the extreme delay in my response.

We've finally gotten around to tackling this for our own app / use case and have come up with a potential solution, which partially involves some AudioKit changes.

I've gone ahead and submitted a PR (https://github.com/AudioKit/AudioKit/pull/1522) - feel free to use it if it's helpful (or at least reference it if you come across this later as a user experiencing this issue, even if it isn't something worth merging).

Thanks!
