### ISSUE TITLE
AudioKit Spectrogram Plot

### ISSUE THREAD

**Issue by eupston** [AudioKit/AudioKit#1479]
Was wondering if you guys had implemented a spectrogram plot or had any ideas on how to?
I know you have waveform plot and such at the moment. 

I understand you basically need three ingredients frequency on the Y axis, Time on X axis, and magnitude represented with the a color spectrum. Then I suppose deciding on the size of your window.

**Comment by aure** [comment]
This would be a nice-to-have.  I'm currently working on beefing up our plot capabilities.

**Comment by eupston** [comment]
Awesome thanks Aure!! Would definitely be a game changer for me, because spectrograms are so useful in Machine Learning and audio classification. The only open source implementation i've seen so far is Auriotouch which seems very bloated and complex. Definitely appreciate your help, and thanks for all you've done so far with AudioKit, its amazing!

**Comment by aure** [comment]
I am making great progress with the spectrograph and I've added this as a feature in the projects section: https://github.com/AudioKit/AudioKit/projects/1  I'm trying to use the issues mostly for actionable projects that don't have an owner yet, so I am going to close this issue.  But feel free to check up on my progress here.
