### ISSUE TITLE
Can I export an audio file from AKSequencer? 

### ISSUE THREAD

**Issue by omatheus015** [AudioKit/AudioKit#1480]
Sorry to ask this question here. I did post it in the [stackoverflow](https://stackoverflow.com/questions/52012143/how-to-render-and-export-audios-in-audiokit), but I don't get some solution until now. 

I'm using AKSequencer to play notes in sequence and I'm also applying some filters on the sound, like reverb.

I found an example code [here](https://audiokit.io/playgrounds/Playback/Exporting%20Files/) that exports an audio from another audio file, but it is not what I need. Actually, I need to render the notes sequence, including the filters, and export it to the user.

My code:

    class Sequencer {
        
        let oscBank = AKOscillatorBank(waveform: AKTable(AKTableType.sawtooth))
        let sequencer = AKSequencer()
        
        init() {
            setup()
        }
        
        func setup() {
            
            // I instantiate a MIDI node with the oscillator bank to put it in the track output.
            // It makes the oscillator's filters are recognized in the track output.
            let midiNode = AKMIDINode(node: oscBank)
            _ = sequencer.newTrack()
            sequencer.tracks[0].setMIDIOutput(midiNode.midiIn)
            
            generateSequence()
            
            // Here I'm applying some filter, a reverb in this case.
            let reverb = AKReverb(oscBank)
            reverb.loadFactoryPreset(.plate)
            
            // The Audiokit's output may be the last filter applyed. It is working to play.
            AudioKit.output = AKMixer(reverb)
            try? AudioKit.start()
        }
        
        func play() {
            sequencer.play()
        }
        
        func stop() {
            sequencer.stop()
        }
        
        
        /// Generates some melody (Sweet Child of Mine)
        func generateSequence() {
            for _ in 0..<2 {
                sequencer.tracks[0].add(noteNumber: 62, velocity: 127, position: AKDuration(beats: 0), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 74, velocity: 127, position: AKDuration(beats: 0.5), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 69, velocity: 127, position: AKDuration(beats: 1), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 67, velocity: 127, position: AKDuration(beats: 1.5), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 79, velocity: 127, position: AKDuration(beats: 2), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 69, velocity: 127, position: AKDuration(beats: 2.5), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 78, velocity: 127, position: AKDuration(beats: 3), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 69, velocity: 127, position: AKDuration(beats: 3.5), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 62, velocity: 127, position: AKDuration(beats: 4), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 74, velocity: 127, position: AKDuration(beats: 4.5), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 69, velocity: 127, position: AKDuration(beats: 5), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 67, velocity: 127, position: AKDuration(beats: 5.5), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 79, velocity: 127, position: AKDuration(beats: 6), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 69, velocity: 127, position: AKDuration(beats: 6.5), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 78, velocity: 127, position: AKDuration(beats: 7), duration: AKDuration(beats: 0.5))
                sequencer.tracks[0].add(noteNumber: 69, velocity: 127, position: AKDuration(beats: 7.5), duration: AKDuration(beats: 0.5))
            }
        }
        
        
        // Here is my problem. I want to get the song and export it with the .wav extension exactly as it was played.
        func saveFile() {
            // What should I do here?
        }
    }

Can someone please help?

**Comment by aure** [comment]
Sorry, I was away on travels for a week, I've responded on StackOverflow.

**Comment by omatheus015** [comment]
@aure, I saw your answer in StackOverflow, but what do you suggest we do? This feature is essential in our project.

**Comment by omatheus015** [comment]
> @aure, Thanks for replying in StackOverflow, but what do you suggest we do? This feature is essential in our project.

??
