### ISSUE TITLE
Hide initial audio tracking line

### ISSUE THREAD

**Issue by TheSwiftyCoder** [AudioKit/AudioKit#1483]
I posted this on StackOverflow and reposted again today with a query to remove/hide the initial plot line from view. Is this possible within AudioKit as I can't see any reference to it within the documentation or exploring the AKNodeOutputPlot API. (It could be that I'm searching for the wrong wording 💯 )

The reposted question is here with reference to the image: https://stackoverflow.com/questions/52113716/audiokit-remove-aknodeoutputplot-center-line-on-launch

Thanks.

**Comment by aure** [comment]
I answered on StackOverflow which is the proper place for the question, but since it fell under my radar and I didn't reply its okay that you cross posted here.  But I will close it for now since its not really an issue.
