### ISSUE TITLE
Xcode 10 beta 6 Issues

### ISSUE THREAD

**Issue by AhmadOdeh93** [AudioKit/AudioKit#1491]
I trying run My app with AudioKit (4.3) on (Xcode 10 beta 6 , Swift 4.2) , I have this error

> Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /Users/MyAppName/Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/arm64.swiftmodule

i tried update pod , remove and install it again    

Note : The app run on (Xcode 9.4.1) Without problem

**Comment by megastep** [comment]
The binaries used by CocoaPods have been built with Xcode 9 and Swift 4.1. Until Xcode 10 is out of beta, you will have to compile the frameworks manually using our provided `build_frameworks.sh` script.
