### ISSUE TITLE
Getting AURemoteIO::IOThread when implementing more than one conductor / sustainer

### ISSUE THREAD

**Issue by RocKhalil** [AudioKit/AudioKit#1496]
I created a fork of SynthOne app (posting the issue here since you're responsible of SynthOne) and I'm trying to load multiple presets at the same time.

Right now, I'm creating a list of `conductors` that contains `sustainers` and each `sustainer` loads a preset. This is working perfectly on the simulator. 2 and more presets are running at the same time. However, when I try using the app on my iPhone 7 Plus, I get `AURemoteIO::IOThread`.

Any idea why this is happening ? Maybe memory leaks ?

**Comment by aure** [comment]
The Synth One repo has its own issue sections though, please post this there, and add a bit of code, I am not sure what you mean.
