### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by pjb493** [AudioKit/AudioKit#1497]
Hi,

Is there any plan to add Swift Package Manager to the PM options in addition to Pods and Carthage? I don't imagine it would be any trouble / cause any issues, it would only take a tiny amount of code and I would really appreciate it.

Thanks

Peter

**Comment by megastep** [comment]
I actually looked into this, but because of the massive amounts of non-Swift code in AudioKit (lots of C++ and Objective-C), it doesn't seem like we would be able to do this with the Swift package manager at the moment. Maybe if they ever expand their build options...

These days the easiest way to use AudioKit would be via CocoaPods.

**Comment by MichaelBuss** [comment]
FWI Apple's documentation now says:
> Swift packages are reusable components of Swift, Objective-C, Objective-C++, C, or C++ code that developers can use in their projects.
Seems SwiftPM is a lot more production ready after WWDC19. Maybe it would be worth it to look into it again? Would **love** to be be able to ditch CocoaPods. 🙌

**Comment by megastep** [comment]
I can take another look but last I checked after WWDC19 it still didn't seem to be a good fit... Even the infrastructure to put out xcframeworks breaks with AudioKit and the current version of Xcode.

**Comment by MichaelBuss** [comment]
You're the expert. The whole reason I would like support for SwiftPM is that I am not. Adding CocoaPods is a bit of an overhead in my world, whereas using SwiftPM is not.
Thank's for the answer either way. You can look into it if you want, but if you say that it is not a good fit, I Believe you. 👍

**Comment by bryansum** [comment]
Looks like starting with Xcode 12 it should be possible to distribute `AudioKit.xcframework` as a Swift package: https://developer.apple.com/videos/play/wwdc2020/10147

**Comment by aure** [comment]
Yeah, lets see if @megastep and I can make this happen.

**Comment by megastep** [comment]
Funny you mention that now, I was looking into it yesterday and was gonna start working on it today but got sidetracked... Anyway, yeah now that we can ship binary xcframeworks it's very much back on the roadmap.

The way they do it is a bit awkward so we may have to do it through a separate repo, but it should be doable.

**Comment by megastep** [comment]
I have tentatively integrated this with the AudioKit 5.0 beta, and Xcode 12 / Swift 5.3 SPM.

More info on this repo: https://github.com/AudioKit/AudioKitSPM

**Comment by aure** [comment]
I'm going to call this "addressed" in that we have a lot of issue piling up and Stephane is on this.
