### ISSUE TITLE
Issue with AKMusicTrack and AKMIDINoteData

### ISSUE THREAD

**Issue by fuad-adetoro** [AudioKit/AudioKit#1498]
Before I start I just want to say that I posted this issue to StackOverflow, but I haven't received a response from anyone. If anyone is interested in the question here's the link: https://stackoverflow.com/questions/52310322/audiokit-akmusictrack-not-playing-midi. 

The problem that I'm currently facing is that if an AKMIDINoteData of the same note is added to the AKMusicTrack with similarities in position and duration then only one will play. Let me clarify the issue a bit more, lets say I have two notes 74 & 74 and the second 74 is supposed to play whilst the first 74 is still playing, it won't.

Here is an example of an array of MIDINoteData from the MusicTrack.

[note: 74 velocity: 127 chan: 0 duration: 1.31484985351562 position 0.663384547,
note: 74 velocity: 127 chan: 0 duration: 1.68195784091949 position 1.09386738]

The second note won't play which is not the behaviour I expected. 

I'm not entirely sure of how complex this would be for you guys, but if you can't solve the issue then I think my best bet would be to force a NoteData to end when the other one starts depending on whether they correlate in terms of position and duration, another possible solution could be attempting to make only one note from both.

**Comment by aure** [comment]
I don't really feel like you gave enough time for this to be answered on StackOverflow before coming here.  In any event, can you provide a project that exhibits this behavior share via Github or Dropbox?
