### ISSUE TITLE
Swift 4.2/Xcode 10 support

### ISSUE THREAD

**Issue by colinhumber** [AudioKit/AudioKit#1499]
Now that Xcode 10 is out of beta and the iOS 12 GM has been posted, can we expect a Swift 4.2-compatible version to be released shortly?

**Comment by aure** [comment]
Develop works on Xcode 10, or else if you're using Cocoapods, you can point to AudioKit's own spec to get access to the latest Xcode 10 build.

**Comment by aure** [comment]
A la https://github.com/AudioKit/SongProcessor/blob/develop/Podfile

**Comment by megastep** [comment]
I've been working on setting up a staging version of our code as a pod until the final 4.4 comes out, you can use it via our Specs repo at http://github.com/AudioKit/Specs

**Comment by megastep** [comment]
I should clarify this pod is built with Xcode 10 and should be suitable to use in your projects.

**Comment by colinhumber** [comment]
Awesome, I'll give this a go this afternoon and see how it works.

**Comment by colinhumber** [comment]
@megastep Ran the 4.4.0b1 pod and everything seemed to be working as expected. I'm able to integrate our library that relies on AudioKit into our main app running Xcode 10 and Swift 4.2.

Thanks for all the work on this!

/cc @aure

**Comment by jbmaxwell** [comment]
Sorry for the stupid question, but how do I get this build from my podfile. With no arguments it installs 4.3.

**Comment by aure** [comment]
@jbmaxwell Make sure the iOS target in your pod file is not still 9.0.  Needs to be 10.0+

**Comment by jbmaxwell** [comment]
Thanks for the heads-up, @aure. No worries here, we're elitists; our target is iOS 11+! ;-)
