### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler

### ISSUE THREAD

**Issue by vojtabohm** [AudioKit/AudioKit#1500]
Hi!

After I've updated to macOS Mojave beta 10, using Xcode 10 beta, when I try to run my project, I get the following error on the import AudioKit line saying "Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler".

I have tried cleaning DerivedData, pod install, pod update, remove the pod. Nothing helped. 

Any ideas please?

**Comment by megastep** [comment]
Until we push out the official v4.4.0 release built with Xcode 10, you can try to use our staging version in the meantime: https://github.com/AudioKit/Specs

**Comment by amardeepranu** [comment]
Getting this error as well - I can't build my app. Is there an ETA on the v4.4.0 release?

**Comment by aure** [comment]
Today, hopefully.

**Comment by atacand1920** [comment]
Any updates for 4.4.0 framework, i am unable to pursue my work unless you guys finish the 4.4.0 framework, i didn't use pods.

**Comment by yoiang** [comment]
In the interim for those of us that don't use pods one can pull/download the latest from the `develop` branch, add it to one's project manually and link that way.

**Comment by megastep** [comment]
Yeah you should try to use the staging build in the meantime if you use pods, otherwise use our develop branch and compile the library yourself with our provided instructions. We have a couple of things to fix before release though but hopefully an official 4.4.0 will be out very soon.

**Comment by atacand1920** [comment]
It worked perfectly, and if you guys want to build the framework from the develop branch , just use the script "build_frameworks.sh" inside Frameworks directory and thank you @yoiang
