### ISSUE TITLE
Can't play audio while using AKFrequencyTracker with AudioKit on iOS

### ISSUE THREAD

**Issue by JPonczek** [AudioKit/AudioKit#1503]
Every time I play audio, either with the AKPlayer built into AudioKit, or with Apple's AVAudioPlayer, the amplitude and frequency values from the AKFrequencyTracker always return 0.0. This is unfortunate, because I was planning on having the auto output come from headphones, with the audio input from the microphone, which would eliminate any interference coming from the output. I noticed that this bug only occurs after I run AudioKit.start().

**Comment by aure** [comment]
I would like issues to be proven to be problems with AudioKit that can be acted on.  But, with the information you provided I can't tell what that would be.  I'd really like if you could ask the question on StackOverflow and once we narrow the problem down, post an issue here.  Also, provide your implementation details or better yet, a project demonstrating the issue.

**Comment by JPonczek** [comment]
I resolved the problem by using AKMixer to add more than one output. However, I did find another unrelated bug. It seems as though the AKTracker frequencies are way off when I tested on my iPhone Xs. The levels are around 4000 and up.

**Comment by WuHarry** [comment]
> I resolved the problem by using AKMixer to add more than one output. However, I did find another unrelated bug. It seems as though the AKTracker frequencies are way off when I tested on my iPhone Xs. The levels are around 4000 and up.

Can you help me with how to set the two output together? Thanks! Here's what I am trying to do:

`   
    var oscillatorBank = AKOscillatorBank()
    var metronome = AKMetronome()
    var microphone = AKMicrophone()
    var tracker = AKFrequencyTracker(microphone)
    silence = AKBooster(tracker, gain: 0)
     metronome.tempo = Double(currentUserPreference.tempo)
     let mixer = AKMixer(silence, metronome, oscillatorBank)
     AudioKit.output = mixer
     try? AudioKit.start()
`

**Comment by WuHarry** [comment]
> I resolved the problem by using AKMixer to add more than one output. However, I did find another unrelated bug. It seems as though the AKTracker frequencies are way off when I tested on my iPhone Xs. The levels are around 4000 and up.

I got frequencies above 20000, any solutions?
