### ISSUE TITLE
AudioKit.output Crash

### ISSUE THREAD

**Issue by atacand1920** [AudioKit/AudioKit#1505]
this error occurred in my project so i tried to run the MicrophoneAnalysis exemple and it crash too.
The first ScreenShoot is with a Breakpoint All Exceptions to know the origin of the crash 

<img width="1440" alt="screen shot 2018-09-20 at 2 59 34 pm" src="https://user-images.githubusercontent.com/17404534/45823593-ec223e80-bce5-11e8-9c2b-176a0ab30e5f.png">

The Second run is without breakpoint 
<img width="1440" alt="screen shot 2018-09-20 at 3 05 22 pm" src="https://user-images.githubusercontent.com/17404534/45823893-a3b75080-bce6-11e8-9c53-57d562889f08.png">

Sorry to bother you guys but i am in hurry with my end of study project.

AudioKit 4.4 , XCODE 10, IOS 12

**Comment by NicolasLourenco** [comment]
Exclatly the same on my side
Here is the logs
```
myProject[1371:184970] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Haut-parleur (type: Speaker)
myProject[1371:184970] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Haut-parleur (type: Speaker)
myProject[1371:184970] [avae] AVAEInternal.h:70:_AVAE_Check: required condition is false: [AVAudioIONodeImpl.mm:910:SetOutputFormat: (IsFormatSampleRateAndChannelCountValid(hwFormat))]
myProject[1371:184970] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: IsFormatSampleRateAndChannelCountValid(hwFormat)'
*** First throw call stack:
(0x1c3a6ff78 0x1c2c68284 0x1c39803b0 0x1c9a1c954 0x1c9a1be54 0x1c9ac1e7c 0x1c9a4dda4 0x1c9ac9ed0 0x1c9ac9f5c 0x1048b8544 0x1048b8624 0x1045bd6bc 0x1045bd9f0 0x1045bcbdc 0x1045bcb94 0x1083341dc 0x1083362d0 0x107a72030 0x1045bcc84 0x10459d334 0x10459d4c0 0x1f0e29728 0x1ce3237e0 0x1ce323a24 0x1ce2c12f0 0x1f1490500 0x1f10620fc 0x1ce3237e0 0x1ce323a24 0x1ce2c12f0 0x1f1490500 0x1f1298bf4 0x1045c1ba0 0x1045c1c54 0x1f0e29728 0x1ce3237e0 0x1ce323a24 0x1ce2c12f0 0x1f1490500 0x1f10620fc 0x1ce3237e0 0x1ce2c12f0 0x1f1179f5c 0x1ce3237e0 0x1ce323a24 0x1ce2c12f0 0x1f109ae20 0x1f1274f40 0x1f1279814 0x1f1279a80 0x1f1497c14 0x1045a3794 0x1045e0684 0x1045e0b20 0x1d7e87238 0x108332c44 0x1083341dc 0x1083419c4 0x1c39fc630 0x1c39f72d4 0x1c39f6844 0x1c5ca5be8 0x1f0da5428 0x10459fb58 0x1c34ac020)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by atacand1920** [comment]
yes on my main project , i have this error too , still wondering how to solve it "IsFormatSampleRateAndChannelCountValid(hwFormat)" , everything was working great with xcode9 and AudioKit 4.2

**Comment by atacand1920** [comment]
update : i found that the problem is coming from AudioKit.output so i am assuming that the SIGABRT occurs somehow when connecting the  nodes to the the output of AudioKit.

I also tried the short way debugging by passing the AKmicrphone directly to the output but same crash  : 
`
       
      
         AKSettings.audioInputEnabled = true
         mic =  AKMicrophone()
        AudioKit.output = mic
        do {
            try AudioKit.start()
            
            
        }catch(let error){
            print("AudioKit:",error.localizedDescription)
        }`
debbuger : 

` 2018-09-22 02:06:33.496112+0100 SINGTN[54588:1444863] [avae] 

AVAEInternal.h:70:_AVAE_Check: required condition is false: [AVAudioEngine.mm:686:ConnectMultipleOutputs: ([_nodes containsObject: connPoint.node])]

2018-09-22 02:06:33.517225+0100 SINGTN[54588:1444863] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: [_nodes containsObject: connPoint.node]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011176929b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010f8a2735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000111769022 +[NSException raise:format:arguments:] + 98
	3   AVFAudio                            0x000000011519a89c _Z19AVAE_RaiseExceptionP8NSStringz + 156
	4   AVFAudio                            0x00000001151d795b _Z11_AVAE_CheckPKciS0_S0_b + 323
	5   AVFAudio                            0x000000011521c31e _ZN17AVAudioEngineImpl22ConnectMultipleOutputsEP11AVAudioNodeP7NSArraymP13AVAudioFormat + 540
	6   AVFAudio                            0x000000011521c0ba -[AVAudioEngine connect:toConnectionPoints:fromBus:format:] + 94
	7   SINGTN                              0x000000010e43c139 $S8AudioKitAAC7connect_2to7fromBus6formatySo11AVAudioNodeC_SaySo0H15ConnectionPointCGSiSo0H6FormatCSgtFZTf4nnnnd_n + 1945
	8   SINGTN                              0x000000010e40b9a8 $S8AudioKit8AKOutputPAAE7connect2to3busAA7AKInput_pAaG_p_SitFAA18AKPeriodicFunctionC_Tg5Tf4nnn_g + 616
	9   SINGTN                              0x000000010e40ca79 $S8AudioKit8AKOutputPAAE7connect2to3busAA7AKInput_pAaG_p_SitFAA6AKNodeC_Tg5Tf4nnn_g + 9
	10  SINGTN                              0x000000010e3e75f5 $S8AudioKitAAC6outputAA6AKNodeCSgvWZTf4dd_n + 1653
	11  SINGTN                              0x000000010e3e6552 $S8AudioKitAAC6outputAA6AKNodeCSgvsZ + 66
	12  SINGTN                              0x000000010e2c582b $S6SINGTN11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtF + 411
	13  SINGTN                              0x000000010e2c6484 $S6SINGTN11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtFTo + 228
	14  UIKitCore                           0x000000012089c4d7 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 280
	15  UIKitCore                           0x000000012089dec4 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3979
	16  UIKitCore                           0x00000001208a3527 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1623
	17  UIKitCore                           0x0000000121145e3e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
	18  UIKitCore                           0x0000000121142403 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	19  UIKitCore                           0x0000000121145a7b -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 233
	20  UIKitCore                           0x0000000121146435 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1085
	21  UIKitCore                           0x0000000121103b31 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 795
	22  UIKitCore                           0x00000001211037db -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 435
	23  UIKitCore                           0x000000012114892c __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 584
	24  UIKitCore                           0x0000000121149256 _performActionsWithDelayForTransitionContext + 100
	25  UIKitCore                           0x000000012114868b -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 221
	26  UIKitCore                           0x0000000121141aa1 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	27  UIKitCore                           0x00000001208a1d46 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
	28  UIKitCore                           0x00000001208d3856 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 357
	29  FrontBoardServices                  0x000000011bbf5dda -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
	30  FrontBoardServices                  0x000000011bc00f43 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 271
	31  FrontBoardServices                  0x000000011bc0063a __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
	32  libdispatch.dylib                   0x0000000114d7b63e _dispatch_client_callout + 8
	33  libdispatch.dylib                   0x0000000114d7ebb4 _dispatch_block_invoke_direct + 301
	34  FrontBoardServices                  0x000000011bc353c8 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	35  FrontBoardServices                  0x000000011bc35080 -[FBSSerialQueue _performNext] + 457
	36  FrontBoardServices                  0x000000011bc35660 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	37  CoreFoundation                      0x00000001116ccb31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	38  CoreFoundation                      0x00000001116cc3a3 __CFRunLoopDoSources0 + 243
	39  CoreFoundation                      0x00000001116c6a4f __CFRunLoopRun + 1263
	40  CoreFoundation                      0x00000001116c6221 CFRunLoopRunSpecific + 625
	41  GraphicsServices                    0x0000000116b061dd GSEventRunModal + 62
	42  UIKitCore                           0x00000001208a5115 UIApplicationMain + 140
	43  SINGTN                              0x000000010e2c7cc7 main + 71
	44  libdyld.dylib                       0x0000000114df1551 start + 1
	45  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by robertcapsure** [comment]
How are you importing the AudioKit Framework? I've noticed I got this crash when I imported manually but works fine when I use cocoapods. Xcode 10 iOS12 AudioKit 4.4

**Comment by NicolasLourenco** [comment]
Hi Robert,
I import the AudioKit framework exactly like you with CocoaPod

**Comment by atacand1920** [comment]
@NicolasLourenco  i found a way to solve this.
So i downloaded the AudioKit 4.2.2 source code from here [https://github.com/audiokit/AudioKit/releases](url) and then fixed all the warnings => build the frameworks (AudioKit,AudioKitUI) then i have removed the AudioKit 4.4 pod and installed the generated frameworks manually (drag & drop then import embedded Binaries)with the old -lstdc++ and voila , everything back to work perfectly :D 

Xcode10, iOS12

**Comment by NicolasLourenco** [comment]
Why closing this issue, it still relevant 🧐

**Comment by atacand1920** [comment]
yes totally, it's true that i found a way with the 4.2.2 but still can't upgrade AudioKit to the lastest version and also if  i build my project on simulator (just build) , i got many build errors like 'AKVariableDelay' is unavailable: cannot find Swift declaration for this class and all the AK classes are like that , it only work when i run on a real device.

**Comment by NicolasLourenco** [comment]
@aure Still relevant on 4.5

**Comment by daviddelmonte** [comment]
Hi all, I've just encountered this issue with  a slight variation: `SetOutputFormat: (format.sampleRate == hwFormat.sampleRate)`.

I'm using AK 4.5.1. Any suggestions for me to fix?

Many thanks

**Comment by atacand1920** [comment]
Yes , download the 4.2.2 source code and build it with xcode 10 then use the build frameworks script.

**Comment by daviddelmonte** [comment]
Can someone please help Aure. My project is written in Swift 4.2 and I cant use AK 4.2.2.

**Comment by aure** [comment]
@daviddelmonte I'm happy to have a direct look at your project too, if you have the ability to share, publicly or privately. I just want to get to the bottom of this.

**Comment by daviddelmonte** [comment]
@aure I'd be happy to send you my project. Where shall I send it?

**Comment by aure** [comment]
Private GitHub invite or dropbox to my GitHub username at my Github username dot com.

**Comment by aure** [comment]
I don't get an error with I run your app @curzel-it but I do get the same messages to the log as the microphone example.  The app is running though. Your timer never starts and your tracker has strange values for hopSize and peakCount, but once you fix those, it works.

**Comment by aure** [comment]
I'm in personal contact with some of you, but its all too intertwined with implementation and simulator issues, so I'd rather not maintain communication on this particular issue.  StackOverflow, email, or a new specific issue are all fine.
