### ISSUE TITLE
AKPlayer.rate ignored

### ISSUE THREAD

**Issue by mirkin** [AudioKit/AudioKit#1507]
Just updated to the latest AudioKit release and AKPlayer.rate doesn't seem to do anything. 
I've also updated to X Code 10 and swift 4.2.

In the previous version to change the rate I just used AKPlayer.rate and I'm wondering if that worked but shouldn't have worked. Now I'm using AKTimePitch which gives me the functionality I need but was getting with AKPlayer on it's own previously.

**Comment by aure** [comment]
If you just change it to AKDynamicPlayer, and leave everything else the same, the rate property will work.  Why rate is defined at that AKPlayer level, I do no know.

**Comment by ryanfrancesconi** [comment]
AKPlayer knew about the rate property so it could do fade timings and take it into account.
