### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by fredz999** [AudioKit/AudioKit#1508]
<img width="846" alt="screenshot 2018-09-21 at 14 27 44" src="https://user-images.githubusercontent.com/42743729/45903554-080b0a80-bde2-11e8-8daa-1e9bb06c910e.png">

Just started using 4.2 for some stuff on a Udemy course. Im new to Xcode as a dev environment(used a few others) is there a AK 4.2 en route or should I alter some sort of compiler setting, I was trying setting the targeted swift version from 4.2 to 4.0 in the project tab earlier, but to no avail....I think I'm getting something wrong.... anyone any ideas?

**Comment by robertcapsure** [comment]
how are you importing the framework? did you add it manually or through the cocoapod?

**Comment by robtize** [comment]
how are you importing the framework? did you add it manually or through the cocoapod?

**Comment by atacand1920** [comment]
what version of AudioKit did you import or installed with pods? you should use AudioKit 4.4 for swift 4.2

**Comment by fredz999** [comment]
OK... atacand1920 and robotize, thanks so much for the quick reply! So I tried again, and this time I used 4.4 like what atacand said, (zip from AudioKit.io, the IOS one), 
<img width="485" alt="screenshot 2018-09-22 at 15 58 32" src="https://user-images.githubusercontent.com/42743729/45918542-62f33f00-be80-11e8-9f0d-d1b8f0a6a288.png">

unzipped the AudioKit-iOS folder into the project folder which also contains base.Iproj
<img width="796" alt="screenshot 2018-09-22 at 15 49 07" src="https://user-images.githubusercontent.com/42743729/45918477-7fdb4280-be7f-11e8-827c-4e73e3a9ff59.png">

imported the two .framework files within that folder into an Xcode project
<img width="736" alt="screenshot 2018-09-22 at 15 35 51" src="https://user-images.githubusercontent.com/42743729/45918326-325dd600-be7d-11e8-88b3-e31aac0a61db.png">

<img width="706" alt="screenshot 2018-09-22 at 15 38 10" src="https://user-images.githubusercontent.com/42743729/45918349-8963ab00-be7d-11e8-8077-52641d1b1680.png">
put -lc++ into 'other linker flags' in build settings then tried to run the app (without any calls to the imported AudioKit)
but got an error that seemed to be concerned with the library:
<img width="786" alt="screenshot 2018-09-22 at 15 43 21" src="https://user-images.githubusercontent.com/42743729/45918491-b0bb7780-be7f-11e8-9692-c507a3c2e6f4.png">

Any idea what I have missed here?

**Comment by robtize** [comment]
You have to add the library to embedded libraries

**Comment by aure** [comment]
Actually just AudioKitUI, AudioKit is static and only needs to be linked, not embedded.  Not the installation instructions have changed in 4.4

**Comment by fredz999** [comment]
thanks guys

**Comment by gertjanjansen** [comment]
Where can I find the installations instructions for 4.4? I'm trying to upgrade from 4.0 tot 4.4 but I haven't been able to do so. Both with CocoaPods and manually. Can 4.4 be installed with CocoaPods at all?

**Comment by atacand1920** [comment]
no , first , you need to drag and drop AudioKit directory into you main source project , not the on that contains pod, .xcworkspace or .xcodeproj and from there , drag & drop AudioKit.framework into the linked Frameworks and Libraries then add -lc++ .
So before that, you need to unlink AudioKit from your project.

**Comment by gertjanjansen** [comment]
Thanks a lot!

**Comment by atacand1920** [comment]
my pleasure 👍
