### ISSUE TITLE
Playgrounds; Import AudioKitUI

### ISSUE THREAD

**Issue by elliottgriff** [AudioKit/AudioKit#1514]
I was getting errors running Hello World in Playgrounds ("Can't lookup symbols, etc.") 
Not sure why, but importing AudioKitUI fixed it. 
AudioKit is awesome! Thanks a bunch.

**Comment by aure** [comment]
Oh thanks, we'll address this in 4.4.1

**Comment by aure** [comment]
I fixed a bunch of the playgrounds on develop.

**Comment by funct7** [comment]
I'm not convinced this issue is resolved. Maybe I'm doing something wrong, but I get `No such module 'AudioKitUI'` in the `AKPhoneView.swift` file. I checked out the `develop` branch.

**Comment by MWAudioAI** [comment]
Same error: No such module 'AudioKitUI' on everything in AudioKit. Tried develop, cleaning rebuilding etc. with no difference. Is this an Xcode 10 issue?

**Comment by irae** [comment]
@funct7 @MWAudioAI For Playgrounds in [repo]/Playgrounds/ you need to use the terminal to build the frameworks first.

See [Building universal frameworks from scratch](https://github.com/AudioKit/AudioKit/tree/master/Frameworks#building-universal-frameworks-from-scratch)
