### ISSUE TITLE
AKMixer rampTime?

### ISSUE THREAD

**Issue by justKD** [AudioKit/AudioKit#1515]
Is there a reason why AKMixer does not have a rampTime or built-in way to smooth changes to volume?

Is there another way to achieve the effect of combining nodes into a single output, with a volume parameter that can be smoothed?

Thanks in advance for any insight.

**Comment by aure** [comment]
This is not an issue, but a question, which should be posted onto StackOverflow as its answer might be relevant to future users. I'll happily answer over there, okay?
