### ISSUE TITLE
AKSlider does not show a property name

### ISSUE THREAD

**Issue by sihwapark** [AudioKit/AudioKit#1516]
With the AudioKit iOS framework for Swift 4.2, AKSlider doesn't show its property name anymore.

I also tested the iOS Recorder example but it also doesn't draw sliders' property names.

**Comment by megastep** [comment]
Are you talking about Interface Builder?

**Comment by sihwapark** [comment]
No, I mean AKSlider's name which is relying on AKSlider's 'property' variable.
For example:

slider = AKSlider(property: "Gain(dB)")

Here "Gain(dB)" was shown on a screen before but now it isn't.

**Comment by aure** [comment]
Hmm, AKSlider is showing the property name in playgrounds, but that's macOS, I'll check iOS now.

**Comment by aure** [comment]
I have assigned this to @Greenwell but I also made a change so that the label at least shows up (on the bottom, even though it should be on the top)
