### ISSUE TITLE
renderToFile producing empty/silent files

### ISSUE THREAD

**Issue by jbmaxwell** [AudioKit/AudioKit#1519]
Our app queues up midi files that the user wants to render to audio, then, when playback is stopped (or the app enters the background), the queue is run through, audio files rendered, and uploaded. We actually use our own sequencer implementation, but since it seemed simples to do our offline rendering in a "pure AudioKit" context, we created a sequencer instance just used for offline rendering; that's the `renderSequencer` below.
The main process looks like this: 

    for renderItem in self.module.stateManager.offlineRenderQueue {
        // get midi file
        var audioFileURL: URL? = nil
        var audioFileName: String = ""
        if let midiURL = renderItem.midiFileURL {
            let fileManager = FileManager.default
            if !fileManager.fileExists(atPath: midiURL.path) {
                print("Couldn't find midi file to convert at \(midiURL.path)")
            } else {
                if let seq = self.renderSequencer.sequence {
                self.renderSequencer.loadMIDIFile(fromURL: midiURL)
                Conductor.sharedInstance.setInstrument(renderItem.soundID, forOfflineRender: true)
                    for track in self.renderSequencer.tracks {
                         track.setMIDIOutput(Conductor.sharedInstance.midiIn)
                    }
                   // create a cached audio file for render (and as source for upload)
                   let audioCacheDir = self.module.stateManager.audioCacheDirectory
                   // strip name off midi file
                   let midiFileName = String(midiURL.lastPathComponent.split(separator: ".")[0])
                   audioFileName = midiFileName
                   audioFileURL = audioCacheDir.appendingPathComponent("\(midiFileName).m4a")
                      if let audioFileURL = audioFileURL {
                          let settings = [
                              AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
                              AVSampleRateKey: 44100,
                              AVNumberOfChannelsKey: 2,
                              AVEncoderAudioQualityKey: AVAudioQuality.high.rawValue
                         ]
                         let audioFile: AVAudioFile = try! AVAudioFile(forWriting: audioFileURL, settings: settings)
                         // get time in seconds of audio file
                         var duration: Float64 = 0.0
                         MusicSequenceGetSecondsForBeats(seq, (16.0 + 4), &duration)
                         // render sequence
                             do { try AudioKit.renderToFile(audioFile, duration: duration) {
                                 self.renderSequencer.setRate(1.0)
                                 self.renderSequencer.play()
                             }
                         }
                         catch { print("Error performing offline file render!") }
                         }
                     }
               }
         }
     }

**Comment by robtize** [comment]
Are you outputting your sequencer tracks  tracks to a sampler unit?

**Comment by jbmaxwell** [comment]
Yes, we have our Conductor handling the midi events.

**Comment by robtize** [comment]
Instead of setMidiOutput can you try setDestinationUnit I forget the exact property sorry I’m not at my computer right now lol

**Comment by jbmaxwell** [comment]
Well, we're not using an AU directly, so the only thing that seems to make sense is setMidiOutput. There is a setNodeOutput() but it takes an AUNode... But maybe that's still usable? (That is, maybe we could use setDestinationNode() with AudioKit.output?)

**Comment by aure** [comment]
Hi there, I really think its cool that you've made your own sequencer to try to accomplish the file rendering outside of the usual, utilizing midi, which doesn't work in the rendering context.  But I use this issue tracker as a way to organize bug reports and feature requests with AudioKit.  I'd encourage you to follow a few other ways of getting help.  a) Get your questions onto StackOverflow, if they are not there already, b) share a simple project, and if you can't share it publicly, share it with me privately, and c) arrange to have a screen sharing session with me, I'm happy to help as it seems you're putting in the requisite amount of effort to warrant my help (ie. you don't seem like slackers!).  So, unless you can give me a specific thing that is not working with AudioKit (separate from your code), I'll have to close this issue.  Hope to hear from you in other channels soon.

**Comment by jbmaxwell** [comment]
Totally understand. Actually, this -- "...which doesn't work in the rendering context" -- is really what I needed to know, since it isn't explicitly stated anywhere (that I could find). We actually set something up using an AKLazyTap, which will work for our purposes right now. Thanks for the brilliant framework.

**Comment by njarecki** [comment]
JB! Were you ever able to make offline rendering work? we are struggling with the same issue. had it working with DunneSampler and old sequencer but that would only play SFZ files and didn't resect release time so it would cut chords and synths short etc. so we switched to applesampler new audio kit and sequencer but it's not working, garbage outputs, etc. maybe you came up with a fix? Desperate to solve this last bewildering issue! would be forever in your debt.
