### ISSUE TITLE
AKDrip produces only noise.

### ISSUE THREAD

**Issue by Paulcoops** [AudioKit/AudioKit#1520]
Try Dripping Sounds Playground in AudioKit V4.5 Playgrounds.

**Comment by aure** [comment]
It actually makes one drip sound and then goes crazy with noise.  I made a note on the playground here https://github.com/AudioKit/AudioKit/commit/5e22faa167c50aec19ce2c9c14baa00b23095063 and I'll leave this issue open until its fixed too.
