### ISSUE TITLE
Can I record output of AKSampler?

### ISSUE THREAD

**Issue by fuad-adetoro** [AudioKit/AudioKit#1523]
Hi. I'm creating an application which uses the AKSampler and an sfz file to play beats based off of the noteNumber. I want to be able to hit record and begin recording the output of the AKSampler and be able to play it back on a click of a button. Is this possible?

**Comment by fuad-adetoro** [comment]
In the past when creating beats I used an OscillatorBank, AKMusicTrack, AKSequencer and the AKKeyboardDelegate to record and playback beats. I would like to do something similar with the AKSampler.

**Comment by aure** [comment]
Hi there, I am not sure what the issue with AudioKit you are trying to address is.  You should be able to do what you describe.  As this is not necessarily a specific problem with AudioKit but rather an implementation question, I really want to encourage you to ask the questions on StackOverflow.
