### ISSUE TITLE
Improvement to allow variable periodic trigger in amplitude triggeredWithEnvelope by parameters

### ISSUE THREAD

**Issue by jumbopilot** [AudioKit/AudioKit#1525]
Improvement to allow variable periodic trigger adjustment of amplitude by parameters in triggeredWithEnvelope(), e.g. when instantiating or updating an oscillator like 

```
let periodTrigg: AKParameter = 880 / Synth.frequency        // not working
let periodTrigg: AKParameter = 1.0                                         // works

let oscillator = AKOperation.morphingOscillator(
                frequency: Synth.frequency,
                amplitude: Synth.amplitude.triggeredWithEnvelope(
                    trigger: AKOperation.periodicTrigger(period: periodTrigg),
                    attack: 0.01,
                    hold: periodTrigg/2,
                    release: 0.01
                ),
                index: 0
            )
```

Using current AudioKit 4.5, the method AKOperation.periodicTrigger(period: periodTrigg) seems to evaluate only constants and disregards any variables.
Meaning only a call containing a constant  will generate the set of expected triggers using AKOperation.periodicTrigger(period: 1.0)

The same applies also to the parameter 'hold' in triggeredWithEnvelope().

**Comment by aure** [comment]
You can send any AKParameter into periodicTrigger, it doesn't have to be a constant.  What is Synth.frequency?  In any event, I don't think this is a well defined issue with AudioKit but rather an implementation question. I'd much rather have this conversation on StackOverflow, and I can also offer to screen share with you.  But, I will close this as an issue unless we find a specific bug to deal with.

**Comment by jumbopilot** [comment]
Dear Aurelius, delighted to hear from you.
I'm not quite sure whether this is only an implementation issue.

I'd like to achieve a variable period trigger for amplitude of the morphingoscillator. I understand that the AKParameters are re-evaluated at each AKOperation cycle. I could use a separate AKParameter or re-use the available Synth.frequency (of type AKOperation.parameters) as the trigger shall be dependent of the requested frequency in:

`trigger: AKOperation.periodicTrigger(period: periodTrigg)
`
As you say it should work.

I may have been misleading in my 1st request: the AKParameter for trigger seems to be instantiated first (or may be not even when using the initialiser let periodTrigg: AKParameter = 880 / Synth.frequency) and then not updated using the above line of code (leaving the periodTrigg constant).

PS: 
```
struct Synth {
    ...
static var frequency: AKOperation {
        return AKOperation.parameters[SynthParameter.frequency.rawValue]
    }
...
}
```

I'm able to programmatically let Synth.frequency vary in a range from 0 to 3k Hz, which is fine (AK audio sweep output according requested frequency). However, the dependency of the period trigger to the same Synth.frequency is not working.

**Comment by jumbopilot** [comment]
I've found out that 
```
            let periodTrigg: AKParameter = 1 / Synth.frequency.dividedBy(880.0) // is not working
            let periodTrigg: AKParameter = Synth.frequency.dividedBy(880.0) // is working

```

**Comment by aure** [comment]
Well, that's actionable, so I'll have a look this week.

**Comment by jumbopilot** [comment]
The AKParameter operations like plus(), minus(), dividedBy() work fine. Original swift operators like '/' or '*' don't seem to be supported on application level, eventhough no warning is thrown.

I'm missing the AKOperation inverse(x: AKParameter), which does nothing else than 1/x, where x is a AKParameter.

Thxs a bunch

**Comment by aure** [comment]
Hey, could you provide an example playground or project that doesn't work?  It seems too for me.  Here's an extension that you might like, please let me know if it works and I'll add it to AudioKit:

```
extension AKParameter {
    /// Division of parameters
    ///
    /// - parameter denominator: The amount to divide
    ///
    public func inversed() -> AKOperation {
        return AKOperation(module: "/", inputs: 1.0, self)
    }
}
```

I'll close the issue for now since I can't replicate and this solution might work.  You can feel free to continue to comment here.

**Comment by jumbopilot** [comment]
Hi Aurelius, perfect. This addresses the issue. I'd be happy to have it integrated in AudioKit. Thx
