### ISSUE TITLE
AKPlayer setPosition method unavailable with Swift since XCode10

### ISSUE THREAD

**Issue by relpot** [AudioKit/AudioKit#1527]
I noticed that since the AudioKit last versions working with Xcode 10,
the AKPlayer method setPosition is not working anymore, making the app crash.
Does I have missed something ?

**Comment by aure** [comment]
You haven't missed anything, except that it would be great if you could provide more information like what the crash log said the crash was due to. If you have the ability to share a simple project that replicates the crash, that's the fast way to have someone here address it.

**Comment by relpot** [comment]
Yes of course, sorry for the missing code, I'm newbie in reporting issue on GitHub, but I get it.
here is the code I use:

```
let audioFile = try? AKAudioFile(readFileName: "pianoC3.wav")
let player = AKPlayer(audioFile: audioFile!)
        
AudioKit.output = player
try? AudioKit.start()
        
player.play()
player.setPosition(0.5)
```

This code crash on the last line when setPosition is called (tested with the last AudioKit version 4.5.1).
The error log message is: [AudioKit.AKPlayer setPosition:]: unrecognized selector sent to instance
The audio file pianoC3 is a standard mono 16bit/44.1Khz wav file.

Tell me if you need anything else.
Thanks!!

**Comment by aure** [comment]
I think I know what this send should be able to address it later today.

**Comment by aure** [comment]
What's strange about this is that your code is Swift but the error is objective-C.  setPosition is defined in an extension that it looks like might need to be preceded with @objc as of swift4. I'll add that. I don't know why this would affect the Swift however.

**Comment by relpot** [comment]
Ok cool thanks for having check this, I'm glad it's not a big bug to repair but only a swift4 syntax "@objc" missing prefix.
Thanks!

**Comment by aure** [comment]
This appears to be fixed.

**Comment by relpot** [comment]
Aure,
I have made home test with the last Audiokit version 4.5.2, with the AKPlayer setPosition fix, 
but unfortunately it does not fix the issue for me, the app still crashing when using AKPlayer.setPosition.
Did you test it ? Does it works for you ?

**Comment by aure** [comment]
Yeah, I tested it in a playground. Can you send me an invite to the project where its not working?

**Comment by relpot** [comment]
I have done an example project based on the HelloWorld example project from the AudioKit Releases page..
[AudioKit-iOS-4.5.2-SetPosition.zip](https://github.com/AudioKit/AudioKit/files/2482109/AudioKit-iOS-4.5.2-SetPosition.zip)
I did not included the AudioKit framework file because of file size, so once you unzipped the file, you will need to add the AudioKit frameworks file at the unzip folder root.

Hope it helps!

**Comment by ryanfrancesconi** [comment]
I will take a look.

**Comment by ryanfrancesconi** [comment]
Yes, I do see this issue with setPosition. It's all the properties of AKTiming actually - not just setPosition. @dave234 do you know why this might be?

In the meantime, use this instead if you need:
```
        player.startTime = time
        player.play()
```

or just:
`player.play(from: time)`

the stack trace is:

2018-10-16 09:11:38.922653-0700 HelloWorld[15641:1479480] -[AudioKit.AKPlayer setPosition:]: unrecognized selector sent to instance 0x7fbb61d16630
2018-10-16 09:11:38.930613-0700 HelloWorld[15641:1479480] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AudioKit.AKPlayer setPosition:]: unrecognized selector sent to instance 0x7fbb61d16630'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011190429b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001102ff735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000111922fa4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000111908fb6 ___forwarding___ + 1446
	4   CoreFoundation                      0x000000011190ae88 _CF_forwarding_prep_0 + 120
	5   HelloWorld                          0x000000010f7466d0 $S10HelloWorld14ViewControllerC4playyyF + 816
	6   HelloWorld                          0x000000010f7462ca $S10HelloWorld14ViewControllerC11toggleSoundyyypF + 58
	7   HelloWorld                          0x000000010f74631c $S10HelloWorld14ViewControllerC11toggleSoundyyypFTo + 76
	8   UIKitCore                           0x000000011b7897c3 -[UIApplication sendAction:to:from:forEvent:] + 83
	9   UIKitCore                           0x000000011b8c1e85 -[UIControl sendAction:to:forEvent:] + 67
	10  UIKitCore                           0x000000011b8c21a2 -[UIControl _sendActionsForEvents:withEvent:] + 450
	11  UIKitCore                           0x000000011b8c10e6 -[UIControl touchesEnded:withEvent:] + 583
	12  UIKitCore                           0x000000011bf9c334 -[UIWindow _sendTouchesForEvent:] + 2729
	13  UIKitCore                           0x000000011bf9da30 -[UIWindow sendEvent:] + 4080
	14  UIKitCore                           0x000000011b7a3e10 -[UIApplication sendEvent:] + 352
	15  UIKitCore                           0x000000011b6dc0d0 __dispatchPreprocessedEventFromEventQueue + 3024
	16  UIKitCore                           0x000000011b6decf2 __handleEventQueueInternal + 5948
	17  CoreFoundation                      0x0000000111867b31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	18  CoreFoundation                      0x00000001118673a3 __CFRunLoopDoSources0 + 243
	19  CoreFoundation                      0x0000000111861a4f __CFRunLoopRun + 1263
	20  CoreFoundation                      0x0000000111861221 CFRunLoopRunSpecific + 625
	21  GraphicsServices                    0x0000000116b271dd GSEventRunModal + 62
	22  UIKitCore                           0x000000011b788115 UIApplicationMain + 140
	23  HelloWorld                          0x000000010f748a77 main + 71
	24  libdyld.dylib                       0x000000011360a551 start + 1
	25  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by aure** [comment]
Thanks for the failing project.  This made it pretty easy to fix, though I don't understand why it fixes it.
