### ISSUE TITLE
AKClipRecorder vs AKNodeRecorder

### ISSUE THREAD

**Issue by dimagimburg** [AudioKit/AudioKit#1528]
Hi guys, I don't really know where is the right place to ask a question about the intent of a class/node. 

I don't have much of experience with sound processing or producing or tools that people use when dealing with sound processing, and this is the reason why I reached AudioKit. Some of the classes doesn't have a brief description about the intention of them, why are they here of when should I use each of them as opposed to other closely related classes.

My concrete question is about the difference between `AKClipRecorder` and `AKNodeRecorder`. Why do we need to separate between the two of them? When to use each one of them?

Personally I use the `AKClipRecorder` only because I have a callback function that triggered when recording is done, and for example from looking into the source code I didn't understand why the `removeTap` function is located in the `deinit` function and not in `stop` function as the regular AKNodeRecorder.

Thanks a lot, and I hope I didn't violate any rule.

**Comment by aure** [comment]
Hi there, we do use Github issues mostly for fixing things in AudioKit, not answering general questions.  The reason for this is that we find StackOverflow to be a much better place for questions and answers to be archived.  The creators of both those classes are active on StackOverflow so I'd respectfully like to re-ask the question there. Thanks.

**Comment by aure** [comment]
Closed this and asked @dave234 to have a look at https://stackoverflow.com/questions/52734330/when-to-use-aknoderecorded-and-akcliprecorder with me.
