### ISSUE TITLE
Generating file from AKSequencer

### ISSUE THREAD

**Issue by fuad-adetoro** [AudioKit/AudioKit#1529]
Hi, I'm trying to generate a .wav file from the sequencer. The issue that I'm currently facing is that when I render to a file it comes out either empty with the correct duration or with a sinus sound and the correct duration.

I'm using the AKMIDISampler for the AKMusicTrack's output, I'm not 100% if this function works with MIDI data but I need to export the MIDI into a track. 

Please can you let me know if there's any way to export the MIDI into a wav file or similar.

**Comment by aure** [comment]
You should be able to record sound generated by MIDI in real time, but you can not at this time render a midi file in faster than real time because the MIDI clock is not tied to the samples being pulled through the signal chain. In the future, it would be great to post questions to StackOverflow, and then when a bug or clear direction for a fix is found, post an issue. Thanks!

**Comment by fuad-adetoro** [comment]
It's great to know that it's possible. Can you explain to me where I went wrong with my code?

let path = "recordedAudio.caf"
        let url = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.appendingPathComponent(path)
        let format = AVAudioFormat(commonFormat: .pcmFormatFloat64, sampleRate: 44100, channels: 0, interleaved: true)!
        
        do {
            let audioFile = try AVAudioFile(forWriting: url, settings: format.settings, commonFormat: .pcmFormatFloat64, interleaved: true)
            
            try AudioKit.renderToFile(audioFile, duration: self.BitbreaksTrackLength, prerender: {
                self.sequencer.play()
            })
        } catch {
            AKLog("Error when converting")
        }

**Comment by fuad-adetoro** [comment]
Also I did end up opening a question on stackOverflow. If you would like to answer it I would appreciate it greatly.

https://stackoverflow.com/questions/52778524/audiokits-rendertofile-not-working-correctly

**Comment by fuad-adetoro** [comment]
@aure Also I did end up opening a question on stackOverflow. If you would like to answer it I would appreciate it greatly.

https://stackoverflow.com/questions/52778524/audiokits-rendertofile-not-working-correctly
