### ISSUE TITLE
Use built-in microphone with headphones connected

### ISSUE THREAD

**Issue by firewallsol** [AudioKit/AudioKit#1532]
I'm trying to change the internal microphone with the connected headphones but I do not change it

im using        

try! AudioKit.setInputDevice(inputs[1])
        try! mic.setDevice(inputs[1])

I have tried inputs 0,1 and 2 but there is no change.

Thank you

**Comment by aure** [comment]
Noting that this is also on StackOverflow: https://stackoverflow.com/questions/52765236/use-built-in-microphone-with-audiokit-with-headphones-connected but I'll leave this issue open as well. Conversation should happen over on StackOverflow however.

**Comment by aure** [comment]
Hopefully this is now fixed.
