### ISSUE TITLE
How to multiple wav audio files in to single audio file.

### ISSUE THREAD

**Issue by ajay2c9** [AudioKit/AudioKit#1534]
Hi,
1. I have multiple audio tracks like background music, a song without background music. those are in .wav format. How to merge the two songs into a single song... like a song with background music.

2. I have multiple audio tracks like background music, a song without background music. one is in .wav format and another is in .m4a format . How to merge the two songs into a single song... like a song with background music.

Please give suggestion

**Comment by aure** [comment]
Use AKMixer to mix different players into one as demonstrated here:

https://audiokit.io/playgrounds/Basics/Mixing%20Nodes/

 This is not an issue with AudioKit, so I am closing it.

**Comment by ajay2c9** [comment]
HI,
Thank you for the reply and support. From the suggested link, I understand that by using the AKMixer we can play the multiple audio tracks into one audio. I want to save the final track(i.e AKMixer final output i.e All audios into one track) in the local storage.

 Please give suggestions
Thank you
