### ISSUE TITLE
AKPlayer.load(...) do not work properly

### ISSUE THREAD

**Issue by elmath** [AudioKit/AudioKit#1544]
There are multiple interconnected issues:

```
let fistSoundURL = // URL pointing to a short sound file
let secondSoundURL = // URL pointing to a long sound file
```

```
let player = AKPlayer(url: fistSoundURL)!
player.play()
... wait for X ...
player.load(url: secondSoundURL)
```
=> Start playing secondSound at position X and stop after firstSound duration

```
let player = AKPlayer(url: fistSoundURL)!
player.isLooping = true
player.play()
...
player.load(url: secondSoundURL)
```
=> secondSound is looping at the same frequency as firstSound

I have been able to fix the issues, but the AKPlayer flow is quite complex, and I'm afraid that my fix may have side effects. Particularly because my fix looks a lot like undoing changes from previous commits. So I'm not confident enough to submit a pull request.

Commit 8233f7fc25a1ab2951825dc0be926bde162123d8 moves `loop.start = 0` and `loop.end = duration` from `initialize()` to `init(audioFile: AVAudioFile)` so the loop properties are no longer set properly when loading a new file.

Also, in the same commit, calling `pause()` at the beginning of `initialize()` set a value to `pauseTime`. And so the newly loaded file doesn't start playing from the start. I think it should be a call to `stop()` if `initialize()` is called from `load(...)`.

At the end, the call to `resume()` start playing with the `endTime` of the previous file as the call to `preroll(...)` has been removed from `initialize()` in commit 72c9cc105a6536f44edf5c0637fbe2f08e8c4266. Commit fe1efe1d65870403919acafeb22f31ee0bea1009 reintroduce a call to `preroll()` in `load(...)`, but if the player was already playing, it's too late because the call to `resume()` already resumed playback with the `endTime` value of the previous file.

**Comment by ryanfrancesconi** [comment]
Hi, sorry for the delay in responding. This looks pretty good to me in general. I will test your changes. The only change you made that I'm not clear on is:

faderNode?.gain = Fade.minimumGain
from 
faderNode?.gain = gain
