### ISSUE TITLE
AKPlayer keeps looping and completionHandler isn't called

### ISSUE THREAD

**Issue by mikewdeasy** [AudioKit/AudioKit#1545]
When using an AKPlayer, it seems to just continue to loop and never stop playing.

`

        let player = try! AKPlayer(file: audioFile)
        mixer.connect(input: player)
        player.play()

        player.completionHandler = {
            print("Done")
        }
        
        Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { (timer) in
            print("time: \(player.currentTime)")
            if player.isPlaying {
                handler(CGFloat(player.duration))
            } else {
                timer.invalidate()
            }
        }

`

isPlaying is never marked as false and the completion is never called.
This is not the case when using an AKAudioPlayer.

**Comment by nfaulkner9312** [comment]
I'm having this same problem, but only when I have two AKPlayers playing at once

**Comment by ryanfrancesconi** [comment]
is there additional code you aren't putting above? In general, if isLooping is true no completion handler will be called.

**Comment by aure** [comment]
Since there was no response to @ryanfrancesconi's question, I will close this issue until further information is received.

**Comment by buechner** [comment]
I had the same issue and found the problem. It is simply the fact, that the completion handler is set after play() is called. This may be worth documenting somewhere...
