### ISSUE TITLE
 iOS mic recording still has a clicking noise

### ISSUE THREAD

**Issue by sihwapark** [AudioKit/AudioKit#1547]
As previously reported in issue #1311, Mic recording still has a clicking noise. It seems that fix #1399  and #1517 don't resolve the issue.

**Comment by aure** [comment]
Please provide a GitHub project showing the problem.

**Comment by aure** [comment]
We've tested in AK4.5.2 so until more information is added to this issue, I'll close it.  Make sure you're completely up to date. Thanks!

**Comment by hoopes** [comment]
@sihwapark here's an example repo that proved (for me) that the bug was fixed. please feel free to try it.

**Comment by sihwapark** [comment]
Thanks for your information. It is working with no click noise.

**Comment by brunomaiamorais** [comment]
Hello @hoopes I am trying to solve the same problem and it would be helpful to also have access to the repo you mentioned. Can you share it? Thanks!
