### ISSUE TITLE
AKWaveTable initialization error

### ISSUE THREAD

**Issue by ogomez92** [AudioKit/AudioKit#1549]
I think there's an issue with initializing AKWaveTable node. I am trying to change the sample rate of a sound on the fly and I thought AKWaveTable would be the best option to do this. According to the documentation, this initialization function already sets default parameters for most of its parameters to 0, so I would only need to give it a filename:
 self.file=try AKAudioFile(readFileName: fileName)
self.player=AKWaveTable(file: self.file)
I get the following error upon running app: 2018-10-21 17:22:29.276450+0200 AKSoundPool[1479:44079] [default] Unable to load Info.plist exceptions (eGPUOverrides) 2018-10-21 17:22:29.570701+0200 AKSoundPool[1479:44079] [AudioHAL_Client] AudioHardware.cpp:666:AudioObjectGetPropertyData: AudioObjectGetPropertyData: no object with given ID 0 AKWaveTable.swift:init(file:startPoint:endPoint:rate:volume:maximumSamples:completionHandler:loadCompletionHandler:):218:Parameter Tree Failed 2018-10-21 17:22:29.607702+0200 AKSoundPool[1479:44079] [avae] AVAEInternal.h:70:_AVAE_Check: required condition is false:[AVAudioEngine.mm:393:AttachNode: (node != nil)] 2018-10-21 17:22:29.609506+0200 AKSoundPool[1479:44079] required condition is false: node != nil
I also tried setting all of the other parameters to 0 but I get the same error, parameter tree failed.

Is this an audiokit problem or my code?

Thanks.

**Comment by aure** [comment]
I'd need more information than this. It looks mostly like you don't have your nodes hooked up right, but you haven't shared that part of your code.

**Comment by aure** [comment]
Feel free to reopen with more info.
