### ISSUE TITLE
maximum & minimum MIDINoteNumber?

### ISSUE THREAD

**Issue by fuad-adetoro** [AudioKit/AudioKit#1552]
Sorry, this isn't an issue just a question, maybe a silly one too. Can someone let me know what the minimum & maximum MIDIiNoteNumber's are please.

**Comment by fuad-adetoro** [comment]
I'm using AKMIDISampler with a soundfont file and I just wanted to know what my boundaries are.

**Comment by bradhowes** [comment]
According to https://www.cs.cmu.edu/~music/cmsip/readings/davids-midi-spec.htm the MIDI note value is 0 - 127 with middle C being 60. That gives 5 octaves below, and a little more than 5 octaves above.

**Comment by fuad-adetoro** [comment]
@bradhowes Thank you for that, extremely helpful.
