### ISSUE TITLE
Swift 4.2, missing AVAudioSession.setCategory() for iOS 9

### ISSUE THREAD

**Issue by emrahgunduz** [AudioKit/AudioKit#1554]
Currently, Swift 4.2 has a major bug with AVFoundation in Xcode 10's SDKs.
`AVAudioSession.setCategory` is marked with `@available(iOS 10.0, *)` and is not compiling for iOS 9. The method is missing in header files for Swift, but defined for Objective-C.

I see that AudioKit's deployment target is set to iOS 10 for the latest releases. Yet, except a single line in AKSettings.swift file, everything compiles and works pretty well for iOS 9 too.

[The line causing build error is here](https://github.com/AudioKit/AudioKit/blob/c730477047ab5bc9bf56ba5ba1cf02fee6547c16/AudioKit/Common/Internals/AKSettings.swift#L233)...
```swift
try session.setCategory(category.avCategory, mode: .default, options: options)
```
I was able to pass this problem by using
```swift
if #available(iOS 10.0, *) {
  try session.setCategory(category.avCategory, mode: .default, options: options)
} else {
  session.perform(NSSelectorFromString("setCategory:error:"), with: category.avCategory)
}
```

This is not an AudioKit bug or problem, I just wanted to let the developers know that there is a problem and a way to solve it.

**Comment by megastep** [comment]
Yeah that was the main reason we changed the requirement to iOS 10. It seemed odd that they would remove a previous API in Swift 4.2 and definitely felt like a bug. But like often with Apple, there's no guarantee they'll ever actually fix it. :)

If this helps restore compatibility with iOS 9 I'm for it :)

**Comment by megastep** [comment]
Will do
