### ISSUE TITLE
Can't get AKMicrophone working in my code and in AudioKitPlaygrounds after upgrading to MacOS Mojave

### ISSUE THREAD

**Issue by iwuvjhdva** [AudioKit/AudioKit#1557]
Hi,

The built-in microphone works perfectly within the System Sound Preferences dialog but not with the AudioKit apps.

Playground apps just stuck on 0 amplitude / 100 Hz, similar situation is with my code too.

Guess that's related to the new Mojave permissions system: AudioKit doesn't ask for microphone permission while other applications (like Skype, Audacity) do that so that they appear on Security & Privacy dialog under Microphone section.

Can you please assist, is there a way to force AudioKit to ask the user for the mike permission?

Audiokit 4.5.3 / MacOS Mojave / XCode 10.1

**Comment by markjeschke** [comment]
Perhaps, this can help:

https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/RequestingPermission/RequestingPermission.html

At the bottom of this page: 
```
Important: As of iOS 10, all apps that access any of the device's microphones must statically declare their intent to do so. To do this, apps must now include the `NSMicrophoneUsageDescription` key in their Info.plist file and provide a purpose string for this key. When the system prompts the user to allow access, this string is displayed as part of the alert.
If an app attempts to access any of the device's microphones without this key and value present, the app will terminate.
```

**Comment by aure** [comment]
That's probably something the AudioKit Playgrounds need, can you post your fix as a pull request?  I think I know what to do, but since you found it I figure I'll give you first dibs.

**Comment by nodeful** [comment]
#1568
