### ISSUE TITLE
Can add AVAudioUnitDistortion node in AudioKit ?

### ISSUE THREAD

**Issue by kevin-lxh** [AudioKit/AudioKit#1558]
sampel codes:

```swift
let echoNode = AVAudioUnitDistortion()
echoNode.loadFactoryPreset(.multiEcho1)
```

**Comment by aure** [comment]
We never liked this module very much because it is just a set of presets that you can get out of AKDistortion too, if you know the numbers that are used.

**Comment by aure** [comment]
You could follow the AudioKit source code and make this but I'm not interested to have it in AudioKit, unless you can convince me otherwise.  I'll close the issue, but feel free to post a reply.

**Comment by kevin-lxh** [comment]
Thanks for your response. I added a new class (just like AKReverb) to wrap AVAudioUnitDistortion. It's working now.

**Comment by aure** [comment]
That's great! Glad to hear it.  If you want to share it in a pull request I'll have a look.
