### ISSUE TITLE
Missing `AKCallbackInstrumentAudioUnit.h` file

### ISSUE THREAD

**Issue by narner** [AudioKit/AudioKit#1562]
I just pulled the 4.5.4 changes in my project that uses AudioKit for macOS, and am seeing an error at line 153 of `AudioKit.h` of `'AKCallbackInstrumentAudioUnit.h' file not found`.

<img width="937" alt="screen shot 2018-11-07 at 10 32 21 pm" src="https://user-images.githubusercontent.com/2131591/48181630-17d0a680-e2dd-11e8-8085-f000625f153c.png">

**Comment by aure** [comment]
This can't be an error in AudioKit because Trello would have caught it.  I just verified its working on my machine as well. Happy to screen share with you, but I'll close this issue unless I get corroborating evidence.
