### ISSUE TITLE
Possible to use libsndfile 1.0.18+ in order to support decoding OGG Vorbis?

### ISSUE THREAD

**Issue by charneykaye** [AudioKit/AudioKit#1565]
It's noted in 2015 [by @narner on github](https://github.com/audiokit/AudioKit/issues/190) and [by Stephane Peter on the AK google group](https://groups.google.com/forum/#!searchin/audiokit/ogg|sort:date/audiokit/oiuNr9IJXr0/VmZ2mjv5CgAJ) that AudioKit does not decode Ogg Vorbis due to the version of `libsndfile` included in the project.

[`libsndfile` on mega-nerd.com](http://www.mega-nerd.com/libsndfile/) notes that version 1.0.18 adds Ogg/Vorbis support, in 2009.

Is it still true that AudioKit will not decode Ogg Vorbis? Has anyone tried a newer version?

**Comment by megastep** [comment]
The current version of AudioKit is a whole new library that no longer depends on `libsndfile` so that would not help. AFAIK there is no native way to handle Ogg Vorbis for now...

**Comment by charneykaye** [comment]
Thanks for the quick reply @megastep
