### ISSUE TITLE
Calling exportAsynchronously with a name that includes spaces will return an error "is invalid".

### ISSUE THREAD

**Issue by cerupcat** [AudioKit/AudioKit#1567]
When calling exportAsynchronously with a name that includes spaces, the result will error. It appears spaces are allowed in file names on the device, the expected behavior would be to be able to convert files that include spaces in the name.

**Comment by aure** [comment]
I suppose the string needs to be encoded specially.  this is not my forte but I'll have a look.  Do you have a sample project I could run to see the behavior immediately? (so I don't have to set up a lot of stuff to fix this).

**Comment by cerupcat** [comment]
I'll see if I can get a chance to create a sample project since I don't have one right now. If there's a example project included with AudioKit that shows how to export, it might be easy enough to just rename the included file to include a space and use that.
