### ISSUE TITLE
AKMicrophone: it is impossible to set an AV session sample rate other than the device's default

### ISSUE THREAD

**Issue by ClassicalDude** [AudioKit/AudioKit#1572]
AK version 4.5.2: sample rate other than the device's default for the microphone causes the app to crash on defining mic=AKMicrophone() - there are multiple issues that raise that problem.

It is possible to prevent the crash by setting before the input device definition:
        `AKSettings.sampleRate = AudioKit.engine.inputNode.inputFormat(forBus: 0).sampleRate`

However, this means that AudioKit will disregard the sample rate set by AVSession, for instance:
        `try AVAudioSession.sharedInstance().setPreferredSampleRate(44_100)`

For a 48K device, functions such as FFT analysis will still happen with 48K sample rate, even if you try to manually override this setting in FFTTap. Therefore it is difficult to create an app for devices that have different sample rates (for instance, the newest iPad Pro, 3rd generation, has a different hardware sample rate than previous generations).

I'll be happy to provide a sample project, if this issue is not known.

**Comment by aure** [comment]
AudioKit v4.5.5 just released should have this fixed @evenbrenna
