### ISSUE TITLE
[iOS] AKDrip works on simulator but not device

### ISSUE THREAD

**Issue by Paulcoops** [AudioKit/AudioKit#1576]
Hello awesome AudioKit developer,
If I trigger AKDrip after four seconds, AudioKit stops working. But if I change AKDrip's intensity and amplitude to: 0.0 it works. But than every once in while I get either a endless stringy sound, or worse, a frequency sweeping sound and all of iOS audio stops working (till I restart the device or switch audio output)

Tested on iPhone 6, iPad Air, and a report of this issue with an iPhone X(10,6)

Attached a test project of my setup:
[AKDripIssue.zip](https://github.com/AudioKit/AudioKit/files/2604639/AKDripIssue.zip)

It seems to work fine in the simulator, but then on the device it fails. 

Thanks

**Comment by aure** [comment]
I can at least confirm that it is how you describe - working on the simulator but not the phone, thanks for pointing this out.

**Comment by aure** [comment]
I have tested your test project quite a bit and I can't understand what makes the drip act so strange. It doesn't seem to be at the AudioKit level though, I think its just some strangeness with the underlying STK module.  My options are to either remove it or leave it be in this very unpredictable state. What do you think?

**Comment by Paulcoops** [comment]
Hi Aure, Thanks for looking in to this! I've already implemented a sampled version of AKDrip as backup, so I will continue using that. The AKDrip-sound is just too perfect for what I'm working on ;) In case you're curious: https://testflight.apple.com/join/r99I4wDr And thanks again for developing AudioKit!

**Comment by aure** [comment]
I tried to check out your project but got this:

![img_0733](https://user-images.githubusercontent.com/13122/51148924-d399df00-1814-11e9-9b4b-27bcb5f47723.jpeg)

**Comment by Paulcoops** [comment]
I'm sorry about that. It should work now: https://testflight.apple.com/join/r99I4wDr

**Comment by aure** [comment]
It's cool as is, but you could also try the other physical models in AK if you wanted. Nice work, fun game!
