### ISSUE TITLE
currentTime is nan after loading audio file

### ISSUE THREAD

**Issue by hipwelljo** [AudioKit/AudioKit#1577]
Hi all! We have updated AudioKit in our app from version 4.3 to 4.5.4 today and have discovered some interesting behavior around AKPlayer's currentTime property. If we try to get the player's currentTime right after loading a song it is nan, not a number. Previously it was 0. This is occurring in iOS 10-12. I suspect this is not intended behavior. ;)

**Comment by aure** [comment]
Hi, I am back from travels and will have a closer look.

**Comment by nevosegal** [comment]
@aure I looked a bit into this and it looks like `endTime` is only updated after you call `play` on the `AKPlayer`. If that's the intended behaviour then the only issue is that there is a  division by 0 (`endTime - startTime`) in `currentTime`. I can make a PR that checks for that and returns 0.0 instead. What do you think?
