### ISSUE TITLE
Support local path with CocoaPods (Feature Request)

### ISSUE THREAD

**Issue by dave234** [AudioKit/AudioKit#1589]
It would be great if we could link to a local copy of AudioKit using CocoaPods via `pod 'AudioKit, :path => '/Users/Dingus/path/to/local/AudioKit'`. 

I would like to be able to test projects against a non `staged` or `release` branch. Currently the only way to do this is to [include the AudioKit library from source](https://github.com/AudioKit/AudioKit/blob/master/Frameworks/README.md#alternative-include-the-audiokit-library-from-source). This is fine for my local projects, but is problematic when testing an existing project that uses CocoaPods, or when sharing my project + branch with others.

**Comment by aure** [comment]
@megastep How hard will this be to do?

**Comment by megastep** [comment]
The biggest issue here is that our pod doesn't build the library from source, and just grabs the built binaries from a zip file and extracts them to use with your project. So just changing the URL won't do it unless you have a way to specify an alternative location for the zip file, which is easy enough to produce using our scripts.

**Comment by aure** [comment]
Right.  I think this will be part of a bigger issue of having more external dependencies and doing so well.  This will be sometime in early 2019.  So, I'm willing to keep this in the back of our minds rather than as an issue.
