### ISSUE TITLE
AKSampler: createAKSamplerDSP init not called immediately

### ISSUE THREAD

**Issue by Pash237** [AudioKit/AudioKit#1599]
I have a kind of a piano app using AKSampler.  
If I try to produce sound immediately after the app launch, I've got a crash:
```
AudioKitCore::MultiSegmentEnvelopeGenerator::advanceToSegment(int) + 16 (vector:1504)
AKCoreSampler::play(unsigned int, unsigned int, float, bool) + 344 (AKCoreSampler.cpp:0)
```

I tried to look up the issue and found that in “AKSamplerDSP.mm” in `createAKSamplerDSP()` `init` is not called during creation. It is called somewhere later asynchronously (but I can't figure out when).
```
extern "C" void *createAKSamplerDSP(int nChannels, double sampleRate) {
    return new AKSamplerDSP();
}
```

So Sampler won't initialize SamplerVoices, their ADSREnvelope won't be initialized and the app crashes in MultiSegmentEnvelopeGenerator.

If I add `init` here, the crash is gone, but `init` is called twice, which is not good :(

```
extern "C" void *createAKSamplerDSP(int nChannels, double sampleRate) {
    AKSamplerDSP *dsp = new AKSamplerDSP();
    dsp->init(nChannels, sampleRate);
    return dsp;
}
```

As I can see, all DSPs except AKSynth and AKSampler are initialized like this.

Is there anything I can possibly did wrong or there should be `init` indeed?

**Comment by getdunne** [comment]
You must be missing something in your setup code. Have a look at https://github.com/AudioKit/SamplerDemo, to see the usual process for setting up an _AKSampler_. The _init()_ gets called automatically when you call `AudioKit.start()`; you should not call it yourself.

**Comment by Pash237** [comment]
Thank you!
I figured it out.
I was starting AudioKit in background thread, which somehow works, but seems to be not supported.
