### ISSUE TITLE
bad sysex data from AudioKit's receivedMIDISystemCommand

### ISSUE THREAD

**Issue by RandyInNashua** [AudioKit/AudioKit#1606]
I am receiving a sysex message from a device using the following code which I got from the MIDIUtility example project supplied with AudioKit:

`func receivedMIDISystemCommand(_ data: [MIDIByte]){
    if let command = AKMIDISystemCommand(rawValue: data[0]) 
{
        var newString = "MIDI System Command: \(command) \n"
        var hexArray = [UInt8]()
        for bit in data 
{
            hexArray.append(bit)    //this requires 'public typealias MIDIByte = UInt8'
            newString.append(String("\(bit) "))
        }
        updateText("\(newString) \n")
        updateData(hexArray)
    }
    updateText("received \(data.count) bytes of data \n\n")
}`

The sysex I am receiving is very different than what I get when using SysEx Librarian or MIDI Monitor to receive the same sysEx. Both of these apps receive 6 packets of 32,110,110,110,110, and 110 bytes. This is what I expect to get from my MIDI device. 
The AudioKit code gives me 6 packets of 520,1300,20,1538,1294 and 1544 bytes. It looks like some of the data I want is in these packets, but it is spit up by a bunch of 0's.

data I receive from SysEx Librarian and MIDI Monitor:\:
![screen shot 2018-12-12 at 4 21 52 pm](https://user-images.githubusercontent.com/45078749/49934365-2a219f80-fe9c-11e8-9d4e-9164f1ddd1b2.png)

data I receive from AudioKit MIDI Utility example app:
<img width="1190" alt="screen shot 2018-12-12 at 4 22 30 pm" src="https://user-images.githubusercontent.com/45078749/49934459-71a82b80-fe9c-11e8-8770-3333ad72eeee.png">

I asked about this in StackOverflow and it was suggested that it might be a bug:

[https://stackoverflow.com/questions/53752049/sysex-from-audiokits-receivedmidisystemcommand](url)

**Comment by eljeff** [comment]
Can you copy/paste the data you are sending as text so we can test it? Alternatively, share the .syx file from the librarian.
Thanks

**Comment by eljeff** [comment]
I've just tested this w/ the first part of your sysex:
`f000 0138 0070 2000 0101 0c48 4947 4820
4841 524d 4f4e 5900 0000 0000 2002 01f7`

AudioKit MIDI Example project works fine:

> received 32 bytes of data
MIDI System Command: sysex 
F0  0  1 38  0 70 20  0  1  1  C 48 49 47 48 20 48 41 52 4D 4F 4E 59  0  0  0  0  0 20  2  1 F7 

I then replaced the receive function with your code, and I had to comment out 'updateData' as I don't have that function, and it still worked (with formatting issues):

> received 32 bytes of data 
(multiple lines of whitespace here)
MIDI System Command: sysex 
240 0 1 56 0 112 32 0 1 1 12 72 73 71 72 32 72 65 82 77 79 78 89 0 0 0 0 0 32 2 1 247 

So yea...I'm not really sure what is going wrong. It would help to get all the sysex data to try instead of just that one bit I recreated.
Thanks

**Comment by RandyInNashua** [comment]
The updateData() function formats the received data for display in my app so it's not important.  The app is for editing the presets of a TC Helicon Play Acoustic.  To get the sysex for a preset I send a 10 byte package and the Play Acoustic sends back one 32 byte package and five 110 byte packages.  I have attached a typical sysex from the Play Accoustic as recieved through SysEx Librarian and a text file of the sysex as received through MIDI Utility.  I send F0 00 01 38 00 70 45 00  xx F7 to the Play Acoustic. "xx" is replace with the preset number that I am asking for.  I am including the code for the function I use to send this MIDI to the Play Acoustic.  This works fine so probably is not related to the problem.  Not sure how you can recreate this.  Do you have a MIDI device that sends sysex?  If I send a sysex from SysEx Librarian, the data I receive in my app and in MIDI Utility is fine.

[Syx Files.zip](https://github.com/AudioKit/AudioKit/files/2685635/Syx.Files.zip)

**Comment by eljeff** [comment]
> Do you have a MIDI device that sends sysex? If I send a sysex from SysEx Librarian, the data I receive in my app and in MIDI Utility is fine.

Ok that is interesting, I was sending the data directly from Sysex Librarian.

So this only happens over a physical midi device + port + cable? I do have an MPC I could use to send this but I won't be back near it for at least a week. I'll keep you posted if I find anything and let me know if you do as well, thanks.

**Comment by intonarumori** [comment]
@eljeff if you can give me a hint about what code you use to set up your testing, I have plenty of MIDI devices to send sysex between so I could give it a shot.

I did a sysex editor in the past and had a lot of strange behaviour parsing longer messages in Swift.
In the end I had to revert back to a C++  implementation for parsing that actually worked and couldn't figure out the differences.

I also noticed strange bugs while using CoreMIDI over WIFI with the simulator (ex. dropping NRPN parameter addressing etc.)

I will take a look at the AudioKit MIDI implementation and run some tests and report back.

**Comment by RandyInNashua** [comment]
My test setup is pretty much the code you have.  I set up a test project just to send and recv sysex.  You have the send and recv code.  I have a couple of controls to select the correct USB midi port and to send the sysex and catch the return data, and a label and scroll view to display the returned data.  I'm very new to programming with swift and xcode.  I have some experience with Visual Basic, so I'm struggling.  I have everything working except for receiving this sysex data.  Updating the settings and sending them down to the Play Acoustic is working.  I did manage to get the same thing happening with CoreMIDI.  The first time I ask for data, what I get looks good, but when I ask for another preset the data is bad again.  I think it's something I am doing wrong in how I deal with the returned data.  Like I need to clear some buffer or memory, but I am kind of in over my head right now.

**Comment by RandyInNashua** [comment]
the .syx file was from SysEx Librarian.  The .rft file is what I got in MIDI Utility and includes text that is added by the app.

**Comment by eljeff** [comment]
@intonarumori I am simply loading up Sysex Librarian, adding the .syx file to that, sending that to Bus1, and having AudioKit MIDI Utility listen on Bus1.

@RandyInNashua just a confirmation, using your provided script does appear to work out-of-the-box, sending sysex via software
If you use the stock AudioKit MIDI Utility, receiving via hardware, does it still work or break?
Also, which version of AudioKit are you using? Are you on Master or Develop?

> received 110 bytes of data
MIDI System Command: sysex 
F0  0  1 38  0 70 21  4  0  0  1 46  0  0  0  0  0  0  0 50  0  0  0 15  0  0  0  0  0  0  1  8  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  5 7F 7F 7F 6B  0  0  0  B  0  0  0 11  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 5E F7 

> received 110 bytes of data
MIDI System Command: sysex 
F0  0  1 38  0 70 21  3 7F 7F 7F 7C 7F 7F 7F 71  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 38  0  0  0  0 2B F7 

> received 110 bytes of data
MIDI System Command: sysex 
F0  0  1 38  0 70 21  2  0  0  0  2  0  0  0  1  0  0  0 4F  0  0  0 4F  0  0  1 16  0  0  1 16  0  0  0  B  0  0  0  1  0  0  0 66  0  0  0 73  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0 7F 7F 7F 79  0  0  0 3B  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  A 7F 7F 7F 74  0  0  0  6  0  0  0  0  0  0  0  3  5 F7 

> received 110 bytes of data
MIDI System Command: sysex 
F0  0  1 38  0 70 21  1 7F 7F 7F 7A 7F 7F 7F 7A 7F 7F 7F 71 7F 7F 7F 7C  0  0  0 64  0  0  0 64  0  0  0 64  0  0  0 64  0  0  0  0  0  0  0 64  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 17  0  0  1 39  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0 7F  0  0  3 58  0  0  3 58  0  0  3 58  0  0  3 58  0  0  0 32  0  0  0 1E 57 F7 

> received 110 bytes of data
MIDI System Command: sysex 
F0  0  1 38  0 70 21  0 7F 7F 7F 74  0  0  0  6  0  0  0 7D  0  0  0 3E  0  0  0 15  0  0  0 10  0  0  0  0  0  0  0  3  0  0  1  7  0  0  1 46  0  0  0 15  0  0  0 10 7F 7F 7F 62  0  0  0  0  0  0  0  A  0  0  0  0  0  0  0  1  0  0  0 16  0  0  0 16  0  0  0  0 7F 7F 7F 7B 7F 7F 7F 7E 7F 7F 7F 7B 7F 7F 7F 76 7F 7F 7F 6E 2D F7 

> received 32 bytes of data
MIDI System Command: sysex 
F0  0  1 38  0 70 20  0  1  1  C 48 49 47 48 20 48 41 52 4D 4F 4E 59  0  0  0  0  0 20  2  1 F7

**Comment by RandyInNashua** [comment]
yes, my app sends sysex fine, it just does not recv sysex the same as SysEx Librarian and Monitor do from my midi device.  I am using the MIDI Utility from the Example in the Master AudioKit.

**Comment by RandyInNashua** [comment]
over the last few days I have managed to build code using CoreMIDI and another open source midi app called WebMIDIKitDemo to receive sysex from my midi device.  AudioKit and both of these are giving similar but not exactly the same results.  I have looked at the source code for SysEx Librarian and MIDI Monitor.  I don't know Objective C so I can't figure out how or even where those apps receive midi messages, but that seems like something that should be looked into since they both work.  I have another midi device that sends sysex.  I plan to give that a try today to see if it has the same issues.

**Comment by RandyInNashua** [comment]
so I tried 3 other midi devices with similar results.

**Comment by RandyInNashua** [comment]
so I tried 3 other midi devices with similar results.

**Comment by RandyInNashua** [comment]
I have managed to finally get something that works for my app but had to do it using CoreMIDI.  I think it may help with this bug as well so I figured I would share it here.  Turns out that the midi data that is captured when a midi message is received comes in a PacketList with 256 bytes of data as well as other information all presented in a tuple (I believe).  Each of these tuples can have multiple packets of valid midi bytes in various size groups.  the packtList.numPackets is the number of groups of data and the packet.length is the number of bytes of valid midi data in each group.  This code finally got me the results I was looking for:

`
var sysEx = [UInt8]()
func myMIDIReadProc(pktList: UnsafePointer<MIDIPacketList>, readProcRefCon: UnsafeMutableRawPointer?,  srcConnRefCon: UnsafeMutableRawPointer?) -> Void 
{

    let packetList:MIDIPacketList = pktList.pointee
    var packet:MIDIPacket = packetList.packet
    
    for _ in 1...packetList.numPackets { //there can be >1 group of valid data/packetList
        let bytes = Mirror(reflecting: packet.data).children
        var i = packet.length  //number of valid bytes in this group
        var dumpStr = ""
        for (_, attr) in bytes.enumerated() {
            let val = (attr.value as! UInt8)
            if val == 240 { dumpStr += "\n" }
            dumpStr += String(format:"%02X ", val)
            sysEx.append(val)
            i -= 1
            if (i <= 0) { break }
        }//end bytes.enumerated loop

        print("\(dumpStr) #=\(packet.length)")
        packet =  MIDIPacketNext(&packet).pointee
    }//end packetList.numPackets loop
}

`

**Comment by RandyInNashua** [comment]
I think we are almost there on this bug.  Don't give up yet!

**Comment by RandyInNashua** [comment]
I did not close this!

**Comment by eljeff** [comment]
Boom. Got it. Stay tuned...

**Comment by aure** [comment]
Should be addressed by https://github.com/AudioKit/AudioKit/pull/1634 and will be in AudioKit 4.5.7
