### ISSUE TITLE
How to save the output Audio in local storage

### ISSUE THREAD

**Issue by ajay2c9** [AudioKit/AudioKit#1613]
Hi,
I am using Audiokit in my app. By using Below link I'm playing multiple audios files as single audio.
https://audiokit.io/playgrounds/Basics/Mixing%20Nodes/

**My requirement is to save the Mixed audio output in the local storage.**  

Please give suggestions

**Comment by aure** [comment]
Hi this is a question on implementation so you should ask it on stackoverflow to get maximum response.

**Comment by ajay2c9** [comment]
Hi,
 I already asked in stack over flow I didn't get any response.

**Comment by ajay2c9** [comment]
This is the link. Please check once.

https://stackoverflow.com/questions/52853880/how-to-mix-the-audio-files-and-upload-to-the-server
