### ISSUE TITLE
After stopEnvelopeTime is set on AKPlayer, a play() followed by stop() will play at faded volume instead of regular volume. 

### ISSUE THREAD

**Issue by ghubaddole** [AudioKit/AudioKit#1616]
There seems to be no way to reset a FaderNode once it's been started on an AKPlayer node.

let player = AKPlayer()
player.stopEnvelopeTime = 0.1
player.load(audioFile: file)
player.play()  // plays at regular volume
<after a while>
player.stop()
<after a while>
player.load(audioFile: anotherFile)
player.play()   // plays at diminished volume.

I tried the following:
1. setting faderNode.gain to 1.0 ==> still same behavior as above.
2. player.gain to 1.0 ==> same behavior as above.
3. detach faderNode and set it to nil (so that when stopEnvelopeTime is set again, it'll get created once again) ... this works but causes audio latency due to allocation/deallocation in the audio path.

Is there a recommend way to reuse a player node once a fade has been triggered?
it seems loading of an audioFile or a stop() should invalidate the fade but that doesn't seem to be happening.
What am I missing? or is there a bug here?

**Comment by ryanfrancesconi** [comment]
seems like a small bug - will take a look.

**Comment by ryanfrancesconi** [comment]
can you post the rest of your test code? I don't see how your code would ever work in a loop. what am i missing?

**Comment by ryanfrancesconi** [comment]
Try what I'm using to test this -- which is the macOSDevelopment project: AudioKit-develop/AudioKit/Developer/macOS/macOSDevelopment/macOSDevelopment.xcodeproj

![image](https://user-images.githubusercontent.com/2917795/50671619-d3355480-0f87-11e9-8e67-a8090812f7cd.png)

Loading new files into the same player is fine and the stop envelope is correct.

**Comment by ghubaddole** [comment]
I'm trying this on iOS. 
I just created a fresh project with a start and stop button.
pressing start button just loads a file and calls player.play(), pressing stop button calls player.stop().
I've set stopEnvelopeTime to 0.5
This setup works with latest audiokit with the fader being reset correctly. 
Thanks!
g
