### ISSUE TITLE
Crackling noises on iPad / Bluetooth

### ISSUE THREAD

**Issue by romancfischer** [AudioKit/AudioKit#1619]
The app runs fine on my iPhone 6S but I am getting crackling noises on my iPad Pro 2018. 
I am using XCode 10.1 | AudioKit 4.5.0 | iOS 12. I couldn't try 4.5.5. because of the microphone bug. The crackling noises get less when I set up the buffer size but I thought performance should improve, not decrease on an iPad Pro.

Also I am having problems with Bluetooth ( on both devices ) as described here:
https://stackoverflow.com/questions/53771908/using-bluetooth-in-audiokit-generates-glitches-crackles-poor-audio-on-ios

There is also a detailed description of my App's architecture. I am triggering up to 16 samples on the main thread via a customized / leightweight AKMetronome class:

```
import AudioKit

public var handler:AKCallback = {return}

public class HTMetronome: AKOperationGenerator {
    
    let callbackUgen =
        AKCustomUgen(name: "triggerFunction", argTypes: "f") { _, stack, userData in
            let trigger = stack.popFloat()
            if trigger != 0 {
                
                handler()
                
            }
            stack.push(trigger)
    }
    
    /// BPM
    public var tempo: Double = 120 { didSet { parameters[0] = tempo } }
    
    /// Function to perform on every tick
    public var callback: AKCallback {
        didSet {
            handler = callback as AKCallback
        }
    }
    
    /// Initialize the metronome
    @objc public init() {
        
        callback = { return }
        let sporth = "(0 p) bpm2rate metro (_triggerFunction fe) 0 0 sine * dup"
        super.init(sporth: sporth, customUgens: [callbackUgen] )
        parameters = [tempo]
    }
    
}
```

Any idea where to look? Is this a problem in the library or in my code only?
Any help highly appreciated

**Comment by aure** [comment]
Apparently there is a problem with the new iPad Pros that Apple is addressing with an iOS update.

**Comment by aure** [comment]
Thanks let me know if I need to reopen the issue. Trying to close as many as I can for the new year!

**Comment by romancfischer** [comment]
Just wanted to inform you that the cracklers magically disappeared with the update to iOS 12.1.1 at least through the internal speakers. Haven't had the change to test bluetooth yet, but I am relieved that it works now.

**Comment by romancfischer** [comment]
So I realized that the crackling is coming from using the customized AKMetronome class using Sporth. It's working perfectly everywhere ( much better in my case than using AKSequencer triggering an AKCallbackInstrument ) except the iPad. Could someone eventually check this code? I am so sorry, I am really frustrated and really need help with this one :/

**HTMetronome.swift**
```
import AudioKit

public var handler:AKCallback = {return}

public class HTMetronome: AKOperationGenerator {
    
    let callbackUgen = AKCustomUgen(name: "triggerFunction", argTypes: "f") { _, stack, userData in
        
        let trigger = stack.popFloat()
        
        if trigger != 0 {
            handler()
        }
        
        stack.push(trigger)
        
    }
    
    public var tempo: Double = 120 { didSet { parameters[0] = tempo } }
    
    public var callback: AKCallback {
        didSet {
            handler = callback as AKCallback
        }
    }
    
    @objc public init() {
        
        callback = { return }
        let sporth = "(0 p) bpm2rate metro (_triggerFunction fe) 0 0 sine * dup"
        super.init(sporth: sporth, customUgens: [callbackUgen] )
        parameters = [tempo]
    }
    
}
```

**MainViewController**
```
let file = try! AKAudioFile(forReading: Bundle.main.url(forResource: "drum-kick", withExtension: "wav", subdirectory: "Samples")!  )
let sample = AKWaveTable(file: file)

var metro = HTMetronome()
metro.tempo = 120.0
metro.callback = {
     self.sample?.play()            
}

let mixer = AKMixer(self.metro, self.sample)

AudioKit.output = mixer
try! AudioKit.start()

metro.play()
```
Any tip or help appreciated!

**Comment by Charles-Stein-Bose** [comment]
Does anybody know if this issue has been addressed by Apple? I am still experiencing the crackling while using a USB-C headset on the new iPad Pro running iOS 12.3.

**Comment by romancfischer** [comment]
In my case the crackling disappeared since I basically moved everything to DSP level.
But bluetooth speakers still sound considerably worse then through internal speakers or plugged headphones, almost like the OS is using a wrong or super low quality protocol. It doesn‘t seem to matter if A2DP is on or not.

**Comment by Charles-Stein-Bose** [comment]
For me the issue is only when using a USB-C headset. It starts out fine, then turns to crackling, then more severe distortion until I restart the app or exit to the home screen and come back.

**Comment by Artaches** [comment]
I have a related crackling issue with bluetooth. On an iPhone 6+ running 12.4.3.
Specifically the crackling only happens when: using sampling rate other than 44.1kHz + using bluetooth device + having a custom C++ AudioKit node in the audio chain like so: mic -> C++ custom DSP node --> bluetooth headphones.

I have no such issues when using any wired headphones. The issue also doesn't happen with bluetooth when audio chain is just: mic -> bluetooth headphones.
The custom AK DSP node isn't doing anything special (just modifying the buffer streams in place), and again there are no issues with wired headphones.
Any ideas of why this could be happening?
