### ISSUE TITLE
Bluetooth settings mess up MPVolumeView and AVRoutePickerView

### ISSUE THREAD

**Issue by ghubaddole** [AudioKit/AudioKit#1620]
Bluetooth settings seem to be very sensitive!
I had to jump through many hoops to figure out how to seamlessly switch to a newly connected bluetooth device (needs me to listen for notifications of route changes and then for new device added, I stop and start AudioKit to accept the new route). Is there a better way of doing this?

I am displaying a MPVolumeView button on ios 11 and before and an AVRoutePickerView on ios 11+. It shows available bluetooth routes correctly. When I switch back to iPhone, it does so fine and sound comes out of the speaker. However, when I wish to go back to the bluetooth device, it'll spin and do nothing. This is only the case when AudioKit is running - If my app is not running, other apps seem to switch routes back and forth fine. Interestingly, if my app (and audiokit) is running, even the other apps can't seem to switch routes to other bluetooth devices.

My bluetooth settings are so:
            `AKSettings.allowAirPlay = true;`
            `AKSettings.enableCategoryChangeHandling = true`
           ` AKSettings.enableRouteChangeHandling = true`
            `AKSettings.defaultToSpeaker = true`
            `// AKSettings.useBluetooth = true seems to mess up things a bit. E.g. if a new device is connected and this flag is true, it would automatically switch!`
            `AKSettings.bluetoothOptions = [.allowBluetoothA2DP  ] // .allowBluetooth creates many beeps and downgrades audio quality.`

**Comment by aure** [comment]
I'm going to assign this to @dave234 with the hope that it will be addressed by some of the things he's working on already.

**Comment by dave234** [comment]
This issue will be easier to diagnose after AVAudioSession is de-coupled from AudioKit's core functionality.

**Comment by Proudspark** [comment]
Did this issue get resolved? Having similar issues using AK, when user changes from speaker to bluetooth headset - my app crashes. 

@ghubaddole - did you have success when rerouting audio and stopping and starting Audiokit as a workaround?

Thanks

**Comment by aure** [comment]
If the issue were resolved I'd happily have closed it, so no.

**Comment by ghubaddole** [comment]
@Proudspark - unfortunately not. Once audiokit is restarted, the icon changes to blue and detects the bluetooth device routes. then, i can go back to iphone speaker but after that can't go back to any bluetooth. no notifications of route change happens.
