### ISSUE TITLE
Cannot record when showing the record view again.

### ISSUE THREAD

**Issue by sujinnaljin** [AudioKit/AudioKit#1632]
Hello, I am using AudioKit version 4.0.4. I got some error but have no idea to fix this issue so I ask for help.
I used this library to record my voice, and it worked only first time. For example, I pressed the button and moved to recording view. In the recording view everything worked fine. However when I back to previous view, move to recording view, and record my voice again, I cannot hear it.
So I downloaded example projects, opened 'Record' project, and edited storyboard like that situation(I attached the image). It worked well in the first time, but in this time, it crashed when I turned back to first page and click the button to show record view.
I got error like this 
*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: nullptr == Tap()'
***

![2019-01-11 10 20 54](https://user-images.githubusercontent.com/20410193/51007699-e2219580-158b-11e9-9351-ea88c8122f01.png)

**Comment by aure** [comment]
Would it be possible you to upgrade to v4.5.x as what you're using is about a year old now and many changes have occurred since then.

**Comment by sujinnaljin** [comment]
I installed v4.5.6 and run example project 'Record' again, but in this time it crashed immediately. I got error message like this.
```
AVAEInternal.h:70:_AVAE_Check: required condition is false: [AVAudioIONodeImpl.mm:911:SetOutputFormat: (format.sampleRate == hwFormat.sampleRate)]
2019-01-11 13:51:31.644414+0900 Recorder[49747:2834358] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: format.sampleRate == hwFormat.sampleRate'
```

And I found this is similar to issue #1603 . So is this the issue to be fixed?

**Comment by aure** [comment]
Closing until more information is received.  Or else, if the info is relevant to the 1603 issue, we can follow up there.
