### ISSUE TITLE
App crashes with SIGABRT error when receiving a call.

### ISSUE THREAD

**Issue by panzerfausten** [AudioKit/AudioKit#1639]
Hi everyone,

I implemented my app with the Audiokit library for ios. Everytime I receive a call and I try to open my app, this crashes with the SIGABRT error.

I think this is an issue with the Audiokit library since it doesn't happen when I remove the library from the project.

![screen_shot_2019-01-08_at_3 13 41_pm](https://user-images.githubusercontent.com/1682906/51144892-279dc700-1807-11e9-84e7-bb75d959a8ec.png)

thank you!

**Comment by aure** [comment]
I need a little more information or an example project to really address this issue.  Like, does this happen if you just have AudioKit project in your build or just if you import AudioKit, or do you have start the engine?  etc. etc.  I'll have to close the issue until I get more information.
