### ISSUE TITLE
AKMicrophone init crash in objective C

### ISSUE THREAD

**Issue by KozDan** [AudioKit/AudioKit#1641]
I am trying to use AKMicrophone in objective C sample app like this and it crashes for all the pod versions above 4.5.1 on the init step.  iOS version is 12.1.2,  iphone 7plus,  Xcode version 10.1.  It works fine in swift sample app MicrophoneAnalysis.  So I suspect maybe missing @objc somewhere?
@property (strong, nonatomic) AKMicrophone *mic;
Then in ViewDidLoad:
_mic = [[AKMicrophone alloc] init];    // Crashes here.  
I am also getting following error in the console:
2019-01-15 12:56:30.809227-0500 VoiceWavePoc[2856:1473174] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Receiver (type: Receiver)

**Comment by aure** [comment]
I know its not that hard to set up an example project, but it would really help if you could zip one up for us to test. thanks.

**Comment by KozDan** [comment]
Adding the sample zip here and have also sent an invite to you to download.  Thanks
[Voice.zip](https://github.com/AudioKit/AudioKit/files/2766375/Voice.zip)

**Comment by aure** [comment]
On my iPhoneX it crashes on either 4.5.1 or 4.5.6 the same way.

**Comment by aure** [comment]
Hopefully this fixes it.

**Comment by KozDan** [comment]
Thanks look forward to testing it soon.  Maybe add a podspec to develop branch...

**Comment by aure** [comment]
I just put it onto our staging branch which you can use in about an hour using:

https://github.com/AudioKit/SongProcessor/blob/develop/Podfile#L5

**Comment by tudorached** [comment]
I am having the same problem.

Voice.zip throws the same error.

Did you fix it?

**Comment by KozDan** [comment]
I believe instead of @objc prefix to classes, to make it global without linking issues should try just public prefix and inherit from NSObject.  I recently created a pod in swift and saw that those fixes helped.  Here is a link which explains it better:
https://medium.com/ios-os-x-development/swift-and-objective-c-interoperability-2add8e6d6887

**Comment by aure** [comment]
AKMicrophone does inherit from NSObject though.

**Comment by KozDan** [comment]
right but you are using @objc prefix in addition to public.  In above article she has pointed out that its an option to use @objc or public and NOT both.  Thats my current take
So my suggestion is trying just public/open in your class and remove @objc from init and other places
https://github.com/AudioKit/AudioKit/blob/master/AudioKit/Common/Nodes/AKNode.swift

**Comment by aure** [comment]
just for AKMicrophone or all of AudioKit?

**Comment by aure** [comment]
I wonder what a good test is - I could easily remove all @objc from AudioKit.

**Comment by KozDan** [comment]
Could try one class first and then if it works all across.  We still don't know if there are more issues in that class.  But thats where it is failing in the sample I have added( _mic = [[AKMicrophone alloc] init];).  Also I did add this import to be sure of which is missing in the attached sample I think
#import <AudioKit/AudioKit-Swift.h>

**Comment by KozDan** [comment]
Test case would be to init

**Comment by aure** [comment]
@KozDan Just for the class declarations? Dynamic vars need the @objc, but methods and inits?

**Comment by KozDan** [comment]
just public for vars and methods should be suffice.

**Comment by aure** [comment]
dynamic vars require the @objc for some reason, but I'll test the rest.

**Comment by aure** [comment]
@KozDan Looks like a lot of @objc were at least unnecessary, perhaps destructive.

**Comment by aure** [comment]
Starting the process: https://github.com/AudioKit/AudioKit/commit/f59da655b035e769e4d9b0e98e8d71621bc50690

**Comment by aure** [comment]
I'm definitely seeing cases you need the @objc.

**Comment by aure** [comment]
I don't see in this link https://medium.com/ios-os-x-development/swift-and-objective-c-interoperability-2add8e6d6887
where it says not to have both @objc and NSObject inheritance. I'm all for cleaner code, so I'm happy to remove unnecessary text, but other than that, what's the benefit/harm?

**Comment by KozDan** [comment]
yes author does say there are two solutions(step 6).  I did some more digging and there seem to be simpler way to handle multiple vars and functions to be marked for Objective C compatibility:"@objcMembers"
https://useyourloaf.com/blog/objc-warnings-upgrading-to-swift-4/  
Not sure impact on Swift version < 4.0
Also looks like many other libraries have started migrating away from @objc
https://github.com/NativeScript/ios-runtime/issues/663
For me I had to cleanup objc and switch to only public.  I have set it for Swift 3.0 in build setting

**Comment by aure** [comment]
Step 6 only provides the two solutions but says nothing about what would be wrong if you did both.  @objcMembers looks cool, but you're right about the swift < 4 question.

**Comment by aure** [comment]
Ivan Buhov over on that NativeScript issue said it well "To make Swift APIs visible by the Objective-C runtime you have to mark them with @objc attribute or to derive from Objective-C interface."

**Comment by tudorached** [comment]
I fixed it adding

` [mic start];
    [tracker start];`

after

    `[AudioKit startAndReturnError:&portErr];`

Here's a demo project:

[TestMicrophoneObjC.zip](https://github.com/AudioKit/AudioKit/files/2824223/TestMicrophoneObjC.zip)

**Comment by KozDan** [comment]
hi tudorached,  your example does work i.e init of AKMicrophone succeeds in viewdidload.  But for me it still is throwing exception on its init in ViewdidLoad.  I did pod deintegrate and pod install. I have attached zip here. 
[VoiceWavePoc.zip](https://github.com/AudioKit/AudioKit/files/2824671/VoiceWavePoc.zip)

**Comment by tudorached** [comment]
@KozDan 

Fix:

Replace:

`tracker = [[AKFrequencyTracker alloc] init:mic hopSize:10 peakCount:10];`
with:

`tracker = [[AKFrequencyTracker alloc] init:mic hopSize:512.0 peakCount:20.0];`

**Comment by KozDan** [comment]
Daniel,  yes that worked.  I need to understand this API a bit... Thank you so much appreciate that.

**Comment by tudorached** [comment]
Cheers!

@aure 

Can you please tell us what **hopSize** and **peakCount** mean and actually do? 

I have tried to find some info but didn't find any. If this question seems trivial, please know I am noob in audio.

Thank you for AudioKit!

**Comment by aure** [comment]
All I really know is imparted in the comments in the code, which I just looked at, pretty pathetic:

    /// - parameter input: Input node to process
    /// - parameter hopSize: Hop size.
    /// - parameter peakCount: Number of peaks.
    ///
    @objc public init(
        _ input: AKNode? = nil,
        hopSize: Int = 4_096,
        peakCount: Int = 20) {

Definitely seems like a hop size of 10 is problematic, perhaps if I understood it more we could add a minimum.

**Comment by KozDan** [comment]
@Aure,  real question is why is it an issue only in objective C.  Swift version works just fine.

**Comment by aure** [comment]
Still happening in 4.6?
