### ISSUE TITLE
pitch shift quality

### ISSUE THREAD

**Issue by ghubaddole** [AudioKit/AudioKit#1647]
I have short samples (1-2 seconds) and pitch shifting for these seems to be a bit of a pain.

AKTimePitch creates a large amount of artifacts, while AKPitchShifter, though better, creates graininess. Making the window and crossfade windows larger results in double sounds (or a weird echo effect). Also, larger windows tend to cause large latencies in the sound production.

Is there a high quality time shift algorithm for shorter samples I can use? Or can I tune the existing ones into giving me better performance?

**Comment by aure** [comment]
AKTimePitch has the "overlap" proper and AKPitchShifter has the "windowSize" property which can be adjusted and tested.  These are the only two algorithms we currently have in AudioKit.
