### ISSUE TITLE
Output to a specific channel

### ISSUE THREAD

**Issue by nikolamajcen** [AudioKit/AudioKit#1648]
Hi,
is there any way to set audio output to a specific channel?
By that, I mean using an e.g. audio device with 8 channels and put a song to channel one, another song to channel two etc. This is the case for Mono. If using stereo, the first song will go through channels 1 and 2, while another song will go through 3 and 4.

I went through examples, code documentation, and other sources, but I did not find an example or usage of things like that.

**Comment by aure** [comment]
This is not an issue with AudioKit, but a question, which we normally like to answer on StackOverflow, but to save you the trouble, we don't have output channel support at this time. We should have that this year though.
