### ISSUE TITLE
Change plot visualization

### ISSUE THREAD

**Issue by donpironet** [AudioKit/AudioKit#1651]
I'm using the library to visualize a wave. Now I can't find how I can tune the wave to look like my design:

![wave](https://user-images.githubusercontent.com/6583650/51493256-14659b00-1db5-11e9-9ded-5cce05fb9825.png)

I'm using this plot:

```
      let plot = AKNodeOutputPlot(micCopy1, frame: .zero)
        plot.translatesAutoresizingMaskIntoConstraints = false
        plot.plotType = .buffer
        plot.shouldFill = true
        plot.shouldMirror = true
        plot.color = UIColor.red
        plot.gain = 2

  private lazy var silence: AKBooster = {
        let micCopy2 = AKBooster(mic)
        let tracker = AKFrequencyTracker(micCopy2, hopSize: 4096, peakCount: 20)
        let silence = AKBooster(tracker, gain: 0)
        
        return silence
    }()
```

I tested with changing values like the plottype and fill, mirror but I can't get close.

Is this not possible or am I looking in the wrong direction?

**Comment by aure** [comment]
Hi, this is not really an issue with AudioKit, but a question, which we normally like to answer on StackOverflow.  AudioKit provides basic graphing functionality, but to give it your own flair, you'll need to subclass or copy the code from our plots, and then create graphics in your own style.

**Comment by ethi1989** [comment]
> I'm using the library to visualize a wave. Now I can't find how I can tune the wave to look like my design:
> 
> ![wave](https://user-images.githubusercontent.com/6583650/51493256-14659b00-1db5-11e9-9ded-5cce05fb9825.png)
> 
> I'm using this plot:
> 
> ```
>       let plot = AKNodeOutputPlot(micCopy1, frame: .zero)
>         plot.translatesAutoresizingMaskIntoConstraints = false
>         plot.plotType = .buffer
>         plot.shouldFill = true
>         plot.shouldMirror = true
>         plot.color = UIColor.red
>         plot.gain = 2
> 
>   private lazy var silence: AKBooster = {
>         let micCopy2 = AKBooster(mic)
>         let tracker = AKFrequencyTracker(micCopy2, hopSize: 4096, peakCount: 20)
>         let silence = AKBooster(tracker, gain: 0)
>         
>         return silence
>     }()
> ```
> 
> I tested with changing values like the plottype and fill, mirror but I can't get close.
> 
> Is this not possible or am I looking in the wrong direction?

how do you fix it , can you help me ,I want to this effect
