### ISSUE TITLE
Unable to use iPhone Speaker as output while bluetooth headset is used as mic

### ISSUE THREAD

**Issue by PrinceAbraham** [AudioKit/AudioKit#1654]
Currently this is my code.
`        AKSettings.playbackWhileMuted = true
        AKSettings.audioInputEnabled = true
        AKSettings.useBluetooth = true
        let mic = AKMicrophone()
        let session = AKSettings.session
        do {
            try session.setCategory(.playAndRecord, mode: .default)
            try session.overrideOutputAudioPort(.speaker)
            try session.setActive(true)
        } catch {
            print("Couldn't override output audio port")
        }

        AudioKit.output = mic
        try! AudioKit.start()`
Seems like the session is not overriding the audio port from my bluetooth headphones to phone speaker.

**Comment by aure** [comment]
Is this a problem with AudioKit?  It seems like you're using AVAudioSession directly.

**Comment by PrinceAbraham** [comment]
The issue might be that since I'm using a headset I can't playback on a different speaker. Can you confirm this behavior? Solution would be to use a bluetooth mic (only mic), right?

**Comment by eljeff** [comment]
I can't comment on this exact problem, but I have done it reverse - I have been able to use the phone microphone and a bluetooth speaker at the same time.

**Comment by aure** [comment]
Can you provide a sample project for us to reproduce this issue?

**Comment by PrinceAbraham** [comment]
It's the same code as given above. I'm using a bluetooth mic, which for some reason shows up as output, I'm trying to get iput from the mic and play back through a bluetooth speaker

**Comment by PrinceAbraham** [comment]
> I can't comment on this exact problem, but I have done it reverse - I have been able to use the phone microphone and a bluetooth speaker at the same time.

How did you achieve this? Currently my bluetooth speaker cuts off most of the words I say

**Comment by kingsofteng** [comment]
> I can't comment on this exact problem, but I have done it reverse - I have been able to use the phone microphone and a bluetooth speaker at the same time.

Can you please share your code snipped for that?

**Comment by kingsofteng** [comment]
> > I can't comment on this exact problem, but I have done it reverse - I have been able to use the phone microphone and a bluetooth speaker at the same time.
> 
> How did you achieve this? Currently my bluetooth speaker cuts off most of the words I say

@PrinceAbraham  Could you resolve this issue?

**Comment by BrianBecker** [comment]
Does it cut off the beginning of your words or after short pauses? If so this is due to your bluetooth speaker going into bypass mode to save battery. 

An simple fix is to have an mp3 file looping and playing with the volume of 0. To prevent from a mistaken output, I have a file called “silence.mp3” which plays whenever my user turns on “Bluetooth Keepalive"

------
Brian Becker
573.778.6500

On April 4, 2019 at 1:53:54 PM, Software Engineer (notifications@github.com) wrote:

I can't comment on this exact problem, but I have done it reverse - I have been able to use the phone microphone and a bluetooth speaker at the same time.

How did you achieve this? Currently my bluetooth speaker cuts off most of the words I say

@PrinceAbraham Could you resolve this issue?

**Comment by Apathia** [comment]
Brilliant.

**Comment by kingsofteng** [comment]
Still not sure...
Can you please share the code snippet for that?
@BrianBecker  @Apathia

**Comment by BrianBecker** [comment]
Off the top of my head? Something like:

var bluetoothKeepAlive: AKPlayer!
var isKeepAlive: Bool {
        get {
            return bluetoothKeepAlive.isPlaying
        }
        set(on) {
            if on { bluetoothKeepAlive.play() }
            else { bluetoothKeepAlive.pause() }
        }
    }
let path = Bundle.main.path(forResource: "silence.mp3", ofType:nil)!
audioUrl = URL(fileURLWithPath: path)
bluetoothKeepAlive = AKPlayer(url: audioUrl)
bluetoothKeepAlive.isLooping = true
bluetoothKeepAlive.volume = 0.0
//add bluetoothKeepAlive to the mix
AudioKit.output = AKMixer(output1, output2, bluetoothKeepAlive)
do {
   try AudioKit.start()
   bluetoothKeepAlive.play()
} catch {
   print("CRAP!")
}






------
Brian Becker
573.778.6500

On April 4, 2019 at 8:01:37 PM, Software Engineer (notifications@github.com) wrote:

Still not sure...
Can you please share the code snippet for that?
@BrianBecker @Apathia

**Comment by kingsofteng** [comment]
Hi @BrianBecker 
Thanks for your code,
I am unable to use <bluetooth headset> as output while <built-in mic> is used as mic...

**Comment by kingsofteng** [comment]
Hey guys,
Do you have any suggestions regarding this issue?

Unable to use iPhone Speaker as output while bluetooth headset is used as mic #1654
Unable to use bluetooth headset as output while built-in microphone is used as mic #1654

**Comment by aure** [comment]
This looks like a problem we might not be able to address.

**Comment by kingsofteng** [comment]
> This looks like a problem we might not be able to address.

Correct.

**Comment by tallen11** [comment]
> I can't comment on this exact problem, but I have done it reverse - I have been able to use the phone microphone and a bluetooth speaker at the same time.

@eljeff would you be able to share how you accomplished this? Currently trying to do the same thing. Thanks!

**Comment by heyarny** [comment]
> I can't comment on this exact problem, but I have done it reverse - I have been able to use the phone microphone and a bluetooth speaker at the same time.

Do you have an example setup for this case?
