### ISSUE TITLE
Details on AudioKit.start() bug mentioned on LoopbackRecording Example

### ISSUE THREAD

**Issue by irae** [AudioKit/AudioKit#1662]
I am about to start writing a multi-track recorder app and I was studying and exploring AudioKit documentation, Examples and StackOverflow questions related to recording in sync with a track playing. I came across a intriguing piece of code by @dave234 in the `LoopbackRecording` example:

https://github.com/AudioKit/AudioKit/blob/ff43976916a96756aa325a205f3087307e82ad04/Examples/iOS/LoopbackRecording/LoopbackRecording/ViewController.swift#L93-L103

Is there still some kind of problem with `AudioKit.start()` as of AudioKit 4.5.5? Should I be avoiding it for advanced recording scenarios? And lastly, in case this is outdated, could someone already proficient with `AKClipRecorder` and `AudioKit.engine` update the example with current best practices?

Thank you very much for your time (and this awesome open source library, really)

**Comment by dave234** [comment]
At the time I wrote this, there were some issues around microphone usage and AudioKit’s implicit AVAudioSession management. Bypassing AudioKit.start() was just a lazy way to avoid these issues. I would suggest using AudioKit.start() unless there are specific issues that arise.

**Comment by irae** [comment]
Thanks for the fast reply! Good to know things should be fixed.

I'll do the following: I'll test a version of the example with `AudioKit.start()` and also try my own implementation. If everything works out fine, I'll make a PR to change the example and remove comments.
