### ISSUE TITLE
Organ.wav is missing from iOS and macOS package examples

### ISSUE THREAD

**Issue by tomshen** [AudioKit/AudioKit#1666]
The iOS AudioUnitManager and macOS SimpleAudioUnit examples expect Organ.wav to be present at `AudioKit-{iOS,macOS}/Common/Organ.wav` and fail to build. Downloading [Organ.wav](https://github.com/AudioKit/AudioKit/blob/master/Examples/Common/Organ.wav) and moving it to that path makes the builds succeed.

**Comment by aure** [comment]
I looked at the Examples and they work for me. Can you explain the steps to reproduce this?

**Comment by tomshen** [comment]
1. Go to releases: https://github.com/AudioKit/AudioKit/releases
2. Download AudioKit-macOS-4.5.6.zip
3. Unzip.
4. Open SimpleAudioUnit.xcodeproj in the Examples folder

**Comment by aure** [comment]
@megastep is this fixable in the build script? Might be time to talk about moving this example into its own repo and set up with Cocoapods.

**Comment by megastep** [comment]
Weird, I wonder if the script is really responsible here though...

**Comment by aure** [comment]
Organ.wav is placed in the regular repo in a place accessible to both iOS and macOS projects, but once it gets packaged up both release zips don't have the file.

**Comment by megastep** [comment]
Ugh, so we could add a special case to the script for this, but it might just be easier to move the file to both the iOS and macOS project directories. It's not a huge file and it would avoid complicating the scripts further for something so small.

**Comment by megastep** [comment]
Actually it was a simple enough change and that should now be fixed in develop.
