### ISSUE TITLE
How to get audio's frequency when using the AKTrackedFrequency Class?

### ISSUE THREAD

**Issue by aidewoode** [audiokit/AudioKit#167]
Hi, everyone. 

I am writing an app and want to get audio's frequency . Then I read the AudioKit's Docs, then I found the AKTrackedFrequency Class, And I think it meet my purpose.  But I don't know how to get the frequency value from a instance of AKTrackedFrequency Class. The AKTrackedFrequency's doc don't show any property or method I can use to get the frequency value.

So I want to know how to get audio's frequency. If there have another method to get the frequency value or I use the AKTrackedFrequency in wrong way?

**Comment by aure** [comment]
AKTrackedFrequency _Is_ the frequency.  It has a value associated with it that is the value you're after.  But, if you want to access outside of the instrument, turn it into an instrument property.  Depending on what you want to do you may be more comfortable using the AKInstrument implementation called the AKAudioAnalyzer which has a frequency property you can access.   For an example of thsi you can check out the AudioKitDemo projects.

**Comment by aidewoode** [comment]
@aure Thanks :+1:
