### ISSUE TITLE
AKPlayer resume bug

### ISSUE THREAD

**Issue by apprithm** [AudioKit/AudioKit#1674]
Im not sure if this is a bug or intended because this issue can be solved outside of the framework.(Preventing user to set pauseTime == duration) but this bug only started to happen at v3.6 and the dev branch. I discovered this problem because my app allow user to  scroll the progress bar of the audio file, if I scroll all the way to the end, and click play it will continue to play without sound.

**Reproduce:**  Set pauseTime to the duration and call resume again. It will start to play out of boundary. 

**Expected behavior:** AudioKit should be able to detect the pauseTime is now == duration. And to start to play restart from the beginning.

**Comment by ryanfrancesconi** [comment]
sounds fine - will check.
