### ISSUE TITLE
AKPlayer reporting wrong startTime after finished playing the track.

### ISSUE THREAD

**Issue by apprithm** [AudioKit/AudioKit#1675]
Im not sure if this is intended or a bug, but it only happens on 3.6 and the dev branch:

**Reproduce:** set pauseTime to a time other than 0, call resume(), wait till it finish play the whole track. Then call play(). It will start from where it previously paused instead of the beginning.

**Expected behavior:** The startTime should report 0 after the track is finished playing. This will effectively play the track from the beginning.

**Comment by ryanfrancesconi** [comment]
Thanks I'll check!
