### ISSUE TITLE
AKSamplerMetronome delay

### ISSUE THREAD

**Issue by ChaseStas** [AudioKit/AudioKit#1677]
Hi. I'm making a metronome app and use AKSampleMetronome class. I did synchronization between devices with Ableton link so they could play together. I start playing and after a while sound on the device starts to delay and after couple of minutes I can clearly hear it.
The thing is beat count synchronized correctly but the sound that comes from the phone is not.
This bug is not on all devices, on some of them it's working great, no delay.
for synchronization I call setBeatTime once on start

Any suggestions what it might be?

**Comment by aure** [comment]
It would be great if you could ask this question on StackOverflow so there could be a more permanent and findable record of the answer. Could you move it there and post a link?

**Comment by ChaseStas** [comment]
[link](https://stackoverflow.com/questions/54645681/akmetronomesampler-delay)
