### ISSUE TITLE
AudioKit buffer to start and stop recording while displaying rolling buffer?

### ISSUE THREAD

**Issue by scheung38** [audiokit/AudioKit#168]
How can I implement in Swift something similar to this project?

http://www.syedharisali.com/projects/EZAudio

**Comment by megastep** [comment]
Funny that you mention that, we actually use some of EZAudio internally to implement some of the rolling waveform plots in AudioKit.

**Comment by scheung38** [comment]
Could you please show me? as I could not add AudioKit to my project since upgrade to Yosemite as Cocoapods doesn't work anymore

for example:

pod 'EZAudio', '~> 0.0.4'

usr/local/var/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'cocoapods' (>= 0) among 154 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/usr/local/rvm/gems/ruby-1.9.3-p194:/usr/local/rvm/gems/ruby-1.9.3-p194@global', execute `gem env` for more information
	from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
	from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /usr/local/var/rbenv/versions/2.1.5/bin/pod:22:in `<main>'

**Comment by megastep** [comment]
I can't really help you with the CocoaPods issue (that's a Ruby problem). However I would point you to the `AudioKitDemo` sample project that ships with the library (there's a Swift version), as it uses the rolling waveform plots to show the audio input in the analysis tab.

**Comment by scheung38** [comment]
Tried to build the suggested AudioKitDemo but the libAudioKit iOS Dyamic.a seems to be missing? as build is successful but nothing shown on my iPhone device?

**Comment by megastep** [comment]
Make sure to follow the instructions here to set up your project (using the static library is easier) : 

https://github.com/audiokit/AudioKit/blob/master/INSTALL-iOS.md

**Comment by scheung38** [comment]
This also allows microphone input and displays the audio in rolling buffers?

**Comment by megastep** [comment]
Yes, you should see that in the analysis tab of the app.

**Comment by scheung38** [comment]
I added  AudioKit.xcodeproj into my project, but still cannot see the AudioKit iOS Dynamic? Please advise. Also cannot run the AudioKitDemo which already has this AudioKit.xcodeproj inside?

**Comment by megastep** [comment]
You could try in the simulator first, and obviously you will need some source of audio going on through the microphone to see anything.

**Comment by scheung38** [comment]
What does it mean when Run -> Success but App not doing anyway at all? Both in device or in simulator?

**Comment by narner** [comment]
When you say 'the app is not doing anything at all', you are referring to the AudioKitDemo, correct?

**Comment by scheung38** [comment]
Yes the AudioKitDemo can Build, but nothing happens, no errors or warning. But do see that under the AudioKit.xcodeproj -> Products -> libAudioKit OSX.a in red, indicating missing lib? But then the list of Targets visible are AudioKit iOS Static, AudioKit iOS Dynamic and AudioKit OSX?

**Comment by aure** [comment]
If you need help building the project, I'd be willing to do a screen share.  It's pretty straightforward and heavily tested so I bet it is something on your system that wouldn't be too hard to debug.

**Comment by scheung38** [comment]
Thanks Aure, I do see video demo but it is for Obj C setup? 

There are few things I would like, record audio and also accelerometer reading with rolling buffer display and then capture these on a per user basis if possible using Parse.

**Comment by aure** [comment]
Not much difference for Obj-C or Swift as far as setup is concerned.  Does the Objective-C app work for you?  Might be a good place to start.  You will have to do all this custom coding yourself, don't expect any libraries to do everything for you! :)

**Comment by scheung38** [comment]
Sure of course, but getting started in installation was not straightforward.

**Comment by scheung38** [comment]
How to capture the duration of the audio? Thanks Aure and team

**Comment by scheung38** [comment]
Is it possible to synchronize stock market data movement with sound to help trading?

**Comment by narner** [comment]
Yes, it is possible to do synchronize data with sound. However, the AudioKit Users Group (https://groups.google.com/forum/#!forum/audiokit) is a better place to discuss that, rather then on GitHub.

**Comment by scheung38** [comment]
With stock market data too?
