### ISSUE TITLE
Can we render .mp3 file? 

### ISSUE THREAD

**Issue by PawanmSpaceo** [AudioKit/AudioKit#1680]
Can we render a .mp3 file? 
because currently, I'm getting an error while rendering mp3 file :/

**Comment by aure** [comment]
Is this a question about your abilities? I don't know you or your code. :) You should probably ask this question on StackOverflow and provide some details about what you are trying.

**Comment by PawanmSpaceo** [comment]
I'm using below code to render
`let audioFile = try AKAudioFile(forWriting: self.exportURL, settings: self.player!.audioFile!.fileFormat.settings, commonFormat: .pcmFormatFloat64, interleaved: true)
            
            try AudioKit.renderToFile(audioFile, duration: self.player!.duration, prerender: {
                self.player?.play()
            })`
