### ISSUE TITLE
AKSampler broken in 4.6

### ISSUE THREAD

**Issue by rzil** [AudioKit/AudioKit#1687]
My app uses AKSampler with AKMIDINode and AKSequencer. It was working perfectly in 4.5.6 and earlier. After upgrading to 4.6 it doesn't produce any sound. There are no errors printed to console either. Help?

**Comment by aure** [comment]
This might have been fixed already in develop, so you can either use that, switch back to 4.5.6 or wait for 4.6.1 which should be soon.

**Comment by aure** [comment]
Check this: https://github.com/AudioKit/AudioKit/pull/1681

**Comment by CooperCodeComposer** [comment]
Not sure if this is related but after upgrading to 4.6 I get a crash from AKMIDISampler whenever I start recording. 

0 closure #1 in AKMIDISampler.enableMIDI(_:name) 

Switching back to AK 4.5.6 - will check out 4.6.1 when available. Thx!

**Comment by aure** [comment]
Please check 4.6.1 and reopen this issue if necessary.
