### ISSUE TITLE
[AudioKit outputDevices] only returning the current output device

### ISSUE THREAD

**Issue by willsmillie** [AudioKit/AudioKit#1688]
I'm working on implementing an output selector in my app, but cannot seem to get a list of available outputs, only the current output.  

```
    for (AKDevice *device in [AudioKit outputDevices]) {
        NSLog(@"Device: %@", device);
    }
```

    Device: <Device: Receiver (Built-In Receiver)>

**Comment by willsmillie** [comment]
Decided to use Apple's AVRoutePickerView which will display the stock output select.

**Comment by aure** [comment]
Cool, sorry AK didn't do that right.  We're working on a hardware layer that will help this considerably. I'll close this for now.
