### ISSUE TITLE
v4.6.1 Xcode warning:  "Umbrella header for module 'AudioKit' does not include header 'AudioKit/AudioKit/Core/AudioKitCore/Synth/AKCoreSynth.hpp'"

### ISSUE THREAD

**Issue by sparist** [AudioKit/AudioKit#1691]
When building on Xcode 10.1 for iOS, I see the following warning:
> Umbrella header for module 'AudioKit' does not include header 'AudioKit/AudioKit/Core/AudioKitCore/Synth/AKCoreSynth.hpp'

This looks like it was caused by commit [826ca5e8f1ce598668873c0e1a1499e270e932f7](https://github.com/AudioKit/AudioKit/commit/826ca5e8f1ce598668873c0e1a1499e270e932f7#diff-854c4cb1ced62fef87810e22635aa2bc), where the AKCoreSynth.hpp include was removed.

**Comment by getdunne** [comment]
Hi Jason!

**Comment by sparist** [comment]
Shane! You beat me to saying hello. Didn't think I'd run into anyone I knew here!

**Comment by getdunne** [comment]
All the best people are with AudioKit!
