### ISSUE TITLE
"AudioKit.output" no longer accessible from Objective-C

### ISSUE THREAD

**Issue by techfreak01** [AudioKit/AudioKit#1697]
The very important property "AudioKit.output" is no longer accessible from Objective-C.

The Objective-C sample "HelloObjectiveC" is also no longer compilable. (Compiler error is: "Property 'output' not found on object of type 'AudioKit'".)

It looks as this was broken by commit "Removing @objc from public classes that already inherit from NSObject".

**Comment by aure** [comment]
This is fixed in develop, as covered here: https://github.com/AudioKit/AudioKit/issues/1695. Will make. a new release soon.
