### ISSUE TITLE
[macOS] AKEqualizerFilter produces distorted results with some Audio Devices

### ISSUE THREAD

**Issue by nodeful** [AudioKit/AudioKit#1698]
Graphic Equalizer playground.
Set the 32, 64 and 125 Hz Bands to gain 2 (or higher)
If you use some wired headphones through the 3.5mm Jack or the Built-in Speakers everything works great, the sound is clear, the bass is pronounced.
If you use any Bluetooth, HDMI, DisplayPort device the sound is distorted. The distortion happens not just to the Bass frequency but the entire audio stream.
I have Bluetooth headphones that are connectable with a 3.5mm Jack. Same headphones produce an entirely different result over a wire vs over Bluetooth.

The problem might be internal with the AVAudioEngine not setting correct decibel scale for the Output Device you are using, but can't be sure. 
Here's a StackOverflow cry for help regarding this issue:
https://stackoverflow.com/questions/54524964/macos-avaudioengine-avaudiouniteq-bluetooth-distorted-audio

And here's an Apple Developer Forum post:
https://forums.developer.apple.com/message/348717

Also filed a bug report for AVAudioEngine and in a conversation with Apple DTS at the moment.
Scoured the entire web can't find anything, so any information would be useful.

My setup:
macOS Mojave 10.14.3 
Xcode 10.1
AudioKit 4.6.1

**Comment by aure** [comment]
Hi, yeah, I don't know if there's anything we could be doing that processes differently based on output.  But, maybe you could check the sample rate of the devices as it could be they have different rates and AudioKit doesn't handle the switch to different rates.

**Comment by nodeful** [comment]
Hey @aure thanks for your reply. Have you managed to replicate the same issue on your hardware?
I think it's a problem internally with the AVAudioEngine as even iTunes Equalizer is suffering from the same bug.
The Apple DTS team has been looking into this for about 3 weeks now.

**Comment by aure** [comment]
Any update? I'll close the issue for now, since I don't know that it's actionable by us, but if it is or if you have more information please feel free to post here and/or reopen as necessary.

**Comment by nodeful** [comment]
No, no updates yet. What I know is that it's not connected with Sampling Rate and I did many tests with that and it all seems fine, I think something to do with the transmission protocol compressing the data too much and it becomes distorted. Still waiting for Apple to come back to me, usually, they solve issues within a couple of days for you, but now as it's been almost a month I think the problem is more serious and they are still digging.  
Completely understand your decision to close this issue.
Thanks
