### ISSUE TITLE
Swift: Getting bad frequency with AKMicrophoneTracker

### ISSUE THREAD

**Issue by JonathanDLR** [AudioKit/AudioKit#1699]
Hi,

I'm using AKMicrohoneTracker in my app, and it doesn't return me the good frequency.

It's ok when using AKFrequencyTracker node and I think that the two classes use the same algorithm, so I don't understand why It's not working well.

Did you ever have this kind of issue or is it just a mistake in my code?

`
    
    let noteFrequencies = [16.35, 17.32, 18.35, 19.45, 20.6, 21.83, 23.12, 24.5, 25.96, 27.5, 29.14, 30.87]
    let noteNamesWithSharps = ["C", "C♯", "D", "D♯", "E", "F", "F♯", "G", "G♯", "A", "A♯", "B"]
    let noteNamesWithFlats = ["C", "D♭", "D", "E♭", "E", "F", "G♭", "G", "A♭", "A", "B♭", "B"]

    override func viewDidLoad() {
        super.viewDidLoad()

        self.microAnalyze = MicroAnalyze()
        self.microAnalyze.setupAubio(samplerate: 44100)
        self.microAnalyze.startRecording()
        self.tracker = AKMicrophoneTracker()
        self.tracker.start()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
 
        
        
        self.timerOutput = Timer.scheduledTimer(timeInterval: 0.1,
                                               target: self,
                                               selector: #selector(HomeController.updateUI),
                                               userInfo: nil,
                                               repeats: true)
        
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        //Dispose of any resources that can be recreated.
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        
        self.timerOutput.invalidate()
        self.tracker.stop()
        self.timerOutput = nil
        
        let name = NSNotification.Name.AVAudioSessionInterruption
        let notification = Notification(name: name)
        NotificationCenter.default.post(notification)
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        

    }
    
    @objc func updateUI() {
        if self.tracker.amplitude > 0.03 {
        
            var frequency = Float(self.tracker.frequency)
            print(frequency)
            while frequency > Float(self.noteFrequencies[noteFrequencies.count - 1]) {
                frequency /= 2.0
            }
            while frequency < Float(self.noteFrequencies[0]) {
                frequency *= 2.0
            }
            
            var minDistance: Float = 10_000.0
            var index = 0
            
            for i in 0..<self.noteFrequencies.count {
                let distance = fabsf(Float(self.noteFrequencies[i]) - frequency)
                if distance < minDistance {
                    index = i
                    minDistance = distance
                }
            }
            let octave = Int(log2f(Float(self.tracker.frequency) / frequency))
            self.noteNameWithSharpsLabel.text = "\(self.noteNamesWithSharps[index])\(octave)"
            self.bpmLabel.text = microAnalyze.bpm.description
        }
    }
    
    @IBAction func toggleBpm() {
        microAnalyze.toggleBpm()
    }
}

Thx a lot!`

**Comment by francdn** [comment]
Same issue here when using it on Objective-C. I think this problem has been already there since version 4.4. This issue was reported  back then. https://github.com/AudioKit/AudioKit/issues/1510

It was supposed to be fixed, maybe it was not? I have been trying to avoid updating the framework version on my app but since March 1st I believe you have to target IOS 10 as a minimum so I am forced to upgrade Audiokit on my app.

Also, the MicrophoneAnalysis example crashes on the simulator still/again and when running on device nothing happens (it does not detect anything).

Also, when using the framework from objective c now and trying to do:

AudioKit.output = silence;

I get: Property 'output' not found on object of type 'AudioKit'

Any help on this would be appreciated.

**Comment by openloop** [comment]
@apple?

**Comment by francdn** [comment]
I was able to make it work by changing the hop size and peak count in a previous version (4.5.2) to default values. 

But with the latest versions I get the error I mentioned before:

AudioKit.output = silence; -> Property 'output' not found on object of type 'AudioKit'

**Comment by JonathanDLR** [comment]
Thx for the link francdn. It's OK on my device with AKSettings.sampleRate = 44100.
