### ISSUE TITLE
AKVocalTract is started on creation; Vocal Tract playground has incorrect behavior

### ISSUE THREAD

**Issue by sparist** [AudioKit/AudioKit#1702]
Unlike all other AKNode classes I've played with, AKVocalTract starts on instantiation instead of when calling start(). In "Vocal Tract.xcplaygroundpage", the tone starts as soon as the Live View is loaded even though the Start/Stop button says "Start" vs. "Stop". Clicking "Start" stops the tone, and the button still displays "Start". It is only from this point that the Start/Stop button works correctly.

**Comment by aure** [comment]
Agreed, should be fixed now. Thank you.
