### ISSUE TITLE
Unable assign microphone.

### ISSUE THREAD

**Issue by vallasd** [AudioKit/AudioKit#1705]
This line of code crashes:

let microphone = AKMicrophone()

Here is the log:

2019-03-13 16:12:26.775724-0400 VoiceModulator[13462:434528] [AudioHAL_Client] AudioHardware.cpp:666:AudioObjectGetPropertyData:  AudioObjectGetPropertyData: no object with given ID 0
2019-03-13 16:12:26.777973-0400 VoiceModulator[13462:434528] [avae] AVAEInternal.h:70:_AVAE_Check: required condition is false: [AUInterface.mm:678:EnableIO: (isInput ? auv3().canPerformInput : auv3().canPerformOutput)]
2019-03-13 16:12:26.782433-0400 VoiceModulator[13462:434528] [General] An uncaught exception was raised
2019-03-13 16:12:26.782477-0400 VoiceModulator[13462:434528] [General] required condition is false: isInput ? auv3().canPerformInput : auv3().canPerformOutput
2019-03-13 16:12:26.782619-0400 VoiceModulator[13462:434528] [General] (
	0   CoreFoundation                      0x00007fff3560623b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5c89ac76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3560bfd2 +[NSException raise:format:arguments:] + 98
	3   AVFAudio                            0x00007fff318d99c6 _Z19AVAE_RaiseExceptionP8NSStringz + 158
	4   AVFAudio                            0x00007fff318b63d2 _Z11_AVAE_CheckPKciS0_S0_b + 330
	5   AVFAudio                            0x00007fff318b7060 _ZN15AUInterfaceIOV38EnableIOEbb + 106
	6   libdispatch.dylib                   0x00000001016b9d8f _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x00000001016d2e4d _dispatch_sync_invoke_and_complete_recurse + 285
	8   libdispatch.dylib                   0x00000001016d266e _dispatch_sync_wait + 622
	9   AVFAudio                            0x00007fff31920934 _ZN13AVAudioIOUnit9EnableBusEj + 80
	10  AVFAudio                            0x00007fff3192c032 _ZN17AVAudioEngineImpl15UpdateInputNodeEb + 410
	11  AVFAudio                            0x00007fff31929933 _ZN17AVAudioEngineImpl12GetInputNodeEv + 43
	12  AVFAudio                            0x00007fff319298bf -[AVAudioEngine inputNode] + 58
	13  VoiceModulator                      0x00000001001a6dff $S8AudioKit12AKMicrophoneCACycfc + 351
	14  VoiceModulator                      0x00000001001a6f1f $S8AudioKit12AKMicrophoneCACycfcTo + 15
	15  VoiceModulator                      0x0000000100002b6d $S14VoiceModulator11AudioEngineCACycfc + 141
	16  VoiceModulator                      0x0000000100002a80 $S14VoiceModulator11AudioEngineCACycfC + 64
	17  VoiceModulator                      0x0000000100003e02 $S14VoiceModulator14ViewControllerC5coderACSgSo7NSCoderC_tcfc + 66
	18  VoiceModulator                      0x0000000100003eef $S14VoiceModulator14ViewControllerC5coderACSgSo7NSCoderC_tcfcTo + 47
	19  AppKit                              0x00007fff32b8742e -[NSClassSwapper initWithCoder:] + 602
	20  Foundation                          0x00007fff3766b823 _decodeObjectBinary + 2095
	21  Foundation                          0x00007fff3766aef0 _decodeObject + 243
	22  AppKit                              0x00007fff32ae2ff8 -[NSNibConnector initWithCoder:] + 66
	23  AppKit                              0x00007fff32ae2e9e -[NSNibOutletConnector initWithCoder:] + 76
	24  Foundation                          0x00007fff3766b823 _decodeObjectBinary + 2095
	25  Foundation                          0x00007fff3766ce35 -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 1687
	26  Foundation                          0x00007fff37670c71 -[NSArray(NSArray) initWithCoder:] + 198
	27  Foundation                          0x00007fff3766b823 _decodeObjectBinary + 2095
	28  Foundation                          0x00007fff3766aef0 _decodeObject + 243
	29  AppKit                              0x00007fff32ae1b75 -[NSIBObjectData initWithCoder:] + 200
	30  Foundation                          0x00007fff3766b823 _decodeObjectBinary + 2095
	31  Foundation                          0x00007fff3766aef0 _decodeObject + 243
	32  AppKit                              0x00007fff32be5c8e -[NSNib _instantiateNibWithExternalNameTable:options:] + 535
	33  AppKit                              0x00007fff32be597a -[NSNib _instantiateWithOwner:options:topLevelObjects:] + 136
	34  AppKit                              0x00007fff3333c46c -[NSStoryboard instantiateControllerWithIdentifier:] + 236
	35  AppKit                              0x00007fff32adea27 NSApplicationMain + 729
	36  VoiceModulator                      0x00000001000042fd main + 13
	37  libdyld.dylib                       0x00007fff5d4b4015 start + 1
	38  ???                                 0x0000000000000003 0x0 + 3
)
2019-03-13 16:12:26.789647-0400 VoiceModulator[13462:434528] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: isInput ? auv3().canPerformInput : auv3().canPerformOutput'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3560623b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5c89ac76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3560bfd2 +[NSException raise:format:arguments:] + 98
	3   AVFAudio                            0x00007fff318d99c6 _Z19AVAE_RaiseExceptionP8NSStringz + 158
	4   AVFAudio                            0x00007fff318b63d2 _Z11_AVAE_CheckPKciS0_S0_b + 330
	5   AVFAudio                            0x00007fff318b7060 _ZN15AUInterfaceIOV38EnableIOEbb + 106
	6   libdispatch.dylib                   0x00000001016b9d8f _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x00000001016d2e4d _dispatch_sync_invoke_and_complete_recurse + 285
	8   libdispatch.dylib                   0x00000001016d266e _dispatch_sync_wait + 622
	9   AVFAudio                            0x00007fff31920934 _ZN13AVAudioIOUnit9EnableBusEj + 80
	10  AVFAudio                            0x00007fff3192c032 _ZN17AVAudioEngineImpl15UpdateInputNodeEb + 410
	11  AVFAudio                            0x00007fff31929933 _ZN17AVAudioEngineImpl12GetInputNodeEv + 43
	12  AVFAudio                            0x00007fff319298bf -[AVAudioEngine inputNode] + 58
	13  VoiceModulator                      0x00000001001a6dff $S8AudioKit12AKMicrophoneCACycfc + 351
	14  VoiceModulator                      0x00000001001a6f1f $S8AudioKit12AKMicrophoneCACycfcTo + 15
	15  VoiceModulator                      0x0000000100002b6d $S14VoiceModulator11AudioEngineCACycfc + 141
	16  VoiceModulator                      0x0000000100002a80 $S14VoiceModulator11AudioEngineCACycfC + 64
	17  VoiceModulator                      0x0000000100003e02 $S14VoiceModulator14ViewControllerC5coderACSgSo7NSCoderC_tcfc + 66
	18  VoiceModulator                      0x0000000100003eef $S14VoiceModulator14ViewControllerC5coderACSgSo7NSCoderC_tcfcTo + 47
	19  AppKit                              0x00007fff32b8742e -[NSClassSwapper initWithCoder:] + 602
	20  Foundation                          0x00007fff3766b823 _decodeObjectBinary + 2095
	21  Foundation                          0x00007fff3766aef0 _decodeObject + 243
	22  AppKit                              0x00007fff32ae2ff8 -[NSNibConnector initWithCoder:] + 66
	23  AppKit                              0x00007fff32ae2e9e -[NSNibOutletConnector initWithCoder:] + 76
	24  Foundation                          0x00007fff3766b823 _decodeObjectBinary + 2095
	25  Foundation                          0x00007fff3766ce35 -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 1687
	26  Foundation                          0x00007fff37670c71 -[NSArray(NSArray) initWithCoder:] + 198
	27  Foundation                          0x00007fff3766b823 _decodeObjectBinary + 2095
	28  Foundation                          0x00007fff3766aef0 _decodeObject + 243
	29  AppKit                              0x00007fff32ae1b75 -[NSIBObjectData initWithCoder:] + 200
	30  Foundation                          0x00007fff3766b823 _decodeObjectBinary + 2095
	31  Foundation                          0x00007fff3766aef0 _decodeObject + 243
	32  AppKit                              0x00007fff32be5c8e -[NSNib _instantiateNibWithExternalNameTable:options:] + 535
	33  AppKit                              0x00007fff32be597a -[NSNib _instantiateWithOwner:options:topLevelObjects:] + 136
	34  AppKit                              0x00007fff3333c46c -[NSStoryboard instantiateControllerWithIdentifier:] + 236
	35  AppKit                              0x00007fff32adea27 NSApplicationMain + 729
	36  VoiceModulator                      0x00000001000042fd main + 13
	37  libdyld.dylib                       0x00007fff5d4b4015 start + 1
	38  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by aure** [comment]
Its obviously not doing that for us, so can you provide more information about the environment that you're trying this in?

**Comment by eljeff** [comment]
Of note...auv3() shows up a lot...

**Comment by vallasd** [comment]
I'm running High Sierra.  Xcode 10.1.  Im using the library from pod 'AudioKit/Core'.  I tried this on two different macs (an older mac and a new one) running this setup and see the same error.  I would like to test if this is a High Sierra bug (I saw some issues raised for the exception in High Sierra) but I can't currently update either of the macs I'm on.

**Comment by vallasd** [comment]
Also, this is with a macOS project

**Comment by aure** [comment]
> Of note...auv3() shows up a lot...

Yeah, well AudioKit is AUv3 based, so that's no surprise, not new.

**Comment by aure** [comment]
I don't get this crash with the Microphone Analysis MacOS project, could you try that out and see if you get a similar issue?

**Comment by aure** [comment]
Unless you can provide more details about your implementation, I will have to close this an issue. Reopen at will of course though, let me know.

**Comment by vallasd** [comment]
Could you provide a link to the Microphone Analysis MacOS project?  I tried this on Mohave now and am getting a different error but this is still failing.

**Comment by aure** [comment]
Yeah, here's the project. 

https://github.com/AudioKit/AudioKit/tree/master/Examples/macOS/MicrophoneAnalysis

You might inspire me to elevate it up to its own project so that it can be tried out just with cocoa pods as opposed to compiling AudioKit from source.

**Comment by vallasd** [comment]
So I actually had already found the project here:
http://github.com/audiokit/AudioKit/releases/download/v4.6/AudioKit-macOS-4.6.zip

I was able to run Microphone Analysis fine when downloading there and everything worked.  So I just moved this folder, renamed project, copied the libraries over, and I had a good starting point for what I am trying to make.  So I am good for now.

Before I was attempting to use AudioKit's Cocoapod.  I basically set up a default macOS project, added the pod, opened the workspace, and started coding.  Basic player stuff was working but whenever I attempted to assign a microphone the app crashed at that line of Code.  I attempted both the Core and UI version of the Cocoapod.  I think you still have an issue with the cocoa pods, you may want to check that out.
