### ISSUE TITLE
AKPlayer outTime not being reset on new load(url: URL)

### ISSUE THREAD

**Issue by BrianBecker** [AudioKit/AudioKit#1713]
Using AKPlayer with song that has:
  startTime: 20 ,  endTime: 40 , outTime: 2

Play song
Stop Song using .stop() after 20 seconds (20 seconds before the fade should happen)
LOAD another song with .load(url: URL) (for now it's loading the same song)
  startTime: 20 , endTime: 40 , outTime: 2

Play Song
Song Fades after 10 seconds which is the remaining time left from the first fade.
Song keeps playing at 0 volume to the end of play(from: , to: )

In other words the fade is not releasing it's values when you issue a STOP or load in a new song.

With app below:
1) Hit Play-button  (playing starts at 20)
2) Hit Fade-button (at 28) -- it fades out
3) Hit Play-button (playing starts at 20...but fades out around 30)
   the 2nd fade seems to be 
     playLength - firstFadeTime - delta = secondFadeTime
                      (delta being the time between fade push and 2nd play push)

**ALSO it's weird** that whenever you first start the app if you hit play and wait, the song fades out but then continues playing to the endTime and then rolls back to the startTime (at 20s and 0 volume) and keeps looping over and over (even though looping is turned off)....  -- BUT AFTER you've hit fade-button which issues stop() once, the player stops after the fade completes as it should. 
```
import UIKit
import AudioKit

class ViewController: UIViewController {
    var player: AKPlayer = AKPlayer()
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        let path = Bundle.main.path(forResource: "04ListenToTheMusic.m4a", ofType:nil)!
        let audioUrl = URL(fileURLWithPath: path)
        player = AKPlayer(url: audioUrl)!
        AudioKit.output = player
        do { try AudioKit.start() } catch { print("ERROR:  Audio A&B Mixer not started") }
        makeShiftUpdater()
    }

    @IBOutlet weak var playBtn: UIButton!
    @IBAction func play(_ sender: Any) {
        do {
            let path = Bundle.main.path(forResource: "04ListenToTheMusic.m4a", ofType:nil)!
            let audioUrl = URL(fileURLWithPath: path)
            try player.load(url: audioUrl)
           player.fade.outRampType = .logarithmic
            player.startTime = 20
            player.endTime = 40
            player.isLooping = false
            player.fade.inTime = 2
            player.fade.inStartGain = 0.0
            player.fade.outTime = 2
            player.fade.outStartGain = 1.0
            player.volume = 1.0
            player.play(from: player.startTime, to: player.endTime)
            player.completionHandler = { print("song end reached")}
        } catch {
            print("didn't play")
        }
    }
    @IBAction func fade(_ sender: Any) {
        player.stopEnvelopeTime = 1.0
        player.stop()
    }
    func makeShiftUpdater() {
        if player.isPlaying {
            let time = Float(Int( player.currentTime * 100 )) / 100
            playBtn.setTitle("Play: " + time.description, for: .normal)
        }
        let delay = DispatchTime.now() + 1.0
        DispatchQueue.main.asyncAfter(deadline: delay , execute: { self.makeShiftUpdater() })
    }
}
```

**Comment by ryanfrancesconi** [comment]
Thanks, i'll take a look.

**Comment by ryanfrancesconi** [comment]
I've gone through this finally - sorry for the delay. I believed I've pushed a fix for it. While the documentation might not be clear, just to clarify what these fade options are for:

The general player.fade is for putting fades that automatically are applied to the player. In a DAW this would correspond to something like:
![image](https://user-images.githubusercontent.com/2917795/56755778-23a60d00-6745-11e9-87bf-eaa6ad1eaba0.png)

The stopEnvelopeTime is for when you just want a player (that doesn't have fades on it) to put a short fade at the end when you press stop to eliminate clicks. Mixing the two isn't really something I had in mind. That said, there was a conflict between them that your example pointed out - which I hope is fixed now. Also, the log fade out type isn't that great. I'd recommend exponential.

Thanks for the report!
Ryan
