### ISSUE TITLE
Trouble compile with XCode 10.2 with swift 4.2

### ISSUE THREAD

**Issue by xieliweiparkman** [AudioKit/AudioKit#1721]
After I updated to 10.2, I cannot compile the project anymore. I didnt change any settings.
**Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: $(MY_APP_ROOT)/AudioKit.framework/Modules/AudioKit.swiftmodule/arm64.swiftmodule**

**Comment by megastep** [comment]
You need a new binary that was built with Swift 5. If you use the pod, we have a staging version for that purpose (4.6.4.b1). Just set up our private repo here: https://github.com/AudioKit/Specs

**Comment by xieliweiparkman** [comment]
Thanks for replying! But it became `Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler: $(MY_APP_ROOT)/AudioKit.framework/Modules/AudioKit.swiftmodule/arm64.swiftmodule` after I updated to that version. @megastep

**Comment by xieliweiparkman** [comment]
I am using swift 4.2 by the way.

**Comment by xieliweiparkman** [comment]
`$(MY_APP_ROOT)/AudioKit/iOS/AudioKit.framework/AudioKit(AKReverb2.o) compiled with older version of Swift language (unknown ABI version 0x06) than previous files (unknown ABI version 0x07) file '$(MY_APP_ROOT)/AudioKit/iOS/AudioKit.framework/AudioKit' for architecture x86_64`

**Comment by bakeddean** [comment]
What is the Swift Language Version set to under Build Settings? Your new Xcode may have set it to 5 automatically. If your using Swift 4.2 and are happy with the Swift 4.2 AudioKit binary, you could try setting the Swift Language Version to 4.2 and see if that fixes your problems.

**Comment by Phzytaylor** [comment]
I followed the direction in the specs and AudioKit compiles fine, but when I use import AudioKitUI the Swift 5 converter states that AudioKitUI is not compatible. I used Cocoapods and did not add AudioKitUI to the pod file.

**Comment by bernikowich** [comment]
Same issue here:

> Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler

So we cannot use framework compiled by Xcode 10.1 in Xcode 10.2 even if they both use Swift 4.2? Sounds crazy. :(

**Comment by stschoen** [comment]
The binaries compiled by the 5.0 compiler are not compatible with the 4.2 binaries. I re-built the 4.6 frameworks from source with Xcode 10.2 using the buildframeworks.sh script provided in the download and was then able to use the new binaries with Xcode 10.2. I been able to run the sample playgrounds as well as a native macOS app So far the only issue I've encountered is the MIDI channel is off by 1 when outputting MIDI.

**Comment by aure** [comment]
@stschoen MIDI Channel in AudioKit is indexed at zero, so what is traditional known as MIDI Channel 1 is the first channel so its 0th element in the array.  So, I think its probably acting as expected.

**Comment by stschoen** [comment]
Thanks for the quick response. I wondered if that was the case.
Stephen Schoen

**Comment by benitol** [comment]
I'm struggling to get any new project with the AudioKit framework or AudioKit provided apps (RomPlayer, SynthOne, etc.) to work in Xcode 10.2.  Can anyone give straight forward instructions on how they have got AudioKit to work on Xcode 10.2?

**Comment by aure** [comment]
@benitol Its actually kind of difficult to write a tutorial because 10.2 is new and things are a bit different.  Stuff should work out of the box though, and it is tested to compile on Travis. Sooo, I guess I could offer to do a screen share with you and see if there are any obvious problems with your set up that I could resolve for you.

**Comment by benitol** [comment]
@aure that would be great!  If possible please dm me on twitter @benitol or email benitothedev@gmail.com.  Thanks you!

**Comment by geeksweep** [comment]
I was having a similar issue. I compiled and ran a project using AudioKit 4.6.4(because I cant so Swift 5 yet, I have other 3rd party frameworks that arent Swift 5) in my podfile and when downloading Xcode 10.2 i get the error:

> Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler:

even though, in Xcode build settings I have selecting Xcode 4.x. do you mean to tell me that the code has to be build not only for the correct Swift version but also the correct Xcode version as well? that sounds like bad design on Apples part.

**Comment by megastep** [comment]
Yeah up till very recently there was no actual ABI compatibility with Swift. I thought this was actually the case in Swift 5.0 but I guess they even broke it in 5.1 again :(
