### ISSUE TITLE
Channel number off by 1 when calling midi.sendEvent. I used channel 3 but AudioKit sent on channel 4

### ISSUE THREAD

**Issue by stschoen** [AudioKit/AudioKit#1725]
If your issue is implementing AudioKit in your own code, post your problem to [StackOverflow](https://stackoverflow.com/search?q=AudioKit) with the #AudioKit hashtag.

GitHub Issues should only be used for confirmed problems with AudioKit and
well-defined feature requests.

Make sure you know about the common gotcha's outlined in this video:
https://vimeo.com/audiokit/connecting-nodes-part-2

Problems when submitting your app with the framework? First make sure to check your run phases are set up properly, as outlined in this doc:
https://github.com/AudioKit/AudioKit/blob/master/Frameworks/README.md

**Comment by stschoen** [comment]
When sending MIDI  on macOS I used the following:
 midi.openOutput()
        let note: MIDINoteNumber = 60
        midi.sendEvent(AKMIDIEvent(noteOn: note, velocity: 127, channel: 3))
        AKLog("sending noteOn \(note)")
        sleep(10)
        midi.sendEvent(AKMIDIEvent(noteOff: note, velocity:0, channel: 3))
        AKLog("sending noteOff \(note)")

Using MIDI monitor I discovered that AudioKit was actually sending on channel 4:
13:33:43.791	To Scarlett 6i6 USB	Note On	4	C3	127

**Comment by aure** [comment]
Just the index 0 thing again.,

**Comment by stschoen** [comment]
BTW Thank you very much for the AudioKit frameworks. I’ve been plowing my way through learning CoreAudio, and this makes life a WHOLE lot simpler. Both the Synth One and Digital D1 synths are grea. $10.00 is a bargain for the D1 and I’m glad to know I’m supporting such a worthwhile project. I built the 4.6 sources using the 5.0 compiler in Xcode 10.2 and so far (other than my mistakes) they seem to be working just fine. I’m looking forward to using AudioKit rather than trying to figure out the complexities of CoreAudio.

Yours,
Stephen Schoen
