### ISSUE TITLE
XCode 10.2 release ETA

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#1727]
When do you guys plan to publish a version that is compiled with XCode 10.2 using the new Swift 5 compiler?

**Comment by megastep** [comment]
There's a build available in our staging pods (use version 6.7.b1 for the latest). Instructions are here: https://github.com/AudioKit/Specs

I think we're pretty much ready for Xcode 10.2 though so I would expect an official release this week.

**Comment by TheHmmka** [comment]
Version: 4.7.b1

**Comment by megastep** [comment]
Correct - my bad :)

**Comment by aure** [comment]
4.7 is released now
