### ISSUE TITLE
AKPlayer.resume() doesn't start with AKPlayer.pauseTime

### ISSUE THREAD

**Issue by apprithm** [AudioKit/AudioKit#1729]
AKPlayer.resume() doesn't resume from AKPlayer.pauseTime, it always resume from AKPlayer.startTime instead.

**Comment by Madrox24** [comment]
I'm having the same problem sometimes, how did you resolve it?

**Comment by apprithm** [comment]
@Madrox24 I later I found out, this was not the problem. pauseTime is actually accurate(At least in version ). My problem is actually this one: 4.6.4
https://github.com/AudioKit/AudioKit/issues/1730
