### ISSUE TITLE
AKPlayer.currentTime is not accurate when AKPlayer.resume() is called

### ISSUE THREAD

**Issue by apprithm** [AudioKit/AudioKit#1730]
AKPlayer.currentTime is not accurate when AKPlayer.resume() is called. The currentTIme always start to increment from 0 instead of the previous pauseTime.

It should increment from the pauseTime.

**Comment by apprithm** [comment]
It looks like the following lines are messing up the logic:
In AKPlayer+Playback.swift
```
line 73 startTime = previousStartTime
```

In AKPlayer+Playback.swift
```
line 306  let current = startTime + playerTime.truncatingRemainder(dividingBy: currentDuration)

```

**Comment by wangrenzhu** [comment]
I solved with code like this:

`do {
                try self.bgMusicPlayer = AKAudioPlayer(file: self.backgroundMusicFile!)
                self.bgMusicPlayer.internalPlayer.installTap(onBus: 0, bufferSize: 512, format: self.bgMusicPlayer.audioFile.processingFormat) { [weak self] (pcmbuffer, time) in
                    guard let nodeTime = self?.bgMusicPlayer.internalPlayer.playerTime(forNodeTime: time), let startTime = self?.bgMusicPlayer.startTime else {
                        return
                    }
                    
                    let currentTime = Double(nodeTime.sampleTime ) / nodeTime.sampleRate
                    self?._bgCurrentTime = (currentTime < 0 ? 0.0 : currentTime) + startTime
                    AKLog("currentTime:", self?._bgCurrentTime ?? 0.0)
                }
                self.bgMusicPlayer.volume = self.backgroundVolume
                self.bgMusicPlayer.looping = self.isBgMusicLooping
                self.bgMusicPlayer.startTime = currentTime
            } catch {
                
            }`

**Comment by Madrox24** [comment]
Someone managed how to solve this problem with AKPlayer?
