### ISSUE TITLE
"'withUnsafeMutableBytes' is deprecated" warning

### ISSUE THREAD

**Issue by sparist** [AudioKit/AudioKit#1731]
In v4.7, the following compilation warning appears with Xcode 10.2 and Swift 5:

> AudioKit/Common/MIDI/AKMIDI+Sending.swift:273:16: 'withUnsafeMutableBytes' is deprecated: use `withUnsafeMutableBytes<R>(_: (UnsafeMutableRawBufferPointer) throws -> R) rethrows -> R` instead

**Comment by aure** [comment]
Yeah, I know how to fix that but didn't get a chance to test it, so I'll commit the fix to develop now.

**Comment by aure** [comment]
That should address the warning.
