### ISSUE TITLE
 How can I use my own algorithm to process audio data of a node?

### ISSUE THREAD

**Issue by isliuyaoyao** [AudioKit/AudioKit#1732]
I currently want to use my own algorithm (c) to make a guitar effect, because I am not familiar with the swift and iOS APIs, how can I use AudioKit to process audio data and use a custom algorithm?

By the way, how do you configure the audio buffer time to the lowest, processing 128/256 points per 44100 sample rate?

**Comment by wangrenzhu** [comment]
custom node, wirte dsp like AKBoosterDSP

**Comment by aure** [comment]
I think @wangrenzhu's answer is sufficient.
