### ISSUE TITLE
Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by MohamedFaroukAbdelazeem** [AudioKit/AudioKit#1734]
Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler

**Comment by jieatgstdev** [comment]
I also facing this issue, but I can not update the version to AK 4.7.1, right now, my lasted version is AK 4.6.1, my Xcode version is 10.3

How to fix this issue?  @megastep 

![image](https://user-images.githubusercontent.com/13427113/62852681-b088cc80-bd1c-11e9-898c-ecb7530f06f2.png)

**Comment by megastep** [comment]
Why don't you just update your pod to the current version? 4.8 works fine for me in Xcode 10.3
