### ISSUE TITLE
AKPlayer class not visible when compiling for real iOS device (objective c)

### ISSUE THREAD

**Issue by techfreak01** [AudioKit/AudioKit#1735]
After updating the iPad to iOS 12.2 I had to update to Xcode 10.2.
Then I had the issue #1734 and updated to AudioKit 4.7, that fixed issue #1734 for me.

Since then I can compile my app only for the simulator.
When I switch to a real iPad or to "Generic iOS device", the AKPlayer class is no longer visible for the compiler. I get the error "Unknown type 'AKPlayer'".

**Comment by megastep** [comment]
We're aware of this issue. It appears that Swift 5 breaks universal frameworks somehow.

**Comment by megastep** [comment]
I have a fix for this and we should have version 4.7.1 out very soon.

**Comment by techfreak01** [comment]
Thank you very much
 I'm looking forward to 4.7.1.
