### ISSUE TITLE
Doesn't build on XCode 10.2 - path issues

### ISSUE THREAD

**Issue by manysounds** [AudioKit/AudioKit#1738]
Mojave
XCode 10.2
Fresh install

"
Showing Recent Messages
:-1: ~~~/Documents/Xcode/AudioKitSynthOne-master/Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.debug.xcconfig: unable to open file (in target "OneSignalNotificationServiceExtension" in project "AudioKitSynthOne") (in target 'OneSignalNotificationServiceExtension')

"~~~" is my redaction

**Comment by megastep** [comment]
Wrong repo - you basically need to do a pod install first.

**Comment by Azeem-pp** [comment]
ok I install CocoaPods but no error resolve

**Comment by Azeem-pp** [comment]
fuck  off I can do it but failed
