### ISSUE TITLE
AKMicrophone init seams ignore the format param

### ISSUE THREAD

**Issue by zzzworm** [AudioKit/AudioKit#1739]
code from AKMicrophone.swift:
`/// Initialize the microphone`
`	public init?(with format: AVAudioFormat? = nil)`
	{
		super.init()
		guard let format = getFormatForDevice() --- here
		else
		{
			AKLog("Error! Cannot unwrap format for device. Can't init the mic.")
			return nil
		}`
AKMicrophone init seams ignore the format param?

**Comment by aure** [comment]
Hi there, this is a pretty difficult to address issue. Questions should be asked on StackOverflow and once a clear, issue with AudioKit is revealed, good information and reproducibility (a project or playground page ideally) can be posted here.

**Comment by zzzworm** [comment]
I just have the issue: when bluetooth device is connected before AKMicrophone inited, then init AKMicrophone will crash:
: required condition is false: format.sampleRate == hwFormat.sampleRate
 it related to the device sample rate is lower then 44100(because the bluetooth mic only support 18000), also will happen when your are video chat with others, the sample rate is also lower then 44100. both you can't change the device sample rate to 44100, Also the fixed is change AKMicrophone's method:getFormatForDevice to use AudioKit.engine.inputNode.inputFormat(forBus: 0).sampleRate, but i don't know why getFormatForDevice try use AudioKit.deviceSampleRate.

private func getFormatForDevice() -> AVAudioFormat? {
let audioFormat: AVAudioFormat?
#if os(iOS) && !targetEnvironment(simulator)
let currentFormat = AudioKit.engine.inputNode.inputFormat(forBus: 0)
let desiredFS = AudioKit.deviceSampleRate
if let layout = currentFormat.channelLayout {
audioFormat = AVAudioFormat(commonFormat: currentFormat.commonFormat,
sampleRate: desiredFS,
interleaved: currentFormat.isInterleaved,
channelLayout: layout)
} else {
audioFormat = AVAudioFormat(standardFormatWithSampleRate: desiredFS, channels: 2)
}
#else
let desiredFS = AKSettings.sampleRate
audioFormat = AVAudioFormat(standardFormatWithSampleRate: desiredFS, channels: 2)
#endif
return audioFormat
}

**Comment by zzzworm** [comment]
see also:[](https://stackoverflow.com/questions/33484140/how-can-i-specify-the-format-of-avaudioengine-mic-input)

**Comment by zzzworm** [comment]
also setPreferSampleRate may not work, see https://developer.apple.com/library/etc/redirect/xcode/content/1189/qa/qa1631/_index.html#//apple_ref/doc/uid/DTS40008120

**Comment by maksutovic** [comment]
Hi zzzworm,

I'm sorry the challenges you are having. I've been busy traveling, but will be settled by tomorrow, I will take a look and see if I can clean up the new init process.

@aure is there a way to set sample rate to AKSettings so that the current init method could work in this edge case?
