### ISSUE TITLE
AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port 耳机 (type: Headphones)

### ISSUE THREAD

**Issue by 690858187** [AudioKit/AudioKit#1740]
在12.2系统中，当播放音乐的时候，拔插耳机不会出现上诉情况，但是在12.1.2中，会出现这种错误，并且播放的音乐会全部失去声音。song processor demo也出现这种情况

**Comment by aure** [comment]
This seems to be a copy of the issue you already posted?
