### ISSUE TITLE
AudioKit 4.7 is Swift 5.0 only?

### ISSUE THREAD

**Issue by WholeCheese** [AudioKit/AudioKit#1741]
When building the AudioKit 4.7 framework for iOS via `PLATFORMS="iOS" ./build_frameworks.sh
` I am getting `❌  error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'AudioKitUI`

The Swift Language Version is set in the XCode project files as "Swift 5.0".  If I change that to my Swift 4.2 environment I then get the error:
 `AKMIDI+Sending.swift` `sendMessage` function: `AudioKit/Common/MIDI/AKMIDI+Sending.swift:273:41: error: 'UnsafeMutableRawBufferPointer' is not convertible to 'UnsafeMutablePointer<_>'`

The readme as displayed on the GitHub page really ought to say that this 4.7 version is Swift 5.0 beta code.  If this is stated somewhere in the docs I apologize for missing it!

**Comment by megastep** [comment]
Yes, Swift 5 is the current stable version since Xcode 10.2 came out, and that's what we support now. Because of the changes to the language, AK 4.7. won't compile with earlier versions of Swift any more. This is not a "beta" feature any longer.

**Comment by WholeCheese** [comment]
Oops, I had the notion that Swift 5 wasn't official yet and my XCode is still at 10.1.  Yet another upgrade to do!

Thanks, megastep!
