### ISSUE TITLE
AKTable's init:phase:count not available from ObjC

### ISSUE THREAD

**Issue by jhhl** [AudioKit/AudioKit#1745]
error: no visible @interface for 'AKTable' declares the selector 'init:phase:count:'
    akt_sine = [[AKTable alloc] init:AKTableTypeSine phase:0.0 count:4096];

"It used to work" -- programmer's motto.

**Comment by megastep** [comment]
Are you using the current 4.7.1 pod with C++ by any chance?

**Comment by jhhl** [comment]
Yeah, because otherwise I wouldn't even have AudioKit.output! (#1697)

**Comment by megastep** [comment]
I suggest you give a try to the staging pod (v4.7.2.b1), with instructions here: https://github.com/AudioKit/Specs

There was a problem in the 4.7.1 headers that prevented C++ from correctly picking up the bridging headers.

**Comment by jhhl** [comment]
Thanks! I'll try it!

**Comment by jhhl** [comment]
It's still not in AudioKit-Swift.h If I fake it out with 
```
@interface AKTable ()
- (nonnull instancetype)init:(enum AKTableType)type phase:(float)phase count:(NSInteger)count OBJC_DESIGNATED_INITIALIZER;
@end
```
It compiles, but then I get `This copy of libswiftCore.dylib requires an OS version prior to 12.2.0.` , which is an entirely different headache.

**Comment by megastep** [comment]
If it's not in AudioKit-Swift.h then we probably need to had a `@objc` attribute to this class.

Xcode 10.2 now pretty much requires you to have a dummy Swift file in your project for the dylib issue to be resolved. Just create an empty Swift file and that should take care of it.

**Comment by jhhl** [comment]
Even lying to it so it compiles and runs, and adding the dummy swift file, it ends up not finding the ` -[AudioKit.AKTable init:phase:count:]` method (which might not be in the framework).

**Comment by aure** [comment]
I think my change will address this.

**Comment by jhhl** [comment]
I pulled in the develop build and built it - yes , all fixed! Thanks for `@objc'ing` the file initializer too.
