### ISSUE TITLE
Crash in MicrophoneAnalysis Example in 4.7.1 with Xcode 10.2.1 swift 5

### ISSUE THREAD

**Issue by peterbmarks** [AudioKit/AudioKit#1754]
running macOS Mojave 10.14.4 (18E226)
Xcode Version 10.2.1 (10E1001)
MacBook Pro (13-inch, Mid 2012)

Cloned the master branch and built frameworks as follows:

git clone https://github.com/audiokit/AudioKit.git
$ ./build_frameworks.sh 
Building frameworks for version 4.7.1 on platforms: iOS macOS tvOS
Build settings from command line:
    AUDIOKIT_VERSION = 4.7.1
… etc…
Build succeeds.

Now open Examples/iOS/MicrophoneAnalysis/MicrophoneAnalysis.xcodeproj
Click Run in xcode.
It warns about a 1024x1024 app store icon being missing.
Build succeeds.
iPhone XR simulator launches running iOS 12.2

Crashes:
2019-04-21 17:29:32.990678+1000 MicrophoneAnalysis[35166:618219] [avae] AVAEInternal.h:70:_AVAE_Check: required condition is false: [AVAudioIONodeImpl.mm:911:SetOutputFormat: (format.sampleRate == hwFormat.sampleRate)]
2019-04-21 17:29:33.012967+1000 MicrophoneAnalysis[35166:618219] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: format.sampleRate == hwFormat.sampleRate'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001117cf6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011024aac5 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001117cf482 +[NSException raise:format:arguments:] + 98
	3   AVFAudio                            0x0000000115398f3c _Z19AVAE_RaiseExceptionP8NSStringz + 156
	4   AVFAudio                            0x00000001153f7937 _Z11_AVAE_CheckPKciS0_S0_b + 295
	5   AVFAudio                            0x00000001153f7f3d _ZN17AVAudioIONodeImpl15SetOutputFormatEmP13AVAudioFormat + 349
	6   AVFAudio                            0x0000000115390f8e _ZN18AVAudioEngineGraph8_ConnectEP19AVAudioNodeImplBaseS1_jjP13AVAudioFormat + 1670
	7   AVFAudio                            0x00000001153ff598 _ZN17AVAudioEngineImpl7ConnectEP11AVAudioNodeS1_mmP13AVAudioFormat + 194
	8   AVFAudio                            0x00000001153ff5ff -[AVAudioEngine connect:to:format:] + 83
	9   MicrophoneAnalysis                  0x000000010f50ba2b $s8AudioKit12AKMicrophoneC4withACSgSo13AVAudioFormatCSg_tcfc + 3563
	10  MicrophoneAnalysis                  0x000000010f50ac2c $s8AudioKit12AKMicrophoneC4withACSgSo13AVAudioFormatCSg_tcfC + 60
	11  MicrophoneAnalysis                  0x000000010f2c5dc6 $s18MicrophoneAnalysis14ViewControllerC11viewDidLoadyyF + 214
	12  MicrophoneAnalysis                  0x000000010f2c5ff4 $s18MicrophoneAnalysis14ViewControllerC11viewDidLoadyyFTo + 36
	13  UIKitCore                           0x000000011b5c543b -[UIViewController loadViewIfRequired] + 1183
	14  UIKitCore                           0x000000011b529004 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 68
	15  UIKitCore                           0x000000011b5292f7 -[UINavigationController _startTransition:fromViewController:toViewController:] + 146
	16  UIKitCore                           0x000000011b52a3b5 -[UINavigationController _startDeferredTransitionIfNeeded:] + 896
	17  UIKitCore                           0x000000011b52b6a7 -[UINavigationController __viewWillLayoutSubviews] + 150
	18  UIKitCore                           0x000000011b50c38d -[UILayoutContainerView layoutSubviews] + 217
	19  UIKitCore                           0x000000011c0959c1 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1417
	20  QuartzCore                          0x00000001126b5eae -[CALayer layoutSublayers] + 173
	21  QuartzCore                          0x00000001126bab88 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 396
	22  QuartzCore                          0x00000001126c6ee4 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 72
	23  QuartzCore                          0x00000001126363aa _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 328
	24  QuartzCore                          0x000000011266d584 _ZN2CA11Transaction6commitEv + 608
	25  UIKitCore                           0x000000011bbe0ccb __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 128
	26  CoreFoundation                      0x0000000111736aec __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	27  CoreFoundation                      0x00000001117362b0 __CFRunLoopDoBlocks + 336
	28  CoreFoundation                      0x0000000111730b34 __CFRunLoopRun + 1252
	29  CoreFoundation                      0x0000000111730302 CFRunLoopRunSpecific + 626
	30  GraphicsServices                    0x00000001169b62fe GSEventRunModal + 65
	31  UIKitCore                           0x000000011bbc7ba2 UIApplicationMain + 140
	32  MicrophoneAnalysis                  0x000000010f2cb40b main + 75
	33  libdyld.dylib                       0x00000001135d1541 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

The crash is in ViewController.viewDidLoad on the line:
mic = AKMicrophone()

**Comment by aure** [comment]
I suspect you might have your mac's microphone set to 48K, switch it to 44.1 or try the code on a device, it should work. I just tested.
