### ISSUE TITLE
Sample rate mismatch issue causes popping noise/distortion when recording

### ISSUE THREAD

**Issue by mnearents** [AudioKit/AudioKit#1755]
I've been using AudioKit to record audio from the iPhone's microphone. It's been working great but since upgrading from 4.6.4 to 4.7, I now have a popping noise/distortion when recording audio. I posted on SO and got feedback that it sounded like a sample rate mismatch. 

I removed the following code from my recorder and the popping went away:

`AKSettings.defaultToSpeaker = true`

The problem with this approach is when the recording is played back, it only comes through the earpiece, not the external speaker.

You can see the SO post here for more info:
https://stackoverflow.com/questions/55789818/popping-noise-when-recording-audio-with-audiokit?noredirect=1#comment98261479_55789818

**Comment by aure** [comment]
This issue is getting more attention on StackOverflow, so I'll close it here, but what would be great would be a set of example projects that demonstrate the issue.
