### ISSUE TITLE
No Audio after updating to AK 4.6.4

### ISSUE THREAD

**Issue by WholeCheese** [AudioKit/AudioKit#1756]
I've been developing an iOS app the last year with AudioKit-4.0.4. Now that I have the app working I thought it was time to update my AudioKit library to a newer version as well as upgrade to Swift 5.0.

I have downloaded AudioKit-4.6.4 and merely swapped out the older "AudioKit For iOS.xcodeproj" in my XCode project with the new version. Everything built just fine, except for my AudioKit.start() now has to be wrapped with a "try". No other changes were needed to get a successful build.

But now my app, built with AK 4.6.4, does not produce audio when playing a note.  Searching for "AudioKit no sound/audio" does not come up with anything like my situation.

Attached is "PlayTone-4.0.4.zip" which contains two simple iOS projects.  They are identical except one is meant for AK 4.0.4 and the other for AK 4.6.4.  I am using Swift 4.2, XCode 10.2, macOS 10.14, iOS 12 on a pad and iOS 11 on a phone.

The sample app uses the same note play technique as used in my larger application and exhibits the same problem: sound with AK 4.0, no sound with AK 4.6.  I suspect my problem has something to do with the way I am playing a group of oscillators, each with its own AKAmplitudeEnvelope?  (See NoteOscillator.play() in the code.)

Note that the AK4.6 sample apps are working for me so this indicates that there is something I am doing with 4.0.4 that is no longer supported in 4.6.

[PlayTone-4.0.4.zip](https://github.com/AudioKit/AudioKit/files/3104607/PlayTone-4.0.4.zip)

**Comment by aure** [comment]
Add an "osc.start()" on line 59 of your NoteOscillator.swift file. A bug was filed that noted the oscillators were default on, which was different than every other generator.  In fixing that, your app no longer played oscillators by default.

**Comment by WholeCheese** [comment]
Thank you, Aure!  Too late to look at it now but will first thing in the morning.  Regarding the Audiobus problem, we can do a screen share if you think that is productive.  More tomorrow.

-Allan

**Comment by WholeCheese** [comment]
Aure, thanks again!  Yes, now the oscillators play.  Except now the oscillators have a weird swoopy sound!  A little digging in the AK code reveals that AKOscillator has a rampDuration of 0.0002.  Explicitly setting the osc.rampDuration = 0 makes it sound just like the AK 4.0.4 version, i.e., no ramping up to the desired frequency.

**Comment by aure** [comment]
Good sleuthing, exactly right. The default ramp helps to avoid pop and clicks, but in your case immediate is what you want.

**Comment by WholeCheese** [comment]
Now I am hearing a problem when playing an oscillator with an envelope.  In AK 4.0.4 `envelopes.map{$0.start()}` would start the note and `envelopes.map{$0.stop()}` would let the note play into the release phase of the envelope.  In AK 4.6.4 my notes are abruptly ending without playing the release.  Where there any changes in this area?

**Comment by aure** [comment]
Nothing has changed in that regard.  Is anything else stopping at the same time? osc.stop?

**Comment by WholeCheese** [comment]
I don't call osc.stop() and a breakpoint in the AKOscillator.swift code shows no one else is either.  This is very puzzling since my code for AK 4.6.4 is the same as it is with the AK 4.0.4 build, except for the `osc.rampDuration` and the `osc.start()` call before I do the `envelopes.map{$0.start()} ` :-(

**Comment by aure** [comment]
Where do you call stop though? I don't see it in the version of your project you sent me. Happy to look at another zip if you want.

**Comment by WholeCheese** [comment]
I've been working today with my Chime app, not the PlayTone app.  Neither on calls stop() on an oscillator.  A note is played by starting the oscillators and envelopes and stoped by stoping just the envelopes.

Now this is really curious.  The PlayTone app **DOES NOT** exhibit the release cut problem, just my Chime app.  They both use the same start/stop mechanism.  Very frustrating!  Don't worry about this anymore tonight.  I will hit it tomorrow with a fresh start.

**Comment by WholeCheese** [comment]
My envelope problem seems to be caused by the reset() function in:

`AudioKit/Common/Nodes/Effects/Envelopes/Amplitude Envelope/AKAmplitudeEnvelopeDSP.hpp`

Lots of debugging showed that my carefully set envelope times were being set to the builtin default values when calling the `AKNode connect(to: mix)` function.

I have modified my local copies of AK 4.6.4 and AK 4.7 so that the reset function now looks like this:

```
void reset() override {
	sp_adsr_init(sp, _adsr);
	_adsr->atk = 0.1;
	_adsr->dec = 0.1;
	_adsr->sus = 1.0;
	_adsr->rel = 0.1;
	//bool immediate = true;
	//attackDurationRamp.setTarget(0.1, immediate);
	//decayDurationRamp.setTarget(0.1, immediate);
	//sustainLevelRamp.setTarget(1.0, immediate);
	//releaseDurationRamp.setTarget(0.1, immediate);
}

```
This fixes my problem with notes being cut off abruptly but I'd like to hear from the AudioKit team if this code patch will cause other problems elsewhere.
