### ISSUE TITLE
Cannot close midi output port

### ISSUE THREAD

**Issue by andreiantonescu** [AudioKit/AudioKit#1757]
Steps:
- open a midi output port based on a UID
- try and then close the respective midi output port based on the same UID

Result:
- midi output port is not closed, throws error -10832. 

From digging a bit around this issue it seems that the error code above refers to kMIDIWrongEndpointType - 'A source endpoint was passed to a function expecting a destination, or vice versa'.

A sample app that exemplifies this issue can be found here: https://github.com/andreiantonescu/audiokitMidiOutTest. I've built a table view which lists the available output ports and a keyboard from which you can send data. You can see that you can successfully open output ports and send data to them but you cannot close them.

**Comment by andreiantonescu** [comment]
I am not sure if what I am trying to do is supported by AudioKit, but by the naming of the API I would presume this is the case. 

I've submitted a PR in which I describe what I did to fix this issue for my project: https://github.com/AudioKit/AudioKit/pull/1758

**Comment by eljeff** [comment]
> kMIDIWrongEndpointType - 'A source endpoint was passed to a function expecting a destination, or vice versa'.

It sounds like somewhere we were just using the wrong function on the wrong type? Is there a way to actually close the port using the correct arguments?

**Comment by aure** [comment]
Closing since the PR was accepted.
