### ISSUE TITLE
Anyone has an audiokit app in the app store?

### ISSUE THREAD

**Issue by elioscordo** [audiokit/AudioKit#176]
Hi,
thanks for the csound porting.
I would like to know if anybody has any app n the appstore with audiokit.

The gpl license is incompatible with the terms of service and I am a bit worried.

Thanks again
elio

**Comment by aure** [comment]
The license is MIT License and there is one app in the store, one more accepted and released this Tuesday.  Check http://audiokit.io/blog/ for more information about app releases.

**Comment by narner** [comment]
@elioscordo Here's a link to the already released app that uses AudioKit: https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=975407337

**Comment by megastep** [comment]
I should add that while AudioKit is now MIT, Csound itself remains under the LGPL. However you can use it in released applications as long as you use the dynamic version of the Csound library (also provided with AudioKit) - but that pretty much restricts you to iOS 8.

**Comment by elioscordo** [comment]
Thank you guys so much!!! amazing work!!!

**Comment by narner** [comment]
@elioscordo Thank you; we can't wait to see what you make!
