### ISSUE TITLE
AK 4.7 excessive CPU usage and audio sputtering.

### ISSUE THREAD

**Issue by WholeCheese** [AudioKit/AudioKit#1763]
I have been comparing CPU usage between Audiokit 4.7 and 4.6.4.  I confess that my app may be pushing things to a limit but it has been working very well so far with AK 4.0 and just recently AK 4.6.4.

My app simulates wind chimes by additive sine wave synthesis.  I am testing the CPU usage on two chimes:

A simple chime that plays 7 notes and a more complex chime set with 23 notes.

The simple 7 note chime uses a sound with 3 oscillators and envelopes for each note.  In total, that's 8 mixers, 21 oscillators and 21 envelopes.

The complex chime uses 23 notes with 28 mixers, 75 oscillators, and 75 envelopes.

AK 4.0.4 and AK 4.6.4 are roughly equivalent but there is a huge difference between AK 4.6.4 and 4.7.

**Simple Chime**
- AK 4.6.4 - average 19% (similar to AK 4.0)
- AK 4.7   - average 41%

**Complex Chime**
- AK 4.6.4 - average 44% (similar to AK 4.0)
- AK 4.7   - average 65% with audio sputtering

The excessive CPU usage is a problem since I expect my app to be played in the background and iOS will generally kill apps in the background that use too many resources.

The audio sputtering is the real problem.

Since AK 4.6.4 does not exhibit any more CPU usage than AK 4.0.4, I am assuming that something bad has creeped into the AK 4.7 code.

Suggestions??

**Comment by aure** [comment]
This is an amazingly well crafted and helpful issue, thank you. We have to figure out what has caused such a big change.  We have the firepower to figure it out.  :) @megastep @jefflivid @sieren @dave234

**Comment by WholeCheese** [comment]
Glad to help!  :-)  But, sorry to say I will be out of town and basically off the grid for the next two weeks and can't compute again until May 16.  I trust your firepower will figure it out!

**Comment by sieren** [comment]
@WholeCheese can you give us some insights on how you're generating those sine waves? 
I'm thinking we should setup a small test-app where we can swap out AK versions to bisect where the problem originated.

**Comment by WholeCheese** [comment]
Maybe Aurelius can help you with that? I sent him a test app last week to demonstrate an envelope problem I was having. That app, PlayChime, is a very simple example of what I am doing but can be easily scaled up to create a more complex mix.  The CPU usage is only an issue when notes are playing.  I'd send you the app but I'm in Fiji for two weeks with very limited wifi and just my phone.

**Comment by sieren** [comment]
Cool! That'd good to know. I'll ping @aure directly and will get it from him

**Comment by sieren** [comment]
I'm looking at the PlayChime App right now and I get roughly 20% on an iPhone 8 with the most complex setting (and that's in Debug mode as well).

On first look I couldnt find anything suspicious.

Which device were you using and are your measurements in line with the sample app?

**Comment by WholeCheese** [comment]
The 20% increase in cpu usage that I saw was when I swapped AK4.6 to AK4.7 in my HarmonicChimes app. The increase was the same on pad and phone.  My usage testing observation was with the HarmonicChimes app not the playchime app.  The PlayChime app may need to be beefed up a bit to demonstrate a similar oscillator usage level.  I can’t look at the code until May 17th so can’t tell you which line or source file. But look for where it connects oscillators and envelopes and add a bunch more.  Hope that helps!  One last thought: the HarmonicChimes app uses reverb in the final mix whereas the demo app does not.

**Comment by aure** [comment]
@WholeCheese when you're back I'd love to do a screenshare with you to look at the two version of your code with 4.6 and 4.7 to see the change in cpu usage first hand.

**Comment by aure** [comment]
But, I'll close this as an issue until we can make it actionable. Look forward to working with you and @sieren and @megastep directly.

**Comment by sieren** [comment]
It'd be great if we could all get on a Slack call and do some screen sharing

**Comment by WholeCheese** [comment]
Back from vacation and looking at the CPU usage difference between AK 4.6.4 and AK 4.7 with the PlayChime demo app.  Attached is the demo app and two screen shots showing the CPU usage: one for AK4.6 and one for AK4.7.  There were no changes to the demo code other than linking with one AK or the other.  The two blips at the beginning of the CPU graph are from selecting the "Alto" chime, or number 4 in the segmented controller UI.  The long blip happens in the AURemoteIO thread after hitting "Play"

[PlayChime-4.6.zip](https://github.com/AudioKit/AudioKit/files/3193267/PlayChime-4.6.zip)

![PlayChime-4 7](https://user-images.githubusercontent.com/19720230/57958547-06341100-78b5-11e9-8ac0-e96c76a6dd4d.png)

![PlayChime-4 6](https://user-images.githubusercontent.com/19720230/57958549-06cca780-78b5-11e9-99f6-bec08790c65e.png)

**Comment by aure** [comment]
I do not see this problem when running your code.  I wonder if someone else on the team can corroborate my findings or yours:

![image](https://user-images.githubusercontent.com/13122/57964312-131e2800-78e8-11e9-8b40-22ee83e76fdd.png)

![image](https://user-images.githubusercontent.com/13122/57964276-5d52d980-78e7-11e9-94a3-44ede83c1181.png)

**Comment by aure** [comment]
Oh I should ask are you running on a device?  My tests were on the simulator.  I'll test on a device now.

**Comment by aure** [comment]
On an iPhone X, iOS12.2.  I do not have an iOS11 device, but I wouldn't be surprised if AudioKit 4.7 is optimized for iOS12. 

![image](https://user-images.githubusercontent.com/13122/57964346-ea4a6280-78e8-11e9-8329-1b84d7780933.png)

![image](https://user-images.githubusercontent.com/13122/57964368-4e6d2680-78e9-11e9-9e2c-158f87b0752a.png)

**Comment by WholeCheese** [comment]
Your results have me baffled! I ran my test on a real iPhone. AK4.6 was built with Swift 4.2 and AK4.7 with Swift 5.0. My code was 5.0 for both.  I ran on a real iPhone 5s iOS 11.  I will run again tomorrow on a 12.0 iPad.

**Comment by aure** [comment]
Here it is on an iOS11 simulator (I don't have an actual device on iOS11).

![image](https://user-images.githubusercontent.com/13122/57964415-12869100-78ea-11e9-9e6e-e872cec0a8a7.png)

![image](https://user-images.githubusercontent.com/13122/57964395-c20f3380-78e9-11e9-912e-36e63853738b.png)

**Comment by aure** [comment]
My feeling is that 28% on an iPhone X is probably about 67% on the iPhone 5s.  So, that would say that I haven't been able to get the improved 20% on the iPhone 5s ie say 7% on an iPhone X.  I would love to get that kind of performance boost.  I don't understand this maybe "AK4.6 was built with Swift 4.2 and AK4.7 with Swift 5.0. My code was 5.0 for both."

**Comment by WholeCheese** [comment]
Oh, dear.  This was my blunder.  Many, many sincere apologies!!

My AK4.6.4 project settings for Clang and Swift optimization (debug build) were set to -O3 and -O respectively.  The AK4.7 Clang and Swift optimization settings (debug build) were -O0 and -Onone

Changing AK4.7 to fastest to match 4.6.4 results in nearly identical CPU usage.

I don't recall setting the optimization options but the finger appears to point in my direction?

As to why my AK4.6.4 project was set to Swift 4.2, again, I don't recall changing that, and actually had the impression that the move to Swift 5.0 started with AK4.7.  AK4.6.4 builds fine with 5.0 but that had little if any effect on the CPU usage.

I am truly sorry about calling for this witch hunt.  Please don't exile me from the club!!

**Comment by sieren** [comment]
Haha oh no! I actually mentioned that as a possibility to @aure but figured that's the first place you might have looked hehe.

Glad you got it solved! :)

**Comment by aure** [comment]
No worries. Its always good to look at the efficiency of AudioKit with very skeptical eyes and ears! I'm glad you got it sorted and you're definitely not exiled!
