### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 4.2.1 compiler

### ISSUE THREAD

**Issue by ShineyVeridic** [AudioKit/AudioKit#1765]
I am facing this isssue with the new version of Audio Kit(4.7.1) after updating my pods.
I am using Xcode 10.1 with swift compiler 4.2.1

I need help resolving this issue. Thanks in advance.

![Screenshot 2019-05-02 at 12 42 16 pm](https://user-images.githubusercontent.com/48543784/57060627-c0cdec00-6cd7-11e9-943f-08f8937e9cc4.png)

**Comment by megastep** [comment]
You need to upgrade to Xcode 10.2 and Swift 5 to use the latest pod.

**Comment by ShineyVeridic** [comment]
@megastep I can't do that right now. I will upgrade to latest Xcode version later but I need a quick fix for this problem.

**Comment by megastep** [comment]
You could just explicitly use versions < 4.7 - I don’t think the current code even compiles with Swift 4 anymore.
