### ISSUE TITLE
Crash with AKMixer and AKPlayer

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#1766]
What is wrong with this very simple example? Is it wrong to add nodes dynamically? Is this not possible during playback?

Here is the error:

```
2019-05-03 19:58:56.592532+0200 AudioKitIssue2[2085:1044968] [avae] AVAEInternal.h:70:_AVAE_Check: required condition is false: [AVAudioNodeImpl.h:245:AVAE_CheckNodeHasEngine: (_engine != nil)]
2019-05-03 19:58:56.593876+0200 AudioKitIssue2[2085:1044968] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: _engine != nil'
*** First throw call stack:
(0x1c3f9b518 0x1c31769f8 0x1c3eb5148 0x1c9d5c438 0x1c9d5ba70 0x1c9dffd04 0x1c9dfef18 0x1009c0150 0x1009d8e2c 0x1009d9c44 0x1008dcfc0 0x1008dce80 0x1008dc480 0x1017d4c74 0x1017d7ffc 0x1017ea610 0x1017e256c 0x1c3f2cec0 0x1c3f27df8 0x1c3f27354 0x1c612779c 0x1f00e8b68 0x1008db040 0x1c39ed8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

And here is the repo

https://github.com/mlostekk/AudioKitIssue2

**Comment by aure** [comment]
AudioKit's handling of dynamic connections needs some work.

**Comment by aure** [comment]
I can't get the example project to load.  I think it is due to a recent rename.  Can you fix it up and reopen the issue?

```
> pod install
[!] Unable to find a target named `Wynton`, did find `AudioKitIssue2`.
```

**Comment by megastep** [comment]
That does sound like a problem in your Podfile (namely there is no corresponding target in the Xcode project).

**Comment by mlostekk** [comment]
This was just a typo. The issue still remains

**Comment by mlostekk** [comment]
> I can't get the example project to load. I think it is due to a recent rename. Can you fix it up and reopen the issue?
> 
> ```
> > pod install
> [!] Unable to find a target named `Wynton`, did find `AudioKitIssue2`.
> ```

How can i reopen that issue?

**Comment by mlostekk** [comment]
@aure 
> I can't get the example project to load. I think it is due to a recent rename. Can you fix it up and reopen the issue?
> 
> ```
> > pod install
> [!] Unable to find a target named `Wynton`, did find `AudioKitIssue2`.
> ```

The project compiles now. Was just a wrong name in the pod due to renaming. Issue / crash is still the same. How can i reopen the issue?

**Comment by ryanfrancesconi** [comment]
Why are you calling detach on the player before trying to play it?

**Comment by mlostekk** [comment]
But shouldnt `detach` followed by `connect` be fine?

**Comment by aure** [comment]
https://github.com/AudioKit/AudioKit/pull/1778
