### ISSUE TITLE
Volume adjustment is not affecting the audio file.

### ISSUE THREAD

**Issue by ajay2c9** [AudioKit/AudioKit#1777]
Hi,
I'm using Audiokit in my application. By using the mixed nodes sample, I'm playing the multiple audios using [This](https://audiokit.io/playgrounds/). and using the Below code I'm merging the audios.

    func merge(tracks:[String]){
        let composition: AVMutableComposition = AVMutableComposition()
        
        for path in tracks {
            var asset: AVURLAsset!
            
            if(path == tracks[0]){
              //  audiotrack.preferredVolume = 0.5
                if(isHighKey){
                     asset = AVURLAsset(url: URL(fileURLWithPath: path), options: nil)

                }else{
                     asset = AVURLAsset(url: URL(fileURLWithPath: path), options: nil)
                }
                
            }else{
                asset = AVURLAsset(url: URL(fileURLWithPath: path), options: nil)
            }

            let audiotrack:AVMutableCompositionTrack = composition.addMutableTrack(withMediaType: AVMediaType.audio, preferredTrackID: kCMPersistentTrackID_Invalid)!
            
            try! audiotrack.insertTimeRange(CMTimeRange(start:.zero, duration: asset.duration), of: asset.tracks(withMediaType: AVMediaType.audio)[0], at: .zero)
        }
        //Path is localstoragepath
        let storagepath:String = Audio.shared.getPath(name: .Saved).path + "/\(String(describing: fileName!)).wav"
        let export:AVAssetExportSession = AVAssetExportSession(asset: composition, presetName: AVAssetExportPresetAppleM4A)!
        export.outputFileType = AVFileType.m4a
        export.outputURL = URL(fileURLWithPath: storagepath)
        export.shouldOptimizeForNetworkUse = true
        export.exportAsynchronously {
            NSLog("Completed successfully")
            print(storagepath)
        }
    } 

While audios are playing, Volume adjustment is working fine while adjusting the volume slider.  My problem is **Exporting audio with adjustable volume**.  for example
I have 3 audios playing using the concept of the mixed nodes. I adjust1 audio volume to 0.5, Second to 0.3, third to 0.8. with these volumes, audios need to merge. 

Is there any possibility to merge the audios like this. Please give suggestions to implement the above requirement.

Thank you

**Comment by aure** [comment]
Hi,

I don't see anything in the attached code that makes me think the volume of the exported file is being controlled by any sliders.  Can you attach a sample project or put one up on Github (that would be ideal).

Closing until more information is provided, but I'll happily reopen the issue when that is available..

Aure
