### ISSUE TITLE
AKPlay 和 AKAudioPlayer 插拔耳机在iphone6,se,6s,7,7s,8,8s ... 都会沉默

### ISSUE THREAD

**Issue by 690858187** [AudioKit/AudioKit#1782]
If your issue is implementing AudioKit in your own code, post your problem to [StackOverflow](https://stackoverflow.com/search?q=AudioKit) with the #AudioKit hashtag.

GitHub Issues should only be used for confirmed problems with AudioKit and
well-defined feature requests.

Make sure you know about the common gotcha's outlined in this video:
https://vimeo.com/audiokit/connecting-nodes-part-2

Problems when submitting your app with the framework? First make sure to check your run phases are set up properly, as outlined in this doc:
https://github.com/AudioKit/AudioKit/blob/master/Frameworks/README.md

**Comment by aure** [comment]
Use stackoverflow.com please
