### ISSUE TITLE
a crash appeared when use microphone.

### ISSUE THREAD

**Issue by duiyueliu** [AudioKit/AudioKit#1784]
i print the samleRate , know AKSettings.sampleRate = 44100,but the AudioKit.engine.inputNode.inputFormat(forBus: 0).sampleRate is 48000.
so what should i do

**Comment by duiyueliu** [comment]
a crash appeared when use microphone.
my AudioKit version is 4.7.2,use Xcode10.2,iphoneX.

Trapped uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: format.sampleRate == hwFormat.sampleRate' 


```swift
//      My code is 
        AKSettings.audioInputEnabled = true
        AKSettings.useBluetooth = true
        microphone = AKMicrophone()
        tracker = AKFrequencyTracker(microphone)
        silence = AKBooster(tracker, gain: 0)
        AudioKit.output = silence
        
         do {
            try AudioKit.start()
        } catch {
            AKLog("fail")
        }
```

**Comment by mklybor** [comment]
Getting a crash using AK 4.7.2 (just downloaded this release). Using the "Node FFT Plot" playground. MacOS 10.14.5, Xcode 10.2.1

Playground execution failed:

error: Execution was interrupted, reason: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0).
The process has been left at the point where it was interrupted, use "thread return -x" to return to the state before expression evaluation.

* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
  * frame #0: 0x00007fff3827aa67 AppKit`-[NSApplication _crashOnException:] + 109
    frame #1: 0x00007fff3827a948 AppKit`-[NSApplication reportException:] + 916
    frame #2: 0x00007fff3833b209 AppKit`uncaughtErrorProc + 145
    frame #3: 0x00007fff3a91bce9 CoreFoundation`__handleUncaughtException + 775
    frame #4: 0x00007fff64f53edd libobjc.A.dylib`_objc_terminate() + 91
    frame #5: 0x00007fff639ac19e libc++abi.dylib`std::__terminate(void (*)()) + 8
    frame #6: 0x00007fff639abf86 libc++abi.dylib`__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
    frame #7: 0x00007fff6399ef99 libc++abi.dylib`__cxa_throw + 113
    frame #8: 0x00007fff64f51b51 libobjc.A.dylib`objc_exception_throw + 362
    frame #9: 0x00007fff3a8c2a1a CoreFoundation`+[NSException raise:format:arguments:] + 98
    frame #10: 0x00007fff36a82304 AVFAudio`AVAE_RaiseException(NSString*, ...) + 156
    frame #11: 0x00007fff36a5df9f AVFAudio`_AVAE_Check(char const*, int, char const*, char const*, bool) + 295
    frame #12: 0x00007fff36ad3b41 AVFAudio`AVAudioIONodeImpl::SetOutputFormat(unsigned long, AVAudioFormat*) + 349
    frame #13: 0x00007fff36ab4f58 AVFAudio`AVAudioEngineGraph::_Connect(AVAudioNodeImplBase*, AVAudioNodeImplBase*, unsigned int, unsigned int, AVAudioFormat*) + 1670
    frame #14: 0x00007fff36ab8c1d AVFAudio`AVAudioEngineGraph::ConnectMultipleOutputs(AVAudioNode*, NSArray*, unsigned long, AVAudioFormat*) + 3295
    frame #15: 0x00007fff36adb925 AVFAudio`AVAudioEngineImpl::ConnectMultipleOutputs(AVAudioNode*, NSArray*, unsigned long, AVAudioFormat*) + 673
    frame #16: 0x00007fff36adb63c AVFAudio`-[AVAudioEngine connect:toConnectionPoints:fromBus:format:] + 94
    frame #17: 0x000000010a3cc521 AudioKitPlaygrounds`function signature specialization <Arg[4] = Dead> of static AudioKit.AudioKit.connect(_: __C.AVAudioNode, to: Swift.Array<__C.AVAudioConnectionPoint>, fromBus: Swift.Int, format: Swift.Optional<__C.AVAudioFormat>) -> () + 1905
    frame #18: 0x000000010a2e1ac1 AudioKitPlaygrounds`function signature specialization <Arg[18446744073709551615] = Owned To Guaranteed> of generic specialization <AudioKit.AKPeriodicFunction> of (extension in AudioKit):AudioKit.AKOutput.connect(to: AudioKit.AKInput, bus: Swift.Int) -> AudioKit.AKInput + 561
    frame #19: 0x000000010a2e32d9 AudioKitPlaygrounds`function signature specialization <Arg[18446744073709551615] = Owned To Guaranteed> of generic specialization <__C.AVAudioInputNode> of (extension in AudioKit):AudioKit.AKOutput.connect(to: AudioKit.AKInput, bus: Swift.Int) -> AudioKit.AKInput + 9
    frame #20: 0x000000010a230660 AudioKitPlaygrounds`AudioKit.AKMicrophone.init(with: Swift.Optional<__C.AVAudioFormat>) -> Swift.Optional<AudioKit.AKMicrophone> + 2000
    frame #21: 0x000000010a22fe7c AudioKitPlaygrounds`AudioKit.AKMicrophone.__allocating_init(with: Swift.Optional<__C.AVAudioFormat>) -> Swift.Optional<AudioKit.AKMicrophone> + 60

**Comment by aure** [comment]
@mklybor Your issue is different from @duiyueliu in that the playgrounds are macOS based but similar because both issues are sample rate related.  In your case, the Mac is probably set to 48000 microphone.  Change that in your audio/midi settings application.  @duiyueliu I don't know why you're getting an error on an iPhoneX.  I have the same phone and things work. Have you tried the latest version of AudioKit, is there a sample project I can run on my iPhone X to test?

**Comment by aure** [comment]
Closing the issue until more information arrives.
