### ISSUE TITLE
Swift 5.1 (Xcode 11) support

### ISSUE THREAD

**Issue by colinhumber** [AudioKit/AudioKit#1786]
I'm sure this is going to be worked on soon, just adding this here for reference. :)

**Comment by aure** [comment]
Probably will look at this over the weekend or next week.

**Comment by colinhumber** [comment]
Not sure if this would be best suited for a subsequent release, but the new XCFramework support in Xcode 11 for distributing frameworks for multiple platforms (specifically UIKit for Mac) would be super useful for clients porting their iPad apps to macOS.

**Comment by aure** [comment]
@colinhumber Yeah, that definitely caught our resident release czar's attention (@megastep)

**Comment by colinhumber** [comment]
I don't know a ton about the compiler, but it sounds like these new framework features would also provide forward compatibility with new versions of the Swift compiler (big win!)

**Comment by Dev1an** [comment]
Swift Package Manager support would also be great.

**Comment by NicolasLourenco** [comment]
The SPM would be great, but I think it was impossible since SPM doesnt support mixed language source files. I've tried, but there's too many differents source files langages (cpp, mm, swift).

```
'AudioKit-iOS' ~/Sources/AudioKit/AudioKit/iOS/AudioKit-iOS: error: target at '~/Sources/AudioKit/AudioKit/iOS/AudioKit-iOS/Sources/AudioKit-iOS' contains mixed language source files; feature not supported

**Comment by killerham** [comment]
I'm getting an error in Xcode 11: `Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 ` I'm not sure if this is an audiokit issue or not though

**Comment by colinhumber** [comment]
@killerham The AudioKit framework needs to be compiled against the Swift 5.1 compiler to work in Xcode 11. This issue is here to track that progress. They're working on a fix. :D

**Comment by AssyriaGameStudio** [comment]
Any update on this? We're beginning to integrate some iOS 13 features internally and currently aren't able to build using XCode beta.

Thanks!

**Comment by offglitch** [comment]
Would love to hear an update about this.

**Comment by megastep** [comment]
I think we should start making Xcode 11 builds available via our staging pods soon - there'll be more work involved to provide proper support (for SwiftUI and XCFrameworks) but hopefully that's a good first step.

**Comment by megastep** [comment]
Just released a pre-release build made with Xcode 11 in our staging repo:

`https://github.com/AudioKit/Specs/`

You need to explicitly use version 4.8.b1 to get it.

**Comment by colinhumber** [comment]
Thanks for all the hard work on this!

**Comment by AssyriaGameStudio** [comment]
Awesome, thanks @megastep :D!

**Comment by meilers** [comment]
Can we get the pre-release build on the staging repo for Xcode 11 Beta 4?

**Comment by megastep** [comment]
Did they break Swift between betas now? 👎

**Comment by ghubaddole** [comment]
The error is just "compiled with a previous version of the compiler" -- they made beta 4 incompatible with previous beta releases. just recompiling should work, i guess?

**Comment by megastep** [comment]
Yeah well since we're just releasing AK 4.8 I'll make a new beta build, hoping that the Travis Xcode 11 image is up to date...

**Comment by ghubaddole** [comment]
Many thanks!

**Comment by megastep** [comment]
Travis is still on beta 2 so I guess I'll have to make a manual build on my Mac.

**Comment by megastep** [comment]
I replaced the archive for `v4.8.b1` with binaries built with beta 4 of Xcode 11. Make sure to clean your pod cache and try to reinstall it.

**Comment by ghubaddole** [comment]
That worked! Thanks a lot :-)

**Comment by colinhumber** [comment]
@megastep Unfortunately, Xcode 11b6 released yesterday updated the compiler again and the previous binaries don't build. :\

**Comment by megastep** [comment]
Dammit, and I had just made a new build for beta 5! I'll update it with beta 6 later today

**Comment by megastep** [comment]
I've updated staging release v4.8.1.b1 with binaries built with beta 6. Make sure to clear your pod cache to get it.

**Comment by gierschv** [comment]
@megastep Could you please make a build for XCode 11.0 Golden Master that was released yesterday? That would be great, thank you!

**Comment by megastep** [comment]
Oh yeah, I'm gonna be needing that myself....

**Comment by megastep** [comment]
Although to be fair, my own app seems to build just fine with the current 4.8 pod (not the beta ones) in the GM.
