### ISSUE TITLE
How to convert the wav files to mp3 files using AudioKit

### ISSUE THREAD

**Issue by ajay2c9** [AudioKit/AudioKit#1787]
Hi,
I am using the AudioKit in my application. In my app voice recording and playing the audio file with both .wav format and .mp3 format audios. 
My requirement is to convert the .wav files to mp3 files.

is there any possibility to convert the .wav files to mp3 files using the AudioKit. 
or is there any other process to convert the .wav files to mp3 files.

Thank you

**Comment by aure** [comment]
Can you please ask this question on StackOverflow?  Issues is for known problems with AudioKit.
