### ISSUE TITLE
Getting loads of "Undefined symbol" errors after importing AudioKit

### ISSUE THREAD

**Issue by SamusAranX** [AudioKit/AudioKit#1791]
I'm trying to write a small Mac app using AudioKit (specifically the macOS version of [this release](https://github.com/AudioKit/AudioKit/releases/tag/v4.7.2)). Here's what little code I have now:
```swift
import Cocoa
import AudioKit

class ViewController: NSViewController {

	override func viewDidLoad() {
		super.viewDidLoad()

		if let devices = AudioKit.inputDevices {
			print(devices)
		} else {
			print("No devices found")
		}
	}

}
```

Trying to build the project results in 65 errors that all follow this format:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/676069/59607342-78498100-9113-11e9-8f31-fe848ae2b5b1.png">

This is all nonsense to me. What do I need to do to fix this?

**Comment by mfk-ableton** [comment]
Are you building AudioKit from source?
Did you add  `-lc++` to the **Other Linker Flags** in Xcode?

**Comment by sieren** [comment]
Are you building AudioKit from source?
Did you add `-lc++` to the **Other Linker Flags** in Xcode?

**Comment by SamusAranX** [comment]
I downloaded release v4.7.2 and used the `AudioKit.framework` file from the `AudioKit-macOS-4.7.2.zip` archive.
There's nothing about any flags in the readme, so I added zero flags to anything.

**Comment by sieren** [comment]
https://github.com/AudioKit/AudioKit/blob/master/Frameworks/README.md

It's described there for both the precompiled frameworks and compiling from source.
