### ISSUE TITLE
ROMPlayer Memory leaks

### ISSUE THREAD

**Issue by Veremei** [AudioKit/AudioKit#1792]
Hi! There are memory leaks in ROMPlayer!
Also in my project https://github.com/AudioKit/ROMPlayer/issues/6

<img width="221" alt="Снимок экрана 2019-06-20 в 13 16 06" src="https://user-images.githubusercontent.com/33792509/59841722-960a2680-935d-11e9-9c7b-a5cf2306318d.png">

**Comment by aure** [comment]
Hi, we are aware of the issue in general.  However, this issue does not present any new information or specify a specific actionable leak so I will close it.
