### ISSUE TITLE
AKMIDIlistener is not receiving Sysex messages in IOS MIDI-utility example

### ISSUE THREAD

**Issue by MaartenWL** [AudioKit/AudioKit#1798]
I builded the IOS MIDI utility example of audiokit 4.7.2. 
It has a function in the akmidilistener to which should display incoming sysex messages.  (receivedMIDISystemCommand)

When my synthesizer (virus TI) sends the following sysex messages:
[240,00,32,51,01,16,112,00,40,95,247]

The following debug messages appear in the debug area of Xcode:
AKMIDI.swift:startReceivingSysex(with:):102:Starting to receive Sysex
AKMIDI.swift:stopReceivingSysex():107:Done receiving Sysex

But nothing is displayed in the midi utility app.

The Virus TI synthesizer is connected to my iPad with a Roland MU-One midi-to-usb interface 

The reason I did this test is that I'm seeing this exact behavior in my own app. In Audiokit version 4.5.6 receivedMIDISystemCommand did receive sysex messages. (in some way)

**Comment by aure** [comment]
Are you running the develop branch or master? We might have to update the examples with the new midi listener protocol. Do note on messages show?

**Comment by MaartenWL** [comment]
I'm running the master branche. CC, polypressure and note on/off messages are displayed as expected.

**Comment by MaartenWL** [comment]
well, works great now! thanks!
