### ISSUE TITLE
AudioKit stops when setting up a custom AURenderCallbackStruct

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#1805]
I am using AudioKit but i also want to use a custom `AURenderCallbackStruct.inputProc` in order to process incoming data. I have just realized that this seems not to work. So whenever i activate one (`AudioKit.start()` or `AudioUnitInitialize`) the other stops to work.

Is there any best practice to achieve this? Or is the only way to use the `AKMicrophone`?

**Comment by aure** [comment]
I don't know the answer to this question.

**Comment by mlostekk** [comment]
What a pitty. Never used AudioKit besided regular AudioUnit?

**Comment by roussetjc** [comment]
@mlostekk I just posted [this](https://stackoverflow.com/questions/58020268/audiokit-how-to-playback-a-modified-buffer-in-a-tap) on SO. I could get a render callback (on the output node). I hope it helps.
