### ISSUE TITLE
AKSequencer track clear() doesn't remove final event

### ISSUE THREAD

**Issue by PQKelly** [AudioKit/AudioKit#1807]
Working with AKSequencer with AKMIDICallbackInstrument, if you add a MIDI note event at the end of a (populated) AKSequencer track like:
`seq.tracks[trackIndex].add(noteNumber: 1, velocity: 0, position: AKDuration(beats: seq.length.beats), duration: AKDuration(beats: 0.0))`
and subsequently 
`seq.tracks[trackIndex].clear()`
the track will clear as expected - except for the note(s) at the track's length location, shortening the track length will change the orphaned event's duration to a negative value.
the only way to remove the event(s) is to 
`seq.tracks[trackIndex].clearNote(1)`

Example - I have two added notes (noteNumbers 0 and 1) at the last track length location.
after a 27 beat sequence is cleared and changed to a 22 beat sequence. - without .clearNote()
seq.debug:
...
	22.000: Note:Ch:0 0 0 (0.000)
	22.000: Note:Ch:0 1 0 (0.000)
	27.000: Note:Ch:0 0 0 (-5.000)
	27.000: Note:Ch:0 1 0 (-5.000)

The orphaned events can accumulate - clearing and creating a 12 beat sequence:
	12.000: Note:Ch:0 0 0 (0.000)
	12.000: Note:Ch:0 1 0 (0.000)
	26.000: Note:Ch:0 0 0 (-14.000)
	26.000: Note:Ch:0 1 0 (-14.000)
	53.000: Note:Ch:0 0 0 (-41.000)
	53.000: Note:Ch:0 1 0 (-41.000)

The reason for adding the note at the end of the sequence is for the callback instrument to notify a delegate to do some needed functions after the sequence plays.

**Comment by aure** [comment]
All AudioKit does is delegate clear down to CoreMIDI as follows:

    /// Clear all events from the track
    open func clear() {
        clearMetaEvents()
        if let track = internalMusicTrack {
            if isNotEmpty {
                MusicTrackClear(track, 0, length)
            }
        }
    }

If that doesn't work I'm not sure what else we can do since the rest is closed source.

**Comment by eljeff** [comment]
Yea I'd need to see more code. There's a new sequencer coming soon anyway, so we'll look at this once we try to settle the dust that gets kicked up from the that.

**Comment by PQKelly** [comment]
I understand the closed source. just wanted to let you know clear() isn't clearing everything.
Here's the general setup of the sequence and generation function for the 'system track' - controls a scrolling line over the written music via a delegate.

`	@objc public func initializeQuiz() {

		if seq.tracks[quizTrackIndex].isNotEmpty { seq.tracks[quizTrackIndex].clear() }

		seq.addTimeSignatureEvent(timeSignature: AKTimeSignature(topValue: UInt8(timeSignature), bottomValue: .four))
		seq.setTempo(UserDefaults.standard.double(forKey: kDefaultsTempo))

		numberOfMeasures = UserDefaults.standard.integer(forKey: kDefaultsNumberOfMeasures)
		timeSignature = 2 + UserDefaults.standard.integer(forKey: kDefaultsTimeSignatureIndex)
		// sequence length (in beats) is 1 measure prep, length of quiz (meter * number of measures) + 1 beat runoff for late releases
		seq.setLength(AKDuration(beats: Double(timeSignature * (numberOfMeasures + 1)) + 1.0))

		generateClickTrack()
		generateSystemTrack()
	}


	func generateSystemTrack() {

		seq.tracks[systemTrackIndex].clear()
		seq.tracks[systemTrackIndex].clearNote(1)	// needed because final midi message at end with length of 0 doesn't get removed

		// sets the resolution of 'move line' messages(quantums) relative to the tempo : bpm 30 - 150 == resolution 96 - 16 (by 16s)
		let scrollRez = (16.0 * (7 - (currentTempo / 25.0).rounded()))
		let totalQuantums = (Double(timeSignature * (numberOfMeasures + 1)) * scrollRez) + 1.0

		for i in stride(from: 0.0, to: totalQuantums, by: 1.0) {
			seq.tracks[systemTrackIndex].add(noteNumber: 0, velocity: 0, position: AKDuration(beats: (i / scrollRez)), duration: AKDuration(beats: 0.0))
			// print("system track - beat: \(Int(floor(i / scrollRez))) quantum: \(Int((i.truncatingRemainder(dividingBy: scrollRez) * (96.0 / scrollRez))))")
		}

		seq.tracks[systemTrackIndex].add(noteNumber: 1, velocity: 0, position: AKDuration(beats: seq.length.beats), duration: AKDuration(beats: 0.0))

	}
`

**Comment by aure** [comment]
Since the new AKSequencer is out, I'm going to close this issue.
