### ISSUE TITLE
NEED HELP IN VOICE RECORDING IMPLEMENTATION

### ISSUE THREAD

**Issue by ajay2c9** [AudioKit/AudioKit#1810]
Hi, 
I'm using the Audiokit in my app. I have three tracks of background music, song, and lyrics.
These tracks are playing at a time using the mixer(implemented from the audio kit sample https://audiokit.io/playgrounds/Basics/Mixing%20Nodes/).
 I also implemented the voice recorder using this sample(https://github.com/AudioKit/AudioKit/tree/master/Examples/iOS/Recorder). 

By using the UiSlider I'm controlling the track volumes. All tracks will play while playing and also while recording.

My requirement is to record the voice while tracks are playing. but while recording the voice, the track songs is also recording in the background. while using the headset and also in high device volume facing the same problem.

Please give suggestions to voice record the voice without recording the tracks.

I have another requirement. i.e 
While voice recording, I have to hear the voice recording and need to control the voice volume using the slider. but in the final, the final recorded voice must be in the full volume. without any volume changes.

Below is my code
//////////////////
    func voiceRecordingSetUp()
    {
        AKAudioFile.cleanTempDirectory()

        AKSettings.bufferLength = .medium
        do {
            try AKSettings.setSession(category: .record, with: .allowBluetoothA2DP)
        } catch {
            AKLog("Could not set session category.")
        }
        AKSettings.defaultToSpeaker = true
 

        // Patching
        let monoToStereo = AKStereoFieldLimiter(mic, amount: 1)
       // mic.volume = 0.5
        micMixer = AKMixer(monoToStereo)
       // micMixer.volume = 0.5
        micBooster = AKBooster(micMixer)
        
        // Will set the level of microphone monitoring
        micBooster.gain = 0
        recorder = try? AKNodeRecorder(node: micMixer)
        try? recorder.reset()
        if let file = recorder.audioFile {
            player = AKPlayer(audioFile: file)
            player.volume = 1.5;
        }
        player.isLooping = true
        player.completionHandler = playingEnded
        moogLadder = AKMoogLadder(player)
    }
/////////////////////////////
    func setUpAudios(type:String){
        // Session settings
        if(type == "WAV"){
        self.type = "WAV"
        guide_transposed = try! AKAudioFile(forReading: URL(fileURLWithPath: path + "/" + Song.GT.rawValue))
        guide = try! AKAudioFile(forReading: URL(fileURLWithPath: path + "/" + Song.Guide.rawValue))
        music = try! AKAudioFile(forReading: URL(fileURLWithPath: path + "/" + Song.Music.rawValue))
        music_transposed = try! AKAudioFile(forReading: URL(fileURLWithPath: path + "/" + Song.MT.rawValue))
        prompter = try! AKAudioFile(forReading: URL(fileURLWithPath: path + "/" + Song.Prompter.rawValue))
        }else{
            self.type = "MP3"
            guide_transposed = try! AKAudioFile(forReading: URL(fileURLWithPath: path + "/" + Song.GTMP3.rawValue))
            guide = try! AKAudioFile(forReading: URL(fileURLWithPath: path + "/" + Song.GuideMP3.rawValue))
            music = try! AKAudioFile(forReading: URL(fileURLWithPath: path + "/" + Song.MusicMP3.rawValue))
            music_transposed = try! AKAudioFile(forReading: URL(fileURLWithPath: path + "/" + Song.MTMP3.rawValue))
            prompter = try! AKAudioFile(forReading: URL(fileURLWithPath: path + "/" + Song.PrompterMP3.rawValue))
        }
        
        AKSettings.allowAirPlay = true;
        AKSettings.enableCategoryChangeHandling = true
        AKSettings.enableRouteChangeHandling = true
        AKSettings.defaultToSpeaker = true
       
        AKSettings.bluetoothOptions = [.allowBluetoothA2DP ]
        
        maxDuration = music.duration
        guidePlayer = AKPlayer(audioFile: guide)
        musicPlayer = AKPlayer(audioFile: music)
        gtPlayer = AKPlayer(audioFile: guide_transposed)
        mtPlayer = AKPlayer(audioFile: music_transposed)
        prompterPlayer = AKPlayer(audioFile: prompter)
        mixer = AKMixer(guidePlayer,musicPlayer,prompterPlayer,gtPlayer,mtPlayer,moogLadder, micBooster)
        
           mixer = AKMixer(guidePlayer,musicPlayer,prompterPlayer,gtPlayer,mtPlayer,moogLadder, micBooster)
        AudioKit.output = mixer
        try! AudioKit.start()

    }
/////////////////////////
func play(){
        if(guidePlayer.isPlaying){
            self.stop()
        }else{
            mixer.start()
            guidePlayer.prepare()
            musicPlayer.prepare()
            gtPlayer.prepare()
            mtPlayer.prepare()
            prompterPlayer.prepare()
            
            guidePlayer.play()
            musicPlayer.play()
            gtPlayer.play()
            mtPlayer.play()
            prompterPlayer.play()
        }
    }
///////////////////////////
    func voiceRecording(){
        stop()
        switch state {
        case .readyToRecord :
            
            if(isHeadSetConnected() == true){
           playBtnAction()
            isRecording = true
           self.vcDelegate.micBtn.isUserInteractionEnabled = true
           self.vcDelegate.micBtn.isEnabled = true
           self.vcDelegate.micBtn.setImage(#imageLiteral(resourceName: "Stop"), for: .normal)
           self.vcDelegate.playBtn.setImage(#imageLiteral(resourceName: "Play"), for: .normal)

            if((recordingTimer) != nil){
                recordingTimer.invalidate()
            }
               
              
            recordingTimer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(stopTimer), userInfo: nil, repeats: true)
            state = .recording
            // microphone will be monitored while recording
            // only if headphones are plugged
            if AKSettings.headPhonesPlugged {
                micBooster.gain = 1
            }
            do {
               
                mic.volume =  Double(self.vcDelegate.voiceVolume.value)
                micMixer.volume =   Double(self.vcDelegate.voiceVolume.value)

               recorder.stop()
               self.vcDelegate.playBtn.isUserInteractionEnabled = false
                self.vcDelegate.mergeBtn.isUserInteractionEnabled = false

                self.vcDelegate.playBtn.isEnabled = false
                self.vcDelegate.mergeBtn.isEnabled = false

                self.vcDelegate.micBtn.isHighlighted = true
                try recorder.record()
                
            } catch { AKLog("Errored recording.") }
            }else{
                Audio.shared.displayAlert("Please Connect your headset", vc: self.vcDelegate)
            }
            
        case .recording :
            // Microphone monitoring is muted
            self.recordingEnd()
            
          
        case .readyToPlay :
           // player.play()
            state = .playing
            
        case .playing :
            player.stop()
            self.vcDelegate.playBtn.isUserInteractionEnabled = true
            self.vcDelegate.micBtn.isHighlighted = false
            self.vcDelegate.mergeBtn.isUserInteractionEnabled = true
            recordingTimer.invalidate()
            self.recordingEnd()
        }
    }
    ///////////////////////
    func recordingEnd(){
        tape = recorder.audioFile!
        player.volume = 1.0
        player.load(audioFile: tape)
        
    if let _ = player.audioFile?.duration {
        if((player.audioFile?.duration)! > 1){
            self.stopRecording()
          
            tape.exportAsynchronously(name: voiceName,
                                      baseDir: .documents,
                                      exportFormat: .wav) {_, exportError in
                                        if let error = exportError {
                                            AKLog("Export Failed \(error)")
                                        } else {
                                            AKLog("Export succeeded")
                                            self.player.stop()
                                            self.recordingTimer.invalidate()
                                            self.playingEnded()
                                        }
            }
        }
     }
    }

PLEASE GIVE SUGGESTIONS.

**Comment by aure** [comment]
This is not an "issue" with AudioKit, its a request for help with implementation.  You can try posting this to StackOverflow but even they might wonder what your central question is.
