### ISSUE TITLE
SequencerDemo iOS example app crashes

### ISSUE THREAD

**Issue by valeriyvan** [AudioKit/AudioKit#1817]
Xcode 10.2.1, both device and simulator.

<img width="1512" alt="Screenshot 2019-07-25 at 13 39 08" src="https://user-images.githubusercontent.com/1630974/61872080-b5f3b380-aee2-11e9-95a7-a0ec76664dd6.png">

**Comment by aure** [comment]
The AudioKitUI framework was not linked for some reason. Fixed it on the develop branch. Thanks for the heads up.
