### ISSUE TITLE
AudioUnitManager doesn't list AUv3 on iOS

### ISSUE THREAD

**Issue by aethernet** [AudioKit/AudioKit#1821]
Hi 

I successfully compiled AudioUnitManager from the zip examples folder (there's painful signing issue but it's another story).

Once running on a freshly booted iPhone 7 (iOS 12) I cannot see the instruments installed on my device (only defaults AuSampler & AuMidiSynth) but nothing else (I have I should have 10+ AU listed like spectrum, Ruismaker, Ruismaker noir, Ruismaker FM, the Rozeta suite, MV08, Noise Drum, etc.)

If I open Garageband and list all AU, it shows properly all the AU. 

Then going back in AudioUnitManager, all instruments are now listed.

I guess there's a missing method to force iOS to (re)scan available AU, but i'm kinda new on the AU front.

Any clue ?

**Comment by aure** [comment]
Sorry this has gone so long with no response. By not closing the issue I was sort of validating that this is a known problem, but I should have at least commented saying this is a confirmed bug.

**Comment by aure** [comment]
I just tested this and it appears to work. I think this was probably a bug in Apple stuff that got fixed.

 What I will do to help everyone out with this project is to move it to its own repo so that it can use Cocoapods for installation of Dropdown and be much easier to try.
