### ISSUE TITLE
AKMIDIListener not receiving Clock events

### ISSUE THREAD

**Issue by mopotmo** [AudioKit/AudioKit#1822]
I have problems receiving MIDI Clock events fron an external device (MC-909) into my iOS App.

I have a simple MIDIListener:
```swift
class MyMIDIListener: AKMIDIListener {
    func receivedMIDINoteOn(noteNumber: MIDINoteNumber, velocity: MIDIVelocity, channel: MIDIChannel, portID: MIDIUniqueID? = nil, offset: MIDITimeStamp = 0) {
        print("Note ON")
    }
    
    func receivedMIDISystemCommand(_ data: [MIDIByte], portID: MIDIUniqueID? = nil, offset: MIDITimeStamp = 0) {
        print("System Command")
    }
}
```

When I trigger notes on the external device, I get "Note ON" messages in the log. So the setup is working. And when I start or stop the external sequencer, I get "System Command" messages. But the problem is, that I get no continuous clock events during playback. Only one event on start and one event on stop of the sequencer.

If have tried with another app ("Midi Tool Box") and the clock events do show up there. Just not through AudioKit.

I am using AudioKit version 4.8.

Not sure, if this may be related to #1798.

**Comment by aure** [comment]
You should use AKMIDIClockListener as well: https://github.com/AudioKit/AudioKit/blob/master/AudioKit/Common/MIDI/Listeners/AKMIDIClockListener.swift

**Comment by mopotmo** [comment]
@aure This did not solve the issue. I submitted a PR with a fix, which works for me.
