### ISSUE TITLE
Low latency audio playback best practice

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#1823]
I am wondering if you guys have assembled a guide to low latency audio playback. I mean things to consider like
- audio compression formats
- Which one is faster (init->play->playing) `AKPlayer` or `AKAudioPlayer`
- any additional configuration needed in `AKSettings`
- what is `lazyBuffering` in `AKAudioPlayer.init` (https://audiokit.io/docs/Classes/AKAudioPlayer.html#/c:@M@AudioKit@objc(cs)AKAudioPlayer(im)initWithFile:looping:lazyBuffering:error:completionHandler:) Documentation missing here, but seems to have an effect on buffering quality.

And maybe one general question injected here. 

*Is it possible to load an audio file into memory for immediate playback regardless of its audio compression format?*

I am asking because we are having trouble get tight audio scheduling. Sometimes the `AKAudioPlayer.play` takes 0.05sec to really start playback. Sometimes it takes up to 0.4sec. Which makes parts of our app unusable.

**Comment by dimagimburg** [comment]
Can you load your file beforehand? If so have alook at the .buffer and .buffering properties here: https://audiokit.io/docs/Classes/AKPlayer.html

**Comment by aure** [comment]
This is definitely a question better asked on StackOverflow. We have not written a guide for this stuff, yet.
