### ISSUE TITLE
AudioKit doesn't pass App Store Validation (Mac App Store)

### ISSUE THREAD

**Issue by serg-vinnie** [AudioKit/AudioKit#1824]
Steps to reproduce:
1. open HelloWorld project (Mac)
2. set valid bundle ID (it must be ID registered in your Developer Account)
3. enable signing
4. make sure project can be build
5. archive project
6. validate archive from Organizer

Actual result:
![Screen Shot 2019-07-31 at 13 56 47](https://user-images.githubusercontent.com/24904140/62206719-17ac9580-b39b-11e9-92b1-b0697b724f05.png)

Expected result: Validation success

I'm trying to submit my new app to the Mac App Store and can't validate it. 

I contacted Apple and they answered "We’ve determined that your question should be addressed by the support channel for AudioKit - the third-party resource you are using".

I created a new ticket and tried to explain the root of the problem "App Store Validation shows wrong error messages – it doesn't help to figure out actual problem". But I'm not sure Apple will help me with this.

**Comment by megastep** [comment]
This is likely because you've set the AudioKit and AudioKitUI frameworks as embedded in your app. You need to link with them only, not embed them, since they are static.

**Comment by serg-vinnie** [comment]
@megastep you just saved my life!
