### ISSUE TITLE
Bluetooth connection poor quality

### ISSUE THREAD

**Issue by romancfischer** [AudioKit/AudioKit#1825]
Unfortunately, connecting to bluetooth devices is very fragile in my development environment and often has poor sound quality. It is in fact mono and sounds like it is downsampling. My DSP Code runs on 44100 and two channels. This is my setup:

```
AKSettings.sampleRate = 44100
AKSettings.channelCount = 2
AKSettings.playbackWhileMuted = true
AKSettings.enableRouteChangeHandling = true
AKSettings.defaultToSpeaker = true
AKSettings.audioInputEnabled = true
AKSettings.useBluetooth = true        
        
do {
            
     if #available(iOS 10.0, *) {
          try AKSettings.setSession(category: .playAndRecord, with: [.allowBluetoothA2DP, .mixWithOthers])
          print("using A2DP")
     } else {
          try AKSettings.setSession(category: .playAndRecord, with: [.allowBluetooth, .mixWithOthers])
     }
            
} catch {
            
     print("Could not set session category.")
            
}
        
        
        
// setting things up including a microphone..
// …

// Initiating a tracker connected to my DSP AudioUnit
self.masterbusTracker = AKAmplitudeTracker(self.dsp)
self.mixer.connect(input: self.masterbusTracker)
AudioKit.output = self.mixer
        
try! AudioKit.start()
```

This is what I happens when I log the engine’s **AudioKit.engine.outputNode** on iPad:

AudioKit.engine.outputNode.inputFormat(forBus: 0).sampleRate **44100.0**
AudioKit.engine.outputNode.outputFormat(forBus: 0).sampleRate **16000.0**
AudioKit.engine.outputNode.outputFormat(forBus: 0).channelCount **1**

Here one can see that it’s indeed downsampling to 16000 kHz and one channel. That’s exactly what it sounds like. 

I just installed iOS 12.4 on my iPad and found a work-around fix:

1. Don’t open / run the app yet
2. Connect Bluetooth 
3. Play Music in Spotify
4. Disconnect Bluetooth
5. Open The App
6. Connect Bluetooth

Now everything sounds fine on my Airpods 2nd Gen and the microphone is working well too.
It sounds bad again, when I switch to Spotify and back again though.

It doesn’t seem to work when I directly start Bluetooth and the same work-around doesn’t seem to work on my iPhone 6S / iOS 12.4. What the heck is going on?

I checked my AudioUnit code, initializing the AudioUnit with allocateRenderResourcesAndReturnError seems fine. Since other apps like Spotify sound badly too while the app is not running properly it doesn’t seem to be a problem there but later in the chain.

I followed another idea where I wanted to downsample the engines output node with AVAudioConverter but I don’t think that’s possible, is it? I tried it but can’t replace the Audiokits engines output node after Audiokit has been initialized.

Anyone any idea where I could look next?

**Comment by romancfischer** [comment]
I realize it is somehow related to this issue https://github.com/AudioKit/AudioKit/issues/1603
when I deactivate the microphone and set the audioInputEnabled to false it is connecting to bluetooth the way it should.

now I need to figure out how to enable bluetooth while still having access to the  microphone at least on the internal microphone of the iPhone or Ipad.

**Comment by romancfischer** [comment]
Ok, I found a way to enable the microphone on the device and at the same time get full quality bluetooth running like this:

`

        // microphone needs to be first
        self.microphone = AKMicrophone()
        
        // select input of device
        if let input = AudioKit.inputDevice {
            try! self.microphone?.setDevice(input)
        }

        AKSettings.sampleRate = 44100
        AKSettings.channelCount = 2
        AKSettings.playbackWhileMuted = true
        AKSettings.enableRouteChangeHandling = false
        AKSettings.useBluetooth = false
        AKSettings.defaultToSpeaker = true
        AKSettings.audioInputEnabled = false
        
        
        // init DSP
        
        self.dsp = AKClock(amountSamples: Int32(self.amountSamples), amountGroups: Int32(self.amountGroups), bpm: self.bpm, iPad:self.iPad)
        
        
        self.masterbusTracker = AKAmplitudeTracker(self.dsp)
        self.mixer.connect(input: self.masterbusTracker)
        
        self.player = AKPlayer()
        self.mixer.connect(input: self.player)
        
        self.microphone?.stop()
        self.microphoneTracker = AKAmplitudeTracker(self.microphone)
        self.microphoneTracker?.stop()
        self.microphoneRecorder = try! AKNodeRecorder(node: self.microphone)
        self.microphoneMonitoring = AKBooster(self.microphoneTracker)
        self.microphoneMonitoring?.gain = 0
        self.mixer.connect(input: self.microphoneMonitoring)
        
        AudioKit.output = self.mixer
        
        do {
            try AudioKit.start()
        }catch{
            print("AudioKit did not start")
        }
        
        
        do {
            
            if #available(iOS 10.0, *) {
                try AKSettings.setSession(category: .playAndRecord , with: [.allowBluetoothA2DP, .defaultToSpeaker, .allowAirPlay ])
                print("using A2DP")
            } else {
                try AKSettings.setSession(category: .playAndRecord, with: [.allowBluetooth, .mixWithOthers])
            }
            
        } catch {
            
            print("Could not set session category.")
            
        }`

it is important to set the categories AFTER AudioKit has been started.

But one problem still remains: It only works when starting the app. It doesn't work when switching between bluetooth on and off. So I tried setting up my own observer:

`

        NotificationCenter.default.removeObserver(self, name: .AVAudioSessionRouteChange, object: nil)
        
        NotificationCenter.default.addObserver(self, selector: #selector(self.audioRouteChangeListener(notification:)), name: NSNotification.Name.AVAudioSessionRouteChange, object: nil)`

I noticed, that even though I turned AKSettings.enableRouteChangeHandling to false, the AudioKits Notification is still running. I don't know why but I also don't understand why this listener is added to NotificationCenter.default in AudioKit+StartStop.swift in the first place. Shouldn't it be left out if enableRouteChangeHandling is set to false instead of asking for this status inside of restartEngineAfterRouteChange? Any idea how to remove it without altering the library itself? I would like to keep the public release.

**Comment by zebpedersen** [comment]
Thanks for sharing this tip. Is there any similar workaround for full duplex Bluetooth audio? (i.e. mic input & output at >16kHz/mono?)

**Comment by romancfischer** [comment]
@zebpedersen I actually don't know, I'm sorry.

The behaviour for this issue in iOS 13.1 on iPad changed a bit. I am at least able now to switch the output device seemingly via the Control Center at least when starting the app while Bluetooth is connected..
