### ISSUE TITLE
SequencerDemo not running

### ISSUE THREAD

**Issue by songproducer** [AudioKit/AudioKit#1828]
> objc[2260]: Class _NSZombie_FBSXPCMessage is implemented in both ?? (0x600003e37570) and ?? (0x600003e2cdb0). One of the two will be used. Which one is undefined.
> objc[2260]: Class _NSZombie_OS_xpc_int64 is implemented in both ?? (0x600003e2ce40) and ?? (0x600003e375a0). One of the two will be used. Which one is undefined.
> AKMIDI.swift:init():63:Initializing MIDI

**Comment by aure** [comment]
@songproducer Thanks for finding all these issues, I will get right on it!

**Comment by aure** [comment]
I have tested this demo on the simulator and on an actual iPad and it works on both. I would need more information about your problem to investigate further.

**Comment by songproducer** [comment]
I am testing on simulator for iPad Pro (12.9-inch) (3rd generation) - which I have but am travelling for next few days and don't have the usb-a to usb-c cable with me right now.

If there's any steps you'd like me to do I'm happy to try.
