### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler: /Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/x86_64.swiftmodule

### ISSUE THREAD

**Issue by jieatgstdev** [AudioKit/AudioKit#1831]
Hi,

Now, I am facing this issue. my AudioKit version is 4.6.1, and Xcode version is 10.3.

I noticed that other comment areas say that AudioKit version can be upgraded to 4.7.1, but I have never been successful.

![image](https://user-images.githubusercontent.com/13427113/62857623-ad94d880-bd2a-11e9-82a2-d161540e8bad.png)

**Comment by moyerr** [comment]
@jieatgstdev Why did you close this issue? Is it resolved? I am currently experiencing the same issue, and cannot figure out how to resolve it. The odd thing is, despite the error message, I am _not_ using the Swift 5.0.1 compiler. I have all my targets set to Swift 4.2

**Comment by LeftyTak** [comment]
@moyerr @jieatgstdev have you found any solution to this issue?  I am also experiencing the same issue.
