### ISSUE TITLE
midiOff not received with midi keyboards with 62+ keys

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#1832]
We are having a strange issue. When we connect any midi keyboard with 62+ keys, note on is coming in properly. But note off is not being received. Everything works as expected in the very same build for smaller keyboards

The only indication i see is a update from AudioKit `4.5.6` to `4.7.2`.

Is this a known issue?

**Comment by mlostekk** [comment]
I have just downgraded to 4.5.6 again (manually build with swift5) and the issue is gone.. was there a change since then?

**Comment by mlostekk** [comment]
I have tried `4.8` and the issue is also present there

**Comment by aure** [comment]
This sounds like it must have to do with the change to the MIDI listener protocol. Do you have an implementation example that we could see? I'm just back at this from a few days of vacation but I can take a look soon.

**Comment by aure** [comment]
This might be addressed by this change: https://github.com/AudioKit/AudioKit/commit/9dcb2f2177f9a575417484752bfb5b9bba6ddfa8

**Comment by aure** [comment]
I have tested the development branch and I am getting note offs with my 88 key keyboard.  I had to fix the MIDI Utility examples to use the MIDI listener protocol correctly and I imagine you'll need to do something similar.

**Comment by mlostekk** [comment]
okay great. i will give it a try and let you know. Any any ETA for the changes above?

**Comment by aure** [comment]
They are already in develop. Are you asking when it will be pushed to master or put into a CocoaPod?

**Comment by mlostekk** [comment]
Yes, i am wondering when its going to be published to cocoapods

**Comment by mlostekk** [comment]
Mh, i have build a framework from latest develop, updated the protocol handler and i am still not receiving the `noteOff` events.

when checking the file `AudioKit.swift` inside the module cache folder in `DerivedData` i see this

```

public protocol AKMIDIListener {

    /// Receive the MIDI note on event
    ///
    /// - Parameters:
    ///   - noteNumber: MIDI Note number of activated note
    ///   - velocity:   MIDI Velocity (0-127)
    ///   - channel:    MIDI Channel (1-16)
    ///
    func receivedMIDINoteOn(noteNumber: MIDINoteNumber, velocity: MIDIVelocity, channel: MIDIChannel)

    /// Receive the MIDI note off event
    ///
    /// - Parameters:
    ///   - noteNumber: MIDI Note number of released note
    ///   - velocity:   MIDI Velocity (0-127) usually speed of release, often 0.
    ///   - channel:    MIDI Channel (1-16)
    ///
    func receivedMIDINoteOff(noteNumber: MIDINoteNumber, velocity: MIDIVelocity, channel: MIDIChannel)

    /// Receive a generic controller value
    ///
    /// - Parameters:
    ///   - controller: MIDI Controller Number
    ///   - value:      Value of this controller
    ///   - channel:    MIDI Channel (1-16)
    ///
    func receivedMIDIController(_ controller: MIDIByte, value: MIDIByte, channel: MIDIChannel)

    /// Receive single note based aftertouch event
    ///
    /// - Parameters:
    ///   - noteNumber: Note number of touched note
    ///   - pressure:   Pressure applied to the note (0-127)
    ///   - channel:    MIDI Channel (1-16)
    ///
    func receivedMIDIAftertouch(noteNumber: MIDINoteNumber, pressure: MIDIByte, channel: MIDIChannel)

    /// Receive global aftertouch
    ///
    /// - Parameters:
    ///   - pressure: Pressure applied (0-127)
    ///   - channel:  MIDI Channel (1-16)
    ///
    func receivedMIDIAfterTouch(_ pressure: MIDIByte, channel: MIDIChannel)

    /// Receive pitch wheel value
    ///
    /// - Parameters:
    ///   - pitchWheelValue: MIDI Pitch Wheel Value (0-16383)
    ///   - channel:         MIDI Channel (1-16)
    ///
    func receivedMIDIPitchWheel(_ pitchWheelValue: MIDIWord, channel: MIDIChannel)

    /// Receive program change
    ///
    /// - Parameters:
    ///   - program:  MIDI Program Value (0-127)
    ///   - channel:  MIDI Channel (1-16)
    ///
    func receivedMIDIProgramChange(_ program: MIDIByte, channel: MIDIChannel)

    /// Receive a MIDI system command (such as clock, sysex, etc)
    ///
    /// - parameter data: Array of integers
    ///
    func receivedMIDISystemCommand(_ data: [MIDIByte], time: MIDITimeStamp)

    /// MIDI Setup has changed
    func receivedMIDISetupChange()

    /// MIDI Object Property has changed
    func receivedMIDIPropertyChange(propertyChangeInfo: MIDIObjectPropertyChangeNotification)

    /// Generic MIDI Notification
    func receivedMIDINotification(notification: MIDINotification)
}
```

The protocol seems not to be updated

**Comment by mlostekk** [comment]
i have tried `4.6.4`, same issue here. noteOff is not incoming.. trying to nail down the version

**Comment by mlostekk** [comment]
well... nailed it down to be introduced in `4.6.0`. the strange thing i just realized is, that we also have an `AKAppleSampler` attached. This device is receiving the `noteOffs` properly from what i hear. Just our client is not receiving them. Doublechecking the protocol

**Comment by mlostekk** [comment]
Mh, seeing this issue in `4.6.0` but not in `4.5.6`. But in between there was not protocol change. so just tried the exact same version of our app, but the issue pops up with `4.6.0` but note offs are properly received with `4.5.6`. 

Any other ideas what the cause could be?

**Comment by aure** [comment]
While I don't see it here in the log, I have an email in which an old version of the MIDI protocol listener was pasted in.  I feel like this still must be the root of the problem. Any way you can add me to the project if its a private repo so I can test for myself. Also willing to do a screen share on your computer if that is more appropriate / easier / quicker.

**Comment by mlostekk** [comment]
yep. i was suspecting this too. But using the same implementation of the protocol between version `4.5.6` and `4.6.0` leads to the same problem while the protocol was not changed in this versions right?

**Comment by aure** [comment]
There were pretty extensive MIDI changes between those two versions. I'd really rather get it fixed for you on the most recent master or even develop branch (and then make a release).
