### ISSUE TITLE
Won't build on Xcode 11 beta 5 (Inc Staging Version)

### ISSUE THREAD

**Issue by AssyriaGameStudio** [AudioKit/AudioKit#1834]
So it looks like the library just needs quickly recompiling with Xcode 11 beta 5, as I'm getting the following error when trying to compile with version AudioKit version 4.8.b1.

Compiled module was created by an older version of the compiler; rebuild 'AudioKit' and try again: /Users/adamgreen/Documents/Projects/sleepiest-texture/Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/arm64-apple-ios.swiftmodule

**Comment by megastep** [comment]
Ugh, so much for Swift 5 having a stable ABI

**Comment by megastep** [comment]
I've made a 4.8.1.b1 beta build and uploaded it, however it's failing pod validation right now...

**Comment by megastep** [comment]
Actually, it turns out that it doesn't validate on Catalina but works on Mojave. So try to update your pod to 4.8.1.b1 and that one is built with beta 5.

**Comment by AssyriaGameStudio** [comment]
Hey @megastep - I'm getting the following error when trying to install the pod with version 4.8.1.b1.

`[!] Error installing AudioKit
[!] /usr/bin/curl -f -L -o /var/folders/gx/pp1d19b52qn79_8wm3k31xqr0000gn/T/d20190819-5076-vuyhg5/file.zip https://files.audiokit.io/staging/v4.8.1.b1/AudioKit.framework.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server`

(Unfortunately I'm on Catalina, which I suspect is the cause given you've said it doesn't validate on Catalina)?
