### ISSUE TITLE
AKSampler goes silent across engine pause/start

### ISSUE THREAD

**Issue by ghubaddole** [AudioKit/AudioKit#1836]
To fix this, I need to unload and reload all samples. 
Other nodes (AKPlayer for instance) doesn't have this behavior.

**Comment by ghubaddole** [comment]
Thanks Shane for such a lightening fast fix!
Is there also an easy way to unload a sample corresponding to a specific descriptor, or is unloadAll the recommended way? I'd like to do lazy loading of samples which currently is not possible. (that way glitching due to stopVoices -> unload all -> reload -> start voices can be avoided).

**Comment by getdunne** [comment]
There's currently no way to do this, but I'd like to understand your goal better. Please email me directly shane [at] audiokitpro.com to discuss.

**Comment by ghubaddole** [comment]
That fix worked amazingly well!! Thank you -- it makes my code much simpler now - and bug free. earlier,  there were many corner cases that were not satisfactorily handled. Thanks again!
