### ISSUE TITLE
Won't build on Xcode 11 beta 6

### ISSUE THREAD

**Issue by NickolayRybalkoMobidev** [AudioKit/AudioKit#1839]
I think it is the same as in previous issue with Xcode beta 5
https://github.com/AudioKit/AudioKit/issues/1834

Compiled module was created by an older version of the compiler; rebuild 'AudioKit' and try again: .../Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/arm64-apple-ios.swiftmodule

**Comment by jpeckner** [comment]
I'm also seeing this issue, even when using `pod 'AudioKit', '=4.8.1.b1'`

**Comment by megastep** [comment]
I just rebuilt 4.8.1.b1 with beta 6, make sure to clear your pod cache and reinstall it. It appears that the last few betas have not been binary compatible with each other (!!)
