### ISSUE TITLE
Sample rate of 16khz leads to pitched down audio

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#1840]
Is it a known behavior that, when setting 

```
AKSettings.sampleRate = 16000.0
```

and playing back some files with the `AKAudioPlayer`, sooner or later the sample rate switches again to a higher one (usually 44.1khz) and then the playback by `AKAudioPlayer` sounds way pitched down?

I dont have a repro repository yet, but will make one during the next days.

**Comment by mlostekk** [comment]
Here is the repro repo... just hit `play` a couple of times, not too fast, but also no need to wait for long (2 seconds). After that the audio is played with a low pitch. Initially i thought that this might be related to the video, but i see that its happening without the video too. so ignore the code for the video (its commented out in the button press function, therefore unused)

https://github.com/mlostekk/AudioKitSampleRate

**Comment by mlostekk** [comment]
when commenting out the line

`AKSettings.sampleRate = 16000.0`

its not possible to reproduce this issue anymore.

Any ideas=

**Comment by aure** [comment]
Huh, I feel like this is unavoidable and working sort of as expected. You're pulling 44.1 data at 16 so  it should be slow. If you want to convert the file to 16 you can do that, but AKAudioPlayer is not going to do it for you. Unless I am missing something?  Feel free to continue to comment on this issue but I will close it for now.

**Comment by mlostekk** [comment]
Well, but why is it working initially.

**Comment by aure** [comment]
Okay, it took a while but I was able to reproduce it playing at normal speed (for quite a few plays) before finally playing at a slow speed. I don't know what could be causing this.

**Comment by aure** [comment]
Do you need to recreate the audioPlayer every time? When I move that let file...mixer.connect stuff up to view did load I don't get the slow down happening.

**Comment by mlostekk** [comment]
Unfortunately yes, we dont know in advance how many players will be playing. I am thinking of creating a player pool. Anyways it would be interesting to know why and when the os changes the samplerate, and why AK starts to get hickups with that changes
