### ISSUE TITLE
Cocoapods to build AudioKit as dynamic library

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#1843]
I know we had this discussion already, but i am wondering if there is a way via the podfile to specify that AudioKit shall be build and included as a dynamic library? I know all the disadvantages of that approach, but we have a legacy system that make the usage as a static library pretty complex. Any ideas?

**Comment by aure** [comment]
No I don't believe so.  Hopefully XCFrameworks will simplify our lives in the near future. @megastep if you have anything to add, please by all means.
