### ISSUE TITLE
"too many open files" problem when loading Wavpack files

### ISSUE THREAD

**Issue by loolloo** [AudioKit/AudioKit#1844]
When I load Wavpack samples with AKSampler repeatedly, I eventually get the "too many open files" error. This happens after loading samples over and over again across several AKSampler instances.

It looked like the issue was adressed before but it was reverted: https://github.com/getdunne/AudioKit/commit/e00d27b417f7eec14cf369a25b8bd2e2480a65e9

**Comment by getdunne** [comment]
That reversion was done because it was a temporary hack. The actual bug was a missing function call in AKSamplerDSP.mm, which was corrected in two commits on April 23.

The "too many open files" error happens when you open lots of files and never close them. Could you be doing this in your own code somewhere? SFZ files, perhaps? How are you loading samples?

Don't forget to call AKSampler.unloadAllSamples() before loading new samples. This used to get done in AKSampler.deinit() but that was changed recently. This shouldn't result in "too many open files" errors, but could cause memory leaks.

**Comment by loolloo** [comment]
I am using this code to load SFZ files: https://github.com/AudioKit/SamplerDemo/blob/master/iOS/SamplerDemo/AKSampler%2BmoreSFZ.swift

And I think that the problem may be comming from loading Wavpack since I didn't have any issues loading Wav samples.
Also my Xcode debugger shows this for many samples before triggering the error:
```
AKSampler+SFZ.swift:loadSfzWithNewLines(path:fileName:):94:load 84 1046.5023 Hz range 84-88 vel 0-127 samples/C6.wv
Wavpack error loading /Users/lucanguilla/Library/Developer/CoreSimulator/Devices/D9C0E9C3-AAD5-4669-B24F-FCD85BB72B51/data/Containers/Bundle/Application/76C77ECC-83A8-424D-885F-93D13805F57F/Symphonia.app/InstrumentSamples/SpanishClassicalGuitar-SFZ-20190618/samples/C6.wv: can't open file
```
The error happens the next time the sfz file is loaded:
```
AKSampler+SFZ.swift:loadSfzWithNewLines(path:fileName:):126:Error Domain=NSCocoaErrorDomain Code=256 "(null)" UserInfo={NSFilePath=/Users/lucanguilla/Library/Developer/CoreSimulator/Devices/D9C0E9C3-AAD5-4669-B24F-FCD85BB72B51/data/Containers/Bundle/Application/76C77ECC-83A8-424D-885F-93D13805F57F/Symphonia.app/InstrumentSamples/SpanishClassicalGuitar-SFZ-20190618/SpanishClassicalGuitar-20190618.sfz, NSUnderlyingError=0x600000319350 {Error Domain=NSPOSIXErrorDomain Code=24 "Too many open files"}}
```

**Comment by getdunne** [comment]
You say you're using the AKSampler+moreSFZ.swift code, but your error messages indicate AKSampler+SFZ.swift, and a function name (loadSfzWithNewLines) I don't recognize.

I wonder if you might not be using the latest version of the AudioKit framework. Are you using a CocoaPods build, or something else?

**Comment by loolloo** [comment]
The filename and the function name are different, but the code is basically the same.
here is my code if you want to check:  [mySfzLoader.zip](https://github.com/AudioKit/AudioKit/files/3531264/mySfzLoader.zip)

I am using a CocoaPods build, here is the version
```
PODS:
  - AudioKit (4.7.1):
    - AudioKit/Core (= 4.7.1)
    - AudioKit/UI (= 4.7.1)
  - AudioKit/Core (4.7.1)
  - AudioKit/UI (4.7.1):
    - AudioKit/Core
```

**Comment by getdunne** [comment]
Your code looks fine. AK 4.7.1 might not have the important changes. Try
  pod repo update
  pod install
That should get you up to 4.8.something, then clean and rebuild your app.

**Comment by aure** [comment]
I agree with @getdunne feel free to comment here if you're still having problems after trying his suggestions.

**Comment by loolloo** [comment]
Updating pods solved the issue. Thank you.
