### ISSUE TITLE
loopCompletionHandler not called when buffering = .always

### ISSUE THREAD

**Issue by WendelVolm** [AudioKit/AudioKit#1852]
loopCompletionHandler is called perfectly fine until i set buffering to always

Simple reproduction:

```
if let mixloop = try? AKAudioFile(readFileName: "mixloop.wav") {
    player = AKPlayer(audioFile: mixloop)
    player.loopCompletionHandler = { AKLog("loop callback has been triggered!") }
    player.isLooping = true
    player.buffering = .always
    AudioKit.output = player
    try! AudioKit.start()
    player.play()
}
```
This is on iOS 12

**Comment by WendelVolm** [comment]
So in AKPlayer+Playback.swift in handleCallbackComplete it will normally call the callbacks, were it not for this part (line 265)

```
// reset the loop if user stopped it
if self.isLooping && self.buffering == .always {
    self.startTime = self.loop.start
    self.endTime = self.loop.end
    self.pauseTime = nil
    return
}
```

Which will return before the handleComplete() and loopCompletionHandler?() can be called. Any help would be much appreciated.

**Comment by ryanfrancesconi** [comment]
the completion handler doesn't fire when loop buffering. that's how it works in the apple scheduler.
