### ISSUE TITLE
@objc and minimized inference / README update?

### ISSUE THREAD

**Issue by dreamwieber** [AudioKit/AudioKit#1854]
I was dusting off an old Objective-C project and it wasn't seeing the initializer of AKFFTTap – I tracked down the change:

https://github.com/AudioKit/AudioKit/commit/f59da655b035e769e4d9b0e98e8d71621bc50690#diff-b4a7bf8afa4b84ec5e248da8c71c4fa1

What I realized was that my project wasn't using swift 3 @objc inference. 

Might bite people with older projects – perhaps worth adding a note to the install instructions for Objective-C users that they should make sure inference is enabled?

**Comment by aure** [comment]
Sounds like a good idea, would you like to make a pull request?

**Comment by dreamwieber** [comment]
No prob! Pull request here: https://github.com/AudioKit/AudioKit/pull/1865

**Comment by aure** [comment]
Thank you!
