### ISSUE TITLE
Synthesis.playground > Drum Synthesizers fails

### ISSUE THREAD

**Issue by mjaal** [AudioKit/AudioKit#1855]
Running the playground fails with the following error message:

error: Drum Synthesizers.xcplaygroundpage:29:60: error: missing argument for parameter 'channel' in call
        snare.play(noteNumber: 60, velocity: randomVelocity)
                                                           ^
                                                           , channel: <#MIDIChannel#>

**Comment by aure** [comment]
This is fixed on the develop branch and will be in the next release, but you can see the easy fix:

https://github.com/AudioKit/AudioKit/blob/develop/Playgrounds/AudioKitPlaygrounds/Playgrounds/Synthesis.playground/Pages/Drum%20Synthesizers.xcplaygroundpage/Contents.swift
