### ISSUE TITLE
Pod, Swift project, XCode; "Use of unresolved identifier AKInstrument"

### ISSUE THREAD

**Issue by eliotstock** [audiokit/AudioKit#186]
I've installed your pod and added this to my bridging header in my Swift iOS project:

    #import <AudioKit/AKFoundation.h>

When trying to use your classes:

        let instrument = AKInstrument()

XCode can't see them. I do NOT want to add a separate subproject just to use this in my project. I can't even see your AudioKit.swift file under the pod in XCode.

**Comment by aure** [comment]
Hi there,

Yeah, I am not sure if the CocoaPod support for Swift is working for AudioKit right now.  Do you think you could try the installation instructions from:

http://audiokit.io/tutorials/

I am happy to help you through Screenhero screensharing if you're so inclined.

Aure

**Comment by aure** [comment]
I'm going to close this for now and reopen if requested.
