### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by DaveWoodCom** [AudioKit/AudioKit#1860]
Unable to import AudioKit into an Xcode 11 project when using the `vendored_frameworks` in CocoaPods.

Xcode 11 gives the following error:

```
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/<snipped>/Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/x86_64.swiftmodule
```

I assume the supplied framework needs to be rebuilt using the Xcode 11 GM?

Xcode Version: Xcode 11 (11A419c)

**Comment by sieren** [comment]
Correct. As a temporary workaround I'd remove the static Frameworks and just drop in the `AudioKit for iOS` xcodeproj into your project (make sure to set it as a dependency / "link with binaries" in your app)

**Comment by megastep** [comment]
It's weird that I've had no issues linking with the 4.8 pod in Xcode 11 GM. In any case, we should probably push out 4.8.1 built with Xcode 11 at some point soon...

**Comment by sieren** [comment]
Oh yeah, might be different when working with the Pods.. In that case `xcode-select -s /Applications/Xcode.app` may do the trick (in case you run multiple Xcode versions @DaveWoodCom )

**Comment by megastep** [comment]
I don't think it really matters because the root of this issue is our pod uses pre-built binaries (still on Xcode 10 at this point). The Swift ABI was supposed to be stable finally so in theory you'd think they would link with any subsequent version of Xcode, but it was definitely broken during the beta period.

**Comment by DaveWoodCom** [comment]
Yes, this is just because of the pre-built binaries built with Xcode 10.

Swift ABI stability only applies to run-time, doesn't apply to compile time. See the blog post about it here: https://swift.org/blog/abi-stability-and-more/#module-stability

**Comment by smarchant-owlet** [comment]
@aure @DaveWoodCom Do you know what the timeline is for issuing a release that fixes this issue?  This will probably become a bigger issue next week, once Xcode 11 rolls out as the final public version.

**Comment by aure** [comment]
As soon as possible!

**Comment by benpackard** [comment]
Would be great to know if anyone has a workaround for Cocoapods users in the meantime. We have a non-AudioKit iOS 13 bug that we are blocked from working on at the moment since we can't compile on Xcode 13.

**Comment by aure** [comment]
Man, we have our hands full just with Xcode11, never mind 13. ;)

**Comment by benpackard** [comment]
Lol oops.

**Comment by megastep** [comment]
Version 4.9 was just pushed out, including a pod built with Xcode 11 GM 2.

**Comment by aboelbisher** [comment]
Hi
did any one found a fix (workaround) for this ?

**Comment by sieren** [comment]
Did you update your Podfile to 4.9?

**Comment by markjeschke** [comment]
@aboelbisher, the mistake that I made, was having Xcode's command line tools _**pointing to the Xcode 10.3 version, instead of Xcode 11.**_ After updating its path with `sudo xcode-select -switch /Applications/Xcode.app`, I was finally able to `pod update` to AudioKit 4.9. Prior to that change, I was only able to install AudioKit 4.7.1, which isn't compatible with Xcode 11 (hence the "Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler" error).

Don't forget to run `pod update`. Please let us know if this helps.

**Comment by TanushreeFating** [comment]
@DaveWoodCom I was facing the same issue for that I have updated my local copy of Swift as well you can do that in XCode's Preferences under Location ->

**Comment by markjeschke** [comment]
Ah, nice shortcut, @DaveWoodCom!

**Comment by jeremycochoy** [comment]
Could we have a 4.8 (.1) build compatible with XCode 11?

**Comment by aure** [comment]
You can make one if you want.

**Comment by romancfischer** [comment]
Just tried compiling version 4.9.1 ( via CocoaPods ) in Xcode 11 Beta 2 with the following result:

> Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.1 compiler

It seems to work when using a different Swift toolchain but that breaks all my other libraries..

**Comment by coreyackland** [comment]
Anyone have an update for this? I've tried using the latest release of AudioKit and also tried implementing it via Cocoa pods, nothing works for me. Xcode Version 11.2 (11B52)

**Comment by aure** [comment]
@coreyackland Works for me, possible that you have a cached copy of AudioKit somewhere. Its really weird that an old version of AUdioKit would work. Which one? how old? like v2? :)

**Comment by coreyackland** [comment]
Ok so downloading directly from the website, AudioKit ver 4.9 is pulled (which is where I was having issues). Downloading from https://github.com/audiokit/AudioKit/releases, with version 4.9.2 works.

**Comment by aure** [comment]
Oh thank you, I forgot to update the web site. Fixed now.
