### ISSUE TITLE
DOCS: Update Playground docs about Callback Instrument and Background Modes

### ISSUE THREAD

**Issue by hepiyellow** [AudioKit/AudioKit#1868]
When trying to run the Callback Instrument playground in a real project.
It doesn't work unless the project enables the "Background Modes - Audio".

I think this is worth mentioning in the Callback [Instrument playground](https://github.com/AudioKit/AudioKit/blob/master/Playgrounds/AudioKitPlaygrounds/Playgrounds/Playback.playground/Pages/Callback%20Instrument.xcplaygroundpage/Contents.swift) itself.
Since troubleshooting this is not trivial.

See Stackoverflow:
https://stackoverflow.com/questions/57954724/akmidicallbackinstrument-callback-not-called/57961358#57961358

**Comment by aure** [comment]
Check the changes in that commit. It should appear in documentation and in playgrounds now.
