### ISSUE TITLE
memory leak in AKPeriodicFunction

### ISSUE THREAD

**Issue by inhumanscale** [AudioKit/AudioKit#1870]
I have been using AudioKit 4.7.1 AKPeriodicFunction on macOS and noticed memory growing even for simple use cases. I have not tested on iOS yet.

I implemented a simple example that you can run through Leaks to track the memory.
```swift
        let path = Bundle.main.resourcePath! + "/leadloop.wav"
        let player = AKPlayer(url: URL(fileURLWithPath: path))!
        player.isLooping = true
        let periodicFunction = AKPeriodicFunction(frequency: 5.0){
        }
        AudioKit.output = player
        try? AudioKit.start(withPeriodicFunctions:periodicFunction)
        periodicFunction.start()
        player.play()
```
Memory should not be increasing in this example. Here is the heaviest part of the stack trace that may be helpful,
```  
  11 AudioToolbox      34.11 MB     __26-[AUAudioUnit renderBlock]_block_invoke
  10 macos-leak-test   34.11 MB     __52-[AKOperationGeneratorAudioUnit internalRenderBlock]_block_invoke
   9 macos-leak-test   34.11 MB     DSPKernel::processWithEvents(AudioTimeStamp const*, unsigned int, AURenderEvent const*)
   8 macos-leak-test   34.11 MB     AKOperationGeneratorDSPKernel::process(unsigned int, unsigned int)
   7 macos-leak-test   34.11 MB     plumber_compute
   6 macos-leak-test   34.11 MB     plumbing_compute
   5 macos-leak-test   34.11 MB     sporth_fexec
   4 macos-leak-test   34.11 MB     akCustomUgenFunction(plumber_data*, sporth_stack*, void**)
   3 libobjc.A.dylib   34.11 MB     -[NSObject autorelease]
```

**Comment by inhumanscale** [comment]
I've upgraded to 4.9 and am noticing a similar issue/stack track on iOS.  I have not tested with the above example but believe the behavior should be the same regardless of macOS/iOS.

**Comment by aure** [comment]
I have an even simpler example that exhibits the behaviors:

        let osc = AKOscillator()
        let pf = AKPeriodicFunction(frequency: 5.0) { [weak self] in }
        AudioKit.output = osc
        try! AudioKit.start(withPeriodicFunctions: pf)
        pf.start()

**Comment by aure** [comment]
I will have to put out an AudioKit 4.9.1 with this very important fix! Thank you.
