### ISSUE TITLE
Failed to fill complex buffer in float converter

### ISSUE THREAD

**Issue by ashishkeshan** [AudioKit/AudioKit#1873]
I am receiving this error as soon as I try to play an audio file using the EZAudioPlayer: **Error: Failed to fill complex buffer in float converter ('insz')**

My code to setup the AVAudioSession is as follows:

```
try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, mode: AVAudioSessionModeDefault)
try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, mode: AVAudioSessionModeDefault)
try AVAudioSession.sharedInstance().setPreferredSampleRate(48000)
try AVAudioSession.sharedInstance().setActive(true)
```
I am testing this on an iPhone 11 running iOS 13. This issue was not happening on my iphone 8 running iOS 12, and also does not present itself in the iphone 11 simulator on Xcode running iOS 13.

Does anyone have any suggestions?

**Comment by ashishkeshan** [comment]
I just set up a sample project here with the EZAudio source code to show the exact error: https://github.com/ashishkeshan/TestEZAudioBug

I am trying to set the sample rate to 48000, but for some reason, the value is not getting updated. The sample rate is always 44100 no matter what code I add, and this is causing the buffer sizes to be 940 or 941 frames resulting in the mismatch. Do you think you could take a look at the project to see if there are any fixes that you can think of? Thanks!

**Comment by nishbu** [comment]
Tried running your build on my device and I’m getting the same issue except I have an iPhone XR running iOS13.

**Comment by IlyaBlinov** [comment]
Guys, I set in file EZOutput.m constant : Float64 const EZOutputDefaultSampleRate = 44100.0f and changed: - (void)convertDataFromAudioBufferList:(AudioBufferList *)audioBufferList
 withNumberOfFrames:(UInt32)frames  toFloatBuffers:(float **)buffers
  packetDescriptions:(AudioStreamPacketDescription *)packetDescriptions in EZAudioFloatConverter.m. I changed :
[EZAudioUtilities checkResult:AudioConverterFillComplexBuffer(self.info->converterRef,
                                                                      EZAudioFloatConverterCallback,
                                                                      audioBufferList,
                                                                      &frames,
                                                                      self.info->floatAudioBufferList,
                                                                      packetDescriptions ? packetDescriptions : self.info->packetDescriptions)
                            operation:"Failed to fill complex buffer in float converter"];     To   
OSStatus status =    AudioConverterFillComplexBuffer(self.info->converterRef,
                                                  EZAudioFloatConverterCallback,
                                                  audioBufferList,
                                                  &frames,
                                                  self.info->floatAudioBufferList,
                                        packetDescriptions ? packetDescriptions : self.info->packetDescriptions);
       
        NSLog(@"status = %d",(int)status);

Status have the value = 1768846202 sometimes.   But it woks for me

**Comment by victaie** [comment]
Same issues with iOS 13.1.X. When i run my project which works correctly with iOS12, I got "Failed to fill complex buffer in float converter('insz')" error. Are there some compatibility issues with iOS 13 ?

**Comment by IlyaBlinov** [comment]
Yes, I had a same problem when had updated my device to iOS 13.1. Now I am using this solution for playing music in my own app

**Comment by victaie** [comment]
> Yes, I had a same problem when had updated my device to iOS 13.1. Now I am using this solution for playing music in my own app

Could you please format your solution in a more friendly type? In fact,  it's hard to find where you had changed :)

**Comment by IlyaBlinov** [comment]
I set in file EZOutput.m constant : Float64 const EZOutputDefaultSampleRate = 44100.0f and   in EZAudioFloatConverter.m I am changed method:  
- (void)convertDataFromAudioBufferList:(AudioBufferList *)audioBufferList
withNumberOfFrames:(UInt32)frames toFloatBuffers:(float **)buffers
packetDescriptions:(AudioStreamPacketDescription *)packetDescriptions. At this method I changed: 
OSStatus status = AudioConverterFillComplexBuffer(self.info->converterRef,
EZAudioFloatConverterCallback,
audioBufferList,
&frames,
self.info->floatAudioBufferList,
packetDescriptions ? packetDescriptions : self.info->packetDescriptions);
if (status > 0 ) {
AudioConverterReset(self.info->converterRef);
}
 Status had errors sometimes and I am reset it to calculate FFT by this function "AudioConverterReset(self.info->converterRef);" Sorry for not friendly text. There are so much text in fuctions/

**Comment by victaie** [comment]
Great, it works for me! Thank you !

**Comment by sasanao** [comment]
It works, but it doesn't seem to be an essential solution.
How can I fix the OSStatus error?

**Comment by IlyaBlinov** [comment]
I don't know how fix this bug without errors. This bug appeared when I had updated my device to IOS 13.1. May be it's IOS bug.

**Comment by jieatgstdev** [comment]
Swift 5.1 cocoapods install.   sample issue.   
how to fix it easily? 

 public let audioPlayer: EZAudioPlayer!
 audioPlayer = EZAudioPlayer()
 audioPlayer.delegate = self
 public func playAudio(url: URL) {
        do {
            let file = try! EZAudioFile(url: url)
            audioPlayer.audioFile = file
        } catch {
            print("\(error)")
        }
        audioPlayer.play()
    }

**Comment by mahadshahib** [comment]
hi can you show me how to change that function I don't know much objective c and I don't know where should I put that code in ezaudiofloatconveter.m file can you help? @IlyaBlinov

**Comment by vishal-i4gs** [comment]
> I don't know how fix this bug without errors. This bug appeared when I had updated my device to IOS 13.1. May be it's IOS bug.

Has it been fixed in 13.2 or 13.3? if so its an iOS issue?

**Comment by dharmeshrchauhan** [comment]
> I set in file EZOutput.m constant : Float64 const EZOutputDefaultSampleRate = 44100.0f and in EZAudioFloatConverter.m I am changed method:
> 
> ```
> - (void)convertDataFromAudioBufferList:(AudioBufferList *)audioBufferList
>                     withNumberOfFrames:(UInt32)frames
>                         toFloatBuffers:(float **)buffers
>                     packetDescriptions:(AudioStreamPacketDescription *)packetDescriptions
> ```
> 
> At this method I changed:
> 
> ```
> OSStatus status = AudioConverterFillComplexBuffer(self.info->converterRef,
>                                                   EZAudioFloatConverterCallback,
>                                                   audioBufferList,
>                                                   &frames,
>                                                   self.info->floatAudioBufferList,
>                                                   packetDescriptions ? packetDescriptions : self.info->packetDescriptions);
> if (status > 0 ) {
>     AudioConverterReset(self.info->converterRef);
> }
> ```
> 
> Status had errors sometimes and I am reset it to calculate FFT by this function "AudioConverterReset(self.info->converterRef);"
> 
> Sorry for not friendly text. There are so much text in fuctions/

This has worked for me, 
however it looks like fix is not applied in latest source code

**Comment by ashokbk** [comment]
sorry, I have been using EZAudio, not AudioKit but exact same fix worked there
