### ISSUE TITLE
Volume Control Issue on iPhone7

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#1874]
We are using the microphones input to do some DSP and AudioKit for output. Now with the current setup we are having some volume issues. So pulling down the volume does notmute it. On iphone7 we are also experiencing extremely loud playback from AudioKit.

Any idea what the reasons could be? Here is the demo project. Its working fine for lower devices (until iphone6splus) but starting from iphone7 the volume is highly unpredictable. Especially on iphone7 we cannot properly control the volume

https://github.com/mlostekk/AudioKitSampleRate/tree/issue/volumeControl

The branch is `issue/volumeControl`

P.S. Maybe worth to mention, we are using the audio component subtype `kAudioUnitSubType_VoiceProcessingIO` to enable echo cancellation

**Comment by ryanfrancesconi** [comment]
I'm not sure what your issue is, but I will say that AKAudioPlayer is no longer being maintained. You might try your project with AKPlayer instead.

**Comment by mlostekk** [comment]
to be honest, meanwhile i think its not audiokit related. I have created [this SO question](https://stackoverflow.com/questions/57612695/avaudioplayer-volume-low-with-voiceprocessingio). The volume control issues seem to happen with the `voiceProcessingIO`. 

https://github.com/mlostekk/AudioKitSampleRate/tree/issue/outputVolumeNoAudiokit (branch outputVolumeNoAudiokit)

**Comment by mlostekk** [comment]
I assume AudioKit just amplifies this issue that is already underlying. The volume control is pretty weird when AK is used on top of this setup as described in the branch / link above

**Comment by aure** [comment]
Since you don't think its AudioKit, I think I will close the issue here. Reopen if necessary. I upvoted the question on SO, hopefully with a high enough rating someone will answer it.
