### ISSUE TITLE
iOS 10.3.2 AKPlayer not call completionHandler when use 4.9

### ISSUE THREAD

**Issue by zzzworm** [AudioKit/AudioKit#1875]
We just upgrade our Xcode to 11, and we upgrade AudioKit to  4.9. This all work fine except our tester found that when user record and try play it, for a iphone 7 plus device, iOS 10.3.2 the player will not stop as expect, the progress will loop but no sound. There I debug found that,  AKPlayer not call completionHandler when it reach end, but same code works for iOS 12. I don't know why? Can anybody help me?

**Comment by ryanfrancesconi** [comment]
can i see the code you're using?

**Comment by zzzworm** [comment]
`@objc open class XMIClipPlayer: NSObject {
@objc open dynamic private(set) var list = Array<AKAudioFile>()
    open private(set) var current:Int = 0
    var mainMixer: AKMixer!
    @objc public private(set) var booster : AKBooster!
    @objc public private(set) var player : AKPlayer!
    /// Will be triggered when AKAudioPlayer has finished to play.
    /// (will not as long as loop is on)
    @objc open dynamic var completionHandler: AKCallback?
    
    @objc open dynamic var playEndedHandler: ClipPlayCallback?
    
    @objc open dynamic var willPlayHandler: ClipPlayCallback?
    
    private var _looping: Bool = false
    
    
    @objc public init(mixer:AKMixer) {
        super.init()
        mainMixer = mixer
        player = AKPlayer()
        player.completionHandler = playingEnded
        booster = AKBooster(player);
        booster.connect(to: mainMixer)
    }`

**Comment by ryanfrancesconi** [comment]
oh yes, in older iOS you will now need to implement the completion handler yourself. In that case Apple's completion handler timing is totally inaccurate, so previously AKPlayer used a Timer to determine when the end of the playback will happen and would fire an event that way. You will now need to implement this logic yourself using a Timer should you wish to support the older OS.
