### ISSUE TITLE
SDBooster Issue

### ISSUE THREAD

**Issue by themichael123** [AudioKit/AudioKit#1877]
Hi! After upgrading from 4.7.1 to 4.9 we are getting errors for our own SDBooster extension. This error can be replicated with the SDBooster included in AK. 

Specifically this line: float* in  = (float*)inBufferListPtr->mBuffers[0].mData + frameOffset;

throws the error: AURemoteIO::IOThread (19): EXC_BAD_ACCESS (code=1, address=0x10)

**Comment by getdunne** [comment]
You'll need to provide more details for me to reproduce the problem. I just obtained the latest code from the AudioKit develop branch, recompiled everything with Xcode 11, and tested both versions of the ExtendingAudioKit project at AudioKit/Developer/macOS (which uses SDBooster), and it runs fine. (iOS version has completely different issues which I'm investigating, likely related to iOS 13.) Can you provide a test project?

**Comment by themichael123** [comment]
I wasn't able to replicate this problem with a new project as we have such an elaborate AK implementation. Most probably it is an iOS 13 issue though.

**Comment by getdunne** [comment]
@themichael123 please close the issue unless you think there is something more that can be done now.

**Comment by themichael123** [comment]
Ok, so we are still seeing this issue. It also affects the SDBooster i.e. not just our customization. 

iOS: 13.3.1
Xcode: 11.2
AudioKit: Develop Branch

**Comment by themichael123** [comment]
<img width="420" alt="Screenshot 2020-02-27 at 20 35 53" src="https://user-images.githubusercontent.com/12985640/75480039-de73ec80-59a0-11ea-8f48-c453879285ae.png">

**Comment by themichael123** [comment]
This is from the logs: 

[general] AKBooster.swift:init(_:gain:):123:Parameter Tree Failed (AKBooster.swift:init(_:gain:):123)

**Comment by aure** [comment]
Okay, but if you scroll up I still think this shane's response is valid. Is there a small project that you can make available that demonstrates this? What happened with your new project that did not replicate the problem?

**Comment by themichael123** [comment]
Ok, solved the problem. It was an old header file which I forgot to update. Thanks for your help.
