### ISSUE TITLE
AudioKit issue or AVFoundation? 

### ISSUE THREAD

**Issue by geeksweep** [AudioKit/AudioKit#1878]
I don't want to waste anyone else's time in here but I wanted to verify that this has nothing to do with AudioKit. 

https://stackoverflow.com/questions/58193040/avaudiorecorder-audiokit-issues-ios-13-1-2

it seems really weird that it works on iOS 13.0 & 13.1 just not on iOS 13.1.1 or iOS 13.1.2

Anyone got an idea of whats going on here?

**Comment by geeksweep** [comment]
it looks like from that above link that something was wrong with not setting something to AudioKit.output. Not sure why there wasn't a problem up until iOS 13.1.x and everything IOS 13.1 and under worked. 

Any thoughts?

**Comment by aure** [comment]
Ugh, no idea.

**Comment by aure** [comment]
Looks like an answer on StackOverflow has been accepted so I'll close the issue here.
