### ISSUE TITLE
change in AKZitaReverb from 4.7.1 to 4.9

### ISSUE THREAD

**Issue by inhumanscale** [AudioKit/AudioKit#1879]
I'm noticing difference in the behavior of AKZitaReverb from 4.7.1 to 4.9.  Minimal example follows,

```swift
        let path = Bundle.main.resourcePath! + "/leadloop.wav"
        let player = AKPlayer(url: URL(fileURLWithPath: path))!
        player.isLooping = true
        let zr0 = AKZitaReverb(player)
        let zr1 = AKZitaReverb(zr0)
        AudioKit.output = zr1
        zr0.start()
        zr1.start()
        try? AudioKit.start()
        player.play()
```
Levels are definitely off but I cannot determine if there is more.

**Comment by aure** [comment]
Because I'm so grateful that you pointed out the memory leak, I thought I'd investigate this next and what's interesting is that we updated Soundpipe on May 15th, and had to update the tests to reflect that Zita Reverb did change.   The answer is definitely something in here https://github.com/AudioKit/AudioKit/commit/031a7dcc421850cb40cfc8d51636fba3f4b3dea8

**Comment by aure** [comment]
Here's the change: 
	
    interface->addHorizontalSlider(interface->uiInterface, "level", &dsp->fHslider0, 0.f, -70.f, 40.f, 0.1f);
 	interface->addHorizontalSlider(interface->uiInterface, "level", &dsp->fHslider0, -20.f, -70.f, 40.f, 0.1f);

**Comment by getdunne** [comment]
I had fixed this way back, but updating Soundpipe probably un-fixed it.

**Comment by aure** [comment]
Why was it changed only in AudioKit and not in Soundpipe?  Which value is "correct"?

**Comment by aure** [comment]
Happy to revert, just want to have a consensus.

**Comment by getdunne** [comment]
Pretty sure the changes I made were to the Soundpipe code. That fHslider business. The problem was that the Zita reverb gain wasn't getting initialized at all, so it was basically default to 0, hence no sound out. Look in the history of that file, and you'll see where I fixed it.

**Comment by aure** [comment]
I do see it, but it never made it back to the Soundpipe repo.

**Comment by aure** [comment]
I committed the reversal.
