### ISSUE TITLE
Cannot invoke initializer for type 'AKSequencer' with no arguments

### ISSUE THREAD

**Issue by dugulong** [AudioKit/AudioKit#1883]
If your issue is implementing AudioKit in your own code, post your problem to [StackOverflow](https://stackoverflow.com/search?q=AudioKit) with the #AudioKit hashtag.

GitHub Issues should only be used for confirmed problems with AudioKit and
well-defined feature requests.

Make sure you know about the common gotcha's outlined in this video:
https://vimeo.com/audiokit/connecting-nodes-part-2

Problems when submitting your app with the framework? First make sure to check your run phases are set up properly, as outlined in this doc:
https://github.com/AudioKit/AudioKit/blob/master/Frameworks/README.md

**Comment by dugulong** [comment]
I upgraded the xcode version to 11.0. Then re-downloaded the version of audiokit4.9 that supports ios11.0
The other questions are ok. A warning appeared when I recompile the code.
Cannot invoke initializer for type 'AKSequencer' with no arguments
my code is like is：

import AudioKit

class PlayMachine: NSObject {
    var sequencer = AKSequencer()

**Comment by aure** [comment]
You're probably intending to use the AKSequencer that has since been renamed "AKAppleSequencer" try changing the class type to that.  But, it is not a bad idea for us to include a blank initializer for the new AKSequencer. I'll work with @eljeff on that.

**Comment by aure** [comment]
Jeff took care of this, but proceed with caution because as I said, the class is totally different.
