### ISSUE TITLE
AKMixer issue in Recorder example project

### ISSUE THREAD

**Issue by knagle** [AudioKit/AudioKit#1888]
If I edit line 79 of the ViewController.swift file in the Recorder iOS example object from:

mainMixer = AKMixer(moogLadder, micBooster)

to:

mainMixer = AKMixer(moogLadder)

I get a crash such as below:

2019-10-08 11:01:36.297567+0100 Recorder[8058:2723212] [avae]            AVAEInternal.h:109   [AVAudioEngineGraph.mm:2053:InstallTapOnNode: (err = AUGraphParser::InitializeActiveNodesInInputChain(ThisGraph, *inputNode)): error -10868
2019-10-08 11:01:36.299539+0100 Recorder[8058:2723212] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10868'

This also happens in a project I have based on Recorder, where there are multiple AKNodeRecorders and AKWaveTables. If the mainMixer has five AkWaveTables plus the micBooster then all is well, if I remove the micBooster from the mixer I get the same crash as above.

**Comment by aure** [comment]
This is because the plot is using the mic node, and if it is not connected to the output through whatever (in this case micBooster), it can not be tapped.  Not an issue with AKMixer.

**Comment by knagle** [comment]
Thanks for the reply Aure. That makes total sense. However, if I disconnect the plot (don't give it a node to plot) so that it's always a flatline in the UI, then if I remove micBooster from the the AKMixer the app runs, but crashes when I tap record. The same error message as in my first comment above. I think I'm missing something fundamental about the setup here. If we change the gain of micBooster when we are recording and its not connected to output, does that mean we'll always get a crash?

**Comment by aure** [comment]
What is the node that is being recorded? If its the microphone, then you will still have the same problem as the plot was producing. Tapped nodes must be part of the signal chain going all the way down to the output, even if silenced at some point in that chain.
