### ISSUE TITLE
AKSequencer documentation is outdated

### ISSUE THREAD

**Issue by thorlucas** [AudioKit/AudioKit#1889]
The [documentation for AKSequencer](https://audiokit.io/docs/Classes/AKSequencer.html#/s:8AudioKit11AKSequencerCACycfc) no longer matches what is on AudioKit 4.9.

Attempts to call `init()` without parameters fail, as does `.newTrack()`.

**Comment by aure** [comment]
oh you are right! I'll fix mic today!

**Comment by aure** [comment]
Okay, so the init() only exists on the develop branch, so if you're using master you'll have to wait for AudioKit 4.9.1 which is what the docs currently show.
