### ISSUE TITLE
Clip rendering crash on actual device running iOS13.1.2

### ISSUE THREAD

**Issue by adubenkov** [AudioKit/AudioKit#1890]
I have met this problem with iOS 13.1.2 and AudioKit 4.9. Testing with iPhone XS.
I'm trying to render clip recorder result using this code:
```
        func preRender() {

            var scheduleTime : TimeInterval = 2
            let dspTime = AVAudioTime(sampleTime: AVAudioFramePosition(scheduleTime * AKSettings.sampleRate), atRate: AKSettings.sampleRate)
            if !clipsOnly {
                self.musicPlayer.play(at: dspTime)
                scheduleTime += 2
            }
            self.clipPlayer.play(at: dspTime)
        }


        let writeFile = try AKAudioFile()
        try AudioKit.renderToFile(writeFile, duration: duration + 2.0,
                                      prerender: preRender)
```

Expected result is rendered audio file. Code above works well in simulator with iOS 13.1.2 and also on a device with iOS 12.

Actual result on a device is:

`[avae]            AVAEInternal.h:109   [AVAudioEngineGraph.mm:1397:Initialize: (err = AUGraphParser::InitializeActiveNodesInInputChain(ThisGraph, *GetInputNode())): error -10868`

**Comment by aure** [comment]
Github issues is for posting problems with AudioKit that we can address, this is really much deeper and unclear what we should do, so it really should have been posted to StackOverflow. Also, while a snippet of code is good, a working GitHub project that exhibits the behavior would be a lot better.

**Comment by davidjaystrauss** [comment]
Also having this issue, but I'll follow it on SO. Just wanted to give a little +1 in here.

**Comment by adubenkov** [comment]
> Github issues is for posting problems with AudioKit that we can address, this is really much deeper and unclear what we should do, so it really should have been posted to StackOverflow. Also, while a snippet of code is good, a working GitHub project that exhibits the behavior would be a lot better.

Thank you for the answer. It's already on StackOverflow - [Link to SO](https://stackoverflow.com/questions/58291425/how-to-fix-ios-13-1-2-audiokit-rendertofile-exception-augraphparserinitialize) 
I will make a repo today and post it here.

**Comment by adubenkov** [comment]
@aure Here is the repo.
https://github.com/adubenkov/issue1890

**Comment by davidjaystrauss** [comment]
@adubenkov have you had any luck on this? Currently wracking my brain.
I've got two apps using AudioKit in a similar fashion, one of which works great still, the other one can't record at all. It's pretty crazy. Currently going through and adding in as much error logging as I can..

**Comment by davidjaystrauss** [comment]
As per usual, looks like this was an error on my part, in my patching.

I would double check all your patches. I was recording straight from the AKMic node and it didn't like that apparently, once I wrapped it into an AKMixer, things started working again.

**Comment by adubenkov** [comment]
> As per usual, looks like this was an error on my part, in my patching.
> 
> I would double check all your patches. I was recording straight from the AKMic node and it didn't like that anymore apparently, once I wrapped it into an AKMixer, things started working again.

Still got the issue. In my app, it's repeating on each renderToFile attempt. In issue1890 repo to represent error you need to press render twice. I have no idea how to fix it. I tried to update adudiokit to 4.9.1. Issue is still here.

**Comment by aure** [comment]
I'm burning through the issues on Github to the point that this is now the most recent one. I just want to double check with adubenkov that the problem hasn't changed and the project above is fully updated, thanks.

**Comment by aure** [comment]
I'll open the issue back up with more information.
