### ISSUE TITLE
Changing Frequency Or Pan Takes 100-200 MS.

### ISSUE THREAD

**Issue by jsl303** [AudioKit/AudioKit#1898]
When I change frequency of oscillator or pan of panner, it takes 100-200 milliseconds for the change to happen.
Also I can hear the sound gliding to the target frequency or pan position.
Is this a bug?
If not, can it be n instant change?
I'm using AudioKit v4.9.1 on macOS Catalina.
Thanks!

**Comment by aure** [comment]
Yes, that's the AudioKit default. Set the rampDuration to zero or whatever value you want.
