### ISSUE TITLE
Cannot play ogg file

### ISSUE THREAD

**Issue by lufutu** [audiokit/AudioKit#190]
Can AudioKit.io play OGG  file type ? Sorry i cannot find anywhere to submit question.
Thank you

**Comment by megastep** [comment]
What platform are you trying to use? We currently don't have Ogg Vorbis support on iOS, only OS X.

**Comment by lufutu** [comment]
I am using on iOS platform.
Thank for quick reply.

**Comment by narner** [comment]
Hi @lufutu! Just an FYI, here's the link for the [AudioKit Users Google Group] (https://groups.google.com/forum/#!forum/audiokit).
