### ISSUE TITLE
App crashing on playing/recording .wav file on iOS 13

### ISSUE THREAD

**Issue by afaq-hussain-tkxel** [AudioKit/AudioKit#1902]
I have this legacy app which was running on a fork of EZAudio. It started crashing on iOS 13 all of sudden with the error:

> ExtAudioFile.cpp:328:FileFormatChanged: about to throw 'fmt?': create audio file
Error: Failed to create audio file ('fmt?')

I removed EZaudio and added AudioKit in. but the Error still persists. 

The crash occurs on creating the recorder:

`self.recorder = [EZRecorder recorderWithURL:[GeneralUtility urlOfFile:kSecondaryRecording] clientFormat:[self.microphone audioStreamBasicDescription] fileType:EZRecorderFileTypeWAV delegate:self];`

The microphone is initiated as:

```
 self.microphone = [EZMicrophone microphoneWithDelegate:self];// withAudioStreamBasicDescription:basicDescription];
    self.player = [EZChartnetPlayer audioPlayerWithDelegate:self];
    
    self.inputs = [EZAudioDevice inputDevices];
    self.outputs = [EZAudioDevice outputDevices];
```

Any ideas?

**Comment by aure** [comment]
No, but you might have more luck asking StackOverflow. EZAudio was deprecated for AudioKit, but it doesn't mean we're doing the support for EZAudio.
