### ISSUE TITLE
AKPlayer problems or is it the way it should be?

### ISSUE THREAD

**Issue by temkich** [AudioKit/AudioKit#1905]
https://github.com/temkich/AudioKit-AKPlayer-problems
I added a repository with an example, the first problem is that there is a playback error if I try play with 

`

            let now = AVAudioTime.now()
            
            self.player1.play(at: now)
`

![](https://github.com/temkich/AudioKit-AKPlayer-problems/blob/master/AKPlayerProblems/AKPlayerProblems/AKPlayerProblem1.png?raw=true)

and second problem, when I try to play two files of the same tempo, but different in the number of beats, they are not synchronized:

`

    var mixer = AKMixer()
    var player1 = AKPlayer()
    var player2 = AKPlayer()
    var views = [UIView]()

    override func viewDidLoad() {
        super.viewDidLoad()
            
        AKSettings.enableLogging = true
        
        guard let clickOne = Bundle.main.url(forResource: "m1", withExtension: "mp3"),
        let clickTwo = Bundle.main.url(forResource: "m2", withExtension: "mp3")
        else {
                fatalError()
        }
            
        player1 >>> mixer
        player2 >>> mixer
        
        player1.isLooping = true
        player1.buffering = .always
        
        player2.isLooping = true
        player2.buffering = .always
        
        AudioKit.output = mixer
        do {
            try player1.load(url: clickOne)
            try player2.load(url: clickTwo)
            
            try AudioKit.start()
        } catch {
            AKLog("AudioKit did not start!")
        }
        setUpUI()
        
        player1.prepare()
        player2.prepare()
    }

    func setUpUI() {
        func startActionProblem1() ->(AKButton) -> Void {
            return { button in
            
            let now = AVAudioTime.now()
            
            self.player1.play(at: now)
            self.player2.play(at: now)
            
            }
        }
        
        func startActionProblem2() ->(AKButton) -> Void {
            return { button in
            
            let now = AVAudioTime.now() + 0.25
            
            self.player1.play(at: now)
            self.player2.play(at: now)
            }
        }
        
        addView(AKButton(title: "Problem1",
                         callback: startActionProblem1()))

        addView(AKButton(title: "Problem2",
                         callback: startActionProblem2()))
    }
`
For example, my files look like this:
![](https://github.com/temkich/AudioKit-AKPlayer-problems/blob/master/AKPlayerProblems/AKPlayerProblems/AKPlayerProblem2.png?raw=true)
The picture shows that the file m1.mp3 is exactly half the file m2.mp3, and ideally if they should loop out of the loop, but this does not happen, because files of different durations.
I do not understand why this is happening? Is this a bug? or should it be so? Does the AKPlayer add delay to schedule next loop?
If I start playing two files: m1 + m1 or m2 + m2 the result is synchronized
if I start playing: m1 + m2 the result is not synchronized

Maybe there is a problem due to the fact that these are mp3 files?

**Comment by aure** [comment]
Thank you for the excellently prepared issue. We (@ryanfrancesconi  or me) will have a look at this soon (in my case when power is restored!)

**Comment by ryanfrancesconi** [comment]
Hi, I took a look. 

In terms of problem 1, you are scheduling a sound that is in the past. AVAudioTime.now() is equivalent to mach_absolute_time at the time of your assignment. By the time you play, it's in the past. Use:

player1.play(when: 0) for this reason.

That said, I will add something to account for playback time that is in the past.

I played your files via problem2 and it matches what i see/hear in logic, so i'm not sure about your issue exactly. But perhaps i'm not totally understanding your meaning here.

Logic:

![image](https://user-images.githubusercontent.com/2917795/67725463-c0b95b00-f99f-11e9-9d15-12871b9f527a.png)

**Comment by ryanfrancesconi** [comment]
You can also pass nil for the player1.play(at: nil) -- effectively the same as saying when: 0

Both mean "now". For sync purposes it's better to put them a bit in the future though.

**Comment by ryanfrancesconi** [comment]
This would demonstrate the fix:

```
    /// Play file using previously set startTime and endTime at some point in the future.
    /// This will not work in the audioTime is in the past
    @objc public func play(at audioTime: AVAudioTime?) {
        var audioTime = audioTime

        if let requestedTime = audioTime {
            if requestedTime.isHostTimeValid, requestedTime.hostTime < mach_absolute_time() {
                AKLog("AudioTime is in the past, playing immediately.")
                audioTime = nil
            }
        }

        play(at: audioTime, hostTime: nil)
    }
```

**Comment by temkich** [comment]
Thanks for the quick response.
1 question: now everything is fine.
2 question: It looks like mp3 conversion adds garbage to the beginning and end of the file, which spoils the synchronization. I updated the repository and added an example of playing wav files and mp3s for the test. And now if you play two wav files, then the sound is synchronized, and if you play mp3 files it will be out of sync. Screenshot attached;

![](https://github.com/temkich/AudioKit-AKPlayer-problems/blob/master/AKPlayerProblems/AKPlayerProblems/wavvsmp3.png?raw=true)
I’m thinking what to do with mp3, do you know anything about this?

**Comment by ryanfrancesconi** [comment]
there shouldn't be any issues with mp3s themselves, i use them all the time. that said, there may be something with the software you're using to create them?

**Comment by ryanfrancesconi** [comment]
that's out of the realm of our discussion here, but try using itunes, lame, or something like that.

**Comment by temkich** [comment]
I tried Audacity, it contains the latest version mp3 lame, but there is the same thing. So far, the only thing I have found is to switch to a different format: m4a.
