### ISSUE TITLE
AKClipPlayer crashes if start position slightly before end of clip

### ISSUE THREAD

**Issue by dmann200** [AudioKit/AudioKit#1907]
I've bee chasing a very hard bug which causes AudioKit to crash. It appears that when playing back one or more clips with AKClipPlayer, if playback position matches the end of a clip MINUS A TINY FRACTION OF A SECOND, then the app will crash with the following error message:

failed: caught "com.apple.coreaudio.avfaudio", "required condition is false: numberFrames > 0"

The interesting thing is, it is not just any start time that causes the crash. It must 0.00001134 seconds or less before the end of the clip. Why such a strange number? Because at 44100hz, one sample = 0.00002268. One half of one sample = 0.00001134. I speculate that the cause is this: if it is less than a half a sample before the end, it is technically not at then end of the file yet. However, it is past the cutoff point at which it could grab the last sample. So when it tries to play, the number of samples is zero.

There is no question this is a bug, but I am not sure of a) What the solution is, short of a hack in which I shift my playback times so they never coincide with 0.00001134 seconds less than the clip end b) Is it an AudioKit bug? c) Is the bug in the Apple API? d) Is the bug with the CAF file format?

Also of interest I was using a .caf file which may or may not contribute to the problem.

I tried with single clips, multiple clips, and multiple start times. If the difference between clipEnd and player position is SLIGHTLY higher, there is no crash. 

Here is a code sample that will run in XCTest:

import XCTest
import AudioKit

 func testClipEndCrash(){
    let bundle = Bundle(for: type(of: self))
    do {
        let url = bundle.url(forResource: "psid-1_line-8", withExtension: "caf")!
        let clip = AKFileClip(url: url)!
        let clipStart = 0.0
        clip.time = clipStart
        let player = AKClipPlayer(clips: [clip])!
        let dur = clip.duration
        let end1 = clipStart + dur //ok
        let end2 = end1 - 0.001 //ok
        let end3 = end1 - 0.0001 //ok
        let end4 = end1 - 0.00001 //fail <---------------------------
        let end5 = end1 - 0.000001 //fail <----------------------------
        let end6 = end1 - 0.0000001 //fail <----------------------------
        let end7 = end1 + 0.001 //ok
        let end8 = end1 + 0.0001 //ok
        let end9 = end1 + 0.00001 //ok
        let end10 = end1 - 0.00005 //ok
        let end11 = end1 - 0.00003 //ok
        let end12 = end1 - 0.00002 //ok
        let end13 = end1 - 0.000015 // ok
        let end14 = end1 - 0.000013
        let end15 = end1 - 0.00001133 // crash
        let end16 = end1 - 0.00001134 //ok

        player.setPosition(end14)
        let expectation = self.expectation(description: "overlapping files")
        try AudioKit.stop()
        AudioKit.output = player
        try AudioKit.start()
        player.play()
        let timer = Timer.scheduledTimer(withTimeInterval: 7.0, repeats: false) { (timer) in
            expectation.fulfill()
        }
        timer.fire()
        self.waitForExpectations(timeout: 8.0, handler: nil)
    } catch {
        XCTAssert(false)
    }
    XCTAssert(true)
}

**Comment by aure** [comment]
I'm not sure if @dave234 will have a chance to have a look at this.  He's the original author of ClipPlayer though.

**Comment by aure** [comment]
Well not really sure what to do about this.

**Comment by dmann200** [comment]
Why is this marked closed?

**Comment by aure** [comment]
The author of clip player removed himself and I have no idea where to start.  Can you provide a sample project that exhibits this behavior? Also, if this is for a company or paid app, please consider sponsorship http://github.com/sponsors/aure

**Comment by dmann200** [comment]
Hi Aurelius,

I already have the fix for the bug. I will push it up when I have time. If you run a unit test using the code I provided in the post it will crash accordingly.

-David Mann

**Comment by aure** [comment]
Wow, that is awesome! Thanks in advance for the pull request.
