### ISSUE TITLE
[iOS13Crash] When I try to create a slow down audio file. 

### ISSUE THREAD

**Issue by xieliweiparkman** [AudioKit/AudioKit#1908]
One of my function is creating slow down audios, I am doing this way
```       
let fileName = dict.originalAssetURL
let url = URL(fileURLWithPath: fileName!.relativePath)
let aFile = try AKAudioFile(forReading: urli)
let player = AKPlayer(audioFile: aFile)
let dur = aFile.duration
let timePitch = AKTimePitch(player)
timePitch.overlap = 8.0
timePitch.rate = ps
            
AudioKit.output = timePitch
guard let lesson = lesson else { return }
let songName = lesson.title
let slowAudioFileName = ps.isEqual(to: 0.5) ? "\(songName)Fifty" : "\(songName)SeventyFive"

let url = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.appendingPathComponent("\(slowAudioFileName).wav")
                       
let format = AVAudioFormat(commonFormat: .pcmFormatInt16, sampleRate: aFile.sampleRate, channels: 2, interleaved: false)

let tape = try! AKAudioFile(forWriting: url, settings: format!.settings)

try AudioKit.renderToFile(tape, duration: player.duration/ps) { _ in
      UserDefaults.standard.set(tape.duration, forKey: "CurrentDuration")
                player.play()
}
```

This was working fine before until iOS13. Now when I run it, it shows
`AUBuffer.h:61:GetBufferList: EXCEPTION (-1) [mPtrState == kPtrsInvalid is false]: ""` like thousand times then crash.
The sample rate of my original audio file is 44100, I guess the sample rate of my device is 48000, but no matter how I set the sample rate, it just wont work anymore.

**Comment by aure** [comment]
So, AKTimePitch is just a thin wrapper for AVAudioTimePitch so I assume Apple must be the culprit here, not AudioKit.

**Comment by aure** [comment]
Since nothing in the error connotes AudioKit "AUBuffer.h:61:GetBufferList: EXCEPTION (-1) [mPtrState == kPtrsInvalid is false]: " Please file a radar with Apple.
