### ISSUE TITLE
When will the latest Swift 5.1.2 module be available?

### ISSUE THREAD

**Issue by MegaMaziar** [AudioKit/AudioKit#1909]
Need Latest Swift 5.1.2 module

Build error: 
"Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler"

I'd appreciate if a timeline of resolution can be provided.

**Comment by megastep** [comment]
I see that Xcode 11.2 just came out, so I'm assuming we'll put out a new version with a pod built with the current version soon enough. In the meantime, you could build your own from source...

**Comment by MegaMaziar** [comment]
thank you. I will keep busy in the meantime while waiting for your updated pod.
