### ISSUE TITLE
Swift 5.1.2 error

### ISSUE THREAD

**Issue by grinmax** [AudioKit/AudioKit#1911]
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler
Help, please.

AudioKit 4.9.1

**Comment by thomassnielsen** [comment]
We'll need to wait for a new release which is compiled with the new compiler. Now that Xcode 11.2 is out I'm sure it'll be here soon.

**Comment by MegaMaziar** [comment]
Any idea of how long this does typically take? (e.g. 1 day, 1 week, etc?)

**Comment by aure** [comment]
a day

**Comment by MegaMaziar** [comment]
thank you!

**Comment by megastep** [comment]
We just released v4.9.2 with pod binaries built with Xcode 11.2.

**Comment by colinhumber** [comment]
@megastep Correct me if I'm wrong, but as of Swift 5.1 the framework should be able to be imported with newer Swift compilers, yeah? I was just on this forum post here (https://forums.swift.org/t/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler/30431) and they mentioned a particular flag that has to be enabled to generate a stable interface.

**Comment by megastep** [comment]
I was under the impression we were sold a false bill of goods with these claims of supposed Swift ABI compatibility. That said, I was not afraid of that flag, and I would love it if it actually enables this. I'll turn it on and see if it helps.

**Comment by megastep** [comment]
Well... in short turning on this flag in the AudioKit library basically crashes the LLVM Swift compiler with AudioKit. I'm going to say that this feature is not quite stable enough for us to use for now, at least in Xcode 11.2....

It's weird that it behaves differently in Travis (in macOS 10.14, where it crashes almost immediately), in Xcode itself (where it actually manages to compile), and via xcodebuild on Catalina (where LLVM crashes randomly)... But it just doesn't seem to work properly.

**Comment by colinhumber** [comment]
Ugh, that's frustrating. It wouldn't surprise me if it was some compiler issue. Xcode 11 hasn't been the most stable lately...

**Comment by megastep** [comment]
I posted about it on the Swift forums, so we'll see if they have any feedback. Compilers are not supposed to ever crash this way, so definitely a bug in the compiler.

**Comment by eNorthug** [comment]
I have downloaded the latest AK 4.9 but still get this error. Running the very newest Catalina Beta and XCode. Any tips, or am I lost?

**Comment by aure** [comment]
Make sure to clean out your build folder. If Xcode can find an old version, it will.

**Comment by ElenaVielva** [comment]
With AudioKit/Core I am still facing this issue:

Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

pod 'AudioKit/Core', '=4.8.1.b1'

**Comment by colinhumber** [comment]
If you update your pod version to 4.9 you should be good.

**Comment by ElenaVielva** [comment]
Do you mean just changing the pod version in the podfile? I am getting this error:

Attempt 1:
```
$ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "AudioKit/Core":
  In Podfile:
    AudioKit/Core (~> 4.9)

None of your spec sources contain a spec satisfying the dependency: `AudioKit/Core (~> 4.9)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Attempt 2:
```
$ pod repo update
Updating spec repo `audiokit`
Updating spec repo `trunk`
$ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "AudioKit/Core":
  In Podfile:
    AudioKit/Core (~> 4.9)

None of your spec sources contain a spec satisfying the dependency: `AudioKit/Core (~> 4.9)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Attempt 3:
```
$ pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "AudioKit/Core":
  In Podfile:
    AudioKit/Core (~> 4.9)

None of your spec sources contain a spec satisfying the dependency: `AudioKit/Core (~> 4.9)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by colinhumber** [comment]
I misspoke. As mentioned [here](https://github.com/AudioKit/AudioKit/issues/1911#issuecomment-549005210), the correct AudioKit version for Xcode 11.2 (Swift 5.1.2 compiler) is 4.9.2.

Updating the version in your `Podfile` then running `pod update AudioKit` should update to the correct version in your workspace and update the version listed in the `Podfile.lock`.

**Comment by ElenaVielva** [comment]
`pod 'AudioKit/Core', '= 4.9.2'`
Still getting the same error on `pod update AudioKit`
