### ISSUE TITLE
Audiokit crash when running “AudioKit.output = oscillator”

### ISSUE THREAD

**Issue by MyDaRen** [AudioKit/AudioKit#1919]
I am writing an ios app with swift5(swiftui), and I just test if Audiokit can work so I copy some code from tutorial like this:

        let oscillator = AKOscillator()
        AudioKit.output = oscillator //<-crash here
        do{
            try AudioKit.start()
        }catch{
            print("AK start error")
        }
        oscillator.start()   
        sleep(2)

Crash mesg is AVAEInternal.h:76 required condition is false: [AVAudioEngineGraph.mm:2219:_Connect: (!destNodeMixerConns.empty() && !isDestNodeConnectedToIONode)] 
And "Thread 1: signal SIGABRT" in AppDelegate. I don't know why, thanks!

**Comment by aure** [comment]
I don't think this should be happening, but if you want to post the link to the GitHub project with this error I can take a look. This kind of thing is done all the time, so I don't why its not working for you. Is it only when SwiftUI is involved?

**Comment by MyDaRen** [comment]
Here is the link: https://github.com/Doubiiu/Project_swiftui_AudioKit.git
I start this project directly from AudioKit/Examples/DrumsSwiftUI, the code mentioned above is in ContentView.swift, triggered by 'play' button. Thanks a lot!

**Comment by aure** [comment]
Don't change AudioKit.output like that. Mix the signals with an AKMixer and start and stop them independently not all of AudioKit.
