### ISSUE TITLE
AKMidi crash on initialization

### ISSUE THREAD

**Issue by romancfischer** [AudioKit/AudioKit#1921]
Since I updated MacOS to Catalina, Xcode to Version 11 and AudioKit to 4.9.1 my app is crashing while trying to initialize AKMIDI with the following error message:

let midi = AKMIDI()

Error message:
**Couldn't find MIDI network driver**

Even if no specific midi setup is set up by my OS it shouldn't crash, right? Any workaround for this?

**Comment by markjeschke** [comment]
@romancfischer, 

Does this crash happen while the app is running on a physical device, or only in the simulator? Please be sure to update to Xcode 11.2.1 and install AudioKit version 4.9.2. If you’re using Cocoapods, run: 

`pod update`

There was a bug in earlier versions of Xcode 11, where the MIDI drivers weren’t included in the iOS simulators. Here’s a workaround solution where you need to manually install the missing drivers:

https://stackoverflow.com/questions/57587784/couldnt-find-midi-network-driver-crash-in-ios-13-simulators

But, the easiest solution would be to update Xcode and AudioKit to the latest versions. I hope this helps!

**Comment by romancfischer** [comment]
@markjeschke thank you very much for your quick reply. I followed your advice and it works now.
I want to notice though, that in order to be able to install Xcode 11.2.1 one needs to update MacOS to Catalina 10.15.1, otherwise the update will fail.
