### ISSUE TITLE
(feature request) way to specify a frequency for AKMandolin?

### ISSUE THREAD

**Issue by ghubaddole** [AudioKit/AudioKit#1926]
is there a way to specify a frequency (like oscillator) for mandolin to play? currently it seems to be using midi note to frequency.

**Comment by aure** [comment]
if you play one string you can bend the note to the right frequency. There is only the polyphonic version of mandolin in AudioKit, but you could probably look at the source to make a mono version of one that takes frequency. Or hire one of us to do it for you.
