### ISSUE TITLE
Crash: If you launch  AudioKit/Examples/iOS/MicrophoneAnalysis, while you are on a phone call it will crash at mic = AKMicrophone() in viewDidLoad()

### ISSUE THREAD

**Issue by MegaMaziar** [AudioKit/AudioKit#1927]
AudioKit/Examples/iOS/MicrophoneAnalysis/

It crashes in viewDidLoad() at the "mic = AKMicrophone()" command.
How would you suggest this could be prevented?

**Comment by aure** [comment]
The phone call is preventing the microphone to be accessed. In general the difference between the examples and an App Store ready project are the details like handling audio route changes, stopping and starting the engine appropriately.  Anyway, this is not an issue per se, so if you want more help with audio route change handling, ask questions on StackOverflow.
