### ISSUE TITLE
iOS 10 errors for trying to start engine while siri is recording 

### ISSUE THREAD

**Issue by frankiesimon** [AudioKit/AudioKit#1928]
This is a bit close to the issue https://github.com/AudioKit/AudioKit/issues/1629 that was closed for not enough details.

I am with AudioKit 4.9.2, running on an iOS 10.3.3 iPad. *HEADPHONES are plugged in*.

In my scenario I respond to route change notifications to reload a sampler and restart the engine (as suggested in https://github.com/AudioKit/AudioKit/issues/1629).

I get a route change notification when I activate Siri - during this one calling AudioKit.start() fails with the errors:
```
2019-12-02 20:02:43.329496+0200 myapp[7238:697861] [aurioc] 892: failed: 'siri' (enable 2, outf< 2 ch,  44100 Hz, Float32, non-inter> inf< 2 ch,      0 Hz, Float32, non-inter>)
2019-12-02 20:02:43.330726+0200 myapp[7238:697861] [central] 54:   ERROR:    [AVAudioSession Notify Thread] >avae> AVAudioEngineGraph.mm:2515: PerformCommand: error 1936290409
```

When I deactivate Siri the signal rebuild works as planned, probably because Siri is no longer recording.

**Comment by frankiesimon** [comment]
Update - when I don't have headphones plugged in I see no error but my audio isn't playing anymore. I suppose I need to also rebuild the chain and restart engine for interruptions?

**Comment by aure** [comment]
Yeah, that's exactly right. Something along these lines:

    @objc func restartEngineAfterRouteChange() {
        print("restartEngineAfterRouteChange")
        let attemptRestart = {

            // Come back up with UI in not playing state

            if !AudioKit.engine.isRunning && UIApplication.shared.applicationState == .active {
                AudioKit.engine.prepare()
                do {
                    try AudioKit.engine.start()
                } catch {
                    AKLog("error restarting AK engine")
                }
            }
        }
        if Thread.isMainThread {
            attemptRestart()
        } else {
            DispatchQueue.main.async(execute: attemptRestart)
        }
    }
