### ISSUE TITLE
Incorrect buffer length when using bluetooth headphones.

### ISSUE THREAD

**Issue by Artaches** [AudioKit/AudioKit#1931]
To replicate the issue modify the "MicrophoneAnalysis" like so:

```
override func viewDidLoad() {
        super.viewDidLoad()

        AKSettings.useBluetooth = true
        AKSettings.bluetoothOptions = [.allowBluetoothA2DP, .allowAirPlay]
        AKSettings.bufferLength = .medium   // 16ms @ 16kHz
        AKSettings.sampleRate = 16000

        AKSettings.audioInputEnabled = true
        mic = AKMicrophone()
        tracker = AKFrequencyTracker(mic)
        silence = AKBooster(tracker, gain: 0)
    }
```

In "updateUI()", add line:
`print ("Buffer length: \(AVAudioSession.sharedInstance().ioBufferDuration)")`

So I'm expecting 16ms buffers @ 16kHz.
On iPhone 6+ (iOS 12.4.3) when using wired headphones I get:
_Buffer length: 0.01600000075995922_ (correct buffer length)

But when using any bluetooth headphones, I get:
_Buffer length: 0.00580498855561018_

Changing `AKSettings.sampleRate = 8000` creates an audible difference of worse quality (for both wired and wireless headphones), however the buffer stays the same for wireless ONLY. So it seems that changing the sampling rate doesn't affect the buffer length for bluetooth headphones :/

Any help is greatly appreciated, thanks!

**Comment by aure** [comment]
Can you try this with the latest develop branch of AudioKit? Microphone changes came in today.

**Comment by Artaches** [comment]
I tried the latest version in develop by importing AudioKit from source as described here: https://github.com/AudioKit/AudioKit/blob/master/Frameworks/README.md
I still get the same behaviour as before for the MicrophoneAnalysis sample app:
_Buffer length: 0.00580498855561018_
when using BlueTooth headphones.

**Comment by aure** [comment]
Unfortunately I have no idea where to look to fix this, perhaps you can ask it on StackOverflow in a general way so that people who aren't familiar with AudioKit may also try to answer.
