### ISSUE TITLE
AKFrequencyTracker problem

### ISSUE THREAD

**Issue by frbl1700** [AudioKit/AudioKit#1932]
Sorry to be asking this here, i have tried Stackoverflow with no luck so far.

I just can't get AKFrequencyTracker to work correctly with AKMicrophone on macOS. No problem on iOS.

The problem is that i just get frequencies in the 40 000+Hz range when playing/singing in the microphone. Tried putting a low-pass filter in between but that does not seem to do anything.
Attaching image when testing the official MicrophoneAnalysis example.

Any guidance would be very appreciated!

```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        mic = AKMicrophone()
        filter = AKLowPassFilter(mic)
        filter.cutoffFrequency = 6900
        filter.resonance = 0
        
        tracker = AKFrequencyTracker(filter)
        silence = AKBooster(tracker, gain: 0)
        
        AudioKit.output = silence
        
        do {
            try AudioKit.start()
        } catch {
            AKLog("AudioKit did not start!")
        }
    }
```

<img width="485" alt="Screen Shot 2019-12-02 at 01 28 48" src="https://user-images.githubusercontent.com/42981710/69985873-641c0380-153c-11ea-8f1e-66966489593f.png">

**Comment by aure** [comment]
This looks like a bug, so it actually makes sense to post here, thank you.

**Comment by aure** [comment]
While it works in iOS it doesn't actually work on the iOS simulator. In the simulator, its actually behaving exactly like it does on macOS. If the hardware of the Mac microphone is just different then you'd think your idea of putting a low pass filter on it would work. Very interesting.

**Comment by frbl1700** [comment]
Interesting. I just tested on my old MacBook Pro (2015) and it works. Both the macOS example and in the iOS simulator. Clean signal and correct frequencies both with and without lowpass filter.

Does not work on either my MacBook Air (2019) or my MacBook Pro (2019).
Maybe a 2016+ generation issue.

**Comment by aure** [comment]
I pushed a digital lowpass filter of sorts that at least mitigates this issue since I don't know what else to do.
