### ISSUE TITLE
AKAppleSampler no response for certain sound font

### ISSUE THREAD

**Issue by zhouhao27** [AudioKit/AudioKit#1933]
We're using the AudioKit SDK to build a music application. There is no sound produced or some weird noise generated for certain keys with certain soundfont, for example, GeneralUser_GS_1.44-SoftSynth. I tried Joomkoo, it also has the same problem so I think this is a bug of AudioKit. Any idea? Thanks.

By the way, my testing code is:

sampler = AKAppleSampler()

```
do {
  try sampler.loadSoundFont("GeneralUser_GS_1.44-SoftSynth", preset: 0 , bank: 0)
  sampler.amplitude = 20

  AudioKit.output = sampler
  try AudioKit.start()

} catch {

}
```

**Comment by aure** [comment]
Maybe post this to StackOverflow until you can nail down to an actionable issue.
