### ISSUE TITLE
offlineRender.renderToURL error

### ISSUE THREAD

**Issue by extnous** [AudioKit/AudioKit#1934]
I am with AudioKit 4.9.2 and 4.9.3, running on an iPhone se and 8. 
I'm getting a crash while running the offlineRender.renderToURL.

```
try? AudioKit.stop()
AudioKit.output = offlineRender
try? AudioKit.start()

offlineRender.internalRenderEnabled = false
player.schedule(from: 0, to: player.duration, avTime: nil)
let sampleTimeZero = AVAudioTime(sampleTime: 0, atRate: AudioKit.format.sampleRate)
player.play(at: sampleTimeZero)
        
do {
      try offlineRender.renderToURL(targetUrl, duration: player.duration)
      player.stop()
} catch {
      print(error)
      self.getCompletion()?(Error.effectRenderingError(error as NSError))
      return
}

offlineRender.internalRenderEnabled = true
```

"Error Domain=AKOfflineRenderAudioUnit Code=1 "Node needs to be connected and engine needs to be running""

The error appeared recently. There are no errors when saving to iphone X. Any ideas what could be the problem?

**Comment by aure** [comment]
Are they all running the same iOS version? What is offlineRender object? Hard to tell from this little code. Probably should post a project and ask the question on StackOverflow. Closing on here until we can pinpoint a particular issue.

**Comment by extnous** [comment]
They are all running the same iOS 13.2.3

**Comment by aure** [comment]
Must be a sample rate mismatch issue, though the error doesn't seem to imply that. That's the only thing that is likely to be different on the devices. Are you utilizing the microphone?

**Comment by extnous** [comment]
If I use headphones with a microphone on the phone X, the same error occurs. On other devices, the error is without a microphone.

**Comment by extnous** [comment]
Checked on other devices. The code runs without errors on iOS 13.2.1 and 13.2.2, an error only on iOS 13.2.3.
