### ISSUE TITLE
change system volume while start play

### ISSUE THREAD

**Issue by Girlsmile** [AudioKit/AudioKit#1937]
hello, i am writing a voice reverse app and change the speed at the same time,  every time i try to play a file, it change my system volume during playback, after playing, the system volume will be reset,  i try tag 4.8.0 and 4.9.3, and it occur in the ios11 and ios13 but work well in the simulator

here is my code:

let playQueue = DispatchQueue.init(label: "player.playQueue")

class RecordPlayer: NSObject {
    
    static var shared = RecordPlayer()
    
    open var player: AKAudioPlayer?
    
    private var timer: SwiftCountDownTimer?
    
    open var progress: Double = 0
    
    open var playTime: Double = 0
    
    private var reverse: Bool = false
    
    private var speed: Double = 1.0

    
    func play(url: URL, reverse: Bool = shared.reverse, speed: Double = shared.speed, from time: Double = 0, needPostNotifiaction: Bool = true) {
        
        if self.player != nil {
            stop()
        }
        
        RecordPlayer.shared.reverse = reverse
        RecordPlayer.shared.speed = speed
        if let file = try? AKAudioFile.init(forReading: url), let player = try? AKAudioPlayer.init(file: file) {
            
            playQueue.async {
                self.player = player
                player.reversed = reverse
                var lastNode: AKNode = player
                
                let pitchNode = AKTimePitch(lastNode)
                lastNode = pitchNode
                pitchNode.rate = speed
                AudioKit.output = lastNode
                
                try? AudioKit.start()
                try? AVAudioSession.sharedInstance().setCategory(.multiRoute, mode: .default, options: [])
             
                player.play(from: time)
    
            }
        }
        
    }
    
    func stop() {
        playQueue.async {
            self.player?.stop()
            try? AudioKit.stop()
            AudioKit.disconnectAllInputs()
            self.timer?.suspend()
            self.timer = nil
            self.progress = 0
            self.playTime = 0
        }
        
    }
 
}

**Comment by aure** [comment]
Hi, until you can pin this down to an identifiable problem with AudioKit and not an implementation concern, this should probably be posted too StackOverflow. Also, even though you've provided code, its not complete and not easily run to test. A working project on Github demonstrating the problem is the best way to encourage others to help.
