### ISSUE TITLE
AudioKit and WatchOS

### ISSUE THREAD

**Issue by aronnelson** [AudioKit/AudioKit#1938]
Has anything changed with respect to using AudioKit with WatchOS?
I saw a post about watchKit hackathon mentioning AudioKit.
Is it possible to use AudioKit with WatchOS?
If so, how?

Thanks

**Comment by aure** [comment]
A couple of hackathons were won pairing AudioKit on the phone with watch controls and sensors, but as far as AudioKit actually running on the watch standalone, we don't have any architecture in place for that.

**Comment by megastep** [comment]
Yeah, last I checked the most crucial APIs of AVFoundation were still missing on watchOS (i.e. the nodes) so it wasn't feasible still.

**Comment by ozgurshn** [comment]
I tried to run basic oscillator with AVAudioEngine on Series 2 watch but it sounds scrannel but when I tried on simulator in sounds good. What could be the reason? I'm running oscillator within the range of 100-900 frequency and 0-1 amplitude.

**Comment by ozgurshn** [comment]
I didn't use AudioKit @aronnelson, I just used AVFoundation and AvAudioEngine.

**Comment by aronnelson** [comment]
Oh, this is the AudioKit Github. What code are you running?

**Comment by ozgurshn** [comment]
I'm running the oscillator from this repo (https://github.com/GrantJEmerson/SwiftSynth) but just want to note it here if someone has an idea.
