### ISSUE TITLE
Audio Player playground errors with expression failed to parse, unknown error

### ISSUE THREAD

**Issue by hipwelljo** [AudioKit/AudioKit#1941]
To replicate:

1. Download the playgrounds zip from Releases
2. Open the Xcode project (in 11.3 (11C29))
3. Select Basics > Introduction and Hello World
4. Build the project
5. Hit play and verify it works
6. Select Playback > Audio Player
7. Build the project just in case
8. Hit play

Result: This is logged: expression failed to parse, unknown error
Expected: No error

If you replace the code with the first block of code from [https://audiokit.io/playgrounds/Playback/Audio%20Player/](https://audiokit.io/playgrounds/Playback/Audio%20Player/ ) then it works. Pasting in the LiveView and running doesn't work again but it gives a useful error:

> error: Audio Player.xcplaygroundpage:35:21: error: cannot convert value of type 'AKPlayer?' to expected argument type 'AKAudioPlayer'
>             player: player,
>                     ^~~~~~

Is it supposed to be AKResourceAudioFileLoaderView (not Resources)? Looking at the source that's what I see, but it doesn't compile it can't find AKResourceAudioFileLoaderView.

If you comment the add views out and uncomment the Disable Looping and Normal buttons it works, but if you uncomment the Fade In slider you get expression failed to parse, unknown error again.

**Comment by aure** [comment]
I'll look into this.

**Comment by aure** [comment]
This is odd, the playground shows that error whenever one of the closures include player.fade or player.loop.  If I comment those lines the playground runs, and plays, but the sliders don't work as they used to.

**Comment by aure** [comment]
Fade and Loop are both properties of AKAbstractPlayer which AKPlayer inherits from. I'm not sure if their inaccessibility is just within playgrounds or if something has changed with AKPlayer. @ryanfrancesconi can you shed any light on this?

**Comment by ryanfrancesconi** [comment]
The error says AKAudioPlayer - which isn't AKPlayer. I haven't had a chance to look at the playgrounds, but perhaps there is a cast to AKAudioPlayer in there?

**Comment by aure** [comment]
@ryanfrancesconi Actually I am not sure what code the poster put in to make the AKAudioPlayer error appear. The playground on https://audiokit.io/playgrounds/Playback/Audio%20Player/ does not involve the older player and errors whenever .loop or .fade are accessed, which is only in AKPlayer.

**Comment by hipwelljo** [comment]
Hey guys, I'm able to see the AKAudioPlayer error by pasting the code from the above link as-is.

<img width="1011" alt="Screen Shot 2020-01-06 at 3 03 16 PM" src="https://user-images.githubusercontent.com/6282848/71852329-ae415900-3095-11ea-969f-8f7a84850479.png">

**Comment by aure** [comment]
This looks like its still seeing an old version of AudioKit. This is not the error I am getting and the AKResourceAudioFileLoaderView clearly uses AKPlayer:

https://github.com/AudioKit/AudioKit/blob/796c974e5f6ea00fdacca062f20f01bfb4689de8/AudioKit/iOS/AudioKit/User%20Interface/AKResourceAudioFileLoaderView.swift#L87

**Comment by aure** [comment]
My error, involving fade and loop, are different, so I will close this issue.
