### ISSUE TITLE
With macOS 10.14+ it would be helpful if AudioKit can throw a mic access exception

### ISSUE THREAD

**Issue by reflectivist** [AudioKit/AudioKit#1944]
I had a problem that was difficult to diagnose with Microphone tracking, which I resolved with Aurelius' help for [this StackOverflow question](https://stackoverflow.com/questions/59551361/on-macos-catalina-why-do-akfrequencytracker-akmicrophonetracker-give-bogus)  

As of Catalina 10.14, the OS requires user permission to access the microphone, and that requires a specific key in the info.plist file. If the key isn't present the user is not prompted to allow access to the mic, but it is problem (I believe) that AudioKit doesn't throw an exception when the mic can't be accessed, particularly if it is a security issue. By throwing an exception, developers would be clued in immediately to what is going wrong. Otherwise it can be extremely elusive.

In my case, I was aware of security/permission issues with iOS, but since it had been awhile since I'd done app development on macOS, I wasn't aware of the new restriction/requirements.

**Comment by aure** [comment]
Its a good idea, do you want to make a pull request with the suggested exception?

**Comment by aure** [comment]
This has been added in development.

**Comment by aure** [comment]
Thanks!
