### ISSUE TITLE
Setting startTime and calling play() starts earlier than specified startTime

### ISSUE THREAD

**Issue by hipwelljo** [AudioKit/AudioKit#1945]
We've noticed in our app when we move the playhead position it's starting earlier than the specified time. We do this via:

    player?.stop()
    player?.startTime = position
    player?.play()

I've created a sample project to demonstrate this behavior. [SamplePlayer.zip](https://github.com/AudioKit/AudioKit/files/4017829/SamplePlayer.zip)
To replicate:
1. Run pod install
2. Open the workspace
3. Run the app
Notice a player is started and its currentTime is logged every millisecond
4. Tap "Go Back"
5. Stop the app
6. Search the console for "moving"
Notice the logs show MOVING PLAYHEAD TO 1.2345 and then the player's currentTime logged after that point are before the specified startTime such as
```
13.973310657596372

MOVING PLAYHEAD TO 1.2345

1.2131848072562357
1.2131848072562357
1.2131848072562357
1.2131848072562357
1.2131848072562357
1.2131848072562357
1.2131848072562357
1.2131848072562357
1.2131848072562357
1.2131848072562357
1.2131848072562357
1.223842403628118
1.223842403628118
1.223842403628118
1.223842403628118
1.223842403628118
1.223842403628118
1.223842403628118
1.223842403628118
1.223842403628118
1.223842403628118
1.223842403628118
1.2345226757369614
1.2345226757369614
1.2345226757369614
1.2345226757369614
1.2345226757369614
1.2345226757369614
1.2345226757369614
1.2345226757369614
1.2345226757369614
1.2345226757369614
```

This is problematic in our app because we run some logic based on the player's currentTime. To support looping sections of a song in real-time, we detect when the player's position has reached the end of a loop and move it back to the start time. This is breaking our logic because it starts earlier than the loop's start time, causing us to lose track of the current loop because we've exited the loop and we'll start a new loop a few milliseconds later.

**Comment by ryanfrancesconi** [comment]
Sorry, I didn't see this issue before. Guessing you have another solution by now.

try:
play(from: startTime).

Also, it may be that the currentTime property is the one that is wrong?

**Comment by aure** [comment]
Closing due to lack of response from the original poster after Ryan's reply.
