### ISSUE TITLE
Error Swift 5.1.3

### ISSUE THREAD

**Issue by jonahoopla** [AudioKit/AudioKit#1948]
Hi! Can you compile a new version? thanks!

This is the error:
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /AudioKit-macOS/AudioKit.framework/Modules/AudioKit.swiftmodule/x86_64.swiftmodule

**Comment by aure** [comment]
Check the old closed issues, this has been brought up before and has been taken care of - do you have the latest AK, did you clean your build environment etc.
