### ISSUE TITLE
AKReverb2 not available on macOS

### ISSUE THREAD

**Issue by btfranklin** [AudioKit/AudioKit#1950]
For some time, the source code for AudioKit has contained both AKReverb and AKReverb2 nodes. However, in AudioKit for macOS, AKReverb2 does not appear to be present, though all the other reverb nodes are. I have confirmed that it does not appear in the framework code as recently as 4.9.3.

I'm filing this because I suspect this is an oversight. I can't find any indication anywhere that this node should not be present, and in the source code, it does not have an "available" tag that would indicate it shouldn't be present.

**Comment by megastep** [comment]
You are correct, it appears it was simply not included in the macOS project somehow. I'm sure we'll correct this oversight shortly.

**Comment by aure** [comment]
Actually for a very long time Reverb2 (kAudioUnitSubType_Reverb2) was only available on iOS so we couldn't include it. This likely changed only in a recent version of macOS, certainly Catalina compiles it just fine.

**Comment by btfranklin** [comment]
Reverb2 appears to be missing in AudioKit 5. Perhaps the same oversight, or the fix didn't make it over to the v5 branch?

**Comment by btfranklin** [comment]
I sure hope you guys get notifications on closed issues...

**Comment by btfranklin** [comment]
Oops, I just noticed this in the Migration Guide:
AKReverb2     Errored in AudioKit 5 on  initialization. Could be resurrected by someone interested in doing so.   

I guess that explains it...
