### ISSUE TITLE
Objective-C Init Problems - HelloWorldObjectiveC Example

### ISSUE THREAD

**Issue by sethmills21** [AudioKit/AudioKit#1954]
Hi there, 

I'm still stuck in Objective-C world and having trouble initing a AKNodeRecorder on the HelloWorldObjectiveC example project. Am I missing something? I can init plenty of other classes. 

![image](https://user-images.githubusercontent.com/7932883/72618866-13087900-390a-11ea-88d8-66cdf0b92c4f.png)

```
- (id)initWithCoder:(NSCoder *)aDecoder {
    self = [super initWithCoder:aDecoder];

    oscillator1 = [[AKOscillator alloc] init];
    oscillator2 = [[AKOscillator alloc] init];
    mixer = [[AKMixer alloc] init: @[oscillator1, oscillator2]];
    mixer.volume = 0.5;

    AudioKit.output = mixer;
    [AudioKit startAndReturnError:nil];
	
	AKNodeRecorder *recorder = [[AKNodeRecorder alloc] ini]

    return self;
}
```

Any help would be greatly appreciated. Already triple checked relevant Xcode settings for the Swift compiler.

**Comment by aure** [comment]
This will be in the next version or if you can use the develop branch, you can have the fix now.

**Comment by sethmills21** [comment]
Thanks mate @aure  🙏
