### ISSUE TITLE
Code relate to AKSequencer not working anymore after update to 4.9.3

### ISSUE THREAD

**Issue by s951736** [AudioKit/AudioKit#1957]
I'm new to iOS dev and have a project using AudioKit.
Before, I have using AKSequencer in my code and it works, but today I update AK to 4.9.3 (so I can open project with xCode 11.2), after that, some code is not working anymore, here is those code:

```swift
let sequencer = AKSequencer()
sequencer.setTempo(Double(bpm))  //Value of type 'AKSequencer' has no member 'setTempo'
let trackA = sequencer.newTrack()  //Value of type 'AKSequencer' has no member 'newTrack'
sequencer.enableLooping(AKDuration(beats: Double(patternSeq.timeCoreData.timeSignature.upper)))
//Value of type 'AKSequencer' has no member 'enableLooping'
```
I guess those code been replaced by other commends in the update process, but I'm not really sure.
How can I know which code I should use to replace my code? 
Is there any official release detail mention those changes that I can read before I update AK?
Thanks.

**Comment by aure** [comment]
Change all your occurrences of AKSequencer to AKAppleSequencer.  AKSequencer is now or own open source sequencer and the one we used to use was renamed.
