### ISSUE TITLE
AudioKit crashing when receiving a phone call

### ISSUE THREAD

**Issue by geeksweep** [AudioKit/AudioKit#1959]
AudioKit 4.9.3
iOS 11+

So i don't know if this is a problem that can be fixed so I am stuck between StackOverflow and asking here at the same time what I can do in this specific case. I did post on SO but its such a special case, I am not sure I will get any bites on it. 

I posted my problem below. Basically I want to continue to record successfully even receiving a phone call.

https://stackoverflow.com/questions/59899759/ios-audiokit-crashes-when-receiving-a-phone-call

**Comment by aure** [comment]
I have read your StackOverflow post and I feel like we've had similar issues with the Hey Metronome app, basically we built our own call handling logic and told Audio to set enableRouteChangeHandling to false.
