### ISSUE TITLE
External mic input dual mono but should be stereo

### ISSUE THREAD

**Issue by nethY-wwmh** [AudioKit/AudioKit#1961]
We have been integrating AudioKit with our app and have been running into issues with our mic setup. The app currently receives input from an external mic (Shure MV88) that is able to record in stereo, and we feed that audio back through to the speakers. I have installed a tap for the input node to write to a file to confirm the audio file is dual mono and not stereo.

I have quickly tested using AVAudioEngine from AVFoundation instead of AudioKit with a similar setup and the input audio file is stereo when using the same external mic.

Is there a setting that needs to be toggled for the input to be stereo when using AudioKit libraries or is stereo microphone input not currently supported?

Here is our setup using AudioKit to record:
```
AKSettings.useBluetooth = true
AKSettings.bluetoothOptions = [.allowBluetoothA2DP, .allowAirPlay]

// Configure AudioKit for low latency
AKSettings.bufferLength = .medium           
AKSettings.sampleRate = 16000               

AKSettings.audioInputEnabled = true
AKSettings.channelCount = 2
AKSettings.defaultToSpeaker = false

mic = AKMicrophone()
AudioKit.output = mic

let format = [
     AVLinearPCMBitDepthKey: 32,
     AVLinearPCMIsBigEndianKey: 0,
     AVNumberOfChannelsKey: 2,
     AVFormatIDKey: 1819304813,
     AVSampleRateKey: 16000,
     AVLinearPCMIsNonInterleaved: 1,
     AVLinearPCMIsFloatKey: 1
     ]

// Install input tap
do {
     inputFile = try AVAudioFile(forWriting: inputPath, settings: format)
} catch {
     AKLog("Error with output file: \(error)")
}
mic.avAudioNode.installTap(onBus: 0,
     bufferSize: 4096,
     format: mic.avAudioNode.outputFormat(forBus: 0),
     block: { (buffer: AVAudioPCMBuffer!, _) -> Void in
          do {
               try self.inputFile.write(from: buffer)
          } catch {
               print(NSString(string: "Write failed: \(error)"))
          }
})

do {
     try AudioKit.start()
} catch {
     AKLog("AudioKit did not start")
}
```

**Comment by Artaches** [comment]
I can confirm the same behavior on the iPhone 6plus and iPhone 8 using the Zoom iQ7 external stereo microphone (https://www.zoom-na.com/products/handy-recorder/zoom-iq7-professional-stereo-microphone-ios). I'm not able to get a stereo signal no matter what settings I choose for AudioKit.

**Comment by akuz** [comment]
@nethY-wwmh - could you please provide a short AVAudioEngine example? The online docs are so bad... I would like to be able to choose a device from a list of available devices, and then read from it in real time. Thanks in advance!

**Comment by aure** [comment]
Pretty sure this is addressed in v5 of AudioKit.

**Comment by aure** [comment]
V5 I should say, is not ready for public consumption, but I'm closing the issue anyway. :)
