### ISSUE TITLE
Reduce noise while recording.

### ISSUE THREAD

**Issue by HassanElDesouky** [AudioKit/AudioKit#1966]
In the example project [Recorder](https://github.com/AudioKit/AudioKit/tree/master/Examples/iOS/Recorder) when I create a record and then play it back... the recorded audio has lots of background noise.

How can I solve that?

Thanks!

**Comment by aure** [comment]
Record in a quieter space? We use Github issues for identifiable problems with AudioKit, so unless you know for sure that we have a coding problem, the question may be better asked on StackOverflow.
