### ISSUE TITLE
Performance issue with AKPlayer nodes

### ISSUE THREAD

**Issue by corentingurtner** [AudioKit/AudioKit#1967]
AKPlayer nodes can take up to 80ms to instantiate, connect and play and take on the average 30ms.
This is great for playing a few samples, but quite slow for playing dozens of samples scheduled in an accurate way.
For instance, I'm trying to develop a sequencer which can play up to 50 sound samples at the same time but it's taking more than 1.5 seconds to prepare and play them all. 
Let's say I have repeated batches of 20 notes to play every 500 ms (it can happen a lot in orchestral music), the playback won't be able to keep up.

In comparison, the Web Audio API, usable within Safari, takes ~3ms to do the same job. 
I'm using the exact same scheduling method with the Web Audio API and have good results in terms of timing, but the Web Audio thread doesn't seem to have a high priority with Safari, so audio samples quickly becomes glitchy.

AKPlayer slowness seems to be caused by the inherent behavior of the AVAudioPlayerNode, and I think it would be better to use a low-level alternative for a broader usage.

**Comment by aure** [comment]
There are a few other players and samplers in AudioKit that may be better suited for your needs. Most of them are open source to the core, so you should be able to get down to the metal to optimize for your use case. I'm inclined to close this an issue unless we can pinpoint something to fix.

**Comment by aure** [comment]
Check out AKWaveTable for one.
