### ISSUE TITLE
Built-in Mic as Input and AirPods as Output

### ISSUE THREAD

**Issue by tallen11** [AudioKit/AudioKit#1970]
Hello,
I need to play mic input, out after applying some effects to it. The problem is that I need to be able to take mic input from the built-in iPhone mics while playing the output through AirPods or other bluetooth headphones. However when I try to set the input device to a built-in mic, the output device gets automatically changed to the phone's receiver/speakers. This works with wired headphones, but not bluetooth ones.

I've gotten my desired behavior using a custom AudioUnit, but I wanted to know if this is possible using stock AudioKit and I'm not sure how to interface my custom AudioUnit with AudioKit.

EDIT: This behavior is the same as what Apple's Live Listen thing does.

Thanks!

**Comment by aure** [comment]
Everything in AudioKit is a custom audio unit, so there are plenty of examples to look at. 

AudioKit's input and outputs are settable, check out the microphone analysis example project to see the extent of what we provide. If you want to beef that up, a pull request would be most welcome.
