### ISSUE TITLE
AKMetronome hides AKMIDISampler on beat 1 when connected through AKMixer

### ISSUE THREAD

**Issue by marcuskim1989** [AudioKit/AudioKit#1972]
I set up a mixer so I could output both a metronome and a drum sequencer at the same time. During the first loop, all the notes of the drum sequence play perfectly well, the metronome clicking in sync. Upon the second loop, at beat 1, the metronome seems to hide the drums sounds so that there is one-half beat of drums sounds missing. I almost certain that I've connected the nodes correctly, both the metronome and drum sounds are audible and continue to loop. However, the drums sounds are hidden at beat 1 out of 4/4 measure. Any help would be greatly appreciated

**Comment by aure** [comment]
AKMetronome is being removed from AudioKit on the next release and there will be a metronome tutorial, so I'd rather not worry about this deprecated part of AudioKit.
