### ISSUE TITLE
Use AudioKit with NSData instead URL

### ISSUE THREAD

**Issue by Cleversou1983** [AudioKit/AudioKit#1975]
I have a audio saved on a Realm Database as NSData. With AVAudioPlayer I can success load the data and play the audio. I'm willing to use AudioKit to display the sound waves, but I couldn't found a way to make it work with NSData instead URL...

Thanks!

**Comment by aure** [comment]
Either write the data to a local URL or extend AudioKit to use NSData. There's nothing built in that does it for you. If you want to build it into AudioKit, create a pull request with your solution and I'll happily accept the update.
