### ISSUE TITLE
.linear fade has stutter, .logarithmic works great

### ISSUE THREAD

**Issue by BrianBecker** [AudioKit/AudioKit#1983]
Using FadeOutAndStop, I had all kinds of gaps and stutters and bad fades when using a ramp of .linear...but on a whim I changed it to .logarithmic and it all cleared up. Whew!

**Comment by BrianBecker** [comment]
Spoke too soon. It fixed my issue on the simulator, but on the iPad mini 12.4.5 it still stutters after issuing the fadeOutAndStop() with time = 1.5.

**Comment by ryanfrancesconi** [comment]
could you put your whole AKPlayer setup here?

**Comment by aure** [comment]
Closing because Ryan's request was not replied to.
