### ISSUE TITLE
MIDI inputs not cleared

### ISSUE THREAD

**Issue by paulorrfilho** [AudioKit/AudioKit#1984]
The call AudioKit.midi.closeAllInputs() does not really close all inputs. MIDI notes received are duplicated when a new MIDI device is connected.

I have to manually close each inputs first then open them one by one like the below. I am fine with the approach, just wanted to raise the issue for future users.

            self.midi.inputUIDs.forEach { (uid) in
                self.midi.closeInput(uid: uid)
            }
            self.midi.inputUIDs.forEach { (uid) in
                self.midi.openInput(uid: uid)
            }

Or maybe I am using it the wrong way?

**Comment by aure** [comment]
Thanks for noticing this and thanks for the support. Anything else you need just holler!

**Comment by romancfischer** [comment]
I'm having the same problem. Using version 4.11.2.
Workaround by paulorrfilho not working. Anyone else?
