### ISSUE TITLE
Cannot build project with AudioKit 4.9.4 using Xcode 11.4 beta 3

### ISSUE THREAD

**Issue by Thomas-Vos** [AudioKit/AudioKit#1987]
Hi, I am having issues building my project with Xcode 11.4 beta 3.

There were no issues when using Xcode 11.3.1 with AudioKit 4.9.3. Then I updated AudioKit to version 4.9.4. Still no issues. Then I downloaded Xcode 11.4 beta 3. Now when building my project I get the following errors: 

![Screenshot 2020-03-16 at 14 59 38](https://user-images.githubusercontent.com/11077217/76765512-d08edb80-6796-11ea-984e-c4d992291d1f.png)
![Screenshot 2020-03-16 at 14 59 47](https://user-images.githubusercontent.com/11077217/76765520-d389cc00-6796-11ea-9fee-dae25111e313.png)

I am using AudioKit through CocoaPods. I also tried to [include the framework manually](https://github.com/audiokit/AudioKit/blob/master/Frameworks/README.md#using-the-compiled-frameworks-in-your-projects) but the same errors still appear. Is there anything I am doing wrong?

**Comment by megastep** [comment]
In 4.9.4 we enabled Library Evolution which allows the compiled framework to be used among different versions of Swift/Xcode. I believe this is related to this though I have not observed that behavior myself.

In the forthcoming v5 I have some cleanups of the swiftinterface files to avoid some similar issues (which involved basically renaming the AudioKit class) but I didn't see it happening it on 4.9. 

Do you want to maybe try our beta pod of v5? https://github.com/AudioKit/Specs

**Comment by Thomas-Vos** [comment]
Thanks @megastep for the explanation. I just tried the beta pod 5.0.b1 and the issue is fixed!

**Comment by yichengchen** [comment]
The Xcode 11.4 is released, When will this fix release?

**Comment by megastep** [comment]
Are you having trouble on Xcode 11.4?

**Comment by theolampert** [comment]
@megastep this should be reopened, I can verify the library doesn't work in 11.4

**Comment by amardeepranu** [comment]
v4.9.4 does not work on Xcode 11.4, I have over 1000 build errors - please re-open. This library breaks overnight without me knowing since Apple automatically updates Xcode.

**Comment by DanielSelig** [comment]
What is the Podfile wording?  My attempts won't find the pod.  My latest attempt is
pod 'AudioKit', '~> 5.0.b1'

The platform is 13.3

**Comment by megastep** [comment]
@DanielSelig that is correct however for this to work you need to make sure you also have the source spec:

`source 'https://github.com/AudioKit/Specs.git'`

**Comment by DanielSelig** [comment]
Thank you!

**Comment by Winton1992** [comment]
> In 4.9.4 we enabled Library Evolution which allows the compiled framework to be used among different versions of Swift/Xcode. I believe this is related to this though I have not observed that behavior myself.
> 
> In the forthcoming v5 I have some cleanups of the swiftinterface files to avoid some similar issues (which involved basically renaming the AudioKit class) but I didn't see it happening it on 4.9.
> 
> Do you want to maybe try our beta pod of v5? https://github.com/AudioKit/Specs

![image](https://user-images.githubusercontent.com/9639404/81515341-e70c7a00-9376-11ea-8a07-268da4878acb.png)
Hi, I am encountering new issues after using pod 'AudioKit', '~> 5.0.b1', do you know how to get rid of it? thanks

**Comment by aure** [comment]
@Winton1992 Change "AudioKit" to "AKManager"

**Comment by Winton1992** [comment]
> @Winton1992 Change "AudioKit" to "AKManager"

Thanks, bro. Have a good day~~~
