### ISSUE TITLE
stray print in AKCoreSampler.cpp: 560

### ISSUE THREAD

**Issue by ghubaddole** [AudioKit/AudioKit#1988]
Seeing lots of these in my log: (AudiokIt 4.9.4)
setting pitch sustain level to xxx

void  AKCoreSampler::setPitchSustainFraction(float value)
--
559 | {
560 | printf("setting pitch sustain level to %f\n", value);  ****
561 | data->pitchEnvelopeParameters.sustainFraction = value;

**Comment by aure** [comment]
Thanks.
