### ISSUE TITLE
Feature request: dialogs to choose inputs / outputs

### ISSUE THREAD

**Issue by akuz** [AudioKit/AudioKit#1989]
It would be nice if AudioKit UI provided dialogs to choose inputs / output from the list of devices, also allowing choosing which channels to use.

**Comment by aure** [comment]
That would be cool. Want to add it via pull request?

**Comment by akuz** [comment]
Will do, if I am able to do it eventually :)

**Comment by aure** [comment]
This will be part of the Cookbook, not part of the AudioKit repo, because its just a recipe which needs to be tweaked by the developer to fit the look and feel of their specific app.

**Comment by RizwanaDesai** [comment]
Any insights if it is added in cookbook for mac?
