### ISSUE TITLE
Swift 5.2 (Xcode 11.4) can't compile AudioKit 4.9.4

### ISSUE THREAD

**Issue by DanielSelig** [AudioKit/AudioKit#1992]
If your issue is implementing AudioKit in your own code, post your problem to [StackOverflow](https://stackoverflow.com/search?q=AudioKit) with the #AudioKit hashtag.

GitHub Issues should only be used for confirmed problems with AudioKit and
well-defined feature requests.

Sponsors will get more attention: https://github.com/sponsors/aure

Make sure you know about the common gotcha's outlined in this video:
https://vimeo.com/audiokit/connecting-nodes-part-2

Problems when submitting your app with the framework? First make sure to check your run phases are set up properly, as outlined in this doc:
https://github.com/AudioKit/AudioKit/blob/master/Frameworks/README.md

**Comment by AssyriaGameStudio** [comment]
Experiencing the same issue:

<img width="1440" alt="Screenshot 2020-03-25 at 17 43 42" src="https://user-images.githubusercontent.com/465214/77568228-37f80a00-6ec0-11ea-9212-ae381916af7d.png">

**Comment by theolampert** [comment]
There is a workaround mentioned here https://github.com/AudioKit/AudioKit/issues/1987#issuecomment-602065765 which suggests using a beta build, this unfortunately produced other issues for me. 
<img width="614" alt="image" src="https://user-images.githubusercontent.com/4714866/77569733-ee60ec80-6eca-11ea-8d25-c9585112376a.png">

**Comment by kurteran** [comment]
> There is a workaround mentioned here [#1987 (comment)](https://github.com/AudioKit/AudioKit/issues/1987#issuecomment-602065765) which suggests using a beta build, this unfortunately produced other issues for me.
> <img alt="image" width="614" src="https://user-images.githubusercontent.com/4714866/77569733-ee60ec80-6eca-11ea-8d25-c9585112376a.png">


AudioKit -> AKManager

**Comment by theolampert** [comment]
@kurteran Ah thank you I missed that! everything appears to be working for me now.

**Comment by kurteran** [comment]
@theolampert yes this is why in 4.9.4 AudioKit made those issues, because AudioKit module and AudioKit had the same name, a common problem in Xcode 11.4.
I have other issues too now: https://github.com/AudioKit/AudioKit/issues/1993

**Comment by aure** [comment]
Lets keep this in one issue. https://github.com/AudioKit/AudioKit/issues/1993

**Comment by tehsven** [comment]
Just updated XCode to 11.4 today and also ran into this same issue.

Relevant PRs that fix the issue for 5.0
https://github.com/AudioKit/AudioKit/pull/1978
https://github.com/AudioKit/AudioKit/pull/1979
https://github.com/AudioKit/AudioKit/pull/1980

But I'm wondering if this issue can ever get fixed for the 4.X series, so we don't have to consume a major version bump of the library?

The other alternative I'm looking at is to downgrade Xcode back to 11.3.

**Comment by naorlugasi** [comment]
Hi 
I'm facing the same problem with the 1000 errors AKNode and all of this
Did anyone manage to solve this?

**Comment by megastep** [comment]
Have you tried 4.9.5 which was released recently, built with Xcode 11.4?

**Comment by naorlugasi** [comment]
> Have you tried 4.9.5 which was released recently, built with Xcode 11.4?

thanks! works

**Comment by zhouhao27** [comment]
> > Have you tried 4.9.5 which was released recently, built with Xcode 11.4?
> 
> thanks! works

How to install 4.9.5 through Pod?

**Comment by megastep** [comment]
@zhouhao27 do a `pod update`, it's the current version and should get picked up.
