### ISSUE TITLE
AKDryWetMixer initializer on v4.9.5

### ISSUE THREAD

**Issue by swlaunch** [AudioKit/AudioKit#1996]
With release of new version 4.9.5, `dry` and `wet` parameters of AKAKDryWetMixer initializer are no longer optional.

Is there any way we can pass optional value here?

**Comment by aure** [comment]
Right, this was a change that @eljeff made. Not sure if we can go back to setting the defaults = nil with his change, but I'll work with him on it.

**Comment by eljeff** [comment]
You can still just AKDryWetMixer() and connect inputs later - that was why I made that change.

**Comment by swlaunch** [comment]
@eljeff I get error when trying to create AKDryWetMixer without parameters, as it tries to call `init()` which is 
```

**Comment by eljeff** [comment]
good find - i missed it because i've been using a copy of this mixer in my own swift file in my project. i'm pushing up a commit right now but if you want to fix it yourself, just add 'public' betwen override and init -> override public init...

**Comment by swlaunch** [comment]
Thanks, @eljeff

**Comment by aure** [comment]
Fixed in https://github.com/AudioKit/AudioKit/pull/2000
