### ISSUE TITLE
Add graphing to more HelloWorld example apps

### ISSUE THREAD

**Issue by narner** [audiokit/AudioKit#200]
The following HelloWorld app currently has a graphing feature implemented: 

* HelloWorld (iOS / Objective - C)

It would be nice to have graphing implemented in the rest of the HelloWorld examples well: 

* HelloWorld (iOS / Swift)
* HelloWorld (OS X  / Objective - C)
* HelloWorld (OS X  / Swift)

**Comment by aure** [comment]
Done.
