### ISSUE TITLE
record iphone 11 microphone with AKClipRecorder Crashed

### ISSUE THREAD

**Issue by snoobel** [AudioKit/AudioKit#2004]
When tried to record iphone 11 microphone with AKCliprecorder, Audiokit can't start.  I wrote a month ago this issue on  SO : https://stackoverflow.com/questions/60263429/audiokit-how-record-iphone-11-microphone-with-akcliprecorder-crashed

**Comment by aure** [comment]
Thanks for pointing out the unanswered SO question. I'll answer what I can over there.
