### ISSUE TITLE
Get Lyrics from MIDI file

### ISSUE THREAD

**Issue by grinmax** [AudioKit/AudioKit#2008]
How can I get the text, or lyrics from a midi file, or karaoke? The text/lyric is on a separate track with a melody inside the MIDI file. Thanks

**Comment by grinmax** [comment]
Why you closed it?

**Comment by aure** [comment]
This is not an issue with AudioKit, more of a question on how to do something with MIDI. In the text that you had to erase to write this issue it suggested that questions are better put on StackOverflow. You're much more likely to find a knowledgeable person on this particular subject than anyone at AudioKit is.  🤷‍♂
