### ISSUE TITLE
how to measure dB(A) or spl meter with audiokit?

### ISSUE THREAD

**Issue by naorlugasi** [AudioKit/AudioKit#2014]
Hi all,
I'm not sure this is the right place but I'm desperate 
I'm using audio kit and I'm trying to measure sound level but the result need ti be with dB(A)
can someone please share with me an example, code lines or anything  to help me solve this.
i tried to look every where but i cant find nothing 

thanks!

**Comment by NicolasLourenco** [comment]
I think you should find your answer here: https://groups.google.com/forum/#!topic/audiokit/9iptQt28bBw

**Comment by naorlugasi** [comment]
> I think you should find your answer here: https://groups.google.com/forum/#!topic/audiokit/9iptQt28bBw

not sure how AKBooster dB return 0

**Comment by NicolasLourenco** [comment]
You need to use `AKAmplitudeTracker`

**Comment by naorlugasi** [comment]
> 20.0 * log10(tracker.amplitude)



> You need to use `AKAmplitudeTracker`
> 
> Something like .
> 
> ```
> mic = AKMicrophone()
> tracker = AKAmplitudeTracker(mic)
> silence = AKBooster(tracker, gain: 0)
> AudioKit.output = silence
> ```
> 
> It's a pseudo code, I've not tested it.
> But the result of `20.0 * log10(tracker.amplitude)` should be the value in dB

im getting negative results 

example:
Amplitude of mic detected:0.0062494161538779736
dB: -44.08321108669632

I thinks this is decibel and not dB(A)

**Comment by NicolasLourenco** [comment]
I think, this is a problem outside the perimeter of this library. 
You have all what you need to calculate db(A)

**Comment by naorlugasi** [comment]
> I think, this is a problem outside the perimeter of this library.
> You have all what you need to calculate dB(A).
> 
> P.S: If you need the frequency, feel free to use `AKFrequencyTracker` instead of `AKAmplitudeTracker ` who allow you to retreive frequency **and** amplitude

Yes i thought so but how?

**Comment by aure** [comment]
Not an issue, but you can feel free to keep posting here with the people who have responded.

**Comment by pniteshnoble** [comment]
Hello @naorlugasi 
Have you found any solutions of it ?
I also looking for it from past few days , But could not find any proper solutions.
