### ISSUE TITLE
AKMicrophoneTracker with custom hopSize + AirPods memory corruption

### ISSUE THREAD

**Issue by ryango** [AudioKit/AudioKit#2015]
let tracker = AKMicrophoneTracker(hopSize: 1024, peakCount: 10)
tracker.start()

This combined with AirPods results in memory corruption - I believe because the hardware only ever seems to provide 4800 sample size buffers, and the tracker is probably copying them into a 1024 frame size buffer.

**Comment by aure** [comment]
The microphone tracker was an old class and it will be deleted from v5.
