### ISSUE TITLE
AKPlayer feature request to reset internal audiofile

### ISSUE THREAD

**Issue by ghubaddole** [AudioKit/AudioKit#2016]
I need to load multiple large files into AKPlayer repeatedly over the lifetime of the app. There are other memory limitations on the app too -- I need a way to have the AKPlayer reset its memory use (the internal audiofile) so as to run lean and not get killed by the os runtime.

since the setter for audioFile is private, I can't do something like player.audioFile = nil. 
This area of the code seems especially intricate to me!

Unless I'm missing an existing way to do so.

thanks!
G

**Comment by ryanfrancesconi** [comment]
have you tried player.load(url: URL) ? An AVAudioFile isn't a heavy object, are you loading exclusively into RAM ?

**Comment by ryanfrancesconi** [comment]
If you are loading into ram the buffer property is public.

**Comment by aure** [comment]
Closing until Ryan's posts are responded to.

**Comment by ghubaddole** [comment]
Sorry -- just recovered from covid.
I can load an empty akaudiofile and that works great. Thanks.

**Comment by aure** [comment]
Awesome! Glad you recovered!
