### ISSUE TITLE
Cannot import AudioKit with cocoapods

### ISSUE THREAD

**Issue by dataexcess** [AudioKit/AudioKit#2017]
Hello,

I am running xcode 11.3.1
When I make a new blank project, first run 'pod install' with the following podfile:

```
target 'testAK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testAK
  pod 'AudioKit'

end
```

I cannot build, I get a 'Failed to load module 'AudioKit' ' Error. 
alongside a long list of other errors. ( https://imgur.com/a/J5SqAC8 )

What could be wrong?
Thnx

**Comment by megastep** [comment]
Try upgrading to Xcode 11.4

**Comment by dataexcess** [comment]
> Try upgrading to Xcode 11.4

Can't - I need to stat on Mojave.

**Comment by megastep** [comment]
In that case, try to request version 4.9.4 explicitly, since that one was built on Xcode 11.3.

**Comment by dataexcess** [comment]
> In that case, try to request version 4.9.4 explicitly, since that one was built on Xcode 11.3.

Thank you! That fixed it.

**Comment by zhouhao27** [comment]
> > Try upgrading to Xcode 11.4
> 
> Can't - I need to stay on Mojave.

How to install 4.9.5 through Pod?

**Comment by dataexcess** [comment]
> > > Try upgrading to Xcode 11.4
> > 
> > 
> > Can't - I need to stay on Mojave.
> 
> How to install 4.9.5 through Pod?

this is my Podfile now:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Header' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Header
  pod 'AudioKit', '4.9.4'

end
```
