### ISSUE TITLE
AKAppleSequencer -> AppleMIDIEvent

### ISSUE THREAD

**Issue by grinmax** [AudioKit/AudioKit#2020]
Hi there.
When i call **AKAppleSequencer(fromURL: url).tracks[2].eventData** i recive this data:
udioKit.AppleMIDIEvent(time: 8.939583778381348, type: 5, data: Optional(0x00007ffeb9123950), dataSize: 25)

How I can understand this data: **Optional(0x00007ffeb9123950)** ?

Thanks.

**Comment by aure** [comment]
Please ask this question on StackOverflow. You may post a link to the SO post here even after I close this issue.
