### ISSUE TITLE
How to simulate scratching / dynamic playback head

### ISSUE THREAD

**Issue by dataexcess** [AudioKit/AudioKit#2021]
Hello, 

This isn't really an issue, but I was wondering if it is possible to simulate scratching of a record player with AudioKit. Going forward and in reverse based on user input. As for now Im not even sure you can easily switch playing back and forward in AudioKit...

Any tips on documentation to achieve this?
Thnx

**Comment by aure** [comment]
Ask that on StackOverflow please. You can post a link to the SO Post in here even after I close this issue.

**Comment by dataexcess** [comment]
> Ask that on StackOverflow please. You can post a link to the SO Post in here even after I close this issue.

Ok. Here it is:
https://stackoverflow.com/questions/61116485/simulate-dynamic-playback-head-with-audiokit-scratching-tunrtablism
