### ISSUE TITLE
More Documentation on Realtime Monitoring and Effects for iOS?

### ISSUE THREAD

**Issue by GastroGeek** [AudioKit/AudioKit#2023]
Hi,

Perhaps I am being blind/dumb but having looked through the playground and examples, most seem to work with pre-recorded audio files only 😦even the 'AKRhinoGuitarProcessor' ?

Is this the sole focus of AudioKit? Or can it be used for realtime effects too?

It would be great to see documentation grouped/specifically for 'realtime' audio processing.

Keep up the good work!

PS - I was trying to build a simple app that applies chorus to the microphone input in realtime and could not get that working... if anyone can point me to a working example, that would be great.

**Comment by GastroGeek** [comment]
Closing as I stumbled on a youtube video with the exact thing I was trying to do 🎉 thanks

**Comment by ghubaddole** [comment]
Could you share the link to the video? Thx
