### ISSUE TITLE
"No such module AudioKit" error in viewController.

### ISSUE THREAD

**Issue by marcuskielman** [AudioKit/AudioKit#2028]
I'm attempting to run the SamplerDemo project from the Source code zip file on the AudioKit.io website. Both the general settings, and build phase settings have the framework imported from the correct file path, and the correct linker flags are added in the Build Settings. This project is also something I haven't even manipulated in any way. However, it always fails to build since the viewController.swift file receives a "No such path AudioKit" error. I assumed this error was specific to the project until I encountered multiple other projects with this similar error, even when downloading the same file from the github repository. I am running these projects in Xcode 11.3.1 on Mac OS Mojave. I'm kinda new to iOS development, so any assistance regarding this will be greatly appreciated.

![Screen Shot 2020-04-14 at 2 07 11 PM](https://user-images.githubusercontent.com/38185803/79258521-426f4900-7e59-11ea-80bc-eb5d6912886f.png)

**Comment by megastep** [comment]
The source code zip file doesn't include built frameworks, so you either need to download one of the other provided files with the releases, or build them yourself using the `Frameworks/build_frameworks.sh` script in the source tree.

**Comment by marcuskielman** [comment]
Thank you so much for this clarification. I'm no longer receiving that error and the Xcode project is building successfully.
