### ISSUE TITLE
Module compiled with Swift 5.1.1 cannot be imported by the Swift 5.2.2 compiler

### ISSUE THREAD

**Issue by markjamesm** [AudioKit/AudioKit#2033]
I'm trying to use CocoaPods to install AudioKit, but after I install the Podfile and open my project's .xcworkspace, I receive the following error: Module compiled with Swift 5.1.1 cannot be imported by the Swift 5.2.2 compiler.

**Steps to reproduce**

1.  Create new project, run 'pod init'
2.  Added this line to my podfile:   pod 'AudioKit', '~> 4.9'
3. Run 'pod install'
4. Open the .xcworkspace file. The error will now display.

![Screen Shot 2020-04-20 at 9 26 45 PM](https://user-images.githubusercontent.com/20845425/79815002-a3ad8580-834d-11ea-89a7-f342a83a97c3.png)

**Comment by markjamesm** [comment]
Xcode version: 11.4.1 (11E503a)

Swift -v output:

Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)
Target: x86_64-apple-darwin19.4.0

**Comment by aure** [comment]
> pod repo update
> pod install

**Comment by markjamesm** [comment]
> > pod repo update
> > pod install

Just tried this now with a fresh project but am still receiving the initial error message.

**Comment by markjamesm** [comment]
> > pod repo update
> > pod install

Many thanks!
