### ISSUE TITLE
AKPlayer duration completely wrong

### ISSUE THREAD

**Issue by Ermahiho** [AudioKit/AudioKit#2037]
Version of AudioKit : Latest
Version of Xcode : Latest available ( not beta )
When you try to open file with .load(url: file) and this file it was made by concatenating two file with AVAssetExportPresetPassthrough will show completely wrong duration. Will show only the duration of first content and not the total. Infact if you try to use .setPosition where the position is in the middle of second part of file will play from 0.0 and not from this point. If you try with the same file something like AVURLAsset(url: voice).duration will show the correct duration. 
You can find file example attach to this message. Try to use .setPosition(5.61) and you will see the problem.
[Traccia_7_Voce.mp4.zip](https://github.com/AudioKit/AudioKit/files/4531979/Traccia_7_Voce.mp4.zip)

**Comment by heldrida** [comment]
Hey @Ermahiho sorry to bother, I'm contacting you because you mentioned that you're using the latest version's of AudioKit and XCode; I tried to create a hello world without success ( https://github.com/AudioKit/AudioKit/issues/2034 ). Would you mind sharing a hello world with latest swift 5.2 and Xcode 1.4, as it seems you managed it? Thanks!

**Comment by ryanfrancesconi** [comment]
actually your file format isn't something I support right now, sorry about that. If you drag into logic you see that you have 2 tracks inside your mp4 container.

![image](https://user-images.githubusercontent.com/2917795/84166593-f6401f80-aa29-11ea-9dc4-5a864a023a61.png)

![image](https://user-images.githubusercontent.com/2917795/84167003-83837400-aa2a-11ea-82ff-ddf1c6714d95.png)

Twisted Wave doesn't open your file at all.

I'm actually surprised that AKPlayer agrees to play it at all. The duration is taken from AVAudioFile, which appears to just be looking at track 1 of your file. If you want to use AKPlayer with this file, you should export to a M4A first. you can do that with AKConverter. File attached as an example.

[Traccia_7_Voce.m4a.zip](https://github.com/AudioKit/AudioKit/files/4753181/Traccia_7_Voce.m4a.zip)

`    
/// The internal audio file
    @objc public private(set) var audioFile: AVAudioFile?

    /// The duration of the loaded audio file
    @objc public override var duration: Double {
        guard let audioFile = audioFile else { return 0 }
        return Double(audioFile.length) / audioFile.fileFormat.sampleRate
    }
`
