### ISSUE TITLE
AKSoundFont.h file not found

### ISSUE THREAD

**Issue by AlesTsurko** [audiokit/AudioKit#204]
Hi! I'm getting this error when trying build latest develop with XCode 7 beta 3. I think the problem is in podspec.

**Comment by aure** [comment]
Sound fonts are only on the develop branch and I think the pod spec is defaults to master - have you changed it?

**Comment by AlesTsurko** [comment]
Yes. In my Podfile I've switched to develop branch. I can't compile master because of getting "bit code enabled/disabled" error for csound framework, that's why I do it - just wanted to try. It's only in XCode 7 new beta. With previous beta there was no this problem. Any way, today I'm already tried to compile with develop just without sound fonts and I get this "bit code" error as I get it with master branch...

**Comment by megastep** [comment]
Bit code is a new Xcode 7 feature we haven't gotten around to implement yet. I heard that they are starting to enforce this in Beta 3.

This is all very beta, so I strongly recommend you stick with Xcode 6 for AudioKit stuff at the moment. We're going to be branching AudioKit at some point over the summer to support all these new features, but it won't be in the mainstream develop branch until Xcode 7 gets out of beta.

**Comment by aure** [comment]
I am going to close this issue for now.
