### ISSUE TITLE
Mac: AKMicrophone initialization crashes when *output* device is not 44.1kHz

### ISSUE THREAD

**Issue by imagine** [AudioKit/AudioKit#2041]
1. Configure *output* device to use non-44.1kHz format in Audio MIDI Setup
2. Launch MicrophoneAnalysis example
3. Crash on AVAudioEngine exception

```[avae]            AVAEInternal.h:76    required condition is false: [AVAudioIONodeImpl.mm:1093:SetOutputFormat: (format.sampleRate == hwFormat.sampleRate)]```

_Originally posted by @fmalekpour in https://github.com/AudioKit/AudioKit/issues/1556#issuecomment-560963001_

**Comment by imagine** [comment]
For AudioKit consumers who are following, the AKSettings workaround does avoid the exception. This line before initializing AKMicrophone():
```AKSettings.sampleRate = AudioKit.engine.inputNode.inputFormat(forBus: 0).sampleRate```

**Comment by heldrida** [comment]
I happen to experience the same issue after leaving a project for a few days and when reopened crashed displaying the message above; Probably could've noticed what caused this before, as I have "External headphones" set to 48khz (I haven't set this myself, and don't know if is the default setting in the operating system so I'll have to assume so). The MacbookPro Microphone default setting might also be 48khz; I did change it a few minutes ago while troubleshooting, so not sure which setting was the default one (haven't changed in the past too), so let's say 48khz.

Catalina 10.15.4
XCode 11.4

Confirming that the `AKSettings.sampleRate = AudioKit.engine.inputNode.inputFormat(forBus: 0).sampleRate` is not the solution for Simulator users , as by changing the Audio Midi settings to 44khz works fine without it.

Tests run without the setting suggested above or @fmalekpour:

1) Audio Midi Settings has MacbookPro Microphone set to 48khz and External Headphones to 44khz | Passed!

2) Audio Midi Settings has MacbookPro Microphone set to 48khz and External Headphones to 48khz | Fails (Thread 1: Exception: "required condition is false: format.sampleRate == hwFormat.sampleRate")

3) Audio Midi Settings has MacbookPro Microphone set to 44khz and External Headphones to 48khz | Fails (Thread 1: Exception: "required condition is false: format.sampleRate == hwFormat.sampleRate")

4) Audio Midi Settings has MacbookPro Microphone set to 48khz and External Headphones to 48khz and the `AKSettings.sampleRate = AudioKit.engine.inputNode.inputFormat(forBus: 0).sampleRate`  | Fails (Thread 1: Exception: "required condition is false: format.sampleRate == hwFormat.sampleRate")

**Comment by ryanfrancesconi** [comment]
Yes, i also saw this issue yesterday working on the v5 branch. The macOS recording needs a total overhaul as it is only a partial implementation. This is on my radar. The fix shown by @imagine is a work around for these examples, but careful sample rate management needs to be done in real applications.

**Comment by aure** [comment]
This will be fixed in version 5, which isn't ready for public consumption, but getting there.
