### ISSUE TITLE
DelayA:setDelay: argument (xxxx.xx) greater than maximum!

### ISSUE THREAD

**Issue by ufosoftwarellc** [AudioKit/AudioKit#2042]
The argument value varies (5090.73, 5393.47, 4280.7)

My original code was
let delay = AKDelay(mandolin)
delay.time = 1.5 / 10.0
delay.dryWetMix = 0.3
delay.feedback = 0.1
let reverb = AKReverb(delay)

I changed it to 
 let delay = AKVariableDelay(mandolin, time: 1.5 / 10.0, feedback: 0.1, maximumDelayTime: 5500)
let reverb = AKReverb(delay)

Then I changed it to
let reverb = AKReverb(mandolin)

Then I changed the effect to AutoWah 

but each case resulted in the same errors
The error causes the audio to glitch and causes the debugger to become unresponsive
DelayA::setDelayMessage from debugger: The LLDB RPC server has exited unexpectedly. Please file a bug if you have reproducible steps.

The issue occurs when the note number fed to the mandolin is less than 5
mandolin.fret(noteNumber: noteNum, course: Int(course))

The AudioKit code should handle this error or at least give a more descriptive error.

**Comment by aure** [comment]
I have updated AKVariableDelay, thanks for pointing this out.
