### ISSUE TITLE
Feature request: AKWaveTable per note velocity (w/ prototype code)

### ISSUE THREAD

**Issue by gregsadetsky** [AudioKit/AudioKit#2043]
Hi! Long time lurker, first time poster :-)

I'm successfully using `AKWaveTable` as the `targetNode` of an `AKSequencerTrack`.

The `AKSequencerTrack` notes are correctly triggering the `AKWaveTable` to start playback. However, the note's velocity information is not used in the playback. As far as I can tell, this is due to [lines 332-333](https://github.com/AudioKit/AudioKit/blob/master/AudioKit/Common/Nodes/Playback/Samplers/Wave%20Table/AKWaveTableDSPKernel.hpp#L332-L333) of `AKWaveTableDSPKernel.hpp` which only check if the velocity is within [0-127], and then start the playback without any velocity info being passed/used.

I made a (hacky? horrible? immoral?) change to `AKWaveTableDSPKernel.hpp` which consists of the following:

```swift
uint8_t note = midiEvent.data[1];
uint8_t veloc = midiEvent.data[2];
if (note > 127 || veloc > 127) break;
// the change is the line below
setVolume(float(veloc) / 127.0);
start();
break;
```

Should I lose my programming license? Be expelled from GitHub? Lose access to electricity? :-)

Yes -- the code above does work. As in, the notes' velocities do affect the `AKWaveTable` playback volume.

But... is this ok? :-) If yes, I'll be happy (& proud) to open a PR. If not, I'll disappear in shame and never bother anybody again here. :-)

Thank you!

**Comment by aure** [comment]
Make a PR, I think this makes sense!
