### ISSUE TITLE
2019 Mac Pro speaker and headphones no sound 

### ISSUE THREAD

**Issue by fabulouspanda** [AudioKit/AudioKit#2047]
I have a strange issue with the 2019 Mac Pro's internal speakers and headphone port. It's running 10.15 Catalina. If they are the selected output device in System Preferences when the app opens there is no sound, however switching to a different device and back again in System Preferences almost always makes the internal speakers start working and occasionally makes the headphones start working. All other output devices (connected via USB or DisplayPort) are working fine. AudioKit.outputDevice shows the speakers or headphones but I hear nothing, whereas on a MacBook Pro running 10.14 Mojave I have no issue with either internal speakers or headphones. How can I further troubleshoot this issue and determine whether I've done something wrong or there's a bug? Due to social distancing those are the only two Macs I have to test with right now.

**Comment by aure** [comment]
Sounds like its probably an issue with the sample rate. Check what it says in Audio Devices in Audio MIDI Setup app:

![image](https://user-images.githubusercontent.com/13122/81619408-62355680-939e-11ea-809a-1b189165f346.png)

Let me know if setting it to 44.1K doesn't solve things.

**Comment by fabulouspanda** [comment]
Thanks for getting back to me - unfortunately that wasn't the issue. The Mac Pro speakers were set to 48k Hz (I think by default as I hadn't changed that) but switching to 44.1 didn't help and the headphones were on 44.1 already.

**Comment by aure** [comment]
Well unfortunately none of have a new Mac to test on and I'm running the latest OS so I don't think its that. I can't really address this issue. 🤷
