### ISSUE TITLE
Possible to build without AudioKitUI?

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#2048]
Is it somehow possible (without big hacks in the script) to use the `./build_frameworks.sh` script to build the whole framework without the AudioKitUI target? The script looks very confusing to me.

**Comment by megastep** [comment]
Not right now, however it should be a simple change to the script to do that.

**Comment by megastep** [comment]
However if you're concerned about build times the UI framework is pretty tiny and shouldn't make a big difference.
