### ISSUE TITLE
AKSequencer tempo incorrect

### ISSUE THREAD

**Issue by SvyatHoly** [AudioKit/AudioKit#2049]
Hello! I'm trying to use the new version of AKSequencer, but it reads midi files incorrectly. 
I set tempo 120, but it is about 4 times faster. When I stretch notes and increase midi file length by  4 - tempo doesn't equal real bpm

**Comment by aure** [comment]
Thanks for notifying us, but its hard to reproduce or get to a fix without sample code or ideally, a sample project demonstrating the issue. I'll alert the primary author of the sequencer but I will also close the issue until more information can be provided.
