### ISSUE TITLE
AKTable Crash

### ISSUE THREAD

**Issue by bport95** [AudioKit/AudioKit#2050]
Occasionally when creating an AKTable my app will crash with the following error: Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

Here is my code: 
`let file = try AKAudioFile(forReading: url)
  let table = AKTable(file: file)`

Attached is one of the audio files that is causing a crash

[Criminal.wav.zip](https://github.com/AudioKit/AudioKit/files/4622957/Criminal.wav.zip)

**Comment by aure** [comment]
Hmm, I don't know how actionable this issue is. Thanks for the wav, but a project or playground that demonstrates the error would be what we would need. I'll re-open this issue if you can get a demo or more info.
