### ISSUE TITLE
Module compiled with Swift 5.1.1 cannot be imported by the Swift 5.2.4 compiler

### ISSUE THREAD

**Issue by waleedsulehria** [AudioKit/AudioKit#2069]
Updated my Xcode and now Audiokit is not been able to compile.

**Comment by aure** [comment]
I have an updated Xcode as well and it compiles, so I need more information from you. I'll close the issue for now.

**Comment by waleedsulehria** [comment]
I am using cocoapoads and Audiokit 4.9.5 and it does not compile. it just simply gives this error. 
Module compiled with Swift 5.1.1 cannot be imported by the Swift 5.2.4 compiler. I have tried updating pod and reinstalling.

**Comment by megastep** [comment]
We're about to push v4.10 which will be built with the current version of Xcode, so hopefully that helps with your issue.

**Comment by waleedsulehria** [comment]
on Cocoapods as well right?

**Comment by megastep** [comment]
Yes, I just pushed the 4.10 pod, it should become available in a few minutes.

**Comment by waleedsulehria** [comment]
Perfect. Thanks you very much it started working again. Thanks again.
