### ISSUE TITLE
AKVibrato causes a crash when phase value is non-integer

### ISSUE THREAD

**Issue by dclelland** [audiokit/AudioKit#208]
I'm trying to use a group of AKVibratos to build a chorus effect, but when I put one out of phase I get an `EXC_BAD_ACCESS` error inside `Csound_render`.

```objc
[self setVibrato1:[[AKVibrato alloc] initWithShape:[AKTable standardSineWave]
                                   averageFrequency:self.rate
                                frequencyRandomness:akp(0.0)
                         minimumFrequencyRandomness:akp(0.0)
                         maximumFrequencyRandomness:akp(0.0)
                                   averageAmplitude:[self.depth scaledBy:akp(0.125)]
                                 amplitudeDeviation:akp(0.0)
                         minimumAmplitudeRandomness:akp(0.0)
                         maximumAmplitudeRandomness:akp(0.0)
                                              phase:akp(0.25)]];
```

![screen shot 2015-07-19 at 19 11 46](https://cloud.githubusercontent.com/assets/967985/8764957/5df9edba-2e4a-11e5-81ed-ff76e3667e38.png)

**Comment by dclelland** [comment]
I'm trying a bunch of random values - 0.0, 0.05, 0.1, 0.15, 1.0 all okay, 0.19, 0.2, 0.25, 0.35, 0.5, 0.75 it doesn't like... weird.

**Comment by aure** [comment]
Can you share the project with me?  I don't think approach will work... and I think the error you're getting is somewhat of a red herring.

**Comment by dclelland** [comment]
Sure thing - I'm pretty sure I'm doing something wrong. 

See here: https://github.com/dclelland/GASP/blob/02a2ff62fa581aad25d43632bba804a0612975cb/GASP/Models/Audio/Filter/Components/GSChorus.m#L41

PS thanks for all your kind help!

**Comment by narner** [comment]
Hey @dclelland, just an FYI that if I click on the link, there's a 404 error.

**Comment by aure** [comment]
For me any non-integer files don't work.  I had to submit a bug report to csound since this is beyond me... https://github.com/csound/csound/issues/507

**Comment by aure** [comment]
They have fixed the issue in git now it is just a matter of updating AudioKit's version of Csound with their changes which Stephane @megastep is in charge of.  Is this a rush or can it come the next time we merge?

**Comment by megastep** [comment]
I can merge this and create new binaries later today. As a side note, the libraries become significantly bigger now that I've turned on Bitcode generation for iOS 9... but we can build with Xcode 6 for now.

**Comment by aure** [comment]
Should we consider using Github's LFS stuff for these binaries so that people aren't necessarily download the history every binary we've ever used?

**Comment by megastep** [comment]
Yeah, it would make sense for that.

**Comment by dclelland** [comment]
No real rush... Cheers though!

**Comment by aure** [comment]
I believe this should now be repaired.
