### ISSUE TITLE
AKDevice has no member 'UID'

### ISSUE THREAD

**Issue by daicche** [AudioKit/AudioKit#2089]
`EZAudioDevice` has member 'UID'
https://github.com/AudioKit/AudioKit/blob/master/AudioKit/Common/Internals/EZAudio/EZAudioDevice.m#L44

However, `AKDevice` has no member 'UID'
https://github.com/AudioKit/AudioKit/blob/master/AudioKit/Common/Internals/AKDevice.swift#L44

I want to use `AudioHardwareCreateAggregateDevice`, which is core-audio function.
`AudioHardwareCreateAggregateDevice` requires device UID as parameters.
So, I need 'UID' member in `AKDevice`.

Is it possible to add UID to `AKDevice` as a member?

**Comment by aure** [comment]
This is probably going to get replaced in v5.
