### ISSUE TITLE
Question - is it possible to export as VST or AU for use within a desktop DAW?

### ISSUE THREAD

**Issue by weavermedia** [AudioKit/AudioKit#2093]
Is it possible to export an AudioKit app as a VST or AU plugin for use within a desktop DAW? Alternatively, is it possible to use JUCE to export an AudioKit app as VST/AU?

I saw a couple of references to this in the closed issues but nothing for the last couple of years.

**Comment by aure** [comment]
Not really as a VST and AUv3 is doable, but not trivial.
