### ISSUE TITLE
V5 develop crashes on code that works on v4...

### ISSUE THREAD

**Issue by ghubaddole** [AudioKit/AudioKit#2102]
I just spent 3 days fixing up code to compile with V5- develop. (mainly AKManager and Double->Float changes all over the place). What was working on v4.9.4 is now crashing in startup. with required condition is false: [AVAudioEngineGraph.mm:3893:MakeVirtualConnection: (IsNodeInGraph(conn.srcNode) && IsNodeInGraph(conn.destNode))]

I'm I doing something wrong, is v5 not ready to test, or is it not compatible with code written for v4? I couldn't find a roadmap or a migration guide :-)
Any guidance on what the recommended changes are coding for v4 vs v5 will help me test the develop branch better!

**Comment by aure** [comment]
V5 is not even in beta yet. It will not be backwards compatible but the changes are pretty easy. 
There will be a migration document. v5 is probably at least a few months away.
I'm happy to review your project if you really want to be ready for v5.

**Comment by ghubaddole** [comment]
Ah ok! Got it :-)
I'll wait -- once it's ready to be tested, I'll be happy to. Looking forward.

**Comment by ryanfrancesconi** [comment]
could you put your crash report here?

**Comment by ghubaddole** [comment]
It's this assert:
required condition is false: [AVAudioEngineGraph.mm:3893:MakeVirtualConnection: (IsNodeInGraph(conn.srcNode) && IsNodeInGraph(conn.destNode))]

I'm trying to narrow it down for you so there's a small amount of code that reproduces the issue.
I'll update this once I have it.
