### ISSUE TITLE
Not sure how to contact about sponsorship

### ISSUE THREAD

**Issue by Rnorback** [AudioKit/AudioKit#2105]
Hi Aure,

Apologies for putting this in the github issues, but this is the only way I have to contact you.

I've signed up as an enthusiast sponsor with hopes of doing a team or enterprise sponsorship soon so we could work together a few hours.

I'm not sure how these sponsorships usually go, but I was hoping to get access to slack as well (That's listed on the sponsorship tier). I have a lot of nuanced questions about AudioKit and think most people won't be able to answer them on StackOverflow.

For instance, I'd like to override the device selection logic so it persists a choice. I'd like to understand why using a BoosterNode results in crashes when I use it with Speech Recognition when changing a device. I'll post a github issue for the second one.

Hope this makes sense and happy to take this down once we're in contact.

Cheers,
Rob

**Comment by aure** [comment]
HI there, yes, as a sponsor, you get special access to me and Github doesn't make it clear. Can you email me at aure. at AudioKit dot io. With your full name and email address and I'll invite you to AudioKit Slack where we can talk in real time as well as exchange files and messages?

**Comment by Rnorback** [comment]
Thanks for the quick reply! I just sent you a message over email.
