### ISSUE TITLE
AKFMOscillator ignoring AKTable when using ADSR for amplitude

### ISSUE THREAD

**Issue by niklassaers** [audiokit/AudioKit#211]
Hi Aure,
The following code gives a nice and pleasing sound, only not a sine wave, like I expected when setting a waveform:

        // Instrument Properties
        _amplitude = [self createPropertyWithValue:0.5 minimum:0.0 maximum:1.0];
        
        _adsr = [[AKLinearADSREnvelope alloc] initWithAttackDuration:akp(0.1)
                                                       decayDuration:akp(0.1)
                                                        sustainLevel:akp(0.5)
                                                     releaseDuration:akp(0.1)
                                                               delay:akp(0)];
        
        // Instrument Definition
        self.oscillator = [AKFMOscillator oscillator];
        self.oscillator.baseFrequency = note.frequency;
        self.oscillator.amplitude = [_adsr scaledBy:_amplitude];
        
        AKTable *sineTable = [AKTable standardSineWave];
        [sineTable scaleBy:0.7];
        self.oscillator.waveform = sineTable;
        
        [self setAudioOutput:[self.oscillator scaledBy:_amplitude]];

If I remove the _adsr part, it produces a nice sine. If I then replace the sine with a square, I get a square sound. If I then put in the _adsr part, I get the original sound, not a square sound.

I've made a diff to the ContinuousControl example that demonstrates this: https://www.dropbox.com/s/qzvfzvia19yq4th/AKFMOscillator_issue.diff?dl=0

How can I keep using the AKFMOscillator with custom AKTables, yet still have an ADSR instead of a fixed amplitude?

Cheers

    Nik

**Comment by aure** [comment]
I am not hearing this behavior.  Are you on develop or master branch?

**Comment by niklassaers** [comment]
This is with master checked out today (of Examples). I've made another diff that just keeps a single frequency: https://www.dropbox.com/s/bmja9ppzk3hxx1q/AKFMOscillator_issue_diff2.diff?dl=0  I would capture the audio, but for some reason my audio recording went all silent. I'll make a sound recording as soon as I've got that one back online :-)

**Comment by niklassaers** [comment]
Here is sine: https://www.dropbox.com/s/m6jtc0omzij5ot2/Sine.mov?dl=0
Here is square: https://www.dropbox.com/s/l8iytfgl1en0q78/Square.mov?dl=0

**Comment by niklassaers** [comment]
Hmm, while it did sound the same to me, now that I switch a bit back and forth, it doesn't sound all that alike. I'll try narrowing it further a bit. :-)

**Comment by niklassaers** [comment]
For what it's worth, what I was trying to recreate was how this sound https://www.dropbox.com/s/aplivwwl7zwoek9/Harmonic-no-adsr.mov?dl=0 morphs to this sound https://www.dropbox.com/s/r3bms8lpgac3f08/Harmonic-with-adsr.mov?dl=0 when all I do is add the ADSR instead of setting the amplitude directly.

**Comment by niklassaers** [comment]
(I'll work out an example and post it in the group, this does not seem to be an issue like I thought it was)
