### ISSUE TITLE
Xcode 12 beta 1 compatibility

### ISSUE THREAD

**Issue by colinhumber** [AudioKit/AudioKit#2110]
I'm sure this is in progress, but adding it here for posterity.

Building AudioKit 4.10.1 (latest) fails in Xcode 12 beta 1.

![image](https://user-images.githubusercontent.com/104855/85340025-8f4b4d80-b4a2-11ea-8404-83679c19251b.png)

**Comment by aure** [comment]
oh we have been working on this for months lol

**Comment by colinhumber** [comment]
FWIW, I am _very_ grateful for all the work you all put into this.

**Comment by aure** [comment]
Well, fyi, the v5-develop branch builds just fine in Xcode 12.

**Comment by colinhumber** [comment]
That is great to know. I'll check it out!

**Comment by aure** [comment]
Well, iOS built, macOS might require some fixes which I'll try to do now.

**Comment by aure** [comment]
Fixed the macOS issue I think, v5-develop now builds on all platforms.

**Comment by aure** [comment]
FWIW, v4-develop worked for me too.

**Comment by aure** [comment]
Is this for the Xcode that builds for hardware that doesn't exist yet?

**Comment by colinhumber** [comment]
I hadn't tried any of the dev branches. We have a cocoapod that uses 4.10.1 as a dependency which was having the problem. I was using just the normal Xcode 12 (12A6159). Just trying the same pod with 5.0.b1

**Comment by colinhumber** [comment]
Got it working with 5.0.b1 as a dependency instead of 4.10.1. Thanks for the heads up about that. Looks like I just have some iOS 14 hiccups to work through now, but the app is at least up and running. Thanks!

**Comment by aure** [comment]
Cool!
