### ISSUE TITLE
Small error in documentation about including from source

### ISSUE THREAD

**Issue by gertjanjansen** [AudioKit/AudioKit#2114]
Could it be that this is a small mistake installation instructions to include AudioKit from source?:

"In the **Build Phases** tab, add AudioKit.framework in **Target Dependencies** for your target. Also add AudioKitUI.framework as needed."

From: https://github.com/audiokit/AudioKit/blob/master/Frameworks/README.md

I don't see **Target Dependencies** under the **Build Phases** tab. I think it should be **Frameworks, Libraries and Embedded Content** under the **General** tab.

**Comment by aure** [comment]
Tne README file is just like source code, it can be edited by you and you can make a pull request. Your update is valid and will be accepted.

**Comment by gertjanjansen** [comment]
I'll do it this week. I might also have a few other fixes for some issues I encountered related to AKAppleSequencer.
