### ISSUE TITLE
Not Getting Documentation in AudioKit Playgrounds

### ISSUE THREAD

**Issue by brentbrinkley** [AudioKit/AudioKit#2115]
I'm running the AudioKit playgrounds and I'm not getting documentation when I option-click or search. I'm using Xcode 11.5. The downloads page says: "Code completion, pop-ups, and sidebar information are automatically created in Xcode 9"

I checked on stackoverflow before coming here and found this similar issue:

[https://stackoverflow.com/questions/47759070/installing-xcode-documentation](url)

A maintainer says they're going to update the page where this information is found but as far as I can tell nothing has changed.

**Comment by aure** [comment]
Hi Brent, we haven't needed to create documentation that way in a while because if you open up the AudioKit Xcode project all the documentation is automatically created from the source by Xcode. This is probably not working in playgrounds, as you point out, so I'll look into if its still possible to install documentation in a different way, perhaps similar to how it was done before Xcode had autodocumentation.

**Comment by brentbrinkley** [comment]
Awesome. Thank you. I'm not sure why playgrounds wouldn't work in the same fashion. You would think that after building the project that same data would be generated.

**Comment by aure** [comment]
My idea of creating docsets is indeed way out of date (as of version 5 and we're on 11). I could make them available so that they could be viewed with this app: https://documancer.com/xcode/ What do you think?

**Comment by aure** [comment]
Actually that app may be outdated since putting the docset in the correct location did not make the docs appear in Xcode. You might just have to use http://audiokit.io/docs/ lame, I know.

**Comment by aure** [comment]
Dash can still open our docsets: https://kapeli.com/dash

**Comment by brentbrinkley** [comment]
Hmm that's unfortunate I really wanted access to the docs in Xcode as I'm playing around with the codebase. Being able to control-click on something when you don't know what it does is extremely helpful when learning.

**Comment by aure** [comment]
I know! If you see another non Apple open source framework where docs work we can look at it to see how they did it.

**Comment by aure** [comment]
This will be working in v5 of AudioKit. I've got some leg work to do to convert things, but after that you should be good.  Closing the issue for now.
