### ISSUE TITLE
Swift Thread 1: EXC_BREAKPOINT (code=EXC_ARM_BREAKPOINT, subcode=0xe7ffdefe)

### ISSUE THREAD

**Issue by saurav-997** [AudioKit/AudioKit#2128]
I am playing a 2500 Hz sound on iPhone 4s iOS(9.3.5) and my app crashed, by debugging i get this error.
Error :- Swift Thread 1: EXC_BREAKPOINT (code=EXC_ARM_BREAKPOINT, subcode=0xe7ffdefe)

override func viewDidLoad()
     {    
     AKSettings.defaultToSpeaker = true
                    do{
                        try AKSettings.setSession(category: AKSettings.SessionCategory.playAndRecord, with: .defaultToSpeaker)
                    }catch{
                        print(error.localizedDescription)
                    }
                    
                    let file_input = try? AKAudioFile(readFileName: "2.5kz_sound.wav")
                    player = AKPlayer(audioFile: file_input!)
                    if !AudioKit.engine.isRunning {
                        try? AudioKit.start()
                    }
                    
                    player.play()
    }
I get this error on AKsettings.setsession line and sometimes audio is not playing on iOS 13.5

**Comment by aure** [comment]
Sorry this is not enough to go on, maybe ask this on StackOverflow or provide a project.
