### ISSUE TITLE
Errors compiling when Project name has a space in it

### ISSUE THREAD

**Issue by mekohler** [audiokit/AudioKit#213]
No idea what the issue is, but I spent hours trying to get AudioKit to compile following your tutorial video. I kept getting the following errors:
dyld: Library not loaded: libsndfile
dyld: Library not loaded: CsoundLib

If you follow the tutorial video exactly but your project name/dir has a space in it, you will get these errors.

The only thing that fixed it was creating a project name with no space in it. You might want to include this in the readme.

**Comment by megastep** [comment]
Are you using the master or develop branch? We actually fixed quite a few problems with this in the develop branch.

**Comment by mekohler** [comment]
Master, I'll try with dev. Thanks!

**Comment by aure** [comment]
Dev has got some other issues, just so you know.  Might be better off just taking the spaces out of your project folder's name.
