### ISSUE TITLE
AKAudioFile Format changed after export

### ISSUE THREAD

**Issue by nikolindima** [AudioKit/AudioKit#2133]
I try to use AKNodeRecorder to record mic data. 
After i run record() method - i get this output in console: 
[general] AKNodeRecorder.swift:record():114:Recording using format <AVAudioFormat 0x2817fe210:  2 ch,  48000 Hz, Float32, non-inter> (AKNodeRecorder.swift:record():114)

My session is setup for 48 kHz  - AKSettings.sampleRate = 48000

After recording I try to save data but saved file have different sample rate

recorder.stop()
let tape = recorder.audioFile
print(tape?.fileFormat) // Optional(<AVAudioFormat 0x2821dd9f0:  2 ch,  48000 Hz, Float32, inter>)
print(tape?.processingFormat) // Optional(<AVAudioFormat 0x2821dd810:  2 ch,  48000 Hz, Float32, non-inter>)
tape?.exportAsynchronously(name: "name", baseDir: .documents, exportFormat: .m4a) {file, exportError in
                if let error = exportError {
                    print("Export Failed \(error)")
                } else {
                    print("Export succeeded")
                    print(file?.fileFormat) //Optional(<AVAudioFormat 0x2821de2b0:  2 ch,  44100 Hz, 'aac ' (0x00000000) 0 bits/channel, 0 bytes/packet, 1024 frames/packet, 0 bytes/frame>)
                    print(file?.processingFormat) //Optional(<AVAudioFormat 0x2821dd9f0:  2 ch,  44100 Hz, Float32, non-inter>)
                }
}

I have this problem only with m4a and mp4 format. With caf, aif and wav - format is 48 kHz

**Comment by ryanfrancesconi** [comment]
AKAudioFile is going to be deprecated. I recommend using AKConverter instead. If the source sample rate is 48k the output should be there as well.

**Comment by ryanfrancesconi** [comment]
check the macOS Recorder example in the v5 development branch for the AKConverter example. AKAudioFile is now removed from the API.
