### ISSUE TITLE
v5.0.b1: Setting the output (AKSampler) to the AKManager causes a crash on iOS 14 devices when started.

### ISSUE THREAD

**Issue by impmaarten** [AudioKit/AudioKit#2136]
We have updated the app to make use of **v5.0.b1** to make it compilable on XCode 12, after some minor required changes we got it compilable (ex. AudoKit -> AKManager and required initializers).

But we do run into some issues,  for instance on iOS 14 Devices build from Xcode 11 and 12, we get the following issue when we assign `AKSampler` as output for the `AKManager.output` and start the `AKManager` with the following console crash details as result:

```
2020-07-06 13:35:18.590866+0200 X[45490:655818]  HALB_IOBufferManager_Client::GetIOBuffer: the stream index is out of range
2020-07-06 13:35:18.591072+0200 X[45490:655818]  HALB_IOBufferManager_Client::GetIOBuffer: the stream index is out of range
2020-07-06 13:35:18.602009+0200 X[45490:655818] [aqme] 255: AQDefaultDevice (1): output stream 0: null buffer
2020-07-06 13:35:18.602404+0200 X[45490:655818] [aqme] 1778: EXCEPTION thrown (-50): error != 0
2020-07-06 13:35:27.485964+0200 X[45490:655338] Initialize: Mach message timeout. Apparently deadlocked. Aborting now.
CoreSimulator 725.10 - Device: iPhone 11 Pro Max (X) - Runtime: iOS 14.0 (X) - DeviceType: iPhone 11 Pro Max
```

And on devices lower than iOS 14.0 the `AKSampler.stop` seems not to work at all. sounds are played, but can't be stopped.

I have tested it on a clean project and the output issue is still present, so it doesn't seem implementation related.

Thanks in advance.

**Comment by aure** [comment]
Could you by any chance use the latest code off of the v5-develop branch? There is work happening on v5 every day and as beta software I can't support debugging off of a specific beta version. Thank you for try v5 however, and I would love to know if the probably persists in the latest versions of the tools and the beta operating systems.

**Comment by impmaarten** [comment]
Thank you for your response, @aure 

I've used the develop branch of version 5 as you suggested via the guide. [**link**](https://github.com/audiokit/AudioKit/blob/master/Frameworks/README.md)
1. Downloading the repository
2. Dragging in the `.xcodeproj` into the app xcode project
3. Adding the Audiokit.frameworks to Frameworks of the target.

I succeeded to build it and I have the following findings:

- The crash no longer appears on iOS 14 when the `AKSampler` is set as `AKManager.output`!
- The issue of AKSampler stop is still present and causes the sound to never stop playing. `AKSampler.stop(noteNumber:)`
    - I did make sure that the playing MIDINoteNumber is the same as the one that is getting stopped.
- `exportAsynchronously` is removed from `AVAudioFile`, I searched a little bit and it could be that we can use `AVAssetExportSession` to replace it with?

**Comment by aure** [comment]
The most recent changes to AKSampler have come from @eljeff but perhaps when I merged them into v5 something went wrong. @ryanfrancesconi removed AKAudioFile which was getting unwieldy and instead we have a suite of tools inside the top level /Audio Files/ folder in the AudioKit xcodeproj, perhaps something in there like AKConverter can help?

**Comment by eljeff** [comment]
Re: aksampler start/stop ... what are your envelope settings?
If you could print out:
.attackDuration
.holdDuration
.decayDuration
.sustainLevel
.releaseHoldDuration
.releaseDuration
That might answer some questions
I can't comment much on AK5 tho - I've barely used it.

**Comment by ryanfrancesconi** [comment]
@impmaarten You can use AKConverter to export to different formats.

**Comment by impmaarten** [comment]
@eljeff 
```
attackDuration: 0.0
holdDuration: 0.0
decayDuration: 0.0
sustainLevel: 1.0
releaseHoldDuration: 0.0
releaseDuration: 0.8
```

We didn't set any of these values, besides the **releaseDuration**

_Start playing of a note_
`play(noteNumber:velocity:)`

_Stop playing of a note_
`stop(noteNumber:))`

**Comment by eljeff** [comment]
Cool thanks - was just checking that your holds werent set. When I start playing with AK5 I'll see how aksampler behaves.

**Comment by Francois-Laberge-Bose** [comment]
Noobie here on using cocoapods. How do I get at a pod of AudioKit that fixes: `Failed to build module 'AudioKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.22.4 clang-1200.0.25.1)'`? 

Do I need to build from source and learn to link in prerelease pods?

**Comment by megastep** [comment]
@Francois-Laberge-Bose Easiest would be for you to use our beta 5.0.b1 pod. Instructions are here:

https://github.com/AudioKit/Specs

**Comment by Francois-Laberge-Bose** [comment]
@megastep Forgot to respond. Thanks, the instructions were easy and it worked. Much appreciated
