### ISSUE TITLE
Big Sur: warnings after updating deployment target

### ISSUE THREAD

**Issue by wtholliday** [AudioKit/AudioKit#2139]
Updating the deployment target for AK results in many warnings about framework headers not using angle brackets, such as:

> Double-quoted include "AKDSPBase.hpp" in framework header, expected angle-bracketed instead

Could get a head start on this cleanup.

**Comment by aure** [comment]
I think this might be taken care of with the recent changes no?

**Comment by aure** [comment]
Closing until more info.
