### ISSUE TITLE
enableMIDI(name: ) bug iOS 14 beta 2

### ISSUE THREAD

**Issue by emurray2** [AudioKit/AudioKit#2145]
The issue is that in files such as `AKMIDISampler.swift`, the function `enableMIDI(name:)` is not working as intended on iOS 14.0 beta.

When the function is run on iOS 14.0, only 1 MIDI Note Event will be parsed at a time and there is no polyphony.

On iOS 13.5.1, the function works as intended and can parse multiple MIDI Note Events occurring at the same `MIDITimeStamp`, allowing polyphony.

Some things I have tested and researched:

When I run this code with the print statement inside the closure on iOS 13.5.1

`open func enableMIDI(_ midiClient: MIDIClientRef = AKManager.midi.client,
                         name: String = "MIDI Sampler") {
        CheckError(MIDIDestinationCreateWithBlock(midiClient, name as CFString, &midiIn) { packetList, _ in
            for e in packetList.pointee {
                let event = AKMIDIEvent(packet: e)
                print(event.data)
                do {
                    try self.handle(event: event)
                } catch let exception {
                    AKLog("Exception handling MIDI event: \(exception)", log: OSLog.midi, type: .error)
                }
            }
        })
    }`

All of the MIDI Note Events print out, including ones that occur at the same `MIDITimeStamp`.

However, on a device running iOS 14.0, only one MIDI Note Event will be printed out at a time and sent to the internal Audio Unit of an `AKNode`.

I also noticed that Apple added a new function in iOS 14 beta, `MIDIDestinationCreateWithProtocol`.

`MIDIDestinationCreateWithBlock(_:_:_:_:)` is now marked as deprecated.

I am not sure how to fix this bug yet, but I will continue figuring it out. I just thought I would leave my findings here incase someone smarter than me knows a fix to the problem ;) .

**Comment by emurray2** [comment]
Just an update so people know I'm making progress on solving this issue:

I have messed around with print statements some more and found good news.

I created a test MIDI file at 120 bpm which plays 1 note, then 2 notes, then 3 notes, then 4 notes to debug polyphony.

I used the new function in iOS 14 beta `MIDIDestinationCreateWithProtocol`

`open func enableMIDI2(
        _ midiClient: MIDIClientRef = AKManager.midi.client,
        name: String = "MIDI Sampler") {
        if #available(iOS 14.0, *) {
            CheckError(MIDIDestinationCreateWithProtocol(midiClient,
            name as CFString,
            MIDIProtocolID._1_0,
            &midiIn, { eventList, _ in
                print(eventList.pointee.packet.words)
            }))
        } else {
            // Fallback on earlier versions
        }
    }`

Inside the closure which is run when a MIDI event is received, I wrote a print statement, `print(eventList.pointee.packet.words)`

This is the output when the program is run with my debug MIDI file:

`(546323556, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
(546323456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
(546323556, 546324068, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
(546323456, 546323968, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
(546323556, 546324580, 546325348, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
(546323456, 546324480, 546325248, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
(546323556, 546324580, 546325348, 546325860, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
(546323456, 546324480, 546325248, 546325760, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
`

From this data, I can tell that all of the MIDI events are being received properly from Apple's end of things. I think the `AKMIDIEvent` class just needs to be updated a little bit to properly read each event. I will work on doing that.

**Comment by aure** [comment]
Make sure you stay up to date with AudioKit v4 and v5 branches as @eljeff has been making some really great updates to MIDI recently.

**Comment by emurray2** [comment]
Sounds good, I will keep looking out for updates. I have lately been using the v5 branch and it works nice with all the betas.

**Comment by eljeff** [comment]
@emurray2 yea i actually tried to tag you in some stuff of yours i edited and/or will need to be updated, but i didnt know your handle.
but yea midi file parsing was way broken (got timing wrong after a few bars) and it should be better now

**Comment by eljeff** [comment]
ANd yea to this particular issue, I can't speak to ios updates, but its a very common mistake to only read the first event in the midi packet. If they changed something or if it was ever working properly for akmidievent (needs a major overhaul, ideally trashed completely), I know we fixed in one spot but there is a lot of redundancy in AK so its hard to keep track of what works best for what.

**Comment by emurray2** [comment]
@eljeff Oh awesome! Thank you for fixing that. Yeah what you're describing I think is what's happening. I have done some testing with the latest v5 branch on both iOS 14 and iOS 13, and I found a slight difference. The MIDI packets are sent out separately for each note event on iOS 13, even if they happen at the same time. However, on iOS 14 things have changed and multiple note events occurring at the same time are sent in one packet. So like you said, only the first event in the MIDI packet is being read.

**Comment by emurray2** [comment]
I changed the code a little bit and submitted a PR. Everything seems to work fine now, so I'll close this for now. But if you guys have any feedback, please let me know. And if this issue comes up again, I'll reopen it.

**Comment by eljeff** [comment]
@emurray2 dude thanks

**Comment by emurray2** [comment]
@eljeff You're welcome. Thank you for helping me out.

**Comment by eljeff** [comment]
Of course - now that I know how to tag you, I will next time I'm in the part of your code I had a question about

**Comment by emurray2** [comment]
Sounds good!
