### ISSUE TITLE
turning off clang optimizer causes 7 test failures

### ISSUE THREAD

**Issue by wtholliday** [AudioKit/AudioKit#2176]
To reproduce:

1. Open iOSTestSuiteForDev/iOSTestSuite.xcodeproj.
1. Select AudioKit-iOS target.
1. Open Build Settings
1. Under "Apple Clang - Code Generation", set "Optimization Level" to "None [-O0]" for Debug build configuration:

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/841144/87858017-f6acbf80-c8df-11ea-9996-72cffa632a10.png">

5. Run iOSTestSuite
6. Observe:

<img width="543" alt="image" src="https://user-images.githubusercontent.com/841144/87858038-0fb57080-c8e0-11ea-8dfc-0e5cb3ab170c.png">

All failing tests are #if'ed out on `macOS`, e.g.:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/841144/87858110-658a1880-c8e0-11ea-977a-c85a45f59d01.png">

**Comment by wtholliday** [comment]
Funny, UBSan hits a failure in the md5 code:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/841144/87859021-0e3b7680-c8e7-11ea-8258-5fd0b0998761.png">

**Comment by wtholliday** [comment]
md5 issue was easy to fix. Wild guess is that this is a manifestation of race conditions uncovered by Thread Sanitizer.

**Comment by aure** [comment]
This is now exactly reproducible on the macOSTestSuiteForDev project as well.

**Comment by aure** [comment]
The thing all of these failing tests have in common is that they set the vibrato. The way vibrato is done in these I think is very bad and related to our conversations about pow in taper/skew.  Check out this:

https://github.com/AudioKit/AudioKit/blob/49d19b2d2ce836b01db39d6973866fe222909095/AudioKit/Common/Nodes/Generators/Polysynths/Oscillator%20Bank/AKOscillatorBankDSPKernel.hpp#L57

The vibrato is a calculated sine in there. These banks are some of the heaviest, nastiest code in AudioKit and I'm tempted to remove them until something similar can be added that is better. I could just remove vibrato on these classes as well, but that's not the way I would like to go with AK5.

**Comment by wtholliday** [comment]
A debugging approach here could be for the kernel to print its state after every render call. Then diff the output for test runs.

**Comment by wtholliday** [comment]
Printing `variation` yields same output for both builds.

**Comment by wtholliday** [comment]
I suspect this is due to slightly different floating point output in the `powf` function between optimized and debug builds.

I'm seeing the same floats (exact, by bit pattern, not by formatted output) passed to powf, but slightly different results between optimized and debug builds. I don't know if there's a guarantee of the same numerical output for C math functions when optimized (one would hope so, but perhaps not).

Because an oscillator is stateful, this compounds into fairly significant difference over time.

The relevant line is:

https://github.com/AudioKit/AudioKit/blob/49d19b2d2ce836b01db39d6973866fe222909095/AudioKit/Common/Nodes/Generators/Polysynths/Oscillator%20Bank/AKOscillatorBankDSPKernel.hpp#L58

**Comment by wtholliday** [comment]
Posted here:

https://stackoverflow.com/questions/62984788/why-does-powf-return-a-different-result-with-optimization-on

**Comment by wtholliday** [comment]
PR: https://github.com/AudioKit/AudioKit/pull/2179
