### ISSUE TITLE
AudioKit pollutes namespace

### ISSUE THREAD

**Issue by wtholliday** [AudioKit/AudioKit#2182]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/841144/87954026-aad55400-ca60-11ea-8c69-9fc6e12668c9.png">

We can do better:

https://medium.com/@yuliiasynytsia/link-static-c-library-to-swift-framework-as-a-private-module-97eae2fec75e

**Comment by aure** [comment]
Maybe we can address this hideous "doAK" prefix Shane resorted to as well:

![image](https://user-images.githubusercontent.com/13122/87972809-65bf1b00-ca7c-11ea-8c0b-0b8c86fd765f.png)

**Comment by wtholliday** [comment]
I haven't been able to hide the functions with module maps. I tried various things.

I created a header `AudioKit_Private.h` and moved `createAmplitudeEnvelopeDSP` into it as a test.

I then created a private module map as explained in the [clang documentation](http://clang.llvm.org/docs/Modules.html#private-module-map-files):

```
module AudioKit_Private {
    header "AudioKit_Private.h"
}
```

That didn't work as there seemed to be no way to import `AudioKit_Private` from Swift.

So I tried the following for the public module map:

```
framework module AudioKit {
  umbrella header "AudioKit.h"

  export *
  module * { export * }

  module Private {
       header "AudioKit_Private.h"
  }
}
```

Now I could do `import AudioKit.Private` within AudioKit and see the function.

Alas, the function is still visible outside of AudioKit.

So I tried getting rid of the `export *`, doing this:

```
framework module AudioKit {
  umbrella header "AudioKit.h"

  export Foundation
  export CoreMIDI
  export CoreAudio
  export CoreAudioKit
  export AVFoundation
  export os
  export Accelerate
  // export *
  // module * { export * }

  module Private {
       header "AudioKit_Private.h"
  }
}
```

But it's STILL visible outside of AudioKit.

If we look at the generated Swift interface for AudioKit, we can see:

```
import AVFoundation
import Accelerate
import AudioKit
import AudioKit.Private
import AudioKit.Private
import AudioKit.Swift
import AudioToolbox
import AudioUnit
import CoreAudio
import CoreAudioKit
import CoreMIDI
import Dispatch
import Foundation
import os
```

So it seems that it just gets imported.

At this point, there are some other options:

- Put a prefix (`__AK_private`) on all those functions. That will make the code completion less likely.
- Use a single function to create nodes.

There are various ways of registering C++ classes, but they will involve ensuring that all initializers are run via `all_load` which isn't great. Perhaps an option would be to use `dlsym` so we would have a single creation function that could be called as follows:

`__AK_private_createDSP("AKOscillatorDSP")`

That has the nice property that AudioKit.h doesn't need to be modified when adding a new node.

**Comment by wtholliday** [comment]
I tried the following:

```
AKDSPRef __ak_private_createDSP(const char* name) {

    // sanity check
    assert(dlsym(RTLD_DEFAULT, "printf"));

    AKDSPRef (*func)(void) = dlsym(RTLD_SELF, name);
    if(func == NULL) {
        printf("error: %s\n", dlerror());
    }
    assert(func);
    return func();

}
```

This fails with the error:

`error: dlsym(RTLD_SELF, createOscillatorDSP): symbol not found`

but that symbol is in the image:

```
holliday@Taylors-iPro % nm -m AudioKit | grep createOsc
0000000000000000 (__TEXT,__text) external _createOscillatorDSP
```

(prepending the `_` doesn't fix it)

**Comment by aure** [comment]
Ameliorated somewhat by the change to "ak" prefix for internal Swift/C communication.  
![image](https://user-images.githubusercontent.com/13122/89115778-f31d4a80-d440-11ea-8a0c-139a171f61b2.png)

If this can be considered good enough, we could close the issue.

**Comment by aure** [comment]
Feel free to reopen, but I am satisfied with tidy pollution.
