### ISSUE TITLE
TSAN CI build doesn't work

### ISSUE THREAD

**Issue by wtholliday** [AudioKit/AudioKit#2183]
The TSAN CI build doesn't recompile AudioKit with TSAN turned on. Should use `Tests/iOSTestSuiteForDev/iOSTestSuite.xcodeproj` to run tests, as this will recompile AudioKit.framework with TSAN instrumentation.

Note that when fixing this, you'll hit test failures because TSAN detects problems with `AKParameterAutomation` and the new automation code.

I tried to fix this myself and hit two roadblocks:
- Adding a TSAN scheme to iOSTestSuiteForDev/iOSTestSuite.xcodeproj didn't result in a git diff. gitignore perhaps? (this project should be renamed actually, instead of just using a different dir)
- When running the fixed TSAN build via command line, the TSAN failures become crashes which seemed to invoke Crash Reporter. The tests did resume, but it was very slow.

**Comment by megastep** [comment]
But I get your point about having to recompile AudioKit itself, so switching to that new project would be doable but will also make the CI test time go significantly slower...

**Comment by wtholliday** [comment]
You added the scheme to the other project. I was trying to add it to `iOSTestSuiteForDev`.

**Comment by megastep** [comment]
Right - but if as you say the tests crash with TSAN on and don't register as failing, should we even bother here?

**Comment by megastep** [comment]
We could also split the tests into more tasks, and spawn these unit test runs in parallel with the regular builds and other tests, since they don't need to wait on any of the other build tasks.

**Comment by megastep** [comment]
So I added a new step to the workflow that runs the `macOSTestSuiteForDev` tests twice with the thread and address sanitizers. Takes about 10 minutes total to complete so it's not too bad, while the rest of the build continues.

Doing just macOS as it's much faster to recover from crashes than the iOS version (no need to respawn the simulator), and I assume we're testing pretty much for the same things. So as of right now the builds crash with 6 failures in the thread sanitizer.

**Comment by wtholliday** [comment]
I think we should disable the TSAN build for now. As best I can tell, Apple's AudioUnit code trips TSAN. I'll be trying to come up with a distilled repro case that I can file with them.

**Comment by megastep** [comment]
I see you already commented out the task in the workflow, however I'm putting it back just without the thread sanitizer for now. It's probably good to at least keep checking the address sanitizer, which was also part of the job.

**Comment by aure** [comment]
Yeah, go for it, I was just sick of seeing failures.

**Comment by aure** [comment]
I see thread sanitizer in the Github actions, so is this issue effectively addressed?

**Comment by megastep** [comment]
It's commented out right now but I left a run with the address sanitizer. So we can turn it back on once we've fixed the underlying issues.
