### ISSUE TITLE
Can I convert audio file to another format instead of wav, aif, caf, m4a

### ISSUE THREAD

**Issue by lieudd** [AudioKit/AudioKit#2186]
Dear AudioKit authors,

I have a project that I have to convert audio file to various types format such as : mp3, aiff, m4a, mp4, caf, flac, acc, ogg, sd2. The original file format should be various format type too. I found Audiokit only support output format 4 types: wav, aif, caf, m4a, and support various input type. So I have two questions:
1, Why audiokit only support 4 output format types?
2, Can I convert a audio file to others type instead of 4 types wav, aif, caf, m4a and how to do that?

Please help me to figure out the solution.

**Comment by aure** [comment]
Thanks for your question, though it doesn't quite belong on issues. We support those file types because they have been sufficient for our project needs. If you'd like to add support for more, you're welcome to.

**Comment by lieudd** [comment]
> Thanks for your question, though it doesn't quite belong on issues. We support those file types because they have been sufficient for our project needs. If you'd like to add support for more, you're welcome to.

Thank so much for the reply!

I need help to export audio file to another format such mp3, aiff, m4a, mp4, flac, acc, ogg, sd2... beside wav, aif, caf. How can I do that?

**Comment by aure** [comment]
Are you a programmer? Can you hire one? I can put a job offer into our AudioKit discussion forum if you like.
