### ISSUE TITLE
Getting a sound finished event

### ISSUE THREAD

**Issue by anderm** [audiokit/AudioKit#219]
Hi all,

I just started working on a project to use the 3D audio capabilities of AudioKit. I implemented the 3d binaural example but I can't seem to get any event that will let me know if a sound has finished playing or not. What is the best way to do that? 

I am looking for something similar to the AVAudioPlayer that has a - (void)audioPlayerDidFinishPlaying.

Thank you for your help

**Comment by aure** [comment]
Sorry I was traveling and didn't have time to respond.  At the moment we don't have a callback for events like that.  I think it would be a good idea, but its not something that AudioKit does currently.

**Comment by megastep** [comment]
Is there something that Csound does that we could hook into to implement this?

**Comment by aure** [comment]
@megastep Not for events like that, I don't believe.  We could rig up a counter and create a callback when it reaches the file length.  Not trivial.

**Comment by aure** [comment]
New version of AudioKit...
