### ISSUE TITLE
Recorded File tickle/sizzle/electronic voice problem

### ISSUE THREAD

**Issue by turtleCombat** [AudioKit/AudioKit#2192]
Hi,

After the audio recording, recorded file has a noise like an electronic voice. I assume, I am doing everything right.

iPhone X - 13.5.1

       
        AKAudioFile.cleanTempDirectory()
        AKSettings.bufferLength = .medium
        AKSettings.setSession(category: .playAndRecord, with: .allowBluetoothA2DP)
        AKSettings.defaultToSpeaker = true
        AKSettings.playbackWhileMuted = true
        AKSettings.channelCount = 1
        AKSettings.sampleRate = 44100

        micMixer = AKMixer(mic)
        micBooster = AKBooster(micMixer)
        micBooster.gain = 1

        recorder = AKNodeRecorder(node: micMixer)
        player = AKPlayer(audioFile: file)
       
        moogLadder = AKMoogLadder(player)
        moogLadder.resonance = 0
        moogLadder.cutoffFrequency = 1991

        mainMixer = AKMixer(moogLadder, micBooster)

        AudioKit.output = mainMixer

[Example audio](https://drive.google.com/file/d/1ZWk-rdOAASvu7LrhPzvzbISRoCkGp9G_/view?usp=sharing)

**Comment by aure** [comment]
This is less to do with the code which I think is fine and probably the hardware. What phone are you using? Are you using a bluetooth mic? If you could provide that info and set up an example project demonstrating it, I'll be happy to investigate further.
