### ISSUE TITLE
Recording AKMicrophone creates feedback squeal on iOS 14

### ISSUE THREAD

**Issue by colinhumber** [AudioKit/AudioKit#2198]
Using 5.0.b1 (latest), recording an `AKMicrophone` causes an immediate squealing noise when the `AKManager` starts. I tested the same code using 4.10.1 (and `AudioKit.output`/`AudioKit.start()`) on iOS 14 and the same issues exist. I've created a very basic recording setup to remove any additional nodes that might be causing the issue. The 

```
class ViewController: UIViewController {
    lazy var mic = AKMicrophone(with: nil)
    var recorder: AKNodeRecorder?

    override func viewDidLoad() {
        super.viewDidLoad()

        do {
            recorder = try AKNodeRecorder(node: mic)

            AKManager.output = mic
            try AKManager.start()
        }
        catch {
            print(error)
        }
    }
}
```

Calling `try AKManager.start()` will cause the squeal to start. I assume this is due to some change in `AVFoundation` or `AudioToolbox` so I'm not sure if this is something that will fix itself or requires internal changes. This has occurred in beta 1, 2, and 3 thus far.

**Comment by aure** [comment]
I actually don't see why this wouldn't squeal on any version of AudioKit or any iOS. You're telling it to output to the speaker everything that ix coming into the microphone. The microphone then picks up that sound and you get a feedback loop. What am I missing?

**Comment by colinhumber** [comment]
You're right, I was just writing a quick contrived example. I guess I'm just confused as our audio recorder we've using works correctly on iOS 13 and lower. When we switched to 5.0.b1 to get it working with Xcode 12 and iOS 14, the same code that worked before is suddenly causing the squealing.

**Comment by colinhumber** [comment]
@aure I'm also a little confused, as the examples I've seen have the microphone being added to an `AKNodeRecorder` to record and also the microphone being added to an `AKBooster` with a gain of 0, and that booster being set as the output. The example below outlines this and it causes the squeal as well when using 5.0.b1 compiled on Xcode 12 running on iOS 14.

https://audiokit.io/examples/RecorderDemo/

Here was my setup based on the example above:

```
class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        AKSettings.bufferLength = .medium

        do {
            try AKSettings.setSession(category: .playAndRecord, with: .allowBluetoothA2DP)
        } catch {
            AKLog("Could not set session category.")
        }

        AKSettings.defaultToSpeaker = true

        let mic = AKMicrophone()
        let micMixer = AKMixer(mic)
        let micBooster = AKBooster(micMixer)
        micBooster.gain = 0

        let mainMixer = AKMixer(micBooster)

        AKManager.output = mainMixer
        try! AKManager.start()
    }
}
```

Using Xcode 12, when this is run on iOS 12/13 there is no squeal. However, when run on iOS 14, the squeal occurs. I'm not sure if I'm missing something, as I'm testing this with the example from developer site (minus the player).

**Comment by colinhumber** [comment]
After playing around with this a bit more, and looking at the full example here (https://github.com/AudioKit/AudioKit/tree/master/Examples/iOS/Recorder), it looks like on <= iOS 13, the nodes don't have to be assigned to a property. Running the code above on iOS 14, and setting up the nodes but not assigning them to properties would cause the squeal. Assigning them to properties, however, would remove the squeal.

**Comment by aure** [comment]
Huh, this is fascinating, I would never expect a squeal with the booster set up with gain of zero.

**Comment by aure** [comment]
The change you've made is good practice anyway, so I think you're good to go, but yeah, hopefully someone finds this issue if they encounter the same thing. Thanks for doing the sleuthing to figure it out!

**Comment by colinhumber** [comment]
For sure! Thanks for the examples! I probably wouldn't have figured it out without a working example to compare against.

**Comment by bfwg** [comment]
Encountering the same problem with AudioKit 5.0.b1 (latest) and iOS 13.7 and iOS 14.0. Tried @colinhumber 's solution but no luck.

**Comment by aure** [comment]
5.0b1 is not the latest by any means. v5-develop is far ahead of that.

**Comment by bfwg** [comment]
Thanks, for the quick reply. Is there a way to install v5-develop from cocoapods?

**Comment by aure** [comment]
no, use SPM.

**Comment by ppamorim** [comment]
@ColinEberhardt Any idea of what I can to stop this bug?

**Comment by colinhumber** [comment]
@ppamorim I'm not sure, unfortunately. We're still using v4.
