### ISSUE TITLE
Workflow: macOSTestSuite requires clean rebuilds for any changes to AudioKit

### ISSUE THREAD

**Issue by wtholliday** [AudioKit/AudioKit#2206]
To reproduce:

1. Open macOSTestSuiteForDev/macOSTestSuite.xcodeproj
1. Build and run tests (cmd-U)
1. Observe: tests pass
1. add call to abort() in `AKOscillatorDSP::process`
1. Run tests (cmd-U)
1. Observe: tests pass

🤬

**Comment by aure** [comment]
fwiw, the iOSTestSuite does not do this, so perhaps that is a clue.

**Comment by aure** [comment]
Can this be closed if it is not happening with AK5?

**Comment by wtholliday** [comment]
Closing since AK5 will use xcodegen.
