### ISSUE TITLE
AKSequencerTrack results depend on AU execution order

### ISSUE THREAD

**Issue by wtholliday** [AudioKit/AudioKit#2209]
To reproduce:

1. In `AKSequencerTrackTests.testBasicSequence` change `AKMixer(synth, seq)` to `AKMixer(seq, synth)`
1. Run test
1. Observe: test fails

It would seem that instead of needing to be hooked up to a mixer, the sequencer should use pre-rendering hooks to send MIDI to an AU (like parameter automation does).

**Comment by aure** [comment]
I suppose this will be fixed (by the poster) soon, but in the mean time, or if this issue shows up in a search, our convention is to always have a mixer at the end of the signal chain, and we would attach the sequencer at the bottom. It should then receive the first pull of samples through it. I'm not saying this is good, just saying its how we've done it, and how if a person is using AK4.x should set it up.

**Comment by wtholliday** [comment]
Fixed by #2214
