### ISSUE TITLE
AKSequencerEngineDSP won't correctly schedule notes that are within a single render cycle

### ISSUE THREAD

**Issue by wtholliday** [AudioKit/AudioKit#2213]
If a note is entirely within the render cycle, a note-off won't be generated until the next render cycle. This could result in inaccurate playback when rendering with large buffer sizes (such as when doing offline rendering).

This bug occurs because in a given render cycle, notes-offs are checked before note-ons.

**Comment by aure** [comment]
I'll consider this addressed on v5-develop
