### ISSUE TITLE
AKOscillatorBank nuked?

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/AudioKit#2223]
I was using AKOscillatorBank in my app. I just tried to move to V5 develop and realized that it's gone!
(v5 beta 1 had it though)...
What can I use in it's absence?

Aloha

**Comment by aure** [comment]
You shouldn't be using V5 develop, things are fluctuating too much. Try AKSynth perhaps. Or, if you want to rewrite AKOscillatorBank feel free. I have removed the banks, for now at least, because they were very old cold that needs to be rewritten to AK5's standards.

**Comment by quantamrhino** [comment]
I see. 
I'll stick to 4.10 -- will 4.x be supported later, or be killed after 5.0 is released? 
That way I can plan for eventual death of my app at a certain point in time.

**Comment by aure** [comment]
I don't know the future. But my prediction is that v4 will exist for quite some time while v5 proves itself. The banks are useful and will likely return in some way shape or form.

**Comment by aure** [comment]
This question of "support" by the way is something worth addressing. AudioKit is free and open-source and we don't promise support for any version per se. That being said, we use AudioKit in our own projects, so things are likely to get addressed and we're appreciative of bug reports.
