### ISSUE TITLE
AKMicrophone + AKFrequencyTracker + AKBooster Not working on IPhone 11

### ISSUE THREAD

**Issue by 432player** [AudioKit/AudioKit#2232]
The following code doesn't work on IPhone 11 I have no idea why but only on iPhone 11 and IPhone 11 Pro this isn't working.
PLEASE HELP!

This issue has been going own for about half a year perhaps more and I was hoping a new version would come out to fix this issue, but updated to the latest version but still not working.

On all other devices it works perfectly but not on iPhone 11 and Pro.

Here is the code that initializes the whole tuner:

        AKSettings.audioInputEnabled = true

        microphone = AKMicrophone()!
        
        tracker = AKFrequencyTracker.init(microphone)
        
        silence = AKBooster(tracker, gain: 0)
        
        AudioKit.output = silence
Please help, here is my email contact@appums.com

Thank you for this wonderful framework, hope this can be solved for iPhone 11 and up

**Comment by aure** [comment]
If it is urgent and you would want to hire me or another person on the AudioKit team to address this, that could be arranged. I don't actually have an iPhone 11 to test on, so that would be the first expense. At very least, maybe sponsor the project and update this with the actual errors that happen or if it just doesn't do anything, ie. expand on "the following code doesn't work" :) I'll close the issue until further information is provided.

**Comment by 432player** [comment]
Dear Aurelius, thanks for getting back to me.
Not sure of this issue actually requires a sponsorship or not but very soon this issue will be mandatory in all IPhones above X.
And that future is not too far away.
I believe the issue is similar to what this guy wrote over here https://stackoverflow.com/questions/60263429/audiokit-how-record-iphone-11-microphone-with-akcliprecorder-crashed
But I can't be 100% sure.
I'm getting the following error:
[AVAudioEngineGraph.mm:1397:Initialize: (err = AUGraphParser::InitializeActiveNodesInInputChain(ThisGraph, *GetInputNode())): error -10868
The operation couldn’t be completed. (com.apple.coreaudio.avfaudio error -10868.)

If you have any ideas that would be amazing. I wish you could get your hands on someones (a friend or family) iphone 11 and see if the AudioKit works on the iphone 11. I have a strong feeling that it wont, and if it does than perhaps the issue is only in the Microphone recording region or something, could be because a different sampling rate I have no idea.

I don't have much to do, I'd gladly pay a symbolic $200 if someone can upload a fix for this issue.
Much blessings :)

**Comment by aure** [comment]
Hi there, we just obsoleted AKFrequencyTracker in favor of AKPitchTap. Can you try to use that instead? Its on the v5-develop brach. The MicrophoneAnalysis examples on that branch have been updated to reflect the new tap.

**Comment by 432player** [comment]
That actually worked... Thank you
I'm working with the v5-develop version and seems that it's working fine.
I can only hope that it's good enough for production

Thanks again

**Comment by aure** [comment]
v5-develop is not ready for production, but you can test your app to see if it does what it needs to do for your app correctly. Its on you :)
