### ISSUE TITLE
AudioKit support record video?

### ISSUE THREAD

**Issue by nguyentrai2011** [AudioKit/AudioKit#2233]
Hi team,

I tried to use AudioKit to record microphone with AKMicrophone. It's good but now I would like to extend record camera also. I search around your document but don't find any information about this.

So my question: Is AudioKit support record video? If not, will your team plan to support this feature?

My additional question: is AKPlayer/AudioKit can play video file?

Thanks.

**Comment by aure** [comment]
We don't have plans to make it a VideoKit.
