### ISSUE TITLE
BufferedAudioUnit Support for Mono In, Stereo Out

### ISSUE THREAD

**Issue by b3ll** [AudioKit/AudioKit#2239]
I'm currently implementing an audio unit that can take a mono signal and turn it into a stereo one (or take a stereo one and alter it for another stereo signal), and it's built atop `AKAudioUnitBase`.

Everything works, except `BufferedAudioUnit` will immediately bail / fail if the input format doesn't match the output format. This in-turn causes `AKAudioUnitBase` to bail, etc. which breaks plugin validation / other things for me.

```objc
AVAudioFormat *format = _outputBusArray[0].format;
if (_inputBusArray != NULL && [_inputBusArray[0].format isEqual:format] == false) {
    if (outError) {
        *outError = [NSError errorWithDomain:NSOSStatusErrorDomain code:kAudioUnitErr_FormatNotSupported userInfo:nil];
    }
    NSLog(@"%@ input format must match output format", self.class);
    self.renderResourcesAllocated = NO;
    return NO;
}
```

Commenting all of this out ends up fixing things, but that seems like a total hack. Would it make more sense to change this to check the format but ignore the channel configuration (or at least subclasses opt for a way to setup their input / output busses manually?).

**Comment by aure** [comment]
As of right now, AudioKit is pretty heavily entrenched in the notion of 44.1K sample rate and 2 channels. I'm not sure of the right way to generalize this. I guess I would treat it internally as a node in which one side is neglected. We're going through big changes for AK5 and I feel like this can only be addressed after the dust has settled, so please allow me to close the issue for now. Use your solution and possibly bring it back up early next year or so?

**Comment by b3ll** [comment]
Fair enough! Thanks so much @aure! I may see if I can do a PR to allow for the ability to opt out or something, or i'll just continue using the fork I have.
