### ISSUE TITLE
AKSettings.enableRouteChangeNotifications removed from macOS API

### ISSUE THREAD

**Issue by btfranklin** [AudioKit/AudioKit#2246]
I've been using AudioKit 4.9.5 with AKSettings.enableRouteChangeNotifications set to true (which I realize is the default). Upon updating to 4.10.1, I got a compile-time error saying that AKSettings.enableRouteChangeNotifications does not exist.

Looking into the source code of AKSettings, it appears that this has been wrapped in an #if that only creates it for iOS.

I feel that this might be a bug, since route change handling is certainly not only an iOS concept. At any rate, I would like to be able to control route change handling on macOS, and I'm not sure what the expected behavior is without this setting.

Thank you!

**Comment by aure** [comment]
I am under the impression that macOS does not do the same kind of route change notifications as iOS.

**Comment by aure** [comment]
It looks like this is in beta for the upcoming macOS release, so I believe it is set up right to have it not on macOS as of yet: https://developer.apple.com/documentation/avfoundation/avaudiosession/1616493-routechangenotification
