### ISSUE TITLE
swift + cocoapod

### ISSUE THREAD

**Issue by ys1382** [audiokit/AudioKit#225]
For a Swift OSX project that installs AudioKit via CocoaPods, what additional steps are needed to run? I've tried all the steps in INSTALL-OSX.md, and none of them, and I always get:

dyld: Library not loaded: CsoundLib
  Referenced from: /Users/xyz/Library/Developer/Xcode/DerivedData/story-ftxkjqthkgxxqbhkgiizafqfffso/Build/Products/Debug/story
  Reason: image not found

I noticed that this: http://audiokit.io/downloads/ says "If you are creating an iOS project using Objective-C, you can use CocoaPods to install AudioKit." Does that mean Swift+OSX projects can't use CocoaPods for AudioKit?

FWIW, I'm using Xcode version 7b5, pod version 0.37.2.

**Comment by megastep** [comment]
The main thing I think CocoaPods doesn't do is configure the run script phase in your project, which is needed for OS X. The INSTALL file for OS X explains how to do this manually. If you don't do it, then you'll get these kinds of errors as your binary won't be able to locate the embedded framework.

I don't think that the language matters here, you just have to make sure to configure you run script phase. We have some changes slated for Xcode 7 (most notably Swift 2 support and an accompanying AudioKit framework), but this should work right now.

**Comment by aure** [comment]
I'm going to close this for now, but feel free to continue the conversation or re-open the issue as needed.

**Comment by ys1382** [comment]
I followed your instructions, but get the same error.

The Pods directory did not have AudioKit/Platforms/OSX/run-script.sh, so I had to download the AudioKit source and copy run-script.sh into my project's Pods directory.

Then I added the build phase that calls that script, but I still get the same error: dyld: Library not loaded: @executable_path/../Frameworks/CsoundLib.framework/Versions/6.0/CsoundLib

You can get the code and see for yourself here: https://www.dropbox.com/sh/043m1te0lvio9az/AADuBKStDCkWK7i6dxcXlAa-a?dl=0

**Comment by aure** [comment]
I can take your code and make a working project out of it without using CocoaPods if that is okay with you.

**Comment by alpadedhia** [comment]
Run script worked for me once. But ever since then it is giving me this image not loaded error. I am using XCode 7
