### ISSUE TITLE
Closing MIDI Inputs does not work

### ISSUE THREAD

**Issue by aure** [AudioKit/AudioKit#2251]
AKMIDI().closeInput(midiInput.name) is having no effect on midi inputs.

AKMIDI().closeAllInputs() also doesn't close MIDI ports.

**Comment by emurray2** [comment]
I'll look into this. It doesn't work on any of the platforms since it's in the Core part of AudioKit? Also, should I use `v5-develop` and Xcode beta to test this?

**Comment by aure** [comment]
v5-develop and Xcode 11 or 12 - shouldn't matter.

**Comment by emurray2** [comment]
Ok sounds good.
