### ISSUE TITLE
MidiOff omitted in case of MidiOn with veloctiy == 0

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#2252]
We just identified an issue while upgrading audiokit. (from 4.5.6 to 4.10.1).

We see that incoming midi on messages with `velocity == 0` land in the midi on callback. 

```
    public func receivedMIDINoteOn(noteNumber: MIDINoteNumber,
                                   velocity: MIDIVelocity,
                                   channel: MIDIChannel,
                                   portID: MIDIUniqueID? = nil,
                                   offset: MIDITimeStamp = 0) 
```
Was this specific case handles by audiokit before? (I would assume so, as this bug was introduced with only upgrading audiokit)

**Comment by aure** [comment]
In which class? Its not possible for us to do this in general, but certain classes could handle that.

**Comment by aure** [comment]
I have just made a change to the v5 in which I have deleted the protocol extensions that implement default behavior to ensure the AKMIDIListener protocol is strictly adhered to.  I'm not going to make that change in v4 but you can look at what I did in https://github.com/AudioKit/AudioKit/commit/95d52e7011d655276a0fe0f0ebcba13daa53a787

Also, do a search for velocity > 0 and see if the code isn't being hit by your implementation:
![image](https://user-images.githubusercontent.com/13122/92508954-4c099c80-f1be-11ea-8192-507aeeceb360.png)

Let me know if this helps, closing the issue for now, to keep the issues list tidy, but I'd like to follow up with you here to make sure we address this.
