### ISSUE TITLE
AudioKit 5 and Xcode 12 beta 6 Build Errors

### ISSUE THREAD

**Issue by Juan-GH** [AudioKit/AudioKit#2253]
I'm trying to build a project using AudioKit 5 (master branch) XCFrameworks in XCode 12 beta 6 for iOS 14 and I'm getting 1 warning and 2 errors:

Warning:
Could not find or use auto-linked library 'swiftAVFoundation'

Error 1:
Undefined symbol: _swiftoverride_class_getSuperclass(swift::TargetMetadataswift::InProcess const*)

Error 2:
Undefined symbol: swift::swift51override_conformsToSwiftProtocol(swift::TargetMetadataswift::InProcess const*, swift::TargetProtocolDescriptorswift::InProcess const*, llvm::StringRef, swift::TargetProtocolConformanceDescriptorswift::InProcess const* ()(swift::TargetMetadataswift::InProcess const, swift::TargetProtocolDescriptorswift::InProcess const*, llvm::StringRef))

Any ideas why this might be happening? Note: The exact same project works fine in XCode 11 when building for iOS 13.7.

**Comment by aure** [comment]
I don't know but v5 is not ready for issues like this especially with Xcode betas. That's like double beta.  I do know that v5-develop works on xcode12 so maybe try that.
