### ISSUE TITLE
5.0.b2 with Xcode 12 beta 6: Cannot compile

### ISSUE THREAD

**Issue by colinhumber** [AudioKit/AudioKit#2254]
I know things are still in flux, so this is more of a general question than anything. I updated to 5.0.b2 but am running into some compile errors. Should we still be using 5.0.b1 with Xcode 12?

![image](https://user-images.githubusercontent.com/104855/92747634-a1ba8200-f341-11ea-996f-066a1b1d58f9.png)

`AudioRecorder` is the name of the project that is pulling in 5.0.b2 via Cocoapods.

**Comment by colinhumber** [comment]
As an aside, I created a brand new project and just installed AudioKit 5.0.b2 directly and get this error instead:

![Uploading image.png…]()

**Comment by aure** [comment]
You should switch to SPM and use the v5-develop branch if you really want to live on the edge like this.

**Comment by colinhumber** [comment]
I don't really want to live on the edge, but unfortunately I need 5.0 to build our iOS 14-compatible version, and we have a pod that has AudioKit as a dependency. I'm just trying to track down if this is an issue on our end, a Cocoapods 1.10.beta.2 issue with xcframeworks or what.

**Comment by colinhumber** [comment]
Specifically, I can build 5.0.b1 for the device without any issues, but it won't compile for the simulator. I thought this might be working with b2, but to no avail.

**Comment by sammarks** [comment]
@colinhumber did you end up finding a solution to this error?

```
ld: in /Users/colin/Library/Developer/Xcode/DerivedData/XCFrameworkIssue-cyilldwqeodeukafogaaytbsbopd/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/CAudioKit/CAudioKit.framework/CAudioKit(EZAudioFFT.o), building for iOS, but linking in object file (/Users/colin/Library/Developer/Xcode/DerivedData/XCFrameworkIssue-cyilldwqeodeukafogaaytbsbopd/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/CAudioKit/CAudioKit.framework/CAudioKit(EZAudioFFT.o)) built for Mac Catalyst, file '/Users/colin/Library/Developer/Xcode/DerivedData/XCFrameworkIssue-cyilldwqeodeukafogaaytbsbopd/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/CAudioKit/CAudioKit.framework/CAudioKit' for architecture arm64
```

I'm running into the same thing in my project currently after updating to XCode 12 GM.

**Comment by colinhumber** [comment]
@sammarks I actually ended up using 4.11.2 which supports Xcode 12 and XCFrameworks. I was more comfortable using a released version that did what we needed.

**Comment by sammarks** [comment]
Interesting because that's the error I'm getting when using 4.11.2 currently :/ - I've seen that perhaps it might have to do with the way the release was packaged, so currently trying 4.11.1 to see if that does the trick.
