### ISSUE TITLE
akbluetoothmidibutton stopped working in current release

### ISSUE THREAD

**Issue by MaartenWL** [AudioKit/AudioKit#2256]
For a long time I have implemented the akbluetoothmidibutton in my app. 
Now after upgrading audiokit to the current release, the popup for selecting bluetoothmidi is not showing up anymore.

In my storyboard I have a UIButton, with custom class AKBluetoothMIDIButton assigned to it.
This has worked fine so far, until now. I do not see any log or error message in the console.

What can or should I try to debug this?

**Comment by aure** [comment]
I also had some weirdness around that button, but I am also working in SwiftUI only now, so I attributed it to that. If you can share the private, even privately, I can have a look. Or do a quick screenshare.

**Comment by MaartenWL** [comment]
Hi!

My code is on Bitbucket, to provide you access I need your e-mailadres.

It's about the blue text button here:

<img width="650" alt="Schermafbeelding 2020-09-12 om 13 15 13" src="https://user-images.githubusercontent.com/8521650/92994415-50a1be00-f4fa-11ea-9d02-4245eab70752.png">


In storyboard it looks like this:

![Schermafbeelding 2020-09-12 om 13 01 24](https://user-images.githubusercontent.com/8521650/92994418-526b8180-f4fa-11ea-85a3-ace5504d92f3.png)


I have changed the way my app deals with different iPad sizes, because until now I used the launchscreen storyboard which made my app scale automatically on all iPad sizes. This is no longer allowed by Apple, and I had to set all views in my storyboard manually to make them scale correct. I did this for all views as shown in the next screenshot. This makes me wonder: could it be some placement issue. In other words: could the menu be somewhere out of screen? 

![Schermafbeelding 2020-09-12 om 13 10 06](https://user-images.githubusercontent.com/8521650/92994414-4ed7fa80-f4fa-11ea-941c-a2d30a2c5bb2.png)

**Comment by aure** [comment]
I have a few email address but I think the one for bit bucket is aure at audiokitpro dot com

**Comment by aure** [comment]
I think it could be that you'll need to run the button.centerPopuIn(view: UIView) command now, to tell your app where you want the pop up to appear. Let me know if that doesn't fix and also invite me to the repo then.

**Comment by aure** [comment]
Did that fix it? I just noticed your invitation to Bitbucket just now, but it had already expired.

**Comment by MaartenWL** [comment]
Hi!

Yes it did work. Sorry for this, I should have found out myself. 
Thanks for your help, and also for the wonderfull Audiokit.
I use audiokits MIDI functionality. Without it I would not have been able to build my app.
The good old MIDI is surprisingly complex when you have to code it.

Thanks!!

Regards,
Maarten
