### ISSUE TITLE
V5 - AKSampler will not stop sounding and keep repeating the note indefinitely.

### ISSUE THREAD

**Issue by impmaarten** [AudioKit/AudioKit#2257]
We had to migrate our usage of AudioKit from version 4 to version 5 due compile issues with Xcode 12 (iOS 14), which will be the new standard in a couple weeks and will be the only version allowed to publish apps to the app store.

With this version 5 we have the problem that the note/sound **never** stop sounding and being **repeated** really fast. 

I've tried the CocoaPods version of version 5 and the development and master branch of audiokit of version 5, with all the same result as described above.

The only interaction we are doing with the AKSampler are the following:

`AKSampler.releaseDuration`
`AKSampler.masterVolume`
`AKSampler.loadSFZ(path:fileName:)`
`AKSampler.play(noteNumber:velocity:)` <-- called when the user touches a button
`AKSampler.stop(noteNumber:)` <-- called when the user no longer touches a button "releases"

**AKSampler Settings**
```
attackDuration: 0.0
holdDuration: 0.0
decayDuration: 0.0
sustainLevel: 1.0
releaseHoldDuration: 0.0
releaseDuration: 0.8
```

Could this issue be looked after, since we are quite reliant upon the usage of AudioKit in our app and it will become a big impediment once iOS 14 is released. Otherwise version 4 should be made compatible with Xcode 12, if there are plans for that it would be appreciated to be aware of it.

**Linked Issue**
https://github.com/AudioKit/AudioKit/issues/2136

**Comment by aure** [comment]
Yeah, that's on my radar, and I can have a look at it over the next few days.

**Comment by aure** [comment]
Do you think you could create a bare bones project showing the issue or share your code with me? It would just be easier and quicker for me to work on a project.
