### ISSUE TITLE
Parametric Equalizer (AKParametricEQ & AKStereoAudio) in current version

### ISSUE THREAD

**Issue by ioanalexme** [AudioKit/AudioKit#2258]
Hello guys,
In your documentation and playgrounds there is a reference to AKParametricEQ filter, but unfortunately it seems that this implementation is gone now. Can you tell me how AKParametricEQ is called in the most recent version of the framework?

Also, the same question for AKStereoAudio. It seems like `AKStereoAudio(leftAudio: microphone, rightAudio: microphone)` cannot be used anymore. How AKStereoAudio is called (or functionality) in the most recent version of the framework?

Thank you guys!

**Comment by aure** [comment]
Depends on what you mean by the most recent version.  I am working on v5 but its not yet released. In v5 the parametric eq is back: https://github.com/AudioKit/AudioKit/blob/v5-develop/Sources/AudioKit/Nodes/Effects/Filters/AKParametricEQ.swift

Also in v5 the AKStereoInput (not Audio) is gone.
