### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by zhs2472** [audiokit/AudioKit#226]
![image](https://cloud.githubusercontent.com/assets/6290153/9698926/862c73ae-53ff-11e5-9708-a67b9bf68b88.png)

I am using Xcode 6.4 (6E35b). And I use AudioKit as dynamic framework according to the installation steps and screencasts. 
Please help me. Thanks a lot.

**Comment by aure** [comment]
We'd like to help you but you haven't given us much information to go on.  There's nothing in the screenshot that helps either.  Provide more information and we'll look again.

**Comment by megastep** [comment]
This does look like a problem with the compiler itself though (clang).

**Comment by zhs2472** [comment]
But there is no more information. What should I do? This issue occurs after I run the playground's install.sh and run.sh. And I can not run any xcode project now:(

**Comment by aure** [comment]
That sucks.  The problem is with The dynamic code injection, not necessarily AudioKit, but necessary for the playgrounds.  Sometimes, and I am not sure when or how, it seems to mess up Xcode badly, and reinstalling Xcode is the only option.  Other times, it works perfectly.

**Comment by megastep** [comment]
Yeah unfortunately you should try to reinstall Xcode from the App Store from scratch and see if it helps.

**Comment by zhs2472** [comment]
OK. I will reinstall Xcode and try again later. Thanks for help.
