### ISSUE TITLE
Setting AKMicrophone device changes the entire system output

### ISSUE THREAD

**Issue by ioanalexme** [AudioKit/AudioKit#2260]
Hello guys,

I don't know if this is a bug or a designed feature, but on macOS setting the device of an AKMicrophone also changes the system wide input.

```
let microphone = AKMicrophone()
let microphoneDevice = AudioKit.inputDevices!.first(where: { $0.name == "My Microphone" })!
try? microphoneAudioNode.setDevice(microphoneDevice)
```

Result: the microphone is initiated correctly, but macOS also changes the microphone to "My Microphone'
Is there any solution for this? To create an AKMicrophone input with a custom microphone?

Thank you

**Comment by aure** [comment]
I believe this is better described in this open issue: https://github.com/AudioKit/AudioKit/issues/2130 so I will close it here for now. It is on our radar.

**Comment by ioanalexme** [comment]
I see.. the same question for output.
Is it possible to set the output without changing the system wide settings? 

```
let outputDevice = AudioKit.outputDevices!.first(where: { $0.name == "Other Speakers" })!
try? AudioKit.setOutputDevice(outputDevice) 
```

Thanks
