### ISSUE TITLE
AudioKit/AVAudioEngine output to another speaker

### ISSUE THREAD

**Issue by ioanalexme** [AudioKit/AudioKit#2263]
Hello guys,

For a couple of days a problem is driving me crazy.
Is it possible for AudioKit (or AVAudioEngine) to output sound (let's say from a microphone or audio file) and play it on a speaker that is not the system default speaker?
For example, if I record from "Microphone 1" (any microphone, system default or not) and my system default speaker is "Speaker 1", can I output the sound I record to "Speaker 2", but without changing the default speaker of the computer?

I've seen that some music player can do that. For example, Elmedia Player can set the output speaker without changing the default system speaker.

Thank you

**Comment by ioanalexme** [comment]
By the way, here is what I have now

`try? AudioKit.setInputDevice(device) // where device is a Loopback Audio with 2 ins and 2 outs`
when I call

`print("Out device: \(AudioKit.outputDevice!.name). In device: \(AudioKit.inputDevice!.name)")`
I receive `Out device: Loopback Audio. In device: Loopback Audio` and this is good.
Also, my default system speaker is Loopback Audio.

The question is if i can output sound to another speaker, for example the built in physical speakers, without changing the default system ones?

**Comment by aure** [comment]
I think is basically the same issue as: https://github.com/AudioKit/AudioKit/issues/2130
