### ISSUE TITLE
V5 - minimal supported iOS version

### ISSUE THREAD

**Issue by impmaarten** [AudioKit/AudioKit#2266]
We have a question about the minimal supported iOS version of Audiokit version 5, which is currently iOS 12.

We recently had to migrate from version 4 to 5 in order to compile our app with Xcode 12 in preparation for iOS 14. But this does mean that our app has drop support for users from iOS 9 to 11.

After some investigation in the branch `v5-develop` we noticed it could compile for iOS 11. Are there any reason why it is currently iOS 12 and what will be the long term goal for the minimal iOS support of v5?

Thanks in advance.

**Comment by aure** [comment]
Pretty sure we can put it back at 11, probably not before that however.

**Comment by aure** [comment]
We will probably be supporting only iOS13 with AK5, but there is a version of AK 4.11 that should work on Xcode 12 (compiles for us), and that will go all the way back to iOS11.

**Comment by megastep** [comment]
Right now AK5 does build on iOS 11 though.

**Comment by aure** [comment]
Yeah, there will be some stuff that will not be available to iOS11 and 12 though.
