### ISSUE TITLE
Xcode 12 + AudioKit 4.11 Problems

### ISSUE THREAD

**Issue by vojtabohm** [AudioKit/AudioKit#2267]
Hi. I just wanted to ask if there is a planned support for v4 of AudioKit in Xcode 12? Or if there is a documentation for the v5 beta version which works in Xcode 12. 

I cannot compile my app in Xcode 12 and hence cannot prepare it for the iOS 14 which is now already released. I have went into detail in this stackoverflow post.
https://stackoverflow.com/questions/63860545/implementing-microphone-analysis-with-audiokit-v5

Thank you.

**Comment by aure** [comment]
Yeah, well I just compiled AudioKit for Xcode 12, it was easy, but as long as @megastep is cool with it, we'll make an AudioKit 4.11 release for Xcode 12 shortly.

**Comment by aure** [comment]
https://github.com/AudioKit/AudioKit/releases/tag/v4.11 will be updated with frameworks etc soon, and hopefully cocoapods as well.

**Comment by fvonk** [comment]
Hi, we have multiple errors:
for instance:
"Failed to build module 'AudioKit' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced"

Using last version:
  - AudioKit (4.11):
    - AudioKit/Core (= 4.11)
    - AudioKit/UI (= 4.11)
  - AudioKit/Core (4.11)
  - AudioKit/UI (4.11):
    - AudioKit/Core

**Comment by megastep** [comment]
Mmh, I did remove a bit of script that I thought was no longer needed, fixing the Swift module interfaces. I might have to turn that back on...

**Comment by megastep** [comment]
OK, I just updated the zip file. Please clean your pod cache and try again with a clean install...

**Comment by ryangenz** [comment]
How does one know if they are installing the New 4.11 or the Old 4.11 ?
I just updated but I seem to be getting the same errors mentioned by fvonk. Which makes me think I didn't _really_ update the pod. ;)

**Comment by megastep** [comment]
I would do `pod cache clean --all`, then just delete your Pods directory and do a new `pod install`

**Comment by fvonk** [comment]
Ok, but now we have
"Cannot find 'output' in scope"
"Cannot find 'midi' in scope"
errors...

**Comment by ryangenz** [comment]
Yes same errors here

**Comment by brizzly** [comment]
Same erreur here

**Comment by trevor-sonic** [comment]
I should have check here before jump into the Xcode 12 :-/ (my mistake).

**Comment by vojtabohm** [comment]
Yes, I can also confirm I have the same errors. On the bright side - before the updates I had 2567 errors and now I only have 6 of them 😄 
<img width="244" alt="image" src="https://user-images.githubusercontent.com/24317956/93536907-6ffd7880-f94a-11ea-91b9-e149a3fb8ced.png">

**Comment by meilers** [comment]
Thanks for the updated builds @aure. However, I'm running into this issue when archiving my app (see screenshot). Any ideas? I used the 4.11 framework from the link https://github.com/AudioKit/AudioKit/releases/tag/v4.11
![Screen Shot 2020-09-17 at 9 17 26 PM](https://user-images.githubusercontent.com/2792041/93544292-b7c0d780-f92b-11ea-9435-f2cf2126e37e.png)
.

**Comment by megastep** [comment]
@meilers are you on Xcode 11 still? These new frameworks include ARM64 slices for the simulator for the new Macs with Apple Silicon. I thought these would be simply ignored by previous versions.

**Comment by meilers** [comment]
@megastep Nope. On Xcode 12 since yesterday.

**Comment by megastep** [comment]
uh, that is odd - is it only happening when archiving your app?

**Comment by meilers** [comment]
@megastep Correct. I can run the app just fine in the simulator.

**Comment by megastep** [comment]
Maybe that's a limitation because you can't submit apps for Apple Silicon yet? Did you override any architecture settings in your project/target?

It makes little sense to me because this is an XCFramework and when you archive for a device the simulator stuff should just be completely ignored.

**Comment by meilers** [comment]
@megastep I agree it is weird. What do the simulators have to do with archives? And no, I didn't override any architecture settings. It's a pretty vanilla project. Let me try with a new project and I'll let you know.

**Comment by megastep** [comment]
One of the biggest problems with publishing universal binary frameworks with Xcode 12 is because of this Apple Silicon slice - so you end up having arm64 slices for both the iOS and Mac architectures. Pretty much have to rely only on XCFrameworks at this point as we can't splice together these same-CPU slices anymore.

At the same time AK4 was triggering some bugs in LLVM because of the AudioKit class, and it appears that is still the case. That doesn't necessarily mean that we can't ship functioning frameworks for CocoaPods here, but it might take more work than anticipated.

If you can't wait you can checkout the `v5-develop` branch which fully supports the Swift Package Manager.

**Comment by meilers** [comment]
@megastep Thanks for the clarification. That makes sense.

By the way, just tested on a brand new project. Dumped the frameworks from the previous link. and same error when archiving.

![Screen Shot 2020-09-17 at 10 14 56 PM](https://user-images.githubusercontent.com/2792041/93547608-72080d00-f933-11ea-94aa-d4664c087545.png)

**Comment by meilers** [comment]
@megastep Are you sure that SPM works for AudioKitUI? It works for AudioKit, but not for AudioKitUI. I'm getting the "No such module AudioKitUI" error.

**Comment by aure** [comment]
@meilers No more AudioKitUI in AudioKit5.

**Comment by aure** [comment]
Mostly its in there, just don't have to import a separate framework anymore.

**Comment by meilers** [comment]
@aure Not sure I understand. If I remove "import AudioKitUI" I get plenty more reference errors like "Cannot find type AKNodeOutputPlot in scope". Am I missing something here?

**Comment by aure** [comment]
@meilers are you saying that you're using SPM with AudioKit 4.11? I was under the impression it only worked with v5. @megastep ?

**Comment by aure** [comment]
@meilers If you are using v5, try dropping the AK prefix on the classes it says it can't find. Most of those have been dropped, except a few like AKMIDI.

**Comment by meilers** [comment]
@aure Yes, I should be. I'm pointing to the v5-develop branch.

**Comment by meilers** [comment]
@aure Dropping the AK prefix did the trick. Thanks!

**Comment by aure** [comment]
@meilers Don't rely on anything about v5 remaining very stable. Its still in a bit of a state of flux. Making great progress, but really not ready for people to be relying on it. Proceed with caution and don't expect many answers from us along the way. :)

**Comment by meilers** [comment]
@aure @megastep Yeah I think I'm gonna have to wait for that Xcode 12 Cocoapods fix then, and stick to AudioKit 4. Thanks for all your support.

**Comment by corentingurtner** [comment]
@aure thanks a lot for the quick update. 
I'm also getting the following errors while building:
"Cannot find 'output' in scope"
"Cannot find 'midi' in scope"
...

Can you reproduce these issues as well or is it likely to be an issue on our side?

**Comment by corentingurtner** [comment]
These errors are coming from AKNodeRecorder, AKMIDISampler, AKMIDIInstrument and AKMIDINode
Below is a screenshot of the first issue, in AKNodeRecorder :
![image](https://user-images.githubusercontent.com/1526401/93560018-62171a00-f981-11ea-9807-57760ac9585a.png)

**Comment by brizzly** [comment]
> @aure Dropping the AK prefix did the trick. Thanks!

Could you explain please?
I get 10 errors like many else, and I don't really understand how to work around it
Thanks in advance!

**Comment by aure** [comment]
@brizzly and everyone. You have to let us know which version of AudioKit you are trying to run. 4.11 is very different from 5 (and 5 is not out yet, so it is still in a constantly changing state).

**Comment by aure** [comment]
Also, everyone here who is expecting "support" from this free and open-source project,  please consider sponsoring stephane and I here:

https://github.com/sponsors/aure
https://github.com/sponsors/megastep

**Comment by abinop** [comment]
> @brizzly and everyone. You have to let us know which version of AudioKit you are trying to run. 4.11 is very different from 5 (and 5 is not out yet, so it is still in a constantly changing state).

I am having the 
`Cannot find 'output' in scope`
`Cannot find 'midi' in scope`
`Failed to build module 'AudioKit' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced`

errors with 4.11

**Comment by peterjdann** [comment]
Similar issue using 4.11 via CocoaPods 10 minutes ago in a virgin xCode 12 Project.
<img width="1401" alt="Screen Shot 2020-09-18 at 6 24 02 pm" src="https://user-images.githubusercontent.com/65576684/93574782-2c534f00-f9dc-11ea-8e27-a23014324d80.png">
Greatly respect @aure call above re sponsorship. Very fair, I think.

**Comment by aure** [comment]
I am changing the name of the issue to include 4.11.  For those who want to know more about v5, I am willing to set up a zoom call for everyone to watch me talk about where we are going and how to set up a project for AKv5.  Email me aure @ at AudioKit dot io or are at audiokitpro dot com to be invited.

**Comment by brizzly** [comment]
> @brizzly and everyone. You have to let us know which version of AudioKit you are trying to run. 4.11 is very different from 5 (and 5 is not out yet, so it is still in a constantly changing state).

Sorry, I talk about AK 4.11 with xCode 12 and iOS 14

**Comment by vojtabohm** [comment]
Thanks @aure for your willingness.
In my case however I would also wait for a 4.11 fix and stay on the stable version.

**Comment by xieliweiparkman** [comment]
Same issues :), waiting for stable 4.11 version. Thanks

**Comment by fattalgazi** [comment]
When I install like this: ```pod 'AudioKit', :git => 'https://github.com/AudioKit/AudioKit.git', :tag => 'v4.11'```it produces : ```[!] Unable to find a specification for 'AudioKit'.```  any idea ?

**Comment by Jackstone92** [comment]
Same issues here too. Eagerly waiting for a stable 4.11. Thanks guys!

**Comment by fattalgazi** [comment]
Okey, I changed the podfile line to origin => ``` pod 'AudioKit' ```, I made pod update, now everything is ok. 4.11 is installed.

**Comment by PQKelly** [comment]
App was 'ready to submit' using 4.9.5 - then updated to Xcode 12.0, now using the 4.11 xcframework - I get the same errors for sim and 'any iOS device' target. - hopefully that can help narrow down the bug?? sorry if I'm only repeating what you already know.
<img width="428" alt="Screen Shot 2020-09-18 at 6 06 00 PM" src="https://user-images.githubusercontent.com/472329/93649544-3a07d500-f9da-11ea-8b24-02a8d786d683.png">
<img width="428" alt="Screen Shot 2020-09-18 at 6 11 55 PM" src="https://user-images.githubusercontent.com/472329/93649644-71768180-f9da-11ea-85eb-fbb9fbef2f00.png">

**Comment by megastep** [comment]
The root case of all this is the AudioKit class - there's a restriction/shortcoming/bug with Swift modules and class names that match the module - I'm trying a few more tricks to see if we can make it work unchanged, but there's a good chance we'll have to rename it to something else to make this work. For a while in v5 it was renamed to `AKManager` so I might just do that.

**Comment by ryangenz** [comment]
We tested the version of v5 where it was renamed to AKManager, and the transition was pretty painless. This solution would work for us 👍

**Comment by fvonk** [comment]
> We tested the version of v5 where it was renamed to AKManager, and the transition was pretty painless. This solution would work for us 👍

How did you install version 5.0 ? I can't install via pod 'AudioKit', '~> 5.0'
Getting this error:
```
[!] CocoaPods could not find compatible versions for pod "AudioKit":
  In Podfile:
    AudioKit (= 5.0)
```

**Comment by megastep** [comment]
There is no pod for v5.0 since it hasn't been officially released yet. You can install via SPM though by pointing it to our `v5-develop` branch.

**Comment by megastep** [comment]
FYI I should have version 4.11.1 out later today that should fix these issues (with a new AKManager class)

**Comment by megastep** [comment]
v4.11.1 is now out and the pod was pushed; let me know if this fixes your issues (it should). You will have to update your code to replace all references to the `AudioKit` class to `AKManager` instead. In most cases this should just be a 2-3 line code change.

**Comment by fattalgazi** [comment]
> There is no pod for v5.0 since it hasn't been officially released yet. You can install via SPM though by pointing it to our `v5-develop` branch.

When I tried like: ```pod 'AudioKit/Core', :git=>'https://github.com/AudioKit/AudioKit/', :branch => 'v5-develop'```

I got this error: ```Analyzing dependencies
Pre-downloading: `AudioKit` from `https://github.com/AudioKit/AudioKit/`, branch `v5-develop`
[!] Unable to find a specification for 'AudioKit'.```

**Comment by fattalgazi** [comment]
> v4.11.1 is now out and the pod was pushed; let me know if this fixes your issues (it should). You will have to update your code to replace all references to the `AudioKit` class to `AKManager` instead. In most cases this should just be a 2-3 line code change.

I missed that comment, now everything is working, thank you so much for your amazing effort.

**Comment by fattalgazi** [comment]
sorry for that but when I install v4.11.1 into simulator, everything is working fine, success built, but when I try to run on my real device which has ios 14, I got those errors:

<img width="465" alt="Screen Shot 2020-09-20 at 03 31 54" src="https://user-images.githubusercontent.com/3602109/93691709-fc966b00-faf1-11ea-8714-27137febdd5c.png">

**Comment by megastep** [comment]
Well that is interesting, it should definitely work the same for devices as the simulator. The target error is weird though - why would it be looking for ARM64 simulator unless you are on an Apple Silicon Mac?

**Comment by megastep** [comment]
FYI I don't get any of these errors with the new frameworks, compiling for devices or archiving. If you are actually on Apple Silicon, you'd be better off actually switching to v5.

**Comment by mocman** [comment]
I'm having the exact same issues as @fattalgazi, and I'm on a 16 inch Intel. Currently running through a list of possible fixes and will get back to this thread if I find one that works.

**Comment by megastep** [comment]
What's your iOS SDK target version in your project? You might need to raise it to something more recent.

**Comment by mocman** [comment]
> What's your iOS SDK target version in your project? You might need to raise it to something more recent.

12.4
Which is weird that they're looking for the "arm64-apple-ios10.0-simulator"

**Comment by megastep** [comment]
Not happening for me with my own project using the pod, and I'm targeting iOS 10. I would guess that maybe CocoaPods might be responsible for this... I am using the latest beta of 1.10.

**Comment by b-hutchison** [comment]
Updating CocoaPods from 1.9.3 to 1.10.0.rc.1 got rid of the "unable to load standard library" errors when running on a device for me.

**Comment by megastep** [comment]
Good to hear. Sounds like something they needed to address for Xcode 12.

**Comment by peterjdann** [comment]
Brilliant effort in getting this far this fast. Well done.

Have installed 4.11.1 from pod. Target is iOS 13.6.

For me, the line   micReverb_03 = AKReverb()

triggers the following runtime error when running app on my phone:

 Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.AKReverb'

Kind regards,

Peter Dann

**Comment by b-hutchison** [comment]
I have a similar new runtime error too. Mine occurs both on simulator and device. For the line: 
        var drums = AKMIDISampler()
I get the error:
       Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.AKMIDISampler'

**Comment by megastep** [comment]
Sounds like something else to do with the generated Swift interfaces - I suggest opening a different issue for this.

**Comment by abinop** [comment]
> I have tried to change `import AudioKit` to `import AKManager` also, but it produces: `No such module 'AKManager'`. I have also done a clean build folder, pod cache clean and deleted Pods folder.

You don't need to change the import, you keep `import AudioKit`. You have to change where `AudioKit` is used, for example, change
`AudioKit.output =` to `AKManager.output =`
`AudioKit.start()` to `AKManager.start()`
etc

**Comment by vojtabohm** [comment]
Running pod update does not update to 4.11.1. What am I doing wrong? On cocoapods.org it also shows that 4.11 is the latest release.

**Comment by vojtabohm** [comment]
Manually downloading the package from the "releases" tab and inserting it into the /Pods folder did the trick though.

**Comment by abinop** [comment]
> Running pod update does not update to 4.11.1. What am I doing wrong? On cocoapods.org it also shows that 4.11 is the latest release.

`pod 'AudioKit' , '~> 4.11.1'`

**Comment by fattalgazi** [comment]
Ok updating cocopods solves all problems. Thank you.
```sudo gem install cocoapods --pre```

**Comment by coryl** [comment]
I'm running a MacOS project and was having trouble getting rid of all the errors with the new 4.11.1 build.

`pod cache clean -all` wasn't quite working
Turns out a complete pod reset fixed it.

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup
pod install
```
https://stackoverflow.com/a/46428793/339946

**Comment by bojanstef** [comment]
@megastep on Xcode Version 12.0 (12A7209) I still get these two issues with 4.11.1. I tried deleting derived data, cleaning pod cache, de-integrating and installing pods again but nothing fixed it.
```
# At `import AudioKit`
Unable to load standard library for target 'arm64-apple-ios10.0-simulator'
Failed to build module 'AudioKit' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced
```

The only AudioKit references I have are these lines:
```
var options = AKConverter.Options()
let converter = AKConverter(inputURL: URL(), outputURL: URL(), options: options)
converter.start { /* ... */ }
```

**Comment by b-hutchison** [comment]
Updating CocoaPods to 1.10.0.rc.1 got rid of the "unable to load standard library" errors for me.

**Comment by elcitrovmtgrande** [comment]
Thank you @aure @megastep for your amazing work. Now it works on 4.11.1 for me. Just had to change de pod ios platform from 9.0 to 11.0.
Thank you guys. I stay here to help if needed.
Best,
@elcitrovmtgrande

**Comment by brizzly** [comment]
Building ok with 4.11.1 and Xcode12 and a few AudioKit.* renames.
Crash when I run my app though 
Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.AKMIDISampler'

**Comment by vojtabohm** [comment]
I confirm everything working with 4.11.1 for me. Thank you @aure @megastep.

**Comment by elcitrovmtgrande** [comment]
> Building ok with 4.11.1 and Xcode12 and a few AudioKit.* renames.
> Crash when I run my app though
> Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.AKMIDISampler'
> 
> New issue added here : #2276
> Thanks a lot

Hi @brizzly, juste replace AudioKit my AKManager.ADMIDISampler, I guess...

**Comment by brizzly** [comment]
> > Building ok with 4.11.1 and Xcode12 and a few AudioKit.* renames.
> > Crash when I run my app though
> > Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.AKMIDISampler'
> > New issue added here : #2276
> > Thanks a lot
> 
> Hi @brizzly, just replace AudioKit by AKManager.ADMIDISampler, I guess...

It was not enough , but another work around did the trick,  to know more about it have a look at the issue 2276

**Comment by willsmillie** [comment]
It looks like 4.11.1 has dropped some support for Objective-C as I am no longer able to call [AKManager setOutput:]. Should I be working on migrating my project to Swift for better compatibility or was this simply an oversight?

**Comment by tehsven** [comment]
Updated to `v4.11.1`, updated cocoapods to `1.10.0.rc.1`, removed derived data, and the build is working again. However now I am seeing missing PCM files, the same issue that was reported on https://github.com/AudioKit/AudioKit/issues/1247 and https://github.com/AudioKit/AudioKit/issues/1325:

```
warning: /var/folders/zg/rxr8tgkn1ylf0hm8crrnrc840000gq/C/org.llvm.clang.megastep/ModuleCache/1BAOMPOQVXYU7/AVFoundation-7O317LEIB4Z2.pcm: No such file or directory
note: while processing /var/folders/zg/rxr8tgkn1ylf0hm8crrnrc840000gq/C/org.llvm.clang.megastep/ModuleCache/1BAOMPOQVXYU7/AVFoundation-7O317LEIB4Z2.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
```

<img width="1171" alt="Screen Shot 2020-09-21 at 9 38 24 AM" src="https://user-images.githubusercontent.com/1480845/93796068-25505a80-fbef-11ea-806e-d0316663d391.png">

**Comment by westside** [comment]
* By updating pod to 1.10.0.rc.1, archiving and running with the simulator are okay. 

But, got same error with real device(XR). 

```
Failed to build module 'AudioKit' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced
```

* Any recommendation for this error only on the real device?

**Comment by megastep** [comment]
Looks like these are referencing files that are on my Mac since I'm the one who built the binaries... :/

**Comment by trevor-sonic** [comment]
I could install ```AudioKit 4.11``` by get riding off ```Pod``` then adding ```AudioKit``` into the workspace.
For me, every time using ```Pods``` I ended up return back to manual integration, slower but clean and safe.
```V5``` is coming with ```SPM``` thanks a lot. I wish to be able to use ```SPM``` for ```V4``` as well _(but this is already answered somewhere here that was not possible)_

**Comment by RichardBoyder** [comment]
> @meilers No more AudioKitUI in AudioKit5.

what do we use instead of AudiokitUI ? Dol ytou have breaking change document what should change from audiokit 10 to audio kit 11 upwards?

**Comment by joengmin** [comment]
Is the latest AudioKit download link posted here for the latest XCode and Swift? I get lots of errors. Is there any clean instruction on linker, library, and embedded content configuration? Thanks.
