### ISSUE TITLE
Add (or switch to) frameworks instead of static libraries

### ISSUE THREAD

**Issue by armadsen** [audiokit/AudioKit#227]
It would be nice if AudioKit.xcodeproj built AudioKit.framework. This would make initial setup easier, removing the need for the explicit user header search paths setting, for example. It would also provide compatibility with [Carthage](https://github.com/Carthage/Carthage).

**Comment by aure** [comment]
Agreed, and its been on our to-do list for a while and we're hoping for the next release.  I'll leave this issue open until it can be done.

**Comment by narner** [comment]
Adding @megastep as a watcher on this one

**Comment by marsman12019** [comment]
To jump on this, CocoaPods does automatically build a framework (I think) when using `use_frameworks!` in your Podfile (in Swift, I'm not sure how it works in Obj-C). Instead of doing `#import "AKFoundation.h"` in a Bridging Header, you have to do `import AudioKit` in whatever file you want to use AudioKit classes in, **including** the AudioKit.swift helper.

**Comment by megastep** [comment]
Unless CocoaPods actually creates the appropriate targets in the Xcode config, I kinda doubt how this actually works. But in any case, this is definitely something we want to add sooner rather than later (probably after 2.3).

**Comment by DanielAsher** [comment]
+1

**Comment by Gutty1** [comment]
+1

**Comment by aure** [comment]
Working on it!

**Comment by Gutty1** [comment]
great to know, please let me know when is fully supported

**Comment by themaninthesuitcase** [comment]
This would be great, I found the setup and linking the hardest part of getting started with AK as a new Apple developer.

**Comment by aure** [comment]
Trust me, working very hard on this and I can already tell you its basically working, just a few more things left.  Probably right around Christmas, but don't hold me to that.

**Comment by DanielAsher** [comment]
Happy New Year !

**Comment by aure** [comment]
Hi, yeah, Happy New Year. Looking to have it as a framework by January 21st!

**Comment by loopbum** [comment]
When might it be a pure Swift framework?  I recall hearing some changes (every year) at WWDC, but Swift 2.1 so far produces very compact code reading and the compiler helps you do things that increase stability dramatically.

**Comment by aure** [comment]
You'll never want it to be pure Swift if you want it as fast as possible.  Next release is a lot swiftier though.  I think you'll like it a lot.  I'm just building a few example apps now to smooth out initial kinks.

**Comment by DanielAsher** [comment]
@aura great news !!

**Comment by loopbum** [comment]
I realize it cannot be all Swift. But Swift is very expressive, so the more examples the quicker to solutions. Some involved know AudioKit extremely well.

I’ve chosen to abstract myself away from the core and use Swift as much as possible to focus on a long list of educational apps that teach some of the mathematics involved in sound synthesis and psychoacoustics, etc.

**Comment by aure** [comment]
I understand and agree, stay tuned.

**Comment by aure** [comment]
I think this will suffice for easy framework installation....  https://vimeo.com/152398360
