### ISSUE TITLE
'unimplemented initializer' runtime error with some 4.11.1 components

### ISSUE THREAD

**Issue by peterjdann** [AudioKit/AudioKit#2272]
In 4.11.1, calls to AKMIDISampler() and AKReverb() fail with "Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.X'" where X is the component whose constructor has triggered the error. The failures occur in both a real device and a simulator.

**Comment by megastep** [comment]
I think this is because of the way Swift generates the interface files. Both of these classes do not have an empty constructor, but rather constructors with default values. I'd try to explicitly set some of these values and see if that helps.

**Comment by b-hutchison** [comment]
Thanks very much! Adding a "midiOutputName" parameter to my AKMIDISampler call solved the problem for me. Interesting that although the docs show a value is required, the autocomplete default is empty.

**Comment by megastep** [comment]
Frankly that does sound like a Swift / LLVM bug.

**Comment by fvonk** [comment]
So what should we do now with this issue ? Project with AudioKit continues to fail in Xcode 12.

**Comment by ClassicalDude** [comment]
Just adding that the AKMicrophone init also fails in the same way.

**Comment by megastep** [comment]
As a workaround, for now look at the source code of the class to figure out exactly how to init it.

**Comment by sharaquss** [comment]
Runtime initialization fails for a lot of signal chain components actually - `AKReverb`,  `AKDelay`, `AKCompressor`, `AKExpander`, `AKLowShelfFilter`, `AKHighShelfFilter` etc. 

Quick fix would be to manually point Swift into right `init` by replacing `AKReverb()` with `AKReverb(nil)`. 
This explicitly points to `.init(_ input: AKNode?)` I guess.

<img width="1089" alt="Screenshot 2020-09-20 at 12 57 12 PM" src="https://user-images.githubusercontent.com/9783699/93709785-89b4e080-fb41-11ea-8a34-01802218d66f.png">

**Comment by ClassicalDude** [comment]
For anyone who's interested, here are some complete inits using default values as workarounds for missing default inits:
```
AKMicrophone(with: nil)
AKBooster(nil, gain: 1)
AKDelay(nil, time: 1, feedback: 0.5, lowPassCutoff: 15_000, dryWetMix: 0.5)
AKFrequencyTracker(nil, hopSize: 4_096, peakCount: 20)
```

**Comment by fvonk** [comment]
Ok now it's compiled. But midi file playing stoped working. Before iOS 14 and Xcode 12 - everything have been worked.
Any ideas ?

```
let midiSample = AKMIDISampler(midiOutputName: nil)
let sequencer = AKAppleSequencer(filename: filename)
sequencer.enableLooping()
sequencer.tracks[1].setMIDIOutput(midiSample.midiIn)
sequencer.setLoopInfo(sequencer.length, numberOfLoops: loopNumber)
let bpm = sequencer.allTempoEvents[0].1
sequencer.setTempo(bpm)
sequencer.play()
```

**Comment by aure** [comment]
@fvonk, let's not lump unrelated stuff into this issue.

**Comment by aure** [comment]
Just so everyone is prepared for AudioKit 5, there will be no more initialization with an optional node, so you might as well set up your signal chain in your 4.11 apps with actual nodes.

**Comment by JonLatane** [comment]
Just to confirm, I was experiencing this issue too with `AKSampler.init()` and fixed it by replacing my constructors `AKSampler()` with `AKSampler(masterVolume:1.0)`.

**Comment by aidanj** [comment]
Here are some more default inits for reference:

`
AKLowPassFilter(resonance: 0)
AKSynthSnare(resonance: 0.9)
`

A default parameter can be found by looking at the `init` of a class within v4 codebase. E.g. [AKLowPassFilter.swift](https://github.com/AudioKit/AudioKit/blob/v4-master/AudioKit/Common/Nodes/Effects/Filters/Low%20Pass%20Filter/AKLowPassFilter.swift) ) has the init:

`
@objc public init(
        _ input: AKNode? = nil,
        cutoffFrequency: Double = 6_900,
        resonance: Double = 0) {
` 

So we can explicit use one of those (like `resonance: 0`) to work around the error using `AKLowPassFilter(resonance: 0)`
