### ISSUE TITLE
AKBooster.leftGain is a let constant

### ISSUE THREAD

**Issue by amardeepranu** [AudioKit/AudioKit#2277]
I'm on the latest AudioKit/Core (4.11.1) pod and I'm getting an error that AKBooster.leftGain and rightGain are both let constants that can't be changed:

<img width="1092" alt="Screen Shot 2020-09-21 at 12 46 07 PM" src="https://user-images.githubusercontent.com/7548096/93796221-859fc600-fc08-11ea-8962-906202a16763.png">

This wasn't an issue on 4.9.5 and it looks like its still declared as a var in source: 

https://github.com/AudioKit/AudioKit/blob/4e71daddf9ba223e46579d52b0dd1a9cc8e011fb/AudioKit/Common/Nodes/Mixing/Booster/AKBooster.swift#L55

**Comment by aure** [comment]
I don't know, even in the 4.11.1 version of AKBooster it is a var. Did you accidentally get a cocoa pod for v5.01b? There is a protocol in your screen shot that's not even part of AK4 at all.
