### ISSUE TITLE
V5-Develop (pre-beta) swift package archive failure

### ISSUE THREAD

**Issue by adamjsutcliffe** [AudioKit/AudioKit#2279]
I may be jumping the gun here as V5 isn't properly out, but 4.11.1 doesn't play any sound on my MidiSampler so I've updated my project to swift package pointing at `https://github.com/AudioKit/AudioKit` using version rule of branch `v5-develop`. Building to device and simulator works fine but when archiving the project a generic archive is produced along with a load of errors for unexpected characters:
```
error reading dependency file '/Users/adamsutcliffe/Library/Developer/Xcode/DerivedData/SpinnerTest-czsfrzkkpvctzcapjnypjtpizbck/Build/Intermediates.noindex/ArchiveIntermediates/SpinnerTest/IntermediateBuildFilesPath/AudioKit.build/Release-iphoneos/AudioKit.build/Objects-normal/arm64/AudioKit-master.d': unexpected character in prerequisites at position 6184335 (in target 'AudioKit' from project 'AudioKit')
```
I'm new to swift packages so not sure how to solve this issue, it seems like a colon just needs to be removed somewhere but I have no idea where!

Screen shot of archive produced, no version number or ability to validate or upload to app store/test flight available
<img width="1279" alt="Screenshot 2020-09-22 at 10 22 29" src="https://user-images.githubusercontent.com/3214274/93865556-63687f80-fcbe-11ea-9ffd-9350560f4079.png">

**Comment by adamjsutcliffe** [comment]
After digging a little deeper its entries like this in the dependency file that are causing the issue. `AudioKit::MAINGROUP::REF_1::REF_90.bc`

**Comment by aure** [comment]
FYI there's a fix in for AKMIDISampler https://github.com/AudioKit/AudioKit/pull/2281 but this looks to be important for v5 going forward.

**Comment by aure** [comment]
@adamjsutcliffe @megastep I've started a Github Project to manage requirements for AK5 release here https://github.com/AudioKit/AudioKit/projects/5.

This issue is on there.

**Comment by megastep** [comment]
I'm rather new to SPM myself too, but these are files generated by Xcode and I'd be inclined to blame it for it.

**Comment by aure** [comment]
Interestingly enough I got like 181 of those type of errors when archiving, but it still archived for me.

**Comment by Luftare** [comment]
Did it still archive it as `Generic Xcode Archive`? I tried all suggested approaches here without any luck: https://stackoverflow.com/a/57749091

**Comment by aure** [comment]
Actually on a second look, the archives that I thought I was creating were basically empty shell xcarchives, so this is definitely not working and has to be fixed before we can think about releasing AK5.

**Comment by gilhadas** [comment]
I'm having same issue archiving. is there any workaround ?

**Comment by aure** [comment]
I have submitted a Developer Technical Support with Apple.

**Comment by aure** [comment]
For completeness, the issues were that some file names were colliding with each other, Operations/Effects/korgLowPassFilter.swift vs. Nodes/Effects/KorgLowPassFilter.swift for example. Why Apple requires unique file names? I have no clue. Once I renamed the operations files this issue went away. what a pain it was.

**Comment by NataVladimir** [comment]
Resolvemos o problema tirando caracter Especial
