### ISSUE TITLE
Xcode 12 и AudioKit v4.11.1

### ISSUE THREAD

**Issue by Evgenij-gostev** [AudioKit/AudioKit#2280]

**Comment by Evgenij-gostev** [comment]
Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.AKAudioFile

**Comment by Evgenij-gostev** [comment]
<img width="898" alt="Снимок экрана 2020-09-22 в 16 21 10" src="https://user-images.githubusercontent.com/35343865/93887643-a2fb8f80-fcef-11ea-874f-2be534c0787b.png">

**Comment by impmaarten** [comment]
Could you try any initialisers mentioned in the source file?
The created swift headers are incorrect for the initialisers.

https://github.com/AudioKit/AudioKit/blob/79cebe3ff8acc64e743b9e9536693c193e478eb4/AudioKit/Common/Internals/Audio%20File/AKAudioFile.swift

`init(forReading fileURL: URL) `
`init(forReading fileURL: URL,
                         commonFormat format: AVAudioCommonFormat,
                         interleaved: Bool)`
`init(forWriting fileURL: URL,
                         settings: [String: Any],
                         commonFormat format: AVAudioCommonFormat,
                         interleaved: Bool)`
`init(forWriting fileURL: URL, settings: [String: Any])`
