### ISSUE TITLE
Sampler init in v5

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/AudioKit#2282]
Sampler init now needs 1 audiofile or a SFZ at creation time.
Also, there's no way to load samples once the sampler is inserted in the chain. 
In v4, the sampler can be created by itself and then audio samples can be 'hot loaded' and unloaded at run time. This allows me to create my simulated instrument with different samples at run time based on the selection than load all samples in at once.

Is this an oversight, or the new way of doing things? If the latter, how do I still do my hot load now?

**Comment by aure** [comment]
This is not an oversight since it is not a thread safe process to do that load.  You can create a new Sampler and then dynamically swap the two using a mixer.  

``` 
 mixer = Mixer()
mixer.addInput(sampler1)
... play it, whatever ... then later
sampler2 = Sampler(with new stuff)
mixer.addInput(sampler2)
mixer.removeInput(sampler1)
```

Should actually be a better experience for users. You could even do crossfading or other stuff as needed.

**Comment by quantamrhino** [comment]
Oh thank you. That makes sense.
Could you add a helper init that takes in multiple audiofiles and descriptors at once perhaps? That way I can continue loading the audiofiles to the sampler as I am currently with little change to the code (I am afraid of doing the SFZ way at this point in the release cycle!).

**Comment by aure** [comment]
Did AK4 allow for that?

**Comment by quantamrhino** [comment]
Yes, in that i could call LoadAudioFile multiple times with different sample descriptors for different notes. LoadAudioFiles is now an internal function :-(

**Comment by aure** [comment]
I think you should give this update a shot and make a pull request. I can do it too, but I have a lot on my plate. Are you a sponsor? That might tip the scale for me. :) http://github.com/sponsors/aure

**Comment by quantamrhino** [comment]
I wish I had the money to sponsor you! I'm a student in south of India :-( trying to get my app to the appstore to get some extra candy money!

I am still learning how to make a pull request etc, but something like this perhaps?( I'm still learning swift too.)

public init(fds: [(sampleDescriptor: SampleDescriptor, file: AVAudioFile)]) {
            super.init(avAudioNode: AVAudioNode())

            instantiateAudioUnit { avAudioUnit in
                self.avAudioUnit = avAudioUnit
                self.avAudioNode = avAudioUnit
                self.internalAU = avAudioUnit.auAudioUnit as? AudioUnitType
            }
        for fd in fds {
            self.loadAudioFile(from: fd.sampleDescriptor, file: fd.file)
        }
    }

**Comment by aure** [comment]
I updated your way slightly.

**Comment by quantamrhino** [comment]
Many many thanks!!
It was also educational to see your way of doing it.

**Comment by quantamrhino** [comment]
I have an array of descriptors - there's no easy way to pass them to the varibale arguments as I don't know how many there are.. I can't for the life of me figure out how to get this into the new init function. A google search shows that splatting is not in the language yet.
Am I missing something simple?

**Comment by aure** [comment]
I can make an array version of the init too, or you can. its pretty easy.

**Comment by quantamrhino** [comment]
Is there an advantage of a variable arg one over an array one?
something like this? 

    /// Initialize this sampler node with many files. There are many parameters, change them after initialization
    ///
    /// - Parameters:
    ///   - sampleDescriptors: An array of sample descriptors, must match the order of the files
    ///   - files: An array of audio files, matched by order to the sample descriptors
    public init(filesWithSampleDescriptors: [FileWithSampleDescriptor]) {
        super.init(avAudioNode: AVAudioNode())

        instantiateAudioUnit { avAudioUnit in
            self.avAudioUnit = avAudioUnit
            self.avAudioNode = avAudioUnit
            self.internalAU = avAudioUnit.auAudioUnit as? AudioUnitType
        }

        for fileWithSampleDescriptor in filesWithSampleDescriptors {
            self.loadAudioFile(from: fileWithSampleDescriptor.sampleDescriptor, file: fileWithSampleDescriptor.file)
        }
    }

**Comment by aure** [comment]
Go ahead and replace the variable argument one with this one in a PR to v5-develop. The only benefit to the other one would be a slightly nicer looking init, if you had say 2 files, but this is not important. If you'd rather not do the PR I can certainly do the cut and paste :)

**Comment by aure** [comment]
Oh, but make sure to fix the documentation comments
it should just be `- filesWithSampleDescriptors: yadda yadda yadda`

**Comment by quantamrhino** [comment]
I'm having trouble getting github to work on my school computer lab network :-( It's stuck downloading the repo for the last 40 min. Can you please make the change? many thanks in advance!

**Comment by quantamrhino** [comment]
A million thanks Sir!! 🙏
