### ISSUE TITLE
Not receiving SysEx messages on iOS 14

### ISSUE THREAD

**Issue by yuriizubkov** [AudioKit/AudioKit#2284]
Hello devs. Thank you for your great framework!
I am using the MIDI part of AudioKit in my app. 

In some cases I am sending sequential SysEx requests (and receiving responses) from my app to MIDI synth with 100ms gap between messages. All was working stable on iOS 11-13 with no issues at all. But the same build of the app stopped working on iOS 14. I tried both AudioKit 5 and 4.11.2 - same issues on iOS 14.

I am getting the first couple of SysEx messages and then I can’t receive anything, SysEx, CC, Note information.
What I found in the logs. Usually I can see in the logs:

```
AKMIDI.swift:startReceivingSysEx(with:):92:Starting to receive SysEx (AKMIDI.swift:startReceivingSysEx(with:):92)
AKMIDI.swift:stopReceivingSysEx():97:Done receiving SysEx (AKMIDI.swift:stopReceivingSysEx():97)
```

But on iOS 14 at some point it stuck at:
```
AKMIDI.swift:startReceivingSysEx(with:):92:Starting to receive SysEx (AKMIDI.swift:startReceivingSysEx(with:):92)
```

And after that I can’t receive any MIDI message from the synth. But I can still send MIDI messages.
What I found in the AudioKit MIDI implementation, it might be some race condition around:
`AKManager.midi.isReceivingSysEx`

Or maybe internal format of MIDI packets has changed so parser can’t recognise the end of SysEx message.
I see many changes in CoreMIDI implementation on iOS 14, so it can be so the internal behaviour changed somehow.

I am not providing my code here, because I think it is not relevant to this issue, since everything is working on iOS 13.
Tell me if I can help to debug this issue better.
Thank you.

**Comment by yuriizubkov** [comment]
After further investigation I think this issue might be related to this:
https://github.com/AudioKit/AudioKit/issues/2145#issue-655054321

Because **MIDIInputPortCreateWithBlock** is deprecated on iOS 14.
List of all deprecated symbols is here: https://developer.apple.com/documentation/coremidi/midi_services/deprecated_symbols

And you are using it for parsing incoming MIDI messages here: https://github.com/AudioKit/AudioKit/blob/v5-develop/Sources/AudioKit/MIDI/MIDI%2BReceiving.swift

My incoming SysEx message is 350 bytes, so this is why probably I am not getting second part of the message and AKManager.midi.isReceivingSysEx never got set to true.

I will try to modify your code to support both iOS 9..13 and iOS 14 and will report later here.

**Comment by aure** [comment]
If you could possibly use AudioKit v5 for this change, that would be great, but if you make it to v4 I can probably figure out how to port it to v5.

**Comment by yuriizubkov** [comment]
@aure Yes, I am using v5 now.

**Comment by yuriizubkov** [comment]
Hello @aure 
I've added a PR https://github.com/AudioKit/AudioKit/pull/2292

Information that I used to get this working:
https://www.midi.org/midi-articles/details-about-midi-2-0-midi-ci-profiles-and-property-exchange
http://download.xskernel.org/docs/protocols/M2-104-UM_v1-0_UMP_and_MIDI_2-0_Protocol_Specification.pdf

My app is working now. I have a couple of questions.
Are there any plans to separate MIDI from the main framework?
Can I somehow downgrade the required iOS version of v5 AudioKit to iOS 11?

Thank you!

**Comment by aure** [comment]
Ha, well it looks like the PR relies on iOS14, so downgrading to iOS11 might be problematic. Honestly, I'd like to make the minimum requirement iOS13 and take advantage of some that releases offerings.

**Comment by yuriizubkov** [comment]
@aure , this PR has checks to support older iOS versions and iOS 14+. On iOS 14+ should work new approach for parsing MIDI messages, on older versions should work existing parsing code.

Just a thought. It would be great to support older iOS devices with older os versions, at least for MIDI.
It would be easier to maintain the MIDI subsystem code if it were a separate framework. Big changes are coming for MIDI 2.0.
I think I read somewhere that you are planning to separate MIDI into a separate framework (maybe MIDIKit). Is it so? And if you are planning to do this, can I ask you when?
Thank you!

**Comment by aure** [comment]
Eventually AudioKitMIDI will be separated out into its own thing, but it seems like a lot of work to do before AudioKit 5 is released.

**Comment by yuriizubkov** [comment]
Ok, got it.

**Comment by aure** [comment]
Can this be closed with your latest PR accepted?

**Comment by yuriizubkov** [comment]
Yes, sure.

**Comment by aure** [comment]
Thank you very much. Gold stars to you for identifying and fixing a problem in AudioKit. I have some ideas on how we can start to separate MIDI stuff. Are you on our Slack group? Would you like to be?

**Comment by yuriizubkov** [comment]
@aure Thank you! I am not on Slack yet and I would like to be. I think I could help with MIDI 2.0

**Comment by aure** [comment]
Email me at aure at AudioKit dot io so I can add invite you.

**Comment by davidgiga1993** [comment]
Hi,
I'm a developer of a cross platform app which uses midi and I'm facing a lot issues with sending sysex on ios/mac since the last couple of OS updates and wanted to ask if you heard about similar issues in that area?

Using the new midi 2.0 api and sendSysex() CoreMidi seems to drop all packets for 500ms after the last sendSysex call. In my application I need to send sysex followed by regular note events in quick succession. Using the old deprecated midi api coremidi just sends garbage to the midi port (randomly injecting sysex start into regular midi packets).

The reason I'm asking here is because I just don't find any other good place with experienced coremidi developers.
