### ISSUE TITLE
Xcode 12.0.1 AudioKit XCFramework 4.11.2 Multiple Warnings

### ISSUE THREAD

**Issue by ClassicalDude** [AudioKit/AudioKit#2287]
When archiving my project, I get 24 of these warnings:
```
warning: /var/folders/zg/rxr8tgkn1ylf0hm8crrnrc840000gq/C/org.llvm.clang.megastep/ModuleCache/1BAOMPOQVXYU7/AVFoundation-7O317LEIB4Z2.pcm: No such file or directory
note: while processing /var/folders/zg/rxr8tgkn1ylf0hm8crrnrc840000gq/C/org.llvm.clang.megastep/ModuleCache/1BAOMPOQVXYU7/AVFoundation-7O317LEIB4Z2.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
```
The XCFramework is manually inserted to the project, not from cocoapods or swift package.

**Comment by megastep** [comment]
Where did you get the XCFramework? Did you compile it yourself?

Looking at our build settings on v4 module debugging should be turned off for releases, so in theory these warnings should not happen.

**Comment by ClassicalDude** [comment]
The XCFramework was downloaded directly from the release page at GitHub. I am adding both AudioKit.xcframework and AudioKitUI.xcframework to my project - it doesn't allow me to add just the external AudioKit.xcframework.
These errors were also on 4.11.1, and they started with the release scheme as soon as I upgraded to Xcode 12.0.1 from Xcode 12.

**Comment by megastep** [comment]
Which platform are you targeting here? iOS?

**Comment by ClassicalDude** [comment]
iOS. The app is for iPad only.

**Comment by megastep** [comment]
This seems to be a common problem with half-solutions: https://forums.swift.org/t/swift-behavior-of-gmodules-and-dsyms/23211/4

I'm gonna look at trying to set the `-no-clang-module-breadcrumbs` in the build options for the next release, but for now just ignore those I guess.

**Comment by aure** [comment]
This may be a lot to ask, but could you try porting your app to AudioKit v5? It is now the default branch, but there is no Cocoapods for it yet, you need to use Swift Package Manager.

**Comment by ClassicalDude** [comment]
I'll try. It will probably take a couple of days. I'll write back as soon as I have something. If you wish, you can close this for now and I'll reopen when I have something to report.

**Comment by ClassicalDude** [comment]
@aure - I have started looking at migrating the app, and there are two show-stoppers for me:
1. The minimal OS of v5 seems to be iOS 13. This in effect drops an entire generation of devices that can be updated only up to iOS 12, which I think was a very good version of iOS, and far more stable and less buggy than iOS 13. If this remains the minimal OS requirement, I think I'll stick to v4 for as long as I can.
2. I am using AKMetronome. I know it's easy to create a metronome, but for me that class was very convenient, and saved me work. This is not a big show-stopper as the first item, though.

For the time being I'll change my minimal OS requirement and drop the metronome, just so I can come back and tell you how everything else is behaving.

**Comment by aure** [comment]
Okay, well thanks for trying it.

**Comment by ClassicalDude** [comment]
Without AudioKit I would be nowhere. Until such time that I feel confident enough to make pull requests, testing is the very least I can do.

**Comment by megastep** [comment]
@aure is there a compelling reason the iOS requirement was raised to 13 in the past few days? It was compiling just fine with iOS 11 a few days ago.

**Comment by ClassicalDude** [comment]
I was able to get my project to work and compile with v5 from SPM. It took a lot of tinkering, but the result seems to be much more stable, consistent and less fragile than v4. This included using the new FFTTap, PitchTap, Fader instead of Booster and NodeOutputPlot instead of EZAudioPlot.

I am facing four issues:
1. The limitation to iOS 13. Xcode 12 has the limitation of iOS 12, and as I mentioned before, the last generation of devices that Apple stopped upgrading is set to iOS 12 as the maximum OS. The iOS 13 limit means we are dropping a whole generation of devices, and losing users accordingly.
2. It is unclear from the current documentation how one can choose the microphone. I could not find the equivalent of AKManager.inputDevices or how to set the AudioEngine's input. This is quite necessary for me. I opened an SO question about this; let me know if you need for me to open a new issue here.
3. I would really love to see the metronome project tutorial.
4. @megastep - when setting the scheme to release, this time I am getting 190 errors, that all look like this:
```error: error reading dependency file '/Users/ron/Library/Developer/Xcode/DerivedData/Score_Wizard-endathdlcybwktcelwogexnugnza/Build/Intermediates.noindex/AudioKit.build/Release-iphoneos/AudioKit.build/Objects-normal/arm64/AudioKit-master.d': unexpected character in prerequisites at position 5801751 (in target 'AudioKit' from project 'AudioKit')```
No errors when using debug.

**Comment by aure** [comment]
1. I just built for iOS12 and its only stupid CGColor stuff in our way, so maybe its fine to lower it down.  
2. `try AudioEngine.setInputDevice(device)`
3. Get in line :) I can't wait either, just gotta get AudioKit 5 moving a bit further first.
4. That's one of the issues already here on Github. We all need to look into it, its a super mystery!

**Comment by aure** [comment]
Also wanted to respond to your first paragraph.. that is awesome to hear! We're about to beef up the plots, so that will take one more round of tinkering probably, but the results will be well worth it.

**Comment by ClassicalDude** [comment]
I wanted to thank you for including hann’s windowing in the new FFTTap. Regarding setting the microphone, how do I get a list of available devices? There is no more AKManager.inputDevices.

**Comment by aure** [comment]
This line and this whole file and repo 
might be helpful
https://github.com/AudioKit/Cookbook/blob/e53054a6bad4e7cad6d96790e87fae1841e84abb/Cookbook/Cookbook/Recipes/Tuner.swift#L152

**Comment by aure** [comment]
Bumped the target back down and tried a new(old) cgcolor technique

**Comment by ClassicalDude** [comment]
Thank you for all of your help. This issue has strayed away from its original subject; I leave it up to you whether you want to keep it open or close it. The original issue, the warnings in 4.11.2 when compiling the release scheme, is not yet resolved. I assume this will be considered for 4.11.3, if and when that version is released.

**Comment by paulorrfilho** [comment]
Late to the discussions but thanks for keep supporting iOS 12. User base is still high at around 10% for my apps.
