### ISSUE TITLE
Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.AKLowPassFilter'

### ISSUE THREAD

**Issue by MrHazee** [AudioKit/AudioKit#2288]
Hi,
This might be a boarderline case if I should file an issue here or put it on stackoverflow.. But my last published build was 5 moths ago and worked like a charm so Im pretty confused with these errors. That build was with 4.9.5. Today I manage to successfully build with Xcode 12.0.1, cocoapods 1.10.0.rc.1 and AudioKit 4.11.2  but at runtime I immediately get this erro:

**Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.AKLowPassFilter'** 

If I remove all use of AKLowPassFilter I get this error instead:
**Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.AKSampler'**

Thanks for the amazing work

**Comment by gilhadas** [comment]
var midiSampler = AKMIDISampler()
I get similar  error : Use of unimplemented initializer 'init()' for class 'AudioKit.AKMIDISampler
is there any workaround  for that?

**Comment by MrHazee** [comment]
Yeah
`var masterVol = 0.5`
` var midiSampler = AKSampler(masterVolume: masterVol)` 
should do the trick for know

**Comment by gilhadas** [comment]
thanks, it doesn't crash anymore, but I hear no sound.
I used:
       midiSampler.loadSFZ(url: soundPath)

**Comment by aure** [comment]
Can you please try to use AudioKit v5 instead?

**Comment by warpling** [comment]
Thank you @MrHazee, it seems a lot of the default initializers fail (in my case `AKBooster`) but using a different initializer did the trick.

**Comment by MrHazee** [comment]
Sure will try v5

**Comment by aidanj** [comment]
For anyone's future reference, adding in a default initializer parameter seems to solve the issue. 
See: https://github.com/AudioKit/AudioKit/issues/2272

For example, if this fails:
`var myFilter = AKLowPassFilter()`

You can instead use:
`var myFilter = AKLowPassFilter(resonance: 0)`

Where `resonance = 0` is the default value anyway, but for some reason explicit setting at least one parameter will get rid of the OP's error message.
