### ISSUE TITLE
Undefined symbol: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers

### ISSUE THREAD

**Issue by ygliboch** [AudioKit/AudioKit#2289]
ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility51'
ld: warning: Could not find or use auto-linked framework 'UniformTypeIdentifiers'
Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility51
Undefined symbol: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers

Xcode Version 11.7   AudioKit Version 4.11.2

hello, errors appear after adding an audio kit, I can't understand what the problems are

**Comment by MIDIKinetics** [comment]
I am getting something similar. Building for macOS. XCode Version 11.7 (11E801a)

ld: warning: Could not find or use auto-linked library 'swiftCompatibility51'
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftCompatibility51", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_AudioKit in AudioKit(AKManager.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_AudioKit in AudioKit(AKSettings.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_AudioKit in AudioKit(AKConnection.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_AudioKit in AudioKit(ExceptionCatcher-085b6ae84c5cca7e4aee40e16564e952457b3d08dd89517cf0f83bfa90525107.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_AudioKit in AudioKit(AKMIDI.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_AudioKit in AudioKit(AKNode.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_AudioKit in AudioKit(AKVariSpeed.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility51_$_AudioKit)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by megastep** [comment]
If you're using the pod for 4.11.2, it was built with Xcode 12 so it might have something to do with it. I would suggest you try to update.

**Comment by megastep** [comment]
Otherwise, explicitly stick to an older release like 4.10

**Comment by MIDIKinetics** [comment]
Gotcha. I'm trying to add it using XCode 11's built-in 'Add package dependency' but I'm getting:

'because no versions of AudioKit match the requirement 4.10.0 and root depends on AudioKit 4.10.0, version solving failed.'
 
https://github.com/AudioKit/AudioKit
Version: Exact: 4.10

**Comment by megastep** [comment]
If you're using the Swift Package Manager, that only works with our `v5-develop` branch at the moment (no released versions). However this is a  pre-release with lots of major API changes.

Otherwise stick with CocoaPods and v4...

**Comment by MIDIKinetics** [comment]
All is well. Thank you very much.

**Comment by ygliboch** [comment]
thanks! release 4.10.1 solved my problem 🎉
