### ISSUE TITLE
Feature Request: Setter for Oscillator Waveform

### ISSUE THREAD

**Issue by Matt54** [AudioKit/AudioKit#2290]
With the removal of AKOscillatorBank and the other banks, we seemingly now no longer have the ability to dynamically swap the waveform of our sound generator on the fly.

Can we simply add a setter for the waveform of an oscillator? If not, is there some alternative approach we could do to have this ability?

Removing the oscillator banks, with their waveform setters, breaks the core functionality of my wavetable synthesizer application.

**Comment by aure** [comment]
AudioKit 4 is not disappearing, your app does not have to follow the V5 trajectory. The AK4 code for banks can be used as a model of functionality, but needs to be implemented in a thread safe and cleanly code way. I do not have time for this right now so someone else will have to step up.

**Comment by Matt54** [comment]
We can close this issue with the addition of the DynamicOscillator.
