### ISSUE TITLE
Reverb2 crashes, but Reverb is fine.

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/AudioKit#2293]
Reverb2 in the audio chain causes crash, when engine is started:
Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: node != nil'
terminating with uncaught exception of type NSException

Replacing Reverb2 with Reverb doesn't crash.

**Comment by aure** [comment]
Are you building for iOS or macOS?

**Comment by quantamrhino** [comment]
sorry -- iOS 14.2 beta. Xcode 12.2 beta 2. v5-develop, as of 2 days ago.

**Comment by aure** [comment]
Not much of a fix, but I can't figure it out and it seems to be a pretty ancient piece of dsp.

**Comment by frogg** [comment]
Getting the same error message for adding a `Mixer()` node as an Engine‘s output.

**Comment by aure** [comment]
@frogg Please don't pile on basically unrelated issues because the generic error printout is the same.
