### ISSUE TITLE
AKAppleSequencer in iOS can't use？

### ISSUE THREAD

**Issue by benben-hello** [AudioKit/AudioKit#2296]
4.11.2
It works on PlayGrounds, but it doesn't work on iOS.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/12512421/95574064-f7786c00-0a5e-11eb-8b3a-c41a7349f413.png">(playgrounds)

<img width="793" alt="image" src="https://user-images.githubusercontent.com/12512421/95574242-39091700-0a5f-11eb-9136-8d318c3de4bf.png">(ios OC)

**Comment by aure** [comment]
This doesn't make sense to me. Explain what you are experiencing more clearly, thanks.

**Comment by benben-hello** [comment]
I need to use AKAppleSequencer for iOS, but I don't know how to use it because it's not the same source as macOS, all right

**Comment by benben-hello** [comment]
> This doesn't make sense to me. Explain what you are experiencing more clearly, thanks.
I know why it can't be used. Today, I created a new swift project, which can be used, but it can't be used in Objective-C project. Is there any missing @obJc keyword?
