### ISSUE TITLE
Occasional crashing after AppleSampler.stop()

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/AudioKit#2297]
I have a bunch of AppleSamplers, loaded with single wav file. 
10% times, after I stop the samplers, the app crashes with this:
I;m on yesterday's v5-develop, ios14.2 beta, xcode 12.2 beta 2.

CoreAudio/DspBase.mm line 124 with AURemoteIO::IOThread (23): EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

    if (pullInputBlock) {
            if (bCanProcessInPlace && inputBufferLists.size() == 1) {
                // pull input directly to output buffer
                inputBufferLists[0] = outputData;
                AudioUnitRenderActionFlags inputFlags = 0;
               - here --->>  pullInputBlock(&inputFlags, timestamp, frameCount, 0, inputBufferLists[0]);
            }

There's a single line from the app log: Not sure where this is even coming from.

MyApp[38441:914469]  Illegal decrement of empty layer bin count

**Comment by aure** [comment]
Would definitely need an example app to test this.  I'll close until that can be provided.
