### ISSUE TITLE
Package Manager error

### ISSUE THREAD

**Issue by JamieScanlon** [AudioKit/AudioKit#2301]
When I try to add AudioKit as a dependency via Swift Package Manager I get the following error:
Package Resolution Failed
"AudioKit.git" could not be resolved:
https://github.com/AudioKit/AudioKit.git has no Package.swift manifest for version 4.11.2

Steps:
"+" Add the package using the url https://github.com/AudioKit/AudioKit
Version: Up to 4.11.2 < 5.0.0

Workaround:
"+" Add the package using the url https://github.com/AudioKit/AudioKit
Branch: v5-master

**Comment by romancfischer** [comment]
+1

**Comment by aure** [comment]
This is expected behavior for now.  v5 is not released, so you can't use it without branch declaration. I've updated the README so others don't get this and think its an issue.

**Comment by romancfischer** [comment]
@aure Thanks Aure, but the problem isn't Version >= 5. The problem is that v4 can not be installed via Swift Package Manager, regardless of branch declaration.

**Comment by megastep** [comment]
SPM was added starting in version 5, so this is just not possible with v4.

**Comment by romancfischer** [comment]
@megastep oh I see. Sorry, my mistake.
