### ISSUE TITLE
Merging AudioKit with AudioKitUI really a good idea?

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#2304]
Hey, 

I have read the following statement

> No longer need to import AudioKitUI. Whatever user interface elements we provide will be in AudioKit

In the [migration guide](https://github.com/AudioKit/AudioKit/blob/v5-master/docs/MigrationGuide.md) .

I am wondering if its really a good idea to merge everything together. I am using AudioKit in quite some projects, but to be honest the sheer size of the framework is always a reason to evaluate other possibilities. When i now imagine that AudioKitUI will be merged into AudioKit framework, i am scared.

Are you guys sure this is a good idea?

**Comment by aure** [comment]
Yes we are sure. AudioKitUI was tiny and is only smaller now.

**Comment by transat** [comment]
So... do I still need to import AudioKitUI or not?? The migration guide now says "AudioKitUI is now a separate package that has AudioKit as a dependency."

**Comment by aure** [comment]
Hi, so yeah, we had intended to merge AudioKitUI to AudioKit, but then decided against it and instead made it its own package with its own GitHub repo. So, you do have to import AudioKitUI after all, in addition to including it as a swift package dependency.
