### ISSUE TITLE
Fatal error throwing empty initializers should be removed 

### ISSUE THREAD

**Issue by warpling** [AudioKit/AudioKit#2307]
**Describe the bug**
Many Node types like `WhiteNoise` can no longer be initialized with an empty initializer like `WhiteNoise()` yet this is allowed at compile time and only detectable when run and a fatal error is thrown at run time.

**To Reproduce**
Use an initializer like `WhiteNoise()`

**Expected behavior**
Unsupported initializer should be removed or have better guardrails or guidance added to them.

**Additional context**
This applies to the latest AK4 release as well.

**Comment by aure** [comment]
Latest AK4 release "as well" What do you mean by "as well"? Is this happening elsewhere?

**Comment by warpling** [comment]
On my AK5 build this doesn't raise any compile time issues but seemed to crash at runtime. The same was true with my AK4 build.

**Comment by aure** [comment]
This does not seem to be the case in the Cookbook's NoiseGenerators Recipe: https://github.com/AudioKit/Cookbook/blob/main/Cookbook/Cookbook/Recipes/NoiseGenerators.swift#L14

Runs just fine, so what's different on your system.

**Comment by aure** [comment]
@megastep seems to be a big headache for v4. As for V5, I'll close this issue until more information comes in.

**Comment by warpling** [comment]
Here is on 4.11.2 
<img width="766" alt="image" src="https://user-images.githubusercontent.com/220240/96778409-f4309900-13eb-11eb-8080-acc08b13df3f.png">

Switching from `WhiteNoise()` to `WhiteNoise(amplitude: 0.5)` stopped the crash.

I thought I had tested with with AK5 and observed the same but may be been confused. I'll double-check as soon as I can but I recommend reopening this issue since many will continue to stay on AK4 until AK5 is stable and this does appear to be a regression.

**Comment by aure** [comment]
This never happened on 5. I seem to remember something like this with objective-C.

**Comment by megastep** [comment]
This somehow started to happen when switching from regular universal frameworks to XCFrameworks. Really not too clear on what would trigger this.
