### ISSUE TITLE
AudioPlayer's isPlaying is not updating correctly

### ISSUE THREAD

**Issue by warpling** [AudioKit/AudioKit#2309]
Buffer an AudioPlayer, play it, observe that `isPlaying` is still true after the file/buffer is done playing.

**Comment by aure** [comment]
Its returning avaudioplayer isPlaying property, so it might a bug in Apple's code.

**Comment by ryanfrancesconi** [comment]
the node's isPlaying property isn't right for this use. The AudioPlayer should keep it's own state flag and update based on play, stop or completionHandler completion. The AudioPlayer should install it's own completionHandler on the schedule call

**Comment by ryanfrancesconi** [comment]
@warpling you can wrap this player and install your own completion too in the schedule. just don't make any UI calls from that callback without passing it to main

**Comment by warpling** [comment]
Gotcha. This property is pretty badly named eh? I guess it just means the node is connected and active?

@ryanfrancesconi Do you happen to know if a looping node calls its completion handler at the end of each loop?

**Comment by ryanfrancesconi** [comment]
buffer looping doesn't no. at least that's my memory of it

**Comment by aure** [comment]
Check out the new AudioPlayer @warpling

**Comment by ryanfrancesconi** [comment]
> Gotcha. This property is pretty badly named eh? I guess it just means the node is connected and active?
> 
> @ryanfrancesconi Do you happen to know if a looping node calls its completion handler at the end of each loop?

so yeah, the new player will call a completion on each loop UNLESS it is buffer looping. no callbacks are given in that case. Callbacks are not returned on the main thread so plan accordingly! @warpling 

though you prob have your own player by now.

**Comment by warpling** [comment]
Thanks @ryanfrancesconi! I'll try this out soon. Would it be possible to add a completion handler for the end of each loop? I have haptic files that need to be retriggered with each loop.

**Comment by ryanfrancesconi** [comment]
it's not possible with buffer looping, but it will already do it if it's not buffered.

**Comment by warpling** [comment]
Okay great, I'll check that out. Will there be performance losses if it's not buffered and it's a 30s loop?

**Comment by ryanfrancesconi** [comment]
@warpling i'd say no, but the loop could have a very small gap. another option is to buffer it, catch the completion yourself and restart it. that is basically the same thing that happens in the case of isLooping and not buffered.

The advantage of the no completion handler is that it's seamless so there is no end event. it's indefinite.

**Comment by ryanfrancesconi** [comment]
note these are just some conveniences on top of AVAudioPlayerNode. to that end, the node itself is public so you can do the schedule yourself if you want.

**Comment by warpling** [comment]
Got it. I guess I'll try to make it buffered, restart it myself, and see if there is a gap.
