### ISSUE TITLE
Failed to add swift package to project in Xcode 12

### ISSUE THREAD

**Issue by zhouhao27** [AudioKit/AudioKit#2310]
**Confirm you should be adding the bug here**
If your issue is implementing AudioKit in your own code, post your problem to [StackOverflow](https://stackoverflow.com/search?q=AudioKit) with the #AudioKit hashtag.

If you can make the issue happen on [AudioKit 5's Cookbook app](https://github.com/AudioKit/Cookbook/) then you can create an issue directly on that repository as well.

GitHub Issues should only be used for confirmed problems with AudioKit and
well-defined feature requests.

Sponsors will get more attention: https://github.com/sponsors/aure

**Describe the bug**
Failed to add swift package to project in Xcode 12. 

**To Reproduce**
1. Go to 'File'
2. Click on 'Swift Packages'
3. Click on 'Add Package Dependency'
4. Add AudioKit GitHub url

<img width="720" alt="Screenshot 2020-10-22 at 5 42 14 PM" src="https://user-images.githubusercontent.com/8099731/96855254-0ca5bf80-148f-11eb-93de-e4e497bb14b5.png">

**Expected behavior**
Should be able to add the package

**Screenshots**
Got the following error message:

<img width="703" alt="Screenshot 2020-10-22 at 5 47 51 PM" src="https://user-images.githubusercontent.com/8099731/96855305-1cbd9f00-148f-11eb-99c3-35eed04e07a0.png">

**Details (please complete the following information):**
 - Type: Mac
 - OS: Big Sur
 - AudioKit Version 4.11.2

**Additional context**

**Comment by aure** [comment]
Use the branch v5-main or v5-develop like it says in the readme file.
