### ISSUE TITLE
Is it possible to reduce the size of Swift package?

### ISSUE THREAD

**Issue by zhouhao27** [AudioKit/AudioKit#2311]
**Is your feature request related to a problem? Please describe.**
It will take very long time to add the Swift Package to the project because the size is too big. It's about 500MB if I'm not wrong.

**Describe the solution you'd like**
Is it possible to reduce the size of the Swift package?

**Describe alternatives you've considered**

**Assign yourself to this task**
AudioKit maintainers are not here to do your work for you, so if you can assign yourself to the feature request, that would be ideal.

**Additional context**

**Comment by aure** [comment]
My understanding is that SPM is making a git copy of the repo, so its pretty big. Perhaps we could have another URL for a lighter version of the Swift Package that doesn't have all the history.

**Comment by warpling** [comment]
Perhaps there are some hidden large files in the git history that could be removed?

**Comment by aure** [comment]
I don't think there's that many bad files added, maybe a few megabytes of audio in the examples. Its just a what, 6 year history of development? Adds up. I wonder if it will be more efficient once we can specify a version, instead of a branch? What do you think @megastep ?

**Comment by megastep** [comment]
A git clone is a git clone, whether or not you specify a tag. I'm not sure if there's a way to selectively check out the commits, and whether Xcode would even do that.

**Comment by aure** [comment]
I guess if you don't wan the overhead you'll need to use a local copy of the repository.

**Comment by warpling** [comment]
For the record or anyone interested, here's a list of files over 1Mb in the git history:
Size | File
--- | ---
1002KiB | AudioKit/macOS/AudioKit for macOS/Playgrounds/Processing.playground/Resources/counting.wav
1018KiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.0MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.0MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.0MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.0MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.0MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.0MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.0MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.0MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.0MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.0MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.0MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | Examples/iOS/SwiftSynth/SwiftSynth/Assets.xcassets/Brand Assets.launchimage/launchimage@2x.png
1.1MiB | Examples/iOS/SwiftSynth/SwiftSynth/Assets.xcassets/Brand Assets.launchimage/launchimage@2x.png
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/iOS/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/iOS/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.1MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | AudioKit/AudioKit.xcodeproj/project.pbxproj
1.2MiB | Examples/iOS/SwiftSynth/SwiftSynth/Assets.xcassets/controls_guide.imageset/controls_guide@2x.png
1.2MiB | Examples/iOS/SwiftSynth/SwiftSynth/Assets.xcassets/controls_guide.imageset/controls_guide@2x.png
1.2MiB | Examples/iOS/SwiftSynth/SwiftSynth/Assets.xcassets/controls_guide.imageset/controls_guide@2x.png
1.2MiB | Examples/iOS/AnalogSynthX/AnalogSynthX/Assets.xcassets/controls_guide.imageset/controls_guide@2x.png
1.2MiB | Examples/iOS/SwiftSynth/SwiftSynth/Assets.xcassets/controls_guide.imageset/controls_guide@2x.png
1.2MiB | Examples/iOS/SwiftSynth/SwiftSynth/Assets.xcassets/controls_guide.imageset/controls_guide@2x.png
1.2MiB | Examples/iOS/AnalogSynthX/AnalogSynthX/Assets.xcassets/controls_guide.imageset/controls_guide@2x.png
1.2MiB | AudioKit/Platforms/OSX/CsoundLib.framework/libs/libsndfile.1.dylib
1.6MiB | Frameworks/DragAndDropFrameworks.gif
1.6MiB | Developer/AKSampler/Windows VST2 Plugin/libsndfile/32-bit/libsndfile-1.dll
1.6MiB | AudioKit/OSX/AudioKit/Playgrounds/AudioKit for OSX.playground/Resources/808loop.wav
1.7MiB | Developer/AKSampler/Windows VST2 Plugin/libsndfile/64-bit/libsndfile-1.dll
1.7MiB | Tests/AudioKitTests/Resources/PinkNoise.wav
1.8MiB | AudioKit/iOS/AudioKit/AudioKit.playground/Resources/poney.mp3
1.8MiB | Examples/PlayerDemo/PlayerDemo/Resources/PinkNoise.wav
1.9MiB | AudioKit/Platforms/tvOS/libsndfile.framework/libsndfile
1.9MiB | AudioKit/Platforms/tvOS/libsndfile.framework/libsndfile
2.2MiB | AudioKit/Platforms/iOS/libsndfile.framework/libsndfile
2.2MiB | AudioKit/Platforms/iOS/CsoundLib.framework/libs/libsndfile.1.dylib
2.2MiB | AudioKit/Platforms/iOS/libsndfile.framework/libsndfile
2.3MiB | AudioKit/OSX/AudioKit/Playgrounds/AudioKit for OSX.playground/Resources/PianoBassDrumLoop.wav
2.6MiB | AudioKit/iOS/AudioKit/AudioKit.playground/Resources/poney.mp3
2.9MiB | Playgrounds/AudioKitPlaygrounds/Playgrounds/Effects.playground/Resources/poney.mp3
3.0MiB | AudioKit/Platforms/iOS/libs/libsndfile.a
3.1MiB | Playgrounds/AudioKitPlaygrounds/Playgrounds/Effects.playground/Pages/Rhino Guitar Processor.xcplaygroundpage/Resources/guitar.wav
3.8MiB | AudioKit/Platforms/iOS/libsndfile.framework/libsndfile
4.0MiB | AudioKit/Resources/AKSoundFiles.bundle/Sounds/GeneralMidi.sf2
4.2MiB | AudioKit/Platforms/OSX/CsoundLib.framework/libs/libvorbisenc.2.dylib
4.5MiB | AudioKit/Platforms/OSX/CsoundLib64.framework/Versions/6.0/CsoundLib64
4.6MiB | csound-iOS/libs/libsndfile.a
4.6MiB | AudioKit/Platforms/OSX/CsoundLib.framework/Versions/6.0/CsoundLib
4.6MiB | AudioKit/Platforms/OSX/CsoundLib.framework/Versions/6.0/CsoundLib
4.8MiB | AudioKit/Platforms/OSX/CsoundLib.framework/Versions/6.0/CsoundLib
4.8MiB | AudioKit/Platforms/OSX/CsoundLib.framework/Versions/6.0/CsoundLib
4.8MiB | AudioKit/Platforms/OSX/CsoundLib.framework/Versions/6.0/CsoundLib
4.8MiB | AudioKit/Platforms/OSX/CsoundLib.framework/Versions/6.0/CsoundLib
4.8MiB | AudioKit/Platforms/OSX/CsoundLib.framework/Versions/6.0/CsoundLib
4.8MiB | AudioKit/Platforms/OSX/CsoundLib.framework/Versions/6.0/CsoundLib
4.8MiB | AudioKit/Platforms/OSX/CsoundLib.framework/Versions/6.0/CsoundLib
4.9MiB | AudioKit/Platforms/OSX/CsoundLib.framework/Versions/6.0/CsoundLib
5.3MiB | csound5-iOS/libs/libsndfile.a
6.2MiB | csound5-iOS/libs/libcsound.a
6.4MiB | csound-iOS/libs/libcsound.a
6.5MiB | csound-iOS/libs/libcsound.a
6.6MiB | csound-iOS/libs/libcsound.a
6.8MiB | AudioKit/Platforms/iOS/libs/libsndfile.a
8.8MiB | Examples/iOS/MicrophoneAnalysis/AudioKit.framework/AudioKit
9.9MiB | AudioKit/Platforms/iOS/CsoundLib.framework/CsoundLib
10MiB | AudioKit/Platforms/iOS/CsoundLib.framework/CsoundLib
10MiB | AudioKit/Platforms/iOS/CsoundLib.framework/CsoundLib
10MiB | AudioKit/Platforms/iOS/CsoundLib.framework/CsoundLib
10MiB | AudioKit/Platforms/iOS/CsoundLib.framework/CsoundLib
10MiB | AudioKit/Platforms/iOS/CsoundLib.framework/CsoundLib
10MiB | csound-iOS/libs/libsndfile.a
10MiB | AudioKit/Platforms/iOS/CsoundLib.framework/CsoundLib
10MiB | AudioKit/Platforms/iOS/CsoundLib.framework/CsoundLib
11MiB | AudioKit/Platforms/tvOS/CsoundLib.framework/CsoundLib
12MiB | AudioKit/Libraries/iOS/csound-iOS/libs/libcsound.a
13MiB | AudioKit/Platforms/iOS/libs/libcsound.a
13MiB | AudioKit/Platforms/iOS/libs/libcsound.a
14MiB | AudioKit/Platforms/iOS/libs/libcsound.a
14MiB | AudioKit/Platforms/iOS/libs/libcsound.a
14MiB | AudioKit/Platforms/iOS/libs/libcsound.a
14MiB | AudioKit/Platforms/iOS/libs/libcsound.a
14MiB | AudioKit/Platforms/iOS/libs/libcsound.a
21MiB | AudioKit/Platforms/iOS/CsoundLib.framework/CsoundLib
23MiB | AudioKit/Platforms/iOS/libs/libsndfile.a
39MiB | AudioKit/Platforms/iOS/libs/libcsound.a

(generated using [this](https://stackoverflow.com/a/42544963/522498))

**Comment by megastep** [comment]
Ouch, I'm not sure how these old Csound libraries still ended up here? I thought we started a new repo when we ditched it?
Really any binary archive should be purged if we can.

**Comment by warpling** [comment]
I recently used [BFG](https://rtyley.github.io/bfg-repo-cleaner/) to remove some large blobs from a repo of mine. We could run this with AK to remove these. Not sure if there are any consequences to needing to force push after.

**Comment by megastep** [comment]
I used BFG on the former AudioKit v3 repo a while back, so not completely unprecedented. The main consequence is obviously these files are no longer available there, but I think we can live with that.

**Comment by warpling** [comment]
Yeah I'm all for maintaining a working history and all but maybe it's safe enough to assume anything pre v3 or something is safe to remove? Could always create a fork to archive an official snapshot so just in case? 200-300Mb+ savings seems fairly worthwhile.

**Comment by aure** [comment]
Given how difficult it is to get old version of AudioKit running on modern os's and Xcode, I'm not worried about old stuff.  I'd love to get rid of all those >1MB files. Thanks @warpling

**Comment by megastep** [comment]
Well I have just used BFG to remove all these old binary files and I'm not sure it completely succeeded in pushing back here (got a bunch of errors in reference to pull request branches). In any event, we should all do a clean clone to get rid of these old files in our local copies and preventing them from being pushed again.

The size of the repo after checking it out from scratch here seems to have gone down significantly though, by almost half.

**Comment by aure** [comment]
The repo is significantly smaller now for fresh clones, so I'd call this issue addressed.

**Comment by warpling** [comment]
What's the best way to pull/merge after these changes? I think I might need to obliterate all my local branches but maybe that's not the case and we can document how to do this for future readers?

**Comment by warpling** [comment]
**Update**: Turns out the issue was branch naming. `master` disappeared which totally confused me when reconfiguring my remotes. The solution for me was essentially to delete all branches, and re-check them out and pull them, with a `git remote prune upstream` for good measure.
