### ISSUE TITLE
Question: Minimum deployment target of iOS 12.0

### ISSUE THREAD

**Issue by mortenkleveland** [AudioKit/AudioKit#2312]
Hi, I am trying to update an existing app to v5-main, but get this error:

<img width="982" alt="Skjermbilde 2020-10-27 kl  08 19 12" src="https://user-images.githubusercontent.com/3432898/97269012-1fbce480-182d-11eb-969f-591b9ade4b7a.png">

I understand that v5 is not out of beta yet, but do you plan to support iOS versions < 12 when it is finished?

**Comment by megastep** [comment]
I'm not really sure if we could lower the requirement to iOS 11, it was at that point not long ago... Just need to make sure that some of the APIs are not accessible on earlier versions if applicable.

**Comment by aure** [comment]
https://www.digitaltrends.com/mobile/ios-distribution-news/ and that was a year ago.

**Comment by megastep** [comment]
Yeah but at the same time I'm of the opinion that this kind of decision should be left up to the app developers, who each have their own requirements for targeting users. Global stats are fine and dandy, but there are plenty of cases where you do need to cover people stuck with older devices that can't get the latest OS.

For the frameworks we provide, unless there's an absolutely compelling reason (like we now rely on new AVFoundation APIs throughout AK), we should leave the OS requirement as low as we can get away with IMHO, especially if it's just a matter of changing a few lines here and there. Then leave it up to the app developers to decide which version they want to target for their users.

**Comment by ryanfrancesconi** [comment]
Yes i agree with @megastep 
it's easy enough in most cases to target the lower release number and use #available if the newer API is available. Unless it's a mission critical thing.

**Comment by aure** [comment]
Of course we'd all like AudioKit to be as backwards compatible as we can, but it gets very difficult to test on older iOSes anyway, so we could just be having the appearance of functionality while still delivering a broken product on those older operating systems. Any effort and help to keep the minimum requirements low will be embraced with open arms, I just won't be putting a lot of my own time into such things.

**Comment by ryanfrancesconi** [comment]
I did roll back the latest develop to mac OS 10.13 for this reason. but I'm not developing for iOS, so don't have so much interest in making changes there.

**Comment by aure** [comment]
@ryanfrancesconi  Yep, others can step for iOS back compatibility.

**Comment by megastep** [comment]
I don't think the ability to test is that important here, as long as the CI tests pass. It is kinda up to the app developers to test their apps on the full range of versions they claim to support. 

As far as the framework is concerned, we really only need to mark APIs that may not be available on older versions. The assumption (however imperfect given Apple's track record) is that the same code should work similarly on older OS versions, and that should be good enough for the vast majority of cases.

**Comment by ryanfrancesconi** [comment]
it does look to me that all apis used are in iOS11. no?

**Comment by aure** [comment]
Possibly.

**Comment by ryanfrancesconi** [comment]
it does build fine for v11. not for v10 due to engine rendering modes.

**Comment by aure** [comment]
You can commit the iOS11 target if it works and passes tests.
