### ISSUE TITLE
No way to initialize AKFFTTap in Objective-C

### ISSUE THREAD

**Issue by OscarCybernetic** [AudioKit/AudioKit#2313]
I don't know if you still accept bug reports for version 4 of AudioKit, but I encountered this in version 4.11.2

The init method in AKFFTTap.swift is missing the `@objc` flag and so it's not revealed to Objective-C code
`public init(_ input: AKNode, fftSize: AKSettings.BufferLength = .veryLong)`

This results in AudioKit-Swift.h not having an init method that can be used for AKFFTTap
```/// FFT Calculation for any node
SWIFT_CLASS("_TtC8AudioKit8AKFFTTap")
@interface AKFFTTap : NSObject <EZAudioFFTDelegate>
/// Array of FFT data
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull fftData;

- (void)fft:(EZAudioFFT * _Null_unspecified)fft updatedWithFFTData:(float * _Nonnull)fftData bufferSize:(vDSP_Length)bufferSize;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end
```

I was able to fix this on my end by adding `@objc` onto the Swift method, which then added the init method to AudioKit-Swift.h. I was able to successfully initialize the tap and get spectral data

In AKFFTTap.swift:
`@objc public init(_ input: AKNode, fftSize: AKSettings.BufferLength = .veryLong)`

After building the framework, resulted in this block of code in AudioKit-Swift.h:
```/// FFT Calculation for any node
SWIFT_CLASS("_TtC8AudioKit8AKFFTTap")
@interface AKFFTTap : NSObject <EZAudioFFTDelegate>
/// Array of FFT data
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull fftData;
/// Initialze the FFT calculation on a given node
/// \param input Node on whose output the FFT will be computed
///
/// \param fftSize The sample size of the FFT buffer
///
- (nonnull instancetype)init:(AKNode * _Nonnull)input fftSize:(enum BufferLength)fftSize OBJC_DESIGNATED_INITIALIZER;
- (void)fft:(EZAudioFFT * _Null_unspecified)fft updatedWithFFTData:(float * _Nonnull)fftData bufferSize:(vDSP_Length)bufferSize;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end
```

**Comment by aure** [comment]
Actually you're welcome to make a PR onto the v4-develop branch.  v5 is not really supporting objc at all.
