### ISSUE TITLE
AudioKit.Settings.playbackWhileMuted = true does not work

### ISSUE THREAD

**Issue by ioswald** [AudioKit/AudioKit#2316]
**Describe the bug**
playbackWhileMuted set to true does not work when phone is in silent mode

**To Reproduce**
`
    let engine = AudioEngine()
    var oscillator1 = Oscillator()
    var mixer = Mixer()
    let pinkNoise = PinkNoise(amplitude: 1.0)
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        mixer = Mixer(oscillator1, pinkNoise)
        oscillator1.frequency = 1000

        // Cut the volume in half since we have two oscillators
        mixer.volume = 1.0
    }
    
    // MARK: - View Controller Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        engine.output = mixer
        
        AudioKit.Settings.playbackWhileMuted = true
        do { try engine.start() }
        catch { logFile.writeLine("AudioKit did not start!") }
        viewStartFrequency.clampValue = true
        viewStartFrequency.value = 1000
        
        viewEndFrequency.clampValue = true
        viewEndFrequency.value = 10000
        
        viewDuration.clampValue = false
        viewDuration.value = 10
        let mPlot = NodeOutputPlot(engine.output!, frame: CGRect(x: 0, y: 0, width: plot!.frame.width, height: plot!.frame.height))
        mPlot.color = UIColor(red: 242/255, green: 212/255, blue: 37/255, alpha: 1)
        mPlot.backgroundColor = .black
        plot?.addSubview(mPlot)
        plot?.backgroundColor = .black
    }`

**Expected behavior**
oscillator/pink noise should play on oscillator1.start()/pinkNoise.start() when phone is in silent mode.

**Details (please complete the following information):**
 - Type: iPhone 11 Pro.
 - OS: 14.0.1
 - AudioKit Version: v5-Main, 
 - Commit ID: 329db67f8156b0d068431aceb0c8fac244c6edfd [329db67f8]

**Comment by warpling** [comment]
I believe `AudioKit.Settings.playbackWhileMuted` is only used when when the audio session category is not `PlayAndRecord` (which is the default). I also don't think AK automatically changes the session/category info when AKSettings are changed (something to consider changing?).
