### ISSUE TITLE
Can't sample rate to other than 44100:  engine fails to start with Code=-10868

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/AudioKit#2317]
Is there a way to set sample rate to native sample rate? Every try I've tried has failed on v5-main and v5-develop. the engine doesn't start basically.

I use cookbook and add a few lines of code to change the sample rate and the code failes because engine doesn't start: 

Cookbook[6261:307347] [general] AmplitudeEnvelope.swift:start():54:Error Domain=com.apple.coreaudio.avfaudio Code=-10868 "(null)" UserInfo={failed call=err = AUGraphParser::InitializeActiveNodesInOutputChain(ThisGraph, kOutputChainOptimizedTraversal, *GetOutputNode(), isOutputChainActive)} (AmplitudeEnvelope.swift:start():54)

Changes are made to Cookbook/AmplitudeEnvelope.swift:

   import AVFoundation,

and then in init(): 

   init() {

/// ***** added this line to change sample rate to native sample rate for iphone 8plus.
        Settings.audioFormat = AVAudioFormat(
                        standardFormatWithSampleRate: 48000,
                        channels: 2)!

        env = AmplitudeEnvelope(osc)
        plot = NodeOutputPlot(env)
        plot.plotType = .rolling
        osc.amplitude = 1
        engine.output = env
    }

If 48000 is replaced by 41000, things work. 
How do I change the sample rate to native then? converting to a lower sample rate will unecessaryily waste cpu right and create delays right? 

Please help sir!
Aloha
Qr

**Comment by olcaydaser** [comment]
kAudioUnitErr_FormatNotSupported error thrown also here. 
Is there a proper solution for these?

**Comment by ryanfrancesconi** [comment]
Yes, you have the right idea. Settings.audioFormat is the correct method at the moment. That said, there was an issue that was preventing the main engine mixer from using it, and it was stuck at the 44.1k default. It should now work (on v5-develop) to set to 48k. 

You must set the sample rate before you create any nodes. To change the sample rate while your app is running you need to tear down your graph and rebuild it.

Some things in the Cookbook may be making assumptions about the sample rate which this global variable might break. We're checking that out - but for the moment it's closer to working correctly outside of the Cookbook.

**Comment by quantamrhino** [comment]
I just tried with v5-develop and setting a diffrent sample rate works.
You are awesome @ryanfrancesconi !! many many thanks!  

My followup question is about the inputNode.
if I use a mic and the sample rate changes and I try to reattach the mic, it crashes with the same error. (prob a sample rate mismatch).
What's the recommended way to deal with sample rate changes on the input note? if the sample rate changes, setting the Settings.audioformat is sufficient to change the session's sample rate. without recreating the graph that is

e.g. I have a mixer node that's tied into the graph. Then, i can attach a mic at a later point (through user action). if the route (rather the sample rate hasn't changed). the mic attach and then the removal works.

**Comment by aure** [comment]
Github Issues and "follow up questions" aren't really compatible. The issue is now closed. If there is a related issue please just create a new one, thanks.

**Comment by ryanfrancesconi** [comment]
Yes the input still needs the fix.
