### ISSUE TITLE
License issue - LGPL contamination because of Csound code

### ISSUE THREAD

**Issue by ufoq** [AudioKit/AudioKit#2318]
AudioKit has MIT license, however I see there are parts of code like this:
https://github.com/AudioKit/AudioKit/blob/329db67f8156b0d068431aceb0c8fac244c6edfd/Sources/soundpipe/modules/eqfil.c#L4

There you claim that you base something on LGPL-licensed code, doesn't it *contaminate* whole lib?

**Comment by aure** [comment]
Thanks for bringing this up. We switched from Csound to Soundpipe which licensed itself as MIT duet massive substantive changes over Csound. Paul's wording here is unfortunate.
