### ISSUE TITLE
Implement Swing in Sequencer

### ISSUE THREAD

**Issue by LawrenceNorman** [AudioKit/AudioKit#2324]
**Is your feature request related to a problem? Please describe.**
Swing seems like it would be a great addition to AKSequencer.  
Tone.js has this, and it really adds a lot of flavor to your sequences!
Swing : https://github.com/Tonejs/Tone.js/blob/641ada9f09bc569cd937ca0da05771b16b2d0740/Tone/core/clock/Transport.ts#L498 
https://tonejs.github.io/docs/14.7.58/type/Subdivision
swing # NormalRange
The swing value. Between 0-1 where 1 equal to the note + half the subdivision.
Defined in: Tone/core/clock/Transport.ts
swingSubdivision # Subdivision
Set the subdivision which the swing will be applied to. The default value is an 8th note. Value must be less than a quarter note.

**Describe the solution you'd like**
Can we we get some Swing into our Sequencer?  Ala the way Tone does it:
 https://github.com/Tonejs/Tone.js/blob/641ada9/Tone/core/clock/Transport.ts#L511

private _processTick(tickTime: Seconds, ticks: Ticks): void {
// handle swing
if (this._swingAmount > 0 &&
ticks % this._ppq !== 0 && // not on a downbeat
ticks % (this._swingTicks * 2) !== 0) {
// add some swing
const progress = (ticks % (this._swingTicks * 2)) / (this._swingTicks * 2);
const amount = Math.sin((progress) * Math.PI) * this._swingAmount;
tickTime += new TicksClass(this.context, this._swingTicks * 2 / 3).toSeconds() * amount;
}
// do the loop test
if (this._loop.get(tickTime)) {
if (ticks >= this._loopEnd) {
this.emit("loopEnd", tickTime);
this._clock.setTicksAtTime(this._loopStart, tickTime);
ticks = this._loopStart;
this.emit("loopStart", tickTime, this._clock.getSecondsAtTime(tickTime));
this.emit("loop", tickTime);
}
**Describe alternatives you've considered**
If I've missed this somewhere or if someone has an example of Swing using AudioKit I'd be glad to see the Sample code but I haven't found it yet.

**Assign yourself to this task**
I'm a bit new to AudioKit Dev, but if I find down the road I have to implement this I'll try to add this, but it would seem like a big benefit to the community.  So I thought I ask here first.

**Comment by aure** [comment]
So, I'm not so convinced that this would be good to add at the AudioKit level. I think if you're writing a notation program or sequence generator, you should have the swing as part of your code and then just place the notes where they ought to be in time. If you do create something generic to be of general purpose to everyone, I'd happily look at a pull request for that.
