### ISSUE TITLE
Engine input node needs sample rate handling

### ISSUE THREAD

**Issue by ryanfrancesconi** [AudioKit/AudioKit#2326]
From @quantamrhino :

if I use a mic and the sample rate changes and I try to reattach the mic, it crashes with the same error. (prob a sample rate mismatch).
What's the recommended way to deal with sample rate changes on the input note? if the sample rate changes, setting the Settings.audioformat is sufficient to change the session's sample rate. without recreating the graph that is

e.g. I have a mixer node that's tied into the graph. Then, i can attach a mic at a later point (through user action). if the route (rather the sample rate hasn't changed). the mic attach and then the removal works.

**Comment by quantamrhino** [comment]
Thank you! was just filing another issue when saw this. 
Many thanks for making these amazing changes. I was going crazy trying to find a way that this works and have spun my wheels for a day and half, no luck. :-(

**Comment by ryanfrancesconi** [comment]
no worries! actually, i'm going to try to look at this now. will update here.

**Comment by quantamrhino** [comment]
Fabulous! 
<Insert "Not all heroes wear capes meme" here>

Aloha!

**Comment by ryanfrancesconi** [comment]
can you post the code you were trying?

**Comment by quantamrhino** [comment]
I've tried to carve out a new barebones project with the issue.
But am running into another problem. Can I email you the code?

**Comment by ryanfrancesconi** [comment]
you can attach it here as a zip

**Comment by quantamrhino** [comment]
I've not been able to repro the crash with my barebones code yet because i'm hitting another issue. perhaps unrelated.
I'm attaching the code. hopefully this code can be tweaked into a repro.

see comment above Audio.swift -> attachMic() 

[audiokitMicAttachIssue.zip](https://github.com/AudioKit/AudioKit/files/5514981/audiokitMicAttachIssue.zip)

**Comment by aure** [comment]
As this issue has become fairly old and so many changes have happened in AudioKit since then, I'm going to close it and see if a new issue can be created with a more directed problem.
