### ISSUE TITLE
static audio graph of 6 nodes, no sound, memory leak. code attached.

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/AudioKit#2328]
I've hit upon an odd situation that needs a few things to hit. In my experiemnts trying to figure out a fast growing memory issue that kills my app in 20 min or so.

I've attached the code (xcode 12.2 RC build) on simulator and device running 14.2 release build.
There was another mem leak on mixers etc on dynamic graph but this is a static graph with no changes. There's no sound playing and the app memory increases over time. The more complex the graph, the faster the leak.

I wanted to see if this is an apple or audiokit issue, but so far, i'm not sure, though given that there' no other report like this out there, could be v5 branch changes.

It's certainly an odd one. needs a few things happening that exacerbates it. I can't see the pattern. small changes to the graph and the memory doesn't leak. I have no insight in the deep down code that audiokit uses. 

[audiokit-leak-autoreleasepool.zip](https://github.com/AudioKit/AudioKit/files/5518003/audiokit-leak-autoreleasepool.zip)

        // This leaks memory in autoreleasepool. Lots of increasing
        //  AUAudioUnitV2Bridge_Renderer thingys, 4KB each,
        //
        // From my experimentation, these things are needed to make the memory leak happen:
        //  - mic input
        //  - setPreferredIOBufferDuration
        //  - 3 or more things in a chain
        // with a more complex graph, there's a much more severe leak. I've a graph that creates
        // a 1 MB per minute leak! The app dies in about 20 min.

**Comment by quantamrhino** [comment]
I'm on the v5-develop branch btw.

**Comment by aure** [comment]
I have downloaded and tried the project. I don't have an answer yet, but I wanted to extend the conversation with my observations.

When I view the app in the simulator and look at the memory usage, it does go up. If I put it through the Profiler for Memory leaks, there are a few but none of them seem AudioKit related per se:  

![image](https://user-images.githubusercontent.com/13122/98852995-59851200-240d-11eb-8154-bb317ed6099a.png)

They also happen exactly once at the beginning of the app but not again.

When I run the app on a device (iPhone X), the way the memory usage increase goes from being chunks every minute or so to a little bit all the time, linearly increasing. 

When I profile the app on the device, the profile is showing zero memory leaks.

So I don't think the increase of memory usage is a leak per se. 

You're right that all the memory is stuck in the autorelease pool:

![image](https://user-images.githubusercontent.com/13122/98854847-f648af00-240f-11eb-921a-28b5ef78c0e1.png)

We might have to make this happen with out AudioKit just using AVAudioEngine and then file a bug with Apple. This wasn't happening before AK5 so it still is probably our mistake somewhere.

**Comment by themichael123** [comment]
We are seeing the same issue with AudioKit 4.11.2.

**Comment by aure** [comment]
@themichael123 Project link to it happening in 4.11.2 please.

**Comment by themichael123** [comment]
@aure Please find a sample project attached. 
[AKTEST.zip](https://github.com/AudioKit/AudioKit/files/5781956/AKTEST.zip)

Thank you.

**Comment by wtholliday** [comment]
No repro on iOS 14.5.1 / AK 5.1.

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/841144/118404978-20329680-b62a-11eb-9ccc-d092c9fcb851.png">

Had to comment out these lines for it to compile:
```
        Settings.audioInputEnabled = true
        Settings.defaultToSpeaker = true
        Settings.playbackWhileMuted = true
        Settings.allowAirPlay = true
```

Closing. Reopen if you can repro.
