### ISSUE TITLE
AURemoteIO.h error with simulator

### ISSUE THREAD

**Issue by hoopes** [AudioKit/AudioKit#2331]
Trying to create a hello-world with AK5. I started a new SwiftUI project, which just has the default `Hello, world!` on the white screen. Here is the entirety of my App.swift:

```
import SwiftUI
import AudioKit

class AKTest {

    init() {
        let engine = AudioEngine()
        let noise = WhiteNoise()
        
        let mixer = Mixer(noise)
        mixer.volume = 1

        engine.output = mixer
        try! engine.start()
    }
}

@main
struct AK5Test1App: App {
    
    var whatever = AKTest()
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

**To Reproduce**
1. Create a new project
2. Replace the main application file with the above contents
3. See error in the console:

```
2020-11-18 21:04:43.390401-0500 AK5Test1[70352:6085755] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000003f55c0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2020-11-18 21:04:43.450166-0500 AK5Test1[70352:6085766] [aurioc] AURemoteIO.h:323:entry: Unable to join I/O thread to workgroup ((null)): 2
```

**Expected behavior**
I expect the app to play white noise from my computer speakers, since I'm on the simulator.

**Details (please complete the following information):**
 - Type: any simulator (I tested most, but not all) 
 - OS: catalina (`10.15.7 (19H2)`)
 - AudioKit Version: `ak5-main`

Any advice would be appreciated!

**Comment by jasonsilberman** [comment]
I am now getting these same error messages on my end, were you able to figure out how to fix this?

**Comment by robmoran** [comment]
I'm also seeing the exact same error messages when using simulator. However, I am able to build and test on my device. 

Was there a fix or workaround for this?

**Comment by hoopes** [comment]
FWIW, the advice is to move to AK5 :) it's a pretty decent refactoring job to do. I'd try it in a branch before i bought fully into it. I never did find a fix for this particular issue though. Good luck! Sorry I couldn't be more help.

**Comment by robmoran** [comment]
Thanks! I actually ended up figuring it out -- the simulator was not able to use my laptop microphone. I had to change to a different audio input and it worked.

**Comment by hoopes** [comment]
oh MAN - what did you change it to???

**Comment by robmoran** [comment]
It worked with my Airpods connected as the computer's sound source.

**Comment by fwalker007** [comment]
Where exactly did you change the audio input ?

**Comment by robmoran** [comment]
I believe it was the standard System Preferences > Sound > Output

**Comment by shravanteegala** [comment]
i got same issue
