### ISSUE TITLE
I would like to create a MIDISampler in a global thread, but he is not available

### ISSUE THREAD

**Issue by benben-hello** [AudioKit/AudioKit#2335]
**Describe the bug**
DispatchQueue.global().async {[self] in 
	let guitar = MIDISampler(name: "guitar")
    	try? guitar.loadWav("guitar")
}

**Screenshots**
![image](https://user-images.githubusercontent.com/12512421/99943488-580ffe00-2dac-11eb-9e3a-9dff10dc7613.png)

**Details (please complete the following information):**
 - Type: [iPhone6s]
 - OS: [iOS14.0]
 - AudioKit Version [5.0]

**Comment by aure** [comment]
Can you provide a link to a GitHub repository that demonstrates this error? Until you can it will be hard to help. Happy to reopen the issue when you do.

**Comment by benben-hello** [comment]
Sorry, I created a demo today, but I found it is available, thanks, good luck!
