### ISSUE TITLE
Feature Request: Listener notified when Sequencer changes isPlaying state

### ISSUE THREAD

**Issue by btfranklin** [AudioKit/AudioKit#2337]
I have a UI that plays generated MIDI. When the generated MIDI has stopped playing, I want my UI to be able to notice that and change the "stop" button into a "play" button. However, as of right now, it doesn't appear obvious to me that there's a way to be notified when the Sequencer finishes playing the queued notes and changes itself to "stopped" (isPlaying == false).

What I would like is to be able to add a SequencerDelegate to the Sequencer, and receive notifications when things happen like "willStopPlaying" and "didStopPlaying". Alternatively, a traditional "Listener" could be attached, but I think a delegate pattern would be more appropriate here.

I would be happy to implement this myself, but I'm a Swift programmer. I don't know Objective-C and from looking at the SequencerEngine.mm file I can see exactly where I *think* this code would go, but I simply don't know how to implement this kind of thing in Objective-C. What I think we'd want here is something like a property observer ("didSet" etc.) on the isPlaying property, but I don't know if Obj-C supports that or how to do it. Alternatively, the same logic could be implemented in any method that modifies the isPlaying property directly.

One kind of unfortunate thing here is that it would probably be necessary to have something of a multi-stage delegation pattern here; the Swift SequencerTrack class needs to be notified by the SequencerEngine, and the Swift Sequencer needs to be notified by the Track. *Then* the Swift Sequencer would call its own delegate to pass the notification along.

That's what I think is the "right" way to do it, but there's another alternative that might be way less painful: NotificationCenter messages. The Obj-C SequencerEngine could simply fire appropriate Notifications when the play state changes, and then I'm pretty sure any code could just hear those and respond without having to go through the big dance I described above.

**Comment by btfranklin** [comment]
Of note: SequencerEngine looks like maybe it's in regular C rather than Objective-C?

**Comment by btfranklin** [comment]
A bit more info: I found this resource about how to call Swift methods from C, but it's pretty complicated as soon as you start using actual instance methods (which I think we'd want to do here).

http://www.perry.cz/clanky/swift.html

**Comment by aure** [comment]
AudioKit calls into C all over the place. Check out all the AK_API stuff

**Comment by btfranklin** [comment]
Oh yeah, calling *into* C isn't the problem. It's calling back from C into Swift that is a little tricky in this case. The state change that needs to be monitored lives in C.

**Comment by aure** [comment]
Oh right, duh, need to wake up before I started reading issues. :)

**Comment by aure** [comment]
Calling Swift functions is pretty convoluted usually. Can you send in a block instead?

**Comment by ClassicalDude** [comment]
Read on @_silgen_name as means to make Swift functions available to be called from C code. It is pretty simple. You can find info here:
https://github.com/apple/swift/blob/main/docs/StandardLibraryProgrammersManual.md

**Comment by aure** [comment]
@ClassicalDude Super interesting!

**Comment by btfranklin** [comment]
Yeah, I found the stuff about _silgen_name, but the challenge I'm still struggling with is what is the best way to have the callback not be a global function, but instead be a call onto a specific object in Swift. In this case, to be specific, we need a particular SequencerEngine (which is in C) to call a method on a *specific* SequencerTrack (which is in Swift). There's probably some way to map back to a particular track by passing a parameter to the global function, but that just feels ugly to me.

**Comment by ClassicalDude** [comment]
I see your reasoning. If my understanding is correct, @_silgen_name creates a global function only as far as the C code is concerned - the Swift protection levels apply to the end user. Additionally, you can pass function parameters from C to Swift, as long as they are unsafe.

**Comment by wtholliday** [comment]
`SequencerEngine` uses an `AURenderObserver` which runs on the audio thread. Calling out to arbitrary code would violate realtime guarantees. Using threading primitives to ensure realtime safety would mean that the timing accuracy of your callback wouldn't be very good (I'm also not sure how to do it in a realtime safe way without polling).

Given those issues, I'd recommend calculating the end time and using a timer, rather than adding a feature to AK.

**Comment by btfranklin** [comment]
@wtholliday In `SequencerEngine`, there's a single atomic boolean called `isStarted`.

`std::atomic<bool> isStarted{false};`

Any request by outside code, including driven by a `Timer` (which is how I'm currently working around this limitation, actually) eventually ends up interrogating this boolean. It is the "source of truth" for this state, at least from the perspective of any outside code.

What I am proposing is that when the value of this boolean gets changed from `true` to `false`, the same code that does that would also invoke the callback to indicate that it has changed. Since the boolean would be getting changed immediately prior to the callback being invoked, the timing accuracy of the callback would be, in essence, as good as possible.

The advantage would be that it wouldn't be necessary to keep asking "are you still playing?" at some arbitrary interval. Driving callbacks in response to a changed value is certainly nothing new. I think the only reason there's even any question around this particular example is simply because we have the additional challenge of crossing the C/Swift boundary.

**Comment by wtholliday** [comment]
Let me be more specific. stop() is called here from the audio thread:

https://github.com/AudioKit/AudioKit/blob/9e9f1ab8312c71c02288f73034b0393faa5e0bd3/Sources/CAudioKit/Sequencing/SequencerEngine.mm#L129

So your proposal ("same code that does that would also invoke the callback to indicate that it has changed") would violate realtime guarantees. I'd recommend this article to learn more: http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing

Now, I suppose we could add a timer on the AK side which invokes the callback. It could do a little polling to ensure by the time the callback is called, isStarted is false.

Still, I'd recommend implementing it on your side, since it doesn't require any additional API from AK.

**Comment by btfranklin** [comment]
@wtholliday Okay, thanks for that explanation. I think I'm getting you now. If I'm understanding correctly, the problem is the risk of introducing code in that momentary block that causes even the slightest unpredictable performance, which is a high-risk item with system code (i.e. firing a Notification) and certainly with user-implemented code (such as delegate code).

In light of that, you are surely right that the approach I've suggested would be wrong. That said, is there *any* safe way to "push" this information out of the SequencerEngine as soon as it occurs, perhaps by using some kind of asynchronous approach? Something that would disconnect it from the audio thread.

**Comment by wtholliday** [comment]
> That said, is there _any_ safe way to "push" this information out of the SequencerEngine as soon as it occurs, perhaps by using some kind of asynchronous approach (other than time-based polling)? Something that would disconnect it from the audio thread.

Not that I know of. The typical way to wake up another thread would involve `pthread_cond_signal` which I don't think is realtime safe.

But I think in principle, you can't do much better than the timer/poll approach. To be specific: you calculate how long the sequence should be, schedule a timer to fire when it's done, and then poll until the sequencer is actually done. It's great because it doesn't involve any scary threading stuff.

**Comment by wtholliday** [comment]
I asked around a bit and it seems the usual way to handle this is just to poll at 60Hz. No need to even calculate the end time.

**Comment by btfranklin** [comment]
It seems like it would be a shame to waste the resources needed to poll a value 60 times per second if it's not actively needed by a particular application. Consider that in my own application, I was able to use a simple Timer at the SwiftUI level polling at the much slower rate of 1Hz, which produced a "good enough" result.

```
playbackStatusMonitoringTimer = Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { _ in
    if Orchestrion.shared.playbackState != .playing {
        self.isPlaying = false
    }
}
```

I'm going to go ahead and close this request, since I'm certainly convinced that there are good reasons not to mess with this.
