### ISSUE TITLE
Add seek for AudioPlayer

### ISSUE THREAD

**Issue by realsnake** [AudioKit/AudioKit#2341]

**Comment by willsmillie** [comment]
Hi @aure 

I'm also interested in this. Any reason why it was closed?

I attempted to write an extension for AudioPlayer: 

```
extension AudioPlayer{    
    func seek(percentage: Float) {
        
        let lengthSamples = file!.length
        let format = file!.processingFormat
        let sampleRate = format.sampleRate
        let duration = Float(lengthSamples)/Float(sampleRate)
        
        let start = AVAudioFramePosition(floor(duration*percentage))
        let length = AVAudioFrameCount(Float(lengthSamples)-Float(start))

        playerNode.scheduleSegment(file!, startingFrame: start, frameCount: length, at: AVAudioTime.now(), completionHandler: nil)
    }
}

```

However after running it (in addition to a player.pause() & player.play() call), it doesn't appear to actually seek. Any hints?

**Comment by aure** [comment]
It was closed because it was rudely worded. At least you're giving it a shot.

**Comment by aure** [comment]
That should work we can test it out.

**Comment by royherma** [comment]
@aure Just to make sure, there is currently no ability to seek on audio player using AudioKit 5?

**Comment by willsmillie** [comment]
Created a PR: #2344

**Comment by royherma** [comment]
@aure Can you please take a look at @willsmillie PR - I believe this top be a very meaningful improvement for the new version of the library

**Comment by aure** [comment]
I did look at it. I made notes for changes.

**Comment by aure** [comment]
It looks as though the PR that addressed is trying to do too much. Perhaps we can get a PR with just the seek in it, or else I'll tease that part out.

**Comment by royherma** [comment]
@aure Any updates/thought on this? Are there any alternatives for seeking functionality right now that one can use or must we wait for a PR?

**Comment by aure** [comment]
The PR content is public and I believe @willsmillie is using it in his project, you're welcome to check out his repo, as it is public, I'm sure. Or you can look at what he did and implement it in your classes. We're being careful to avoid feature creep and features that are explicitly there to serve one project while potentially hobbling others or adding complexities that will be hard to maintain.

**Comment by royherma** [comment]
@aure Got it - thanks Aure. Just need to figure out how I can use it using swift's package manager and get to work!

**Comment by thejeff77** [comment]
@aure and @royherma the PR mentioned was closed. I also tried to pull in portions of it to my own fork and the code didn't seem to work, after calling seek(to:), the player would hang, seemingly waiting for a future scheduled date.

I think the AVPlayer has a seek method, I don't know the history as to why its needed to use the AVPlayerNode instead, but it might be nice to be able to re-use Apple's supported and maintained methods. 

Either way I need this!! I'd love any update or suggestions, or continued comments - I'm happy to potentially help with something.

**Comment by royherma** [comment]
@thejeff77 so i'm confused, how is anyone (or is anyone?) using this without seek functionality? Is it possible just using a different less convenient method or is it just currently not supported in any way?

**Comment by thejeff77** [comment]
> @thejeff77 so i'm confused, how is anyone (or is anyone?) using this without seek functionality? Is it possible just using a different less convenient method or is it just currently not supported in any way?

I’m still new to this library.. but I know that v5 is new, and uses SPM so its my first integration. As far as I can tell it was supported in v4 and hasn’t been ported over yet.

**Comment by royherma** [comment]
@thejeff77 Yes thats what I figured although I think i used 5 because i wasn't able to get it running on the latest dev env on xcode.. will double check

**Comment by Matt54** [comment]
PR for seeking the AudioPlayer:
https://github.com/AudioKit/AudioKit/pull/2428
