### ISSUE TITLE
Cannot find audiokitUI

### ISSUE THREAD

**Issue by Kenneth-Adams** [AudioKit/AudioKit#2343]
**Confirm you should be adding the bug here**
If your issue is implementing AudioKit in your own code, post your problem to [StackOverflow](https://stackoverflow.com/search?q=AudioKit) with the #AudioKit hashtag.

If you can make the issue happen on [AudioKit 5's Cookbook app](https://github.com/AudioKit/Cookbook/) then you can create an issue directly on that repository as well.

GitHub Issues should only be used for confirmed problems with AudioKit and
well-defined feature requests.

Sponsors will get more attention: https://github.com/sponsors/aure

**Describe the bug**
I used the SPM to download AudioKit but whenever I try to import AudioKitUI into a file, I'm told its not found. I've tried using cocoapods and directly loading the pods 'AudioKit/UI' to fix it but to no success. I am a first time user of AudioKit and it seems every time I run into a problem and fix it, Ill find a couple more.

**Comment by aure** [comment]
There is no more AudioKitUI https://github.com/AudioKit/AudioKit/blob/v5-main/docs/MigrationGuide.md
