### ISSUE TITLE
Issue when creating multiple Samplers

### ISSUE THREAD

**Issue by nicolaasdan** [AudioKit/AudioKit#2348]
Hi,

I'm using AudioKit v5.0 in my ios app and i've seem to have encountered an issue when creating multiple samplers.

**Parameter address keeps incrementing in SamplerAudioUnit.swift**
When creating multiple sampler-objects the parameterAddresses of underlying AUParameters keeps incrementing. Updating parameters does not work in the case when the sampler is not instantiated first. For example, updating the vibratoDepth on the first sampler works but updating the vibratoDepth on a second sampler does not. 

**To Reproduce**
pseudo code:

    var sampler1 = Sampler("somePath", "someFileName.sfz")
    var sampler2 = Sampler("somePath", "someFileName2.sfz")

    sampler1.vibratoDepth = 0.8 -> this works
    sampler2.vibratoDepth = 0.8 -> does not work

**Expected behavior**
I think the parameterAddress of parameters on sampler1 and sampler2 should be the same. 

A Sampler has an internalAU which consists of many AUParameters (mastervolume, pitchbend, vibratoDepth,...). These AUParameters have an _address-property. This address-property is set when initiliazing the Sampler-object. It seems to me that the address-property keeps incrementing when i'm initializing multiple Sampler-objects. In the file SamplerAudioUnit.Swift the property _parameterAddress is static, which is why it keeps incrementing i think?

When i create multiple Synth-objects i can see that here the ParameterAddress-property on the AUParameters are the same over the different objects. This is not the case for Sampler-objects

**Screenshots**
n/a

**Details (please complete the following information):**
 - Type: iphone Xr
 - OS: iOS14
 - AudioKit Version v5.0

**Additional context**
Let me know if you need any more information, or if this is actually not a bug at all.

Otherwise really enjoying audiokit!

Kind regards,
Nicolaas

**Comment by aure** [comment]
Thanks Nicolaas, I am not sure how this could be happening. I know we don't have a similar issue with multiple oscillators running at once and couldn't see anything in sampler that was different. Do you bye any chance have a test project you can post to GitHub?

**Comment by nicolaasdan** [comment]
Hi Aurelius,

Thank you for your response. I have created a small project that demonstrates the issue. All code is located in a conductor-class and should be easy to follow. I create 2 samplers, set vibrato on both samplers (as example), and then play a note on both samplers subsequently. I expect to hear vibrato on both samplers but you only hear it on one.

link to the project:
https://github.com/nicolaasdan/MultipleSamplersAudioKit

Let me know if you have any issues or questions with the project.

I'm always willing to try and fix the issue myself and then create a pull request, not sure what you prefer?

Nicolaas

**Comment by aure** [comment]
Well of course always love PRs! There's so much to do that any help I can get is appreciated.

**Comment by aure** [comment]
Your deduction from the original issue statement is absolutely correct. static variables for the loss

**Comment by aure** [comment]
This Sampler was one of the parts of AudioKit that wasn't fully converted to the nice AK5 format. Might be nice to do that as part of the fix. Compare Sampler to Oscillator to see what I mean.

**Comment by aure** [comment]
I did a one-liner fix but if you wanted to beef it up by AK5-ifying it, that would be fine :) Closing for now.
