### ISSUE TITLE
 Cannot find type 'AKMIDIListener' in scope 

### ISSUE THREAD

**Issue by vishallohiaimpinge** [AudioKit/AudioKit#2349]
Hi all, I am not able to find AKMIDIListener. in AudioKit 5 Itsowing methe error Cannot find type 'AKMIDIListener' in scope

**Comment by markjeschke** [comment]
@vishallohiaimpinge,

You simply want to drop the "AK" prefix from the class names. This is referenced in the AudioKit 5 migration guide:

https://github.com/AudioKit/AudioKit/blob/v5-main/docs/MigrationGuide.md#lesser-differences

You can also see an example of it in action within the AudioKit Cookbook recipe, which demonstrates MIDI monitoring with AudioKit 5:

https://github.com/AudioKit/Cookbook/blob/main/Cookbook/Cookbook/Recipes/MIDIMonitor.swift#L22

I hope that this helps.

Take care,
Mark
