### ISSUE TITLE
AKSequence inaccurate while device is asleep

### ISSUE THREAD

**Issue by rosano** [audiokit/AudioKit#235]
Is AKSequence supposed to be sample-accurate while the device is locked or is it intended for events that don't need to be precise? I tried making a small metronome, but it seems to go out of sync on sleep, and even before. I notice it's using performSelector:withObject:afterDelay:inModes: which I have heard is inaccurate when it comes to audio timing.

**Comment by aure** [comment]
No, AKSequence isn't sample accurate.  AKPhrase should be, but I haven't tested sleep conditions on that one.

**Comment by rosano** [comment]
Ah, okay. FWIW, AKPhrase was what I used.
