### ISSUE TITLE
Bug MIDI+Sending Audiokit 5 Dev Branch, Index out of range line 287 virtualOutputs array

### ISSUE THREAD

**Issue by Nicolaudie** [AudioKit/AudioKit#2350]
**Describe the bug**
Calling **sendNoteOnMessage**(noteNumber: noteNumber, velocity: velocity) in the class MIDI+Sending.swift will occasionally cause an **index out of range** crash in the **virtualOutputs** array on line 287

**To Reproduce**
1. Run audio kit on an iPad Pro (12.9 inch) 4th generation or the Xcode simulator of this iPad
2. Call sendNoteOnMessage: noteNumber: 63 and velocity: 1
3. Call this repeatedly
Not exactly sure of how to guarantee reproduction of this as it seems to happen only occasionally

**Details (please complete the following information):**
 - Type: [iPad Pro (12.9 inch) 4th Gen, also simulator of same iPad, also occurs on multiple other iPads]
 - OS: [e.g. iOS 14.2]
![Screenshot 2020-12-17 at 22 07 15](https://user-images.githubusercontent.com/15261192/102549611-4f150280-40b4-11eb-8afd-4cc7fea1d336.png)

 - AudioKit Version [5.0 dev branch]

**Additional context**
This only seems to happen on iOS 14.2 and above and is more common on later iPads

**Comment by aure** [comment]
This must have been introduced recently with https://github.com/AudioKit/AudioKit/pull/2345 @Thomasv46 can you have a look?

**Comment by Thomasv46** [comment]
Hi,

#2355 should fix the problem !
