### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by nor-bu** [audiokit/AudioKit#236]
Hi,

i have problem with the setup of the Dynamic Framework in Xcode 7 and iOS 9, i setup step by step with your movie, then i build and i become this error:
```
ld: framework not found CsoundLib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

PS: The Setup with the Static Library works fine, but i need Dynamic for a commercial app

thanks for help

**Comment by nor-bu** [comment]
I have found the solution.
I had add "Framework Search Paths" to build settings

sorry for this post

**Comment by aure** [comment]
Hey no problem at all, We are currently working on making installation much easier.
