### ISSUE TITLE
iOS and MacOS inconsistency in AKConverter

### ISSUE THREAD

**Issue by cihadturhan** [AudioKit/AudioKit#2364]
**Describe the bug**
Hi, I'm not sure if this is a bug or feature. While AKConverter can convert some files on MacOS app, it can't do in iOS app.

**To Reproduce**
- Clone "FileConverter" example
- Build and run in macbook, try to convert a MOV into wav file. Success ✅ 
- Copy same code to an iOS project
- Build and run in an iPhone, try to convert "the same" MOV into wav file. Fail 👎 
- iOS console returns: `ExtAudioFile.cpp:193:Open: about to throw 'typ?': open audio file.` and `Unable to open the input file`
- It works fine if I want to convert MP4 files

**Expected behavior**
I would expect FileConverter works same in both ios and macos.

**Screenshots**

**Details (please complete the following information):**
 - Type: [iPhone XR, Macbook Pro 2018]
 - OS: [iOS 14, MacOS 10.15.7]
 - AudioKit Version [Tried both 4.11.2 and 5-develop]

**Additional context**
Thanks

**Comment by ryanfrancesconi** [comment]
Sorry for not seeing this issue till now. The converter was written for macOS actually, though I'd assumed it mostly would work the same on iOS. I'm surprised to hear that it doesn't. You could try first converting to m4a then convert to wave.

**Comment by aure** [comment]
This seems we would have to rely on Apple to make consistent.

**Comment by tvongerlach** [comment]
I ran into the same issue as you @cihadturhan. Converting a `mov` file to `m4a` with `AVAssetExportSession` and then using `FormatConverter` on iOS works. Another thing I discovered along the way is that the `m4a` file can't be in the user's temporary directory. If the file is in the home directory it works.

**Comment by tvongerlach** [comment]
Ok never mind, unfortunately. What I had worked on a simulator but when running on an actual device it fails.
