### ISSUE TITLE
AKFFT Example

### ISSUE THREAD

**Issue by nor-bu** [audiokit/AudioKit#237]
Hi,

Do you have a AKFFT example with microphone input?
How can i get the FFT data as array?
The Harmonizer Example is not working.

thanks

**Comment by narner** [comment]
Hi @nor-bu, what exactly is the issue with the Harmonizer Example?

**Comment by nor-bu** [comment]
I tab on the record button and hold, then i tap on the play butten but the is not playing

ios 9 simulator and iPhone6+

Can you give me a little halp to start with the following use case.

How can i get the fft data from 0-44100hz from mic to do a special analysier algorythm?(on live input)

thanks for help

**Comment by aure** [comment]
A bunch of the playgrounds are doing real time microphone processing, and some of them display the FFT, but if not, just use 

[self addAudioOutputFFTPlot];

Oh, and you don't need to install dyci to use playgrounds (dyci is dicey, esp on Xcode7), just run them without the interactive coding aspect.

**Comment by aure** [comment]
It is good that you moved this to the discussion forums.  I'll close the issue here.
