### ISSUE TITLE
Can't Get List of Available Devices

### ISSUE THREAD

**Issue by jsl303** [AudioKit/AudioKit#2371]
I'm using AudioKit v5-main, Swift 5, XCode 12.3, MacOS 10.15.7.
When I try to get engine.outputDevices, I get "Static member 'outputDevices' cannot be used on instance of type 'AudioEngine'.

```
import AudioKit

class Player {

    let engine = AudioEngine()

    func setOutput() {
        if let devices = engine.outputDevices {
            // ...
        }
    }

}
```

**Comment by aure** [comment]
Right, so replace `engine.outputDevices` with `AudioEngine.outputDevices`. Let me know if that just works.
