### ISSUE TITLE
Help: Use mic from stethoscope and listen the sound through the AirPods.

### ISSUE THREAD

**Issue by eduardotamaki** [AudioKit/AudioKit#2379]
I'm building a Stethoscope app, with a proper hardware that behaves like a headphone, It has a mic attached and an plug to connect any phone. I have done the app with filter and so on, everything goes well... but, my client wants to use the mic from Stethoscope and listen the sound through the AirPods.

How can I achieve this? Is there a solution?

Thanks in advance!

**Comment by aure** [comment]
This is not an AudioKit problem or issue so it is not appropriate to be asked here.
