### ISSUE TITLE
Framework not found CsoundLib

### ISSUE THREAD

**Issue by neesonqk** [audiokit/AudioKit#238]
Following exactly the same installation instruction of "AudioKit 2.1 Configuration for OSX Applications", however there's an error occured, "Framework not found CsoundLib".

My Xcode is 7.0.1 (the latest version currently).

**Comment by nor-bu** [comment]
Hi,

You need to set the "Framework Search Paths".

Here the text from the install instructions:

This will automatically add a "Framework Search Paths" entry for you, but it will be an absolute reference, so if you are sharing your projects with others, you should go to Build Settings Tab and add an entry relative to $(SRCROOT) that leads to AudioKit/Platforms/iOS.

**Comment by neesonqk** [comment]
Thanks, it works
