### ISSUE TITLE
AudioPlayer completion is not called and player itself in not looping in rendering-mode

### ISSUE THREAD

**Issue by sroik** [AudioKit/AudioKit#2382]
Your AudioPlayer is always using `AVAudioPlayerNodeCompletionCallbackType.dataPlayedBack` completionCallbackType when playing a file 
(https://github.com/AudioKit/AudioKit/blob/v5-main/Sources/AudioKit/Nodes/Playback/AudioPlayer/AudioPlayer.swift#L249)

But when I try to render it in manual mode, player is not looped, cause internalCompletionBlock is not called.
Maybe let us pass completionCallbackType in `AudioPlayer.play` func ?

Thanks!

**Comment by aure** [comment]
Thanks for the follow through.
