### ISSUE TITLE
I am having a similar issue to #1531, which is closed.

### ISSUE THREAD

**Issue by bcichowlas** [AudioKit/AudioKit#2386]
I am having a very similar issue to #1531, which is closed.

Half my users get a crash that looks a lot like the above, but for the others it works fine. I am using code based on "Tuner" in "Cookbook". This has happened with both v4 and v5.

I wish I could get the crash to happen for me, but my app works on all of my iPhones and iPads and those to which I have access.

<img width="1460" alt="Screen Shot 2021-01-16 at 12 07 23 PM" src="https://user-images.githubusercontent.com/354720/104818205-263b7680-57f4-11eb-91d0-43c5a306438f.png">

**Comment by aure** [comment]
How is this actionable with the given information?
