### ISSUE TITLE
v5 - "Cannot form Range" crash when AudioKit receives a particular MIDI sysex message

### ISSUE THREAD

**Issue by adamjansch** [AudioKit/AudioKit#2387]
I'm building a SysEx editor for Emu Proteus 2K family devices, using AudioKit for the MIDI side. One particular sysex response from my test hardware (an Emu MoPhatt sound module) is causing a crash in *MIDI+Receiving.swift*:

    private func processUMPSysExMessage(with bytes: [UInt8]) -> [UInt8]? {
        // Chapter 4.4 of Universal MIDI Packet (UMP) Format and MIDI 2.0 Protocol, Version 1.0
        // http://download.xskernel.org/docs/protocols/M2-104-UM_v1-0_UMP_and_MIDI_2-0_Protocol_Specification.pdf
        
        let umpSysExStatus = UMPSysEx7bitStatus(rawValue: getMSB(from: bytes[0])) // status byte
        let validBytesCount = getLSB(from: bytes[0]) // valid bytes count field
        let validBytes = Array(bytes[1...Int(validBytesCount)])    // <--- CRASH OCCURRING HERE
        
        guard (umpSysExStatus != nil) else {
            Log("UMP SYSEX - Got unsupported UMPSysEx7bitStatus", log: OSLog.midi)
            return validBytes
        }

        ...

The crash (marked on the code above) is:

> Fatal error: Can't form Range with upperBound < lowerBound

This is because `validBytesCounts` is `0`, which is clearly less than the lower bound of 1.

The sysex response I'm receiving (which I've confirmed is the correct response for the message I'm sending) is:

    F0 18 0F 04 55 0B 01 01  00 0D 00 62 74 73 3A 54 10  68 65 20 55 6C 74 69 6D  61 74 65 F7

I have other sysex messages being received correctly, and as far as I can tell there isn't something in *my* code that is causing this (as I said, the MoPhatt is sending the expected SysEx message to my app, and then this crash occurs before my code is hit). 

To replicate:

I realise few will have this MIDI hardware available, but I would assume that "playing" the sysex above out from SysEx Librarian into a MIDI receiving AudioKit app should trigger the same crash.

Setup:

 - Type: iPhone X
 - OS: iOS 14.3
 - AudioKit Version: v5 main (last updated 2021-01-15)
 - Emu MoPhatt MIDI sound module running OS v2.26
 - Cakewalk UM-2G MIDI interface, connected to iPhone via Apple Camera Connector

**Comment by aure** [comment]
Can you make it fail in a sample project that both sends and receives sysex? This will be a while before one of us goes to the trouble of setting up your situation. If you want to do a screenshare, that could be the most efficient.

**Comment by adamjansch** [comment]
I've created a minimal project that demonstrates the crash – https://github.com/adamjansch/AudioKit-SysEx-crash. This project only implements sysex reception.

**To reproduce**

You will need some way of sending the sysex file at https://github.com/adamjansch/AudioKit-SysEx-crash/blob/main/Sysex/MoPhatt%20Preset%20Name%20response.syx – I used SysEx Librarian for Mac (https://www.snoize.com/SysExLibrarian/).

1. Run the project on an iOS device. When ready it should display a "Hello World!" message.
2. Make a MIDI connection between a Mac running SysEx Librarian and the iOS device (note: I tested using hardware MIDI, I don't know if network MIDI will work out of the box). The Mac should run MIDI out to iOS device MIDI in.
3. Start SysEx Librarian, set the MIDI out endpoint to point to the iOS device, and load in https://github.com/adamjansch/AudioKit-SysEx-crash/blob/main/Sysex/MoPhatt%20Preset%20Name%20response.syx.
4. Press Play in SysEx Librarian.

If the MIDI connections are all correct then the iOS app should crash as described.

**Comment by jrmaxdev** [comment]
This crash has nothing to do with your hardware.
It is caused by a malformed range expression (MIDI+Receiving.swift)
```swift
// this range will cause a crash when validBytesCount is 0
 1...Int(validBytesCount)
```
It should be written like this:
```swift
// correct
 1..<1+Int(validBytesCount)
```
You can confirm this be running the following tests:
```swift
import XCTest

extension UInt8 {
    var lowNibble: UInt8 { self & 0x0F }
}

// this is how bytes are extracted from the UMP64 (MIDI+Receiving.swift)
func getBytesFromUMPWords(word0: UInt32, word1: UInt32) -> [UInt8] {
    let bytes0 = withUnsafeBytes(of: word0.bigEndian, Array.init)
    let bytes1 = withUnsafeBytes(of: word1.bigEndian, Array.init)
    return Array(bytes0[1..<4]) + bytes1
}

// this is how data is read (MIDI+Receiving.swift)
func getDataFromUMPBytes(bytes: [UInt8])->[UInt8] {
    let validBytes = Int(bytes[0].lowNibble)

    // this is the correct range
    let validBytesRange = 1..<1+validBytes

    return Array(bytes[validBytesRange])
}


class UMPSysexGetDataTests: XCTestCase {


    func testWith4DataBytes() throws {
        // group: 3, umpType: 5, sysexType: 0, validbytes: 4, data0: 1, data1: 2
        let word0: UInt32 = 0x35_04_01_02

        // data2: 3, data3: 4, data4: 0, data5: 0
        let word1: UInt32 = 0x03_04_00_00

        let bytes = getBytesFromUMPWords(word0: word0, word1: word1)
        let data = getDataFromUMPBytes(bytes: bytes)

        XCTAssertEqual(data, [1, 2, 3, 4])
    }

    func testWithNoDataBytes() throws {
        // group: 3, umpType: 5, sysexType: 0, validbytes: 0, data0: 0, data1: 0
        let word0: UInt32 = 0x35_00_00_00

        // data2: 0, data3: 0, data4: 0, data5: 0
        let word1: UInt32 = 0x00_00_00_00

        let bytes = getBytesFromUMPWords(word0: word0, word1: word1)
        let data = getDataFromUMPBytes(bytes: bytes)

        XCTAssertEqual(data, [])
    }
}
```

**Comment by aure** [comment]
Want to make a pull request with the fix?

**Comment by jrmaxdev** [comment]
Ok. I can do it this afternoon.

**Comment by adamjansch** [comment]
Just gave the fix a test, looks good at this end! Thanks for your help @jrmaxdev and @aure :-)
