### ISSUE TITLE
v5 AmplitudeTap.amplitude always equal to 0.0

### ISSUE THREAD

**Issue by Evgenij-gostev** [AudioKit/AudioKit#2393]
When using AmplitudeTap I want to get the amplitude value. I put a microphone at the entrance. For some reason, the amplitude is always 0.0.

**Comment by aure** [comment]
You're doing something wrong but you haven't shown anything. Issues are for posting specific problems proven to be with AudioKit not your own code. This is just too vague.

**Comment by Evgenij-gostev** [comment]
Thanks, I figured it out. The problem was that I did it like this:
     let stereoMic = StereoFieldLimiter (mic, amount: 1)
     let amplitude = AmplitudeTap (stereoMic)
And you need to feed the microphone directly:
     let amplitude = AmplitudeTap (mic)
