### ISSUE TITLE
Improve Build Speed for Swift Package Manager

### ISSUE THREAD

**Issue by thejeff77** [AudioKit/AudioKit#2394]
**Description**

The build speed of the SPM v5 is extremely slow. Every time I run/test/build it rebuilds CAudioKit. It has doubled my build times or more. Please look into optimizing the Swift Package Manager config for AudioKit so that a complete rebuild (at least for CAudioKit) for every run doesn't _always_ occur, or is much faster.

**To Reproduce**
1. Add v5 AudioKit to project.
2. Build it and run it a lot. Observe painfully slow wait times every time.

**Expected behavior**
No rebuild sometimes, or much faster rebuild, or no rebuild of AudioKit for subsequent runs/builds.

**Details (please complete the following information):**
 - Type: iPhone
 - OS: 14.3
 - AudioKit Version 5

**Comment by aure** [comment]
So, do you think we forgot to add the "Make Xcode not suck" flag to our SPM?

**Comment by megastep** [comment]
As an alternative, you could also try to use our beta CocoaPod that uses pre-compiled binaries, so that's not an issue there (though has other issues).

**Comment by wtholliday** [comment]
I tried this with the Cookbook project and it was really fast on my end. @thejeff77 Can you reproduce using the Cookbook project?

**Comment by aure** [comment]
I wonder if this is something that gets progressively worse and you might need to delete your derived data folder.

**Comment by thejeff77** [comment]
Thanks for the feedback folks. 

I'll try to keep a sharper eye on if this is any better after cleaning the build folder @aure 

I'll also come and post additional feedback after I run the cookbook project @wtholliday 

This post is about Swift Package Manager, I was excited to not have to integrate with CocoaPods for just this project, so props for getting this working at all with AudioKit/SPM @megastep . Is there a similar feature to use pre-compiled for SPM that could be implemented?

Generally, does anyone know of any SPM applicable settings that may help here that could be investigated?

That is, settings other than "Make Xcode not suck" that is... @aure ;)

**Comment by megastep** [comment]
Xcode 12 has SPM support for XCFrameworks, and I did manage to get it working at some point, but the way this is managed is just really cumbersome and it seems easier just to go with a regular source SPM package.

**Comment by aure** [comment]
I'll close this but feel free to reopen when new information is provided.

**Comment by CliefLord** [comment]
repeat wilth me : ) Xcode suck,they probely make some limited to protect Scheme building Application for Xcode.ip proxy doesn`t work.All request will send to California
