### ISSUE TITLE
Support M/S Stereo / flip left & right channel

### ISSUE THREAD

**Issue by JayBrown** [AudioKit/AudioKit#2398]
**Is your feature request related to a problem? Please describe.**
* Some audio needs to be transformed from "regular" stereo to Mid/Side Stereo (M/S Stereo, a.k.a. Matrix Stereo) in playback or offline rocessing.
M = 1/2 * ( L + R )
S = 1/2 * ( L – R )

* Some audio input has been coded in M/S Stereo, and during playback or offline processing this often needs to be converted to "regular" stereo. 
L = M + S
R = M – S

* Some audio signals have been mapped incorrectly, with left and right inverted, independent of the source material ("regular" stereo or M/S stereo), which needs to be rectified during playback/processing
L < > R

**Describe the solution you'd like**
Extend the type **StereoOperation** to include:
Input: L+R Stereo
* **toFlippedStereo** (just exhange L & R channels)
* **toMSStereo** (convert L+R stereo to M/S stereo, i.e. to 1/2*(L+R) and 1/2*(L-R), and map those signals on the two L & R channels respectively)

Either by inclusion in type **StereoOperation**, or in new type **MSStereoOperation**:
Input: M/S stereo signal
* **convertToStereo** (convert M/S stereo signal to "regular" stereo; differently named to set it apart from the already existing **toStereo**)

Notes: sometimes M/S audio can be mapped to the wrong channels; in that case you'd need to use StereoOperation > toFlippedStereo first, and then send that through convertToStereo

**Describe alternatives you've considered**
No alternatives considered.

**Assign yourself to this task**
Sorry, I'm probably not your man.

**Additional context**
n/a

**Comment by JP-Lisn** [comment]
I am quite new to AudioKit, so this _may be_ a horrible solution. However, from my understanding I believe you could use OperationEffect to accomplish most, if not all, of what you are looking to achieve here.  

Flip Stereo: 
```
let toFlippedStereo = OperationEffect( inputNode, channelCount: 2) { _, _ in 
  return [ Operation.rightInput, Operation.leftInput ]
}
```

toMSStereo: 
```
let toMSStereo = OperationEffect( inputNode, channelCount: 2) { _, _ in
  let leftResult = 0.5 * (Operation.leftInput + Operation.rightInput);
  let rightResult = 0.5 * (Operation.leftInput - Operation.rightInput); 
  return [ leftResult, rightResult ];
}
```

Question for the AudioKit Pro's: Is this appropriate?

**Comment by aure** [comment]
@JP-Lisn That won't be the most CPU efficient way of doing it, but it will get the job done.  These change could probably be added to the StereoFieldLimiter or some other node pretty easily. Perhaps I'll do it in an office hours.

**Comment by ryanfrancesconi** [comment]
There is a flip stereo and mono merge in the Fader class.

**Comment by aure** [comment]
Yeah, this seems pretty easy, but I have no project that requires this, so if you'd like to add it or work on it and make a PR, that would be best.
