### ISSUE TITLE
Problem of sound output to phone speakers

### ISSUE THREAD

**Issue by Evgenij-gostev** [AudioKit/AudioKit#2401]
During the recording, a song is played and sound is captured from the microphone, but on the phone, the sound is heard only in the upper speaker and is very quiet. Everything worked fine in AK4.

class RecordAudioService2 {
    
    var micGain: AUValue = 3 {
        didSet { micFader.gain = micGain }
    }
    var trackGain: AUValue = 1 {
        didSet { playerFader.gain = trackGain }
    }
    
    private var mixer: Mixer!
    private var engine = AudioEngine()
    private var micFader: Fader!
    
    private var player: AudioPlayer!
    private var playerFader: Fader!
    
    // record
    private var micRecorder: NodeRecorder!
    private var trackRecorder: NodeRecorder!
    
    private var reverb: SEReverb!
    private var delay: SEStereoDelay!
        
    // Live Cicle
    
    init() {
        createChainOfNodes()
    }
    
    
    // MARK: - Public funcs
    
    func record() {
        do {
            try micRecorder.reset()
            try trackRecorder.reset()
            player.play()
            recordingAudio()
        } catch {
            Log("[Record] Couldn't reset.")
        }
    }
    
    func safe() {
        if !micRecorder.isRecording { return }
        saveAudio()
        player.stop()
    }
    
    func pause() {
        if micRecorder.isRecording {
            print("[Record] micRecorder Recording")
            player.pause()
            saveAudio()
        } else {
            print("[Record] micRecorder not Recording")
            player.play()
            recordingAudio()
        }
    }
    
    // MARK: - Private funcs
    
    private func createChainOfNodes() {
        startAudioKit()
        // player
        createPlayerNodes()
        // mic
        createMicrophoneNodes()

        // mixer
        guard let micRecorder = micRecorder,
              let trackRecorder = trackRecorder else {
            print("[Record] error create nodes")
            return
        }
        mixer = Mixer([micRecorder.node, trackRecorder.node])
        
        if mixer != nil {
            if !engine.avEngine.isRunning { engine.output = mixer }
            startAudioKit()
        }
    }
    
    private func createMicrophoneNodes() {
        guard let mic = engine.input else {
            print("[Record] error create mic")
            return
        }
        let stereoMic = StereoFieldLimiter(mic, amount: 1)
        micFader = Fader(stereoMic, gain: micGain)
        micRecorder = createNodeRecorder(node: micFader, filename: "voiceFile.caf")
    }
    
    private func createPlayerNodes() {
        guard let trackUrl = Bundle.main.url(forResource: "MARINA", withExtension: "mp3") else  {
            print("[Record] file no found")
            return
        }
        player = AudioPlayer(url: trackUrl)
        
        playerFader = Fader(player!, gain: trackGain)
        playerFader.start()
        trackRecorder = createNodeRecorder(node: playerFader, filename: "trackFile.caf")
    }
    
    private func createNodeRecorder(node: Node, filename: String) -> NodeRecorder? {
        do {
            let recorder = try NodeRecorder(node: node)
            return recorder
        } catch {
            print("[Record] Oops! NodeRecorder (\(filename)) error!")
            return nil
        }
    }
    
    private func startAudioKit() {
        if engine.avEngine.isRunning { return }
        do {
            configureRecordingAndPlaybackOptions()
            try engine.start()
            print("[Record] engine.start")
        } catch {
            print("[Record] engine no start")
        }
    }
    
    private func configureRecordingAndPlaybackOptions() {
        do {
            try Settings.setSession(category: .playAndRecord)
        } catch {
            Log("Error \(error)")
        }
    }
    
    private func recordingAudio() {
        do {
            try micRecorder.record()
            try trackRecorder.record()
            completion?(.record)
        } catch {
            Log("[Record] Couldn't record")
        }
    }
    
    private func saveAudio() {
        micRecorder.stop()
        trackRecorder.stop()
        if let url = micRecorder.audioFile?.url {
            print("[Record] save micFile")
            UserDefaults.standard.set(url.absoluteString, forKey: "urlRecord")
        }
    }
    
}

**Comment by blindgaenger** [comment]
Hi @Evgenij-gostev  If I understood you correctly then you get the sound through the earpiece and not the speakerphone. So you could try to set `Settings.defaultToSpeaker = true` or provide the option to `setSession` directly. Could be that the default value changed in AudioKit 5 (I've never used AK4, though).

**Comment by Evgenij-gostev** [comment]
Settings.defaultToSpeaker = true - Does not help

**Comment by Evgenij-gostev** [comment]
"provide the option to setSession directly" I didn't quite understand what to do

**Comment by aure** [comment]
AK4 did a lot of things for you that ended up being an overreach, so AK5 makes fewer assumptions. I suggest working with AVAudioSession directly.

**Comment by Evgenij-gostev** [comment]
private func configureRecordingAndPlaybackOptions() {
        Settings.defaultToSpeaker = true
        do {
            try AVAudioSession.sharedInstance().setCategory(.playAndRecord)
        } catch {
            print("Failed to set audio session category.")
        }
    }

doesn't help either

**Comment by Evgenij-gostev** [comment]
I checked, if you remove the creation of the microphone and leave only the player, then the sound plays as it should. There is something wrong with the microphone.

**Comment by blindgaenger** [comment]
Yep, the AudioSession can be quite confusing. Especially if you rely on a mode and can't access all devices anymore. I'd set the mode to `default` which works with every category. And then try one of the category's options.

`AVAudioSession.sharedInstance().setCategory(.playAndRecord, mode: .default, options: .defaultToSpeaker)`

Also the official docs can be helpful. 🤞 

https://developer.apple.com/documentation/avfoundation/avaudiosession/capturing_stereo_audio_from_built-in_microphones#3686658

**Comment by Evgenij-gostev** [comment]
thanks, now it works as it should
