### ISSUE TITLE
AudioPlayer does not play after the engine it's attached to restarts

### ISSUE THREAD

**Issue by warpling** [AudioKit/AudioKit#2403]
**Describe the bug**
AudioPlayers don't play if their parent engine is restarted.

**To Reproduce**
See the `AudioKitExample` branch of [this Cookbook fork](https://github.com/warpling/Cookbook/tree/AudioPlayerExample) and try running `AutoPanner`. It will create and play an AudioPlayer. One second later it will stop the engine, and one second after that it will start the engine and attempt to play the player again. Observe that after the first restart the player does not produce sound nor does its callback work.

**Expected behavior**
AudioPlayer should play after engine restarts.

**Details (please complete the following information):**
 - Type: Tried on an older iPad, and iPhone 12 Pro
 - OS: iOS 14
 - AudioKit Version 5.0: v5-main

**Additional context**
This was tested with local files only, and not buffered

**Comment by warpling** [comment]
It seems replacing the Mixer and reconnecting it's inputs/output can restore functionality after an engine restart

**Comment by ryanfrancesconi** [comment]
can you make a test that shows the issue rather than the cookbook example?

**Comment by aure** [comment]
I wrote a test for this and it seems to work.

**Comment by warpling** [comment]
Thanks Aure!

**Comment by ryanfrancesconi** [comment]
You need to test this in realtime mode, not just offline. The test is only doing offline rendering.
