### ISSUE TITLE
Can this lib convert the format audio m4a to mp3?

### ISSUE THREAD

**Issue by nthnhung23** [AudioKit/AudioKit#2404]
I have read the AKConverter file, but the format audio mp3 not be support? Could you help me to expand it?

These lines:
        **switch outputFormat {
        case "m4a", "mp4":
            format = .m4a
            formatKey = kAudioFormatMPEG4AAC
        case "aif":
            format = .aiff
            formatKey = kAudioFormatLinearPCM
        case "caf":
            format = .caf
            formatKey = kAudioFormatLinearPCM
        case "wav":
            format = .wav
            formatKey = kAudioFormatLinearPCM
        default:
            AKLog("Unsupported output format: \(outputFormat)")
            return
        }**

**Comment by aure** [comment]
I could be wrong, but I think these are the supported ones because they are lossless whereas mp3 is lossy.
