### ISSUE TITLE
swift package generate-xcodeproj leads to non-compiling xcode-project

### ISSUE THREAD

**Issue by niklassaers** [AudioKit/AudioKit#2406]
I do:

```bash
git clone https://github.com/AudioKit/AudioKit.git
cd AudioKit
swift package generate-xcodeproj
xcodebuild
```

it fails with
```
AudioKit/Sources/CAudioKit/Devoloop/pluginobjects.cpp:1:10: fatal error: 
      'pluginconstants.h' file not found
#include "pluginconstants.h"
```

If I do this on the v5-develop branch, thus

```bash
git clone https://github.com/AudioKit/AudioKit.git
cd AudioKit
git checkout -b v5-develop
swift package generate-xcodeproj
xcodebuild
```

I get
```
The following build commands failed:
	CompileC AudioKit/build/AudioKit.build/Release/CAudioKit.build/Objects-normal/arm64/SamplerVoice.o AudioKit/Sources/CAudioKit/AudioKitCore/Sampler/SamplerVoice.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC AudioKit/build/AudioKit.build/Release/CAudioKit.build/Objects-normal/x86_64/pluginobjects.o AudioKit/Sources/CAudioKit/Devoloop/pluginobjects.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```

In my workflow I still like a working Xcode project. Any ideas on how we should fix this?

**Comment by megastep** [comment]
Haven't checked this lately, but for building the frameworks the actual command we use is `swift package generate-xcodeproj --xcconfig-overrides AudioKit.xcconfig`, with some configuration overrides in that file which may help in your case.

**Comment by megastep** [comment]
And yes there are bugs in the swift package command that we run into :/

**Comment by aure** [comment]
What do you want an xcodeproj for AudioKit for? You will still have the xcodeproj for your own project, which can refer to AudioKit locally or via SPM as in the Cookbook project. Closing the issue, but feel free to add to it or bring it up on Slack.

**Comment by niklassaers** [comment]
Thanks for the command @megastep . Using that it built fine, but I was not able to run the tests.

@aure Opening it up by itself in Xcode would allow me to focus on just this when writing my test.

**Comment by aure** [comment]
You can open up the folder and run the tests with cmd U. What am I missing?
