### ISSUE TITLE
Why I can still hear the sound if the frequency was set to above 20000?

### ISSUE THREAD

**Issue by neesonqk** [audiokit/AudioKit#241]
Here is my code,

``` swift
var frequency = AKInstrumentProperty(value: 25000,  minimum: 25000, maximum: 2000000)

let instrument = AKInstrument();
let oscillator = AKFMOscillator();
oscillator.baseFrequency = frequency;
instrument.setAudioOutput(oscillator);
AKOrchestra.addInstrument(instrument);

instrument.play();
```

By right, above 20000Hz human cannot hear anymore, did I do something wrong?

**Comment by aure** [comment]
You're attempting to play a note at above the Nyquist frequency (https://en.wikipedia.org/wiki/Nyquist_frequency) which is 22.05KHz, ie half the sampling frequency of 44.1KHz.  If you attempt to play notes in this range, you will still hear a tone based on what is able to be played, but your results are unpredictable.

**Comment by neesonqk** [comment]
Thanks @aure
