### ISSUE TITLE
xcframework missing Mac Catalyst ARM 64

### ISSUE THREAD

**Issue by francdn** [AudioKit/AudioKit#2411]
Hi,

I believe the xcframework is missing Mac Catalyst ARM 64. When trying to build for Mac Catalyst on Mac Silicon it returns several "Undefined symbol" errors.

I checked the xcframework folders and I could find ios-x86_64-maccatalyst but it should be ios-arm64_x86_64-maccatalyst.

**Comment by megastep** [comment]
Is this for v4 or v5 of AudioKit? Are you trying to use the pod?

**Comment by francdn** [comment]
AudioKit v4.11.2 release -> AudioKit.xcframework.zip

**Comment by megastep** [comment]
Yeah I don't think the build scripts were updated yet for that. Pretty sure it should be included in the v5 beta one though. You can try it but there were some very significant API changes.

https://files.audiokit.io/staging/v5.0.b2/AudioKit.xcframeworks.zip

**Comment by francdn** [comment]
I rather stick with V4 for now.

**Comment by francdn** [comment]
Why was this closed? Was it fixed?

**Comment by aure** [comment]
If Stephane wants to do it for AK4, its up to him, but I recommend switching to AK5.

**Comment by francdn** [comment]
Ok thanks. I am not comfortable switching to AK5 since it still in beta.
