### ISSUE TITLE
DRWAV conflicts with other libraries

### ISSUE THREAD

**Issue by KTRosenberg** [AudioKit/AudioKit#2412]
There are plenty other audio libraries that use dr_wav and other dependencies, so installing AudioKit via the dependency manager introduces multiple symbol definition errors. Is there any way in which you could add an AudioKit prefix or namespacing to the third-party libraries? I would do this myself, but I am not sure what the desired format would be.

Thanks.

**Comment by aure** [comment]
What other libraries? Have you asked them to change their namespacing? This is the first I've heard of this.

**Comment by KTRosenberg** [comment]
The other library is miniaudio, which tightly integrates with drwav and doesn’t rename the functions. I think audiokit’s internal library (soundpipe?) uses drwav as a single header library, so this causes issues even when loaded as a swift package. I’ve temporarily worked around the issue by renaming the functions in the miniaudio library, but I was hoping that all libraries would use some namespacing. I’ll have to make the change every time I update.

**Comment by aure** [comment]
We aren't actually using it anymore so I removed it.
