### ISSUE TITLE
How to use AKMixer with both AKPlayer and AKMetronome at the same time?

### ISSUE THREAD

**Issue by millionairesby28** [AudioKit/AudioKit#2415]
I'm currently making a metronome app, it uses AKMetronome for the core part since it has the callback function, I need the callback function to visualize the beat, I also want to use it for customized click sound (and I'll mute the original AKMetronome sound, but it'll still play, just without the original sound).

Now, I have two wav files which are customized click sound, there will be two AKPlayers to play it, and the AKPlayers need to be triggered on every AKMetronome beat's callback. Since AKPlayer and AKMetronome are both need to be played, I put them in an AKMixer, like this:

So I would like to customise my Metronome so that other sounds can be played too.

    var playerA: AKPlayer!
    var playerB: AKPlayer!
    var clickA: AKAudioFile?
    var clickB: AKAudioFile?
    var metronome: AKMetronome?

    override func viewDidLoad() {
        super.viewDidLoad()

        prepareAudio()
        metronome!.start()
    }

    func prepareAudio() {
        clickA = try? AKAudioFile(readFileName: "Click1A.wav")
        clickB = try? AKAudioFile(readFileName: "Click1B.wav")

        playerA = AKPlayer(audioFile: clickA!)
        playerA.buffering = .always
        playerB = AKPlayer(audioFile: clickB!)
        playerB.buffering = .always

        //metronome
        metronome = AKMetronome.init()
        metronome!.subdivision = 4
        metronome!.frequency1 = 1000
        metronome!.frequency2 = 800
        metronome!.tempo = 60
        metronome!.callback = {
            self.playAudio()
        }

        let mixer = AKMixer(playerA, playerB, metronome)
        AudioKit.output = mixer
        do {
            try AudioKit.start()
        } catch {
            print("audiokit start fail!")
        }
    }

    func playAudio() {
            playerA.play()
            playerB.play()
    }

Then, when playerA.play() is executed, it'll crash. This is the error message:

AURemoteIO::IOThread (11): EXC_BAD_ACCESS (code=1, address=0xffff9ffffdb0e360)

**Comment by millionairesby28** [comment]
So rather than the normal sine wave to be heard, I would like to put my own click sounds?

**Comment by aure** [comment]
Dispatch your play function. There's a metronome example in the cookbook now too. This doesn't seem like an issue with AudioKit, more like a request for help, so I am closing it here.

**Comment by millionairesby28** [comment]
I can't seem to find the metronome example in the cookbook
can you send me the link please?
@aure

**Comment by aure** [comment]
Sorry its a little hidden at the moment https://github.com/AudioKit/Cookbook/blob/develop/Cookbook/Cookbook/Recipes/Shaker.swift

Developed in a livestream: https://www.youtube.com/watch?v=ISJo3vzaBcw
