### ISSUE TITLE
Cookbook app crash on iOS 13.7

### ISSUE THREAD

**Issue by abinop** [AudioKit/AudioKit#2420]
Cookbook app crashes when it is run on iOS versions prior to ios 14. 

**Describe the bug**
Just by running the app on the simulator, it crashes on this line

`avEngine.connect(mixer.avAudioNode, to: avEngine.outputNode, format: Settings.audioFormat)`

**To Reproduce**
Just run the Cookbook app on an iOS 13.7 simulator. You will need to remove a couple of lines that do not work on iOS prior to 14, like

```
//        .navigationBarTitle("AudioKit", displayMode: .inline)
//        .toolbar {
//            ToolbarItem(placement: .principal) {
//                Image("audiokit-logo")
//                    .resizable()
//                    .frame(width: 117,
//                           height: 20)
//            }
//        }
```

**Screenshots**
<img width="841" alt="Screenshot 2021-02-08 at 9 39 21 AM" src="https://user-images.githubusercontent.com/1769597/107194864-462c1780-69f9-11eb-842d-c06dd2439c18.png">

**Details (please complete the following information):**
 - Type: iPad 9.7 simulator
 - OS: iOS13.7
 - AudioKit Version 5.0 (v5-main)

**Comment by abinop** [comment]
I first faced the problem with the 13.7 iOS version with AudioKit 4 as well, see [here](https://stackoverflow.com/questions/66077123/akmanager-audiokit-crash-halb-iobuffermanager-clientgetiobuffer-the-stream-i)

**Comment by aure** [comment]
Is this limited to crashing in the simulator? Or are devices running iOS13 also affected? I haven't seen this error.

**Comment by abinop** [comment]
> Is this limited to crashing in the simulator? Or are devices running iOS13 also affected? I haven't seen this error.

I know some clients have had this problem on real devices, I don't have one myself though. I can only reproduce it on a simulator.
