### ISSUE TITLE
Are AK Notifications still in use?

### ISSUE THREAD

**Issue by warpling** [AudioKit/AudioKit#2421]
The `Settings.notificationsEnabled` setting has been removed from `Settings` but the [Notification names](https://github.com/AudioKit/AudioKit/blob/v5-main/Sources/AudioKit/Internals/Utilities/Notifications.swift) remain. Perhaps they were meant to be removed?

**Comment by warpling** [comment]
I don't see any evidence of these being throw in AK4 either so perhaps I'm missing something.

**Comment by aure** [comment]
Thanks!
