### ISSUE TITLE
Reimplement  support for 3D spatialization

### ISSUE THREAD

**Issue by roaring-b** [AudioKit/AudioKit#2426]
Dropping support for AK3DPanner in AudioKit 5 makes sense if it wasn't working in previous versions. But when I first came to AudioKit I was hoping (expecting?) to find it doing some 3D audio spatialization and still think it would be nice to have this available.

The Feature Request is for AudioKit to include 3D audio spatialization by leveraging AVAudioEnvironment or [Resonance Audio](https://resonance-audio.github.io/resonance-audio/). Both have both become more stable in recent years and Resonance Audio in particular now incorporates lots of advances features—not all of which would need to be implemented in AudioKit.

I'm not sure how much my coding skills could contribute to this but I'm willing to do what I can, and I can certainly help with implementation ideas, testing, and documentation.

Here's a link to a review that shows of some of what Resonance Audio can do: https://designingsound.org/2018/03/29/lets-test-3d-audio-spatialization-plugins/

**Comment by misterinterrupt** [comment]
2 cent thought:
Resonance Audio uses the Apache 2.0 license. I am no lawyer, but Including this cwould mean that all apps using AK would have to deal with including that licence's notice and license in their 'distribution'. I don't know what that means, legally.

**Comment by roaring-b** [comment]
Agreed. If someone needs what Resonance Audio offers they should probably just include that separately.

Probably not a priority, but what are people's thoughts about eventually reimplementing spatialization using AVAudioEnvironment?

**Comment by misterinterrupt** [comment]
I could see those spatialization features being implemented as a 3DMixerNode or similar..
Seems worthwhile, would you take a stab at something like that, @roaring-b ?

**Comment by roaring-b** [comment]
I'm not sure my abilities are a good match for this but when I find time I'm willing to see how far I can get on my own.

**Comment by aure** [comment]
We will accept this as a PR if you or anyone would like to do it, thanks.
