### ISSUE TITLE
Unable to hear output on macOS 11.2.1

### ISSUE THREAD

**Issue by thislooksfun** [AudioKit/AudioKit#2427]
**Describe the bug**
When running even a simple engine on macOS I don't hear any audio. When it starts I hear a 'pop' as if the audio hardware is initializing, but then it's just silence.

**To Reproduce**
Run the following code (created with Xcode 12.4 (12D4e), New Project > macOS > Command Line Tool)
```swift
import Foundation
import AudioKit

let engine = AudioEngine()
engine.output = Oscillator()
try! engine.start()

RunLoop.main.run()
```

**Expected behavior**
I expect to hear audio.

**Screenshots**
N/A

**Details (please complete the following information):**
 - Type: macOS
 - OS: macOS 11.2.1 (20D74)
 - AudioKit Version 5.0 (b1099859f6654c98f0f28e9fb1ed388ae96cb7d6)

**Additional context**
N/A

**Comment by aure** [comment]
Oscillator don't play by default. This works:

```
import Foundation
import AudioKit

let engine = AudioEngine()
let osc = Oscillator()
osc.amplitude = 0.1
engine.output = osc
try! engine.start()
osc.start()

RunLoop.main.run()

```

**Comment by thislooksfun** [comment]
...ah, that would do it.
