### ISSUE TITLE
(anonymous struct)::head' from module 'AudioKit.TPCircularBuffer' is not present in definition of 'TPCircularBuffer' in module 'MyProject.TPCircularBuffer'

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#2429]
We am using `AudioKit` since quite some time mainly for its midi implementations. At the same time we are using Michael Tysons `TPCircularBuffer` for our threaded audio processing in a static library way down in the dependency graph. 

I just wanted to upgrade to the latest 4.x AudioKit upgrade and XCode 12 from XCode 11 and i see this error messages

```
.../XCFrameworkIntermediates/AudioKit/AudioKit.framework/Headers/TPCircularBuffer.h:68:23: '(anonymous struct)::head' from module 'AudioKit.TPCircularBuffer' is not present in definition of 'TPCircularBuffer' in module 'MirgaWrapper.TPCircularBuffer'
.../XCFrameworkIntermediates/AudioKit/AudioKit.framework/Headers/TPCircularBuffer.h:67:23: '(anonymous struct)::tail' from module 'AudioKit.TPCircularBuffer' is not present in definition of 'TPCircularBuffer' in module 'MirgaWrapper.TPCircularBuffer'
.../XCFrameworkIntermediates/AudioKit/AudioKit.framework/Headers/TPCircularBuffer.h:66:23: '(anonymous struct)::length' from module 'AudioKit.TPCircularBuffer' is not present in definition of 'TPCircularBuffer' in module 'MirgaWrapper.TPCircularBuffer'
```

When inspecting both `TPCircularbuffer.h` (from the c++ library and from AudioKit, both seem identical)

I am wondering how can i solve this problem without touching any of the TPCircularBuffer implementations? Both are not my code, so I would like to avoid forking their repos to make changes. On the other hand the library that is used by `MyProject` is a pure C/C++ implementation and cannot import AudioKit to use its `TPCircularBuffer` implementation.

**To Reproduce**
1. Create a c++ library that includes TPCircularBuffer via Submodule from https://github.com/michaeltyson/TPCircularBuffer
2. Create a host application that includes AudioKit and the c++ library from 1.
3. Try to compile the host application

**Expected behavior**
Compilation should pass

**Details (please complete the following information):**
 - Type: any
 - OS: ios14.4
 - AudioKit Version 4.11.2

**Additional context**

**Comment by aure** [comment]
I'd rip TPCircularBuffer out of AudioKit 4 and make your own local copy. We will be removing it from AudioKit 5 shortly.

**Comment by mlostekk** [comment]
is it not required by audiokit?

**Comment by aure** [comment]
No, not anymore.

**Comment by aure** [comment]
well, it's not once we remove ezaudio, which is slated to happen soon.

**Comment by mlostekk** [comment]
well, i cant just rip it out. then audiokit wont compile anymore into a xcframework :/

**Comment by aure** [comment]
Latest AK5 doesn't have TPCircularBuffer in it anymore. Not sure what else I can do. What's holding you onto AK4?
