### ISSUE TITLE
Looking for a rolling plot with negative values

### ISSUE THREAD

**Issue by holoman0** [audiokit/AudioKit#243]
I'm able to get the rolling plot to not fill and to not mirror but somewhere all of the values are being translated into positive values and the plot always floors at 0. I want the rolling sound graph to look like it does when those same sounds are plotted on a "non-rolling" plot (with positive and negative values plotted around a line at 0.
Is this possible?

**Comment by aure** [comment]
Maybe what you're describing is not offered by default, but it shouldn't be too hard to tweak to make that happen.
