### ISSUE TITLE
Possibility to subclass BaseTap

### ISSUE THREAD

**Issue by hamtiko** [AudioKit/AudioKit#2430]
**Is your feature request related to a problem? Please describe.**
I figured out that it is not possible to subclass `BaseTap` and create custom Tap due to `internal` access modifier of `doHandleTapBlock` function.

**Describe the solution you'd like**
I will suggest making it `open` so we can create custom Tap.

**Describe alternatives you've considered**
As an alternative solution I think will be to provide `BufferTap` which will send raw buffer (`AVAudioPCMBuffer`) to the handler without any modifications.

**Assign yourself to this task**
Please confirm which option is preferable for you and I can create a PR for that.

**Comment by aure** [comment]
Um, it is open?  

https://github.com/AudioKit/AudioKit/blob/bd206fa2109df78da9bfe0059cbaa7544d9e1e74/Sources/AudioKit/Analysis/BaseTap.swift#L101

**Comment by aure** [comment]
Reopen or comment on this, but I'll close it for now.

**Comment by hamtiko** [comment]
@aure Thanks. 
It seems it was updated recently, and I haven't updated it in my project.
