### ISSUE TITLE
MIDI setup change after sendNoteOnMessage called many times

### ISSUE THREAD

**Issue by Nicolaudie** [AudioKit/AudioKit#2432]
**Describe the bug**
Bug when sendNoteOnMessage is called around 50 times in MIDI

**To Reproduce**
- Initialise a MIDI object 
- open input 
- call **sendNoteOnMessage(noteNumber: MIDINoteNumber,
                                  velocity: MIDIVelocity)** around **50** times 
- MIDI controller set up is changed 
- **receivedMIDISetupChange** is received

 - iPad iOS 14.5
 - AudioKit 5 development branch commit bd206fa2109df78da9bfe0059cbaa7544d9e1e74

- This bug was discovered using an APAC Mini MIDI controller

**Comment by Nicolaudie** [comment]
This issue may be coming from the MIDI controller itself rather than AudioKit but still receivedMIDISetupChange is being received when it shouldn't

**Comment by misterinterrupt** [comment]
the code docs in `CoreMIDI/MIDIServices.h` for that message mention a case when the msg can be ignored. perhaps it just isnt being ignored when it should and is bubbling up to you erroneously.
`@constant	kMIDIMsgSetupChanged
		Some aspect of the current MIDISetup has changed.  No data.  Should ignore this message if
		messages 2-6 are handled.`

**Comment by misterinterrupt** [comment]
I have an akai mpd 16 I can try 50 events at some point soon and look for some weird events

**Comment by Nicolaudie** [comment]
Seems like if I call **sendNoteOnMessage** a 43 times with a different **MIDINoteNumber** each time I get this output in Xcode:

MIDI+Receiving.swift:closeInput(uid:):423:Disposed Session 1 (MIDI+Receiving.swift:closeInput(uid:):423)
MIDI+Receiving.swift:closeInput(uid:):408:Closing MIDI Input 'APC MINI' (MIDI+Receiving.swift:closeInput(uid:):408)
MIDI+Receiving.swift:closeInput(uid:):417:Disconnected APC MINI and removed it from endpoints and input ports
MIDI+Receiving.swift:closeInput(uid:):423:Disposed APC MINI (MIDI+Receiving.swift:closeInput(uid:):423)

If the MIDINoteNumber is the same it doesn't happen

**Comment by Nicolaudie** [comment]
I'm going to close the issue as I'm pretty sure its the hardware and not AudioKit
