### ISSUE TITLE
v5 Sequencer doesn't handle tempo changes smoothly.

### ISSUE THREAD

**Issue by milkypostman** [AudioKit/AudioKit#2433]
**Bug**
I have been playing around with all the sequencers in AudioKit and one of the issues I found is that the *Shaker Metronome* which uses the AudioKit sequencer (not AppleSequencer) doesn't handle tempo changes gracefully. As the temp changes the hits will start happening close together and there will be big pauses sometimes. Some trippy random stuff can happen which is kinda cool but I think it should behave more naturally, like the AppleSequencer does. 

**Reproducing**
You can reproduce this in the Cookbook by going to the *Shaker Metronome* and hitting *start* and then changing the tempo while it plays. The tempo doesn't smoothly ramp up between the changes.

**Details (please complete the following information):**
 - Type: iPhone 12 mini
 - OS: iOS 14.4
 - AudioKit Version: v5-main

**Comment by aure** [comment]
I can check myself, but I'm sorta wondering the v4 sequencer also has this issue.

**Comment by misterinterrupt** [comment]
I'm working on profiling the timing of the v5 seq, I may be able to adapt the profiling code to 4v and then compare

**Comment by milkypostman** [comment]
I am using the v4 sequencer and I'm not having the same issue with tempo changes. As I set a new tempo `sequencer.tempo = BPM(newBPM)` it adjusts smoothly. There isn't any weird behavior like what I'm seeing in the Cookbook.

Both the v5 and v4 code changes the tempo by changing the tempo on the individual tracks. However, from what I can tell, the code to change tempo for tracks is quite different. In v4 it just sets the tempo on the `internalAU` vs v5 which calls the [updateSequence function](https://github.com/AudioKit/AudioKit/blob/b1099859f6654c98f0f28e9fb1ed388ae96cb7d6/Sources/AudioKit/Sequencing/Sequencer/SequencerTrack.swift#L123) which looks much more involved, updating all the events and notes. I apologize for my naivety because I didn't dig further down so maybe the code is doing the same things.

**Comment by misterinterrupt** [comment]
there are definitely differences in the way that sequencer works between versions. I am currently working on sequencer bugs, so your debugging info is helpful. 

if possible, try to create a programmatic test for the behavior you are experiencing.

**Comment by Oli-C** [comment]
On the topic of the sequencer, I've been trying to use Synth instead of Shaker in the cookbook example, but no Synth notes are triggering. Only STK nodes seem to produce any sound. Is this a current bug or am I missing something needed for other nodes such as Synth to work?

**Comment by aure** [comment]
@Oli-C I'd prefer if we didn't add tangential issues onto current ones. What you mention is something else entirely.

**Comment by Oli-C** [comment]
@aure Apologies, was unsure if a bug or whether additional code is needed for non-STK nodes. Would you like me to log the issue?

**Comment by aure** [comment]
Yes, do a new issue about your topic.
