### ISSUE TITLE
How to send transport codes like record / play stop?

### ISSUE THREAD

**Issue by pistacchio** [AudioKit/AudioKit#2442]
Hi, thanks to AudioKit I can easily instantiate a MIDI out engine and send notes to my DAW with the following code:

```swift
        self.engine = AudioKit.MIDI()
        self.engine.createVirtualOutputPorts()
        self.engine.openOutput()
       self.engine.sendEvent(MIDIEvent(noteNo: UInt8(80), velocity: UInt8(80), channel: UInt8(1)))
```

How to send transport events like "Play" / "Record" / "Stop"?

Thanks

**Comment by aure** [comment]
Those are probably done using MMC: https://en.wikipedia.org/wiki/MIDI_Machine_Control

You would need to generate a Sysex MIDIEvent from the bytes, and send that along. We don't currently have any helper functions to make that any easier.
