### ISSUE TITLE
Using seek(time:) of AudioPlayer  two times, the players current play state is not respected.

### ISSUE THREAD

**Issue by jucysoft** [AudioKit/AudioKit#2443]
**Describe the bug**

Using seek(time:) of AudioPlayer  two times, the players current play state is not respected.

**To Reproduce**
1. player.play
2. player.seek(time:)  --> at this time, current play state is play.
3. player.seek(time:) --> at this time, current play state is stop

**Expected behavior**
play state should be play at step 3.

**Details (please complete the following information):**
 - AudioKit Version [5.0-develop]

**Additional context**
step 2 seek(time:) makes isPlaying variable to false.

**Comment by ryanfrancesconi** [comment]
actually it's the completion handler being called which is setting isPlaying to false. Previously the seek method was outside of the playback flags.

I have a potential work around though.

**Comment by Matt54** [comment]
I think we can close this issue with the latest changes to AudioPlayer.
