### ISSUE TITLE
Bypass function may not be working on Mixers

### ISSUE THREAD

**Issue by warpling** [AudioKit/AudioKit#2444]
It appears that bypassing a mixer with CPU intensive nodes connected upstream does not reduce CPU load. 

My test case involves 12 `FMOscillator`s, connected through 12 `AmplitudeEnvelope`s, connected to a `Mixer`. While CPU usage is notably lower if I never connect/start the oscillators, it is unchanged if I bypass the `Mixer`. I would expect the CPU usage to be almost equivalent to the nodes not being connected when they are bypassed.

**Comment by aure** [comment]
So, bypassing a mixer only turns down its volume. All the nodes are being asked to produce data so there will be no CPU advantage.  It might be cool if mixers automatically managed the nodes they are connected to, but that seems like it might be complicated and have unintended consequences, plus I am not sure how we would do that either.

**Comment by warpling** [comment]
@aure My mental model was that everything was still on a "pull for data" system where 0 volume also meant that but I guess I need to refresh that! Is there anyway to implement something like that here where nodes can be cut-off on demand?

**Comment by aure** [comment]
Yeah, just disconnect those nodes from the mixer.

**Comment by warpling** [comment]
Okay, so there's no way other than disconnecting? Won't stopping an oscillator, etc reduce CPU?

**Comment by aure** [comment]
When you stop an oscillator the DSP does not compute the next sample so yes you should reduce CPU usage.
