### ISSUE TITLE
DispatchQueue.main.async crash

### ISSUE THREAD

**Issue by Azcdragon** [AudioKit/AudioKit#2446]
![WechatIMG74](https://user-images.githubusercontent.com/25076293/111858084-22051400-8971-11eb-90a2-5b77f58b7913.jpeg)
我在使用sdk进行获取音频流进行解析为频率时候发生了crash，目前测试复现情况比较频繁，具体崩溃见截图。
使用的sdk版本为v5-main，测试使用的设备为：Model: iPad (5th generation) (Model A1822) iOS 13.6.1 (17G80)。

为防止图片显示问题，特复制出问题代码为下：
```
// AVAudioNodeTapBlock - time is unused in this case
    private func handleTapBlock(buffer: AVAudioPCMBuffer, at time: AVAudioTime) {
        // Call on the main thread so the client doesn't have to worry
        // about thread safety.
        buffer.frameLength = bufferSize
        DispatchQueue.main.async {           //这里为崩溃发生位置。
            // Create trackers as needed.
            self.lock()
            guard self.isStarted == true else {
                self.unlock()
                return
            }
            self.doHandleTapBlock(buffer: buffer, at: time)
            self.unlock()
        }
    }
```

**Comment by aure** [comment]
I don't understand this question but it looks you're capturing self from the audio thread and trying to use it on main, which will crash for sure.
