### ISSUE TITLE
Docs for v5

### ISSUE THREAD

**Issue by yusuftor** [AudioKit/AudioKit#2448]
Hi, I've just found AudioKit and am eager to use it. As new users we're encouraged to use v5. However, the docs and playgrounds are all for v4. Old sample code I'm trying to follow doesn't work with v5 either - why are there no proper docs for v5 yet?

**Comment by maksutovic** [comment]
Hi Yusuftor,

There is a migration guide for v5: https://github.com/AudioKit/AudioKit/blob/v5-main/docs/MigrationGuide.md

Also, feel free to contribute documentation as you see fit, this is a collaborative effort :D

**Comment by yusuftor** [comment]
@maksutovic Hi, I saw that but it didn't really help me. It tells me what I need to do to convert my app to V5, but doesn't explain the fundamentals.
For example, someone has created a tuner [here](https://github.com/elslooo/guitar-tuner/blob/master/Tuner/Logic/Tuner.swift), but none of what they use is available in V5, and just searching for an AKOrchestra or AKAnalyzer in the guide doesn't bring up any results. I can see that there's a PitchTap that I can attach to the microphone, but the docs don't explain what the PitchTap returns in its handler.

**Comment by aure** [comment]
@yusuftor Have you seen https://github.com/AudioKit/Cookbook ?

**Comment by yusuftor** [comment]
@aure Ah that's perfect, thanks!
