### ISSUE TITLE
Warning about "unhandled files" in XCode with v5-develop branch Swift Package

### ISSUE THREAD

**Issue by btfranklin** [AudioKit/AudioKit#2452]
I'm importing AudioKit into my project via directly pulling v5-develop as the Swift Package URL. Functionally, it is working great, and I've been building it this way for quite some time.

However, recently, a bunch of warnings have started appearing related to AudioKit. I don't know exactly what it's wanting to change or I'd make the PR myself, and like I said, it seems to work just fine. But maybe you guys can make heads or tails of it. It would be nice to not see these numerous warnings at build time.

(I already did the whole "delete your Derived Data folder" etc. etc. Nothing obvious fixes it.)

<img width="1320" alt="Screen Shot 2021-04-02 at 5 09 18 PM" src="https://user-images.githubusercontent.com/23176608/113462652-c60da700-93d6-11eb-9cff-877c873d5c3d.png">

**Comment by megastep** [comment]
I guess Swift PM still doesn't recognize .hpp files - but at the very least all these .md files should be excluded from the package...

**Comment by aure** [comment]
Alrighty then. Those warnings are history on the develop branch.

**Comment by btfranklin** [comment]
You guys are awesome. :)
