### ISSUE TITLE
Only STK Nodes have innate MIDI so that they can be controlled with the Sequencer

### ISSUE THREAD

**Issue by Oli-C** [AudioKit/AudioKit#2453]
I have been testing the sequencer within the shaker example of AudioKit’s cookbook. This is the AudioKit sequencer (non-apple). When the shaker is changed to a node that is not an STK Node, such as Synth, it will no longer sequence notes. I was hoping to use Synth with the sequencer but have been unable to connect them.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Shaker example in the cookbook.
2. Change shaker to another STK node (Shaker, Flute, Clarinet, Mandolin, RhodesPiano). This should still work and sequence.
3. Now change the STK node to Synth or VocalTract.
4. The code will compile and the sequencer will progress. However, no audio is output and the Synth node will not be triggered.

**Expected Behaviour**
I expected to be able to change the example for any AK node to be sequenced, as AK4 worked similar to this. Apologies if this is a simple misuse of how the AK5 sequencer works, however I've been struggling to find a solution to this problem. I've temporarily used the RhodesPiano in a project I've been working on for University and hopefully this can be solved as it would allow me to sequence notes and control the timbre of the sequenced notes.

Best,
Oli

Additional Info:
 - Type: iPhone Xs
 - OS: iOS 14.4.2
 - AudioKit Version: 5-main

**Comment by aure** [comment]
So, yeah, most AudioKit nodes do not have default MIDI implementations like the STK Instruments do. What we usually do is to implement a class of MIDIInstrument to receive the MIDI commands and then internally handle the stopping and starting of nodes at appropriate note and velocity (or whatever) values. Synth should definitely be able to handle MIDI directly like the way STK does. I'd welcome a pull request that makes that so. VocalTract I'm not so sure if there's an obvious MIDI implementation that would satisfy everyone.

**Comment by aure** [comment]
This is becoming less true as we have been adding midi triggering to many nodes in AudioKit, so more things will be sequencable.

**Comment by Oli-C** [comment]
Thanks Aure! I'll check out the recent updates. Shout out to you and the team at AudioKit :)
