### ISSUE TITLE
AudioKit Tests do not run

### ISSUE THREAD

**Issue by eljeff** [AudioKit/AudioKit#2460]
Trying to run the tests locally - failing with no error.

1) new project
2) add ak v5-develop branch via SPM
3) drag in audiokit folder to debug locally
4) change target to AudioKit
5) click test tabs, and run tests
6) XCode says 'Build failed' with no error. Parent app builds fine, c-audiokit tests build and pass.

**Expected behavior**
tests should run

**Details (please complete the following information):**
MacBook Pro (Retina, 15-inch, Late 2013)
macos big sur  
I can get the tests to run if I roll back my branch to 22 Mar - haven't explored anything beyond that.

**Comment by eljeff** [comment]
Found this in the logs: 
**bundle format unrecognized, invalid, or unsuitable**

Full log:
```
CodeSign /Users/jeffcooper/Library/Developer/Xcode/DerivedData/ak5tests-ezrjdtvhkqigsnadeukaxbuvdsry/Build/Products/Debug-iphonesimulator/AudioKit_AudioKitTests.bundle (in target 'AudioKit_AudioKitTests' from project 'AudioKit')
    cd /Users/jeffcooper/Documents/code/audiokit/audiokit\ v5/AudioKit
    export CODESIGN_ALLOCATE\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp\=none /Users/jeffcooper/Library/Developer/Xcode/DerivedData/ak5tests-ezrjdtvhkqigsnadeukaxbuvdsry/Build/Products/Debug-iphonesimulator/AudioKit_AudioKitTests.bundle

/Users/jeffcooper/Library/Developer/Xcode/DerivedData/ak5tests-ezrjdtvhkqigsnadeukaxbuvdsry/Build/Products/Debug-iphonesimulator/AudioKit_AudioKitTests.bundle: bundle format unrecognized, invalid, or unsuitable
Command CodeSign failed with a nonzero exit code
```

**Comment by aure** [comment]
But the test do run on CI and on my machine. CI is a fresh checkout every time.

**Comment by aure** [comment]
Fixed.
