### ISSUE TITLE
MultiChannelInputNodeTap, bug in ioLatency 

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/AudioKit#2468]
@ryanfrancesconi - i was just looking at this very useful code you added and found a possible bug in MultiChannelInputNodeTap -> WriteableFile -> writeFile function

if buffer size is 4800 and latency is say 10000, the code will always fail. (failed to edit buffer).
ioLatency needs to be adjusted as ioLatency  - totalFramesRead, metthinks.

            if !ioLatencyHandled, ioLatency > 0 {
                if totalFramesRead > ioLatency {
                    Log("Actual buffer size is", buffer.frameLength,
                        "Attempting to skip", ioLatency, "frames for latency compensation")

                    // edit the first buffer to remove io latency samples length
                    if buffer.frameLength > ioLatency,
                       let offsetBuffer = buffer.copyFrom(startSample: ioLatency) {
                        buffer = offsetBuffer
                    } else {
                        Log("Failed to edit buffer")
                    }
                    ioLatencyHandled = true

                } else {
                    // very long IO latency?
                    Log("Actual buffer size is", buffer.frameLength,
                        "waiting for", ioLatency, "samples...")
                    return
                }
            }

also, i was thinking, this code could be also very useful in nodeRecorder, to compensate for latency in the. same way?

**Comment by ryanfrancesconi** [comment]
@quantamrhino cool, i'll improve, thanks!. In general, latency on my computer is 1700 frames or so but i'm using CoreAudio calculations on macOS, so I don't know what iOS returns in that regard.

**Comment by ryanfrancesconi** [comment]
and yes, any tap based method of recording will have latency and won't be accurate without accounting for it.

**Comment by quantamrhino** [comment]
I get 0.3 seconds or so on bluetooth. about 10000 frames at 44.1K and a buffer of 4410.
using wired or direct is much less, about 1000-1500 frames.
With the fix to that code, it was pretty accurate actually... if the fix isn't applied, it means a buffer size deviation, so it'll do about 4410*3 skips, and be about 1000 off.
NodeRecorder has a process function that can also use the same piece of code to skip frames at the beginning, with a 0 default, same as it's in the MultiChannelInputNodeTap... what do you think?

**Comment by ryanfrancesconi** [comment]
Yes, got it, going to add a PR in a second with the fix. Good point about bluetooth, thanks!

**Comment by quantamrhino** [comment]
Wonderful! Many thanks, Sir!

**Comment by ryanfrancesconi** [comment]
@quantamrhino thanks for the callout as I meant to do this before but totally forgot.

**Comment by ryanfrancesconi** [comment]
@quantamrhino also, yes, it'd be good if node recorder had this as well

**Comment by ryanfrancesconi** [comment]
@quantamrhino is this working now for you?

**Comment by quantamrhino** [comment]
It's working well. Thank you. 
(I'd just noticed the issue eyeballing the code, but I did do a quick trial, it's working well).

**Comment by ryanfrancesconi** [comment]
nice, thanks
