### ISSUE TITLE
V5 missing ability to play audio file from and to a specific time.

### ISSUE THREAD

**Issue by leamars** [AudioKit/AudioKit#2470]
**Is your feature request related to a problem? Please describe.**
Comparing V4 and V5, I've noticed some things missing from the previous AKAudioPlayer into the new AudioPlayer. In particular, the method to start and end playback of a file at a specific time.

This method is still mentioned in the docs:
https://audiokit.io/docs/Classes/AKAudioPlayer.html#/c:@M@AudioKit@objc(cs)AKAudioPlayer(im)playFrom:to:
![image](https://user-images.githubusercontent.com/2446390/115391551-81a44880-a1d7-11eb-8c95-f4dbd6602a86.png)

**Describe the solution you'd like**
I'd like to know whether it's going to be re-implemented, is it gone forever, and what the workaround is at the moment - if there is one?

**Comment by leamars** [comment]
Just read through all the docs to see that you mentioned AudioPlayer's functionality is limited in V5, so I'll just switch to V4 (:

**Comment by aure** [comment]
Actually this particular function does seem like something we could implement in v5. Would really like to have you using v5 if possible.

**Comment by ryanfrancesconi** [comment]
I'll try to make some time asap to add this to the v5 player.
