### ISSUE TITLE
MIDIEvent error in Node.swift

### ISSUE THREAD

**Issue by rodoortiz** [AudioKit/AudioKit#2472]
I'm trying to make a tvOS app with AudioKit v5 but when trying to build for the first time after adding the framework with the _Add Package Dependency_ method, I'm getting an error on line 183 from _AudioKit/Nodes/Node.swift_ file that says **"Cannot find type 'MIDIEvent' in scope"**. 

Also when trying to do _import AudioKit_ to any of my project swift files Xcode can't find it, but I think this is due to mentioned error.

I'm using XCode 12.4 and an empty project for tvOS, haven't done anything on it yet.

<img width="1044" alt="Captura de Pantalla 2021-04-25 a la(s) 2 03 46" src="https://user-images.githubusercontent.com/35291751/115984025-7ac85d80-a56a-11eb-9aa6-9b508812ef0c.png">

**Comment by aure** [comment]
ah yeah, that function should be behind a tvOS check. I'll have a look.

**Comment by aure** [comment]
It should be fixed on the v5-develop branch, can you try it out and make sure it works for you?
