### ISSUE TITLE
AppleSequencer().setLength can't change

### ISSUE THREAD

**Issue by benben-hello** [AudioKit/AudioKit#2474]
**Describe the bug**
1. When I first set the length to 4:  such as sequencer.setLength(Duration(beats: 3)), He can work well
2. When I set a value greater than 4：such as sequencer.setLength(Duration(beats: 5)),It stops when it gets to 4
3. When I set a value Less than 4:  such as sequencer.setLength(Duration(beats: 2)), He can work well  

So setLength can only be less than the previous value, it can't be greater than that

**Details (please complete the following information):**
 - Type: [e.g. iPhoneX]
 - OS: [e.g. iOS14.1]
 - AudioKit Version [e.g. 5.0]
 - V5 main

**Comment by aure** [comment]
I tried to write a test to show this but it works in tests. Can you provide a project or test that shows this as not working?

**Comment by benben-hello** [comment]
I found the problem, but I don't know what to do about it

![image](https://user-images.githubusercontent.com/12512421/117249216-cc7abd00-ae73-11eb-8a2e-efba2fe96025.png)
![image](https://user-images.githubusercontent.com/12512421/117249257-dbfa0600-ae73-11eb-9cb2-e5e69d580924.png)
