### ISSUE TITLE
ObjectAL for iPhone to AudioKit

### ISSUE THREAD

**Issue by swapnilnandgave** [AudioKit/AudioKit#2484]
ObjectAL for iPhone is deprecated and not in swift programming language and we have decided to remove and try audio kit so we are looking suggestion for moving ObjectAL for iPhone to AudioKit.
Here is the link for more reference
https://github.com/kstenerud/ObjectAL-for-iPhone
and it provided below main features and 
- Play, Pause, Stop, Loop
- Volume, Pitch, Pan, Mute
- Maybe some "power user" stuff, such as preloading and session control

We wanted to know whether that is possible in AudioKit before moving to AudioKit. 
Can you help me with this?

**Comment by aure** [comment]
You can definitely use AudioKit for those features. I'm not sure how this is an "issue" with AudioKit though. Would you like to come to our AudioKit Slack group and perhaps find people who can help you? If so, give me your email address.

**Comment by developer-celusion** [comment]
Thanks for quick reply. I can provide email address. Can you send invitation to 
swapnil.nandgave@celusion.com
