### ISSUE TITLE
NodeParameters for Apple AU nodes

### ISSUE THREAD

**Issue by maxmuermann** [AudioKit/AudioKit#2485]
Apple-AU-based nodes do not use automatable `NodeParameter`

Nodes based on Apple's AudioUnits (Mixer, Delay, Distortion, Reverb, Compressor, PeakLimiter, etc.) do not use `NodeParameter` to model their parameters. All node parameters should be automatable in the same way, but `Mixer().$volume.ramp(to: 0.9, duration: 1.2)` is not valid at the moment. Mixer.volume is an `AUValue` (`typealias Float`), rather than a `NodeParameter`.

It looks like `NodeParameter` is an internal concept to AudioKit and is automated in the internal AudioUnit C code; I have not found any obvious way to extend this to non-AK AudioUnit parameters.

**Comment by wtholliday** [comment]
After some cleanup, which has been good, I think Aure is right: AVAudioMixerNode can't be automated. Still, it's annoying that the mixer volume can't be automated. We could consider adding a Fader inside the Mixer to automate volume, etc.

**Comment by aure** [comment]
Alternatively, we can also leave it up to the users to add faders when they want automation. While this issue has been an inspiration for a lot of good work, I'm going to close it.

**Comment by maxmuermann** [comment]
The workaround of using a Fader after a Mixer works, of course - that's what I had ended up doing as well - but it doesn't solve the problem of all the other parameters for the Apple nodes.

After some more thought, I'd think I want to have a consistent interface for _all_ node parameters, whether they are Apple AUs or not. The `@Parameter` property wrapper is really nice, because I can just pass an instance of the wrapper to my UI components. It seems to me that the parameter metadata (currently NodeParameterDef) might be implemented in the property wrapper itself, so you'd have things like `mixer.$volume.name`, `mixer.$volume.range`, `mixer.$volume.unit`, or even something like `mixer.$volume.stringValue` for display purposes.

Theoretically, it should also be possible to provide some sort of timer-based automation as a fallback for non-AK parameters - I'm pretty sure I implemented something like that a couple of years ago.

I'd be happy to help out with this, if you think it would be useful.

**Comment by wtholliday** [comment]
Thanks @maxmuermann ! If you take a look at the 2485_automation branch, we're going in the direction of passing parameter defs to each `@Parameter`.

If you have some time, what we need is:
- Unit tests on the develop branch for `Synth` and `Sampler`
- A code coverage build to see which nodes are missing tests
- Parameter definitions for any `@Parameter` missing one so we can make the def non-optional
