### ISSUE TITLE
Congratulations on 5.0 launch! Thanks team! Any up for porting the Roland filter to previous versions of Audiokit? Thanks in advance!

### ISSUE THREAD

**Issue by 01GOD** [AudioKit/AudioKit#2488]
Any up for porting the Roland filter to previous versions of Audiokit? There is no roland filter in pre-5 audiokit versions. 

Any guidance on how to use that filter with previous versions is also appreciated. 

Thanks in advance!

**Comment by aure** [comment]
Would you like to be on the AudioKit Slack? I'm happy to make that happen, but this should not be on the Github issues page.

**Comment by aure** [comment]
Plus, the Roland Filter has been in AudioKit for a long time.
