### ISSUE TITLE
Issue archiving projects containing beta AudioKit 5 packages

### ISSUE THREAD

**Issue by b-hutchison** [AudioKit/AudioKit#2491]
**Description**:
Issue archiving projects containing beta AudioKit 5 packages. When I add the release version of AudioKit 5 to my project, it archives properly as an “iOS App Archive”. If I add a beta package instead, with no other changes, my Xcode project archives as a “Generic Xcode Archive”, which cannot be deployed.

**Steps to reproduce the behavior**:
To test AudioKit release version, which archives properly:

**In Xcode**:
Open your project, or create a new one. For my testing, I just created a new iOS App project.

With your project open:
File->Swift Packages->Add Package Dependency
Select AudioKit, or enter https://github.com/AudioKit/AudioKit.git 
Click Next
Click Branch: and select or enter: main. Click Next
Swift Package Manager resolves and checks out the package.
"Add Package" window appears. Click Finish
"AudioKit main" appears under Swift Package Dependencies in the Xcode Navigator.

Product->Archive
Organizer window shows newly created archive, of type "iOS App Archive"

Once you've verified your project archives properly with the release version:

To test a beta version, which does not archive properly:

**In Xcode**:
Select your project in the Navigator
Select Project in Editor 
Click Swift Packages in Editor
Double-click on AudioKit 
Click Commit and enter a beta commit number. I used: 

f544c2c252488f4c406ea1adc5689a086114c266

Click Done
Swift Package Manager checks out the beta package
"AudioKit f544c2c" appears under Swift Package Dependencies in the Xcode Navigator.

Product->Archive
Organizer window shows newly created archive, of type "Generic Xcode Archive"

Both the release and beta versions build and run on devices and simulators. But the project using the beta version cannot be archived to upload to the App Store or TestFlight.

**Expected behavior**
I would expect project archives built using beta versions of AudioKit to be the same format as those built with the release version.

**Details**
2015 iMac
Big Sur 11.3.1
Xcode version 12.5 (12E262)

<img width="1112" alt="Screen Shot 2021-05-07 at 3 10 45 PM" src="https://user-images.githubusercontent.com/26174604/117513443-8a6e7b80-af46-11eb-98e7-a4789269da6a.png">
<img width="1112" alt="Screen Shot 2021-05-07 at 2 22 17 PM" src="https://user-images.githubusercontent.com/26174604/117511545-bbe54800-af42-11eb-92ca-71c86927cf81.png">

**Comment by aure** [comment]
I'm not going to worry about this any longer.
