### ISSUE TITLE
MIDICallbackInstrument can't get 'noteOff' status !!!

### ISSUE THREAD

**Issue by benben-hello** [AudioKit/AudioKit#2492]
- AudioKit Version [e.g. 5.0.1]

Today, I upgraded to the new version to 5.0.1, and found that the callback state of MIDICallbackInstrument only has NoteOn, without NoteOff, it is normal in 5.0.0.

I use the Cookbook CallbackInstrumentConductor Demo, found the same only noteOn state.

I'm sorry my English is poor.
best wishes！

![image](https://user-images.githubusercontent.com/12512421/117539735-8cb40100-b03e-11eb-88ca-aba0e5f10fe9.png)

**Comment by aure** [comment]
You can add `midiStatus == .noteOff` to react to note offs.

**Comment by benben-hello** [comment]
Yes, I have added midiStatus ==.noteoff, but callback only .noteOn

**Comment by aure** [comment]
Some keyboards do not send noteOff and instead send a noteOn with a velocity of zero and its up to you to treat those like noteOffs.

**Comment by benben-hello** [comment]
Thanks for your reply.
In the same condition, in V5.0 noteOn,noteOff, but in V5.0.1 there is only noteOn, I think this is a bug.
You can see the Cookbook CallbackInstrumentConductor Demo, in V5main noteOff, but only noteOn in version 5.0.1.

**Comment by aure** [comment]
Its fixed on the develop branch.

**Comment by aure** [comment]
Will be fine in 5.0.2 which will probably be out soon.

**Comment by benben-hello** [comment]
Thank you very much,  Sweet dreams！

**Comment by newagerep03** [comment]
What is 5.0.2?

**Comment by aure** [comment]
We didn't put out a 5.0.2 we made changes that warranted 5.1
