### ISSUE TITLE
With createVirtualPorts, uniqueID is not used

### ISSUE THREAD

**Issue by ShowtimeSoft** [AudioKit/AudioKit#2494]
When I create virtual MIDI ports (midi.createVirtualPorts) , the PortID that I define does not work, instead, default PortIDs (2000000 and 2000001) are used to create the input and output ports.

The bug seems to be in MIDI+VirtualPorts.swift line 26 and line 27. The uniqueIDs are not forwarded from line 23.

I do realise that each port (input and output) need to have unique IDs, so a fix could be something like adding 1 to each of the created output ports.

**To Reproduce**
1.
I create a (set of) virtual midi ports, where I specify a uniqueID, say 1000000
let midi = MIDI()
midi.createVirtualPorts(numberOfPort: 1, [1000000], names: ["Test Port"])

2.
I check the UIDs of the ports created, using 
midi.inputInfos[0].midiUniqueID
midi.destinationInfos[0].midiUniqueID

3.
I get 2000000 and 2000001

**Expected behavior**
I would expect to get midiUniqueID = 1000000 and 1000001

**Details**
macOS Big Sur 11.2.3
AudioKit v5
I'm building for Mac (not iOS).

**Additional**
"numberOfPort" seems to be a typo, should have been "numberOfPorts"

**Comment by aure** [comment]
Reopen if the fix is not working for you on the develop branch.
