### ISSUE TITLE
Virtual MIDI ports, inputs and outputs are swapped

### ISSUE THREAD

**Issue by ShowtimeSoft** [AudioKit/AudioKit#2495]
When I list my virtual MIDI ports, input ports and output ports are swapped.
Virtual input ports are listed as output ports and vice versa.

**To Reproduce**

1. I create my ports:
let midi = MIDI()

midi.createVirtualInputPorts(numberOfPort: 1, [Int32(1000000)], names: ["MIDI Test Input Port"])
midi.createVirtualOutputPorts(numberOfPort: 1, [Int32(2000000)], names: ["MIDI Test Output Port"])

2. I list them, using:
midi.inputNames
and
midi.destinationNames

3. I see, that 
midi.inputNames includes "MIDI Test Output Port"
midi.destinationNames includes "MIDI Test Input Port"

**Expected behavior**
I would expect that my input port is listed in midi.inputNames, and output in outputNames.

**Screenshots**
![Artboard](https://user-images.githubusercontent.com/77680597/117583475-9d7c7980-b107-11eb-879b-b0c7d1b0baed.png)

**Details (please complete the following information):**
 - Type: Mac
 - OS: Big Sur 11.2.3
 - AudioKit Version 5

**Additional context**
StackOverflow user "Eggsalat" suggested:
In MIDI+VirtualPorts.swift, createVirtualInputPorts calls MIDIDestinationCreateWithBlock, and createVirtualOutputPorts calls MIDISourceCreate. Maybe that's where the issue is?

**Comment by aure** [comment]
Bad commit message, but this should be addressed here c7438568b468eeefcda855d8ddce1e3b9ac4f239

Let me know if that works as expected.

**Comment by ShowtimeSoft** [comment]
I do like 'count' rather than 'numberOfPort'.
I also like that we got rid of an unwanted whitespace in front of port names.

However, on core functionality, I now have two issues that relates to ports being swapped.

1) In the application that I send FROM (Logic Pro), the destination port now shows up as "MIDI Test Output Port".
I would expect the INPUT port to show up.

2) I can create only one port, either input or output. Only the last port created show up.

If I:
        midi.createVirtualInputPorts(count: 1, uniqueIDs: [Int32(1200000)], names: ["MIDI Test Input Port"])
        midi.createVirtualOutputPorts(count: 1, uniqueIDs: [Int32(1500000)], names: ["MIDI Test Output Port"])

Only the Output port is available

If I:

        midi.createVirtualOutputPorts(count: 1, uniqueIDs: [Int32(1500000)], names: ["MIDI Test Output Port"])
        midi.createVirtualInputPorts(count: 1, uniqueIDs: [Int32(1200000)], names: ["MIDI Test Input Port"])

Only the Input port is available.

Seems that the destroyInputPort and destroyVirtualOutput port destroy the wrong ports?

This might dig deeper, and perhaps it drills down to a bug in CoreMIDI?

**Comment by ShowtimeSoft** [comment]
Aure, I have done a small demonstration project for this issue. It's a MIDI monitor that lists the inputs and outputs with their PortIDs. It tracks incoming MIDI messages with their PortIds.
As I'm a newbie on this, I have no idea how to share it on GitHub, so I've simply zipped it an put it on DropBox:
https://www.dropbox.com/s/szeaiqjo7na015r/MIDI%20Port%20Test.zip?dl=0

Use it if you will. If not, it was fun to do anyway :-)

**Comment by aure** [comment]
This is great, sample projects help us a lot.

**Comment by aure** [comment]
@ShowtimeSoft Can you give @emurray2 's solution a shot. You can either copy the file that he changed, or upgrade to develop. There have been other change for 5.2 though, so you might have some migration headaches. 5.2 is not ready for release yet.

**Comment by ShowtimeSoft** [comment]
Thanks, guys!

@emurray2, I'd very much like to see your example project, as I can still not quite make it work as expected.
Fixed: I can now create both an input and an output port.
Still, to address a specific port ID, I need to swap the portUIDs, using an input ports uid for destination.

I do have a confession here. Perhaps I have totally misunderstood the concept of virtual ports. I'd like to hear what you think.

My understanding was that I was creating virtual input and destination ports _of my app_.
In that, I would expect the virtual destinations to be listed as destinations.

But the more I think of it, it seems that the virtual ports conceptually live _outside the app_, as stand alone objects.
In that thinking, it makes sense that the input of the virtual port is listed in the destination list of my app.

I've tried to make a diagram for this.

![Virtual Ports](https://user-images.githubusercontent.com/77680597/119262363-349f0200-bbdb-11eb-803e-b3fa1aa4935e.png)

Is that correctly understood?

Still, no matter if I use main or develop, I do need to swap the uids, using the inputport uid as destination port uid if I want to target a specific port.

Finally, I'm experiencing that I can't use both virtual ports and physical ports at the same time.
If I call midi.openOutput(), messages are sent out on the physical ports, but the virtual ports doesn't work anymore.
@aure, should I file this as a separate issue?

**Comment by emurray2** [comment]
- You're welcome! I would love to share a Cookbook example I have of sending/receiving MIDI to an external receiver. The way your diagram is set up is how the virtual ports are set up right now. For example, creating virtual input ports actually creates a destination input port for the receiver. I'll do some more tests and see if I can make the `openOutput()` more clear. I believe that is the default function for opening a virtual output port with no parameters provided.

**Comment by ShowtimeSoft** [comment]
That sounds fantastic!

Not sure about openOutput(). I think it is for opening the physical outputs.
At least, that seems to be the case with regards to inputs.
If I midi.openInput(), I do receive messages from my physical device. If not, I don't.

If I do midi.openOutput(), I can send to my physical device, but then it seems that the virtual port is disabled.

**Comment by emurray2** [comment]
Interesting... I'll do some tests in the next couple of days and try it out. For now, here's a zip project demonstrating what I've done so far. The `develop` branch seems to be able to handle multiple virtual inputs and outputs at the same time without destroying them this time.
[MIDI Debug.zip](https://github.com/AudioKit/AudioKit/files/6528580/MIDI.Debug.zip)

**Comment by ShowtimeSoft** [comment]
@emurray2 I tried to run your example, but could not get it to work. As far as I understand, it can't find AudioKit.

![Screenshot 2021-05-26 at 08 45 43](https://user-images.githubusercontent.com/77680597/119614724-ed915680-bdfe-11eb-9b9c-3b5f02e73dd0.png)

I tried to link to AudioKit as a package dependency. It worked, but naturally, the develop branch did not include the changes you made.

**Comment by ShowtimeSoft** [comment]
@emurray2 In case it can be of any help, I have attached my Test App.
Compiled (MacOS Big Sur)

[MIDI Port Test.zip](https://github.com/AudioKit/AudioKit/files/6544474/MIDI.Port.Test.zip)

Source Code:
[MIDI Port Test Source.zip](https://github.com/AudioKit/AudioKit/files/6544492/MIDI.Port.Test.Source.zip)

**Comment by emurray2** [comment]
Oh awesome! I have been using it, and it's a big help! The ports don't show up correctly yet when a MIDI message is received, but that's what I'm going to work on today. It's not anything wrong with the app (but I need to make sure I have everything organized in the MIDI API itself).

For the package, I think I included a local one on my system. That was my mistake and probably why it's not showing up.
Try this one instead:
[MIDI Debug.zip](https://github.com/AudioKit/AudioKit/files/6548329/MIDI.Debug.zip)

Also, if it ever gets out of sync, just delete and re-add the package or right click on the package itself and select "Update."
