### ISSUE TITLE
MIDICallbackInstrument can't get 'noteOn' status

### ISSUE THREAD

**Issue by benben-hello** [AudioKit/AudioKit#2503]
Will be fine in 5.0.2 which will probably be out soon.

_Originally posted by @aure in https://github.com/AudioKit/AudioKit/issues/2492#issuecomment-836281469_

Hello, today I updated to 5.1.0, but I found a new problem, noteOff is correct, but there is no noteOn status.

Only the first note is correct.

**Comment by aure** [comment]
Maybe you should get on the develop branch so you don't have to wait until releases to test.

**Comment by aure** [comment]
I am not seeing this behavior, or I don't understand what you mean.

**Comment by herrDerToene** [comment]
Had the same issue when I was upgrading to the latest release yesterday. This is how I setup the track for the sequencer:

```
        let track = sequencer.tracks[0]
        track.resetToInit()
        track.add(noteNumber: firstNote,
                  velocity: 100,
                  position: Duration(beats: 0 + Double(beatDelay)),
                  duration: Duration(beats: 1))
        track.add(noteNumber: secondNote,
                  velocity: 100,
                  position: Duration(beats: 1 + Double(beatDelay)),
                  duration: Duration(beats: 1))
        return track
```

The MIDICallbackInstrument gets messages in the following order:
noteOn
noteOff
noteOff

So the second noteOn was missing. I "fixed" it by subtracting 0.00001 from the duration of the first note. Afterwards:
noteOn
noteOff
noteOn
noteOff

like expected.

**Comment by aure** [comment]
@herrDerToene this code doesn't compile for latest AudioKit. I changed it up and ran it as a tests and it showed noteOn/noteOff properly.

**Comment by herrDerToene** [comment]
@aure thanks for looking into it. To clear things up I created a small project stripped down to what I was trying to achieve: a Sampler and a CallbackInstrument fed by the same track, the Sampler should play the sound, the CallbackInstrument should drive the UI.

When Playing the sequence I still get the following output:
Note On: 60
Note Off: 60
Note Off: 61

The second NoteOn-message doesn't reach the Callback for some reason. It also could be me using it the wrong way? Any help is appreciated.

[CallbackBugInvestigation.zip](https://github.com/AudioKit/AudioKit/files/6644560/CallbackBugInvestigation.zip)

**Comment by jaapmengers** [comment]
I'm also experiencing this problem in my project since upgrading from version 5.0.0 to 5.1.0. I ran the reproduction scenario that @herrDerToene posted above, and I can confirm the behaviour that they mentioned. I also use the NoteOn-messages to update my UI, which broke since upgrading to 5.1.0.
