### ISSUE TITLE
5.0.1  build in Xcode 12.4 error: failed to build module 'AudioKit' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced.

### ISSUE THREAD

**Issue by zgyxl** [AudioKit/AudioKit#2504]
**Confirm you should be adding the bug here**
If your issue is implementing AudioKit in your own code, post your problem to [StackOverflow](https://stackoverflow.com/search?q=AudioKit) with the #AudioKit hashtag.

If you can make the issue happen on [AudioKit 5's Cookbook app](https://github.com/AudioKit/Cookbook/) then you can create an issue directly on that repository as well.

GitHub Issues should only be used for confirmed problems with AudioKit and
well-defined feature requests.

Sponsors will get more attention: https://github.com/sponsors/aure

**Describe the bug**

**To Reproduce**
3. See / hear error

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - Type: [e.g. iPhone6, iPad, Mac]
 - OS: [e.g. iOS13.1]
 - AudioKit Version [e.g. 5.0]

**Additional context**

**Comment by aure** [comment]
AudioKit 5.1 is out and most of this issue is just the boilerplate text.
