### ISSUE TITLE
AudioPlayer, pause() cannot be resumed?

### ISSUE THREAD

**Issue by BarryHaanstra** [AudioKit/AudioKit#2507]
**Describe the bug**
AudioPlayer does not resume after pausing when I call start(), it just restarts from the beginning.
In the wiki the pause() function description says 'Pauses audio player. Calling play() will resume from the paused time.'
Also, I think the old AKAudioPlayer had 'resume', this one has not. I'm slightly confused :)

**To Reproduce**
Set up a simple AudioPlayer, try to do start/pause/start.

**Expected behavior**
It should restart at the same time it was paused at (or a resume method should be implemented so I can use that?)

**Details (please complete the following information):**
 - Type: iPhone 11
 - OS: iOS 14.5.1
 - AudioKit Version: 5.1

**Additional context**
I looked at the code, and a pausedTime is stored, but doesn't seem to be used at all. Also, it is an internal property so it can't be used to call `play(from:)`

**Comment by aure** [comment]
I wrote this test to verify and demonstrate your issue 
```    
func testPlayAfterPause() {
        guard let url = Bundle.module.url(forResource: "TestResources/12345", withExtension: "wav"),
              let file = try? AVAudioFile(forReading: url) else {
            XCTFail("Didn't generate test file")
            return
        }

        let engine = AudioEngine()
        let player = AudioPlayer()
        engine.output = player

        let audio = engine.startTest(totalDuration: 5.0)
        player.file = file

        player.play()
        audio.append(engine.render(duration: 2.0))
        player.pause()
        audio.append(engine.render(duration: 1.0))
        player.play()
        audio.append(engine.render(duration: 2.0))

        testMD5(audio)
        audio.audition()
    }
```

**Comment by aure** [comment]
Added a resume() function and made play() work as well.
