### ISSUE TITLE
Crash during XCode Unit Test run: "Bank manager destroyed with active banks"

### ISSUE THREAD

**Issue by btfranklin** [AudioKit/AudioKit#2510]
My relatively simple unit tests in SongSprout have started crashing out with the latest AudioKit release 5.1.0, and it happens against the develop branch as well. I've tried a few things to isolate the problem, and it appears to be triggered by the call to `mixer.connectionTreeDescription` (surprisingly enough).

Here's what the output looks like:
```
Test Suite 'AccompanimentTrackDefinitionTests' started at 2021-05-20 10:31:55.117
Test Case '-[SongSproutTests.AccompanimentTrackDefinitionTests testMakeNodeAndConnectRoute]' started.
2021-05-20 10:31:55.163155-0700 xctest[74766:4718854] [midi] MIDI.swift:init():52:Initializing MIDI (MIDI.swift:init():52)
2021-05-20 10:31:57.243504-0700 xctest[74766:4718854]  ASSERT FAILURE: Bank manager destroyed with active banks
Program ended with exit code: 9
```

While this error may _seem_ to have something to do with the financial system, I suspect it has more to do with soundbanks of some kind.

Should be easy to reproduce by just running unit tests from this project:
https://github.com/dunesailer/SongSprout

**Comment by aure** [comment]
That's not a very good warning message, but for your tests, the main issue is that you're not connecting the mixer. I can add a check to make sure the engine is not null when querying for the connectionTreeDescription, but for your test, I just added

``` 
        let engine = AudioEngine()
        engine.output = mixer
        try! engine.start()
 ```
 in the first test that failed, before the connectionTreeDescription request and the test passed.

**Comment by btfranklin** [comment]
Okay, thank you for the tip to solve this. However, it does strike me a bit as unexpected behavior. I would not expect the calling of connectionTreeDescription to fail based on a specific attachment state of the graph. In fact, this used to pass just fine. Is the underlying cause of this related to the fact that I load a soundfont during the creation of the node, which requires some engine resources that it didn't require before?

**Comment by aure** [comment]
I don't understand how it could have ever worked without an engine being defined. Could it be you create the engine elsewhere in your code before?

**Comment by btfranklin** [comment]
No, the only place I create the engine has always only been inside the Orchestrion class itself, which never gets called  by these unit tests. 
<img width="269" alt="Screen Shot 2021-05-23 at 10 14 44 AM" src="https://user-images.githubusercontent.com/23176608/119270061-b842f980-bbaf-11eb-92ba-c5efa9b1bd0e.png">

I try to write unit tests so they are as self-contained as possible, so I avoided initializing anything that I didn't have to. I actually kind of liked the fact that these used to work as sort of "standalone graphs", even though that's certainly not much of a realistic use case (unless somebody wanted to do something like pre-assemble various graphs and then conditionally hook them up to the output mixer based on some change of condition, maybe?)

**Comment by aure** [comment]
So somehow in the past that engine must have been the one providing the connectionTreeDescription. Why isn't it doing so anymore?

**Comment by aure** [comment]
I think it has to do with Node now being a protocol. Before it may have kept a reference to the engine internally or something.

**Comment by btfranklin** [comment]
That's a reasonable theory. I don't have a better one. :) If you think it's important to get to the bottom of this, I can do some forensic analysis to try to figure it out. If not, I'm comfortable just moving on and chalking it up as "interesting".
