### ISSUE TITLE
AudioiKit 4.11.x release with missing Apple Silicon architectures in XCFrameworks (ios-arm64_x86_64-maccatalyst, macos-arm64_x86_64)

### ISSUE THREAD

**Issue by techfreak01** [AudioKit/AudioKit#2515]
With the latest 4.11.x release (4.11.2) of AudioKit I'm getting the following linker warning when creating a build an iOS app with Catalyst support for "Any Mac (Apple Silicone, Intel)":

`ld: warning: ignoring file /.../DerivedData/.../Build/Products/Debug-maccatalyst/AudioKit.framework/AudioKit, building for Mac Catalyst-arm64 but attempting to link with file built for Mac Catalyst-x86_64
ios-arm64_x86_64-simulator`

So the app will probably not work on Apple Silicone Macs.

Would it be possible to create a 4.11.x release with XCFrameworks containing the same architectures as current 5.x releases?
Since AudioKit 5 comes with many breaking changes in the API, it would be great to have a 4.11.x release that also supports these architectures.

**Comment by aure** [comment]
All the framework creating resources are in the repository itself if you want to create your own variants.
