### ISSUE TITLE
https://github.com/AudioKit/ExtendingCore

### ISSUE THREAD

**Issue by themichael123** [AudioKit/AudioKit#2517]
Hi! We are running into issues relating to our AudioKit extensions with AudioKit V5. Could this document (https://github.com/AudioKit/ExtendingCore) perhaps be updated? Thanks.

**Comment by aure** [comment]
Hi, I've removed that repo for now since it is woefully out of date and can only lead people astray. Give us a couple of weeks to release the next version which will make extending AudioKit very clear.

**Comment by themichael123** [comment]
Excellent, thanks!
