### ISSUE TITLE
Any way to use AudioKit 4.11 in Xcode 12.4 or has Apple broken it fully? (Failed to build module 'AudioKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)')

### ISSUE THREAD

**Issue by 01GOD** [AudioKit/AudioKit#2519]
How to use AudioKit 4.11 in Xcode 12.4? Or is there a version of Xcode it's compatible with that can also build apps that App Store Connect will accept? 

Compiler error is: Failed to build module 'AudioKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'

Thanks in advance for a solution that isn't "use a later version of AudioKit". Lots of documentation and examples seem to be based on 4.11 at the latest. 

PS: I imagine many software engineers are unhappy with Apple the past couple of years. I personally regret having invested years into software engineering on the Apple platform at this point generally. Sad to watch good apps and frameworks being broken rampantly by corporate "issues".

**Comment by aure** [comment]
I feel your pain, but this is not an issue that I am able to address.
