### ISSUE TITLE
USER_HEADER_SEARCH_PATHS for swift projects with Pods

### ISSUE THREAD

**Issue by Gutty1** [audiokit/AudioKit#252]
Hi,
I suceed to compile my code in swift copying the AudioKit libraries into my project and following all the configuration settings from the tutorials.
When I try to use the audiokit in cocoaPods, I get an error in my Bridging-Header.h that the MKFoundation.h is not found. I really would like to use the cocoa Pods with AudioKit libraries same as I use for all my other 3rd party libraries.

What path should I define in the build settings ->USER_HEADER_SEARCH_PATHS for using readding the headers from cocoapods?

is Audiokit Cocoapods supported for swift or only for Objective-C?

A prompty response will be higly appreciated
Thanks in advance
Gutty

**Comment by aure** [comment]
I don't use CocoaPods much, perhaps someone else can comment on this.  I assumed it would be similar to the regular swift setup.

**Comment by aure** [comment]
Closing this for now since there hasn't been activity on the issue for three weeks.
