### ISSUE TITLE
TB303 Filter 

### ISSUE THREAD

**Issue by 01GOD** [AudioKit/AudioKit#2520]
In the most recent version of the cookbook (AudioKit 5.1), the demo for the Roland filter seems simply very wrong. I have used the original Roland product and own some of the best software emulations. Perhaps an incorrect filter model was ported from another library without comparing or is the filter range simply extremely extreme in the AudioKit emulation?

First time running the most recent version of the cookbook and ran the demo for the Roland filter (AudioKit 5.1). 

That filter model seems simply very wrong. I am EXTREMELY familiar with the actual Roland filter sound and have used the original Roland product and have licensed copies of some of the best commercial software emulations. Perhaps an incorrect filter model was ported from another library without comparing or is the filter range simply extremely extreme in the AudioKit emulation? I doubt it's the range, but if the range is overly extreme and that is causing the issue, it seems advisable to provide a "stock-ish range" setting. It's certainly nice to be able to get a sound at least vaguely similar to what one would expect straight out of the box. 

I was getting ready to make something similar to that Roland product with AudioKit, but that filter simply seems wrong. 

Thanks in advance! (and thanks again for AudioKit)

PS: Adding an unaccented, un-auto-wah'd, un-envelope-followed bass synth loop to those previews is also advisable as it's not as easy to hear the wonderful AudioKit effects otherwise.

**Comment by aure** [comment]
Since this filter has been moved to the other repo I opened a new issue there and I'll close this one.
