### ISSUE TITLE
Cannot find type 'NodeOutputPlot' in scope. 

### ISSUE THREAD

**Issue by isurugajasinghe** [AudioKit/AudioKit#2521]
**Screenshots**

<img width="887" alt="Screenshot 2021-05-27 at 9 32 49 PM" src="https://user-images.githubusercontent.com/23732707/119859517-17e43080-bf33-11eb-9880-3754e8af473f.png">

**Details (please complete the following information):**
 - Type: iphone
 - OS: iOS 13.0+
 - AudioKit Version 5.0.0

**Comment by aure** [comment]
NodeOutputPlot is gone. We have NodeOutputView in AudioKitUI. In any case, its an issue for the AudioKitUI repo, not AudioKit itself.
