### ISSUE TITLE
iOS 12 Support

### ISSUE THREAD

**Issue by wallisch** [AudioKit/AudioKit#2525]
I am currently migrating from AudioKit 4 via Carthage to AudioKit 5 via SPM, and of course I tried to use AudioKit 5.2 right away. Unfortunately, it now declares iOS 13 as minimum target version, as opposed to iOS 11 in 5.1

Would it be possible to re-add at least iOS 12 support, since that version is still actively maintained by Apple and still used by a lot of devices which can't upgrade to iOS 13 and beyond? I would be glad to help with this, if desired.

_Sidenote: It's generally not optimal to introduce breaking changes in non-major versions, given how SPM works by default (Semver, Up to next major)_

**Comment by aure** [comment]
We don't support more than 2 versions back, sorry.

**Comment by aure** [comment]
As for major changes, might as well consider v5 really the start of 5, as its where we fully embraced swift package manager. I didn't want to go to 6 a month after 5 came out. :)

**Comment by wallisch** [comment]
I understand, thanks for the quick response thought.
I guess we'll just stay on 5.1 until we can drop iOS 12

**Comment by benben-hello** [comment]
It's a sad story. Oooo ooo ooo

**Comment by aure** [comment]
It is open source you can fork it and change the min version and see what breaks. You might not even need it,

**Comment by wallisch** [comment]
Can confirm, in the current state you only need to change the target version in Package.swift, the rest is working fine.

**Comment by aure** [comment]
Ahh, yeah, it could very well be that we moved the target, changed a bunch of things, moved them around and never tested to see if the target could go back down. 🤷

**Comment by m-herold** [comment]
I can also confirm that AudioKit is working perfectly with iOS 12. All we did was changing the target version as mentioned by @wallisch:

```
diff --git a/Package.swift b/Package.swift
index 2fb2b8e2ab..8e14ace5b1 100644
--- a/Package.swift
+++ b/Package.swift
@@ -5,7 +5,7 @@ import PackageDescription
 
 let package = Package(
     name: "AudioKit",
-    platforms: [.macOS(.v10_14), .iOS(.v13), .tvOS(.v13)],
+    platforms: [.macOS(.v10_14), .iOS(.v12), .tvOS(.v12)],
     products: [.library(name: "AudioKit", targets: ["AudioKit", "AudioKitEX"])],
     targets: [
         .target(name: "AudioKit"),
```

Although it works, including AudioKit from a separate fork is not an ideal solution. Is there any chance that you put back iOS 12 in a future release? Unfortunately we can not drop iOS 12 (and I assume many others can not either), since it is the latest supported iOS version for many older but still "popular" devices (5S,6).

**Comment by aure** [comment]
Yes I will bump it back down to iOS12 for 5.2.1 on all the repos that allow me to.

**Comment by m-herold** [comment]
That's great news! Thanks @aure!
