### ISSUE TITLE
Mixer tree not wired together correctly after engine started

### ISSUE THREAD

**Issue by wallisch** [AudioKit/AudioKit#2527]
When wiring together a connection tree after after the engine started, `Mixer.addInput(node:)` doesn't seem to behave correctly, so an AudioPlayer at the end of the chain fails with `player started when in a disconnected state (com.apple.coreaudio.avfaudio)`.

However, according to the output of `AudioEngine.connectionTreeDescription`, the tree looks correct.
This used to work in AudioKit 4 (with the `connect(to:)` method). Is this an intentional change or a regression?

Code to reproduce the issue (for `NodeTests.swift`)
``` swift
func testWiringAfterEngineStart() {
    let engine = AudioEngine()
    let engineMixer = Mixer()

    engine.output = engineMixer
    try? engine.start()

    let subtreeMixer = Mixer()
    engineMixer.addInput(subtreeMixer)

    let url = Bundle.module.url(forResource: "12345", withExtension: "wav", subdirectory: "TestResources")!
    let player = AudioPlayer(url: url)!
    subtreeMixer.addInput(player)

    print(engine.connectionTreeDescription)
    player.play()

    engine.stop()
}
```

Output:
```
AudioKit | ↳Mixer("AudioKit Engine Mixer")
AudioKit |  ↳Mixer("0x000000013e80d0c0")
AudioKit |   ↳Mixer("0x000000013de3f190")
AudioKit |    ↳AudioPlayer
error: -[AudioKitTests.NodeTests testWiringAfterEngineStart] : player started when in a disconnected state (com.apple.coreaudio.avfaudio)
```

**Comment by wtholliday** [comment]
The more accurate thing to look at is the underlying AVAudioEngine graph:

```
(lldb) po engine.avEngine

________ GraphDescription ________
AVAudioEngineGraph 0x102a0bbb0: initialized = 1, running = 1, number of nodes = 6

	 ******** output chain ********

	 node 0x100fb82f0 {'auou' 'ahal' 'appl'}, 'I'
		 inputs = 1
			 (bus0, en1) <- (bus0) 0x100d38920, {'aumx' 'mcmx' 'appl'}, [ 2 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]

	 node 0x100d38920 {'aumx' 'mcmx' 'appl'}, 'I'
		 outputs = 1
			 (bus0, en1) -> (bus0) 0x100fb82f0, {'auou' 'ahal' 'appl'}, [ 2 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]

	 ******** pending connections - output ********

	 (bus0) 0x100d30780, {'aumx' 'mcmx' 'appl'} -> (bus0) 0x100d38920, {'aumx' 'mcmx' 'appl'}, [ 2 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]

	 (bus0) 0x102a13140, {'aumx' 'mcmx' 'appl'} -> (bus0) 0x100d30780, {'aumx' 'mcmx' 'appl'}, [ 2 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]

	 node 0x102a13140 {'aumx' 'mcmx' 'appl'}, 'U'
		 inputs = 1
			 (bus0, en1) <- (bus0) 0x102a22260, {'aumx' 'mcmx' 'appl'}, [ 2 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]

	 node 0x102a22260 {'aumx' 'mcmx' 'appl'}, 'U'
		 inputs = 1
			 (bus0, en1) <- (bus0) 0x102a20aa0, {'augn' 'sspl' 'appl'}, [ 2 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]
		 outputs = 1
			 (bus0, en1) -> (bus0) 0x102a13140, {'aumx' 'mcmx' 'appl'}, [ 2 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]

	 node 0x102a20aa0 {'augn' 'sspl' 'appl'}, 'U'
		 outputs = 1
			 (bus0, en1) -> (bus0) 0x102a22260, {'aumx' 'mcmx' 'appl'}, [ 2 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]
______________________________________
```

Looks like subtreeMixer isn't getting connected to engineMixer. I'll dig further.

**Comment by wtholliday** [comment]
- Don't need `subtreeMixer` to repro
- Bug doesn't occur with `PlaygroundOscillator`

**Comment by wtholliday** [comment]
Seems this has to do with the `PlayerNode` having internal connections. When I remove its internal mixer (using only `AVAudioPlayerNode`), the test passes.

**Comment by ryanfrancesconi** [comment]
looking at the code above, it seems that you'd need to create your subtreeMixer before setting the AudioKit output as the connection tree is made at that point in AK5 and it doesn't play so well with dynamic connections now. There's a lot of funny business involved with making dynamic mixer connections work correctly which is why it worked in AK4... but it's fairly hard to generalize these hacks (and they are still required).

**Comment by ryanfrancesconi** [comment]
Does it work if you change the order to this?

```swift

func testWiringAfterEngineStart() {
    let engine = AudioEngine()
    let engineMixer = Mixer()
    let subtreeMixer = Mixer()
    engineMixer.addInput(subtreeMixer)
    let url = Bundle.module.url(forResource: "12345", withExtension: "wav", subdirectory: "TestResources")!
    let player = AudioPlayer(url: url)!
    subtreeMixer.addInput(player)

    engine.output = engineMixer
    try? engine.start()

    print(engine.connectionTreeDescription)
    player.play()

    engine.stop()
}
```

**Comment by ryanfrancesconi** [comment]
@wtholliday would know much better than me, but as I understand how they have set up AK5, it looks to me that wiring after the engine is started requires initializing an empty mixer first before connecting. If you look at the old AKManager, this was done with the gross addDummyToEmptyMixer() hack.

I still do this in my work like this:

```swift

extension AVAudioEngine {
    var outputFormat: AVAudioFormat {
        outputNode.outputFormat(forBus: 0)
    }
    
    func safeAttach(nodes: [AVAudioNode]) {
        let unattached = nodes.filter { $0.engine == nil }

        for node in unattached {
            attach(node)

            // We don't have a valid lastRenderTime until we query it, might as well do it now
            _ = node.lastRenderTime
        }
    }

    func safeDetach(nodes: [AVAudioNode]) {
        let attached = nodes.filter { $0.engine != nil }
        _ = attached.map { detach($0) }
    }

    func connectAndAttach(_ node1: AVAudioNode, to node2: AVAudioNode, format: AVAudioFormat?) {
        safeAttach(nodes: [node1, node2])

        // see below
        var mixerReset1 = initializeMixer(node1)

        connect(node1, to: node2, format: format)

        mixerReset1?.disconnectOutput()
        mixerReset1 = nil
    }
}

extension AVAudioEngine {
    internal func mixerHasInputs(mixer: AVAudioMixerNode) -> Bool {
        return (0 ..< mixer.numberOfInputs).contains {
            self.inputConnectionPoint(for: mixer, inputBus: $0) != nil
        }
    }

    /// If an AVAudioMixerNode's output connection is made while engine is running, and there are no input connections
    /// on the mixer, subsequent connections made to the mixer will silently fail.  A workaround is to connect a dummy
    /// node to the mixer prior to making a connection, then removing the dummy node after the connection has been made.
    /// This is still a bug as of macOS 11.4 (2021). A place in ADD where this would happen is the Importer editor
    internal func initializeMixer(_ node: AVAudioNode) -> AVAudioNode? {
        // Only an issue if engine is running, node is a mixer, and mixer has no inputs
        guard isRunning,
              let mixer = node as? AVAudioMixerNode,
              !mixerHasInputs(mixer: mixer) else {
            return nil
        }

        let dummy = AVAudioUnitSampler()
        attach(dummy)
        connect(dummy,
                to: mixer,
                format: AudioEngineManager.systemFormat)

        Log.debug("⚠️🎚 Added dummy to mixer (\(mixer) with format", AudioEngineManager.systemFormat)
        return dummy
    }
}

```

**Comment by ryanfrancesconi** [comment]
this is why I assume that they (taylor and aure) decided to remove all dynamic connection support. It does require some careful workarounds, but if you are careful it does work fine and everything can be done with a running engine.

**Comment by wtholliday** [comment]
We didn’t remove dynamic connection support. You can make dynamic
connections to mixers, which is all AVAudioEngine supports.

**Comment by wtholliday** [comment]
@ryanfrancesconi did you file that mixer bug? (initializeMixer)

**Comment by ryanfrancesconi** [comment]
@wtholliday but using mixers as a connection for a one to one node pair isn't performant in large scale graphs. sorry, should of clarified, dynamic connection to any AVAudioNode.

I do need to file this mixer bug if it isn't already there. It's been there kind of the whole time.

**Comment by ryanfrancesconi** [comment]
This is actually the issue here. This will work if changed to the following:

```swift

extension FaderAutomationTests {
    func testWiringAfterEngineStart() {
        let engine = AudioEngine()
        let engineMixer = Mixer()
        engine.output = engineMixer
        try? engine.start()

        let subtreeMixer = Mixer()
        
        let mixerReset1 = engine.avEngine.initializeMixer(engineMixer.avAudioNode)
        engineMixer.addInput(subtreeMixer)
        if let mixerReset = mixerReset1 {
            engine.avEngine.disconnectNodeOutput(mixerReset)
        }

        let url = Bundle.module.url(forResource: "12345",
                                    withExtension: "wav",
                                    subdirectory: "TestResources")!
        let player = AudioPlayer(url: url)!
        
        let mixerReset2 = engine.avEngine.initializeMixer(subtreeMixer.avAudioNode)

        subtreeMixer.addInput(player)

        if let mixerReset = mixerReset2 {
            engine.avEngine.disconnectNodeOutput(mixerReset)
        }
        
        print(engine.connectionTreeDescription)
        player.play()

        wait(for: player.duration)
        
        engine.stop()
    }
}

```

Given that, for the moment it would make sense to put this connection hack somewhere in the makeAVConnections.
I did just file the AVFoundation bug.

**Comment by ryanfrancesconi** [comment]
> We didn’t remove dynamic connection support. You can make dynamic connections to mixers, which is all AVAudioEngine supports.

That's not quite true, the documentation says:

```
You create each audio node separately and attach it to the audio engine. You can perform all operations on audio nodes during runtime—connecting them, disconnecting them, and removing them—with only minor limitations:

Reconnect audio nodes only when they’re upstream of a mixer.
```

And that is true. If your final node in your graph is a mixer, then you do dynamic connections of any type upstream. So assuming the last node is a mixer wired to the engine.outputNode, it does work fine.

The main problem I found that prevents it is this empty mixer thing.

**Comment by wtholliday** [comment]
> using mixers as a connection for a one to one node pair isn't performant in large scale graphs

What was the overhead? I'm surprised that extra mixers matter much, given how trivial the DSP for a mixer is.

**Comment by ryanfrancesconi** [comment]
@wtholliday the overhead for me was total node count. I need to do some more testing in this regard after i stopped using the AVAudioEngine statically though. It's possible that the issues i saw could of been related to that. 

But in general, depending on the system, the output of the engine would be turned into something sounding like an 8bit atari when you passed a certain load threshold. Generally in this case the HAL would spit these out:

`AudioHAL_Client    default    13:49:39.199049 -0700    ADD    HALC_ProxyIOContext.cpp:1068:IOWorkLoop:  HALC_ProxyIOContext::IOWorkLoop: skipping cycle due to overload`

At this point i catch these events, but that was my general move towards using as few nodes as possible. That said, I don't think this is important for AudioKit. If someone is making an engine with 1500+ nodes they probably shouldn't be using AudioKit.

**Comment by wtholliday** [comment]
@aure Want to try make that test into a MD5 test? You'll need to verify that removing the fix breaks the test, which might not happen because of the offline rendering.

**Comment by ryanfrancesconi** [comment]
@wtholliday I think with your fix is that you are leaving dummy nodes in the mixer. the way i do it is to only add the dummy on the input connection to it, then remove it after. 

I didn't know you were going to fix this right away, so i PR'd a different version of a fix.

**Comment by wtholliday** [comment]
Oh sorry I didn't see your PR. I'll revert my change and merge your PR.

**Comment by wtholliday** [comment]
Hopefully Apple will fix this and we can remove this ugly kluge.

**Comment by ryanfrancesconi** [comment]
It is really gross
