### ISSUE TITLE
Some Apple Effects (PeakLimiter, Compressor, Expander) not updatable after engine starts

### ISSUE THREAD

**Issue by themichael123** [AudioKit/AudioKit#2528]
Hi! As far as we can tell, the PeakLimiter is not working i.e. not accepting preGain changes. This can be reproduced in the CookBook PeakLimiter section. 

We are using Version 5.2

Thanks

**Comment by themichael123** [comment]
Fairly confident that this also affects another Apple effect, namely the Compressor.

**Comment by DedicatedDev** [comment]
Yes. Recently I've trying to use Compressor(CookBook), it has no effect about inputed signal

**Comment by aure** [comment]
At this point I think this is actually an Apple bug that we've uncovered. The only way I can see to fix it is to put in explicit index-based setters on the offending audio units.

**Comment by themichael123** [comment]
Thank you for the update. Any fix would be great.

**Comment by eljeff** [comment]
What's the status of this? Saw you fixed it by accessing the params directly as you reference here, but now that code is removed?

**Comment by aure** [comment]
Its fixed, in a better way than that first fix.

**Comment by eljeff** [comment]
What was it? Point me to a commit?

**Comment by eljeff** [comment]
Found it: 
`Removed subscript notation and do the AudioUnit 2.0 type setting	b25b77779`

**Comment by eljeff** [comment]
confirmed this is fixed - gracias @aure 
all those different ways to set auparameters work slightly different so this type of fix makes some sense.
