### ISSUE TITLE
NodeOutputPlot not found

### ISSUE THREAD

**Issue by vittalk** [AudioKit/AudioKit#2529]
The migration guide says that AKNodeOutputPlot  is now NodeOutputPlot, but NodeOutputPlot doesnt exist. 
Can you please clarify.

Thanks, 
-Vittal

**Comment by aure** [comment]
Moved to **https://github.com/AudioKit/AudioKitUI**

**Comment by vittalk** [comment]
Thanks Aure,
I grepd in AudioKitUI. I didnt find NodeOutputPlot  anywhere in the code
Please let me know where I am missing.
Thanks and Best Regards,
-Vittal

**Comment by vittalk** [comment]
I included AudioKit main branch using the SPM, and it picked up AK 5.2. Now
my compilation fails with error that Fader  type is not in the scope.
I noticed that you have created the AudioKitEx folder and move the
fader.swift to that folder. Wonder if this is causing this problem.

Please let me know how to fix.

Thanks and Best Regards,
-Vittal

**Comment by aure** [comment]
Use `NodeOutputView`
