### ISSUE TITLE
Error when starting with AudioKit Tutorial

### ISSUE THREAD

**Issue by sasfatu** [audiokit/AudioKit#253]
Hi,

i have problems with the setup of the Dynamic Framework in Xcode 7.0.1 and iOS 9. 
I have set up step by step with your movie, however it ends always with this error.
I used the tutorial video either with a new Objective C project and a new Swift project.

Both ends with the given error message.

```
ld: framework not found libsndfile
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Regards

Sas

**Comment by megastep** [comment]
It does sound like you didn't set up the `libsndfile.framework` properly in your project. It should be set up the same way as the `CsoundLib.framework` in your project, so maybe you just overlooked it.

**Comment by sasfatu** [comment]
I have followed exactly the steps in the tutorial video.
Both *.framework files are available in my project.
I have checked it several times but the result was always the same. 

So are there any other steps that have not been mentioned in the tutorial?

**Comment by sasfatu** [comment]
One more note:
Under General>Linked Frameworks and Libraries
libsndfile.framework and CsoundLib.framework appear two times.

**Comment by narner** [comment]
Pining @aure to make sure he sees this one.

**Comment by sasfatu** [comment]
If you need more info - just let me know.

**Comment by aure** [comment]
Do the examples inside the AudioKit repo, like "HelloWorld" or "AudioKitDemo" work on your machine?

**Comment by sasfatu** [comment]
Yes, they work out of the box. 
I have tried to compare the settings but wasn't able to find some.

**Comment by aure** [comment]
Can we do a screensharing session on Screenhero?  I'm happy to invite you if you do not have an account.

**Comment by sasfatu** [comment]
Yes, that would be great.

**Comment by aure** [comment]
Email me at aure@audiokit.io with an email address you can use for screenhero and I'll send you an invitation.

**Comment by sasfatu** [comment]
With the help of Aurelius I was able to successfully run the tutorial.
By adding the folder AudioKit/AudioKit/Platforms/iOS to the setting "Framework Search Paths" it was possible to run a project from scratch with AudioKit. 

I think its worth mentioning as I have tried the tutorial from a fresh & clean XCode installation. 

Regards

sas
