### ISSUE TITLE
using AK5.2.  compilation fails:  Cannot find Fader in scope, Also NodeOutputPlot not found in AudioKitUI (main branch)

### ISSUE THREAD

**Issue by vittalk** [AudioKit/AudioKit#2530]
hi Aure, 
you replied that NodeOutputPlot is now moved to AudioKitUI. But I cannot find it. can you please point me. 
I am using AudioKit5.2 and AudioKitUI (main)branch. 
 compilation fails:  with the error 'Cannot find Fader in scope'

**Comment by misterinterrupt** [comment]
https://github.com/AudioKit/Cookbook/commit/0092990ea640e528bf6e46948f70026179cb3b48

1 of a few things that come up in github search for nodeoutputplot.. idk if it helps

**Comment by aure** [comment]
`import AudioKitEX` to get Fader. `NodeOutputView` is in `AudioKitUI`.
