### ISSUE TITLE
PitchTap is not available in 5.2.0

### ISSUE THREAD

**Issue by jpsim** [AudioKit/AudioKit#2533]
# Summary

PitchTap is available in 5.1.0: https://github.com/AudioKit/AudioKit/blob/v5.1.0/Sources/AudioKit/Taps/PitchTap.swift

But not available in 5.2.0: https://github.com/AudioKit/AudioKit/blob/v5.2.0/Sources/AudioKit/Taps/PitchTap.swift

This doesn't seem deliberate based on reading the [release notes here](https://github.com/AudioKit/AudioKit/releases/tag/v5.2.0) and the [migration guide here](https://github.com/AudioKit/AudioKit/blob/v5.2.0/docs/MigrationGuide.md). So it seems like it was removed by mistake?

It's the only tap that was removed from that directory between 5.1.0 and 5.2.0:

![image](https://user-images.githubusercontent.com/474794/121899339-2c694c80-ccd9-11eb-8b0d-cdbb0193e2e8.png)

---

**Confirm you should be adding the bug here**
If your issue is implementing AudioKit in your own code, post your problem to [StackOverflow](https://stackoverflow.com/search?q=AudioKit) with the #AudioKit hashtag.

If you can make the issue happen on [AudioKit 5's Cookbook app](https://github.com/AudioKit/Cookbook/) then you can create an issue directly on that repository as well.

GitHub Issues should only be used for confirmed problems with AudioKit and
well-defined feature requests.

Sponsors will get more attention: https://github.com/sponsors/aure

**Describe the bug**

**To Reproduce**
3. See / hear error

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - Type: [e.g. iPhone6, iPad, Mac]
 - OS: [e.g. iOS13.1]
 - AudioKit Version [e.g. 5.0]

**Additional context**

**Comment by jpsim** [comment]
Ah, I found 2a7a83f2027c742ab03b0ab876e9bd3bd56c50ed which removed PitchTap from this git repository and moved it to https://github.com/AudioKit/SoundpipeAudioKit. PitchTap wasn't listed in the migration guide, nor the release notes so I suppose this is more of an omission in the docs/release notes than a code issue.

Indeed if I add AudioKitEX and SoundpipeAudioKit (and remove references `Settings.audioInputEnabled`) in my file interacting with AudioKit, everything works.

**Comment by aure** [comment]
Glad you figured it out. Please feel free to update the migration guide by editing the file in the /docs/ directory and making a pull request. Thanks!
