### ISSUE TITLE
Cannot import AudioKit 

### ISSUE THREAD

**Issue by vittalk** [AudioKit/AudioKit#2535]
Hi, 
I have been trying to compile my project with AudioKit 5.2 and compilation always fails with AudioKit being the culprit.  
Previously (in AK4.x) I used to use Pods and everything worked. Now, I am trying to upgrade to AK5.2 and it is causing a lot of problems.
Firstly, with AK5.2, I cannot use the old Podfile method.  AudioKitUI is not available as a pod, based on the errors I get. 
So I had to switch to Swift Package Manager. 
with SPM i have tried several combinations -- a) including AK,AKUI to my main project under Swift Packages  AND/OR including AK,AKUI to my pod target (my project.pod). None of them work. 

Can you please provide more detailed instructions on how and where to add AK, AKUI?  
to my main project and/or pods?  

Please help. Open to have a debug session if you are open to it. 

thanks, 
-Vittal

--
compilation error log --

Ld /Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/Smart\ Practice.app/Smart\ Practice normal (in target 'SmartPractice' from project 'SmartPractice')
    cd /Users/vittal/Documents/Feb25_Xcode_newBackup2SanjiLaptop/SmartPractice_Apr10_21/ForGitHub/SP_phase2/compilationFixes/SmartPractice_AK5_2_SPM_v1-2
    /Applications/Xcode_Images/Xcode_12.5/Xcode_12_5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios14.1-simulator -isysroot /Applications/Xcode_Images/Xcode_12.5/Xcode_12_5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -L/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator -L/Applications/Xcode_Images/Xcode_12.5/Xcode_12_5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/Alamofire -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/AvailableHapticFeedback -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/DropDown -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/FDWaveformView -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/GTMSessionFetcher -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/GoogleAPIClientForREST -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/GoogleDriveBrowser -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/Kingfisher -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/MultiSlider -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/SCLAlertView -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/SweeterSwift -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/SwiftyDropbox -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/TLPhotoPicker -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/YouTubePlayer -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/YoutubeKit -F/Users/vittal/Documents/Feb25_Xcode_newBackup2SanjiLaptop/SmartPractice_Apr10_21/ForGitHub/SP_phase2/compilationFixes/SmartPractice_AK5_2_SPM_v1-2/Pods/AudioKit -F/Users/vittal/Documents/Feb25_Xcode_newBackup2SanjiLaptop/SmartPractice_Apr10_21/ForGitHub/SP_phase2/compilationFixes/SmartPractice_AK5_2_SPM_v1-2/Pods/FirebaseAnalytics/Frameworks -F/Users/vittal/Documents/Feb25_Xcode_newBackup2SanjiLaptop/SmartPractice_Apr10_21/ForGitHub/SP_phase2/compilationFixes/SmartPractice_AK5_2_SPM_v1-2/Pods/FirebaseCore/Frameworks -F/Users/vittal/Documents/Feb25_Xcode_newBackup2SanjiLaptop/SmartPractice_Apr10_21/ForGitHub/SP_phase2/compilationFixes/SmartPractice_AK5_2_SPM_v1-2/Pods/FirebaseInstanceID/Frameworks -F/Users/vittal/Documents/Feb25_Xcode_newBackup2SanjiLaptop/SmartPractice_Apr10_21/ForGitHub/SP_phase2/compilationFixes/SmartPractice_AK5_2_SPM_v1-2/Pods/Google/Frameworks -F/Users/vittal/Documents/Feb25_Xcode_newBackup2SanjiLaptop/SmartPractice_Apr10_21/ForGitHub/SP_phase2/compilationFixes/SmartPractice_AK5_2_SPM_v1-2/Pods/GoogleSignIn/Frameworks -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/AudioKit -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/CAudioKit -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/STK -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/soundpipe -F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/sporth -F/Users/vittal/Documents/Feb25_Xcode_newBackup2SanjiLaptop/SmartPractice_Apr10_21/ForGitHub/SP_phase2/compilationFixes/SmartPractice_AK5_2_SPM_v1-2/Frameworks -filelist /Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Intermediates.noindex/SmartPractice.build/Debug-iphonesimulator/SmartPractice.build/Objects-normal/x86_64/Smart\ Practice.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Intermediates.noindex/SmartPractice.build/Debug-iphonesimulator/SmartPractice.build/Objects-normal/x86_64/Smart\ Practice_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -L/Applications/Xcode_Images/Xcode_12.5/Xcode_12_5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Intermediates.noindex/SmartPractice.build/Debug-iphonesimulator/SmartPractice.build/Objects-normal/x86_64/Smart_Practice.swiftmodule -lc++ -ObjC -lc++ -lsqlite3 -lstdc++ -lz -framework AVFoundation -framework Accelerate -framework AddressBook -framework Alamofire -framework AssetsLibrary -framework AudioKit -framework AvailableHapticFeedback -framework CAudioKit -framework CFNetwork -framework CoreFoundation -framework CoreGraphics -framework CoreLocation -framework CoreMotion -framework CoreText -framework DropDown -framework FDWaveformView -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseInstanceID -framework Foundation -framework GGLCore -framework GGLSignIn -framework GTMSessionFetcher -framework GoogleAPIClientForREST -framework GoogleDriveBrowser -framework GoogleSignIn -framework GoogleToolboxForMac -framework Kingfisher -framework LocalAuthentication -framework MessageUI -framework MultiSlider -framework SCLAlertView -framework STK -framework SafariServices -framework Security -framework StoreKit -framework SweeterSwift -framework SwiftyDropbox -framework SystemConfiguration -framework TLPhotoPicker -framework UIKit -framework WebKit -framework YouTubePlayer -framework YoutubeKit -framework soundpipe -framework sporth -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Intermediates.noindex/SmartPractice.build/Debug-iphonesimulator/SmartPractice.build/Smart\ Practice.app-Simulated.xcent -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Intermediates.noindex/SmartPractice.build/Debug-iphonesimulator/SmartPractice.build/Objects-normal/x86_64/Smart\ Practice_dependency_info.dat -o /Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/Smart\ Practice.app/Smart\ Practice -Xlinker -add_ast_path -Xlinker /Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Intermediates.noindex/AudioKitUI.build/Debug-iphonesimulator/AudioKitUI.build/Objects-normal/x86_64/AudioKitUI.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Intermediates.noindex/AudioKit.build/Debug-iphonesimulator/AudioKit.build/Objects-normal/x86_64/AudioKit.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Intermediates.noindex/AudioKit.build/Debug-iphonesimulator/AudioKitEX.build/Objects-normal/x86_64/AudioKitEX.swiftmodule

ld: warning: directory not found for option '-F/Users/vittal/Documents/Feb25_Xcode_newBackup2SanjiLaptop/SmartPractice_Apr10_21/ForGitHub/SP_phase2/compilationFixes/SmartPractice_AK5_2_SPM_v1-2/Pods/AudioKit'
ld: warning: directory not found for option '-F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/AudioKit'
ld: warning: directory not found for option '-F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/CAudioKit'
ld: warning: directory not found for option '-F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/STK'
ld: warning: directory not found for option '-F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/soundpipe'
ld: warning: directory not found for option '-F/Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/sporth'
ld: warning: directory not found for option '-F/Users/vittal/Documents/Feb25_Xcode_newBackup2SanjiLaptop/SmartPractice_Apr10_21/ForGitHub/SP_phase2/compilationFixes/SmartPractice_AK5_2_SPM_v1-2/Frameworks'
ld: framework not found AudioKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by aure** [comment]
Clean out your derived data, looks like there's your old AudioKit in there mucking things up. Other than that there's not much info that you're offering here.

**Comment by vittalk** [comment]
I have done that several times over.. result is the same.
The only caveat is that some of my pods are not available in SPM. So I have
to retain them in podfile.
in my project only AudioKit is in SPM.
BTW,  is AK5.2 available in pod format? or compilable by downloading the
sources and building the framework file which I can then import ?
Also, Wondering if Xcode 12.5 has something to do with this.

Thanks and Best Regards,
-Vittal

**Comment by vittalk** [comment]
Thank you so very much for your quick response. I truly appreciate your
help.

Thanks and Best Regards,
-Vittal

**Comment by aure** [comment]
No, AudioKit will never again be offered in CocoaPods format.  You have lines like:

    /Users/vittal/Library/Developer/Xcode/DerivedData/SmartPractice-fdeczuydiqsyszbdgkuqbaubsqqo/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/STK'
    
 In your error report and STK doesn't appear in AudioKit 5.2 so it must be something on your system.

**Comment by aure** [comment]
BTW, every time we make an update to AudioKit, continuous integration happens which ensures it can be compiled which is what gives me confidence the problem is on your system.

**Comment by vittalk** [comment]
Ok thanks. I’ll try again
________________________________

**Comment by vycoder** [comment]
> No, AudioKit will never again be offered in CocoaPods format

I'm also having a similar problem since I'm trying to import AudioKit as a CocoaPod as well. I'm writing a Capacitor plugin that uses AudioKit, but I get import errors when using the actual plugin (that uses AudioKit) on my Capacitor App.

I'm pretty new to iOS development, is there a guide in the docs on how I could import AudioKit in a way that would work in my use-case?

>  BTW,  is AK5.2 available in pod format? or compilable by downloading the 
> sources and building the framework file which I can then import ?

Is this ^ how it is supposed to be done?
