### ISSUE TITLE
AudioPlayer: Can't load an audio file that is longer than the one currently loaded (buffered = true)

### ISSUE THREAD

**Issue by ShowtimeSoft** [AudioKit/AudioKit#2539]
**Describe the bug**
AudioPlayer:
If I load an audiofile B that is longer (duration wise) than the one currently loaded A, it does not seem to be loaded correctly, at least A is still being played back.

Happens only when isBuffered = true.

I have attached a compiled test app and source code.

The test app includes three audio files of various length.
You will see that you can only load files that are shorter (further down the list) than the one currently loaded.

**To Reproduce**

1) player.load(file: "a short file", buffered: true)
2) player.load(file: "a long file", buffered: true)

**Expected behavior**
I expect that the long file is now loaded and played back, but it is not. It is still the short file that is being played.

**Details (please complete the following information):**
 - Type: MacOS
 - OS: Big Sur
 - AudioKit Version 5.2 Main

As far as I can see from one of my other projects, this is not new to version AK 5.2, as I can also make it occur there.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/77680597/123964333-9bba8e00-d9b3-11eb-86ec-50f702451322.png">

[AudioKitTest.zip](https://github.com/AudioKit/AudioKit/files/6741005/AudioKitTest.zip)

Source:
[AK Test Source.zip](https://github.com/AudioKit/AudioKit/files/6741067/AK.Test.Source.zip)

**Comment by aure** [comment]
@ShowtimeSoft You may reopen the issue if @emurray2 's fix proves insufficient. Till then, this is closed.
