### ISSUE TITLE
AudioPlayer getCurrentTime() returns incorrect time when audio is paused

### ISSUE THREAD

**Issue by yberdnikov** [AudioKit/AudioKit#2540]
Steps to reproduce :
1. Start audio playback
2. Pause audio after some time
3. Call getCurrentTime() - it returns 0

**Comment by EssamSoft** [comment]
I got another bug related to getCurrentTime

steps: 
1. set player.isLooping = true 
2. print (player.getCurrentTime())

it will return infinite time after the first round

I'm using AudioKit v5.2.0

**Comment by emurray2** [comment]
@EssamSoft Have you tried using a buffer? The play time will always be running as long as the engine is running. The only way to put it back to 0 seconds is to call `player.play()` before it finishes playing the file/looping it again.
