### ISSUE TITLE
Documentation for Input Device Selection on Mac OS

### ISSUE THREAD

**Issue by lukasroberts** [AudioKit/AudioKit#2543]
How do you choose a different input device other then the default microphone on MacOS?

I've seen the below code in AudioEngine:

```
#if os(macOS)
    /// Enumerate the list of available devices.
    public static var devices: [Device] {
        return AudioDeviceUtils.devices().map { id in
            Device(deviceID: id)
        }
    }

 /// One device for both input and output. Use aggregate devices to choose different inputs and outputs
    public var device: Device {
        Device(deviceID: avEngine.getDevice())
    }`

    /// Change the preferred output device, giving it one of the names from the list of available output.
    /// - Parameter output: Output device
    /// - Throws: Error if the device cannot be set
    public func setDevice(_ output: Device) throws {
        avEngine.setDevice(id: output.deviceID)
    }

    #else
    /// Change the preferred input device, giving it one of the names from the list of available inputs.
    public static func setInputDevice(_ input: Device) throws {
        // Set the port description first eg iPhone Microphone / Headset Microphone etc
        guard let portDescription = input.portDescription else {
            throw CommonError.DeviceNotFound
        }
        try AVAudioSession.sharedInstance().setPreferredInput(portDescription)

        // Set the data source (if any) eg. Back/Bottom/Front microphone
        guard let dataSourceDescription = input.dataSource else {
            return
        }
        try AVAudioSession.sharedInstance().setInputDataSource(dataSourceDescription)
    }

    /// The current input device, if available.
    public var inputDevice: Device? {
        if let portDescription = AVAudioSession.sharedInstance().preferredInput {
            return Device(portDescription: portDescription)
        } else {
            let inputDevices = AVAudioSession.sharedInstance().currentRoute.inputs
            if inputDevices.isNotEmpty {
                for device in inputDevices {
                    return Device(portDescription: device)
                }
            }
        }
        return nil
    }

    /// The current output device, if available.
    public var outputDevice: Device? {
        let devs = AVAudioSession.sharedInstance().currentRoute.outputs
        if devs.isNotEmpty {
            return Device(name: devs[0].portName, deviceID: devs[0].uid)
        }
        return nil
    }
    #endif
```

Do we have to use aggregate devices on MacOS then? There's no way to select a custom device? What's the point in returning a list of input devices at all then?

On a more general note, what's going on with the documentation for this project? I can barely find anything now that it's all been migrated to version 5.

Additionally I've read https://github.com/AudioKit/AudioKit/issues/2130 and whilst it shows the issues this library has. It doesn't show a clear example of how to change the input device or what decision was made to fix the issue.

**Comment by aure** [comment]
Are http://audiokit.io/ and https://github.com/AudioKit/AudioKit/wiki not sufficient documentation?

**Comment by lukasroberts** [comment]
I wouldn't say so, since it doesn't actually give a concrete example of how to change the input device

For example:

`for device in devices {
            print(#"Device Name: \#(device.name), number of inputs: \#(device.inputChannelCount ?? 0)"#)
//            engine.input = device // DOES NOT WORK, only sets output device
            do { try engine.setDevice(device) } catch {}
        }`

Above is an example using swift, but there seems to be no way to set the input device on MacOS. Is this even possible?

**Comment by aure** [comment]
I just mean in regards to:

> On a more general note, what's going on with the documentation for this project? I can barely find anything now that it's all been migrated to version 5.

Did you know about those two links? I don't think the documentation has done anything but improved with v5.

**Comment by lukasroberts** [comment]
I did know about those two links.

They are fairly helpful, the most helpful thing is the Cookbook repository. If those examples were indexable by Google with some wording around it, then that would be even more helpful. As it stands the examples hyperlink from the main page gives a 404, so most stuff is not easily searchable.

In regards to my other questions, is it possible to set the audio input to a custom sound card with a specific channel on MacOS? Or do I need to do it via Aggregate devices?

**Comment by aure** [comment]
Thanks for the note about the 404 error. I fixed that.

**Comment by aure** [comment]
I think because we're based off AVAudioEngine, you will probably have to use Aggregate devices. I could be wrong.

**Comment by ryanfrancesconi** [comment]
No, the AVAudioEngine creates its own aggregate device, it doesn't work well to use one unless you're only taking the output from the aggregate. Rules change with AVAudioEngine when the inputNode is accessed. Why?? I have no idea, and it's annoying.

To answer the question about input device selection on mac os - yes it is possible, but perhaps not with how AudioKit is setup at the moment. I would recommend using SimplyCoreAudio if you are macOS based to set the devices. Once you have the device, getting the channel selection is simple.

If you are using the input of the engine, then your devices need to match the System default devices. If you aren't using the input then you can use the engine output as a separate target to a device like AudioKit does.

Recording from specified channels is also possible and there is a class in AudioKit for this purpose:

https://github.com/AudioKit/AudioKit/blob/main/Sources/AudioKit/Taps/MultiChannelInputNodeTap.swift

CoreAudio channel mapping isn't the most intuitive thing...

**Comment by emurray2** [comment]
Ah I see. Good to know.

**Comment by lukasroberts** [comment]
@ryanfrancesconi Thanks for that.

I ended up going with RtAudio and creating an Objective C++ wrapper from it.

Currently I don't think that AudioKit has an intuitive way of doing easy input / output device selection. It's not really its fault as you say, since it's based on AVAudioEngine, which itself does not have an easy way of doing it.

Shall close this for now - unless someone wants to try and create a feature out of this, in which case that brave soul can re-open it and implement.

**Comment by emurray2** [comment]
To give everyone an update, I'm still working on this--it's sort of tough with school and all. But I've made some progress looking through the core audio API.

I found out that iOS uses `AURemoteIO` for input/output device, and it's possible to get that audio unit.

I also found out that MacOS uses the `AUHAL` (hardware audio layer) for it's input output device, which is also possible to get through `AudioUnitGetProperty()`.

My next goal would be how to configure those audio units through higher level API's, such as `AVFoundation`. If there's no such way, then I'm going to try and abstract them away with AudioKit to make a friendly interface to use.

If anyone else has thoughts on this, please let me know. I'd love to hear them and learn more.

**Comment by emurray2** [comment]
@aure Is the `inputDevices` property in `AudioEngine.swift` only supposed to return 1 I/O device, which is the currently selected input device in system preferences? I tested `ChannelDeviceRouting.swift` today on my iPad with my audio interface, and it works nice. I can select the iPad Microphone or a microphone input from the audio interface and have them both output to the audio interface monitoring output.

I was curious if the intended behavior on macOS was to limit the available devices to whichever one the user selects in system preferences. It would be nice to have the behavior be the same for both iOS and Mac Catalyst, but it may not be possible.

**Comment by rebryk** [comment]
@emurray2 @aure @ryanfrancesconi so it is possible now to select input device on MacOS using AudioKit?

**Comment by emurray2** [comment]
> @emurray2 @aure @ryanfrancesconi so is it possible now to select an input device on macOS using AudioKit?

Not as far as I know. You can always give this demo a try: https://github.com/AudioKit/Cookbook/blob/main/Cookbook/CookbookCommon/Sources/CookbookCommon/Recipes/InputDeviceDemo.swift

If by input device you mean an audio interface or something more advanced than the typical built in mic, I'd suggest using those C++ or CoreAudio resources above.

I'm not sure if non-`AVFoundation` I/O device handling was on the to-do list yet for AudioKit v6, but we've been trying to move further away from `AVAudioEngine` (though not entirely) to allow for more flexibility.

**Comment by daxmacrog** [comment]
> @emurray2 @aure @ryanfrancesconi so is it possible now to select an input device on macOS using AudioKit?

I sure wish there were. I've spent a lot of time trying to figure a way to make that work for a macOS music visualizer app, but I'm stuck using BlackHole and a Multi-Output Device. Installing BlackHole and creating a Multi-Output Device isn't the end of the world. The problem is that I have to switch my system-level input to BlackHole 2ch and output to a Multi-Output Device with BlackHole and whichever speakers I'm using. It would be grand if I could leave the system input setting alone, and I don't even actually need audio output for my app, although I understand that both an input and output are required to complete the audio chain as things stand currently.

Also, in this and other discussions, links to a mythical example of how to do this are broken, probably because it didn't actually work.

**Comment by emurray2** [comment]
> > @emurray2 @aure @ryanfrancesconi so is it possible now to select an input device on macOS using AudioKit?
> 
> 
> 
> I sure wish there were. I've spent a lot of time trying to figure out a way to make that work as part of a macOS music visualizer app, but I'm stuck using BlackHole and a Multi-Output Device. Installing BlackHole and creating a Multi-Output Device isn't the end of the world. The problem is that I have to switch my system-level input to BlackHole 2ch and system output to a Multi-Output Device that includes BlackHole plus whichever speakers I'm using.
> 
> 
> 
> It would be grand if I could leave the system input setting alone (so other apps would still have access to the mic or Bluetooth headset or whatever I have set as the default). And I don't actually even need audio output for my app, although it's my understanding that both an input and output are required to complete the audio chain as things currently stand.
> 
> 
> 
> Also, in this and other discussions, links to the mythical example of how to do this are broken, probably because it didn't actually work.

You can find a simple example here in our Cookbook: [](https://github.com/AudioKit/Cookbook/blob/main/Cookbook/CookbookCommon/Sources/CookbookCommon/Recipes/WIP/InputDeviceDemo.swift).

I would try enumerating the system inputs/outputs and changing each one through the AVFoundation API. If this doesn't work, it's best to use Core Audio for things like this.

**Comment by daxmacrog** [comment]
Thanks Evan. I don't believe that will work in macOS, but I would love to be wrong about that. It appears to rely on AVAudioSession.

**Comment by ryanfrancesconi** [comment]
I use [SimplyCoreAudio](https://github.com/rnine/SimplyCoreAudio) for macOS device management. You can use inputs, sure. It's AVAudioEngine that is the issue in terms of flexibility with them.

If you are using its input node then you must keep your devices in sync with the system devices. Other than that, it has always worked fairly normally.

I'm not current with AudioKit's implementation.
