### ISSUE TITLE
Basic Demo for MIDI file playback on external device (like an e-piano)

### ISSUE THREAD

**Issue by ahilti** [AudioKit/AudioKit#2548]
It would be great to include a little demo, preferably in SwiftUI, that shows how to **play a .mid** file on iPhone/iPad located in the project resources folder. Playback on an external device like an e-piano would be preferred, as probably some additional steps have to be considered.

**Comment by aure** [comment]
There are no demos in this repo. You may add this to the Cookbook repo issues https://github.com/AudioKit/Cookbook/issues
