### ISSUE TITLE
Basic Demo for reading notes from a local MIDI file on iOS/macOS

### ISSUE THREAD

**Issue by ahilti** [AudioKit/AudioKit#2549]
Opening a .mid file from local project resources and looping (forEach) through the notes of specific tracks seems not trivial. A github gist on that would greatly help. Especially a demo or article on how Sequencer, MusicTrackManager, etc. interact with each other would be greatly appreciated.

**Comment by aure** [comment]
There are no demos in this repo. You may add this to the Cookbook repo issues https://github.com/AudioKit/Cookbook/issues
