### ISSUE TITLE
Sound Font not Loaded ¿why?

### ISSUE THREAD

**Issue by carlosypunto** [audiokit/AudioKit#255]
Hi Aurelius,

This library is awesome. Thanks for share it :-)

I'm testing how to use SoundFonts, but I can't load it, I don't know if I'm doing bad

![image](https://cloud.githubusercontent.com/assets/1680094/11162933/4cb50928-8aba-11e5-9cb4-42d77542b26a.png)

Thanks in advance

**Comment by megastep** [comment]
You need to call `fetchPresets:` on the `AKSoundFont` object to trigger the actual loading of the data.

**Comment by carlosypunto** [comment]
Thanks for your rapid response :-)

But I get the same

![image](https://cloud.githubusercontent.com/assets/1680094/11162954/11eea6e4-8abc-11e5-96e7-adb8f254ab07.png)

**Comment by megastep** [comment]
You should check the value of the `loaded` property from within the block you give to `fetchPresets:`, it's quite likely it hasn't actually finished doing the loading by the time you reach your print statement.

Also double check that your sf2 file is actually being included in your target so it will be copied with your binary.

**Comment by carlosypunto** [comment]
`fetchPresets` callback is never called
```
soundFont.fetchPresets { soundFont in
    print("My font: \(soundFont)") // never is called
}
```

Yeah, the sf2 file is member of the target

**Comment by carlosypunto** [comment]
I've made a repository https://github.com/carlosypunto/SoundFonts, could you check it?
Thanks in advance

**Comment by megastep** [comment]
I think it might actually be simply that AudioKit hasn't been properly initialized first, likely Csound is not able to load the file yet...

**Comment by carlosypunto** [comment]
@megastep how I initialize AudioKit correctly?

**Comment by megastep** [comment]
Mostly you could start by creating an instrument, you can look at AudioKitDemo for some examples of that.

```
   _instrument = [[AKMidiInstrument alloc] init];
    _instrument.instrumentNumber = 1;
    [AKOrchestra addInstrument:_instrument];
```

**Comment by carlosypunto** [comment]
Works!! Thank a lot
