### ISSUE TITLE
When Reverb on bypass there is no sound

### ISSUE THREAD

**Issue by David4noy** [AudioKit/AudioKit#2551]
When Reverb on bypass there is no sound:

let reverb:Reverb
.
.
.
        reverb = Reverb(myNode, dryWetMix: 0.2)
        reverb.loadFactoryPreset(.plate)
        reverb.bypass()
.
.
.

in this case there is no sound.
I can switch and put the on/off switch on dryWetMix but..

**Comment by aure** [comment]
I wote a test for Reverb's bypass to confirm your findings. I then modified Reverb to toggle the dryWetMix of the internal AU. I don't think this is the correct thing to do and that its actually a bug in Apple's code. But, since I have no control over that closed source audio unit, this is the best I can do. I hope it suffices.

**Comment by David4noy** [comment]
Yes, actually  I did the same..
Thanks!

**Comment by eljeff** [comment]
I don't think this is a good idea ... we just went to lengths the other day to write our own code to handle this as suggested here.

If I 'stop' the effect now, I haven't actually stopped the effect because of this hack.
I don't think this is a bug in apple's code.

I think this is on the user to decide and set up correctly, but this solution now makes this node behave differently than the others.

**Comment by aure** [comment]
@eljeff I don't agree. Write a test that shows any other effect having bypass stop all sound like this one does.

**Comment by eljeff** [comment]
I didn't mention bypass though, I mentioned stop.

But that shows my point - there's confusion between start/stop/play/bypass. If I were to 'stop' a processor, I would expect to not use those resources. This makes bypass / stop the same thing... the plugin is still processing, it is just only sending the dry signal. 

Maybe I am expecting too much, maybe 'stop' was never intended to be able to 'stop' a processor... Many nodes used to save resources by calling stop. I see that's not necessarily the case now. Old habits...

It's a small thing that just adds to the confusion, and you mentioned yourself that this is not the correct way to fix this - I was just agreeing with that. Go on w yo bad self.

**Comment by aure** [comment]
Ideally, bypass and stop do the same thing in the case of processing. The work the AU does is saved and the unaffected sound still comes out. If you know a better way of doing, by all means submit a PR. I have no horse in this race, as I don't even like the Apple Reverb and its messed up on macOS.

**Comment by eljeff** [comment]
I only said something cause its a good example of how this confusion slips in - like why would a reverb have a 'play' command?
(That's a rhetorical question at an appropriate time, I don't need / want an answer).

**Comment by eljeff** [comment]
And if I start w the rhetoricals, we'll never get out alive...
Thank yall

**Comment by David4noy** [comment]
> as I don't even like the Apple Reverb and its messed up on macOS.

So what reverb do you use?

**Comment by emurray2** [comment]
> > as I don't even like the Apple Reverb and its messed up on macOS.
> 
> So what reverb do you use?

You could try using some of the SoundpipeAudioKit reverbs, such as [`ChowningReverb()`](https://github.com/AudioKit/SoundpipeAudioKit/blob/main/Sources/SoundpipeAudioKit/Effects/ChowningReverb.swift), [`Convolution()`](https://github.com/AudioKit/SoundpipeAudioKit/blob/main/Sources/SoundpipeAudioKit/Effects/Convolution.swift), and one of my favorites: [CostelloReverb()](https://github.com/AudioKit/SoundpipeAudioKit/blob/main/Sources/SoundpipeAudioKit/Effects/CostelloReverb.swift).

**Comment by David4noy** [comment]
> > > as I don't even like the Apple Reverb and its messed up on macOS.
> > 
> > 
> > So what reverb do you use?
> 
> You could try using some of the [SoundpipeAudioKit](https://github.com/AudioKit/SoundpipeAudioKit) reverbs, such as [`ChowningReverb()`](https://github.com/AudioKit/SoundpipeAudioKit/blob/main/Sources/SoundpipeAudioKit/Effects/ChowningReverb.swift), [`Convolution()`](https://github.com/AudioKit/SoundpipeAudioKit/blob/main/Sources/SoundpipeAudioKit/Effects/Convolution.swift), and one of my favorites: [`CostelloReverb()`](https://github.com/AudioKit/SoundpipeAudioKit/blob/main/Sources/SoundpipeAudioKit/Effects/CostelloReverb.swift).

Thanks a lot!
A great idea, I'll check them all
