### ISSUE TITLE
Missing creator task warnings

### ISSUE THREAD

**Issue by kbendelow** [AudioKit/AudioKit#2552]
**Describe the bug**
When compiling with Xcode 13 beta 3 I am getting thousands of warnings in my project related to AudioKit. 

**To Reproduce**
1. Open a project that has AudioKit installed via cocoapods
2. Build and compile the app
3. Observe a large amount of errors. 

**Expected behavior**
Build without seeing thousands of "missing creator task" errors. 

**Screenshots**
![Screen Shot 2021-07-20 at 4 36 06 PM](https://user-images.githubusercontent.com/8882405/126398577-f2fa3e31-e553-46d2-a2aa-13bf0ffd9e00.png)
![Screen Shot 2021-07-20 at 4 36 15 PM](https://user-images.githubusercontent.com/8882405/126398587-a1984527-b6f9-4a5c-8ce6-988810cab292.png)

**Details (please complete the following information):**
 - Type: Mac Mini 2018, iPhone 11 Pro simulator
 - OS: Mac: Big Sur 11.4. Simulator: iOS 15 simulator (beta 3)
 - AudioKit Version: 4.0

**Additional context**
It seems like someone else is experiencing a similar problem with .hpp files [here](https://github.com/realm/realm-cocoa/issues/7348)

**Comment by megastep** [comment]
You should seriously consider switching to SPM on Xcode 13, we're not going to update the pod any more.

**Comment by aure** [comment]
What Stephane said.
