### ISSUE TITLE
Delay time causing digital click when changing

### ISSUE THREAD

**Issue by David4noy** [AudioKit/AudioKit#2557]
I'm building a synth using AudioKit and I’m trying to change the delay time with slider but it's causing a digital click when changing. I tried also the Cookbook of delay but didn't work.

Here is my code:

    @IBAction func delayTimeSlider(_ sender: UISlider) {
        mySynth.setDelayTime(time: AUValue(sender.value / 1000))
    }

    func setDelayTime(time: AUValue){
        delay.time = time
    }

I also post it on stackoverflow but no one answered yet.

https://stackoverflow.com/questions/68439512/audiokit-5-delay-time-causing-digital-click-when-changing

**Comment by emurray2** [comment]
It looks like this is a problem at the Apple Audio Unit level. `Delay()` is one of the effects that wraps an Apple Audio Unit (specifically _AUDelay_). If you try using AUDelay in a DAW like GarageBand, it does the same thing.

But there's another delay effect you should try out if you haven't yet. There's a [`VariableDelay()`](https://github.com/AudioKit/SoundpipeAudioKit/blob/main/Sources/SoundpipeAudioKit/Effects/VariableDelay.swift) effect from [SoundpipeAudioKit](https://github.com/AudioKit/SoundpipeAudioKit) that's similar to the delay effect on synths such as the OP-1. It's designed to have the time change while rendering.

**Comment by aure** [comment]
Yep, Apple's delay clicks when changing the value, nothing we can do.

**Comment by David4noy** [comment]
> It looks like this is a problem at the Apple Audio Unit level. `Delay()` is one of the effects that wraps an Apple Audio Unit (specifically _AUDelay_). If you try using AUDelay in a DAW like GarageBand, it does the same thing.
> 
> But there's another delay effect you should try out if you haven't yet. There's a [`VariableDelay()`](https://github.com/AudioKit/SoundpipeAudioKit/blob/main/Sources/SoundpipeAudioKit/Effects/VariableDelay.swift) effect from [SoundpipeAudioKit](https://github.com/AudioKit/SoundpipeAudioKit) that's similar to the delay effect on synths such as the OP-1. It's designed to have the time change while rendering.

Thanks again!
I'll try it
