### ISSUE TITLE
renderToFile Cannot be used in Sequencer

### ISSUE THREAD

**Issue by devlong** [AudioKit/AudioKit#2561]
Hi，In my project, I will use renderToFile to record my sequence to hard disk space, using the m4A format. I tried many ways, but I couldn't get the right route. What's wrong with my code?

    `guard let outputURL = try? FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false).appendingPathComponent("audio_file.m4a") else { return }
      guard let format = AVAudioFormat(commonFormat: .pcmFormatFloat32, sampleRate: 44100, channels: 2, interleaved: false) else {
            fatalError("Failed to create format")
        }
        guard let output = try? AVAudioFile(forWriting: outputURL, settings: format.settings) else {
             print("AVAudioFile erro!!!!")
            return
        }
        print("outputURL:\(outputURL)")
        try? engine.renderToFile(output, maximumFrameCount: 4_096, duration: 20, prerender: {
            self.sequencer?.rewind()
            self.sequencer?.play()
        }, progress: { progress in
            print("progress:\(progress)")
        })`

**Comment by aure** [comment]
I can't tell what is wrong, if anything, with your code. I suggest you prepare a demo project, perhaps ask for help on StackOverflow. Once you have proven there is a problem with AudioKit, please submit the evidence as an issue and we'll do our best to address it.

**Comment by devlong** [comment]
Thank you for your answer. I have put relevant questions on [https://stackoverflow.com/questions/68650011/applesequencer-export-m4a-format-file-error-when-use-audiokit]
 and built a GitHub address[https://github.com/devlong/sequenceExport.git].
 This problem has bothered me for a long time. I really hope you can help me solve this problem.

**Comment by devlong** [comment]
> I can't tell what is wrong, if anything, with your code. I suggest you prepare a demo project, perhaps ask for help on StackOverflow. Once you have proven there is a problem with AudioKit, please submit the evidence as an issue and we'll do our best to address it.



> I can't tell what is wrong, if anything, with your code. I suggest you prepare a demo project, perhaps ask for help on StackOverflow. Once you have proven there is a problem with AudioKit, please submit the evidence as an issue and we'll do our best to address it.

Thank you for your answer. I have put relevant questions on [stackoverflow](https://stackoverflow.com/questions/68650011/applesequencer-export-m4a-format-file-error-when-use-audiokit)
and built a [GitHub](https://github.com/devlong/sequenceExport.git)
This problem has bothered me for a long time. I really hope you can help me solve this problem.
