### ISSUE TITLE
Cannot import to Swfit project

### ISSUE THREAD

**Issue by neesonqk** [audiokit/AudioKit#257]
Following exactly [Getting Started in Swift](http://audiokit.io/tutorials/swift/configuration/).

But get below errors,
![image](https://cloud.githubusercontent.com/assets/7279067/11173661/2dace74e-8c54-11e5-8011-7b48a263aa32.png)

I'm using latest Xcode 7, please how to solve this problem, thanks.

**Comment by aure** [comment]
You must not have things set up right.  This screenshot doesn't really give us any information to help you though.   My best guess is that I don't think you have the bridging header set up right.

**Comment by neesonqk** [comment]
Hi Aure,

I followed `Configuring AudioKit 2.1 with Static Libraries for iOS Apps`, but the difference was target language I chose to `swift`, the rest was exactly same with the tutorial.

![image](https://cloud.githubusercontent.com/assets/7279067/11173838/406c91f2-8c56-11e5-95d8-8ed7601aadd5.png)

Please see my settings

![image](https://cloud.githubusercontent.com/assets/7279067/11173843/5a8d0d3c-8c56-11e5-9b6a-2830fe3a772d.png)

![image](https://cloud.githubusercontent.com/assets/7279067/11173883/0ab23660-8c57-11e5-8e3f-3589e1bdea75.png)

![image](https://cloud.githubusercontent.com/assets/7279067/11173847/6e5577c8-8c56-11e5-800e-cef3038b104f.png)

![image](https://cloud.githubusercontent.com/assets/7279067/11173849/9462f792-8c56-11e5-8430-803fe760fca4.png)

and last one
![image](https://cloud.githubusercontent.com/assets/7279067/11173853/b556df18-8c56-11e5-9637-b3ea403da1c7.png)

 The path I used `$(SRCROOT)....` it automic converted to my local path. did I miss anything?

**Comment by aure** [comment]
I am sure it is srcroot inside, but in this view it shows the full path.  What's insider your Bridging-Header.h file?

**Comment by neesonqk** [comment]
This is the header file

![image](https://cloud.githubusercontent.com/assets/7279067/11173989/b04c9966-8c58-11e5-9be8-64744928ed0f.png)

**Comment by aure** [comment]
You have a typo in the spelling of AKFoundation.h

**Comment by neesonqk** [comment]
Oh shit, I found a spelling error. ah It works. thank Aure, sorry wasting of time.

**Comment by neesonqk** [comment]
@aure do you have any examples about `AKAudioAnalyzer`, like how to use it, I googled a lot, but there isn't too much info about it.
What I'm going to do is actually capturing the sound in particular frequency range, e.g. the frequency above 1000Hz, something like `analyzer.trackedFrequency.floatValue > 1000`, I'm not sure if `AKAudioAnalyzer` is the correct class to use, would you please give a guide or suggestion? thanks again.

**Comment by aure** [comment]
Tracked frequency just give you a best guess of what frequency is the loudest in a signal, so it won't help you do what you're trying to do, I don't think.  It sound to me like you want the AKHighPassFilter.

**Comment by neesonqk** [comment]
I tried to timmer out the result, like this

```swift

let timer = NSTimer.scheduledTimerWithTimeInterval(0.05, target: self, selector: "printCapturedFrequency", userInfo: nil, repeats: true);
timer.fire();

func printCapturedFrequency(){
        if(analyzer.trackedFrequency.floatValue > 1000){            
            print("captured frequency ", analyzer.trackedFrequency.floatValue);
        }
}
```

**Comment by neesonqk** [comment]
The loudest frequency in a signal would be enough in my case, the sound is from the microphone, if like using timer to capture in an interval, I think there must be some missing sound.

So as your mentioned 'AKHighPassFilter',  is there any examples?

**Comment by aure** [comment]
There's a few examples in the Examples directory in AudioKit (AudioKitDemo uses AKTrackedFrequency) and in the examples repo: http://github.com/audiokit/Examples/

**Comment by neesonqk** [comment]
In fact I'm developing an app to capture environment sound then display the frequency of them in a graph, quite similar to below screenshot, however in the examples mostly are generating sound/waveform then display, I tried but couldn't find a clue where to start, I'm wondering if it's possible to implement by AudioKit?

I can add `microphone` to `instrument`, [from this example](https://github.com/audiokit/AudioKit/blob/master/Examples/iOS/Swift/AudioKitDemo/AudioKitDemo/Analysis/AnalysisViewController.swift) it shows updating UI via timer, however as you mentioned, `..Tracked frequency just give you a best guess of what frequency is the loudest in a signal...`, so this wouldn't update all frequency to UI at a second except the loudest one, right?

![file_000](https://cloud.githubusercontent.com/assets/7279067/11178847/6a073376-8c8a-11e5-84ad-ee643dcd4363.png)

**Comment by neesonqk** [comment]
Thanks, will have a further study, thanks for your time.
