### ISSUE TITLE
AudioPlayer  doesn't stop after pause and volume decreases when pressing play

### ISSUE THREAD

**Issue by David4noy** [AudioKit/AudioKit#2576]
If I do pause and then stop or pause -> play -> stop, it doesn't stop.
Instead,  it keeping the last pause point and "stop" there (and play from there).
Also, if you do pause - > stop -> play - it won't play in the first tap - only in the second.

I use the simple methods:
    
    func playPlayback(){
        playback.play()
    }
    
    func pausePlayback(){
        playback.pause()
    }
    
    func stopPlayback(){
        playback.stop()
    }
    
I tried also with:

    func playPlayback(){
        
        if playback.isPaused {
            playback.resume()
        } else {
        playback.play()
        }
    }

But was the same

**Comment by aure** [comment]
You're a good problem finder. Do you think you could write a test that produces the incorrect result that we could then fix?  It would be a good habit to get into.

**Comment by David4noy** [comment]
> You're a good problem finder. Do you think you could write a test that produces the incorrect result that we could then fix? It would be a good habit to get into.

To be honest, I don't really know how to write and do test yet, I'm still a beginner.. I'll try to learn about it and do, I guess it will take me awhile but I want to help if I can.

**Comment by David4noy** [comment]
Btw, I thought about something who might be helpful, to add to AudioPlayer:

enum StateMod {
    
    case looping
    case paused
    case playing
    case stopped
    case seeking
    case reversing
    case buffering
    case scheduled
    
}

This way we can interact more easily with the player state and to move between them (I think...)

We can also add some row value for some uses or debugging. for example:

enum StateMod: String {
    
    case looping = "looping"
    case paused = "paused"
    case playing = "playing"
    case stopped = "stoped"
    case seeking = "seeking"
    case reversing = "reversing"
    case buffering = "buffering"
    case scheduled = "scheduled"
    
}

Log(StateMod.RawValue)

**Comment by David4noy** [comment]
Btw, I thought about something who might be helpful, to add to AudioPlayer:


enum StateMod: String {

    case looping
    case paused
    case playing
    case stopped
    case seeking
    case reversing
    case buffering
    case scheduled

}



This way we can interact more easily with the player state and to move between them (I think...)

We can also add some row value for some uses or debugging. for example:


enum StateMod: String {

    case looping = "looping"
    case paused = "paused"
    case playing = "playing"
    case stopped = "stoped"
    case seeking = "seeking"
    case reversing = "reversing"
    case buffering = "buffering"
    case scheduled = "scheduled"

}

Log(StateMod.RawValue)

**Comment by David4noy** [comment]
I just looked on the source code again and so this:

    public func stop() {
        guard isPlaying else { return }
        pausedTime = getCurrentTime()
        isPlaying = false
        isSeeking = false
        playerNode.stop()
        scheduleTime = nil
    }

Is that means that when you stop you getCurrentTime()?
Because then if you press play it will do resume isteed, isn't it?

    // Time in audio file where track was stopped (allows retrieval of playback time after playerNode is paused)
    var pausedTime: TimeInterval = 0.0

So I thought maybe this is one of the reasons - is it connected to the issue?
And maybe to add isPaused = false (or to work with the enum I suggested)

**Comment by emurray2** [comment]
@David4noy What device were you testing the volume on? Was it the simulator or a regular device?

Also -- getting closer to figuring out a solution for this. If you just access the `AudioPlayer` `playerNode` directly and call `playback.play()` and `playback.playerNode.pause()`, things work fine in buffer mode.

Here's the problem with file mode: inside `AudioPlayer+Playback.swift` on lines 42 and 43, the player's `editStartTime` and `editEndTime` never get reset because of these statements `editStartTime = startTime ?? editStartTime` `editEndTime = endTime ?? editEndTime`.

Whenever the file finishes looping, inside `AudioPlayer.swift`, lines 208-211:
```
if !isBuffered, isLooping, engine?.isRunning == true {
  play()
  return
}
```
We have a play call with no specified `startTime` or `endTime`, which means `editStartTime = editStartTime` and `editEndTime = editEndTime`, which were set when the player was last paused. They won't be set until the player is paused again.

Simple test demoing part of the problem:
```
    func testPauseResumePlay() {
        guard let url = Bundle.module.url(forResource: "TestResources/12345", withExtension: "wav") else {
            XCTFail("Didn't get test file")
            return
        }
        let engine = AudioEngine()
        let player = AudioPlayer()
        engine.output = player
        player.isLooping = true

        let audio = engine.startTest(totalDuration: 7.0)

        do {
            try player.load(url: url, buffered: true)
        } catch let error as NSError {
            Log(error, type: .error)
            XCTFail(error.description)
        }

        // Get player's starting point
        let originalStartTime = player.getCurrentTime()
        player.play()

        // editStartTime should not be modified by calling play()
        XCTAssertEqual(originalStartTime, player.editStartTime)
        audio.append(engine.render(duration: 2.0))

        player.pause()

        // Get player's pause point
        let pauseTime = player.getCurrentTime()
        audio.append(engine.render(duration: 1.0))

        player.resume()

        // editStartTime should be set to pauseTime on resume()
        XCTAssertEqual(pauseTime, player.editStartTime)
        audio.append(engine.render(duration: 2.0))

        player.play()

        // play() should reset player's editStartTime
        XCTAssertEqual(originalStartTime, player.editStartTime)
        audio.append(engine.render(duration: 2.0))

        testMD5(audio)
    }
```
Result:
`XCTAssertEqual failed: ("0.0") is not equal to ("2.0")`

**Comment by emurray2** [comment]
The test I made above actually still fails, but the others won't. However, I'm going to keep working on making it pass by decoupling the `editStartTime` and `editEndTime` from the `resume()` and `seek()` function which control the player's playhead. If we make separate variables for the actual playhead of the player but keep the edit times, things may be less confusing.

Again, I also think the enums are a great idea, and maybe we should add those too.

**Comment by David4noy** [comment]
@emurray2 
Very cool and interesting.
Yes I'll try to add and edit them and I'll be in touch about the PR.

Another point- what if we won't use resume() at all?
Maybe to add to 
stop() -> startTime = 0
pause() -> startTime = getCurrentTime
play() -> always will be: play(from: startTime)

I wonder what is the benefit of resume()?

About the seeking:
When start to seek -> to do stop(), 
(on touch up or) in the end of method -> startTime = getCurrentTime + play(from: startTime)

I'll also keep checking and trying things, thanks a lot!

**Comment by emurray2** [comment]
> @emurray2 
> Very cool and interesting.
> Yes I'll try to add and edit them and I'll be in touch about the PR.
> 
> Another point- what if we won't use resume() at all?
> Maybe to add to 
> stop() -> startTime = 0
> pause() -> startTime = getCurrentTime
> play() -> always will be: play(from: startTime)
> 
> I wonder what is the benefit of resume()?
> 
> About the seeking:
> When start to seek -> to do stop(), 
> (on touch up or) in the end of method -> startTime = getCurrentTime + play(from: startTime)
> 
> I'll also keep checking and trying things, and I started to learn about testing and how to do them. 
> Thanks a lot!

The point of `resume()` is so the player can resume where it was paused when it's in file mode. It won't know that without the `editStartTime`, so setting it to zero every time would make it replay from the beginning. But these are great ideas, and definitely keep exploring 👍!
