### ISSUE TITLE
Output of FFTTap conflicts with how it's used in examples

### ISSUE THREAD

**Issue by aburgel** [AudioKit/AudioKit#2578]
I've been reading through the FFTTap code to familiarize myself with how it works, and I've also looked at some of the examples in AudioKitUI to make sense of it. I'm having a hard time wrapping my head around this, and am wondering if there is something wrong with the implementation, especially given how the examples are making use of the FFT data.

Starting with the implementation, one of the later steps in the FFTTap is to [compute the magnitude from the complex FFT data](https://github.com/AudioKit/AudioKit/blob/main/Sources/AudioKit/Taps/FFTTap.swift#L79). This [results in an array of real numbers](https://developer.apple.com/documentation/accelerate/1450557-vdsp_zvmags).

Yet, in FFTView, it [assumes that the output is an interleaved array of complex numbers](https://github.com/AudioKit/AudioKitUI/blob/main/Sources/AudioKitUI/Visualizations/FFTView.swift#L36-L61). My understanding of the view code is that it is taking the complex numbers, computing the amplitude (`sqrt(real^2 + imag^2)`) and then converting to decibels (`20 * log10(amplitude)`).

Given that you already have the magnitude (which I think is the same thing as power), then you can skip some of this math and go directly to converting the magnitude to decibels (`10 * log10(magnitudes)`).

**Comment by emurray2** [comment]
Looks like you're correct. FFT code can definitely be confusing sometimes, but your interpretation seems correct. Here are some tests I did below with oscillator tones. Test **2.** is with the code you suggested, and test **3.** is with the current code.

### 1. Ableton Operator with Spectrum Analyzer (A 440Hz Sine Tone)
<img alt="ableton_spectrum_analyzer" src="https://user-images.githubusercontent.com/15041342/129435237-79f580c2-92f8-4822-afc7-2bda397a89f8.png" width="500" height="260">

### 2. AudioKit Oscillator with FFTView (A 440Hz Sine Tone)
<img alt="Screen Shot 2021-08-14 at 12 29 36 AM" src="https://user-images.githubusercontent.com/15041342/129435398-a2c4fa73-a7fb-4a56-ab36-fa68b5053d7f.png" width="500" height="373">

### 3. AudioKit Oscillator with FFTView (A 440Hz Sine Tone)
<img alt="Screen Shot 2021-08-14 at 12 30 44 AM" src="https://user-images.githubusercontent.com/15041342/129435464-4f7f8b72-5c04-4331-96d4-4ef81859c722.png" width="500" height="375">

I definitely think **2.** looks closer to **1.**, but I'm open to what others think as well. I'll make a PR with these changes for now.

**Comment by aure** [comment]
Closing the issue, thanks @emurray2 can still post comments or reopen this issue if necessary, but it does seem like this issue would have been better in the AudioKitUI issues anyway. Thank @aburgel as well, for bringing it to our attention with good details.
