### ISSUE TITLE
After deploying the project on ipad - sound doesn't generate 

### ISSUE THREAD

**Issue by NehalRaj** [audiokit/AudioKit#258]
The audio kit project builds successfully, and it run's perfectly fine in the simulator. However when i deploy the project on my ipad the app runs, but it doesn't generate any sound. Anyone having this issue?

**Comment by NehalRaj** [comment]
Any help be appreciated

**Comment by megastep** [comment]
Do you see any suspicious messages in the console when running the app? Are you talking about your own project or one of the demos?

**Comment by NehalRaj** [comment]
I don't see any suspicious message, i am talking about the "TableDemo" project which is on Audiokit. If there are thing i can try please let me know?

**Comment by NehalRaj** [comment]
The project runs fine in the simulator but when i deploy it on my Ipad it doesn't generate any sound. Everything else works!

**Comment by aure** [comment]
This is really not very much information to go on.  Is the ipad muted?

**Comment by NehalRaj** [comment]
Nope, checked the voice on ipad and it works for other stuff.

**Comment by aure** [comment]
Feel free to re-open this issue if you can provide more information.
