### ISSUE TITLE
Compile error: kDynamicsProcessorParam_MasterGain deprecated

### ISSUE THREAD

**Issue by matts9000** [AudioKit/AudioKit#2580]
For AudioKit 5.2.1:
The flag kDynamicsProcessorParam_MasterGain has been renamed to kDynamicsProcessorParam_OverallGain, which causes a compile error for target iOS 15.

Please update the sources for this.
Thanks!

**Comment by aure** [comment]
We don't support beta software and this appears to be an error in Apple deprecation.  Easy enough to change that to the constant. I believe its 6.

**Comment by aure** [comment]
Made the change on develop which you should use if you're also on beta iOS. https://github.com/AudioKit/AudioKit/commit/f6ac112ce97092b2394776088edaa39213c2d92d

**Comment by aure** [comment]
btw, https://github.com/AudioKit/AudioKit/issues/2568

**Comment by matts9000** [comment]
Hi,

You are right, that changing it for myself is easy enough, but I didn't think that this could be an Apple issue.
Anyway, now you updated it already.

May thanks for your ultra-fast response and support!
Matthias
