### ISSUE TITLE
AudioKit fails to build on XCode 13

### ISSUE THREAD

**Issue by dsharma** [AudioKit/AudioKit#2592]
AudioKit Cookbook fails to build on XCode 13. There is a build error in two files (DynamicsProcessor.swift and Compressor.swift):

       kDynamicsProcessorParam_MasterGain' has been renamed to 'kDynamicsProcessorParam_OverallGain': APIs deprecated as of iOS 7 and earlier are unavailable in Swift

**Comment by aure** [comment]
This is a copy of several other issues. Its not a problem with AudioKit but with Xcode 13, which is in beta still right? If you're using beta you might as well use AudioKit develop branch, which shouldn't have a hack around for this.

**Comment by nikolay-kapustin** [comment]
Xcode 13 now released. But, unfortunately, i still get above compile error.

**Comment by aure** [comment]
@nikolay-kapustin Using develop you get the error? I'm waiting for Xcode 13 to download and I'll get a release out for it soon.

**Comment by aure** [comment]
New version of AudioKit is out.
