### ISSUE TITLE
'kDynamicsProcessorParam_MasterGain' has been renamed to 'kDynamicsProcessorParam_OverallGain': APIs deprecated as of iOS 7 and earlier are unavailable in Swift

### ISSUE THREAD

**Issue by benben-hello** [AudioKit/AudioKit#2593]
xcode13.0
![image](https://user-images.githubusercontent.com/12512421/134322035-b6551eb5-045e-49dd-9be3-c25ac32d98ea.png)

**Comment by aure** [comment]
Copy of at least three other issues. Use AudioKit develop branch if you're on a beta of Xcode 13.
