### ISSUE TITLE
AudioKit does not work with CocoaPods if using Xcode13

### ISSUE THREAD

**Issue by Sheeproid** [AudioKit/AudioKit#2594]
**Describe the bug**
Using CocoaPods, AudioKit breaks the build because version 5.2.2 that supports Xcode13 haven't been uploaded there yet

**To Reproduce**
1. Create an Xcode project with a Podfile that uses AudioKit.
2. Try to Pod install with version 5.2.2

**Expected behavior**
Can you please upload the 5.2.2 version to CocoaPods 🙏 ?

Thanks

**Comment by aure** [comment]
We've left CocoaPods behind for the greener pastures of Swift Package Manager, sorry. I really recommend using SPM with AudioKit, even if you also use CocoaPods for other things, its a breeze.
