### ISSUE TITLE
Thread is locked when AudioEngine is deallocated.

### ISSUE THREAD

**Issue by Moriquendi** [AudioKit/AudioKit#2596]
**Describe the bug**
Thread is trapped in a mutex-wait when AudioEngine is deallocated.

**To Reproduce**
1. Create AudioEngine with an AudioPlayer
2. Play a segment of the player using `play(from: X, to: Y, ...)` // This one is important!
3. Stop an engine and destroy it
4. Repeat fast a few times

**Screenshots**
![Screenshot 2021-10-02 at 12 05 26](https://user-images.githubusercontent.com/1915971/135711837-dcb5f3c0-afd0-4294-8d71-0e6e28ff8823.png)

**Video**
https://www.dropbox.com/s/r7grvf20rno9us3/issue.mov?dl=0

**Details (please complete the following information):**
- Macbook Pro M1
- macOS Monterey, Beta 6 (21A5522h)
- Xcode 13.0
- AudioKit Version 5.2.2

**Additional context**
Attaching a sample Xcode project that demonstrates the issue:
[AudioTests.zip](https://github.com/AudioKit/AudioKit/files/7271265/AudioTests.zip)
And I'm also pasting the code here:
```swift
import SwiftUI
import AudioKit
import AVFAudio

struct ContentView: View {
    
    @StateObject private var viewModel = ViewModel()
    
    var body: some View {
        VStack {
            Button(action: {
                viewModel.start()
            }) {
                Text("Play")
            }
            
        }
        .padding(50)
    }
}


class ViewModel: ObservableObject {

    var engine: AudioEngine!
    
    var player: AudioPlayer?
    
    func prepare() {
        // Make new engine
        engine = AudioEngine()
        
        let fileURL = Bundle.main.url(forResource: "sine", withExtension: "m4a")!
        let avFile = try! AVAudioFile(forReading: fileURL)
        let player = AudioPlayer(file: avFile)!
        
        engine.output = player
        self.player = player
    }
    
    func start() {
        stop()
        
        prepare()
        
        try! engine.start()
        
        // Calling just play() doesn't cause problems
        // player?.play()
        // ...but calling play(from: , to: ...) will eventually lead to locked thread.
        player?.play(from: 0.1, to: 0.5,
                     at: nil,
                     completionCallbackType: .dataPlayedBack)
    }
    
    func stop() {
        // Stop and deinit old engine
        engine?.stop()
        engine = nil
    }
    
}

```

**Comment by aure** [comment]
Can you show that this problem does not occur when just using AVAudioEngine directly? If you can cause the problem to occur outside of AudioKit, the best bet would be to submit that as a bug to Apple. Since what you're doing is not involving too many layers of AudioKit I think there is a good chance this is on Apple.

**Comment by Moriquendi** [comment]
@aure I quickly implemented an `AVAudioEngine` implementation and it works fine (see code below).
I think the problem is somehow related to the `completionHandler` of `scheduleSegment(...)`. That's just a hunch since passing `nil` to the `completionHandler` fixes the issue. 
That completion handler is called during deallocating of AVAudioEngine - and within that block we're accessing the AVAudioEngine. 

On the other note, something that AudioKit is doing triggers memory leaks in Apple's `AudioToolboxCore`. It does not happen in that simple AVAudioEngine example.
I just noticed it now so I'm not sure if that's related to that particular issue or which code causes it. Will dig into it when I get a moment.
![Screenshot 2021-10-02 at 20 47 33](https://user-images.githubusercontent.com/1915971/135728496-c79a1567-42e2-4df8-9b37-3a705e334ad4.png)

(AVAudioEngine example that works fine:)
```swift
class ViewModel: ObservableObject {

    var engine: AVAudioEngine!
    
    weak var player: AVAudioPlayerNode?
    
    func prepare() {
        // Make new engine
        engine = AVAudioEngine()
        
        let fileURL = Bundle.main.url(forResource: "sine", withExtension: "m4a")!
        let avFile = try! AVAudioFile(forReading: fileURL)
        let player = AVAudioPlayerNode()
        
        engine.attach(player)
        engine.connect(player, to: engine.mainMixerNode, format: nil)
        
        player.scheduleSegment(avFile,
                               startingFrame: 100,
                               frameCount: 44_100,
                               at: nil,
                               completionHandler: {
            
        })
        
        
        self.player = player
    }
    
    func start() {
        print("[🎤] STOP")
        stop()
        
        print("[🎤] PREPARE")
        prepare()
        
        try! engine.start()
        
        player?.play()
    }
    
    func stop() {
        // Stop and deinit old engine
        engine?.stop()
        engine = nil
    }
    
}

```

**Comment by Moriquendi** [comment]
@aure All right, I actually was able to replicate the issue in the `AVAudioEngine` example. So as I mentioned, the issue is related to referencing `node.engine` in the `completionHandler` of `scheduleSegment`.

```swift
player.scheduleSegment(avFile,
                               startingFrame: 100,
                               frameCount: 44_100,
                               at: nil,
                               completionCallbackType: .dataPlayedBack) { [weak player] _ in
            print(player?.engine) // THIS WILL CAUSE PROBLEMS
        }
```

It does sound like a bug on the Apple's side, right? 😬 I'll report.

**Comment by aure** [comment]
Closing this issue for now, would love to get updates if Apple responds.

**Comment by Moriquendi** [comment]
I got response from Apple to my radar.

> The client should dispatch all interactions with the engine, or the player, to a different queue/thread.
> 
> From the the docstring on AVAudioPlayerNodeCompletionHandler in AVAudioPlayerNode.h:
> 
> “In general the callbacks arrive on a non-main thread and it is the client's responsibility
> to handle them in a thread-safe manner.
> 
> Setting or getting properties on an AVAudioPlayerNode while the AVAudioEngine is running requires
> some synchronisation between the calling threads internally. If you want to call player node API within this
> completion handler block, calls should be synchronised to the same thread/queue.”
> 

Here's a sample project I sent them for reference:
[AudioTests.zip](https://github.com/AudioKit/AudioKit/files/7776915/AudioTests.zip)
