### ISSUE TITLE
Not supported in swift 5.5 and compiler version 5.3

### ISSUE THREAD

**Issue by shivam6900** [AudioKit/AudioKit#2609]
when i am building it using xcode 13 and swift version 5.5 and compiler version 5.3 i am getting following error
**Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.5 compiler**

if anything wrong please help me out

**Comment by xbaldiq** [comment]
> thanks

sorry for reviving this old post, is there any chance to successfully install this via SWP on react-native?
