### ISSUE TITLE
Missing Plist Keys

### ISSUE THREAD

**Issue by gmcerveny** [audiokit/AudioKit#261]
I just uploaded a build to apple and the validator returned errors that CFBundleVersion and CFBundleShortVersionString were missing in libsndfile and csoundlib plist files.

**Comment by aure** [comment]
Did you grab the latest develop branch?  I think Stephane might have fixed this?

**Comment by aure** [comment]
https://github.com/audiokit/AudioKit/commit/204c9cbee0e63036a074e962e8a02b2f7ffd8e67

**Comment by gmcerveny** [comment]
Yes that's it, I should've checked the develop branch.
