### ISSUE TITLE
AudioKit-4.11.2 framework build failure on EZOutput on macOS 12.0.1, Xcode 13.1

### ISSUE THREAD

**Issue by inhumanscale** [AudioKit/AudioKit#2610]
I'm still in the process of migrating from v4 to v5 and getting the following compile-time error for v4 when running ./build_frameworks.sh,
```
.../AudioKit-4.11.2/AudioKit/Common/Internals/EZAudio/EZAudioUtilities.h:420:40: expected a type

+ (void)getColorComponentsFromCGColor:(CGColorRef)color
                                       ^

▸ Compiling EZOutput.m
```
Happy to provide more information.

 - OS: macOS 12.0.1, Xcode 13.1
 - AudioKit 4.11.2

**Comment by aure** [comment]
Is it something you use in your application? Maybe comment it out and see what breaks. Maintaining EZAudio was one of the pain points of AudioKit pre-version 5, and 5 has been out for a while now, so I can't see anyone going back to look into this futher.
