### ISSUE TITLE
how to make pod with 5.2.0?

### ISSUE THREAD

**Issue by OHeroJ** [AudioKit/AudioKit#2616]
project to frameworks

**Comment by megastep** [comment]
You can't; however you can use the Swift Package Manager alongside other pods, works fine in my experience.

**Comment by OHeroJ** [comment]
> You can't; however you can use the Swift Package Manager alongside other pods, works fine in my experience.

thanks! 

I use it in the flutter plugin, but the plugin only supports pod。

**Comment by OHeroJ** [comment]
https://github.com/akkyie/XPM

不知道是否可以打包成 xcframework
