### ISSUE TITLE
DynamicRangeCompressor initial crash

### ISSUE THREAD

**Issue by OHeroJ** [AudioKit/AudioKit#2617]
use AudioKit 5.1.0 with pod,

**and crash**

<img width="982" alt="Screen Shot 2021-11-10 at 10 29 36 AM" src="https://user-images.githubusercontent.com/12316547/141038704-815e0a74-c653-4382-a743-75abd0651118.png">

**the console show:**

```
akGetParameterAddress: Unknown parameter name: DynamicRangeCompressorParameterRatio
akGetParameterAddress: Unknown parameter name: DynamicRangeCompressorParameterThreshold
akGetParameterAddress: Unknown parameter name: DynamicRangeCompressorParameterAttackDuration
akGetParameterAddress: Unknown parameter name: DynamicRangeCompressorParameterReleaseDuration
Unknown DSPBase subclass: cpsr
Runner was compiled with optimization - stepping may behave oddly; variables may not be available.
```

**and the sample project:**

[https://github.com/OHeroJ/audiokitDemo](https://github.com/OHeroJ/audiokitDemo)

**Comment by aure** [comment]
Does this happen with AudioKit included via Swift Package Manager?

**Comment by aure** [comment]
Well, I just verified your code does fine using AudioKit via SPM. I have no idea what had to go into making a pod out of it, but I can't really debug something I can't condone.
