### ISSUE TITLE
'receivedMIDINoteOff' not calling

### ISSUE THREAD

**Issue by Memtimen** [AudioKit/AudioKit#2618]
**Describe the bug**
playing MIDINoteData using sequencer function 'receivedMIDINoteOff' not calling, 'receivedMIDINoteOn' Only.

**To Reproduce**

1. There is a AppleSequencer with MIDINoteData;
2. I have create createVirtualPorts using sequncer?.tracks[bass].setMIDIOutput(ref) and adding listener.
3. receivedMIDINoteOn works great, but receivedMIDINoteOff not calling.
4. I have send MIDI message using Logic Pro X, both receivedMIDINoteOff and receivedMIDINoteOn works fine.

//////AppleSequencer:
Bass Track Onte On: 48
Bass Track Onte On: 48
Bass Track Onte On: 48
Bass Track Onte On: 48
Bass Track Onte On: 48
Bass Track Onte On: 48
Bass Track Onte On: 48
Bass Track Onte On: 48

//////AppleSequencer: Logic Pro X with MIDI Keyboard.
Bass Track Onte On: 48
Off Note: 48
Bass Off: 48
Bass Track Onte On: 48
Off Note: 48
Bass Off: 48
Bass Track Onte On: 48
Off Note: 48
Bass Off: 48
Bass Track Onte On: 48
Off Note: 48
Bass Off: 48

**Details (please complete the following information):**
 - Type: [ Mac]
 - OS: [12.1 Beta (21C5021h)]
 - AudioKit Version [Main]

**Comment by aure** [comment]
Could it be callign midinote onwith velocity of zero? That's a very common note off alternative.

**Comment by Memtimen** [comment]
yes, "velocity of zero" works great, thanks.
