### ISSUE TITLE
Package download URL doesn't work (XCode 13.1)

### ISSUE THREAD

**Issue by profjb58** [AudioKit/AudioKit#2619]
**Describe the bug**
Think it's an issue with the latest XCode version (13.1) but I can't import AudioKit using the following URL ```https://github.com/AudioKit/AudioKit```. Similarly i'm trying to import as a local package from one of the github releases but i'm getting nothing. Wondering if i've missed a step maybe.

**To Reproduce**
- Click File > Add Packages
- `+` button, Add Swift Collection, enter the URL

OR

- Add Local...
- Select the location for the packages contents, in this case the audio kit source including the Package.swift file

**Expected behavior**
Should load AudioKit properly as a package.

**Details (please complete the following information):**
XCode 13.1, AudioKit 5.2.2, Macbook Air, latest M1 chip

I should note that i'm not a MacOS / IOS developer, this is for a one off project at the moment so I may be missing something obvious.

**Comment by profjb58** [comment]
I should note loading the example Swift playground file provided and trying to run it also doesn't work

**Comment by aure** [comment]
That's not a URL for a collection. Try the directions on thed develop branch: https://github.com/AudioKit/AudioKit/tree/develop
