### ISSUE TITLE
The "Play Audio File" example on the website is confusing.

### ISSUE THREAD

**Issue by alexdmiller** [audiokit/AudioKit#262]
This page feels incomplete: http://audiokit.io/examples/swift/PlayAudioFile/

It says that, "A path to the audio file that will be played ("blaster.aiff") is defined in the code below from "AudioFilePlayer.m"." But it's not specific about whether you should import AudioFilePlayer, extend it, or just copy and paste the code from AudioFilePlayer.

If you're supposed to edit the code that's already there, then its placement inside of AudioKit/Utilities/Instruments/File Players/ is odd. If that's the case, it should be in an Examples folder, not the Utilities folder.

**Comment by aure** [comment]
Fixed in https://github.com/audiokit/audiokit.github.io/commit/6807614bff0214670163cd621f54063effa801c2

Thanks.

**Comment by alexdmiller** [comment]
That doesn't address the issue. First of all, I don't think a file called "AudioFilePlayer.swift" exists in the project. Secondly, the file extension isn't the confusing part. The confusing part is the documentation doesn't tell you *how to use* AudioFilePlayer.m (whether to create an instance of AudioFilePlayer, or extend the class, or copy and paste the code into your own project). The documentation needs to be more explicit about how to use the AudioFilePlayer class.

I've re-opened the issue on the audiokit.github.io project:
https://github.com/audiokit/audiokit.github.io/issues/62
