### ISSUE TITLE
getCurrentTime() returns infinite time if player is in loop mode.

### ISSUE THREAD

**Issue by ShowtimeSoft** [AudioKit/AudioKit#2620]
**Describe the bug**
AudioPlayer.getCurrentTime() does not report the correct playtime if AudioPlayer is in loop mode. 
After the first loop, time continues as if there was no loop.

**To Reproduce**
player.isLooping = true
print (player.getCurrentTime())

**Expected behavior**
I would expect the reported time to follow the timing of the loop.

**Details (please complete the following information):**
 - Mac
 - OS: 15
 - AudioKit Version 5.2

**Comment by aure** [comment]
I wonder if this shouldn't be thought of as a feature? Its easy enough to "mod" the current time with the duration to get the time within the loop and you also can get the number of loops that have been played out of this information.

**Comment by ShowtimeSoft** [comment]
Ok, to me it looked like a bug, but I guess you can argue that currentTime is infinite.
So let's close it here, thanks!
