### ISSUE TITLE
Weird midi file events since migrating to 5.2.2 (5.0.0 was ok) 

### ISSUE THREAD

**Issue by gregoireLem** [AudioKit/AudioKit#2622]
**Weird midi file events since migrating to 5.2.2**
I use exactly the same piano midi files I was using in audio kit 5.0.0 and it was working perfectly. Since migrating ro 5.2.2, some Note On events are skipped (I have noticed that it seems to happened when two same notes are following)
To precise the expected behavior : Note A ON -> Note A OFF -> Note A ON. The bug behavior : last Note A ON is skipped

**To Reproduce**
 Load a midi file from AppleSequencer(filename: filename)
 sequencer.setGlobalMIDIOutput(self.midiIn)

subscribe to MIDICallbackInstrument delegates, some notes event will be skipped.

**Additional context**

I experience the bug every time, but not always at the same moment of the midi file sequence
Once again everything is ok on Audiokit 5.0.0 or Garageband

How can I help to debug ?
What can I do to fix this ?

Thanks

**Comment by aure** [comment]
So, you can't use 5.0.0 because it won't compile on modern Xcode right? So we have to figure out if its a change in AudioKit or a change in MIDI that may have occurred along the way right?

**Comment by gregoireLem** [comment]
It's because I need DunneAudiokit which depends on Audiokit 5.2
Do you want me to test each version since 5.0.0 to see were the bug comes from ?

**Comment by aure** [comment]
I think there are versions of DunneAudioKit for each release of AudioKit, but it may not be perfect. It would be of course amazing if you could narrow down at which version it still worked and what version it stopped working.

**Comment by gregoireLem** [comment]
5.0.1 -> Ok
5.1.0 -> buggy

**Comment by christianhengst** [comment]
Already any updates on this? I'm having the same issue. Also, the callback is only called for the lowest note of a chord. 

For example, for a MIDI file containing one track with chords `Bbm Cm Bbm Ab`

The callback only triggers the very first "noteOn" event and then only "noteOff" events AND only for the bass notes.

```
noteOn noteNumber: 46
noteOff noteNumber: 46
noteOff noteNumber: 36
noteOff noteNumber: 46
```

I'm loading the MIDI file like this

```
let sequencer = AppleSequencer()

sequencer.loadMIDIFile(fromURL: pathToMidiFile)
```

The sequencer is playing the file correctly if connected to, for example, a MIDISampler. Meaning there is probably something wrong with `MIDICallbackInstrument`

When adding a track and events manually, the callback triggers fine.

Thanks for any help!
