### ISSUE TITLE
Sampler (Dunne): Assertion failure (segments) in `DunneCoreMultiSegmentEnvelopeGenerator::skipEmptySegments()`

### ISSUE THREAD

**Issue by maksutovic** [AudioKit/AudioKit#2623]
(Note, I would try to reproduce in the cookbook, however the Cookbook currently has no recipes utilizing the (Dunne) `Sampler()`).

**Describe the bug**
When attempting to play a note with the `Sampler()` object, the app crashes. 
I.E. `sampler.play(noteNumber: velocity: channel)`

It is a failed assertion on segments in the envelope generator:
```
Assertion failed: (segments), function skipEmptySegments, file EnvelopeGeneratorBase.cpp, line 93.
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/usr/lib/libMTLCapture.dylib
```

This is with samples loaded into the sampler via the SFZ method (the preferred method). I have tried loading a sample with `Sampler(sampleDescriptor: file)` however I am unable to produce any output with this method.

**To Reproduce**
I have made a rudimentary repo which demonstrates the issue: https://github.com/maksutovic/DunneSamplerCrash-AK-5.2.2

1. Clone Repo
2. Run in either Simulator or Device
3. Assertion failure

**Expected behavior**

I expect the `Sampler()` to in fact play the note specified and not crash.

**Screenshots**
<img width="2551" alt="Screen Shot 2021-11-17 at 12 48 19 PM" src="https://user-images.githubusercontent.com/1383383/142195744-065aa419-96d6-4ca8-8749-d4281a9ca929.png">
<img width="751" alt="Screen Shot 2021-11-17 at 12 48 38 PM" src="https://user-images.githubusercontent.com/1383383/142195756-962975d9-7817-4366-a78e-e7e00267dcf5.png">

**Details (please complete the following information):**
 - Type: iPhone 11 Pro OR Simulator
 - OS: iOS 15.1 19B74
 - AudioKit Version: 5.2.2

**Additional context**
I would be happy to try and resolve this issue however I would definitely need some pointers of how the envelope generator works with the sampler.

**Comment by aure** [comment]
The Sampler is in DunneAudioKit so this issue should go there https://github.com/AudioKit/DunneAudioKit/issues
and the fact that the Cookbook doesn't have an example from DunneAudioKit could in the Cookbook issues. The bug report looks good though so should just be a copy and paste job, thanks in advance.
