### ISSUE TITLE
AudioKit.swiftmodule is either malformed or generated by a different Swift version

### ISSUE THREAD

**Issue by nalexn** [AudioKit/AudioKit#2624]
**Describe the bug**
 
`import AudioKit` line shows the warning:

> '/Users/me/Library/Developer/Xcode/DerivedData/my-app/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/AudioKit/Core/AudioKit.framework/Modules/AudioKit.swiftmodule/Project/x86_64-apple-ios-simulator.swiftsourceinfo' is either malformed or generated by a different Swift version. Note that it uses an unstable format and may leak internal project details, it should not be distributed alongside modules

**Details (please complete the following information):**
 - Xcode 13.1
 - Swift 5
 - Building for an iOS simulator 15.0
 - M1 mac
 - AudioKit Version 5.1.0
 - Added using cocoapods

Steps like clearing DerivedData, re-opening Xcode, etc don't help.

**Comment by aure** [comment]
Sounds likes its telling you what it is wrong. AudioKit "is either malformed or generated by a different Swift version." you don't mention which version of AudioKit you're using. Hav you updated to the latest? Closing for now.

**Comment by megastep** [comment]
That's because you're using the CocoaPods version with Xcode 13. You need to switch to using SPM for AudioKit. The compiled binaries we used are no longer compatible.

**Comment by nalexn** [comment]
I can see now the latest is v5.2.2, while the latest version published on CocoaPods is 5.1.0. That's a bummer AudioKit no longer supports CocoaPods.

**Comment by nodata** [comment]
This sucks
