### ISSUE TITLE
Could not find module 'AudioKit' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by nalexn** [AudioKit/AudioKit#2625]
**Describe the bug**

When building the project with the latest stable Xcode (13.1), latest stable AudioKit (5.2.2) for iOS 15 simulator on mac M1, I get the error:

> Could not find module 'AudioKit' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /Users/me/Library/Developer/Xcode/DerivedData/my-app/Build/Products/Debug-iphonesimulator/AudioKit.swiftmodule

When building for a device, the error goes away.

**Details (please complete the following information):**
- Xcode 13.1
- Swift 5
- Building for an iOS simulator 15.0
- M1 mac
- AudioKit Version 5.2.2
- Added using SPM

**Comment by aure** [comment]
I compile to the simulator every day on my M1 and have no problems. I can do a screen share with you if you like, but as far as I can tell this is not reproducible. It could be a problem with your set up.

**Comment by nalexn** [comment]
Ok, for anyone else facing this error: the problem was with `Excluded Architectures` section in the `Build Settings`. `arm64` was excluded for the iOS simulator, I don't remember when / why that setting was set:

<img width="745" alt="1" src="https://user-images.githubusercontent.com/1594746/142655453-3eed71f8-8989-4d07-9b6a-29d5bf53848f.png">

**Comment by aure** [comment]
Ahh, yes, I guess I have seen that before but it has happened to me personally. Hopefully this will help others. Thanks for the follow up.
