### ISSUE TITLE
Pitch Tap Memory Leak

### ISSUE THREAD

**Issue by ChondroSW** [AudioKit/AudioKit#2626]
<img width="1786" alt="Screen Shot 2021-11-19 at 02 13 42" src="https://user-images.githubusercontent.com/90369090/142481662-b318b8ea-4b66-492d-97b1-84e3476f70a7.png">
**Screenshots**

<img width="1283" alt="Screen Shot 2021-11-19 at 02 18 57" src="https://user-images.githubusercontent.com/90369090/142482663-8c9ee1f5-3380-49c6-89dd-3be7dc9ef687.png">
**Details (please complete the following information):**
<img width="1283" alt="Screen Shot 2021-11-19 at 02 18 02" src="https://user-images.githubusercontent.com/90369090/142482598-23394e82-d681-4c56-9a94-f8502cc05231.png">
 - Type: IPAD pro 2020
 - OS: IPAD OS 15
 - AudioKit Version 5.2.2

<img width="1283" alt="Screen Shot 2021-11-19 at 02 18 13" src="https://user-images.githubusercontent.com/90369090/142482616-d9510537-4180-48a3-be47-0f6af6616dba.png">
**Additional context**
 I have issued with memory leak.
<img width="1283" alt="Screen Shot 2021-11-19 at 02 18 33" src="https://user-images.githubusercontent.com/90369090/142482625-a6f84f30-30c3-4acb-80f6-875bbc80acfc.png">
 when i start to use PitchTap and Audio Engine and node. how to i solve memory leak when i use Audiokit?

**Comment by wtholliday** [comment]
Given your code is leaking `PitchDetectionViewModel` which isn't in AudioKit, this seems like a bug outside of AudioKit. The AK objects are leaking probably because your `PitchDetectionViewModel` has strong references to them.
