### ISSUE TITLE
Trying to record to m4a format using NodeRecorder

### ISSUE THREAD

**Issue by hoopes** [AudioKit/AudioKit#2634]
**Describe the bug**
I am attempting to use the `NodeRecorder` to record to a different file format - in this case, `m4a`. The use case is that it will trade cpu usage for disk activity, theoretically reducing battery usage.

**To Reproduce**

I tried to copy `NodeRecorder.createTempFile()`, ([here](https://github.com/AudioKit/AudioKit/blob/main/Sources/AudioKit/Taps/NodeRecorder.swift#L92)) and just replace the `AVFormatIdKey` in the settings:

```
    let filename = UUID().uuidString + ".m4a"
    let fileUrl = fm.tempDir.appendingPathComponent(filename)

    var settings = Settings.audioFormat.settings
    settings[AVFormatIDKey] = kAudioFormatMPEG4AAC
    settings[AVLinearPCMIsNonInterleaved] = NSNumber(value: false)

    let file = try! AVAudioFile(
      forWriting: fileUrl,
      settings: settings,
      commonFormat: Settings.audioFormat.commonFormat,
      interleaved: true)

    // Use the AK recorder
    recorder = try! NodeRecorder(node: node, file: file)
```

(Ignore the forced unwrapping, as it’s just a test so far)

This _appears_ to be doing the right thing - I see in the log:

```
[general] NodeRecorder.swift:record():136:⏺ Recording using format <AVAudioFormat 0x6000034dbde0:  2 ch,  44100 Hz, Float32, non-inter> (NodeRecorder.swift:record():136)
```

However, when I go to finish the recording, I get the error:
```
OpenFromDataSource failed
Open failed
[default]          ExtAudioFile.cpp:193   about to throw 'dta?': open audio file
[avae]            AVAEInternal.h:109   [AVAudioFile.mm:134:AVAudioFileImpl: (ExtAudioFileOpenURL((CFURLRef)fileURL, &_extAudioFile)): error 1685348671
```

That error code (see [here](https://www.osstatus.com/search/results?platform=all&framework=all&search=1685348671)) means `kAudioFileInvalidFileError`.

Further, if i add a breakpoint [here](https://github.com/AudioKit/AudioKit/blob/main/Sources/AudioKit/Taps/NodeRecorder.swift#L45) and look at the file on disk, it _appears_ to be a valid m4a file, but have zero duration and a `N/A` bitrate:

```
$ ffmpeg -i 120B3F7B-5E9D-4620-804C-7FF9906F87A0.m4a
...snip...
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '120B3F7B-5E9D-4620-804C-7FF9906F87A0.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2021-12-05T19:30:28.000000Z
  Duration: 00:00:00.00, bitrate: N/A
  Stream #0:0(eng): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2021-12-05T19:30:28.000000Z
      vendor_id       : [0][0][0][0]
```

**Expected behavior**
I expect/hope the data will be written in a compressed format using the `NodeRecorder`.

**Screenshots**

**Details (please complete the following information):**
 - Type: various iphone/ipad simulators - not yet attempted on an actual device
 - OS: `ios 15`
 - AudioKit Version: `5.2.2`
 
**Additional context**
For reference, in another codebase I have access to that used AK4, it was done like so:

```
let tempFile = try AKAudioFile()
let originalUrl = tempFile.url
var settings = tempFile.fileFormat.settings
let location = tempFile.url.deletingLastPathComponent()
let fixedURL = location.appendingPathComponent(name).appendingPathExtension(“m4a”)
settings["AVFormatIDKey"] = kAudioFormatMPEG4AAC

return try AKAudioFile(forWriting: fixedURL, settings: settings)
```

Not sure if that’s helpful at all.

**Comment by hoopes** [comment]
thanks @wtholliday !!!

**Comment by hoopes** [comment]
Hi, I’m sorry to admit, I’m still having a problem recording to m4a. Your test works cleanly - it records 2 seconds of an oscillator, ffmpeg reads it correctly, and VLC plays it correctly. However, I’m still having trouble using it - I was hoping you could point me in the right direction. I checked that that `settings` being passed to each `AVAudioFile` were the same - see below. However, the result file is malformed. Doing the default `caf` recording works totally fine, so I’m not sure if there’s a detail I’m missing.

Could it potentially be something from the AK `Settings` object?

If there’s nothing obvious here, I will try to rebuild my audio chain from scratch, but like I said, `caf` recordings are working perfectly. Any advice you can offer would be greatly appreciated and gratefully received.

<details><summary>From the AK test</summary>

In test breakpoint:

```
(lldb) po settings
▿ 7 elements
  ▿ 0 : 2 elements
    - key : "AVNumberOfChannelsKey"
    - value : 2
  ▿ 1 : 2 elements
    - key : "AVLinearPCMIsNonInterleaved"
    - value : 0
  ▿ 2 : 2 elements
    - key : "AVSampleRateKey"
    - value : 44100
  ▿ 3 : 2 elements
    - key : "AVFormatIDKey"
    - value : 1633772320
  ▿ 4 : 2 elements
    - key : "AVLinearPCMIsBigEndianKey"
    - value : 0
  ▿ 5 : 2 elements
    - key : "AVLinearPCMBitDepthKey"
    - value : 32
  ▿ 6 : 2 elements
    - key : "AVLinearPCMIsFloatKey"
    - value : 1
```

```
fileURL: file:///var/folders/gp/xydljsp152zb92c1cqftlnjh0000gn/T/1915AF91-6BB8-4458-B95B-E1E8AD33B1FC.m4a
```

```
$ ffmpeg -i /var/folders/gp/xydljsp152zb92c1cqftlnjh0000gn/T/1915AF91-6BB8-4458-B95B-E1E8AD33B1FC.m4a
…snip…
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/folders/gp/xydljsp152zb92c1cqftlnjh0000gn/T/1915AF91-6BB8-4458-B95B-E1E8AD33B1FC.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2021-12-08T02:29:29.000000Z
    iTunSMPB        :  00000000 00000840 00000072 000000000001474E 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
  Duration: 00:00:01.95, start: 0.047891, bitrate: 319 kb/s
  Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 84 kb/s (default)
    Metadata:
      creation_time   : 2021-12-08T02:29:29.000000Z
      vendor_id       : [0][0][0][0]
```
</details>

<details><summary>From my app</summary>

```
(lldb) po settings
▿ 7 elements
  ▿ 0 : 2 elements
    - key : "AVFormatIDKey"
    - value : 1633772320
  ▿ 1 : 2 elements
    - key : "AVLinearPCMBitDepthKey"
    - value : 32
  ▿ 2 : 2 elements
    - key : "AVLinearPCMIsBigEndianKey"
    - value : 0
  ▿ 3 : 2 elements
    - key : "AVSampleRateKey"
    - value : 44100
  ▿ 4 : 2 elements
    - key : "AVNumberOfChannelsKey"
    - value : 2
  ▿ 5 : 2 elements
    - key : "AVLinearPCMIsFloatKey"
    - value : 1
  ▿ 6 : 2 elements
    - key : "AVLinearPCMIsNonInterleaved"
    - value : 0
```

```
$ ffmpeg -i EBD923E4-99AF-452D-9D70-B70483A9A23F.m4a
…snip…
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fb29c815c00] moov atom not found
EBD923E4-99AF-452D-9D70-B70483A9A23F.m4a: Invalid data found when processing input
```
</details>

**Comment by aure** [comment]
Are you sure you've updated to the latest code? Seems like it's possible that it's still hanging onto the old code. I released AudioKit 5.2.3 with the fix, so if that's the version SPM says you have that would be good to double check.

**Comment by aure** [comment]
Make a test that demonstrates the bug, and we'll be all over it :)

**Comment by hoopes** [comment]
I was unable to add a true test to the AK codebase, but I tried two things to record to an m4a file, copying the steps from the given [test](https://github.com/AudioKit/AudioKit/blob/main/Tests/AudioKitTests/Extension%20Tests/AVAudioPCMBufferTests.swift#L20):

1) I cloned the Cookbook, and edited the Recorder.swift file. See the branch ([here](https://github.com/AudioKit/Cookbook/compare/main...hoopes:recorder-m4a-test?expand=1)) that copy/pasted the m4a code from the test ([here](https://github.com/AudioKit/AudioKit/blob/main/Tests/AudioKitTests/Extension%20Tests/AVAudioPCMBufferTests.swift#L20)).

When I run this on both a simulator or a physical (iPhone 12 pro max), I get the following error:

```
2021-12-12 14:06:04.513232-0500 Cookbook[7895:854763]  OpenFromDataSource failed
2021-12-12 14:06:04.514796-0500 Cookbook[7895:854763]  Open failed
2021-12-12 14:06:04.515909-0500 Cookbook[7895:854763] ExtAudioFile.cpp:193:Open: about to throw 'dta?': open audio file
2021-12-12 14:06:04.516183-0500 Cookbook[7895:854763] [avae]            AVAEInternal.h:109   [AVAudioFile.mm:134:AVAudioFileImpl: (ExtAudioFileOpenURL((CFURLRef)fileURL, &_extAudioFile)): error 1685348671
2021-12-12 14:06:04.519237-0500 Cookbook[7895:854763] [general] NodeRecorder.swift:audioFile:48:Error, Cannot create internal audio file for reading: The operation couldn’t be completed. (com.apple.coreaudio.avfaudio error 1685348671.) (NodeRecorder.swift:audioFile:48)
```


2) I’ve also created a test app [here](https://github.com/hoopes/AKRecorderTest), which is a copy/paste of the Recorder.swift, and added an mp3 player as the node to be recorded. It exhibits the same issue, except not from the `engine.input`. Not sure of how much use it is.

**Comment by aure** [comment]
Why weren't you able to make a test?

**Comment by eljeff** [comment]
I've gone through and altered his test project code to something that can be more easily copy/pasted into a self-contained test, and he's got a test that fails now.
I'm making no assumptions or guesses re: the failure, I'm just helping get the syntax of the code easier to show the failure.
@hoopes make a note here when you've got a failing a test and this should be reopened.

**Comment by hoopes** [comment]
Thanks @eljeff  - the failing test (and PR) are here: https://github.com/AudioKit/AudioKit/pull/2642

**Comment by emurray2** [comment]
@hoopes It appears that `AVAudioEngine` get's angry when you try to read/write an `AVAudioFile` in the same code block. See these examples below, which don't use AudioKit at all. I also made a pull request you'll see above which you can try and build. Let me know if it works for you.

This is yet again another one of those weird Apple quirks. I'm surprised I didn't see any warnings about this in the documentation. Maybe I should file a bug report?

<details>
<summary>Code that Breaks</summary>

```
let fm = FileManager.default
let filename = UUID().uuidString + ".m4a"
let fileUrl = fm.temporaryDirectory.appendingPathComponent(filename)

let audioFormat = AVAudioFormat(standardFormatWithSampleRate: 44_100, channels: 2)!
var settings = audioFormat.settings
settings[AVFormatIDKey] = kAudioFormatMPEG4AAC
settings[AVLinearPCMIsNonInterleaved] = NSNumber(value: false)

let fileForWriting = try! AVAudioFile(forWriting: fileUrl, settings: settings)
print("Written File URL:",fileForWriting.url)

let fileForReading = try! AVAudioFile(forReading: fileUrl)
print("File URL to Read:",fileForReading.url)
```
</details>

<details>
<summary>Code that Works</summary>

```
let fm = FileManager.default
let filename = UUID().uuidString + ".m4a"
let fileUrl = fm.temporaryDirectory.appendingPathComponent(filename)

let audioFormat = AVAudioFormat(standardFormatWithSampleRate: 44_100, channels: 2)!
var settings = audioFormat.settings
settings[AVFormatIDKey] = kAudioFormatMPEG4AAC
settings[AVLinearPCMIsNonInterleaved] = NSNumber(value: false)

if true {
    let fileForWriting = try! AVAudioFile(forWriting: fileUrl, settings: settings)
    print("Written File URL:",fileForWriting.url)
}

let fileForReading = try! AVAudioFile(forReading: fileUrl)
print("File URL to Read:",fileForReading.url)
```
</details>

**Comment by emurray2** [comment]
This issue should be fixed now with #2716

**Comment by hoopes** [comment]
Hi Evan - sorry for the slow response. The `if true` thing is kind of hilarious. I actually have a "fix" (such as it is) in a branch [here](https://github.com/hoopes/AudioKit/pull/1/files#diff-38154f531c6719bf247cfacbb45c7c017cda2ff35c5556d2e61395e0ba2ee32aR53-R64). 

Jeff Cooper helped me find (if memory serves, he would be the one with the deeper detailed description) that m4a files are not closed/flushed until they go out of scope, so in my "fix" I set it to null. Obviously it's not great in that you can only read the recorded file once, but it is working for me and my current use case.

I will gladly try this new stuff, and report back. I was kinda dreading keeping a branch up to date with whatever release was out. Thanks so much!

**Comment by emurray2** [comment]
> Hi Evan - sorry for the slow response. The `if true` thing is kind of hilarious. I actually have a "fix" (such as it is) in a branch [here](https://github.com/hoopes/AudioKit/pull/1/files#diff-38154f531c6719bf247cfacbb45c7c017cda2ff35c5556d2e61395e0ba2ee32aR53-R64). 
> 
> 
> 
> Jeff Cooper helped me find (if memory serves, he would be the one with the deeper detailed description) that m4a files are not closed/flushed until they go out of scope, so in my "fix" I set it to null. Obviously it's not great in that you can only read the recorded file once, but it is working for me and my current use case.
> 
> 
> 
> I will gladly try this new stuff, and report back. I was kinda dreading keeping a branch up to date with whatever release was out. Thanks so much!

No worries, yeah luckily he told me after I initially replied. Yeah, that was my weird way of getting the code to run in a different scope 😂.

But the `nil` thing makes so much more sense. As far as the new stuff goes, it's actually breaking the CI, so I'm not sure about it yet. I'll let you know if it does end up getting merged. But it's great to hear your original code is working now 🙌🏻! This is a weird quirk about Apple code. I'm surprised `AVAudioFile` doesn't have a `close` function or something.

**Comment by aure** [comment]
This thread has gotten too long to follow.  If there are still problems lets reopen some new highly specific issues.
