### ISSUE TITLE
AudioKit is throwing -10878

### ISSUE THREAD

**Issue by ShowtimeSoft** [AudioKit/AudioKit#2635]
**Describe the bug**
AudioKit seems to be throwing, and I get numerous lines in the console like these:
2021-12-09 11:26:12.682832+0100 Cookbook[28349:9181454] throwing -10878

I am not sure what it is, but it looks quite unhealthy :-)

**To Reproduce**
Steps to reproduce the behaviour:
As soon as I connect to the mixer, I start getting these.
I also get these as soon as I start the Cookbook and watch the output console.

**Expected behavior**
I would not expect AudioKit to be throwing

**Details (please complete the following information):**
 - Type: Mac
 - OS: Monterey 12.1
 - AudioKit Version: This started a while ago, but is certainly present in 5.2.3

**Comment by aure** [comment]
No, AudioKit is not throwing this issue.  This is happening at the Apple level and we're all just waiting for an update from them that will fix this.
