### ISSUE TITLE
Can't compile,error: Expected '>'

### ISSUE THREAD

**Issue by starock** [audiokit/AudioKit#264]
There are 20 errors like:

/AudioKit-master/AudioKit/Tables/AKTable.h:43:49: Expected '>'

How to fix them?

**Comment by aure** [comment]
According to our automated testing service, and my own results on my machine, AudioKit compiles fine.  I have never seen an error like this and its not really much information to analyze.

**Comment by megastep** [comment]
Yeah, you should paste more of the actual logs you get from the compiler here, but I'd guess it probably has very little to do with AudioKit itself and more with the way you set up your project.
