### ISSUE TITLE
v4.11.2: kDynamicsProcessorParam_MasterGain renamed to kDynamicsProcessorParam_OverallGain

### ISSUE THREAD

**Issue by sparist** [AudioKit/AudioKit#2640]
For v4.11.2 to build on Xcode 13.2 for iOS 15.1.1, `kDynamicsProcessorParam_MasterGain` has to be renamed to `kDynamicsProcessorParam_OverallGain` in order to build.

I understand that v4.* may not be supported anymore, but there are limitations with v5.* that prevent me from upgrading at this time. I've done the rename and will be submitting the fix for this ticket.

**Comment by aure** [comment]
Thanks!
