### ISSUE TITLE
Support Swift Playgrounds app

### ISSUE THREAD

**Issue by luizmb** [AudioKit/AudioKit#2643]
**Describe the bug**
As a first step to support Swift Playgrounds app, the release tags should not have the "v" prefix, such as "v5.2.3". It's not clear if Apple will eventually fix that to also allow tags with the prefix, but at the moment the workaround is to simply create another tag in GitHub and point the release to it.

After that, further changes may be necessary to support it, but as AudioKit already offers Swift Playgrounds playground, this is promissing.

**To Reproduce**
1. Open 'Swift Playgrounds 4' app on an iPad running iPadOS 15.2
2. Click on '+ App' icon
3. Click on '+ document icon, on top-right corner of the split view collapsible left panel.
4. Pick 'Swift Package'
5. Type https://github.com/AudioKit/AudioKit and hit enter

**Expected behavior**
A list of AudioKit released versions should be shown

**Status quo**
Error message "Package does not have version tags".

**Details (please complete the following information):**
 - Type: iPad
 - OS: iPadOS 15.2

**Comment by aure** [comment]
I just pushed a "5.2.3" tag which should allow you to get to the next blocking step of this process, whatever that might be.

**Comment by aure** [comment]
Seems like the Playgrounds app doesn't like frameworks with clang targets.

**Comment by luizmb** [comment]
Hu @aure ,

Thanks a lot for the very quick response. I also faced the same issue as you, I wonder why a regular playground allows such target, while the playground app does not.

I'm gonna open a radar and hope that Apple will eventually fix this.

**Comment by aure** [comment]
Well, what's interesting is that @wtholliday and I went to great pains to make AudioKit a Swift-only framework. But, AudioKitEX is not, and since it sits alongside AudioKit in the repo, its causing this issue. I suppose I could make AudioKitEX its own repo.

**Comment by aure** [comment]
I just tested it and it works for AudioKit 5.3. Mind you there is a lot of functionality missing, but it does work!!!!

```
import SwiftUI
import AudioKit

class Tester {
    let engine = AudioEngine()
    let osc = PlaygroundOscillator()
    init() {
        engine.output = osc
        osc.start()
        try! engine.start()
        
    }
}

struct ContentView: View {
    var tester = Tester()
    
    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundColor(.accentColor)
            Text("Hello, world!")
        }
    }
}
```

**Comment by aure** [comment]
https://www.youtube.com/watch?v=_H7xj_HCByA

**Comment by luizmb** [comment]
Hi @aure,

Gre	at work, thanks a lot for the video, really cool having this kind of material!

I'm gonna have time to explore more AudioKit as a Playgrounds App today,  my interest is more towards MIDI Bluetooth, which is painful to debug using mac + a real iOS device + the peripheral, I see potential on the iPad as dev tool for this, a much simpler setup. Using CoreMIDI directly would hurt the purpose completely.

Again, thanks for the effort, have fantastic holidays!
