### ISSUE TITLE
[AppleSequencer] `bindMemory` API misuse

### ISSUE THREAD

**Issue by YuAo** [AudioKit/AudioKit#2645]
https://github.com/AudioKit/AudioKit/blob/9d25f6c1e40975f321786d9b70502b4d74421707/Sources/AudioKit/Sequencing/Apple%20Sequencer/AppleSequencer.swift#L354

The `capacity` parameter of `bindMemory(to:capacity:)` means 

> The amount of memory to bind to type T, counted as instances of T.

Not the size in bytes.

https://developer.apple.com/documentation/swift/unsafemutablerawpointer/2428061-bindmemory

---

Also the use of `assumingMemoryBound(to:..)` is also not technically safe. 

> Accessing memory through the returned pointer is undefined if the memory has not been bound to T.

https://developer.apple.com/documentation/swift/unsafemutablerawpointer/2428188-assumingmemorybound

https://github.com/AudioKit/AudioKit/blob/9d25f6c1e40975f321786d9b70502b4d74421707/Sources/AudioKit/Sequencing/Apple%20Sequencer/AppleSequencer.swift#L261

https://github.com/AudioKit/AudioKit/blob/9d25f6c1e40975f321786d9b70502b4d74421707/Sources/AudioKit/Sequencing/Apple%20Sequencer/AppleSequencer.swift#L445

---

A better way to parse things like MIDIMetaEvent is

```swift
// bind the pointer to a MIDIMetaEvent
let eventPointer = pointer.bindMemory(to: MIDIMetaEvent.self, capacity: 1)
// get the `data` field offset
let offset = MemoryLayout<MIDIMetaEvent>.offset(of: \.data)!
// get the data payload size
let dataLength = Int(eventPointer.pointee.dataLength)
// bind the data pointer
let dataPointer = pointer.advanced(by: offset).bindMemory(to: UInt8.self, capacity: dataLength)
// use the data pointer, e.g. create a `Data`
let eventPayload = Data(buffer: UnsafeBufferPointer(start: dataPointer, count: dataLength))
```

**Comment by aure** [comment]
I'd really welcome a pull request from you to fix the points this issue raises.

**Comment by YuAo** [comment]
Sorry, pretty busy recently. Maybe I can get around to this next week.
