### ISSUE TITLE
AudioPlayer play() & pause() not behaving as expected

### ISSUE THREAD

**Issue by kxmmeron** [AudioKit/AudioKit#2646]
**Describe the bug**
When using play() and pause() for toggle playback functionality (where play() is called if the audio is paused and pause() is called if audio is playing), calling pause() during the second toggle cycle does not pause the audio and the UI becomes out of sync.

**To Reproduce**
1. Create an instance of AudioPlayer
2. Load an audio file
3. Call AudioPlayer.play() to start audio
4. Call AudioPlayer.pause() to pause audio
5. Repeat step 3-4
6. See that audio isn't paused on second cycle and UI reports inaccurately

**Expected behavior**
I expect that calling pause() after play() would always stop the audio.  Not too sure but seems that it could be some sort of state issue.  I noticed that both `isPlaying` and `!isPaused` in `AudioPlayer+Playback.swift` Line 56 are false causing the function to return when this issue is encountered even though audio is playing.

There seems to be a workaround for this: calling play() right before pause() seems to give the behavior that I am looking for but doesn't seem natural to me.

**Details (please complete the following information):**
 - Type: macOS, iOS
 - OS: macOS Monterey 12.1, iOS 15.2
 - AudioKit 5.3

**Additional context**
It also seems that `getCurrentTime()` is still increasing after pausing audio as well.

### Commit demonstrating issue in Cookbook: https://github.com/kxmmeron/Cookbook/commit/3523f9063e0559571389c1d20199ac82c8737e3a

Use `Enable Workaround` toggle to see behavior before and after workaround (calling play() right before calling pause())

**Comment by emurray2** [comment]
I believe `getCurrentTime()` was mentioned in #2620 as a feature, but it seems like enough people are expecting it to return a finite time. I'll open up another PR for that soon.

**Comment by kxmmeron** [comment]
Thanks for the quick fix Evan, I appreciate it!
