### ISSUE TITLE
engine must be running before playback.

### ISSUE THREAD

**Issue by artem-sherbachuk** [AudioKit/AudioKit#2649]
This works in the simulator but does not work on real device iOS 15, iPhone 11

```swift 
final class AudioEngine {

    private let engine = AudioKit.AudioEngine()

    let mixer: Mixer

    let player = AudioPlayer()

    init() {
        mixer = Mixer()
        mixer.addInput(player)
        engine.output = mixer

        do {
            try AudioKit.Settings.setSession(category:.playAndRecord,
                                             with: [.allowBluetoothA2DP,
                                                        .allowAirPlay])

            try engine.start()
        } catch let error {
            print("AudioEngine Error:\(error)")
        }
    }

    func playSound(url: URL) {
        do {
            try player.load(url: url)
        } catch let error {
            print(error)
        }

        player.isLooping = true
        player.play()
    }

    func stop() {
        player.stop()
    }
}

let audioEngine = AudioEngine()
let url = Bundle.main.url(forResource: "fan-default", withExtension: "mp3")!
audioEngine.playSound(url: URL)
```

on real device no sound and error message shown in console
`[general] AudioPlayer+Playback.swift:play(from:to:at:completionCallbackType:):33:🛑 Error: AudioPlayer's engine must be running before playback. (AudioPlayer+Playback.swift:play(from:to:at:completionCallbackType:):33)`

on a simulator, all works fine.

**To Reproduce**
1. install audio kit 5.3.0 
2. use this code snippet above
3. launch on iOS 15, iPhone 11

**Expected behavior**
Play Sound

**Comment by emurray2** [comment]
Seems to me like there are asynchronous threads. What are you running this in? For example, are you using Playgrounds, SwiftUI, UIKit, etc.? Also what version of Xcode?

**Comment by artem-sherbachuk** [comment]
this is called from the main thread from the view controller no async execution from my side. 
Xcode 13.2 
I fixed it by checking if the audio engine isStart from the play() function.  if false call start one more time right before audioplayer palay call.

**Comment by emurray2** [comment]
> this is called from the main thread from the view controller no async execution from my side. 
> Xcode 13.2 
> I fixed it by checking if the audio engine isStart from the play() function.  if false call start one more time right before audioplayer palay call.

Interesting, it must be a state-based behavior then. I'll try to write an XCTest for it tonight if there isn't already one and see if I can fix it.

**Comment by emurray2** [comment]
I'm having some trouble writing the tests. It's difficult to have both the AudioKit `AudioEngine` and the `AudioEngine` namespaces colliding in how the tests are set up. It's great to hear you fixed this in your own code--still a strange behavior to call `play()` twice though.

I'm curious, where do you run these three lines of code? 
```
let audioEngine = AudioEngine()
let url = Bundle.main.url(forResource: "fan-default", withExtension: "mp3")!
audioEngine.playSound(url: URL)
```
If I try running them all in one function, I don't hear sound (because I think the `audioEngine` gets deallocated before the function returns). However, if I allocate the engine above `viewDidLoad()` method and run those three lines in `viewDidLoad()`, everything works fine on my iPhone 7 running 15.0.1 Xcode 13.2.1. Possibly this was patched in that update--wish I could downgrade :(.

**Comment by emurray2** [comment]
I added a test case for this on my fork, trying to make my code example as close to yours as possible. See if you can test it on your iOS 15 device, and let me know if it does the same thing.

**Comment by artem-sherbachuk** [comment]
"I'm curious, where do you run these three lines of code?"
Using the AudioEngine object described above. 

```swift
class ViewController: UIViewController {

    let audioEngine = AudioEngine()

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func play(sender: UIButton) {
        let url = Bundle.main.url(forResource: "fan_default", withExtension: "mp3")!
        audioEngine.playSound(url: url)
    }

}
```
here is a demo project with a bug, run on a real device, in my case, it's iPhone 11 iOS 15.
https://github.com/artem-sherbachuk/Bug-AudioKit

**Comment by aure** [comment]
Don't tie your audio lifecycle to the UI lifecycle. You can't rely on the view controller code view to be called in any predictable way.

**Comment by emurray2** [comment]
> Don't tie your audio lifecycle to the UI lifecycle. You can't rely on the view controller code view to be called in any predictable way.

+1 to this. I've found Dependency Injection to be helpful in passing the Audio Engine to the view. This method also works with SwiftUI too.

https://cocoacasts.com/dependency-injection-in-swift
