### ISSUE TITLE
Analysis demo in AudioKitDemo broken

### ISSUE THREAD

**Issue by warpling** [audiokit/AudioKit#265]
I've tried the AudioKitDemo (both 2.3, and 2.2) on two different devices (iOS 9.1/9.2) but the Analysis demo seems messed up. Once selected navigation becomes unresponsive and while the graphs are live/updating the labels don't seem to ever change from 0/0/C.

**Comment by warpling** [comment]
It appears that the `AKEvent` setup in `viewDidAppear` for the `AnalysisViewController` never gets run on the devices I tested, but does run in the simulator.

**Comment by aure** [comment]
That's bad.  I'll make sure to test on actual devices, thanks for posting this.  I'll look into it.

**Comment by aure** [comment]
Just released a new version of AudioKit...

**Comment by warpling** [comment]
Awesome! I'll go check it out :)

~Ryan
