### ISSUE TITLE
AudioPlayer `isPaused` should be set to `false` when call `stop()`

### ISSUE THREAD

**Issue by yberdnikov** [AudioKit/AudioKit#2654]
Issue description:
- call AudioPlayer.start()
- call AudioPlayer.stop()
- call AudioPlayer.start() - there's an issue with `isPaused` property as it set to `true`, however, this is not correct as player is not paused.

Possible fix:
set `isPaused` to false when call AudioPlayer.stop()

**Comment by emurray2** [comment]
Have you tried out the `develop` branch? I made a commit the other day to start using enums instead of using booleans. Now you can use `AudioPlayer.status` to get what the audio player is doing. More info here: https://github.com/AudioKit/AudioKit/commit/3abfc568c286ebcad1eb2088ca6c0700c4e794f4

**Comment by aure** [comment]
I am pretty sure this is addressed in develop. Get back to us if its not good there.
