### ISSUE TITLE
NodeOutputView cannot share NodeRecorder input 

### ISSUE THREAD

**Issue by ViaJables** [AudioKit/AudioKit#2655]
I'm trying to record from the mic and show the waveform while it records but cannot find a way that the NodeOutputView can share the NodeRecorder. The work find separately but no combination of the two that I've found won't break the other.

I've tried the following:
Put the mic input into each
Put the mic input into a fader and pass the fader into the NodeOutputView
Put the mic input into a fader and pass it to both the NodeOutputView and the NodeRecorder
Add the recorder.node to the NodeOutputView

is this a bug or a misunderstanding of how to use this?

**Comment by aure** [comment]
Hard to answer this without detail, but I will respond that things like NodeOutputView and NodeRecorder rely on tapping the signal chain at a certain node. There can only be one tap per node, so if you need both of these things, tap one node, then add. a mixer that just has the node has input and then tap the mixer for the second one.
