### ISSUE TITLE
AudioKit 5.3.1 fails to compile on Xcode 12.4 / macOS 10.15.7

### ISSUE THREAD

**Issue by orchetect** [AudioKit/AudioKit#2656]
## Issue

- 5.3.1 fails to compile in Xcode 12.4 on macOS Catalina 10.15.7
- 5.3.1 compiles fine in Xcode 13 on macOS Monterey 12.1

Had to roll back to 5.3.0 which still compiles fine in Xcode 12.4

## Screenshots

It's just Xcode 12 being fussy about syntax.
It wants explicit keypath notation including the base type name (`.offset(by: \MIDIMetaEvent.data)`).

In UnsafeMIDIMetaEventPointer.swift:

![UnsafeMIDIMetaEventPointer](https://user-images.githubusercontent.com/11605557/150016446-3e7f9fa0-4f12-4397-afcf-b0fbe02e753a.png)

**Comment by orchetect** [comment]
I don't have time right this second to submit a PR so just wanted to log the issue here. But if it's still unresolved later today I might be able to get a fix in.

**Comment by orchetect** [comment]
@aure: On a related note, it wouldn't be hard to set up a Xcode 12.4 GitHub CI pipeline in parallel to the existing 13.1 one. Would be useful to catch these issues.

**Comment by aure** [comment]
Actually this bug is showing up when sending other AudioKIts like SoundpipeAudioKit through CI - I guess they are on the Xcode 12 version as well. A fix would be welcomed as I'm not sure I'll get a chance to look today.

**Comment by orchetect** [comment]
The first PR CI run seems to be freewheeling for some reason. Might want to manually cancel it manually: https://github.com/AudioKit/AudioKit/actions/runs/1714913244

**Comment by orchetect** [comment]
Merged: https://github.com/AudioKit/AudioKit/pull/2657

Tagged at 5.3.2
