### ISSUE TITLE
Sequencer tempo range clamped to 10 to 280?

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/AudioKit#2658]
I have need for 3bpm to about 1000bpm. Logic can do this quite easily for example. 
Is this a limitation of the Apple's music sequence (I couldn't find any reference to 280 being the max bpm).
I was wondering if the clamping be left to the user of the setTempo and other apis in AppleSequencer?

Thanks!
q

**Comment by NickCulbertson** [comment]
That's a pretty easy fix. I'll submit a pull request for it.

**Comment by quantamrhino** [comment]
How wonderful! Many thanks!!
