### ISSUE TITLE
Clicking in simple oscillator demo

### ISSUE THREAD

**Issue by sehugg** [audiokit/AudioKit#266]
Executing this code on iOS gives a 440 Hz tone, but there is periodic clicking (one or two clicks) every half-second or so.

(iOS 9.2.1 with AudioKit 2.3)

    AKInstrument* instrument;
    instrument = [AKInstrument instrument];
    [instrument setAudioOutput:[AKOscillator oscillator]];
    [AKOrchestra addInstrument:instrument];
    [instrument play];

**Comment by aure** [comment]
Working on a new release that will be available today or tomorrow.

**Comment by aure** [comment]
Brand new version, no clicking https://vimeo.com/152398360
