### ISSUE TITLE
Sequencer finds only one track in a multi-track MIDI file

### ISSUE THREAD

**Issue by matbouil** [AudioKit/AudioKit#2660]
Hi guys,

**Describe the bug**

I am trying to play a 11 tracks MIDI file using the AudioKit 5's Apple Sequencer.
However the sequencer seems to only find 1 track.

**Steps to reproduce**

Here is my code:
```
let sequencer = AppleSequencer(filename: "Tutu - 2 - Miles Davis")
print("Track count : \(sequencer.tracks.count)")
```

I obtain the same result when using the `MIDIFile` parser directly:
```
let filePath = Bundle.main.path(forResource: "Tutu - 2 - Miles Davis", ofType: "mid")!
let midiFile = MIDIFile(path: filePath)
print("Track count : \(midiFile.trackCount)")
```
Here is the midi file in question:
[Tutu - 2 - Miles Davis.mid.zip](https://github.com/AudioKit/AudioKit/files/7933091/Tutu.-.2.-.Miles.Davis.mid.zip)

**Expected behavior**

Obviously I would have expected to find 11 tracks in the sequencer instance.

Here is a screenshot of the tracks when the file is imported in Garageband:

![image](https://user-images.githubusercontent.com/225499/150965417-7dc2f67b-3935-4846-a018-56dfaa8a6ee5.png)

**Details :**
 - Type: Simulator iPhone 13
 - OS: iOS 15.0
 - AudioKit Version : 5.2.3

**Comment by NickCulbertson** [comment]
The problem appears to be with the midi file. I tried re-exporting it in Logic with the first bar removed and it seems to load as intended. Perhaps the initial track automation is throwing something off. 
[TestTutu.mid.zip](https://github.com/AudioKit/AudioKit/files/7933441/TestTutu.mid.zip)

**Comment by aure** [comment]
It really is doubtful this is an AudioKit problem since our wrapper around the Apple core code for Apple Sequencer is very thin.
