### ISSUE TITLE
AudioKit engine stops occasionally when loading an AVPlayer elsewhere

### ISSUE THREAD

**Issue by ViaJables** [AudioKit/AudioKit#2662]
In my app I have AudioKit playing local audio, then I stream remote audio using AVPlayer. 
Not every time but a lot of the time the engine will stop.

Details:
It stops when readyToPlay KVO is sent
Doesn't matter if I make a new AVPlayer or if I use AVPlayer.replaceCurrentItem
The player call to play does not need to be called to stop the engine.

**Comment by ryango** [comment]
(Disclaimer, not affiliated with AudioKit) It would be helpful if you could create a simple project that demonstrates the issue. I would also check [audio session interruptions](https://developer.apple.com/documentation/avfaudio/avaudiosession/responding_to_audio_session_interruptions) to see if AVPlayer itself interrupts the audio
