### ISSUE TITLE
CallbackInstrument causing extremely high CPU use (c. 150%) on init (iOS 15.2, AudioKit 5.3)

### ISSUE THREAD

**Issue by anytwopoints** [AudioKit/AudioKit#2664]
The below conductor class initialised in an iOS app reproduces the problem for me, both on actual hardware and on the simulator.

MIDICallbackInstruments and other Node types don't produce the problem.

The issue doesn't occur if the project is built with AudioKit 5.1

```
class Conductor {

    static let sharedInstance = Conductor()
    
    let audioEngine = AudioEngine()
    var callbackInstrument : CallbackInstrument
      
    init() {
        callbackInstrument = CallbackInstrument(midiCallback: { (_,_,_) in
            print("This is a callback")
        })
        audioEngine.output = callbackInstrument
    }
}
```

**Comment by NickCulbertson** [comment]
Does it look like this same issue? #2632

Try the Develop branch and see if you are getting the same result.

**Comment by anytwopoints** [comment]
Looks like it is the same issue- switching to develop has fixed it.
