### ISSUE TITLE
Typo: wrong enum case used. 

### ISSUE THREAD

**Issue by Truba** [AudioKit/AudioKit#2669]
https://github.com/AudioKit/AudioKit/blob/42ef2da5281768fbe43bfaa9b108b69d34a4a5f0/Sources/AudioKit/Nodes/Effects/Reverb.swift#L65
It should be:
`.largeRoom, .mediumHall, .largeHall,`

`largeHall` is currently mentioned twice :)

**Comment by aure** [comment]
Thanks!
