### ISSUE TITLE
Get waveform mid/low/high by its self

### ISSUE THREAD

**Issue by tegab** [AudioKit/AudioKit#2670]
How to get high, mid, low waveform by its self?

**Comment by ryango** [comment]
(Disclaimer, not affiliated with AudioKit) This probably belongs on StackOverflow with the AudioKit tag

You can follow [this guide](https://audiokitpro.com/audiovisualizertutorial/) to creating a visualizer and either sum buckets if that's what you're talking about

Alternatively you could use a band pass filter for each of the regions you're looking for and check amplitude of the output of each of those filters
