### ISSUE TITLE
Equivalent of   AudioPlayer.isPlaying()

### ISSUE THREAD

**Issue by vittalk** [AudioKit/AudioKit#2671]
can you please let me know the equivalent function/code to check whether my AudioPlayer is still playing. Currently I have audioPlayer.isPlaying(). But this doesn't compile anymore because this flag has been removed in the latest.
Please let me know the alternative option.

thanks, 
-Vittal

**Comment by NickCulbertson** [comment]
Try isStarted. (I answered on StackOverflow too.)
