### ISSUE TITLE
Bug Fix and Refactor Proposal: Midi note on/off + Time Stamps (Ableton Midi into tracks bug)

### ISSUE THREAD

**Issue by Matt54** [AudioKit/AudioKit#2676]
**Screenshot / Describe the bug**
![image (2)](https://user-images.githubusercontent.com/15333030/154376943-843ca885-6d7f-4cdd-9a07-cdd3110d5662.png)

I'll start with the solution and work backwards - if you send midi note on/off with an appropriate timestamp included, then Ableton will always forward the messages to the tracks.

(What I say below applies to both note on and note off - I will just refer to note on)
We have two main methods in AudioKit for sending note on:
- MIDI.sendNoteOnMessage
- MIDI.sendNoteOnMessageWithTime

The sendNoteOnMessage method calls sendMessage
The sendNoteOnMessageWithTime calls sendMessageWithTime

I cannot tell the difference between sendMessage and sendMessageWithTime at a glance (they appear a little different in implementation), so I could be wrong with what I'm about to suggest.

My suggested changes:
1) Refactor sendNoteOnMessage and sendNoteOnMessageWithTime into one method and refactor sendMessage and sendMessageWithTime into one method.

Reason:
It's safe to assume users of AK will always use sendNoteOnMessage as their first choice (I mean why include the time if you aren't keeping time of anything?? - just want to send a midi note NOW. Well apparently, that's not good enough...)

2) Document somewhere that a timeStamp is needed to avoid possible bugs with the way a DAW handles a midi event. 

AND/OR

Determine how to create a timeStamp when we are "self generating a midi note" as opposed to just getting it from a keyboard and forwarding it to the DAW (this is my current use case). If you are "self generating a midi note", where you don't actually have a timeStamp, then you will find that just sending 0 or MIDITimeStamp() will not work. If no timeStamp is included in the refactored sendNoteOn method, then we will add this "self generated timeStamp" as the default.

**To Reproduce**
This is a difficult to reproduce issue. It does not consistently occur, but as far as I can tell it tends to occur after Ableton has been open on your computer for a long time or your have not restarted your computer for a long time.

**Expected behavior**
Midi notes should always be forwarded to Ableton tracks (assuming appropriate preferences and I/O setup)

**Comment by orchetect** [comment]
As per Apple docs, timeTag must not be 0 when a packet is sent with `MIDIReceived()`. It must be a proper timeTag, which would be passing in `mach_absolute_time()` for the timetag. Some software and hardware will not respond to messages if you pass in 0.

Using `MIDISend()` is a bit different, that’s where passing 0 is allowed. It schedules packets if the timetag is in the future. If timetag is <= now it just sends the same as passing 0, so passing `mach_absolute_time()` into it is also safe.
