### ISSUE TITLE
Calling `AudioPlayer#seek` fires completionHandler

### ISSUE THREAD

**Issue by osheroff** [AudioKit/AudioKit#2683]
After upgrading to AudioKit from 5.2.2 to 5.3.3, when I call `AudioPlayer#seek()` it fires the `completionHandler` method.  Is this an intentional change?  In previous versions the completionHandler was only called when the end of the track was reached naturally.

**Comment by osheroff** [comment]
specifically this PR https://github.com/AudioKit/AudioKit/pull/2652/files removes the guard that prevents the completion handler from firing in a seek.  Doesn't look super intentionally removed, LMK if you want a PR to put back the seek-suppression-guard

**Comment by aure** [comment]
Go for it, thanks in advance.

**Comment by emurray2** [comment]
> specifically this PR https://github.com/AudioKit/AudioKit/pull/2652/files removes the guard that prevents the completion handler from firing in a seek.  Doesn't look super intentionally removed, LMK if you want a PR to put back the seek-suppression-guard

Yes, that I may have not intentionally removed. What I was trying to get rid of were a bunch of booleans to keep track of states. I switched to enums instead so the player sometimes only has one state (i.e. it can't be paused and playing at the same time).

Feel free to experiment with the code and add it back in somehow if you like.
