### ISSUE TITLE
loadEXS24(url: URL) optimization

### ISSUE THREAD

**Issue by NickCulbertson** [AudioKit/AudioKit#2690]
In AppleSampler using the new: `public func loadEXS24(url: URL) throws {
        try samplerUnit.loadInstrument(at: url)
 }` bypasses the `findFileURL` method that helps in finding a file in the main bundle from a string.

I like AppleSampler's `try loadInstrument(file, type: "exs")` method for that reason. If the desire is to simplify the number of methods maybe "loadInstrument" could become a public function, then the user can pass any type they like.

**Comment by aure** [comment]
I am thinking of deprecating all of that wishy washy findFile stuff.  I think the user could be relied on to supply the URL don't you?

**Comment by NickCulbertson** [comment]
That could work. It kind of changes the calls from being like this:

`try instrument.loadEXS24("Sounds/Sampler Instruments/sawPiano1")`

to this:

`try instrument.loadEXS24(url: Bundle.main.url(forResource: "Sounds/Sampler Instruments/sawPiano1", withExtension: "exs")!)`

**Comment by aure** [comment]
More importantly, it puts the handling of an unfound file squarely in the responsibility of the app maker, not framework maker. They also can handle what happens when the file is not available.

**Comment by NickCulbertson** [comment]
That makes sense and it's more in line with the underlying AVAudioUnitSampler methods. 

Should the deprecation message point to AppleSampler's `loadInstrument(url: URL)`? It is the same as the new `loadEXS24(url: URL)` but it includes the line `samplerUnit.reset()` and both method can be used to load multiple instrument file types.

**Comment by NickCulbertson** [comment]
This is how I would load an instrument after the deprecation:

```
do {
            if let fileURL = Bundle.main.url(forResource: "Sounds/Sampler Instruments/sawPiano1", withExtension: "exs") {
                try instrument.loadInstrument(url: fileURL)
            }else{
                Log("Could not find file")
            }
        } catch {
            Log("Could not load instrument")
        }
```

**Comment by aure** [comment]
That looks right to me. What's the point of this issue?

**Comment by NickCulbertson** [comment]
Great, thanks! I'll close the issue. `loadInstrument(url: URL)` and `loadEXS24(url: URL)` are the same method but other than that it all looks good.
