### ISSUE TITLE
AudioPlayer.getCurrentTime() does not seem to compensate for whenTime

### ISSUE THREAD

**Issue by ShowtimeSoft** [AudioKit/AudioKit#2691]
**Describe the bug**
It seems that getCurrentTime() does not compensate for the at:whenTime parameter.

**To Reproduce**
First:
Set whenTime to +2 seconds:
whenTime = AVAudioTime.now() + 2

Then play:
audioPlayer.play(from: playbackStartTime, to: playbackEndTime, at: whenTime)

The getCurrentTime() is now offset by 2 seconds.

**Expected behavior**
I would expect getCurrentTime() to report the actual time position within the audiofile

**Details (please complete the following information):**
 - Type: Mac
 - OS: macOS 12.2
 - AudioKit Version 5.3.2 and latest develop branch

**Comment by emurray2** [comment]
Hmm, seems related to the failing test in #2692. I'll take a look at it this week.

**Comment by ShowtimeSoft** [comment]
Hi,
Any news here, something I can do to help?

Thanks

**Comment by emurray2** [comment]
Hi, my apologies -- I completely forgot.

I know the player's time is based off this:
[https://developer.apple.com/documentation/avfaudio/avaudioplayernode/1390449-playertime](https://developer.apple.com/documentation/avfaudio/avaudioplayernode/1390449-playertime)

which is set whenever `getCurrentTime()` is called.

What I don't know is if this `playerTime` returns the actual position of the playhead **or** the time since the node has been playing. If the second case is true, the behavior you expected will never be observed since `playerTime` is always set to `0.0`, regardless of the position of the player when it starts.

Does that make sense, and is it what you observe to happen? Please let me know. Thanks.

**Comment by emurray2** [comment]
I'm also going to open this up for anyone else to look at, as I have final exams and projects coming up in school for the next 3 weeks.

**Comment by ShowtimeSoft** [comment]
Thanks,
Yeah, that is kind of what I see: it seems that the "when" time is not compensated for, so if I set the "when" time to 2 seconds, getCurrentTime() is off by 2 seconds.

I'm trying to do a multi-track player, and I need to set the "when" time because I'm starting an array of players.
If I don't set the when time to, say 30ms, the players are not started simultaneously and the timing between the tracks is unstable.

Perhaps an array of AudioPlayers is not at all the way to do a multi track player (?).

**Comment by emurray2** [comment]
> Thanks, Yeah, that is kind of what I see: it seems that the "when" time is not compensated for, so if I set the "when" time to 2 seconds, getCurrentTime() is off by 2 seconds.
> 
> I'm trying to do a multi-track player, and I need to set the "when" time because I'm starting an array of players. If I don't set the when time to, say 30ms, the players are not started simultaneously and the timing between the tracks is unstable.
> 
> Perhaps an array of AudioPlayers is not at all the way to do a multi track player (?).

I see, I'd like to play around with the AVFoundation API a bit when I get a chance to understand the `playerTime()` function. It may need to be set during seek or when the play head location is changed with that "when" parameter.

As I mentioned, these last three weeks are a bit chaotic for me with finals, but if you're able to figure it out before me, I invite you to by all means.

As far as multi-track players go, arrays are one way to build one. Another way would be to sum the audio from each of the tracks into one track and play it.

**Comment by ShowtimeSoft** [comment]
Thanks!

I'll be patient and see what you find out. I'm afraid it's a bit over my head :-)

**Comment by emurray2** [comment]
> Thanks!
> 
> I'll be patient and see what you find out. I'm afraid it's a bit over my head :-)
> 

You're welcome, I'm happy to help 🙂! Some of it is still over my head as well to be honest.

**Comment by emurray2** [comment]
My apologies this took me so long. School is finally over, so I had a look at it. Please let me know if these changes make it work for you :) !
