### ISSUE TITLE
MIDIFile parsing returns a wrong number of tracks

### ISSUE THREAD

**Issue by matbouil** [AudioKit/AudioKit#2698]
Hi,

First of all, thanks for this great AudioKit framework !

**Describe the bug**
When parsing the following midi file using the `MIDIFile` class, it returns only three tracks whereas there are actually four : 
[file_example_TEST.midi.zip](https://github.com/AudioKit/AudioKit/files/8464328/file_example_TEST.midi.zip)

However the four tracks are properly read by the `AVAudioSequencer` (as well as in GarageBand or Musescore apps).

**To Reproduce**

Run the following code:
```
let midiFile = MIDIFile(path: "file_example_TEST.midi")
print("Track count = \(midiFile.tracks.count)")
```

**Expected behavior**
Only three tracks are extracted by the `MIDIFile` parser.

**Details**
 - Type: iOS Simulator 15.0
 - OS: iOS 14, iOS 15.3
 - AudioKit Version : 5.1.0

**Comment by NickCulbertson** [comment]
Try counting with `Log("Track count = \(midiFile.trackCount)")`

The tracks method drops the first midi track as it presumes that one to be a tempo track. This is the tracks method in the MIDIFile class:

` /// Array of MIDI File tracks
    public var tracks: [MIDIFileTrack] {
        var tracks = trackChunks
        if format == 1 {
            tracks = Array(tracks.dropFirst()) // drop tempo track
        }
        return tracks.compactMap({ MIDIFileTrack(chunk: $0) })
}`

**Comment by emurray2** [comment]
> Try counting with `Log("Track count = \(midiFile.trackCount)")`
> 
> 
> 
> The tracks variable drops the first midi track as it presumes that one to be a tempo track. This is the tracks variable in the MIDIFile class:
> 
> 
> 
> ```
> 
> /// Array of MIDI File tracks
> 
> public var tracks: [MIDIFileTrack] {
> 
>         var tracks = trackChunks
> 
>         if format == 1 {
> 
>             tracks = Array(tracks.dropFirst()) // drop tempo track
> 
>         }
> 
>         return tracks.compactMap({ MIDIFileTrack(chunk: $0) })
> 
> }
> 
> ```

Yes, as Nick said, one of the tracks is sometimes a tempo track. Note this isn't always the case. There are different types of MIDI files described by the 1.1 specs (i.e. type 0 and type 1).

MIDI is one of those parts of AudioKit which is tricky because we need to be able to handle lots of unique file types, even though all of them probably have the `.mid` extension. This is because each of the files has a different data layout according to its type.

I have 3 weeks left of school, but I'm going to try and jump back into the MIDI code this summer. However, if you're able to come up with improvements, anyone is welcome to contribute to AudioKit 🙂!

**Comment by matbouil** [comment]
Thanks @NickCulbertson and @emurray2 

It appears that the tempo track for this MIDI File also contains Channel MIDI events, which make it a tempo track but also an "instrument" track at the same time (which should not be dropped).

I finally implemented a method to identify pure tempo tracks:
```
private extension MIDIFileTempoTrack {
    // Sometimes a tempo track is also used as an "instrument" track (ie: it contains channel midi events, notes, ...)
    // This function checks if the tempo track is a pure tempo track
    var isPureTempoTrack: Bool {
        return track.channelEvents.isEmpty
    }
}
```
