### ISSUE TITLE
No effect on audio player instance when using seek(time: TimeInterval)

### ISSUE THREAD

**Issue by aPeddi** [AudioKit/AudioKit#2707]
Hi, I've been working with AudioKit for a few months now primarily to apply reverb and time-pitch effects to an audio player instance. 
I'm routing the audio which is loaded in a buffer into a reverb mixer and then applying a time pitch effect which is then being fed into to the engine output:

		reverb = CostelloReverb(audioPlayerInstance)
		reverbMixer = DryWetMixer(audioPlayerInstance, reverb!)
		reverbMixer.balance = 20		
		timePitch = TimePitch(reverbMixer)
		engine.output = timePitch

		//start engine
               audioPlayerInstance.play()

 Everything works fine but when i try to use the seek function 'seek(time: TimeInterval)' to change the main audio position:

		print(audioPlayerInstance.getCurrentTime) // 4

		audioPlayerInstance.seek(to: 85)

		print(audioPlayerInstance.getCurrentTime) // 89
		print(audioPlayerInstance.duration) // 165

 the player's currentTime property gets updated as I change play position but the track either plays from the beginning or just stays where it's at (I've experienced both).

Things I've tried to find a workaround as of yet:
1) Calling the seek method on a background and main queue asynchronously.
2) seeking a track using play(from:, to:, when:) method
3) stopping and pausing track before seeking and then playing it after

I'd appreciate any suggestions or changes you can think of to make it work.

Thanks in advance :)

**Comment by emurray2** [comment]
Interesting, the player is getting a bit of a revamp right now. I'll take a look at this and get back to you ASAP.

**Comment by emurray2** [comment]
Which version of AudioKit did this occur with? I've tested with the current `main` branch and can't seem to reproduce this issue.

**Comment by emurray2** [comment]
I believe this issue pertains to #2683 which was fixed in #2685

**Comment by aPeddi** [comment]
Thanks for the update. Will try it out from the main branch and post my findings in here.

**Comment by aPeddi** [comment]
> Which version of AudioKit did this occur with? I've tested with the current `main` branch and can't seem to reproduce this issue.

Btw I was using AudioKit 5.4 through SPM

**Comment by emurray2** [comment]
> Thanks for the update. Will try it out from the main branch and post my findings in here.

You're welcome 😊! Looking forward to hearing about your findings 😃!

**Comment by emurray2** [comment]
> > Which version of AudioKit did this occur with? I've tested with the current `main` branch and can't seem to reproduce this issue.
> 
> Btw I was using AudioKit 5.4 through SPM

That's good to know. Strange since I believe the bug I was referring to a couple messages ago was patched before this release. I'm confident we'll get to the bottom of this though 👌🏻!

**Comment by emurray2** [comment]
Also, when I did this with buffering, it did work, but I noticed a couple of problems you may notice too.

1. The slider is really slow. My guess is this is due to the `updateBuffer()` function being so slow when its in a callback (such as a slider value changing).
2.  If you put the slider to the very end, it will keep looping that section of the file without going back to the beginning of the file.

Issue 1 is fixable for now by switching to files if possible. Files don't use the `updateBuffer()` function, but buffers do. So using only files will be much faster. Issue 2 is in the works. As I mentioned, the player is still getting a revamp, so I'm open to any other suggestions you may have. Thanks for sharing this example too, I love the music!

**Comment by aPeddi** [comment]
That actually worked like a charm! (using files instead). Really thanks for the tip, had spent a few days trying to figure this out. 
Since you've mentioned that updating buffer is a bit slow I tried loading the sample with:
                  player.load(file: playerFile, buffered: false) 
and i'm not experiencing any latency when seeking now.

Appreciate the support :)
