### ISSUE TITLE
MIDI Sysex message size problem

### ISSUE THREAD

**Issue by kenypp** [AudioKit/AudioKit#2711]

**Comment by kenypp** [comment]
I noticed after updating to 5.4 that my longer sysex messages in my IOS app would cause a crash. I was able to workaround by cutting the message size in half from the previous version. The message size that worked in earlier versions but now causes crash is 269 bytes including header and tail byte. Possibly max size is now one page?

**Comment by aure** [comment]
I can't really act on this without any context. But, it seems like you'd be in the perfect position to fix it if your app works with one version and not with another.

**Comment by kenypp** [comment]
I will look at it, thanks
