### ISSUE TITLE
Ramping mastervolume

### ISSUE THREAD

**Issue by andreiantonescu** [AudioKit/AudioKit#2724]
**Describe the bug**
I have a sequencer based on sampled sounds. The samples are around 1-2 secs long, but the sequencer can play them faster, meaning it stops the sample before it gets to the end. 

When it does so, there’s a “click/tick” sound and I’m trying to prevent this by ramping the volume down before actually stopping the node.

I've managed to reproduce this with the Synth as well, for simplicity.

**To Reproduce**
See example code here:
```
    let akEngine = AudioEngine()
    let osc = Synth()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        akEngine.output = osc
        do {
            try akEngine.start()
        } catch {
            print("Couldn't start AudioEngine.")
        }
        
        osc.play(noteNumber: 50, velocity: 100)
        osc.$masterVolume.ramp(to: 0, duration: 1)
        sleep(2)
        osc.stop()
    }
```

**Expected behavior**
I would have expected the note to stop playing before the sleep call finishes, thus ending via the ramp, not abruptly via the stop call.

**Details (please complete the following information):**
 - Type: Simulator iPhone 13 Pro
 - OS: iOS 15.5
 - AudioKit Version 5.4.2

**Additional context**
[verySimpleRampTest2.zip](https://github.com/AudioKit/AudioKit/files/8757888/verySimpleRampTest2.zip)

Sample project attached.

**Comment by aure** [comment]
THere is no synth in AudioKit, so this is the wrong place for this issue. DunneAudioKit would be the place.
