### ISSUE TITLE
 Playing a clip does not start if one already playing

### ISSUE THREAD

**Issue by emurray2** [AudioKit/AudioKit#2725]
Reopening in AudioKit/AudioKit since this is an issue with `AudioPlayer` and not Cookbook
Original ticket: AudioKit/Cookbook#97

**Comment by emurray2** [comment]
Hi @roboldham,

Can you test your example with AudioKit `main` branch and let me know if the new changes work. Thanks.

**Comment by roboldham** [comment]
It does indeed! Yay... across all apps using AudioPlayer , .status() also reporting correctly in all cases

Thanks very much!
