### ISSUE TITLE
AudioKitEx Sequencer not playing first note, issues adding notes while playing

### ISSUE THREAD

**Issue by kenwheeler** [AudioKit/AudioKit#2727]
**Describe the bug**
I'm witnessing two issues with the Sequencer.

1. When I have two tracks, and add a note at 0.0 for each:
```
conductor.sequencer.tracks[selected].sequence.add(noteNumber: 60, position: Double((index)) * 0.25, duration: 1.0)
```
I'm seeing that the first note of the second track isn't played. All subsequent notes play alright. 

2. When adding notes programmatically using the same API above, _while the sequencer is playing_, I'm hearing offset note timings. If I stop the sequencer and restart it, the timing is correct.

**To Reproduce**
1. Add two notes programmatically using the above API at the 0.0 position and play with looping enabled
2. For the other issue, use the same API as above to add notes programmatically while the sequencer is playing

**Expected behavior**
I would expect a) two tracks, each with a note at 0.0 position to be able to play simultaneously. and b) I would expect notes added when the sequencer is playing to be time accurate in the current play context.

**Screenshots**

**Details (please complete the following information):**
 - Type: [e.g. iPhone6, iPad, Mac] iPhone 13 pro
 - OS: [e.g. iOS13.1] iOS 15.4.1
 - AudioKit Version [e.g. 5.0] 5.3.3, 
**Other Context**
I'm using samplers.

p.s. Thanks so much, this project rules

**Comment by kenwheeler** [comment]
Just an update on this, seems like the first issue is some weird note on/note off handling when using Sequencer with AppleSampler. I was able to work around by using callback instruments to trigger .play on them. The second issue, with timing of added notes while the sequencer is running remains.

**Comment by kenwheeler** [comment]
Timing still seems slightly slightly weird here and there, but it appears that setting .loopingEnabled after adding each note makes the timing offset go away

**Comment by emurray2** [comment]
I've opened this in AudioKit/AudioKitEX to help keep track of things
