### ISSUE TITLE
BaseTap crash: length <= _imp->_frameCapacity

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/AudioKit#2729]
Crash in BaseTap in rare cases, line 91.

 *** required condition is false: length <= _imp->_frameCapacity
CoreFoundation __exceptionPreprocess 
AVFAudio -[AVAudioPCMBuffer setFrameLength:] 
BaseTap.handleTapBlock(buffer:at:) + 91 

line 91 is the dispatch async call, but I think it's here: buffer.frameLength = bufferSize 

Not much more in the stack trace either :-( 
This happens 1/1000 times, and in the wild. I have no idea how to reproduce this crash.

on iphone 11, ios 15.4.1

**Comment by aure** [comment]
A bit hard to act on this.
