### ISSUE TITLE
Deadlock starting BaseTap after stopping it.

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/AudioKit#2730]
With the latest BaseTap fix (on the main branch) (the handler is no longer called on the main queue), 
doing a start() tap after it was stopped leads to a deadlock. 
The tap in question is the AmplitudeTap. 
Starting/stopping the tap from the main queue seems to solve this. Is this the right 'fix' for this problem?

**Comment by emurray2** [comment]
Yes, stopping things from a background queue (specifically a serial queue in a handler) generally leads to deadlocks because the background queue is busy processing data. You can use the main queue or run the code asynchronously on another queue.

**Comment by jcavar** [comment]
Hey @quantamrhino. Can you share a bit more context:
- Are you starting and stopping from the same background queue?
- What kind of queue is it?
- Do you have a stack trace? What is waiting on what?

**Comment by aure** [comment]
Waiting on more info, reopen when/if that comes in.
