### ISSUE TITLE
InputNode -> DynamicsProcessor is silent on iOS16, works fine on 14.x and 15.x

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/AudioKit#2747]
Rather odd things I observed:
I have a mic (Input node) -> Mixer -> DynamicsProcessor -> Fader(gain 0) -> Mixer -> main mixer node.
On ios 15 and earlier, this setup works great and I can record output of mic well.
On ios16, this returns silence. If I remove the dynamics node from the chain, things work again (raw mic sound is not silent). But having the dynamics node in the chain and bypassing (or starting) doesn't work and still returns silence. 
I have other dynamics nodes connected downstream of things like AppleSampler and that works (sound is coming). when mic is connected, there's no sound on ios 16+.

Also, If I add nodes like high pass filter, low pass filter, reverb etc under the dynamics processor, things are silent. if I take the dynamics node out, the remaining node chain works fine. So it's just dynamics processor that seems to not be happy with mic perhaps?

Oh and another curiosity -- If I substitute Compressor for DynamicsProcessor, it works! but under the covers both are using kAudioUnitSubType_DynamicsProcessor.. so it is likely not an apple bug then?

**Comment by quantamrhino** [comment]
It's values of expansionRatio > 1.0 that cause the dynamics processor to be silenced. compressor has this at 1 default likely.
Weird, no? 
Can someone also explain why dynamics processor and compressor are different objects? is this a convenience things, or something else? And what difference expansion ratio and threshold make on the sound? All very confusing stuff for me. 😬

**Comment by quantamrhino** [comment]
It also works if the value of expansionRatio is set before connecting to the mixer. if changed later, it causes it to be silenced.

**Comment by aure** [comment]
More than likely an Apple bug since it is such a light wrapper to their stuff. You're right that Compressor exists as a convenience.
