### ISSUE TITLE
toFloatChannelData seems to return the wrong file length

### ISSUE THREAD

**Issue by wtholliday** [AudioKit/AudioKit#2748]
To reproduce run `testFileLength` in the `file-length-bug` branch (in `AVAudioPCMBufferTests.swift`).

The test file I'm using is 32768 samples long according to Audacity and AVAudioFile.

When I call toFloatChannelData, I get 32748 samples.

```Swift
    func testFileLength() {
        let path = Bundle.module.url(forResource: "TestResources/SIN_0045_0", withExtension: "wav")

        let file = try! AVAudioFile(forReading: path!)

        let samples = file.toFloatChannelData()!

        XCTAssertEqual(Int(file.length), samples[0].count)
    }
```

**Comment by JP-Lisn** [comment]
This appears only to be an issue with the `SIN_0045_0` test resource. When using `12345` or `PinkNoise` this test passes.

**Comment by JP-Lisn** [comment]
Seems that this file is somehow corrupted. Re-encoding the file appears to resolve the issue though: 
`ffmpeg -i SIN_0045_0.wav -c:a copy SIN_0045_2.wav`

**Comment by aure** [comment]
@JP-Lisn If the file is corruped could you make a pull request with the new file and then we can close this issue?

**Comment by agilecollab** [comment]
No prob, https://github.com/AudioKit/AudioKit/pull/2767

**Comment by JP-Lisn** [comment]
No problem: https://github.com/AudioKit/AudioKit/pull/2768
