### ISSUE TITLE
How to generate AudioKit Node from faust dsp ?

### ISSUE THREAD

**Issue by theyoogle** [AudioKit/AudioKit#2756]
yes, there is already a program, faust2audiokit, but the produced code is outdated, gives lots of errors.

**Comment by aure** [comment]
We didn't create faust2audiokit, maybe check with the people who did.

**Comment by theyoogle** [comment]
Its working for monophonic node with audiokit 5.0.1

Now struggling, how to make it work for polyphonic node, and how to trigger something like keyOn, keyOff, pitchBend messages to dsp code.

`// Copyright AudioKit. All Rights Reserved. Revision History at http://github.com/AudioKit/AudioKit/
import AVFoundation
import CAudioKit
import AudioKit

/// Faust node
public class Faustguitar: Node, AudioUnitContainer, Toggleable {

	/// Unique four-letter identifier. If using multiple Faust generated nodes, make this unique for each
	public static let ComponentDescription = AudioComponentDescription(instrument: "Fdsp")

	/// Internal type of audio unit for this node
	public typealias AudioUnitType = InternalAU

	public private(set) var internalAU: AudioUnitType?

	// MARK: - Parameters

	// freq
	public static var letfreqDef = NodeParameterDef(identifier: "freq", name: "freq", address: akGetParameterAddress("guitar_freq"), range: 20 ... 20000, unit: .customUnit, flags: .default)

	@Parameter public var freq: AUValue

	// gain
	public static var letgainDef = NodeParameterDef(identifier: "gain", name: "gain", address: akGetParameterAddress("guitar_gain"), range: 0 ... 1, unit: .customUnit, flags: .default)

	@Parameter public var gain: AUValue

	// gate
	public static var letgateDef = NodeParameterDef(identifier: "gate", name: "gate", address: akGetParameterAddress("guitar_gate"), range: 0 ... 1, unit: .customUnit, flags: .default)

	@Parameter public var gate: AUValue

	// MARK: - Audio Unit
	public class InternalAU: AudioUnitBase {
		/// Get an array of the parameter definitions
		/// - Returns: Array of parameter definitions
		public override func getParameterDefs() -> [NodeParameterDef] {
			[Faustguitar.letfreqDef,
			Faustguitar.letgainDef,
			Faustguitar.letgateDef]
		}
		/// Create the DSP Refence for this node
		/// - Returns: DSP Reference
		public override func createDSP() -> DSPRef { akCreateDSP("Faustguitar") }
	}

	// MARK: - Initialization
	public init(_ input: Node? = nil, freq: AUValue = 440, gain: AUValue = 1, gate: AUValue = 1) {
		super.init(avAudioNode: input?.avAudioUnitOrNode ?? AVAudioNode())
		instantiateAudioUnit { avAudioUnit in
			self.avAudioUnit = avAudioUnit
			self.avAudioNode = avAudioUnit
			guard let audioUnit = avAudioUnit.auAudioUnit as? AudioUnitType else { fatalError("Couldn't create audio unit") }
			self.internalAU = audioUnit
			self.stop()
			self.freq = freq
			self.gain = gain
			self.gate = gate
		}
	}

}

`

Please Help !

**Comment by aure** [comment]
Is this in the open source somewhere?
