### ISSUE TITLE
AudioPlayer.play has no completion callback parameter

### ISSUE THREAD

**Issue by DrBilitski** [AudioKit/AudioKit#2759]
`player.play(from: <TimeInterval?>, to: <TimeInterval?>, at: <AVAudioTime?>, completionCallbackType: <AVAudioPlayerNodeCompletionCallbackType>)`

You can set the completion callback type but there is no parameter for passing in the handler itself.  How do we get called back?

**Comment by DrBilitski** [comment]
I assume the handler is set before hand with player.completionHandler=

**Comment by emurray2** [comment]
> I assume the handler is set before hand with player.completionHandler=

Yep, that's correct. There should be an example of it in the Cookbook.

**Comment by emurray2** [comment]
The parameter is also there so you can pass in the function straight away as a closure.

https://docs.swift.org/swift-book/LanguageGuide/Closures.html

**Comment by DrBilitski** [comment]
> 

In the cookbook, I saw a file AudioPlayerCompletionHandler.swift but I did not see anything referencing it.
