### ISSUE TITLE
Cannot find 'AKPitchShifter' in AudioKit v5.4.4

### ISSUE THREAD

**Issue by lsamaria** [AudioKit/AudioKit#2760]
I'm using `AudioKit v5.4.4` via Swift Package Manager. Has `AKPitchShifter` been renamed or removed?

![Screen Shot 2022-08-11 at 11 26 05 AM](https://user-images.githubusercontent.com/15787990/184170526-24dbb5f6-e98a-4b88-9f43-5c09fd50a70b.png)

**Comment by NickCulbertson** [comment]
It looks like it is called PitchShifter now and it lives in [SoundpipeAudioKit](https://github.com/AudioKit/SoundpipeAudioKit)

**Comment by NickCulbertson** [comment]
And there is an example of it being used in the [Cookbook](https://github.com/AudioKit/Cookbook).

**Comment by lsamaria** [comment]
@NickCulbertson Thanks for the reply.

I actually tried that after I saw the TimePitch had been renamed. I just tried it again and I still received the same error

```
import AudioKit

// ...
let pitchShifter = PitchShifter(player)
// ...
```

![Screen Shot 2022-08-11 at 12 07 13 PM](https://user-images.githubusercontent.com/15787990/184179451-8c46bd14-0d98-4afe-88b4-06df0025a834.png)

**Comment by NickCulbertson** [comment]
AudioKit 5 split all the different sections of AudioKit into different swift packages. You'll need to import the SoundpipeAudioKit swift package, then `import SoundpipeAudioKit` in your swift file. You might possibly need SporthAudioKit too if you are implementing like the Cookbook example.

**Comment by lsamaria** [comment]
@NickCulbertson Ok thanks.  I'm working on it now. I ran into an SSL Certificate bug via Swift Package Manager.

I'n googling the fix. I'll let you know the results when I'm done.

**Comment by aure** [comment]
Thanks @NickCulbertsonl but @lsamaria Read https://audiokit.io/documentation/audiokit/migrationguide
