### ISSUE TITLE
How to access AKFrequencyTracker

### ISSUE THREAD

**Issue by lsamaria** [AudioKit/AudioKit#2765]
AudioKit v5.4.4

How to access `AKFrequencyTracker`? I tried the code below but I got `Cannot find 'AKFrequencyTracker' in scope`:

```
import AudioKit

// ...

let frequencyTracker = AKFrequencyTracker()
```

I went to the [migration guide](https://audiokit.io/documentation/audiokit/migrationguide) and it appears that it hasn't been renamed to _FrequencyTracker_:

<img width="637" alt="Screen Shot 2022-08-17 at 11 04 21 PM" src="https://user-images.githubusercontent.com/15787990/185285761-13cede75-0b4f-43c3-842d-c9067c19a1d8.png">

I downloaded the cookbook to find some examples of AKFrequencyTracker in use but it couldn't find any results. I ran a global search for it (cmnd+4):

<img width="1050" alt="Screen Shot 2022-08-17 at 11 09 34 PM" src="https://user-images.githubusercontent.com/15787990/185285895-07048137-7776-46b8-bd60-66c795e65a99.png">

**Comment by aure** [comment]
https://audiokit.io/documentation/audiokit/migrationguide/

**Comment by lsamaria** [comment]
I checked there earlier, I just tried again, ran a search, and I only found 1 match to it:

<img width="1245" alt="Screen Shot 2022-08-17 at 11 37 23 PM" src="https://user-images.githubusercontent.com/15787990/185287863-182448c8-7692-49d9-851b-fba258f8fdaf.png">

**Comment by aure** [comment]
that mean it is gone.

**Comment by lsamaria** [comment]
Oh, ok. Is there anything to replace it?

**Comment by aure** [comment]
Can you just add issues to your project that I am subscribed instead of on AudioKit itself? You have to think out of the box. What else could frequency be called? Look for `pitchtap`

**Comment by lsamaria** [comment]
Ok. I will, thanks. Please close this

**Comment by maksutovic** [comment]
Yes, PitchTap which is in the SoundPipeAudioKit package, for whatever reason your documentation is missing the third column of notes, which instructs you to use PitchTap.

**Comment by lsamaria** [comment]
@maksutovic my window wasn't full screen so I didn't even see the 3rd column. Thanks for pointing that out. I found it.
