### ISSUE TITLE
AppleSequencer doesn't parse duration of MIDI Note event correctly

### ISSUE THREAD

**Issue by dburchik** [AudioKit/AudioKit#2769]
Hello, 

I use AppleSequencer to read & play harmonical MIDI file. The MIDI file contains first two notes with the same noteNumber and second note starts at the same position where the first note ends (look at the screenshot attached). In that case the first note is read with duration = 0.

<img width="1335" alt="Screenshot 2022-08-26 at 10 12 57" src="https://user-images.githubusercontent.com/1419186/186845141-1a48e56c-b577-4ef8-8fd8-77432c91517d.png">
[harmony.mid.zip](https://github.com/AudioKit/AudioKit/files/9430668/harmony.mid.zip)

I've printed the main fields of sequencer to the log

```
AppleSequencer(filename: "harmony")

allTempoEvents [(0.0, 89.9999550000225)]
allTimeSignatureEvents [(0.0, 4/4)]
---track--- 0
noteData ["time: 0.0, type: MIDINoteMessage, data: [n48 v77 c0 d0.0]", "time: 4.0, type: MIDINoteMessage, data: [n48 v78 c0 d4.0]", "time: 8.0, type: MIDINoteMessage, data: [n57 v76 c0 d4.0]", "time: 12.0, type: MIDINoteMessage, data: [n55 v89 c0 d4.0]"] 

eventData ["time: 0.0, type: Meta, data: [type: 3, data: 104]", "time: 0.0, type: Meta, data: [type: 4, data: 104]", "time: 0.0, type: Meta, data: [type: 89, data: 0]", "time: 0.0, type: MIDINoteMessage, data: [n48 v77 c0 d0.0]", "time: 0.0, type: Meta, data: [type: 3, data: 73]", "time: 4.0, type: MIDINoteMessage, data: [n48 v78 c0 d4.0]", "time: 8.0, type: MIDINoteMessage, data: [n57 v76 c0 d4.0]", "time: 12.0, type: MIDINoteMessage, data: [n55 v89 c0 d4.0]"] 

programChangeEvents [] 

getMIDINoteData ["n48 v77 c0 d0.0 p0.0", "n48 v78 c0 d4.0 p4.0", "n57 v76 c0 d4.0 p8.0", "n55 v89 c0 d4.0 p12.0"]```

**Comment by orchetect** [comment]
![midi-file-debug](https://user-images.githubusercontent.com/11605557/188034966-4f08d3ba-bbfe-44fb-9a90-aa3d01a3f2ec.png)

The second note-on happens before the first note's note-off. It may be tripping up the sequencer object.

What is the issue you're having?

**Comment by dburchik** [comment]
Hi @orchetect,

Thank you for you reply. Actually the exported MIDI is quantized (we use Logic). Shortening the note looks like a trick and is not convenient approach for musicians. There is a high possibility of human error.

If you open the file in Logic or in Garage Band you will find the notes and durations are correctly imported. 

For now I manually fix the duration once a file is loaded.

`    private func fixDuration() {
        tracks.compactMap { $0.internalMusicTrack }.forEach {
            fixDuration($0)
        }
    }
    
    private func fixDuration(_ track: MusicTrack) {
        var tempIterator: MusicEventIterator?
        NewMusicEventIterator(track, &tempIterator)
        guard let iterator = tempIterator else {
            Log("Unable to create iterator")
            return
        }
        
        NewMusicEventIterator(track, &tempIterator)
        guard let fixIterator = tempIterator else {
            Log("Unable to create iterator")
            return
        }

        var eventTime = MusicTimeStamp(0)
        var eventType = MusicEventType()
        var eventData: UnsafeRawPointer?
        var eventDataSize: UInt32 = 0
        var hasNextEvent: DarwinBoolean = false

        MusicEventIteratorHasCurrentEvent(iterator, &hasNextEvent)

        while hasNextEvent.boolValue {
            MusicEventIteratorGetEventInfo(iterator,
                                           &eventTime,
                                           &eventType,
                                           &eventData,
                                           &eventDataSize)
            
            if let type = EventType(rawValue: eventType),
               let eventData = eventData,
               var midiNoteMessage = type.midiNoteMessage(eventData) {
                
                if midiNoteMessage.duration == 0,
                    let nextMidiPosition = nextMidiNotePosition(iterator: fixIterator, anchorTime: eventTime) {
                    
                    let fixedDuration = nextMidiPosition - eventTime
                    midiNoteMessage.duration = Float32(fixedDuration)

                    MusicEventIteratorSetEventInfo(iterator, eventType, &midiNoteMessage)
                }
            }
            
            MusicEventIteratorNextEvent(iterator)
            MusicEventIteratorHasCurrentEvent(iterator, &hasNextEvent)
        }
        
        DisposeMusicEventIterator(iterator)
        DisposeMusicEventIterator(fixIterator)
    }
    
    private func nextMidiNotePosition(iterator: MusicEventIterator, anchorTime: MusicTimeStamp) -> MusicTimeStamp? {
        var eventTime = MusicTimeStamp(0)
        var eventType = MusicEventType()
        var eventData: UnsafeRawPointer?
        var eventDataSize: UInt32 = 0
        var hasNextEvent: DarwinBoolean = false

        MusicEventIteratorHasCurrentEvent(iterator, &hasNextEvent)

        while hasNextEvent.boolValue {
            MusicEventIteratorGetEventInfo(iterator,
                                           &eventTime,
                                           &eventType,
                                           &eventData,
                                           &eventDataSize)
            
            if eventTime > anchorTime,
               let type = EventType(rawValue: eventType),
               type == .midiNoteMessage {
                return eventTime
            }
                        
            MusicEventIteratorNextEvent(iterator)
            MusicEventIteratorHasCurrentEvent(iterator, &hasNextEvent)
        }
        
        return nil
    }`

**Comment by aure** [comment]
I think your fix is good enough for now until we revamp AudioKit's MIDI.
