### ISSUE TITLE
How to use MIDIClockListener and MIDIBeatObserver?

### ISSUE THREAD

**Issue by atchoo78** [AudioKit/AudioKit#2770]
I am asking this question here, since I can't find any information about it in the docs, and I [get no replies on Stackoverflow](https://stackoverflow.com/questions/73530788/how-to-observe-events-and-functions-from-midiclocklistener-and-midibeatobserver)

I am trying to use the MIDIBeatObserver/MIDIClockListener class in AudioKit 5, so I can sync MTC, realtime messages and Bars/Beats time code from Logic Pro to my app (Swift / Xcode 13.4.1).

However, I can't seem to find any information on this subject in the AudioKit documentation, except for the following (from the first comments section of the MidiClockListener.swift source file from AudioKit 5):

```swift
/// This class is used to count midi clock events and inform observers
/// every 24 pulses (1 quarter note)
///
/// If you wish to observer its events, then add your own MIDIBeatObserver
```

I would, if I only knew how. So my question is simply:

How do I proceed to "add my own MIDIBeatObserver", and how do I access the methods and functions from it? 

Thanks!

**Comment by aure** [comment]
We're going to be overhauling the MIDI with @orchetect 's https://github.com/orchetect/MIDIKit
