### ISSUE TITLE
Audiokit 5 - background MIDI note play delays

### ISSUE THREAD

**Issue by aectannctx** [AudioKit/AudioKit#2772]
### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 13.4.1

### Description

kAudioUnitErr_TooManyFramesToProcess error when app enters background with audio playing. 
Please help. I have absolutely no idea. Sound plays well when app is foreground, but when it enters background, sound immediately glitches and delays. 

    private let sequencer = AppleSequencer()
    private let metronome = MIDISampler(name: nil)
    private let engine = AudioEngine()
    private var metronomeTrack: MusicTrackManager

    init() {
        self.metronomeTrack = sequencer.newTrack()!

        try? metronome.loadWav("my_audio_wav_file")
        
        let mixer = Mixer(metronome)
        let fader = Fader(mixer, gain: 50.0) // регулировка звука
        
        self.updateSequences()
        self.engine.output = fader

         try? engine.start()
         sequencer.play()
     }

### Crash Logs, Screenshots or Other Attachments (if applicable)

2022-09-03 20:13:58.353958+0300 Metronome[72103:5358826] kAudioUnitErr_TooManyFramesToProcess : inFramesToProcess=3763, mMaxFramesPerSlice=1156

2022-09-03 20:13:59.377745+0300 Metronome[72103:5358826] kAudioUnitErr_TooManyFramesToProcess : inFramesToProcess=3763, mMaxFramesPerSlice=1156

**Comment by NickCulbertson** [comment]
I don't observe this behavior when using the MusicToy example in the AudioKit Cookbook. Try setting your session https://github.com/AudioKit/Cookbook/blob/2ce0d2fd0c6850cb4b6a5058309af0571b69f468/Cookbook/Cookbook/CookbookApp.swift

**Comment by aure** [comment]
Answered by @NickCulbertson with no follow up, closing for now.
