### ISSUE TITLE
MIDI File Parser crashes on copyright meta events

### ISSUE THREAD

**Issue by matbouil** [AudioKit/AudioKit#2782]
### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 13.4.1

### Description
Observed on : AudioKit 5.1

MIDI files containing copyright notice meta events makes the MIDI file Parser crash.

These kind of event doesn't seem to be supported in the `MIDIFileTrackChunk` `chunkEvents` process:

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/225499/191733888-84a7dfe2-a544-4016-ade3-bedaef744813.png">

### Crash Logs, Screenshots or Other Attachments (if applicable)

Here is a MIDI file which contains a copyright notice event.
[It Must Be Love.mid.zip](https://github.com/AudioKit/AudioKit/files/9625157/It.Must.Be.Love.mid.zip)

**Comment by aure** [comment]
We're going to be overhauling the MIDI with @orchetect 's https://github.com/orchetect/MIDIKit
