### ISSUE TITLE
Tuner Text not working

### ISSUE THREAD

**Issue by rickhardy** [AudioKit/AudioKit#2783]
### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 14

### Description

The App i'm working on is based on the mini app - Tuner. 
(The official tuner does not work properly for me there either -- the three text fields show 0.0 0.0 and -/-  )

With Audiokit v5.3.0 the re are three text fields showing  amp, pitch and notename

eg: 
`Text("\(conductor.data.pitch, specifier: "%0.1f")")`

With Audiokit 5.5.4 the fields do not work. 

These still work if I go revert to Audiokit 5.3.0 and add back in the start and stop functions which have been moved into basetap in 5.5.4

The conductor runs and the other tuner graphics (nodeOutputView, etc... ) pick up the data from it. The text fields do not. 

Do you have the same fault if running cookbook.tuner?  Maybe it is my specific set up. 

### Crash Logs, Screenshots or Other Attachments (if applicable)

![Screenshot 2022-09-28 at 20 42 13](https://user-images.githubusercontent.com/45637470/192874024-2a5ca4de-5df5-425b-b2e5-bc0d8972100c.png)

**Comment by aure** [comment]
This is the repo for AudioKIt, the library. Open Cookbook issues over there.

**Comment by aure** [comment]
I'm not sure if this where this problem lies actually, I'll look into it.

**Comment by rickhardy** [comment]
Thanks, very much, I have opened the same bug on the cookbook issues , as requested.

**Comment by aure** [comment]
Fixed in Cookbook.
