### ISSUE TITLE
Sending `MIDIControl.damperOnOff` to a `MIDISampler` doesn't use the channel number.

### ISSUE THREAD

**Issue by tgrapperon** [AudioKit/AudioKit#2787]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

I created a `MIDISampler` and successfully loaded an instrument. I would like to perform the following sequence of events:
```swift
midicc(MidiControl.damperOnOff.rawValue, value: 127, channel: 0) // Sustain On on ch. 0
play(noteNumber:40, velocity: 127, channel: 0) // Play on ch. 0
stop(noteNumber:40, channel: 0) // Stop on ch. 0
// A note rings on channel 0…

midicc(MidiControl.damperOnOff.rawValue, value: 127, channel: 1) // Sustain On on ch. 1
play(noteNumber:50, velocity: 127, channel: 1) // Play on ch. 1
stop(noteNumber:50, channel: 1) // Stop on ch. 1
// A note rings on channel 1…

midicc(MidiControl.damperOnOff.rawValue, value: 0, channel: 0) // Sustain Off on ch. 0
// The note on channel 0 disappears…
// But so does the note on channel 1!
```
At the end of this sequence, I would expect the damper to be still "On" on channel 1, and its note still ringing, but setting it to `0` on channel 0 shuts down everything on all channels.
It also seems that the damper is active on channel `x` whatever channel I send the `On` message.

So it behaves as if this message applies to all channels and as if the channel wasn't relevant when messaging with the cc code 64. Is this the expected behavior from MIDI spec, or a limitation of `AVAudioUnitSampler`? Or am I doing something wrong elsewhere and it should work independently for each channel?

Thanks!

**Comment by NickCulbertson** [comment]
I imagine you would need a separate AppleSampler/MIDISampler for each channel if you don't already.

**Comment by tgrapperon** [comment]
Thanks for the feedback @NickCulbertson, this is indeed what I envisaged as a workaround. Do you know if this behavior is expected?

**Comment by NickCulbertson** [comment]
I think it probably is the intended behavior for AVAudioUnitSampler to only observe one set of MIDICC events regardless of the channel you put it on.
