### ISSUE TITLE
Cookbook - iPhone physical device - sound switches to receiver speaker after viewing 'Channel/Device Routing' screen

### ISSUE THREAD

**Issue by DaveHineman** [AudioKit/AudioKit#2790]
### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 14

### Description

Download the Cookbook from Github.
Perform the personalization steps needed to run the workspace on a physical iPhone (not iPad, not simulator).
Select the Dynamic Oscillator screen and play a sound. Observe that sound is coming from the loudspeakers, not the receiver earpiece. 
Return to the main menu and select the Channel/Device Routing menu item. You don't have to press anything. 
Return to the main menu and select Dynamic Oscillator screen again. 
Playing a sound now comes from the receiver speaker and won't change until you kill and restart the app. 

What's odd is that this issue doesn't happen if you visit the Tuner screen (which also uses the mic). It only happens after you visit the Channel/Device screen. After viewing Channel/Device screen, all sounds are routed to the receiver speaker, not just the Oscillator screen.

**Comment by NickCulbertson** [comment]
It probably has something to do with setting the AudioSession`try Settings.setSession(category: .playAndRecord,
                                    with: [.mixWithOthers, .allowBluetooth, .allowBluetoothA2DP])` It needs `.defaultToSpeaker`

**Comment by NickCulbertson** [comment]
That is how it is set in the app delegate which is only called when the app is launched. That line might be able be omitted entirely since the session is already setup.

**Comment by DaveHineman** [comment]
Thanks, Nick. 

I can edit that here and give it a try. I’m having problems with my own app, as well, using .defaultToSpeaker. 
What worked great two years ago is now killing the mic input on iPhones. 

Dave.

**Comment by NickCulbertson** [comment]
You might need mic permissions if you haven’t set that up already.

**Comment by DaveHineman** [comment]
Mic permissions are in place. 

In the Cookbook, I found two files that reference .setCategory and they both already have .defaultToSpeaker in the options. 
If there are any others that I overlooked, please advise. 

So, the session begins, defaulted to Speaker. The sound output routing is changing whenever the Channel/Device screen is accessed. Are you able to reproduce my issue?

<img width="1455" alt="Screen Shot 2022-10-20 at 2 13 32 PM" src="https://user-images.githubusercontent.com/49221132/197040455-e289bf57-a659-4eff-9820-53e8f767d861.png">
<img width="1453" alt="Screen Shot 2022-10-20 at 2 14 08 PM" src="https://user-images.githubusercontent.com/49221132/197040458-cc6dc645-b86a-4703-b244-8a6d0a215467.png">

**Comment by DaveHineman** [comment]
Thanks, Nick, I will check that out.

**Comment by DaveHineman** [comment]
After adding .defaultToSpeaker to ChannelDeviceRouting.swift, the sound output is no longer switching to the receiver speaker as I move around the menu items. The microphone is continuing to function, as well.

I tested on an iPhone XR with iOS 16.0.2 and also an iPhone7S with iOS 15.7. I don't see the problem anymore. Thanks a ton!

**Comment by NickCulbertson** [comment]
Sweet! Does it also work with removing that and the next line entirely since it is already being set in the app delegate?On Oct 20, 2022, at 4:26 PM, DaveHineman ***@***.***> wrote:﻿
After adding .defaultToSpeaker to ChannelDeviceRouting.swift, the sound output is no longer switching to the receiver speaker as I move around the menu items. The microphone is continuing to function, as well.
I tested on an iPhone XR with iOS 16.0.2 and also an iPhone7S with iOS 15.7. I don't see the problem anymore. Thanks a ton!

**Comment by NickCulbertson** [comment]
No, that sounds good. It just feels odd that the AudioSession is set 3 different ways in the app.I’ll add your fix to the Cookbook soon unless you feel like doing a pull request on the Cookbook.On Oct 20, 2022, at 4:26 PM, DaveHineman ***@***.***> wrote:﻿
After adding .defaultToSpeaker to ChannelDeviceRouting.swift, the sound output is no longer switching to the receiver speaker as I move around the menu items. The microphone is continuing to function, as well.
I tested on an iPhone XR with iOS 16.0.2 and also an iPhone7S with iOS 15.7. I don't see the problem anymore. Thanks a ton!

**Comment by DaveHineman** [comment]
Thanks, Nick. I’m good with you adding it in to the next version. 

Best,
Dave.

**Comment by NickCulbertson** [comment]
Thanks, Dave! Fixed here: https://github.com/AudioKit/Cookbook/pull/116

**Comment by DaveHineman** [comment]
Thanks so much for your help, Nick.
Working through this issue with you confirmed that I should be able to get ‘defaultToSpeaker' working on my own app and that it isn’t an Apple bug. Whew!
Because of your help, I am making some changes to the Flutter audio capture plugin that I’m using and will submit those improvements to the author. 

Dave.
