### ISSUE TITLE
Can't start a recorder while remaining pitchTap state

### ISSUE THREAD

**Issue by muvich3n** [AudioKit/AudioKit#2793]
### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 13.4.1

### Description

I'm working on a feature that enables users records audio while the pitchTap is running at the same time. 
But when I start recorder, Xcode return an error.
Is there a way to implement this feature? Thanks!

```
  @Published var data = SoundData() {
    didSet {
        if data.isRecording {
            NodeRecorder.removeRecordedFiles()
            do {
                try recorder?.record()
            } catch let err {
                print(err)
            }
        } else {
            recorder?.stop()
        }

        if data.isPlaying {
            if let file = recorder?.audioFile {
                player.file = file
                player.play()
            }
        } else {
            player.stop()
        }
    }
}

  let engine = AudioEngine()
  let mic: AudioEngine.InputNode
  let tappableNodeA: Fader
  let tappableNodeB: Fader
  let tappableNodeC: Fader
  let silencer: Fader

  var tracker: PitchTap!

  let recorder: NodeRecorder?
  let player = AudioPlayer()
  let mixer = Mixer()
```

### Crash Logs, Screenshots or Other Attachments (if applicable)

Thread 1: "required condition is false: nullptr == Tap()"

**Comment by Matt54** [comment]
Are you recording the same node that you are pitch tapping?

I ask because you can't have two taps running on the same node and the Recorder has a tap of it's own that gets hooked up on Recorder start.

If this is the case, you can work around the issue by adding another downstream node to act as an additional tap location.

**Comment by muvich3n** [comment]
> @muvich3n Are you recording the same node that you are pitch tapping?
> 
> I ask because you can't have two taps running on the same node and the Recorder has a tap of it's own that gets hooked up on Recorder start.
> 
> If this is the case, you can work around the issue by adding another downstream node to act as an additional tap location.

I think you are right! Thank you for your help!
