### ISSUE TITLE
FFT tap on mixer node, not working with node panned to full right

### ISSUE THREAD

**Issue by sethiris** [AudioKit/AudioKit#2795]
### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 14

### Description

I have a mixer node L, panned to -1, and other mixer node R panned to 1, this 2 mixers are inputs in another mixer node (Main Mixer), where I have a ffttap, analyzing the data, the panned sounds to 1 don't appear in the fft. 

I would love to have fft data separated by left and right, without need 2 fftaps (one for each mixer) because is a problem for the performance, but if the solution is have only un fft for Left and right, its ok. I'm doing something wrong? if I pan the mixer node R to center(0), the fft data come up, but i need this mixer to be in the right (1)

Thanks!

**Comment by aure** [comment]
The tests I added pass. So it does take into account the right channel. Maybe you mean to submit another bug? If so, please add a test proving the problem. Also, please consider becoming an AudioKit Sponsor:  https://github.com/sponsors/AudioKit
