### ISSUE TITLE
watchOS Support

### ISSUE THREAD

**Issue by raymondwelch33** [AudioKit/AudioKit#2796]
### Description

I would love to be able to have all of the features from AudioKit available via watchOS, and I think now that the watchOS platform is well developed and stable -- it's a necessity for any popular or mainstream (if you will) high quality open source Apple library to support watchOS. 

### Proposed Solution

Full feature parity or at least partial feature parity (e.g. the ability to play / clip audio via watchOS). 

### Describe Alternatives You've Considered

Other open source libraries.

**Comment by aure** [comment]
Supporting watchOS is a good idea, but it's not trivial, please consider becoming an AudioKit Sponsor:  https://github.com/sponsors/AudioKit
