### ISSUE TITLE
Can't install Package

### ISSUE THREAD

**Issue by doriansgithub** [AudioKit/AudioKit#2797]
### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 14

### Description

Can't add to project in Xcode 14.1.

See image.

![XCode Package Fail](https://user-images.githubusercontent.com/5715600/200153618-204a50b5-5a5c-4c20-aa4c-c5ba1a886570.jpg)

### Crash Logs, Screenshots or Other Attachments (if applicable)

Try to add the package dependency, paste the link and it is asking for a user and password to the package. See image.

**Comment by aure** [comment]
It's not our issue, it's with SwiftPackageIndex: https://swiftpackageindex.com/AudioKit/collection.json. Alert them at https://swiftpackageindex.com/ if you like, but they are usually pretty good about fixing this sort of thing.

**Comment by doriansgithub** [comment]
Got it. Will do. Thanks!Sent from my iPhoneOn Nov 5, 2022, at 11:42 PM, Aurelius Prochazka ***@***.***> wrote:﻿
It's not our issue, it's with SwiftPackageIndex: https://swiftpackageindex.com/AudioKit/collection.json. Alert them at https://swiftpackageindex.com/ if you like, but they are usually pretty good about fixing this sort of thing.

**Comment by aure** [comment]
Resolved: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2118
