### ISSUE TITLE
On Microphone permission in iOS 16 producing screeching noise

### ISSUE THREAD

**Issue by kumarlav0** [AudioKit/AudioKit#2798]
### macOS Version(s) Used to Build

macOS 11 Big Sur

### Xcode Version(s)

Xcode 13.0

### Description

I am working on a guitar application written in Objective-C. It has a feature like Tuning from Guitar. The tuning screen requires microphone permission. When we give permission to the app, suddenly the app starts producing a screeching noise which sounds very weird.

The same code is working on iOS 15 and lower versions. Only in iOS 16 and higher it is having this noise issue.

I have used Audiokit and the version of Audiokit is 2.2 [ pod 'AudioKit', '~> 2.2' ] and the latest version is 5.5.7

pod 'AudioKit'

I also created a question on Stackoveflow :- 
https://stackoverflow.com/questions/74317276/on-microphone-permission-in-ios-16-producing-screeching-noise

**Comment by aure** [comment]
AudioKit 2 is unfortunately way too old for us to support.

**Comment by kumarlav0** [comment]
I am totally agree with you @aure . But how it works with iOS 15 and Why not working with iOS 16 ?

**Comment by aure** [comment]
Yeah, hopefully you could wait for an update from Apple if it affects other developers like it has you. Nobody has complained about something similar in AK5, but it could do the same thing. Is the noise feedback?
