### ISSUE TITLE
Solution for #298

### ISSUE THREAD

**Issue by charliewilliams** [AudioKit/AudioKit#2803]
### Description

Re discussion in https://github.com/AudioKit/AudioKit/issues/298

From Logic, if you save your EXS24 instrument *into the Samples/ folder in your Xcode project* and also pick "include audio data" — the saved EXS24 instrument will contain the correct relative path to be able to load!

### Proposed Solution

Since this is something a few people have run into, it might be worth adding something in the docs or FAQ about it?

### Describe Alternatives You've Considered

This seems like the best thing

### Additional Context

Happy to write up the FAQ post if you like

**Comment by NickCulbertson** [comment]
Yeah, that is a weird gotcha for AUAudioUnitSampler. I put my sounds in a `Sounds` folder in my Xcode project and then drag those sounds into Logic's Sampler. I found out about it the same way you did, by digging through old closed issues. There is brief mention of it in the AudioKit docs, but it wouldn't hurt to beef it up. https://www.audiokit.io/AudioKit/documentation/audiokit/samplers
