### ISSUE TITLE
Approach to disable input bus

### ISSUE THREAD

**Issue by jcavar** [AudioKit/AudioKit#2805]
### Description

`AUAudioUnitBus` has `isEnabled` property. If this property is disabled, `pullBlock` will not be called on an input bus and will save processing time.

This is working very well in Apple's Audio Units (e.g. `AVAudioMixerNode`) and depending where this bus in the chain is, you might experience significant performance improvements as none of the upstream nodes will be called.

Unfortunately this is not implemented in AudioKit units (e.g. DryWetMixer).

### Proposed Solution

This check would need to happen [here](https://github.com/AudioKit/AudioKitEX/blob/main/Sources/CAudioKitEX/Internals/DSPBase.mm#L104) and [here](https://github.com/AudioKit/AudioKitEX/blob/main/Sources/CAudioKitEX/Internals/DSPBase.mm#L112) I believe.

I am not sure how to approach this since this property is in `AUAudioUnitBusArray->AUAudioUnitBus` which is not available within DSP.

### Describe Alternatives You've Considered

I guess one approach would be to duplicate these properties on DSP, but that seems not very elegant.

### Additional Context

Please note that this is different to bypass effect, which just bypasses processing in one node, but doesn't prevent further signal propagation.

**Comment by aure** [comment]
@jcavar This issue is pretty old, I was wondering, since you have made pull requests before if you want to try to close this issue or if you find its not something you need, maybe it can be closed without code.

**Comment by jcavar** [comment]
Hi @aure, we got around this in a different way, but I think the problem is still relevant.

I am ok if you would like to close it as we don't have capacity to work on it.
