### ISSUE TITLE
randomly Index Out of range crash (using NodeOutputView)

### ISSUE THREAD

**Issue by lucarocchi** [AudioKit/AudioKit#2808]
### macOS Version(s) Used to Build

macOS 13 Ventura, macOS 12 Monterey

### Xcode Version(s)

Xcode 14

### Description

I'm working on an iOS app that uses NodeOutputView 
Randomly I get this "Index Out of range" as you can see in the screen shot 
 

### Crash Logs, Screenshots or Other Attachments (if applicable)

<img width="1440" alt="Screenshot 2022-12-07 alle 17 41 54" src="https://user-images.githubusercontent.com/213265/206874449-8f3e2702-48bf-4259-924b-7a4829ed67cd.png">
<img width="1440" alt="Screenshot 2022-12-10 alle 19 24 32" src="https://user-images.githubusercontent.com/213265/206874459-6ba680b0-9cc4-4f06-baca-3b2916668d33.png">

**Comment by aure** [comment]
This is not in AudioKit, it is in AudioKitUI, please post it there.
