### ISSUE TITLE
When I modify the Engine's output, it stop playing

### ISSUE THREAD

**Issue by ladeng** [AudioKit/AudioKit#2812]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

I want to choose different sound effects to listen to when playing music
this is my code:
`
class EffectConductor: ObservableObject, ProcessesPlayerInput {
    var engine = AudioEngine()
    var player = AudioPlayer()
//    var dryWetMixer : DryWetMixer
    var isPlaying = false
    

    init(path:String) {
        let mediaUrl = URL.init(fileURLWithPath: path)
        let file = try! AVAudioFile(forReading: mediaUrl)
        try! player.load(file: file, buffered: true)
        engine.output = player
    }

    @Published var effectType: Int = 0 {
        didSet {
            var node : Node? = nil
            switch effectType {
            case 1:
                node = AutoPanner(player)
            case 2:
                node = AutoWah(player)
            case 3:
                node = Compressor(player)
            case 4:
                node = DynamicRangeCompressor(player)
            case 5:
                node = Expander(player)
            case 6:
                node = Phaser(player)
            case 7:
                node = StringResonator(player)
            default:
                node = nil
            }
            if node==nil
            {
                print("effect nil")
                engine.output = player
            }else{
                engine.output = DryWetMixer(player, node!)
            }
        }
    }
}
`
when i call this code：
`
engine.start()
player.start()
`
Can play music. but when i click a button and call this code:
effectType = 2(or ever value) 
to change engine.output  value
it's stop playing
how to solve this problem?
thanks everyone!

**Comment by ladeng** [comment]
i try this when i click a button
`
let progress = player.getCurrentTime()
if(isPlaying){
   player.stop()
}
self.effectType = 3
if(isPlaying){
   player.seek(time: progress)
   player.play()
}
`
But there will be a pause in the playback process
How to better solve this problem?

**Comment by ladeng** [comment]
can someone help me?

**Comment by aure** [comment]
Sorry, we use the Issues forum just to manage known problems in AudioKit, not in client code. Maybe post your question to StackOverflow?
