### ISSUE TITLE
Memory Leak in MIDI+Sending.swift

### ISSUE THREAD

**Issue by alenicol** [AudioKit/AudioKit#2819]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

Hi,
apologies for not making the Bug Report as complete as requested, however it's such a small thing that I did not think it was worth it.

I found a memory leak in MIDI+Sending.swift

In line 359:
        let packetListPointer: UnsafeMutablePointer<MIDIPacketList> = UnsafeMutablePointer.allocate(capacity: 1)

This memory is never deallocated. By adding at line 384:
         packetListPointer.deallocate()

The problem should be solved. Please double check that this does not have ramifications or bad consequences in the rest of the code

**Comment by orchetect** [comment]
MIDI code is completely stripped out and replaced for v6.

**Comment by aure** [comment]
I closed the issue but then I thought, okay if someone wants to fix it they can, for v5.

**Comment by orchetect** [comment]
Can close if this is now resolved.
