### ISSUE TITLE
@testable doesn't work

### ISSUE THREAD

**Issue by wtholliday** [AudioKit/AudioKit#2826]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

@testable doesn't work. Perhaps this is a problem with SPM?

Made changes to remove it.

**Comment by evan-templeton** [comment]
Do you have any more details on your issue? `@testable` imports are working for me.

<img width="498" alt="Screenshot 2024-09-05 at 9 09 15 AM" src="https://github.com/user-attachments/assets/c58a7c73-2d01-4da2-861a-38380424f9f1">

**Comment by evan-templeton** [comment]
@aure permission to close this one? Unable to repro.
