### ISSUE TITLE
Support for delay node with greater than 2 seconds of delay

### ISSUE THREAD

**Issue by ellbosch** [AudioKit/AudioKit#2827]
### Description

I'm trying to create a delay effect using the microphone and my desired delay length may exceed 2 seconds. From what I can tell, the `Delay` node is the best approach for creating a delay effect but I appear to be maxed out at 2 seconds.

### Proposed Solution

Really any way for me to exceed the 2 second max delay. I'm curious if there are any workarounds that have worked here.

### Describe Alternatives You've Considered

I've tried a recursive strategy that wraps Delay nodes until the desired length is reached, but had problems getting this to work.

**Comment by aure** [comment]
Hi, AudioKit utilizes Apple's Delay Audio Unit which imposes this restriction. In order to have longer delay times, use one of the delays from the SoundpipeAudioKit package. VariableDelay, for instance, has a 10 second maximum delay time.

**Comment by ellbosch** [comment]
Thanks @aure!
