### ISSUE TITLE
minimum iOS versions supported by AudioKit

### ISSUE THREAD

**Issue by jalalimehdi** [AudioKit/AudioKit#2835]
### Description

Hi nice job
What are the minimum iOS versions supported by AudioKit?
I want to Record and add audio effects at the same time in iOS . can I do with audiokit.
[my problem without audiokit](https://stackoverflow.com/questions/75963313/record-and-add-audio-effects-at-the-same-time-in-ios-with-audio-unit)

### Proposed Solution

What are the minimum iOS versions supported by AudioKit?

### Describe Alternatives You've Considered

What are the minimum iOS versions supported by AudioKit?

**Comment by aure** [comment]
Read the Package.swift file.

**Comment by jalalimehdi** [comment]
@aure 
thanks 

can I Record and add audio effects at the same time in iOS  with audiokit?

**Comment by aure** [comment]
I can :)

**Comment by jalalimehdi** [comment]
please guide me how to connect RemoteIO (kAudioUnitType_Output) unit with the effect unit (kAudioUnitType_Effect) to record audio file with effect.
thanks

**Comment by maksutovic** [comment]
GitHub Issues are only for reporting bugs with the library. Please use
StackOverflow with the "AudioKit" Tag for implementation questions. Also
please refer to the Cookbook:
https://github.com/AudioKit/Cookbook for hundreds of ready made examples of
using AudioKit.

**Comment by jalalimehdi** [comment]
i realized thanks
