### ISSUE TITLE
Xcode 15 Beta Build error

### ISSUE THREAD

**Issue by iamluisg** [AudioKit/AudioKit#2845]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

Hello, I am sorry, I know it is the Xcode 15 beta but I am not able to build the Cookbook project due to the following error:

CDunneAudioKit -> Wavestack 
Line 33
assert(waveData.size() >= fftLength);

Is giving the following error:
`Use of undeclared identifier 'assert'`

**Comment by NickCulbertson** [comment]
This seems related to [https://github.com/AudioKit/DunneAudioKit/pull/14](https://github.com/AudioKit/DunneAudioKit/pull/14). The fix seems to be adding  `#include <cassert>` to WaveStack.h and EnvelopeGeneratorBase.h to resolve the errors. I assume that is available on earlier OS versions, but I haven't checked. That pull request also includes some test changes that may or may not be needed. @aure ¯\_(ツ)_/¯

**Comment by NickCulbertson** [comment]
This and other Xcode 15 stuff has been fixed in the latest release.
