### ISSUE TITLE
Pitch detection error, frequencies offset in 5.6 SDK

### ISSUE THREAD

**Issue by brizzly** [AudioKit/AudioKit#2846]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

Issue with latest SDK 5.6 on ios, "A" pitch detection value is incorrect.
There is an offset of -2 / -3 hertz starting at 110 Hz.

### Crash Logs, Screenshots or Other Attachments (if applicable)

use the last sdk 5.6 for ios and get the microphone pitch.

**Comment by ilonashub** [comment]
was there any solution to it?

**Comment by NickCulbertson** [comment]
Test it again with the latest AudioKit main branch release and see if that works better. I think this PR may have fixed it https://github.com/AudioKit/AudioKit/pull/2860

**Comment by ilonashub** [comment]
thanks! it fixed it indeed (that PR was made by my teammate :))
