### ISSUE TITLE
can i audio record?

### ISSUE THREAD

**Issue by davut5** [audiokit/AudioKit#285]
For example, i might have a karaoke app with a record function, and i want to record both the backing music and the microphone audio at the same time.

**Comment by aure** [comment]
Yeah, this should be possible.  Will work up an example.

**Comment by davut5** [comment]
can u give me an example for iOS?

**Comment by davut5** [comment]
please put an example for us. :(

**Comment by aure** [comment]
There's an AKAudioRecorder class in the latest Xcode7.3 development branch.  If you want to try that, it's incredibly simple.  Or, wait for it to get merged onto master.

**Comment by Isuru-Nanayakkara** [comment]
Hi @aure, can you please elaborate on how to use the `AKAudioRecorder` class? I have the following setup.

```swift
import AudioKit

class ViewController: UIViewController {

    var recorder: AKAudioRecorder!
    var recording = false
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let documentDirPath = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true).first!
        let recordingAudioFilePath = NSURL(string: documentDirPath)!.URLByAppendingPathComponent("recording.caf").path!
        let recordingAudioFileURL = NSURL(fileURLWithPath: recordingAudioFilePath)
        recorder = AKAudioRecorder(recordingAudioFileURL.absoluteString)
    }

    @IBAction func didTapRecordButton(sender: UIButton) {
        if recording == true {
            print("Recording stopped")
            recording = false
            recorder.stop()
        } else {
            print("Recording started")
            recording = true
            recorder.record()
        }
    }
}
```

The output of the `recordingAudioFileURL` is this;
```
file:///var/mobile/Containers/Data/Application/CA55306F-E145-4338-9F3E-5492CBFF13F2/Documents/recording.caf
```

But it crashes at the `recorder = AKAudioRecorder(recordingAudioFileURL.absoluteString)` line.

![screen shot 2016-05-05 at 8 28 08 pm](https://cloud.githubusercontent.com/assets/2551877/15046936/fd1e4040-12ff-11e6-987f-c2e37006c778.png)

What am I doing wrong here?

**Comment by aure** [comment]
I don't see any code setting up what you actually want to record.  You have to have AudioKit running and record from it. Maybe you have that set up elsewhere in your code?

**Comment by nick-thompson** [comment]
Hi, I'm trying to follow along here and get recording audio from the mic in a simple iOS app, and I'm hitting a few errors.

```swift
import AudioKit
 
let mic = AKMicrophone()
let bundle = NSBundle.mainBundle()
let file = bundle.pathForResource("recording", ofType: "wav")
 
@objc(AudioEngineManager)
class AudioEngineManager: NSObject {
 
  var recorder = AKMicrophoneRecorder(file!)
  var sampler = AKSampler()
 
  @objc func prepareRecorder() -> Void {
    AudioKit.output = sampler
    AudioKit.start()
  }

  @objc func startRecording() -> Void {
    recorder.record()
  }

  @objc func stopRecording() -> Void {
    recorder.stop()
  }

  @objc func play() -> Void {
    sampler.loadWav(file!)
    sampler.playNote()
  }
```

The current error I'm having is that `file` unwraps as `nil` while trying to initialize the microphone recorder. Perhaps that's a silly error as I'm new to swift, but I borrowed it straight from the OS X playground example for recording from mic, so I'm a little confused.

In a previous example that I was working through, I seemed to be able to start/stop the recorder successfully, and when trying to `play()`, the `loadWav(file!)` line would fail because it couldn't find the file.

Hoping you can help me kill two birds with one stone here, I'm brand new to swift and to AudioKit so this is all a little confusing! Thank you

**Comment by aure** [comment]
You need to have  a recording.wav in your project already.  It can be blank, but it needs ot be there.  This is less of an issue for Github and more of a conversation for the AudioKit google group.

**Comment by Asbat** [comment]
Can anyone write some simple example of how to start the microphone, record some samples and write them in a file in the documents directory? Is that so hard?! Excuse me if AudioKit has such example already. I just can't find any helpful info. Thanks!

**Comment by aure** [comment]
@Asbat https://github.com/audiokit/AudioKit/tree/master/Examples/iOS/Recorder
