### ISSUE TITLE
SIGABRT in DSPBase::addCreateFunction

### ISSUE THREAD

**Issue by jumbopilot** [AudioKit/AudioKit#2852]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode Version 15.0 beta 4 (15A5195m)

### Description

Pre-Condition: Use AudioKit 5.6.0 
Action: Compile, Build and Run the project using a DryMixer

Observed: Target instantiation ends with signal SIGABRT in  DSPBase:327: assert(factoryMap->count(name) == 0 && "redundant DSP kernel registration");

  0x10107fd00 <+0>:  pushq  %rbp
    0x10107fd01 <+1>:  movq   %rsp, %rbp
    0x10107fd04 <+4>:  leaq   0x1e564a(%rip), %rdi      ; __registerDryWetDualMixerDSP
    0x10107fd0b <+11>: leaq   0xc4cfe(%rip), %rsi       ; "dwm2"
    0x10107fd12 <+18>: callq  0x101068630               ; DSPRegistration<DryWetDualMixerDSP>::DSPRegistration at DSPBase.h:246
->  0x10107fd17 <+23>: popq   %rbp
    0x10107fd18 <+24>: retq   
    0x10107fd19 <+25>: nopl   (%rax)

<img width="1125" alt="Screenshot 2023-07-24 at 18 34 23" src="https://github.com/AudioKit/AudioKit/assets/43632124/23fd87a7-48b9-431f-ab72-8638aa92e7f5">

Expected: No assertion "redundant DSP kernel registration" in DSPBase

**Comment by NickCulbertson** [comment]
There was a similar issue in DunneAudioKit (https://github.com/AudioKit/DunneAudioKit/pull/15/commits/5718ef0feec39cea48ebc02f9967436d99c57bde). The same probably needs to be applied to the other AudioKit packages. DryWetDualMixer is in AudioKitEX. `#include <cassert>`
