### ISSUE TITLE
Some APIs are unavailable on visionOS

### ISSUE THREAD

**Issue by warpling** [AudioKit/AudioKit#2853]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

A couple APIs AudioKit uses (only a couple!) seem to be unavailable on visionOS. They will need workarounds or their enclosing functions to be excluded on visionOS.

I propose making a new branch that's visionOS ready by marking those functions as unavailable until those who understand them better can create workarounds.

**Comment by musesum** [comment]
Same here. Am using XCode 15 beta 5.  Error at 

`guard let track = asset.tracks(withMediaType: .audio).first else {...}`

Am working full time on a visual music synth for visionOS. Would rather not fork on my own; would spend a lot of time on an official branch.

**Comment by warpling** [comment]
@musesum [I have a branch](https://github.com/warpling/audiokit/tree/visionOS) you can feel free to use in the meantime.

**Comment by musesum** [comment]
@warpling  Well I tried in my Package.swift
        `.package(url: "https://github.com/warpling/AudioKit/tree/visionOS", from: "5.0.0"),`
 but the most recent tags on your site stop at 3.6 -- I also tried 
        `.package(url: "https://github.com/warpling/AudioKit/tree/visionOS", from: "3.0.0"),`
but no luck. Not sure how tags work, I assumed they would carry over.

**Comment by warpling** [comment]
Hmmm I don't know tags well either but just target the latest from the branch instead. I don't know what the config looks like without using the SPM GUI.

**Comment by musesum** [comment]
This worked: 
`.package(url: "https://github.com/warpling/AudioKit.git", branch: "visionOS"),`

**Comment by musesum** [comment]
@warpling 

I'm able to get the visionOS simulator to compile (yay!) but, am experiencing a problem with iPadOS 17 beta on device with the following error
`'loadTracks(withMediaType:)' is only available in iOS 15.0 or newer`

Perhaps changing thie line in the Package.swift might fix? 
`platforms: [.macOS(.v11), .iOS(.v13), .tvOS(.v13)],`
