### ISSUE TITLE
AudioKit issues with implementing the app "preferences" (Settings) for the app.

### ISSUE THREAD

**Issue by DarLohr** [AudioKit/AudioKit#2857]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 13.4.1

### Description

Hi,
I have made an app and finally I decided to have a "preferences" / "Settings" window for my app. After wasting hours, thinking maybe my code is broken, I figured out that AudioKit is causing that. I have created a new Xcode document without AudioKit and implemented the "Settings" there and it worked perfectly. to make sure that the problem is caused by Audiokit, I then added the AudioKit into my project, and there it was. the error shoed up again. AudioKit is using "Settings" in one of their modules which is reserved by Xcode. and that creates the conflict.. I have tested this with AudioKit version 5+ on macOS 13+. I have included a screenshot from the issue

### Crash Logs, Screenshots or Other Attachments (if applicable)

<img width="782" alt="Screenshot 2023-08-19 at 11 03 20 PM" src="https://github.com/AudioKit/AudioKit/assets/19311412/b02bc558-eedf-416e-8db7-2567334b6a9d">

**Comment by orchetect** [comment]
If you replace `Settings {` with `SwiftUI.Settings {` does it build successfully?

**Comment by DarLohr** [comment]
Yes that did it. Thanks a million.
