### ISSUE TITLE
Convert Audio data without files

### ISSUE THREAD

**Issue by geofstro** [AudioKit/AudioKit#2858]
### Description

I wanted to use FormatConverter to convert Audio Data from an http url in one format, and return data in the new desired format.  As far as I can see though, FormatConverter is only designed to take a file URL and write to a new file in the user's file system. I don't want to touch the file system though.

I want to keep the data representing the audio in my App's memory at all times!

Apologies if I'm missing something. I can't see how to achieve this in the documentation though. So I don't believe it's a bug; but rather a new feature request, which I believe should be easily achievable.

Alternatively to 1 above, I could feed in the Audio _data_ pointed to be the original http url, rather than the URL.

Grateful if someone could advise, either if this is already possible and, if so, an example of how to achieve it, or if it could be added as a new feature on top of the existing conversion options.

Thanks in advance.

### Proposed Solution

Here's what I'd like to be able to do:

1. Feed an http which points to audio data in one format (e.g. WAV).
2. Convert that data to a different audio format (e.g. flac)
3. Return the converted Audio data.

### Describe Alternatives You've Considered

ffmpeg can do this, as it can output to data, rather than a file; but I'd like to achieve it without having to add the ffmpeg library to my app.

### Additional Context

Instead of the converter taking the original http url as an argument I could input the data it points to, in case that would be easier to implement.

**Comment by NickCulbertson** [comment]
Unfortunately I'm not sure of a solution for this inside of AudioKit currently. I'm going to close this for now but feel free to reopen if you have any specific API questions.
