### ISSUE TITLE
FormatConverter giving Optional("Operation Stopped") error

### ISSUE THREAD

**Issue by numandev1** [AudioKit/AudioKit#2859]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

```
 let oldUfileUrlRL = URL(string: fileUrl)!
            let newURL = URL(string: outputMp3Path)!
            
            var options = FormatConverter.Options()
            options.sampleRate = 44100
            options.bitRate = 256000
            options.format = "m4a"
            options.eraseFile = true
            options.bitDepthRule = .any
             
            let converter = FormatConverter(inputURL: oldUfileUrlRL, outputURL: newURL, options: options)
            converter.start { error in
            // check to see if error isn't nil, otherwise you're good
                if((error) != nil)
                {
                    print("error=> \(error?.localizedDescription)")
                    reject(error?.localizedDescription,error?.localizedDescription, error)
                    return
                }
               
                resolve(newURL.absoluteString)
            }
```

### Crash Logs, Screenshots or Other Attachments (if applicable)

getting errors like below
```
Optional("Operation Stopped")
```

when I try to give the `mp3` file as input and an output file as `m4a` then I get the error `Optional("Operation Stopped")` and if I open the temp folder then I get `filename_TEMP.wav` file which has bigger size

**Comment by NickCulbertson** [comment]
If you can make a small example project I'll take a look.

**Comment by numandev1** [comment]
@NickCulbertson thanks for you response, I was trying to add it to my react native package https://github.com/numandev1/react-native-compressor
I am not an IOS native developer, can you try to give an mp3 file path and expect m4a or mp3 as output

**Comment by NickCulbertson** [comment]
The only issue I saw was that `"m4a"` should be `.m4a`. Also the file paths might have been off. I got this to work ( replace with your file names).

```
init() {
        let fileURL = Bundle.main.url(forResource: "1beep", withExtension: "mp3")
        let oldUfileUrlRL = fileURL!
        let newURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.appendingPathComponent("NewAudio.m4a")
        print(newURL)
        var options = FormatConverter.Options()
        options.sampleRate = 44100
        options.bitRate = 256000
        options.format = .m4a
        options.eraseFile = true
        options.bitDepthRule = .any
        
        let converter = FormatConverter(inputURL: oldUfileUrlRL, outputURL: newURL, options: options)
        converter.start { error in
            // check to see if error isn't nil, otherwise you're good
            if((error) != nil)
            {
                print("error=> \(error?.localizedDescription)")
                //                           reject(error?.localizedDescription,error?.localizedDescription, error)
                return
            }
            
            //                       resolve(newURL.absoluteString)
        }
    }
```

**Comment by NickCulbertson** [comment]
Since it appears to be working properly I'll close this for now. Feel free to reopen if you are still having this issue.

**Comment by numandev1** [comment]
@NickCulbertson from docs `format` is in string format https://www.audiokit.io/AudioKit/documentation/audiokit

![Screenshot 2023-11-06 at 2 36 59 AM](https://github.com/AudioKit/AudioKit/assets/36044436/aa539e36-d191-4392-870d-9e8b16720bec)

also getting this warning
![Screenshot 2023-11-06 at 2 37 28 AM](https://github.com/AudioKit/AudioKit/assets/36044436/b83d0a08-4c9b-4d9c-9d49-927c3f5da12a)

**Comment by numandev1** [comment]
@NickCulbertson note i am using cocoapod

**Comment by NickCulbertson** [comment]
Try deleting derived data and updating to a newer version of AudioKit. I think the docs are wrong as the method I posted works natively on the latest version of AudioKit and that's how the tests use it. 

https://github.com/AudioKit/AudioKit/blob/82cab9d4c168b5b03b67e2ff099819f589b530f7/Tests/AudioKitTests/Node%20Tests/Player%20Tests/AudioPlayerFileTests%2BRealtimeContent.swift#L443 

https://github.com/AudioKit/AudioKit/blob/82cab9d4c168b5b03b67e2ff099819f589b530f7/Sources/AudioKit/Audio%20Files/Format%20Converter/FormatConverter%2BCompressed.swift#L77

**Comment by NickCulbertson** [comment]
`note i am using cocoapod`

Okay that might be the issue. They have switch to using Swift Package Manager for AudioKit 5. I'm not sure if you can configure the pod file to grab the latest github tag.

**Comment by numandev1** [comment]
@NickCulbertson thanks for you response, i am using `5.1.0` audiokit version from cocoapod, I don't wanna use swift package manager as I am making react native package https://github.com/numandev1/react-native-compressor

can you tell me the workaround using format like this `.m4a`

**Comment by NickCulbertson** [comment]
They dropped support for cocoapods in Xcode 13. Since that version can’t really be updated and you don’t want to use SPM, maybe you could just copy the 4 newest FormatConverter files into your project. On Nov 5, 2023, at 5:14 PM, Numan ***@***.***> wrote:﻿
@NickCulbertson thanks for you response, i am using 5.1.0 audiokit version from cocoapod, I don't wanna use swift package manager as I am making react native package https://github.com/numandev1/react-native-compressor
can you tell me the workaround using format like this .m4a

**Comment by numandev1** [comment]
going to copy these 4 files, thanks a lot for your help ❤

**Comment by numandev1** [comment]
@NickCulbertson 
this is my code
```
 let outputMp3Path = Utils.generateCacheFilePath("m4a")
            
            let oldUfileUrlRL = URL(string: fileUrl)!
            let newURL = URL(string: outputMp3Path)!
            
            var options = FormatConverter.Options()
            options.sampleRate = 44100
            options.bitRate = 256000
         
            options.format = .m4a
            options.eraseFile = true
            options.bitDepthRule = .any
```

https://github.com/AudioKit/AudioKit/blob/82cab9d4c168b5b03b67e2ff099819f589b530f7/Sources/AudioKit/Audio%20Files/Format%20Converter/FormatConverter%2BCompressed.swift#L122

getting `Optional("Operation Stopped")` error on this line `try AVAssetReader(asset: asset)`

https://github.com/AudioKit/AudioKit/blob/82cab9d4c168b5b03b67e2ff099819f589b530f7/Sources/AudioKit/Audio%20Files/Format%20Converter/FormatConverter%2BCompressed.swift#L120

note: inputUrl is like this and I confirm wav file exist on this path
```
"/Users/apple/Library/Developer/CoreSimulator/Devices/9B4BAC0C-FE22-4C0E-BB73-66DD5CA6B091/data/Containers/Data/Application/7B2BCC11-84BD-49E7-9657-FB7D8CFA0529/tmp/2A46E221-BF71-4DA2-A04D-982C3436A8F3_TEMP.wav"
```

**Comment by numandev1** [comment]
fixed by appending file:// uri for output path `let outputMp3Path = "file://\(Utils.generateCacheFilePath("m4a"))"`

thanks
