### ISSUE TITLE
Mixing midi files and display result on MIDITrackView.

### ISSUE THREAD

**Issue by airakivela** [AudioKit/AudioKit#2865]
### Description

Hi.
Thanks for this useful SDK.
I am making midi mixing appliction now.
I imported 2 midi files and displays on each MidiTrackview.
I need to mix these 2 midi files and diplay results on new MIDITrackView.
I am new on this SDK.
How to do this and play mixed result?
Very thanks.

### Proposed Solution

Is there any solution??

### Describe Alternatives You've Considered

Hope you would provide any sample code..
Thanks again.

**Comment by emurray2** [comment]
Hi, thank you for your issue. With the way `MIDITrackView` is setup, it currently isn't possible to do this. However, I've been working on a new `MIDITrackView` for about over a year now which I hope to share with the AudioKit community soon.

For now, a workaround would be to write a new midi file using something like https://github.com/orchetect/MIDIKit/tree/main/Sources/MIDIKitSMF and then render it again through the old `MIDITrackView`.

**Comment by airakivela** [comment]
Hi. @emurray2 
Thanks for your reply.
I am new for this AudioKit and MIDIKit as well..
Very thanks for sharing any sample code.

**Comment by emurray2** [comment]
> Hi. @emurray2 Thanks for your reply. I am new for this AudioKit and MIDIKit as well.. Very thanks for sharing any sample code.

Tell you what, if everyone thinks this makes sense--I might just make the currently private AudioKit/MIDITrackView repo public once I clean up my code a bit. Then we can move each of these issues there and I'll keep them in mind as I go along. I'd say I'm pretty much almost up to speed with the current `MIDITrackView`. If you didn't know, we're probably going to remove the one from AudioKit UI and move it into its own repo. The AudioKit/MIDITrackView will be written purely in SwiftUI as well. I think the current one still uses some UIKit. Anyway, let me think about this over the weekend and I'll get back to you shortly. Thank you for bringing this feedback to my attention.
