### ISSUE TITLE
FFTTap seems choppy in updating

### ISSUE THREAD

**Issue by roboldham** [AudioKit/AudioKit#2867]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

Sonoma / XCode 15

Hi folks... thought I'd try here as Stackoverflow hit & miss, mostly miss

I'm running an FFTTap in an ObservableObject, and I am then accessing the fftData in a UIView (representable), that is updating a shader at 60fps, and then pulling in the data to modify the shader... but it seems the FFTTap is only doing its callback at about 5-10 times per second.... previous versions of Audiokit (eg 5.3) running with standard UIView were silky smooth an updating very quickly

Latest version of AudioKit uses a callback queue as such:

fft = FFTTap(mixer, bufferSize: UInt32(512), fftValidBinCount: .fiveHundredAndTwelve, callbackQueue: DispatchQueue.main, handler: {  _ in
                print("something")
        } )

I can find no documentation so this was a guess re callbackQueue.... is this the right way of doing it?

the print something is only firing 5-10 times per sec, so I am assuming this is why the .fftData is only updating at this rate too... so my shader looks choppy even though it is rendering at 60fps fine

Any tips?

Thanks!

**Comment by NickCulbertson** [comment]
Test it again with the latest AudioKit main branch release and see if that works better. I think this PR fixed it https://github.com/AudioKit/AudioKit/pull/2860

**Comment by NickCulbertson** [comment]
I'll close this for now. Feel free to reopen if you're still having this issue after the update.
