### ISSUE TITLE
Pitch Detection issues

### ISSUE THREAD

**Issue by herrDerToene** [AudioKit/AudioKit#2869]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

I have updated my app with the latest versions of AudioKit and SoundPipeAudioKit. I was previously on AudioKit version 5.5.4 and SoundPipeAudioKit version 5.5.3. I use PitchTap to analyze pitch.
While testing, I noticed that the accuracy for low frequencies has massively decreased (below 70 Hz). Often, the pitch was now recognized an octave too high. After reverting to the old versions, it works as usual again. I couldn't identify the error myself.

**Comment by NickCulbertson** [comment]
My guess would be that the buffer isn't large enough to fill with the data of those low frequency notes. If you are setting the buffer explicitly try increasing it to see if that yields a better result.

There was work done on the taps a while ago. I'm not sure if this is a side effect.

**Comment by NickCulbertson** [comment]
This may be related to https://github.com/AudioKit/AudioKit/pull/2860

**Comment by NickCulbertson** [comment]
Test it again with the latest AudioKit main branch release and see if that works better. I think this PR fixed it https://github.com/AudioKit/AudioKit/pull/2860

**Comment by NickCulbertson** [comment]
I'll close this for now. Feel free to reopen if you're still having this issue after the update.
