### ISSUE TITLE
404 file not found for Audio Kit package collection json 

### ISSUE THREAD

**Issue by danWorkUK** [AudioKit/AudioKit#2873]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

Hi, 

When trying acess https://swiftpackageindex.com/AudioKit.collection.json we get a 404 file not found.  Not a big problem as I can import the individual packages as needed, but this does not appear to be highlighted in the documentation. 

Cheers 

Dan 

### Crash Logs, Screenshots or Other Attachments (if applicable)

404 file not found

**Comment by NickCulbertson** [comment]
I think that might be the wrong URL. Does it work with https://swiftpackageindex.com/AudioKit/collection.json
