### ISSUE TITLE
Make name of MusicTrackManager public

### ISSUE THREAD

**Issue by misteu** [AudioKit/AudioKit#2878]
### Description

When I want to somehow identify music tracks on an `AppleSequencer` I need to build this / keep track of it myself. There is already a `name` property but for some reason it's `fileprivate`:

```swift
fileprivate var name: String = "Unnamed"
```

What it the reason for it being `fileprivate`? Can't we just make it usable for identification purposes?

### Proposed Solution

Change `fileprivate var name: String = "Unnamed"` in `MusicTrack.swift` to `public var name: String = "Unnamed"`

### Describe Alternatives You've Considered

Building my own wrapper for adding some id / name field.

**Comment by NickCulbertson** [comment]
I'm sure that would be fine. I would make it `open var` to match the other variables in the class. Can you submit a PR?

**Comment by florrablog** [comment]
Yes, makes sense! Alright, I will open a small PR later tonight.

**Comment by misteu** [comment]
Thanks for merging!
