### ISSUE TITLE
Add VisionOS support

### ISSUE THREAD

**Issue by klyusko** [AudioKit/AudioKit#2885]
### Description

Currently, it is not possible to use the Audiokit library for the VisionOS platform and Xcode 15.2

### Proposed Solution

Update lib with new VisionOS SDK support.

### Describe Alternatives You've Considered

-

**Comment by NickCulbertson** [comment]
This was mentioned in https://github.com/AudioKit/AudioKit/issues/2853 which is still open.

There is a branch in that thread: https://github.com/warpling/audiokit/tree/visionOS

**Comment by klyusko** [comment]
Thank you @NickCulbertson , but looks like branch also has issue 

`'loadTracks(withMediaType:)' is only available in iOS 15.0 or newer`

**Comment by ellbosch** [comment]
Also would like to share the same sentiment as @klyusko here—would be great to get proper visionOS support or at least have access to a working branch to get unblocked.

**Comment by NickCulbertson** [comment]
@ellbosch It looks like @wtholliday made a visionOS branch that might be worth checking out.  https://github.com/AudioKit/AudioKit/tree/visionOS-build
