### ISSUE TITLE
WatchOS supported

### ISSUE THREAD

**Issue by aronnelson** [AudioKit/AudioKit#2893]
### Description

I have noticed that there are native tuner apps running on WatchOS - and watch only. Did something change with regards to supporting audio for analysis? Can AudioKit run on WatchOS now?

Thanks

### Proposed Solution

Allow analysis of audio on watchOS

### Describe Alternatives You've Considered

I've looked and cannot find any source code that does analysis of audio.

**Comment by NickCulbertson** [comment]
As far as I know, AudioKit doesn't support WatchOS and it's not on the road map unless someone wants to take it on. There is an iOS/ Mac Catalyst tuner example in the Cookbook: https://github.com/AudioKit/Cookbook/blob/main/Cookbook/CookbookCommon/Sources/CookbookCommon/Recipes/MiniApps/Tuner.swift

You would have to import a local copy of the AudioKit package, remove all the methods not supported on watchOS, and it might work. It's uncharted territory.
