### ISSUE TITLE
MIDISampler issue with XCode 15.3RC

### ISSUE THREAD

**Issue by matts9000** [AudioKit/AudioKit#2901]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

The Drum Sequencer from the AudioKit Cookbook does not work anymore with XCode 15.3.

I know that you don't want to work with unreleased versions, but as I have seen this issue with beta versions and the current release candidate of XCode 15.3, so I think this will stay with the official release.

Versions:
- AudioKit 5.6.3 
- iOS/iPadOS 17.3 (also with 17.4)

What I found is that the issue seem to be connected to the MIDI handling in MIDISampler (in conjunction AppleSequencer). Playing single notes with MIDISampler play function works fine.

**Comment by NickCulbertson** [comment]
I'm on Xcode 15.0 and it's working there so it must be version specific. Is the Music Toy example working? Those examples are pretty similar. Are there any clues in the console?

**Comment by matts9000** [comment]
Yes, it this issue appears only with Xcode 15.3 - it does not show up to Xcode 15.2
I just tried with the Music Toy, and it has the same issue - no sound after start playing.

**Comment by NickCulbertson** [comment]
I just downloaded the Xcode beta and I'm getting the issue too. If you create a MIDICallback instrument it works, but not with `drums.midiIn`.  I'll add a MIDICallback in the Drum Sequencer as a workaround, but I'll leave the Toy example as-is for now since it might still be working in the release version. The workaround for Drum Sequencer should work on the Toy example too if the Xcode release borks things.

**Comment by NickCulbertson** [comment]
@michaelsteeber Is the DrumSequencer example working? That one uses AppleSequencer with a MIDICallback to play the instruments.

**Comment by NickCulbertson** [comment]
I'm downloading the new Xcode version now. If I can't figure it out, I'll update all the Cookbook examples to use the MIDICallback. There is also a second Sequencer class in AudioKit that isn't facing this issue. An example of that is in the Arpeggio recipe.

**Comment by NickCulbertson** [comment]
Are on the latest version of the Cookbook?

**Comment by NickCulbertson** [comment]
I just submitted a new PR to AudioKit that should fix the issue. I updated the enableMIDI method on AppleSequencer.

**Comment by NickCulbertson** [comment]
This should now be resolved in the latest version of AudioKit and the Cookbook.

**Comment by michaelsteeber** [comment]
Tested today, it works great.
