### ISSUE TITLE
Module 'AudioKit' has no member named 'AKBooster'

### ISSUE THREAD

**Issue by canbalkaya** [AudioKit/AudioKit#2906]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

I've been trying to boost the volume of the audio using AudioKit. Some of the articles shows a solution using AKBooster for my issue but Xcode says there is no such object called AKBooster in AudioKit.

I use AudioKit v5.6.3.

**Comment by NickCulbertson** [comment]
Nodes with the prefix AK were removed in AudioKit 5. I think the boost class wasn't migrated to version 5, but you could substitute it with another Node that has gain control like PeakLimiter.

**Comment by mahal** [comment]
@canbalkaya Thanks for submitting the issue. Could you please report where exactly you found references to `AKBooster`? We then can update documentation accordingly.
