### ISSUE TITLE
 "Framework 'CsoundLib' not found" error. AudioKit v2.3

### ISSUE THREAD

**Issue by punicappdev** [AudioKit/AudioKit#2909]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

I have an old objective-C project where is using AudioKit v2.3 https://github.com/AudioKit/AudioKit/releases/tag/v2.3.
Could not launch on Xcode 15.0.1. I've made all steps described in INSTALL-iOS.md. Tried as dynamic/static lib. But all the time got error "Framework 'CsoundLib' not found". How can I fix this error? 
Xcode 15.0.1 
OS Ventura 13.6.1

P.S. using the latest release not suitable - because API has changed globally. I need only launch project on Xcode 15.

### Crash Logs, Screenshots or Other Attachments (if applicable)

<img width="1409" alt="Screenshot 2024-04-15 at 22 01 14" src="https://github.com/AudioKit/AudioKit/assets/88042995/24da9c3e-a3c6-4c8e-8071-65ddc580e5de">

**Comment by aure** [comment]
AudioKit 2 is no longer supported, sorry.
