### ISSUE TITLE
Analog Synth X No Audio on iPad 2

### ISSUE THREAD

**Issue by AnthonyMcInvale** [audiokit/AudioKit#291]
I downloaded Analog Synth X from Apple Store.  I am not getting any audio on iPad 2.  I get audio from other apps including Yamaha Synth.  

Is there an issue with app on iPad 2?

**Comment by megastep** [comment]
I just tried the app on my iPad mini (which is essentially the same hardware as an iPad 2 with a smaller screen), and indeed there is no sound coming out. We'll have to take a closer look at this...

**Comment by aure** [comment]
We have updated the description on the iTunes store to say that iPad2 isn't supported.  Basically it would work if you brought the voices down, so we're adding support for that.  But, if you want to build from the source you can just bring the voice count down.  Let us know what voice count is low enough to make it work (or if that doesn't solve it).

**Comment by megastep** [comment]
@aure it would be nice to do that automatically depending on what kind of hardware is detected, I wonder if there's a way to do this reliably.

**Comment by megastep** [comment]
Actually I think we could just look at the CPU type for this. Likely `armv7` is for older 32-bit devices whereas `arm64` would cover the more recent and more capable 64-bit processors. We can probably determine that via `uname()`, assuming it is still safe to use.

**Comment by megastep** [comment]
Actually we don't even need to do that since these are different slices of the same binary. In Objective-C, you could check for the `__LP64__` macro for a 64-bit CPU, I'm assuming there's an equivalent in Swift. So basically we'd have different number of voices for 32-bit and 64-bit CPUs.

**Comment by AnthonyMcInvale** [comment]
I have been playing with the source code and was having the same problem running in debug mode.  I thought I was doing something wrong.  Can you point me to where the voice count is controlled?

**Comment by megastep** [comment]
I think it is done in the `Conductor` class.

**Comment by AnthonyMcInvale** [comment]
I had to go to voiceCount: 1 to get audio.  With one voice, the tone generated is not consistent and contains static.  Would the demand on cpu be less using an Objective C program calling your code?

**Comment by AnthonyMcInvale** [comment]
Never mind on my question above.  I was able to compile and execute other example programs on the iPad 2 without this audio issue.  HelloWorld, HelloObjectiveC, and MollyBChimes was not a problem from the 3.0.1 code.  I am assuming that the complexity of the synthesizer code is the problem for the iPad 2 and its 32 bit CPU.  FYI, there was no issues for the Analog Synth X on an iPad Air that I tried.

Thanks!

**Comment by aure** [comment]
Hi yeah, we're working on a version optimized for ipad2 so for now I'll close this issue.  Thanks very much for checking us out and the info that even voice count 1 has issues, that's helpful.

**Comment by aure** [comment]
you know on second thought, I'll leave it open just so other people realize we're working on it.

**Comment by padur74** [comment]
Same problem on Ipad 3

**Comment by davidbehrend** [comment]
I installed Analog Synth on a few older devices and experienced the same issues as mentioned above.
However, the same devices are more than capable of running other audio apps (Korg Gadget for example).

I'm wondering if this is a limitation of the framework? Or if this particular app hasn't been coded with optimisation in mind and could be made to work on older devices?

**Comment by aure** [comment]
@toydivision There are a couple of effects that we use in the synth that are CPU suckers.  But since we didn't test on older devices, it went unnoticed.  We're working to optimize everything in AudioKit.

**Comment by aure** [comment]
Just wanted to add to this issue that the new version of the app is in the store.  It works great on the ipad2.
