### ISSUE TITLE
AudioPlayer completionHandler

### ISSUE THREAD

**Issue by mahal** [AudioKit/AudioKit#2916]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

Running AudioKit Cookbok Recipe "Completion Handler" plays two files then stops. In Simulator as well as on actual device. 

I digged a bit round and found that `internalCompletionHandler` is called too late when status is already == .stopped and then completionHandler() isn't called. 

There seems to be some threading issue as the log always shows
`Thread Performance Checker: Thread running at User-interactive quality-of-service class waiting on a lower QoS thread running at Default quality-of-service class. Investigate ways to avoid priority inversions`

**Comment by NickCulbertson** [comment]
Yes, I'm seeing this issue in the Cookbook example too. I think the thread performance part has to do with the Timer running on the main thread. As for the completion handler, it seems like `status` is set to `.stopped` and is never set back to `.playing`. There are a lot of checks on `status` that are blocking methods from executing.

**Comment by mahal** [comment]
Thanks for the fix !-))
