### ISSUE TITLE
Can't import package:  https://github.com/AudioKit/Cookbook  into Swift Playgrounds on iPad

### ISSUE THREAD

**Issue by matthewrodgerson** [AudioKit/AudioKit#2918]
### iOS Version(s) Used to Build

iPadOS Version 17.4.1

### Swift 

Swift Playgrounds for iPadOS version 4.5.1, iOS 17.5 SDK

### Description

When trying to import package:

https://github.com/AudioKit/Cookbook

into Swift Playgrounds on iPad, I get the error 'Package does not have version tags.'
I think this is similar to 
https://github.com/AudioKit/AudioKit/issues/2643 

I also logged this on https://stackoverflow.com/questions/78496343/how-can-i-import-audiokit-cookbook-into-swift-playgrounds-on-ipad because I couldn't choose iPad as the build OS, but was advised there that I should try logging in Github and would be able to change to iOS aftewards.

### Crash Logs, Screenshots or Other Attachments (if applicable)

![Screenshot 2024-05-19 at 19 10 49](https://github.com/AudioKit/AudioKit/assets/12842795/b5880133-fe65-43f6-94d7-d6db2446c38c)

**Comment by aure** [comment]
The Cookbook is not a package, it is a project. It might be fun to create an iPad Playgrounds version of the Cookbook. To do so, you would need to import AudioKit, which is a package. This might be helpful: https://audiokitpro.com/drumpadplayground/
