### ISSUE TITLE
Unable to play audio through external speakers

### ISSUE THREAD

**Issue by ChopinDavid** [AudioKit/AudioKit#2919]
### macOS Version(s) Used to Build

macOS 14 Sonoma

### Xcode Version(s)

Xcode 15

### Description

I don't believe there is a way to write a failing test for this issue.

I am trying to make an application that takes audio from an external microphone (i.e. not the iOS device's built-in speaker, connected via USB-C), modulates it, and then feeds it back through an external speaker (i.e. not the iOS device's built-in speaker, connected via USB-C to auxiliary).

When the app is launched, the user is prompted to select a microphone (this can be either the built-in microphone, or my external microphone). Upon selecting, the user is able to speak through the selected mic and the modulated effects are output through the device's speakers. All of this works as expected.

Now, when I connect any sort of external speaker (whether it be AirPods over Bluetooth or computer speakers over my USB-C to auxiliary converter) none of the microphone audio comes through the external speakers. Other apps, such as YouTube, have their audio come through fine on these external speakers.

Here's the code I am using:

```swift
import Foundation
import AudioKit
import SoundpipeAudioKit
import AVFAudio

protocol MicrophoneDelegate {
    func promptUserToSelectDevice(_ devices: [Device])
}

class Microphone: ObservableObject {
    let engine = AudioEngine()
    var mic: AudioEngine.InputNode!
    var tap: BaseTap!
    var _delegate: MicrophoneDelegate?
    var delegate: MicrophoneDelegate? {
        get {
            return _delegate
        }
        set (newVal) {
            _delegate = newVal
            guard let input = engine.input else {
                return
            }

            guard let device = engine.inputDevice else {
                return
            }
            _delegate?.promptUserToSelectDevice(AudioEngine.inputDevices)
        }
    }
    
    init() {
        delegate?.promptUserToSelectDevice(AudioEngine.inputDevices)
    }
    
    func selectDevice(_ device: Device) {
        do {
            try AudioEngine.setInputDevice(device)
            setup()
        } catch let err {
            print(err)
        }
    }
    
    private func setup() {
        guard let input = engine.input else { fatalError() }
        mic = input
        let delay = Delay(mic)

        // Add some effects here
        
        tap = MyTap(delay) {
        }

        tap.start()
        try! engine.start()
    }
}

class MyTap: BaseTap {
    /// Callback type
    public typealias Handler = (AVAudioPCMBuffer, AVAudioTime) -> Void
    
    private var handler: Handler = { _, _ in }
    
    public init(_ input: Node, bufferSize: UInt32 = 4096, handler: @escaping Handler) {
        self.handler = handler
        super.init(input, bufferSize: bufferSize, callbackQueue: DispatchQueue.main)
    }
    
    override public func doHandleTapBlock(buffer: AVAudioPCMBuffer, at time: AVAudioTime) {
        handler(buffer, time)
    }
}
```

Is there some step I am missing to have an external speaker work with my application? Is this even possible?

**Comment by NickCulbertson** [comment]
Here are a couple things to try: 

1) Set your AVAudioSession like this [https://github.com/AudioKit/Cookbook/blob/main/Cookbook/Cookbook/CookbookApp.swift](https://github.com/AudioKit/Cookbook/blob/main/Cookbook/Cookbook/CookbookApp.swift)

2) Check if the engine needs to be restarted after a route change.
```
// SwiftUI
.onReceive(NotificationCenter.default.publisher(for: AVAudioSession.routeChangeNotification)) { event in
            switch event.userInfo![AVAudioSessionRouteChangeReasonKey] as! UInt {
            case AVAudioSession.RouteChangeReason.newDeviceAvailable.rawValue:
                reloadAudioMethod()
            case AVAudioSession.RouteChangeReason.oldDeviceUnavailable.rawValue:
                reloadAudioMethod()
            default:
                break
            }
        }
```

**Comment by ChopinDavid** [comment]
@NickCulbertson  So, neither of those solutions seemed to work for me. What I did find is that I have a USB-C webcam that always works as the "microphone". My proper microphone, which is also USB-C, does not usually work. What I have found is that if I run my application once  using the webcam as my "microphone" and then subsequently using the proper microphone, the subsequent run with the proper microphone does work. So you almost need to setup the app using my webcam first, and then suddenly the proper microphone works. Its one of the weirdest things I've seen.

So, this is more than likely an input issue, and not an output issue.

**Comment by ChopinDavid** [comment]
@NickCulbertson Do you know of any microphone specifications that make it so that the device doesn't play well with AudioKit/AVFoundation? For reference, [this is the microphone](https://www.amazon.com/Cubilux-Lavalier-Microphone-Recording-Interviewing/dp/B07ZQB2VF3/ref=asc_df_B07ZQB2VF3/?tag=hyprod-20&linkCode=df0&hvadid=693461287397&hvpos=&hvnetw=g&hvrand=3043725456746113613&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9022878&hvtargid=pla-1090113567272&mcid=08f92ce627e73acb8ea369d56535202e&gad_source=1&gbraid=0AAAAA9azOzMph3xbLNWdpAtRndLCpsbp9&gclid=CjwKCAjw9IayBhBJEiwAVuc3fkdxM7K7zHgzgzI-n47xEOouMqdSZ-PvqDCBFfR-2gIzkjZWmgn06xoChoMQAvD_BwE&th=1) my team is struggling to use and [this is the webcam](https://www.amazon.com/dp/B0CM949QRS/ref=twister_B0CN1YPYP1?_encoding=UTF8&th=1) we are seeing success with.

**Comment by NickCulbertson** [comment]
In the Cookbook there is an InputDeviceDemo in the WIP folder. It looks like when a new input is selected the engine is stopped and setPreferredInput is called on Settings.session (AVAudioSession.sharedInstance()). https://github.com/AudioKit/Cookbook/blob/main/Cookbook/CookbookCommon/Sources/CookbookCommon/Recipes/WIP/InputDeviceDemo.swift

It seems like something is or isn't being handled in the Settings class. That's where I would poke around.

```
/**
        @brief Select a preferred input port for audio routing.
     
        If the input port is already part of the current audio route, this will have no effect.
        Otherwise, selecting an input port for routing will initiate a route change to use the preferred
        input port. Setting a nil value will clear the preference.
    */
    @available(iOS 7.0, *)
    open func setPreferredInput(_ inPort: AVAudioSessionPortDescription?) throws
```

**Comment by ChopinDavid** [comment]
@NickCulbertson thanks, I'll take a look and see if my microphone works with this demo

**Comment by NickCulbertson** [comment]
Great! I'm glad that worked. Hopefully your solution will help others if they encounter this behavior.
