### ISSUE TITLE
AKmanager is gone in the new version and scrubbed from documentation

### ISSUE THREAD

**Issue by markostam** [audiokit/AudioKit#293]
First examples depend on AKManager. Just trying to learn my way around here. Any help appreciated.

**Comment by megastep** [comment]
The class was renamed to `AudioKit` in 3.0.1, and lost its sharedInstance() method. Everything else should be the same.

**Comment by markostam** [comment]
Thank you for the quick response. Tried to update code to reflect the new class. Still throwing this error. What's missing..?
![screenshot 2016-02-05 03 51 47](https://cloud.githubusercontent.com/assets/14855383/12841715/cdf6efb4-cbbb-11e5-9f5b-86327684ef12.png)

**Comment by megastep** [comment]
You don't need the `let audiokit ...` declaration anymore. You should use `AudioKit.output` and `AudioKit.start()` directly (these are now class methods).

**Comment by megastep** [comment]
Incidentally, you don't need to call `init()` explicitly in Swift, you can just do `let oscillator = AKOscillator()` above.

**Comment by markostam** [comment]
Still throws the same error even with updated syntax
![screenshot 2016-02-05 04 11 08](https://cloud.githubusercontent.com/assets/14855383/12842105/80e5bd1a-cbbe-11e5-8e88-5aa062174b52.png)

**Comment by megastep** [comment]
That's because you need to put this in the body of a method, you are doing it in the main body of a class, which is all wrong. If you're doing a view controller, you could do that inside of a viewDidLoad() method for instance.

**Comment by markostam** [comment]
cheers man that sorted me out. thanks for sticking with me, my first time playing with swift or ios development.

**Comment by megastep** [comment]
Thanks for making AudioKit your first try on the platform. :)
