### ISSUE TITLE
Disable earback (the feature where you hear your own voice in the headphones while recording)

### ISSUE THREAD

**Issue by tuananhdtu** [AudioKit/AudioKit#2930]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

I use Audiokit play video beat and record my voice
I want to record when not plug headset but i hear sound feedback
How i can disable when add engin.input to mixer to engine.output

**Comment by NickCulbertson** [comment]
Take a look at the Recorder example in the Cookbook. https://github.com/AudioKit/Cookbook/blob/main/Cookbook/CookbookCommon/Sources/CookbookCommon/Recipes/MiniApps/Recorder.swift

In that example, you pass the engine.input to the NodeRecorder, then pass it to a Fader where the gain is set to 0.

**Comment by tuananhdtu** [comment]
Thank you, i will try

**Comment by tuananhdtu** [comment]
Is there any other way to disable earback when recording?

I have audioplayer play beat mp3 and recording from mic, but no headset, i hear feedback u u u

**Comment by NickCulbertson** [comment]
If I'm understanding correctly, it sounds like your microphone is picking up the sound of the speaker causing feedback. There is not a built-in way that I know of to fix that other than having the user wear headphones. Are you hearing the feedback while recording or while playing back the audio? If you can share a code sample or example project, I'll take a look.

**Comment by tuananhdtu** [comment]
code sample it here
```
    engine = AudioKit.AudioEngine()
      playerAudio = AudioPlayer(url: URL(fileURLWithPath: localBeatPath ?? ""))
        micRecorder = createNodeRecorder(node: engine.input!)
     
        
        mixer = Mixer([playerAudio!, engine.input!])
        
        if !engine.avEngine.isRunning {
            engine.output = mixer
        }
        startAudioKit()
```

**Comment by NickCulbertson** [comment]
The feedback is because you are passing the mic input to the speaker. To avoid this you can pass the mic to a Fader Node and lower the volume while still capturing the input by a Node recorder. This is from the NodeRecorder example I posted before but with your method and variable names.
```
	let engine = AudioEngine()
    	let playerAudio = AudioPlayer()
    	var silencer: Fader?
    	let mixer = Mixer()
…

        guard let input = engine.input else {
            fatalError()
        }

        micRecorder = createNodeRecorder(node: input)
        
        let silencer = Fader(input, gain: 0)
        self.silencer = silencer
        mixer.addInput(silencer)
        mixer.addInput(player)
        engine.output = mixer
	
        do {
                try playerAudio.load(url: URL(fileURLWithPath: localBeatPath ?? ""))
        } catch {
                Log(error.localizedDescription, type: .error)
        }

	engine.start()     
```

**Comment by NickCulbertson** [comment]
You might be able to replace it with a Mixer() with the volume set to 0.On Sep 8, 2024, at 9:38 PM, tuananhdtu ***@***.***> wrote:﻿
Is there any way to not use fader, because audiokit currently I use xcframework to add to sdk, I tried to convert audiokitex to xcframework but it didn't work due to errors in the files written in C language

**Comment by tuananhdtu** [comment]
when using taae, i can record beats and mic, earback can be added or removed, but in audiokit, if set mixer volume = 0 then nothing can be recorded

**Comment by tuananhdtu** [comment]
taae is The Amazing Audio Engine

**Comment by NickCulbertson** [comment]
I meant to replace the Fader with another Mixer Node. It is being recorded because you are capturing the engine's input. The volume is then passed to a Mixer to lower the volume since ultimately all nodes need to be passed to the engine's output. ```     let engine = AudioEngine()
    	let playerAudio = AudioPlayer()
    	var silencer: Mixer?
    	let mixer = Mixer()
…

        guard let input = engine.input else {
            fatalError()
        }

        micRecorder = createNodeRecorder(node: input)
        
        let silencer = Mixer(input)
        silencer.volume = 0
        self.silencer = silencer
        mixer.addInput(silencer)
        mixer.addInput(player)
        engine.output = mixer
	
        do {
                try playerAudio.load(url: URL(fileURLWithPath: localBeatPath ?? ""))
        } catch {
                Log(error.localizedDescription, type: .error)
        }

	engine.start()  ```

**Comment by tuananhdtu** [comment]
thank you, i will try

**Comment by tuananhdtu** [comment]
thank you, i did it.
