### ISSUE TITLE
Audio output stops when switching from speaker to AirPods (and vice-versa)

### ISSUE THREAD

**Issue by jdanthinne** [AudioKit/AudioKit#2933]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

I'm building a metronome app, and all audio is working fine until I change the output (not by code, but as a user). If the session started on the speaker and I put my AirPods, audio stops, and same if I start from the AirPods and remove them.

As I've seen similar issue, I've tried to intercept `AVAudioSession.routeChangeNotification`, but it never gets fired…

### Crash Logs, Screenshots or Other Attachments (if applicable)

Here are the logs I see when changing output device:
```
HALSystem.cpp:2170   AudioObjectPropertiesChanged: no such object
AQMEIO_HAL.cpp:2720  timeout
AudioHardware-mac-imp.cpp:2706   AudioDeviceStop: no device with given ID
HALSystem.cpp:2170   AudioObjectPropertiesChanged: no such object
AQMEIO_HAL.cpp:2720  timeout
```

**Comment by NickCulbertson** [comment]
This is how I detect and respond to audio device changes: https://github.com/NickCulbertson/AUv3-Instrument/blob/7ab6c55599b10a5be1a967ef9b68edd141f6da86/Instrument/InstrumentEXS.swift#L86

You may also need to set up your AVAudioSession if you aren't already: https://github.com/NickCulbertson/AUv3-Instrument/blob/master/Instrument/InstrumentApp.swift

You might need to restart the engine and reload samplers and audio files after a route change.

**Comment by jdanthinne** [comment]
@NickCulbertson Thanks for the advice (and sorry for the late answer). I think I wasn't able to catch `AVAudioSession.routeChangeNotification` because I was on the simulator. I catch it on the iPad, and as you say, I restart the engine, reload the sampler, and when the sequencer is relaunched, sound is coming out the new output.
