### ISSUE TITLE
Sequencer App randomly gets distorted sound

### ISSUE THREAD

**Issue by harthorst** [AudioKit/AudioKit#2934]
### macOS Version(s) Used to Build

MacOS: 14.7

### Xcode Version(s)

Xcode 16.0

### AudioKit Version

AudioKit Version 5.6.4
AudioKitEX Version 5.6.0

### Description

Hello again :) 

I'm working on a drum engine which runs fine. But recently I discovered that on my iPhone 13 Mini it sometimes creates distorted sound. To get rid of it most of the time I simply have to kill the app and start it again.

The issue can be reproduced by:
1) starting the app
2) checking playback
3) if playback is ok: kill the app and go to 1)

Sometimes it seems the sequencer tracks are not synced properly. Sometimes it seems I hear the samples 2 times with a very short delay.
But that are just speculations.

Stopping and starting the sequencer has no effect. I also disabled the reverb branch for testing without success.

Can you give me any hints how to debug this? I already spend days in comparing values like buffer size, sample rates and object tree dumps.

I added some crappy recordings of the good and the bad case: [samples.zip](https://github.com/user-attachments/files/17268673/samples.zip)

### Crash Logs, Screenshots or Other Attachments (if applicable)
see: [tree-dump.txt](https://github.com/user-attachments/files/17268686/tree-dump.txt)

### Update
After removing anything optional in the node tree I discovered that the culprit might be the `CallbackInstrument`. 

After removing the last line of:

```
        callbackTrack = sequencer.addTrack(for: callback)
        masterMixer?.addInput(callback)
```

the glitch was gone and never came back. It does not matter whether the track is empty or even the callback implementation does nothing - just adding a CallbackInstrument to the master mixer produces those glitches.

**Comment by NickCulbertson** [comment]
I'm glad you got it working! I'm going to close this but feel free to reopen if it comes back.
