### ISSUE TITLE
possible to use AKMicrophone for 2 simultaneous inputs?

### ISSUE THREAD

**Issue by markostam** [audiokit/AudioKit#294]
possible to use akmicrophone (or any other method) for 2 simultaneous audio inputs? for example from both internal and external mic.

**Comment by aure** [comment]
Not currently, though that's certainly intriguing.

**Comment by markostam** [comment]
ok thanks. so AKMic will default to internal mic if nothing is plugged in and wired mic if something is plugged in correct?

**Comment by aure** [comment]
Yeah. that's all it does for now.

**Comment by aure** [comment]
I'll close this issue, but I have it my head to think about multiple mics.

**Comment by markostam** [comment]
sounds good. would allow for some pretty awesome applications.
