### ISSUE TITLE
AKMIDI.openMIDIIn() throws exception on OSX

### ISSUE THREAD

**Issue by jdundee** [audiokit/AudioKit#295]
Hi

When attempting to call AKMIDI.openMIDIIn() with any named input (e.g. "Session 1", "iRig PRO") an exception is thrown at line 161 in the file AKMIDI.swift:

![screen shot 2016-02-06 at 16 08 51](https://cloud.githubusercontent.com/assets/17099241/12867684/00d1bcda-ccec-11e5-8c4e-367c17eda671.png)

Any help on this would be much appreciated, thanks.

**Comment by aure** [comment]
Thanks for finding this, will definitely check it out.

**Comment by jdundee** [comment]
I've noticed that unplugging some interfaces or disabling the network midi port in Audio MIDI setup can avoid the exception although it's difficult to know if there's a particular pattern. For example, disabling network MIDI allows me to use the iRig Pro but trying to use my MIDISport 2x2 still throws the execption.

**Comment by aure** [comment]
Hi there,  I am not sure if this got fixed through some other improvements over the last few months, but I just built a midi monitor for OSX and it seems to work.  Can you try again?  Here's a link to the most up-to-date code including a midi monitor for OSX.

https://github.com/audiokit/AudioKit/commit/c8094255454bdac581b7620556590e1b76b58202

**Comment by jdundee** [comment]
Hi Aure

Will do - I'll have a look over the weekend and get back to you. 

John.

**Comment by aure** [comment]
Actually I think I may have found something wrong.  I'll update this issue when/if I figure it out.  Working on it.

**Comment by jdundee** [comment]
Ok no problem.
John.

**Comment by aure** [comment]
Should be fixed on the develop branch:

https://github.com/audiokit/AudioKit/commit/7d00ba80c31b916e096d8097f7e7ca5026f719e9

**Comment by jdundee** [comment]
Thanks - I will have a look tomorrow.
