### ISSUE TITLE
Loading EXS24 file not locating resource

### ISSUE THREAD

**Issue by AnthonyMcInvale** [audiokit/AudioKit#298]
I am experimenting with loading an EXS24 file in an actual app and including in the app bundle.  I tried using a file that I provided without success.  Then tried the sawPiano1.exs file.  I was able to get app to locate the sawPiano1 file, but it references saw220.wav file.  I included the wav file in bundle, but I receive:
16:13:53.243 ERROR:    372: Failed to locate sample 'saw220.wav -- file:///Users/jeffcooper/Documents/code/Livid/minim/minim/Sounds/basicSamples/'
I receive same type error with my file. 
It appears to be an issue with the lack of folders in the bundle.  Any suggestions?

Thank you,
Anthony McInvale

**Comment by AnthonyMcInvale** [comment]
Never mind.  I found my problem.

**Comment by aure** [comment]
Glad you figured it out.  I think Jeff's info is embedded in the binary files but it shouldn't show up like that and I'm wondering what you did to fix it.  Good luck with your project and we'd love to see it when you're done.

**Comment by AnthonyMcInvale** [comment]
Nothing too complicated to fix it.  I have not had a need for a lot of resources in apps before.  I had to recreate the folder structure in the app bundle “Sounds/basicSamples” with the EWS and WAV files in their respective folders.  Everything worked as expected after that.

Thanks,
Tony

**Comment by eljeff** [comment]
Glad you figured it out. It drove me crazy until I figured out sometimes saving or exporting the instrument in Logic can rewrite the paths relative to the project. One of the following has to be part of the path to the sample that the instrument looks for:
"/Sounds/"
"/Sampler Files/"
"/Apple Loops/"
"/EXS Factory Samples/"
"/SoundFont Samples/"

Hope that helps.
-j
