### ISSUE TITLE
AKMixer.connect() throws exception if you don't call AudioKit.stop()

### ISSUE THREAD

**Issue by pcbeard** [audiokit/AudioKit#299]
Build AudioKit.framework for OSX, install in /Library/Frameworks. Run the attached command line swift script (aksporth) like this:

aksporth '440 0.1 sine'

Swift will abort() with this uncaught exception:

2016-02-18 10:45:47.849 swift[4127:626336] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10877'

If you change the function addGenerator() by uncommenting out the calls to AudioKit.stop()/start() then the script will work normally.

[aksporth.txt](https://github.com/audiokit/AudioKit/files/136759/aksporth.txt)

**Comment by aure** [comment]
What would you like to see different?  You can't change the signal chain while the engine is running.

**Comment by pcbeard** [comment]
At least not throwing an exception. Would it be possible to adopt swift error handling for these cases? Or do you think it's such an obvious error that it deserves an uncaught exception?

**Comment by aure** [comment]
good point!

**Comment by aure** [comment]
The mixer class is pretty straightforward if you want to have a go.

**Comment by pcbeard** [comment]
Another possibility would be to have the mixer stop the engine when nodes are added/removed, to avoid the error altogether. Would that be a reasonable approach?

**Comment by aure** [comment]
I feel like if we give the ability to change connections after the engine was started, someone might think they can do so smoothly, and undoubtedly there would be a disruption to the audio, so I'm not sure that's beneficial.  Do you have a preference?

**Comment by aure** [comment]
I followed your suggestion and stopped a started engine if a connection is attempted. It's in the Xcode7.3 branch that will get merged when 7.3 comes out of beta.

**Comment by pcbeard** [comment]
Thanks!
