### ISSUE TITLE
plugging in headphone jack on iMac causes exception

### ISSUE THREAD

**Issue by codebeaulieu** [audiokit/AudioKit#301]
I searched before adding this issue, hopefully it's not a duplicate.

I'm working on my first AudioKit project and I decided to put headphones on while working and my app started crashing, unplugging the headphones fixes the issues. I am able to consistently reproduce the error simply by plugging my headphones in.

AudioKit 3
iMac iMac (27-inch, Late 2013)
OSX El Capitan 10.11.4 Beta (15E39d)

Exception:

`2016-02-21 23:00:12.477 Synth[9325:2825291] 23:00:12.477 ERROR:    63: Error getting preferred stereo channels from device 74: 'who?'
2016-02-21 23:00:12.478 Synth[9325:2825291] 23:00:12.478 WARNING:  79: Error setting preferred stereo channels on device 74: 'who?'
2016-02-21 23:00:12.478 Synth[9325:2825291] 23:00:12.478 ERROR:    111: Error getting preferred channel layout from device 74: 'who?'
2016-02-21 23:00:12.478 Synth[9325:2825291] 23:00:12.478 WARNING:  133: Error setting preferred channel layout on device 74: 'who?'
2016-02-21 23:00:12.479 Synth[9325:2825108] 23:00:12.479 ERROR:    >aurioc> 807: failed: -10851 (enable 2, outf< 2 ch,      0 Hz, Int16, inter> inf< 2 ch,      0 Hz, Int16, inter>)
2016-02-21 23:00:12.479 Synth[9325:2825274] 23:00:12.479 ERROR:    237: CA_UISoundClientBase::StartPlaying: AddRunningClient failed (status = -66637).
2016-02-21 23:00:12.479 Synth[9325:2825108] 23:00:12.479 ERROR:    >aurioc> 807: failed: -10851 (enable 2, outf< 2 ch,  44100 Hz, Float32, non-inter> inf< 2 ch,      0 Hz, Int16, inter>)
2016-02-21 23:00:12.480 Synth[9325:2825108] 23:00:12.480 ERROR:    >aurioc> 807: failed: -10851 (enable 2, outf< 2 ch,  44100 Hz, Float32, non-inter> inf< 2 ch,      0 Hz, Int16, inter>)
2016-02-21 23:00:12.480 Synth[9325:2825108] 23:00:12.480 ERROR:    AVAudioEngineGraph.mm:2510: PerformCommand: error -10851
2016-02-21 23:00:12.525 Synth[9325:2825108] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10851'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b423e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010ae9cdeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b423cca +[NSException raise:format:arguments:] + 106
	3   libAVFAudio.dylib                   0x000000010d556e83 _Z19AVAE_RaiseExceptionP8NSStringz + 176
	4   libAVFAudio.dylib                   0x000000010d56828b _ZNK18AVAudioEngineGraph14PerformCommandER11AUGraphNodeNS_12ENodeCommandEPvj + 1571
	5   libAVFAudio.dylib                   0x000000010d571a5d _ZNSt3__110__function6__funcIZN13AUGraphParser34InitializeActiveNodesInOutputChainER18AVAudioEngineGraph14ETraversalModeR11AUGraphNodeRbE3$_8NS_9allocatorIS9_EEF16ETraversalStatusS7_P17AUGraphConnectionEEclES7_OSE_ + 231
	6   libAVFAudio.dylib                   0x000000010d572abf _ZNKSt3__18functionIF16ETraversalStatusR11AUGraphNodeP17AUGraphConnectionEEclES3_S5_ + 31
	7   libAVFAudio.dylib                   0x000000010d565098 _ZN13AUGraphParser18TraverseGraphNodesERK18AVAudioEngineGraph10EDirection10ERecursionR11AUGraphNodeP17AUGraphConnectionRKNSt3__18functionIF16ETraversalStatusS6_S8_EEE + 48
	8   libAVFAudio.dylib                   0x000000010d56518f _ZN13AUGraphParser18TraverseGraphNodesERK18AVAudioEngineGraph10EDirection10ERecursionR11AUGraphNodeP17AUGraphConnectionRKNSt3__18functionIF16ETraversalStatusS6_S8_EEE + 295
	9   libAVFAudio.dylib                   0x000000010d56614b _ZN13AUGraphParser34InitializeActiveNodesInOutputChainER18AVAudioEngineGraph14ETraversalModeR11AUGraphNodeRb + 833
	10  libAVFAudio.dylib                   0x000000010d5690af _ZN18AVAudioEngineGraph10InitializeEv + 1031
	11  libAVFAudio.dylib                   0x000000010d5a11c5 _ZN17AVAudioEngineImpl10InitializeEv + 29
	12  libAVFAudio.dylib                   0x000000010d5a06be _ZN17AVAudioEngineImpl5StartEPP7NSError + 22
	13  libAVFAudio.dylib                   0x000000010d5a065b -[AVAudioEngine startAndReturnError:] + 65
	14  AudioKit                            0x000000010a5ff4de _TTSf4d___TZFC8AudioKit8AudioKit5startfMS0_FT_T_ + 94
	15  Synth                               0x000000010a1932db _TFC5Synth19SynthViewController10initializefS0_FT_T_ + 3307
	16  Synth                               0x000000010a19212d _TFC5Synth19SynthViewController11viewDidLoadfS0_FT_T_ + 125
	17  Synth                               0x000000010a1923b2 _TToFC5Synth19SynthViewController11viewDidLoadfS0_FT_T_ + 34
	18  UIKit                               0x000000010bb8ef98 -[UIViewController loadViewIfRequired] + 1198
	19  UIKit                               0x000000010bbd3651 -[UINavigationController _layoutViewController:] + 54
	20  UIKit                               0x000000010bbd3f26 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 462
	21  UIKit                               0x000000010bbd4098 -[UINavigationController _startTransition:fromViewController:toViewController:] + 126
	22  UIKit                               0x000000010bbd52f1 -[UINavigationController _startDeferredTransitionIfNeeded:] + 890
	23  UIKit                               0x000000010bbd63af -[UINavigationController __viewWillLayoutSubviews] + 57
	24  UIKit                               0x000000010bd7cff7 -[UILayoutContainerView layoutSubviews] + 248
	25  UIKit                               0x000000010baaf4a3 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
	26  QuartzCore                          0x000000010e85559a -[CALayer layoutSublayers] + 146
	27  QuartzCore                          0x000000010e849e70 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
	28  QuartzCore                          0x000000010e849cee _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	29  QuartzCore                          0x000000010e83e475 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
	30  QuartzCore                          0x000000010e86bc0a _ZN2CA11Transaction6commitEv + 486
	31  QuartzCore                          0x000000010e86c37c _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
	32  CoreFoundation                      0x000000010b34f367 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	33  CoreFoundation                      0x000000010b34f2d7 __CFRunLoopDoObservers + 391
	34  CoreFoundation                      0x000000010b34484c CFRunLoopRunSpecific + 524
	35  UIKit                               0x000000010b9f37cd -[UIApplication _run] + 402
	36  UIKit                               0x000000010b9f8610 UIApplicationMain + 171
	37  Synth                               0x000000010a196d1d main + 109
	38  libdyld.dylib                       0x000000010f4a292d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by aure** [comment]
Yes, that's new, thanks for bringing it up.

**Comment by aure** [comment]
So, it could be that this is not easily solvable.  When the simulator starts up, it populates the input and output sources from the current audio set up.  Then when you change that on your Mac, what the simulator points to is not updated and sending audio to the intended output results in a crash.  We should at least make a note about this.  What do you think?

**Comment by aure** [comment]
I will close this issue, but feel free to open it again if you need to.
