### ISSUE TITLE
Can we sequence MIDI notes?

### ISSUE THREAD

**Issue by JoshuaBThompson** [audiokit/AudioKit#302]
Can we add MIDI notes to the sequencer? Want to make a list of MIDI notes and then use the sequencer to loop / play them periodically. Is there an example of this anywhere? Currently only see sequencer example for pre-recorded sounds only.

**Comment by eljeff** [comment]
Howdy
Check out the MollyBChimes Example project. It sort of goes even further than midi notes, creating a midi instrument and triggering that, but you could also direct the midi to a midi out port. Try that out.

**Comment by JoshuaBThompson** [comment]
Thank you, exactly what I was looking for...

**Comment by aure** [comment]
Joshua, do you want to close this issue then?

**Comment by JoshuaBThompson** [comment]
Hi Aurelius,
Sorry, I should have done that earlier. Resolved.

**Comment by eljeff** [comment]
Who doesn't love a happy ending?!
Thanks!
-j

**Comment by Mistobaan** [comment]
I was interested in this too. What happened to the MollyBChimes example? seems has been removed?

**Comment by aure** [comment]
MollyBChimes is now known as the SequencerDemo I believe.
