### ISSUE TITLE
STK integration

### ISSUE THREAD

**Issue by knagle** [audiokit/AudioKit#305]
Are there any recommended strategies for integrating the STK with AudioKit? I'm currently using STK for iOS (https://github.com/thestk/stk/) with the Amazing Audio Engine but would like to make the switch to AudioKit in Swift. Alternatively, do you intend to port previous models such as Marimba, Vibes and Flute that existed in Audio Kit 2 but are currently missing from AudioKit 3?

**Comment by aure** [comment]
@PaulBatchelor and I will be working on a way to more easily integrate STK directly with AudioKit.

**Comment by PaulBatchelor** [comment]
@knagle We have just implemented the Mandolin STK instrument. 

Aure will attack the instruments you've mentioned at a later time. The hard stuff should be behind us now...

**Comment by aure** [comment]
I'll close this issue for now since we have one example in STK, but its on our radar to add those three soon.
