### ISSUE TITLE
Audio glitches when no other audio source is active

### ISSUE THREAD

**Issue by knagle** [audiokit/AudioKit#306]
I'm building an iOS objective-C app that links to the Swift AudioKit 3.0.1. The synth I'm currently working on is quite basic, and certainly not as complicated or processor intensive as Analog Synth X. However, the sound is quite glitchy even with relatively low processor loads. I have found that if another audio app is also running, such as GarageBand, then the audio cleans up and the synth behaves as expected. If I run the app by itself the audio starts to get glitchy once again. Is there something I'm missing?

**Comment by aure** [comment]
That's pretty bizarre!  At this point I have no idea why this is.  If you or anyone gets more clues, please post them to this issue thread.

**Comment by knagle** [comment]
The glitchy sound might be linked to my UI. If I tap a button for a popover menu the audio becomes very glitchy while the popover is presenting itself and for several seconds afterward. Basically whenever my app performs any animation I get audio glitches. Is there a audio thread priority setting I have missed?

**Comment by aure** [comment]
I'm going to close this issue since it doesn't appear to be on other apps, but if you still want my help, feel free to ask for it here or by email.
