### ISSUE TITLE
import AudioKit not working on Playground file

### ISSUE THREAD

**Issue by pablocaro** [audiokit/AudioKit#307]
first of all thanks for AudioKit! -- I followed the instructions on https://vimeo.com/152398360 and I was able to do "import AudioKit" in my view controller file. However, I created a playground file inside my project and when I write "import AudioKit" I got an error. - were you able to replicate?

**Comment by aure** [comment]
Playgrounds cannot use custom frameworks that are prebuilt.  You have to basically have the playground in the framework project itself.  You can download the source for the framework and open up the playground there.  Does that make sense? I can make a video if you like.

**Comment by pablocaro** [comment]
I see! thanks @aure! - if you can would be good the see the video, but no rush! :+1:

**Comment by aure** [comment]
I went ahead and created a screencast https://vimeo.com/157204402  I hope this helps and if so please close this issue.

**Comment by pablocaro** [comment]
Awesome!! thanks!
