### ISSUE TITLE
Can you update metronome operation while AudioKit is running?

### ISSUE THREAD

**Issue by JoshuaBThompson** [audiokit/AudioKit#308]
Is is possible to update the metronome operation while audiokit is running?

Trying to create a click track in the background while running a sequence. Using the metronome operation but can't seem to be able to update the metronome frequency without making AudioKit stop working.

I want to call an update method whenever the tempo is updated in the UI text field, but after updating the AudioKit output stops.

//AudioKit has already by started, trying to update the metronome operation generator with new frequency
func update(tempo: Double){
        if clickGenerator != nil{
            print("Stopping click generator")
            clickGenerator.stop()
            return;
            
        }
        
        clickOperation = AKOperation.metronome(tempo) // metronome needs frequency
        clickGenerator = AKOperationGenerator(operation: clickOperation)
        avAudioNode = clickGenerator.avAudioNode
        clickGenerator.start()
    }

**Comment by aure** [comment]
Yes you can, let me whip up an example.

**Comment by JoshuaBThompson** [comment]
Ok, thank you Aure!

**Comment by aure** [comment]
So, basically you need to replace the tempo constant with an AKOperation.parameters(parameterNumber) call.  Here is the code from a playground that increases the tempo over time:

```
import AudioKit
import XCPlayground

var currentFrequency = 1.0
let beep = AKOperation.sineWave(frequency: 480)

let trig = AKOperation.metronome(AKOperation.parameters(0))

let beeps = beep.triggeredWithEnvelope(
    trig,
    attack: 0.01, hold: 0, release: 0.01)

let generator = AKOperationGenerator(operation: beeps)
generator.parameters = [currentFrequency]

AudioKit.output = generator
AudioKit.start()
generator.start()

AKPlaygroundLoop(frequency: 5) {
    currentFrequency *= 1.1
    generator.parameters = [currentFrequency]
}

XCPlaygroundPage.currentPage.needsIndefiniteExecution = true
```

**Comment by aure** [comment]
If this wasn't sufficient, please feel free to reopen the issue, but I think for now this is resolved.

**Comment by JoshuaBThompson** [comment]
Great, this is exactly what I needed. Thank you for your help.
