### ISSUE TITLE
Hot swapping instruments

### ISSUE THREAD

**Issue by knagle** [audiokit/AudioKit#309]
Is there a safe strategy for swapping instruments in real time while an application is running?
I have been using AnalogSynthX conductor and a similarly created conductor for a polyphonic instrument of AKPluckedString voices. My approach (ommiting instrument creation and some function calls) has been:

AudioKit.stop()
// create PluckedString instrument 
...
// set the audioKit output
AudioKit.output = reverbMixer // from PluckedString instrument
// half second timer before turning audio back on
...
AudioKit.start()

Later, when I want to swap to the AnalogSynthX instrument I use:
AudioKit.stop()
// create AnalogSynth instrument 
...
AudioKit.output = reverbMixer // from AnalogSynthX instrument
// half second timer before turning audio back on
...
AudioKit.start()

I hear an audio glitch sound and get a couple of log messages:
Could not find function called '\240'.
Stack is empty.
I think this has something to do with the MoogFilterSection, because if I remove that variable from AnalogSynthX entirely, they will swap nicely. The Plucked string instrument will always swap nicely, but the AnalogSynthX instrument does not, unless the MoogFilterSection is removed. I wonder if has to do with these lines in AnalogSynthX:
        self.avAudioNode = output.avAudioNode
        input.addConnectionPoint(self)
Any help would be greatly appreciated.

**Comment by aure** [comment]
Yeah, it seems like things based off of AKOperations do not react well to starting and stopping AudioKit.  Good catch, I'll look into it.

**Comment by aure** [comment]
Is there any way you can share the code with me?   In general I am not sure that its a very good idea to stop and start AudioKit, but if you do, you should probably stop all of the nodes, including processing nodes before stopping to avoid glitches.

**Comment by knagle** [comment]
I will see if I can write a quick test project demonstrating the behaviour. Our software requires a hardware controller to work, so sending you the code for our project wouldn't be much use.

**Comment by aure** [comment]
@knagle I am not sure what I can really do about this without more information.  I'm happy to address it again with more info or a sample project to look at it, so feel free to re-open the issue if need be.
