### ISSUE TITLE
Error in Playground Node Output Plot & Node FFT Plot

### ISSUE THREAD

**Issue by magge73** [audiokit/AudioKit#311]
Hi, first of all: great library - thanks!!!

I get an error in the node fft plot playground for the AKMixer object 'mixer':

let plot = AKNodeFFTPlot(mixer)
Cannot convert value of type 'AKMixer' to expected argument 'NSCoder'

Similar error for node output plot, AKAudioPlayer 'player':
let plot = AKNodeOutputPlot(player)
Cannot convert value of type 'AKAudioPlayer' to expected argument 'NSCoder'

Build suceeded for iOS 9  target with XCode 7.2.1

**Comment by aure** [comment]
I think this has to do with making plots usable in interface builder.  If you're making the plots programmatically, try adding the frame: declaration so that you're using this initializer:

    public init(_ input: AKNode, frame: CGRect)

It would be something like 

   let plot = AKNodeFFTPplot(mixer, CGRect(...))

Let me know if that helps.

**Comment by ianrahman** [comment]
Seconding this problem. It seems `EZAudioPlot` isn't initialized correctly when passed only a Node, which is the problem in the Node Output and FFT Plot-related playgrounds.

**Comment by aure** [comment]
In the Xcode 7.3 branch I have both of these playgrounds working, so you can either check it out or wait for it to get merged to master when 7.3 comes out of beta.

**Comment by aure** [comment]
Closing since we merged the fixes in to master with release 3.1
