### ISSUE TITLE
Support for audio streaming

### ISSUE THREAD

**Issue by pcbeard** [audiokit/AudioKit#314]
The project https://github.com/tumtumtum/StreamingKit has a nice abstraction for audio sources, be they files or network streams. Would it be possible to add support to AKAudioPlayer to process audio http streams? StreamingKit makes extensive use of AUGraph to convert a network stream into a canonical LPCM format before playing it. I'd like to figure out a way to do the same thing, but to pass the resulting stream of samples through an AKNode.

**Comment by aure** [comment]
I don't think extending AKAudioPlayer is the way, but maybe make a new AKStreamingAudioPlayer that utilized StreamingKit.  This would be a great addition to AudioKit.

**Comment by aure** [comment]
After diving into StreamingKIt for some time, I think that the first step would actually have to be on the StreamingKit side to support output to an AVAudioEngine node.  Once that were done it would be easy to implement in AudioKit.  Perhaps you can encourage tumtumtum to do so?

**Comment by joshbruhin** [comment]
I need to add this functionality (unless streaming support has already been added?). Thing is, I know virtually nothing about audio and just a little bit about AudioKit. Any chance you can point me in the right direction? I know it makes sense to capture the stream and feed it to an AKAudioNode (not sure using StreamingKit makes sense, it seems to be not well used/supported these days). Any help appreciated!

**Comment by aure** [comment]
Hasn't been added.  I know nothing about streaming so to me it sounds pretty difficult.
