### ISSUE TITLE
AudioKit build problem

### ISSUE THREAD

**Issue by blazejchwiecko** [audiokit/AudioKit#317]
Hello!

After last Xcode update to 7.3 version. My project with AudioKit is failing to build. What I'm  getting is compiler error saying: "Module file was created by an older version of complier; rebuild 'AudioKit' and try again: some_path/Project's name/Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/arm64.swiftmodule". I removed AudioKit from pod file and added it again. I tried to clear product and build folder but I doesn't help.  Is there any chance I can fix it by myself or should I wait for new version build with new Xcode?

**Comment by miwanski** [comment]
Hi,

first thing I'd do in that case is confirm I'm using the 7.3 developer tools installed and selected (Xcode preferences -> Locations -> Developer Tools), and then try building it manually, without using Cocoapods.

Regards,
Michal

**Comment by blazejchwiecko** [comment]
OK. I downloaded whole package from your website open example project and build it. I copied .framework file and pasted it to pod/AudioKit and replaced the old file and it's working. :)

**Comment by miwanski** [comment]
Glad it worked for you! That's one of the main reasons I avoid using Cocoapods.

Oh and I'm not Aure, just a random watcher. ;)

Cheers!

**Comment by aure** [comment]
The dream of any toolkit developer is that users help each other get through issues, thanks so much Michal!

**Comment by miwanski** [comment]
My pleasure, Sir. Keep up the great work!
