### ISSUE TITLE
Module file was created by an older version of the compiler; rebuild 'AudioKit' and try again

### ISSUE THREAD

**Issue by palatov** [audiokit/AudioKit#321]
Hi, I am trying to add AudioKit to a new project, started from scratch and getting this error when adding import line to my viewController. I am using cocoapods and xcode 7.3.

**Comment by aure** [comment]
This will be solved when we update Cocoapods to the 7.3 version of the code (currently on develop) when we do the next release.  The next release is about a week away.  Till then do you think you could build from source?

**Comment by palatov** [comment]
Hi Aure, thanks for your respond. I have started another project and dragged AudioKit.framework from source folder to new project's embedded binaries like it was shown in the tutorial, however I've got the same errror afterwards. Am I doing something wrong here?

**Comment by eirikurorri** [comment]
For Carthage users running into the same problem: If you're willing to switch over to the develop branch , you can do it by pointing your Cartfile to it like so:

`github "audiokit/AudioKit" "develop"`

**Comment by aure** [comment]
Cocoapods has been updated to v3.1
