### ISSUE TITLE
No reading from AKFrequencyTracker on AKMicrophone

### ISSUE THREAD

**Issue by blerchy** [audiokit/AudioKit#322]
Hi! I'm having an issue with tracking frequency on the microphone. I'm using iOS, and whenever I run the code below, it seems to just read _nothing._

I'm not sure if I just don't understand how AudioKit is supposed to work, but Googling didn't really help with the issue. I've tried modifying line 41 in `AudioKit.swift` but that didn't yield any results. I'm sure it's just something to do with my misunderstanding of how AudioKit works. :confused:

```swift
import UIKit
import AudioKit

class ViewController: UIViewController {

    @IBOutlet weak var frequencyLabel: UILabel!
    @IBOutlet weak var amplitudeLabel: UILabel!
    
    let minimum: Double = 60
    let maximum: Double = 560
    
    var timer = NSTimer()
    let microphone = AKMicrophone()
    var tracker: AKFrequencyTracker?
    var debugIncrement = 0
    
    override func viewDidLoad() {
        super.viewDidLoad()
        tracker = AKFrequencyTracker(microphone, minimumFrequency: minimum, maximumFrequency: maximum)
    }

    override func viewDidAppear(animated: Bool) {
        timer = NSTimer.scheduledTimerWithTimeInterval(1, target: self, selector: "measureFrequency", userInfo: nil, repeats: true)
        AudioKit.start()
        microphone.start()
    }
    
    func measureFrequency() {
        print("NSTimer Fired \(debugIncrement++)")
        print("microphone is on: \(microphone.isStarted)")
        
        if let frequency = tracker?.frequency {
            print("get frequency: \(frequency)")
            frequencyLabel.text = "\(frequency)"
        } else {
            frequencyLabel.text = "Problem"
        }
        
        if let amplitude = tracker?.amplitude {
            amplitudeLabel.text = "\(amplitude)"
        } else {
            amplitudeLabel.text = "Problem"
        }
    }


}
```

Thank you in advance!

**Comment by aure** [comment]
You have to hook up the microphone.  I'm suprised Google didn't help you find this:

https://groups.google.com/forum/#!topic/audiokit/L9tb9TRL9bs

Let me know if that fixes things.

**Comment by blerchy** [comment]
Hi @aure! Thanks for looking into this. I changed my file to this, and we're making progress.

```swift
//
//  ViewController.swift
//  Frequency Analyzer
//
//  Created by Matt Lebl on 2016-03-27.
//  Copyright © 2016 Matt Lebl. All rights reserved.
//

import UIKit
import AudioKit

class ViewController: UIViewController {

    @IBOutlet weak var frequencyLabel: UILabel!
    @IBOutlet weak var amplitudeLabel: UILabel!
    
    let minimum: Double = 60
    let maximum: Double = 560
    
    var timer = NSTimer()
    let microphone = AKMicrophone()
    var tracker: AKFrequencyTracker?
    var silence: AKBooster?
    var debugIncrement = 0
    
    override func viewDidLoad() {
        super.viewDidLoad()
        tracker = AKFrequencyTracker(microphone, minimumFrequency: minimum, maximumFrequency: maximum)
        silence = AKBooster(tracker!, gain: 0)
    }

    override func viewDidAppear(animated: Bool) {
        timer = NSTimer.scheduledTimerWithTimeInterval(1, target: self, selector: "measureFrequency", userInfo: nil, repeats: true)
        AudioKit.output = silence
        AudioKit.start()
        microphone.start()
        tracker?.start()
    }
    
    func measureFrequency() {
        print("NSTimer Fired \(debugIncrement++)")
        print("microphone is on: \(microphone.isStarted)")
        
        if let frequency = tracker?.frequency {
            print("get frequency: \(frequency)")
            frequencyLabel.text = "\(frequency)"
        } else {
            frequencyLabel.text = "Problem"
        }
        
        if let amplitude = tracker?.amplitude {
            amplitudeLabel.text = "\(amplitude)"
        } else {
            amplitudeLabel.text = "Problem"
        }
    }


}
```

The problem, now, is that I'm just getting this from my debug console:

```
NSTimer Fired 0
microphone is on: true
get frequency: 0.0
NSTimer Fired 1
microphone is on: true
get frequency: 561.783447265625
NSTimer Fired 2
microphone is on: true
get frequency: 561.783447265625
NSTimer Fired 3
microphone is on: true
get frequency: 561.783447265625

...
```

Which is especially weird, as the maximum frequency to be detected is 560. I tried changing the max to something like `500`, and then it was just giving me readings of `501.136352539062`.

**Comment by aure** [comment]
That looks "correct" - this particular frequency detection algorithm generates a lot of false mins and maxes when it can't get a good read on a frequency in the middle.  We're going to be replacing it soon.  See if singing at 440Hz gives you approx 440 out.

**Comment by aure** [comment]
Make the min frequency like 300 and max 600 and sing 440 (A)...

**Comment by blerchy** [comment]
Okay, I've found something out. When I try to run on my physical device, it is stuck at `600.0` (with the new settings of min `300` and max `600`)

But when I run in on the _simulator_ it seems to work very well (It will give me an accurate reading when I sing A4), with the exception that _it plays back whatever the mic picks up,_ resulting in nasty feedback. (I had to mute my computer to test it)

If you can see why this is, please let me know. I know you're very busy and I don't want to send you on some wild goose chase.

Thanks for all the info you've provided so far. :blush:

**Comment by aure** [comment]
Are you using the develop branch?  In there I make sure that the microphone is enabled on the device, but on older versions you have to do so manually using: AKSettings.audioInputEnabled = true before starting AudioKit.

**Comment by blerchy** [comment]
That fixed it! There are no more problems, thank you so much @aure. :bowtie:
