### ISSUE TITLE
Are there list of parameters for AKOperation.parameters?

### ISSUE THREAD

**Issue by JoshuaBThompson** [audiokit/AudioKit#325]
I have this code:
let trig = AKOperation.metronome(AKOperation.parameters(0))

And when I look at the AKOperation params I see:
public static func parameters(i: Int) -> AKOperation {
        return AKOperation("(\(i+2) p)")
    }

I know that parameters(0) is the frequency but how do I find out what the other parameters are for AKOperation.parameters?

**Comment by aure** [comment]
parameters(0) is not the frequency.  Its just the first parameter and can be assigned to whatever you want. In this case you've made it the frequency by using it in the first argument of the metronome.  If you want something else to be controlled by the next parameter, use AKOperation.parameter(1) and then it becomes whatever.  I'll try to work on making this system less index-y and more friendly.

**Comment by JoshuaBThompson** [comment]
Ah, I see.
Thank you for clarifying that. I was racking my brain trying to figure out what was going on...

**Comment by aure** [comment]
You might also like the way I just updated the AutoPan playground as a way to name the parameters so that the code looks simpler:

https://github.com/audiokit/AudioKit/blob/develop/AudioKit/iOS/AudioKit/AudioKit.playground/Pages/AutoPan%20Operation.xcplaygroundpage/Contents.swift

**Comment by aure** [comment]
And btw, the i+2 from the code snippet you posted is just there because there are two behind the scenes parameters (triggers) that are reserved.

**Comment by Joshua-Thompson** [comment]
Hi Aure,
I see, thank you. I checked out the AutoPan code and will definitely use it for our work.
Thanks again for the help!
