### ISSUE TITLE
Is there a way to update the sineWave operation params live?

### ISSUE THREAD

**Issue by JoshuaBThompson** [audiokit/AudioKit#326]
I'm trying to make a boom sound and allow for a user to change the boom params (frequency).
Trying to use the updateFreq function to update the generator.parameters with the new frequency but the boom still keeps the initial freq parameters and does not change.

Any advice?

Trying this (left out some of the code that's not relevant)

class MyInstrumentVoice: AKVoice {
    var generator: AKOperationGenerator
    var currentFrequency = 120.0
    /// Create the synth kick voice
    override init() {
        let frequency = AKOperation.lineSegment(AKOperation.trigger, start: 120, end: 40, duration: 3)
        let volumeSlide = AKOperation.lineSegment(AKOperation.trigger, start: 1, end: 0, duration: 3)
        let boom = AKOperation.sineWave(frequency: frequency, amplitude: volumeSlide)
        
        
        generator = AKOperationGenerator(operation: boom)
        generator.parameters = [currentFrequency]
        
        
        super.init()
        avAudioNode = generator.avAudioNode//filter.avAudioNode
        
    }
    
    func startGen(){
        generator.start()
    }
    
    func updateFreq(freq: Double){
        currentFrequency = freq
        generator.parameters = [currentFrequency]
    }
.
.
.
.

**Comment by aure** [comment]
Looks like you're changing the parameters, but never referencing them in your operation code.  I also don't see where you trigger the generator.  Don't forget to trigger like this: 
http://audiokit.io/playgrounds/iOS/Linear%20and%20Exponential%20Segment%20Operations/

and change parameters like:
https://github.com/audiokit/AudioKit/blob/develop/AudioKit/iOS/AudioKit/AudioKit.playground/Pages/AutoPan%20Operation.xcplaygroundpage/Contents.swift

**Comment by JoshuaBThompson** [comment]
Great, the examples you provided were exactly what I needed.
I left out the triggering code in the example code I referenced.
