### ISSUE TITLE
Cannot assign AKOperation.lineSegment to AKOperationGenerator.parameters

### ISSUE THREAD

**Issue by JoshuaBThompson** [audiokit/AudioKit#327]
Trying to use AKOperationGenerator parameters to update sineWave lineSegment frequency (frequency starts and ends at some value over duration).
But seems like parameters only accept Double values (tried to convert lineSegment to Double but no dice).

Are parameters limited to Double values?

![screen shot 2016-04-02 at 11 56 47 am](https://cloud.githubusercontent.com/assets/11626839/14228450/43a40c52-f8ca-11e5-8bdb-8840a5d4f310.png)

**Comment by JoshuaBThompson** [comment]
Looks like my understanding of the AKOperation.parameters was a little off.
I was able to achieve the desired results using the code below. Although, it seems like it only works when I trigger the generator THEN update the parameters. It doesn't seem to work by updating the parameters then triggering the generator.

![screen shot 2016-04-02 at 6 16 51 pm](https://cloud.githubusercontent.com/assets/11626839/14230107/5275b4d0-f8ff-11e5-890c-e6162b56baf8.png)

**Comment by JoshuaBThompson** [comment]
Looks like my understanding of the AKOperation.parameters was a little off.
I was able to achieve the desired results using the code below. Although, it seems like it only works when I trigger the generator THEN update the parameters. It doesn't seem to work by updating the parameters then triggering the generator.
![screen shot 2016-04-02 at 6 20 58 pm](https://cloud.githubusercontent.com/assets/11626839/14230117/e9b3fbe0-f8ff-11e5-8f8b-bc3eb457c745.png)

**Comment by aure** [comment]
I'm glad you got something to work, but that's pretty odd behavior that I wouldn't have expected.  I'll keep this issue open while I investigate.

**Comment by JoshuaBThompson** [comment]
Ok, thank you Aure.

**Comment by aure** [comment]
Can you email me or gist the code from above?

**Comment by JoshuaBThompson** [comment]
Hi Aure,
Attached is the ViewController.swift file that I'm using.
You need to add some buttons / textfields on your storyboard and connect
them to the IBoutlets / actions on my file, but otherwise should be good to
go:)

On Wed, Apr 6, 2016 at 9:53 AM, Aurelius Prochazka <notifications@github.com

**Comment by JoshuaBThompson** [comment]
Just e-mailed you :)

**Comment by aure** [comment]
Thanks very much for the email.  You have found a bug in AudioKit indeed.  I fixed it on the develop branch.  Basically, calling trigger without any parameters was erasing all the parameters that you had set.  Now it doesn't do that.  Thanks very much!

**Comment by Joshua-Thompson** [comment]
My pleasure :) 
I'll checkout the latest branch.
