### ISSUE TITLE
delay node doesn't seem to work properly when assigning delay.time > 2 seconds

### ISSUE THREAD

**Issue by JoshuaBThompson** [audiokit/AudioKit#329]
Using a sineWave operation generator and delay effect to echo the beat like so, but instead of delaying boom for 10 seconds it only delays for 2. Tried this with multiple times > 2 and it always only maxes out to 2 seconds.
Am I doing this wrong?

```
override init()
{
frequency = AKOperation.lineSegment(AKOperation.trigger, start: 90, end: 60, duration: 0.1)
volume = AKOperation.lineSegment(AKOperation.trigger, start: 1, end: 0, duration: 0.1)
boom = AKOperation.sineWave(frequency: frequency, amplitude: volume)
generator = AKOperationGenerator(operation: boom)

delay = AKDelay(generator)
        delay.time      = 10.0 // seconds
        delay.feedback  = 0.5 // Normalized Value 0 - 1
        delay.dryWetMix = 0.5 // Normalized Value 0 - 1

super.init()
avAudioNode = delay.avAudioNode
}

// trigger code
func playDrum()
{
   generator.trigger() //triggers boom and delays but only for 2 seconds (not 10)
}
```

**Comment by aure** [comment]
I've updated the documentation to let the users know that the delay time is only up to 2 seconds on this stock delay.  AKVariableDelay allows you to set the maximum possible time, but I found a bug in that on my machine at least and it is not making sound.  I'll close this issue because it has to do with regular delay and 2 seconds, which is just the max.

**Comment by aure** [comment]
I've committed a working AKVariableDelay node to the develop branch that will let you have longer delay times by setting the maximumDelayTime property at initialization.

**Comment by JoshuaBThompson** [comment]
I see, thank you Aure. I'll try the new AKVariableDelay on the development branch.

**Comment by aure** [comment]
Its also on Master as of 3.1
