### ISSUE TITLE
Error when starting AudioKit when output is a mixer with no nodes

### ISSUE THREAD

**Issue by PumpMagic** [audiokit/AudioKit#332]
When attempting to start AudioKit with an output of a nodeless mixer, it dumps out the following error. Is this an invalid use case?
>2016-04-06 18:25:37.612 audiotest[1826:18529] 18:25:37.611 ERROR:    AVAudioEngineGraph.mm:2607: PerformCommand: error -10877

I can reliably produce this error with the following code:
```
let mixer = AKMixer()
AudioKit.output = mixer
AudioKit.start()

let oscillator = AKMorphingOscillator()
oscillator.start()
mixer.connect(oscillator)
```
using AudioKit OS X on a late 2013 Macbook Pro running OS X 10.11.4 against master 93c3e.

This (presumably preferred) code with a rearranged AudioKit.start() works just fine:
```
let mixer = AKMixer()
AudioKit.output = mixer
        
let oscillator = AKMorphingOscillator()
oscillator.start()
mixer.connect(oscillator)
        
AudioKit.start()
```
Sorry if this question is answered in the docs! I wasn't able to find it under the docs for the AudioKit class or the AKMixer class.

**Comment by aure** [comment]
Yeah, use the code that works.  You don't want to be connecting sources after the engine has started.

**Comment by PumpMagic** [comment]
Thank you, @aure . Is this the kind of thing that warrants a change in documentation and/or error handling? In retrospect, I should have hit the mailing lists before posting it as an issue here - sorry about that.

**Comment by aure** [comment]
AudioKit 3 doesn't have the kind of beginner docs AudioKit 2 had, not because we're crusty and mean, just a question of time! :)  Would love to get some help with web site docs if anyone is willing.  Otherwise, it will come after this big project I am working on is done.
