### ISSUE TITLE
Changing input/output of a node at runtime (AKA rewiring)

### ISSUE THREAD

**Issue by oleiade** [audiokit/AudioKit#335]
Hi!

I'm trying to change the input and output of a node at runtime. For example in the case of an effect chain, in which you could change the effects order. I've been going through the Documentation, and dug through the source code but can't figure how to achieve something like that:

*initial declaration*
```swift
let delay = AKDelay(player)
let reverb = AKCostelloReverb(delay)
```

*later on: I'd like to do something like*
```
AudioKit.stop()
reverb.source = player
delay.source = reverb
```

Can you point me to a way of achieving that, even very hacky. 

Thanks!

PS: AudioKit rocks, keep up the good work folks!

**Comment by aure** [comment]
Rewiring is not recommended for most apps.  It's kind of like you are a guitarist with a pedalboard in front of you.  If you're playing live, you don't want to be reconnecting cables.   Instead, you keep everything plugged in but route the signal turning things on and off, or mixing effects in or out.  But, if you don't mind the down sides, you can stop AudioKit, recreate a brand new signal chain and start it again.

**Comment by oleiade** [comment]
Hey @aure thanks for your quick answer!

I'm actually trying to build an effect chain, and this effect chain should be reorderable, or at least, elements of it should replacable.

I have indeed explored the track of an immutable device chain, where I would recreate the whole chain every time in its new setup. However, to my knowledge the AKNode objects don't expose a copy constructor and that makes the operation much trickier, as I would like to keep the setup of existing effects. But my swift skills are still limited at the moment, and maybe I missed something!

Any ideas, recommendations that could bring me further on this track?
Thanks a lot!

**Comment by aure** [comment]
You bring up a lot of good ideas.  Some would take some serious re-architecture.  For instance, if we were to introduce the concept of node container that would stay in the signal chain but the internals could be replaced.  Good stuff, would be cool if it were there! :)  Also, if you want to figure out a way to make a node copyable, that would be welcomed I am sure.  I don't think it would be that difficult to make a copy of all the parameters.  

Finally, I'd love to see an integration with AudioBus.  I've been too busy with all the other stuff, but that's been on my todo list for over a year now!

**Comment by aure** [comment]
Looking at this more, I do think that the best we can offer at this point is to stop the engine and then rebuild the signal chain using a system of setting parameters and then calling them back. So, I'll close the issue, but if you need to reopen it and add new information, please don't hesitate to.

**Comment by oleiade** [comment]
@aure thanks for your support anyways!

I finally was able to create a DeviceChain that supports moving nodes around, by
- Implementing it as a completely immutable data structure
- Encapsulate the nodes I'm using in a parent type that implements a copy constructor
- Making sure the chain input node ``play()`` method is called after every restart of AudioKit

Would you be open to the following contributions (I can't take any engagement on time though):
  - Implementing a copy constructor on AKNode/AKToggeable children classes of the lib
  - Porting my device chain concept to the project as a AKNodeChain or something like that? I'm pretty sure I'm not the only one who's hit this problem.

I would also be really interested in participating in conception/development of nodes containers if that ever happens.

Let me know what you think,
Cheers!

Theo

**Comment by aure** [comment]
Sure I'd love to see what you've done and incorporate it into AudioKit.  Make a pull request!
