### ISSUE TITLE
Example for how to add tanh distortion to triangle wave?

### ISSUE THREAD

**Issue by Joshua-Thompson** [audiokit/AudioKit#339]
Trying to smooth out a triangle wave to make it look more like a sine wave (but don't want a sine wave).
![tanh](https://cloud.githubusercontent.com/assets/7103392/14406894/2b36d73a-fe6a-11e5-93c7-81e92b5eb57c.png)

However, when I try using the tanh distortion node on a triangleWave operation generator it just modifies the amplitude of the wave or widens it a bit. 
Using the code:
```swift
import XCPlayground
import AudioKit

//make triangle wave operation @ 86Hz
var triangleWave = AKOperation.triangleWave(frequency: 86.0, amplitude: 0.25)
var waveGen = AKOperationGenerator(operation: triangleWave)

//Tanh Distortion of triangle wave so make it look a little more like a sine wave
var distortion = AKTanhDistortion(waveGen, pregain: 0.5, postgain: 0.5, postiveShapeParameter: 0.5, negativeShapeParameter: 0.5)

AudioKit.output = distortion
AudioKit.start()

waveGen.start()
distortion.start()

let plotView = AKOutputWaveformPlot.createView()
XCPlaygroundPage.currentPage.liveView = plotView
XCPlaygroundPage.currentPage.needsIndefiniteExecution = true
```

This is what I see from the above code

![screen shot 2016-04-09 at 3 50 16 pm](https://cloud.githubusercontent.com/assets/7103392/14406932/fd79aad8-fe6a-11e5-8e78-2f2ec0d6c089.png)

Is this the correct way to tanh distort a triangleWave ?

**Comment by aure** [comment]
This must be a bug and I'll look at it, but if you really want that other curve, why don't you make it?  See the playground for general purpose oscillator where the custom curve is defined:  http://audiokit.io/playgrounds/General%20Purpose%20Oscillator/

**Comment by Joshua-Thompson** [comment]
Hi Aure, 
Thank you for that example. I made a custom wave that was pretty close to what I wanted.
However, I like using the AKOperation.triangleWave since I can use the triggerWithAttack operation that ends the waveform after the hold param is complete:
```swift
var boom = AKOperation.triangleWave(frequency: 80, amplitude: 1.0)
var boomTrigger = boom.triggeredWithEnvelope(AKOperation.trigger, attack: 0.01, hold: 0.2, release: 0.1)
``` 
I know I can do this with the AKOscillator using the amplitude envelop but it requires me to manually call the start and stop methods of the amplitude envelope which makes what I'm trying to do a little more complicated.

I'll wait to see what you found for the other issues I mentioned (clipper and tanh distortion) .....

**Comment by PaulBatchelor** [comment]
@Joshua-Thompson Hey Joshua!

This one is a "bug" that I think I fixed. It turns out that the sp_dist module was set up by default to distort a signal in the range [-32767, 32767] when really it should have been set up by default to process normalized signals in the range [-1, 1]. This problem is really just an artifact of the original Csound code it was ported from. 

I have put the new changes in soundpipe dev branch, so Aure can put those changes in.

**Comment by PaulBatchelor** [comment]
Okay, this produces errors on valgrind. Now we're getting somewhere. I think there's some uninitialized variable somewhere:

```
#include <stdio.h>
#include "soundpipe.h"

typedef struct {
    sp_bltriangle *tri;
    sp_clip *clp;
} UserData;

void write_clip(sp_data *sp, void *ud) {
    UserData *udp = ud;
    SPFLOAT out, tri;
    sp_bltriangle_compute(sp, udp->tri, NULL, &tri);
    sp_clip_compute(sp, udp->clp, &tri, &out);
    sp->out[0] = out;
}

int main() {
    UserData ud;
    sp_data *sp;
    sp_create(&sp);

    sp_bltriangle_create(&ud.tri);
    sp_clip_create(&ud.clp);

    sp_clip_init(sp, ud.clp);
    ud.clp->lim = 0.4;
    ud.clp->meth = 0;
    sp_bltriangle_init(sp, ud.tri);
    *ud.tri->amp = 1.0;
    sp_process(sp, &ud, write_clip);

    sp_clip_destroy(&ud.clp);
    sp_bltriangle_destroy(&ud.tri);

    sp_destroy(&sp);
    return 0;
}

```

**Comment by aure** [comment]
@PaulBatchelor I think you posted that message to the wrong issue :)

**Comment by aure** [comment]
@Joshua-Thompson I believe this is fixed in the develop branch. I ran your playground and the parameters now shape the sound a lot.  Thanks a lot!

**Comment by Joshua-Thompson** [comment]
I see, ok I'll download the new code from the dev branch.
Thank you both!

**Comment by JoshuaBThompson** [comment]
Just wanted to say that it works great now, thanks for resolving that bug :)
