### ISSUE TITLE
Possible clipper bug?

### ISSUE THREAD

**Issue by Joshua-Thompson** [audiokit/AudioKit#340]
Trying to clip a triangle wave to make it look at little more like a sine wave.

```swift
import XCPlayground
import AudioKit

//make triangle wave generator
var triangleWave = AKOperation.triangleWave(frequency: 86, amplitude: 0.5)
var waveGen = AKOperationGenerator(operation: boom)

//Distortion using clipper
var clipper = AKClipper(waveGen)
clipper.limit = 0.4
clipper.clippingStartPoint = 0.3
clipper.method = 0 // tried method = 2 for tanh but didn't work the way I expected

AudioKit.output = clipper
AudioKit.start()

waveGen.start()
clipper.start()

XCPlaygroundPage.currentPage.liveView = plotView
XCPlaygroundPage.currentPage.needsIndefiniteExecution = true
XCPlaygroundPage.currentPage.needsIndefiniteExecution = true
```

However I see this:
![screen shot 2016-04-09 at 4 43 22 pm](https://cloud.githubusercontent.com/assets/7103392/14407121/39c27a86-fe72-11e5-8d22-6137c7375c63.png)

Am I doing something wrong?

**Comment by aure** [comment]
You're not doing anything wrong.  Investigating, thanks!

**Comment by Joshua-Thompson** [comment]
Ok, that was driving me crazy... thank you:)

**Comment by PaulBatchelor** [comment]
@aure I take it this is being generated in Sporth, and not Soundpipe?

**Comment by PaulBatchelor** [comment]
@Joshua-Thompson Thanks for pointing this out! What is the ideal waveform you are trying to achieve? The clip module in Soundpipe is a soft clipper intended to perceptually try to mask the clipping effects of audio signals. While they can make the signal sound better than hard clipping, the cost is often these uglier looking plots. While I don't fully claim to understand these algorithms, I believe these are the correct behaviors from the original clip opcode in Csound. 

If you're looking to "chop" the tops of the triangle waveform, you'll need a hard clipper, which can be produced by putting your signal through a max and min function in series. I have posted sporth code and plots in the Soundpipe bug that Aure. I am certain there's a way to achieve this in AudioKit.

**Comment by aure** [comment]
After Paul's changes, which I merged onto our develop branch.  Modes 1 and 2 of clip seem to be acting properly, but we are still getting weird behavior on mode 0.  ANyway, I think mode 2 will work for your problem, but lets keep this issue open until mode 0 is figured out.  I hate modes.  If anyone wants to help me out, lets at least turn this into an enumeration.

**Comment by aure** [comment]
We found that there was an initialization issue in method 0 that was fixable, but in general it wasn't worth it to have different clipping modes.  So, we chose the sine method (what was method=1) because it was just fine. :)  So, this issue is resolved by way of simplifying the code. I like that.  Thanks again Joshua.

**Comment by Joshua-Thompson** [comment]
Great, I checkout the new code. Thanks again!
