### ISSUE TITLE
Issue when trying to run in Objective-C project

### ISSUE THREAD

**Issue by olexl** [audiokit/AudioKit#342]
I got this error when tried to run my app with _AudioKit.framework_ embedded (not used in code, just added)

> dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
>   Referenced from: /Users/**********/Frameworks/AudioKit.framework/AudioKit
>   Reason: image not found
> 

Changing **Build Settings->Embedded Content Contains Swift Code** to **YES** resolved the issue.
Can you add information about this to _INSTALL.md_?

**Comment by narner** [comment]
@olexl If you're comfortable with adding it yourself and making a pull-request, feel free to. If you're not, I can add this note in the INSTALL.md file.

**Comment by megastep** [comment]
I think I'll do it myself, I'm gonna get the release ready for 3.1.1 anyway and might as well do it at the same time.

**Comment by megastep** [comment]
OK, added a blurb in INSTALL.md in develop, will be in 3.1.1

**Comment by olexl** [comment]
thanks
