### ISSUE TITLE
Can't import AudioKit framework

### ISSUE THREAD

**Issue by vladik-t** [audiokit/AudioKit#343]
Hi!
Having the latest OS X and Xcode (OS X 10.11.4 and Xcode 7.3)
But when I'm trying to install AudioKit framework exactly one-to-one as described in video it just doesn't work. When I write up "import AudioKit" in ViewController.swift page I have a message "No such module "AudioKit" and also I can't see this module in pop-up menu when i write just the first letters. What is wrong?
![123](https://cloud.githubusercontent.com/assets/18419956/14459698/7b5475e4-00ca-11e6-90f9-f8660de889b9.jpg)

**Comment by aure** [comment]
What happens when you try to build?  Would you like to do a screen share with me so that I can get you set up?  Email me directly and I can invite you to screenhero if you are not a member already.

**Comment by vladik-t** [comment]
Just send you a email

**Comment by aure** [comment]
Seeing as we got your playgrounds working, I'm thinking this could be a problem with your Xcode simulator set up.  Did you have any luck after our screenshare?  If so, let us know, and close the issue.

**Comment by vladik-t** [comment]
Just updating now another MacBook from Yosemite to El Captain. Next step
would be Xcode setup and AudioKit framework again. Let's see what we get
for this time )

вторник, 12 апреля 2016 г. пользователь Aurelius Prochazka написал:

**Comment by GoodVillager** [comment]
I was having the exact same issue. By installing AudioKit through Cocoapods, I've managed to make the import work. However, now I have a different error: linker command failed with exit code 1 (use -v to see invocation). Any help would be greatly appreciated.

<img width="908" alt="screen shot 2016-04-12 at 20 33 40" src="https://cloud.githubusercontent.com/assets/18430708/14478641/e7876884-00ed-11e6-8716-a2b8f70b914b.png">

**Comment by aure** [comment]
@GoodVillager I am sorry you're having problems.  I am not familiar with your error, but I am willing to do a screenshare if you want me to have a look at your situation personally.  Let me know and I can invite you to screenhero.

**Comment by vladik-t** [comment]
Just solve the problem
Step-by-step instructions:
1. Create a new Xcode project
2. Close the project 
3. Drag&Drop or copy AudioKit framework file into the project folder (where all project files store)
4. Run the project & add AudioKit framework in Project Navigator/General/Embedded Binaries
After these steps AudioKit framework is importing just fine

**Comment by aure** [comment]
So, this looks like a problem where some people's Framework search paths do not get updated when dragging in the framework or using the + button to include the framework from another location.  That's a great little fix to just copy the framework into the project directory.  I'm going to close this issue, even though GoodVillager added a related problem, that could be added as a separate issue if it persists or if using your solution here doesn't work.

**Comment by fridemar** [comment]
Hello, thank you for this promising framework. 

Perhaps it needs only a small step for the generous developer(s) of the framework:

Using Xcode Version 8.0 beta 4 (8S188o) I got the error:
"Module file was created by an older version of the compiler; rebuild AudioKit and try again."

Looking forward to the great potential of this framework.

**Comment by aure** [comment]
@fridemar Xcode betas are not supported.

**Comment by magicwave** [comment]
I just encountered this with Xcode 8. The problem for me was that I needed to build the framework target for (any) simulator for the AudioKit to be found by the playground.

Awesome work Aure!!!!
