### ISSUE TITLE
AudioKit OS X is not working

### ISSUE THREAD

**Issue by modulusMathews** [audiokit/AudioKit#344]
### __Info__:

I've tried running the HelloWorld example project, and when I toggle the button no sound emits. I've also tried following the installation video for 3.1, and still no sound. I'm also not getting any sort of errors. 😢

### __Specs__: 
- __Version__: 3.1
- __OS__: El Capitan 10.11.4
- __Processor__: 2.8GHz Intel Core i7
- __Graphics__: Intel Iris Pro 1536 MB

**Comment by narner** [comment]
This sounds a lot like this issue that was reported the other day: https://github.com/audiokit/AudioKit/issues/336

@modulusMathews, try switching to the develop branch and seeing if that helps at all
