### ISSUE TITLE
Crash after making to many convolutions 

### ISSUE THREAD

**Issue by blazejchwiecko** [audiokit/AudioKit#348]
Hello,
I'll start with what I want to achieve. I'm creating an app in which user gets surround effects based on his location in the room. I've done volume by simply changing player's volume. Right now I'm struggling with pan. I know HRTFs technique and convolutions and I'd really like to implement it here. I created 60 impulse response for each 6* in full angle. After that I'm creating convs this way

    for (_, angleURL) in hrtfs.enumerate() {
       let angleConvolution = AKConvolution.init(customPlayer.audioPlayer, impulseResponseFileURL: angleURL, partitionLength: 128)
       customPlayer.audioConvolutions.append(angleConvolution)
       let dryWetMixer = AKDryWetMixer(customPlayer.audioPlayer, angleConvolution, balance: 1)
       let helperMixer = AKMixer()
       helperMixer.connect(dryWetMixer)
       customPlayer.audioMixers.append(helperMixer)
    }

 and than I'm adding each of created AudioMixers to mainMixer and in a loop start each conv and player. App is working when I'm adding one, two players sometimes with three, four players. If there's more it crashes. The issue here is really weird, once in a while an app starts and works, but mostly it crashes with error

    AURemoteIO::IOThread (13)
    0 sp_conv_compute
    65 thread_start`.

and 

      AudioKit`sp_conv_compute:
           0x100556f3c <+0>:   stp    x28, x27, [sp, #-96]!
           0x100556f40 <+4>:   stp    x26, x25, [sp, #16]
           0x100556f44 <+8>:   stp    x24, x23, [sp, #32]
           0x100556f48 <+12>:  stp    x22, x21, [sp, #48]
           0x100556f4c <+16>:  stp    x20, x19, [sp, #64]
           0x100556f50 <+20>:  stp    x29, x30, [sp, #80]
           0x100556f54 <+24>:  add    x29, sp, #80              ; =80 
           0x100556f58 <+28>:  sub    sp, sp, #64               ; =64 
           0x100556f5c <+32>:  mov    x19, x1
           0x100556f60 <+36>:  str    x19, [sp, #32]
           0x100556f64 <+40>:  ldp    w12, w8, [x19, #36]
           0x100556f68 <+44>:  lsl    w24, w12, #1
           0x100556f6c <+48>:  str    x24, [sp, #24]
           0x100556f70 <+52>:  mul    w10, w8, w24
           0x100556f74 <+56>:  ldr    x9, [x19, #56]
           0x100556f78 <+60>:  add    x22, x9, w10, sxtw #2
           0x100556f7c <+64>:  ldr    w10, [x2]
           0x100556f80 <+68>:  ldrsw  x11, [x19, #28]
      ->  0x100556f84 <+72>:  str    w10, [x22, x11, lsl #2]`

and error here is

    AURemoteIO::IOThread(14):EXC_BAD_ACCESS(code=0,address=0x0)

Does it possible to make it work every time?

**Comment by narner** [comment]
Hi @blazejchwiecko, sounds like a cool project! Are you able to tell what specific line in your code the crash occurs at?

**Comment by blazejchwiecko** [comment]
Thanks. :) It's crashing just after calling conv.start(). 
    AudioKit.output = mixer
    AudioKit.start()
    for player in self.playersWithConvolution {
         for conv in player.audioConvolutions {
           conv.start()
        }
        player.audioPlayer.play()
    }

**Comment by aure** [comment]
So it works for one but not more?  I'm wondering if they are not getting connected to the output.  I could see multiple convolutions bogging down the system and even not making a sound after a while, but to just crash straight away makes me think they are not connected right.

**Comment by blazejchwiecko** [comment]
The weirdest thing here is that app is launching once in a while, for example I'm coding right now and I have to run it 4-5 times (cmd+R) before it'll boot properly. I wish it could start every time, this HRTFs creates super natural sound space. :) Removing some of middle points in HRTS (like leaving only convs for 0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330 degrees) makes app boots more often. That leads to conclusion that too many convs at the same time leads to this issue. Like I wrote before the error here is ```0 sp_conv_compute``` so it my by something under AudioKit?

**Comment by aure** [comment]
sp_conv_compute is the Soundpipe part of AudioKit doing the convolution math.  So its still AudioKit, just the underlying C.

**Comment by blazejchwiecko** [comment]
I wasn't aware of that. :) Is there anything more information I can deliver to resolve my issue?

**Comment by aure** [comment]
I'd basically need to have your project to do any real sleuthing.  Willing to share?

**Comment by blazejchwiecko** [comment]
@aure I made give you permission to repository. :) Main  audio related class is AudioHelper, you will not be able to get full localisation based effects, because your room is not configured and you don't have estimote beacons in your location. To make app crash just uncomment HRTF lines in `PlayerWithConvolution.swift" :)

**Comment by aure** [comment]
@blazejchwiecko I'll look at it this weekend.

**Comment by blazejchwiecko** [comment]
@aure Thanks a lot, but no rush. Right now it's working for the fewer angles (30* step)  like I wrote above. I would be great to have it working with more frequent  steps, but right now the convolution seems to be the problem. :)

**Comment by aure** [comment]
@blazejchwiecko I tried your repo but it wouldn't compile for me.  It sounds like you have your problem sorted out as much as can be anyway.  Can this issue be closed or is there something we can look into for you?

**Comment by blazejchwiecko** [comment]
Sure, if there's nothing we can do.

**Comment by aure** [comment]
Paul Batchelor could possibly make a morphing convolution some day.  The idea would be instead of mixing together all these expensive convolution calculation, you do one but change the impulse response file in real time.  But, that's a lot to ask of him to do unless he's personally motivated to do so for another project. :-/
