### ISSUE TITLE
Polyphonic Sampler ––> Perhaps AKVoice should be a class only protocol

### ISSUE THREAD

**Issue by modulusMathews** [audiokit/AudioKit#349]
### __Proposed Enhancement__
I'm currently trying to decide how I want to implement a polyphonic sampler. I want to use `AKPolyphonicInstrument`, but I'm unsure of how to enable `AKSampler` to be an `AKVoice`. I was hoping `AKVoice` would be a class only protocol.

**Comment by aure** [comment]
Will you try this out on a fork? If it works for you, you could make a pull request.

**Comment by eljeff** [comment]
AKSampler is actually already polyphonic. How are you loading the samples?

**Comment by aure** [comment]
Until more information is received I'm going to call this resolved, but reopen as necessary.
