### ISSUE TITLE
Noise in audio on Simulator

### ISSUE THREAD

**Issue by dreamwieber** [audiokit/AudioKit#35]
Experiencing a lot of noise in the audio on iOS 8 simulator, Xcode 6.1 (6A1052d). Running Yosemite 10.10.

Almost sounds like a bit or sample rate issue. 

Sound is normal on device.

**Comment by aure** [comment]
Hi, I am going to close this issue for now, but if you're still having problems and want more help, don't hesitate to bring it up again.  But, most people are not having this issue...
