### ISSUE TITLE
Can't build sample projects OSX 10.10.5 (XCode 7.2)

### ISSUE THREAD

**Issue by SeedyROM** [audiokit/AudioKit#353]
When I attempt to compile the example AudioKit OSX XCode project I get this error:

> /Users/user/Downloads/AudioKit-OSX/Examples/HelloWorld/HelloWorld/ViewController.swift:10:8: Module file was created by a newer version of the compiler: /Users/user/Downloads/AudioKit-OSX/Examples/HelloWorld/../../AudioKit.framework/Modules/AudioKit.swiftmodule/x86_64.swiftmodule

Not entirely sure what's up, I also get a couple strange syntax errors when I try to build the framework on my system.

Here's the error's I get when compiling the .framework:

> /Users/user/Downloads/AudioKit-3.1.1/AudioKit/OSX/AudioKit/AudioKit for OSX.playground/Sources/AKPlaygroundLoop.swift
> /Users/user/Downloads/AudioKit-3.1.1/AudioKit/OSX/AudioKit/AudioKit for OSX.playground/Sources/AKPlaygroundLoop.swift:43:30: Expected expression in list of expressions
> /Users/user/Downloads/AudioKit-3.1.1/AudioKit/OSX/AudioKit/AudioKit for OSX.playground/Sources/AKPlaygroundLoop.swift:43:30: Expected ',' separator
> /Users/user/Downloads/AudioKit-3.1.1/AudioKit/OSX/AudioKit/AudioKit for OSX.playground/Sources/AKPlaygroundLoop.swift:43:29: Missing argument for parameter #1 in call
> AudioKit Group
> /Users/user/Downloads/AudioKit-3.1.1/AudioKit/Common/Internals/AudioKit.swift
> /Users/user/Downloads/AudioKit-3.1.1/AudioKit/Common/Internals/AudioKit.swift:119:90: Expected expression in list of expressions
> /Users/user/Downloads/AudioKit-3.1.1/AudioKit/Common/Internals/AudioKit.swift:119:90: Expected ',' separator

**Comment by SeedyROM** [comment]
Realizing now that even though I updated XCode recently, I'm still one version behind.

**Comment by megastep** [comment]
Yeah the current version was built with Xcode 7.3, and Apple has been changing a bunch of things in Swift even between minor versions.

**Comment by aure** [comment]
Download from the source and build the framework for your system directly using the build_frameworks.sh script in the Frameworks directory or by dragging the AudioKit project into your project as a subproject.  Let us know if you have any issues.
