### ISSUE TITLE
Analyse High frequencies Audio

### ISSUE THREAD

**Issue by remirobert** [audiokit/AudioKit#354]
I am writing an application, which will be able to analyse the sound from the micro, but only the frequencies above 13000 Khz.

- To try the high frequency sound, I am using this tool : http://onlinetonegenerator.com

This is the code I am using : 

```swift
let mixer = AKMixer(mic)
let highPassFilter = AKHighPassFilter(mic)

tracker = AKFrequencyTracker(highPassFilter, minimumFrequency: 13000, maximumFrequency: 20000)
highPassFilter.play()
AudioKit.output = tracker
AudioKit.start()
        
highPassFilter.start()
        
let _ = Loop(every: 1 / 1000) {
  let freq = self.tracker.frequency
  print(freq)
}
```

I don't display the right frequencies on the loop.
Do I have to use FFT to analyse my current frequency ?

I am totally new in the sound analyse, and first time using this framework.

Thanks in advance for you help.

**Comment by aure** [comment]
I think the problem here is likely not the frequency tracking but rather the microphone.  I don't think it's going to be able to pick up vibrations at that high of a frequency.
