### ISSUE TITLE
populating  AKTable field to make custom waveforms

### ISSUE THREAD

**Issue by sova** [audiokit/AudioKit#355]
using AKMorphingOscillator, is there a way I can supply my own waveform information? (AKTable or similar?) Thanks :)

**Comment by aure** [comment]
Hi,

There are two variations of the morphing oscillator.  If you're using the one that is an operation, the tables are limited, but the one that is a generator node is completely up to you:

var morph = AKMorphingOscillator(waveformArray:[AKTable(.Sine), AKTable(.Triangle), AKTable(.Sawtooth), AKTable(.Square)])

In that example the tables are ones created with the default initializers, but you can create your own.  Check out these playgrounds for examples:

http://audiokit.io/playgrounds/Morphing%20Oscillator/
http://audiokit.io/playgrounds/General%20Purpose%20Oscillator/

Aure
