### ISSUE TITLE
Audiobus integration question

### ISSUE THREAD

**Issue by oleiade** [audiokit/AudioKit#356]
Hi,

I'm currently trying to implement _Audiobus_ support in my _Audiokit_ based prototype. I'm struggling a bit with some aspects of the _AudioUnit_ part of the implementation and could use your help. Here's the thing,  as mentioned in #335 I build an effect rack, which consists in multiple ``AKNode`` elements wired to each other.

Now I'm following _Audiobus_ documentation on how to have your app integrate as an effect, and wish to use the ``ABAudioFilter`` classe like in the "Filter port" section documented here: https://developer.audiob.us/doc/_integration-_guide.html#Create-Controller
The documentation says that the ``ABAudioFilter`` will take an audio unit as input, and if it's input is activated will feed the input sound into it, and send the output of it to the AudioBus port output.

Now my question is: I see that all _AudioKit_ ``AKNode`` are basically audio units. But I don't quite understand how they are wired together when I use say a ``AKCostelloReverb`` as input for a ``AKDelay``. Therefore I have a hard time figuring out in my case, which audio unit to provide to the ``ABAudioFilter``, and if that's even possible. As I understand it right now, it means that my whole effect chain should work as a single audio unit. Is that even possible with _AudioKit_? In General?  Maybe something I've missed with ``AudioKit.engine``?

I'm aware this question might be out of borders. If it is let me know. However, I'd love to get your help on this matter, as it would also help outlining the path to _AudioBus_ integration with _AudioKit_. 

Thanks!

**Comment by aure** [comment]
When you tell AKDelay that its input it is AKCostelloReverb, this happens behind the scenes:

public func addConnectionPoint(node: AKNode) {
        connectionPoints.append(AVAudioConnectionPoint(node: node.avAudioNode, bus: 0))
        AudioKit.engine.connect(avAudioNode,
            toConnectionPoints: connectionPoints,
            fromBus: 0,
            format: AudioKit.format)
    }

which forms an audio chain from one node's output to another's input.  

AKOperations create a single audio unit from many operations however, so you could make a single audio unit that uses the operation version of delay and costello reverb.

This is an important process you're going through and I'm hoping that you'll provide good information back to us as you pave the path forward and I'll try to be of as much help to you as I can.

**Comment by oleiade** [comment]
Thanks for your quick answer @aure 

The ``AKOperation`` seems interesting, however this opens a bunch of other questions:
- How can I concretely chain multiple operation based effects as a single node? Do you have any example? The documentation does not seem to provide one, and I couldn't figure out myself.
- I tried to read the code of ``AKOperation`` but don't quite understand how it really works under the hood. Thus a question arises: is it possible to re-implement the existing ``AKNode`` effects using ``AKOperation``?
- As previously mentioned, their documentation states that the ``AudioUnit`` must have input activated, is it the case on with ``AKOperation`` (Nota: I'm not sure to know what that actually means :D)
- Also, I'm quite new to iOS development, what is the role of the ``AVFoundation`` elements, especially in the usage you've mentioned in ``AKNode`` with the ``AVAudioConnection`` point usage

If I understand this properly, it means that an implementation in my case would be to create an ABAudioFilter with my ``AKOperation`` as ``AudioUnit`` right? 

I will for sure try to contribute back my learnings if I can get this to work :-)

**Comment by aure** [comment]
Most of the operation playgrounds string together several operations.  Here's one example:

http://audiokit.io/playgrounds/Linear%20and%20Exponential%20Segment%20Operations/

Yes, you can access parameters at any time as demonstrated on this playground:

http://audiokit.io/playgrounds/AutoPan%20Operation/

I was just thinking if you were limiting to a single audio unit, operations would allow you to jam one audio unit with a lot of cool things.

**Comment by oleiade** [comment]
Thanks for the example @aure 

After a lot of die and retry, I come to the conclusion that in my specific case of an effect rack AudioKit is probably not the best tool for the job (yet?). 

Thanks again for the support :-)
