### ISSUE TITLE
Can't build library for Playgrounds?

### ISSUE THREAD

**Issue by EliotSlevin** [audiokit/AudioKit#358]
Hey, 

So I've followed the installation instructions for playgrounds from [this video](https://vimeo.com/153057128).

I downloaded the source zip, opened the ios project, changed the scheme to AudioKit not AudioKitTests, and when I compile I very quickly get this strange error.

![error](http://puu.sh/ow5nU/80c46d4424.png)

There error is cutoff but it's full text is 
`/Users/Eliot/Desktop/AudioKit-3.1.1/AudioKit/Common/MIDI/AKMIDI.swift:34:25: '((UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8)) -> AnyGenerator<Any>' is not convertible to '(Any) -> AnyGenerator<Any>'`

I'm a little confused about how to solve it haha. 

I am using the latest GM seed of Xcode, version 7.3.1 build 7D01012, literally downloaded yesterday, I'm not sure if that could affect it. Any help or ideas would be appreciated

Cheers - Eliot

**Comment by aure** [comment]
I'll download that build of Xcode and see if I get this same error.

**Comment by aure** [comment]
I just built AudioKit from scratch using Xcode 7.3.1 GM no problem.  The video you've referenced was re-recorded here: https://vimeo.com/157204402 and I'm wondering if that will help.  I can already see from your screen shot that you're doing something wrong because the framework icon is showing in the sidebar when it should be the project icon in order to have the playgrounds show up.  If you'd like I can invite you to screenshare on screenhero to walk you through this.  For now, try again with the new video.

**Comment by aure** [comment]
Actually  just got this to show up.  So I can work on fixing it now.

**Comment by aure** [comment]
Hi, I have fixed this in the develop branch.  It will be merged to the master branch shortly.

Here's the one change that needs to be made if you just want to overwrite your AKMIDI.swift file with the new one:

https://github.com/audiokit/AudioKit/commit/4241903eea3e961f0ccc1d5d5233dd6d89423659

**Comment by EliotSlevin** [comment]
Its working! Thanks so much for your help
