### ISSUE TITLE
AKAudioPlayer: Skip back and forward

### ISSUE THREAD

**Issue by andreamazz** [audiokit/AudioKit#359]
Hi everyone.
I'm writing an app that plays an audio file from the library, and shows its waveform. I need to introduce some basic controls over the playback, like the ability to skip back and forth for a given amount of seconds.  

AKAudioPlayer only provides the current play time as a read only property. I was wondering if there is a way to also control the state of the song.  

Thank you.

**Comment by aure** [comment]
I can make AKAudioPlayer play a segment of an audio file which I think would suffice.  I could make the API be something like playFromFrame: or maybe even playFromTime: and then it will play to the end of the file.  Sound good?

**Comment by andreamazz** [comment]
That sounds great, thank you so much for the quick reply.

**Comment by aure** [comment]
I added a playFrom(time: Double) function in the develop branch:

https://github.com/audiokit/AudioKit/commit/7253673be8e1866112ae24d8944dc6e04ea7037e

That should allow you stop and restart playback from the appropriate point.

Hope that helps, if not you can reopen this issue.

**Comment by andreamazz** [comment]
Thank you, I'll try this right away. 👍

**Comment by andreamazz** [comment]
It works perfectly, thank you so much for all your work in this amazing library.

**Comment by andreamazz** [comment]
By the way, I noticed that the `currentTime` returned by the player is always relative to the starting point. So if you `playFrom` 60, the current time reset from 0 instead of starting from 60 too. I don't know if this is intended by design or not.

**Comment by aure** [comment]
Good catch.  I just made a commit that should address this issue:

https://github.com/audiokit/AudioKit/commit/b9a49c6c2f4260ddbfde07145a7f0dc315238844

Untested at this point.  Can you let me know if that works for you?

Thanks.

**Comment by andreamazz** [comment]
Just tested it, it works great, now the `currentTime` is always relative to the whole audio file. 

Thanks 👍

**Comment by aure** [comment]
Andrea, is this still working for you?  It seems like the newest Xcode update may have broken this.

**Comment by aure** [comment]
Actually, found a way to beef up the audio player code and things seem to be fine again.  If you're having any problems, you might want the latest updates in the develop branch.  There's a useful playhead property in there now.

**Comment by andreamazz** [comment]
Thank you @aure, this is great!
