### ISSUE TITLE
iTunes, Spotify and other audio apps mute AudioKit engine

### ISSUE THREAD

**Issue by knagle** [audiokit/AudioKit#360]
I built AnalogSynthX using AudioKit 3.1.1 and employed the fix that allows us to continue playing sound while the app is in the background. It behaves very well: 

AKSettings.playbackWhileMuted = true

However, whenever I bring forward the iTunes or Spotify apps and play a tune it immediately mutes AnalogSynthX. If I then stop the track from iTunes or Spotify and bring AnalogSynthX forward, the synth does not play. The only way to resolve the issue is to dismiss the app and restart it.

This does not happen if I open GarageBand. The AnalogSynthX and GarageBand play nice together. However, other synth apps like Roli NOISE mute the audio for AnalogSynthX if they are started after AnalogSynthX. If they are started before AnalogSynthX they usually play nice together.

So, I am wondering if there is a setting that needs to be changed to stop other apps from killing our audio in AnalogSynthX or if there is an issue with AudioKit 3.

**Comment by dskulina** [comment]
This option lets you mix with other audio sources - on or around line 134 of AudioKit.swift, in the playbackWhileMuted section, add `withOptions:AVAudioSessionCategoryOptions.MixWithOthers`  to the code that is there already, as below:

`try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, withOptions: AVAudioSessionCategoryOptions.MixWithOthers)`

For more options see https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAudioSession_ClassReference/#//apple_ref/c/tdef/AVAudioSessionCategoryOptions

**Comment by aure** [comment]
Thanks David, looks great, I'm also going to pass this along to the mailing list. @swiftcodex We should definitely do this for the synth.
