### ISSUE TITLE
Low-Pass Filter and Wave Form Selection Implementation

### ISSUE THREAD

**Issue by JadinT** [audiokit/AudioKit#364]
Hello, I am creating a small app in conjunction with my senior design project for school. The goal is to have a simple morphing oscillator and a low-pass filter. I want to be able to control the frequency of the oscillator, the cutoff of the low-pass, and the wave form of the oscillator. Here is my code:

`import UIKit
import AudioKit

class ViewController: UIViewController {
    
    var node1 = AKAudioPlayer(<#T##file: String##String#>)
    
    var morph = AKMorphingOscillator(waveformArray:[AKTable(.Sine), AKTable(.Triangle), AKTable(.Sawtooth), AKTable(.Square)])
    let lowPassFilter = AKLowPassFilter(morph, cutoffFrequency: 50, resonance: 0);
    override func viewDidLoad() {
        super.viewDidLoad()
        
        lowPassFilter.cutoffFrequency = 50
        lowPassFilter.resonance = 0
        
        node1.output = morph
        AudioKit.output = lowPassFilter
        AudioKit.start()
        morph.frequency = 0
        morph.start()
        
        
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
        
        
    @IBAction func changeFrequency(sender: UISlider) {
        morph.frequency = Double(sender.value)
    }
    

 }`

I took out the function where I was trying to change the waveform all together because it kept crashing. I originally created a UI slider that would move from value 0 to 3 and each vlue would be a different waveform. However, every time I moved the slider the app would crash. How can I get the oscillator to switch between the waveforms smoothly?

Also how can i get the low-pass filter set-up properly. XCode keeps telling me I need a type of AKNode in the declaration of the filer, but no matter what node I put in it doesn't seem to work. Any help would be greatly appreciated. Thanks

**Comment by aure** [comment]
I'm happy to do a screenhero screenshare but I don't see from glancing your code what could be wrong.

**Comment by aure** [comment]
Well, except that node1 stuff - the file placeholder and then node1.output = morph?  Not sure what you're trying to do there.

**Comment by JadinT** [comment]
Unfortunately I am at work right now so I can't screen share. I'll try to outline what I think is going on. I am new to coding iPhone apps so bare with me a little bit.

So I initially tried to assign a node to an AKAudioPlayer thinking it was another way of routing audio, but I am not sure thats correct. I was thinking I would output the morph oscillator through node1 and then route node1 into the low-pass filter? But I don't think that is working.

My main issue is trying to figure out the declaration of the lowPassFilter

At first I tried to declare it as...

let lowPassFilter = AKLowPassFilter(morph)

but i get "instance member morph cannot be used on type 'ViewController'"

And from then on I can't figure out how to properly declare it. The documentation says that AKLowPassFilter takes an AKNode as the first part of its declaration but whenever I put in a node i receive an error. Is there a specific kind of node that needs to be included in the first part of the declaration?

**Comment by JadinT** [comment]
Alternatively, now I am declaring it as

let lowPassFilter = AKLowPassFilter(AudioKit.output!)

and i get the Fatal Error: Unexpectedly found nil while unwrapping an optional value.

**Comment by aure** [comment]
You absolutely cannot send AudioKit.output into the into the input of the low pass filter.  The output is there just so you can send the very last item in your signal chain to it.  So you were better off with AudioKit.output = lpf  Have you taken a look at the examples or the playgrounds?

**Comment by aure** [comment]
I think this is more of a discussion than an issue.  We have a google forum at:  https://groups.google.com/forum/#!forum/audiokit

Also happy to do a screenshare with you and walk you through your signal chain setup.
