### ISSUE TITLE
Framework installation not working

### ISSUE THREAD

**Issue by sigmonky** [audiokit/AudioKit#365]
Hi --

I'm using XCode 7.3 and followed the instructions in your HelloWorld video tutorial to the letter. However, the framework is not being recognized by the project. Any idea what could be causing that? 

I got the Molly B Chimes example working last night but only because I compiled the AudioKit project included in the Molly B Chimes project as a framework. 

I'm most likely missing something. Would greatly appreciate some help.

Thanks
Randy Weinstein

**Comment by sigmonky** [comment]
Think I solved my own problem here. 

Using XCode 7.3, I had to manually add the AudioKit framework file path in HelloWorld target build settings Search Paths/framework search paths to get this to work.

**Comment by aure** [comment]
You're right.  The video tutorial might need to be updated to include that framework search path.  Some machines seem to need it while others don't, so I might as well include it.  I'll mark this as fixed for now.
