### ISSUE TITLE
sequencer: crash when attempting to loop

### ISSUE THREAD

**Issue by laurentVeliscek** [audiokit/AudioKit#366]
Hi, 

I couldn't find a way to create a looping sequence properly on Iphone 4S / 9.1.
(it  works fine on iPhone 6S)

I get a fatal error: unexpectedly found nil while unwrapping an Optional value
(triggered on line 67 of  AKMIDIEvent.swift)

I tried using seq.setLoopInfosetLoopInfo(),  using loopOn() with or without a loopLength set.
with a length shorter or longer or equal to the sequence length...

Either I crash, either the sequence is just played once.

The crash occurs just when the last note should begin to play.

I join my ViewController.swift file.

Did I miss something ?

(by the way, I noticed that "seq.setLength" documentation tells that it sets the
"Length of tracks in seconds". Shoudn't be a length in Beats ?)

thanks :-)

**Comment by laurentVeliscek** [comment]
I made few more tests. In fact, the problem occurs on ios 9.1, but everything works fine on ios 9.3, even using a iphone4S . So it seems to be ios version dependant.

The crash seems to occur from attempting to unwrap status! value (line 67 of AKMIDIEvent.swift).

Just to mention, the property  seq.isAvSeq is set to false (default) as timing glitches is a big issue for a sequencer...

**Comment by eljeff** [comment]
iOS 9.1 broke a lot of sequencing stuff. They fixed it in 9.2.

**Comment by aure** [comment]
@eljeff I think Laurent's right about the setLength thing.  At some point, want to go through AKSequencer and see what should be in Beat instead of Double?

**Comment by aure** [comment]
I think I've gone through and fixed the references to seconds and also changed their types to Beat, so I think this issue is pretty much resolved as much as it can be.
