### ISSUE TITLE
Archive upload failed with errors:

### ISSUE THREAD

**Issue by socialvanana** [audiokit/AudioKit#368]
Hello, I made an app with this awesome library.
I'm about to use TestFlight on iTunes connect. I have to upload archive for that.
When I remove AudioKit from Podfile, then uploaded well.
If I add AudioKit in Podfile, then upload failed with this message.
How can I resolve this?

ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

**Comment by megastep** [comment]
You probably need to run the fix-framework.sh script as part of your build process, as outlined in our INSTALL.md document: https://github.com/audiokit/AudioKit/blob/master/Frameworks/INSTALL.md

I don't think that's something CocoaPods can do for you but it's likely the reason you get these submissions errors. This script at the very least will strip the simulator slices from the framework.

**Comment by socialvanana** [comment]
"$BUILT_PRODUCTS_DIR/$FRAMEWORKS_FOLDER_PATH/AudioKit.framework/fix-framework.sh"
I don't use bitcode but..THIS IS WORKING!!
I spent almost 3 days. 
Thank you so much megastep!!!!!!

**Comment by megastep** [comment]
Yup, that's all because it also removes the simulator bits from the framework. :)

**Comment by powhu** [comment]
Thank you solved my problem.

**Comment by swordmanboy** [comment]
Where is for "$BUILT_PRODUCTS_DIR/$FRAMEWORKS_FOLDER_PATH/AudioKit.framework/fix-framework.sh"?   I don't understand. please tell me for keyword.

**Comment by phin** [comment]
Just spent 4 days googling this before finding this thread. I know we need to read everything, but could be amazing to put it somewhere more prominent (ex : quick start), since I almost removed it all together :) Just a note, thanks!

**Comment by newinh** [comment]
How to Add a Run Script Build phase.
http://runscriptbuildphase.com
