### ISSUE TITLE
How to update AKVoice attributes in Polyphonic Instrument available voices?

### ISSUE THREAD

**Issue by Joshua-Thompson** [audiokit/AudioKit#369]
I have a custom voice class that I want to use in a custom instrument but I can't seem to update the attribute of the custom voice after initializing the instrument.

```swift
class CustomVoice: AKVoice {
  var preset: Int = 0 //attribute I want to update
}

class CustomInstrument: AKPolyphonicInstrument {
  init(voiceCount: Int) {
        super.init(voice: CustomVoice(), voiceCount: voiceCount)
    }
}

var instrument = CustomInstrument(voiceCount: 1)

//trying to update voice preset attribute but receive error 
instrument.availableVoices[0].preset = 1; //error, preset not an attribute

```

I get that the AKPolyphonicInstrument availableVoices are of type AKVoice. But, how would I go about being able to update attributes of the voices in the Polyphonic Instrument?

Thank you for any help with this...

**Comment by aure** [comment]
availableVoices is an array of AKVoice not an array of CustomVoice.  So, when you pull out the 1st element, all the compiler knows for sure is that it has the properties of an AKVoice.  You can either force cast the element into a CustomVoice or make a new array of CustomVoice that you use to change the preset with.

**Comment by aure** [comment]
I am not sure if my response was helpful...

**Comment by aure** [comment]
I'm going to close this for now, but please feel free to reopen it with new information.

**Comment by JoshuaThompsonSS** [comment]
Hi Aure,
Yes, thank you for the response. That resolve my issue.
