### ISSUE TITLE
No Sound AKOscillator (version 3.1.2

### ISSUE THREAD

**Issue by devintyler** [audiokit/AudioKit#370]
I'm using AKOscillator, and I noticed that version 3.1.2 broke it. There is now no output sound. I went back down to 3.1 and output sound works again. AKMicrophone and fft seem to work fine.

**Comment by aure** [comment]
I just tested this on both iOS and OSX playgrounds for the "General Purpose Oscillator" aka AKOscillator, and they stil work. I also checked HelloWorld which uses the oscillator and it still works.  Can you provide me more information or do a screenshare with me?

**Comment by aure** [comment]
Also, which version of Xcode are you using?  3.1.2 is specifically targeted to Xcode 7.3.1.

**Comment by devintyler** [comment]
Xcode 7.3.1
Here's some of the code:

```
class SignalGen {
    // General
    var waveform: AKTable;
    var frequency: Double;
    var oscillator: AKOscillator;
    
    init() {
        self.frequency = 1000;
        self.waveform = AKTable(.Triangle, size: 4096);
        self.oscillator = AKOscillator.init(waveform: AKTable(.Sine, size: 4096), frequency: 1000, amplitude: 0.5, detuningOffset: 0, detuningMultiplier: 0);
    }
}

class UISignalGenViewController: UIViewController {
    
    var oscillator: AKOscillator = SignalGen().oscillator;
    var waveType: String = "Sine";
    var freqSelect: Double = 2.0;
    
    // MARK: Property
    @IBAction func startButtonAction(sender: UIButton) {
        AudioKit.output = self.oscillator;
        AudioKit.start();
        if (self.oscillator.isStarted) {
            self.oscillator.stop();
            self.startButton.setTitle("Start", forState: UIControlState.Normal);
        } else {
            self.oscillator.start();
            self.startButton.setTitle("Stop", forState: UIControlState.Normal);
        }
    }
}
```

That button turns the oscillator on/off

**Comment by aure** [comment]
You've set the detuning multiplier to zero.  The default value is 1.  Maybe this was broken in 3.1, but it is fixed now so your code is telling the frequency to be detuned to zero. Use:

self.oscillator = AKOscillator.init(waveform: AKTable(.Sine, size: 4096), frequency: 1000, amplitude: 0.5)

or 

self.oscillator = AKOscillator.init(waveform: AKTable(.Sine, size: 4096), frequency: 1000, amplitude: 0.5, detuningOffset: 0, detuningMultiplier: 1);

and you'll be fine.

**Comment by aure** [comment]
BTW, you should put the AudioKit start stuff in viewDidLoad instead instead of on the button press.

**Comment by devintyler** [comment]
Thanks!
