### ISSUE TITLE
Play two Sounds simultaneously

### ISSUE THREAD

**Issue by floriannagel** [audiokit/AudioKit#372]
Hey folks, i'm new to AudioKit.
I want to mix several Files. How can i do that in AK?

**Comment by narner** [comment]
Hi Florian, 

You'll want to take a look at the documentation for [AKMixer](http://audiokit.io/docs/Classes/AKMixer.html). 

There's also a Playground ([Mixing Nodes](http://audiokit.io/playgrounds/Mixing%20Nodes/)) that shows you how to mix audio files using `AKMixer`.

**Comment by aure** [comment]
Hi, I think when we upgraded to AudioKit version3, the web site lost its links to the discussion forum, allowing new users to discuss stuff.  

https://groups.google.com/forum/#!forum/audiokit

Github issues are for problems with the code, so I'll close this issue.  But, please come to the Google Group!
