### ISSUE TITLE
AUIOClient_StartIO failed

### ISSUE THREAD

**Issue by socialvanana** [audiokit/AudioKit#377]
I'm using AVAudioSessionInterruptionNotification.

sound is not resume after phone call ended.
but till yesterday, it was worked. and code is not changed.. weird..

below is my code.

when user get call,

if (interruption began) {
  AKOperationGeneratorList[current].stop()
  AudioKit.engine.pause()
} 

when user call is ended,
if (interruption ended) {
  _ = try? audioSession.setActive(true)

  // 1.5 sec delay to start engine. I don't know why I have to this, but if there is no delay, sound is not started.
  _ = try? AudioKit.engine.start()  <<== this line make error

  AKOperationGeneratorList[current].play()
}

error message:
00:06:58.068 ERROR:    [0x19e191000] 1233: AUIOClient_StartIO failed (560557684)
00:06:58.069 ERROR:    [0x19e191000] AVAudioEngineGraph.mm:1174: Start: error 560557684

Can I resolve this?

Thank you

**Comment by aure** [comment]
huh, yeah, I have no idea why it stopped working for you.  Something must have changed right? :) Perhaps if you shared the project I could dig in, but it would be hard to test this very well.

**Comment by socialvanana** [comment]
That sounds good!
I'll send you a project to your email(aure@aure.com)

**Comment by aure** [comment]
I'm curious if this happens just with Operation-based generators.  For instance, if you were to use an oscillator or noise node, do those come back after interruption?

**Comment by aure** [comment]
Any updates on this?  If so we can open the issue back up, but until then I will close it.
