### ISSUE TITLE
AKMix with startingPoint

### ISSUE THREAD

**Issue by floriannagel** [audiokit/AudioKit#379]
Hi folks, sorry that i must ask a normal question again. Next time in the google group (i started a request to join)

When i use a AKMix, i want to set the startPoint for one of the nodes. Example:

audioPlayer1 starts at 0:00
audioPlayer2 starts when audioPlayer1 at 11:23 is

Is there a possibility?

**Comment by floriannagel** [comment]
Did it myself. You don't have to start every player at the same time.

**Comment by narner** [comment]
Glad you got it figured out!
