### ISSUE TITLE
AKAudioRecorder saves files in a format AKAudioPlayer can't read

### ISSUE THREAD

**Issue by floriannagel** [audiokit/AudioKit#380]
Can't find anything in the documentation.

The AKRecorder get a documentString/URL and create the file itself. I tested the same path with AKAudioRecorder and it did nothing :/ i also tried to create an empty file in the NSBundle and tried the AKRecorder with it. And same thing. Nothing happens.

Can anyone help me? :/

**Comment by narner** [comment]
Hey @floriannagel that is odd. Can you attach a snippet of your code? Thanks!

**Comment by aure** [comment]
Not to be pedantic, but what is AKRecorder?  I'd assume it was a typo but you typed it twice and you mention AKAudioRecorder too, so there must be a reason.

**Comment by floriannagel** [comment]
Sorry of course i mean AKAudioRecorder. My code is like this:

```
let format = NSDateFormatter()
format.dateFormat="yyyy-MM-dd-HH-mm-ss"
let currentFileName = "recording-\(format.stringFromDate(NSDate())).m4a"
        
let documentDirPath = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true).first!
let recordingAudioFilePath = NSURL(string: documentDirPath)!.URLByAppendingPathComponent(currentFileName).path!
        
self.akRecorder = AKAudioRecorder(recordingAudioFilePath)
AudioKit.start()
akRecorder?.record()
```

And there is a Thread Error

**Comment by narner** [comment]
@floriannagel, can you add in the thread error to your comment above? Thanks!

**Comment by floriannagel** [comment]
<img width="1155" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1937096/15274858/244ba990-1abd-11e6-815f-ced1af4b5651.png">

**Comment by aure** [comment]
I'm working on AKAudioRecorder right now and I'm having similar issues to you.  The way it should work however, is that it will require a starting file that is in the correct format.  So, instead of using some complicated method of saving as a certain format, it instead just writes in the same format that the file from your bundle was in.  So, it really shouldn't create files.  But, even when I give it a file it was not recording so I am trying to debug that.  I just thought I'd update you about the file creation thing.

**Comment by aure** [comment]
My latest push to the develop branch does record the file, so maybe it will work for you.  I am having some trouble loading the file back into AKAudioPlayer.  I can listen to the recording using VLC but no Audacity, so my feeling is that there is something inconsistent about the audio format settings that certain apps can ignore but others need to be perfect.

**Comment by aure** [comment]
I'm going to rename this to AKAudioRecorder does not save in a format AKAudioPlayer can read because that seems to be the biggest issue around this right now.

**Comment by floriannagel** [comment]
My first bug! I used the standard AVAudioRecorder. But I will try AK again

**Comment by aure** [comment]
I've introduced the AKMicrophoneRecorder which is just a lightweight wrapper around AVAudioRecorder, so I am sure that will work for you if nothing else.

**Comment by aure** [comment]
I think this is fixed now.

**Comment by roecrew** [comment]
Whenever I try to play a file that AKMicrophoneRecorder created with AKAudioPlayer I get 'No Audio to load.'

Can AKMicrophoneRecorder create files? Any help appreciated.

**Comment by aure** [comment]
@roecrew  Laurent Veliscek is rewriting the AKAudioPlayer and I think it will be more robust.  perhaps as soon as tomorrow.

**Comment by roecrew** [comment]
@aure So it turns out that AVAudioplayer.record() was returning false because no AVAudioSession had been initialized. So files of length 0 were being created. That's why I was receiving log 'No Audio to load' from my AKAudioplayer.

**Comment by aure** [comment]
And you were nice enough to contribute the fix back!  So I guess AKNodeRecorder needs this as well?

**Comment by roecrew** [comment]
@aure Just tried, but no dice.
