### ISSUE TITLE
How to display sine waveform?

### ISSUE THREAD

**Issue by Tanisha27** [audiokit/AudioKit#382]
how to display the waveform from the audio playing on AKAudioPlayer? tried to find the code...but didnt get it anywhere....and didnt understand the documentation on http://audiokit.io....plzz help..

**Comment by aure** [comment]
Hi Tanisha, this would be something for the Google Group for AudioKit, not a Github issue.  https://groups.google.com/forum/#!forum/audiokit

There are playgrounds that show how to use the plotting classes and how to use AKAudioPlayer, so that would be another good place to start.

**Comment by Tanisha27** [comment]
sorry for the inconvenience and thanx for the reply... but i was facing some problem...but anyway, i'll look for the answer in the link...
