### ISSUE TITLE
Sampler cuts off wav file sound midway when using playNote

### ISSUE THREAD

**Issue by JoshuaThompsonSS** [audiokit/AudioKit#383]
I'm trying to play a custom sound saved in a wav file (unzip attached for wav file).
[TCM_Snare_4.wav.zip](https://github.com/audiokit/AudioKit/files/275945/TCM_Snare_4.wav.zip)

But, when running the sampler.playNote() the audio file is played and then maybe 30% into the sound it cuts off for about 1/4 of a sec and then continues finishing the sound (it's a long snare drum sound).

Here is my playground code  - running the latest audiokit-develop branch (downloaded about 2 days ago)

```swift
import XCPlayground
import AudioKit

let sampler = AKSampler()

sampler.loadWav("Sounds/TCM_Snare_4")

let ampedSampler = AKBooster(sampler, gain: 3.0)

AudioKit.output = ampedSampler
AudioKit.start()

AKPlaygroundLoop(every: 4) {
    sampler.playNote(60) // this should play the custom snare drum sound for about 2 sec but it
                                       // gets cut off midway and then continues after 1/4 sec
}

XCPlaygroundPage.currentPage.needsIndefiniteExecution = true

```

Any idea why this would happen? 
It works for samples that are shorter, but not for longer drawn out samples.

Thank you for any help with this :)

**Comment by JoshuaThompsonSS** [comment]
I'm thinking that maybe it's due to the higher frequencies involves in the snare sample. Because I have a kick sample that is similar in length that works fine....

**Comment by JoshuaThompsonSS** [comment]
The kick sample has much lower frequencies

**Comment by aure** [comment]
It can't have to do with the content of the file, but it could be due to the encoding.

This wav file has sample rate of 48000Hz.  I wonder if the problem will go away if you use a 44.1kHz file?  Is the other file 44.1?

**Comment by JoshuaBThompson** [comment]
Hi Aure, 
I'll check and see what the other sample frequencies are at.
Thank you for your help :)

**Comment by JoshuaBThompson** [comment]
Hi Aure,
What is the optimum bit depth for sampled sounds?

**Comment by aure** [comment]
Infinity minus one!  :)  I think 16-bit is fine though.

**Comment by JoshuaThompsonSS** [comment]
Ha! Touché...
Ok, thank you:)

On Saturday, May 21, 2016, Aurelius Prochazka <notifications@github.com>
wrote:

> Infinity minus one! :) I think 16-bit is fine though.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/audiokit/AudioKit/issues/383#issuecomment-220807409>
>


-- 
Joshua Thompson
Firmware Engineer
Sonic Sensory Inc
Mobile: 626-200-5346

**Comment by aure** [comment]
Wondering what the status of this issue is...

**Comment by JoshuaBThompson** [comment]
Hi Aure,
Sorry, yes your suggested bit depth fixed our problem.
Thank you!
