### ISSUE TITLE
AKAudioPlayer: pause and playFrom methods seems to corrupt their instance

### ISSUE THREAD

**Issue by laurentVeliscek** [audiokit/AudioKit#384]
Hi !

Bad news...
Playing with AKAudioplayer , I got very buggy behaviors.

If I only use start stop methods, everything works fine. But when I call pause or playFrom,  many problems occur.

-> The sound can play silently (current time is still updated, but no sound)
-> I can loose control (start doesn't work anymore at all)
-> It may finish in a crash (buttons do not fire anything anymore.)
-> If I start playing using playFrom, then the callBack is trigerred BEFORE the player reach the end of the file (I's say about an half a second before). Then, you cannot play the sound anymore. 
-> call playFrom twice (or once after the player started) will play a short time of the sound, then stop (and the callback will be triggered)
-> If I use "replace" file and then "reload", then the played file is the previous file (not the replaced one). But if you just replace and NOT reload, then it is the replacing file that is played.
And so on...

I noticed that if I pause the player, currentTime and playhead properties give 0.0

Right now, except if you only just play / stop, audioplayer seems to be unusable.

:-/

I plan to work on an AKAudioFile class first (I need it :-). Then I'll try to fix or may be rewrite an AKAudioPlayer. I'll try to stick to the actual methods and properties.

But, right now, I think the start() method should be deprecated or changed and we should use a play() method instead (it would be more coherent with  Apple's AVAudioPlayer implementation.)
May be Start() should play the sound from the beginning when play() should continue to play according the playhead/currentTime value.

It would be cool to have a loopStart/loopEnd property that could be set.

And I'd like to try to implement a kind of markers callback, that could be triggered when the player reach an associated playing time value.

I attach a zip with my testPlayground, and the audio files I trig with.
I extended AKAudioPlayer to expose some internal var properties for debug.
so just add those lines to your AKAudioPlayer.swift if you want to experiment with my playground page.

```
// Added for debug
extension AKAudioPlayer {

    public var Paused : Bool {
        get {
            return paused
        }
    }

    public var InternalPlayerPlaying : Bool {
        get {
            return internalPlayer.playing
        }
    }
}
```
I'll let you know if I can submit a tested and working AKAudioPlayer.

:-)

Laurent.

[_Recorder.xcplaygroundpage.zip](https://github.com/audiokit/AudioKit/files/277025/_Recorder.xcplaygroundpage.zip)

**Comment by aure** [comment]
I guess start() and play() methods should do the same thing AKNode expects them and I think defaults one just calling the other, but I'll have to look at this in more detail in the morning.

**Comment by aure** [comment]
This issue seems to be in place to let us know that you've identified something that you plan to fix right?  I'll leave you to it unless you want me to get involved.

**Comment by laurentVeliscek** [comment]
I Think I can try to fix it.
As I'm a beginner in swift and AVFoundation, it takes years to code anything, but I learn a lot.
I begin to have a better understanding, and I should be able to submit soon a V1 of AKAudioFile (that inheritates AVAudioFile, with some utilities and public handy properties). 
Right now, I already got some success with a my custom class in the playground.
But I must work on it to keep things simple and handy.

Then, I hope I can submit an upgraded AKAudioPlayer based on your implementation. I have an idea about what is going wrong in the current version, but I haven't made tests yet.

So if there's no emergency, I think I should be able to fix the AKAudioPlayer within a reasonable delay.

Coming back soon with some lines of code !

:-)

Laurent.

**Comment by roecrew** [comment]
Hey @laurentVeliscek,
Just curious where your at with your AKAudioPlayer. If you need any help or want to pass on the job, let me know.

**Comment by laurentVeliscek** [comment]
I’m just working on now !

Just cleaning and should be ready very soon…

:-)

Laurent
> Le 10 juin 2016 à 19:08, Brandon Barber <notifications@github.com> a écrit :
> 
> Hey @laurentVeliscek <https://github.com/laurentVeliscek>,
> Just curious where your at with your AKAudioPlayer. If you need any help or want to pass on the job, let me know.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/audiokit/AudioKit/issues/384#issuecomment-225240104>, or mute the thread <https://github.com/notifications/unsubscribe/ASTVrlb14vQr2iSmspROJbPOq_Tb66eZks5qKZoagaJpZM4IkRWV>.
> 




Mes compos en téléchargement libre sont sur Soundcloud (musicatalogue) :

https://soundcloud.com/musicatalogue

**Comment by laurentVeliscek** [comment]
I think this one could be closed...
