### ISSUE TITLE
Audio triggering

### ISSUE THREAD

**Issue by codecowboy** [audiokit/AudioKit#385]
I have an iRig HD for iPad and would like to plug in a roland drum pad to trigger a sample. Could this be done with Audiokit? Perhaps some kind of spectral analysis of the incoming signal and then if the input is in range x, I could trigger a sound file or synth sound. It would need to be very low latency for live performance.

**Comment by aure** [comment]
Everything's doable I guess, but its not like we have this exact applicationbuilt in.  You kind of have said one of everything in that paragraph.  Microphone input, sampling, spectral analysis, synth, low latency, oh my. :) This is not really an issue with AudioKit but a discussion, so I'd encourage you join the forum:

https://groups.google.com/forum/#!forum/audiokit

Aure
