### ISSUE TITLE
Where are the playgrounds?

### ISSUE THREAD

**Issue by codecowboy** [audiokit/AudioKit#387]
There is mention of playgrounds in the documentation and on the project website but I can't see any mention of where the playground files are or how to open them? Theres an entry on the forum on building / installing the playgrounds but the command required is missing.

I installed Audiokit using Carthage. Xcode 7.3 on El Capitan.

**Comment by aure** [comment]
Playgrounds don't come with Carthage since you wouldn't necessarily want them in  your code.  Download AudioKit directly from the source and you'll find them in the Xcode projects for both iOS and OSX.  Maybe this video will help too:  https://vimeo.com/157204402
