### ISSUE TITLE
Soundfont Support in V3

### ISSUE THREAD

**Issue by Jafri69** [audiokit/AudioKit#389]
There doesn't seem to be any way to select presets from a Soundfont and thus to actually use a Soundfont. The AKSampler does have a loadSoundfont method though. An example is needed demonstrating the actual use of a Soundfont.

**Comment by aure** [comment]
While I agree that an example would be useful, I don't think I'll be adding one to the repo, but rather making a separate repo with a big ol' sf2 file in it.  In any event, I believe your issue should be resolved with the two new methods in the develop branch, loadMelodicSoundFont and loadPercussiveSoundFont.

Use like this:

syn1.loadMelodicSoundFont("GeneralUserGS", preset: 10)

**Comment by Jafri69** [comment]
Thanks a lot, Aurelius. Let me take it for a spin.

Regards,

Azfar

On Tue, Jun 7, 2016 at 10:39 PM, Aurelius Prochazka <
notifications@github.com> wrote:

> While I agree that an example would be useful, I don't think I'll be
> adding one to the repo, but rather making a separate repo with a big ol'
> sf2 file in it. In any event, I believe your issue should be resolved with
> the two new methods in the develop branch, loadMelodicSoundFont and
> loadPercussiveSoundFont.
>
> Use like this:
>
> syn1.loadMelodicSoundFont("GeneralUserGS", preset: 10)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/audiokit/AudioKit/issues/389#issuecomment-224356677>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE44-Q74VoX6MeopYnnlziPQzTcETEbOks5qJay_gaJpZM4IugIN>
> .
>



-- 
Regards,

Azfar

**Comment by sigmonky** [comment]
This worked great for me with just a few minor updates to the SequencerTracks example project:

added fluid_gm sound font to project or the GM soundfont of your choice

In ViewController.viewDidLoad(),made following changes:
```
//call loadMelodicSoundFont method instead of load EXS24 for the 4 AKSampler instances
syn1.loadMelodicSoundFont("fluid_gm", preset: 0)
syn2.loadMelodicSoundFont("fluid_gm", preset: 0)
syn3.loadMelodicSoundFont("fluid_gm", preset: 0)
drmKit.loadMelodicSoundFont("fluid_gm", preset: 0)

```

Of course, everything sounds like a piano with these settings but changing that is just a matter of using different preset values.
