### ISSUE TITLE
Error using AKFrequencyTracker on AKMicrophone

### ISSUE THREAD

**Issue by rbaranov** [audiokit/AudioKit#390]
Hi! Thank you for AudioKit!

Trying to work with AuidoKit 3. I need to track frequency from microphone so I tried sample code from issue #322 and got error at AudioKit.start():

```
import Foundation
import AudioKit

let mic = AKMicrophone()

let tracker = AKFrequencyTracker.init(mic, minimumFrequency: 200, maximumFrequency: 2000)
let silence = AKBooster(tracker, gain: 0)

AKSettings.audioInputEnabled = true
AudioKit.output = silence
AudioKit.start()
```

> 2016-06-06 21:41:04.389 Tracking Frequency Microphone[4791:609500] 21:41:04.388 WARNING:  40: ERROR: couldn't get default input device, ID = 0, err = 0!
2016-06-06 21:41:04.398 Tracking Frequency Microphone[4791:609500] 21:41:04.398 WARNING:  803: The default input device 0x0 '(null)' has no input channels.
2016-06-06 21:41:04.400 Tracking Frequency Microphone[4791:609429] 21:41:04.400 ERROR:    >aurioc> 807: failed: -10851 (enable 1, outf< 2 ch,      0 Hz, Int16, inter> inf< 2 ch,      0 Hz, Int16, inter>)
2016-06-06 21:41:04.414 Tracking Frequency Microphone[4791:609429] 21:41:04.414 ERROR:    308: input bus 0 sample rate is 0
2016-06-06 21:41:04.415 Tracking Frequency Microphone[4791:609429] 21:41:04.414 ERROR:    AVAudioEngineGraph.mm:2510: PerformCommand: error -10875
2016-06-06 21:41:04.420 Tracking Frequency Microphone[4791:609429] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10875'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107c17d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010768bdeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107c17bea +[NSException raise:format:arguments:] + 106
	3   libAVFAudio.dylib                   0x0000000115342ff3 _Z19AVAE_RaiseExceptionP8NSStringz + 176
	4   libAVFAudio.dylib                   0x00000001153543fb _ZNK18AVAudioEngineGraph14PerformCommandER11AUGraphNodeNS_12ENodeCommandEPvj + 1571
	5   libAVFAudio.dylib                   0x000000011535dbcd _ZNSt3__110__function6__funcIZN13AUGraphParser34InitializeActiveNodesInOutputChainER18AVAudioEngineGraph14ETraversalModeR11AUGraphNodeRbE3$_8NS_9allocatorIS9_EEF16ETraversalStatusS7_P17AUGraphConnectionEEclES7_OSE_ + 231
	6   libAVFAudio.dylib                   0x000000011535ec2f _ZNKSt3__18functionIF16ETraversalStatusR11AUGraphNodeP17AUGraphConnectionEEclES3_S5_ + 31
	7   libAVFAudio.dylib                   0x0000000115351208 _ZN13AUGraphParser18TraverseGraphNodesERK18AVAudioEngineGraph10EDirection10ERecursionR11AUGraphNodeP17AUGraphConnectionRKNSt3__18functionIF16ETraversalStatusS6_S8_EEE + 48
	8   libAVFAudio.dylib                   0x00000001153512ff _ZN13AUGraphParser18TraverseGraphNodesERK18AVAudioEngineGraph10EDirection10ERecursionR11AUGraphNodeP17AUGraphConnectionRKNSt3__18functionIF16ETraversalStatusS6_S8_EEE + 295
	9   libAVFAudio.dylib                   0x00000001153522bb _ZN13AUGraphParser34InitializeActiveNodesInOutputChainER18AVAudioEngineGraph14ETraversalModeR11AUGraphNodeRb + 833
	10  libAVFAudio.dylib                   0x000000011535521f _ZN18AVAudioEngineGraph10InitializeEv + 1031
	11  libAVFAudio.dylib                   0x000000011538d2b5 _ZN17AVAudioEngineImpl10InitializeEv + 29
	12  libAVFAudio.dylib                   0x000000011538c827 -[AVAudioEngine prepare] + 58
	13  AudioKit                            0x0000000115c466cc _TZFC8AudioKit8AudioKit5startfT_T_ + 268
	14  ???                                 0x0000000112dff47e 0x0 + 4611634302
	15  Tracking Frequency Microphone       0x0000000107101ab0 main + 0
	16  Tracking Frequency Microphone       0x00000001071049a1 _TTRXFo__dT__XFo_iT__iT__ + 17
	17  Tracking Frequency Microphone       0x0000000107104401 _TPA__TTRXFo__dT__XFo_iT__iT__ + 81
	18  Tracking Frequency Microphone       0x00000001071049d0 _TTRXFo_iT__iT__XFo__dT__ + 32
	19  Tracking Frequency Microphone       0x0000000107104a07 _TTRXFo__dT__XFdCb__dT__ + 39
	20  CoreFoundation                      0x0000000107b3d2ec __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	21  CoreFoundation                      0x0000000107b32f75 __CFRunLoopDoBlocks + 341
	22  CoreFoundation                      0x0000000107b326d2 __CFRunLoopRun + 850
	23  CoreFoundation                      0x0000000107b320f8 CFRunLoopRunSpecific + 488
	24  GraphicsServices                    0x000000010e6f7ad2 GSEventRunModal + 161
	25  UIKit                               0x0000000107fcdf09 UIApplicationMain + 171
	26  Tracking Frequency Microphone       0x0000000107101f39 main + 1161
	27  libdyld.dylib                       0x000000010a95d92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

![image](https://cloud.githubusercontent.com/assets/19781023/15828331/a6bf4254-2c30-11e6-83c2-11d2a399b23f.png)
![image](https://cloud.githubusercontent.com/assets/19781023/15828292/8332a754-2c30-11e6-94db-06dc1802e7ab.png)
![image](https://cloud.githubusercontent.com/assets/19781023/15828299/8dbafa46-2c30-11e6-9de6-59f02c8e145e.png)

I use AudioKit-3.1.3.

**Comment by aure** [comment]
Are you running this in playgrounds?  Asking just because the microphone doesn't work in the simulator.  If you're running on an app do you have audio input enabled?

**Comment by rbaranov** [comment]
I tried this code in playgrounds and in iOS App (in Simulator) and got the same error. I've just tried it on the device and got another error:
![image](https://cloud.githubusercontent.com/assets/19781023/15846095/9e49a5d6-2c9b-11e6-8ddf-7890f831fc3b.png)
![image](https://cloud.githubusercontent.com/assets/19781023/15846099/ab6b0fde-2c9b-11e6-80c5-5a1f16fe0b1e.png)

> If you're running on an app do you have audio input enabled?

Yes.

Also I tried this code:
```
import Foundation
import AudioKit

let mic = AKMicrophone()

AKSettings.audioInputEnabled = true
AudioKit.output = mic
AudioKit.start()
```
You were right — it doesn't work in playgrounds.

But it works fine in simulator and on the device (I here sounds from microphone in headphones).

So I guess the initial error related to FrequencyTracker, not to Microphone.

**Comment by aure** [comment]
Can you share your project or do a screenhero screenshare with me?

**Comment by rbaranov** [comment]
I'm totally confused. After your request I've prepared a new project with bug demonstration and that project worked fine.

I returned to main project (there were many changes there), tried to use AKFrequencyTracker with AKMicrophone again and... it works fine too!

So I think that was my mistake. Shame on me. Sorry for this and thank you for your help, Aurelius!

**Comment by aure** [comment]
I suppose that's good news, but yeah audio programming can be a dark art a lot of the time.

**Comment by returnzer0** [comment]
Hey, Im having this exact same problem. I am not trying to user any frequency trackers but I downloaded the examples and I am running the RecorderDemo for iOS.

When running on a simulator it works perfectly fine, but when I run it on a device it gives me the following error.

`deleteFileWithFileName "D96D044D-0352-45C1-8A54-508ADAEE76D7.caf" deleted.
cleanTempDirectory() 1 files deleted
setSession(category:with:) Error: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)" Cannot set AVAudioSession Category to AVAudioSessionCategoryPlayback with options:AVAudioSessionCategoryOptions(rawValue: 8)
Errored setting category.
initialize() AKAudioPlayer Warning:  "BE9FF3CF-3DAF-42EB-BFEB-4DB51AF02680.caf" is an empty file
2017-02-05 12:30:32.038621 AudioKitTest[1637:454799] [mcmx] 337: input bus 0 sample rate is 0
2017-02-05 12:30:32.040892 AudioKitTest[1637:454799] [central] 54:   ERROR:    [0x1a7df2c40] >avae> AVAudioEngineGraph.mm:2515: PerformCommand: error -10875
2017-02-05 12:30:32.041711 AudioKitTest[1637:454799] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10875'
*** First throw call stack:
(0x1826c51b8 0x1810fc55c 0x1826c508c 0x19c12f300 0x19c142b3c 0x19c14c688 0x19c13f7fc 0x19c13f684 0x19c13f774 0x19c140868 0x19c143a54 0x19c1b102c 0x19c1b03d0 0x10027cf40 0x100048bfc 0x100048fa0 0x18857a924 0x18857a4ec 0x188580c98 0x18857e138 0x1885f068c 0x1887fccb8 0x188802808 0x188817104 0x1887ff7ec 0x18429b92c 0x18429b798 0x18429bb40 0x182672b5c 0x1826724a4 0x1826700a4 0x18259e2b8 0x1885e57b0 0x1885e0534 0x100050330 0x1815815b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `


I'm not sure why this is happening, I have put breakpoints and have narrowed it to the line `AudioKit.start()`

**Comment by aure** [comment]
@returnzer0 This should be fixed in the develop branch, we'll make a new release soon.

**Comment by returnzer0** [comment]
@aure Thanks! It works now, but for making it work on your app, would one just copy the framework from the Frameworks folder and then put it in a folder in the project instead of using cocoapods?

If not, how would one install cocoapods from the developer branch?

Thanks!

**Comment by aure** [comment]
Yeah, just build the framework and use it instead of using Cocoapods.

**Comment by returnzer0** [comment]
Thank you very much! And thanks once again for building such an awesome framework! 😄

**Comment by dkun7944** [comment]
@aure Is this in the latest release now? I'm getting this error too.

**Comment by aure** [comment]
The session management bug fix is in the latest release, yes.  If there's a bug, probably deserves a new issue.
