### ISSUE TITLE
Sampler Instrument Playground Wave File Problem?

### ISSUE THREAD

**Issue by WholeCheese** [audiokit/AudioKit#404]
I am Playing around with building an iOS wind chime app but figured the playground "Sampler Instrument" was the best first place to start.  However, there seems to be a bug in AKSampler().loadWav()   Below is my modified version with comments - see: BUG!

Note that I have copied all of my .wav files to the appropriate place in the playground bundle.

Is there a way to upload my wave files to GitHub so someone can test this?  Or can someone give me a hint how I can debug it?  Actually, if you just reach into the Resources/Sounds and change the file "fmpia1.wav" to "1-G#5-835Hz.wav" you will see (not hear) the problem.

-Allan

//: [TOC](Table%20Of%20Contents) | [Previous](@previous) | [Next](@next)
//:
//: ---
//:
//: ## Sampler Instrument - Wav File
//: ### Loading a sampler with a reference wav file

import XCPlayground
import AudioKit

let pulse = 0.523 // seconds

let sampler1 = AKSampler()
let sampler2 = AKSampler()
let sampler3 = AKSampler()
let sampler4 = AKSampler()

//: Here is where we reference the Wav file in the AudioKit.playground bundle: Resources/Sounds
//sampler.loadWav("Sounds/fmpia1")
//sampler.loadWav("Sounds/kylebell1-shrt")

//	BUG!  My prefered file names are:
//		1-G#5-835Hz.wav
//		2-C#6-1125Hz.wav
//		3-E6-1337Hz.wav
//		4-G#6-1638Hz.wav
//	For some reason the names with a '#' appear to load (no error) but they will not play.
//	Also the file named 3-E6-1337Hz.wav appears to load but will not play.
//	If I change the file names as follows then it all works as expected, sounds nice too!

sampler1.loadWav("Sounds/1-Gshrp5-835Hz")
sampler2.loadWav("Sounds/2-Cshrp6-1125Hz")
sampler3.loadWav("Sounds/Test")
sampler4.loadWav("Sounds/4-Gshrp6-1638Hz")

// Note that the two wave files "Test" and "3-E6-1337Hz" are identical binary files but the one
// named "3-E6-1337Hz" will not play.

//sampler1.loadWav("Sounds/3-E6-1337Hz")
//sampler2.loadWav("Sounds/3-E6-1337Hz")
//sampler3.loadWav("Sounds/3-E6-1337Hz")
//sampler4.loadWav("Sounds/3-E6-1337Hz")

//sampler1.loadWav("Sounds/Test")
//sampler2.loadWav("Sounds/Test")
//sampler3.loadWav("Sounds/Test")
//sampler4.loadWav("Sounds/Test")

//let ampedSampler = AKBooster(sampler, gain: 0.50)

var delay1  = AKDelay(sampler1)
delay1.time = pulse * 1.5
delay1.dryWetMix = 0.3
delay1.feedback = 0.2

var delay2  = AKDelay(sampler2)
delay2.time = pulse * 1.5
delay2.dryWetMix = 0.3
delay2.feedback = 0.2

var delay3  = AKDelay(sampler3)
delay3.time = pulse * 1.5
delay3.dryWetMix = 0.3
delay3.feedback = 0.2

var delay4  = AKDelay(sampler4)
delay4.time = pulse * 1.5
delay4.dryWetMix = 0.3
delay4.feedback = 0.2

let reverb1 = AKReverb(delay1)
let reverb2 = AKReverb(delay2)
let reverb3 = AKReverb(delay3)
let reverb4 = AKReverb(delay4)

reverb1.loadFactoryPreset(.SmallRoom)
reverb2.loadFactoryPreset(.SmallRoom)
reverb3.loadFactoryPreset(.SmallRoom)
reverb4.loadFactoryPreset(.SmallRoom)

let mix = AKMixer(reverb1, reverb2, reverb3, reverb4)

//: Connect the mixer to the main output
AudioKit.output = mix
AudioKit.start()

//: This is a loop to send a random note to the sampler
//: The sampler 'playNote' function is very useful here
AKPlaygroundLoop(every: pulse)
{
	let scale = [0, 2, 4, 5, 7, 9, 11, 12]
	var note = scale.randomElement()

	let octave = randomInt(3...6) * 12

	if !scale.contains(note % 12) { print("ACCIDENT!") }
	
	let rnd = random(0, 4)
	if rnd > 3
	{
		print("play 1")
		sampler1.playNote(note + octave)
	}
	else
	if rnd > 2
	{
		print("play 2")
		sampler2.playNote(note + octave)
	}
	else
	if rnd > 1
	{
		print("play 3")
		sampler3.playNote(note + octave)
	}
	else
	{
		print("play 4")
		sampler4.playNote(note + octave)
	}
}

XCPlaygroundPage.currentPage.needsIndefiniteExecution = true
//: [TOC](Table%20Of%20Contents) | [Previous](@previous) | [Next](@next)

**Comment by aure** [comment]
You can email me a zip to aure at audiokit dot io or we can do a screenshare.

**Comment by aure** [comment]
We've shared files and figured out that Apple's sampler unit is very touchy with file names and doesn't like dashes or numbers as the first character, etc.   Weird, but there doesn't seem like much I can do about it.  I suppose we could file a radar with Apple if it becomes an issue
