### ISSUE TITLE
AKNodeRecorder creates empty file.

### ISSUE THREAD

**Issue by roecrew** [audiokit/AudioKit#405]
AKNodeRecorder is creating empty files for me.
I don't think installTapOnBus's block is being called. As for why...
Is anyone else having this issue?

**Comment by aure** [comment]
Playing and Recording is definitely the order of the day with Laurent also looking at making improvements so we'll tackle this.

**Comment by laurentVeliscek** [comment]
Should be fixed soon !
:-)
I have a working beta that does the job.
But not happy with my implementation. Give me 2 days !...
 :-)

**Comment by roecrew** [comment]
Sounds good!

**Comment by laurentVeliscek** [comment]
Fixed !

(should be online soon in the develop branch)

**Comment by aure** [comment]
Nice work Laurent!
