### ISSUE TITLE
Possible to create dynamic Waveforms?

### ISSUE THREAD

**Issue by floriannagel** [audiokit/AudioKit#409]
Hey guys, audio is a hard topic :/
I try to generate a dynamic waveform from the input. The waveform should resize after the record to a view. Anyone an idea? Could i generate it with AudioKit/EZAudio?

**Comment by aure** [comment]
AudioKit/EZAudio will help you make the graph from the samples, but resizing and such is all stuff you'd have to implement yourself.  This is not really an issue for Github, perhaps you can join the Google group and engage with other users that way.
