### ISSUE TITLE
Playground Error: Audio files cannot be non-interleaved

### ISSUE THREAD

**Issue by narner** [audiokit/AudioKit#418]
In the OS X Playgrounds that use audio files, I'm receiving the error log below:

```
2016-06-17 18:14:52.842 com.apple.dt.Xcode.PlaygroundStub-macosx%5B22544:697006%5D Audio files cannot be non-interleaved. Ignoring setting AVLinearPCMIsNonInterleaved YES.
AKAudioPlayer Warning:  "drumloop.wav" is an empty file

```

@laurentVeliscek, could this be related to some of the changes you've made to `AKAudioPlayer`?

**Comment by laurentVeliscek** [comment]
it seems to be. I gonna check this.

2016-06-18 0:20 GMT+02:00 Nick Arner <notifications@github.com>:

**Comment by laurentVeliscek** [comment]
Okay !
I found where it came from. A specific init for AKAudioFile that lets you use a string file path is missing. 
I will work tomorrow on AKAudioFile and AKAudioPlayer. Will be fixed I promise. :-)

**Comment by aure** [comment]
I believe I've fixed most of the playgrounds on the develop branch. @narner if you want want to check them again, that would be great.

**Comment by narner** [comment]
@aure I've pulled from develop, deleted the Derived Data folder, and rebuilt the framework in the OS X playgrounds. Seeing errors like this: 
```
AKAudioPlayer Warning:  "guitarloop.wav" is an empty file
```

**Comment by aure** [comment]
Restored those files, should work again.

**Comment by narner** [comment]
@aure All working as expected. Thanks for catching that.
