### ISSUE TITLE
Setting generator parameters before AudioKit.start() results in unfiltered range

### ISSUE THREAD

**Issue by roecrew** [audiokit/AudioKit#421]
Say we have the following code.

```
var oscillator = AKOscillator()
oscillator.amplitude = 100.0
AudioKit.output = oscillator
AudioKit.start()
oscillator.play()
```

This will blow your speakers (it almost did for me).
If a generator's parameter is set before AudioKit.start() is called. The range of the parameter isn't checked!!!

I think the best fix would be to remove the else statement from every generator parameter code. Then if the user tries to set the parameter before AudioKit.start(), the value will be ignored, and the default will be used.
```
public var amplitude: Double = 1 {
  willSet {
            if amplitude != newValue {
                if internalAU!.isSetUp() {
                    amplitudeParameter?.setValue(Float(newValue), originator: token!)
                } else { // remove this
                    internalAU?.amplitude = Float(newValue)
                }
            }
        }
    }
```

Does this seem like a reasonably solution?

**Comment by aure** [comment]
Damn, I can't believe it.  You're absolutely right that no bounds are ever checked.  I will try to fix this in a global way.  Very good find.

**Comment by aure** [comment]
I have fixed this on a local branch, will do it for all nodes and then make a push to develop.

**Comment by aure** [comment]
I did push the oscillator fix up to develop since it will take me a little while to do it for all nodes.

**Comment by aure** [comment]
Aside from the physical models, all of which are getting some attention, the bounds are being checked on all parameters at the DSP level so I think we're good.  Let me know if not.
