### ISSUE TITLE
AKPluckedString amplitude decay rate

### ISSUE THREAD

**Issue by kkleidal** [audiokit/AudioKit#424]
It would be nice to have an amplitude decay rate parameter for AKPluckedString.

I tried using AKOperation.pluckedString so that I could set durations of the attack and decay, but I'm running into problems with AKOperation.pluckedString where if I trigger the operation generator node very frequently, I get points where the audiokit output node flatlines briefly.  I'm thinking that it might be triggering the operation generator too frequently and it lags and fails to fill a buffer (but I really haven't looked very much into the internals).

Any help for either issue would be much appreciated.

**Comment by kkleidal** [comment]
Solved my problem with AKAmplitudeEnvelope.

I'm still concerned about the AKOperation though.  If you want, I can try to do more diagnostics for that.

**Comment by kkleidal** [comment]
Actually, I'm still having problems, because I can't retrigger the ADSR.  I think I'm having a similar problem as was mentioned in this thread:  https://groups.google.com/forum/#!topic/audiokit/dLZxjGf2KVE

**Comment by aure** [comment]
Also, adsr recently changed again, might want to check that: https://github.com/audiokit/AudioKit/pull/416/files

**Comment by aure** [comment]
Any updates on this?  Will close for now.
