### ISSUE TITLE
Display values of AKOperation.parameters(i)

### ISSUE THREAD

**Issue by zmcartor** [audiokit/AudioKit#429]
`AKOperation.parameters` is an array of 16 `Double` values. When attempting to inspect the value of `AKOperation.parameters(0)` , it returns `(p 2)`.  Expected a `Double` value to be returned.

Could the default values for `AKOperation.parameters[0-15]` please be documented somewhere?

As I understand it, these parameters can be substituted for any other other param. It would be helpful to understand exactly what the `Double` typed value is within `AKOperation.parameters`

**Comment by aure** [comment]
Pretty sure the default values are just zeroes.  The parameters are sent in to the operation the p values, offset by two to make room for default triggers.

**Comment by aure** [comment]
So, I think I see the issue here.  AKOperation.parameters(0) is a method to use the zeroth value inside the buliding of an operation.  If you just want to access the operation's parameters from elsewhere, you want to use operationInstance.parameters[0] ...  If that doesn't help feel free to reopen the issue.

**Comment by zmcartor** [comment]
hello, appreciate the discussion. 

Unfortunately, that doesn't make it any clearer what the 'value' of `AKOpertaion.parameters(N)` represents. 

Could please post an example of what is meant by "access operations parameters from elsewhere?"
The docs are not clear on how parameter assignment works or how assigning opaque param indexes affects the params within the operation. 

The phrase 'operation's parameters' is extremely vague. What specific params are we talking about and what are the values of these params.

In the AutoPan example 
`let oscillator = AKOperation.sineWave(frequency: AutoPan.speed, amplitude: AutoPan.depth)` 

What are the values of AutoPan.speed and AutoPan.depth ? I can see that they are accessing `AKOperation.parameters(0)` and `AKOperation.parameters(1)` , but what is the REAL scalar value of the speed and pan ?

**Comment by aure** [comment]
Parameters are just a double array as you know, and its up to you to fill them and keep track of which index represents.   I made the enum in the AutoPan as an example of one way to manage that complexity.  Operations are built with Sporth, so these parameters are a bridge between what is available in swift as parameters[] and what is available in Sporth as p values, ie. paramers().   Perhaps you're discovering and proving that the system is kinda crappy and needs to be improved!  Or perhaps by the time I explain it here, it can be converted into real docs.

**Comment by aure** [comment]
In the AutoPan playground, change these functions:

    func setSpeed(slider: Slider) {
        effect.speed = Double(slider.value)
        speedLabel!.text = "Speed: \(String(format: "%0.3f", effect.speed))"
        printParameters()
    }

    func setDepth(slider: Slider) {
        effect.depth = Double(slider.value)
        depthLabel!.text = "Depth: \(String(format: "%0.3f", effect.depth))"
        printParameters()
    }
    
    func printParameters() {
        let realSpeed = effect.parameters[AutoPanParameter.Speed.rawValue]
        let realDepth = effect.parameters[AutoPanParameter.Depth.rawValue]
        print("speed = \(realSpeed), depth = \(realDepth)")
    }

**Comment by zmcartor** [comment]
Thanks very much for the sample code! 

Finally clicked that the param values come from the enclosing `AKOperationEffect` or `AKOperationGenerator` . This allows parameterization of all the contained `AKOperations` etc from the top-level params. 

It seems that the value of  `AKOperation.parameter(0)` cannot be known because of the way `AKOperationEffect` and `AKOperationGenerator` are built in a bottom-up fashion instead of top-down.

Happy to contribute documentation playground for parameters 👍

**Comment by aure** [comment]
I'd love to see a new playground that exposes this a bit more.  I'm happy to consult on it if you want to have a go!
