### ISSUE TITLE
Playing audio in background while analyzing waveform

### ISSUE THREAD

**Issue by dennisfedorko** [audiokit/AudioKit#437]
Is it possible to play audio in the background, such as when playing a song using the spotify app, and analyzing the microphone input to produce a waveform? Everything I have tried so far causes the music to stop playing when running AudioKit.start()

**Comment by aure** [comment]
This is an AVAudioSession configuration thing.  I'm not sure we can predict all the possible configurations people would want, but we will be trying to make it easier in the future.  For now, not much can be done on this issue :-/
