### ISSUE TITLE
AudioKit.playground with XCode 7,3,1

### ISSUE THREAD

**Issue by ukelady** [audiokit/AudioKit#439]
Hi, I've just started playing with AudioKit. I've got the framework working on my system but I am unable to use AudioKit.playground. I downloaded the source code and built the iOS part of the project (by loading AudioKit/iOS/AudioKit For iOS.xcodeproj). But I am not able to execute the playgrounds. So I wonder if it's tested with XCode 7.3.1?

**Comment by narner** [comment]
@ukelady Hey there, can you provide some detail on the problem you're having?

**Comment by ukelady** [comment]
@narner - sorry I clicked enter twice so I published a blank issue by mistake. Now the question is updated. You answered incredibly fast :D

**Comment by ukelady** [comment]
So it turns out it does work. It is just the text formatting isn't working properly (see screenshot), which confuses me. I'll close the issue now. Thanks for the swift reply!

<img width="996" alt="screen shot 2016-06-27 at 18 55 34" src="https://cloud.githubusercontent.com/assets/1383198/16388472/97cdca8a-3c99-11e6-8459-8ea8e64157f9.png">
<img width="1273" alt="screen shot 2016-06-27 at 19 02 06" src="https://cloud.githubusercontent.com/assets/1383198/16388505/aeb8d17c-3c99-11e6-9f06-a044d6e6987b.png">

**Comment by narner** [comment]
@ukelady Ahh I know what the problem is. It looks "Rendered Documentation" is turned off. I'm not sure why, as I made a pull request enabling documentation to be rendered by default (https://github.com/audiokit/AudioKit/pull/403). But glad things are working for you!
