### ISSUE TITLE
Offer an envelope generator audio unit with multiple sustain points

### ISSUE THREAD

**Issue by brettbits** [audiokit/AudioKit#440]
I was looking into AKAmplitudeEnvelopeAudioUnit.h and thinking about something that I'd like to achieve, which is an envelope generator with multi-point sustain. Using the existing ADSR model, delay duration would determine the duration to the S level as it does already. Additional sustain points could be specified in an array, e.g.

// pseudocode only, this needs to be an object
typedef sustainPoint {
    float duration; // duration to arrive at this sustain level
    float level;
}

@property (nonatomic) NSArray *additionalSustainPoints;

I'm just beginning with AudioKit so if there is another way which amplitude could be modulated with an envelope more complex with ADSR, I haven't discovered it yet. Thanks for reading!

**Comment by aure** [comment]
This seems kind of complex and specific for inclusion in the toolkit itself, but you should be able to implement something like this within AudioKit in a few different ways. You should probably also join the AudioKit Google group where we can discuss this further.
