### ISSUE TITLE
Consider renaming AKNoiseGenerator.whitePinkMix

### ISSUE THREAD

**Issue by brettbits** [audiokit/AudioKit#441]
By name alone, I can't determine if whitePinkMix = 1.0 is 100% white noise or 100% pink noise. I propose that this class is given independent whiteLevel and pinkLevel properties, where setting one implicitly sets the other to total 1.0.

Example:

let noise = AKNoiseGenerator()
noise.whiteLevel = 0.9
// pinkLevel now equals 0.1

I see however that this could impact the init method AKNoiseGenerator(whitePinkMix: voices: ).

**Comment by aure** [comment]
Brilliant!  Coming right up.

**Comment by aure** [comment]
Oh, actually on develop we deprecated this instrument as it currently stands, but I will implement it this way in the next incarnation.

**Comment by aure** [comment]
So, gonna close this issue for now. Thanks though!
