### ISSUE TITLE
AudioKit missing a resonant filter

### ISSUE THREAD

**Issue by dclelland** [audiokit/AudioKit#453]
Hi @aure 

As part of upgrading to AudioKit 3, I discovered that AudioKit no longer has support for the old AKResonantFilter/reson opcode.

I spoke with @PaulBatchelor about it, turns out he used to have a port of Csound's reson opcode in Soundpipe, but as it's not the most stable filter, he removed it in [September last year](https://github.com/PaulBatchelor/Soundpipe/commit/9f461bf20c56d7ab8768c4eee5445f254eb0d052), but he's happy to put it back in.

If you're okay with this, I'm happy to help by putting a PR together if need be, just point me in the right direction :)

**Comment by aure** [comment]
Depending on the parameters, I'd just copy the folder for another similar node and make the tweaks as necessary.  Putting the soundpipe in is very easy.

**Comment by PaulBatchelor** [comment]
@dclelland I've just re-added the reson code back into Soundpipe in the dev branch.

**Comment by dclelland** [comment]
@PaulBatchelor Thanks very much :) I'm going to be out of town for a few days but will have a look when I get back.

**Comment by dclelland** [comment]
@PaulBatchelor do I need to add reson into Sporth, as well?

**Comment by PaulBatchelor** [comment]
@dclelland only if you plan on using reson inside of Sporth. I'll bring it back for you.

**Comment by aure** [comment]
I have some scripts to automate this process, I can run them to at least get the ball rolling unless you want to experience the full from-scratch experience Daniel.

**Comment by dclelland** [comment]
I'll show you what I have so far

**Comment by dclelland** [comment]
Have added a PR with the progress I've made so far... https://github.com/audiokit/AudioKit/pull/471

**Comment by aure** [comment]
I think we can move this conversation to the pull request so that things are in context with the code in question.
