### ISSUE TITLE
Build Framework for Simulator and Device

### ISSUE THREAD

**Issue by enriquesalas506** [audiokit/AudioKit#455]
This is not an issue but I have searched through all forums and haven't found the solution.
I am on the development branch on AudioKit to get the latest upgrades and fixes. The problem is when I build the framework I just get the device product or the simulator product.
I tried to use the _lipo_ tool but when I add the framework and compile it gives me an Installation error. This doesn't happen when I add the device or the simulator framework.

If any one can help to build a fat framework would be much appreciated. Thanks.

**Comment by megastep** [comment]
The proper way to generate universal frameworks is to use the `build_frameworks.sh` script in the Frameworks directory. Is this how you are trying to build the framework? Otherwise you will only get the architecture you selected in Xcode.

**Comment by enriquesalas506** [comment]
Where do I have to add the script?
In Build Phases?

**Comment by megastep** [comment]
You don't use it in Xcode, you run it once from a terminal and it builds the frameworks that you then use in your projects. They will be located under `Frameworks/AudioKit-iOS`, and so on. This is essentially what we release as binary archives.

**Comment by aure** [comment]
Have you seen https://github.com/audiokit/AudioKit/blob/master/Frameworks/INSTALL.md ?

**Comment by enriquesalas506** [comment]
Yes _aure_ I just wanted to be able to generate the framework file. 
_Megastep_ thanks. I just used the sh file. I just builded the framework file. 
Everything is working now in the simulator and the device.

Thanks for your help

**Comment by iosDemo99880** [comment]
Hello EveryOne,

I created o demo of framework using swift, working fine both simulator and device, but i want to create one framework for both (simulator and device). i am using lot of script and commands in terminal.
Anyone help me , how to create it to universal for using with simulator as well as Device.
Please

Thanks
