### ISSUE TITLE
gatedADSREnvelope broken when sustain = 0

### ISSUE THREAD

**Issue by ukelady** [audiokit/AudioKit#462]
Hi, 

When the sustain value is 0, there would be no sound coming out of the system after triggering a few keys (rapidly). You can reproduce the issue by modifying the **Filter Envelope** example in the playground. 

With the develop branch, at line 48, change sustain to 0:
`
let cutoff = Synth.cutoff.gatedADSREnvelope(Synth.gate, attack: 0.1, decay: 0.01, sustain: 0.0, release: 0.6)`

Then Trigger a few notes, you should eventually hear no sounds coming out when a key is triggered

**Comment by aure** [comment]
This is fixed in the develop branch, thanks!
