### ISSUE TITLE
AKFrequencyTracker() at low freq

### ISSUE THREAD

**Issue by rmoughan** [audiokit/AudioKit#490]
I was wondering if there is a way to change the class implementation of AKFrequencyTracker() to get it to work at frequencies lower than 27 Hz (right now that appears to be the lower bound). This isn't for analyzing music, but waveforms for science. I program in Swift and I love AudioKit, thanks to everyone who works hard to support it, but I don't know enough to go in and work on the tracker. If anyone could help we'd really appreciate it.

**Comment by aure** [comment]
That's a very low frequency, almost in the realm of beat detection.  I don't think it would be a matter of editing the current frequency tracker.  It would be fundamentally different.

**Comment by rmoughan** [comment]
Thanks for letting me know. Could you point me to any software or theory that could help?

Thanks,

Ryan Moughan

**Comment by aure** [comment]
Maybe @PaulBatchelor might know where to look

**Comment by rmoughan** [comment]
Great, thanks.

**Comment by PaulBatchelor** [comment]
@rmoughan hmm... I really don't know of any ready-to-go software suitable sub-audio frequency detection. I'd search the literature for keywords like "warped fft" or "warped signal processing". Good luck!
