### ISSUE TITLE
Reading and Writing Audio Files playground

### ISSUE THREAD

**Issue by ferama** [audiokit/AudioKit#499]
I'm trying to normalize and apply some reverb to an audio file on an iOS app. The audio file need to be exported to the Document folder but I don't understand how to accomplish it.

To experiment with something more simple I downloaded the AudioKit source code and played with the playgrounds.

Running the Reading and Writing Audio Files playground, myExportCallback seems to be never called and print ("myExportCallBack has been triggered. It means that export ended") never print :)

I'm doing something wrong or there is an issue?

**Comment by aure** [comment]
There is no known issue regarding this.  Hard to say with is wrong with your stuff with the amount of information provided.  If you can post the project to github I can have a look.  Closing the issue until further information.

**Comment by ferama** [comment]
I'm talking about this playground 

https://github.com/audiokit/AudioKit/blob/master/AudioKit/iOS/AudioKit/AudioKit.playground/Pages/Reading%20and%20Writing%20Audio%20Files.xcplaygroundpage/Contents.swift

If you run it, "myExportCallback" is called and "drumloop" is exported correctly?

**Comment by aure** [comment]
If you open up the console portion of the screen (at the bottom) you're probably seeing an error message like this:  ERROR AKAudioFile export: cannot create an AVAssetExportSession!...
which is stopping the rest of this playground from running.  That's the bug I am seeing and I'm going to keep this issue open until it is resolved.  There is still pretty active development of AKAudioFile by me and @laurentVeliscek so we'll definitely correct this problem.  Thank you!!!

**Comment by ferama** [comment]
Thanks. I'm trying to investigate and the problem seems to be related to the outputURL of the AVAssetExportSession. The following playground works but on first execution only. If i change anything (add a simple print somewhere for example), it throws the error you mentioned. I'm just a swift and Xcode beginner so surely you will solve before me :) 

`
import Foundation
import XCPlayground
import AudioKit

let file = try AKAudioFile(readFileName: "drumloop.wav", baseDir: .Resources)

let asset  = AVURLAsset(URL: file.url)
let exporter = AVAssetExportSession(asset: asset, presetName: AVAssetExportPresetPassthrough)


let documentsDirectory = NSFileManager.defaultManager().URLsForDirectory(.DocumentDirectory, inDomains: .UserDomainMask)[0]
var outputPathURL = documentsDirectory.URLByAppendingPathComponent("out.wav")

// NEVER WORKS. Why?
//
//var filePath: String
//filePath = "/Users/ferama/tmp/out.wav"
//var outputPathURL = NSURL.fileURLWithPath(filePath)

exporter!.outputURL = outputPathURL
print(exporter!.outputURL)

exporter!.outputFileType = AVFileTypeWAVE as String
let timeRange = CMTimeRangeMake(kCMTimeZero, asset.duration)
exporter!.timeRange = timeRange
exporter!.exportAsynchronouslyWithCompletionHandler({
    () -> Void in
    print("here")
    
    switch exporter!.status {
        case  AVAssetExportSessionStatus.Failed:
            print("ERROR AKAudioFile: Export Failed!...")
            print("Error: \(exporter!.error)")
        case AVAssetExportSessionStatus.Cancelled:
            print("ERROR AKAudioFile: Export Cancelled!...")
            print("Error: \(exporter!.error)")
        default:
            // Export succeeded !
            // We create an AKAudioFile from the exported audioFile
            let url = NSURL(string: exporter!.outputURL!.path!)
            print("success")
        
        }
    
    }
)
XCPlaygroundPage.currentPage.needsIndefiniteExecution = true
`

**Comment by laurentVeliscek** [comment]
There's strange things with Avasset things.
I spent hours to figure out that the file path should begin with file:// with Avasset and a file path beginning with a slash won't. I got crazy with this behavior. And I couldn't find an easy way to convert from relative to absolute and reverse. So there's a lot of mysterious code in AKaudioFile export code to handle this. 

I'm in holidays, far from a keyboard and may be it is not the reason of the bug you mentioned but it made me think of this weird behavior using Avasset universe.
So may be this is a clue for investigating.

Good luck !

Laurent.
Envoyé de mon iPhone

**Comment by laurentVeliscek** [comment]
Here:


    private lazy var internalAVAsset: AVURLAsset = {
        let avAssetUrl = NSURL(fileURLWithPath:self.url.absoluteString)
        return AVURLAsset(URL: avAssetUrl)
    }()

The weird thing is that avurlasset(URL: url) won't work...
I had to use this trick to make it work...

Best !

Laurent.


Envoyé de mon iPhone

**Comment by ferama** [comment]
Ok i figured out something. The output file need to be deleted if it already exists. Here the updated playground. Now the problem is that it doesn't work if I use the normalized AKAudioFile instead of the original one.

```
//: [Previous](@previous)

import Foundation
import XCPlayground
import AudioKit

let file = try AKAudioFile(readFileName: "drumloop.wav", baseDir: .Resources)

let normalized: AKAudioFile
normalized = try file.normalize()

// Doesn't Works!!!
//let asset  = AVURLAsset(URL: normalized.url)
let asset  = AVURLAsset(URL: file.url)

let exporter = AVAssetExportSession(asset: asset, presetName: AVAssetExportPresetPassthrough)


let documentsDirectory = NSFileManager.defaultManager().URLsForDirectory(.DocumentDirectory, inDomains: .UserDomainMask)[0]
var outputPathURL = documentsDirectory.URLByAppendingPathComponent("out.wav")

let fileManager = NSFileManager.defaultManager()
print(outputPathURL.path)
if fileManager.fileExistsAtPath(outputPathURL.path!) {
    print("File exists")
    do {
        try fileManager.removeItemAtURL(outputPathURL)
    }
    catch let error as NSError {
        print("Ooops! Something went wrong: \(error)")
    }
} else {
    print("File doesn't exists")
}


exporter!.outputURL = outputPathURL
print(exporter!.outputURL)

exporter!.outputFileType = AVFileTypeWAVE as String
let timeRange = CMTimeRangeMake(kCMTimeZero, asset.duration)
exporter!.timeRange = timeRange
exporter!.exportAsynchronouslyWithCompletionHandler({
    () -> Void in
    print("here")
    
    switch exporter!.status {
        case  AVAssetExportSessionStatus.Failed:
            print("ERROR AKAudioFile: Export Failed!...")
            print("Error: \(exporter!.error)")
        case AVAssetExportSessionStatus.Cancelled:
            print("ERROR AKAudioFile: Export Cancelled!...")
            print("Error: \(exporter!.error)")
        default:
            // Export succeeded !
            // We create an AKAudioFile from the exported audioFile
            let url = NSURL(string: exporter!.outputURL!.path!)
            print("success")
        
        }
    
    }
)
XCPlaygroundPage.currentPage.needsIndefiniteExecution = true

//: [Next](@next)

```

**Comment by laurentVeliscek** [comment]
About :
// Doesn't Works!!! //let asset = AVURLAsset(URL: normalized.url) 
let asset = AVURLAsset(URL: file.url)
Did you try :
Let asset = normalized.avAsset 
?

Best,
Laurent.


Envoyé de mon iPhone

**Comment by ferama** [comment]
normalized.avAsset works!

**Comment by aure** [comment]
Does this issue need any further action or can it be closed?

**Comment by aure** [comment]
This seems to be an orphaned issue, possibly fixed.
