### ISSUE TITLE
need help with AKAudioPlayer

### ISSUE THREAD

**Issue by EssamSoft** [audiokit/AudioKit#500]
Hi

I just need help to play wav file with change file 

    let file   = NSBundle.mainBundle().pathForResource("song", ofType: "wav")
    let song  = AKAudioPlayer(file!)
    
    override func viewDidLoad() {
        super.viewDidLoad()
    
        AudioKit.output = song
        AudioKit.start()

        song.play()
    }

    
    @IBAction func btn(sender: AnyObject) {
        
        song.replaceFile("NewFile")
        
    }

    
    

@aure

**Comment by aure** [comment]
This is not an AudioKit issue, but a request for support, which is better served by posting to the forum: https://groups.google.com/forum/#!forum/audiokit
