### ISSUE TITLE
Way to enable sporth 'print' function

### ISSUE THREAD

**Issue by jdundee** [audiokit/AudioKit#501]
Hi Aure

Do you know if there is a way to enable the 'print' function in sporth? It's a documented function but seems to be unavailable in AudioKit. I think it would really help me to debug sporth code. Or is there another recommended way to track values in sporth?

Many thanks
John.

**Comment by aure** [comment]
Set the parameter and it will be accessible from the node's parameter array.  "7 pset" for instance would store the parameter into the 8th element of the array, then you can access and print it.

**Comment by jdundee** [comment]
Aure

Thank you so much for such a rapid and precise solution. 

Best wishes
John.

**Comment by aure** [comment]
No problem!
