### ISSUE TITLE
Cannot submit app with AudioKit (3.1.3) to AppStore.

### ISSUE THREAD

**Issue by Asbat** [audiokit/AudioKit#502]
AudioKit (3.1.3) is installed via pods. The app builds properly but when I try to submit it to AppStore I receive the following error:

>  ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all.

If I rebuild the app without AudioKit and try to submit it again it succeeds.

**Comment by aure** [comment]
Apple's changing code signing for frameworks to optional in Xcode 8 so this is not a long term issue, but we just submitted an AK3.1.3 powered app and didn't have any problems.  @megastep Helped me set that up so he may have some words of wisdom for you.

**Comment by megastep** [comment]
Mostly you want to make sure that the script we include in the framework is properly called in your build phase. We have documentation about that here:

https://github.com/audiokit/AudioKit/blob/master/Frameworks/INSTALL.md

**Comment by Asbat** [comment]
I just submitted my app successfully after reading the section "Handling Bitcode" from INSTALL.md.

Just one note: I was trying to submit the app without BITCODE enabled and still it didn't want to accept the build. So you could probably add that to the docs.

Thanks @aure @megastep !
