### ISSUE TITLE
update pod

### ISSUE THREAD

**Issue by Ferrick90** [audiokit/AudioKit#505]
Hi, could update Cocoapods v3.2?

**Comment by aure** [comment]
We tried this go around but got a cryptic error.   We'll try with 3.2.1 as well to see if it has changed.

**Comment by aure** [comment]
Going to see if this helps http://codeslingers.co.uk/2014/05/16/why-your-podspec-is-failing/

**Comment by Ferrick90** [comment]
OK. Thanks Aure

**Comment by aure** [comment]
If anyone has any clues for me, the full output of the pod spec lint is here:

https://gist.github.com/aure/49e4f8d5c4b13252608c26d60308d74d

Everything goes well and then at the end..

** BUILD SUCCEEDED **

 -> AudioKit (3.2)
    - ERROR | [OSX] xcodebuild: Returned an unsuccessful exit code.

**Comment by Ferrick90** [comment]
Hi, I have tried pod lib lint to testing it. Get this error below:

 -> AudioKit (3.2)
    - ERROR | file patterns: The `source_files` pattern did not match any file.

**Comment by aure** [comment]
that error I got past by specifying source_files, but still no.

**Comment by aure** [comment]
We're very close to fixing this I believe.

**Comment by Ferrick90** [comment]
Could early of Sep release AudioKit v3.2.1? I noticed v3.2 that's not very stable.

**Comment by aure** [comment]
Ferrick, AudioKit is free and open-source written and maintained by volunteers.  I was willing to keep this issue open for you until resolution, but not now that you are suggesting a schedule for us and making statements on stability.

**Comment by Ferrick90** [comment]
@aure  I'm so sorry about that, just willing to know because I got project deadline. Else I can start to try another way to archive my project. Hope u can understand my situation.

**Comment by aure** [comment]
I am back from the conference and will be working on AudioKit a lot this week so hopefully everything gets done soon.  Thanks!

**Comment by aure** [comment]
Updated cocoapods to 3.3 on iOS and tvOS.  Something still weird on macOS with Cocoapods.
