### ISSUE TITLE
Can't update AKSequencer track length 

### ISSUE THREAD

**Issue by JoshuaBThompson** [audiokit/AudioKit#508]
Trying to do the following:
```swift
sequencer.newTrack()
sequencer.setLength(AKDuration(seconds: 8))
sequencer.setTempo(120)
sequencer.tracks[0].setMIDIOutput(bassDrum.midiIn)

sequencer.tracks[0].add(noteNumber: 60, velocity: 127, position: AKDuration(seconds: 0), duration:AKDuration(seconds: 0.1))
sequencer.tracks[0].add(noteNumber: 60, velocity: 100, position: AKDuration(seconds: 0.5), duration:AKDuration(seconds: 0.1))
sequencer.tracks[0].add(noteNumber: 60, velocity: 100, position: AKDuration(seconds: 1), duration:AKDuration(seconds: 0.1))
sequencer.tracks[0].add(noteNumber: 60, velocity: 100, position: AKDuration(seconds: 1.5), duration:AKDuration(seconds: 0.1))


sequencer.enableLooping()
sequencer.play()

/*....some time later .....*/
sequencer.stop()
sequencer.disableLooping()
sequencer.setLength(AKDuration(seconds: 4)) //shorten loop length
sequencer.enableLooping()
sequencer.play()
/*....start playing loop again....*/
```

Doesn't update the loop length though.

Am I updating incorrectly?
Thank you :)

**Comment by aure** [comment]
setting the length in the example project "Sampler Demo" appears to be working.  The only thing that loos weird here is perhaps disabling and then re-enabling looping with setting the length in between.  Happy to take a look at the project if its shareable. 

Aure

**Comment by JoshuaBThompson** [comment]
Hi Aure,
Thank you. I tried removing the disable / re-enable code and the behavior changed slightly. It played the loop one time and then did not play it anymore.

I'm running the 'Sequencer - single output' playground with my own edits.

Here is the playground code:
```swift
var sequencer = AKSequencer()
let midi = AKMIDI()
var bassDrum = AKSynthKick()
bassDrum.enableMIDI(midi.client, name: "bassDrum midi in")

AudioKit.output = bassDrum
AudioKit.start()

sequencer.newTrack()
sequencer.setLength(AKDuration(beats: 8))
sequencer.setTempo(120)
sequencer.tracks[0].setMIDIOutput(bassDrum.midiIn)

sequencer.tracks[0].add(noteNumber: 60, velocity: 127, position: AKDuration(beats: 0), duration:AKDuration(seconds: 0.1))
sequencer.tracks[0].add(noteNumber: 60, velocity: 100, position: AKDuration(beats: 1), duration:AKDuration(seconds: 0.1))
sequencer.tracks[0].add(noteNumber: 60, velocity: 100, position: AKDuration(beats: 2), duration:AKDuration(seconds: 0.1))
sequencer.tracks[0].add(noteNumber: 60, velocity: 100, position: AKDuration(beats: 3), duration:AKDuration(seconds: 0.1))

sequencer.enableLooping()

sequencer.play()

//now change the length of the loop after playing
sequencer.setLength(AKDuration(beats: 4))

//will play loop once and the stop playing anything

XCPlaygroundPage.currentPage.needsIndefiniteExecution = true
```

Am I updating the loop length correctly?

Thank you Aure,
-Josh

**Comment by JoshuaBThompson** [comment]
What's interesting though is that when I initially set the length to 2 instead of 8 then it works....

**Comment by JoshuaBThompson** [comment]
Hi Aure,
There's definitely something strange going on.
When I try and use the setLengthSoft then the track keeps on playing beats but not in the correct order. Also, if I set a new length greater than 8 no beats are played anymore after the first 4 are played.

Here is my playground code:

```swift
var sequencer = AKSequencer()
let midi = AKMIDI()
var bassDrum = AKSynthKick()
bassDrum.enableMIDI(midi.client, name: "bassDrum midi in")

AudioKit.output = bassDrum
AudioKit.start()

sequencer.newTrack()

sequencer.setTempo(60)
sequencer.setLength(AKDuration(beats: 4.0))
sequencer.tracks[0].setMIDIOutput(bassDrum.midiIn)

sequencer.tracks[0].add(noteNumber: 60, velocity: 127, position: AKDuration(beats: 0), duration:AKDuration(seconds: 0.1))
sequencer.tracks[0].add(noteNumber: 60, velocity: 100, position: AKDuration(beats: 1), duration:AKDuration(seconds: 0.1))
sequencer.tracks[0].add(noteNumber: 60, velocity: 100, position: AKDuration(beats: 2), duration:AKDuration(seconds: 0.1))
sequencer.tracks[0].add(noteNumber: 60, velocity: 100, position: AKDuration(beats: 3), duration:AKDuration(seconds: 0.1))

sequencer.enableLooping()
sequencer.play()

sequencer.tracks[0].setLengthSoft(AKDuration(beats: 7.0)) //this will keep playing beats but incorrectly. If I set length to 8.0 then no beats are played after the first 4 beats.
sequencer.rewind()

```

I've only tried using the sequence with a midi instrument like AKSynthKick so maybe this is just a bug with AKMidiInstrument?

Thank you Aure

**Comment by JoshuaBThompson** [comment]
I tried to change the length in the SequencerDemo (iOS) and got the same bug.

What I did was comment out all the other beats (bass, snare, melody...etc) and just played the ghost snare then I edited the code to just update the sequence length after the user hits the regenerate sequence button on the UI.

```swift
func generateSnareDrumGhostSequence(stepSize: Float = 1/8, clear: Bool = true) {
        if(testCount > 0){
            print("snare drum new length!!!")
            sequence.setLength(AKDuration(beats: 16.0))
            sequence.rewind()
            return
        }
        if (clear) { sequence.tracks[Sequence.SnareDrumGhost.rawValue].clear() }
        let numberOfSteps = Int(Float(sequenceLength.beats)/stepSize)
        //print("steps in sequnce: \(numberOfSteps)")
        for i in 0 ..< numberOfSteps {
            if(arc4random_uniform(17) > 14) {
                let step = Double(i) * stepSize
                sequence.tracks[Sequence.SnareDrumGhost.rawValue].add(noteNumber: 60,
                                       velocity: Int(arc4random_uniform(65) + 1),
                                       position: AKDuration(beats: step),
                                       duration: AKDuration(beats: 0.1))
            }
        }
        sequence.setLength(sequenceLength)
        testCount += 1
    }
```

It will stop playing the sequence when you change the beat length to 16.0.

**Comment by aure** [comment]
Can you try all this as an OSX playground?  I wonder if the problem is isolated to iOS. I know that iOS playgrounds can't do external midi for instance.

**Comment by JoshuaThompsonSS** [comment]
I'm trying to get the OSX Playground to work but for some reason I can't resolve the no module named AudioKit error...

**Comment by aure** [comment]
Are you on the develop branch?  Make sure the playground is set to be OSX and not iOS.

**Comment by JoshuaThompsonSS** [comment]
Using master right now. Yeah, set to OSX. 
I've had this problem before with the iOS playground but it always resolved itself after cleaning, building and restarting. 
I'll figure it out eventually.

**Comment by aure** [comment]
Check your "Products" directory and clean out any other versions of AudioKit besides the OS you want.

**Comment by bishop800** [comment]
Check your "Products" directory and clean out any other versions of AudioKit besides the OS you want.

**Comment by JoshuaBThompson** [comment]
Hi Aure,
Sorry haven't tested this on the iOS playground yet. But, I noticed that there have been a few commits to the sequencer source code lately. Has this already been addressed?

**Comment by aure** [comment]
It might have been helped by the recent changes, but I am not sure.

**Comment by JoshuaBThompson** [comment]
Hi Aure, 
Ok got my OSX playground working. The bug is exhibited in the OSX version  as well.
It seems like updating the sequence causes the significant problems.

**Comment by aure** [comment]
Hi Joshua,

Where does this currently stand?

**Comment by JoshuaBThompson** [comment]
Hi Aure, the last time I pulled from the dev branch ( a few weeks ago) this was still an issue.

**Comment by olivierlesnicki** [comment]
I confirm this is still an issue.

**Comment by aure** [comment]
Olivier, could you provide a project that demonstrates what's happening and what you're expecting?

**Comment by olivierlesnicki** [comment]
I've made a couple of observations (note they could be the intended behaviors, they're just not intuitive).

**Any track added after the sequencer `.play()` method has been called is ignored. There's no way to add a new track while the sequencer is playing.**

```swift
init() {
    
    AudioKit.output = mixer
    AudioKit.start()
    
    let kick = AKSynthKick()
    kick.enableMIDI(midi.client, name: "midi")
    
    mixer.connect(kick)
    
    sequencer.setTempo(100)
    sequencer.setLength(AKDuration(beats: 8.0))
    sequencer.enableLooping()
    sequencer.play()

    let track = sequencer.newTrack()
    track?.setMIDIOutput(kick.midiIn)
    track?.add(noteNumber: 60, velocity: 127, position: AKDuration(beats: 0), duration: AKDuration(beats: 1))
    
  }
```
I expected the kick sound to play. It never plays.

**Setting the sequencer length after enabling the loop causes the loop to be disabled.**

```swift
init() {
    
    AudioKit.output = mixer
    AudioKit.start()
    
    let kick = AKSynthKick()
    kick.enableMIDI(midi.client, name: "midi")
    
    mixer.connect(kick)

    let track = sequencer.newTrack()
    track?.setMIDIOutput(kick.midiIn)
    track?.add(noteNumber: 60, velocity: 127, position: AKDuration(beats: 0), duration: AKDuration(beats: 1))
    
    sequencer.setTempo(100)
    sequencer.enableLooping()
    sequencer.setLength(AKDuration(beats: 8.0))
    sequencer.play()
    
  }
```

I expected the kick sound to play in loop. It only plays once. However calling `.enableLooping()` after calling `.setLength()` allow the loop to be restored.

**Comment by eljeff** [comment]
_RE: adding a track while playing...._
You can't do too much editing of the sequence while it is playing. It takes some work to set it up, but properly designed, you can make the sequence behave almost however you want while it is running.

_RE: EnableLooping..._
Just call it after you set the length. The sequence has a default length so the loop first sets it up for that length. When you then change the length, looping needs to be reset to the new length.

**Comment by olivierlesnicki** [comment]
@eljeff - Will go with your suggestions

**Comment by aure** [comment]
With Jeff's comments, can this issue be closed?  We're rearchitecting AKMIDI from the ground up so I'm not too involved in fixes to it right now.  If it works in a predictable way, I think that's the most we can expect for now.
