### ISSUE TITLE
Crash when reaction too fast in Recording

### ISSUE THREAD

**Issue by Ferrick90** [audiokit/AudioKit#510]
Sorry, I encountered recording and sudden stop the recording. It will crash it. 

Result: 
recording
writing ( file duration:  0.0928798185941043 seconds)
writing ( file duration:  0.185759637188209 seconds)
writing ( file duration:  0.278639455782313 seconds)
writing ( file duration:  0.371519274376417 seconds)
Recording Stopped.
recording
AKNodeRecorder Warning: Cannot stop recording, already stopped !
recording
2016-08-04 17:29:29.300 tedmi[13325:4384304] 17:29:29.300 ERROR:    [0x3798e000] AVAudioNode.mm:561: CreateRecordingTap: required condition is false: _recordingTap == nil
2016-08-04 17:29:29.301 tedmi[13325:4384304] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: _recordingTap == nil'
*** First throw call stack:
(0x20d21b0b 0x204dedff 0x20d219e1 0x26622ea9 0x266658d3 0x266629bf 0x1ab6d4c 0x471b50 0x2633dc 0x26659e4f 0x464b1c 0x464c9c 0x253376a1 0x25337631 0x2531f56b 0x2533fe23 0x25336a9f 0x2532f547 0x252ffdd5 0x252fe379 0x20ce39e7 0x20ce35d7 0x20ce193f 0x20c301c9 0x20c2ffbd 0x2224caf9 0x25368435 0x277100 0x208dc873)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by laurentVeliscek** [comment]
Hi ferrick,

I noticed this in your report :

> 0.278639455782313 seconds)
> writing ( file duration: 0.371519274376417 seconds)
> Recording Stopped.
> recording
> AKNodeRecorder Warning: Cannot stop recording, already stopped !
> recording
> 

It is strange... Looks like a problem with multi threading. (Intuition).
Please check aknoderecorder code, may be something wrong somewhere.

I'm not at home (I'm in holidays) so I cannot investigate.

You may check the place where "recording" bool is set to true.

May be it must be moved earlier in the code.

I noticed random crash when record/stop occurs very fast. Checking if tape's length was not zero before allowing stop recording seemed to fix the crash in iOS recorder example. But there's definitely a problem somewhere...

This crash seems to occur randomly (can you confirm?). I suspect that the problem may come from the fact taponbus is a background process. just an intuition...

I couldn't find a way to propagate errors from within the closure. Its signature doesn't allow this. Asked in apple's forum but no answer. So I haven't a solution yet. The way AKNodeRecorder is implemented is standard, no fancy things. May be experiment with different recording buffer length (in aksettings). (Setting the recording buffer size is not officially supported by Apple, I find very strange that it works, but it works. But may be it is related with the crash you mention.)

I noticed that records seemed to truncate the last 300 ms. Shortening the record buffer length doesn't fix the problem (curiously a shorter buffer seems to increase the truncated length).

May be we should check that any buffer data has been properly been written to file before stopping the taponbus record loop.

I just give some clues. This crash is really a problem. Please share if you make some progress with this issue.

Thanks again for pointing this issue.

:-)

Best,

Laurent.

Envoyé de mon iPhone

**Comment by roecrew** [comment]
@Ferrick90 Can you post a bit of your code? Thanks.

**Comment by Ferrick90** [comment]
Hi, @roecrew 

This is a example (https://github.com/audiokit/AudioKit/tree/master/Examples/iOS/Recorder) and try to commenting this line of code (self.performSegueWithIdentifier("stop", sender:recorder.audioFile!.url). And, keep repeat recording and stoping quickly after that crash will appear.

Results:
recording
AKNodeRecorder Warning: Cannot stop recording, already stopped !
recording
AKNodeRecorder Warning: Cannot stop recording, already stopped !
recording
AKNodeRecorder Warning: Cannot stop recording, already stopped !
recording
AKNodeRecorder Warning: Cannot stop recording, already stopped !
recording
AKNodeRecorder Warning: Cannot stop recording, already stopped !
recording
AKNodeRecorder Warning: Cannot stop recording, already stopped !
recording
AKNodeRecorder Warning: Cannot stop recording, already stopped !
recording
AKNodeRecorder Warning: Cannot stop recording, already stopped !
2016-08-05 13:34:28.193 Recorder[13583:4455213] 13:34:28.193 ERROR:    [0x3798e000] AVAudioEngineGraph.mm:1743: _Connect: required condition is false: !destNodeMixerConns.empty() && !isDestNodeConnectedToIONode
2016-08-05 13:34:28.198 Recorder[13583:4455213] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: !destNodeMixerConns.empty() && !isDestNodeConnectedToIONode'
*** First throw call stack:
(0x20d21b0b 0x204dedff 0x20d219e1 0x26622ea9 0x26637945 0x2663abbb 0x26671d61 0x26671ee1 0x26671e0d 0x2709d4 0x80150 0x80470 0x253376a1 0x25337631 0x2531f56b 0x2533fe23 0x25336a9f 0x2532f547 0x252ffdd5 0x252fe379 0x20ce39e7 0x20ce35d7 0x20ce193f 0x20c301c9 0x20c2ffbd 0x2224caf9 0x25368435 0x86b20 0x208dc873)
libc++abi.dylib: terminating with uncaught exception of type NSException

It different error with my project error. In my project error, I guess the recording block a bit slower than stop func.

node!.avAudioNode.installTapOnBus(0, bufferSize: recordingBufferLength, format: internalAudioFile.processingFormat, block: { (buffer: AVAudioPCMBuffer!, time: AVAudioTime!) -> Void in
                do {
                    buffer.frameLength = recordingBufferLength
                    try self.internalAudioFile.writeFromBuffer(buffer)
                    self.recording = true
                    print("writing ( file duration:  \(self.internalAudioFile.duration) seconds)")
                } catch let error as NSError {
                    self.recording = false
                    print("Write failed: error -> \(error.localizedDescription)")
                }
            })

Could try to avoid when the user reaction too fast in this situation.

Thanks.

Regards,
Ferrick Chan

**Comment by laurentVeliscek** [comment]
Hi again ferrick, hi Brandon!

The warnings can be a clue to fix the problem. They shouldn't be printed as long as user don't ask to stop when record is not running. But we get those warnings. So there's something to fix here.

Have you tried to :
- move the "recording = true" earlier in the code and outside of the closure block ? "Recording" could be set to true as soon as the record method has been invoked, at the beginning of the function code.
(It's my guess about the problem)

Other suggestions :
- comment or remove the "print" line from the taponbus closure ?

- may be remove the if "recording is true" check from the stop() method.

Let us know if it helps...

I think there's something wrong and it is probably a thread issue. It seems that it can happen that recording bool can be false even user started to record. There's a latency from when you invoke record() and when it is actually record (buffer is filled) that could explain why you get those warnings.

Something very annoying is the description of the error:
> required condition is false: !destNodeMixerConns.empty() && !isDestNodeConnectedToIONode'
> *** First throw call stack:
> (0x20d21b0b 0x204dedff
> 


There's no reason to get this exception as there's no connection / deconnection that occurs.
May be add a debug print to track user interaction (print "clicked record" and print "clicked stoprecord") and see what is really happening, and what is the instruction that leads to crash (is it record()? Is it stop()?) 
Your report suggest that it is possible that install taponbus is triggered many times (it must not happen), or that remove taponbus is invoked while there's no taponbus set yet (that could may be explain the reason described while crashing)

Thanks,

Best !

Laurent.

Envoyé de mon iPhone

**Comment by aure** [comment]
This appears to have been fixed in the develop branch.  Reopen if not.
