### ISSUE TITLE
Clone/Build issue

### ISSUE THREAD

**Issue by daviddelmonte** [audiokit/AudioKit#512]
Hi. I'm getting this message (Xcode 8 b3, Swift 3): "The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET AudioKit OF PROJECT AudioKit For iOS WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly."

Is there a workaround?

Many thanks for the hard work.

**Comment by aure** [comment]
This is basically a repeat of this issue:  https://github.com/audiokit/AudioKit/issues/511
If you're using beta, you have to be able to build yourself.
