### ISSUE TITLE
Analyser custom drawing

### ISSUE THREAD

**Issue by terenzeyuen** [audiokit/AudioKit#519]
Hi we are using the iOS microphone analysis example which works well but can't seem to be able to customise the drawing paths...especially the height (seems to be very short). We would like to achieve something like the below...possible?

![screen shot 2016-08-15 at 19 06 55](https://cloud.githubusercontent.com/assets/2553680/17674006/8ba0375e-631b-11e6-881c-ab771bf04ac5.png)

**Comment by aure** [comment]
Yes, its possible.  Not sure how drawing is related to AudioKit though.  You can scale at will.
