### ISSUE TITLE
AKNodeRecorder Pause

### ISSUE THREAD

**Issue by terenzeyuen** [audiokit/AudioKit#520]
Will we be able to pause a recording instead of stopping it entirely?

**Comment by aure** [comment]
Stop is effectively pause.  Reset clears the tape.

**Comment by terenzeyuen** [comment]
I see but at the moment when you call recorder.stop() it creates a file. So if the user record and pause a few times in a session, I assume it will create multiple files?

What we want is a recording session that can pause/record and playback in one file..if that make snese.

**Comment by aure** [comment]
it writes to the same file if you hit record again.  Try it.

**Comment by terenzeyuen** [comment]
Okay thanks. Maybe I am missing something, just tried the iOS recorder but it seems to be writing to different .caf files.

Here is the log output (I printed out the file path instead of pushing to play screen):

recording
writing ( file duration:  0.0928798185941043 seconds)
writing ( file duration:  0.185759637188209 seconds)
writing ( file duration:  0.278639455782313 seconds)
writing ( file duration:  0.371519274376417 seconds)
writing ( file duration:  0.464399092970522 seconds)
writing ( file duration:  0.557278911564626 seconds)
writing ( file duration:  0.65015873015873 seconds)
writing ( file duration:  0.743038548752834 seconds)
Recording Stopped.
/Library/Developer/CoreSimulator/Devices/ED9CB1E0-9E4A-4A82-B5E6-4B8BAE85651E/data/Containers/Data/Applica ... **65DB.caf**
recording
writing ( file duration:  0.0928798185941043 seconds)
writing ( file duration:  0.185759637188209 seconds)
writing ( file duration:  0.278639455782313 seconds)
writing ( file duration:  0.371519274376417 seconds)
writing ( file duration:  0.464399092970522 seconds)
writing ( file duration:  0.557278911564626 seconds)
writing ( file duration:  0.65015873015873 seconds)
writing ( file duration:  0.743038548752834 seconds)
Recording Stopped.
/Library/Developer/CoreSimulator/Devices/ED9CB1E0-9E4A-4A82-B5E6-4B8BAE85651E/data/Containers/Data/Applica ... **FA3D.caf**

**Comment by aure** [comment]
Are you defining the file that is being used to record to?  If you want to keep the file the same and add to it, you will need to do that.  That's they way it is done in the "Recording Nodes" playground.
