### ISSUE TITLE
Sequencer and Midi not stopping

### ISSUE THREAD

**Issue by ivanmkc** [audiokit/AudioKit#521]
I'm playing a bunch midi notes using the following code:

```swift
var sequenceLength : Float = 0
        for note in notes
        {
            sequence.tracks[0].add(noteNumber: note.midiValue,
                                   velocity: 100,
                                   position: AKDuration(beats: Double(note.onsetInBeats)),
                                   duration: AKDuration(beats: Double(note.durationInBeats)))
            sequenceLength = max(sequenceLength, note.onsetInBeats + note.durationInBeats)
        }
        
        sequence.setLength(AKDuration(beats: Double(sequenceLength)))
        sequence.disableLooping()
        sequence.setTempo(Double(tempo))
```

I then have a NSTimer (will switch to CVDisplayLink later) to poll the progress of the playing:

```swift
func updateBeat()
    {
        let currentBeat = Float(midiPlayer.sequence.currentPosition.beats)             
    }
```

The problem is that the current position keeps increasing past the sequence length that I set, indefinitely. I expect it to stop at the set sequence length. Note that I disabled looping.

Thanks in advance!

**Comment by aure** [comment]
Seems like you could just check if the playing time is greater than the length.

**Comment by ivanmkc** [comment]
I could but I would expect the sequencer to stop the midi player after it
reaches the end. Is it a bug or am I misunderstanding something?

Thanks

**Comment by aure** [comment]
I have made that change in the develop branch, but I am a bit worried it might have unexpected consequences for other people using currentPosition as some sort of total play time measurement.  It does make sense to keep currentPosition within the bounds of the sequence length, so hopefully this is an improvement.

**Comment by ivanmkc** [comment]
Thank you. I'll pull develop and test it out.
