### ISSUE TITLE
AKAudioFile AVAsset metadata is not accessible

### ISSUE THREAD

**Issue by lastcommit** [audiokit/AudioKit#522]
On the master and develop branches, when I try to access metadata of a file using the AKAudioFile, I do not get any results. If I load the same file using the AVAsset class, I can see it.

In a Playground, this code produces an empty array:
```
if let akAudioFile = try? AKAudioFile(readFileName: "02 Default.m4a",
                                      baseDir: .Resources) {
    let metadata = akAudioFile.avAsset.metadata
    print(metadata)
}
```
This code will produce an array of AVMetadataItems:
```
if let assetURL = NSBundle.mainBundle().URLForResource("02 Default", withExtension: "m4a") {
    let avAsset = AVURLAsset(URL: assetURL)
    let metadata = avAsset.metadata
    print(metadata)
}
```
The same thing happens if you use AVAsset's .commonMetadata, .availableMetadataFormats, etc.

It's not too different from the internalAVAsset method in the AKAudioFile class. Does anyone know why accessing the .avAsset on the AKAudioFile would make the metadata inaccessible?

**Comment by aure** [comment]
Just want to state that I've been on vacation without much time to check into this.  Perhaps @laurentVeliscek will get a chance the AKAudioFile is his baby!  If not, I should be back at it next week.

**Comment by aure** [comment]
I just had a look at this and I'm really surprised it doesn't work.  Will keep investigating, good catch!

**Comment by aure** [comment]
I think this is fixed in develop now.  Reopen if not.  Thanks!
