### ISSUE TITLE
AKOscillator max frequency

### ISSUE THREAD

**Issue by neesonqk** [audiokit/AudioKit#523]
It seems that AKOscillator only supports max 20000 frequency?

        let oscillator = AKOscillator()
        oscillator.amplitude = 0.3
        oscillator.frequency = 24000
        
        AudioKit.output = oscillator
        
        AudioKit.start()
        
        oscillator.start()

![24000](https://cloud.githubusercontent.com/assets/7279067/17761740/543b2058-653c-11e6-8781-340153b77ebe.PNG)

**Comment by aure** [comment]
By design.  If you want to try to go beyond that limit, change the DSP Kernel for the AKOscillator to not clamp the value:

    void setFrequency(float value) {
        frequency = clamp(value, (float)0, (float)20000);
        frequencyRamper.setImmediate(frequency);
    }
