### ISSUE TITLE
Play a tone with certain frequency periodically

### ISSUE THREAD

**Issue by neesonqk** [audiokit/AudioKit#524]
Hi, I'm quite a newbie to audio related stuffs, for further study, I'd like to play a tone with fixed frequency periodically, like every 1s play a tone with 400Hz, now I found AKSequencer, so I referred this  https://github.com/audiokit/AudioKit/issues/371.

Firstly, I created a AKOscillator

```
        let oscillator = AKOscillator()
        oscillator.frequency = 400;
```

Then I think I need to make a connection between this oscillator and a AKMIDI, so I did,

```
     let melody = AKMIDIInstrument() // Here, seems the method interface was changed, I want to pass oscillator to this instrument, like below
     let melody = AKMIDIInstrument(instrument: oscillator) //This is what I expect, but now I cannot do this
```

I'm stuck here, then I found this https://github.com/audiokit/AudioKit/blob/master/Examples/iOS/SequencerDemo/SequencerDemo/Conductor.swift

In above sample, a **AKFMOscillatorBank** was used, so I altered to **AKOscillatorBank**, but unlucky, I'm unable to set a 'Frequency' kind property for this AKOscillatorBank, so that I'm unable to specify a frequency...

My questions are:

1. Is the implementation way wrong?
2. if not wrong, then how to make this connection happens?

Thank you.

**Comment by aure** [comment]
I see that you joined the discussion forums.  That is the appropriate place for questions like this because it is not an issue with AudioKit, more about learning to use it.  For now let me just say that there is a difference between and AKxxxOscillator and an AKxxxOscillatorBank.

**Comment by neesonqk** [comment]
Yeah I saw you recommend people forums for discussion and study, will go there to seek a help, and thank you for making this great thing!
