### ISSUE TITLE
Cannot import AudioKit

### ISSUE THREAD

**Issue by jcpsimmons** [audiokit/AudioKit#525]
![screen shot 2016-08-18 at 5 07 59 pm](https://cloud.githubusercontent.com/assets/6600962/17794666/646dd2de-6566-11e6-9dee-ab533f3d9f4c.png)

Getting the following error in Xcode (no such module) when trying to use the AudioKit framework. I have tried the method described here: https://github.com/audiokit/AudioKit/issues/343 to no avail. I've also tried putting the framework in the same directory as the playground file path, but this also does not change anything.

**Comment by aure** [comment]
You can't use playgrounds with an external framework.  You open up the project file for the OS you're interested, make sure the OS is correct for the playground (only an issue in the develop branch), build and then you run the playground.   Have you followed this?  https://vimeo.com/157204402

**Comment by jcpsimmons** [comment]
Yikes -- pardon my ignorance, I didn't see this video on the site when installing.
