### ISSUE TITLE
Archive upload failed

### ISSUE THREAD

**Issue by Ferrick90** [audiokit/AudioKit#526]
Hi, I have edited the coding in AudioKit and try to build a new framework into my project. But I encountered some issue when i upload to AppStore.

My Step:
- Build Settings set Valid Architectures to arm64 armv7 armv7s x86_64 i386
- Use terminal to run the build_frameworks.sh inside the Frameworks folder
- Open AudioKit-iOS folder and copy AudioKit.framework to my project
- Set enable Bitcode true and add Run Script "$BUILT_PRODUCTS_DIR/$FRAMEWORKS_FOLDER_PATH/AudioKit.framework/fix-framework.sh" in my project
- Archive successful
- Archive fail to upload AppSotre

<img width="585" alt="screen shot 2016-08-19 at 4 58 42 pm" src="https://cloud.githubusercontent.com/assets/6068413/17805290/5a5d67d4-6631-11e6-8dfe-a589c07116df.png">

did I make any mistake?

Regards,
Ferrick

**Comment by aure** [comment]
Looks like its telling you that you have inconsistent value for enable_bitcode are there are other frameworks in your app?

**Comment by Ferrick90** [comment]
I fixed ady. Archive upload and uncheck the bitcode. Anyway, thanks
