### ISSUE TITLE
AKMIDI with MIDI via Bluetooth

### ISSUE THREAD

**Issue by mlostekk** [audiokit/AudioKit#530]
Hello,

is it possible to connect the AKMIDI interface to a bluetooth midi connection? If it is, do you have some advice or examples?

**Comment by aure** [comment]
I just got a bluetooth midi device, but I haven't tested it with AudioKit.  Does a bluetooth midi connection show up differently from regular ones?

**Comment by aure** [comment]
So, bluetooth MIDI works just fine with AKMIDI, but you have to be connected to it.  I don't have the boiler plate code for doing so, but all I had to do was to first use Garageband to connect to the Bluetooth MIDI.  Once it connected I could quit Garageband and use the Bluetooth MIDI to control my AudioKit synth.  Just make sure openInput() with nothing in the argument list, ie. don't specify "Network Session 1" or anything.
