### ISSUE TITLE
AKSequence setLength for tracks attributes sets all track lengths not the selected track

### ISSUE THREAD

**Issue by JoshuaBThompson** [audiokit/AudioKit#533]
seq.tracks[0].setLength(AKDuration(seconds: 4.0))
seq.tracks[1].setLength(AKDuration(seconds: 8.0))

the notes in the track 0 will play for 4.0 sec and then wait another 4 sec before starting over.
Shouldn't the notes in track 0 start replaying as soon as 4.0 seconds has elapsed? It seems like the track 1 set length overrides the track 0 setLength.

**Comment by aure** [comment]
I don't think it is intended to work the way you are expecting.  its kind of like a multitrack recorder.  if you don't have anything from 4-8 but something is playing there, it will be silent.

**Comment by aure** [comment]
Not that I don't think your way would be better.

**Comment by JoshuaBThompson** [comment]
Ah, ok. 
I see, thank you for that clarification. Is there a good way to do what I'm trying to do in AudioKit besides making separate AKSequence instances (which I'm doing now, but since I'm making many (over 24) it's kind of overkill).

**Comment by aure** [comment]
So, yeah, I am not sure that length is telling the sequencer anything beyond "there could be notes in this range"much like DAW would have for a piano roll.  So, I am not sure this is an issue as much of a limitation.  Instead, we have to roll our own looping logic.

**Comment by JoshuaBThompson** [comment]
I guess I could append the tracks that are meant to loop around quicker with copies of their notes to make it seem like they are looping...

**Comment by JoshuaBThompson** [comment]
what do you mean by 'roll our own looping logic' ?

**Comment by aure** [comment]
Yep, that's what we did in a recent project.  In fact we never looped, just constantly added the next sequences to a queue before they were needed.

**Comment by JoshuaBThompson** [comment]
ah, ok.

**Comment by aure** [comment]
Does this change the status of the other issue?  Could it all be related to the same thing?

**Comment by JoshuaBThompson** [comment]
Looks like they are related.
But, I'm a little confused about your method. Is there an example of what you did in the other project you mentioned? Constantly adding the next sequence to a queue before they were needed?

**Comment by JoshuaBThompson** [comment]
Also wouldn't that create problems for AKSequence tracks? I mean, if I understand you correctly (which I probably don't ...) then you are simply doing a sequence.tracks[0].addNote(.....) every time you want the track to continue. Won't this result in the track being filled up 'infinitely' as you keep on playing the sequence...?

**Comment by aure** [comment]
It's a tiny amount of data to add a note every couple of seconds.  We looped once a day I think and started fresh.  I don't have an example, this was for a client. :-/

**Comment by JoshuaBThompson** [comment]
I guess my scenario would be:
track 0:
note 1 (0 sec)....note 2 (1 sec)....note 3 (2 sec) note 4 (3 sec)....(wait 1 sec then start back at note 1)

track 1:
note 1 (0 sec).... note2 (2 sec) ...note 3 (4 sec) ... note 4 (6 sec) (wait 1 sec then start back at note 1)

So using your suggestion for track 0
track[0].addNote(note 1 at 0 sec)
track[0].addNote(note 2 at 1 sec)
track[0].addNote(note 3 at 2 sec)
track[0].addNote(note 4 at 3 sec)
//now want to make it seem like track 0 repeats / loop restarts
track[0].addNote(note 1 at 4 sec)
track[0].addNote(note 2 at 5 sec)
track[0].addNote(note 3 at 6 sec)
track[0].addNote(note 4 at 7 sec)
....etc

Is this what you mean?

**Comment by ewalt** [comment]
What is this

**Comment by JoshuaBThompson** [comment]
Hi Aure,
Sorry, what I was trying to demonstrate was that I would be continuously adding notes to a track and incrementing the position of the note to mimic a multitrack. I got it working and so far so good.

**Comment by aure** [comment]
Cool.  Well, if you feel like things work, maybe close the issues.  Perhaps its instead a documentation issue and we can add docs to the web site.  (Something I've wanted to do for some time).
