### ISSUE TITLE
Remove AKSettings.disableAVAudioSessionCategoryManagement parameter

### ISSUE THREAD

**Issue by andreyz** [audiokit/AudioKit#538]
There's a following code in `AKSettings.setSessionCategory` static method:
``` swift
    if AKSettings.disableAVAudioSessionCategoryManagement == false {
            
            // print( "ask for category: \(category.rawValue)")
            // Category
            if options != nil {
                do {
                    try session.setCategory(category.rawValue, withOptions: options!)
                } catch let error as NSError {
                    print ("AKAsettings Error: Cannot set AVAudioSession Category to \(String(category)) with options: \(String(options!))")
                    print ("AKAsettings Error: \(error))")
                    throw error
                }
            }
        } else {
            
            do {
                try session.setCategory(category.rawValue)
            } catch let error as NSError {
                print ("AKAsettings Error: Cannot set AVAudioSession Category to \(String(category))")
                print ("AKAsettings Error: \(error))")
                throw error
            }
        }
```
It seems it just does basically the same category setting, only in first case using `options` parameter and in the else case without. Was there any intent behind that code?

I'd really like to be able to manage AVAudioSession myself and `AKSettings.disableAVAudioSessionCategoryManagement` parameter seems misleading, since it's really does nothing useful.

It's possibly can be reimplemented, but that then requires thinking through the design where AudioKit can't rely on full control of AVAudioSession.

**Comment by aure** [comment]
Its open source, you could of course just comment out the stuff you don't want.  I'm not really sure what I should do about it.  Its on our list to revamp the category management stuff already.  If you have any suggestions, we're open.

**Comment by andreyz** [comment]
I was asking since it wasn't clear if that code was intentional and I didn't follow the purpose or it's just a remaining of old functionality that became irrelevant. So, I could guess and make conclusions or ask a main contributor, which I did. 

Sorry for taking your time.

**Comment by aure** [comment]
I hope I didn't seem dismissive of your issue.  We will definitely look at this further. I think if you did a blame on that line it wasn't me so maybe I should have waited for someone else to respond.
