### ISSUE TITLE
AVSpeech​Synthesizer

### ISSUE THREAD

**Issue by alexbilbie** [audiokit/AudioKit#540]
I'm wondering if with this project it's possible to sample AVSpeech​Synthesizer utterance?

I'm intending to create a wave form based on the live output.

Thank you

**Comment by aure** [comment]
Nope, not as far as I know anyway.  Its a bummer how closed off AVSpeechSynthesizer is.  It should be a node but it only outputs to the speaker.

**Comment by alexbilbie** [comment]
Thank you for your swift answer!

**Comment by aure** [comment]
Sorry it wasn't more positive!
