### ISSUE TITLE
Set AKMicrophone to use non-default input

### ISSUE THREAD

**Issue by thislooksfun** [audiokit/AudioKit#546]
Hello! I was wondering if it's possible to set an instance of `AKMicrophone` to use a different input on macOS (change to a usb microphone / digital audiobus / etc.). I found the method `AudioKit.setInputDevice(AudioKit.AKDevice)`, but that changes the entire system default input, which not only changes every instance of `AKMicrophone`, it also changes the input for every other app using the default microphone.

`EZMicrophone` has the ability to use a specific input device, but I can't figure out how to pipe its output into the rest of the system.

I would appreciate any help you can give on getting this to work.

Thanks,
-tlf

**Comment by aure** [comment]
Hi, this sounds like an important issue, but I don't have the solution for it yet, so I'll leave it open until we can look at it further (probably after Xcode8 conversion is done).

**Comment by aure** [comment]
I'm hoping this solves your issue.  I could only test with two devices though, so maybe it still needs work. I'll close this issue, but feel free to reopen it if necessary.

**Comment by thislooksfun** [comment]
I'm currently unable to test it, but I will get back to you as soon as I find out. Thanks for the update!

**Comment by thislooksfun** [comment]
Well, the selection of the microphone appears to be working, however now I'm getting a new error, as documented in issue #631

**Comment by thislooksfun** [comment]
Forgot to include this in the previous comment:

Is there some way to set the output device as well? I see `AudioKit.setOutputDevice(_:)`, but that has the same problem as `AudioKit.setInputDevice(_:)` does. If I'm missing some way to do this, I apologize, but that would be huge boost to my workflow, plus would be very useful for many audio routing applications (in both relevant senses of the word).

If you want, I can make this its own ticket.

Thanks again,
-tlf

**Comment by aure** [comment]
I can probably doing something similar for output, but yeah, make a new issue please.
