### ISSUE TITLE
AK3DPanner not working?

### ISSUE THREAD

**Issue by GreatApe** [audiokit/AudioKit#551]
I posted a question on StackOverflow but it seems that this is a better place for it. Basically AK3DPanner doesn't seem to work a lot of the time. Since then I have been able to make it work together with AKAudioPlayer, but it refuses to work with AKDrip for example.

http://stackoverflow.com/questions/39469575/audiokit-ak3dpanner-not-working

**Comment by aure** [comment]
Hmm, what if you send the drip through an AKMixer first?  Thanks for noticing this.

**Comment by GreatApe** [comment]
Yes, that actually works, thanks for the painless workaround!

It seems like the panner fails for certain sound sources and works for others. I can hook it up to a mandolin, but not to a mandolin-delay-reverb chain for example. Here too it starts working again if I interject a mixer.

Has this got to do with mismatches in formats and/or channel counts?

**Comment by GreatApe** [comment]
By the way is it normal that the panner node has 32 seemingly empty inputs, and one non-empty?

**Comment by aure** [comment]
I guess it must have to do with a audio file spec mismatch, but we always use the standard definition so I am not sure what's causing the issue.  I don't know how you counted the empty input nodes for the panner.  Are you talking 3D or regular panner?

**Comment by GreatApe** [comment]
I'm not sure exactly what they are, since I'm new to AudioKit and audio in general, but the engine says that `node 0x7f97d943c910 {'aumx' '3dem' 'appl'}, 'U'` has 33 inputs, of which 32 look like this:

`(bus0) <- (bus0) 0x0, {}, [ 1 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]
`

I'm working with the 3d panner. Now that it works it has another issue, unless the listener is very close, a meter or so, the sound only reaches one ear at a time, so the 3d effect is very crude.

**Comment by aure** [comment]
Well, there's very little I can do about that.  This is Apple's 3D engine, so however it works I don't have access at that deep of a level.

**Comment by aure** [comment]
I'll close this issue for now, but you may reopen it as necessary.
