### ISSUE TITLE
Cocoapods Swift3 branch empty folder

### ISSUE THREAD

**Issue by eh1255** [audiokit/AudioKit#554]
I've been having problems migrating to Swift 3, so I tried creating a new project in an attempt to isolate the problem. I eventually narrowed it down to AudioKit and found out that installing via cocoapods on the Swift3 branch results in an empty in Pods (see screenshot). I have cocoapods 1.0.1 installed. The issue is reproducible by creating a new project with the podfile shown. I tried specifying the most recent commit, but that had the same results. I suspected something was wrong with cocoapods, but it's working with all the other pods in my projects, so I think it might be related to AudioKit itself.

Thanks in advance!

<img width="851" alt="empty" src="https://cloud.githubusercontent.com/assets/17945242/18624432/a9b3b96e-7e82-11e6-975e-937c3931874c.png">

**Comment by aure** [comment]
I suspect this will work itself out when we release the Swift3 version and push the podspec up to cocoapods.   We're just about ready to do so.

**Comment by eh1255** [comment]
Alright, I'll just sit tight for a bit then. Thanks for the quick response.

**Comment by jasonmerchant** [comment]
Looking forward to this update as well. (Was about to switch my Mac app to use a different audio framework, but will wait until tomorrow) Thanks so much for your hard work aure! :)

**Comment by aure** [comment]
AudioKit v3.4 was released just now and should take care of these problems, and I'm sure it will not be perfect so a 3.4.1 is probably not too far off.

**Comment by eh1255** [comment]
I haven't finished migrating my own code yet, so I can't test, but it builds properly now. Thank you.
