### ISSUE TITLE
fix-frameworks.sh un-signs already signed frameworks when using Carthage

### ISSUE THREAD

**Issue by larsacus** [audiokit/AudioKit#570]
When using Carthage for dependency management, the frameworks must be copied into the target since they are not a part of the build products of the project. In Xcode 8, it will also sign these binaries by default at copy time. The recommended method to execute the fix-frameworks script is to run it _after_ the "embed frameworks" phase (since the fix-frameworks script actually expects to be executed in the `$BUILT_PRODUCTS_DIR/$FRAMEWORKS_FOLDER_PATH` path).

![screen shot 2016-10-04 at 10 20 55](https://cloud.githubusercontent.com/assets/590216/19080301/41cb9290-8a1c-11e6-9d9f-25313c5c88a8.png)

When the fix-framework script executes, it modifies the already-signed binary, which simply un-signs it. This causes iTunes validation to fail just as in #368.

In order to work around this, I have had to copy and modify the fix-frameworks script to execute on the unsigned framework in `Carthage/Build/` before it is copied over to the target during archive:

![screen shot 2016-10-04 at 10 22 41](https://cloud.githubusercontent.com/assets/590216/19080408/9f350b00-8a1c-11e6-9a8d-00d3fdf66c26.png)

Ordering in relation to Carthage copy-frameworks:

![screen shot 2016-10-04 at 10 48 33](https://cloud.githubusercontent.com/assets/590216/19081512/2912d6d8-8a20-11e6-942e-c73126e09c22.png)

``` bash
#
# Process the framework to copy symbol maps to the archive, remove simulator slices and remove extra data from the framework itself
#

cd "Carthage/Build/iOS"

framework=./AudioKit.framework
binary="$framework/AudioKit"

if [ "$ACTION" == "install" ]; then
find "$framework/BCSymbolMaps" -name \*.bcsymbolmap -type f -exec mv {} "$CONFIGURATION_BUILD_DIR" \;
lipo -remove i386 -output "$binary" "$binary"
lipo -remove x86_64 -output "$binary" "$binary"
plutil -remove CFBundleSupportedPlatforms "$framework/Info.plist"
rm -f "$framework/fix-framework.sh"
fi

rm -rf "$framework/BCSymbolMaps"
```

This obviously breaks the nice containment you have of this script inside of your framework and requires someone to manually update this script whenever it changes, but this does do everything required for iTunes Connect and bitcode when using the Carthage workflow with frameworks that are not part of the project build products.

**Comment by megastep** [comment]
Thanks for your insights. I assume that this signing of frameworks is new in Xcode 8?

**Comment by larsacus** [comment]
I'm actually not positive as I've already deleted Xcode 7, but this is the first time I have run into it.

**Comment by megastep** [comment]
I just committed some fixes to the script that builds the framework, maybe you can check it out and let me know if this helps. Maybe Xcode 8 is smarter at handling simulator slices and this could effectively obsolete the `fix-framework.sh` script.

I would check this out myself however I don't currently have an AudioKit App Store app ready for submission to try this out. :)

**Comment by larsacus** [comment]
I just posted this in #567 since they're similar but different, but I don't use `build-frameworks.sh`. Carthage handles all of our dependency building.

**Comment by megastep** [comment]
@larsacus  Well Carthage should be fetching the zip with compiled frameworks we have from the current version which obviously has some problems. Can you try to build the framework manually from our `devel` branch and see if it works better before we make a new release?

**Comment by larsacus** [comment]
Oh so you're saying to actually checkout AudioKit develop in another location and build manually using your script. That even if I were to specify develop and use `carthage update --no-use-binaries`, because your build-frameworks script isn't being used, none of what you're doing will be present.

Yeah I'll have to prioritize this and try it out later as it takes about 30 minutes to re-build all of our carthage dependencies.

**Comment by larsacus** [comment]
I just rebuilt AudioKit (using carthage directly, not your script) and am now running into compilation issues when importing AudioKit in source files stating that AudioKit is requires to be linked with iOS 10+:

```
module file's minimum deployment target is ios10.0 v10.0: /<project_dir>/Carthage/Build/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/arm64.swiftmodule
```

My application still supports iOS 9. I'm going to try with your `build-frameworks.sh` script next to see if something is somehow different with the script than building through Xcode via carthage.

**Comment by megastep** [comment]
@larsacus Yeah that's to be expected, we explicitly override the required minimum version in the script to build the framework properly. The reason the deployment target is set to iOS 10 in the main configuration is to allow the playgrounds to work in Xcode 8 - it is a requirement for that.

So as a trade-off we do it this way and allow the binary frameworks we provide to be correctly built for iOS 9.

**Comment by larsacus** [comment]
This is actually really difficult for me to verify since I have essentially commit changes that I don't know if they will work yet into our production deployment workflow. Especially since you cannot delete builds from TestFlight.

From going through submission to iTC with a known failing parameter in another framework (to prevent actual submission), this issue _appears_ to be resolved. I cannot validate that the validation did not also prematurely terminate when it found other issues, however.

**Comment by megastep** [comment]
@larsacus  Are you able to just use the validate button in Xcode instead of fully submitting the build to see if these errors pop up though?

**Comment by aure** [comment]
What's the status of this issue?

**Comment by aure** [comment]
Closing this issue until further information, feel free to reopen.
