### ISSUE TITLE
Objective C error : Unknown type name 'AKNodeRecorder'

### ISSUE THREAD

**Issue by uc3po** [audiokit/AudioKit#573]
Hi all, 
i've developing an audio app with Objective C. I integrated successfully with AudioKit and played lats of file via AudioKit using mixer etc but i need  recording input from mic while players is running. 
When try to use AKNodeRecorder got this message: Unknown type name 'AKNodeRecorder'.
Any idea of this situation?

**Comment by aure** [comment]
Yeah, its a pretty simple fix.  Its updated on the develop branch, or you can make the change yourself too:  https://github.com/audiokit/AudioKit/commit/c0ba34789eb49fda642f82eb80e0c40bd99e35d3
