### ISSUE TITLE
Crash when plugging in/taking out headphones with metronome

### ISSUE THREAD

**Issue by junhohong** [audiokit/AudioKit#575]
Hi, I'm currently working with the metronome example from here: http://audiokit.io/playgrounds/Basics/Metronome/

The only different thing I did was making Audiokit.output a mixer with the generator connected, because i want to have multiple sounds at once. Whenever I plug in my headphones, I get this error or something similar: 

```
Could not find function called '\255\276\374m\216\377ݺ'.
\255\276\374m\216\377ݺ returned an error.
```

The error is not consistent - the function name is almost always different. 
When I take out the headphones, I usually get this error:

```
Could not find function called ''.
 returned an error. 
```
The generator has not yet been started at this point. 

I'm so confused... What is wrong here?

**Comment by junhohong** [comment]
Another related(?) issue, all of my output sounds stop once I plug in headphones even without the metronome. I've read that this is because AudioKit restarts. Is there a way around this?

**Comment by aure** [comment]
I thought I had responded to this but maybe not.  Do you have this set up as an iOS playground?  The playground is running a simulator that inherits the sound set up from the host mac.  It doesn't surprise me at all that it would cause problems to change that system (by pugging or unplugging the headphones) after the simulator was launched.

**Comment by junhohong** [comment]
It's not set up as a playground. This is within the context of a full sized project.

**Comment by aure** [comment]
Are you plugging and unplugging headphones into the computer or into the iOS device?

**Comment by junhohong** [comment]
into the iOS device.

**Comment by junhohong** [comment]
I can share the project with you or show you the error in action if you would like.

**Comment by aure** [comment]
I guess you'll need to respond to route changes.  

https://developer.apple.com/library/content/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/HandlingAudioHardwareRouteChanges/HandlingAudioHardwareRouteChanges.html  

It would be good if AudioKit handled these events gracefully but we haven't standardized a way of handling them.

**Comment by aure** [comment]
yes, please share the project

**Comment by junhohong** [comment]
https://github.com/junhohong/PracticeTools
Here is the project. The code in question is located in the viewDidAppear method of ViewController.

**Comment by junhohong** [comment]
Commenting out 
`mixer.connect(generator)`
will get rid of the error.

**Comment by aure** [comment]
Cool, won't have a chance to check this out tonight, but tomorrow.

**Comment by junhohong** [comment]
Ok! Thanks so much :)

**Comment by junhohong** [comment]
I fixed it! Here's how I did it:
First, I set the observer from the link you showed me
```
NotificationCenter.default.addObserver(
            self,
            selector: #selector(self.audioRouteChangeListener(notification:)),
            name: NSNotification.Name.AVAudioSessionRouteChange,
            object: nil)
```

Then in the function, I stopped AudioKit manually and called my own reset function.
```
func audioRouteChangeListener(notification:NSNotification) {
        let audioRouteChangeReason = notification.userInfo![AVAudioSessionRouteChangeReasonKey] as! UInt
        
        switch audioRouteChangeReason {
        case AVAudioSessionRouteChangeReason.newDeviceAvailable.rawValue:
            AudioKit.stop()
            print("headphone plugged in")
            reset()
        case AVAudioSessionRouteChangeReason.oldDeviceUnavailable.rawValue:
            AudioKit.stop()
            print("headphone pulled out")
            reset()
        default:
            break
        }
    }
```
In the reset function, what I did was completely reset AudioKit.output. I rebuilt all the instruments (not sure if this was necessary) and mixed all of them and set them as the output. 

What I found was that you cannot attempt to start AudioKit again without resetting the output. Should I try to fix this with a pull request?

**Comment by aure** [comment]
This is great!  If we can put something in AudioKit that sets this up so the users only has to worry about the reset function, that would be great.  Otherwise, we just need to provide this as a tutorial.

**Comment by aure** [comment]
Also, If you'd like to be part of our Slack group, just ask and I'll send you invite.

**Comment by junhohong** [comment]
Sure, I would love to join! I'll send you an email.

**Comment by calflegal** [comment]
This is such great news! I had tweeted about this issue! Thank you all so much, great library!
