### ISSUE TITLE
Metronome custom audio

### ISSUE THREAD

**Issue by junhohong** [audiokit/AudioKit#577]
Is there a way to incorporate custom audio (.wav) clicks with the metronome?

**Comment by aure** [comment]
Sure, take a look at the "Using Functions 2" playground which does a lot of interesting things with a metronome pulse.

**Comment by aure** [comment]
Oops, I didn't read carefully enough.  If you want wav files I'd recommend making a sequence like in the Sequencer playground.

**Comment by junhohong** [comment]
Is there a way to incorporate AKOperation method triggeredWithEnvelope with the sequencer or sampler? I want to be able to use the frequency I set on the metronome to play a wav file.

**Comment by peterdouglas** [comment]
@junhohong did you end up resolving this issue? As I am currently trying to get a custom metronome sound triggered without any success so far. I have been through all of the docs, and have looked at different generators - and at the moment I think the only way is to use sporth code.

Thanks.
