### ISSUE TITLE
Overwrite AKAudioFile

### ISSUE THREAD

**Issue by ppamorim** [audiokit/AudioKit#578]
Hi.

I'm developing a application that allow the user to record and it does edits like overwrite and insert. The first feature that I'm implementing is overwrite. I did this code that implements the logic to do this:

```
do {

  AudioKit.output = AKMixer()
  AudioKit.start()

  let mixer = try AKAudioFile(
    forWriting: masterFileURL,
    settings: setMasterAudioSettings,
    commonFormat: AVAudioCommonFormat.pcmFormatFloat32,
    interleaved: true)

  try layers?.forEach { layer in
    let layerFile = try AKAudioFile(forReading: documentDirectory.appendingPathComponent(layer.fileName))

    //The first layer always start from 0.0.
    if layer.position > 0 {
      mixer.framePosition = Int64(layer.startMilliseconds * 1000.0)
    }
    try mixer.write(from: layerFile.pcmBuffer) //Crash
  }

  mixer.exportAsynchronously(name: "testing.wav", baseDir: .documents, exportFormat: .wav) { exportedFile, error in
    print(error)
  }

} catch let error {
  print(error)
}
```

I saw this code and I think it's useful: http://audiokit.io/playgrounds/Playback/Editing%20Audio%20Files/

For the writing of the first layer, everything is ok. But after that I need to move the framePosition (to overwrite) to the start of the layer 1. The app crashes and notify: `Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -66568'`.

Am I doing it correct?

I can't merge it during the recording. It needs to record these layers separately. I know that this library doesn't have a perfect offline render. I know that I can write a code that can do this but I don't know how. Can you help me?

Thank you.

**Comment by aure** [comment]
Yeah, I think it's great that you requested to be on our Slack because I think Laurent will be most helpful if he's available.

**Comment by ppamorim** [comment]
If I got success, I will create a sample implementing this feature. :)

**Comment by ppamorim** [comment]
I tried to use `try mixer.appendedBy(file: layerFile)` and I received this error: 

    Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -50'

**Comment by laurentVeliscek** [comment]
Hi Pedro,

You may try to create different instances of AKaudioFile for reading and writing, even if they target the same "physical file", depending on your purpose.

Playing with frame position can leads to crash in some cases. AKaudioFile inherits from avaudiofile, and I noticed that it behaves differently depending on how you instanciate it (for reading vs for writing).

Your sample code is a little bit short for more investigation...

:-/

I hope this will help.

Best :-)

Laurent.

Envoyé de mon iPhone

**Comment by ppamorim** [comment]
@laurentVeliscek I'm creating a new instance of `AKAudioFile` for every layer (as reading) and for the mixer (as writing). I moved the `framePosition` of the mixer because I need to move the flag that represents the position where I need to write the file, based on the layer start position.

**Comment by addy28** [comment]
how can i install audio kit v2 on my mac ?? plus guide me

**Comment by aure** [comment]
What's the status of this issue?

**Comment by aure** [comment]
Last new information this issue was over a month ago so I will close the issue, but if you need to reopen it, please do.

**Comment by Joni-Aaltonen** [comment]
@ppamorim I'm actually playing with something similar, and getting same errors. How did you get around the problem?
