### ISSUE TITLE
sample frame calculation error in getWavInfo/FileRead.cpp

### ISSUE THREAD

**Issue by ThomasRehaag** [audiokit/AudioKit#579]
actually it's:
  fileSize_ = bytes / temp / channels_;  // sample frames
  fileSize_ *= 8;  // sample frames
for e.g. 1 Channel, 44 Samples, 16 Bit you'll get fileSize = 40 here.

Just replace those lines with:
fileSize_ = bytes / (temp/8) / channels_;

**Comment by aure** [comment]
So this code is part of the STK library.  I wonder if you shouldn't bubble up your findings to them because even if I make this change, it could get bashed if I later update from their code base

**Comment by ThomasRehaag** [comment]
sorry, seems I was too hectic. Didn't see that I was in the wrong place

Am 12.10.2016 um 19:29 schrieb Aurelius Prochazka:
