### ISSUE TITLE
Missing AKVibrato.h

### ISSUE THREAD

**Issue by txaiwieser** [audiokit/AudioKit#583]
Am I missing something? I can't find the AKVIbrato on the framework, but a search on the cocoapods docs is showing the class exists.

Awesome work on the lib by the way! Thanks!

**Comment by aure** [comment]
What version of AudioKit are you looking at?

**Comment by txaiwieser** [comment]
I have in my project the last version (3.4.2) and was searching on the internet for the Vibrato and found the docs the AKVibrato, but can't find locally

**Comment by aure** [comment]
AKVibrato was in AudioKit 2 only.

**Comment by txaiwieser** [comment]
Do you guys have plans to bring it to the version 3?

**Comment by aure** [comment]
We have a pitch shift operation that could be used to do it.  I supposed that could be wrapped up into an AKVibrato but its pretty easy to use pitchShift with a sine wave.
