### ISSUE TITLE
Fatal Error when running Hello World example

### ISSUE THREAD

**Issue by jivers** [audiokit/AudioKit#585]
Hello! AudioKit is so wonderful and I'm excited to dive in deeper. What a great project!

Originally I was having issues locating the AudioKit framework. I would follow steps provided in video but it wouldn't be found. That said, I started manually copying framework to the project folder and this seemed to solve the issue. Build succeeds. 

However, when I run the Hello World example (simple osc) in simulator, I get this message:
![image](https://cloud.githubusercontent.com/assets/6712221/19623749/3c9820f2-990a-11e6-837a-28999eb37e84.png)

That said, all of my playgrounds and projects are working from the AudioKit examples. I've searched around a bunch and tried a few different things...any advice would be much appreciated!

**Comment by jivers** [comment]
Hm I think Google Group is a better place for this question because it's not really an issue.

**Comment by aure** [comment]
I think you're missing the step of including the framework in the Xcode build process.  But yeah, the Google group might have got you a quicker answer.

**Comment by jivers** [comment]
Build with framework is successful - I'll move to google group. Thanks -

**Comment by aure** [comment]
I think the build could be successful even if it isn't linked properly.  But then you get the fatal error later when it is not found.

**Comment by aure** [comment]
Happy to do a screenshare with you to track down the issue.
