### ISSUE TITLE
Audio Player Output Doesn't Go To Speaker

### ISSUE THREAD

**Issue by qiangyu** [audiokit/AudioKit#586]
Hello,
I installed AudioKit sample app Recorder(http://audiokit.io/examples/SequencerDemo/) into my iPhone, and noticed when playing audio, the output went to the ear speaker not the speakers at the bottom of my phone. Thus, it is barely audible.

I tried adding these two lines into the code but they didn't help

      try AKSettings.setSession(category: .playback)
      try AKSettings.session.overrideOutputAudioPort(AVAudioSessionPortOverride.speaker)

Any ideas what may cause the problem? Thanks a lot!

Qiang

**Comment by treblenow** [comment]
Try : `AKSettings.defaultToSpeaker = true`

**Comment by junhohong** [comment]
Try: `AKSettings.defaultToSpeaker = true`

**Comment by qiangyu** [comment]
Thanks guys,
I tried "AKSettings.defaultToSpeaker = true" but it didn't help.

**Comment by junhohong** [comment]
Try this then. Comment out defaultToSpeaker. `try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, with:AVAudioSessionCategoryOptions.defaultToSpeaker)`

**Comment by qiangyu** [comment]
haha. Thanks! That works 👍

**Comment by junhohong** [comment]
Yay! Use .mixWithOthers for simulators though, otherwise you won't hear anything.

**Comment by qiangyu** [comment]
Got it. Thanks for the hint!

**Comment by aure** [comment]
I am going to call this issue resolved, re-open if necessary.  Thanks Jun Ho!

**Comment by rickyjwhong** [comment]
hey there, 

great library first of all. using the example project for recorderdemo for iOS, and having trouble with the output being the speaker. I tried using `try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, with:AVAudioSessionCategoryOptions.defaultToSpeaker)` instead of the default but it still outputs it with really low volume. any idea?

**Comment by petkrein** [comment]
Hi,

having the same problem.

tried:
`
try AKSettings.setSession(category: .playAndRecord, with: AVAudioSessionCategoryOptions.defaultToSpeaker)`

and...

`try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, with:AVAudioSessionCategoryOptions.mixWithOthers)`

**Audio Player Output Doesn't Go To Speaker**

**Comment by LeeMatthewHiggins** [comment]
This should be re-opened. Its not working.

**Comment by aure** [comment]
I don't reopen issues that are several releases of AudioKit old, but you can make a new issue.
