### ISSUE TITLE
recognize metronome trigger

### ISSUE THREAD

**Issue by junhohong** [audiokit/AudioKit#587]
Hi Aure,

```
generator = AKOperationGenerator() { parameters in
            let beep = AKOperation.sineWave(frequency: 880,amplitude:parameters[1])
            let metronome = AKOperation.metronome(frequency: parameters[0] / 60)
            let beeps = beep.triggeredWithEnvelope(
                trigger: metronome,
                attack: 0.02, hold: 0, release: 0.1)
            return beeps
        }
```

In this example, is there a way to recognize when a beep has been triggered? I basically want to keep a count of how many times a beep has played.

**Comment by aure** [comment]
What you wan to do is definitely possible, depending on how deep you'd be willing to code.  I am currently preparing for a talk on Friday, but I can switch to this once that is over.  I hope that is not too much of an inconvenience.

**Comment by junhohong** [comment]
Awesome. That won't be a problem at all. Would this require modifying the AudioKit source code?

**Comment by aure** [comment]
We can do it directly with Sporth, but if we want it to look like an operation, it will mean editing AudioKit source code.

**Comment by junhohong** [comment]
Ooo ok. I will learn about Sporth so I'm prepared to understand what we're working with. I would prefer not to edit the source code because I'm still reliant on using pods. I should learn how to work without it..

**Comment by aure** [comment]
You actually won't have to edit AudioKit source, just extend it locally. When I'm back we'll dive in.

**Comment by junhohong** [comment]
Sporth is a bit intimidating but I think I get the gist of it. Do I create my own sporth patch and use that to create a generator?

**Comment by junhohong** [comment]
This might be a dumb question, but is there a way to use my own version of AKOperationGenerator to extend the trigger function to fit my needs?

**Comment by junhohong** [comment]
Ok that didn't work, i guess the trigger function isn't what actually triggers the metronome sound.

**Comment by aure** [comment]
I am back from my conference now so I will start looking at this after releasing an Xcode 8.1 compatible precompiled framework for AudioKit/

**Comment by junhohong** [comment]
Ok! Take your time. Thank you 🙂

**Comment by junhohong** [comment]
Hey Aure, do you think you could give an estimate on how long this would take? I could start looking into alternative methods for the metronome.

**Comment by aure** [comment]
Let's do it today.  I'll try to see if I can do it within a playground to send you.  Basically just a metronome with a counter that increment each time.

**Comment by junhohong** [comment]
Awesome! Really appreciate it. 🙂

**Comment by aure** [comment]
Here's a playground that "works".  The UI is nothing special though, every time you change the slider, you'll see the counter printed to the console.  I'll wrap this up into AudioKit and make a nicer playground but I wanted to get this to you asap.  If it works, you could close the issue, knowing that I'll get this in develop today.

```
import AudioKit

extension AKOperation {
    
    public func count(max: AKParameter = 1000000) -> AKOperation {
        return AKOperation(module: "count", inputs: self.toMono(), max, 0)
    }
}

extension AKOperation {

    public func save(parameterIndex: AKParameter) -> AKOperation {
        return AKOperation(module: "dup \(parameterIndex) pset", inputs: self.toMono())
    }
}



var currentFrequency = 60.0
var count = 0.0

let generator = AKOperationGenerator() { parameters in
    let beep = AKOperation.sineWave(frequency: 480)

    let metronome = AKOperation.metronome(frequency: parameters[0] / 60)
        
    let counter = metronome.count().save(parameterIndex: 1)
    
    let beeps = beep.triggeredWithEnvelope(
        trigger: metronome,
        attack: 0.01, hold: 0, release: 0.05)
    return beeps + (counter * 0)
}

generator.parameters = [currentFrequency, count]

AudioKit.output = generator
AudioKit.start()
generator.start()


class PlaygroundView: AKPlaygroundView {

    override func setup() {
        addTitle("Metronome")

        addSubview(AKPropertySlider(
            property: "Frequency",
            format: "%0.2f BPM",
            value: 60, minimum: 40, maximum: 240,
            color: AKColor.green
        ) { frequency in
            generator.parameters[0] = frequency
            Swift.print(generator.parameters[1])
        })
    }
}

import PlaygroundSupport

PlaygroundPage.current.needsIndefiniteExecution = true
PlaygroundPage.current.liveView = PlaygroundView()
```

**Comment by junhohong** [comment]
I haven't had a chance to test this yet but if I'm understanding this correctly, the counter is printed every time the frequency changes through the slider. Can I do something like this then?
```
var count = 0.0{
    willSet(newValue){
        print(newValue)
    }
}
```

**Comment by junhohong** [comment]
It's hard to see where generator.parameters[1] is modified, but I'd want it to print when that happens.

**Comment by junhohong** [comment]
Let me get on a computer and test this out.

**Comment by aure** [comment]
also I'm on slack...
