### ISSUE TITLE
Detect when a Midi device is connected

### ISSUE THREAD

**Issue by ivanmkc** [audiokit/AudioKit#590]
Hi,

I want to detect when a user connected their Midi device, either through USB or Bluetooth.

Is there a notification or delegate I can subscribe to in order to do this?

Thanks!

Btw, AudioKit is amazing

**Comment by aure** [comment]
Not currently, but its a good idea that I think we should try to add.

**Comment by aure** [comment]
There doesn't seem to be any distinction with USB or Bluetooth, this is just the general MIDI setup changing, so hopefully it is inclusive.

**Comment by ivanmkc** [comment]
Is there now a method to detect the MIDI setup changing then? That would
serve nicely.

**Comment by aure** [comment]
Yes I just added in that commit you see above.  In your MIDI listener, implement receivedMIDISetupChange()

**Comment by ivanmkc** [comment]
Thanks, I'll let you know how it is.
