### ISSUE TITLE
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1: 

### ISSUE THREAD

**Issue by Tr736** [audiokit/AudioKit#593]
Updated Xcode this morning and was greeted by this lovely warning. Tried uninstalling audio kit.. reinstalling... changing "Use Legacy Swift Language Version" to "Yes,No and unspecified"... still will not let me compile. Any ideas?

**Comment by megastep** [comment]
Yeah, we have to rebuild the binaries with Xcode 8.1, should happen in the coming days hopefully.

**Comment by Tr736** [comment]
Thanks for the quick response

**Comment by petkrein** [comment]
Thanks for the quick response

**Comment by Tr736** [comment]
Do that you think this issue will be resolved by Monday?

**Comment by megastep** [comment]
Looks like we're making a new release tomorrow which will address this issue.

**Comment by megastep** [comment]
We just released 3.4.3, built with Xcode 8.1. This should address this issue.

**Comment by Tr736** [comment]
Thanks Stephane.. I'll give it a go in a moment and let you know if the issue has been resolved

**Comment by Tr736** [comment]
Thanks again works like a charm
