### ISSUE TITLE
Recognizing human voice

### ISSUE THREAD

**Issue by matheusjkweber** [audiokit/AudioKit#594]
I am getting sound from microphone and I want to recognize if the voice is male or female, I have to make a FFT or something like this? I am getting the frequency using:

tracker = AKFrequencyTracker.init(mic)
and tracker.frequency, but the frequency get is very high(800++).

I know that male voice frequency is 85-180Hz and female is 165-255Hz(https://en.wikipedia.org/wiki/Voice_frequency).

**Comment by aure** [comment]
There is no issue listed here.
