### ISSUE TITLE
[QUESTION] is audiokit useful for making actual audio units for DAWs

### ISSUE THREAD

**Issue by lewislepton** [audiokit/AudioKit#597]
howdy folks

so i have been thinking of getting back into doing audio units. and by those i mean in the traditional sense of DAW AU components.
is audiokit capable of such things?
it seems like a great project, but cant seem to find much info, tutorials, if any that could help towards this. did spot something on AU within the audiokit docs, but merely a mention

whilst i know this is for application use, the term audio units can be vague considering that im used to AU in a sense of DAW effects and/or instruments

cheers if you can help. id love to make some AU again for effects and instrument building for myself. maybe even market ;)

thanks

**Comment by aure** [comment]
Yes, someone already has used AudioKit for this.  

https://gist.github.com/iamyellow/58aa2a3240cecb42bf4235bd0eb2864e

It's on our agenda to make it easier: https://github.com/audiokit/AudioKit/projects/2

**Comment by lewislepton** [comment]
that is brilliant. and great to know. there isnt really much in terms of building AU things without having to know either something that helps you build it like reaktor or use VST instead

thanks again. ill keep my eye out and start learning now ;)
