### ISSUE TITLE
AQDefaultDevice messages using Develop branch and Xcode 8.1

### ISSUE THREAD

**Issue by csann** [audiokit/AudioKit#598]
I am getting the following message printed every 2 seconds after I do "AudioKit.start()":

2016-10-30 21:36:08.615013 MyProduct[8349:76547] [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0

I do not recall seeing this back with Xcode 8.0. Otherwise my app appears to be working normally. 

I get this message using both the master and develop branch. 

See this link for others who experience this using audio other than AudioKit....

[http://stackoverflow.com/questions/40048954/xcode-8-1-beta-3-aqdefaultdevice-messages](url)

**Comment by aure** [comment]
The link is dead and I do not get this error.  Does it appear when running one of the example apps?  On the simulator or an actual device?

**Comment by csann** [comment]
Here is the link again...
http://stackoverflow.com/questions/40048954/xcode-8-1-beta-3-aqdefaultdevice-messages
I think I somehow pasted it into the issue incorrectly. 

The message occurs in various simulators but not in an actual device. I have not been able to reproduce it in one of your example apps. 

It now seems to me that I have a problem with my app that I need to diagnose. Shall I close this issue?

**Comment by csann** [comment]
I have found more information about this problem. This code will cause the problem...

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        sampler = AKMIDISampler()
        sampler.loadMelodicSoundFont("RealFont_2_1", preset: 26)  // or pick your own sound font.
        AudioKit.output = sampler
        AudioKit.start()
}

...but only in the simulator, not in the device. The problem appears to be related to the MIDISampler. 

Incidentally, I have a simple project demonstrating the AKMidiSampler. It might make sense to include it in with the examples. If you want it, let me know how to send it to you.

**Comment by aure** [comment]
Hi, it sounds like the message is out of my control.  Of course, I'd love to see your example.  If you can make a repo for it, or email at aure at audiokit dot io and we can set up dropbox.  Or if it is small enough, just email the zipped project to that address.
