### ISSUE TITLE
Volume really low with AKOscillatorBank

### ISSUE THREAD

**Issue by dkun7944** [audiokit/AudioKit#599]
I'm using an AKOscillator bank as such:

```
self.mixer = AKMixer()
bank = AKOscillatorBank(waveform: AKTable(.triangle), attackDuration: 0.05, releaseDuration: 0.05)

mixer.connect(bank)
AudioKit.output = mixer
AudioKit.start()
```

but when I do `bank.play(noteNumber: 80, velocity: 127)` the volume is rather quiet. I've tried using an AKBooster but that results in really ugly sounding oscillators, and I've verified that `bank.sustainlevel` is at 1.0. I've also tried running the code on two different devices (iPhone 6 with iOS 10.0.2 and iPhone 6S with iOS 10.0.2). 

Any suggestions?

**Comment by junhohong** [comment]
How does it sound through headphones? There are hardware limitations on the speakers. Is the sound coming out of the earpiece, or the bottom speakers? Have you checked the amplitude?

**Comment by dkun7944** [comment]
Ah! It looks like the audio is coming out of the earpiece. I didn't even notice that. How do I make it come out of the bottom speakers?

**Comment by junhohong** [comment]
Check out #586

**Comment by dkun7944** [comment]
Thanks. Really appreciate your help

**Comment by aure** [comment]
Seems to be resolved, reopen if necessary.

**Comment by junhohong** [comment]
@dkun7944  :)
