### ISSUE TITLE
Only ear speaker on iPhone

### ISSUE THREAD

**Issue by carbonimax** [audiokit/AudioKit#600]
Hi,

On iPhone, this code generate sound only on the ear speaker (next to the FaceTime camera). Nothing out of the main speaker at the bottom. It works great on iPad Pro or simulators.

    let mic = AKMicrophone()
    let tracker = AKFrequencyTracker(mic)
    let sampler = AKSampler()
    sampler.loadMelodicSoundFont("Gibson", preset: 0)
    AudioKit.output = AKMixer(AKBooster(tracker, gain: 0), sampler)
    AudioKit.start()
    sampler.play(noteNumber: 44, velocity: 96, channel: 0)

I do something wrong?

Solution in #586 doesn't help

**Comment by carbonimax** [comment]
With 

    ...
    AudioKit.start()
    try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, with:AVAudioSessionCategoryOptions.defaultToSpeaker)
    sampler.play(noteNumber: 44, velocity: 96, channel: 0)

it works.

**Comment by carbonimax** [comment]
With 

    ...
    AudioKit.start()
    try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, with:AVAudioSessionCategoryOptions.defaultToSpeaker)
    sampler.play(noteNumber: 44, velocity: 96, channel: 0)

it works but with a lot of distorsion.

**Comment by junhohong** [comment]
Check out AKBalancer. I think the distortion happens when the amplitude is more than the hardware can handle.

**Comment by junhohong** [comment]
Your gain is pretty high. That can also lead to distortion if many of them are overlapped.

**Comment by carbonimax** [comment]
Finally it works with this code :

    let mic = AKMicrophone()
    let tracker = AKFrequencyTracker(mic)
    let sampler = AKSampler()
    sampler.loadMelodicSoundFont("Gibson", preset: 0)
    AudioKit.output = AKMixer(AKBooster(tracker, gain: 0), sampler)
    try! AKSettings.session.overrideOutputAudioPort(AVAudioSessionPortOverride.speaker)
    AudioKit.start()
    sampler.play(noteNumber: 44, velocity: 96, channel: 0)

Thank you
