### ISSUE TITLE
Possible to process and then export?

### ISSUE THREAD

**Issue by ellieDev** [audiokit/AudioKit#601]
Hey, cool project!! 

Maybe a silly question - but I didn't find an example showing this.   

Here's what I need to do: 

- take audio (either from a video file, or a CMSampleBuffer, or possibly the microphone), 
- process it (just a simple pitch shift to start), and 
- export the result (to be added back into the video file)

I've been reading the docs and following the example here -- http://audiokit.io/playgrounds/Effects/Pitch%20Shifter/ -- and I'm able to grab audio and process it (play it with effects), but I'm unsure of how to export the result after processing. 

Ideally, the audio would be loaded, processed, and exported back into the video file without any realtime playback - so my users would be unaware of the post processing of the audio until the video file is shown (with the pitch shifted audio)

Is this possible with AudioKit, or should I look elsewhere?

Thanks!

**Comment by aure** [comment]
Are you basically talking about recording and saving?  We have that.
