### ISSUE TITLE
Recent AKAudioPlayer Updates Break Setting startTime Ahead of Playback

### ISSUE THREAD

**Issue by lastcommit** [audiokit/AudioKit#603]
@ryanfrancesconi It looks like this change #592 alters the default behavior of the AKAudioPlayerNode in a way that breaks with the expected behavior. Now that play() is a synonym for play(from:0), it messes up code that relies on setting a startTime before playback. It also breaks with the documentation for [AKToggleable ](http://audiokit.io/docs/Protocols/AKToggleable.html#/s:FE8AudioKitPS_12AKToggleable4playFT_T_) which states that play() is a synonym for start().

Consider this example with the current code:

```
let player = AKAudioPlayer!
\* code to setup and initialize the player with an audio file *\

player.startTime = 2.0
player.play()
```
The player startTime is reset by the play(from: 0) call and the player starts playing at the incorrect start time.

Or consider this:

```
let player = AKAudioPlayerNode!
\* code to setup and initialize the player with an audio file *\

player.startTime = 2.0
player.start()
```
Here the buffer is never scheduled and there is no sound played.

**Comment by ryanfrancesconi** [comment]
Thanks for this. I will fix it today!
Ryan
 
 
-----Original Message-----

**Comment by aure** [comment]
Fixed by https://github.com/audiokit/AudioKit/pull/604
