### ISSUE TITLE
AKFluteDSPKernel.hpp doesn't handle note off's correctly

### ISSUE THREAD

**Issue by knagle** [audiokit/AudioKit#608]
It looks like sending a stop() from AKFlute will never lead to a flute note off in AKFluteDSPKernel. This is because trigger() causes the 'started' property to be set to true, and the process() function then triggers a flute->noteOn. However, when we call stop() from AKFlute, even though it leads to 'started' being false, the process() function then sets *out to 0.0, and then immediately overwrites that with a flute->tick(). 

Should *out = 0.0; on line 132 be replaced with flute->noteOff(amplitude); in this instance? In my testing I'm getting infinite hanging notes from AKFlute otherwise. It does not naturally decay like the karplus string or metal bar does.

**Comment by aure** [comment]
So, I just moved the tick up into the else block.  Does that work better for you?

**Comment by aure** [comment]
Closing for now, you can reopen it if you have more issues.
