### ISSUE TITLE
AudioKit not importing

### ISSUE THREAD

**Issue by BMarx981** [audiokit/AudioKit#617]
I have looked through a few different versions of this issue, such as Can't import AudioKit framework #343 
I thought it got me out of the woods but then I ended up with this error:
module compiled with swift 3.0.1 cannot be imported in swift 3. 
This is the error given with the exclamation point on the import AudioKit line.
I'm not sure if this is an Xcode 8 issue or an AudioKit problem. I am using Xcode 8 with OS 10.11.6. Let me know if you need any more info.
Thanks

**Comment by aure** [comment]
Update your Xcode to the latest and you should be fine.

**Comment by aure** [comment]
Reopen this issue if new Xcode doesn't fix things.
