### ISSUE TITLE
Playground for iOS Balancing Nodes error 'required condition is false: comp != NULL'

### ISSUE THREAD

**Issue by doozMen** [audiokit/AudioKit#627]
The line:
```swift
let highPassFiltering = AKHighPassFilter(source, cutoffFrequency: 900)
```
gives the error. It looks like something is released by I don't know what. Petty because the filter is the part I am most interested in.
Thanks for any help!

**Comment by aure** [comment]
Okay, this just happened to me too, so we'll get to the bottom of this!

**Comment by aure** [comment]
So, I was having this problem for a while, but its gone now.  Which branch are you using?

**Comment by aure** [comment]
This should be fixed with tonight's release.

**Comment by doozMen** [comment]
I was on develop. Help and Quick fix is much appriciated!
