### ISSUE TITLE
Attempting to use AKNodeFFTPlot or AKNodeOutputPlot causes crash

### ISSUE THREAD

**Issue by thislooksfun** [audiokit/AudioKit#631]
When attempting to use a `AKNodeFFTPlot` I came across the following crash:

<img width="1680" alt="screen shot 2016-11-16 at 10 17 13 pm" src="https://cloud.githubusercontent.com/assets/5367333/20376271/ab4c4cc8-ac4a-11e6-9c2c-a0a317d70bb2.png">

Here's the code that causes that:

```swift
import Cocoa
import AudioKit

class ViewController: NSViewController
{
	override func viewDidLoad() {
		super.viewDidLoad()
		
		let oscillator = AKOscillator(waveform: AKTable(.sine, count: 4096))
		
		AudioKit.output = oscillator
		AudioKit.start()
		
		oscillator.start()
		
		let plot = AKNodeFFTPlot(oscillator, frame: CGRect(x: 0, y: 0, width: 500, height: 500))
		
		self.view.addSubview(plot)
	}
}
```

More info:
* Replacing the `AKNodeFFTPlot` with an `AKNodeOutputPlot` causes the same crash (I only tested those two).
* Removing the `addSubview(_:)` call does nothing
* Removing the AKNode???Plot fixes the crash, but as you can see from the stacktrace it's not being directly called anywhere, so I can't give any more detailed info atm. Let me know if there's any more info you need.
* If `AudioKit.start()` hasn't been called, this problem doesn't happen

**Comment by aure** [comment]
Is this using the latest AudioKit 3.5?  I thought I had fixed that, but see if sending the microphone into an AKMixer and the putting the fft plot on the mixer instead.  It has to do with audio formats.

**Comment by thislooksfun** [comment]
Can confirm: putting it through an `AKMixer` worked perfectly

**Comment by thislooksfun** [comment]
Also, yes I'm using the latest 3.5. Just downloaded it 30 mins before I posted this. Totally forgot to answer that question.

**Comment by aure** [comment]
Yeah, so I guess I fixed this, but only on the iOS side, on the Mac side you'll still need to stick in a mixer whenever you want to tap an AKNode that is not built off of an Apple based processor.  I think I'll still call this issue closed, but feel free to open it or another one.  You can see I'm responsive! :)
