### ISSUE TITLE
iOS 7

### ISSUE THREAD

**Issue by pjebs** [audiokit/AudioKit#633]
My project targets iOS7+ and is a mixed Swift 2/Obj-C Project. It uses TAAE 1.

A few days ago the creator of TAAE retired TAAE 1 and said moving forward use AudioKit.

Is there some way I can use this library with iOS7+, even if it means I add the code manually since Swift2+iOS7+Cocoapods doesn't work (i.e. I have to add Swift code manually directly into project)

I'm not sure what to do here.

**Comment by aure** [comment]
No, AudioKit uses AVAudioEngine which was first introduced iOS8.  Stick with TAAE if you want to maintain backwards compatibility that far.
