### ISSUE TITLE
Out of memory crash when loading mp3

### ISSUE THREAD

**Issue by mkoorn** [audiokit/AudioKit#635]
Hi,

I'm trying to load and play an mp3 file. The file is around 8mb.

i'm using code like below:
let audioFile = try AKAudioFile(forReading: url)
let player = try AKAudioPlayer(file: audioFile) {
                print("completion callback has been triggered !")
            }

AudioKit.output = player
AudioKit.start()
player.play()

When I run this on the simulator the memory spikes to 150MB. When running on a device the connection to the device is lost and the app crashes.

Is this kind of memory usage expected? Is there a way to lower memory usage when playing an mp3 file?

**Comment by aure** [comment]
This is definitely strange.  The song processor demo loads up my mp3s just fine, and they are bigger than 8MB.  Can you send me the file / project in question?

**Comment by aure** [comment]
It seems like there might be an issue where it is trying to repeatedly load the same file into memory.

**Comment by mkoorn** [comment]
Hi Aure,

I have attached the file I am using. It is just a standard beat created in garageband and then exported to mp3.
I have also tried some mp3's from my music library, while not crashing these still increases memory over 100mb.

[beat 100bpm.mp3.zip](https://github.com/audiokit/AudioKit/files/612783/beat.100bpm.mp3.zip)

**Comment by aure** [comment]
That link doesn't work for me.  It's probably not the file but the implementation. Can you share a github project with me?

**Comment by mkoorn** [comment]
ok, will share a project later today.

Thanks!

**Comment by aure** [comment]
Reopen the issue when you have a project to share.

**Comment by mkoorn** [comment]
Hi have created a test project.
https://github.com/mkoorn/AudioKitTest

**Comment by aure** [comment]
Cool, I'll have a look.  I was thinking that actually the memory going up that much may not be too bad.  It does uncompress the audio file, so I'd expect an mp3 to expand quite a bit, but why that should lead to a crash is troubling.

**Comment by mkoorn** [comment]
Hi Aure, thanks for looking into this.

I did some more testing. When running a debug session, the app crashes due to memory issues. When running without debug this mp3 loads and plays ok.

I added a new test mp3, which is 11,5MB and 12 minutes long. Loading and playing this file crashes even when not attached to the debugger.

I have no experience with audio programming, but I can imagine that having the complete uncompressed audio in memory lets you do more advanced processing on the audio in real time.

It would however be very useful to me to be able to play longer mp3's
Would it be possible to have the option to either load the entire audio in memory and an option not pre-loading the whole file and, so to speak, stream the audio from disk?

One of the reasons I found AudioKit, is that it lets me change the speed of audio without affecting pitch.
Hopefully this feature could still be used when not loading the entire uncompressed audio data.

**Comment by aure** [comment]
The thing is that I can run Song Processor (a demo included with AudioKit) and easily open up a twenty minute long piece of music and process it.  Can you try that app and in the mean time I will open up your demo project.

**Comment by aure** [comment]
I tried your app and it ran fine, but if i pressed the button more than once, it crashes, is it possible that you're pressing it twice?

**Comment by mkoorn** [comment]
Yes, possible, I retested making sure this was not the case.
I also tested the Song processor demo, with this file and ran into the same issue.

I think the issue is due to 512MB memory of my iPad2. On my other devices (1024MB) I don't have this issue with the files tested.

Mostly songs played will be around 3 or 4 minutes. So these will be fine, but it leaves a vulnerability for older devices and larger songs.

I guess newer devices would run into this issue as well, if the song is long enough.

I would welcome the possibility to play larger songs without loading all uncompressed audio in memory, but I don't know if it would still be possible to use features like changing speed without pitch.
Also, I have no idea what the workload for such a feature is and how many users would even want it.

Anyways,

Thanks for your time and effort checking this out.

**Comment by aure** [comment]
Well, if it is something that I can fix, then I put the time in to fix it regardless, but this seems like it may be deeper than I'm able to go.  We rely on the AVAudioPlayer for playback so if that is failing, that's not part of the AudioKit code base, but rather AVFoundation.  We've been considering the idea of writing our own player to cut the dependencies a bit but that is only in the idea stage right now.

**Comment by mkoorn** [comment]
I updated the test project with a test for AVAudioPlayer.
using this, I can play the file without any memory issue, but it's evidently not loading the total uncompressed audio into memory.
