### ISSUE TITLE
AKMicrophone limits input to 2 channels max

### ISSUE THREAD

**Issue by scamhaji** [audiokit/AudioKit#638]
Hi, 
I try to work with AudioKit and a Soundflower virtual sound card. Here is an example of what I am trying to achieve:

```
        let mic = AKMicrophone()
        let device = AKDevice(name:"Soundflower (64ch)", deviceID:55);
        do {
            try mic.setDevice(device)
        }
        catch  {}

        AudioKit.output = mic
        AudioKit.start()
        mic.start()
```

When I launch this example, I can only hear (on the default Speaker output) the first 2 channels.
I was expecting to hear the 64 channels. Am I thinking wrong ? Moreover, I'd like to be able to mute/unmute chosen channels dynamically and also manage individual channel volume.

PS.: mic.setDevice does not seem to work properly (I know the bug is supposed top be fixed, but I cloned the master yesterday and it seems it it not resolved).

Thanks for your time and this great work!

**Comment by aure** [comment]
Hmm, yeah, this _was_ working, as far as microphone selection was concerned, but a quick check seems to verify your findings.  As for the 64 channels, we don't have anything in there to mix down n channels into the standard AudioKit stereo, ie 2 channels.  So, it would be something you or someone would have to extend AudioKit to do.

**Comment by scamhaji** [comment]
Thanks Aurelius, I'd like to participate and extend AudioKit if I can. Do you think dealing with `kAudioUnitSubType_MultiChannelMixer` or `kAudioUnitSubType_MatrixMixer` is the right direction?
And last but not least, do I have to manipulate buffers to do the mix down (summing the samples or something like that)?

**Comment by aure** [comment]
I think the multi channel mixer is a good place to start.  Probably won't need the matrix mixer for this.

**Comment by aure** [comment]
I've fixed the mic.setDevice on the develop branch.  It seems to me that Apple changed something because the set input device no longer sets it for the entire mac, which is good.  I'll close this issue now because that bug is fixed, and it's kind of an old issue anyway, if you ever want to recreate an issue with new information, please do, by all means.
