### ISSUE TITLE
EXC_BAD_ACCESS crash when opening a malformed file in AKAudioFile for reading

### ISSUE THREAD

**Issue by lastcommit** [audiokit/AudioKit#639]
This is a bit weird. If you take a malformed audio file and open it with AKAudioFile(forReading: badFile) it will create a crash even if you attempt to catch the error. The crash doesn't happen if you call the super class with the same method.

To reproduce, create a bad file by renaming a mp3 as a wav (i.e. badFile.mp3 -> badFile.wav) then run this in a playground:

This will catch a bad file:
```
let badFile = Bundle.main.url(forResource: "badFile", withExtension: "wav")!

do {
    let akAudioFile = try AKAudioFile(forReading: badFile, commonFormat: .pcmFormatFloat32, interleaved: true)
} catch {
    dump(error)
}
```

This results in a crash with an EXC_BAD_ACCESS error:
```
do {
    let akAudioFile = try AKAudioFile(forReading: badFile)
} catch {
    dump(error)
}
```

This is where it gets weird. This properly catches in the super class even though AKAudioFile's init(forReading:) is simply calling the super's init.:
```
do {
    let avAudioFile = try AVAudioFile(forReading: badFile)
} catch {
    dump(error)
}
```

**Comment by aure** [comment]
Do you by any chance have the playground you can either zip and send me or post as a project on github?  Just would make it faster to test.  Otherwise I will get around to testing this eventually.  Thanks!

**Comment by lastcommit** [comment]
You can grab the zipped playground here: [Issue639.playground.zip](https://github.com/audiokit/AudioKit/files/623689/Issue639.playground.zip).

I've noticed the crash is intermittent in the playground. If it loads fine right away, you may need to copy and paste the crashing block elsewhere in the file. Thanks for looking!

**Comment by jsbean** [comment]
I have seen this error occur on the simulator and devices, as well. Further, there has been a circumstance where it occurs on one device, yet not on another.

If a non-Playground project would be helpful, I can put something together.

**Comment by aure** [comment]
@jsbean Sure, that would be helpful. Thanks!

**Comment by aure** [comment]
Well, this one is officially a stumper.  I see no reason why this happens like this.  It almost feels like a Swift bug given how thin the layer of AudioKit is on this.

**Comment by aure** [comment]
@laurentVeliscek Have you had a look at this issue?  It's a weird one.

**Comment by adamnemecek** [comment]
This seems to be a AVAudioFile issue. See this gist https://gist.github.com/adamnemecek/1ad587720676ae807c95518ded46c694
AKAudioFile still fails despite having no additional code.

**Comment by aure** [comment]
The important thing about Adam's gist is that any subclassing of AVAudioFile reveals this problem.  His gist used the name "AKAudioFile" but it could have been anything because it was just an empty subclass.

**Comment by adamnemecek** [comment]
Now that I think about it, I'm not sure if there aren't more than one issue going on. How did this ever work in the first place? I guess the only explanation would be if Apple introduced this bug only recently.

**Comment by aure** [comment]
So, I'm going to officially classify this as a "won't fix" because it is so bizarre.  But, we should probably take a second look at all the AKAudioFile and AKAudioPlayer stuff.
