### ISSUE TITLE
No tools for this?

### ISSUE THREAD

**Issue by pjebs** [audiokit/AudioKit#640]
I have two sources of audio data:

```
static OSStatus playout_cb(void *ref_con,
                           AudioUnitRenderActionFlags *action_flags,
                           const AudioTimeStamp *time_stamp,
                           UInt32 bus_num,
                           UInt32 num_frames,
                           AudioBufferList *buffer_list)

static OSStatus recording_cb(void *ref_con,
                             AudioUnitRenderActionFlags *action_flags,
                             const AudioTimeStamp *time_stamp,
                             UInt32 bus_num,
                             UInt32 num_frames,
                             AudioBufferList *data)
```

I'm in the process of transitioning from TAAE1 to AudioKit.
In TAAE1, I use the `AEMixerBuffer` to combine the 2 streams together.
I then redirect the output of the mixer to `AEAudioFileWriter` to save it to file.

I've gone through the documentation for AudioKit and I don't see any class where I can load raw audio data that fits the function parameters above and then load it into a Mixer (AKMixer???) and then save the combined audio and save to a file (or append to a file if it already exists).

The raw audio data coming in is in real-time.

Your guidance would be greatly appreciated.

**Comment by aure** [comment]
AudioKit doesn't work like that, that is much lower basically at CoreAudio level.

**Comment by aure** [comment]
You're welcome to keep contributing to this issue as a discussion forum, but its not actionable, so its really more appropriate for the Google group for AudioKit and I am closing the issue.
