### ISSUE TITLE
Can't run any Common playground

### ISSUE THREAD

**Issue by rayray** [audiokit/AudioKit#642]
- Xcode 8.1
- I ran `build_frameworks.sh` and it completed without error
- I closed Xcode & I deleted my derived data folder as recommended here: https://groups.google.com/forum/#!topic/audiokit/Gw8M-t1MS4Q

When I open any of the Common playgrounds (Basics for instance, and going to the Metronome example), I only get this output in the console:

```
Playground execution failed: error: Metronome.xcplaygroundpage:7:8: error: no such module 'AudioKit'
import AudioKit
       ^


* thread #1: tid = 0x25372d, 0x00000001009013c0 Metronome`executePlayground, queue = 'com.apple.main-thread', stop reason = breakpoint 1.2
  * frame #0: 0x00000001009013c0 Metronome`executePlayground
    frame #1: 0x00000001009009c0 Metronome`__37-[XCPAppDelegate enqueueRunLoopBlock]_block_invoke + 32
    frame #2: 0x000000010141b25c CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
    frame #3: 0x0000000101400304 CoreFoundation`__CFRunLoopDoBlocks + 356
    frame #4: 0x00000001013ffa75 CoreFoundation`__CFRunLoopRun + 901
    frame #5: 0x00000001013ff494 CoreFoundation`CFRunLoopRunSpecific + 420
    frame #6: 0x0000000106813a6f GraphicsServices`GSEventRunModal + 161
    frame #7: 0x0000000101faa964 UIKit`UIApplicationMain + 159
    frame #8: 0x00000001009006e9 Metronome`main + 201
    frame #9: 0x000000010495d68d libdyld.dylib`start + 1
```

**Comment by aure** [comment]
You don't run the command line framework building scripts for playgrounds.  The framework must be built either in the same workspace or same project.

Are you opening the playgrounds up one by one or are you opening up the "AudioKit for XXX.xcodeproj" files where XXX is the platform?  You should be opening the project.

**Comment by aure** [comment]
https://vimeo.com/153057128
