### ISSUE TITLE
Can we have demo for SessionCategory ?

### ISSUE THREAD

**Issue by hainguyen86** [audiokit/AudioKit#644]
Hi audiokit,
Thanks audiokit,
I'm an AudioKit beginner and I have made an music player app with AudioKit.
It's can play in background well :).
Now, I want to interact with playback control on locked screen so I'm looking for a solution.
Currently, I'm stuck with SessionCategory.

`player = try AKAudioPlayer(file: AKAudioFile(forReading: URL(fileURLWithPath: sound.filePath)))
                player!.completionHandler = { [unowned self] _ in
                    self.onPlayingSubject.onNext(false)
                }
                AKSettings.playbackWhileMuted = true
                AudioKit.output = player
                AKSettings.disableAVAudioSessionCategoryManagement = false
                try AKSettings.setSession(category: AKSettings.SessionCategory.playback)
                
                AudioKit.start()
                player!.play()`

No playback controll is on lock screen right now.
Please give me some advice.
Regards,

**Comment by dylan** [comment]
I would recommend checking out: https://developer.apple.com/library/content/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionBasics/AudioSessionBasics.html#//apple_ref/doc/uid/TP40007875-CH3-SW5, it may help you sort out the best path to take.

**Comment by aure** [comment]
Yeah, this is basically core audio session stuff, not specific to AudioKit and I don't really know what a compelling demo would look like anyway.  Perhaps you can make one and submit it via a pull request?
