### ISSUE TITLE
AKTable very long init times

### ISSUE THREAD

**Issue by knagle** [audiokit/AudioKit#647]
One of my custom instruments was taking quite a while to load when I made the switch to AudioKit 3.5. I had switched directly from version 3.3 to 3.5 so did not notice the significant changes to AKTable that were made in the meantime.

I eventually tracked my problem down to AKTable. On my machine the 3.5 version takes 2.1 seconds to generate a sine table, 3.12 seconds for a square and 3.13 seconds for a sawtooth. This compares with 1.09 seconds for a sine wave, 2.17 seconds for a square and 2.16 seconds for a sawtooth in version 3.4.3. 

However, in version 3.3 a sine table is generated in 0.025 seconds, a square table takes 0.02 seconds and a sawtooth table takes 0.026.

My instrument contains three oscillator banks: a square and two sawtooth. So the load time is now almost 10 seconds, where before it was 0.07 seconds.

I'm not quite sure what causes the slowdown. It could be that the AKTable is now a MutableCollection and sets the entire collection to zero before performing the calculations. I haven't quite narrowed it down. I can solve the problem by reverting to the 3.3 version of AKTable with a slight re-write for Swift 3 compatibility. However, that breaks 9 Oscillator classes, which all need to be adjusted to accommodate the older version of the AKTable (i.e. not a collection, so no enumeration etc.). This is not an ideal solution. 

Can anything be done about the performance of the latest AKTable? Was there a compelling reason to make it a MutableCollection?

**Comment by aure** [comment]
@adamnemecek I think this was your change.  When some initial changes were made, things got faster, but yeah, it does seem like something has gone terribly wrong.  Thanks for noticing @knagle

**Comment by aure** [comment]
@knagle You can probably fairly easily revert to the 3.3 version of AKTable if you are using the source directly, or else when its fixed we'll release an updated framework and CocoaPod.

**Comment by adamnemecek** [comment]
tell me more about your test. how did you measure this and did you run it on debug or release?

**Comment by adamnemecek** [comment]
also even 1s seems like a lot. are you running this in the ios simulator by any chance?

**Comment by knagle** [comment]
I first noticed the delay when loading the instrument as part of my built app on an iPad, with the audio kit iOS project included in mine, so it compiles as an embedded framework for my app. My app would stall on the load screen and only fully load when the instrument had loaded, about 10 seconds later. I then ran a few tests in the playground for AKOscillatorBank using Date() to measure the times before and after the AKtable is initialised. Crude, I know, but the delay seemed to be accounted for with AKTable. I'll make sure the AudioKit project is built in release and repeat the tests in my app and the playground and see if it makes a difference.

**Comment by adamnemecek** [comment]
also re: I'm not quite sure what causes the slowdown. It could be that the AKTable is now a MutableCollection and sets the entire collection to zero before performing the calculations.

this should actually be a speedup because we alloc the memory in one shot before setting the values as opposed to appending one by one. 

also you shouldn't be using Date i think try CACurrentMediaTime from QuartzCore.

**Comment by knagle** [comment]
Thanks @adamnemecek. I switched the build from debug to release and it changed everything. The 10 second delay is gone. I should have checked this before logging the issue. 
I also repeated my playground tests using CACurrentMediaTime instead of date as you suggested. The results were interesting in that the AKTable from version 3.3 performs the same in debug and release mode and AKTable from version 3.5 has such a huge discrepancy. My code is pretty basic. e.g.

` var before = CACurrentMediaTime()`
`let sin = AKTable(.sine)`
`var after = CACurrentMediaTime()-before`
`print("Time to load AudioKit 3.5 sine table: \(after)")`

`before = CACurrentMediaTime()`
`let sin2 = AKTable3_3(.sine)`
`after = CACurrentMediaTime()-before`
`print("Time to load AudioKit 3.3 sine table: \(after))") `

and so on for the square and sawtooth tables...

Here are my console results for the release build:

Time to load AudioKit 3.5 sine table: 0.0418615669987048
Time to load AudioKit 3.3 sine table: 0.0258172339963494)
Time to load AudioKit 3.5 square table: 0.0348588740016567
Time to load AudioKit 3.3 square table: 0.02439965299709
Time to load AudioKit 3.5 sawtooth table: 0.0470353819982847
Time to load AudioKit 3.3 sawtooth table: 0.0275405590000446

And the results for the debug build:

Time to load AudioKit 3.5 sine table: 2.21423152300122
Time to load AudioKit 3.3 sine table: 0.0270791740040295)
Time to load AudioKit 3.5 square table: 3.21181402599905
Time to load AudioKit 3.3 square table: 0.0296517530077836
Time to load AudioKit 3.5 sawtooth table: 3.15386372899229
Time to load AudioKit 3.3 sawtooth table: 0.027750578999985

So, the AKTable from version 3.3 performs about the same in release and debug mode, but the version from 3.5 performs terribly in debug mode. For what it's worth, AKTable in version 3.3 appears to be faster to load in release mode, even though it's much less noticeable. 3-4ms to generate a table once and pass its contents on to an oscillator is more that fast enough I would imagine, but it brings me back to the last part of my original question; was there a compelling reason to make AKTable a MutableCollection?

**Comment by adamnemecek** [comment]
> was there a compelling reason to make AKTable a MutableCollection?

making it idiomatic.

i figured out what the issue. imma submit a patch to make it roughly as fast as release.

**Comment by adamnemecek** [comment]
if you want to give it a shot replace the aktable file with this file

https://gist.github.com/adamnemecek/619d85885a030dbb9efe54be25cddae3

and tell me what you see. i did some perf testing and it might make it slightly faster so i'm curious to compare it on your machine.

**Comment by aure** [comment]
This seems to have been solved.
