### ISSUE TITLE
availableInputs not showing interface

### ISSUE THREAD

**Issue by Joebayld** [audiokit/AudioKit#650]
I'm on macOS and I'm having an issue getting AudioKit to see my MOTU 828 interface. It works fine with other CoreAudio apps, but for some reason this won't see it. I can see the system default input only. Is this expected behavior? 

Thanks,
Joe

**Comment by aure** [comment]
No, this is not expected.  It should show up.  Is this in an application or playground or?

**Comment by Joebayld** [comment]
Tried both an Application and a playground. My Apogee Duet shows up, but not the MOTU. 

Also, is there any documentation that explains how to use a specific input on the interface. i.e. the Duet has two inputs, is it possible to specify only input one?

I really like the framework and hope I can use it in the future!

**Comment by aure** [comment]
huh, that is weird that one shows up but not the other.  I used to have a few MOTU devices but I don't any longer, so I can't really test.  I'm willing do a screen share with you but I don't know what else I can do.  If you're willing to dig into the source, you could probably make good progress.

**Comment by Joebayld** [comment]
After digging into the source, I found where the problem is. I'm getting a NSLog error saying:

`Error: Failed to get frame size ('!siz')
`

EZAudio is not finding the number of inputs and outputs for the interface in the calls: 

```
device.inputChannelCount = [self channelCountForScope:kAudioObjectPropertyScopeInput forDeviceID:deviceID];
device.outputChannelCount = [self channelCountForScope:kAudioObjectPropertyScopeOutput forDeviceID:deviceID];

```

I think part of the issue is that the interface has multiple streams. See attached screenshot from another app that lists the interface input streams. I don't think AudioKit accounts for interfaces like this (thus the error). To my understanding, it currently supports a single stream interface. Which brings me back to my original question - how would you specify a specific channel on a interface? On the `AKMicrophone` class, you can set a device as the source, but in my scenario, that device has up to 24 individual inputs. Is this possible?
 
<img width="548" alt="screen shot 2016-12-11 at 5 54 59 pm" src="https://cloud.githubusercontent.com/assets/9399317/21084083/9637c3c8-bfcb-11e6-83ad-91aabb5b4bed.png">

**Comment by Joebayld** [comment]
@aure I've submitted a pull request to EZAudio to fix the issue of it not showing the interface. It all seems good now. Now we just need to figure out how to work with multi-channel interfaces. 

I feel like it would be nice to have a channel variable on the AKMicrophone. And then maybe a channelL and channelL on the stereo input. That way, if I have a 24ch interface, I can have multiple instances of the AKMicrophone referring to different inputs. I'm willing to help make this possible. Thoughts? The only other struggle will be making sure that it works with interfaces that have multiple streams. I'll dive into the CoreAudio SDK and figure out how that works. 

Thanks

**Comment by aure** [comment]
Um, EZAudio is deprecated and Haris doesn't keep up with pull requests anymore.  Can you make the same pull request onto AudioKit?

**Comment by Joebayld** [comment]
Added a pull request for AudioKit. Working on a channeling solution for inputs now. 

#653

**Comment by aure** [comment]
Cool, well since you're the one pushing this forward, I'm not seeing a reason to keep the issue open, but if you want, you can reopen it.

**Comment by Joebayld** [comment]
Unfortunately I've not had much luck with this. Each AKMicrophone instance has a AVAudioMixerNode. I'm trying to determine what channels of the AudioKit.engine get to each mixer, but there's not a lot of documentation. Do you have any insight on this? 

The perfect example of what I want to do is a 2ch audio interface and 2 AKMicrophones. Each microphone gets their own input. 

Thanks for everything thus far. If you can help get this in the right direction, I can put more time into it.

**Comment by aure** [comment]
The problem is I don't have hardware.  I suppose I'll be near a Guitar Center Tuesday and could pick up a hardware interface like yours...
