### ISSUE TITLE
AKSampler connect after AudioKit.start() - (Middle C sine wave)

### ISSUE THREAD

**Issue by pjb493** [audiokit/AudioKit#656]
I am currently having an issue whereby I have multiple AKSamplers being created dynamically, and as I connect them to the master AKMixer, these samples play a middle-C sine wave when more than one sampler is present. According to the forum, this is attributable by connecting nodes to the mixer AFTER AudioKit.start() has been called. Unfortunately due to the nature of my app this has to happen. I have created a simplified example:

    let sampler1 = AKSampler()
    let sampler2 = AKSampler()

    sampler1.loadWav("Sounds/fmpia1")
    sampler2.loadWav("Sounds/fmpia1")

    let mixer = AKMixer()

    mixer.connect(sampler1)
    // mixer.connect(sampler2)   // No sine wave heard

    AudioKit.output = mixer
    AudioKit.start()

    mixer.connect(sampler2)  // sine wave is heard

    sampler1.play()
    sampler2.play()

Please can someone tell me a way to be able to add new samplers to the mixer on the fly without incurring this added sine wave?

Thanks

**Comment by aure** [comment]
This was also posted to the forum which I think is a more appropriate place for the discussion.
