### ISSUE TITLE
Apply effect to AudioFile and save

### ISSUE THREAD

**Issue by appsforall** [audiokit/AudioKit#660]
Is there a way in AudioKit to use an existing AudioFile, apply a certain effect to it and save it? This should all be done in a background process as fast as possible (so not realtime). So basically some export mode that runs faster than realtime?

**Comment by aure** [comment]
This is a known upgrade to AudioKit. http://audiokit.io/wip/  It's not really an issue per se, but a feature.

**Comment by appsforall** [comment]
Hey Aurelius!


Hope you are doing good! Any progress on the offline rendering feature?
Looking forward to start using it! Anything I can do on my end to help or
to make it work?

Regards,
Wim


2016-12-15 3:47 GMT+01:00 Aurelius Prochazka <notifications@github.com>:

**Comment by aure** [comment]
Not much progress that I know of but I will check with some of the people who were looking into it.

**Comment by appsforall** [comment]
Thanks!!!

Verstuurd vanaf mijn iPhone
