### ISSUE TITLE
AKMicrophone routing to bluetooth headphones?

### ISSUE THREAD

**Issue by playfulart** [audiokit/AudioKit#661]
Is it possible to take in the microphone input/stream on the iPhone, analyze it, modify/add to it, and then output that to bluetooth headphones?   I am working on an augmented reality game that modifies/augments/routes the microphone feed to headphones and I can't seem to get this to work with bluetooth headphones.  It seems as though Apple requires the bluetooth route to share input/output (take from bluetooth headphones and output back out to bluetooth headphones).  At the moment, my game audio doesn't work for anyone with bluetooth headphones (required without an adapter on iPhone 7).

**Comment by aure** [comment]
Yes, I believe so, what did you try?  I'm closing the issue until more information is added so that the issue can be actionable.
