### ISSUE TITLE
Audio Player Output Doesn't Go To Speaker (not fixed in #586)

### ISSUE THREAD

**Issue by petkrein** [audiokit/AudioKit#662]
Hi,

i tried (AudioKit 3.5):

`try AKSettings.setSession(category: .playAndRecord, with: AVAudioSessionCategoryOptions.defaultToSpeaker)`

and...
`
try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, with:AVAudioSessionCategoryOptions.mixWithOthers)`

But the **Audio Player Output Doesn't Go To Default Speaker (Bottom Speaker)** only to top Speaker very low (ringtone speaker) !!!

(see project for recorder demo for iOS)

**Comment by aure** [comment]
Where does the audio go?

**Comment by aure** [comment]
I mean, is it just the audio player or anything from AudioKit?

**Comment by petkrein** [comment]
the audio is playing from the top speaker very low (ringtone speaker) not the bottom speaker

**Comment by petkrein** [comment]
I found a solution. When overriding the **outputAudioPort** of the AVAudioSession, i am able to route the audio directly to the default speaker. That seems the only way to go!

  
```
do {
            
    //  try AKSettings.setSession(category: .playAndRecord, with:  AVAudioSessionCategoryOptions.defaultToSpeaker)
            
    let session = AVAudioSession.sharedInstance()
    try session.setCategory(AVAudioSessionCategoryPlayAndRecord)

    if !AKSettings.headPhonesPlugged {
        try session.overrideOutputAudioPort(AVAudioSessionPortOverride.speaker)
     }
} catch {
    print("Errored setting category.")
}
```

**Comment by aure** [comment]
Sweet!

**Comment by olivierlesnicki** [comment]
It also seems to work when using:
```swift
AKSettings.defaultToSpeaker = true
```
