### ISSUE TITLE
fix-framework.sh emits errors when creating archive

### ISSUE THREAD

**Issue by percysnoodle** [audiokit/AudioKit#664]
I've added AudioKit to my project using Cocoapods, and when I tried to publish to the app store I got the error described in #368, so I added a build step to run fix-framework.sh.  The project now builds fine in the Debug configuration, but when I try to create an archive I get:

```
fatal error: lipo: -remove i386 specified but fat file: ./AudioKit.framework/AudioKit does not contain that architecture
fatal error: lipo: -remove x86_64 specified but fat file: ./AudioKit.framework/AudioKit does not contain that architecture
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
```

What do I need do to fix these errors?

**Comment by aure** [comment]
@megastep Do you know what is up with this?

**Comment by megastep** [comment]
Maybe it's got to do with where he put the run phase calling the script, additionally the current version in the `develop` branch should first check for the presence of the architectures before attempting to strip them.

**Comment by aure** [comment]
@percysnoodle Have you tried the recent develop branch?  I'll assume that fixes it as @megastep suggests, but if it doesn't, please feel free to re-open this ticket.

**Comment by percysnoodle** [comment]
Sorry for the late reply - I couldn't test until I got back after the holidays. The develop version of the script has fixed it - thanks!
