### ISSUE TITLE
Fails AppStore validation

### ISSUE THREAD

**Issue by daviddelmonte** [audiokit/AudioKit#665]
I thought I should make this a new issue...

I’m getting these messages on App Store validation.. Did I miss something else? Thanks

 I’m using Xcode 8 GM

oops, forgot to add the messages:

iTunes Store operation failed.
Invalid Signature. Code object is not signed at all. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html

(My app is signed the same as my others)

iTunes Store operation failed.
Unsupported Architectures. The executable for FatTuna.app/Frameworks/AudioKit.framework contains unsupported architectures '[x86_64, i386]'.

iTunes Store operation failed.
Invalid Segment Alignment. The app binary at 'FatTuna.app/Frameworks/AudioKit.framework/AudioKit' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

iTunes Store operation failed.
The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

**Comment by aure** [comment]
Have you added the fix_frameworks step from https://github.com/audiokit/AudioKit/blob/master/Frameworks/INSTALL.md

**Comment by daviddelmonte** [comment]
Thanks Aure. I recompiled the framework, and all is well.
