### ISSUE TITLE
Will it be possible to set individual track lengths in AKSequencer?

### ISSUE THREAD

**Issue by JoshuaBThompson** [audiokit/AudioKit#667]
As I understand it the AKSequence.tracks all have the same loop length.
Is there an possibility in allowing the individual tracks in AKSequencer to have exclusive loop lengths?

ex:
```swift
sequencer.newTrack()
sequencer.setTempo(120)

//track 0
sequencer.tracks[0].setMIDIOutput(bassDrum.midiIn)
//track 1
sequencer.tracks[1].setMIDIOutput(bassDrum.midiIn)

//track 0 add notes
sequencer.tracks[0].add(noteNumber: 60, velocity: 127, position: AKDuration(seconds: 0), duration:AKDuration(seconds: 0.1))
sequencer.tracks[0].add(noteNumber: 60, velocity: 100, position: AKDuration(seconds: 0.5), duration:AKDuration(seconds: 0.1))

//track 1 add notes
sequencer.tracks[1].add(noteNumber: 60, velocity: 127, position: AKDuration(seconds: 0), duration:AKDuration(seconds: 0.1))
sequencer.tracks[1].add(noteNumber: 60, velocity: 100, position: AKDuration(seconds: 0.5), duration:AKDuration(seconds: 0.1))

//now set track lengths
let track0_loop_length = AKDuration(seconds: 8)
sequence.tracks[0].setLengthSoft(duration: track0_loop_length)

let track1_loop_length = AKDuration(seconds: 4)
sequence.tracks[0].setLengthSoft(duration: track1_loop_length)

//this will cause all track lengths to be 4 seconds instead of having track0 be 8 and track1 be 4

```

That's what I would like to do.
Will this be possible in the near future?

**Comment by aure** [comment]
I assume you mean tracks[1] on the last line?  Nobody is looking at AKSequencer currently, but you're welcome to make it better, open it up and have a look.

**Comment by aure** [comment]
So, I guess the answer to your question, is "No".  I will close this issue since it doesn't seem like anyone else is interested in addressing it. Feel free to reopen it with more information or motivation.

**Comment by JoshuaBThompson** [comment]
Hi Aure,
Sorry, yes I'm going to attempt to update the code to make it work in the fashion I mentioned:)
