### ISSUE TITLE
Disable permission dialog when using AKMicrophone?

### ISSUE THREAD

**Issue by dkun7944** [audiokit/AudioKit#668]
I noticed that when I record using AKMicrophone, the record permission dialog automatically shows when I call AudioKit.start(). Is there any way to prevent this dialog from showing automatically and  show it manually instead using `AKSettings.session.requestRecordPermission()`? I'd like to perform some custom actions based on whether the user presses 'OK' or 'Don't Allow'. 

![img_0186](https://cloud.githubusercontent.com/assets/2880086/21549670/db8e2b52-cdc1-11e6-9fec-49567f851259.PNG)

**Comment by aure** [comment]
That's a good point, but I am not sure how to do that.

**Comment by laurentVeliscek** [comment]
Hi !

Did you try to use AKSettings.session.requestRecordPermission() BEFORE starting AudioKit ?

The major problem is that the permission is requested only once. 
Then, it is set to false or true.
After user disallowed microphone access, he has to change manually this setting. 

Good luck,

Laurent.

Envoyé de mon iPhone

**Comment by dkun7944** [comment]
Hi Laurent,

I did try that, but for some reason whenever I call AudioKit.start() after using the requestRecordPermission, it doesn't always work. I'd say about 40% of the time it works. Maybe this is a bug with AudioKit? I'd be happy to link my project files so someone could take a look.

Thanks,

Daniel

**Comment by aure** [comment]
It's unlikely to be a bug with AudioKit because we're not really doing much beyond what Apple requires you to do.

**Comment by aure** [comment]
@dkun7944 I'm trying to address AudioKit issues this week (while at NAMM with the AudioKit core team).  If this isssue is resolved can you close it, if not can you provide the project files link so that we can look at this once and for all?  Thanks!

**Comment by dkun7944** [comment]
@aure I was able to resolve it on my own. Instead of doing:

 `AKSettings.setSession(category: .playAndRecord, with: .defaultToSpeaker)` 

I used this instead:

 `AKSettings.session.overrideOutputAudioPort(AVAudioSessionPortOverride.speaker)`

Seemed to clear things up. Thanks!

**Comment by aure** [comment]
Sweet!
