### ISSUE TITLE
Found another source (and solution) for "no such module: AudioKit" error

### ISSUE THREAD

**Issue by geoffsdavis** [audiokit/AudioKit#669]
Hey guys,

Looks like an awesome framework, and I'm just about to dive in. I got the famous "no such module: AudioKit" error, and after trying everything I could think of, I noticed I was building for an iPad that was already connected to my Mac. After I selected a simulated iPad, I re-built and ran the playground, and it worked fine. Perhaps it's common knowledge that you can't build frameworks for playgrounds with an actual device, but I didn't know, and didn't think to check until I had exhausted a lot of other possibilities.

Just a thought--maybe you could drop in a sentence or two on your Playgrounds _Non-Audio Tutorial_ page informing people of this possible pitfall, and that they should make sure their selected device is a simulated one.

And thanks for all the hard work! I'm off to dive in and start playing...

Geoff

**Comment by aure** [comment]
Great idea, I'll do it unless you want to make a pull request.

**Comment by aure** [comment]
Fixed in https://github.com/audiokit/AudioKit/commit/4ffcbeece91e3f1e2ad0f34511ffa31cfabaead2

**Comment by aure** [comment]
Thanks @geoffsdavis

**Comment by geoffsdavis** [comment]
Thank you!
