### ISSUE TITLE
Can i make a karaoke effect

### ISSUE THREAD

**Issue by Rozariozaro** [audiokit/AudioKit#674]
I am trying to make a karaoke app that includes audio from music library and makes it into a karaoke like audio by processing the given audio. can you please help me if this effect is possible with AudioKit.

**Comment by narner** [comment]
Yes, it is possible. But you'll have to write some code first - try looking at the example projects to get started. If you get stuck, take a look at the [forum](https://groups.google.com/forum/#!forum/audiokit) and post a question there.
