### ISSUE TITLE
Bluetooth iOS 10

### ISSUE THREAD

**Issue by themichael123** [audiokit/AudioKit#675]
Hi, 

since iOS 10 it is no longer possible to use a bluetooth headset in combination with AudioKit (input, processing, output). 

Can this be fixed ?

**Comment by aure** [comment]
Can you provide more information?  Are you saying this worked with AudioKit in iOS9?  Do you have an example project you can share that demonstrates this so we can test?  Closing until more information.

**Comment by themichael123** [comment]
Hi Aure. 

Yes, this worked in iOS 9. Please find the Xcode Project attached. As you can see, the microphone input is not taken from a connected bluetooth headset, but rather from the internal mic. 

Thanks.
[MicrophoneAnalysis.zip](https://github.com/audiokit/AudioKit/files/686985/MicrophoneAnalysis.zip)

**Comment by aure** [comment]
Hi, we're working on this, its not forgotten.

**Comment by themichael123** [comment]
Thanks Aure.

**Comment by aure** [comment]
I'm not sure if its taken care of by this, but here's some updated bluetooth stuff https://github.com/audiokit/AudioKit/pull/770

**Comment by themichael123** [comment]
Thanks. Will test and let you know...

**Comment by pcbeard** [comment]
I'm assuming the problem boils down to this:

if AKSettings.audioInputEnabled and AKSettings.useBluetooth are both true, then on iOS 10 the opts parameter is set to [.allowBluetoothA2DP, .mixWithOthers]. According to the documentation,

> If this option and the allowBluetooth option are both set, then when a single device supports both the Hands-Free Profile (HFP) and the Advanced Audio Distribution Profile (A2DP), the Hands-Free ports will be given a higher priority for routing.

Even if this isn't the exact cause, it seems like more than a bool is needed to control how Bluetooth is configured. Some kind of enum, or perhaps a value of type AVAudioSessionCategoryOptions that lets the application configure which Bluetooth options should be set. These options would be union'd along with the options passed along to AKSettings.setSession().

**Comment by aure** [comment]
The state of affairs for me currently is that I can get AudioKit outputing to Bluetooth no problem, but the input is still not working.   When I ask AVAudioSession for the list of available inputs, it doesn't even show the bluetooth microphone.  Apple's music memos app also doesn't use the bluetooth input, but facetime does appear to.  Anyway have any ideas?

**Comment by aure** [comment]
Alright, I basically have this working.  @pcbeard is right, it all has to do with bluetooth opts.  For mine to work, I need to have the older .allowBluetooth option set, but then it worked fine.  Once the option was set I was able to set the microphone's device to be the bluetooth mic. So, I think I might add that into the defaults for AudioKit.
