### ISSUE TITLE
AKTimePitch pitch default should be 0.0

### ISSUE THREAD

**Issue by geoffsdavis** [audiokit/AudioKit#679]
Easy bug. In AKTimePitch:

`    /// Pitch (Cents) ranges from -2400 to 2400 (Default: 1.0)
    open var pitch: Double = 1.0 {
        didSet {
            pitch = (-2400...2400).clamp(pitch)
            timePitchAU.pitch = Float(pitch)
        }
    }`

The default value should be 0.0. A default of 1.0 would be a 1 cent shift upward in pitch. 

In Apple's own documentation, they list the default pitch value of the underlying AVAudioUnitTimePitch as 1.0. In fact, if you do a simple printout:

`import AVFoundation  let pitch = AVAudioUnitTimePitch()  print(pitch.pitch) //->0.`

I filed a documentation bug with Apple for this.

**Comment by aure** [comment]
We generated those from the docs, so that's how the 1.0 made it into AudioKit.  Thanks!
