### ISSUE TITLE
AUV3 Effects memory leak

### ISSUE THREAD

**Issue by kowongh** [audiokit/AudioKit#682]
I have come across some memory leaks concerning the C code in Soundpipe when instantiating some AudioKit AVAudioUnit/AUAudioUnits. I've checked the leak issue with multiple AudioKit effects units and they all seem to point to sp_create malloc which is called from the effect's DSPKernels, and SoundPipe>Modules>base.c

It seems to when we start the engine (after they've been connected and attached) and sometimes when we are instantiating the units... so it leads me to believe something is happening when we start up the audio hardware.

### > Bytes Used	                             # Leaks		  Symbol Name
    320 Bytes   90.9%	3	 	                              +[AVAudioUnit instantiateWithComponentDescription:options:completionHandler:]
    320 Bytes   90.9%	3	 	                               APComponent::NewInstance(unsigned int, bool, void (OpaqueAudioComponentInstance*, int) block_pointer)
    320 Bytes   90.9%	3	 	                                AUIB_OpenAsync(void*, OpaqueAudioComponentInstance*, unsigned int, void (OpaqueAudioComponentInstance*, int) block_pointer)
    320 Bytes   90.9%	3	 	                                 AUAudioUnitSubclassInstance::OpenAsync(OpaqueAudioComponentInstance*, unsigned int, void (OpaqueAudioComponentInstance*, int) block_pointer)
    320 Bytes   90.9%	3	 	                                  AUAudioUnitSubclassInstance::Open(OpaqueAudioComponentInstance*)
    320 Bytes   90.9%	3	 	                                   -[AUAudioUnit initWithComponentDescription:error:]
    320 Bytes   90.9%	3	 	                                    -[AKMoogLadderAudioUnit initWithComponentDescription:options:error:]
    256 Bytes   72.7%	2	 	                                     sp_create
    256 Bytes   72.7%	2	 	                                      malloc
    256 Bytes   72.7%	2	 	                                       malloc_zone_malloc
>

**Comment by aure** [comment]
I'm going to need a sample project or something to be able to act on this issue.

**Comment by kowongh** [comment]
Hey Aure, I just ran the SamplerDemo. Thanks!

**Comment by aure** [comment]
Was this analyzing the simulator or the app running on a device?  I have had some spuriously reported memory leaks on the simulator.

**Comment by ryanfrancesconi** [comment]
My comment might be related to this issue - if not, let me know and I can start a new Issue. I have found that the AKAmplitudeTracker isn't being deallocated after the containing class has had its deinit block called. I've dereferenced the object, but it persists. I see that it is using the C++ kernel audio unit method, so I'm wondering if it is related to that.

Here's what I'm seeing in the memory graph of xcode:
![image](https://cloud.githubusercontent.com/assets/2917795/21909626/92c956a0-d8cd-11e6-9e23-6eb24a024ccb.png)

**Comment by kowongh** [comment]
I've confirmed it happens in both the simulator and on a device in both my project and the SamplerDemo

I also see multiple leaks for AVAudioFormat that I've experienced in my own project and SamplerDemo

<img width="1025" alt="screen shot 2017-01-12 at 3 04 57 pm" src="https://cloud.githubusercontent.com/assets/1892737/21912079/9e153c8a-d8d8-11e6-9528-a804c4d036af.png">

**Comment by ryanfrancesconi** [comment]
I don't know if the Leaks screenshot is helpful or not, but here's what I see there in a very short run of my app instantiating and deleting a few objects. It seems like Apple's frameworks also show up as Leaks so I don't know exactly what to think. I'm new to even looking at this Instruments app so I don't know what to expect there.

![image](https://cloud.githubusercontent.com/assets/2917795/21913293/669df244-d8e0-11e6-8b5b-3c642e53fb13.png)

**Comment by PaulBatchelor** [comment]
the initial stack trace posted ends with a call to sp_create. A memory leak there would indicate that sp_destroy isn't being called at cleanup.

**Comment by aure** [comment]
So, for the record, my idea about what is wrong here is a long standing thing with AudioKit / Audio Units v3.  Basically, there's a stage in which you create the audio unit, but we're usually ending up with two, one that works and one that just doesn't go away / isn't ever used.  It hasn't seemed to affect things too negatively yet, so it hasn't been a priority.   But perhaps now is the time.

**Comment by kowongh** [comment]
The weird thing was in the initial stack trace, it did seem to call sp_destroy when I was deiniting the class that held the units and it was freeing up the memory... But the fact that there are two audio units being created makes sense...

Is this the line?

>         AVAudioUnit.instantiate(with: _Self.ComponentDescription, options: []) {
>             avAudioUnit, error in
> 
>             guard let avAudioUnitEffect = avAudioUnit else { return }
> 
>             self.avAudioNode = avAudioUnitEffect
>             self.internalAU = avAudioUnitEffect.auAudioUnit as? AKAudioUnitType
> 
>             AudioKit.engine.attach(self.avAudioNode)
>             input.addConnectionPoint(self)
>         }

**Comment by ryanfrancesconi** [comment]
So this is only with some of the Audio Units though, or is it for all of them? For example, I don't see this behavior in the AKTimePitch class - it is deallocated. I haven't yet tested too many of the effects, but have noticed it in particular with the AKAmplitudeTracker. Do you mean any of the AudioKit nodes that also use embedded C code in them?

For me, I'm developing a desktop application where performance is key, not an iOS app - so anything hanging around after I want to get rid of it is a bit worrying.

**Comment by ryanfrancesconi** [comment]
I'm also allocating up to thousands of AudioKit objects over the lifecycle of a session.

**Comment by aure** [comment]
It's only for nodes that employ AUv3.  Anything with a DSP kernel.  AKTimePitch is just a wrapper around Apple's time stretcher, so it handles its own lifecycle. If you're up for the challenge of figuring out this memory leak, we can certainly use the help!  Thanks!

**Comment by kowongh** [comment]
I'm also using a lot of effects nodes so this adds just to hundreds of leaks and confirm the leak with AKAmplitudeEnvelope. Ryan and I are up for the challenge, but no guarantees :P 

I'm not that versed with C as much as ObjC or Swift, but I'd love to try to contribute to this amazing project.

What are the two audio units being initialized? Are you saying that AVAudioUnit and AVAudioNode are the two AudioUnits? I'm not seeing where the two audio units are being created...

>         self.avAudioNode = avAudioUnitEffect
>         self.internalAU = avAudioUnitEffect.auAudioUnit as? AKAudioUnitType
> 

Or are you saying that the dsp _kernel is the second audio unit? 

Inside the .mm files for AUAudioUnit subclass there is

```
- (instancetype)initWithComponentDescription:(AudioComponentDescription)componentDescription
                                     options:(AudioComponentInstantiationOptions)options
                                       error:(NSError **)outError {
    self = [super initWithComponentDescription:componentDescription options:options error:outError];

    if (self == nil) {
        return nil;
    }

    // Initialize a default format for the busses.
    AVAudioFormat *defaultFormat = [[AVAudioFormat alloc] initStandardFormatWithSampleRate:AKSettings.sampleRate
                                                                                  channels:AKSettings.numberOfChannels];

    // Create a DSP kernel to handle the signal processing.
    _kernel.init(defaultFormat.channelCount, defaultFormat.sampleRate);

```
is the _kernel the second "AudioUnit"? This would make sense because AVAudioFormat seems to be leaking consistently on that line.

**Comment by ryanfrancesconi** [comment]
I'll do what I can though my C skills are very rusty.
Soon I'll create a very simple project to test this with.

**Comment by ryanfrancesconi** [comment]
Hi guys, I finally had a bit of time tonight to look closer at the issue. It's actually a very simple bug in the swift code. In the closures self is a strong reference so this creates a retain cycle. All that needs to be done is to use a weak reference to it like this:

```
        AVAudioUnit._instantiate(with: _Self.ComponentDescription) { [weak self]
            avAudioUnit in

            self?.avAudioNode = avAudioUnit
            self?.internalAU = avAudioUnit.auAudioUnit as? AKAudioUnitType

            input.addConnectionPoint(self!)
        }
```

Aure, I'll go through all the AUv3 classes and make the fixes. Will send you a pull request when done!
Ryan

**Comment by ryanfrancesconi** [comment]
Note these strong self references in closures may be in other places in the AudioKit code besides these v3 classes, so keep an eye out for them!

**Comment by ryanfrancesconi** [comment]
Aure,
I'm wondering about the following Dispatch block:
`        token = tree.token (byAddingParameterObserver: { [weak self]
            address, value in

            DispatchQueue.main.async {
                if address == self?.halfPowerPointParameter!.address {
                    self?.halfPowerPoint = Double(value)
                }
            }
        })`

Specifically, does that DispatchQueue really need to be in there? I think it's possible in certain situations that by the time the code is executed on the main thread the reference to self could be gone.

**Comment by aure** [comment]
Fixed by https://github.com/audiokit/AudioKit/pull/697
