### ISSUE TITLE
OutputPlot + FFTPlot

### ISSUE THREAD

**Issue by Patak123** [audiokit/AudioKit#689]
Hello :-)

I'm trying to get an OutputPlot & a FFTPlot from the same oscillator.

```
let oscillator = AKOscillator();

AudioKit.output = oscillator;
AudioKit.start();

oscillator.start();

let plot1 = AKNodeOutputPlot(oscillator, frame: firstView.bounds);
firstView.addSubview(plot1);

let plot2 = AKNodeFFTPlot(oscillator, frame: secondView.bounds);
secondView.addSubview(plot2);
```

But I get this error :

`ERROR:    >avae> AVAudioNode.mm:565: CreateRecordingTap: required condition is false: _recordingTap == nil`

Do you know why ?
Thanks and have a nice day :)

**Comment by aure** [comment]
Have you tried adding in a do nothing mixer like:

secondTappingSpot = AKMixer(oscillator)

and then have plot2 connect to that instead of oscillator?

**Comment by Patak123** [comment]
Indeed, it works !

But still, I think I should be able to use them both on the same audio node :)

**Comment by aure** [comment]
There's only support for one tap per node, perhaps we can do a better job of documenting that.  You could make your own custom grapher that uses one tap to supply the data to both plots.

**Comment by Patak123** [comment]
Yes, I will, thank you for your valuable time :)
