### ISSUE TITLE
How to store amplitude values into a variable?

### ISSUE THREAD

**Issue by tangert** [audiokit/AudioKit#690]
I'm trying to store a series of AKMicrophone's amplitude and frequency values into an array but there doesn't seem to be a delegate method that supports this sort of tracking. Does anyone know how to do this? EZMicrophone has a delegate method so I'm pretty confused.

**Comment by aure** [comment]
Microphone doesn't have frequency or amplitude.  There's an AKFrequencyTracker and an AKAmpliutdeTracker that probably will do what you need.
