### ISSUE TITLE
AKNodeRecorder creates corrupted audio file on Mac OS X Cocoa Application 

### ISSUE THREAD

**Issue by curtdissel** [audiokit/AudioKit#693]
Firstly, thanks for making this.
I made a recorder as best as I could following the iOS recorder example. Things are much easier on iOS than Desktop applications. When I close my application the  .m4a file is about 64kb and quicktime can't play it. I attached a code snippet. I just create an AKAudioFile, mic, recorder and whatnot. start recording, and then 5 for seconds. once that is done I close everything and check the file. The file does grow, but I can't open it for some reason. AVAudioFile gave me much trouble various settings crashed everything because this or that was not valid. so maybe that is a place to start. Also if an OS X sample does exist, please share it. The Examples in the project do not show how to take microphone audio and turn it into an actual .m4a or other sound type. Thanks. Sorry that I don't know how to color the code text.

I also made one change to: AKAudioNodeRecorder.swift's
    public init(node: AKNode = AudioKit.output!,
                file: AKAudioFile? = nil);
to stop it from crashing whenever could not find my: file!.processingFormat.settings

Change I made:

            do {
                // We initialize AKAudioFile for writing (and check that we can write to)
                self.internalAudioFile = file!
            } catch let error as NSError {
                print("AKNodeRecorder Error: cannot write to \(file!.fileNamePlusExtension)")
                throw error
            }

View controller's recorder code.

`
    var mic: AKMicrophone!
    var tracker: AKFrequencyTracker!
    var silence: AKBooster!
    var audioFile:AKAudioFile?
    var recorder: AKNodeRecorder?
    var micBooster: AKBooster?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        mic = AKMicrophone()
        
        let micMixer = AKMixer(mic)
        micBooster = AKBooster(micMixer)
        
        // Will set the level of microphone monitoring
        micBooster!.gain = 0
        
        AudioKit.output = mic
        AudioKit.start()

        do{
            let url = URL(fileURLWithPath: "\(NSHomeDirectory())/Documents/test.m4a")
            try audioFile = AKAudioFile(forWriting: url, settings: [AVFormatIDKey : NSNumber(value: kAudioFormatMPEG4AAC), AVNumberOfChannelsKey : NSNumber(value:2), AVSampleRateKey : NSNumber(value:44100.0)] )
            try recorder = AKNodeRecorder(node: mic, file: audioFile)
            mic.start()
            try recorder?.record()
            
            sleep(5)
            
            recorder?.stop()
            mic.stop()
            print("done")
            
        } catch {
            print("Error: \(error)")
        }
        AudioKit.stop()
        
    }

`

**Comment by aure** [comment]
Hi, just wanted to comment on this to let you know we're working on fixes to AKAudioFile and we'll definitely port the Recorder example to OSX as a way to test for this problem.  Hopefully this week, though we are all at NAMM, I think we'll find some time to code as well.

**Comment by laurentVeliscek** [comment]
Hi,

Do you really need to record in MP4 format (not recommended) ?

I'm not even sure it is possible to record into a compressed format using
an avAudioNode.

Default values when when creating an AKAudioFile using a convenience init,
just setting a basedir and a name should create a .caf audiofile what will
record in 32 float PCM (much more recommended).

You can use later AudioKit facilities to convert the recorded file  into
M4A or WAV or AIFF if you wish to.

Hope this will help.

Best,

Laurent.


2017-01-18 9:06 GMT+01:00 Aurelius Prochazka <notifications@github.com>:

**Comment by curtdissel** [comment]
Thanks for the replies you two.  @laurentVeliscek I currently record as m4a or .mp4 and then convert to .wav to pipe the resulting file into a program that expects .wav. The only reason i chose the .mp4 is because I get various issues relating to the format settings whenever I try anything else. I thought Apple made if difficult to produce .wav files with their api. @aure  Thanks for taking the time to port the iOS microphone project to an OS X cocoa project.  On a side note, if i wanted to detect whether someone was speaking, would i check the frequency value or something else to do the comparison? I desire to stop recording once no sound is detected for 2 or 3 seconds. Thanks all.

**Comment by laurentVeliscek** [comment]
Hi again, when I worked on AKnodeRecorder and AKAudioFile; I got some
strange bugs too, when trying to record to wav files.

That's why I choosed to set the default file format of AKAudioFile is set
to .CAF.

But I only tested with iOs.

To detect silence, AKAmplitudetracker is your friend !

Best;

laurent.

2017-01-18 16:41 GMT+01:00 curtdissel <notifications@github.com>:

**Comment by curtdissel** [comment]
Hi @laurentVeliscek Could you provide me with the sample AKAudioFile that you used? I am mainly interested in the settings parameter. I tried various parameters for settings and they usually ended with the program crashing or corrupt wave files. I think on iOS you don't have to set the settings parameter which makes life a lot easier. Thanks for sharing the AKAmplitudetracker

`
            try audioFile = AKAudioFile(forWriting: URL(fileURLWithPath: "\(NSHomeDirectory())/Documents/test.m4a"), settings: AKSettings.audioFormat.settings)
`

**Comment by ryanfrancesconi** [comment]
In my project on OS X I found that I had to record to a 32 bit CAF file, then convert it after. Recording to a wave file didn't work for me either.

**Comment by ryanfrancesconi** [comment]
after record completion:
nodeRecorder.audioFile!.exportAsynchronously(name: url!.lastPathComponent, baseDir: .custom, exportFormat: fileFormat, callback: handleExportComplete)

I added the .custom base directory type for this situation on OS X.

**Comment by aure** [comment]
I think this might also be fixed by the change I just committed. Can someone check and reopen the issue if necessary?
