### ISSUE TITLE
RecorderDemo (iOS) on device produces very low volume playback

### ISSUE THREAD

**Issue by kharmabum** [audiokit/AudioKit#695]
On simulator, everything works as expected; but when running on a device the playback is heavily muted.

**Comment by aure** [comment]
I bet its coming out of the ringtone speaker, not the actual speakers.

**Comment by aure** [comment]
The earpiece is a speaker as well. Is it coming out of that?  I looked at your example project code and its definitely a style I haven't seen implemented before.  The core team and I are at NAMM this week and I'll try to have a couple of us look at this issue, and the other similar ones.

**Comment by kharmabum** [comment]
@aure ah yes indeed it is coming out of the earpiece.

**Comment by aure** [comment]
I think was already addressed:

https://github.com/audiokit/AudioKit/issues/662

do {
            
    //  try AKSettings.setSession(category: .playAndRecord, with:  AVAudioSessionCategoryOptions.defaultToSpeaker)
            
    let session = AVAudioSession.sharedInstance()
    try session.setCategory(AVAudioSessionCategoryPlayAndRecord)

    if !AKSettings.headPhonesPlugged {
        try session.overrideOutputAudioPort(AVAudioSessionPortOverride.speaker)
     }
} catch {
    print("Errored setting category.")
}
