### ISSUE TITLE
iphone 7 plus first time initialize problem

### ISSUE THREAD

**Issue by berkankisaoglu** [audiokit/AudioKit#698]
Having the below configuration, I wasn't able to read any data from the `AKFrequencyTracker` on iPhone 7 plus devices. (simulator is fine). 

```
        AKSettings.bufferLength = .medium
        AKSettings.audioInputEnabled = true
        AKSettings.numberOfChannels = 1
        AKSettings.sampleRate = 44100 / 4
        
        do {
            try AKSettings.setSession(category: .playAndRecord, with: .defaultToSpeaker)
        } catch { print("Unable to prepare for recording") }

        mic = AKMicrophone()
        mic.volume = 80
        
        micMixer = AKMixer(mic)
        tracker = AKFrequencyTracker.init(micMixer)
        
        micBooster = AKBooster(tracker)
        micBooster!.gain = 0
        
        let recordFile = try! AKAudioFile(forWriting: someURL, settings: AKSettings.audioFormat.settings, commonFormat: .pcmFormatInt16, interleaved: true)
        recorder = try! AKNodeRecorder(node: micMixer, file: recordFile)
        
        AudioKit.output = micBooster
        AudioKit.start()
```

At any random time, if I try to read the data on `tracker.amplitude` or `tracker.frequency` it gives me `0`. 

To fix it, I need to change the last above to 

```
        ...
        AudioKit.start()
        AudioKit.stop()
        AudioKit.start()
```

Basically, `AudioKit.stop()` seems to do something internally and then I was able to read tracker data. What's weird is that it only happens on certain devices. 
Any love here?

**Comment by aure** [comment]
That's pretty weird.  Thanks for reporting, I'll try to reproduce and fix.  Lots of love!

**Comment by aure** [comment]
What happens when you move the recorder =  line after the AudioKit.start() line?

**Comment by berkankisaoglu** [comment]
Didn't help. Have you been able to reproduce or just going instinctively?

**Comment by aure** [comment]
Hi, we were at NAMM over the weekend so I was just reading your code, not testing it, will do so this week.

**Comment by aure** [comment]
Just to speed things along, any way you can share your project with me so I can run your exact same code (and not have to set up my own project)?

**Comment by berkankisaoglu** [comment]
Sure thing, give me a sec

**Comment by aure** [comment]
I'm thinking this will be fixed by https://github.com/audiokit/AudioKit/commit/6943bf32cd7a94b34f51ab82b4ee3683a782325a 
on the develop branch.
