### ISSUE TITLE
All OS X examples crash on launch

### ISSUE THREAD

**Issue by Nikolozi** [audiokit/AudioKit#70]
I tried all 4 OS X example apps. When I try to run them they all crash at the following line

int ret = csoundCompile(cs, 5, argv);

It's inside - (void)runCsound:(NSString *)csdFilePath method. Compiler gives EXC_BAD_ACCESS. When I hover over cs and argv they are both non-nil. So, I'm not sure why it's crashing.

I'm running Xcode 6.1.1 on Yosemite 10.10.1.

Up until now I've been playing with iOS example code only. I'll try to create an OS X app following the tutorial on AudioKit.io page to see if I can find out why it's crashing.

**Comment by Nikolozi** [comment]
Hi Aure,

Thanks for the quick response. The funniest thing happened to me just now. As I was writing the response, describing that I don't use audio interface and don't have any drivers installed, it hit me that I have Apogee's MiC connected to my iMac via USB. I thought I'd disconnect it and see if it solves anything. Sure enough, the Mac examples started working. As soon as I connect it back they stop working.

I wonder if the example apps automatically pick the MiC as an audio interface to output sound and fail obviously since it doesn't support audio output? And as a follow up question, is there a facility in AudioKit to choose an output device if multiple audio interfaces are connected to a mac?

Cheers
Niko

**Comment by aure** [comment]
Yeah, that's interesting.  I can try with my USB mic here.  I want to close this issue because the name of the issue might scare people off.  You can open a new issue with the USB mic question if you like, or else I'll just look into it and contact you directly.

**Comment by Nikolozi** [comment]
Good idea regarding closing the issue. It's not something I need resolved right now. I can simply disconnect the MiC when I'm working with AudioKit stuff. If I ever need it resolved I'll re-open it as a separate issue.

Cheers
Niko

**Comment by gritd** [comment]
I think it has something to do with multiple sound cards and cSound selecting the wrong default, I looked up the correct outputs in the csoundQT tool and added -i and -o arguments like this in the line above the error:
char *argv[5] = { "csound", "-+ignore_csopts=0",
            "-+rtaudio=coreaudio -i=adc0 -o=dac0","-b256", (char*)[csdFilePath
                                                    cStringUsingEncoding:NSASCIIStringEncoding]};

(adc0 for microphone input and dac0 for built-in output in my case)
All is now working perfectly.
