### ISSUE TITLE
AKAudioFile: reverse playback

### ISSUE THREAD

**Issue by ryanfrancesconi** [audiokit/AudioKit#704]
AKAudioFile.reverseAsynchronously()
AKAudioFile.reversed()

These both just create empty data for me. I am only testing on OS X.

Additionally the whole BaseDirectory concept isn't too friendly for OS X apps. We need to implement the .custom type if the BaseDirectory is going to be required. I personally would rather just see it gone completely, but I'm not working on iOS! 

I have added reverse playback to AKAudioPlayer though!

Thanks!
Ryan

**Comment by aure** [comment]
Thanks for your pull request and yeah, lets get to the bottom of the OSX AKAudioFile insanity.

**Comment by aure** [comment]
Hey Ryan, these both seem to be working for me on macOS.  I'll close this issue for now (trying to clean up the issues page) but hit me up on slack if you want to go over it together.

**Comment by ryanfrancesconi** [comment]
Hmm - weird. Alright! Glad it worked for you. Unsure at this point what the issue was for me.
