### ISSUE TITLE
No callback capability in metronome?

### ISSUE THREAD

**Issue by justbane** [audiokit/AudioKit#710]
Sorry if this is known and I can't find it - there must be a way to receive a callback fire or event fire when the metronome fires a click... Anyone making a metronome would want to visually indicate the tempo with a blink or a number of some sort.

I am using the standard playground example and can not find a decent way to recieve or fire a function based on when the met fires.

**Comment by aure** [comment]
What metronome are you speaking of?

**Comment by aure** [comment]
Yeah, so the metronome maybe has a bad name.  It's really just a periodic trigger for sound design.  If I were to make a full scale metronome app, I think I might just use the midi functionality.  That has callbacks as well so you can have a UI.  People have successful made traditional metronomes with AudioKit though: http://audiokit.io/blog/2016/10/30/treble/
