### ISSUE TITLE
Noise happened when audio file playback in v3.5.1.

### ISSUE THREAD

**Issue by kentny** [audiokit/AudioKit#713]
My project uses several effectors, AKReverb and AKPinkNoise to apply them to local audio file playback with AKAudioPlayer. After I updated AudioKit from v3.5 to v3.5.1, big noise sound happened. I cannot hear the playback sound anymore due to this big noise sound.
 This noise issue was never happened in v3.5.
 My iPhone iOS version is 10.2.

Following is a part of code in my project.
```
self.player = try！ AKAudioPlayer(file: file)
self.reverb = AKReverb(self.player, dryWetMix: 0)
self.pinkNoise = AKPinkNoise(amplitude: 0)
let mix = AKMixer(self.reverb, self.pinkNoise)
AudioKit.output = mix!
AudioKit.start()
```

When playback starts, following play() method is called.
```
func play() {
  self.reverb.start()
  self.pinkNoise.start()
  self.player.play(from: currentTime, to: duration)
}
```

Then, noise happens.
Could you give any advise ?

**Comment by aure** [comment]
Quick fix, go back to 3.5.  :)  But thanks for the issue and the walkthrough for reproducing the issue.  I haven't had time to do so yet but I will soon.

**Comment by ryanfrancesconi** [comment]
I tried this code and it is working as expected in the latest dev. AudioKit on OS X.

**Comment by aure** [comment]
This works perfectly me on the develop branch for AudioKit on iOS so I am going to assume whatever it was has been addressed.

**Comment by ryanfrancesconi** [comment]
It's quite possible this was the AKAudioPlayer pause bug I fixed recently - unrelated to his signal chain.
 
 
-----Original Message-----
