### ISSUE TITLE
Analyzing Speaker Output

### ISSUE THREAD

**Issue by grantgumina** [audiokit/AudioKit#717]
Sorry if this is a silly question, but I've reviewed these two issues (#546 and #632) hoping they'd help me out here, but I haven't had any luck.

I'm trying to analyze the output coming from the speakers on a device (specifically MacOS right now) just like I'd analyze the input coming from the microphone as shown in this AudioKit playground http://audiokit.io/examples/MicrophoneAnalysis/

I'm expecting the code to take the sound coming from my speakers (for example from Spotify) and treat that the same as microphone input, but it's actually just analyzing the microphone input despite setting the mic's input as the speaker output.

```
import Cocoa
import AudioKit

class ViewController: NSViewController {

    @IBOutlet weak var infoLabel: NSTextField!
    var tracker: AKFrequencyTracker!
    var timer = Timer()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        timer = Timer.scheduledTimer(timeInterval: 1, target: self, selector: #selector(self.measureFrequency), userInfo: nil, repeats: true)

        let mic = AKMicrophone()
        
        if let aos = AudioKit.availableOutputs {
            for ao in aos {
                print(ao)
            }
        }

        do {
            try mic.setDevice(AudioKit.availableOutputs![0])
        } catch let error {
            print("ERROR")
            print(error)
        }
        
        tracker = AKFrequencyTracker.init(mic, hopSize: 200, peakCount: 2000)
        let silence = AKBooster(tracker, gain: 0)
        AudioKit.output = silence
        AudioKit.start()
        
    }

    override var representedObject: Any? {
        didSet {
        }
    }
    
    func measureFrequency() {
        infoLabel.stringValue = "\(tracker.frequency)"
    }

}
```

Thanks for any tips you might have!

**Comment by aure** [comment]
I admire your creativity but AudioKit's output, even though it also comes from the speakers, is not related to the output of other apps.  As far as I know you can't access other apps output unless they are doing Inter-App Audio or Audiobus, which Spotify does not.
