### ISSUE TITLE
Exporting From Engine with Effects 

### ISSUE THREAD

**Issue by lmick002** [audiokit/AudioKit#720]
I have chain thats connected like : 
 AKAudioFile -> Delay -> Reverb -> Engine. 

What would be the best way to export the final file with the delay and reverb processing with AudioKit? Ive tested exporting from the AKAudioFile, but that would just return would just return the dry file. Thanks for your help in Advance.

**Comment by ryanfrancesconi** [comment]
Run it through an AKAudioPlayer, then use the AKNodeRecorder on the final AudioKit.output to record to file.

There isn't any non-realtime export yet.

**Comment by ryanfrancesconi** [comment]
Btw, this isn't an issue - this is a question, so it's better to ask it in the AudioKit google group: https://groups.google.com/forum/#!forum/audiokit
