### ISSUE TITLE
AKKeyboard is not yet multi-touch

### ISSUE THREAD

**Issue by aure** [audiokit/AudioKit#727]
AKKeyboard, designed for playgrounds, works well for that purpose but should be extended as an all purpose keyboard with multi-touch and skinning.  Granted, this is a bit of a feature request, but at least the multi-touch part is an issue.

**Comment by crashingbooth** [comment]
Hi, I've never contributed before, but I came across this issue and realized I have an almost ready-made multi-touch solution. I made a little keyboard similar to AKKeyboardView with mono/poly modes a few months back.  I think it would be almost trivial to just insert my touch logic (with minor changes) into AKKeyboard.
If work has already started on this, then never mind.  But if it would help, I could do this shortly.
Jeff

**Comment by aure** [comment]
@crashingbooth It's been on my mind, but not much has been done.  I'd love to have your help with this.  Thanks in advance!

**Comment by aure** [comment]
@crashingbooth Also, I should state that if you want to replace all my code with yours, that's fine.  Or they can live side by side.  Is your keyboard based on bitmap images of keys or vector?  Mine are all vector drawn, so unless they can be combined into one awesome class, we could have separate bitmap oriented and vector oriented keyboards. Basically I'm just happy for some collaboration and perhaps there can be some back and forth once you submit yours.  Looking forward to it. If you'd like to be added to AudioKit's slack, just email me aure at audiokit dot io.

**Comment by aure** [comment]
Oh wow, you're way ahead of the game.  This will be great.  Thanks again.

**Comment by aure** [comment]
Fixed by https://github.com/audiokit/AudioKit/pull/759 and even if it requires further development, I don't think it needs to be a Github issue, Jeff and I can be in charge. :)
