### ISSUE TITLE
AKBandPassFilter bug

### ISSUE THREAD

**Issue by masaldana2** [audiokit/AudioKit#728]
Hello 
I think AKBandPassFilter() doesn't work
it worked with 3.5.0
I try:

`do{
        try sampler.loadWav("FM Piano")
        }catch{
            print("err")
        }
        var bandPass2 = AKBandPassFilter(sampler)
       AudioKit.output = bandPass2
        AudioKit.start()`

> 2017-02-05 14:04:09.280034 beatmaker fix[4009:1684185] [central] 54:   ERROR:    [0x1ae547c40] >avae> AVAudioEngine.mm:283: AttachNode: required condition is false: !nodeimpl->HasEngineImpl()
2017-02-05 14:04:09.280697 beatmaker fix[4009:1684185] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: !nodeimpl->HasEngineImpl()'
*** First throw call stack:
(0x1896f91b8 0x18813055c 0x1896f908c 0x1a2b34300 0x1a2bb371c 0x1a2bb353c 0x10036f454 0x10035a898 0x10035ab90 0x10007c054 0x100079828 0x1000797f0 0x101225218 0x101226048 0x1000798d0 0x100079484 0x100079594 0x18faaa308 0x18fbf3f14 0x18fbf3c5c 0x18faa9fac 0x18fbf3f14 0x18fbf4088 0x18fbf3c5c 0x18faa92ac 0x18fd5cae4 0x18f830a90 0x18f619320 0x18f82f6e8 0x18f844104 0x18f82c7ec 0x18b2cf92c 0x18b2cf798 0x18b2cfb40 0x1896a6b5c 0x1896a64a4 0x1896a40a4 0x1895d22b8 0x18f6127b0 0x18f60d534 0x100080480 0x1885b55b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

if i try var bandPass = AKBandPassButterworthFilter(sampler)
it works 
audiokit 3.5.2

**Comment by aure** [comment]
This filter is removed in the develop branch as discussed here https://github.com/audiokit/AudioKit/commit/859f003dee3098274938a7530407d1f69deb4353
