### ISSUE TITLE
Widen detuningMultiplier to more octaves

### ISSUE THREAD

**Issue by dennisvennink** [audiokit/AudioKit#729]
`detuningMultiplier` currently internally clamps to one octave. Most synthesizers have a range control that can detune an oscillator to more than one octave.

Would it be possible to widen the range of `detuningMultiplier` (without any loss in sound quality)?

**Comment by aure** [comment]
Yeah, this is very easy.  What do you think is a good octave range?  How about +/- 10?  Effectively full range.

**Comment by dennisvennink** [comment]
-/+ 10 octaves is perfect!

Do you want me to work on it and send in a pull request?

**Comment by aure** [comment]
If you can, that would be great. Just look for clamps that instead of clamping 0.5 to 2.0 should clamp 0.1 to 10.  Also if there are comments that need updating, that would be good too.  Otherwise I can do it in the next couple of days.

**Comment by aure** [comment]
Sorry, that was wrong advice.  the range would be 1/2^10 to 2^10. or 0.0009765625 to 1024.  might as well just use 0.0001 to 1000.

**Comment by dennisvennink** [comment]
Why are we clamping in the first place?

**Comment by aure** [comment]
Good point, might as well not clamp at all.

**Comment by aure** [comment]
@dennisvennink  Shall I do this on February 9th or is a pull request imminent?

**Comment by dennisvennink** [comment]
@aure Hopefully I'll have a pull request ready within the hour.

**Comment by aure** [comment]
Dennis fixes his own issue ftw. https://github.com/audiokit/AudioKit/commit/615d0e07bcb7874e084ff44c6b4d13182cb13e0f
