### ISSUE TITLE
Create a waveform from AKAudioFile

### ISSUE THREAD

**Issue by olivierlesnicki** [audiokit/AudioKit#730]
Is there a synchronous method to create a WaveForm view from an AKAudioFile (without having to play it)?

**Comment by ryanfrancesconi** [comment]
This is currently in EZAudioFile / EZAudioPlot, an older API embedded in AudioKit. Note - this is a question, not an issue. So, you can ask this in the forum: https://groups.google.com/forum/#!forum/audiokit

let waveform = EZAudioPlot()
let data:EZAudioFloatData = file.getWaveformData()
waveform.updateBuffer( data.buffers[0], withBufferSize: data.bufferSize )

**Comment by aure** [comment]
Thanks @ryanfrancesconi

**Comment by olivierlesnicki** [comment]
Good enough answer! :)

**Comment by olivierlesnicki** [comment]
```swift
// file being an AKAudioFile
let plot = EZAudioPlot()
let ezFile = EZAudioFile(url: URL(fileURLWithPath: file.url.absoluteString))
let data = ezFile?.getWaveformData()

plot.updateBuffer(data?.buffers[0], withBufferSize: (data?.bufferSize)!)
```

**Comment by ryanfrancesconi** [comment]
are you asking if that is correct?

**Comment by olivierlesnicki** [comment]
@ryanfrancesconi no, I'm just showing the code I ended up using for future reference - the thing you forgot to mention in your answer is that a EZAudioFile needed to be created. AKAudioFile doesn't have the method .getWaveformData()

**Comment by ryanfrancesconi** [comment]
yes, i know. i was just giving you the basic idea. You should verify that your optionals aren't nil before proceeding in your code there.
