### ISSUE TITLE
Installation instructions via cocoapods do not work when submitting to the app store. 

### ISSUE THREAD

**Issue by adamdahan** [audiokit/AudioKit#731]
The instructions for linking against 3.5 for cocoapods are good for testing but this is not the case when trying to compile and submit your app to the app store. 

pod 'AudioKit', '~> 3.5' 

**Causes this issue on iTunes:** 
Invalid signature. Code object is not signed at all. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level. Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a simulator target.

I have gone through closed issues and found issues relating to this where your recommendation is to use the develop branch to resolve this issue. 

^^^ Should not be considered a fix. 

It would be nice if you guys gave some proper instructions on how to include the framework in your app in such a way that satisfies itunes / application loader. 

As of now - about 3 days no luck. Such a disaster.

**Comment by adamdahan** [comment]
All my certificates etc are kosher. So no need to suggest that is the mistake.

**Comment by olivierlesnicki** [comment]
@adamdahan how did you solve it?

**Comment by adamdahan** [comment]
@oliviernicki

1. Download the master branch as a zip
2. In this repo under frameworks/INSTALL.md follow the compile from source instructions
3. Go to build settings and type in bitcode
4. Set enable bitcode to NO

Then archive and voila! 

Let me know if you need further help - best.

**Comment by adamdahan** [comment]
@oliviernicki using cocoapods or simply embedding as framework will not work to submit to iTunes even if you add the run script build phase they suggest. So specifically dont follow step 1 or 2 in INSTALL.md.
