### ISSUE TITLE
Drag-drop installation doesn't seem to work

### ISSUE THREAD

**Issue by jconst** [audiokit/AudioKit#734]
I'm on Xcode 8.2.1, trying to install AudioKit 8.5.2 for iOS. Following the instructional video on http://audiokit.io/downloads/, Xcode still seems unable to recognize the framework. Here's a short (<1 min) video of what I tried: https://www.dropbox.com/s/e44ilqdpwufxmd9/Install.mov?dl=0

I also tried making a bridging header and importing <AudioKit/AudioKit.h> in it, which didn't solve the problem. I am able to install using Cocoapods, though.

**Comment by aure** [comment]
I don't think the framework search path gets set up when you do it like that.  If you'd like I'm happy to get you rolling via a screenshare.

**Comment by jconst** [comment]
Thanks, I actually got it working, so no need for a screenshare. It looks like your call on the framework search paths was right, because checking the "Copy items if needed" box when importing the framework solved the issue.

Shouldn't the docs / video / something on audiokit.io/downloads mention this, though, so other people don't have the same issue? I was just following the video exactly so I would guess it might be a common problem.
