### ISSUE TITLE
AudioKit.start() crash

### ISSUE THREAD

**Issue by dkun7944** [audiokit/AudioKit#735]
Hi there,

Getting a lot of crashes when I call AudioKit.start() upon opening my app. The weird thing is that it doesn't crash every single time, most of the time it appears to be working perfectly. It's affecting 6% of my app's users and I can't replicate it. It's spread out pretty evenly across all devices and iOS versions so it's not a device specific or OS specific thing.

[Here is the file in question in the project (you can clone and run the project) ](https://github.com/dkun7944/pitch-ios/blob/master/Pitch/SoundGenerator.swift)

The crash is occurring at line 32 when I call AudioKit.start():
 
        self.mixer = AKMixer(tuner.silence)

        bank = AKOscillatorBank(waveform: AKTable(.triangle), attackDuration: 0.06, releaseDuration: 0.06)
        mixer.connect(bank)
        
        AudioKit.output = mixer
        try! AKSettings.session.overrideOutputAudioPort(AVAudioSessionPortOverride.speaker)
        AudioKit.start() --- CRASH

This method is only called once when the user opens the app.

Stack trace:

[com.danielkuntz.pitchtuner_issue_9_crash_ebfaf35c1f82427d84ac5fb7086e6228_edee4442519f4755ba14518d373a3033_0_v1 (1).txt](https://github.com/audiokit/AudioKit/files/762558/com.danielkuntz.pitchtuner_issue_9_crash_ebfaf35c1f82427d84ac5fb7086e6228_edee4442519f4755ba14518d373a3033_0_v1.1.txt)

**Comment by megastep** [comment]
I have been getting some rather similar crash reports from users of my own AudioKit app. I wonder if this might be explained by audio session types and the user's particular configuration.

**Comment by aure** [comment]
@dkun7944 We saw that Apple featured your app in the "New apps we love" category.  Congratulations!  I hope it translates to a lot of downloads.  I do believe these bugs are related to session management.  What version of AudioKit is your app using?  If its on 3.5.2 I'd definitely recommend updating to 3.5.3.

**Comment by dkun7944** [comment]
@aure Thanks! I believe I'm on 3.5.2. I'll try updating to 3.5.3 and let you know if that clears things up.

**Comment by dkun7944** [comment]
@megastep Glad to know I'm not the only one with this issue. I'll let you know what happens after updating to 3.5.3

**Comment by megastep** [comment]
FYI my own crashes look like this: http://crashes.to/s/952f9695c5a

I see that you are also using Crashlytics so maybe you can compare with the error codes from the exceptions.

**Comment by dkun7944** [comment]
@megastep I'm getting error code 561017449.

http://crashes.to/s/f3a95c95692

**Comment by swiftcodex** [comment]
@dkun7944, congrats on the Apple love. And, it was super cool of you to upload your code to Github so others can learn from it. You should join the AudioKit slack. We're cheering you on there.

**Comment by megastep** [comment]
@dkun7944 That's code for AVAudioSessionErrorInsufficientPriority, FYI

**Comment by dkun7944** [comment]
@megastep thanks. That's a step in the right direction.

@swiftcodex Thanks! I learned a lot from open sourced iPhone apps in my early programming days so I thought I'd give back. How do I join the slack channel?

**Comment by aure** [comment]
@dkun7944 Just drop me an email and I'll add you to our slack group.

**Comment by dkun7944** [comment]
@aure Done.

In regards to the error code, I understand it means that the category AudioKit is trying to set is already being used by another app. 

How should I work around this since the code for setting the category is being called within the AudioKit framework? Should I set the category manually at first in a try-catch block and then do AudioKit.start()?

**Comment by aure** [comment]
It would be awesome if you could, for the purposes of the good of all, build your changes into the framework.  It would mean not useing the framework file and instead building with an embedded AudioKit for iOS.xcodeproj.  Once you got it working, then it could be compiled and you could go back to using the framework.  

If it makes sense, to close this issue and start a new one, please do.  Long issue-based discussions that go off the initial issue are not so good for new users looking through the archives for previously solved issues.  Thanks!

**Comment by aure** [comment]
Also "AudioKit.start() crash" is just a scary title. :)

**Comment by dkun7944** [comment]
@aure Ok, sounds good.
