### ISSUE TITLE
Mic to Speaker.?

### ISSUE THREAD

**Issue by davut5** [audiokit/AudioKit#738]
i am using your MICROPHONE ANALYSIS... i want to add only 1 properties.   Hear my voice from speaker at the same time. is it possible?

i want to set output to speaker.

**Comment by aure** [comment]
The mic was purposely silenced in this project.  Simply unsilence it onl ine 43 of the view controller.

**Comment by davut5** [comment]
oh ok thanks..:) working now.   i want to hear the smallest frequnecy sounds.
Which frequency do I need to set? and which line to edit 👍
