### ISSUE TITLE
Xcode weirdness when using AudioKit as a framework

### ISSUE THREAD

**Issue by aure** [audiokit/AudioKit#743]
Need to get to the bottom of why Xcode is giving a lot of "not found" errors and not doing proper code completion when the framework is used.  Things do compile, but you're coding blind until then.  You have to use the AudioKit xcodeproj to get proper code completion, but this is new as of Xcode 8.2 or so.

**Comment by megastep** [comment]
I had narrowed this down to the compiled architectures included in the framework. We don't include an armv7s slice in them (mostly because it's obsolete), but apparently Xcode complains if it's not present.

A quick fix is to set your project architectures to exclude armv7s from the "Valid Architectures" setting.

**Comment by aure** [comment]
How do you do that?  My valid architecture setting is simply: "$(ARCHS_STANDARD)"

**Comment by megastep** [comment]
You manually replace it with "arm64 armv7"

**Comment by megastep** [comment]
Actually, scratch that. Normally $(ARCHS_STANDARD) should expand to just these values anyway. Is it not the case for you?

**Comment by aure** [comment]
No, not as far as I can tell.  changing it didn't have an effect on Xcode's confusion over AK classes.

**Comment by ryanfrancesconi** [comment]
I don't think I have this issue:
![image](https://cloud.githubusercontent.com/assets/2917795/22941809/d8da1188-f29b-11e6-83e9-73974091b6fc.png)

This is with the mac os x framework. Build settings are pretty standard using link binary with libraries and embed framework.

I have found that getting a new project started is a mix of trying these things and waving a magic wand, then at some point it starts working.

**Comment by ryanfrancesconi** [comment]
I also copy the framework to my project folder.

**Comment by aure** [comment]
@ryanfrancesconi It's interesting that it worked for you when you copy the framework into the project folder.  I verified that that "fix" works for me too.  Problem is, in the examples, we really want to refer the one framework that lives in the Frameworks folder rather than making copies in each example folder.  So, what's the magic setting that lets Xcode see the framework?  It's not framework search path because that is set correctly as necessary for compilation.

**Comment by aure** [comment]
@megastep Here's a hint on the iOS side- if I change the target from being a simulator to being "Generic iOS Device" or my real physical device, then the autocomplete works fine.

**Comment by aure** [comment]
So just to summarize: On Mac, you can solve this by copying AudioKit into the project folder. On iOS you can solve this by making the target not the simulator. Neither are solutions, just clues to what has to be done to fix this in a more general way.

**Comment by ryanfrancesconi** [comment]
One thing though - I'm also having some weird issues starting up a new project. I'll let you know what I figure out. There's definitely some weird stuff going on.

**Comment by ryanfrancesconi** [comment]
coming from being a java programmer, i still find the sharing of resources between projects and name spaces, unintuitive and weird with xcode/swift/etc

**Comment by aure** [comment]
I'll close this for now, not like we're getting anywhere with this.
