### ISSUE TITLE
When including from Carthage, the bitcode is not "fully" activated

### ISSUE THREAD

**Issue by NicolasLourenco** [audiokit/AudioKit#745]
Hello,
Tested on the lastest release, and when I try to upload app to AppStore, it say the AudioKit is not fully bitcode compatible.

It's possible to release a version with bitcode fully enabled?
Thanks

**Comment by megastep** [comment]
That's rather odd, maybe you have some incorrect settings when submitting or compiling your project. Can you get the exact text of the error reported?

**Comment by NicolasLourenco** [comment]
After updating Audiokit, I havent more this error, but when I try to call anything from AudioKit it crash.
