### ISSUE TITLE
Effects not being recorded

### ISSUE THREAD

**Issue by tomw** [audiokit/AudioKit#749]
I don't seem to be able to save any effects when recording. For example:

```
let microphone = AKMicrophone()
let pitchShifter = AKPitchShifter(microphone, shift: 10, windowSize: 1024, crossfade: 512)
let micMixer = AKMixer(pitchShifter)

let format = AVAudioFormat(commonFormat: .pcmFormatFloat32, sampleRate: 44100, channels: 2, interleaved: false)
let audioFile = try AKAudioFile(forWriting: recordingUrl, settings: format.settings)

self.recorder = try AKNodeRecorder(node: micMixer, file: audioFile)
```
That code records fine, but it just sounds like a plain recording. Is anyone else getting this problem? Or do I have a problem in my code?

**Comment by aure** [comment]
I can verify that something is wrong, looking into what it could be.

**Comment by aure** [comment]
Okay, I am not sure why this is but this works for me if the pitch shifter is defined as an instance variable: 

```
    var tape: AKAudioFile?
    var pitchShifter: AKPitchShifter?
    var micBooster: AKBooster?
```

And then just use it like the others.

```
        inputPlot.node = mic
        pitchShifter = AKPitchShifter(mic, shift: 12)
        let micMixer = AKMixer(pitchShifter!)
```

I don't really understand why declaring it locally doesn't work.
