### ISSUE TITLE
tracker.start() crash after updating Audiokit

### ISSUE THREAD

**Issue by NicolasLourenco** [audiokit/AudioKit#750]
Hello,
From the last update, when I try to set the tuner, AudioKit crash on `tracker.start()` line.
Here is my code. I don't understand why it appears now. 

After the init all objects (tracker, silence) are initialised.

    class Tuner: NSObject {
    var delegate: TunerDelegate?

    /* Private instance variables. */
    var mic: AKMicrophone!
    var tracker: AKFrequencyTracker!
    var silence: AKBooster!
    var displayLink: CADisplayLink!
    var loopAlreadySetup: Bool = false

    override init() {
        AKSettings.audioInputEnabled = true
        mic = AKMicrophone()
        tracker = AKFrequencyTracker.init(mic)
        silence = AKBooster(tracker, gain: 0)

        AudioKit.output = silence
    }

    func startMonitoring() {
        AudioKit.start()
        mic.start()
        tracker.start()
        silence.start()

        displayLink = CADisplayLink(target: self, selector: #selector(updateMeters))
        displayLink.add(to: RunLoop.current, forMode: RunLoopMode.commonModes)
    }

    func stopMonitoring() {
        silence.stop()
        tracker.stop()
        mic.stop()
        AudioKit.stop()

        displayLink.invalidate()
        displayLink = nil
    }

Any ideas?

**Comment by NicolasLourenco** [comment]
The problem don't appear when integrate from CocoaPod. Only from Carthage

**Comment by aure** [comment]
What versions of AudioKit are you getting through Carthage and Cocoapods?  The same?

**Comment by NicolasLourenco** [comment]
Exactly the same. The last version available in the two cases.

**Comment by aure** [comment]
You want to try the code directly as a framework or or an embedded project?  I mean, we will get to this but the more information the better.

**Comment by NicolasLourenco** [comment]
Initialy, I try to integrate as a framework through Carthage.

**Comment by aure** [comment]
I wonder if Carthage is getting the most recent code whereas CocoaPods is getting the most recent release.  So bizarre that they act differently.

**Comment by aure** [comment]
Since this is working for me can you tell me what the error you're getting is when it crashes?  I'll close this issue until more information is received, but feel free to reopen it.  Thanks.
