### ISSUE TITLE
Error When Recording Microphone with Effect Nodes

### ISSUE THREAD

**Issue by SoundandStuff** [audiokit/AudioKit#752]
Hello, 
I think I found a bug when I attach any node to my recorder and deploy it I consequently get this error and I have isolated the problem to Audiokit.  I created this simple recorder with an AKPitchShifter attach it works on the simulator, but always crashes on my iPad. I have tried reverbs and delays with no better results. I was wondering if anyone can help?

This is the code 

import UIKit

import AudioKit

class ViewController: UIViewController {

    var recorder: AKNodeRecorder?

    var player: AKAudioPlayer?

    var tape: AKAudioFile?

    var micBooster: AKBooster?

 

    override func viewDidLoad() {

        super.viewDidLoad()

        AKAudioFile.cleanTempDirectory()

        AKSettings.bufferLength = .medium

        

        do {

            try AKSettings.setSession(category: .playAndRecord, with: .defaultToSpeaker)

        } catch { print("Errored setting category.") }

        let mic = AKMicrophone()

        //inputPlot.node = mic

        let micMixer = AKMixer(mic)

        micBooster = AKBooster(micMixer)

        let pitch = AKPitchShifter(micMixer) //If you take this out

        pitch.shift = 8   //and take this out 

        micBooster!.gain = 0

        recorder = try? AKNodeRecorder(node: pitch) //and finally change this micMixer it will work on my iPad, however I can not use any Effect nodes.

        player = try? AKAudioPlayer(file: (recorder?.audioFile)!)

        let mainMixer = AKMixer(micBooster!, player!)

        AudioKit.output = mainMixer

        AudioKit.start()

        // Do any additional setup after loading the view, typically from a nib.

    }

    override func didReceiveMemoryWarning() {

        super.didReceiveMemoryWarning()

        // Dispose of any resources that can be recreated.

    }

    

    @IBAction func recordButton(_ sender: Any) {

        if recorder!.isRecording {

            micBooster!.gain = 0

            do {

                try player?.reloadFile()

            } catch { print("Errored reloading.") }

            

            let recordedDuration = player != nil ? player?.audioFile.duration  : 0

            if recordedDuration! > 0.0 {

                recorder?.stop()

                let fileName = player?.audioFile.url.lastPathComponent

                do {

                    let nonExistentFile = try AKAudioFile(readFileName: fileName!,

                                                          baseDir: .temp)

                    try  nonExistentFile.exportAsynchronously(name: "exported.m4a", baseDir: .documents, exportFormat: .m4a) { exportedFile, error in

                        print("myExportCallBack has been triggered. It means that export ended")

                        if error == nil {

                            print("Export succeeded")

                        }

                        else {

                            print("Export failed\(error)")

                        }

                        

                    }

                } catch let error as NSError {

                    print("There's an error: \(error)")

                }

                

                let recordedDuration =  player != nil ? player?.audioFile.duration  : 0

            }

        } else {

            try? recorder?.record()

        }}

    @IBAction func playButton(_ sender: Any) {

        print(player?.audioFile.directoryPath)

        if player!.isPlaying {

            player?.stop()

        } else {

            try? player?.reloadFile()

            if player?.audioFile.duration ?? 0 > 0 {

                player?.play()

            }

        }

    }

}

This is the error code I consistently get.

2017-02-16 16:40:46.941292 Reocord and Play test Audiokit[511:72322] [central] 54:   ERROR:    [0x1b6f52c40] >avae> AVAudioEngineGraph.mm:2515: PerformCommand: error -10875

2017-02-16 16:40:46.942208 Reocord and Play test Audiokit[511:72322] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10875'

I would appreciate any help to solve this problem. 

Thanks,

Eric

**Comment by aure** [comment]
Thanks for posting here, it may be related to another issue, but it will be a good check.

**Comment by aure** [comment]
I think this is basically a duplicate to this issue: https://github.com/audiokit/AudioKit/issues/749
for which the solution was to have the AKPitchShifter be an instance variable like the others:

```
    var tape: AKAudioFile?
    var pitchShifter: AKPitchShifter?
    var micBooster: AKBooster?
```

And then just use it as so.

```
        inputPlot.node = mic
        pitchShifter = AKPitchShifter(mic, shift: 12)
        let micMixer = AKMixer(pitchShifter!)
```

I don't really understand why declaring it locally doesn't work.

**Comment by SoundandStuff** [comment]
Hi Aure,
For me that worked on the simulator, but not when I deployed it unfortunately.

**Comment by SoundandStuff** [comment]
I got it to work on the example code though. I think you can still close this case. I probably need to mess with my own code.
