### ISSUE TITLE
Error using cocoapods on xcode 8 swift 2.3. Module build for 

### ISSUE THREAD

**Issue by sonic555gr** [audiokit/AudioKit#753]
Hello. 
I' recently had to update Xcode and now my project is not compiling since the Audio kit library is complaining about being built with the wrong compiler version. On your website I found this article that talks about Xcode 8 and swift 2.3 support but I couldn't find the respective branch. 
[](http://audiokit.io/blog/2016/08/26/audiokit-v3.3/)
This is the error I'm getting when trying to build.
<img width="629" alt="screen shot 2017-02-18 at 13 07 34" src="https://cloud.githubusercontent.com/assets/1837788/23093437/6428beaa-f5db-11e6-9dd4-7530715bda84.png">

I can't convert my project to swift 3.0.2 just yet as it is quite large and the changes are breaking. 
Where can I find a version of the framework that is built with Xcode 8 and supports swift 2.3? 

I'm using AudioKit version 3.3. 

Thanks

**Comment by aure** [comment]
You will have to build it yourself with the build_frameworks.sh script in Frameworks/ or include AudioKit as a subproject.

**Comment by megastep** [comment]
Also Swift 2.3 is both source and binary incompatible with Swift 3, so really no luck here short of migrating your project to Swift 3.

**Comment by sonic555gr** [comment]
Thank you. At least now I know not to spend silly time playing with cocoapods and build settings. 
Can you please add something on the wiki about compatibility because I'm pretty sure other people have faced the same problem. 

I've already started converting. I will go directly to the latest version of AudioKit. Peace.
