### ISSUE TITLE
"Exporting Files"and "Reading and Writing Audio Files" playgrounds fail

### ISSUE THREAD

**Issue by trevor-sonic** [audiokit/AudioKit#754]
Hi,
I'm trying official provided code "Exporting Audio Files"

Console message shows that files exported like;

```
Export succeeded, converted file: test3.aif
Exported File Duration: 0.453514739229025 seconds
replace(file:) AKAudioPlayer -> File with "test3.aif" Reloaded
```

But there is no any trace about the file exported. Where are the file exported? (in playground)
And example code suppose to play exported samples. It plays a glitch sound this give me an impression that files aren't  exist or corrupted, to give an accurate information about the file exported I desperately need to know where they are normally.
Thank you.

**Comment by aure** [comment]
Are you running playgrounds for iOS or macOS?  I assume you're on the latest 3.5.3?

**Comment by aure** [comment]
Anyway, in a playground, the file is probably getting saved to your home directory.  In an app it would be the app's documents directory.  HTH, if not please reopen the issue with more information.

**Comment by trevor-sonic** [comment]
Hi aure,

I use for iOS, I compiled for iPhone 7 plus. Problem is happening on playground. Version 3.5.3 yes.

I took 12sec video screen capture 10th sec. to be helpful, you can hear a glitch sound. I don't have any clue where the files are.

(Sorry for my late feedback I didn't receive notification from GitHub)
Thank you

**Comment by aure** [comment]
This was also reported in https://github.com/audiokit/AudioKit/issues/763 with a bit of a clue that the errors look like not-found errors.  Looking into it for you both.
