### ISSUE TITLE
AKMixer + AKOscillator: No sound

### ISSUE THREAD

**Issue by artgillespie** [audiokit/AudioKit#755]
I have the following simple code that I'm running in the simulator:

```swift
        let osc = AKOscillator()
        osc.frequency = 880.0
        osc.amplitude = 0.5
        osc.start()
        let osc2 = AKOscillator()
        osc2.frequency = 440.0
        osc2.amplitude = 0.5
        osc2.start()
        let mixer = AKMixer(osc, osc2)
        AudioKit.output = mixer
        AudioKit.start()
```

This code results in no sound, but changing the output to one of the oscillators, e.g.,

```swift
AudioKit.output = osc
```

or

```swift
AudioKIt.output = osc2
```

Results in the individual oscillator being audible.

I tried experimenting with the SequencerDemo example since it's working fine, but I get the same result. From `Conductor.swift:66`

```swift
        /*
        mixer.connect(verb!)
        mixer.connect(bassDrum)
        mixer.connect(snareDrum)
        mixer.connect(snareGhost)
        mixer.connect(snareVerb!)
        */
        
        let osc = AKOscillator()
        osc.start()
        mixer.connect(osc)
        mixer.connect(bassDrum)
        
        AudioKit.output = mixer
```

With this code I hear the bassDrum track, but not the oscillator... if I assign the oscillator directly to `AudioKit.output` I hear the oscillator fine.

I've tried this with the iOS framework built from both `master` and the `v3.5.3` tag, I'm running Xcode 8.2.1 on OS X 10.11.6

Shouldn't `AKMixer` mix any `AKNode`?

**Comment by aure** [comment]
I got the first example mixing oscillators to work on playgrounds and I was able to mix oscillators with AKAudioplayers as well. This is in playgrounds though, will make an app to test too, but you may want to try the playgrounds to see if it happens for you there too.

**Comment by artgillespie** [comment]
Thanks for the quick reply!

Confirmed. The following works as expected (both oscillators are audible) in a new Playground page in the AudioKit for iOS project:
```swift
import AudioKit
import PlaygroundSupport

let osc = AKOscillator()
osc.frequency = 440.0
osc.amplitude = 0.5
osc.start()
let osc2 = AKOscillator()
osc2.frequency = 880.0
osc2.amplitude = 0.5
osc2.start()
let mixer = AKMixer(osc, osc2)
AudioKit.output = mixer
AudioKit.start()

PlaygroundPage.current.needsIndefiniteExecution = true
```

Still not working in an otherwise blank app in the Simulator. Let me get a device provisioned and see if it's happening on-device.

**Comment by artgillespie** [comment]
I'm getting the same unexpected behavior on an iPhone 7 Plus running iOS 10.2.1.

Here's the project in case it's helpful. (It's just a single-page view iOS template with an added `Conductor.swift` file)

[AudioKit_1.zip](https://github.com/audiokit/AudioKit/files/788573/AudioKit_1.zip)

**Comment by aure** [comment]
I'm stumped.  Mixer is somehow messed up...  It works in playgrounds and macOS, but not simulator or actual devices.  Looking at it.

**Comment by aure** [comment]
Pull your oscillators out of init and define them as instance variables and it will work:

```
class Conductor {
    let osc = AKOscillator()
    let osc2 = AKOscillator()

    init() {
        osc.frequency = 880.0
        osc.amplitude = 0.5
        osc.start()
        osc2.frequency = 440.0
        osc2.amplitude = 0.5
        osc2.start()
        let mixer = AKMixer(osc, osc2)
        AudioKit.output = mixer
        AudioKit.start()
    }
}
```

**Comment by artgillespie** [comment]
Thanks, @aure!
