### ISSUE TITLE
Audiokit framework size issue

### ISSUE THREAD

**Issue by dreamBegin** [audiokit/AudioKit#758]
I just started using audiokit , works like a charm. I'm from Objective-C background and using xcode 8.2 i'm including audiokit using cocoapods and the problem i encountered is size. I'm only using AKMicrophone , AkfrequencyTracker and AKBooster.the size of my project was 70mbs after including audiokit the size increased to 120mb's approx and the before including audiokit the size of my ipa was 32mb now it is 87. what are the possible solutions for that. any help will be truly appreciated. thanks in advance.

**Comment by aure** [comment]
You can't reduce the size of AudioKit if you use CocoaPods, but if you build the framework yourself, or include the source, you can strip away a lot of functionality by deleting swift files and removing lines from AudioKit.h and then removing the corresponding audio units.

**Comment by dreamBegin** [comment]
how can I build the framework on  my own i have no idea about that any suggestions....

**Comment by aure** [comment]
I don't mean to be disrespectful, because I am happy when people use AudioKit, but you seem to be asking a lot of questions that are specific to your situation.  Teaching how to build a framework is beyond my duties and I'm super busy right now anyway.

**Comment by dreamBegin** [comment]
No probelm for sure. i can understand .appreciate your time , thanks.

**Comment by dreamBegin** [comment]
if you find some time in future tell me about the thing "include the source"  is there any way i can get the source code?
