### ISSUE TITLE
Value observation

### ISSUE THREAD

**Issue by plm75** [audiokit/AudioKit#760]
In the playground examples, an `AKPlaygroundLoop` is used to update the UI.  How should I do this for an application ?

More generally, what's the recommended way to observe AKNodes' property value changes ? Is KVO supported ?

Thanks

**Comment by plm75** [comment]
Hello again,

I tried a quick and dirty hack:

```swift 
class RZAudioPlayer: AKAudioPlayer {
  dynamic var observableReversed: Bool = false
  
  override var reversed: Bool {
    didSet {
      print("Changed reversed to \(reversed)")
      observableReversed = reversed
    }
  }
  
  override init(file: AKAudioFile, looping: Bool, completionHandler: AKCallback?) throws {
    try super.init(file: file, looping: looping, completionHandler: completionHandler)
  }
}
```

Observing `observableReversed` on a instance of RZAudioPlayer then seems to work fine.

Is there any reason why we couldn't directly add `dynamic` to all  AKNodes' public properties ?  This way, we could have KVO enabled for all these properties.

Thanks

**Comment by aure** [comment]
I think that's reasonable, do you want to do it and make a pull request?

**Comment by aure** [comment]
(If you do want to make a pull request, make sure to do it on the develop branch as there have ben a lot of changes there recently)

**Comment by aure** [comment]
Pull requested accepted!
