### ISSUE TITLE
Playground crash due to AKAudioFile+Processing

### ISSUE THREAD

**Issue by plm75** [audiokit/AudioKit#762]
Hello,

The playground `Playback / Editing Audio Files` crashes.

This is due to the fact that when not provided with names, `AKAudioFile+Processing` methods return an empty string for the name and not a random unique name as stated in the playground comment.

Changing the processing methods signatures with 

```swift 
name: String = UUID().uuidString
```

instead of 
```swift
name: String = ""
```

seems to fix the issue.  I have PR ready if you want, but I do not know enough of AudioKit's internals to be sure about the fix.  Let me know.

**Comment by aure** [comment]
Sure, please PR.

**Comment by aure** [comment]
Thanks!
