### ISSUE TITLE
"Exporting Files"and "Reading and Writing Audio Files" playgrounds fail

### ISSUE THREAD

**Issue by plm75** [audiokit/AudioKit#763]
The "Exporting Files" playground fails with the following error:

`Error: The requested URL was not found on this server.`

Not exactly sure where this is coming from.

The "Reading and Writing Audio Files" playground also fails with error: "Export failed"

**Comment by aure** [comment]
I can confirm this is true.  Working on it.

**Comment by aure** [comment]
This is actually very similar to another issue, so I am going to combine them.
