### ISSUE TITLE
Cocoapod - Cannot use specific branch

### ISSUE THREAD

**Issue by plm75** [audiokit/AudioKit#766]
Hello,

With the following in my Podfile:
`pod 'AudioKit', :git => 'https://github.com/audiokit/AudioKit', :branch => 'develop'`

`pod install` completes successfully, but `Pods/AudioKit/` only contains LICENCE and README files.  No source files.  This is very annoying because if I want to test changes in my fork's develop branch (or from Audiokit's develop branch), I have to build the framework ... 

I'm far from being a `cocoapods` expert, but I think this probably comes from Audiokit's cocoa pods setup because pulling branches works for some other frameworks I tested.

**Comment by megastep** [comment]
Yes, that's because our current CocoaPods setup doesn't use the source from the GitHub branch, but rather the zip file containing the compiled frameworks for that release. So in effect switching the branch won't really work since there won't be a corresponding zip file.

**Comment by aure** [comment]
Yeah, we definitely haven't been treating Cocoapods as a legitimate way to do active development, more like just for those who want a relatively stable release.  I am not sure we should change it and I wouldn't know how to start.
