### ISSUE TITLE
Memory leak on AKOperationEffect and crash when setting the output.

### ISSUE THREAD

**Issue by sonic555gr** [audiokit/AudioKit#767]
Hello.  I have the following code in a view controller. if I push the controller, pop it and push it again. 
When the code reaches  
`AudioKit.output = dryWetMixer`
It crashes with the following stack trace. 

> 2017-02-28 13:36:35.719307 AudioKitTest[15445:21755998] [central] 54:   ERROR:    >avae> AVAudioEngine.mm:301: DetachNode: required condition is false: [_nodes containsObject: node]
> 2017-02-28 13:36:35.766 AudioKitTest[15445:21755998] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: [_nodes containsObject: node]'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00000001140c4d4b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x0000000110e7621e objc_exception_throw + 48
> 	2   CoreFoundation                      0x00000001140c8e42 +[NSException raise:format:arguments:] + 98
> 	3   AVFAudio                            0x00000001134f0fd0 _Z19AVAE_RaiseExceptionP8NSStringz + 176
> 	4   AVFAudio                            0x0000000113547d80 _ZN17AVAudioEngineImpl10DetachNodeEP11AVAudioNodeb + 424
> 	5   AVFAudio                            0x0000000113547b91 -[AVAudioEngine detachNode:] + 67
> 	6   AudioKit                            0x000000011033f6f4 _TToFC8AudioKit6AKNodeD + 84
> 	7   libobjc.A.dylib                     0x0000000110e8ab12 _ZN11objc_object17sidetable_releaseEb + 212
> 	8   AudioKit                            0x0000000110408d89 _TToFC8AudioKit13AKDryWetMixerE + 25
> 	9   libobjc.A.dylib                     0x0000000110e74a0a _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
> 	10  libobjc.A.dylib                     0x0000000110e805f6 objc_destructInstance + 129
> 	11  libobjc.A.dylib                     0x0000000110e80628 object_dispose + 22
> 	12  AudioKit                            0x000000011033f72b _TToFC8AudioKit6AKNodeD + 139
> 	13  libobjc.A.dylib                     0x0000000110e8ab12 _ZN11objc_object17sidetable_releaseEb + 212
> 	14  AudioKitTest                        0x000000010fda70f2 _TFC12AudioKitTest14ViewController15initAudioEnginefT_T_ + 1458
> 	15  AudioKitTest                        0x000000010fda688f _TFC12AudioKitTest14ViewController11viewDidLoadfT_T_ + 31
> 	16  AudioKitTest                        0x000000010fda68c2 _TToFC12AudioKitTest14ViewController11viewDidLoadfT_T_ + 34
> 	17  UIKit                               0x00000001114e7a3d -[UIViewController loadViewIfRequired] + 1258
> 	18  UIKit                               0x00000001114ee062 -[UIViewController __viewWillAppear:] + 118
> 	19  UIKit                               0x00000001115191d3 -[UINavigationController _startCustomTransition:] + 1290
> 	20  UIKit                               0x0000000111529e48 -[UINavigationController _startDeferredTransitionIfNeeded:] + 697
> 	21  UIKit                               0x000000011152afdb -[UINavigationController __viewWillLayoutSubviews] + 58
> 	22  UIKit                               0x0000000111721dd7 -[UILayoutContainerView layoutSubviews] + 223
> 	23  UIKit                               0x000000011140aab8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1237
> 	24  QuartzCore                          0x00000001157cfbf8 -[CALayer layoutSublayers] + 146
> 	25  QuartzCore                          0x00000001157c3440 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
> 	26  QuartzCore                          0x00000001157c32be _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
> 	27  QuartzCore                          0x0000000115751318 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 280
> 	28  QuartzCore                          0x000000011577e3ff _ZN2CA11Transaction6commitEv + 475
> 	29  UIKit                               0x000000011133ed9b _UIApplicationFlushRunLoopCATransactionIfTooLate + 206
> 	30  UIKit                               0x0000000111b4977c __handleEventQueue + 5672
> 	31  CoreFoundation                      0x0000000114069761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
> 	32  CoreFoundation                      0x000000011404e98c __CFRunLoopDoSources0 + 556
> 	33  CoreFoundation                      0x000000011404de76 __CFRunLoopRun + 918
> 	34  CoreFoundation                      0x000000011404d884 CFRunLoopRunSpecific + 420
> 	35  GraphicsServices                    0x000000011451fa6f GSEventRunModal + 161
> 	36  UIKit                               0x0000000111345c68 UIApplicationMain + 159
> 	37  AudioKitTest                        0x000000010fda86cf main + 111
> 	38  libdyld.dylib                       0x000000011674568d start + 1
> 	39  ???                                 0x0000000000000001 0x0 + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException

I made sure that the `AudioKit.stop()` is being called on deinit. This is a consistent crash.

If you would like to replicate I would suggest you create a NavigationStack with two controllers so you can push and pop the controller in question. 

This is the full initialization code. 
```
func initAudioEngine() {
        player = try? AKAudioPlayer(file: try! AKAudioFile(readFileName: "brass_beat.mp3"))
        let input  = AKStereoOperation.input
        let sporth = "\(input) 15 200 7.0 8.0 10000 315 0 1500 0 1 0 zitarev"
        effect = AKOperationEffect(player!, sporth: sporth)
        dryWetMixer = AKDryWetMixer(player!, effect!, balance: 0)
        AudioKit.output = dryWetMixer
        AudioKit.start()
    }
```

Also after profiling I found that when the controller is popped, 
AKOperationEffect is leaking a substantial amount of memory. 

<img width="1280" alt="screen shot 2017-02-28 at 13 40 54" src="https://cloud.githubusercontent.com/assets/1837788/23407381/99521904-fdbb-11e6-8a48-8ae77574a04e.png">

I was wandering if I'm doing something wrong or if this is a bug. 

Thanks!

**Comment by aure** [comment]
In general, its a bad idea to do this with your audio engine.  When nothing is being pulled to the output, the audio engine does not do much work, so its better to keep your audio engine running and just start and stop drawing waveforms as necessary.

**Comment by sonic555gr** [comment]
@aure This doesn't really solve my problem. Even If I don't stop the AudioKit Engine, crash persists. Please try to replicate when you have time. Thanks.

**Comment by aure** [comment]
Is the issue that you are changing the components in the signal chain?  You can't set up the signal chain once and leave it off until you need it?  I really need to be given an example project, not be asked to create one.  So far, I don't see why you need to be doing it this way instead of having the audio engine run as a singleton available project wide.

**Comment by sonic555gr** [comment]
Hey, Here is a copy of the example project. 
[](https://www.dropbox.com/s/zks1j3by0t8h4qe/AudioKitTest.zip?dl=0)

Before making assumptions about how I structure my code, can you please tell me exactly why the example project is crashing if you tap "button", go back and tap "button" again?

You said that it's a bad idea to do this with the Audio engine, but I still don't understand what "this" is. All examples I found online say that I should first create the components, then set the output and then start() and this is exactly what is going on. 
I'm not very familiar with sound programming.

Best

**Comment by aure** [comment]
Messing with your project now, looks like its not the operationEffect this is the issue, but the dry/wet mixer, because if I use a regular mixer it goes back and forth fine.  So one option is to avoid dry wet mixing:

```
    var mixer1: AKMixer? = nil
    var mixer2: AKMixer? = nil
```
and:
```
        mixer1 = AKMixer(player!)
        mixer2 = AKMixer(effect!)
        AudioKit.output = AKMixer(mixer1!, mixer2!)
```

Instead of balance, you'd user the mixer1/2 volume property.  If you look at the dry wet mixer, it is just AKMixers behind the scenes, so I am not sure why this is happening, but while I investigate that I thought I'd at least respond with a fix that keep you developing, I hope.

**Comment by sonic555gr** [comment]
Thanks, replacing the drywet with 2 simple mixers worked. I will get back to you with more issues as I face them.

**Comment by aure** [comment]
I still think this is a product of the view controller lifecycle and you'd be better off with a conductor class that wouldn't have to necessarily reinitialize itself, so I'll close this for now and perhaps revisit later.
