### ISSUE TITLE
Request: AKAudioPlayer loop restart closure / handler

### ISSUE THREAD

**Issue by jsonfellin** [audiokit/AudioKit#769]
Thanks for the great library.

I'd like to request a closure that fires when a AKAudioPlayer instance is set to loop and the loop restarts. Let me know if you have questions.

**Comment by aure** [comment]
Can you just run a timer that checks the playhead location periodically as done in the Audio Player playground page in the Playback playground? http://audiokit.io/playgrounds/Playback/Audio%20Player/

**Comment by jsonfellin** [comment]
I suppose, but that feels like a hassle. I looked at the code. At a glance, it looks as simple as calling a closure after scheduleBuffer(). Correct me if I'm wrong.


```
    fileprivate func internalCompletionHandler() {
        if playing {
            if looping {
                scheduleBuffer()
            } else {
                stop()
                self.completionHandler?()
            }
        }
    }
```

What you open to me submitting a pull request? Thanks again.

**Comment by aure** [comment]
Of course, submit a pull request!  That would be great.

**Comment by aure** [comment]
I'll close this for now seeing as you know how to solve it.  Definitely looking forward to a pull request from you soon.
