### ISSUE TITLE
AKDelay doesn't work as expected on iOS 10

### ISSUE THREAD

**Issue by bryanhadlock** [audiokit/AudioKit#771]
I messed with AKDelay for a bit yesterday in my iOS application, and couldn't get it to work. So I figured it was my code, and created a new solution with the exact same code from the "Splitting Nodes" playground and it did the exact same thing. No delay/feedback or dryWetMix sound, but it works fine in the playground.  Can I get some help getting this to work? Here is the "Splitting Nodes" code https://drive.google.com/open?id=0BxT1JnY1XqoWU1lodUhqY2p2Zzg 

`do {
            let file = try AKAudioFile(readFileName: "drumloop.wav")
            
            let player = try AKAudioPlayer(file: file)
            player.looping = true
            
            //: The following nodes are both acting on the original player node
            var ringMod = AKRingModulator(player)
            
            var delay = AKDelay(player)
            delay.time = 0.01
            delay.feedback = 0.8
            delay.dryWetMix = 1
            
            //: Any number of inputs can be equally summed into one output, including the
            //: original player, allowing us to create dry/wet mixes even for effects that
            //: don't have that property by default
            let mixer = AKMixer(player, delay)
            
            AudioKit.output = mixer
            AudioKit.start()
            player.play()
        }
        catch let error as NSError {
            print(error.localizedDescription)
        }`

**Comment by aure** [comment]
Does the delay playground work as expected?

**Comment by bryanhadlock** [comment]
yes it does

**Comment by aure** [comment]
Here's a view controller that works.  Basically just moving the nodes out of view did load and into instance variables.  HTH


```
//
//  ViewController.swift
//  TestAKDelay
//
//  Created by Bryan Hadlock on 3/2/17.
//  Copyright © 2017 Bryan Hadlock. All rights reserved.
//

import UIKit
import AudioKit

class ViewController: UIViewController {
    
    var delay: AKDelay?
    var ringMod: AKRingModulator?
    
    @IBAction func play(_ sender: Any) {
        do {
            let file = try AKAudioFile(readFileName: "drumloop.wav")
            
            let player = try AKAudioPlayer(file: file)
            player.looping = true
            
            //: The following nodes are both acting on the original player node
            ringMod = AKRingModulator(player)
            
            delay = AKDelay(player)
            delay?.time = 0.01
            delay?.feedback = 0.8
            delay?.dryWetMix = 1
            
            //: Any number of inputs can be equally summed into one output, including the
            //: original player, allowing us to create dry/wet mixes even for effects that
            //: don't have that property by default
            let mixer = AKMixer(player, delay!)
            
            AudioKit.output = mixer
            AudioKit.start()
            player.play()
        }
        catch let error as NSError {
            print(error.localizedDescription)
        }
    }
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}


```

**Comment by bryanhadlock** [comment]
Awesome. Thank you.
