### ISSUE TITLE
Wav File Analysis with AudioKit

### ISSUE THREAD

**Issue by oyzh888** [audiokit/AudioKit#776]
I want to use tools like AKFrequencyTracker to analyze the frequency of a file directly, not in real time ( like the Tuner APP ). For example, if I want to know the frequency sequence of a wav file,262hz-294hz-330-349hz-392hz-440hz-494hz…., but I do not want to play the whole wav file. 
1. How can I use AKFrequencyTracker to analyze the file directly?
2. If I want to perform “pitch shift” or "change duration” operations to part of WAV file, what should I do?

**Comment by aure** [comment]
Hi, thanks for this issue and for the email you sent with a little more information and graphics.  Honestly, you're best bet for static analysis of a file is another library called Aubio or perhaps GistSwift.  You should be able to do file transformation with AudioKit, but I haven't yet fleshed it out yet with cross-platform concerns.  But, its already on our Project list, and its more of a feature than an issue, so I am going to close this Github issue.

**Comment by oyzh888** [comment]
Thx! Your advice is really helpful! And I will pay attention to the update of AudioKit😆

**Comment by vinidiktov-edsd** [comment]
Has the ability to analyze the frequency of a file directly, not in real time been added to AudioKit?

Thanks!
