### ISSUE TITLE
AKWhiteNoise amplitude not working

### ISSUE THREAD

**Issue by macguydvd** [audiokit/AudioKit#777]
Hello, thanks for the great tool!

I am learning my way around AudioKit and I noticed that while the amplitude for Pink Noise seems to work fine, changing the amplitude on the White Noise module seems to have no effect, it appears to be set to 1.0 regardless.

Thanks in advance for any help!

**Comment by aure** [comment]
Pretty sure this is fixed on the develop branch already as per https://groups.google.com/forum/#!searchin/audiokit/noise%7Csort:relevance/audiokit/07zOWQQQT_E/6WwCYb8kDAAJ

**Comment by macguydvd** [comment]
Thanks Aure!
