### ISSUE TITLE
Error in examples

### ISSUE THREAD

**Issue by scinfu** [audiokit/AudioKit#778]
I can not try example projects , cocoapods export this error:

> [!] Error installing Audiobus
[!] /usr/local/bin/git clone https://developer.audiob.us/download/SDK.git /var/folders/x8/ww6m8ssd2p7fwqk3hz8whrfm0000gn/T/d20170308-4948-17watrc --template= --single-branch --depth 1 --branch 2.3.3

>Cloning into '/var/folders/x8/ww6m8ssd2p7fwqk3hz8whrfm0000gn/T/d20170308-4948-17watrc'...
fatal: unable to access 'https://developer.audiob.us/download/SDK.git/': Unknown SSL protocol error in connection to developer.audiob.us:-9838

**Comment by aure** [comment]
This looks like a problem with Audiobus or CocoaPods, but not AudioKit.
