### ISSUE TITLE
fix-frameworks.sh Command not Found Error

### ISSUE THREAD

**Issue by ercantulu** [audiokit/AudioKit#779]
On Xcode 8.2.1 I get Command Not Found error on this lines:

16: if (`echo $BINARY_INFO | grep i386`); then
21: if (`echo $BINARY_INFO | grep x86_64`); then

and the not needed Architechtures are not stripped.

Showing Recent Messages
..../Frameworks/AudioKit.framework/fix-framework.sh: line 16: Architectures: command not found
..../Frameworks/AudioKit.framework/fix-framework.sh: line 21: Architectures: command not found

After removing these if cases the stripping worked and I could submit it to itunesstore.

**Comment by megastep** [comment]
Make sure you have the Xcode command-line tools installed, you need the `lipo` command available for this script.

You can do `xcode-select --install` to install them.

**Comment by ercantulu** [comment]
lipo is avaible and is working. 

After removing if clause 
I echo lipo command and get following before and after stripping:

Architectures in the fat file: ./AudioKit.framework/AudioKit are: i386 x86_64 armv7 arm64


Architectures in the fat file: ./AudioKit.framework/AudioKit are: armv7 arm64

**Comment by megastep** [comment]
Do you have a weird version of bash on your system? There's no reason you'd get errors unless you're running this script with the wrong shell.

**Comment by ercantulu** [comment]
/bin/bash is running as normal. echo $SHELL gives me /bin/bash

**Comment by aure** [comment]
I don't get any errors like these, and I presume Stephane doesn't either, so I'll close the issue as a public issue, but feel free to continue to converse on this thread.
