### ISSUE TITLE
Exception when connecting nodes

### ISSUE THREAD

**Issue by nonggiatu** [audiokit/AudioKit#781]
Hi,
I am testing connecting nodes using the sample code:

            let file = try? AKAudioFile(readFileName: "005.wav", baseDir: .resources)
            let player = try? AKAudioPlayer(file: file!)

            let delay = AKDelay(player!)
            delay.time = 0.1 // seconds
            delay.feedback  = 0.8 // Normalized Value 0 - 1
            delay.dryWetMix = 0.2 // Normalized Value 0 - 1
            
            let reverb = AKReverb(delay)
            reverb.loadFactoryPreset(.cathedral)
            
            AudioKit.output = reverb
            AudioKit.start()
            
            player!.play()

When running on the simulator, it is crashed with following message:

> TestAudioKit[3890:89164] [central] 54:   ERROR:    >avae> AVAudioEngineGraph.mm:1365: RemoveNode: required condition is false: !nodeMixerConns.empty() && !hasDirectConnToIONode
> 2017-03-08 22:11:31.935 TestAudioKit[3890:89164] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: !nodeMixerConns.empty() && !hasDirectConnToIONode'

If I only use the delay or reverb filter, it can work properly.

Can anyone please help?

**Comment by aure** [comment]
INstead of setting up the nodes as local variables, make them all instance variables in the class.  Not exactly sure why this fixes things, but it recently appeared and its not too much of a hassle to do it that way.

**Comment by nonggiatu** [comment]
After changing the nodes to class properties, it works now. Thanks a lot!

**Comment by aure** [comment]
Glad to help.
