### ISSUE TITLE
Can't plot AKMicrophone using AKNodeOutputPlot

### ISSUE THREAD

**Issue by denisb411** [audiokit/AudioKit#782]
I am trying to plot the wave generated by AKMicrophone but I think this is not working...

Error:

2017-03-08 12:44:00.823693 Microphone_Analyser_AK[32413:8926966] [central] 54:   ERROR:    >avae> AVAudioNode.mm:565: CreateRecordingTap: required condition is false: _recordingTap == nil
2017-03-08 12:44:01.161 Microphone_Analyser_AK[32413:8926966] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: _recordingTap == nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109536d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000108f9821e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010953ae42 +[NSException raise:format:arguments:] + 98
	3   AVFAudio                            0x000000010e71dfd0 _Z19AVAE_RaiseExceptionP8NSStringz + 176
	4   AVFAudio                            0x000000010e76acf8 _ZN19AVAudioNodeImplBase18CreateRecordingTapEmjP13AVAudioFormatU13block_pointerFvP16AVAudioPCMBufferP11AVAudioTimeE + 144
	5   AVFAudio                            0x000000010e768ded -[AVAudioNode installTapOnBus:bufferSize:format:block:] + 209
	6   AudioKit                            0x00000001084fdafc _TTSf4g_n_n_n___TFC8AudioKit16AKNodeOutputPlotcfTCS_6AKNode5frameVSC6CGRect10bufferSizeSi_S0_ + 700
	7   AudioKit                            0x00000001084fd364 _TFC8AudioKit16AKNodeOutputPlotCfTCS_6AKNode5frameVSC6CGRect10bufferSizeSi_S0_ + 116
	8   Microphone_Analyser_AK              0x0000000108221268 _TFC22Microphone_Analyser_AK14ViewController9setupPlotfT_T_ + 376
	9   Microphone_Analyser_AK              0x00000001082216cf _TFC22Microphone_Analyser_AK14ViewController7inspectfT_T_ + 319
	10  Microphone_Analyser_AK              0x0000000108221702 _TToFC22Microphone_Analyser_AK14ViewController7inspectfT_T_ + 34
	11  Foundation                          0x0000000108af18d4 __NSFireTimer + 83
	12  CoreFoundation                      0x00000001094c8db4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	13  CoreFoundation                      0x00000001094c8a43 __CFRunLoopDoTimer + 1075
	14  CoreFoundation                      0x00000001094c85ca __CFRunLoopDoTimers + 250
	15  CoreFoundation                      0x00000001094c02f1 __CFRunLoopRun + 2065
	16  CoreFoundation                      0x00000001094bf884 CFRunLoopRunSpecific + 420
	17  GraphicsServices                    0x000000010fb46a6f GSEventRunModal + 161
	18  UIKit                               0x000000010af3cc68 UIApplicationMain + 159
	19  Microphone_Analyser_AK              0x0000000108223a4f main + 111
	20  libdyld.dylib                       0x000000010e14668d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

And this is the default code (caught from playground) :

@IBOutlet var audioInputPlot: AKNodeOutputPlot!
    func setupPlot() {
        let plot = AKNodeOutputPlot(soundAnalyser.mic, frame: audioInputPlot.bounds)
        plot.plotType = .rolling
        plot.shouldFill = true
        plot.shouldMirror = true
        plot.color = UIColor.blue
        audioInputPlot.addSubview(plot)
    }

I am simply creating an UIView and setting it's class as AKNodeOutputPlot. Is this wrong?

**Comment by aure** [comment]
That's kind of weird how you're adding a a subview of the kind of plot that you're telling it it already is.  Try instead to just do:
```
func setupPlot() {
audioInputPlot.node = mic
audioInputPlot.plotType = .rolling
audioInputPlot.shouldFill = true
audioInputPlot.shouldMirror = true
audioInputPlot.color = UIColor.blue
}
```

**Comment by victorBaro** [comment]
I run into the same error. I can see my plot on the screen but as soon as I try to start recording, I get: 

```
AVAudioNode.mm:565: CreateRecordingTap: required condition is false: _recordingTap == nil
```

Here is my code, it is super simple but can't get it to work... @aure I would really appreciate if you can help me.

```swift
    private func setup() {
        // Clean tempFiles !
        AKAudioFile.cleanTempDirectory()

        // Session settings
        AKSettings.bufferLength = .medium
        do {
            try AKSettings.setSession(category: .playAndRecord, with: .allowBluetoothA2DP)
        } catch {
            AKLog("Could not set session category.")
        }
        startPlot()

        recorder = try? AKNodeRecorder(node: mic)
        recorder.durationToRecord = GlobalConstants.maxClipDuration

        AudioKit.start()
    }

    private func startPlot() {
        plot = AKNodeOutputPlot(mic, frame: bounds)
        plot.backgroundColor = UIColor.white
        plot.color = UIColor.customBlue
        plot.gain = 5
        plot.plotType = EZPlotType.rolling
        plot.shouldFill = true
        plot.shouldMirror = true
        addSubview(plot)
    }

    func startRecording() {
        do {
            try recorder.record()
        } catch { print("Can't record!") }
    }
```

**Comment by aure** [comment]
@victorBaro I don't see where mic is defined.

**Comment by victorBaro** [comment]
Thank you @aure for your quick reply. This is my declaration of mic (most of the code is copied from your amazing playgrounds examples :) ).
```swfit
let mic = AKMicrophone()
```

**Comment by aure** [comment]
I figured it was that, but I kinda need to see it all in context to try to figure out whats going wrong. The playgrounds work, I checked that much.

**Comment by victorBaro** [comment]
@aure any updates on this? Still not working.

**Comment by aure** [comment]
@victorBaro pretty much looking to replace the plotting system with a metal powered alternative.

**Comment by aure** [comment]
@victorBaro Meanwhile: https://github.com/AudioKit/AudioKit/pull/1042 might help?

**Comment by ryanthon** [comment]
Hi, is there any update on this issue? I'd like to update to Xcode 9.3, but I can't get AKMicrophone to work with AKNodeOuputPlot either. This one problem is holding me back from updating my version of Xcode.
