### ISSUE TITLE
Restart playback from the beginning?

### ISSUE THREAD

**Issue by amotion** [audiokit/AudioKit#783]
Hey guys! I've been trying to find an easy way to restart playback in the AKAudioPlayer and haven't found anything that clean. Curious if I'm missing something.

I tried calling `.play(from: 0.0)` but that will say the player is already playing. The best thing I came up with was stopping the player, reloading the file, and then calling play again. But it feels clunky. Would appreciate any tips if anyone knows a better way!

Ideally I would want to trigger playing from the beginning each time a button is tapped.

**Comment by aure** [comment]
Doesn't stop and then play do this?

**Comment by amotion** [comment]
For some reason when I try that it will only stop but not restart playing again (unless I reload the file)

**Comment by aure** [comment]
It's working as expected in the Audio Player playground page in the Playback playground.  Want to share your project?

**Comment by amotion** [comment]
Dang! Ok, I'll post what I'm doing here. Thanks for checking!

**Comment by aure** [comment]
Closing until then, feel free to reopen.

**Comment by amotion** [comment]
Ok! Here's a simple example of what I'm doing:

```
import UIKit
import AudioKit

class ViewController: UIViewController {

  let mixer = AKMixer()
  var player: AKAudioPlayer?

  override func viewDidLoad() {
    super.viewDidLoad()

    do {
      let audioFile = try AKAudioFile(readFileName: "BS_130_POVBrushes_2.wav")
      let player = try AKAudioPlayer(file: audioFile)
      self.mixer.connect(player)
      self.player = player
    } catch {
      fatalError()
    }

    AudioKit.output = self.mixer
    AudioKit.start()
  }

  @IBAction func play(sender: UIButton) {
    self.player?.stop()
    self.player?.play()
  }

}
```

**Comment by amotion** [comment]
This seems to only stop the player on second tap when it's already playing, instead of restarting playback from the beginning. Is it because the stop() and play() methods are called so close to each other?

**Comment by aure** [comment]
Probably.

**Comment by aure** [comment]
do the stop and then put a while loop while player.isplaying before hitting play.  Not good style, but at least it would answer some questions.

**Comment by amotion** [comment]
Ok! I'll give it a shot. FWIW this will successfully restart playback again on each tap:

```
   self.player?.stop()
    do {
      try self.player?.reloadFile()
    } catch {
      print("failed to reload")
    }
    self.player?.play()
```

**Comment by amotion** [comment]
One thing I'm noticing is if I print out something in `play()` and `player.completionHandler`, I see play gets called and then the completion handler gets called immediately afterwards.

**Comment by amotion** [comment]
I guess I really just should be using an AKSampler here if I want to trigger a sound to play on each tap. Getting better results with that!

**Comment by aure** [comment]
Yeah, AKSampler is the way to go.

**Comment by amotion** [comment]
Yeah! Thanks for all your help. Is there an easy way to know when a sample ends though? I'm setting an active state on the button and just want to set it to inactive once the sound stops. That was easy with the player :)
