### ISSUE TITLE
No sound with AKPanner / AKMixer / AKReverb

### ISSUE THREAD

**Issue by paulmasson** [audiokit/AudioKit#784]
This may or may not be an issue, since I found a resolution, but I would appreciate some feedback on what's going on. I'm also putting it here to make it available to search engines.

I tried a very simple program to pan a single note,

    func startPlaying() {
        
        let note = AKOscillator()
        note.start()
        
        let leftPan = AKPanner(note, pan: -1)

        AudioKit.output = leftPan
        AudioKit.start()

    }

but strangely got no sound. The same was true if the panner was replaced by a mixer or reverb node. The solution, inspired by #755, was to move the note declaration outside of the function:

    let note = AKOscillator()

    func startPlaying() {
        
        note.start()
        
        let leftPan = AKPanner(note, pan: -1)

        AudioKit.output = leftPan
        AudioKit.start()

    }

Why is it necessary to have the declaration outside of the function? Does this have to do with how Swift works or is it an issue for AudioKit?

And thanks for providing this terrific library!

**Comment by aure** [comment]
Yeah, its a new thing where all the nodes need to be instance variables or else they're kind of forgotten.  Not sure what caused it, if it was something we did or a change in swift.

**Comment by aure** [comment]
Members of the AudioKit team think that this is now the correct behavior.  Before, there was memory leaks, but now that we have that cleared up you need to have an explicit ownership of the nodes.  So I guess its a feature!? :)

**Comment by paulmasson** [comment]
Thanks for the response. Shouldn't this information be added to the documentation for AKNode?
