### ISSUE TITLE
frameworks.sh getting stuck

### ISSUE THREAD

**Issue by kevin-coelho** [audiokit/AudioKit#785]
Seems to get stuck here:

^C/Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/bin/xcpretty:83:in `each_line': Interrupt
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/bin/xcpretty:83:in `<top (required)>'
	from /usr/local/bin/xcpretty:23:in `load'
	from /usr/local/bin/xcpretty:23:in `<main>'

**Comment by aure** [comment]
Your installation of xcpretty must not be working.  You can edit the build_frameworks.sh to just use cat

```
if which xcpretty > /dev/null 2>&1;
then
	XCPRETTY=xcpretty
else
	XCPRETTY=cat
fi
```

I just replace all that with XCPRETTY=cat

**Comment by kevin-coelho** [comment]
I already tried that and it's still getting stuck. Here's what gets printed out:

Building frameworks for platforms: iOS macOS tvOS
Build settings from command line:
    BUILD_DIR = /Users/katc/Documents/coding_projects/CS194/AudioKit/Frameworks/build
    SDKROOT = iphonesimulator10.2

Build settings from configuration file 'simulator.xcconfig':
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ENABLE_BITCODE = YES
    IPHONEOS_DEPLOYMENT_TARGET = 9.0
    ONLY_ACTIVE_ARCH = NO
