### ISSUE TITLE
crashed when running the target

### ISSUE THREAD

**Issue by jessefang** [audiokit/AudioKit#786]
I have down load the audiokit.framework file from my colleague and drop it  to my project then run and build.
It crash when the app start, but the framework works fine in my colleague project.
The error is follow:
dyld: Library not loaded: @rpath/AudioKit.framework/AudioKit
  Referenced from: /private/var/mobile/Containers/Bundle/Application/B2DF5B30-6850-48FA-ABEC-F5BFF3874348/XWShiChangProject.app/XWShiChangProject
  Reason: no suitable image found.  Did find:
	/private/var/mobile/Containers/Bundle/Application/B2DF5B30-6850-48FA-ABEC-F5BFF3874348/XWShiChangProject.app/Frameworks/AudioKit.framework/AudioKit: mmap() error 1 at address=0x00218000, size=0x001A8000 segment=__TEXT in Segment::map() mapping /private/var/mobile/Containers/Bundle/Application/B2DF5B30-6850-48FA-ABEC-F5BFF3874348/XWShiChangProject.app/Frameworks/AudioKit.framework/AudioKit

**Comment by aure** [comment]
Follow the instructions in this video and it should work. https://vimeo.com/162156851 This is less of an issue and probably deserves to be a discussion on the Google group, not a Github issue:  https://groups.google.com/forum/#!forum/audiokit
