### ISSUE TITLE
Playground execution failed: expression failed to parse, unknown error

### ISSUE THREAD

**Issue by DAC17** [audiokit/AudioKit#787]
This occurs when opening AudioKit for IOS XCode Project, and prevents any part of the project from running:
`Playground execution failed: expression failed to parse, unknown error
* thread #1: tid = 0x54310, 0x00000001096d23c0 FM Oscillator Operation`executePlayground, queue = 'com.apple.main-thread', stop reason = breakpoint 1.2
  * frame #0: 0x00000001096d23c0 FM Oscillator Operation`executePlayground
    frame #1: 0x00000001096d19c0 FM Oscillator Operation`__37-[XCPAppDelegate enqueueRunLoopBlock]_block_invoke + 32
    frame #2: 0x000000010a1ed6ac CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
    frame #3: 0x000000010a1d26f4 CoreFoundation`__CFRunLoopDoBlocks + 356
    frame #4: 0x000000010a1d1e65 CoreFoundation`__CFRunLoopRun + 901
    frame #5: 0x000000010a1d1884 CoreFoundation`CFRunLoopRunSpecific + 420
    frame #6: 0x000000010f671a6f GraphicsServices`GSEventRunModal + 161
    frame #7: 0x000000010ad7fc68 UIKit`UIApplicationMain + 159
    frame #8: 0x00000001096d16e9 FM Oscillator Operation`main + 201
    frame #9: 0x000000010d7b368d libdyld.dylib`start + 1`

**Comment by LeonidKokhnovich** [comment]
@DAC17 How did you solve the issue?

**Comment by DAC17** [comment]
Playgrounds do not support external frameworks, therefore you must open the project named "AudioKit For IOS" in the IOS folder of the audiokit package, and make sure all of the playgrounds are present in that project(and if not open them there) and then run the project. This might throw up a few warnings, but should still work.

**Comment by aure** [comment]
This is actually true only in AudioKit 3.5.x.  In AudioKit 3.6 AudioKit Playgrounds are located at the top level Playgrounds folder.  You can still run playgrounds the way @DAC17 is describing, but I think the new way is a lot easier.
