### ISSUE TITLE
build_frameworks.sh still getting stuck

### ISSUE THREAD

**Issue by kevin-coelho** [audiokit/AudioKit#789]
Switched from xcpretty to cat and it prints out below, then gets stuck:

Building frameworks for platforms: iOS macOS tvOS
Build settings from command line:
    BUILD_DIR = /Users/katc/Documents/coding_projects/CS194/AudioKit/Frameworks/build
    SDKROOT = iphonesimulator10.2

Build settings from configuration file 'simulator.xcconfig':
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ENABLE_BITCODE = YES
    IPHONEOS_DEPLOYMENT_TARGET = 9.0
    ONLY_ACTIVE_ARCH = NO

**Comment by aure** [comment]
there's no information of anything getting stuck here, again, I'd say these are not issues/bugs but rather problems you're having getting set up.  https://groups.google.com/forum/#!forum/audiokit
