### ISSUE TITLE
Unitialized Variable Warnings

### ISSUE THREAD

**Issue by pcbeard** [audiokit/AudioKit#793]
AudioKit/Common/Internals/Sporth/ugens/t.c:146:22: Variable 'ft' is uninitialized when used here
AudioKit/Common/Internals/Sporth/ugens/argtbl.c:151:22: Variable 'at' is uninitialized when used here

Not sure how to fix these. Initializing to NULL will likely cause a crash.

**Comment by aure** [comment]
Where are you compiling this, ie for iOS, macOS, or tvOS?  In any case, I do not get any such warnings in Xcode.

**Comment by pcbeard** [comment]
Compiling for iOS using the Xcode 8.3 beta 4 tools. If you look at sporth_tblsize(), it does seem pretty obvious by inspection that ft is unitialized.

**Comment by aure** [comment]
This type of issue probably belongs on the https://github.com/PaulBatchelor/Sporth issues page since we would want any important updates to be done at the source.  We keep a slightly modified version of Sporth, mostly just to not include things we don't need or haven't implemented.  @PaulBatchelor what is your take on this?

**Comment by PaulBatchelor** [comment]
I'll look into it. I usually catch these warnings. Hmmm...

**Comment by PaulBatchelor** [comment]
Yup, I indeed see uninitialized behavior happening here with "tblsize"
https://github.com/audiokit/AudioKit/blob/master/AudioKit/Common/Internals/Sporth/ugens/t.c#L146
However, this has been fixed now:
https://github.com/PaulBatchelor/Sporth/blob/master/ugens/t.c#L146

The other initialized variable is "argtbl":
https://github.com/PaulBatchelor/Sporth/blob/master/ugens/argtbl.c#L151
Still an issue with my Sporth:
https://github.com/PaulBatchelor/Sporth/blob/master/ugens/argtbl.c#L151

Actually, tbh whole ugen is an issue if you ask me. I thought I removed it long ago...

**Comment by PaulBatchelor** [comment]
All these warnings should be gone in the upstream version of Sporth: https://github.com/PaulBatchelor/Sporth/commit/163cb93562e6126b9051c923b50e15bf2c303b08

**Comment by aure** [comment]
Okay, I will update Sporth on AudioKit shortly.

**Comment by aure** [comment]
We're fully up to date with newest Soundpipe and Sporth as of https://github.com/audiokit/AudioKit/commit/3cf43e2d5a5be85538c10957c1db4fdc91853b80 so I am going to assume this is taken care of, but of course feel free to reopen as necessary.
