### ISSUE TITLE
How Often does AKFrequencytracker update?

### ISSUE THREAD

**Issue by saxjax** [audiokit/AudioKit#795]
I am a newbee, so please forgive me if my question is dumb.
I'm creating a tuner, Id like to call a function on didset, everytime frequencytracker.frequency changes, is that possible? and How Often does AKFrequencytracker measure? 100/sec, 1000/sec

**Comment by pcbeard** [comment]
If you set a breakpoint on sp_ptrack_compute(), you'll see that it gets called on every buffer received from the microphone, so the frequency will depend on the input buffer size and sampling rate.

**Comment by aure** [comment]
Good answer @pcbeard Saxjax, Github issues are meant for bugs or problems we can address. This kind of question belongs in our forum: https://groups.google.com/forum/#!forum/audiokit

**Comment by saxjax** [comment]
Thanks A lot
