### ISSUE TITLE
AKSampler fatal error: file not found

### ISSUE THREAD

**Issue by jonasbarsten** [audiokit/AudioKit#796]
On a clean Xcode 8.2.1 project with AudiKit 3.5.3 installed with CocoaPods I get this error when trying to use AKSampler:

> AudioKitTest[3521:1372147] fatal error: file not found.: file /Users/megastep/src/ak/AudioKit/AudioKit/Common/Nodes/Playback/Sampler/AKSampler.swift, line 58

This is my ViewController.swift

```
import UIKit
import AudioKit

class ViewController: UIViewController {
    
    var sampler = AKSampler()

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        try! sampler.loadWav("samples/KICK_1")
        AudioKit.output = sampler
        AudioKit.start()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}
```

**Comment by aure** [comment]
Hi, so the file it is looking for is under the home directory @megastep who makes our framework file so its possible that it gets baked in when he makes them.  But, I think what's really happening is that its not finding the file in a number of local directories first and finally complaining with that error that you see.  Make sure that you actually have that file including in your project target.

**Comment by megastep** [comment]
This is likely related to debugging information with file paths embedded in the framework.

**Comment by aure** [comment]
I've just confirmed this is the error you get when you don't properly include the wav file in your project, so I will call this issue addressed.  Reopen if necessary.
