### ISSUE TITLE
module file build issue

### ISSUE THREAD

**Issue by kevin-coelho** [audiokit/AudioKit#797]
Playground execution failed: error: Introduction and Hello World.xcplaygroundpage:6:8: error: module file was created for incompatible target x86_64-apple-macosx10.12: /Users/katc/Library/Developer/Xcode/DerivedData/AudioKit_for_macOS-dxtrfxdmuufmdvdzkdccjabhinsg/Build/Products/Debug/AudioKit.framework/Modules/AudioKit.swiftmodule/x86_64.swiftmodule

Tried wiping DerivedData and building again, no fix

**Comment by aure** [comment]
Have you set the playground to be for macOS?  The default is iOS.

**Comment by aure** [comment]
Just reproduced this and option-cmd-1 shows the file utilities and if you change the Playground Settings to "macOS" it will work, so I am calling this issue addressed.
