### ISSUE TITLE
Issues with iOS RecorderDemo, Mic clicking noise

### ISSUE THREAD

**Issue by jacobdfriedmann** [audiokit/AudioKit#798]
I've been using AudioKit for a couple days, primarily on the simulator and noticed some issues when running on an actual device.

First, in the recorder demo, the session category is set with the `.defaultToSpeaker` option before `AudioKit.start()` is called. This actually seems to have no effect because `AudioKit.start()`–as a matter of course–will set the session category itself without the `.defaultToSpeaker` option. This will mean that on the phone playback comes through the earpiece (default for `.playAndRecord` sessions) instead of the speaker. This I can fix pretty easily and will submit a small pull request for.

The second issue is a bit more out of my depth. When I do successfully set the session to play through the speaker instead of the earpiece, the mic recording contains clicking or rattling noise (maybe mic saturation or feedback?) even when booster has gain set to 0. This is hard to tell in demo code as is because the `player` node is routed through a moog ladder, but if you were to bypass the moog ladder:

```
// Will set the level of microphone monitoring
        micBooster!.gain = 0
        recorder = try? AKNodeRecorder(node: micMixer)
        player = try? AKAudioPlayer(file: (recorder?.audioFile)!)
        player?.looping = true
        player?.completionHandler = playingEnded
        
        moogLadder = AKMoogLadder(player!)
        
        let mainMixer = AKMixer(moogLadder!, micBooster!)
        
        AudioKit.output = mainMixer
        AudioKit.start()

        moogLadder.stop() // bypass
```

you'll hear the clicking noise during playback in the demo code as well. I have tried a bunch of things, mostly shooting in the dark and cannot for the life me get rid of the noise without reverting the session to do playback through the earpiece, which is not ideal.

I suppose you could maybe address it by switching the audio session between earpiece and speaker for recording vs. playback, but this would cause the engine to restart and doesn't seem ideal. It seems like something else must be going on.

Happy to help in any way I can, but like I said, I am a bit out of my depth. Thanks!

p.s. I am using an iPhone 7 running iOS 10.2.1

**Comment by aure** [comment]
I'll take a look at the demo with the moog ladder bypassed.

**Comment by aure** [comment]
I gotta say, I don't experience this problem, could it be your phone?  Reopen if you have checked another device and it continues.

**Comment by marcosgriselli** [comment]
@jacobdfriedmann Did you ever solved this issue? I'm having the exact same problem. Issue has to be `.defaultToSpeaker` option as I don't get the clicking noise while recording with my headphones on.

**Comment by sihwapark** [comment]
@aure I have the same issue. In my iphone7, `.defaultToSpeaker = true' always cause clicking noise in a recorded sound but `.defaultToSpeack = false' doesn't. My temporary solution is toggling `defaultToSpeaker` whenever I record or playback as below:

`
AKSettings.defaultToSpeaker = false // before when you begin to record.
// AKSettings.defaultToSpeaker = true // before when you playback a recorded file

do {
     try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, with:AKSettings.computedSessionOptions())
} catch {
     print("Filed to change AVAudioSessionCategoryOptions")
}
`

However, with the above trick, it is impossible to record additionally while you are playing a recorded file.

Is there any solutions for it?

**Comment by aure** [comment]
@sihwapark Can you make a new issue for this?  I hate glomming onto old closed issues and this one was started almost a year ago.
