### ISSUE TITLE
Node Output Plot Playground not working

### ISSUE THREAD

**Issue by denisb411** [audiokit/AudioKit#803]
See this:

<img width="1280" alt="screen shot 2017-03-17 at 18 59 27" src="https://cloud.githubusercontent.com/assets/13735079/24064593/14f64cca-0b44-11e7-8705-3b03d64683d3.png">

**Comment by aure** [comment]
If you see at the top of the screen it has said that your build of AudioKit has failed.  That's the problem and the output of the playground doesn't help me debug that. Provide more information and I'll reopen the issue.  Or, I can do a screenshare with you if you can do that.
