### ISSUE TITLE
Audio sync / timing / looping is wrong

### ISSUE THREAD

**Issue by trevor-sonic** [audiokit/AudioKit#807]

**Comment by trevor-sonic** [comment]
(accidentally pressed enter with empty post. so I closed the issue)

**Comment by trevor-sonic** [comment]
I'm trying to do a metronome with audio file for  accurate timing.
in the code below I have a metronome sound perfectly sliced in DAW for 122BPM and song is 122BPM and it is perfectly start from 1st beat.

When I play them as the code below it lose sync after 15 sec and later it is more noticeable.
If I use the 1 beat of the 1 bar metronome by .endTime properties the timing issue is drastically noticeable.

As metronome  was slower/behind the song; I tweak the bpm to 123.03 but it always lose the sync.

I could achieve to perfect sync without AudioKit. By using audio node + pcm buffer etc. and it's super accurate till the end of the song 4 minutes! 

I want to use AudioKit for improve my code but how to improve this? I can test and improve AK.
I can provide metronome + song samples if necessary.

    let file1 = try AKAudioFile(readFileName: "122bpm.wav", baseDir: .resources)
    let file2 = try AKAudioFile(readFileName: "one_life.mp3", baseDir: .resources)

    var player1 = try AKAudioPlayer(file: file1)
    var player2 = try AKAudioPlayer(file: file2)

    // uncomment line below for dividing 1 bar metronome sound to 1 beat click
    //player1.endTime = Double (60.0 / 123.03)
    player1.looping = true

    var mixer = AKMixer(player1, player2)

    AudioKit.output = mixer
    AudioKit.start()

**Comment by aure** [comment]
Yeah, if you can share the project, I'll be able to look at this some more.  It seems like there's some time lost in the looping of AVAudioPlayer (under AKAudioPlayer).

**Comment by trevor-sonic** [comment]
I simplified for you to test. I work on playground. It's enough to create a new play ground page and paste this code. In the zip file there are 2 files metronome and song . Drag them into resources folder. I hope that helps to find the calculation issue.   

[song122bpm_metronome122bpm.zip](https://github.com/audiokit/AudioKit/files/856584/song122bpm_metronome122bpm.zip)



     // Metronome sync test
    import PlaygroundSupport
    import AudioKit

    let file1 = try AKAudioFile(readFileName: "122bpm.wav", baseDir: .resources)
    let file2 = try AKAudioFile(readFileName: "one_life.mp3", baseDir: .resources)

    var player1 = try AKAudioPlayer(file: file1)
    var player2 = try AKAudioPlayer(file: file2)

    // below  * 1 is 1 beat,      * 4 is 1 bar
    player1.endTime = Double (60.0 / 122) * 1
    player1.looping = true

    var mixer = AKMixer(player1, player2)

    AudioKit.output = mixer
    AudioKit.start()

    public class PlaygroundView: AKPlaygroundView {
    public override func setup() {
          player1.play()
          player2.play()
        }
    }


    PlaygroundPage.current.liveView = PlaygroundView()
    PlaygroundPage.current.needsIndefiniteExecution = true

**Comment by aure** [comment]
Hi Trevor, thanks very much for the playground.  I have "fixed" this issue, in that I got the playground to work.  But it, kind of break the AKAudioPlayer's completion handler stuff.  While I figure out the best way to make this a general fix, I'll tell you what I did and maybe it will help you.  Basically on line 426 of AKAudioPlayer, I hardcoded looping:              if let buffer = audioFileBuffer {
                internalPlayer.scheduleBuffer(buffer,
                                              at: atTime,
                                              options: [.interrupts, .loops],
                                              completionHandler: internalCompletionHandler)

Which is not what we want, but like I said, it works. I'll work on this a bit more tonight but I wanted to at least respond with my progress and that I'm pretty confident we'll figure something out that will get you through this problem.

**Comment by trevor-sonic** [comment]
Hi Aure, I really appreciate your help. Be for you fix this issue; I just like to tell a bit more about the process I followed to add (maybe) some useful function to AK.
I've inspired very much from this resource to have an exact timing.
https://github.com/AlexShubin/MetronomeIdea/blob/master/PlaybackTest/ViewController.swift
By the way the think I liked in this code that using an audio file within a longer buffer.
It means; click sample is 0.01 but it sets the buffer according the BPM as result looping perfectly.
Can we implement in AK kind of override timing/buffer to define the time we want?

    
    // click.wav is tiny wav, duration let's say around 0.05 sec.
    let clickFile = try AKAudioFile(readFileName: "click.wav", baseDir: .resources)

    let metroPlayer = try AKAudioPlayer(file: clickFile)

    // normally this definition makes nothing because wave file is shorter than endTime
    metroPlayer.endTime = Double (60.0 / 122) * 4

    //(Alias code)
    // But if we set timeOverride = true buffer will be set to calculated value
    metroPlayer.timeOverride = true
    metroPlayer.looping = true

Or any method name to allow this buffer loop size.
I hope you like this idea. I think it can be useful in many different situations. 
Maybe in this way you'll not have to modify the code (around line 426)
Thank you

**Comment by aure** [comment]
I would love for you to improve AudioKit with more exact timing.  We're serious about open source and letting people add to AudioKit as they need.  So please, yes, contribute some code!

**Comment by trevor-sonic** [comment]
I do want to contribute, sure for timeOverride etc. but for the issue I've asked for I couldn't  get trough :-/ 
I'll appreciate to see a new release with correct sync.
Thank you very much.

**Comment by aure** [comment]
I believe this latest merged pull request addresses this problem well, so I will close this issue for now.  Kudos to @sweetmandm for a world-class pull request.
