### ISSUE TITLE
AKMicrophone.setDevice() doesn't seem to work after the fact

### ISSUE THREAD

**Issue by pcbeard** [audiokit/AudioKit#808]
I'm looking for a solution for configuring the preferred input before creating an AKMicrophone instance. Calling `AKMicrophone.setDevice()` doesn't seem to change anything once `AudioKit.start()` has been called. My current workaround is to call `AVAudioSession.setCategory()` before accessing `AudioKit.availableInputs`

     try? AKSettings.session.setCategory(AVAudioSessionCategoryPlayAndRecord, with: .mixWithOthers)
     if let inputs = AudioKit.availableInputs, !inputs.isEmpty {
      if let device  = inputs.last {
        try? AudioKit.setInputDevice(device)
      }
    }

This is needed, because all of the available inputs don't show up unless `setCategory()` has been called already. Ideally, one could call `AKMicrophone.setDevice()` anytime after the audio engine has started, and things would just work.

**Comment by aure** [comment]
I don't really know what to do about this.  What do you think would be a good solution?  It's more like a basic design issue with AVAudioEngine than anything AudioKit could be doing better, isn't it?

**Comment by pcbeard** [comment]
Isn't it possible to detect the configuration change using the AVAudioEngineConfigurationChangeNotification? Changing the input device will likely change the sampling rates, so I think this comment is relevant:

> When the engine's I/O unit observes a change to the audio input or output hardware's
> channel count or sample rate, the engine stops itself (see `AVAudioEngine(stop)`), and
> issues this notification.
> The nodes remain attached and connected with previously set formats. However, the app 
> must reestablish connections if the connection formats need to change (e.g. in an 
> input node chain, connections must follow the hardware sample rate, while in an output only
> chain, the output node supports rate conversion).

So, to properly respond to input routing changes, which may include hardware sample rate changes, we'd need to restart the engine, and potentially tear down all the nodes.

**Comment by pcbeard** [comment]
Apologies, I see that you are already handling route changes in AudioKit.restartEngineAfterRouteChange.

**Comment by aure** [comment]
So, you're making pull requests and you're knowledgeable about the code base, do you think there's anything we can do to address this issue?  If yes, let me know, if not, can we close this issue.  And have I inviited you to slack?  Would you like to be part of the AudioKit Slack?

**Comment by pcbeard** [comment]
I'm working on it. Please do invite me to the Slack. I think the recent change I made to the move the notification handlers to the main queue has fixed most of the issues I've been seeing.

**Comment by aure** [comment]
Can you email your real name and email address?

**Comment by aure** [comment]
Any reason to keep this issue open?  As far as I know, you are the only person working on it.  Reopen if you want.
