### ISSUE TITLE
Filter / Audiobus examples gives a compile error: "no such file or directory: '...AudioKit/iOS/Audiobus/Audiobus.swift'"

### ISSUE THREAD

**Issue by o-g-sus** [audiokit/AudioKit#810]
I added the Audiobus library via Cocopads, then some "Audiobus.swift" file seems to get created automatically, which does not work, even exist.

Has anybody a solution for this? What am I doing wrong?

**Comment by aure** [comment]
If you want to use Audiobus, you need that file.  I'm not sure if its included with Cocoapods, but it is not auto-generated and you can grab it here:  https://github.com/audiokit/AudioKit/blob/master/AudioKit/iOS/Audiobus/Audiobus.swift

You should be able to just put a copy in your folder and have things work.  Reopen the issue if you have any problems.

**Comment by o-g-sus** [comment]
Thanks, I just saw, that it’s in the Source code zip :)
Maybe copy that file to the AudioKit-iOS examples, that’s where I started and missed that file …

Awesome audio framework and awesome documentation (playground) by the way !!!
I was using libPD/PD so far, but my next project will use AudioKit finally :)

Cheers,
Oliver



Please rate our apps in the iTunes store !!

Info:  		http://mominstruments.com
fluXpad:		https://itunes.apple.com/us/app/fluxpad/id975033604
WretchUp: 	https://itunes.apple.com/us/app/wretchup/id928543264
Elastic Drums:	https://itunes.apple.com/us/app/elastic-drums/id817419955

Making Apps That Make Music: https://www.facebook.com/groups/271117483063480
