### ISSUE TITLE
Pause and Resume recording

### ISSUE THREAD

**Issue by lususvir** [audiokit/AudioKit#813]
Is there a way for the AKNodeRecorder to stop recording, and then resume recording and continue to append audio data to the end of the audio file? So basically a pause and resume effect.

**Comment by ashusath** [comment]
@lususvir Hey, were you able to achieve this?

**Comment by OfTheWolf** [comment]
If you create AKNodeRecorder(node: mic) instance each time on pause and play it will restart the record file. But i have seen that if you create instance once and just call recorder.record() / recorder.stop() on play / pause it will append to the record file. I don't know if there is a doc about this. i noticed that just by experience.
