### ISSUE TITLE
Swift 3.1

### ISSUE THREAD

**Issue by pardeike** [audiokit/AudioKit#814]
Hi, 
I followed the instructions on building AudioKit but I use the latest Xcode and it complains about audiokit not working with Swift 3.1. Am I missing something here?

**Comment by aure** [comment]
How are you using AudioKit, from source, as a CocoaPod, from Carthage?  AudioKit works with the latest official releases.  Are you using Xcode beta?

**Comment by pardeike** [comment]
Yes, I have a project using the latest beta of Xcode 8.3 and I tried AudioKit via Carthage.

**Comment by fobin** [comment]
This seems to be the issue with yesterdays release of 10.12.4 and Xcode updating using swift 3.1.

![unspecified](https://cloud.githubusercontent.com/assets/1096951/24391494/1e9aa792-1398-11e7-91f9-b8c8e26ed7d5.png)
