### ISSUE TITLE
AKAudioPlayer completionHandler gets called before the audio is played

### ISSUE THREAD

**Issue by pavan309** [audiokit/AudioKit#817]
Hi

**Background/Setup**

We are recording audio from a device's microphone and storing it in a file (via AVAudioRecorder) while playing the realtime buffered waveform through AudioKit's EZAudioPlot and AKNodeOutputPlot. For playback, we are playing back a recorded m4a from a file using AKAudioPlayer with the same visualization of whatever is being output from the device's speaker for visual feedback of the audio.

**Issue**

AKAudioPlayer's completionHandler gets called as soon as the play() function is called without any audio output. This happens only after AVAudioRecorder is used to record an audio. Until AVAudioRecorder is used AKAudioPlayer's completionHandler works fine as expected. Issue persists for all the audio files until the app is relaunched.

I am unable to figure out reason why this is happening. Please help me if I am missing anything here or this is a known issue. I am happy to provide the sample code if needed.

PS: This is only happening on devices iOS 10.2 and above.

**Comment by pavan309** [comment]
I am using AudioKit 3.5.3, Xcode 8.2 on iOS 10.2.1

**Comment by aure** [comment]
Hi, I see you've also posted to google group.  I'm not really sure what to do to fix this issue for you.  Perhaps sharing the code will help.

**Comment by pavan309** [comment]
Hi Aure,

Sorry for posting in both places. Some how I missed google group before posting it here.

I have attached the code as an attachment to this comment. I was unable to attach AudioKit framework as GitHub is allowing me to only attach files below 10mb. So can you please add the framework after downloading.

To give you more context on this issue, it is only happening only on devices iOS 10.2 and above. Some times its device specific too, we are unable to reproduce in iPhone 5 and 5 SE even on iOS 10.2.1

Regarding the sample code, please record something before playing.
[SampleAudio.zip](https://github.com/audiokit/AudioKit/files/870574/SampleAudio.zip)

Thank you for taking time and help us with this issue. :)

**Comment by aure** [comment]
No worries about posting in two places, my apologies for not responding quicker.

**Comment by pavan309** [comment]
Hi,

Just figured out the issue on why it is happening, raised a PR to fix it. Not sure on larger scope of the project if that change will work or not.

Please let me know if you are happy with the change or not.

Thanks.

**Comment by aure** [comment]
Thanks for the PR!
