### ISSUE TITLE
Custom build with CocoaPods to avoid breaking projects

### ISSUE THREAD

**Issue by Legoless** [audiokit/AudioKit#821]
Currently with the release of iOS 10.3 and Swift 3.1 AudioKit causes projects to fail building, as it is compiled with Swift 3.0.2. I propose a solution that over CocoaPods AudioKit is built from repository using the provided scripts that build framework on the fly. This ensures that AudioKit is built from source everytime Swift version changes instead of copied from static resource on GitHub, which is outdated.

The podspec would need to be updated to something like this:
```
Pod::Spec.new do |s|
    ...
    s.preserve_paths = "AudioKit.framework"
    s.vendored_frameworks = "AudioKit.framework"
    s.prepare_command = <<-CMD
       ./frameworks/build_frameworks.sh
        cp -a ./AudioKit-iOS/AudioKit.framework ./AudioKit.framework
    CMD
end
```

**Comment by aure** [comment]
I can say that we'd at least want to limit the building to the OS that you actually need, but even so I wonder if this would be too slow for Cocoapods users.  We're trying to be on top of the Swift change and come out with a working build soon.

**Comment by Legoless** [comment]
Definitely, this was just an example, how this can be done. Surely we do not need to build it for all platforms. Likely the `build_frameworks.sh` script would need to be modified to take a parameter which platform to build. I think it's possible to do something like this:

```
s.ios.prepare_command = ...
s.tvos.prepare_command = ...
```

As for the build time, it is not really a problem. Both [Realm](https://github.com/realm/realm-cocoa/blob/master/Realm.podspec) and OpenCV do this. Alternatively, this could be a separate Podspec, like `AudioKitSwift` or something like that, while keeping the original one intact.

**Comment by aure** [comment]
So, just to keep this moving, can you make us a new podspec that would do this?  I don't like have a separate podspec.  For now, we did come out with a release within a day of the new Xcde being officially released. Re-open the issue with new info... ore create a pull request with an alteration to the podspec.  thanks!

**Comment by tonyashah** [comment]
Aure, 

You mention "for now, we did come out with a release within a day of the new Xcde being officially released."

My XCode updated this AM, and not my project won't build due to the AudioKit module being compiled with Swift 3.0.2 (vs 3.1).  I have tried removing / re-installing via my Podfile (currently pop 'AudioKit', '~.3.5'), but no dice.  Any suggestions?  I suppose I can simply stop using Cocoapods & compile from source, but I thought I would double-check ,first just in case I a missing something...

Thanks in advance!

**Comment by aure** [comment]
@tonyashah I think your Xcode has probably got a cached version of AudioKit somewhere.  It can be super persistent about holding on to old versions which is pretty annoying.

**Comment by tonyashah** [comment]
Sure sounds plausible to me, thanks for the tip!  After installing / removing the framework with Cocoapods (clean, restarting, searching for rogue AudioKit mentions, etc), I finally opted to just manually move the a copy of framework 3.5.4 over, and it worked.  

Cheers!
