### ISSUE TITLE
EZAudioPlotGL - calling pauseDrawing or clear does nothing

### ISSUE THREAD

**Issue by joshbruhin** [audiokit/AudioKit#823]
I have an EZAudioPlotGL, which is working fine, i.e. the waveform is displayed. But, I cannot pause or clear the drawing. When calling either of these (.pauseDrawing or .clear), nothing happens, it just keeps on drawing.

**Comment by aure** [comment]
I'd have to see more, do you have an example project to share?

**Comment by joshbruhin** [comment]
We're you able to get the example project running? I tried subclassing EZAudioPlotGL and am having the same problem.

**Comment by aure** [comment]
Yeah, I was able to run the project.  I don't know much about EZAudioPlotGL, just enough to get AudioKit plots working.  Looks like stop is just telling the display link to stop.  That might not be enough anymore, not sure.  We added a restHistoryBuffers function to the plots the other day to do a clear.

**Comment by joshbruhin** [comment]
Ok, thanks for looking. Is there another plot type you'd recommend using instead? Just looking for a basic 'waveform' plot with rolling history.

**Comment by aure** [comment]
AKNodeOutputPlot or AKRollingOutputPlot if you just want to plot what's going to the speaker.

**Comment by aure** [comment]
Reopen the issue if those plots don't work out for you.
