### ISSUE TITLE
Error when calling player.audioFile.exportAsynchronously

### ISSUE THREAD

**Issue by joshbruhin** [audiokit/AudioKit#824]
I get the following error when running the RecorderDemo example app (and when running the same code in my own app). Here's the error and the code is below:

AKNodeRecorder: Recording Stopped.
2017-03-28 10:40:00.427117 SkyWriter[81813:2322334] [] << ModelSpecific >> __CelestialGetModelSpecificName_block_invoke: NULL model (no model name?), pretending this is N94
2017-03-28 10:40:00.428737 SkyWriter[81813:2322334] [] << ModelSpecific >> CelestialCFCreatePropertyListForModelAndBundleIdentifier: Device not found (N94); Falling back to Default model
ERROR AKAudioFile export: cannot create AVAssetExportSession!...
Export Failed Optional(Error Domain=NSURLErrorDomain Code=-3000 "(null)")

THE CODE:
        let recordedDuration = player != nil ? player?.audioFile.duration  : 0
        if recordedDuration! > 0.0 {
            recorder?.stop()
            player?.audioFile.exportAsynchronously(name: "TempTestFile.m4a", baseDir: .documents, exportFormat: .m4a) {_, error in
                if error != nil {
                    print("Export Failed \(error)")
                } else {
                    print("Export succeeded")
                }
            }
        }

**Comment by aure** [comment]
I believe this is a duplicate issue.

**Comment by joshbruhin** [comment]
Can you point me to original issue/resolution? I searched and couldn't find. Thank you so much!

**Comment by aure** [comment]
There are two open issues https://github.com/audiokit/AudioKit/issues/792 https://github.com/audiokit/AudioKit/issues/754

**Comment by joshbruhin** [comment]
Upgrading to 3.5.4 (thru cocoapods) solved the issue.
