### ISSUE TITLE
Xcode 8.3 Swift 3.1

### ISSUE THREAD

**Issue by pjvea** [audiokit/AudioKit#825]
Hey! :) 

After I updated a project to 3.5.4 for Xcode 8.3 compatibility I'm seeing a crash on an iPhone 6S Plus running iOS 10.3.

The following code worked previously.

```
        let mic = AKMicrophone()
        
        fft = AKFFTTap(mic)
        
        amplitudeTracker = AKAmplitudeTracker(mic)

        highPassFilter = AKHighPassFilter(mic)

        // Set Parameters of Hi Pass filter
        highPassFilter?.cutoffFrequency = 1000 // Hz
        highPassFilter?.resonance = 0 // dB

        freqTracker = AKFrequencyTracker(highPassFilter!, hopSize: 7000, peakCount: 8000)
        highPassFilter?.play()
        
        // Turn the volume all the way down on the output of amplitude tracker
        let noAudioOutput = AKMixer(amplitudeTracker!)
        noAudioOutput.connect(freqTracker!)
        noAudioOutput.volume = 0
        
        AudioKit.output = noAudioOutput

        AudioKit.start()
```

The crash is 

```
*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10875'
```

I _think_ it has something to do with the format but I can't confirm that. 

Any help would be appreciated. :)

**Comment by aure** [comment]
Ugh, sorry to hear that.  This isn't enough info to go on, but I am about to convert several apps so perhaps I'll find the same issue.

**Comment by pjvea** [comment]
No problem! I will continue to look into it as well.

**Comment by aure** [comment]
I think the problem will be resolved if you declare the mixer "noAudioOutput" as an instance variable instead of inline.  Reopen this issue if not.
