### ISSUE TITLE
Swift 3.1 AKFrequencyTracker crash

### ISSUE THREAD

**Issue by dkun7944** [audiokit/AudioKit#828]
AKFrequencyTracker was working before the Swift 3.1 update. Just crashes now when AudioKit.start() is called. Console is printing this:

`malloc: *** error for object 0x103c47850: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug`

Stack trace:

<img width="992" alt="screen shot 2017-03-30 at 6 16 09 pm" src="https://cloud.githubusercontent.com/assets/2880086/24528581/2a4e398a-1575-11e7-9790-ef0876f401b4.png">

**Comment by dkun7944** [comment]
It looks like AKFrequencyTrackerDSPKernel thinks member variable `ptrack` is non-null on init, so it calls `sp_ptrack_destroy` which crashes because `ptrack` hasn't been allocated. Not sure why `ptrack` would be non-null on init. 

The problem file (so others don't have to dig for it): https://github.com/audiokit/AudioKit/blob/master/AudioKit/Common/Nodes/Analysis/Frequency%20Tracker/AKFrequencyTrackerDSPKernel.hpp

**Comment by aure** [comment]
Could be that Swift 3.1 fixes a bug that we were working around.  I'll look into this.  Good that you found a temp fix.

**Comment by aure** [comment]
So, I tested AKFrequencyTracker by running the playground for it, and it worked fine. Is this on a device only?

**Comment by dkun7944** [comment]
Yes, running it on an iPhone 6S with iOs 10.3

**Comment by aure** [comment]
I think the problem may actually be in your view controller, or wherever you're setting up the signal chain.  Are any of the nodes declared with a "let xxx =" inline instead of being instance variables of the class?  There was a memory leak that was fixed, but now requires that you explicitly keep a reference to the nodes you need active.  I'm 99% sure this is the issue, but reopen the issue if not.

**Comment by dkun7944** [comment]
@aure All of my nodes are declared as instance variables. However the AKMixer is an instance variable of a singleton. Would this cause the same memory leak?

**Comment by aure** [comment]
Yeah, please add me to the repo.  It's got to be something!

**Comment by dkun7944** [comment]
https://github.com/dkun7944/pitch-ios-public

**Comment by aure** [comment]
I just tested in the simulator and it works, will try an actual phone next.

**Comment by dkun7944** [comment]
Did you uncomment the line in the temporary fix I did?

**Comment by aure** [comment]
It crashes on my 7+.  I am using my own copy of AudioKit, so I don't think I am using your fix.

**Comment by dkun7944** [comment]
Ah ok. Good to hear you were able to reproduce it. Let me know if I can be of any help in getting this resolved.

**Comment by aure** [comment]
I think it might have to do with calling AudioKit.start() twice, but right now I am waiting to update my device to 10.3

**Comment by dkun7944** [comment]
Hm ok, I have it setup such that AudioKit.start() won't be called two times in a row, but will be called each time the app re-enters the foreground.

**Comment by aure** [comment]
I made sure to start only once and it still crashes, so nvm that idea.

**Comment by aure** [comment]
The microphone analysis example project works just fine which is why this is so strange.

**Comment by dkun7944** [comment]
Is this the same exact crash that occurs when you don't make the frequency tracker an instance var?

**Comment by aure** [comment]
No, that seems to be wrong advice as well.

**Comment by aure** [comment]
Maybe you're just right and we don't need that destroy line anymore

**Comment by dkun7944** [comment]
Should we be worried about a memory leak?

**Comment by dkun7944** [comment]
No prob. AudioKit is rock solid otherwise so that's understandable. Glad we got this fixed.
