### ISSUE TITLE
Distortion when using more than 2 instances of AKFMOscillator at once

### ISSUE THREAD

**Issue by arsone** [audiokit/AudioKit#83]
I'm working on a synth app that includes a bank of 8 FM oscillators. Whenever I activate more than 2 of them I start getting digital noise. Initially the effect was only in Simulator and not on device, although now it occasionally happens on the device as well. The noise is much more pronounced on Simulator. It doesn't appear to be destructive interference, as it happens even when all 8 oscillators are set to the same frequency and mod index.

link to sound sample (recorded from simulator using SoundFlower): https://soundcloud.com/ars-one/aksample-distortion

link to repo for project: https://github.com/arsone/swarmatron

Not sure if it's a memory management issue, or an issue with handling multiple simultaneous audio threads, or if I just screwed something up in my implementation, but any guidance you guys could provide would be much appreciated.

**Comment by arsone** [comment]
Looks like it was an amplitude summing problem on my end. Apologies - fixed my code and am closing the issue. There are still some irregularities with audio output in Simulator, although they seem to be universal and not specific to AudioKit.

**Comment by aure** [comment]
Hi there, first of all I have to apologize for not seeing your original message.  Not sure why Github never notified me of the issue.  I'm glad you figure out the problem and please feel free to email me as well if you have any issues in the future. aure at aure dot com or aure at audiokit dot io will work.  I have checked out the Swarmatron project so next time it will be easy for me to help.  Sounds like a cool idea.
