### ISSUE TITLE
Is it possible to change AudioKit's input device just like EZAudio? 

### ISSUE THREAD

**Issue by leejust** [audiokit/AudioKit#830]
I just find availableInputs in AudioKit content only one device:build-in. How to get other inputs such as font or back ?

**Comment by aure** [comment]
On the actual device that's all you see as well?  ie. not the simulator

**Comment by leejust** [comment]
I use iPhone 6s and show the availableInputs is one device

**Comment by leejust** [comment]
But using EZaudio the inputs content three.So if it is possible to get more inputs in audioKit, please give me some advice.Thank you.

**Comment by WebberLai** [comment]
First , I have to thank you that you create a such great framework

And I also have the same need as this issue
ie. When using external sound card via lightning cable , in EZAudio still not enough for this case, if you just select specific device , you also need select specific inputs
For me , I use Apogee Quartet recording interface , It has 4 analog input , so when I use Garage band ,I have to select which input is I want , not just select Quartet. 
 
My suggestion is add a "Setting Input/Output" example , Like this image

![maestro-ios-quartet-input-800](https://cloud.githubusercontent.com/assets/1185079/24688225/29ef67ea-19f1-11e7-921b-514a68bcaca2.jpg)

**Comment by leejust** [comment]
I try to use EZAudio to control inputs and use AudioKit to process audio and find it work! But sometimes when I stop and reopen the AudioKit ,I get a crash like this:

> Error: Failed to fill complex buffer in float converter ('insz')

I check all my codes and didn't find any problem.The only change is that I add EZAudio to my program . I replace EZAudio included in AudioKit to source  [EZAudio](https://github.com/syedhali/EZAudio ) and until now I don't get that crash anymore.


And in my project I get another crash:

> Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: hwFormat'

and this is a small probability of crash when I run the program on iPhone 7(p) .I try it on 6 and iPad Pro and it work fine. 

I am a complete beginner to audio progressing so I don't have any idea. Maybe you can do something about this.

Finally,I appreciate all you did. AudioKit is a great Project. Best wishes to you.

**Comment by aure** [comment]
@leejust I'd love to see how you use EZAudio to control inputs and pass the processing along to AudioKit.  Can you either post the relevant code here or invite me to your project (or link to it if it is public)?  Thanks.

**Comment by leejust** [comment]
@aure I write a demo using OC and all the code as follows:

> #import "ViewController.h"

> #import <AudioKit/AudioKit-Swift.h>
> 
> #import <AudioKit/EZAudio.h>
> 
> @interface ViewController ()<UIPickerViewDelegate, UIPickerViewDataSource, EZMicrophoneDelegate>
> 
> @property (nonatomic, strong)AKNodeOutputPlot *plot;
> 
> @property (nonatomic, strong)AKNode *akMic;
> 
> @property (nonatomic, strong) UIPickerView *pickerView;
> 
> @property (nonatomic, strong) EZMicrophone *ezMic;
> 
> @property (nonatomic, strong) NSArray <EZAudioDevice *>*inputs;
> 
> @end
> 
> #define rgba(r, g, b, a) [UIColor colorWithRed:r / 255.0 green:g / 255.0 blue:b / 255.0 alpha:a]
> 
> @implementation ViewController
> 
> - (void)viewDidLoad {
>     [super viewDidLoad];
>     
>     self.akMic = [[AKMicrophone alloc] init];
>     
>     [AudioKit setOutput:self.akMic];
>     
>     self.plot = [[AKNodeOutputPlot alloc] init:self.akMic frame:CGRectMake(2, 60, self.view.frame.size.width - 4, self.view.frame.size.width* 70.f / 667.f - 4) bufferSize:1024];
>     
>     self.plot.plotType = EZPlotTypeBuffer;
>     
>     self.plot.shouldFill = YES;
>     
>     self.plot.backgroundColor = [UIColor clearColor];
>     
>     self.plot.shouldMirror = YES;
>     
>     self.plot.color = rgba(95,218,229,1);
>     
>     [self.view addSubview:self.plot];
>     
>     self.pickerView = [[UIPickerView alloc] initWithFrame:CGRectMake(0, 60 + self.view.frame.size.width* 70.f / 667.f - 4 + 200, self.view.frame.size.width, self.view.frame.size.width* 200.f / 667.f)];
>     
>     [self.view addSubview:self.pickerView];
>     
>     self.pickerView.delegate = self;
>     
>     self.pickerView.dataSource = self;
>     
>     self.ezMic = [EZMicrophone microphoneWithDelegate:self];
>     
>     [self.ezMic setOutput:[EZOutput sharedOutput]];
>     
>     [AudioKit start];
> 
>     // Do any additional setup after loading the view, typically from a nib.
> }
> 
> 
> - (void)viewDidAppear:(BOOL)animated {
>     
>     [super viewDidAppear:animated];
>     
>     self.inputs = [EZAudioDevice inputDevices];
>     
>     [self.pickerView reloadAllComponents];
> 
> 
> }
> 
> 
> 
> 
> 
> #pragma mark - UIPickerViewDelegate
> 
> - (NSInteger)numberOfComponentsInPickerView:(UIPickerView *)pickerView {
>     return 1;
> 
> }
> 
> 
> - (NSInteger)pickerView:(UIPickerView *)pickerView numberOfRowsInComponent:(NSInteger)component {
> 
>     return self.inputs.count;
> 
> }
> 
> //           setDevice
> - (NSString *)pickerView:(UIPickerView *)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component {
> 
>     return self.inputs[row].name;
> 
> }
> 
> - (void)pickerView:(UIPickerView *)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component {
> 
>     [self.ezMic setDevice:self.inputs[row]];
> 
> }
> 
> 
> #pragma mark - EZMicrophoneDelegate
> - (void)microphone:(EZMicrophone *)microphone
>   hasAudioReceived:(float **)buffer
>     withBufferSize:(UInt32)bufferSize
> withNumberOfChannels:(UInt32)numberOfChannels
> {
>     
> //    __weak typeof (self) weakSelf = self;
> //    
> //    dispatch_async(dispatch_get_main_queue(), ^{
> //        
> //        [weakSelf.audioPlot updateBuffer:buffer[0] withBufferSize:bufferSize];
> //        
> //        
> //    });
>     
> }
> 
> //------------------------------------------------------------------------------
> 
> - (void)microphone:(EZMicrophone *)microphone hasAudioStreamBasicDescription:(AudioStreamBasicDescription)audioStreamBasicDescription
> {
>     
>     //    [MFEZAudioUtilities printASBD:audioStreamBasicDescription];
>     
> }
> 
> //------------------------------------------------------------------------------
> 
> - (void)microphone:(EZMicrophone *)microphone
>      hasBufferList:(AudioBufferList *)bufferList
>     withBufferSize:(UInt32)bufferSize
> withNumberOfChannels:(UInt32)numberOfChannels
> {
>     
>     
>     
> }
> 
> 
> //------------------------------------------------------------------------------
> 
> 
> 
> - (void)microphone:(EZMicrophone *)microphone changedDevice:(EZAudioDevice *)device
> {
>     
>         __weak typeof(self) weakSelf = self;
>     
>         dispatch_async(dispatch_get_main_queue(), ^{
>     
>             NSLog(@"mic output change");
>     
>             weakSelf.inputs = [EZAudioDevice inputDevices];
>     
>             [weakSelf.pickerView reloadAllComponents];
>     
>         });
>     
> }
> 
> 
> - (void)outputDeviceChanged:(NSNotification *)aNotification
> {
>     
>     NSLog(@"output device change");
>     
>     dispatch_async(dispatch_get_main_queue(), ^{
>         
>         self.inputs = [EZAudioDevice inputDevices];
>         
>     });
>     
> }
> 
> 
> - (void)didReceiveMemoryWarning {
>     [super didReceiveMemoryWarning];
>     // Dispose of any resources that can be recreated.
> }
> @end
> 

And scroll the pickerView you can change the input mic so maybe it is not a native way to solve this problem but it really work.Hope this can help you.

**Comment by aure** [comment]
@leejust Huh, this looks like it just takes the AudioKit microphone and sets it to the AudioKit output.  Maybe you stripped out the post processing.  You could pick the AudioKit input device directly the "AudioKit way", but are you seeing more options in the EZAudio input device list?

**Comment by leejust** [comment]
@aure I don't know how to get the input device list without using EZAudio. availableInputs in AudioKit is only one device.So I have to change EZMicrophone's input device and don know the reason but it also change AKMicrophone's input.And what's that mean of more options?I just got three EZAudioDeivce instance from EZAudio availableInputs.

**Comment by aure** [comment]
```
if let inputs = AudioKit.availableInputs {
    try AudioKit.setInputDevice(inputs[0])
    try mic.setDevice(inputs[0])
    dump(inputs)
    dump(EZAudioDevice.inputDevices())
}
```
When I do this I see the exact same list of devices in EZAudio as in AudioKit.    The problem I'm trying to solve is having more than one input.  AudioKit (via AVAudioEngine) only allows the one input whereas EZAudio I think could allow multiple microphones to be set up.

**Comment by aure** [comment]
@leejust what are the three devices EZAudio lists vs. the one device that AudioKit lists for you?

**Comment by aure** [comment]
@leejust I see why changing the EZAudio device changes it for AudioKit too.  Under the hood we're both doing the same thing, so the only real mystery is why a different input list appears.  I mean we literally are using EZAudio on macOS.  For iOS, we probably could as well, and it might just solve everything.

```
    /// Enumerate the list of available input devices.
    open static var availableInputs: [AKDevice]? {
        #if os(macOS)
            EZAudioUtilities.setShouldExitOnCheckResultFail(false)
            return EZAudioDevice.inputDevices().map {
                AKDevice(name: ($0 as AnyObject).name, deviceID: ($0 as AnyObject).deviceID)
            }
        #else
            if let devices = AVAudioSession.sharedInstance().availableInputs {
                return devices.map {
                    AKDevice(name: $0.portName, deviceID: $0.uid)
                }
            }
            return nil
        #endif
    }
```

**Comment by leejust** [comment]
@aure 

I don't know why this difference happens.

```
    self.inputs = [EZAudioDevice inputDevices];
    
    self.akInputs = [AudioKit availableInputs];
    
    NSLog(@" AKAudioOutputs = %@ \n EZAudioOutputs = %@  ", _akInputs, _inputs);

```

```
 AKAudioOutputs = (
    "<Device: iPhone \U9ea6\U514b\U98ce (Built-In Microphone)>"
) 
 EZAudioOutputs = (
    "<EZAudioDevice: 0x170226220> { port: <AVAudioSessionPortDescription: 0x174010d80, type = MicrophoneBuiltIn; name = iPhone \U9ea6\U514b\U98ce; UID = Built-In Microphone; selectedDataSource = \U4e0b>, data source: <AVAudioSessionDataSourceDescription: 0x170010b00, ID = 1835216945; name = \U4e0b> }",
    "<EZAudioDevice: 0x1702261e0> { port: <AVAudioSessionPortDescription: 0x174010d80, type = MicrophoneBuiltIn; name = iPhone \U9ea6\U514b\U98ce; UID = Built-In Microphone; selectedDataSource = \U4e0b>, data source: <AVAudioSessionDataSourceDescription: 0x170010a20, ID = 1835216946; name = \U524d> }",
    "<EZAudioDevice: 0x170225820> { port: <AVAudioSessionPortDescription: 0x174010d80, type = MicrophoneBuiltIn; name = iPhone \U9ea6\U514b\U98ce; UID = Built-In Microphone; selectedDataSource = \U4e0b>, data source: <AVAudioSessionDataSourceDescription: 0x170010a10, ID = 1835216947; name = \U8fd4\U56de> }"
)
```
And I also agree that AudioKit could list all device as well. Otherwise you would not call it as availableInputs :)

**Comment by aure** [comment]
@leejust trying this right now...

**Comment by leejust** [comment]
I 'm sorry I can do nothing and just watching. Really hope you can fix it.Good luck！

**Comment by aure** [comment]
@WebberLai I think your comments are valid, but this issue I think can be closed for @leejust with the fixes on the develop branch.  For your issue, maybe make a new issue card?

**Comment by WebberLai** [comment]
OKAY , Thank you
