### ISSUE TITLE
Simple Synthesizer Architecture Question for Beginner 

### ISSUE THREAD

**Issue by bencbernstein** [audiokit/AudioKit#831]
Hi all, thanks for the great framework, amazing stuff ...

I'm just getting started with AudioKit and building a simple synthesizer from sine wave oscillators. Right now I have 9 individual oscillators that trigger with 9 pads ... `touchDown` starts them, `touchUp` stops.

I'm sure this isn't a great way, and my `Conductor` class feels pretty messy. I've gone through a lot of the playgrounds, but I'm still a little confused about the sturdiest way to structure this.

So my question is, do you have any design patterns you recommend for building a simple oscillator synth. Should I be creating an `AKInstrument`, using `AKOperation`, or something else?

The repo is here if anyone is interested: https://github.com/bencbernstein/Simple-Synth

Thanks for the help

Ben

**Comment by aure** [comment]
You should be using AKOscillatorBank or one of various AKxxxxxOscillatorBanks.  They have polyphony straight out of the box.

**Comment by aure** [comment]
Oh and they also have envelopes.

**Comment by bencbernstein** [comment]
makes sense, cheers
