### ISSUE TITLE
Disconnect node from AKMixer

### ISSUE THREAD

**Issue by hhanesand** [audiokit/AudioKit#836]
After using `connect` to connect an `AKNode` to an `AKMixer`, how can I remove that node from the mixer in the future?

(or what is another way I can effectively accomplish the same thing)

**Comment by aure** [comment]
This isn't really an issue, but a discussion, which probably should be on the google group: https://groups.google.com/forum/?#!forum/audiokit  What are you disconnecting for?  Can you just stop/bypass it?
