### ISSUE TITLE
AKAudioFile.exportAsynchronously error to export

### ISSUE THREAD

**Issue by erngarcar** [audiokit/AudioKit#839]
Hello,

I've been trying to record and save audio files in my app, but have been getting errors like this:

Export Failed Error Domain=NSURLErrorDomain Code=-1100 "No se ha encontrado la URL solicitada en este servidor." UserInfo={NSLocalizedDescription=No se ha encontrado la URL solicitada en este servidor., NSErrorFailingURLStringKey=file:///file:/private/var/mobile/Containers/Data/Application/38FEF1D2-E4DA-4FD1-89AB-090CF67A9A5E/tmp/2017-04-05_12:34:25.caf, NSErrorFailingURLKey=file:///file:/private/var/mobile/Containers/Data/Application/38FEF1D2-E4DA-4FD1-89AB-090CF67A9A5E/tmp/2017-04-05_12:34:25.caf, NSURL=file:///file:/private/var/mobile/Containers/Data/Application/38FEF1D2-E4DA-4FD1-89AB-090CF67A9A5E/tmp/2017-04-05_12:34:25.caf, NSUnderlyingError=0x170250230 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

The code:

let audioFile = try AKAudioFile(readFileName: "nameFile" + ".caf", baseDir: .temp)
audioFile.exportAsynchronously(name: "nameExportFile",
                                               baseDir: .documents,
                                               exportFormat: .m4a) {_, exportError in
                                               
                    if let error = exportError {
                        print("Export Failed \(error)")
                    } else {
                        print("Export succeeded")
                    }
                }

The error shows that the URL contains twice "file: /" at begining, this is ok?. I'm on 3.5.4 version.

Thanks.

**Comment by aure** [comment]
Seems related to this: https://github.com/audiokit/AudioKit/issues/792
definitely need to get to the bottom of this to close a few similar issues.

**Comment by erngarcar** [comment]
Hi, the problem seems to be the line 328 from /AudioKit/Common/Internals/Audio File/AKAudioFile+ProcessingAsynchronously.swift

I think that instead of 
        let asset = AVURLAsset(url: URL(fileURLWithPath: url.absoluteString))
it should be like this
        let asset = AVURLAsset(url: url)
Best regards.

**Comment by aure** [comment]
You're beautiful! thank you!

**Comment by Audiograins** [comment]
I had this same error until I reverted this change (I was building from source in my project). Is this a change from Swift 3.0 to 3.1?

**Comment by hwiorn** [comment]
@Audiograins 
I have a same error.
I think AVURLAsset(url:URL) make "file://" prefix to file path in Swift 3.0. In 3.1, however, there is no "file://" prefix.(It is only speculation.)

I tested using below code.
/AudioKit/Common/Internals/Audio File/AKAudioFile+ProcessingAsynchronously.swift:328
        var asset = AVURLAsset(url: url)
        if !asset.isExportable {
            asset = AVURLAsset(url: URL(fileURLWithPath: url.absoluteString))
        }

**Comment by aure** [comment]
That seems to be old code, it has been updated in AudioKit3.6

**Comment by Audiograins** [comment]
Sorry, I wasn't clear in my earlier comment. 
I'm still using Swift 3.0.2 as I can't upgrade Xcode just yet, but using AudioKit 3.6 source (so I had this fix in my project). It seems to me that the fix for this issue works only with Swift 3.1 but fails for earlier versions, so I reverted to the old code and it seems to work now. I think the reason given by hwiorn is probably correct but couldn't find anything in the Swift documentation to confirm a change between Swift 3.0 and 3.1 that would cause this issue in the first place.
