### ISSUE TITLE
AudioKit-Swift.h - why some extensions listed and others not, ie. AKAudioFile's exportAsynchronously?

### ISSUE THREAD

**Issue by NathanWalker** [audiokit/AudioKit#841]
Hopefully this is a simple question with a simple answer -
I've noticed that the iOS framework's `AudioKit-Swift.h` bridging header (which can be viewed here for convenience: https://cdn.filestackcontent.com/HHYq68t9TWMBIQ9k5uJl?v=0) contains only a subset of functions, for example, `AKAudioFile`'s extensions like `exportAsynchronously` is not made available in this bridging header. I'd like to use and expose those to ObjC and curious if there's an easy way I could do that from a fork with a custom build of the iOS framework and/or if it would be worth making those changes on master here?

Any help or pointers here would be greatly appreciated!
This is the best framework - just tremendous work - I marvel at the engineering often.
Curiously I notice the `AudioKit-Swift.h` header file that's generated ends up with 3 blank `SWIFT_EXTENSION` interfaces for `AKAudioFile`:

```
@interface AKAudioFile (SWIFT_EXTENSION(AudioKit))
@end


@interface AKAudioFile (SWIFT_EXTENSION(AudioKit))
@end


@interface AKAudioFile (SWIFT_EXTENSION(AudioKit))
@end
```

I'm guessing that's where some of the extensions like perhaps those from `AKAudioFile+ProcessingAsynchronously.swift` might end up but appears a good portion of those extensions are not exposed to ObjC.

**Comment by megastep** [comment]
My guess from having that kind of issue with other parts of AudioKit in Objective-C projects is that some types don't always translate to Obj-C at all, and this cascades to excluding some of the APIs using these types. In this case, I would think that the embedded enums used in these APIs is the cause (for example, `ExportFormat` is a complex enum inside the class extension).

Personally I'd be in favor of making AudioKit more open to legacy Objective-C but that comes at the cost of making the project less like a native Swift library - which has its own trade-offs.

**Comment by NathanWalker** [comment]
Thank you for the insight @megastep - I may try simplifying the enum in a fork and rebuild the frameworks and see if that helps.

**Comment by aure** [comment]
I'm not sure how I would even begin to act on this issue.  I think its probably easier to mix and match obj-c in a project than try to get all of AK working with Obj-c.  Sorry.

**Comment by NathanWalker** [comment]
Totally understand @aure - would be too large an undertaking for such an elegant Swift codebase at moment. In meantime, I was able to expose the methods I need to ObjC by flattening the complex enum's, ie:

```
@objc public enum ExportFormat: Int {
        /// Waveform Audio File Format (WAVE, or more commonly known as WAV due to its filename extension)
        case wav

        /// Audio Interchange File Format
        case aif

        /// MPEG-4 Part 14 Compression
        case mp4

        /// MPEG 4 Audio
        case m4a

        /// Core Audio Format
        case caf
        
    }

    // MARK: - AKAudioFile public interface with private AKAudioFile ProcessFactory singleton

    // Returns a Uniform Type identifier for each audio file format
    static public func stringUTI(type: ExportFormat) -> CFString {
        switch type {
        case .wav:
            return AVFileTypeWAVE as CFString
        case .aif:
            return AVFileTypeAIFF as CFString
        case .mp4:
            return AVFileTypeAppleM4A as CFString
        case .m4a:
            return AVFileTypeAppleM4A as CFString
        case .caf:
            return AVFileTypeCoreAudioFormat as CFString
        }
    }

    // Available Export Formats
    static public var supportedFileExtensions: [String] {
        return ["wav", "aif", "mp4", "m4a", "caf"]
    }
```

Then adjusting the usage throughout and that opened all those extensions up to ObjC.
