### ISSUE TITLE
Dynamic set sampleRate and numberOfChannels 

### ISSUE THREAD

**Issue by Pikachu7074** [audiokit/AudioKit#842]
hi,
I am a new to AudioKit
I tried to dynimic set aksettings as blow 
 func setupAudioKit(numberOfChannels:UInt32,sampleRate:Double){
        
        //Session settings
        AKSettings.audioInputEnabled = true
        AKSettings.bufferLength = .medium
        AKSettings.numberOfChannels = numberOfChannels
        AKSettings.sampleRate = sampleRate
    
        
        mic = AKMicrophone()
        micMixer = AKMixer(mic)
        
        recorder = try? AKNodeRecorder(node: micMixer)
        micBooster = AKBooster(micMixer)
        // Will set the level of microphone monitoring
        micBooster!.gain = 0
        AudioKit.output = micBooster
        AudioKit.start()
        
    }
--------------------------------------------------
error:

  ERROR:    >avae> AVAudioNode.mm:751: AUSetFormat: error -10865
2017-04-07 17:03:55.217 ArtRecord[25039:6330579] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10865'

**Comment by aure** [comment]
Okay, uh, so your numberOfChannels was what?

**Comment by aure** [comment]
I don't think we support numberOfChannels != 2 yet actually.

**Comment by Pikachu7074** [comment]
thank u for your answer ,Aure numberOfChannels is 1 or 2 ,
