### ISSUE TITLE
[BUG possibly] loading & playing of samples in project spits errors

### ISSUE THREAD

**Issue by lewislepton** [audiokit/AudioKit#844]
ive recently ran into this when on a xcode project, not playground. i can set up playgrounds. but was running into this just when 3.6 happened

the project, again, is super duper simple. just a loading of a sample to play [wav]. but even just before the 3.6 release, the sample would not even play, no sound. which i could not understand. but now it errors, on a clean new project

```
import Cocoa
import AudioKit

class ViewController: NSViewController {
  let sampler = AKSampler()
  override func viewDidLoad() {
    super.viewDidLoad()
    do {
      try sampler.loadWav("idle")
      sampler.amplitude = 0.5
      sampler.play()
    } catch {
      AKLog("NOT LOADED DAWG")
    }
    AudioKit.output = sampler
    AudioKit.start()
  }

  override var representedObject: Any? {
    didSet {
    // Update the view, if already loaded.
    }
  }
}
```

& this is the error that spits out in the console, no matter what
```
2017-04-08 13:20:51.705912+0100 SampleLayer[7795:82471] [central] 54:   ERROR:    >avae> AVAudioUnitMIDIInstrument.mm:105: -[AVAudioUnitMIDIInstrument startNote:withVelocity:onChannel:]: error -10867
2017-04-08 13:20:51.706105+0100 SampleLayer[7795:82471] Failed to set (contentViewController) user defined inspected property on (NSWindow): error -10867
```

as said before, the sample just didnt play, for some reason before 3.6. but now it doesnt play & errors in the console

**Comment by lewislepton** [comment]
i am using latest xcode 8.3.1. if that by chance may help. also this is a macOS app, not iOS

**Comment by lewislepton** [comment]
i have just tried in the same project, the oscillator. that worked perfectly. no errors popping up in the console when running. i did comment out the sampler code obviously, as it would not run properly with it in still

**Comment by aure** [comment]
Trying to play before starting AudioKit... try this:

```
  override func viewDidLoad() {
    super.viewDidLoad()
    do {
      try sampler.loadWav("idle")
      sampler.amplitude = 0.5
    } catch {
      AKLog("NOT LOADED DAWG")
    }
    AudioKit.output = sampler
    AudioKit.start()
    sampler.play()
  }
```
