### ISSUE TITLE
is it possible to have the frameworks named with iOS/macOS?

### ISSUE THREAD

**Issue by lewislepton** [audiokit/AudioKit#847]
just to ask. though it may be too much to ask etc
but would it be possible to change the downloadable framework names? such as something like AudioKitiOS & AudioKitmacOS?

just really in terms of if people are working on both of the different platforms, rather than just one of them.
more just as something to help people know exactly what they are using.
know it may be a bit to ask, but worth asking

cheers

**Comment by aure** [comment]
No, because its cross platform and the code is transportable.

**Comment by lewislepton** [comment]
cool. cheers
