### ISSUE TITLE
how to submit minor enhancement to a playground

### ISSUE THREAD

**Issue by sigmonky** [audiokit/AudioKit#848]
Hi --

I was experimenting with the recording nodes playground and implemented a minor UI enhancement that updates the play button when audio stops. The enhancement was simply a matter of assigning the play button object to a playground scope variable so that it's title could be updated inside the playback completion handler. I would like to start contributing to the project via pull requests but thought this enhancement might be too trivial for that. If you'd prefer a pull request, I'd be happy to go that route.

In setup...
```
playButton = AKButton(title: "Play") {
            if player!.isPlaying {
                self.playLabel!.text = "Stopped playback!"
                player?.stop()
                return "Play"
            } else {
                try? player?.reloadFile()
                // If the tape is not empty, we can play it !...
                if player?.audioFile.duration ?? 0 > 0 {
                    self.playLabel!.text = "Playing..."
                    player?.completionHandler = self.callback
                    player?.play()
                } else {
                    self.playLabel!.text = "Tape is empty!..."
                }
                return "Stop"
            }}
        
        addSubview(playButton!)
```
The callback ...
```
func callback() {
        // We use Dispatch_async to refresh UI as callback is invoked from a background thread
        DispatchQueue.main.async {
            self.playLabel!.text = "Finished playing!"
            self.playButton!.title = "Play"
        }
    }
```

**Comment by aure** [comment]
Hey there, thanks for your thoughtfulness about asking first, but yeah, you're right, I love pull requests the most because its just easier.  Just make sure to make the pull request off of the develop branch because there have been quite a few playground updates there recently.

**Comment by sigmonky** [comment]
ok. will do.
