### ISSUE TITLE
Period too small

### ISSUE THREAD

**Issue by icare-petibles** [audiokit/AudioKit#850]
Hi,
I use RPi3 witch librpip (Raspbian Jessie + Pixel).
With :
```
echo 20000 > /sys/class/pwm/pwmchip0/pwm0/period
echo 5000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
echo 1 >  /sys/class/pwm/pwmchip0/pwm0/enable
```
I have a frequency of 500 Hz and not 50 kHz.
Same problem with a RPi Zero v1.3
Where is my mistake?
Thanks

**Comment by aure** [comment]
This has nothing to do with AudioKit.

**Comment by icare-petibles** [comment]
all my excuses
