### ISSUE TITLE
App Signing Error using Cocoapod build

### ISSUE THREAD

**Issue by MDBox** [audiokit/AudioKit#852]
It seems that a file in the cocoapod build `fix-framework.sh` is causing problems with signing the application for release.  I had to manually delete this file in order to upload to itunes.  

Error itms-90035 - Xcode

Found a workaround here: http://stackoverflow.com/questions/29788601/error-itms-90035-xcode

**Comment by megastep** [comment]
The script should already remove itself from the archive - I bet you are probably just calling it at the wrong time in your run phase so that it is still there.

**Comment by MDBox** [comment]
That could be the case.  It was the default cocoapod build with `pod install` command. Perhaps the issue is with cocoapod itself. I'm not sure why the file is needed at all in the cocoa package but I'm not that familiar to know one way or another.  Anyways thanks for your comment I'll check out if there are settings I can adjust or integrate the framework another way.

**Comment by aure** [comment]
Is this resolved?

**Comment by MDBox** [comment]
I just reinstalled pod and version 3.6 and didn't have the problem this time.  Not sure the root cause but perhaps it is safe to close this issue.

**Comment by StefanNestorov** [comment]
I have the same problem with the latest version of AudioKit integrated by cocoa pods. Had to manualy delete the fix-framework.sh file from the archive to be able to upload the build.
