### ISSUE TITLE
AKNodeOutputPlot plotType buffer is not working as expected from 3.5.4

### ISSUE THREAD

**Issue by pavan309** [audiokit/AudioKit#856]
Hi

Background/Setup

We are recording audio from a device's microphone and storing it in a file (via AVAudioRecorder) while playing the realtime buffered waveform through AudioKit's EZAudioPlot and AKNodeOutputPlot. For playback, we are playing back a recorded m4a from a file using AKAudioPlayer with the same visualization of whatever is being output from the device's speaker for visual feedback of the audio.

Issue

AKNodeOutputPlot graph is not being plotted either when recording or when playing back. Looks like the issue is only with plotType buffer, rolling plotType seems working fine. 

I am unable to figure out the way to debug this issue. Is there a way where I can run AudioKit code instead of from framework. Please let me know if I am missing anything.

Thanks

**Comment by pavan309** [comment]
Do you think the reason I am seeing this issue because of the condition that was added in this [commit](https://github.com/audiokit/AudioKit/commit/86e760038528ca86b4978c8e0961e2f2759b17a6) in the method `displayLinkNeedsDisplay`?

**Comment by aure** [comment]
Yeah,  I think you're right that that is the issue and should be reversed.

**Comment by pavan309** [comment]
Hi Aure,

I have raised PR which I think it will fix. Do let me know if that works.
Is there a way where I can debug AudioKit code along with the my code?

Thanks.

**Comment by aure** [comment]
Merged your fix.
