### ISSUE TITLE
can upload because of a sh file in the framework.

### ISSUE THREAD

**Issue by kvacquier** [audiokit/AudioKit#861]
I could not upload my app to the app store because there was a strange sh in the iOS framework : Products/Applications/myApp.app/Frameworks/AudioKit.framework/fix-framework.sh

**Comment by aure** [comment]
This should help: https://github.com/audiokit/AudioKit/issues/852

**Comment by kvacquier** [comment]
Removed and that didn't worked.

**Comment by hhanesand** [comment]
@kvacquier Building from source is also an option if you can't get this resolved

**Comment by aure** [comment]
Really there's not enough information to go on to address this issue, so I'll close this for now.
