### ISSUE TITLE
Incorrect output when loading mixing two sequencers

### ISSUE THREAD

**Issue by kinggryan** [audiokit/AudioKit#862]
I am attempting to connect two sequencers to avaudioengine, mix them, and play the mixed output. In addition, I want the user to be able to mute the samplers. I've initialized my audio system like so:

```swift
        do{
            try samplerA.loadPercussiveSoundFont("samplerfile1", preset: 0)
            try samplerB.loadPercussiveSoundFont("samplerfile2", preset: 0)
        } catch let error as NSError {
            print(error.localizedDescription)
        }
        
        mixer = AKMixer(samplerA,samplerB)
        AudioKit.output = mixer
        AudioKit.start()
        
        sequencerA = AKSequencer(filename: "beat_01", engine: AudioKit.engine)
        sequencerA?.enableLooping()
        sequencerA!.avTracks[0].destinationAudioUnit = samplerA.samplerUnit
        sequencerA!.setLength(AKDuration(beats: 4))
        
        sequencerB = AKSequencer(filename: "beat_02", engine: AudioKit.engine)
        sequencerB?.enableLooping()
        sequencerB!.avTracks[0].destinationAudioUnit = samplerB.samplerUnit
        sequencerB!.setLength(AKDuration(beats: 4))
```

On the push of a play button, the audio plays:

```swift
        sequencerA?.loadMIDIFile("beat_01")
        sequencerB?.loadMIDIFile("beat_02")
        sequencerA?.enableLooping()
        sequencerB?.enableLooping()
        sequencerA!.setLength(AKDuration(beats: Double(4)))
        sequencerB!.setLength(AKDuration(beats: Double(4)))
        
        sequencerA?.play()
        sequencerB?.play()
```

On the push of another button, the one of the samplers is muted. Pushing the button changes which sampler is muted:

```swift
        usingA = !usingA
        if usingA {
            samplerA.volume = 1
            samplerB.volume = 0
        } else {
            samplerA.volume = 0
            samplerB.volume = 1
        }
```

The issue is that only one of the samplers seems to be playing audio properly. The other sampler seems to only be playing some of the notes of the intended audio. In addition, changing the line from 

`mixer = AKMixer(samplerA,samplerB)` 
to 
`mixer = AKMixer(samplerB,samplerA)` 
inverts the sampler that plays properly.

Thanks for the help.

**Comment by aure** [comment]
Maybe don't trust the sampler volume and send the samplers each into booster of their own?

**Comment by aure** [comment]
I heard this might have been sorted out, if so, can you make a note of the solution you came up with and then close the issue?

**Comment by aure** [comment]
Closing due to lack of response, will reopen with new info.
