### ISSUE TITLE
How to play midi notes

### ISSUE THREAD

**Issue by zsheikh-systango** [audiokit/AudioKit#864]
I have midi notes information from sysex in below format:
note_name1, note_on
note_name1, note_off
note_name2, note_on
note_name2, note_off
...

Is there any way to play this format using AudioKit?

**Comment by aure** [comment]
Yes.

**Comment by aure** [comment]
For things like this you should join the AudioKit forum: https://groups.google.com/forum/#!forum/audiokit

**Comment by zsheikh-systango** [comment]
Thanks, Have sent request to join

**Comment by zsheikh-systango** [comment]
I have posted on group, can you please reply
https://groups.google.com/forum/#!topic/audiokit/8XbQfrfpi-U
