### ISSUE TITLE
Crash for AKMixer

### ISSUE THREAD

**Issue by terenzeyuen** [audiokit/AudioKit#868]
Maybe I am doing this wrongly but we are trying to use High Pass Filter, Low Pass filter and Graphic Equalizer together – combined using AKMixer. 
The audio mixing runs fine, we can hear the adjustments but it keeps crashing when the ViewController gets deallocated...is this not possible?

> 2017-04-28 17:34:19.650455+0100 Noted[20872:6193871] [central] 54:   ERROR:    [0x1aaa6db40] >avae> AVAudioEngine.mm:301: DetachNode: required condition is false: [_nodes containsObject: node]
> 2017-04-28 17:34:19.651449+0100 Noted[20872:6193871] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: [_nodes containsObject: node]'

Code:
```
@IBAction func onPlay(_ sender: Any) {
        if player != nil {
            player.stop()
            AudioKit.stop()
            playButton.setTitle("PLAY", for: .normal)
            return
        }
        do {
            let file = try AKAudioFile(readFileName: fileName,
                                       baseDir: .documents)
            player = try AKAudioPlayer(file: file)
            player.looping = true
            lowFilter = AKEqualizerFilter(player, centerFrequency: 50, bandwidth: 100, gain: 1.0)
            midFilter = AKEqualizerFilter(lowFilter, centerFrequency: 350, bandwidth: 300, gain: 1.0)
            highFilter = AKEqualizerFilter(midFilter, centerFrequency: 5_000, bandwidth: 1_000, gain: 1.0)
            
             highPassFilter = AKHighPassFilter(player, cutoffFrequency: 6900)
            lowPassFilter = AKLowPassFilter(highPassFilter, cutoffFrequency: 6900)

            let rebalancedWithSource = AKBalancer(lowPassFilter, comparator: player)
           // mixer =  AKMixer(highPassFilter, highFilter)
            AudioKit.output = rebalancedWithSource
            AudioKit.start()
            player.play()
            playButton.setTitle("STOP", for: .normal)
        } catch {
            print(error)
        }

    }
```

**Comment by aure** [comment]
Don't do audio start stuff on IBActions, follow the model where there is a singleton class handling your audio signal chain, like in the more complex examples.  There's certainly nothing wrong with AKMixer.

**Comment by aure** [comment]
Consider joining the google group for AudioKit instead of using the issue tracker, which we use mostly for bug tracking. https://groups.google.com/forum/#!forum/audiokit
