### ISSUE TITLE
Have one error on a simple metronome

### ISSUE THREAD

**Issue by doriansgithub** [audiokit/AudioKit#869]
Hi,

What I'm I doing wrong?
Thanks in advance.

import Foundation
import AudioKit

    var startMetronome: Bool = false

    var generator: AKOperationGenerator?

    var currentFrequency: Int = Int(120) {
        didSet {
            metronomeRateLabel.text = "\(currentFrequency)"
            metronomeRateSlider.value = Float(Int (currentFrequency))
        }
    }
    @IBOutlet weak var onOffButton: UIButton!
    @IBOutlet weak var decreaseMetronomeRate: UIButton!
    @IBOutlet weak var increaseMetronomeRate: UIButton!
    @IBOutlet weak var metronomeRateLabel: UILabel!
    @IBOutlet weak var metronomeRateSlider: UISlider!

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        webView.isHidden = true
        webViewOpen = 0
        pickerBackground.layer.cornerRadius = pickerBackground.frame.width / 2.0
        pickerBackground.clipsToBounds = true
        let thumb = UIImage(named: "glassballThumb.png")
        metronomeRateSlider.setThumbImage(thumb, for: .normal)
        metronomeRateSlider.setThumbImage(thumb, for: .highlighted)
        self.onOffButton.setBackgroundImage(UIImage(named: "AlarmGreen.png"), for: .normal)
        self.onOffButton.setTitle("Play", for: [])

        generatorSettings()
    }
    func generatorSettings ()  {
        var currentFrequency = 1.0
        let beep = AKOperation.sineWave(frequency: 480)

//  HERE I get a "missing argument label" Error.
        let trig = AKOperation.metronome(AKOperation.parameters(0))

        let beeps = beep.triggeredWithEnvelope(
            trig,
            attack: 0.01, hold: 0, release: 0.05)
        let generator = AKOperationGenerator(operation: beeps)
        AKOperationGenerator(operation: beeps)
        generator!.parameters[0] = Double(currentFrequency)
        AudioKit.output = generator
        AudioKit.start()
    }
    @IBAction func metronomeRateSliderChanged(_ sender: UISlider) {
            let currentValue = sender.value
            metronomeRateSlider.minimumValue = 40
            metronomeRateSlider.maximumValue = 240
            currentFrequency = Int(currentValue.value())
            generator!.parameters[0] = Double(currentFrequency)
    }
    @IBAction func increaseMetroFrequency(_ sender: UIButton) {
        currentFrequency += 1
    }
    @IBAction func decreaseMetroFrequency(_ sender: UIButton) {
        currentFrequency -= 1
    }
    @IBAction func startStopMetronome(_ sender: UIButton) {
        if startMetronome == false {
            self.onOffButton.setTitle("Pause", for: [])
            startMetronome = true
            generator!.restart()
            UIView.animate(withDuration: 1,
                           animations: {
    self.onOffButton.setBackgroundImage(UIImage(named: "AlarmRed.png"), for: .normal)
            }, completion: nil)
        } else {
            self.onOffButton.setTitle("Play", for: [])
            startMetronome = false
            generator!.stop()
            UIView.animate(withDuration: 1,
                           animations: {
    self.onOffButton.setBackgroundImage(UIImage(named: "AlarmGreen.png"), for: .normal)
            }, completion: nil)
        }
    }

**Comment by aure** [comment]
I don't know, try making the generator an instance variable on the class instead of a locally defined variable.  What exactly is happening when you try to run this.  That would be the first thing I'd need to know.  In any event, this is much more of a discussion group thing than an "issue" since its not a bug in AudioKit.  Try posting more info here: https://groups.google.com/forum/#!forum/audiokit

**Comment by doriansgithub** [comment]
I know you’re busy, but although it’s no longer crashing, we are not getting audio out.  Can you glance at this real quick and give me a clue? 



Thanks!

Dorian
