### ISSUE TITLE
Plotting audio of a selected channel

### ISSUE THREAD

**Issue by shylock74** [audiokit/AudioKit#871]
Hi there,
Is there a way to plot the audio of a selected single channel of the audio?
I'm using a virtual device with N channels and I'd like to plot a single waveform for each one of them.
Thank you in advance.

Alex.

P.S. (AK rocks!)

**Comment by aure** [comment]
Hi, we use Github issues mostly for bug tracking and have a google group for discussions such as this, so I encourage you to join: https://groups.google.com/forum/#!forum/audiokit
But, while I am responding I might as well give you some useful now, which is that AudioKit is very stereo-centric at the moments, so our N=2.  We'd love to extend AudioKit to be multichannel configurable, but that would take some development effort.  Our plots are based of taps of these stereo nodes and you could elect to plot either the left or right channel pretty easily.
