### ISSUE TITLE
ld: warning & clang: error opening AudioKitPlaygrounds

### ISSUE THREAD

**Issue by AdrianBinDC** [audiokit/AudioKit#876]
I'm running Xcode Version 8.3.2 (8E2002)

I downloaded the [AudioKit repo](https://github.com/audiokit/AudioKit) from the "Clone or download" button. I navigated AudioKit-master's Playgrounds subdirectory and opened AudioKitPlaygrounds.xcodeproj in Xcode.

I encountered this warning:

`ld: warning: directory not found for option '-F../Frameworks/AudioKit-macOS'`

I resolved the warning by selecting the project in the navigation pane, clicking the AudioKitPlaygrounds target, and searching for "Framework Search Paths" in build settings. Deleting the path coupled with a "clean and build" removed the warning.

I also encountered this error:

`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Building didn't resolve it for me, as the video on the Playgrounds section of AudioKit.io's video recommended, so I went ahead and ran the script to build the frameworks. I deleted the framework from the AudioKitPlaygrounds.xcodeproj file and dropped in AudioKit.framework in its place. Then, rebuilding it worked perfectly

**Comment by aure** [comment]
Yep, that's all reasonable for running the playgrounds from source.  What is the issue?

**Comment by AdrianBinDC** [comment]
I thought I'd throw up a solution in case anyone else encountered difficulty.

**Comment by aure** [comment]
Ahh, yeah, its definitely not bad to have this issue in the closed issues since people do search through them. I just also like to keep the issues list short so its a tradeoff. Thanks Adrian!
