### ISSUE TITLE
AKFFTTap on low pass butterworth filter gives 'com.apple.coreaudio.avfaudio', reason: 'error -10868

### ISSUE THREAD

**Issue by AlbanPerli** [audiokit/AudioKit#877]
Hi,
I'm working on a wav file, simulator iPhone 5s iOS 10.3.
(same behavior on real device iPhone 5s iOS 10.2.1)

It works when the player is given to the AKFFTTap, 
but it crash when tries to build the AKFFTTap object with the filter.

```
let file = try! AKAudioFile(readFileName: "fileName.wav",
                                    baseDir: .resources)
player = try! AKAudioPlayer(file: file)
player.looping = true
let filter = AKLowPassButterworthFilter(player)
filter.cutoffFrequency = cutoffFrequency // 150 Hz        
AudioKit.output = filter
AudioKit.start()
player.play()
let fft = AKFFTTap(filter) //  CRASH
let fft = AKFFTTap(player) //  OK

```

Maybe I've missed something as I'm new to AudioKit?

Thx for your good work!

**Comment by aure** [comment]
If you want to FFT the filter, it may help to send it through a mixer first.  For some reason taps don't like certain kinds of nodes.  So just do 

```
let mixer = AKMixer(filter)
...
let fft = AKFFTTap(mixer) // Should be OK
```

**Comment by aure** [comment]
The mixer won't be doing anything to the sound, and it is low energy, so it should be a fairly easy modification. Mind you, make sure these variables are local, so in a real project you'll probably want them to be instance variables retained by a class.

**Comment by AlbanPerli** [comment]
Thx for the quick response!
It doesn't crash anymore.
