### ISSUE TITLE
Can't use AKFFTap and AKNodeOutputPlot at the same time

### ISSUE THREAD

**Issue by denisb411** [audiokit/AudioKit#890]
Hello,

I'm having some problems with the AKNodeOutputPlot...
I see that the class make a new tap at the Microphone in order to make the plot process. I think it isn't right because it's not possible to 'double tab' a node.
In my case, I'm doing some stuff using the AKFFTTap, which already makes a Tap at the input.
How can I use AKFFTTap and AKNodeOutputPlot with the same Node? (AKMicrophone node, in this case).

If it's not an issue, please help me.

Thanks in advance,
Denis.

**Comment by aure** [comment]
Yeah, so you can't tap the node twice, but you can send the node into a mixer that doesn't do anything and then tap that for a second data source.

**Comment by denisb411** [comment]
Nice to hear that. Do you have any example?
What I'm trying to do:

```
    override func viewDidAppear(_ animated:Bool){
        
        setupPlot(ChromaticViewController.tuner.mic)
::
func setupPlot(_ mic:AKMicrophone) {
        let plot = AKNodeOutputPlot(mic, frame: nodePlotView!.bounds)
        plot.plotType = .rolling
        plot.shouldFill = true
        plot.shouldMirror = true
        plot.color = UIColor.blue
        nodePlotView!.addSubview(plot)
    }
```

**Comment by denisb411** [comment]
Solved with:

```
let mixer = AKMixer(ChromaticViewController.tuner.mic)
setupPlot(mixer)
```

But UIView isn't showing anything...

**Comment by denisb411** [comment]
Solve the problem creating a initializing a new AKMicrophone() instance. Now i'm using 'micPlot' instead of 'mic'.
