### ISSUE TITLE
replace audio files of different SampleRate

### ISSUE THREAD

**Issue by qqqssagithub** [audiokit/AudioKit#896]
When using AKAudioPlayer, first loaded into an audio file (SampleRate: 44100). Then use: player.replace (file: newFile), the switch to a new file (SampleRate: 48000), the audio file playback will slow down, reverse order load becomes faster.
I have done the following test to eliminate this problem:

let engine = AVAudioEngine()
 let player = AVAudioPlayerNode()
        
let url = URL(fileURLWithPath: Bundle.main.path(forResource: "one", ofType: "mp3")!)
let file = try! AVAudioFile(forReading: url)
let buffer = AVAudioPCMBuffer(pcmFormat: file.processingFormat, frameCapacity: AVAudioFrameCount(file.length))
        
try? file.read(into: buffer)
        
engine.attach(player)
engine.connect(player, to: engine.mainMixerNode, format: buffer.format)
try? engine.start()
        
player.scheduleBuffer(buffer, completionHandler: nil)
player.play()
        
let newUrl = URL(fileURLWithPath: Bundle.main.path(forResource: "two", ofType: "mp3")!)
let newFile = try! AVAudioFile(forReading: newUrl)
let newBuffer = AVAudioPCMBuffer(pcmFormat: newFile.processingFormat, frameCapacity: AVAudioFrameCount(newFile.length))

 try? file.read(into: newBuffer)
        
player.stop()
        
/// detach Node
engine.detach(player)
        
/// attach Node, using new format
engine.attach(player)
engine.connect(player, to: engine.mainMixerNode, format: newBuffer.format)
        
player.scheduleBuffer(newBuffer, completionHandler: nil)
player.play()

**Comment by aure** [comment]
I am sorry, what is it that you would like AudioKit to do differently?

**Comment by qqqssagithub** [comment]
I wrote a demo with AudioKit, so you can listen to the difference in speed between the two ends of the audio
https://github.com/qqqssagithub/AudioTest.git

**Comment by aure** [comment]
@qqqssagithub I thin you should try using the new AKSamplePlayer instead of AKAudioPlayer.  As long as your files aren't too huge, it should be a better player.
