### ISSUE TITLE
AKSequencer delegate

### ISSUE THREAD

**Issue by qualee** [audiokit/AudioKit#897]
I have a sequence which is played in the sequencer and I'd like to get notified when it's state is changed, for example the sequence ended playing, new loop started, every new bar. I don't see any of this in the class' documentation. am I missing something or is this feature is not implemented yet? If not I'll probably do this myself...

Thanks

**Comment by aure** [comment]
Its not part of AudioKit yet, but if you'd like to add it, that would be great.
