### ISSUE TITLE
dyld: Library not loaded: @rpath/AudioKit.framework/AudioKit

### ISSUE THREAD

**Issue by BusFactor1Inc** [audiokit/AudioKit#899]
I have followed the intro video, and dragged the framework into my iPhone/iWatch app, and now when I run the app I get the following:

dyld: Library not loaded: @rpath/AudioKit.framework/AudioKit
  Referenced from: /Users/burton/Library/Developer/CoreSimulator/Devices/41CED83E-0B6C-437A-A7D4-542DD3305024/data/Containers/Bundle/Application/25A36116-D899-467A-846A-5B3EDEB05B1B/VimoHeartRate.app/VimoHeartRate
  Reason: image not found

Any help appreciated.

**Comment by aure** [comment]
Drag it and make a copy, and make sure its included in embedded frameworks.  Also, feel free to join the google group for general help.  We use issues for bug tracking mostly.

**Comment by ingconti** [comment]
for XCode 9 simply check "build Phases" -> Embed framework
<img width="636" alt="screen shot 2017-12-09 at 2 08 00 pm" src="https://user-images.githubusercontent.com/4048423/33795913-8f1e9d9a-dcea-11e7-823c-be0b2f10859a.png">

**Comment by ingconti** [comment]
for XCode 9 simply check "build Phases" -> Embed framework


<img width="650" alt="screen shot 2017-12-09 at 2 11 02 pm" src="https://user-images.githubusercontent.com/4048423/33795930-e3739760-dcea-11e7-9018-1b25f6e4ae2d.png">
