### ISSUE TITLE
AKAudioFile get frequencies and amplitude

### ISSUE THREAD

**Issue by Herz3h** [audiokit/AudioKit#901]
Hello,

I have this code currently to get the frequencies and amplitude of an audio file : 

let url = mypathtothefilehere...
let file = try! AKAudioFile(readingFrom: url)
var data = file.floatChannelData[0]

But i get too much data, its too precise. (30million of points for 20mins of audio 44Khz sample rate stereo)

Is there a way to choose how many points to get when i do floatChannelData ? Because if i keep like this, files that are pretty long( say 20mins) bump the memory to around 250mo)

I've seen there is a getWaveFormData() which has an argument numberOfPoints but no such thing for AKAudioFile.

Could anyone help me?

Thanks in advance.

**Comment by aure** [comment]
That's not the frequencies and amplitudes of a file, that's the raw waveform data.  If you're looking for frequencies and amplitudes you'd want to run the file through AKFrequencyTracker.  Unfortunately currently that only work iwith real time playback, not offline processing.  Theoretically you could use AudioKit's algorithms to loop through the floatChanneldata.  But, the issue tracker is for bugs and such and this is more of a discussion, could you move it to https://groups.google.com/forum/#!forum/audiokit  Thanks.
