### ISSUE TITLE
Cannot create a mono file with AKAudioFile.init(createFileFromFloats ...

### ISSUE THREAD

**Issue by MathieuLescure** [audiokit/AudioKit#902]
In AKAudioFile+ConvenienceInitializers.swift:

With the following constructor, an error is thrown (by `try self.write(from: buffer)`) if floatsArrays contains only one array.

```
    public convenience init(createFileFromFloats floatsArrays: [[Float]],
                            baseDir: BaseDirectory = .temp,
                            name: String = "") throws {
        
        let channelCount = floatsArrays.count
        var fixedSettings = AKSettings.audioFormat.settings
        
        fixedSettings[AVNumberOfChannelsKey] = channelCount
        
        try self.init(writeIn: baseDir, name: name)
```

Replacing 
`try self.init(writeIn: baseDir, name: name)` 
by 
`try self.init(writeIn: baseDir, name: name, settings: fixedSettings)` 
fix the problem.

**Comment by aure** [comment]
Can you make a pull request for this fix?

**Comment by MathieuLescure** [comment]
No problem, I will.
