### ISSUE TITLE
Is there a quantitative standard to meature the sound volume?

### ISSUE THREAD

**Issue by tudou152** [audiokit/AudioKit#913]
let generator = AKOperationGenerator { _ in

    // Generate a sine wave at the right frequency
    let crossingSignalTone = AKOperation.sineWave(frequency: 2_500)

    // Periodically trigger an envelope around that signal
    let crossingSignalTrigger = AKOperation.periodicTrigger(period: 1.5)
    let crossingSignal = crossingSignalTone.triggeredWithEnvelope(
        trigger: crossingSignalTrigger,
        attack: 0.01,
        hold: 0.1,
        release: 0.01)

    // scale the volume
    return crossingSignal * 0.001
}

just like how much is the decibels of the sound that is generated by this method.

**Comment by aure** [comment]
AKAmplitudeTracker will  give you an RMS average amplitude of any input you give it.
