### ISSUE TITLE
Audiokit is very quiet on iPhone5 & 7 built-in speaker, and sometimes make no sound at all

### ISSUE THREAD

**Issue by ukelady** [audiokit/AudioKit#914]
I have a very simple synth that runs perfectly on iPad. But on iPhones (5c, 7) the sound is not audible with the built-in speaker on the phone, but it's fine with earphones. If I unplug and plug the earphones a few times I would end up with no sounds from the synth at all (it doesn't happen every single time, you'll need to try a few times) And if I record the silence, it would end up being a broken audio file. Here is the code:

```
    var fmBank : AKFMOscillatorBank!
    var fmBankLow : AKFMOscillatorBank!
    var mixer : AKDryWetMixer!
    var lowPassFilter : AKLowPassFilter!
    var reverb : AKCostelloReverb!
    var distortion : AKDistortion!
    var recorder : AKNodeRecorder!

    var fmMixer : AKMixer!

    public override init() {

        super.init()

        fmBank = AKFMOscillatorBank();
        fmBankLow = AKFMOscillatorBank();
        mixer = AKDryWetMixer(fmBank, fmBankLow)
        lowPassFilter = AKLowPassFilter(mixer)        
        distortion = AKDistortion(lowPassFilter)
        reverb = AKCostelloReverb(distortion)

        reverb.start()

        fmMixer = AKMixer(reverb)

        do {

            recorder = try AKNodeRecorder(node: fmMixer)

        } catch {
            AKLog("can't create recorder")
        }

        AudioKit.output = fmMixer
        AudioKit.start()
    }
```

**Comment by aure** [comment]
When you do that you're changing the audio route, and you might need to set up your signal chain again.  It sounds like audio is probably being re-routed to the ringtone speaker sometimes, and dying other times.  Audio routing is one of the most frustrating parts of programming for the iPhone.

**Comment by ukelady** [comment]
Thanks for the reply, aure. Could you please give some hints about what you mean by "setting up the signal chain again"? Do you mean just to call Audiokit.stop() and then Audiokit.start() to reset the signal chain? 

Do you think that the audio is inaudible from the ringtone speaker is an expected behavior?
