### ISSUE TITLE
Installing AudioKit 3.7 with cocoa pods gives error on Swift 3.1

### ISSUE THREAD

**Issue by denisb411** [audiokit/AudioKit#922]
Basically, this is the error:

![screen shot 2017-06-01 at 20 41 00](https://cloud.githubusercontent.com/assets/13735079/26705159/b54e4b08-470a-11e7-85ed-7390b7326112.png)

**Comment by aure** [comment]
You're using an old version of Xcode with Swift 3.0.2.  Update and this will go away.

**Comment by denisb411** [comment]
Sorry. I thought it was reversed. Anyway, no updates of Xcode shows for me, don't know why.
