### ISSUE TITLE
AudioKit.stop() seems broken

### ISSUE THREAD

**Issue by denisb411** [audiokit/AudioKit#923]
Hello,

Firstly I was attempting to use the new class AKMicrophoneTracker on another class that has a installTap on it and was found a messy problem: the installTap worked but was never called.

Took me several hours to find out that I had to set an AudioKit device (AKBooster(mic,gain:0) and call AudioKit.start() ir order to get this working.... Is there some documentation explaining this?

Second, the AudioKit.stop() isn't working.
If AudioKit.stop() is called, the AudioKit.start() never works anymore and this leads to the installTap problem. The worst thing is that this does't generate any error and it turns out to hard find out where's the error.

Check out my custom MicrophoneTracker:

https://gist.github.com/denisb411/d6b36062686a305a93141a2f6dac96fe

**Comment by aure** [comment]
The simplified microphone tracker was never meant for installing taps, its meant for when you just want quick access to the microphone frequency and amplitude.  If you want to get your own data, yeah, you have to use AKMicrophone and tap that.  

Stop is a very simple function

```
    /// Stop the audio engine
    open static func stop() {
        // Stop the engine.
        self.engine.stop()
        shouldBeRunning = false
        #if os(iOS)
        do {
            try AVAudioSession.sharedInstance().setActive(false)
        } catch {
            AKLog("couldn't stop session \(error)")
        }
        #endif
    }
```
Any reason why this is an issue and not just on Google groups?  Just wondering if you didn't think you were getting proper support there.  I tend to use Github issues for framework bugs where this is more of what is wrong with my set up type thing.

**Comment by aure** [comment]
I'm closing this hoping we can move the discussion to google groups, but if this can be further specified, reopen it as an issue.

**Comment by denisb411** [comment]
@aure 

I don't use AKMicrophoneTrack to tap, I create a new AKMicrophone to it. I use AKMicrophoneTrack together with the tap.

Please check the gist code.

My proposition here is to warn that when firstly start() the AudioKit and then stop(), taps on AKNodes (like AKMicrophone) will not work anymore even another start() is called before. Isn't it an issue?

**Comment by aure** [comment]
I don't think taps survive a start.  I feel like a tap is a very temporary thing and you might need to install the tap each time.
