### ISSUE TITLE
Consider removing variadic initializers?

### ISSUE THREAD

**Issue by warpling** [audiokit/AudioKit#924]
## Current Problem
Variadic initializers in classes like `AKMixer` make subclassing difficult:

For example `AKMixer` has the following initializer:
```
public init(_ inputs: AKNode?...) {
    super.init()
    self.avAudioNode = mixerAU
    AudioKit.engine.attach(self.avAudioNode)
    for input in inputs {
        connect(input)
    }
}
```

Because of the use of `_` combined with variadic parameters the behavior of subclassing and creating convenience initializers is unsupported:
##### Swift 3 warning: Synthesizing a variadic inherited initializer for subclass 'subclassName' is unsupported
```
public convenience init(inputs: [AKNode], addedParameter: Bool) {
   // ...
}
```

## Potential Solution
While variadics are convenient the same effect can be easily reached with the addition of two square brackets to pass an unambiguous array, which also allows for subclassing and convenience initializers. So this…
```
AKMixer(nodeA, nodeB)
```
becomes this…
```
AKMixer([nodeA, nodeB])
```

**Comment by aure** [comment]
That's pretty ugly.

**Comment by aure** [comment]
Considered. :)
