### ISSUE TITLE
Open Sound Control (OSC)

### ISSUE THREAD

**Issue by devinroth** [AudioKit/AudioKit#925]
I've noticed a few requests for OSC support in audioKit. I wrote a SwiftOSC library if you're interested in adding it into AudioKit.

https://github.com/devinroth/SwiftOSC

**Comment by aure** [comment]
That would be quite welcomed indeed.  Would you want us to make a copy and then maintain it along with everything else or are you thinking that we'd have an OSC example explaining how to integrate it with your Github repo?

**Comment by devinroth** [comment]
I haven't given it much thought. Either way would be fine with me. What do you think would be better?

**Comment by aure** [comment]
SwiftOSC hasn't changed for 11 months... not sure if that means its just stable or not being put through its paces.  As part of AudioKit it will probably be tested by someone.  If we include it as part of AudioKit, then you become part of the AudioKit core team.  If you keep it separate, then its up to us to coordinate an example.  Eventually we do want to modularize the components of AudioKit, so maybe it makes sense to keep it separate and start going down that path.  As you can see there are pros and cons, and I don't have much of a preference.

**Comment by devinroth** [comment]
SwiftOSC is sable for me but I'm probably the only one using it. If you're planning on modularizing AudioKit it's probably best to just keep them separate. Probably make it easier to deal with issues. I must say you're great at keeping on top of AudioKit. 

So what are you thinking would be a good example? Use OSC to control an audio synth?

**Comment by aure** [comment]
Hi, the only problem with this is that there are a lot of things going on and simply no time, but if you want to integrate it, I'll certainly provide help.  Otherwise it might wait until someone has a need for it.

**Comment by devinroth** [comment]
I'm looking to create work without reason. SwiftOSC is more of an altruistic offering.  No point creating more work unless someone actually has need. You know where to find me.

**Comment by aure** [comment]
Yeah, I know, and its a great offer, I know it will happen!

**Comment by OscarBouwmans** [comment]
Figure53 (maker of QLab) has made open source an Objective-C OSC library called [F53OSC](https://github.com/Figure53/F53OSC), using [CocoaAsyncSocket](https://github.com/robbiehanson/CocoaAsyncSocket).

Maybe not of much use for AudioKit, as it isn't written in Swift, but potentially interesting for developers reading this thread.

https://github.com/Figure53/F53OSC

**Comment by aure** [comment]
In an effort to pare down the growing list of issues, I'm going to close this issue, but add the repo and a link to this discussion to the AudioKit projects "MIDI" page: https://github.com/AudioKit/AudioKit/projects/3

**Comment by aure** [comment]
Just in case you've come to this issue checking out AudioKit with OSC:  https://github.com/AudioKit/AudioKit/pull/1622/
