### ISSUE TITLE
AKSettings.useBlueTooth not working

### ISSUE THREAD

**Issue by cheng-kang** [audiokit/AudioKit#926]
Hi, I followed the recorder example and changed AKSettings from .defaultToSpeaker to .userBluetooth, but no sound came out from the Bluetooth device.

Is there any solution to that?

```
        do {
            try AKSettings.setSession(category: .playAndRecord, with: .allowBluetooth)
        } catch {
            AKLog("Could not set session category")
        }
        
        AKSettings.useBluetooth = true
```

**Comment by aure** [comment]
Which version of AudioKit, what Bluetooth device?  How about a little information to go on.

**Comment by cheng-kang** [comment]
😅
AudioKit v3.7
Powerbeats Wireless

**Comment by cheng-kang** [comment]
I just accidentally made it work by adding the following code before playing the audio:

```
if let _ = try? AKSettings.setSession(category: .playAndRecord, with: .allowBluetooth) {
    // code for play audio file
}
```
Don't know why the session needs to be set twice though.

I'll create another project to reproduce the issue. Hope I could provide some useful information then.

**Comment by aure** [comment]
Glad you figured it out!
