### ISSUE TITLE
Crash when start recording

### ISSUE THREAD

**Issue by chashmeetsingh** [audiokit/AudioKit#927]
AURemoteIO:IOThread (10) EXC_BAD_ACCESS error comes each time I use `startRecording`.

Repo for testing: https://github.com/chashmeetsingh/Snowboy-Swift-Example'

@aure ^

**Comment by aure** [comment]
Busy with AltConf/WWDC but will look at this soon.

**Comment by chashmeetsingh** [comment]
No problem, I got it fixed already. Thanks.
Used EZAudio instead.
