### ISSUE TITLE
Podfile dependency missing

### ISSUE THREAD

**Issue by niklassaers** [audiokit/AudioKit#93]
Hi, to include AudioKit from Cocoapods, I had to add the dependency "pod 'TPCircularBuffer'" in addition to not get linker errors for missing functions in EZAudio.o. Perhaps this dependency should be added to the Cocoapod podspec?

**Comment by aure** [comment]
Hmmm, good catch, I think it has less to do with that podfile dependency and more to do with a .c file that didn't get included in AudioKit for TPCircularBuffer.c.  I have updated the Podspec in the develop branch and pushed the podspec up to cocoapds, hopefully this will fix it.

**Comment by aure** [comment]
Actually it looks like cocoapods is going to require me to update the version number for this process.

**Comment by niklassaers** [comment]
2.0.1? :-) As it stands, Audiokit doesn't compile with Cocoapods. The workaround I mentioned doesn't work for Swift projects that need to enable module support, so in that case it's won't compile at all.

I'd prefer the version bump to not compiling, but if you don't want to bump the version you could make the change in the podspec and then ask the user to point to your repo in the podfile in the README.md :-) For now I'll clone and send you a pull request for a version that includes the dependency, and can be included via a "pod 'AudioKit', :git => 'https://github.com/audiokit/AudioKit.git'"

**Comment by aure** [comment]
Hi, yeah we were just really improving the plots so I wanted to get those done before release a 2.0.1.  Let's get this resolved one way or another today, thanks.
