### ISSUE TITLE
Runtime issue in `+ (void)checkResult:(OSStatus)result operation:(const char *)operation`

### ISSUE THREAD

**Issue by hhanesand** [audiokit/AudioKit#930]
> file://Common/Internals/EZAudio/EZAudioUtilities.m: runtime: Undefined Behavior: Store to misaligned address 0x0dc5b791 for type 'UInt32' (aka 'unsigned long'), which requires 4 byte alignment
> 
> Misaligned pointer use
> #0	0x05940224 in +[EZAudioUtilities checkResult:operation:] at Common/Internals/EZAudio/EZAudioUtilities.m:531
> #1	0x0594d238 in -[EZAudioFile getWaveformDataWithNumberOfPoints:] at Common/Internals/EZAudio/EZAudioFile.m:447
> #2	0x0030d6e4 in MUSCachingWaveformView.loadAudioData(from:) at Library/Multitrack/Waveforms/MUSCachingWaveformView.swift:197
> #3	0x0030e728 in @objc MUSCachingWaveformView.loadAudioData(from:) ()
> #4	0x00163700 in -[MUSWaveformCoordinator didStartRecordingSessionWithRecordingTrack:] at Library/Multitrack/Waveforms/MUSWaveformCoordinator.m:162
> #5	0x0020ec56 in __57-[MUSMultitrackEditingCoordinator appendCurrentRecording]_block_invoke at Library/Multitrack/Editing/MUSMultitrackEditingCoordinator.m:144
> #6	0x00282f0a in __45-[BFTask(MUSTaskTools) mus_mainThreadResult:]_block_invoke at Library/Categories/BFTask+MUSTaskTools.m:120
> #7	0x0111066a in __62-[BFTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke at Bolts/Bolts/Common/BFTask.m:496
> #8	0x0110d7f2 in __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke at Bolts/Bolts/Common/BFTask.m:412
> #9	0x07fdf466 in _dispatch_call_block_and_release ()
> #10	0x07fdf452 in _dispatch_client_callout ()
> #11	0x07fe3d46 in _dispatch_main_queue_callback_4CF ()
> #12	0x1da2fd68 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
> #13	0x1da2de18 in __CFRunLoopRun ()
> #14	0x1d9811ae in CFRunLoopRunSpecific ()
> #15	0x1d980fd0 in CFRunLoopRunInMode ()
> #16	0x1f12bb40 in GSEventRunModal ()
> #17	0x22d02e12 in UIApplicationMain ()
> #18	0x0010ccf8 in main at Supporting Files/main.m:14
> #19	0x1d16e4ea in start ()

**Comment by aure** [comment]
I don't really know how to act on this.  I would need more information like what causes the problem. But, I am happy to reopen the issue with more info.
