### ISSUE TITLE
When will an Ableton LinkKit Interface be available

### ISSUE THREAD

**Issue by JoshuaBThompson** [audiokit/AudioKit#935]
We are looking forward to integrating Ableton linkKit with our AudioKit App but it seems like this is not so straight forward.
I've heard that this is on AudioKit's todo list.
Is this a feature that is in the works?

Curious :)

**Comment by aure** [comment]
Hi Joshua, yes, it is on our list: https://github.com/audiokit/AudioKit/projects/2
but no one has a project that required it yet, so it hasn't been started. I'd love to collaborate with you on it.

**Comment by JoshuaBThompson** [comment]
Hi Aure,
great, we are looking to integrate link as soon as possible.
Please let us know how you would like to proceed collaborating.

**Comment by aure** [comment]
Can I invite you to the AudioKit Slack group?  Email me with your email address.

**Comment by JoshuaBThompson** [comment]
@aure Sure,
Joshua
email: jbthompson.eng@gmail.com

**Comment by aure** [comment]
Closing this as an issue, because we'll be collaborating on Slack to get this done.
