### ISSUE TITLE
Crash on iOS 11.0

### ISSUE THREAD

**Issue by ekscrypto** [AudioKit/AudioKit#940]
Notes from the Apple Engineering team:

> **[AVAudioPlayerNode stop] cannot be called directly from within the completion handler. The client can dispatch_async this operation onto its own queue.** 
> 
> The header AVAudioPlayerNode.h has been updated in iOS 11, macOS 10.13 with this documentation.

BUFFER/FILE COMPLETION HANDLERS  … Note that a player should not be stopped from within a completion handler callback because it can deadlock while trying to unschedule previously scheduled buffers.

Thread 1 name: Dispatch queue: AVAudioPlayerNodeImpl.CompletionHandlerQueue Thread 1 Crashed: 0 libdispatch.dylib 0x000000018392ccb0 _dispatch_sync_wait + 608 1 AVFAudio 0x00000001a16acd34 AVAudioPlayerNodeImpl::StopImpl+ 650548 () + 204 2 AVFAudio 0x00000001a16acd34 AVAudioPlayerNodeImpl::StopImpl+ 650548 () + 204 3 AVFAudio 0x00000001a16abaf8 -[AVAudioPlayerNode stop] + 96 4 AudioKit 0x0000000102f17278 0x102be8000 + 3338872 5 AudioKit 0x0000000102f1adb0 0x102be8000 + 3354032 6 AudioKit 0x0000000102f1c700 0x102be8000 + 3360512 7 AudioKit 0x0000000102ec82e8 0x102be8000 + 3015400 8 libdispatch.dylib 0x000000018391e418 _dispatch_client_callout + 16 9 libdispatch.dylib 0x0000000183927414 _dispatch_queue_barrier_sync_invoke_and_complete + 56 10 AVFAudio 0x00000001a16adaec CallCompletionHandler(NSObject<OS_dispatch_queue>*, AVAudioPlayerNodeCompletionCallbackType, void + 654060 (AVAudioPlayerNodeCompletionCallbackType) block_pointer) + 140 11 AVFAudio 0x00000001a16ad6e8 AVAudioPlayerNodeImpl::Command::~Command+ 653032 () + 68 12 AVFAudio 0x00000001a16ad814 non-virtual thunk to AVAudioPlayerNodeImpl::BufferCommand:: ~BufferCommand+ 653332 () + 16 13 AVFAudio 0x00000001a16babd4 RealtimeMessenger::_PerformPendingMessages+ 707540 () + 68 14 AVFAudio 0x00000001a16baae8 RealtimeMessenger::ReceivePing+ 707304 () + 96 15 libdispatch.dylib 0x000000018391e418 _dispatch_client_callout + 16 16

**Comment by aure** [comment]
Thanks for the note.  I had actually heard about this, but iOS11 isn't out yet, so its not really supported by us yet. Soon we'll have a branch for it where this will be addressed so I'll leave the issue open till then.

**Comment by ekscrypto** [comment]
While this may not be officially supported by you guys, many of your developers are testing/developing their apps to support iOS 11 when it gets out.  Would be nice to have a working library!

**Comment by aure** [comment]
Fair enough, but I would counter by saying its open source and if you're a good enough developer to be working in beta OSes, you're probably good enough to also fix it and make a pull request! :)

**Comment by megastep** [comment]
To be fair, this warning seems to be pointing at a bad practice that Xcode was probably just pointing it out before Xcode 9. I doubt the semantics of the API have changed per se. We should probably fix it and I bet it might explain some of the weird crashes I have been seeing in my apps.

**Comment by aure** [comment]
@megastep the API has changed for the player, check out my WWDC Blog Post http://audiokit.io/blog/2017/06/13/wwdc/
