### ISSUE TITLE
AKTable[Type] not available in Objective C

### ISSUE THREAD

**Issue by tghs** [AudioKit/AudioKit#941]
When using AudioKit from Objective C, AKTable and AKTableType don't appear to be exposed correctly. I'm getting undeclared identifier errors.

Tested with the release framework build: AudioKit-iOS-3.7.1.zip.

**Comment by aure** [comment]
Hmm yeah, that's troublesome.

**Comment by aure** [comment]
I'm sorry for leaving this issue hanging for so long, should work for you now.

**Comment by tghs** [comment]
Perfect, thanks very much!
