### ISSUE TITLE
AKVariSpeed

### ISSUE THREAD

**Issue by themichael123** [AudioKit/AudioKit#942]
Hi !

Whilst trying to use AKVariSpeed with nodes i.e. not playback from a file the following error message is being shown: 

*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: false == isInputConnToConverter'
***

Thanks for your help!

**Comment by aure** [comment]
You can’t control the speed of just anything, it has to be file based so it can look in the future.

**Comment by themichael123** [comment]
Got it. Thanks!
