### ISSUE TITLE
Module compiled with Swift 3.0.1 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by Tauf** [AudioKit/AudioKit#944]
I am using AK 3.7.1 and after updating XCode I am getting the following:
"Module compiled with Swift 3.0.1 cannot be imported in Swift 3.1"

Can you help me?

**Comment by aure** [comment]
If you've got the source, just rebuilt the framework by cd into Frameworks/ and then doing ./build_frameworks.sh

**Comment by aure** [comment]
A clean and build may also do the trick.

**Comment by Tauf** [comment]
Thanks for your response. I was just wondering if you guys plan to provide a pre-built version any time soon.

**Comment by aure** [comment]
Which version of Xcode are you using?

**Comment by aure** [comment]
Pretty sure the prebuilt version with 3.7.1 is for Swift 3.1. That's why I was thinking you mihgt need to clean. Right @megastep?

**Comment by megastep** [comment]
Yeah the current version should have been built with Swift 3.1 which is what is in the current Xcode 8.3.
