### ISSUE TITLE
When Archiving the iOS app for the App store files get removed

### ISSUE THREAD

**Issue by themichael123** [AudioKit/AudioKit#950]
Hi Guys!

apparently, when archiving a build to publish on the App Store some files get deleted leading to a large list of errors:

This file gets deleted: AudioKit.framework/fix-framework.sh

.../AudioKit.framework/fix-framework.sh: line 6: cd: /Users/.../Library/Developer/Xcode/DerivedData/.../Build/Intermediates/ArchiveIntermediates/.../BuildProductsPath/Release-iphoneos/.../Frameworks: No such file or directory
find: ./AudioKit.framework/BCSymbolMaps: No such file or directory
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

Thanks for your help!

**Comment by themichael123** [comment]
I am using v3.7.1

**Comment by aure** [comment]
@megastep should be able to give you an idea of what's going wrong.  People haven't had too many issues getting AudioKit into the store, but when they do its often around that script.

**Comment by megastep** [comment]
The most common cause of this kind of error is the run script being called at the wrong time. Specifically you should have a phase that happens after the "Embed Frameworks" phase in your project. Is it the case?

Instructions here: https://github.com/AudioKit/AudioKit/blob/develop/Frameworks/README.md

**Comment by themichael123** [comment]
Configuration mistake on my part! Sorry and thanks for your help !
