### ISSUE TITLE
AKPanner crash when numberOfChannels = 1

### ISSUE THREAD

**Issue by frasersdev** [AudioKit/AudioKit#953]
I'm doing some CPU optimisation and as part of that I have set `AKSettings.numberOfChannels = 1` - audioKit promptly crashed at next run when starting up the panners. 

yes I understand having a panner in a mono signal path is completely meaningless.

I have traced the crash to the process(AUAudioFrameCount frameCount, AUAudioFrameCount bufferOffset) function in [AKPannerDSPKernel.hpp](https://github.com/AudioKit/AudioKit/blob/dd91071bdeb617b18f8d551120ce2a6efbb97cbf/AudioKit/Common/Nodes/Mixing/Panner/AKPannerDSPKernel.hpp) The problem seems to be the sp_panst_compute() function gets passed uninitialised pointers as the for(;;) loop didn't go through the expected number or loops.

```
  | float *tmpin[2];
  | float *tmpout[2];
  | for (int channel = 0; channel < channels; ++channel) {
  |     float *in  = (float *)inBufferListPtr->mBuffers[channel].mData  + frameOffset;
  |     float *out = (float *)outBufferListPtr->mBuffers[channel].mData + frameOffset;
  |     if (channel < 2) {
  |          tmpin[channel] = in;
  |          tmpout[channel] = out;
  |      }
  | }
  | sp_panst_compute(sp, panst, tmpin[0], tmpin[1], tmpout[0], tmpout[1]);
```
tmpin[1] & tmpout[1] never get set if channels = 1

I suppose you could probably just  set outbuffer[0] = inbuffer[0] as if the panner was bypassed when its operating in a mono signal path but I'll leave the solution up to those who know audiokit better

**Comment by aure** [comment]
okay, I think your solution makes sense
