### ISSUE TITLE
Connecting an OUTPUT prompts the user to access the Microphone

### ISSUE THREAD

**Issue by npahucki** [audiokit/AudioKit#96]
AudioKit Version 2.0 
iOS 8

        let audio = AKAudioOutput(audioSource: osc)
        self.connect(audio)

As soon as I connect the AKAudioOutput to a subclass of AKInstrument, a prompt asking to use the Microphone is issued. Since I am not trying to do anything at all with input, this seems like a bug. 

Is there any workaround to this?

**Comment by aure** [comment]
In the develop branch there is a setting in the Core Classes/AudioKit.plist file that allows you to choose whether or not use microphone access.  P.S. Also in you can do both the lines above with "setAudioOutput(osc)

**Comment by npahucki** [comment]
I don't think this issue is resolved. I tried with version 2.0.1 and i can see that in AKOrchestra, the setting 'Enable Audio Input By Default' is being read, AND that the [[AKManager sharedManager] disableAudioInput] is being called, however, the microphone prompt happens BEFORE this code block is ever hit, so the setting in the plist file is not doing anything to prevent the message from showing. Further suggestions? 

I'm going to see if I can pin point exactly which line of code is causing the microphone prompt, but you could probably direct me faster than I could find it by trial and error.

**Comment by npahucki** [comment]
BTW: I tried HEAD of the development branch and it will not compile, missing files.

**Comment by npahucki** [comment]
I found and fixed the problem, see https://github.com/audiokit/AudioKit/pull/117.

**Comment by megastep** [comment]
In the develop branch, we now have an `AKSettings` class encapsulating the contents of the plist, so you now need to get the proper attribute from the singleton object instead of parsing the plist.

**Comment by megastep** [comment]
And actually, looking at the current state of the code, it already mirrors what you patch does so no further action is needed on `develop`. :)

**Comment by aure** [comment]
Actually what Nathan did was relevant to the develop branch, but the implementation was different so I changed it to match.  Thanks again Nathan!
