### ISSUE TITLE
Memory leak from AKOscillator

### ISSUE THREAD

**Issue by jhristov** [AudioKit/AudioKit#961]
AudioKit from the **develop** branch (compiled with Swift 3.2 for iOS 11) gives memory leaks when running a simple Oscillator test:

        let oscillator = AKOscillator()
        AudioKit.output = oscillator
        AudioKit.start()

[AudioKitXXX.zip](https://github.com/AudioKit/AudioKit/files/1167192/AudioKitXXX.zip)
![screenshot](https://user-images.githubusercontent.com/29655331/28489416-476b1e60-6ecc-11e7-85a0-d1be800b5a29.jpeg)

**Comment by aure** [comment]
I'm not sure what I should do with this information.  Doesn't seem to egregious to me.

**Comment by aure** [comment]
@dave234 Could this also be examined as part of an audit process?

**Comment by dave234** [comment]
I'll try to reproduce the leak, but it seems negligible at < 1K.  Foundation leaks way more than that in my experience.

**Comment by dave234** [comment]
Oh, iOS 11, lets wait until release.

**Comment by aure** [comment]
Okay, I'll just close this issue now but we'll keep a note to look for significant memory leaks.
