### ISSUE TITLE
Why isn't it possible to connect AKAudioPlayers on the go?

### ISSUE THREAD

**Issue by julienfouilhe** [AudioKit/AudioKit#970]
(Tried to post this on Google Groups but there was no button to create a new topic, sorry)

Hi, first of all, incredible work, thank you very much!

I'm wondering about what happens there:
https://github.com/AudioKit/AudioKit/commit/1e562cac251b88b143b19184eb14356fec0f1825#diff-3268b51331ad6b09923655df2fb42f81R54

My use case is:

I have a description of a music, with notes, their volume, effects to apply to them etc. Sometimes, there can be thousands of notes, that have to be played at specific times.
Since it was not possible to change the signal chain, I initialized everything at once, and it works great, but it also takes a long time to load and about 3Gb of memory for something that is not even really a big file.

What I would like to do is schedule my next AVAudioPlayers every X seconds, but AKMixer won't let me do that and stops everything that's playing if I try.

I'm wondering if anyone has an idea about how I can achieve that? Do I have to abandon the idea of using AudioKit?

Cheers!

**Comment by aure** [comment]
I'll look at your issue, but firsst, Google groups should have a new topic button...

![screen shot 2017-08-02 at 1 52 53 pm](https://user-images.githubusercontent.com/13122/28894538-f890019a-7789-11e7-97ca-92f3843918f6.png)

**Comment by julienfouilhe** [comment]
Yup it does now, it appears I had to be accepted to be able to post. Do you want me to take the conversation there?

Thanks a lot!

**Comment by aure** [comment]
I'm not sure how AKMixer could stop you from controlling a specific AKAudioPlayer. If you're able to share your project or even message me privately on what you're trying to do, I might be able to lead you in a better direction.

**Comment by aure** [comment]
I think you'd be well served to organize your files into a Soundfont and then use AKSampler to play it. It will do much better with memory handling and using standard midi to play back the appropriate sounds.  You could even use sequencing to play back at the proper times.  Do you know about soundfonts or soundfont support in AudioKit?  I should probably highlight it more.

**Comment by julienfouilhe** [comment]
I abandonned the idea of using AKSampler because I didn't find how to schedule notes for later and how to set a duration.

Is there a way to do that? Just like AKAudioPlayer is doing with from:to:avTime :)

Thanks a lot!

**Comment by aure** [comment]
Your control would be play and stop (playtime+duration) on any given note number.  The timing would either be up to you via scheduling or via midi sequencing.

**Comment by julienfouilhe** [comment]
Would this allow me to have a microsecond accuracy? If I understand correctly what you're saying, I would have to play/stop notes using some kind of timer such as `Timer.scheduledTimer`, do you think I can expect at least a microseconds accuracy? If notes are delayed it won't sound right to our users :/

Again, thanks a lot for your help!

**Comment by aure** [comment]
Usually durations / stop time variations are much less noticeable, if detectable at all with notes that decay out.  As for start times, I'm not sure AKAudioPlayers start time is that accurate either.  You probably should test to make sure.  AKSamplePlayer is another option.

**Comment by dave234** [comment]
Hi Julien,  I'm working on a file based player called AKClipPlayer.  You can use it to schedule multiple audio clips of multiple files in a sequence .  It's based off of AVAudioPlayerNode so there's very low memory usage and it does give sample accuracy.  It's in a good working state, but I need to clean it up and try to push it to develop.  I'll try to get to it sooner than later.

**Comment by dave234** [comment]
I just read further up the thread.  Why not AKSampler/AKSequencer?  Seems like the way to go.

**Comment by julienfouilhe** [comment]
@aure @dave234 Ok, thank you very much, I'll try it to see if we can work with that! I'll come back then to keep you guys and potentially future struggling users updated!

**Comment by ryanfrancesconi** [comment]
@aure AKAudioPlayer's scheduled start time is accurate.

**Comment by aure** [comment]
@ryanfrancesconi Thanks for the affirmation!

**Comment by julienfouilhe** [comment]
Hi guys!

First of all thank you for your help, I use AKSampler now and it seems to work great for now (not tested thoroughly yet).

Basically what I do is load each instrument into a AKSampler, that I connect to a mixer, which is connected to my main mixer.

**The problem** is when I have more than one AKSampler. It seems like having a second AKSampler, even if that second one does not play anything, changes the way the first AKSampler sounds in the end.

Here is what I do:

```
let mainMixer = AKMixer()
let mixer1 = AKMixer()
let mixer2 = AKMixer()

let sampler1 = AKSampler()
sampler1.loadAudioFiles(files1)
let sampler2 = AKSampler()
sampler2.loadAudioFiles(files2)

mixer1.connect(sampler1)
mixer2.connect(sampler2)

mainMixer.connect(mixer1)
mainMixer.connect(mixer2)

AudioKit.output = mainMixer

AudioKit.start()

// later on

Timer.scheduledTimer(...) {
  sampler1.play(midiNumber: midiNote, velocity: 1, channel: 1)
}
```

Now if I remove the sampler2, everything sounds the way it should, great! But if I have 2, or more than 2, the sound is like distorted like if there was a reverb effect applied to it, or even like if it was a totally different instrument.

Is that not the way to do it, the WebAudioAPI allows us to do so, but I haven't seen examples of AudioKit using several AKSamplers, is it possible this is a bug?

I also have the following files architecture, where files for all my soundfonts are named the same, but within a different directory:

-- acoustic_grand_piano
---- C3.m4a
---- C4.m4a
---- ...
-- percussion_kit
---- C3.m4a
---- C4.m4a
---- ...
-- ...

I don't think this is the problem though but I thought I would say it just in case.
