### ISSUE TITLE
Can't get Playgrounds to work at all, or the code even compiling.

### ISSUE THREAD

**Issue by kcorey** [AudioKit/AudioKit#974]
Hi All,

Just trying to do the basic hello world audiokit sample.

AudioKit 3.7.1, XCode 8.3.3 (and/or 9.0-beta), AppCode 2017.2.

I can't seem to get the playgrounds working at all.  Spent 1/2 a day, and no luck. "AudioKit is not defined".

Okay, methinks, I'll just add the framework to my classes skipping the framework.  As long as I don't call the AudioKit, it compiles.

The first couple of lines of Audiokit Hello, World.:

    var oscillator = AKOscillator()
    
    AudioKit.output = oscillator  <<< highlights 'AudioKit' as "Expected Definition".

When I cmd-click through AudioKit, AudioKit is an @interface.

So, anyone seen anything to cause this sort of behaviour?

**Comment by aure** [comment]
Want to do a screenshare? I can invite you to Screenhero if you send me your email address.

**Comment by aure** [comment]
Just a general piece of advice.  If you download the playground stuff directly, it should "just work".  If you're working from the source, you'll need to run build_frameworks.sh in the Frameworks directory, and undo the changes you made that doesn't sound right.  I'll close this issue for now but you can add to it or email me directly and I'll get you up and running.

**Comment by kcorey** [comment]
Hi Aurelius,

Thanks for the offer!  I’ll take you up on it.

I’m on Screenhero as ‘kcorey’.

Is there a specific time over the next few days that would be good for you?

For the record, I am pulling in AudioKit as a Cocoapod.  I was on version 3.5.0, but I’m on 3.7.1 now.

I’ve installed the iOS beta on my iPad (and XCode 9 beta on my iMac, as well as 8.3.3).  Could that have caused issues?

-Ken

**Comment by aure** [comment]
I need an email to connect with you on screenhero.  I think it has to do with cocoapods.  Can you try just downloading it direct from https://github.com/AudioKit/AudioKit/releases/download/v3.7.1/AudioKitPlaygrounds-3.7.1.zip

**Comment by aure** [comment]
That version will require Xcode8.3.  You'll have to build the version for Xcode9 beta on your machine, but I can work you through that.

**Comment by kcorey** [comment]
Sorry...my email is 'ken@kencorey.com'.

I've downloaded the zip file you've linked to...still says no such module AudioKit/AudioKitPlayground.

**Comment by aure** [comment]
Did you run build on the playground project cmd-B or the play button?
