### ISSUE TITLE
More than one AKSampler makes weird noises

### ISSUE THREAD

**Issue by julienfouilhe** [AudioKit/AudioKit#976]
I feel like this could be a bug from AudioKit, or at least something that should be explained in the docs if it's a normal behaviour, hence why I'm positing it here instead of Google Groups.

It seems like having more than one AKSampler, even if only one plays anything, changes the way the first AKSampler sounds in the end.

Here is what I do (it's obviously sample code, everything is well retained and I don't get any error)

```
let mainMixer = AKMixer()
let mixer1 = AKMixer()
let mixer2 = AKMixer()

let sampler1 = AKSampler()
sampler1.loadAudioFiles(files1)
let sampler2 = AKSampler()
sampler2.loadAudioFiles(files2)

mixer1.connect(sampler1)
mixer2.connect(sampler2)

mainMixer.connect(mixer1)
mainMixer.connect(mixer2)

AudioKit.output = mainMixer

AudioKit.start()

// later on

Timer.scheduledTimer(...) {
  sampler1.play(midiNumber: midiNote, velocity: 1, channel: 1)
}
```

Now if I remove the sampler2, everything sounds the way it should, great! But if I have 2, or more than 2, the sound is like distorted like if there was a reverb effect applied to it, or even like if it was a totally different instrument.

Isn't that the way to do it, the WebAudioAPI allows us to do so, but I haven't seen examples of AudioKit using several AKSamplers, is it possible this is a bug?

I also have the following files architecture, where files for all my soundfonts are named the same, but within a different directory:

acoustic_grand_piano
--     C3.m4a
--     C4.m4a
--     ...
percussion_kit
--     C3.m4a
--     C4.m4a
--     ...
...

I don't think this is the problem though but I thought I would say it just in case.

**Comment by aure** [comment]
You mixer logic is a little weird.  I mean, it seems like it should work but all you're doing ins mixing two things so I don't see why you've got three mixers.  Here's an example app that works with many samplers.  https://github.com/John231/Drums808/blob/master/Drums808/samplerEngine.swift

That example uses wavs.  I think you might need to have the sounds in a specific subdirectory named "Sounds/" as discussed here. 

Finally if you'd like to share your project, we can probably get to the bottom of things fairly quickly.

**Comment by julienfouilhe** [comment]
I tried to do a playground with my use case but it was working, so I had a look at my code again and realized that since I'm using On Demand Resources, samplers were initialized after AudioKit.start() was called. Since there was no problem when only one Sampler was initialized I didn't look there.

Sorry and again thank you for this flawless library! :)

**Comment by aure** [comment]
Ha!  Well, its not flawless, but hopefully "always improving". :)
