### ISSUE TITLE
Analyse audio file without playing

### ISSUE THREAD

**Issue by AntonFox** [AudioKit/AudioKit#977]
read file by parts and get fft data, amplitude and other values without playing/out sound and waiting when playing ends

**Comment by aure** [comment]
This is possible with the latest iOS and OSX updates which should be released in September I guess.

**Comment by AntonFox** [comment]
Cool, thanks, waiting next release

**Comment by aure** [comment]
There's an example of offline rendering in the SongProcessor now, which could be used to do analysis without playing.

**Comment by charliewilliams** [comment]
I'm interested in offline analysis, but I can't find this "SongProcessor" in the docs or in the github download. Can you point me toward it? Thanks
