### ISSUE TITLE
trouble building with xcode 9 - Version 9.0 beta 5 (9M202q) 

### ISSUE THREAD

**Issue by johndpope** [AudioKit/AudioKit#980]
<img width="1392" alt="screen shot 2017-08-09 at 2 54 02 pm" src="https://user-images.githubusercontent.com/289994/29138751-9f530d28-7d12-11e7-8bad-2f5b9dd6eada.png">

**Module compiled with Swift 3.1 cannot be imported in Swift 4.0: /Users/jpope/Desktop/AudioKit/Examples/iOS/SongProcessor/Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/arm64.swiftmodule**

tried compiling to device with ios 11 + simulator - 

I'm using cocoapods so that is most likely culprit.
Thought I'd capture this in this ticket.

<img width="1180" alt="screen shot 2017-08-09 at 2 51 40 pm" src="https://user-images.githubusercontent.com/289994/29138688-85cc9586-7d12-11e7-9d1b-48c273044b25.png">

tried this - to no avail.
```
target 'SongProcessor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SongProcessor
  pod 'AudioKit'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.2'
          end
      end
  end
end


```
https://stackoverflow.com/questions/44399109/xcode-9-module-compiled-with-swift-3-1-cannot-be-imported-in-swift-4-0

<img width="694" alt="screen shot 2017-08-09 at 2 59 04 pm" src="https://user-images.githubusercontent.com/289994/29138998-55c159fc-7d13-11e7-897e-2632504174dd.png">

rm -rf ~/Library/Developer/Xcode/DerivedData
also failed

**Comment by megastep** [comment]
Yeah, the binaries referenced in the pod were compiled with Xcode 8. So you can't use the pod version with Xcode 9, you'll have to build it from source, though that it is easy enough to do with the `build_frameworks.sh` script in Frameworks.

**Comment by johndpope** [comment]
ah - thank you.

**Comment by johndpope** [comment]
not Audiokit's problem but fyi - 
seems like you need to be on high sierra to build successfully.
I'm on sierra 10.12.6 (16G29)

/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/**MacOSX10.13**.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVFoundation.h:88:9: error: 'AVFoundation/AVRouteDetector.h' file not found

**Comment by megastep** [comment]
Actually, that is a problem with Xcode 9 beta 5 that came out yesterday. They broke AVFoundation on macOS and as such you can't build AK for Mac with this version.

If you don't need the macOS version, I suggest you specify the `PLATFORMS=iOS` environment variable before running the `build_frameworks.sh` script to skip it.

**Comment by johndpope** [comment]
thanks again.

**Comment by aure** [comment]
Thanks, Apple. :)

**Comment by lamgadekamal** [comment]
@megastep could you elaborate a bit how is it possible to build it from source or with build_frameworks.sh script in frameworks? I am having the same error as below:

`The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler`

**Comment by megastep** [comment]
The README here should tell you what you need to know: https://github.com/AudioKit/AudioKit/tree/develop/Frameworks

**Comment by frakman1** [comment]
- Using cocoapods for AudioKit and 
- Run into this very problem, then
- Built AudidoKit from source using build_frameworks.sh

Now what?

I still get this error despite removing Audiokit from the Podfile and manually adding the freshly built AudioKit Framework to my project. What am I missing?

**Comment by aure** [comment]
@frakman1 this issue is getting pretty convoluted to follow so I am going to close it to additional comments.
