### ISSUE TITLE
SongProcessor LoopsViewController.swift - play bunch of caf files together at once. 

### ISSUE THREAD

**Issue by johndpope** [AudioKit/AudioKit#981]
Expectation 

I open songprocessor -> click loops
there's the ability to solo the mix - but I want each wav file playing separately.

inside LoopsViewController
-> 
 let _ = try? songProcessor.audioFilePlayer?.replace(file: songProcessor.audioFile!)
this is blowing away any playing audio. 

I'll keep digging and submit a PR if I can resolve.

**Comment by aure** [comment]
Calling this an enhancement to separate it from known bugs.

**Comment by johndpope** [comment]
here's a video from - https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine
@michaeltyson - has retired this code base and yield power to this repo - but it looks like it still valid and worthwhile. Michael - would you be opposed to salvaging some of your code for mixing (providing it's appropriately licensed / attributed)

**Comment by michaeltyson** [comment]
Possibly - the only reason I'd be opposed is if the code were crappy; TAAE 1 generally no longer meets my standards, so I'd be a little skittish at the idea. TAAE 2, which despite my public claims of retirement is actually alive and well though (I just didn't want to handle all the questions =)), so happy for any DSP stuff from there to be used. It's zlib licensed, so pretty open.

**Comment by johndpope** [comment]
no problem @michaeltyson - 
I also found this - seems Apple have gone to some efforts to catch up in this space.
 https://developer.apple.com/library/content/samplecode/AVAEMixerSample/Introduction/Intro.html#//apple_ref/doc/uid/TP40015134  - the demo sucks - you need to swipe down to close the vc (it wasn't clear when I first tried it) you can actually add multiple effects / sounds / recording.

**Comment by johndpope** [comment]
video of apple mixer - 2017 - august
https://drive.google.com/open?id=0B-w3I-xzXGu0bFBya0labW9xRGc

**Comment by aure** [comment]
Not sure why this issue to combine audio has changed into a discussion of TAAE, but if all you want to do play multiple files, why not just use AKMixer and multiple players?

**Comment by aure** [comment]
Since this issue is ill defined, I'll close the issue for now.  You can still use this as a forum for discussion, but I just don't think it should be on our open issues page.  Its re-openable if necessary.

**Comment by johndpope** [comment]
sorry about google drive sharing permissions - I updated.
I threw this code together this morning - https://gist.github.com/johndpope/059f8aaaafab14b28756fa47558102e5

my intention is to be able to play / pause a whole bunch of tracks / fade in / out.
<img width="253" alt="screen shot 2017-08-10 at 10 55 09 am" src="https://user-images.githubusercontent.com/289994/29176641-667c60fa-7dba-11e7-8f67-adbb2311638f.png">

you mentioned using layers - I'm running into memory issues when I use so many players - but will keep digging.  I'm using caf - but might try to switch to mp3 to reduce memory foot print.

**Comment by aure** [comment]
There's a tradeoff of course, you do have to use CPU cycle to expand mp3s and depending on the implementation, sometimes the expanded version is kept in memory.  Have you thought about wrapping all your samples up into a soundfont or EXS24 file? That would probably be best way to avoid reinventing the wheel.

**Comment by dave234** [comment]
FYI I'm using the SongProcssor example to demonstrate offline renderer
before I create a pull request for it.  I actually did end up using an
array of file players so that I could also demonstrate how to synchronize
the AKAudioPlayer in an offline context (merge pending).  The offline
renderer isn't in there yet, but will be soon.  Anyhow, here it is
https://github.com/dave234/AudioKit/tree/songProcessorUpdate.

Dave

**Comment by johndpope** [comment]
for some unknown reason - memory problems resolved using full blown caf files.
(maybe because I'm using 6s not iphone 6.) 
https://gist.github.com/johndpope/059f8aaaafab14b28756fa47558102e5
almost done - 
I will recode so that player has all players playing synchronised - but will mute tracks on / off. 
just need to dive into documentation.
