### ISSUE TITLE
AKAudioPlayer - Playing from certain time

### ISSUE THREAD

**Issue by Xcoder89** [AudioKit/AudioKit#982]
The fix for iOS 11 crash #945 seems to have messed up the working of play(from time:) i.e player doesn't restart. Perhaps moving stop to the main thread is creating a race condition.

**Comment by aure** [comment]
oh crap.  Should we revert for now?

**Comment by Xcoder89** [comment]
From the discussion in #940, I suppose dispatch_async is needed only when called within the completion handler.

**Comment by aure** [comment]
There have a been a number of changes to AKAudioPlayer in the develop branch, is this still an issue and if so can you make a pull request with a fix?
