### ISSUE TITLE
AVAudioFile crashes instead of throwing error when loading an invalid file

### ISSUE THREAD

**Issue by julienfouilhe** [AudioKit/AudioKit#983]
Hi I have the following code:

```swift3
do {
    let audioFile = try AKAudioFile(forReading: url)
    soundfont.append(audioFile)
} catch {
    Crashlytics.sharedInstance().recordError(error, withAdditionalUserInfo: [
        "instrument": self.id,
        "file": file,
        "path": url,
    ])
}
```

I get a EXC_BAD_ACCESS error instead of having my catch execute.

I've attached the corrupt file if need be, but clearly this is an automatically generated file that shouldn't be there in the first place. Still :)

[corrupt.zip](https://github.com/AudioKit/AudioKit/files/1215307/corrupted.zip)

**Comment by aure** [comment]
So I think what's happening here is that soundfont.append cannot be in the do try catch cycle. audioFile should be declared outside of the do and try'ed inside.  Let me know if that fixes things.
