### ISSUE TITLE
Enhancement / clarification - AKAudioPlayer - isMuted to allow toggling audio on /off

### ISSUE THREAD

**Issue by johndpope** [AudioKit/AudioKit#986]
Background

I'm wanting to audition audio stems and solo / mute / unmute them on iphone
currently I dig up relative files from bundle (say x10 - currently it's not limited) >
I then create separate AKAudioPlayers for each track
https://gist.github.com/johndpope/059f8aaaafab14b28756fa47558102e5

rather than trying to keep them in sync by system timer / I simply want to mute / unmute them. 
It seems this is possible globally via AKSettings / or perhaps if I go to the trouble of creating a AKSettings instance for each player? 

https://github.com/AudioKit/AudioKit/blob/cb1207dbdd77723cbcdb9aed69e4e625bb4a37e8/AudioKit/Common/Nodes/Playback/Player/AKAudioPlayer.swift

related
https://github.com/AudioKit/AudioKit/issues/981

**Comment by dave234** [comment]
I'm actually working on this on the same [example](https://github.com/dave234/AudioKit/tree/songProcessorUpdate/Examples/iOS/SongProcessor) :)

I'm still cleaning up the iTunes importer, but it's doing exactly what you were hoping.

**Comment by johndpope** [comment]
Nice. It seems like the only way to mute a track here is by stopping it then to unmute would be .....schedule a start time from current playing time ???

**Comment by dave234** [comment]
If an AKAudioPlayer is upstream from a mixer you can just set AKAudioPlayer.volume = 0 to mute, and . AKAudioPlayer.volume = 1 to un-mute.

**Comment by aure** [comment]
Yeah, I'm not for adding an isMuted thing to the player.

**Comment by johndpope** [comment]
that's not a problem. can bend the rules here with this hack.
unfortunately ran into a new challenge - new ticket to follow.

```
extension AKAudioPlayer{
    func isMuted()->Bool{
        if (self.volume > 0){
            return false
        }else{
            return true
        }
    }
    
    func unmute(){
        self.volume = 1
    }
    func mute(){
        self.volume = 0
    }
}
```

**Comment by aure** [comment]
That's not bending the rules, you're more than welcome to extend AudioKit as you see fit!  Cheers!
