### ISSUE TITLE
EZMicrophone calls Objective-C from the render thread in EZMicrophone.m

### ISSUE THREAD

**Issue by dave234** [AudioKit/AudioKit#991]
static OSStatus EZAudioMicrophoneCallback(void                       *inRefCon,
                                          AudioUnitRenderActionFlags *ioActionFlags,
                                          const AudioTimeStamp       *inTimeStamp,
                                          UInt32                      inBusNumber,
                                          UInt32                      inNumberFrames,
                                          AudioBufferList            *ioData)
{
    EZMicrophone *microphone = (__bridge EZMicrophone *)inRefCon;
    EZMicrophoneInfo *info = (EZMicrophoneInfo *)microphone.info;
    
    // render audio into buffer
    OSStatus result = AudioUnitRender(info->audioUnit,
                                      ioActionFlags,
                                      inTimeStamp,
                                      inBusNumber,
                                      inNumberFrames,
                                      info->audioBufferList);
    
    // notify delegate of new buffer list to process
    if ([microphone.delegate respondsToSelector:@selector(microphone:hasBufferList:withBufferSize:withNumberOfChannels:)])
    {
        [microphone.delegate microphone:microphone
                          hasBufferList:info->audioBufferList
                         withBufferSize:inNumberFrames
                   withNumberOfChannels:info->streamFormat.mChannelsPerFrame];
    }
    
    // notify delegate of new float data processed
    if ([microphone.delegate respondsToSelector:@selector(microphone:hasAudioReceived:withBufferSize:withNumberOfChannels:)])
    {
        // convert to float
        [microphone.floatConverter convertDataFromAudioBufferList:info->audioBufferList
                                               withNumberOfFrames:inNumberFrames
                                                   toFloatBuffers:info->floatData];
        [microphone.delegate microphone:microphone
                       hasAudioReceived:info->floatData
                         withBufferSize:inNumberFrames
                   withNumberOfChannels:info->streamFormat.mChannelsPerFrame];
    }
    
    return result;
}

**Comment by aure** [comment]
I don't think we use EZMicrophone for any audio output activities, so it shouldn't be a problem.  Its only used for analysis, in which case a pause in processing wouldn't resulting in any frame dropping or badness.  Unless I am mistaken?

**Comment by dave234** [comment]
Unless you're using it in an offline render, it will be called from the audio render thread.  So even if it's not producing audio directly in the callback, it can block the thread, choking other operations on that thread.  This can even affect inter-app audio, it's a system priority thread used across all apps.  I think this is why audio developers have to restart their devices more than others :)

**Comment by dave234** [comment]
This particular issue will often not have any noticeable side effects during development, but will definitely cause problems when multiple audio apps are running with low latency.  I think we should do an audit at some point.  [This](https://github.com/TheAmazingAudioEngine/RealtimeWatchdog) would be a good place to start.

**Comment by aure** [comment]
But I don't think its being used by AudioKit apps unless they create AKMicrophoneTracker.  Why would you use a microphone in an offline render?

**Comment by dave234** [comment]
You wouldn't I suppose, I only mentioned it for completeness.  An offline render would be the only context where it could be called on a thread other than the audio render thread.

**Comment by aure** [comment]
Cool, not be defensive, just I am not sure what to about these issues.  I'd love for more capable people to do an audit!

**Comment by dave234** [comment]
Didn't seem defensive :)  One way to test is to just add a breakpoint and look at the thread it breaks on.  There shouldn't ever be any Swift or Objective-C on that thread.  Michael Tyson's watchdog MACRO will catch Objective-C, but we just need to be diligent for Swift.

**Comment by aure** [comment]
Are there any tasks we can take to address this issue?

**Comment by dave234** [comment]
Yes.  I'm creating a fast tap implementation where audio can be pulled from the render thread, rather than on a callback like a normal tap.  This will allow for faster updates in general.  In the case of EZAudio, it will look the same visually, but will use considerably less CPU, and will not risk mucking up the render thread.  Currently it's dispatching to the main thread every render which is expensive, and risks audio pops.

**Comment by aure** [comment]
Awesome, thank you!

**Comment by dave234** [comment]
I looked at implementing the fix I was talking about, but after looking at the rest of EZAudio it looks to me like we should strip out most of what's there, leaving just the plotting functions.  There's a lot of use of AUGraph, which IMO doesn't belong in the same codebase.

**Comment by aure** [comment]
Okay, I think I know what needs to be done and it is partially on its way, not sure this needs to be a public issue as I don't think its causing any problem.
