### ISSUE TITLE
Precise synchronization of multiple AKAudioPlayers

### ISSUE THREAD

**Issue by johndpope** [AudioKit/AudioKit#994]
Using this code - I grab 10 local files eg .caf (drums / bass/ vocals) and create associated audio players. Based off SongProcessor
https://gist.github.com/johndpope/059f8aaaafab14b28756fa47558102e5

I press - play mix
and rather than playing a single file which is a mix as demo is designed - I want to simultaneously play multiple files. 

Digging under the hood it doesn't seem to use AVAudioPlayer
https://developer.apple.com/documentation/avfoundation/avaudioplayer

<img width="776" alt="screen shot 2017-08-11 at 8 04 24 pm" src="https://user-images.githubusercontent.com/289994/29235782-4edae310-7ed0-11e7-87c4-602a5d89b7ec.png">

Expected outcome - plays all files at once.

What actual happens - it does do this - but it's not precisely synchronized. 
Seems some start sooner than others.

I don't know if there's a quick remedy - or I'm bumping up against design of code.

**Comment by dave234** [comment]
This should really be a support question.

[Here](https://github.com/AudioKit/AudioKit/blob/292ccaccdb8680509fff0c40aa993572b8d85fc4/Examples/iOS/SongProcessor/SongProcessor/SongProcessor.swift#L119) is how I do it in the SongProcessor Example.  GitHub's not previewing all of the relevant code so follow the link.

https://github.com/AudioKit/AudioKit/blob/292ccaccdb8680509fff0c40aa993572b8d85fc4/Examples/iOS/SongProcessor/SongProcessor/SongProcessor.swift#L119

**Comment by dave234** [comment]
The AVAudioTime that play(at:) accepts is a time in the future that the players will play.

**Comment by johndpope** [comment]
nice nice. Thanks Dave. Need to get a PR in for your code.
